### ISSUE TITLE
[Feature]: Log if a call is a retry/fallback in the litellm completion call 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1002]
### The Feature

"We want to log this telemetry into langfuse and other places so we can investigate when things are having trouble / patterns we see"

### Motivation, pitch

user request

user is using the router for load balancing across multiple deployments

**Comment by ghost** [comment]
initial commit - https://github.com/BerriAI/litellm/commit/7b83238cb5e6e1a40c94f8f55a7ea4c6b7fc014e
