### ISSUE TITLE
[Bug]: Sagemaker max tokens mapping error. 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1004]
### What happened?

support max new tokens for sagemaker

### Relevant log output

```shell
APIConnectionError: sagemaker does not support parameters: {'stream': True, 'max_tokens': 1000}. To drop these, set `litellm.drop_params=True`.
```

**Comment by ishaan-jaff** [comment]
fixed - the doc with the error https://docs.litellm.ai/docs/completion/input#translated-openai-params

**Comment by ishaan-jaff** [comment]
it clarifies max_tokens is only translated for jumpstart llama 2
