### ISSUE TITLE
[Docs]: Add async custom callbacks to docs

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1006]
### The Feature

This commit - https://github.com/BerriAI/litellm/commit/e0ccb281d8941ee0992bc26c4a5ad48616125eaf, added async custom callbacks (currently only on success for async calls). 

We should add it to our docs.

This was added to resolve issues asyncio event loops caused during logging on the proxy - 
https://github.com/BerriAI/litellm/issues/989

### Motivation, pitch

Enable calling async events during logging

**Comment by ghost** [comment]
added - https://github.com/BerriAI/litellm/commit/7adb8f493d0a9b3af16912075c2e45692e4209ea
