### ISSUE TITLE
[Feature]: Expand async callback support to other event types

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1007]
### The Feature

We've implemented async custom callbacks on just success events for async completion/embedding calls. https://github.com/BerriAI/litellm/commit/e0ccb281d8941ee0992bc26c4a5ad48616125eaf

Expand this to also support the other event types (pre-input, post-input, on-failure) and sync completion/embedding calls. 

### Motivation, pitch

consistent ux

**Comment by ghost** [comment]
+1 user requested

**Comment by ghost** [comment]
test case: use it to log events from proxy to fluent-bit

**Comment by ghost** [comment]
closing as this is now supported for failure + customhandler class.
