### ISSUE TITLE
[Docs]: Add custom auth docs 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1008]
### The Feature

This commit introduced user-defined auth - https://github.com/BerriAI/litellm/commit/030bd220785765638b57d929a8e05b4be5303e45

We should add this to our docs so people know how to use it. 

### Motivation, pitch

multiple users requested this.

**Comment by ghost** [comment]
We've already outlined steps in this issue - https://github.com/BerriAI/litellm/issues/898

Just add those to the docs.

**Comment by ghost** [comment]
Added - https://github.com/BerriAI/litellm/commit/37251d327d4b0fe564fd8d7223d5d96cde7752b1
