### ISSUE TITLE
[Bug]: config.yaml problem

### ISSUE THREAD

**Issue by iplayfast** [BerriAI/litellm#1009]
### What happened?

With the following config.yaml
`model_list:  
  - model_name:  DeepSeek-Coder
    litellm_params:  
      model:  ollama/DeepSeek-Coder
      api_base:  http://0.0.0.0:9000
    headers:  {
        "HTTP-Referer":  "litellm.ai",
        "X-Title":  "LiteLLM Server"
    }

litellm_settings: 
  drop_params:  True
  set_verbose:  False

`

It opens a port at 8000 which isn't working as I've not set an API_KEY. The text displayed says that it loaded the right one, but I guess ignored it. Trying to access port 9000 just fails.

### Relevant log output

```shell
itellm --config ./config.yaml 
INFO:     Started server process [1531907]
INFO:     Waiting for application startup.

#------------------------------------------------------------#
#                                                            #
#              'I don't like how this works...'               #
#        https://github.com/BerriAI/litellm/issues/new        #
#                                                            #
#------------------------------------------------------------#

 Thank you for using LiteLLM! - Krrish & Ishaan



Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new


Loaded config YAML:
{
  "model_list": [
    {
      "model_name": "DeepSeek-Coder",
      "litellm_params": {
        "model": "ollama/DeepSeek-Coder",
        "api_base": "http://0.0.0.0:9000"
      },
      "headers": {
        "HTTP-Referer": "litellm.ai",
        "X-Title": "LiteLLM Server"
      }
    }
  ],
  "litellm_settings": {
    "drop_params": true,
    "set_verbose": false
  }
}
LiteLLM: Proxy initialized with Config, Set models:
    DeepSeek-Coder

LiteLLM: Test your local proxy with: "litellm --test" This runs an openai.ChatCompletion request to your proxy [In a new terminal tab]

LiteLLM: Curl Command Test for your local proxy
 
    curl --location 'http://0.0.0.0:8000/chat/completions' \
    --header 'Content-Type: application/json' \
    --data ' {
    "model": "gpt-3.5-turbo",
    "messages": [
        {
        "role": "user",
        "content": "what llm are you"
        }
    ]
    }'
    

     

Docs: https://docs.litellm.ai/docs/simple_proxy

INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
```

**Comment by ishaan-jaff** [comment]
If you want to set a port for the litellm proxy you must start it like this: 
`litellm --port 8080` https://docs.litellm.ai/docs/proxy/cli#--port 

it looks like you set `ollama` api_base to `http://0.0.0.0:9000` and you're starting the proxy which defaults to to `8000`

- what port do you want the proxy running on ? 
- what port do you want ollama on ?

**Comment by iplayfast** [comment]
I have several ollama models to run and need them to run on specific ports. 
Ideally I'd like to replicate:
`
litellm -m ollama/alfred --port 9000 --drop_params&

litellm -m ollama/DeepSeek-Coder --port 9001 --drop_params&

litellm -m ollama/starling-lm --port 9002 --drop_params&

litellm -m ollama/orca2:13b --port 9003 --drop_params&

`
in a config.yaml file.

**Comment by ghost** [comment]
Hi @iplayfast is this still an open issue after our conversation on Discord?

**Comment by ghost** [comment]
@iplayfast it's unclear how the proxy isn't working without the api key. Just ran it locally and it worked fine. 

Closing for now, please re-open if the issue persists, with steps for repro. 
<img width="712" alt="Screenshot 2023-12-05 at 10 06 07 AM" src="https://github.com/BerriAI/litellm/assets/17561003/142874fb-1114-4635-adb8-dbe70bd9d2a5">

<img width="1554" alt="Screenshot 2023-12-05 at 10 06 55 AM" src="https://github.com/BerriAI/litellm/assets/17561003/26988736-b2a8-4b26-911e-818240237424">
