### ISSUE TITLE
Slack alerting not firing

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#101]
<img width="1206" alt="Screenshot 2023-08-11 at 8 57 08 PM" src="https://github.com/BerriAI/litellm/assets/17561003/94c7b9aa-d452-4105-a616-e263f9e737eb">
<img width="810" alt="Screenshot 2023-08-11 at 8 57 34 PM" src="https://github.com/BerriAI/litellm/assets/17561003/3aafa3ef-6fc4-4e80-9991-bcad3d16e203">

i don't see any alerts despite this failing

**Comment by ghost** [comment]
turns out my key was invalid, nvm
