### ISSUE TITLE
[Bug]: TextChoices: if text='', text will be None

### ISSUE THREAD

**Issue by langgg0511** [BerriAI/litellm#1010]
### What happened?

class TextChoices(OpenAIObject):
    def __init__(self, finish_reason=None, index=0, text=None, logprobs=None, **params):
        super(TextChoices, self).__init__(**params)
        if finish_reason:
            self.finish_reason = map_finish_reason(finish_reason)
        else:
            self.finish_reason = "stop"
        self.index = index
        **if text:
            self.text = text
        else:
            self.text = None**
        if logprobs:
            self.logprobs = []
        else:
            self.logprobs = logprobs

**Comment by ghost** [comment]
Acknowledging this

**Comment by ghost** [comment]
fix pushed - https://github.com/BerriAI/litellm/commit/ef7795add6680591a60b5cb71c7134c3571a4657
