### ISSUE TITLE
[Bug]: stream async client bug on proxy

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1012]
### What happened?

when a non openai / azure model is passed in, an async client initialization error happens. 

### Relevant log output

```shell
llm-proxy:dev: An error occurred: 'stream_async_client'
```

**Comment by ghost** [comment]
@ishaan-jaff i know you're working on this right now - just update ticket once this is resolved.

**Comment by ishaan-jaff** [comment]
it's fixed - waiting on deploying a new version of litellm

**Comment by ishaan-jaff** [comment]
fixed + added testing on router for this
