### ISSUE TITLE
[Bug]: Langsmith not working with streaming results

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1015]
### What happened?

I'v been trying to use litellm to log chats to langsmith. It seems to be an issue with the lack of serializability of the CustomStreamWrapper object. It fails silently. When I switch litellm.set_verbose=True I get the following: 

TypeError: Object of type CustomStreamWrapper is not JSON serializable

And when I dig into the logs I see this: 

'log_event_type': 'successful_api_call', 'original_response': <litellm.utils.CustomStreamWrapper object at 0x10a4e3a90>, 'end_time': datetime.datetime(2023, 12, 4, 16, 9, 34, 499526)}

### Relevant log output

```shell
'log_event_type': 'successful_api_call', 'original_response': <litellm.utils.CustomStreamWrapper object at 0x10a4e3a90>, 'end_time': datetime.datetime(2023, 12, 4, 16, 9, 34, 499526)}
```

**Comment by ghost** [comment]
Looks to be caused by serializing customstreamwrapper which is a generator object. i believe we'll see similar issues with coroutines as well (for async responses). 

The fix looks like checking if the object in original_response is json serializable, in `success_handler`

**Comment by ghost** [comment]
fixed - https://github.com/BerriAI/litellm/commit/43f409601422748865a9707ce0adac61dfc07f74
