### ISSUE TITLE
[Feature]: Support *llama* sagemaker jumpstart models 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1017]
### The Feature

check for consistent formatting for sagemaker jumpstart → primarily for llama models 

### Motivation, pitch

user using our proxy for sagemaker jumpstart

**Comment by ghost** [comment]
should enable using max tokens, temperature, and streaming with sagemaker endpoint.

**Comment by ghost** [comment]
Tracking llama models on jumpstart and their supported params: 

Jumpstart has 2 versions for llama2 -> chat and completions (consistent params for variants within those) 

**Chat**

Params: 
max_new_tokens
temperature
top_p

Models: 

*Llama-2-7b-chat*
*Llama-2-13b-chat*
*Llama-2-70b-chat*
*Llama-2-7b-chat Neuron*
*Llama-2-13b-chat Neuron*

Code: https://github.com/aws/amazon-sagemaker-examples/blob/main/introduction_to_amazon_algorithms/jumpstart-foundation-models/llama-2-chat-completion.ipynb

**Completions**

Params: 
max_new_tokens (int, must be > 0) 
temperature (float, must be > 0)
top_p (float b/w 0 and 1)
return_full_text (default False) 

Models:
*Llama-2-7b*
*Llama-2-13b*
*Llama-2-70b* 
*Llama-2-7b Neuron*
*Llama-2-13b Neuron*


Code: https://github.com/aws/amazon-sagemaker-examples/blob/main/introduction_to_amazon_algorithms/jumpstart-foundation-models/llama-2-text-completion.ipynb

**Comment by ghost** [comment]
Test for completion, async completion, streaming, async streaming, and exception mapping

**Comment by ghost** [comment]
Completion models have this kind of id: 

You can continue with the default model or choose a different model: this notebook will run with the following model IDs :

meta-textgeneration-llama-2-7b-f
meta-textgeneration-llama-2-13b-f
meta-textgeneration-llama-2-70b-f

**Comment by ghost** [comment]
All Supported Params for completion: 
```python
max_length: Model generates text until the output length (which includes the input context length) reaches max_length. If specified, it must be a positive integer.
max_new_tokens: Model generates text until the output length (excluding the input context length) reaches max_new_tokens. If specified, it must be a positive integer.
num_beams: Number of beams used in the greedy search. If specified, it must be integer greater than or equal to num_return_sequences.
no_repeat_ngram_size: Model ensures that a sequence of words of no_repeat_ngram_size is not repeated in the output sequence. If specified, it must be a positive integer greater than 1.
temperature: Controls the randomness in the output. Higher temperature results in output sequence with low-probability words and lower temperature results in output sequence with high-probability words. If temperature -> 0, it results in greedy decoding. If specified, it must be a positive float.
early_stopping: If True, text generation is finished when all beam hypotheses reach the end of sentence token. If specified, it must be boolean.
do_sample: If True, sample the next word as per the likelihood. If specified, it must be boolean.
top_k: In each step of text generation, sample from only the top_k most likely words. If specified, it must be a positive integer.
top_p: In each step of text generation, sample from the smallest possible set of words with cumulative probability top_p. If specified, it must be a float between 0 and 1.
return_full_text: If True, input text will be part of the output generated text. If specified, it must be boolean. The default value for it is False.
stop: If specified, it must be a list of strings. Text generation stops if any one of the specified strings is generated.
```

Looks like model ids are unique to a user
<img width="781" alt="Screenshot 2023-12-05 at 1 26 36 PM" src="https://github.com/BerriAI/litellm/assets/17561003/fba7d1fb-d3d1-4948-bd3c-767cc778c63c">


Prompt templating required before calling the model: 
<img width="1343" alt="Screenshot 2023-12-05 at 1 27 59 PM" src="https://github.com/BerriAI/litellm/assets/17561003/566dc028-a65d-4ac2-8f8b-b8796a916414">

**Comment by ghost** [comment]
Llama2 (completion) neuron models: 
You can continue with the default model or choose a different model: this notebook will run with the following model IDs :

meta-textgenerationneuron-llama-2-7b
meta-textgenerationneuron-llama-2-7b-f
meta-textgenerationneuron-llama-2-13b
meta-textgenerationneuron-llama-2-13b-f

example config 
<img width="629" alt="Screenshot 2023-12-05 at 1 25 00 PM" src="https://github.com/BerriAI/litellm/assets/17561003/b2d48c6d-f0fa-4a2c-b4c8-dbb7df2a3d41">


All supported params: 
This model supports many parameters while performing inference. They include:
```python
max_length: Model generates text until the output length (which includes the input context length) reaches max_length. If specified, it must be a positive integer.
max_new_tokens: Model generates text until the output length (excluding the input context length) reaches max_new_tokens. If specified, it must be a positive integer.
num_beams: Number of beams used in the greedy search. If specified, it must be integer greater than or equal to num_return_sequences.
no_repeat_ngram_size: Model ensures that a sequence of words of no_repeat_ngram_size is not repeated in the output sequence. If specified, it must be a positive integer greater than 1.
temperature: Controls the randomness in the output. Higher temperature results in output sequence with low-probability words and lower temperature results in output sequence with high-probability words. If temperature -> 0, it results in greedy decoding. If specified, it must be a positive float.
early_stopping: If True, text generation is finished when all beam hypotheses reach the end of sentence token. If specified, it must be boolean.
do_sample: If True, sample the next word as per the likelihood. If specified, it must be boolean.
top_k: In each step of text generation, sample from only the top_k most likely words. If specified, it must be a positive integer.
top_p: In each step of text generation, sample from the smallest possible set of words with cumulative probability top_p. If specified, it must be a float between 0 and 1.
stop: If specified, it must be a list of strings. Text generation stops if any one of the specified strings is generated.
```

**Comment by ghost** [comment]
For chat models 

Supported Params: 

```python
max_length: Model generates text until the output length (which includes the input context length) reaches max_length. If specified, it must be a positive integer.
max_new_tokens: Model generates text until the output length (excluding the input context length) reaches max_new_tokens. If specified, it must be a positive integer.
num_beams: Number of beams used in the greedy search. If specified, it must be integer greater than or equal to num_return_sequences.
no_repeat_ngram_size: Model ensures that a sequence of words of no_repeat_ngram_size is not repeated in the output sequence. If specified, it must be a positive integer greater than 1.
temperature: Controls the randomness in the output. Higher temperature results in output sequence with low-probability words and lower temperature results in output sequence with high-probability words. If temperature -> 0, it results in greedy decoding. If specified, it must be a positive float.
early_stopping: If True, text generation is finished when all beam hypotheses reach the end of sentence token. If specified, it must be boolean.
do_sample: If True, sample the next word as per the likelihood. If specified, it must be boolean.
top_k: In each step of text generation, sample from only the top_k most likely words. If specified, it must be a positive integer.
top_p: In each step of text generation, sample from the smallest possible set of words with cumulative probability top_p. If specified, it must be a float between 0 and 1.
return_full_text: If True, input text will be part of the output generated text. If specified, it must be boolean. The default value for it is False.
stop: If specified, it must be a list of strings. Text generation stops if any one of the specified strings is generated.
```

**NOTE**: If `max_new_tokens` is not defined, the model may generate up to the maximum total tokens allowed, which is 4K for these models. This may result in endpoint query timeout errors, so it is recommended to set `max_new_tokens` when possible. For 7B, 13B, and 70B models, we recommend to set `max_new_tokens` no greater than 1500, 1000, and 500 respectively, while keeping the total number of tokens less than 4K.

**Comment by ghost** [comment]
pushed - https://github.com/BerriAI/litellm/commit/b4c78c7b9eb7657f2a793ccd681c527963cce9ca

**Comment by ghost** [comment]
closing as this is live in v`1.10.11`
