### ISSUE TITLE
[Docs]: Add tutorial for using proxy with langchain

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1018]
### The Feature

Add a tutorial here - https://docs.litellm.ai/docs/proxy/quick_start#using-with-openai-compatible-projects

showing how to use the proxy with langchain

### Motivation, pitch

user was trying to do this (i believe with langchain.js) and unsure how.

**Comment by ishaan-jaff** [comment]
done: https://docs.litellm.ai/docs/proxy/quick_start#using-litellm-proxy---curl-request-openai-package-langchain-langchain-js
