### ISSUE TITLE
[Feature]: help with debugging

### ISSUE THREAD

**Issue by iplayfast** [BerriAI/litellm#1019]
### The Feature

add --verbose startup
it would show 
1 input from whereever to litellm,
2. output from litellm to whatever
3. output from whatever to litellm
4. output from litellm to wherever

Things seem to die in unexpected ways, and with no way to follow it's very hard to debug.

### Motivation, pitch

Things seem to die in unexpected ways, and with no way to follow it's very hard to debug.

**Comment by ghost** [comment]
@iplayfast this already exists `litellm --debug`

**Comment by ghost** [comment]
How can we improve the existing implementation to be more helpful for you?

**Comment by ghost** [comment]
closing as this functionality already exists - @iplayfast please reopen if you have suggestions for improvement

**Comment by iplayfast** [comment]
I think I was using an older version, which wasn't as nice. --debug looks good.
