### ISSUE TITLE
[Docs]: Add redis url / additional kwargs to docs

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1021]
### The Feature

we just pushed a commit that enabled this use-case https://github.com/BerriAI/litellm/issues/994

Add it to docs

### Motivation, pitch

make it easier for users to deploy litellm

**Comment by ghost** [comment]
done - https://github.com/BerriAI/litellm/commit/68ca2a28d41701218b5111e7e3f05eae3e3dd370
