### ISSUE TITLE
[Feature]:  acomplete see explicit args instead of *args, **kwargs on acomplete,

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1024]
### The Feature

> would love to see explicit args instead of *args, **kwargs on acomplete, like you have in complete

### Motivation, pitch

everyone loves intellisense

**Comment by MateoCamara** [comment]
Hello there! I'd like to try it! It would be my first issue. Cheers :)

**Comment by ishaan-jaff** [comment]
any updated @MateoCamara ?

**Comment by MateoCamara** [comment]
just added a PR @ishaan-jaff
