### ISSUE TITLE
[Bug]: Together ai calls not ending

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1025]
### What happened?

![image](https://github.com/BerriAI/litellm/assets/17561003/af987217-b685-4a9f-b65d-8448fea098cd)

### Relevant log output

```shell
https://gist.github.com/duc-phamh/20db03a7f21928daa1ea656ecaa12bcf
```

### Twitter / LinkedIn details

[Duc Pham](https://www.linkedin.com/in/ducpham1160/)

**Comment by ghost** [comment]
fixed - https://github.com/BerriAI/litellm/commit/fff0228c201c788f99a49277ad80874f70a2145d

**Comment by ghost** [comment]
Made more updates - together ai has an internal api to pull their model configs from `/models/info`

So we now pull the model config (incl. prompt/chat template) from there, for togetherai calls.
