### ISSUE TITLE
[Feature]: Enable custom routing strategies

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1027]
### The Feature

Enable users to define their own routing strategy when a completion call fails / doesn't do what's expected

### Motivation, pitch

User chose not to use router b/c: 

Regarding your question of what is missing there, in your example the routing is deterred from one model to another based on exceptions, we needed a more flexible strategy, I'll give an example.
Let's say you use function calling, but the response is not json serializable. Then there is no exception thrown here, that's the first difference. Secondly, in the "mitigation" part you just go to the next model, we wanted to have the ability to continue the chat if it failed like appending to the messages asking the model to fix this to be json serializable.

So in essence, this examples shows 2 differences (1) first one is that routing the call from one model or the other can be dependent on more than exceptions thrown by response, and second (2) is the ability to mitigate the error by doing something else than going to the next model in the list

**Comment by ghost** [comment]
cc: @eliorc

**Comment by ishaan-jaff** [comment]
done here https://docs.litellm.ai/docs/routing#advanced---routing-strategies-%EF%B8%8F
