### ISSUE TITLE
[Feature]: Context management for caching

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1028]
### The Feature

A user of the cache could do something like with cache.disable_cache()... or with cache.cache_context(ttl=1000) to change the behavior of the cache.

### Motivation, pitch

user request

**Comment by ghost** [comment]
cc: @eliorc

**Comment by eliorc** [comment]
For the meantime, how would I disable caching? I have this weird behavior

If I remove `"cache"` from `litellm.input_callback` and `litellm.input_callback`, but leave `litellm.cache = Cache(...)` it does not use the current cache, but it overrides in the cache the previously cached content and saves it as a new cached entry.
Is that expected? I expected if I remove `"cache"` from the callbacks, that no cache will be used at all

**Comment by ghost** [comment]
i suspect this might be due to us checking if litellm.cache is set, without checking if it's part of the callback list. 

Can you share a sample test script for this? @eliorc

**Comment by eliorc** [comment]
Ye, so basically what I've implemented are context managers for the cache. 

 - `cache.no_cache()` - Avoid using or writing result to cache
 - `cache.cache_context(**kwargs)` - Allows overwriting the TTL and other settings 
 - `cache.cache_context(overwrite_cache=True)` - Allows avoiding reading from the cache, but writes results to the cache

So for that I have two methods

```python3
def enable_cache(attach_cache: bool = True):
    """
    Enable caching.

    :param attach_cache: If True, attach the cache to litellm.cache
    :return: None
    """

    if not is_cache_enabled():
        if "cache" not in litellm.input_callback:
            litellm.input_callback.append("cache")
        if "cache" not in litellm.success_callback:
            litellm.success_callback.append("cache")

    if attach_cache:
        from my.private.module import cache_init
        litellm.cache = cache_init()


def disable_cache(detach_cache: bool = True):
    """
    Disable caching.

    :param detach_cache: If True, detach the cache from litellm.cache
    :return: None
    """

    with suppress(ValueError):
        litellm.input_callback.remove("cache")
        litellm.success_callback.remove("cache")

    if detach_cache:
        litellm.cache = None
```

Now, for `cache.no_cache` I use `disable_cache(detach=True)` for overwriting, I use `disable_cache(detach=False)`

**Comment by ishaan-jaff** [comment]
this is neat @eliorc thanks for sharing your code snippet

Added here: https://github.com/BerriAI/litellm/commit/ddddfe6602346b7b87308275e55695069415bdac 


+ testing in the next commit

**Comment by ishaan-jaff** [comment]
docs for doing this is here - https://docs.litellm.ai/docs/caching/redis_cache#cache-context-manager---enable-disable-update-cache

@eliorc does this solve your problem well ? Any suggestions on improving it

**Comment by ishaan-jaff** [comment]
closing this issue - feel free to re-open
