### ISSUE TITLE
[Feature]: Support sagemaker jumpstart embedding models 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1029]
### The Feature

enable `embeddings()` to work for sagemaker jumpstart models 

### Motivation, pitch

user request

**Comment by ghost** [comment]
make it work for gptj 6b jumpstart embedding,

**Comment by ghost** [comment]
pushed - https://github.com/BerriAI/litellm/commit/94f065f83c20f5ca2f9fb41c16f62a23d75c024d
