### ISSUE TITLE
[Feature]: Proxy - Add Pre / Post API call hooks 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1037]
### The Feature

Allows users to modify the incoming request / output to the proxy 

### Motivation, pitch

-

**Comment by ghost** [comment]
initial commit made which instruments this for /chat/completions + /embeddings

**Comment by ghost** [comment]
this is pushed - https://github.com/BerriAI/litellm/commit/effdddc1c8a4dd69fe0f1369043fad649661ae2d
