### ISSUE TITLE
Rename 'force_timeout' to 'timeout' 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#104]
<img width="1079" alt="Screenshot 2023-08-12 at 10 20 08 AM" src="https://github.com/BerriAI/litellm/assets/17561003/7461fdd4-62cc-4f14-a362-87bb2ccf3793">

**Comment by ishaan-jaff** [comment]
can we not just use `request_timeout` like OpenAI used to ?

**Comment by ghost** [comment]
lgtm

**Comment by ishaan-jaff** [comment]
done
