### ISSUE TITLE
[Feature]: Enable alias for router model groups 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1041]
### The Feature

Enable aliases for model_name (i.e. model groups) on router

### Motivation, pitch

user request

**Comment by ishaan-jaff** [comment]
added https://github.com/BerriAI/litellm/commit/900b8d66f3fdc9e4a68407715d6d9ed5af304b58

**Comment by ishaan-jaff** [comment]
will wait for it to reach prod + add docs/ testing
