### ISSUE TITLE
[Bug/Feature]: REDIS_SSL support

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#1046]
### What happened?

Right now, redis can only be used without SSL/TLS. Could we add something like `REDIS_SSL` as an env var to allow using SSL/TLS?

**Comment by eliorc** [comment]
This is already solved, please see #994

**Comment by Manouchehri** [comment]
So `REDIS_ssl=True` should work?

**Comment by ghost** [comment]
@Manouchehri i believe so check out `_redis.py` to see the implementation

**Comment by Manouchehri** [comment]
Hmm, that's what I tried and it didn't seem to work. I'll try again, one minute. (Shower thought, will it be attempting to use `"True"` instead of `True`?)

**Comment by Manouchehri** [comment]
`REDIS_ssl=True` doesn't seem to do anything for me.

**Comment by eliorc** [comment]
> `REDIS_ssl=True` doesn't seem to do anything for me.

Why do you think its `REDIS_ssl`? The documentation states differently https://redis-py.readthedocs.io/en/stable/examples/ssl_connection_examples.html

**Comment by Manouchehri** [comment]
I have zero clue what environment variable I'm supposed to set then.. hence why I asked.

https://github.com/BerriAI/litellm/commit/68ca2a28d41701218b5111e7e3f05eae3e3dd370#diff-28af68fdfe30eec60bd05c134d2978cf45789ff835cb3766ffc3c9ce2e8cf30dR32

That shows `REDIS_` is needed.

And the link you sent, shows 

```
ssl_cert_conn = redis.Redis(
    host="localhost",
    port=6666,
    ssl=True,
    ssl_certfile=ssl_certfile,
    ssl_keyfile=ssl_keyfile,
    ssl_cert_reqs="required",
    ssl_ocsp_context=ctx,
    ssl_ocsp_expected_cert=expected_certificate,
)
```

...which has `ssl=True`. So I guessed that `REDIS_ssl=True` was the solution. It's wrong, I'm aware of that.

**Comment by ghost** [comment]
@Manouchehri Can you try `REDIS_SSL` and let me know if that works?

**Comment by Manouchehri** [comment]
Hmm, `REDIS_SSL=True` doesn't seem to change anything for me. Is it working for other users?

**Comment by ghost** [comment]
i'm looking into this now @Manouchehri

**Comment by Manouchehri** [comment]
Neon does have a free tier if you don't want to spin up another redis instance with SSL. =) https://neon.tech/pricing

**Comment by ghost** [comment]
Hi @Manouchehri just pushed a fix for Redis caching. 

Looks like the default router value was incorrectly set, causing the call to skip the cache check. 

Here's my env: 
```env
REDIS_HOST = "redis-host"
REDIS_PORT = "redis-port"
REDIS_PASSWORD = "redis-password"
REDIS_SSL = "True"
```

Here's the test I ran to check this:  https://github.com/BerriAI/litellm/blob/2b04dc310abcb5dabff875791134b6bb9a2ba069/litellm/tests/test_proxy_server_caching.py

**Comment by ghost** [comment]
will update this thread when the fix is in prod

**Comment by ghost** [comment]
@Manouchehri this should be live in v`1.12.0`. Let me know if the fix solves your problem.

**Comment by Manouchehri** [comment]
I think it's working now, thanks! Will reopen if I'm wrong. =)

**Comment by ghost** [comment]
sounds good -  i've added testing for this as well https://github.com/BerriAI/litellm/blob/main/litellm/tests/test_caching_ssl.py
