### ISSUE TITLE
[Bug] Fix hugging face implementation - [Exceptions not raised]

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#105]
Since we're doing response.json the hugging face error does not get raised

**Comment by ghost** [comment]
i think this is similar for anthropic as well - i'm working on moving to the REST implementation. However it returns the exception as a dictionary {"error": "error_msg"} 

So I can do some of the mapping work for that before I push it to prod

**Comment by ghost** [comment]
@ishaan-jaff maybe run through `test_exceptions.py` for hf and see what exceptions their endpoint raises

**Comment by ghost** [comment]
Seems like for HF you can do - at least rate limit errors - based on response status

<img width="995" alt="Screenshot 2023-08-12 at 5 20 14 PM" src="https://github.com/BerriAI/litellm/assets/17561003/387813d2-18a3-4caa-8d1e-315cc98f0510">

**Comment by ishaan-jaff** [comment]
This is the error 

<img width="1239" alt="Screenshot 2023-08-14 at 11 35 11 AM" src="https://github.com/BerriAI/litellm/assets/29436595/0bb358e8-e534-4c0f-ac37-0deb93794688">

**Comment by ghost** [comment]
https://huggingface.github.io/text-generation-inference/#/Text%20Generation%20Inference/compat_generate

**Comment by ishaan-jaff** [comment]
Fix is live for the issue I was facing,  it raises the HF error now 

<img width="1252" alt="Screenshot 2023-08-14 at 11 57 10 AM" src="https://github.com/BerriAI/litellm/assets/29436595/5e6bd985-2508-4397-b7dd-02da595460ea">

<img width="1223" alt="Screenshot 2023-08-14 at 11 56 54 AM" src="https://github.com/BerriAI/litellm/assets/29436595/5bc08e43-b8d2-4838-9da6-94e6c71c5413">
