### ISSUE TITLE
[Feature]: Add Google Gemini - Day 1 - Dec 13 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1051]
### The Feature

> Starting on December 13, developers and enterprise customers can access Gemini Pro via the Gemini API in Google AI Studio or Google Cloud Vertex AI.

### Motivation, pitch

-

**Comment by janaka** [comment]
@ishaan-jaff @krrishdholakia you all haven't seem any early info being released on the Gemini API have you? I presume the web API is going to be the current Vertex API. But the LLM level will be new. Is that what you all are expecting? 

I've not played with Vertex AI at all. Just looking to get an endpoint deployed in our account now to get more familiar.

Hopefully, pricing isn't going to be extortionate :)

**Comment by phact** [comment]
gemini-pro api dropped 15 minutes ago. It didn't immediately work [with litellm] on my first try. Having a look, will add details as I go.

**Comment by ghost** [comment]
<img width="755" alt="Screenshot 2023-12-13 at 7 23 40 AM" src="https://github.com/BerriAI/litellm/assets/17561003/cb77c967-3b33-495b-8d18-e7c6f719656d">

**Comment by ghost** [comment]
looks like it uses a new module in vertex ai.

**Comment by ghost** [comment]
Working on adding support for this now

**Comment by phact** [comment]
does litellm really rely on a call to `https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json` to get the list of models?

https://github.com/BerriAI/litellm/blob/c9b83ff85321ca39dd2b13da3bf7a0244100dd08/litellm/__init__.py#L57

**Comment by ghost** [comment]
yes - that lets us decouple adding new models from version bumps

**Comment by phact** [comment]
I see, but it means you can't easily test without deploying to master?

**Comment by phact** [comment]
anyway, I'm having trouble finding the max_tokens for gemini-pro documented anywhere, may have to resort to empirically using tiktoken and making it barf w/ large payloads...

Would you do a place holder for now?

**Comment by phact** [comment]
> Working on adding support for this now

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/generative_ai/chat.py

vs 

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/generative_ai/gemini_chat_example.py

right?

**Comment by phact** [comment]
so in this case we will need a new release / version bump

**Comment by ghost** [comment]
yea @phact

**Comment by janaka** [comment]
I can do a quick test if you have a branch ( though looks like you guys mostly just push on main 😀 )

**Comment by ghost** [comment]
Adding list of things we need to make sure support is added for: 

- [x] streaming 
- [x] completion 
- [x] async completion 
- [x] async streaming 
- [x] exception mapping

**Comment by ghost** [comment]
@janaka expect something out by 12pm PST

**Comment by phact** [comment]
Here we go max tokens is 8192
![image](https://github.com/BerriAI/litellm/assets/1313220/8525e82a-afa4-4099-a797-1bed117d2363)

**Comment by ghost** [comment]
Here's what i'm looking at @phact 
<img width="926" alt="Screenshot 2023-12-13 at 9 59 36 AM" src="https://github.com/BerriAI/litellm/assets/17561003/f3f23ced-fe56-4957-89a8-a0c70faf438f">
https://ai.google.dev/models/gemini

I'll also run the vertex ai model against our context window limit testing to see what actually works

**Comment by ghost** [comment]
Looks like it doesn't natively support streaming. Will have to fake it like sagemaker/ai21/etc. 
<img width="1019" alt="Screenshot 2023-12-13 at 10 02 29 AM"
 src="https://github.com/BerriAI/litellm/assets/17561003/5b5ae963-c536-4535-8872-8c2fc2aef54f">

Odd, since i can see it's a private var
<img width="1653" alt="Screenshot 2023-12-13 at 10 03 35 AM" src="https://github.com/BerriAI/litellm/assets/17561003/0e0fdb3a-ccb9-4196-94ef-7754fb0de2bb">

**Comment by ghost** [comment]
Update on streaming, looks like they support `chat.send_message(.., stream=True)` for gemini cc: @ishaan-jaff 
<img width="1627" alt="Screenshot 2023-12-13 at 10 06 23 AM" src="https://github.com/BerriAI/litellm/assets/17561003/a4c477ac-4fa7-4942-901b-fa63455fe623">

**Comment by ghost** [comment]
@janaka @phact initial dev release is now out - https://pypi.org/project/litellm/1.14.0.dev1/

Here's the relevant commit - https://github.com/BerriAI/litellm/commit/ef7a6e3ae1c6c41cf406fbb38eb483790fd196d1

Dev release is unstable. Full release will be out once commit has passed our ci/cd testing.

**Comment by ghost** [comment]
Please let me know if you see any bugs. I've also added gemini-pro testing to our ci/cd.

**Comment by ghost** [comment]
Code for testing: 

```python
import litellm
litellm.vertex_project = "hardy-device-38811" # Your Project ID
litellm.vertex_location = "us-central1"  # proj location

response = completion(model="gemini-pro", messages=[{"role": "user", "content": "write code for saying hi from LiteLLM"}])
```

**Comment by janaka** [comment]
>raised APIError: VertexAIException - ChatSession.send_message() got an unexpected keyword argument 'temperature'.

getting this. running against source code. fairly sure it's referencing the latest commit.

**Comment by ghost** [comment]
noted, missed this in testing. Able to repro. thanks @janaka

**Comment by janaka** [comment]
Nice. FYI - I'm using via Llama Index. So might be other things. Not quite sure how to set location. I don't think additional_kwargs in llama-index LiteLLM() constructor get's passed through for that?

I have to get shut eye now. Will try again in the morning :)

**Comment by phact** [comment]
it works for me!

interestingly my first try gave this which seems to be a content moderation error. 
>vertexai.generative_models._generative_models.ResponseBlockedError: The response was blocked.


I asked it to draw an ascii art kitten eating ice cream (no idea how that is unsafe). But a simpler prompt works great!

**Comment by ghost** [comment]
@janaka if you have gcp credentials setup in your environment, i believe that should work - let me know if you hit any issues. 

@phact  lol

**Comment by ghost** [comment]
This is now out in v`1.14.0` - pip install litellm==1.14.0 https://pypi.org/project/litellm/

**Comment by janaka** [comment]
"draw me a picture of a house" or "what's the sun?"

>Error: VertexAIException - The response was blocked.

"what's a parrot?" works

Looks the the Responsible AI and Safety component is working overtime for Gemini

haha

**Comment by haseeb-heaven** [comment]
> This is now out in v`1.14.0` - pip install litellm==1.14.0 https://pypi.org/project/litellm/

I am going to test this out.
