### ISSUE TITLE
[Feature]: async boto3 calls for bedrock + sagemaker

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1055]
### The Feature

make boto3 create invocation endpoint calls async for litellm.acompletion 

today sync boto3 calls are wrapped in an async process

### Motivation, pitch

make sure proxy embeddings can handle high-traffic queries

**Comment by ishaan-jaff** [comment]
looked into this for bedrock, so far have not found boto3 to have any async support for bedrock

**Comment by ishaan-jaff** [comment]
our current implementation takes 26s for 50 requests on the proxy to bedrock/cohere command

**Comment by ghost** [comment]
Sagemaker llama2 70b is pretty quick as well - 
<img width="809" alt="Screenshot 2023-12-28 at 5 11 31 PM" src="https://github.com/BerriAI/litellm/assets/17561003/89363e47-6ef0-4e61-9a3a-8cd52f216aa7">

**Comment by ghost** [comment]
Azure openai (real async) was much quicker though. 
<img width="654" alt="Screenshot 2023-12-28 at 5 12 50 PM" src="https://github.com/BerriAI/litellm/assets/17561003/93ada1cc-43d7-45c6-9434-493080ff900b">

**Comment by ghost** [comment]
I think this is a no-op for sagemaker. boto3's sagemaker async call isn't an aiohttp implementation. It's a queuing/s3 bucket architecture thing, 

so basically you'd have to write the user request to an s3 bucket, and then poll if it's been written to an s3 bucket location.

**Comment by ghost** [comment]
to do what we want (aiohttp calls) we'd probably need to write our own http calling logic (not boto3). This seems like a large lift, without users asking for it already. Closing as unplanned for now, let's revisit this if a user has complaints.
