### ISSUE TITLE
[Feature]: add prisma retry parameter (failing db writes for neon db) 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1056]
### The Feature

Prisma DB calls will occassionally fail. Add retry logic + reliability testing for this. 

![image](https://github.com/BerriAI/litellm/assets/17561003/490bc9bd-7057-4475-a0d2-bed8c3ca5c3b)

### Motivation, pitch

user request

**Comment by ghost** [comment]
cc: @Manouchehri

**Comment by ghost** [comment]
User needs confidence that spend tracking will work for them reliably in prod. They are connecting to the proxy to neon db. 

A good idea here would be to load test the spend tracking with Neon db on 1000 requests, to check if it works.

**Comment by ghost** [comment]
Ran a 2k call load test, and all calls seemed to work fine. 

Pushed sentry logging for being able to catch future exceptions - f06c3e0f08cddd8079955f355612e2517c076055

Added backoff + retries for db read/write calls - 9f0b83248a743f2a3c5bc0b836979837c0634e7e, bab958561effb3a888ff8c47c03604dc2d9a27b5

**Comment by ghost** [comment]
closing as this is now in prod.
