### ISSUE TITLE
[Feature]: set config via ui 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1057]
### The Feature

Enable setting config via ui (maybe just the default swagger ui) 

### Motivation, pitch

Hard to use the litellm docker image w/ a config.yaml on deployment platforms (not obvious how to give them a file), it's usually just a docker image link.

**Comment by kno2gether** [comment]
Checkout this simple UI. I m not a much of UI Person. Used AppSmith and used LiteLLM API to create this simple UI
https://github.com/kno2gether/LitellmProxyUI

Tutorial here - https://www.youtube.com/watch?v=-Wo025I-_I4

**Comment by ishaan-jaff** [comment]
done - you can now add models on litellm admin ui
