### ISSUE TITLE
[Bug]: Fix pytest/proxy testing client init issue 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1059]
### What happened?

We have multiple test files that initialize a proxy server for testing. But the way pytest runs group tests, the individual tests seem to use the last initialized proxy config (the one which requires api keys). 

This makes it hard to test different config.yaml variations.

**Comment by ghost** [comment]
You can repro this by running `pytest test_proxy_*.py -x` 

And seeing how even proxy test files that use configs w/ no auth, still require auth tokens to be passed in. 

e.g. https://github.com/BerriAI/litellm/blob/main/litellm/tests/test_proxy_server.py

**Comment by ishaan-jaff** [comment]
+1 we should resolve this - ran into issues too

**Comment by ishaan-jaff** [comment]
fixed with our fixtures
