### ISSUE TITLE
[Bug]: `/v1/models` does not accept user keys

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#1062]
### What happened?

When using user keys, `/v1/models` should return a filtered list of what that user key is allowed to access.

Without this, some applications (like LibreChat) break as they expect to be able to query the models.

### Relevant log output

```shell
dave@mbp ~ % curl -X 'GET' \
  'https://litellm.example.com/v1/models' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer sk-removed' -s | jq
{
  "detail": "invalid user key"
}
```

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by ghost** [comment]
acknowledging this issue

**Comment by ghost** [comment]
resolved with this commit - https://github.com/BerriAI/litellm/commit/db8d7936182567e5fe469cb1a6abf349902f1437
<img width="1001" alt="Screenshot 2023-12-14 at 9 58 40 AM" src="https://github.com/BerriAI/litellm/assets/17561003/217d42d7-570b-4113-b50e-f9d0d13b504b">
