### ISSUE TITLE
[Feature]: router- better debugging 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1069]
### The Feature

separate model id param from `model`

when users see router / proxy debug logs they see the litellm generated model id  

### Motivation, pitch

- t

**Comment by ghost** [comment]
Since Router auto-generates id in model info, if not set, I think we can just use that @ishaan-jaff

**Comment by ishaan-jaff** [comment]
working on this, using the router auto generated model ids now

**Comment by ishaan-jaff** [comment]
commit with fix : 
https://github.com/BerriAI/litellm/commit/b6a78cd349d4c516a399049bc1f865c3f668ba9b

**Comment by ishaan-jaff** [comment]
passes local testing on router_*.py group

**Comment by ghost** [comment]
kudos on your cute little commit @ishaan-jaff

**Comment by ishaan-jaff** [comment]
thanks for the kudos! love the vision @krrishdholakia
