### ISSUE TITLE
[Feature]: Adopting ruff for Unified Code Formatting and Linting

### ISSUE THREAD

**Issue by Undertone0809** [BerriAI/litellm#1073]
### The Feature

Hi there,

To ensure our project's code quality and consistency, I propose that we consider adopting `ruff` as our primary tool for code formatting and linting. [ruff]() is a cutting-edge tool that amalgamates the capabilities of `black`, `isort`, and `flake8`, facilitating the automation of code style standardization to enhance readability and maintainability.

ref: [enhancing-python-code-quality-a-comprehensive-guide-to-linting-with-ruff](https://dev.to/ken_mwaura1/enhancing-python-code-quality-a-comprehensive-guide-to-linting-with-ruff-3d6g)

I have explored configuring `ruff` and found that we can seamlessly integrate it by adding some basic settings to our `pyproject.toml`. This approach ensures uniform code styling without the need for manual adjustments across multiple tools. For reference, here's a template: [Python Package Template](https://github.com/Undertone0809/python-package-template/blob/main/pyproject.toml).

![image](https://github.com/BerriAI/litellm/assets/72488598/7af7b4b4-f38e-4457-a19c-6859a013fdf9)

Within our development workflow, we can format our code using the following command:

```shell
poetry run ruff format --config pyproject.toml litellm
```

This command will format the code within the `hooks` and `tests` directories, ensuring consistency before commits.

Moreover, I recommend integrating `ruff` into our pre-commit hooks. This automatic check will prevent code style inconsistencies from being merged into our codebase.

Finally, to guarantee consistent code styling throughout our project, I suggest employing GitHub Actions to automate code format checking. This ensures that any commits not adhering to our styling standards are flagged for correction before merging into the main branch.

![image](https://github.com/BerriAI/litellm/assets/72488598/ef51c5a5-4cce-4500-b4ba-28f9e1116f28)

By adopting `ruff`, I believe we can further elevate our code quality and foster a smoother collaborative experience for our team. I look forward to hearing your thoughts and am happy to answer any questions regarding this proposal.

There projects use code format tool as references.
- https://github.com/Undertone0809/promptulate
- https://github.com/langchain-ai/langchain
- https://github.com/microsoft/autogen

Developers can not pass the github actions check if there is no formatting. To ensure consistency in code style.

![image](https://github.com/BerriAI/litellm/assets/72488598/548fc39d-0876-4e7c-bfd2-e80faecf40e2)

### Motivation, pitchzh

To ensure our project's code quality and consistency.

**Comment by Undertone0809** [comment]
@krrishdholakia Hope to receive your feedback 👋

**Comment by ishaan-jaff** [comment]
FYI we use `isort` + flake8 linting throughout the litellm code base now 

@Undertone0809 I'm closing this issue since we've address the concern of adding linting / code formatting 

Feel free to open a new issue for moving to ruff
