### ISSUE TITLE
[Feature]: Day 1 Mistral api support 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1083]
### The Feature

add support for mistral api - https://docs.mistral.ai/api#operation/createChatCompletion

### Motivation, pitch

user request

**Comment by ghost** [comment]
on the waiting list for mistral. if anyone can help us test a devrelease for this, that'd be great! 

https://docs.mistral.ai/api/

**Comment by shuther** [comment]
On top:
- mistral API is supporting a [safe mode](https://docs.mistral.ai/platform/guardrailing); could make sense to have something similar in the proxy/router (it is just a pre-prompt)
- Mistral is working best with [specific prompt approach](https://docs.mistral.ai/models); is it possible (mainly for the routing capability) to get the prompt transformed automatically? I did not find any project that was doing it but I do see it as a requirement (at least to best support Mistral) but it could be the case for other models (different templates for different model to aggregate the system prompt, history, ...)

**Comment by ghost** [comment]
yes

**Comment by aseifert** [comment]
I have access to the API, what can I do to help?

**Comment by dhruv-anand-aintech** [comment]
Same here. Let me know how I can help. Would like to use it via litellm library and proxy server

**Comment by shuther** [comment]
about the pre-prompt, it seems it is done (I saw something under the hugging face documents); is it working in proxy/routing mode also?

**Comment by ishaan-jaff** [comment]
Added here: https://github.com/BerriAI/litellm/commit/7945664e6186fcd3ce1f95771aaf8795ab804669 

I just got access and was able to test it too

**Comment by ishaan-jaff** [comment]
We've added it for 

- [x] completion
- [x] acompletion 
- [x] mistral params - safe mode, random seed
- [x] stream - completion + acompletion 
- [x] docs
- [ ] embedding
- [x] pricing, context window 
- [x] Exception Mapping

**Comment by ishaan-jaff** [comment]
done: 
https://docs.litellm.ai/docs/providers/mistral

**Comment by ishaan-jaff** [comment]
In prod
https://pypi.org/project/litellm/1.14.2/

@shuther @aseifert @dhruv-anand-aintech if possible can you let me know if you run into any issues

**Comment by ishaan-jaff** [comment]
closing - feel free to re-open if any problems
