### ISSUE TITLE
[Feature]: Add unit tests for Custom Callback Handler class

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1087]
### The Feature

1. document the types of the data passed in the callback  via hints 

2. assert the types in unit tests

### Motivation, pitch

User's filing repeated issues about things not working as expected in callbacks.

**Comment by ghost** [comment]
initial commit made - this adds coverage for testing sync + async completion calls on openai + azure via litellm completion/acompletion

https://github.com/BerriAI/litellm/commit/ea89a8a9386faacbc9c946149b23d3376997c79a

**Comment by ghost** [comment]
This is now added.
