### ISSUE TITLE
[Feature]: Add VoyageAI embeddings 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1090]
### The Feature

https://docs.voyageai.com/embeddings/

### Motivation, pitch

user request

**Comment by ishaan-jaff** [comment]
we support this now: https://docs.voyageai.com/embeddings/ 

cc @morgante this will be live on 1.16.4, just queue a new release

**Comment by morgante** [comment]
Thanks @ishaan-jaff.
