### ISSUE TITLE
[Bug]: openrouter prompt transform

### ISSUE THREAD

**Issue by dvolgyes** [BerriAI/litellm#1093]
### What happened?

I opened a pull request for it, but it is a 'bug' or 'feature' question.
So openrouter.ai transforms the prompt by default with a middle-out transform,
unless you provide an empty list of transforms.
See: https://openrouter.ai/docs#transforms

In my opinion, prompt transformation is not the responsibility of the router or
the llm interface layer, that is a higher level decision, so litellm (and openrouter) should not
transform the prompt. That is implemeneted here:
#1079 

I don't know where, but regardless of the default transform is left enabled,
or you accept the above PR, and it gets disabled, or it gets an option somewhere, it should be added to documentation somewhere. 

So consider it, if this is a bug or feature.

**Comment by ishaan-jaff** [comment]
we support setting openrouter specific params now: https://docs.litellm.ai/docs/providers/openrouter

**Comment by ishaan-jaff** [comment]
@dvolgyes I'd love to hop on a quick call to learn how we can make litellm better for your use case: 

sharing my calendly for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
