### ISSUE TITLE
[Bug]: langfuse: duplicate results in stream mode

### ISSUE THREAD

**Issue by langgg0511** [BerriAI/litellm#1096]
### What happened?

![image](https://github.com/BerriAI/litellm/assets/38091079/84c37e1d-1f5c-4a53-8159-118ac3d6b84b)

**Comment by CalabiYau14** [comment]
I observed the same in the most recent version (even with the fix of #1061)

**Comment by ghost** [comment]
@CalabiYau14 @langgg0511 is this with async streaming? 

Any sort of code to repro would be great.

**Comment by langgg0511** [comment]
@krrishdholakia yes, using langfuse under async streaming can cause this issue.

litellm.success_callback = ["langfuse"]
async def chat_completion(, *args, **kwargs)
    response = await litellm.acompletion(*args, **kwargs)
