### ISSUE TITLE
[Bug]: Lack of version for openai specified in requirements leads to error

### ISSUE THREAD

**Issue by abigailhaddad** [BerriAI/litellm#1098]
### What happened?

I have openai version 0.27.8 installed to be compatible with the marvin package. I'm able to pip install both marvin and litellm without any dependency errors. But there is a dependency error, because litellm requires a later version of openai. Ideally this would get resolved via compatibility with earlier versions of openai, less-ideally a version would just be specified so that when users try to install both, there's an error. 

### Relevant log output

```shell
>>> import litellm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\abiga\OneDrive\Documents\PythonScripts\llm_eval\env\Lib\site-packages\litellm\__init__.py", line 333, in <module>
    from .timeout import timeout
  File "C:\Users\abiga\OneDrive\Documents\PythonScripts\llm_eval\env\Lib\site-packages\litellm\timeout.py", line 20, in <module>
    from litellm.exceptions import Timeout
  File "C:\Users\abiga\OneDrive\Documents\PythonScripts\llm_eval\env\Lib\site-packages\litellm\exceptions.py", line 12, in <module>
    from openai import (
ImportError: cannot import name 'AuthenticationError' from 'openai' (C:\Users\abiga\OneDrive\Documents\PythonScripts\llm_eval\env\Lib\site-packages\openai\__init__.py)
```

**Comment by ishaan-jaff** [comment]
hmm we have it specified here: https://github.com/BerriAI/litellm/blob/b6ff59b62f53ef6b34c2544668cc78bed9b896aa/pyproject.toml#L11C19-L11C19

**Comment by abigailhaddad** [comment]
Good to know. That's for poetry, though, not pip. I think if you update your https://github.com/BerriAI/litellm/blob/b6ff59b62f53ef6b34c2544668cc78bed9b896aa/requirements.txt it will work for pip, too.

**Comment by ishaan-jaff** [comment]
updated : 
https://github.com/BerriAI/litellm/blob/main/requirements.txt

**Comment by ishaan-jaff** [comment]
feel free to re-open if not fixed
