### ISSUE TITLE
[Feature]: Add testing to ensure `import litellm` will not fail 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1099]
### The Feature

we had a commit that recently led to failing `import litellm` on machines without `tkinter` 

### Motivation, pitch

-

**Comment by ishaan-jaff** [comment]
cc @aseifert

**Comment by aseifert** [comment]
@ishaan-jaff  there's another tkinter import here: https://github.com/BerriAI/litellm/blob/da9976441b76067b6fe4614ef45439f184bb7697/litellm/llms/openai.py#L1

**Comment by ishaan-jaff** [comment]
removed - thanks for raising. cc @krrishdholakia I think ur vscode is acting up🤣

**Comment by ghost** [comment]
yea i think so. I'm surprised this passed circle ci. Open to feedback on how to prevent future issues @aseifert @ishaan-jaff

**Comment by aseifert** [comment]
Thanks! Build is passing on render.com now.

Not sure how to prevent this. I mean you COULD just set up auto-deploy to render (a free deployment) and then check for failing builds :-) not the most elegant way, but it IS a way ;-)

**Comment by ishaan-jaff** [comment]
we do this now, we auto-deploy litellm to railway https://litellm-api.up.railway.app/ 

builds are monitored to check for regressions
