### ISSUE TITLE
(feat) Add support for openai.Moderation.create

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#110]
Nice to have - some repos use`openai.Moderation.create`. When they move to using litellm they should not have any break functionality

**Comment by ishaan-jaff** [comment]
Saw some proxy servers using Moderation too

**Comment by ishaan-jaff** [comment]
https://github.com/whylabs/whylogs-container-python/pull/10

**Comment by ghost** [comment]
closing as we now support this - https://docs.litellm.ai/docs/embedding/moderation

**Comment by mkwasniak-brainly** [comment]
@krrishdholakia I do not want to open a new issue for that so let me ask here - is there also a way to use Moderation API with **LiteLLM Proxy**?

**Comment by ishaan-jaff** [comment]
Hi @mkwasniak-brainly not as yet, but I can start a PR for this? 

Would you be free to get on a quick call ? IT would be helpful to hear how you'd like to use the Moderation API / what interface you need 

Sharing a link to my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by ishaan-jaff** [comment]
Hi @mkwasniak-brainly I started a PR here: https://github.com/BerriAI/litellm/pull/1974 

It would be helpful to get on a quick call to understand how you're planning on using the proxy so we can improve for your use case
