### ISSUE TITLE
[Feature]: Caching across multiple model groups

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1101]
### What happened?

Router supports caching by model group, but based on this gist, a call that should be getting cached, isn't - https://gist.github.com/aseifert/20a1e8cfcccd8e9e684dddb9b05f7b7a

**Comment by ghost** [comment]
Updated based on user feedback - seems like they want to have gpt-4 and azure-gpt-4 be different groups but still cache across them. 

I think this can be solved by enabling caching groups on the Router

**Comment by ghost** [comment]
cc: @aseifert

Looking deeper into this, how would you expect to pass this in? 

```python
model_list = [
			{
				"model_name": "openai-gpt-3.5-turbo",
				"litellm_params": {
					"model": "gpt-3.5-turbo-0613",
					"api_key": os.getenv("OPENAI_API_KEY"),
				},
				"tpm": 100000,
				"rpm": 10000,
			},
			{
				"model_name": "azure-gpt-3.5-turbo",
				"litellm_params": {
					"model": "azure/chatgpt-v-2",
					"api_key": os.getenv("AZURE_API_KEY"),
					"api_base": os.getenv("AZURE_API_BASE"),
					"api_version": os.getenv("AZURE_API_VERSION")
				},
				"tpm": 100000,
				"rpm": 10000,
			}
		]

		messages = [
			{"role": "user", "content": f"write a one sentence poem {time.time()}?"}
		]
		start_time = time.time()
		router = Router(model_list=model_list,  caching_groups=[(openai-gpt-3.5-turbo, azure-gpt-3.5-turbo)])
```

?

**Comment by aseifert** [comment]
LGTM, thanks! (sorry, saw this only now)

**Comment by ghost** [comment]
closing as this is now supported
