### ISSUE TITLE
[Bug]: embedding calls - pass user/openai optional params 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1103]
### What happened?

Embedding calls pass non-default params. This means an openai param (e.g. user) is not sent as part of logging or the actual api call.

**Comment by ghost** [comment]
fixed - https://github.com/BerriAI/litellm/commit/8b07a6c046e30c666d39c036a73e96a05a379390

should be in prod in v`1.12.8` - https://github.com/BerriAI/litellm/commit/7efcc550e26f95579f9820a3b664115046bf4daa
