### ISSUE TITLE
[Bug]: `/key/generate` not working on GKE cluster

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1104]
### What happened?

The prisma db client variable says it's set to None. But in a prior step it's working with the llm api calls. 

Steps for repro: 
- num workers = 8
- gke cluster

**Comment by ghost** [comment]
cc: @Manouchehri have you come across this issue?

**Comment by Manouchehri** [comment]
Not yet.

**Comment by ghost** [comment]
user says they were using langfuse and the missing langfuse install was causing this. Closing as they fixed it
