### ISSUE TITLE
[Feature]: `/key/update` enable admin to update the values of a user key

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1107]
### The Feature

sure: i'd like to be able to update specific values like the models array column on some user key. Let's say i generated a key for a user with model1 and model2 in the models list/column, and now i want to update his models again and add model3 and model4 to the models list. that's where i would need a /key/update endpoint. 

### Motivation, pitch

user request

**Comment by ghost** [comment]
Added - https://github.com/BerriAI/litellm/commit/693292a64ca85e8a752dc653896c91ad541d2fe3
