### ISSUE TITLE
[Feature]: Langfuse installed in docker image

### ISSUE THREAD

**Issue by bsu3338** [BerriAI/litellm#1108]
### The Feature

When I try to run langfuse with the docker image, it says Langfuse is not installed.  Would be be possible to install all the possible llm monitor modules within the docker image?

### Motivation, pitch

I do not want to have to build a custom docker image for monitoring.

**Comment by ghost** [comment]
that's a good idea. Are you self-hosting langfuse or using their hosted solution? 

@bsu3338

**Comment by bsu3338** [comment]
Trying out self hosted first, I may want to try some of the others which is why I mentioned adding the others.

**Comment by ishaan-jaff** [comment]
this is now in requirements.txt @bsu3338 
https://github.com/BerriAI/litellm/blob/main/requirements.txt

**Comment by ishaan-jaff** [comment]
Would love to give you a shoutout on our daily change log. 
What's your Linkedin / Twitter ?

**Comment by ishaan-jaff** [comment]
closing this issue since it's done

**Comment by bsu3338** [comment]
@ishaan-jaff Sorry, I just tried it out and it all works great with the latest image. I do not have a twitter or LinkedIn. I appreciate the change.  I am currently trying to integrate litellm with Librechat, BionicGPT, Langfuse, and Ollama. So far it all seem to be working.

**Comment by ishaan-jaff** [comment]
@bsu3338 any chance you're free for a quick call sometime this week / next ? 

I'd love to learn how we can make litellm better for you 

sharing a link to my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
