### ISSUE TITLE
(feat) Allow users to pass HF LLM URL 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#111]
Currently we only allow model name but several repos use : 

`HUGS_SENTIMENT_API_URL = "https://api-inference.huggingface.co/models/cardiffnlp/twitter-roberta-base-sentiment"`

adding litellm should be as simple as changing one line of code

**Comment by ghost** [comment]
closing as we support this now - https://docs.litellm.ai/docs/completion/supported
