### ISSUE TITLE
[Feature]: Huggingface InferenceClient

### ISSUE THREAD

**Issue by shuther** [BerriAI/litellm#1110]
### The Feature

As per [HF inference doc](https://huggingface.co/docs/huggingface_hub/v0.19.3/guides/inference), it is possible to call a model based on a domain (text_to_image, text-generation, ...); I do see some logic in litellm but no call to InferenceClient, so I was wondering if it is possible to use litellm as a proxy to HF and let HF decides which model to use?

### Motivation, pitch

I expect the users to define the models they accept (due to license...) but letting the final choice to an engine (could be hosted within HF or within litellm).

**Comment by ghost** [comment]
Hey @shuther, you can now use custom api's with litellm with your own integration - https://docs.litellm.ai/docs/providers/custom_llm_server

Feel free to share your integration via PR if you find it works well!
