### ISSUE TITLE
[Feature]: Support streaming for `/completions`

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1113]
### The Feature

```
curl http://localhost:6000/v1/completions \                                               
-H "Content-Type: application/json" \
-H "Authorization: Bearer YOUR_API_KEY" \
-d '{"model": "text-davinci-003", "prompt": "Say this is a test", "temperature": 0, "max_tokens": 7, "stream': true}'
```

Returns chunks in the chat completions format. 

Support it being in the /completions format. 

### Motivation, pitch

yes my app is big on completions, and it's still going to be used. they are just finished with the API. they are also turning off some models, but the api will continue to be used. lot of applications like autocomplete, etc

**Comment by ghost** [comment]
This is now done - https://github.com/BerriAI/litellm/commit/1608dd7e0b011c35ae3b7078b28257d085c79c92
