### ISSUE TITLE
[Feature]: add testing for /embedding cache 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1115]
### The Feature

currently our test is only for in memory embedding cache, we need to make sure it works for redis and assert the response id's are the same 

### Motivation, pitch

-

**Comment by ghost** [comment]
added - https://github.com/BerriAI/litellm/commit/8d688b6217eb83ac59630f487039402af2b6b560

Our callback unit tests, test azure embeddings and if a cache hit happens (only logging state entered would be 'success').
