### ISSUE TITLE
[Feature]: Allow configuring cache for embedding - on, completions() off

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1117]
### The Feature

allow the user to initialize cache to only be used for `embeddings` but not `completions`

### Motivation, pitch

> I dont think I would want caching for chat/completion models, only embedding models for now.

**Comment by ghost** [comment]
@ishaan-jaff isn't this already covered, since we cache on model name + params?

**Comment by ghost** [comment]
support for embedding caching added - https://github.com/BerriAI/litellm/commit/8d688b6217eb83ac59630f487039402af2b6b560

key change - adding the embedding params to the cache key generation file.
