### ISSUE TITLE
[Feature]: Identify cache hits in litellm callbacks 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1118]
### The Feature

> I think I'd want to be able to tell in the callback that the response was "free" so I can log a 0 cost, and perhaps generate a "cached: True" 

### Motivation, pitch

-

**Comment by krrishdholakia** [comment]
![Uploading Screenshot 2023-12-13 at 4.57.49 PM.png…]()

**Comment by ghost** [comment]
Working on this now. Initial thoughts - looks like this will require us to create a new param in success handler to pass in a "cache hit occurred" kwarg
<img width="1245" alt="Screenshot 2023-12-13 at 4 58 01 PM" src="https://github.com/BerriAI/litellm/assets/17561003/7ef75e42-e7ba-4c42-8cea-46ac53a9e597">

**Comment by ghost** [comment]
pushed - https://github.com/BerriAI/litellm/commit/8d688b6217eb83ac59630f487039402af2b6b560

we now log a `kwargs["cache_hit"]: Optional[bool]` value in async success
https://github.com/BerriAI/litellm/commit/8d688b6217eb83ac59630f487039402af2b6b560

**Comment by ishaan-jaff** [comment]
can you update this doc for this ticket too: 
https://docs.litellm.ai/docs/caching/redis_cache#detecting-cached-responses

**Comment by ghost** [comment]
added - https://github.com/BerriAI/litellm/commit/589a6ca863000ba8e92c897ba0f776796e7a5904
