### ISSUE TITLE
[Feature]: Gemini support through google generativeai library

### ISSUE THREAD

**Issue by phact** [BerriAI/litellm#1126]
### The Feature

There's a new module for the palm library for gemini that supports streaming: 

https://ai.google.dev/api/python/google/generativeai/GenerativeModel

The current PALM support in litellm uses:

https://ai.google.dev/api/python/google/generativeai/generate_text

These APIs have an advantange over the VertexAI module in that they allow for API key usage.

It doesn't seem like they call the new API Palm anymore so maybe it makes sense to do a new "llm" for it? We should make it work with google/... models instead of palm/... models.

### Motivation, pitch

Buys us api_key based access while retaining streaming for Gemini models. This may be the easiest way for developers to use Gemini and it's free up to 60 qps. You still need VertexAI for prod.

### Twitter / LinkedIn details

https://twitter.com/syllogistic https://www.linkedin.com/in/sestevez/

**Comment by ghost** [comment]
@phact seems like you'd still switch to vertex ai for prod? Any reason you're not just starting with that

**Comment by phact** [comment]
I was wondering the same thing. Got my answer though and it's pretty clear. It's because the dev api is free:
https://x.com/DynamicWebPaige/status/1735156128777175116?s=20

It's going to get way more adoption than VertexAI

**Comment by ghost** [comment]
are you planning on using that? @phact

**Comment by phact** [comment]
I may try it with open interpreter which also depends on this project

**Comment by haseeb-heaven** [comment]
Yes Please add support for this LangChain already added this support for Gemini

**Comment by ghost** [comment]
I'm currently working on this issue - https://github.com/BerriAI/litellm/issues/1139

Would welcome a PR that adds the palm/gemini support. 

Brief outline of how i'd expect it to work:
- separate file - `gemini.py` (similar structure to `palm.py`)
- provider name (i.e. `gemini`) added to provider_list in __init__.py 
- testing added in `test_completion.py` and `test_streaming.py` that shows it works 
- models added to model_prices_and_context_window.json as `gemini/<model-name>` (similar to palm)

How it works on litellm.completion()

```python
litellm.completion(model="gemini/gemini-pro", messages=[{"role": "user", "content": "Tell me a story about a magic backpack"}]
```

--
Thinking: 
- i don't want to ship a breaking change (changing from `palm/` to `google_gen_model/` would be a breaking change).

**Comment by haseeb-heaven** [comment]
> I'm currently working on this issue - #1139
> 
> Would welcome a PR that adds the palm/gemini support.
> 
> Brief outline of how i'd expect it to work:
> 
> * separate file - `gemini.py` (similar structure to `palm.py`)
> * provider name (i.e. `gemini`) added to provider_list in **init**.py
> * testing added in `test_completion.py` and `test_streaming.py` that shows it works
> * models added to model_prices_and_context_window.json as `gemini/<model-name>` (similar to palm)
> 
> How it works on litellm.completion()
> 
> ```python
> litellm.completion(model="gemini/gemini-pro", messages=[{"role": "user", "content": "Tell me a story about a magic backpack"}]
> ```
> 
> -- Thinking:
> 
> * i don't want to ship a breaking change (changing from `palm/` to `google_gen_model/` would be a breaking change).

I have added a [Gemini PR](https://github.com/BerriAI/litellm/pull/1144) for this feature request please take a look

**Comment by cwang** [comment]
Would you be considering adding `gemini-pro-vision` too? I think there's something extra to align the image transmission format for it with OpenAI's vision model `gpt-4-vision-preview` but otherwise should be largely covered by whatever implementation there is for `gemini-pro`.

**Comment by haseeb-heaven** [comment]
> Would you be considering adding `gemini-pro-vision` too? I think there's something extra to align the image transmission format for it with OpenAI's vision model `gpt-4-vision-preview` but otherwise should be largely covered by whatever implementation there is for `gemini-pro`.

I think it needs separate PR since its different category of Image generation.

**Comment by twardoch** [comment]
Ideally PaLM & Gemini should be moved to a "Google generative AI" provider module, and then the old PaLM support could be made into a shim

**Comment by twardoch** [comment]
https://youtu.be/64Ldwi9YU4I?si=YOzPZugctD3vyVcF

I think the fact that the Gemini API is free* for 60 calls/minute is very attractive.

[*] Google reads your data then & will use it for training

**Comment by haseeb-heaven** [comment]
> https://youtu.be/64Ldwi9YU4I?si=YOzPZugctD3vyVcF
> 
> I think the fact that the Gemini API is free* for 60 calls/minute is very attractive.
> 
> [*] Google reads your data then & will use it for training

Yes its already mentioned free API means the take data to train their models.
But Gemini Ultra will be the one focusing one.

**Comment by ghost** [comment]
Initial commit made that adds google gemini support for completion calls - https://github.com/BerriAI/litellm/commit/1262d89ab385d16220d1578a4908f53b9bc5a075

Need to add: 
- [ ] Support for optional params
- [ ] Streaming 
- [ ] Async support 


cc: @twardoch @cwang @haseeb-heaven @phact

**Comment by haseeb-heaven** [comment]
> Initial commit made that adds google gemini support for completion calls - [1262d89](https://github.com/BerriAI/litellm/commit/1262d89ab385d16220d1578a4908f53b9bc5a075)
> 
> Need to add:
> 
> * [ ]  Support for optional params
> * [ ]  Streaming
> * [ ]  Async support
> 
> cc: @twardoch @cwang @haseeb-heaven @phact

I already had a PR for that [Pr for Gemini](https://github.com/BerriAI/litellm/pull/1144) check this one

**Comment by ErnestDong** [comment]
Another reason for the feature may be there are [restrictions](https://www.googlecloudcommunity.com/gc/Cloud-Hub/How-can-I-use-vertex-ai-in-China/td-p/691912) on using vertex ai.

**Comment by ghost** [comment]
This is now live - https://docs.litellm.ai/docs/providers/gemini
