### ISSUE TITLE
[Bug]: remove secret credentials from debug / set_verbose = True logs

### ISSUE THREAD

**Issue by chymian** [BerriAI/litellm#1127]
### What happened?

API-Keys are printed in full lenght in logs.

that is a major security flaw.

**Comment by ishaan-jaff** [comment]
how can I repro this ? you should not see any logs when `litellm.set_verbose=False` or on the proxy when you start it with `litellm`

**Comment by chymian** [comment]
that might be true for normal operation.
but for `set_verbose: True`, which is essential to have the full log to open a issue, I had manually remove all together_ai keys in [1111](https://github.com/BerriAI/litellm/issues/1111) 
search for `valid-key` in the log.

**Comment by ishaan-jaff** [comment]
that's good feedback, would it be helpful if we mask the keys ? 

so we only log sk-1234444***** when set_verbose is True

**Comment by dnxnf** [comment]
20个小时前，是个新bug吗，我也遇到这个问题了
Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

**Comment by chymian** [comment]
@ishaan-jaff,
> so we only log sk-1234444***** when set_verbose is True

yep, somthing like that would do it.
(also for self-assigned, much shorter credentials.)

**Comment by dkindlund** [comment]
Hey @ishaan-jaff , I'm also seeing the full `model_name.litellm_params.api_key` details appear in the logs at the `INFO` level.  Example:
```
[92m23:09:07 - LiteLLM Router:INFO[0m: get_available_deployment for model: gpt-3.5-turbo-1106, Selected deployment: {'model_name': 'gpt-3.5-turbo-1106', 'litellm_params': {'model': 'azure/gpt-35-turbo', 'api_base': 'https://fletch-prod-9.openai.azure.com/', 'api_key': 'XXXREDACTEDXXX', 'api_version': '2024-02-15-preview', 'rpm': 720}, 'model_info': {'id': '91f7a2f6-3d15-4b64-8a79-5e174fb2b790'}} for model: gpt-3.5-turbo-1106
```

**Comment by ghost** [comment]
Hey @dkindlund just pushed a fix for it - https://github.com/BerriAI/litellm/pull/2125

It should mask the api key being printed in the router.py file (where the debug statement you shared was coming from). 

Will update this ticket once it's in prod.

**Comment by ghost** [comment]
live in v`1.26.8` @dkindlund

**Comment by ghost** [comment]
leaving this ticket open in case there's other places keys are showing up

**Comment by ishaan-jaff** [comment]
closing since we've cleaned this up
