### ISSUE TITLE
[Feature]: litellm --version missing

### ISSUE THREAD

**Issue by chymian** [BerriAI/litellm#1128]
### The Feature

litellm is missing a `--version` cmd option.

### Motivation, pitch

alternative to the missing option is only `git logs` if you have cloned the repo, or `pip list`

**Comment by ishaan-jaff** [comment]
added here: https://github.com/BerriAI/litellm/commit/241add8b333a8568627a1fe084267bb1993da185 

@chymian closing this issue let me know if you have feedback. Feel free to re-open
