### ISSUE TITLE
[Feature]: support cli args for /health endpoint

### ISSUE THREAD

**Issue by shuther** [BerriAI/litellm#1130]
### The Feature

add a /ping or /healthcheck endpoint (see: [health check](https://testfully.io/blog/api-health-check-monitoring/) ) so we can:
- validate that it is running (good for docker compose and external hosting) as a best effort.
- run a ping (or a small test) to every model/upstream endpoints (more usefull for the router mode).

### Motivation, pitch

we need to be able to monitor litellm from outside and restart it as needed.

**Comment by shuther** [comment]
it seems it exists, there are the /test and /health but I am not sure how to interpret the data, I receied this while I am using ollama. Is it expected?
```
{
  "healthy_endpoints": [],
  "unhealthy_endpoints": []
}
```

**Comment by ishaan-jaff** [comment]
- use `/test` to check if the proxy_server is alive 
- use `/health` to get healthy LLM endpoints

**Comment by ishaan-jaff** [comment]
hmm investigating why it's not working for ollama for you

**Comment by ishaan-jaff** [comment]
<img width="1278" alt="Screenshot 2023-12-14 at 4 43 25 PM" src="https://github.com/BerriAI/litellm/assets/29436595/d84a2a21-98c6-44b9-bf3d-d9096a894fe2">

worked fine with ollama for me @shuther 

- do you start the proxy with a config.yaml ?

**Comment by ishaan-jaff** [comment]
open to suggestions on what to name each endpoint
- ping/test is used to check if the proxy is healthy 
- health is used to actually make the LLM call, check if the LLMs are active

<img width="588" alt="Screenshot 2023-12-14 at 4 46 24 PM" src="https://github.com/BerriAI/litellm/assets/29436595/6e8463f2-3fb1-415d-9752-561d142e4bfa">

what do you think @shuther ?

**Comment by shuther** [comment]
looks good for me, just need to understand why it does not work in my scenario
for the /health, is it a secure end point (does it require authentification)? This is what I tried:
```
curl -X 'GET' \
  'http://localhost:8000/health' \
  -H 'accept: application/json'
{"healthy_endpoints":[],"unhealthy_endpoints":[]}
```

**Comment by shuther** [comment]
I was working with an old version of litellm, with the latest one I am getting an error 500:
```
curl -X 'GET' \
  'http://localhost:8000/health' \
  -H 'accept: application/json'
{"detail":{"error":"Model list not initialized"}}
```
Even if I do a 1st call before, I still get the same error.

**Comment by ishaan-jaff** [comment]
this error looks like you're creating the proxy without a config.yaml 

- how are you starting the proxy ?

**Comment by shuther** [comment]
`litellm --model ollama/mistral --add_function_to_prompt --telemetry=false --debug --drop_params`

**Comment by ishaan-jaff** [comment]
@shuther fixed here: https://github.com/BerriAI/litellm/commit/ce1b0b89bae72c45b09d1737304686049032e512 

closing this issue , feel free to re-open if this next version of litellm does not fix this for you
