### ISSUE TITLE
[Bug]: missing favicon.ico

### ISSUE THREAD

**Issue by shuther** [BerriAI/litellm#1131]
### What happened?

while running litellm using:
`litellm --model ollama/mistral --add_function_to_prompt --telemetry=false --debug --drop_params`
I faced in the log- missing favicon.ico.
I can't reproduce it, so not sure when the browser tried to access this file.

### Relevant log output

```shell
INFO:     127.0.0.1:59790 - "GET /favicon.ico HTTP/1.1" 404 Not Found
```

**Comment by ishaan-jaff** [comment]
I've been unable to repro this issue on my side, can we get help on how to repro this? @shuther

**Comment by shuther** [comment]
Let's ignore it for now. It is connected to openapi but if you have an icon, it is always good to add it
