### ISSUE TITLE
[Feature]: Support dynamo db logging on the proxy 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1141]
### The Feature

Support dynamo db logging (maybe via our open telemetry integration) on the proxy

### Motivation, pitch

user request

**Comment by ishaan-jaff** [comment]
cc @nirga is there an easy way to export traceloop logs to dynamo db ?

**Comment by nirga** [comment]
@ishaan-jaff hmm I'll double check later but I don't see anything out of the box:

https://opentelemetry.io/ecosystem/registry/?component=exporter&language=collector

**Comment by ishaan-jaff** [comment]
thanks for the response @nirga

**Comment by ishaan-jaff** [comment]
working on adding a custom dynamodb integration

- [x] docs https://docs.litellm.ai/docs/proxy/logging#logging-proxy-inputoutput---dynamodb 
- [x] code changes for adding dynamodb 
- [x] test creating a dynamodb table when it does not exist 
- [x] test async completion
- [x] test async streaming completion 
- [x] test proxy logging 
- [x] test embedding 
- [x] New LiteLLM Release

**Comment by ishaan-jaff** [comment]
this is completed !

**Comment by ishaan-jaff** [comment]
on 1.14.6+
