### ISSUE TITLE
[Feature]: Add liveness and readiness probe mechanism for proxy server

### ISSUE THREAD

**Issue by abhinavkulkarni** [BerriAI/litellm#1145]
### The Feature

Hi,

To use `litellm-proxy` in production environments (`docker-compose` or `k8s` installation), we need liveness and readiness probes so that it can be restarted automatically, etc.

E.g., the `text-generation-inference` server exposes `/health` endpoint which can be queried to figure out when the service is ready (it takes a while to load the model) for readiness probe and can be queried periodically for liveness probe.

The `litellm-proxy` project should introduce a helm chart that exposes such a health endpoint which internally maps to various health endpoints of corresponding services.

Thanks!

### Motivation, pitch

This will help integrate `litellm-proxy` in production workflows.

**Comment by ishaan-jaff** [comment]
thanks for the issue 

- we expose a `/health` endpoint which makes a request to all set LLMs
- we expose a `/test` endpoint which makes a ping to the litellm server and respons 

what's missing in these endpoints to be useful for your use case ?

**Comment by abhinavkulkarni** [comment]
Thanks @ishaan-jaff, that satisfies my requirement.

**Comment by ghost** [comment]
@abhinavkulkarni i've updated our docs with this as well - https://docs.litellm.ai/docs/proxy/health

Was this what you were looking for?
