### ISSUE TITLE
[Resolved]: Proxy streaming has a delay for ollama / vLLM 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1148]
### What happened?

> when using vLLM, we get like 1 string of words every ~2 seonds, and for ollama its even less. is it meant to be like that? or should it stream token by token?
> i tested ollama direct API, there it streams token per token, and ollama served over litellm "streams" like 1 paragraph all 5-6 seconds
> and for vllm its faster, but still same experience: direct vllm streams token by token, vllm via litellm streams ~1 block of text each 2 secs

## steps to repro:
- try streaming to ollama/vLLM with large prompts
- ollama / vLLM stream token per token. LiteLLM stream 1 para every 5-6 seconds

**Comment by ghost** [comment]
Hey @ishaan-jaff I don't think this is the case for ollama anymore. We yield the chunk as we get it. Same for vllm if they're calling it via the openai interface. Is there additional info like liteLLM version, etc. here?

**Comment by ishaan-jaff** [comment]
I'm on the latest version of litellm and I can consistently repro this on ollama

**Comment by ishaan-jaff** [comment]
actually correct - I can confirm ollama works great for me with stream you're right @krrishdholakia

**Comment by ishaan-jaff** [comment]
cc @morgendigital can you confirm the latest version works well for you too

**Comment by ishaan-jaff** [comment]
closing since this works on the latest version for me

**Comment by morgendigital** [comment]
Thanks guys, will test and confirm it later.
