### ISSUE TITLE
[Feature]: Add support for ollama/llava

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1151]
### The Feature

https://ollama.ai/library/llava

### Motivation, pitch

user wants to use GPT-V and LLaVa as the failback using Ollama's docker image

**Comment by ishaan-jaff** [comment]
this is added, need to add it to docs too

**Comment by ishaan-jaff** [comment]
done

**Comment by MrXandbadas** [comment]
[Providers-ollama-vision](https://docs.litellm.ai/docs/providers/ollama#ollama-vision-models)
took me a sec but I think I found it xD
