### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by elisalimli** [BerriAI/litellm#1154]
### What happened?

Litellm in timeout.py file trying to access TimeoutError from openai.error which does not exist.

I think it should be like in the following example:

from openai import APITimeoutError

def timeout(timeout_duration: float = 0.0, exception_to_raise=APITimeoutError):
 

### Relevant log output

```shell
ModuleNotFoundError: No module named 'openai.error'
```

**Comment by ghost** [comment]
@elisalimli can you share the stack trace - i don't believe we're using timeout.py anymore
