### ISSUE TITLE
[Bug]: Pin dependencies on proxy

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1160]
### What happened?

A runtime dependency install caused a user's proxy to crash in runtime. 

"You also absolutely should not have code that installs dependencies at runtime."

### Relevant log output

```shell
litellm-litellm-1  | callback: <bound method Router.deployment_callback_on_failure of <litellm.router.Router object at 0xffff9cdd3fd0>>
litellm-litellm-1  | callback: <bound method Router.deployment_callback of <litellm.router.Router object at 0xffff9cdd3fd0>>
litellm-litellm-1  | callback: traceloop
litellm-litellm-1  | An error occurred: type object 'TracerWrapper' has no attribute 'app_name'
```

**Comment by ghost** [comment]
We should also add checks to ensure no dependencies are being installed on runtime, to prevent any future regressions.

**Comment by ghost** [comment]
Able to repro this problem 
<img width="805" alt="Screenshot 2023-12-16 at 11 12 00 AM" src="https://github.com/BerriAI/litellm/assets/17561003/c6b35502-9a3a-4bfe-9a27-d16900a55816">

**Comment by ghost** [comment]
I'm seeing an error when it's doing the initialization of the callbacks. I would expect this error to happen on proxy startup, not once the call is being made (very bad!). 
<img width="1165" alt="Screenshot 2023-12-16 at 11 14 44 AM" src="https://github.com/BerriAI/litellm/assets/17561003/7309de97-abb1-481a-83db-daa289e1d9fe">

**Comment by ghost** [comment]
Moved the init to proxy startup. 

Hit another issue with traceloop where their transformers library was causing us to fail. Had to remove transformers from my environment. now hit the same issue 


```
  File "/Users/krrishdholakia/Documents/litellm/litellm/proxy/proxy_server.py", line 829, in startup_event
    proxy_logging_obj._init_litellm_callbacks() # INITIALIZE LITELLM CALLBACKS ON SERVER STARTUP <- do this to catch any logging errors on startup, not when calls are being made
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/krrishdholakia/Documents/litellm/litellm/proxy/utils.py", line 55, in _init_litellm_callbacks
    litellm.utils.set_callbacks(
  File "/Users/krrishdholakia/Documents/litellm/litellm/utils.py", line 3558, in set_callbacks
    raise e
  File "/Users/krrishdholakia/Documents/litellm/litellm/utils.py", line 3523, in set_callbacks
    traceloopLogger = TraceloopLogger()
                      ^^^^^^^^^^^^^^^^^
  File "/Users/krrishdholakia/Documents/litellm/litellm/integrations/traceloop.py", line 6, in __init__
    self.tracer_wrapper = TracerWrapper()
                          ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/traceloop/sdk/tracing/tracing.py", line 47, in __new__
    obj.__resource = Resource(attributes={SERVICE_NAME: TracerWrapper.app_name})
                                                        ^^^^^^^^^^^^^^^^
```

**Comment by ghost** [comment]
Realized my traceloop api key was missing from the environment. 
<img width="1211" alt="Screenshot 2023-12-16 at 11 38 40 AM" src="https://github.com/BerriAI/litellm/assets/17561003/a30b5d94-e607-40e6-b002-f94320568c4b">

When I went to traceloop and added the api key into my environment, this problem was fixed. 
<img width="1219" alt="Screenshot 2023-12-16 at 11 39 28 AM" src="https://github.com/BerriAI/litellm/assets/17561003/3637bae5-54e5-46b7-a878-c30e43b1f472">

**Comment by ghost** [comment]
Works
<img width="842" alt="Screenshot 2023-12-16 at 11 40 03 AM" src="https://github.com/BerriAI/litellm/assets/17561003/249e101c-3bf1-486f-9200-c53d2efa309d">
<img width="902" alt="Screenshot 2023-12-16 at 11 40 16 AM" src="https://github.com/BerriAI/litellm/assets/17561003/1c2eb5f4-fcd6-4550-9a89-0960c51e7901">

**Comment by ghost** [comment]
fixed
