### ISSUE TITLE
[Bug]: 422 Unprocessable Entity

### ISSUE THREAD

**Issue by dtthanh1971** [BerriAI/litellm#1165]
### What happened?

A bug happened when I want to generate a key by trying to use:

curl "http://127.0.0.1:8000/key/generate" -H "Authorization: Bearer sk-123456789" -d "{\"models\": [\"gpt-3.5-turbo\"], \"duration\": \"20m\"}"

I have successfully installed Postgres and declared it in config.yml as follows:
general_settings: 
  master_key: sk-123456789
  database_url: "postgresql://<user>:<password>@<host>:<port>/<dbname>"

### Relevant log output

```shell
But II received the messages on the console as follow:

INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:64258 - "POST /key/generate HTTP/1.1" 422 Unprocessable Entity
```

**Comment by dtthanh1971** [comment]
I install prisma client. The problem is solved.

**Comment by ghost** [comment]
Hey @dtthanh1971 the prisma client should be getting automatically installed on startup. Can you share steps to repro this?

**Comment by ishaan-jaff** [comment]
I saw the 422 Unprocessable Entity, its caused when the server does not receive a valid json in the body 

fixed when you specify content type in the header
```
curl 'http://0.0.0.0:8000/key/generate' \
--header 'Authorization: Bearer sk-1234' \
--header 'Content-Type: application/json' \
--data-raw '{"models": ["gpt-3.5-turbo", "gpt-4", "claude-2"], "duration": "20m","metadata": {"user": "ishaan@berri.ai", "team": "core-infra"}}'
```

**Comment by ishaan-jaff** [comment]
422s don't even reach any of our code logic for the endpoint
https://www.google.com/search?q=422+error&oq=422+er&gs_lcrp=EgZjaHJvbWUqDQgAEAAYgwEYsQMYgAQyDQgAEAAYgwEYsQMYgAQyDQgBEAAYgwEYsQMYgAQyBggCEEUYOTIHCAMQABiABDIHCAQQABiABDIHCAUQABiABDIHCAYQABiABDIGCAcQRRg8qAIAsAIA&sourceid=chrome&ie=UTF-8
