### ISSUE TITLE
[Bug]: Using the gpt-3.5-turbo-instruct model will have two successful callbacks.

### ISSUE THREAD

**Issue by langgg0511** [BerriAI/litellm#1172]
### What happened?

Using the gpt-3.5-turbo-instruct model will have two successful callbacks.
If langfuse is used, two identical Traces and Generations will be recorded.

**Comment by langgg0511** [comment]
in litellm.text_completion() ,stream is true

**Comment by ishaan-jaff** [comment]
@langgg0511 are you using the langfuse callback? or a custom callback ?

**Comment by ishaan-jaff** [comment]
I can repro this problem, using langfuse with streaming atext_completion

**Comment by ishaan-jaff** [comment]
this is caused because openai sends 2 chunks with `finish_reason != None` for `/completions`

**Comment by ishaan-jaff** [comment]
fixed here: https://github.com/BerriAI/litellm/commit/646c106983a185bcf9dd002dd331135cdcd504eb @langgg0511

**Comment by ishaan-jaff** [comment]
@langgg0511 we'd love to learn how we can make LiteLLM better for you 

are you free for a quick call sometime this week/next ? Sharing my cal for your convenience: 
https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by ishaan-jaff** [comment]
this is in prod on v1.15.10+ 

@langgg0511 can you lmk if it's resolved for you ?

**Comment by ishaan-jaff** [comment]
feel free to reopen if not resolved

**Comment by langgg0511** [comment]
> this is in prod on v1.15.10+
> 
> @langgg0511 can you lmk if it's resolved for you ?

thank
