### ISSUE TITLE
[Bug]:  langfuse integration returning error

### ISSUE THREAD

**Issue by speedyankur** [BerriAI/litellm#1177]
### What happened?

I tried integrating both local and cloud hosted langfuse latest versions(ver 2.0) to litellm proxy server. but in both cases Im getting this error

### Relevant log output

```shell
LiteLLM.LoggingError: [Non-Blocking] Exception occurred while success logging Traceback (most recent call last):
  File "/home/A65379/.pyenv/versions/3.10.13/envs/genai/lib/python3.10/site-packages/litellm/utils.py", line 1180, in async_success_handler
    await langFuseLogger._async_log_event(
  File "/home/A65379/.pyenv/versions/3.10.13/envs/genai/lib/python3.10/site-packages/litellm/integrations/langfuse.py", line 78, in _async_log_event
    self.log_event(kwargs, response_obj, start_time, end_time, print_verbose)
  File "/home/A65379/.pyenv/versions/3.10.13/envs/genai/lib/python3.10/site-packages/litellm/integrations/langfuse.py", line 34, in log_event
    from langfuse.model import InitialGeneration, Usage
ImportError: cannot import name 'InitialGeneration' from 'langfuse.model' (/home/A65379/.pyenv/versions/3.10.13/envs/genai/lib/python3.10/site-packages/langfuse/model.py)
```

**Comment by speedyankur** [comment]
It seems that litellm is not compatible with langfuse > ver 2.0

**Comment by speedyankur** [comment]
I tried debugging it a little bit, found that litellm is only compatible until langfuse ver 1.14.0 only. So I updated the documentation accordingly to install langfuse ver1.14.o

**Comment by speedyankur** [comment]
https://github.com/BerriAI/litellm/pull/1178

**Comment by ghost** [comment]
Sweet - thanks!

**Comment by dtthanh1971** [comment]
A lot of bug with the Callback

I have successfuly setup callback with helicone.

![image](https://github.com/BerriAI/litellm/assets/46180030/01c5171b-9aad-4c39-96a1-c524b5243a3e)

**Comment by ghost** [comment]
@dtthanh1971 what were the issues with callbacks? 

Here's our unit tests for it: https://github.com/BerriAI/litellm/blob/9eb487efb37c2257bc5499e9a1dcc6c4906facfa/litellm/tests/test_custom_callback_input.py#L4
https://github.com/BerriAI/litellm/blob/9eb487efb37c2257bc5499e9a1dcc6c4906facfa/litellm/tests/test_custom_callback_router.py#L4

**Comment by ghost** [comment]
bump @dtthanh1971

**Comment by dtthanh1971** [comment]
Something has change in langfuse

This is my work around for the file langfuse.py


```
def log_event(self, kwargs, response_obj, start_time, end_time, print_verbose):
        # Method definition
        #from langfuse.model import Usage,  InitialGeneration
        try:
            print_verbose(
                f"Langfuse Logging - Enters logging function for model {kwargs}"
            )
            # print(f"--------- kwarg: {kwargs}")
            litellm_params = kwargs.get("litellm_params", {})
            metadata = litellm_params.get("metadata", {}) or {} # if litellm_params['metadata'] == None 
            prompt = [kwargs.get('messages')]
            optional_params = kwargs.get("optional_params", {})

            # langfuse only accepts str, int, bool, float for logging
            for param, value in optional_params.items():
                if not isinstance(value, (str, int, bool, float)):
                    try:
                        optional_params[param] = str(value)
                    except:
                        # if casting value to str fails don't block logging
                        pass
                        
            
            # end of processing langfuse ########################
            self.Langfuse.generation(
                name=metadata.get("generation_name", "litellm-completion"),
                startTime=start_time,
                endTime=end_time,
                model=kwargs['model'],
                modelParameters=optional_params,
                input=prompt,
                output = response_obj['choices'][0]['message']['content'],
                usage={
                    "promptTokens":response_obj['usage']['prompt_tokens'],
                    "completionTokens":response_obj['usage']['completion_tokens'],
                    "totalTokens":response_obj['usage']['total_tokens']
                },
                metadata=metadata
            )
            self.Langfuse.flush()
            print_verbose(
                f"Langfuse Layer Logging - final response object: {response_obj}"
            )
        except:
            traceback.print_exc()
            print_verbose(f"Langfuse Layer Error - {traceback.format_exc()}")
            pass

```
    async def _async_log_event(self, kwargs, response_obj, start_time, end_time, print_verbose):
        self.log_event(kwargs, response_obj, start_time, end_time, print_verbose)

Please read here:
https://langfuse.com/docs/sdk/python#generation

And my screen:
![image](https://github.com/BerriAI/litellm/assets/46180030/b0b1fe31-578c-4523-98fa-bd0a723885cc)

**Comment by ghost** [comment]
Thanks @dtthanh1971 - i'll prioritize a fix for this.

**Comment by ghost** [comment]
Hi @dtthanh1971 we just merged a PR from the langfuse team, updating their integration for langfuse's v2 sdk. 

Let me know if the issue still persists for you. Here's the new langfuse.py file - https://github.com/BerriAI/litellm/blob/2df5ce4b7c3d6bcc22a184572489c71d155993ca/litellm/integrations/langfuse.py#L4

**Comment by ghost** [comment]
closing as I believe this is now solved. @dtthanh1971 @speedyankur @oneline-hyunjun-jeon please reopen if this issue persists for you
