### ISSUE TITLE
pkg_resources is deprecated

### ISSUE THREAD

**Issue by yujonglee** [BerriAI/litellm#118]
https://github.com/BerriAI/litellm/blob/e354b71df028312d8fcb2220467f92c37fbfcac5/litellm/utils.py#L9

https://setuptools.pypa.io/en/latest/pkg_resources.html

> Use of pkg_resources is deprecated in favor of [importlib.resources](https://docs.python.org/3/library/importlib.resources.html#module-importlib.resources), [importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html#module-importlib.metadata) and their backports ([importlib_resources](https://pypi.org/project/importlib_resources), [importlib_metadata](https://pypi.org/project/importlib_metadata)). Some useful APIs are also provided by [packaging](https://pypi.org/project/packaging) (e.g. requirements and version parsing). Users should refrain from new usage of pkg_resources and should work to port to importlib-based solutions.

I am not aware of alternatives though. Happy do work on PR if anyone let me know alternatives.

**Comment by ghost** [comment]
Hey @yujong-lee thanks for surfacing this. Looks like we might be able to use import-lib as well? I can explore this as well. 

Are you facing this issue in production? 

cc: @ishaan-jaff

**Comment by yujonglee** [comment]
@krrishdholakia  Thank you.

No this does not cause any trouble. I am using it just fine.
Just found it while reading codebase.

**Comment by ghost** [comment]
Sounds good! @yujong-lee  

Any chance you could do a <15min chat sometime this/next week? Would love to get your thoughts on the product and how we can make it better for you.

https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by yujonglee** [comment]
For anyone interested: https://github.com/pypa/packaging-problems/issues/664

**Comment by ishaan-jaff** [comment]
![Screenshot 2023-08-17 at 11 15 12 AM](https://github.com/BerriAI/litellm/assets/29436595/d6461a0a-83be-4841-93c9-ed2ab24dc1c6)

+1 saw this when running locally thanks for raising @yujonglee

**Comment by ghost** [comment]
I dealt with this by just try-excepting on ImportError instead of the distributionnotfound, etc. which were subclasses of ImportError

**Comment by zakhar-kogan** [comment]
Maybe [this](https://github.com/BerriAI/litellm/commit/d27aa67777bbcf2cdfbf2eb2d01a3fc7cca8801b) can work, too? To ditch `pkg_resources` completely 😅

The most basic change ever:
<img width="719" alt="image" src="https://github.com/BerriAI/litellm/assets/36503576/5178563d-6602-47b4-a3b1-0a0278d25beb">

Seems to work fine:
<img width="650" alt="image" src="https://github.com/BerriAI/litellm/assets/36503576/f5c82292-2d94-489f-a545-cef01e66482c">

@krrishdholakia

**Comment by yujonglee** [comment]
@krrishdholakia  I think we can close this by #180.

**Comment by ghost** [comment]
done - thanks for the great work @zakhar-kogan @yujonglee

**Comment by WesleyYue** [comment]
It looks like there's still a `pkg_resources` usage [here](https://github.com/BerriAI/litellm/blob/2165dcf6fbce2f92e1d4744613c0d4375e57c8f3/litellm/utils.py#L2495C12-L2495C25), and it's breaking the package for me on Python 3.12.

**Comment by ghost** [comment]
Reopening to track this, thanks for flagging @WesleyYue

**Comment by ghost** [comment]
Created a PR - https://github.com/BerriAI/litellm/pull/1556, will update this ticket once it's merged

**Comment by WesleyYue** [comment]
fyi still running into this issue https://github.com/BerriAI/litellm/blob/fd0a360d61eafdf2a35740113fd2782c3018c54a/litellm/utils.py#L32

**Comment by ghost** [comment]
merged @sorokine's PR here - let me know if this issue still persists @WesleyYue
