### ISSUE TITLE
liteLLM  error while running GPT 3.5 turbo with open-interpreter 

### ISSUE THREAD

**Issue by vighnxsh** [BerriAI/litellm#1181]
![Screenshot 2023-12-19 110145](https://github.com/BerriAI/litellm/assets/115893429/692e7e0b-c72b-4553-b6f0-efa3a54be266)

i even check the compatibilites of packages i downgraded the litellm and openai package according to open-interpreter need still its throwing this error

**Comment by ghost** [comment]
hey @vighnxsh i can't tell what the error raised is. Looks like it's being swallowed by open interpreter. Might be worth checking to see if they have a debug flag - https://github.com/KillianLucas/open-interpreter/
