### ISSUE TITLE
[Bug]: Making sure API keys and protected information are not logged in callback under observability 

### ISSUE THREAD

**Issue by navidre** [BerriAI/litellm#1186]
### What happened?

During testing Slack callback, noticed the API keys get logged too. Added this PR to prevent it in the callback definition: https://github.com/BerriAI/litellm/pull/1185

It will be good to audit and make sure the callbacks do not log API keys or sensitive information

### Twitter / LinkedIn details

@navid_re / https://www.linkedin.com/in/navidrezaei/

**Comment by Manouchehri** [comment]
Likewise with Sentry (though it seems to have built in filtering, so it stops LiteLLM from logging private API keys).

**Comment by ghost** [comment]
Hey @navidre can we close this ticket, since the pr is merged?
