### ISSUE TITLE
(fix) HF flan t-5 missing output params

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#119]
HF flan t-5 missing out params
<img width="1006" alt="Screenshot 2023-08-15 at 8 59 27 AM" src="https://github.com/BerriAI/litellm/assets/29436595/8ca67c48-310b-424b-a84b-8a474ef46ba6">

**Comment by ghost** [comment]
i don't think that's the value of response. moreso an errant print statement.

**Comment by ghost** [comment]
cleaned - 04bffcea924700a236c261e280b3b6ea3dc410d4
