### ISSUE TITLE
[Feature]: Support OpenAI logprobs for chat completions

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1194]
### The Feature

This now exists. We should support it asap. 
![image](https://github.com/BerriAI/litellm/assets/17561003/28a617a3-96bd-4997-91a4-77e26318bdb9)

### Motivation, pitch

logprobs is important in calculating things like confidence in output generated

**Comment by ghost** [comment]
We already support this for TGI, we should see how to leverage some of that work here.

**Comment by ishaan-jaff** [comment]
added openai logprobs: 
https://github.com/BerriAI/litellm/commit/7b097305c1c5ca810ef2e57038dab0c0c5555664 

test for this: https://github.com/BerriAI/litellm/commit/b9f2262d5f2d7bf92721e1aa0819226169ad4f12

**Comment by ishaan-jaff** [comment]
remaining -
- add this for streaming
- add to docs
- add for azure 
- add for azure streaming

**Comment by ishaan-jaff** [comment]
azure has a different arg for logprobs 😄https://learn.microsoft.com/en-us/azure/ai-services/openai/reference 

@Manouchehri thanks for linking to this

**Comment by ishaan-jaff** [comment]
Update on Azure: 
They don't support logprobs as yet: https://learn.microsoft.com/en-us/answers/questions/1462367/azure-openai-endpoint-support-for-logprobs 

We get this error on sending logprobs 
```shell
Failed: Error occurred: AzureException - Error code: 400 - {'error': {'message': 'Unrecognized request argument supplied: logprobs', 'type': 'invalid_request_error', 'param': None, 'code': None}}
```

**Comment by ishaan-jaff** [comment]
for this issue will just address logprobs for OpenAI

**Comment by ishaan-jaff** [comment]
marking this as completed - we support logprobs for openai, openai w streaming now 

Azure has not yet rolled out logprobs support for gpt-3.5, gpt-4

**Comment by ghost** [comment]
@ishaan-jaff Can you confirm that's true for the latest api version? I've noticed azure has different functionality based on version
