### ISSUE TITLE
print `pip install litellm[proxy]` if user is trying to run litellm proxy without installing dependencies

### ISSUE THREAD

**Issue by Huge** [BerriAI/litellm#1206]
So if you `pip install litellm`, without the `litellm[proxy]` you still get the in `litellm` commnad in `somewhere/bin`, but you can not use it for anything. That seems incoherent.

**Comment by ghost** [comment]
what should the expected behaviour here be @Huge ?

**Comment by Huge** [comment]
I believe the bin/litellm should simply not be created, although possibly more practical would be to have it just one line that prints out that for the command to work `pip install llitellm[proxy]` is needed.

**Comment by ghost** [comment]
oh! i like that. That seems helpful. cc: @ishaan-jaff this is neat!

**Comment by ishaan-jaff** [comment]
just tried to repro this on a replit and I didn't run into any errors, litellm began install the dependencies missing 

- I ran `pip install litellm`
- `litellm --model gpt-3.5-turbo` 

<img width="494" alt="Screenshot 2023-12-26 at 8 34 17 AM" src="https://github.com/BerriAI/litellm/assets/29436595/a3903714-45fd-468b-abc9-36edfe72e224">

@Huge what error did you run into ?

**Comment by ishaan-jaff** [comment]
perhaps the action item here is to just raise that users need to run `pip install litellm[proxy]` instead of auto-installing for them ? 
cc @krrishdholakia 

(I prefer that it auto-installs so I don't need to constantly run pip installs)

**Comment by ghost** [comment]
^ the auto-install seems more convenient. @Huge did the auto-install not run? I'm assuming there was some sort of stacktrace - what did it say?

**Comment by ishaan-jaff** [comment]
perhaps what we can do is print run `pip install litellm[proxy]` in red before auto-installing

**Comment by bufferoverflow** [comment]
I would rather suggest to change https://github.com/BerriAI/litellm/blob/main/README.md?plain=1#L45

```diff
-pip install litellm[proxy]
+pip install litellm        # Install the client library
+pip install litellm[proxy] # Install the LiteLLM proxy
```

and remove the sub process call here completely: https://github.com/BerriAI/litellm/blob/main/litellm/proxy/proxy_server.py#L26-L39

**Comment by ishaan-jaff** [comment]
@bufferoverflow any reason why you want to remove the subprocess call completely ?

**Comment by bufferoverflow** [comment]
@ishaan-jaff I think dependencies are already managed via poetry and should not be installed afterwards using pip with sub process calls. People could install using `pip install litellm[proxy]` or use the litellm container image. Somehow I do not feel comfortable with applications that are calling the package manger by themself using subprocess, also security wise.

**Comment by ghost** [comment]
That's good feedback @bufferoverflow, thanks for that!

**Comment by ishaan-jaff** [comment]
done - we don't auto install packages on the proxy now, we tell users to `pip install litellm[proxy]` 

https://github.com/BerriAI/litellm/commit/af15e49948285fa2fa01aa31843b41a3fabc5111

**Comment by ishaan-jaff** [comment]
@Huge @bufferoverflow feel free to re-open this issue if you have any feedback

**Comment by bufferoverflow** [comment]
awesome ! thanks @ishaan-jaff !
