### ISSUE TITLE
[Feature]: Support new anthropic messages endpoint

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1209]
### The Feature

Anthropic has a new messages endpoint - https://docs.anthropic.com/claude/reference/messages_post

<img width="713" alt="Screenshot 2023-12-21 at 11 50 28 AM" src="https://github.com/BerriAI/litellm/assets/17561003/f916fd68-63cc-425d-8834-d93a422a106e">

### Motivation, pitch

I'm pretty sure this is how they're going to expose function calling 
<img width="691" alt="Screenshot 2023-12-21 at 11 50 59 AM" src="https://github.com/BerriAI/litellm/assets/17561003/8f76e43f-de70-4d96-8213-70355e75fcf2">

**Comment by ishaan-jaff** [comment]
supported by us
