### ISSUE TITLE
huggingface - scaling to zero 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#121]
Our public huggingface endpoint was set to 'scale to zero' after 15 minutes of inactivity. But this also means that when a user tests it out - it'll fail for a while due to the inactivity 

<img width="991" alt="Screenshot 2023-08-15 at 11 36 44 AM" src="https://github.com/BerriAI/litellm/assets/17561003/b115c4af-e99c-4229-93cb-485f9abeb636">

**Comment by ghost** [comment]
no-op
