### ISSUE TITLE
[Feature]: allow setting num retries / request

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1210]
### The Feature

"like if I give a bad request, and it fails on the first x number of endpoints, there's no need to try them all"
e.g. failing on 3 endpoints is just as good as failing on all 9 endpoints

### Motivation, pitch

User Request cc: @Manouchehri

**Comment by ghost** [comment]
This is now supported - https://github.com/BerriAI/litellm/commit/e516cfe9f5d7d9405ff9b476ef6493e7a4cb5657. Out in v`1.15.10`. 

```
litellm_settings: 
   num_retries_per_request: 0
```
