### ISSUE TITLE
[Feature]: Support function calling on gemini-pro 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1214]
### The Feature

gemini-pro supports function calling, so we should support it 

### Motivation, pitch

improve user experience

**Comment by phact** [comment]
I've been trying your function calling prompt with gemini and it work quite well. It would be cool to compare it with their official function calliung API.

**Comment by ghost** [comment]
Thanks @phact, moving to theirs would mean we could guarantee response format and so output parse it to be in the openai function calling format (we currently return response in content)

**Comment by ghost** [comment]
just pushed - https://github.com/BerriAI/litellm/commit/86403cd14eb2247b8f4d3576e3b6f0660a67a79d. Should be live in v`1.16.4`.
