### ISSUE TITLE
[Feature]: Cache - Allow users to set time to live, invalidate cache on the router 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1218]
### The Feature

- Proxy Caching implementation needs to be improved:
    - Wants a time to live on cache for the proxy
    - Invalidate / purge the cache
- Look at vercel caching docs → pass via headers https://vercel.com/docs/edge-network/caching

### Motivation, pitch

user request

**Comment by ghost** [comment]
Updating to be on router, as user said they wouldn't mind just using it on the client sdk

**Comment by ghost** [comment]
i like helicone's approach to this, it's pretty clean: https://docs.helicone.ai/features/advanced-usage/caching#quick-start

**Comment by ghost** [comment]
Going through how Vercel uses Cache-Control headers, documenting exposed functionality: 

Functionality listed in mozilla docs - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#cache_directives


- **max-age**: indicates how long response remains 'fresh' until N seconds after response is generated
- **must-revalidate**: it's a flag. Response can be cached, but if stale, get new response and update cache. 
- ~~max-stale:~~ not supported by major browsers
- ~~min-fresh:~~ not supported by major browsers
- only-if-cached: if a cache has a stored response, even a stale one, it will be returned. Else 504 gateway timeout error
- no-cache: it stores the value in cache, but requires you to still call the backend server and check your cached response against the server value each time 
- no-store: means 'don't cache' 
- no-transform: don't modify the content (e.g. reduce image size). 
- only-if-caches
- stale-if-error: use stale response if an error occurred. Contains the number of days in seconds this can be done for. 
- stale-while-revalidate: cache can use a stale response, while it revalidates it to a cache. Contains the number of days in seconds, this can be done for. 
- no-cache: validate response with origin server before reuse (i guess this means, you can store the cache but still need to make a call to the backend servers and return the fresh response) 
-

**Comment by ghost** [comment]
~~Vercel seems to have taken the ideas from mozilla's cache control docs and added their own custom params e.g. `s-max-age`.~~

They took their flags variables from the cloudflare directives - https://developers.cloudflare.com/cache/concepts/cache-control/#cache-control-directives

**Comment by ghost** [comment]
## for proxy 
I think this would basically be solved by accepting an `s-max-age` flag in the proxy headers 

## for router 
i think if we just accepted ttl in the client wrapper, this would solve the problem

**Comment by ghost** [comment]
looks like we already so support a ttl param in caching.py

Will run some tests for this.

**Comment by ghost** [comment]
we now support ttl for completion, embedding, img gen calls (incl. router) https://github.com/BerriAI/litellm/commit/f0b6b9dce2a88cb2189758ae5a5120ae8b2ce499

**Comment by ghost** [comment]
we now also support `s-max-age` as a cache-control param for the proxy 

```javascript

const { OpenAI } = require('openai');

const openai = new OpenAI({
  apiKey: "sk-1234", // This is the default and can be omitted
  baseURL: "http://0.0.0.0:8000"
});

async function main() {
  const chatCompletion = await openai.chat.completions.create({
    messages: [{ role: 'user', content: 'Say this is a test' }],
    model: 'gpt-3.5-turbo',
  }, {"headers": {
    "Cache-Control": "s-maxage=0" // 👈 sets ttl=0
  }});
}

main();
```

**Comment by prd-tuong-nguyen** [comment]
@krrishdholakia Hi guy, can I turn off the cache by default and turn on it per request?
when I set `cache=false` in the config and pass `cache: {"ttl": 600}` in the request's body => the cache still not hit
when I set `cache=true` in the config, all requests will be cached
so is there any way that I can turn off the cache by default and just cache some specific request?

**Comment by ghost** [comment]
@prd-tuong-nguyen how would you want to set this up on the config?

**Comment by ghost** [comment]
we let you disable cache per request

not sure what turning it on looks like

**Comment by prd-tuong-nguyen** [comment]
I hope that I can turn off the cache for all requests, except for some requests with `cache: {"ttl": 600 }`. In the config, maybe we need another field called `cache_all_requests: bool` to decide whether the proxy will cache all requests or only specific ones. It's just my idea, bro.

**Comment by ghost** [comment]
interesting - why do you want to do it this way? @prd-tuong-nguyen

**Comment by prd-tuong-nguyen** [comment]
@krrishdholakia In our case, we still need to keep the various LLM responses for almost all requests. In a few cases, we need to cache and ensure consistent responses.

Hey, maybe I've found a way to do that. I will set the default cache TTL to 0 in the config to disable caching and pass the cache TTL per request to enable it.

**Comment by langgg0511** [comment]
I hope to set a unified cache disabling feature for the virtual key, so that I don't have to set "cache": {"no-cache": True} every time I use this key.

**Comment by ghost** [comment]
@langgg0511 you can set it on the key metadata already - https://docs.litellm.ai/docs/proxy/caching#turn-on--off-caching-per-key

**Comment by langgg0511** [comment]
@krrishdholakia thanks
