### ISSUE TITLE
[Bug]: Ollama Proxy

### ISSUE THREAD

**Issue by syaikhipin** [BerriAI/litellm#1221]
### What happened?

A bug happened!, I try to run custom model litellm --model=ollama/phi --api_base=http://llm.arifin.uk/ --port 9000 --debug
INFO:     Started server process [115860]
INFO:     Waiting for application startup.

And run this stuff :  curl --location 'http://localhost:9000/chat/completions' \
--header 'Content-Type: application/json' \
--data ' {
      "model": "phi",
      "messages": [
        {
          "role": "user",
          "content": "what llm are you"
        }
      ],
    }
'
{"detail":"Expecting property name enclosed in double quotes: line 9 column 5 (char 144)\n\nTraceback (most recent call last):\n  File \"/home/llm/.local/lib/python3.8/site-packages/litellm/proxy/proxy_server.py\", line 955, in chat_completion\n    data = await request.json() # type: ignore\n  File \"/home/llm/.local/lib/python3.8/site-packages/starlette/requests.py\", line 244, in json\n    self._json = json.loads(body)\n  File \"/usr/lib/python3.8/json/__init__.py\", line 357, in loads\n    return _default_decoder.decode(s)\n  File \"/usr/lib/python3.8/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/usr/lib/python3.8/json/decoder.py\", line 353, in raw_decode\n    obj, end = self.scan_once(s, idx)\njson.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 9 column 5 (char 144)\n"}%  

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/llm/.local/lib/python3.8/site-packages/litellm/proxy/proxy_server.py", line 955, in chat_completion
    data = await request.json() # type: ignore
  File "/home/llm/.local/lib/python3.8/site-packages/starlette/requests.py", line 244, in json
    self._json = json.loads(body)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 9 column 5 (char 144)
```

**Comment by ghost** [comment]
Hey @syaikhipin you had a misformatted curl request. No worries, just pushed a fix to handle that - https://github.com/BerriAI/litellm/commit/979575a2a6d9d4338ad46da81360c687cd23c1d0
<img width="161" alt="Screenshot 2023-12-22 at 12 30 49 PM" src="https://github.com/BerriAI/litellm/assets/17561003/76ab988b-346d-4fd4-947f-7863951422f5">
