### ISSUE TITLE
Question on best way to check if provider exists

### ISSUE THREAD

**Issue by davidmezzetti** [BerriAI/litellm#1224]
Hello, thank you for your open source contributions and work on this library!

What is the recommended way to check if a provider exists for a model string? This is the code I have now that works but I'm hoping there is a better way. Perhaps I'm asking for a better way :smile: 

```python
import contextlib
import os
import litellm as api

# pylint: disable=W0702
with open(os.devnull, "w", encoding="utf-8") as f, contextlib.redirect_stdout(f):
  try:
    return api.get_llm_provider(path)
  except:
    return False
```

I'm redirecting stdout to devnull because I can't find a way to check for a provider without it printing message with a link to the provider lists to stdout, i.e.

```
Provider List: https://docs.litellm.ai/docs/providers
```

**Comment by ghost** [comment]
Hey @davidmezzetti we have a module level variable called `provider_list` 

I believe in your code it work work if you just did

```python
import litellm as api

print(api.provider_list) 
```

Curious - what do you use this for?

**Comment by davidmezzetti** [comment]
Thank you for the response @krrishdholakia.

I'm looking to test if a model string can be instantiated by LiteLLM. I'm using this in txtai to create a LLM instance. txtai has a number of methods to create a LLM including local through Hugging Face, llama.cpp and LiteLLM.

I'd like to do more than just check the prefix and go through the logic in `get_llm_provider`. This currently works, the only issue is the print when it can't find a model.

https://github.com/BerriAI/litellm/blob/main/litellm/utils.py#L3089

Perhaps this could instead be a standard logging message?

**Comment by ishaan-jaff** [comment]
@davidmezzetti if you set `litellm.suppress_debug_info=True` it should not print this information. Would that solve your issue ?

**Comment by davidmezzetti** [comment]
Hi @ishaan-jaff, thanks for responding. This works for v1.15.8. For reference, this is what I did.

```python
debug = litellm.suppress_debug_info
try:
  # Suppress debug messages for this test
  litellm.suppress_debug_info = True
  return litellm.get_llm_provider(path)
except:
  return False
finally:
  # Restore debug info value to original value
  litellm.suppress_debug_info = debug
```

Ideally, I'd be able to set logging/debug at the module level but I can work with this. Appreciate the help! Best of luck with LiteLLM.
