### ISSUE TITLE
[Feature]: Add safety setting feature for PaLM model

### ISSUE THREAD

**Issue by tikendraw** [BerriAI/litellm#1227]
### The Feature

There is a safety setting in [google.generativeai](https://github.com/google/generative-ai-python/blob/main/google/generativeai/types/safety_types.py) api. Add Add saftey settings as optional parameters to the Palm config class. 

### Motivation, pitch

To add safety checks.

**Comment by motin** [comment]
I think this already works and has been working for quite some time. If you add the safety_settings kwarg to the completion() function when using a palm model, it will be forwarded to Palm Config by this line: https://github.com/BerriAI/litellm/blob/d90e04b531692dcb8672909f526c234d0f828595/litellm/llms/palm.py#L119

**Comment by ghost** [comment]
closing as this is resolved then?

**Comment by ghost** [comment]
Although i do believe we could have better docs on this. 

@tikendraw @motin we'd welcome a doc contribution here

**Comment by ghost** [comment]
if you can share a working code snippet i can add it to the docs - https://docs.litellm.ai/docs/providers/palm
