### ISSUE TITLE
[Bug]: migrate router to use model id instead of model name

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1228]
### What happened?

In some places in router.py we're still using model_name or some version of it, to identify deployments. This isn't unique enough (multiple deployments can have the same model name). Now that we have an id for each deployment, we should migrate to using that consistently across router.py 

### Relevant log output

```shell
e.g.: 

`self.deployment_latency_map[model_name] = (end_time - start_time).total_seconds()`
```

**Comment by ghost** [comment]
closing as this is now done for all the routing logic.
