### ISSUE TITLE
[Feature]: virtual keys without time limits 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1229]
### The Feature

allow creating virtual keys without time limits on the proxy 

### Motivation, pitch

user request

**Comment by ghost** [comment]
Turns out we already support tokens that don't expire. I'll make this more clear in the docs. 

<img width="858" alt="Screenshot 2023-12-25 at 10 33 08 AM" src="https://github.com/BerriAI/litellm/assets/17561003/e4a3ed04-2ec4-4aef-9abf-e2ba133ed66d">

**Comment by ghost** [comment]
added to docs - https://docs.litellm.ai/docs/proxy/virtual_keys#keys-that-dont-expire
