### ISSUE TITLE
(feat) load test - show me logs of questions +handle slow responses

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#123]
Trying to use load test but i need to see the responses that actually came in. I need to see the responses to know if there were actually 0 errors 

<img width="1229" alt="Screenshot 2023-08-15 at 2 33 24 PM" src="https://github.com/BerriAI/litellm/assets/29436595/f07d7b5d-613e-452c-b7df-3ca335a102d7">

**Comment by ishaan-jaff** [comment]
cc @krrishdholakia

**Comment by ghost** [comment]
writing the notebook for this right now, and i realize that load / reliability testing feels weird for this core I/O package to handle, but does make sense as an integration - like berri spend

**Comment by ishaan-jaff** [comment]
marking this as done: https://github.com/BerriAI/litellm/blob/main/cookbook/Evaluating_LLMs.ipynb
