### ISSUE TITLE
[Feature]: proxy management ui v1 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1231]
### The Feature

Enable users to create virtual keys through a simple ui 

### Motivation, pitch

user request

**Comment by ghost** [comment]
Min requirements: 
- [ ] admin can set default budget for users
- [ ] auth users (Google/Github auth is fine), do not let them just type in their email.
- [ ] user should be able to create a key to call proxy

**Comment by ghost** [comment]
What makes a good management interface? 
- Not working in git to make changes to the proxy -> add model + rotate key.
- If a user's having trouble - e.g. key doesn't work -> they can just go and make a new one, or increase their budget 
- User can just go to the proxy -> see the current models they have -> click request key -> user now has a key -> it's their job to keep it safe

"You can use this for anything: use it with langchain, rust, java, etc." 


Entire thing becomes self-serve: user shows up, logs in, gets the key, sees how it works, goes off and has fun.

**Comment by ghost** [comment]
There **would** be a budget for that key <- cost management is super important, this lets admins allow people to try all the models without being worried about unexpected high costs.

**Comment by ghost** [comment]
Admin setup step: 
- master key 
- proxy url 
- default budget 
- default models ??

**Comment by ghost** [comment]
^ I wonder if default models is a p0, if you have default budget.

**Comment by ghost** [comment]
V1 (user feedback): 
- someone sets up a key, a proxy url, a budget and a model list 
- and then someone else can come and click generate + delete key.

**Comment by ghost** [comment]
## Implementation thinking 

- Admin can put in the initial proxy url (e.g. `http://0.0.0.0:8000`) 
- We can then hash this 
- Append the hash to the ui url (e.g. `http://0.0.0.0:4000/b263a6c4f34a2d3bb2c31796d1a18b2f`) -> this is now the publicly accessible url that users can use to create keys, etc. 
- ~~we can add a way for the proxy to confirm if master key hash == url hash~~

**Comment by ghost** [comment]
wonder if it might be more convenient if we host this 🤔 (e.g. `https://api.litellm.ai/b263a6c4f34a2d3bb2c31796d1a18b2f`)

**Comment by ghost** [comment]
v1
<img width="1018" alt="Screenshot 2023-12-23 at 2 15 58 PM" src="https://github.com/BerriAI/litellm/assets/17561003/e067b385-7d7b-4ff9-b2f9-70ead2a0e4f3">

**Comment by ghost** [comment]
## More thoughts 

my main concern is that if the ui url leaks, anyone can create a key to use these models. 

We could potentially deal with this by allowing admins to specify an accepted subdomain, and use passwordless-auth to make sure emails with the accepted subdomains are actually valid and owned by the user logging in (they have to click on a link sent to their email, to log in).

**Comment by ghost** [comment]
Breaking this down into steps: 
- [x] Auth page - Working passwordless auth (i provide my email -> get a magic link -> redirected to create key page) -> https://github.com/BerriAI/litellm/commit/abcd7cf54fa1cf321bf2d7aec9ef14e71119679b
- [x] Admin page - admin sets proxy url + accepted email subdomain -> https://github.com/BerriAI/litellm/commit/adfcbd90387a8381ce5698402c9b826e113d4ec0, https://github.com/BerriAI/litellm/commit/8c6d11ea07d0fbd45921fd410c1001425a21b621, https://github.com/BerriAI/litellm/commit/1bfab8732330c483c95cfbe88912802a3d49308d
- [ ] User page - Auth'ed User can create key for proxy

**Comment by ghost** [comment]
Initial commit made for the admin page - https://github.com/BerriAI/litellm/commit/adfcbd90387a8381ce5698402c9b826e113d4ec0

This will also require the proxy to expose a way to modify the config.yaml (why? -> to store the accepted email subdomain -> where is this needed? -> we will need this on the ui to know if an email is allowed or not) 

## idea 1: store in config.yaml -> read from proxy server
- if we need the config.yaml to be consistent across multiple workers, this will also mean we need the config.yaml to be stored on a db 


## idea 2: hash the proxy url + accepted subdomain - read from url on user-auth page
- admin puts in email + proxy url - e.g. `example.com` and `http://0.0.0.0:8000`  -> combine into 1 hash: `proxy_url=<>;accepted_email_subdomain=<>`
- user goes to `https://api.litellm.ai/b263a6c4f34a2` -> logs in 
- user page knows what url to call `/key/generate` on



Idea 2 seems simpler (no db/config changes), let's do that.

**Comment by ghost** [comment]
admin page v2 now pushed - https://github.com/BerriAI/litellm/commit/8c6d11ea07d0fbd45921fd410c1001425a21b621
<img width="873" alt="Screenshot 2023-12-23 at 4 04 19 PM" src="https://github.com/BerriAI/litellm/assets/17561003/03f450e9-7299-4957-b4d9-42b43d1e324d">

**Comment by ghost** [comment]
v3 now has functional routing between the admin page -> auth page https://github.com/BerriAI/litellm/commit/1bfab8732330c483c95cfbe88912802a3d49308d

**Comment by ghost** [comment]
v4 now adds redirect urls to the magic link - https://github.com/BerriAI/litellm/commit/189fcc09342e74bd53f41cc7be949e18a03549e9

**Comment by ghost** [comment]
Pausing on this for today, will pick up on Monday  - i'd like to get a hosted demo set up so we can share it with users for feedback.

**Comment by ghost** [comment]
## User Page

User needs to be able to create / delete keys 

Currently any key related request, requires the master key. We need to: 
 - let auth'ed users create their own keys (if user exists in table, and has a valid token let them hit `/key/generate`).
 - let auth'ed users delete their own keys (if user exists in table, and has valid token let them hit `/key/delete`). 

### Open Questions 

User -> UI -> Server 

How do we give the user a valid server token, they can use to talk to the proxy? 
- Could replace Supabase Auth with just an email endpoint that uses resend - `/user/auth` -> rate limit (oncer every 60s)
- the endpoint generates a secure token_hash (maybe use the master key for signing it)  -> (valid for 24 hrs) 
- sends the hash in a link to the user 
- User clicks on link in email 
- UI now has the token hash, it can use to send requests to server

**Comment by ghost** [comment]
closing as v1 is now released - https://dashboard.litellm.ai/
