### ISSUE TITLE
how to use vertex gemini with Proxy?

### ISSUE THREAD

**Issue by tgyy1995** [BerriAI/litellm#1232]

**Comment by ghost** [comment]
Hey @tgyy1995, do you have vertex ai credentials stored in your server?

**Comment by ghost** [comment]
you'll need to store your credentials like this
<img width="947" alt="Screenshot 2023-12-23 at 5 44 41 PM" src="https://github.com/BerriAI/litellm/assets/17561003/fe3034f1-e943-4c66-b537-b2b2da88879f">

**Comment by tgyy1995** [comment]
Yes, I have already set up the credentials.
But I don't know how to use Gemini in this way. For example,  litellm --model huggingface/bigcode/starcoder.

**Comment by hongliang-wei** [comment]
I can use Gemini in this way:

```
from litellm import completion
import os
# auth: run 'gcloud auth application-default'
os.environ["VERTEX_PROJECT"] = "hardy-device-386718"
os.environ["VERTEX_LOCATION"] = "us-central1"
response = completion(
  model="chat-bison", 
  messages=[{ "content": "Hello, how are you?","role": "user"}]
)
```

But I want to use Gemini in this way and i dont kown how. For example, `litellm --model huggingface/bigcode/starcoder`.
How should I set up VERTEX_PROJECT and VERTEX_LOCATION?

**Comment by ghost** [comment]
Do this in your terminal before running the liteLLM command. 
```
export VERTEX_PROJECT="hardy-project"
export VERTEX_LOCATION="us-west"
```

**Comment by hongliang-wei** [comment]
Thank you.

**Comment by ishaan-jaff** [comment]
<img width="708" alt="Screenshot 2023-12-27 at 5 15 48 PM" src="https://github.com/BerriAI/litellm/assets/29436595/be607fa9-ab28-4662-9b6f-8cdaf6c7a43f">

@tgyy1995 added docs on how to do this too: https://docs.litellm.ai/docs/providers/vertex#gemini-pro

**Comment by ishaan-jaff** [comment]
@tgyy1995 what are you using the LiteLLM proxy for ?

**Comment by hongliang-wei** [comment]
Thank you for your work. I can now use Gemini. I use Litellm for autogen.
