### ISSUE TITLE
[Bug]: docker-compose up does not work with out-of-date main and latest images

### ISSUE THREAD

**Issue by dkondoetsy** [BerriAI/litellm#1233]
### What happened?

With `image: ghcr.io/berriai/litellm:main` in the [docker compose yaml file](https://github.com/BerriAI/litellm/blob/main/docker-compose.example.yml),
`docker-compose -f docker-compose-litellm.yml up` fails with:

```
raise OpenAIError(openai.OpenAIError: Missing credentials. Please pass one of `api_key`, `azure_ad_token`, `azure_ad_token_provider`, or the `AZURE_OPENAI_API_KEY` or `AZURE_OPENAI_
AD_TOKEN` environment variables.
```
even though my litellm config specifies a key.

An error also occurs with `image: ghcr.io/berriai/litellm:latest`

If I change the image to `ghcr.io/berriai/litellm:main-v1.15.3`, then docker-compose up works.

The `main` and `latest` images look old.  So maybe latest should be updated on each release?

**Comment by ghost** [comment]
@dkondoetsy thanks for flagging this. cc: @ishaan-jaff / @Rested, i believe the PR https://github.com/BerriAI/litellm/pull/1197 added auto-deploy on gh releases, perhaps a better way would be to do it on pypi publish (already auto-triggered + passes through ci/cd testing). 


I would assume this is where the change needs to be made - https://github.com/BerriAI/litellm/blob/main/.circleci/config.yml

**Comment by ishaan-jaff** [comment]
Added code to update the ghcr docker image for every new pypi release: 
https://github.com/BerriAI/litellm/commit/157b21c5918ccc3bfb9d462ff80184261d2b7dc3 

cc @dkondoetsy, this will ensure the ghcr container is always on the latest version of litellm

**Comment by ishaan-jaff** [comment]
closing this issue since it's completed, we now auto deploy to ghcr after passing ci/cd 

feel free to re-open @dkondoetsy

**Comment by dkondoetsy** [comment]
Awesome, thank you so much Ishaan.

**Comment by RodolfoCastanheira** [comment]
had exactly the same problem today

**Comment by FilJed** [comment]
> had exactly the same problem today

Double this. 
main-v1.15.3 is still working though.

**Comment by chymian** [comment]
@ishaan-jaff 
+1

I used the latest docker image 1.23.9
encountered this error:
```
openai.OpenAIError: Missing credentials. Please pass one of `api_key`, `azure_ad_token`, `azure_ad_token_provider`, or the `AZURE_OPENAI_API_KEY` or `AZURE_OPENAI_AD_TOKEN` environment variables
```
the proxy config has dummy keys configured for every entry (ollama & openai -> ooboga's)

it is working with 1.23.9, using this simple Dockerfile:
```
FROM python:3.11

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

RUN pip install -U pip && \
                pip install --break-system-packages litellm[proxy] && \
                pip cache purge

COPY start.sh /start.sh

EXPOSE 8000
ENTRYPOINT [ "/bin/bash", "/start.sh" ]
```
that let me assume, someting with the provided image is nok?
