### ISSUE TITLE
[Feature]: Support Google Cloud KMS for managing encryption keys

### ISSUE THREAD

**Issue by dkondoetsy** [BerriAI/litellm#1235]
### The Feature

Support Google Cloud KMS for managing encryption keys.

### Motivation, pitch

Deploying litellm on GCP/GKE with virtual keys enabled requires Postgres [via CloudSQL].  This in turn requires a secure way of managing [Postgres] encryption keys with Google Cloud KMS.

**Comment by ghost** [comment]
Hi @dkondoetsy i can do this today. Will DM you on linkedin once it's out, for feedback.

**Comment by ghost** [comment]
Hey @dkondoetsy going through CloudSQL docs now. Checking my understanding: 

- you're using Google Cloud KMS for encrypting data stored in the CloudSQL db 

Isn't this process handled by CloudSQL? How would your application code change here?

**Comment by dkondoetsy** [comment]
The idea would be to decrypt the [postgres] credentials using [google.cloud.kms.KeyManagementServiceClient.decrypt()](https://cloud.google.com/python/docs/reference/cloudkms/latest/google.cloud.kms_v1.services.key_management_service.KeyManagementServiceClient#google_cloud_kms_v1_services_key_management_service_KeyManagementServiceClient_decrypt), passing a key name and cipher.  We might need a way to specify the key name and cipher text in the config to create the request passed to `decrypt()`.  I can try to submit a PR for this if you'd like after I get back from vacation.

**Comment by ghost** [comment]
adding a mock code snippet for reference 

```python
from google.cloud import kms_v1

# Create the KMS client
client = kms_v1.KeyManagementServiceClient()

# The resource name of the CryptoKeyVersion. It's in the form
# projects/*/locations/*/keyRings/*/cryptoKeys/*/cryptoKeyVersions/*
name = 'projects/my-project/locations/my-location/keyRings/my-key-ring/cryptoKeys/my-key/cryptoKeyVersions/my-version'

# The encrypted payload, likely received as a ciphertext blob
# For example, from an environment variable, secret store, etc.
ciphertext_blob = b"..."

# Use the KMS client to decrypt the database secret
response = client.decrypt(request={'name': name, 'ciphertext': ciphertext_blob})

# Plaintext of the response is the decrypted secret (e.g., database password)
plaintext = response.plaintext.decode('utf-8')

# Use the decrypted secret to connect to the database
# Note: Ensure you're handling this securely!
db_password = plaintext
```

**Comment by ghost** [comment]
Hey @dkondoetsy this commit - https://github.com/BerriAI/litellm/commit/2070a785a433c9b3681244b7b097293229fd9291, adds support for Google KMS to the proxy.

Here's how to enable it: 

## Step 1. Add keys to env 
```
export GOOGLE_APPLICATION_CREDENTIALS="/path/to/credentials.json"
export GOOGLE_KMS_RESOURCE_NAME="projects/*/locations/*/keyRings/*/cryptoKeys/*"
export PROXY_DATABASE_URL_ENCRYPTED=b'\n$\x00D\xac\xb4/\x8e\xc...'
```

## Step 2: Update Config

```yaml
general_settings:
  use_google_kms: true
  database_url: "os.environ/PROXY_DATABASE_URL_ENCRYPTED"
  master_key: sk-1234
```

## Step 3: Start + test proxy

```
$ litellm --config /path/to/config.yaml
```

And in another terminal
```
$ litellm --test 
```

**Comment by ghost** [comment]
Let me know if this solves your problem, well

**Comment by dkondoetsy** [comment]
Thank you very much.  PR looks great.  I added a new minor comments.

**Comment by ghost** [comment]
Yes - tracking them in a separate issue.

**Comment by ghost** [comment]
closing as this is now live.
