### ISSUE TITLE
[Bug]: proxy - bedrock streaming hangs 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1239]
### What happened?

when running streaming with bedrock, the chunks come instantly on litellm but do not get sent to the client side instantly.

Repro this by sending a request to bedrock + stream on the proxy 

### Relevant log output

```shell
-
```

**Comment by ghost** [comment]
this is a serious issue, but i'm unable to repro this on my end. @ishaan-jaff are you working on this?

**Comment by ghost** [comment]
@ishaan-jaff bump on this?

**Comment by ghost** [comment]
I was unable to repro this issue on my system

**Comment by daikeren** [comment]
I think maybe it's because in Bedrock's async implementation, streaming is blocking when called within a thread, so it waits until all streams are generated then returning them all at once.

Here's some code for testing

```python
from litellm import acompletion
import asyncio, traceback

async def completion_call(model: str, num: int):
    try:
        print(f"test acompletion + streaming with {model}")
        response = await acompletion(
            model=model,
            messages=[
                {
                    "content": "How to use FastAPI to write a REST API Server?",
                    "role": "user",
                }
            ],
            stream=True,
            max_tokens=512,
        )
        print(f"response: {response}")
        async for chunk in response:
            print(num)
    except:
        print(f"error occurred: {traceback.format_exc()}")
        pass

async def run():
    await asyncio.gather(
        completion_call("bedrock/anthropic.claude-v2:1", 1),
        completion_call("bedrock/anthropic.claude-v2:1", 2),
        completion_call("bedrock/anthropic.claude-v2:1", 3),
    )

asyncio.run(run())
```

The output
```
test acompletion + streaming with bedrock/anthropic.claude-v2:1
test acompletion + streaming with bedrock/anthropic.claude-v2:1
test acompletion + streaming with bedrock/anthropic.claude-v2:1
response: <litellm.utils.CustomStreamWrapper object at 0x11587f450>
3
3
3
3
3
3
3
3
3
3
response: <litellm.utils.CustomStreamWrapper object at 0x11485dcd0>
2
2
2
2
2
2
2
2
2
response: <litellm.utils.CustomStreamWrapper object at 0x11481bbd0>
1
1
1
1
1
1
1
1
```

**Comment by ghost** [comment]
To solve this, we'd probably need to use our own async bedrock implementation, as boto3 doesn't support that yet.

**Comment by daikeren** [comment]
Maybe package like [aioboto3](https://pypi.org/project/aioboto3/) could solve this. Seems that [aioboto3 has already supported bedrock after v12.0.0](https://github.com/terrycain/aioboto3/issues/317)

**Comment by ghost** [comment]
I wonder if we could do something similar to this - https://github.com/openai/openai-python/blob/f1c7d714914e3321ca2e72839fe2d132a8646e7f/src/openai/lib/azure.py#L63

Where we have a custom class on top of the openai python baseclient class (that's the one that handles all the async connection opening/closing etc.). 

Benefit would be that it's not a new dependency (vs. aiboto3).

**Comment by ghost** [comment]
I can try exploring that within the scope of https://github.com/BerriAI/litellm/issues/1040

Since cloudflare bedrock support requires changing the url

**Comment by ghost** [comment]
closing as @ishaan-jaff i believed you solved this with the sync streaming support

**Comment by Lunik** [comment]
I'm still experiencing this issue.

Chunck arrives in Litellm (I can see them in verbose output) but sent in group to the client.

I have tested it using the following Proxy config :
```yaml
    model_list:
        - model_name: claude-3
          litellm_params:
            model: bedrock/anthropic.claude-3-sonnet-20240229-v1:0
            aws_access_key_id: "os.environ/AWS_ACCESS_KEY_ID"
            aws_secret_access_key: "os.environ/AWS_SECRET_ACCESS_KEY"
            aws_region_name: "eu-west-3"
            aws_bedrock_runtime_endpoint: https://xxxxxxxxxx.bedrock-runtime.eu-west-3.vpce.amazonaws.com
```

And the following cURL command : 
```bash
curl --location 'https://litellm.example.org/chat/completions' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer sk-12345' \
--data ' {
      "stream": true,
      "model": "claude-3",
      "messages": [
        {
          "role": "user",
          "content": "Tell me a long story about the roman empire"
        }
      ]
    }
'
```

**Comment by ghost** [comment]
going to try and repro this on my end today @Lunik

**Comment by ghost** [comment]
@Lunik which version are you on? We recently moved to async bedrock support. I'm also unable to repro the hang when running this via postman 

<img width="1197" alt="Screenshot 2024-05-21 at 11 13 40 AM" src="https://github.com/BerriAI/litellm/assets/17561003/8e5903f5-51da-4628-8d4a-dbeaf4a7bab1">

**Comment by ghost** [comment]
I also ran a script locally to test with streaming - i see a time to first token as '0.2ms' 
<img width="1505" alt="Screenshot 2024-05-21 at 11 28 56 AM" src="https://github.com/BerriAI/litellm/assets/17561003/179e4a82-ed43-48d3-be8e-cda7eca5a946">

My script: 

```python
import openai, time

client = openai.OpenAI(
    base_url="http://0.0.0.0:4000",
    api_key="sk-1234"
)


completion = client.chat.completions.create(
  model="claude-3",
  messages=[
    {"role": "user", "content": "Hello!"}
  ],
  stream=True
)

start_time = time.time()
print(f"start_time: {start_time}")
first_chunk = False
for chunk in completion: 
    if first_chunk == False: 
        first_chunk_time = time.time()
        print(f"First chunk received: {first_chunk_time}")
        print(f"First chunk received latency: {round(first_chunk_time - start_time, 5)}")
        first_chunk = True
    print(f"chunk: {chunk}")
```

**Comment by Lunik** [comment]
V1.37.16 with #3708 fixed it
