### ISSUE TITLE
Create abstraction for OpenAI POST url requests too 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#124]
Several users directly post to 
```python
 requests.post(
    url=CHAT_GPT_URL,
    json=json_dict,
    headers={'Authorization': 'Bearer ' + OPENAI_API_KEY.get(),
             'Content-Type': 'application/json'})
```

We change their entire code structure when they use litellm

We should support something like this - allowing them to call multiple diff providers

```python
 requests.post(
    url=litellm.get_url(model),
    json=litellm.get_inputs(dict, model),
    headers={'Authorization': 'Bearer ' +litellm.get_key(model),
             'Content-Type': 'application/json'})
```

**Comment by ishaan-jaff** [comment]
Open to thoughts on this - would love to get feedback on how to make this elegant

**Comment by zakhar-kogan** [comment]
Yeah, something drop-in/seamless looks awesome
And maybe something like message dict auto-converter to bring them to the unified format for all the LLMs litellm calls?
