### ISSUE TITLE
[Feature]: OpenAI Responses - support dict access and object access 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1241]
### The Feature

For streaming & non streaming responses we don't support accessing the responses using dict & object access 

## For this issue both of these should work
```python
response.choices[0].logprobs["content"][0]["top_logprobs"]
```
```python
response.choices[0].logprobs.content[0].top_logprobs
```

### Motivation, pitch

-

**Comment by ghost** [comment]
@ishaan-jaff We could solve this by having a custom pydantic object (like we do for the normal openai responses), which would allow us to set it to be accessible as a dict as well. See ModelResponse for context - https://github.com/BerriAI/litellm/blob/ef074c707a3f745bc4554954ea26518ad355296c/litellm/utils.py#L421

**Comment by edwinjosegeorge** [comment]
Logprobs is now removed after https://github.com/BerriAI/litellm/issues/579 . Rest of the models support dict as well as attribute access. Is this issue still relevant? If not, we might as well close this issue 

@krrishdholakia  @ishaan-jaff

**Comment by ghost** [comment]
yes - we can close this. Thanks for the bump @edwinjosegeorge
