### ISSUE TITLE
[Bug]: some model hangs and an error is returned

### ISSUE THREAD

**Issue by yairVanti** [BerriAI/litellm#1242]
### What happened?

i get on completion api on open source models :
{model} is currently loading.

### Relevant log output

```shell
benchmarking the following models :
models = ["gpt-3.5-turbo", "huggingface/echarlaix/tiny-random-mistral"]

returns error on huggingface model , apparently its not loaded at time.

litellm.exceptions.APIError: HuggingfaceException - response is not in expected format - [{'error': 'Model echarlaix/tiny-random-mistral is currently loading', 'estimated_time': 20.0}]

what can be done to wait until the model is available.
```

**Comment by ishaan-jaff** [comment]
@yairVanti in this case LiteLLM send the request to huggingface and you're seeing hugginface raise the exception

**Comment by ishaan-jaff** [comment]
what would you like litellm to do here?

**Comment by yairVanti** [comment]
i suspect it not really a huggingface model serving issue, but something with the integration or params passed to the API.
tried models i know that are servable.
is litellm trying to download the model and then serve it , like TGI , or is there another way?
if is trying to download, maybe this is why i get the timeout.

**Comment by ishaan-jaff** [comment]
can you run this with `litellm.set_verbose=True` and send the log ?

**Comment by ishaan-jaff** [comment]
> is litellm trying to download the model and then serve it , like TGI , or is there another way?

Nope, litellm is not trying to download your model, it's just making the api call

**Comment by ghost** [comment]
@yairVant The error message is from Huggingface. They're raising an exception as the model is still being loaded, and returning the eta on when it'll be complete. I've faced this a few times with their public inference endpoints. If you don't want to deal with their long cold start times, you could either host a permanent instance or use alternate services like runpod with potentially quicker cold start times. 

<img width="739" alt="Screenshot 2023-12-26 at 9 04 41 PM" src="https://github.com/BerriAI/litellm/assets/17561003/bbc867b3-9d5c-456b-a0bb-1c439f3fba74">

**Comment by ghost** [comment]
I'm closing this issue, as it's **not** litellm related. But @yairVanti if there is a suggestion for a way we could deal with this better, please re-open / make a feature request issue.
