### ISSUE TITLE
[Feature]: Move to a key_management_system enum in config.yaml 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1244]
### The Feature

nit: maybe consider making the setting key_management_system an enum in general_settings and the enum values be "GOOGLE_KMS" and "AZURE_KEY_VAULT". This would make it a bit more extensible for other key management systems in the future, and prevent multiple key management systems from being used at the same time (eg setting use_azure_key_value and use_google_kms to True) [assuming that should be prevented].
Something like:

```python
class ConfigGeneralSettings(LiteLLMBase):
       class Config:
            # when model is serialized as dict, enum values are used
            use_enum_values = True 
       key_management_system: Optional[KeyManagementSystem] = None

@unique        
class KeyManagementSystem(StrEnum):
    GOOGLE_KMS = auto()
    AZURE_KEY_VAULT == auto()
    
    # In the future, IBM_KMS, and other secret management systems etc
```

https://github.com/BerriAI/litellm/commit/2070a785a433c9b3681244b7b097293229fd9291#r135737682

### Motivation, pitch

user request

**Comment by ghost** [comment]
Additional comments: https://github.com/BerriAI/litellm/commit/2070a785a433c9b3681244b7b097293229fd9291#r135738583

**Comment by ghost** [comment]
Pushed - https://github.com/BerriAI/litellm/commit/9ba520cc8b000b8910b503941e4875de6c2fa701

cc: @dkondoetsy
