### ISSUE TITLE
[Feature]: Updating links to docs at various places for updated info

### ISSUE THREAD

**Issue by prateeksachan** [BerriAI/litellm#1247]
### The Feature

Need to find a way to update the docs github links since they contain the commit SHA at the time of commit but the code has got changed since then.

An example: while looking at the anyscale docs, it got linked back to the prices json of around Nov which mentioned the `max_tokens` as `4096` which was outdated. Have pushed a small change https://github.com/BerriAI/litellm/pull/1246 for the just anyscale docs for now.

### Motivation, pitch

Keeping docs updated with the code, since a lot of docs are tied-up with the contents of the repo itself.

**Comment by ghost** [comment]
Hi @prateeksachan - dm'ed via linkedin. 

How're you using litellm today?

**Comment by ghost** [comment]
Also closing this issue as the PR has been merged
