### ISSUE TITLE
Standardize usage of Token / key + accept both 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#125]
we use OPENAI_API_KEY, REPLICATE_API_TOKEN, HF_TOKEN

It's not consistent. 

We should just standardize to always accept 

`PROVIDER_API_KEY -> REPLICATE_API_KEY, HUGGINGFACE_API_KEY , COHERE_API_KEY, BASETEN_API_KEY`

**Comment by ghost** [comment]
i like this - why not just accept that

**Comment by ishaan-jaff** [comment]
done: https://docs.litellm.ai/docs/completion/supported#api-keys
