### ISSUE TITLE
[Feature]: show more information in /health

### ISSUE THREAD

**Issue by liuhetian** [BerriAI/litellm#1252]
### The Feature

when using openai, there are more information could be shown:

```python
response = (
    openai.OpenAI()
    .client
    .chat
    .completions
    .with_raw_response
    .create(
        model=model,
        messages=[{"role":"user", "content":"test"}]
    )
)
response.headers.get('openai-organization')
limit_requests = int(response.headers.get('x-ratelimit-limit-requests'))
limit_tokens = int(response.headers.get('x-ratelimit-limit-tokens'))


int(rep.headers.get('x-ratelimit-remaining-requests'))
int(rep.headers.get('x-ratelimit-remaining-tokens'))
rep.headers.get('x-ratelimit-reset-requests')
rep.headers.get('x-ratelimit-reset-tokens')
```

### Motivation, pitch

want to see more details about the routers

**Comment by ishaan-jaff** [comment]
@liuhetian do you want to see this on the litellm proxy `/health` endpoint ?

**Comment by liuhetian** [comment]
> @liuhetian do you want to see this on the litellm proxy `/health` endpoint ?

Yes, with this information can better monitor whether the rate limit has been reached or is about to be reached. This will be very helpful for some high-concurrency projects (such as mine now) to monitor whether openai_key needs to be increased or decreased.

**Comment by ishaan-jaff** [comment]
this is currently what /health returns, what would be ideal for you for it to return @liuhetian 

```json
{
    "healthy_endpoints": [
        {
            "model": "azure/gpt-35-turbo",
            "api_base": "https://my-endpoint-canada-berri992.openai.azure.com/"
        },
        {
            "model": "azure/gpt-35-turbo",
            "api_base": "https://my-endpoint-europe-berri-992.openai.azure.com/"
        }
    ],
    "unhealthy_endpoints": [
        {
            "model": "azure/gpt-35-turbo",
            "api_base": "https://openai-france-1234.openai.azure.com/"
        }
    ]
}
```

**Comment by ghost** [comment]
@liuhetian how do you use `/health`? 

Is this a hack b/c we don't pass this information in the existing proxie'd openai completion call?

**Comment by liuhetian** [comment]
> this is currently what /health returns, what would be ideal for you for it to return @liuhetian
> 
> ```json
> {
>     "healthy_endpoints": [
>         {
>             "model": "azure/gpt-35-turbo",
>             "api_base": "https://my-endpoint-canada-berri992.openai.azure.com/"
>         },
>         {
>             "model": "azure/gpt-35-turbo",
>             "api_base": "https://my-endpoint-europe-berri-992.openai.azure.com/"
>         }
>     ],
>     "unhealthy_endpoints": [
>         {
>             "model": "azure/gpt-35-turbo",
>             "api_base": "https://openai-france-1234.openai.azure.com/"
>         }
>     ]
> }
> ```


When requesting the /health endpoint, the same request is still made, but the difference is that the information in the header part that is hidden by default in the openai request is returned. [openai]( https://github.com/openai/openai-python#accessing-raw-response-data-eg-headers) 

```json

{
    "healthy_endpoints": [
        {
            "model": "gpt-3.5-turbo",
            # all those information are provided by openai
            # https://github.com/openai/openai-python#accessing-raw-response-data-eg-headers
            "ratelimit-requests": 10000,
            "ratelimit-remaining-requests": 9999,
            "ratelimit-tokens": 2000000,
            "ratelimit-remaining-tokens": 1999981,
            "ratelimit-reset-requests": "6ms",
            "ratelimit-reset-tokens": "0s",
        },
        {
            "model": "gpt-3.5-turbo",
            "ratelimit-requests": 10000,
            "ratelimit-remaining-requests": 9999,
            "ratelimit-tokens": 2000000,
            "ratelimit-remaining-tokens": 1999981,
            "ratelimit-reset-requests": "6ms",
            "ratelimit-reset-tokens": "0s",
        }
    ],
    "unhealthy_endpoints": [
        {
            "model": "azure/gpt-35-turbo",
            "api_base": "https://openai-france-1234.openai.azure.com/"
        }
    ]
}

```

**Comment by ghost** [comment]
Hey @liuhetian,

bump on this question - how do you use `/health`?

Is this a hack b/c we don't pass this information in the existing proxie'd openai completion call?

**Comment by liuhetian** [comment]
> ```json
> https://github.com/openai/openai-python#accessing-raw-response-data-eg-headers
> ```

hello! Are you referring to whether I used hackers to attack openai? Not at all. I just used the official interface and only reproduced the original information.
https://github.com/openai/openai-python#accessing-raw-response-data-eg-headers

**Comment by liuhetian** [comment]
> Hey @liuhetian,
> 
> bump on this question - how do you use `/health`?
> 
> Is this a hack b/c we don't pass this information in the existing proxie'd openai completion call?

hello! Are you referring to whether I used hackers to attack openai? Not at all. I just used the official interface and only reproduced the original information.
https://github.com/openai/openai-python#accessing-raw-response-data-eg-headers

**Comment by ghost** [comment]
Not at all @liuhetian. 

Just wanted to understand how you're using the `/health` endpoint.

So, how do you use `/health`?

**Comment by liuhetian** [comment]
> Not at all @liuhetian.
> 
> Just wanted to understand how you're using the `/health` endpoint.
> 
> So, how do you use `/health`?

thanks for your attention! I use /health for two purposes, I have a high concurrency project:
1. I need to monitor whether my project api_key needs to be increased (currently using 3 openai api keys). If it is close to going online, 1-2 api_keys of other projects will be added.
2. If all three api_keys are down due to the openai interface or have reached the rate limit, temporarily add an azure endpoint as an emergency record.

**Comment by ghost** [comment]
@liuhetian i can work on this today. 

Curious - how do you get alerted when to add a new key, etc.?

**Comment by liuhetian** [comment]
> @liuhetian i can work on this today.
> 
> Curious - how do you get alerted when to add a new key, etc.?

I imagine starting a small process separately to monitor the monitoring situation, and be responsible for adding or deleting api_key and api_base through /model/new or /model/delete. After experiencing frequent openai downtime in November, I feel that this is a problem. Necessary, after all, every downtime for online projects may be a major accident.

**Comment by ghost** [comment]
would it be better if we just returned these headers when you make a normal openai/azure call to the proxy? 

@liuhetian

**Comment by liuhetian** [comment]
> would it be better if we just returned these headers when you make a normal openai/azure call to the proxy?
> 
> @liuhetian

Do you mean to return these headers information together with normal requests? It may be possible, but I don't think it is necessary.
The purpose of using litellm-proxy is to manage all keys and bases in a unified manner. In my current project, I wrote a large piece of code to cool down and filter available keys based on header information. If I have another project, these codes will have to be rewritten. Again, this is too troublesome, so I hope to use litellm-proxy to solve this trouble and separate the function of managing keys separately, instead of each project managing the key by itself.
So for me, as long as I can add detailed information to the /health endpoint, combined with the [Dynamic reloading config file](#964), it can meet all my needs. thanks for the dynamic reloading config i love this feature so much!

**Comment by ghost** [comment]
This should be out soon. Fixing some bugs. 
<img width="993" alt="Screenshot 2023-12-28 at 8 09 18 AM" src="https://github.com/BerriAI/litellm/assets/17561003/61d050f0-c4b4-40da-b6ed-48fa6effc436">

**Comment by ghost** [comment]
Pushed - https://github.com/BerriAI/litellm/commit/3b1685e7c6003e5dd2ea303050205d3f763df898

Should be live soon in v`1.16.0`

**Comment by ghost** [comment]
@liuhetian can you let me know if this solves your problem?

I'd also like to set up a dedicated support channel for you. Here's my linkedin + discord, feel free to reach out wherever's convenient: 

LinkedIn: https://www.linkedin.com/in/krish-d/
Discord: Krrish#8748

**Comment by ghost** [comment]
@liuhetian following up on this - did this work for you?
