### ISSUE TITLE
[Feature]: Add support for Predibase Lorax apis 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1253]
### The Feature

Predibase now has serveless endpoints: https://docs.predibase.com/user-guide/inference/serverless_deployments#prompt-the-base-model

### Motivation, pitch

user request 
<img width="856" alt="Screenshot 2023-12-27 at 4 37 28 PM" src="https://github.com/BerriAI/litellm/assets/17561003/6b9449e0-b5f0-4456-8ca3-be44422f5038">

**Comment by ghost** [comment]
https://docs.predibase.com/user-guide/inference/rest_api

**Comment by ghost** [comment]
Second user just asked for predibase lorax support 
<img width="1366" alt="Screenshot 2024-01-02 at 10 31 14 AM" src="https://github.com/BerriAI/litellm/assets/17561003/cd18662b-6be6-4dba-9f9c-1023f84c30d3">

**Comment by ghost** [comment]
Working on this now - waiting on predibase for login details
