### ISSUE TITLE
[Feature]: Add gemini Pro Vision Cost Tracking

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1260]
### The Feature

- 

### Motivation, pitch

help track costs well

**Comment by ishaan-jaff** [comment]
vertex ai does a lot of the heavy lifting for us here, we just need to ensure we use the prompt_tokens returned from vertex ai:

fixed here: https://github.com/BerriAI/litellm/commit/739d9e7a78f72c8d0fc44d6fb81a451011b0c046

**Comment by ghost** [comment]
@ishaan-jaff is this solved then?

**Comment by ishaan-jaff** [comment]
done
