### ISSUE TITLE
[Bug]: The same input will have different prompt_tokens in different streams acompletion.

### ISSUE THREAD

**Issue by langgg0511** [BerriAI/litellm#1264]
### What happened?

![image](https://github.com/BerriAI/litellm/assets/38091079/a0fc6531-4379-4807-b94d-3a5d564638da)
![image](https://github.com/BerriAI/litellm/assets/38091079/7c3f1194-712a-420c-a818-3e7766771938)

**Comment by langgg0511** [comment]
litellm==1.16.3

**Comment by ishaan-jaff** [comment]
acknowledging this, taking a look

**Comment by ishaan-jaff** [comment]
trying to repro, this works fine with azure streaming so far 
<img width="969" alt="Screenshot 2023-12-29 at 1 53 38 PM" src="https://github.com/BerriAI/litellm/assets/29436595/258763dd-86d0-4baf-8af1-35a44f9abada">

**Comment by ishaan-jaff** [comment]
<img width="957" alt="Screenshot 2023-12-29 at 1 55 12 PM" src="https://github.com/BerriAI/litellm/assets/29436595/fbbb5fc1-b6ec-4eb2-86ff-021277298ff2">


I see the issue the `prompt tokens in the streamed response != prompt tokens in non streamed response`

**Comment by ishaan-jaff** [comment]
@langgg0511 are your requests to azure/gpt-3.5-turbo ?

**Comment by ishaan-jaff** [comment]
fixed here for Azure: https://github.com/BerriAI/litellm/commit/a300ab9152c06bc4358dc5a0fed2834c33dde0f7

**Comment by ishaan-jaff** [comment]
testing this here too: https://github.com/BerriAI/litellm/commit/73f60b731565b92cfa831552f53d3c29d9e2a3cc

**Comment by ishaan-jaff** [comment]
<img width="988" alt="Screenshot 2023-12-29 at 3 34 18 PM" src="https://github.com/BerriAI/litellm/assets/29436595/ed2e6bac-c8b7-4de2-adc6-2a25c3cd89a4">

verified on langfuse too

**Comment by ishaan-jaff** [comment]
live on 1.16.7 

@langgg0511 can you confirm it works for you ?


feel free to re-open this issue if it's not working

**Comment by langgg0511** [comment]
@ishaan-jaff  Now I find that in 1.16.11, the same return is calculated with different completion_tokens under different streams.

{
    "model": "gpt-3.5-turbo",
    "messages": [
        {
            "role": "user",
            "content": "say 1"
        }
    ],
}

openai/gpt-3.5-turbo; stream=false; completion_tokens=1
openai/gpt-3.5-turbo; stream=true; completion_tokens=4
