### ISSUE TITLE
[Bug]: TypeError: 'async for' requires an object with __aiter__ method, got coroutine

### ISSUE THREAD

**Issue by langgg0511** [BerriAI/litellm#1265]
### What happened?

def test_async_text_completion_stream():
    # tests atext_completion + streaming - assert only one finish reason sent
    litellm.set_verbose = False
    print("test_async_text_completion with stream")

    async def test_get_response():
        try:
            response = await litellm.atext_completion(
                model="gpt-3.5-turbo",
                prompt="good morning",
                stream=True,
                max_tokens=10,
            )
            print(f"response: {response}")

            num_finish_reason = 0
            async for chunk in response:
                print(chunk)
                if chunk["choices"][0].get("finish_reason") is not None:
                    num_finish_reason += 1
                    print("finish_reason", chunk["choices"][0].get("finish_reason"))

            assert (
                num_finish_reason == 1
            ), f"expected only one finish reason. Got {num_finish_reason}"
        except Exception as e:
            pytest.fail(f"GOT exception for gpt-3.5 instruct In streaming{e}")

    asyncio.run(test_get_response())

**Comment by langgg0511** [comment]
litellm=1.16.3
use gpt-3.5-turbo in stream atext_completion

**Comment by ghost** [comment]
taking a look at this.

**Comment by ghost** [comment]
Able to repro this 
<img width="1356" alt="Screenshot 2023-12-29 at 11 23 36 AM" src="https://github.com/BerriAI/litellm/assets/17561003/7d6b8201-d255-478a-a720-52757bab2385">

**Comment by ishaan-jaff** [comment]
we have this code snippet in our testing, do you know how it was able to pass ?

**Comment by ghost** [comment]
I think b/c it's written without a pytest.fail 
<img width="624" alt="Screenshot 2023-12-29 at 11 36 35 AM" src="https://github.com/BerriAI/litellm/assets/17561003/e2a2f8d9-fb78-403d-8039-67748fdf8094">

**Comment by ghost** [comment]
nope - that's wrong, it still passes. That's odd - investigating.

**Comment by ghost** [comment]
But when I run @langgg0511's function, i'm able to trigger pass/fails. 

Btw the fix is pushed - https://github.com/BerriAI/litellm/commit/6f2734100fff285c76ec2963cc3d78e30892cdde

**Comment by krrishdholakia** [comment]
Oh, got it. @langgg0511's test is a lot better, as it actually checks the value of response. our test was just printing response
<img width="1183" alt="Screenshot 2023-12-29 at 11 39 46 AM" src="https://github.com/BerriAI/litellm/assets/17561003/8f36254e-bea5-4269-b8a5-886cdab79359">

**Comment by ghost** [comment]
Found the issue - our test was testing text completion, but a change we made to fix async streaming for chat completions wasn't being tested. I've added the testing for this. 
<img width="1437" alt="Screenshot 2023-12-29 at 11 45 17 AM" src="https://github.com/BerriAI/litellm/assets/17561003/04eab466-8691-401c-b7ca-53b8c88a16a0">

**Comment by ghost** [comment]
fix should be live with v`1.16.5`

@langgg0511 please re-open if the issue persists
