### ISSUE TITLE
[Feature]: Add openmeter support for spend tracking across llm providers

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1268]
### The Feature

Have an openmeter integration for logging spend data to openmeter 

### Motivation, pitch

- openmeter seems focused on doing usage-billing well
- they're open-source, so people can self-host

**Comment by ghost** [comment]
https://github.com/openmeterio/openmeter/tree/main/api/client/python

Their sdk seem well-designed to consume from our logging integration 

<img width="1090" alt="Screenshot 2023-12-29 at 12 40 50 PM" src="https://github.com/BerriAI/litellm/assets/17561003/3adbc283-761c-4a0f-a050-bbeaad8190be">

**Comment by tothandras** [comment]
Thank you, @krrishdholakia, for your interest in our project! Based on our docs for [LangChain.js integration](https://openmeter.io/docs/collectors/langchain), do you think it would be straightforward to add this? I haven't tried to translate it to Python yet and we're not power users of LangChain. Let me know how we can help; we're happy to contribute.
