### ISSUE TITLE
proxy-server error when trying to use cohere api

### ISSUE THREAD

**Issue by johnd0e** [BerriAI/litellm#127]
```
litellm._thread_context: <litellm.MyLocal object at 0x000001B7FED2A980>
ERROR:waitress:Exception while serving /chat/completions
Traceback (most recent call last):
  File "D:\AI\litellm\cookbook\proxy-server\venv\lib\site-packages\waitress\channel.py", line 428, in service
    task.service()
  File "D:\AI\litellm\cookbook\proxy-server\venv\lib\site-packages\waitress\task.py", line 168, in service
    self.execute()
  File "D:\AI\litellm\cookbook\proxy-server\venv\lib\site-packages\waitress\task.py", line 472, in execute
    self.write(chunk)
  File "D:\AI\litellm\cookbook\proxy-server\venv\lib\site-packages\waitress\task.py", line 316, in write
    towrite += data + b"\r\n"
TypeError: unsupported operand type(s) for +: 'dict' and 'bytes'
```

**Comment by ghost** [comment]
cc: @ishaan-jaff

**Comment by ishaan-jaff** [comment]
@johnd0e is this with streaming cohere ?

**Comment by johnd0e** [comment]
Yes, that is because of streaming.
There is no problem when `"stream": false`

**Comment by ishaan-jaff** [comment]
@johnd0e will make a fix to the repo and revert in the next 2 hrs

What are you using the proxy server for ?

**Comment by johnd0e** [comment]
> What are you using the proxy server for ?

Just trying to explore cohere model with tools that support openai only.

**Comment by ishaan-jaff** [comment]
What tools specifically ? Can we help by adding an integration directly into `litellm` ?

**Comment by johnd0e** [comment]
> What tools specifically ?

Just some CLI tools, like [this](https://github.com/charmbracelet/mods)

> Can we help by adding an integration directly into litellm ?

Speaking about that, you could add KoboldAI/Horde integration https://aihorde.net/

**Comment by ishaan-jaff** [comment]
@johnd0e thanks for the info - we'll fix cohere streaming 

> Speaking about that, you could add KoboldAI/Horde integration https://aihorde.net/

Yes, can you share a code snippet of how you're calling KoboldAI/Horde - will help us add the integration quick

**Comment by johnd0e** [comment]
Ok, #130 and #131

**Comment by ishaan-jaff** [comment]
@johnd0e just tried locally and confirmed it's working for this arg in json

```
{
    "model": "command-nightly",
    "stream": true,
    "messages": [
                    { 
                        "content": "write a page about YC and legal procedure",
                        "role": "user"
                    }
                ]
    
}
```
![Postman](https://github.com/BerriAI/litellm/assets/29436595/63bd1ef7-38c3-428a-8a7a-b4b73bdc8f3a)

**Comment by ishaan-jaff** [comment]
What model are you using ?

**Comment by ishaan-jaff** [comment]
Also can you try running 

`git clone https://github.com/BerriAI/liteLLM-proxy`

It has the latest version of the proxy that I'm using

**Comment by johnd0e** [comment]
Indeed, https://github.com/BerriAI/liteLLM-proxy has no such problem

**Comment by ishaan-jaff** [comment]
Awesome - going to mark this as closed😊

**Comment by ghost** [comment]
Hey @johnd0e why use cohere?

**Comment by johnd0e** [comment]
Why not?
(I am just testing)

**Comment by ghost** [comment]
oh - is openai expensive?

Context - i've usually seen people use cohere as a backup model to openai, not try and switch to it entirely so wanted to understand the reason better (maybe we could do more to help)
