### ISSUE TITLE
[Bug]: async timeout error on proxy

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1278]
### What happened?

Hey, it seems after a few hours, the python server starts timing out for every call, then when it's restarted, it's fine but then starts timing out all the calls again.

### Relevant log output

```shell
ERROR    raise APITimeoutError(request=request) from err
ERROR    raise APITimeoutError(request=request) from err
ERROR    raise APITimeoutError(request=request) from err
ERROR    raise APITimeoutError(request=request) from err
ERROR    raise APITimeoutError(request=request) from err
ERROR    raise APITimeoutError(request=request) from err
ERROR    raise APITimeoutError(request=request) from err
ERROR    raise APITimeoutError(request=request) from err
ERROR    raise APITimeoutError(request=request) from err
ERROR    raise APITimeoutError(request=request) from err
ERROR    raise APITimeoutError(request=request) from err
ERROR    raise APITimeoutError(request=request) from err
ERROR    raise APITimeoutError(request=request) from err
```

**Comment by ghost** [comment]
User is using: 
- litellm proxy
- azure chat completions

**Comment by ishaan-jaff** [comment]
we have a deployed instance of the proxy here, we can run load testing against it: https://litellm-api.up.railway.app/ and try to repro

**Comment by ishaan-jaff** [comment]
seems related to this: https://github.com/openai/openai-python/issues/821 

I suspect it has something to do with the Azure/OpenAI client Initialization

**Comment by ghost** [comment]
"It's like consistently around 4 hours" - user 

"[7:51 AM, 12/30/2023] Okay happened, again, checking logs
[7:53 AM, 12/30/2023]  No errors
[7:53 AM, 12/30/2023]  Only warning is 

WARNINGWarning: the config option 'server.enableCORS=false' is not compatible with 'server.enableXsrfProtection=true'.
[7:54 AM, 12/30/2023]  any subsequent calls to gpt-3.5-turbo (azure) hung. calls to gpt-4 (openai) were fine
[7:55 AM, 12/30/2023]  After restart, all is good"

**Comment by ghost** [comment]
Pretty sure it's an azure-openai client issue. 

@ishaan-jaff open to thoughts on how to repro this within a shorter timeperiod. Can play around with min timeouts, and see how to better test this.

**Comment by ghost** [comment]
This seems pretty similar to what we're facing: https://github.com/openai/openai-python/issues/769#issuecomment-1806919277
<img width="1066" alt="Screenshot 2023-12-30 at 9 55 10 AM" src="https://github.com/BerriAI/litellm/assets/17561003/47e36dbc-4156-4d5b-a790-5902026497fc">

**Comment by ghost** [comment]
Seems like this might be related to connections not being properly closed, I don't think bumping the number is a good solution, as it'll just show up a little later on - 

<img width="1120" alt="Screenshot 2023-12-30 at 10 00 09 AM" src="https://github.com/BerriAI/litellm/assets/17561003/1cf584c5-d113-466a-ad16-d1491c382c50">

<img width="1090" alt="Screenshot 2023-12-30 at 10 01 06 AM" src="https://github.com/BerriAI/litellm/assets/17561003/3dcbd44e-b5d5-412f-a0ac-9f68a330cebb">

**Comment by ghost** [comment]
Another relevant issue - https://github.com/openai/openai-python/issues/874#issue-2008782190

**Comment by ghost** [comment]
Seems like this - https://github.com/BerriAI/litellm/issues/1270, could be a solution for the async timeout problem. 

We can just cache clients for ~1hr, and reinitialize them if they're invalid.

**Comment by ghost** [comment]
have this be a controllable param, for users who are seeing higher traffic, and need to re-initalize clients more frequently (there's obviously a trade-off here). 

This is also a patch, until openai has a more permanent fix out for how they handle connections (seems to be some sort of underlying bug with connections not being closed properly).

**Comment by ghost** [comment]
this is now added.
