### ISSUE TITLE
[Feature]: Add type hints for litellm.Router - model_list

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1282]
### The Feature

I was using the router and would have liked the model_list params to have type hint. Needed to go back and forth on docs to initialize the Router 

### Motivation, pitch

-

**Comment by rishabh279** [comment]
@ishaan-jaff I would like to work on this. Please assign this to me.

**Comment by ishaan-jaff** [comment]
done - thanks for the help !

**Comment by ishaan-jaff** [comment]
@rishabh279 FYI we now have this: https://github.com/BerriAI/litellm/blob/main/litellm/types/router.py 

hope this is useful

**Comment by rishabh279** [comment]
@ishaan-jaff Can you please suggest:

Will this works?
**model_list: Optional[List[Dict[str, Union[str, int, Dict[str, Union[str, int, float, bool, dict, List[str]]]]]]]**
or 
can we use this **model_list: Optional[List[ModelConfig]]** to provide balance between readability and precision?

**Comment by rishabh279** [comment]
While running the test cases through pytest, I ran into the following issues, can you please help me here?

![Selection_363](https://github.com/BerriAI/litellm/assets/13590232/671f1d63-be03-4e1f-a370-649089ba8369)

Seems like keys are required from different LLM providers like AWS, Google Cloud. Does that mean, to run test cases we need keys from different LLM providers?
I exported the Azure keys and base url, still facing exception related to the missing token
![Selection_370](https://github.com/BerriAI/litellm/assets/13590232/27dcf970-0bac-4250-925b-0d1dd0801b7b)
![Selection_369](https://github.com/BerriAI/litellm/assets/13590232/90f7d684-a013-41fd-9f65-160362c890d4)
![Selection_368](https://github.com/BerriAI/litellm/assets/13590232/f7ae4a7d-9699-445d-a512-139484eddf7f)
![Selection_367](https://github.com/BerriAI/litellm/assets/13590232/970026cd-23ca-4a08-b811-d8a60e8b56b0)
![Selection_366](https://github.com/BerriAI/litellm/assets/13590232/65c3f199-03a5-4a5e-b980-39c3ae53c8bd)
![Selection_365](https://github.com/BerriAI/litellm/assets/13590232/230a61b1-14a5-4c8b-b909-38af01223b6d)
![Selection_364](https://github.com/BerriAI/litellm/assets/13590232/8ee17c47-318b-45ac-a591-668d2251814c)

@ishaan-jaff @krrishdholakia

**Comment by ishaan-jaff** [comment]
done
