### ISSUE TITLE
GitHub Release vs pypi vs tags have inconsistent version info

### ISSUE THREAD

**Issue by ogencoglu** [BerriAI/litellm#1285]
### What happened?

As of now, Github shows 1.15.0, [pypi shows](https://pypi.org/project/litellm/) 1.16.8

Can this info be consistent and up to date?

**Comment by ghost** [comment]
I believe our ci/cd pipeline now automatically updates the `main-latest` tag - https://github.com/BerriAI/litellm/pkgs/container/litellm/162445810?tag=main-latest

We can fix this to use the same version tags.

**Comment by ghost** [comment]
Also DM'ed on LinkedIn to better understand how you're trying to use the proxy @ogencoglu

**Comment by ishaan-jaff** [comment]
we now create a new release every time we have a new pypi release: https://github.com/BerriAI/litellm/blob/main/.github/workflows/ghcr_deploy.yml 

I believe GitHub Release version == pypi version (will now always be True)

**Comment by ishaan-jaff** [comment]
@ogencoglu does this solve your problem well ?

**Comment by ogencoglu** [comment]
Yep, thanks!
