### ISSUE TITLE
change api key in terminal interpreter

### ISSUE THREAD

**Issue by ProZoNeMAB** [BerriAI/litellm#1286]
![Uploading Capture d’écran 2023-12-31 à 13.54.39.png…]()
Bonjour je ne peux plus utiliser chat gpt sur mon terminal car mon ancienne clé api est supprimée, quand je tape la commande interpreter je ne peut plus rentrer de clé api je me retrouve maintenant bloqué... avez vous une solution svp ? merci

**Comment by ghost** [comment]
The image didn't get uploaded, but I'm guessing this is an open-interpreter issue. I'd recommend checking out their github - https://github.com/KillianLucas/open-interpreter/
