### ISSUE TITLE
[Docs]: passing metadata openai.py, openai js, langchain py, langchain js 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1287]
### The Feature

clear docs on how to pass additional metadata via openai/langchain. We have a version of this already - https://docs.litellm.ai/docs/proxy/user_keys

### Motivation, pitch

we've heard this ask couple different times - "how do i pass additional params/metadata via openai/langchain"

**Comment by ghost** [comment]
User feedback - "I think the biggest thing is docs/suppoet for metadata passthrough in langchain. Both with LCEL chains and via a model directly"

**Comment by ghost** [comment]
cc: @ishaan-jaff

**Comment by ishaan-jaff** [comment]
docs on how to do this are here: https://docs.litellm.ai/docs/proxy/user_keys#pass-user-llm-api-keys
