### ISSUE TITLE
[Bug]: tpm/rpm routing not raising 'no models available error' on hitting limits

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1289]
### What happened?

I added models in model list with tpm and rpm. Even it reached cutoff limits still router using models without throwing error (no models available)

### Twitter / LinkedIn details

https://www.linkedin.com/in/sumanth18131a0363/

**Comment by ghost** [comment]
able to repro this

**Comment by ghost** [comment]
occurred due to:
1. not counting current call tokens 
2. if no deployment is returned, just randomly picking and returning that deployment

**Comment by ghost** [comment]
Resolved in v1.16.9
