### ISSUE TITLE
[Feature]: Support smtp server for handling user auth emails 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1293]
### The Feature

let user pass in their own smtp details for handling email sending - instead of needing to specifically use resend 

(similar to postgres db url) 

### Motivation, pitch

let user use whatever service they want - feels weird for proxy to have a hard dependency on one particular service

**Comment by ghost** [comment]
this is now supported - https://github.com/BerriAI/litellm/commit/070520d2376d42edce5d037c0eca8fc5e2295bb9
