### ISSUE TITLE
[Bug]: fix model info to handle fixed azure names

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1295]
### What happened?

Get model info has a mapping of openai names to azure names in model cost map, but thanks to @fcakyon the azure names have been fixed to reflect what they look like in the azure openai call. 

so we need to update the get model info function to handle this as well

Wondering if it might be better to have some abstraction class over model cost map to handle all these edge cases, and return stuff in a uniform format.

**Comment by ghost** [comment]
relevant function - https://github.com/BerriAI/litellm/blob/18ef244230e6a05086acf6e9ce35a9e37e763027/litellm/utils.py#L4035

Important as it impacts `/model/info` on the proxy server

**Comment by ghost** [comment]
cc: @ishaan-jaff

**Comment by ishaan-jaff** [comment]
we maintain `litellm.azure_llms` for this, that endpoint needs to be updated to use it

**Comment by ghost** [comment]
yup that's what i did - https://github.com/BerriAI/litellm/commit/a778f8a00e4e123d7d88f5133c9542746eaf9c4f
