### ISSUE TITLE
[Feature]: Docker builds - use correct release, latest tags 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1299]
### The Feature

`latest` on docker usually refers to main/master 

### Motivation, pitch

user feedback

**Comment by ghost** [comment]
I think this is an easy fix @ishaan-jaff 

since the circle ci flow already contains the pypi version number, it should be possible to also use that as the tag value

**Comment by ghost** [comment]
working on alerting now, can look at this after that + smtp stuff.

**Comment by ishaan-jaff** [comment]
<img width="594" alt="Screenshot 2024-01-04 at 3 58 00 PM" src="https://github.com/BerriAI/litellm/assets/29436595/7eef9a97-7b68-4516-95fd-9086e6f99a98">

docker images / builds now tag to the passing version on pypi


main-1.16.3 
main-1.16.4
main.1.16.5 

and so on

we'll stick to this convention since it's automated in our ci/cd now
