### ISSUE TITLE
Show me details about my llm calls - breakdown models called, total costs, by user ID

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#13]
I need visibility to see what litellm is calling
eg. What models get called 

If I'm using litellm for my I/I - it should give me visibility into what the package itself is doing

<img width="1280" alt="Screenshot 2023-07-28 at 5 32 10 PM" src="https://github.com/BerriAI/litellm/assets/29436595/798c5e09-7cc7-41e3-b659-a74b74247b83">

**Comment by ghost** [comment]
check out my PR -> specifically the logging i implemented around the `embedding` function. 

I believe we should do something like that for completions as well. Just need to do it in a simple/clean way.

**Comment by ghost** [comment]
logging is now implemented across the system. If you'd like to push data to a specific integration you can do that to with callbacks. 

Docs cover this in more detail https://litellm.readthedocs.io/en/latest/advanced/

**Comment by ghost** [comment]
version 0.1.341 now returns token usage across all providers. Where possible it uses the providers own tokenizer (E.g. anthropic) else it defaults to tiktoken.

Need to now build on this to expose a pricing functionality - required for aispend ticket as well

**Comment by ishaan-jaff** [comment]
closing this
