### ISSUE TITLE
New provider: KoboldAI

### ISSUE THREAD

**Issue by johnd0e** [BerriAI/litellm#130]
[Their](https://github.com/KoboldAI) API is [rich](https://gist.github.com/johnd0e/2f066aa1327245aafae699cc6c31dbdd), but for the purposes of this project similar simple implementation should be enough (I suppose)
https://github.com/Josh-XT/AGiXT/blob/main/agixt/providers/kobold.py

Here is more detailed implementation: https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/llms/koboldai.py

**Comment by ishaan-jaff** [comment]
thanks for making this issue - closing as this is not a top priority right now
