### ISSUE TITLE
[Feature]: enable s3 backend for caching 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1302]
### The Feature

 S3 as a backend for cached queries 

"make sure we can set the full endpoint URL, so we can use Backblaze B2 or Cloudflare R2 and not just AWS S3"

### Motivation, pitch

user request

**Comment by ishaan-jaff** [comment]
done, + docs here:  https://docs.litellm.ai/docs/caching/redis_cache 

we also added testing for using s3 Cache @Manouchehri 

**Before closing this issue-I want to make sure it works with Backblaze or Cloudflare**

**Comment by ishaan-jaff** [comment]
we should also add docs here on how to use s3 caching with the Proxy: 
https://docs.litellm.ai/docs/proxy/caching#set-cache-params-on-configyaml

**Comment by ishaan-jaff** [comment]
this is completed
