### ISSUE TITLE
The same return is calculated with different completion_tokens under different streams

### ISSUE THREAD

**Issue by langgg0511** [BerriAI/litellm#1304]
@ishaan-jaff  Now I find that in 1.16.11, the same return is calculated with different completion_tokens under different streams.

{
    "model": "gpt-3.5-turbo",
    "messages": [
        {
            "role": "user",
            "content": "say 1"
        }
    ],
}

openai/gpt-3.5-turbo; stream=false; completion_tokens=1
openai/gpt-3.5-turbo; stream=true; completion_tokens=4

_Originally posted by @langgg0511 in https://github.com/BerriAI/litellm/issues/1264#issuecomment-1874783955_

**Comment by ishaan-jaff** [comment]
will work on this today, @langgg0511 any chance you're free for a quick call? It will help us support your use case well 

Attaching a link to my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by langgg0511** [comment]
@ishaan-jaff Sorry, English conversation is still difficult for me.

**Comment by ishaan-jaff** [comment]
@langgg0511 can we start a group chat on Linkedin / Discord in that case ? 

My linkedin: https://www.linkedin.com/in/reffajnaahsi/ 
Discord: ishaanberri.ai

**Comment by langgg0511** [comment]
> @langgg0511 can we start a group chat on Linkedin / Discord in that case ?
> 
> My linkedin: https://www.linkedin.com/in/reffajnaahsi/ Discord: ishaanberri.ai

yes, how can I start a chat on LinkedIn?

**Comment by ghost** [comment]
@langgg0511 if you can share your linkedin - i'll send over a friend request, and set up the support channel

**Comment by langgg0511** [comment]
> @langgg0511 if you can share your linkedin - i'll send over a friend request, and set up the support channel

My linkedin: https://www.linkedin.com/in/wu-langgg-2980002a8/

**Comment by ishaan-jaff** [comment]
Fix for this issue is on this commit: 

https://github.com/BerriAI/litellm/commit/f3b8d9c3ef99ddf1eb4af8bedbc9f95667a0f4b4 

Your test case is here too: @langgg0511 : https://github.com/BerriAI/litellm/commit/2bea0c742e5db65c12d0c5fb210183fc09f81031 

Thanks for the issue @langgg0511 this made our token counter for Azure much better, really appreciate it

**Comment by ishaan-jaff** [comment]
just sent a Linkedin request, + queued a new deploy. will lyk once in prod

**Comment by ishaan-jaff** [comment]
https://pypi.org/project/litellm/1.16.12/ in prod

**Comment by langgg0511** [comment]
There seems to be still an issue with acompletion, which I observed in Lanfuse.
stream=true
![image](https://github.com/BerriAI/litellm/assets/38091079/b18cb4c9-80d7-475c-a204-1cd038fc09ca)
stram=false
![image](https://github.com/BerriAI/litellm/assets/38091079/9248f55d-ba3a-4e78-b829-eba7107d6ab0)

**Comment by ishaan-jaff** [comment]
oh looks like it did not reach prod as yet, the prod version is 1.16.3

**Comment by ishaan-jaff** [comment]
live here @langgg0511 : https://github.com/BerriAI/litellm/releases/tag/v1.16.15. 

let me know if it works for you

**Comment by langgg0511** [comment]
> live here @langgg0511 : https://github.com/BerriAI/litellm/releases/tag/v1.16.15.
> 
> let me know if it works for you

acompletion is correct, the prompt_tokens of atext_completion under stream==true is still 0.

**Comment by ishaan-jaff** [comment]
okay - tracking the `atext_completion` in a different issue
