### ISSUE TITLE
[Feature]: Proxy - Allow users to set DynamoDB URL for Key Management 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1307]
### The Feature

User wants to do key mgmt and budget tracking, but can only use DynamoDB 

### Motivation, pitch

user request

**Comment by ishaan-jaff** [comment]
looks like we had an issue for dynamoDB: https://github.com/BerriAI/litellm/issues/887 

doesn't seem like dynamodb would be supported by the prisma interface - https://github.com/prisma/prisma/issues/1676#issuecomment-1464117515

**Comment by ishaan-jaff** [comment]
An alternative here is using AWS RDS https://aws.amazon.com/rds/free/?loc=ft#Free_Tier 

Which provides PostgreSQL on AWS

**Comment by ghost** [comment]
User said DynamoDB is a hard requirement. 

We could just use boto3 for this - https://www.honeybadger.io/blog/using-dynamodb-with-python/


Since our db client is already abstracted away - https://github.com/BerriAI/litellm/blob/aa757d19f56a83323fb01ea298b36480fd5f718c/litellm/proxy/utils.py#L251

We could just do this ourselves

**Comment by ghost** [comment]
Don't think we should do this ourselves. Seems like there's different edge cases here - e.g. how you set compute cost (aws charges per read/write or by compute, etc.) 

Considering using this - https://github.com/pynamodb/PynamoDB

**Comment by ghost** [comment]
I have an initial working commit - https://github.com/BerriAI/litellm/tree/litellm_dynamo_db_keys

Really concerned about the overhead of supporting 2 different db formats (nosql + sql)

**Comment by ghost** [comment]
pynamodb doesn't support async 😢  https://github.com/pynamodb/PynamoDB/issues/802

exploring alternatives

**Comment by ghost** [comment]
👀 https://github.com/HENNGE/aiodynamo

**Comment by ghost** [comment]
pending work - enable spend tracking for dynamodb

**Comment by brunobelloni** [comment]
> 👀 https://github.com/HENNGE/aiodynamo

👀 https://github.com/brunobelloni/aioPynamoDB
