### ISSUE TITLE
[Bug]: LiteLLM Proxy High Traffic Fixes

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1308]
### What happened?

Issue to track errors when using LiteLLM proxy for high traffic

**Comment by ishaan-jaff** [comment]
- User complained about elevated dropped requests after using the proxy for 6+ hours with Azure OpenAI

**Comment by ghost** [comment]
We should set up a test environment - 1k req. / min. across the day

This will help us repro the load our users are facing, and catch any networking bugs that come up. 

cc: @jordancde

**Comment by ghost** [comment]
Working on setting up a long term proxy load test

Basic idea: 
- be able to run a proxy over night (~12 hrs)
- hit it with 500-1k req./min 
- catch / repro any errors that come up -> send to sentry + slack

**Comment by ghost** [comment]
Update:
- model added to hosted endpoint

Going to work on setting up the supabase cron job

**Comment by ghost** [comment]
This is now set up 

- we have a supabase cron job hitting our deployed endpoint - https://litellm-api.up.railway.app/
with 1k requests per minute 

- we also have slack alerting + langfuse logging set up, so we should be able to catch any dropped requests / issues

**Comment by ghost** [comment]
Taking a look at langfuse logging - i don't see any new logs, so there might be a connection setup issue. 

Going to investigate this next. 

I think we should probably be sending some sort of test request to integrations when somebody tries to add them on the proxy, just so we know things are setup correctly. 

Min requirement would be for slack alerting.

**Comment by ghost** [comment]
pushed commit to send a slack test message when it's added via `/config/update`

**Comment by ghost** [comment]
Seeing some prisma client connection errors already - i believe this is related to the fix we just pushed cc: @ishaan-jaff 
<img width="974" alt="Screenshot 2024-01-04 at 6 30 16 PM" src="https://github.com/BerriAI/litellm/assets/17561003/9adfc3f7-4195-4124-9cd3-39050b80609d">
