### ISSUE TITLE
[Feature]: proxy - add testing for Caching

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1309]
### The Feature

- Add testing for using Redis Cache, s3 Cache 

### Motivation, pitch

reliability

**Comment by ishaan-jaff** [comment]
also for using s3 compatible api endpoints like backblaze or cloudflare

**Comment by ishaan-jaff** [comment]
s3 cache test here: https://github.com/BerriAI/litellm/commit/54653f9a4a4b22417689c6d99c3f93b02c037c01

**Comment by ishaan-jaff** [comment]
done

**Comment by ghost** [comment]
@ishaan-jaff we already have unit tests for caching on the completion call + router 

Any specific part of the proxy you're trying to test?
