### ISSUE TITLE
[Feature]: Improve LiteLLM Release information, Github Releases 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1310]
### The Feature

- github release automatically whenever there's a new pypi release
- github tag automatically whenever there's a new pypi release
- reference the commit somehow on pypi's release 

### Motivation, pitch

user request

**Comment by ghost** [comment]
Got a 2nd user request for having the github release be tagged. 

Are you looking into this @ishaan-jaff

**Comment by ishaan-jaff** [comment]
yes, doing this today

**Comment by ishaan-jaff** [comment]
we now do the following:

- github release automatically whenever there's a new pypi release 
- github tag automatically whenever there's a new pypi release
- reference the commit somehow on pypi's release (github automatically references the latest commit for this)

**Comment by Manouchehri** [comment]
woot woot, thanks!

This is my workflow now (if anyone else is curious):

```sh
git clone git@github.com:aimoda/litellm.git # private fork
cd litellm/
git remote add upstream https://github.com/BerriAI/litellm.git
git fetch --tags upstream
git merge v1.16.13
```
