### ISSUE TITLE
[Bug]: Typo in `s-max-age` (should be `s-maxage`)?

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#1312]
### What happened?

Not sure if it's intentional or not.

Typically, the shared cache max age is called `s-maxage`. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#response_directives

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by krrishdholakia** [comment]
Looks like it was a doc typo. In code we do check for `s-maxage`. Thanks for flagging this @Manouchehri 
<img width="713" alt="Screenshot 2024-01-04 at 11 29 31 AM" src="https://github.com/BerriAI/litellm/assets/17561003/005a03b8-9150-40e9-b835-d9b145ae73f1">

**Comment by ghost** [comment]
Fixed - https://github.com/BerriAI/litellm/commit/b0827a87b2a66bb2e375b50de36eb48e43239e53

We now check if either `s-maxage` or `s-max-age` are passed in
