### ISSUE TITLE
[Feature]: Passthrough BadRequest message to client

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#1316]
### The Feature

When Azure OpenAI triggers a filtered error like this, we should pass it through to the user so they know what happened.

```
openai.BadRequestError: Error code: 400 - {'error': {'code': 'BadRequest', 'message': "The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: \r\nhttps://go.microsoft.com/fwlink/?linkid=2198766.", 'param': None, 'type': None}}
```

### Motivation, pitch

So while testing `gpt-4-vision-preview` on my own face, I discovered that apparently my appearance breaks Azure OpenAI's content management policy. Had to look at LiteLLM logs to figure out why it wasn't working.

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by ghost** [comment]
I like OpenAI's approach here, where they have a set of status codes for which they will do retries 

Could do something similar

**Comment by ghost** [comment]
This commit should address this - https://github.com/BerriAI/litellm/commit/25241de69e571bf9159cdf67a02b10a0dc7306c6

@Manouchehri my test showed we weren't retrying 400 status code requests (we already re-implemented openai's 'should_retry' logic, but we weren't checking this in fallbacks, I added a quick check to pass through a 400 status code exception, open to just using the same 'should_retry' logic there too.

**Comment by ghost** [comment]
should be live soon in v`1.16.14`
