### ISSUE TITLE
[Feature]: Cloudflare AI gateway + Azure OpenAI - failing chat/completions 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1318]
### The Feature

- 

### Motivation, pitch

-

**Comment by ghost** [comment]
We actually test for this in our ci/cd, so i'm confused how this is happening. 

Will look into it as well

**Comment by ishaan-jaff** [comment]
it was only failing `non streaming` requests, there was a bug when initializing cloudflare gateway Azure clients

**Comment by ishaan-jaff** [comment]
fix + testing is here: https://github.com/BerriAI/litellm/commit/6d21ee3a2f17a51e3d537fcee9749d0b9d1450f9

**Comment by ishaan-jaff** [comment]
added more testing here: https://github.com/BerriAI/litellm/commit/aa757d19f56a83323fb01ea298b36480fd5f718c 

we test the following scenarios for init clients now 
```
    # init azure + cloudflare
    # init OpenAI gpt-3.5
    # init OpenAI text-embedding
    # init OpenAI comptaible - Mistral/mistral-medium
    # init OpenAI compatible - xinference/bge
```

**Comment by ishaan-jaff** [comment]
closing this as fixed
