### ISSUE TITLE
[Bug]: Model list lost on redeploys 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1322]
### What happened?

When we redeploy the proxy, any models added while the proxy was deployed is lost. 

This is **very bad**, as I now have to re-add all my models 

- [x] Enable persisting config to db 
- [x] Remove sensitive information (api keys) from config before saving to db 
- [ ] Support reading config from db 
- [ ] Support writing sensitive information (api keys) to supported key manager

**Comment by ghost** [comment]
Store config in DB 

1. When new model added / config updated via APIs - update the db config 
2. when proxy redeployed - pull from db as well

**Comment by ghost** [comment]
Just built a working version locally, 

Seeing my keys in the pg db feels really weird. I don't feel very comfortable with that. I'm more okay with re-adding models than I am exposing my keys.

**Comment by ghost** [comment]
I like the convenience of having 1 place from which to add models, but I don't want my keys exposed in the db. 

I wish I could have it either - write the key locally or save it to a connected key manager **NOT** write the value to the db.

**Comment by ishaan-jaff** [comment]
this is live now - with write models to the DB
