### ISSUE TITLE
[Bug]: `seed` parameter not used in OpenAI API

### ISSUE THREAD

**Issue by fcakyon** [BerriAI/litellm#1323]
### The Feature

OpenAI API accepts a `seed` parameter to generate reproducible outputs. This is a very useful feature for predictable production deployments. It would be great to be able to used this param with LiteLMM.

Here is the official docs: https://platform.openai.com/docs/api-reference/chat/create#chat-create-seed

### Motivation, pitch

`seed` parameter is a handy feature for predictable production deployments. It would be great if it is added as OpenAI/Azure OpenAI input.

### Twitter / LinkedIn details

@fcakyon / https://www.linkedin.com/in/fcakyon/

**Comment by ishaan-jaff** [comment]
we already support this https://github.com/BerriAI/litellm/blob/773a0a147a5c86b6fa6cfbf79afd113f7669e6f9/litellm/tests/test_completion.py#L606 

did you run into any issue @fcakyon ?

**Comment by ghost** [comment]
If this was missing in docs - let me know where you looked and i'll add it @fcakyon

**Comment by fcakyon** [comment]
@ishaan-jaff @krrishdholakia that seed parameter provided in wrapper level doesn't make it into AzureOpenAI and OpenAI classes. In docs, it says OpenAI models support seed param, but in practice, it is not supported.

There is no seed parameter in the classes:

AzureOpenAI:
https://github.com/BerriAI/litellm/blob/6b708347f3bb3c6f08b2d3a28cdca9d4dc0a15b2/litellm/llms/azure.py#L71-L83
https://github.com/BerriAI/litellm/blob/6b708347f3bb3c6f08b2d3a28cdca9d4dc0a15b2/litellm/llms/azure.py#L112-L131

OpenAI:
https://github.com/BerriAI/litellm/blob/6b708347f3bb3c6f08b2d3a28cdca9d4dc0a15b2/litellm/llms/openai.py#L83-L95
https://github.com/BerriAI/litellm/blob/6b708347f3bb3c6f08b2d3a28cdca9d4dc0a15b2/litellm/llms/openai.py#L164-L178

**Comment by ghost** [comment]
@fcakyon that's incorrect. 

The config you're referring to is an optional class you can use to define provider specific params, if you don't want to pass it in during the completion call - https://docs.litellm.ai/docs/completion/input#provider-specific-params (see: provider-specific config variable) 

We do respect the seed param - https://github.com/BerriAI/litellm/blob/aa72d65c90c23f429661a283c6dd8fb59e8cee83/litellm/utils.py#L3079

And is sent across if you pass it in the completion function 

```
from litellm import completion
import os

## set ENV variables
os.environ["OPENAI_API_KEY"] = "your-api-key"

response = completion(
  model="gpt-3.5-turbo", 
  messages=[{ "content": "Hello, how are you?","role": "user"}],
  seed=23
)
```

https://github.com/BerriAI/litellm/blob/6b708347f3bb3c6f08b2d3a28cdca9d4dc0a15b2/litellm/llms/openai.py#L218


--
Did you try this and see any issue?

**Comment by ghost** [comment]
Closing the issue as I believe the original ask re: supporting the seed param exists. 

@fcakyon please re-open if i misunderstood

**Comment by Manouchehri** [comment]
We've been using the seed param for awhile with LiteLLM + Azure OpenAI and it seems to be working fine.
