### ISSUE TITLE
[Feature]: Allow to specify prompt templates for the new proxy.

### ISSUE THREAD

**Issue by lukolszewski** [BerriAI/litellm#1326]
### The Feature

Ability to specify prompt templates for models.

### Motivation, pitch

This would be very useful to tweak own model prompt templates. Based on documentation and history this used to work on older versions. These old methods (config.toml, running with just --config switch) no longer work. It would be good to have this feature back.

**Comment by lukolszewski** [comment]
Actually this is working and is described here: https://docs.litellm.ai/docs/proxy/configs I haven't noticed.

**Comment by ghost** [comment]
Hey @lukolszewski this is supported on the new proxy - https://docs.litellm.ai/docs/proxy/configs#set-custom-prompt-templates

Where did you look in docs? I'll make sure to add it

**Comment by ghost** [comment]
Glad you found it! @lukolszewski 

How're you using the proxy?

**Comment by lukolszewski** [comment]
Thanks @krrishdholakia , I'm using it just as a translation layer to a local TGI host. I previously looked at the docs in the repo, but I must have missed it. I saw files like this instead: docs/tutorials/model_config_proxy.md
