### ISSUE TITLE
[Bug]: Huggingface streaming connection closed early - httpx client 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1334]
### What happened?

httpx client in huggingface closes the timeout early (within 5s) for streaming. 

I think it would b a cool feature to be able to configure that timeout by the config file. I'll just hardcode this to 60s for myself. It's in litellm/llms/huggingface_restapi. py line 609.

### Relevant log output

```shell
user request
```

**Comment by ghost** [comment]
Fix pushed - https://github.com/BerriAI/litellm/commit/b1fd0a164bca6981d6f1df91ee2b5ff5ad79bb93
