### ISSUE TITLE
[Bug]: Installation issue on zsh: no matches found

### ISSUE THREAD

**Issue by tylerbrandt** [BerriAI/litellm#1335]
### What happened?

I attempted to install the package using `pip install litellm[proxy]` (verbatim). However, it raised an error from my shell (zsh, which is the default on macOS):
```
zsh: no matches found: litellm[proxy]
```
In order to make it install successfully I had to quote it:
```
pip install 'litellm[proxy]'
```

**Comment by ghost** [comment]
Hi @tylerbrandt thanks for flagging this. Trying to repro now

**Comment by ghost** [comment]
This `pip install litellm[proxy]` seems to work for me: 

<img width="1426" alt="Screenshot 2024-01-06 at 11 01 59 AM" src="https://github.com/BerriAI/litellm/assets/17561003/fe713cb1-48ac-4ca0-8cb7-45b1219a651c">

**Comment by ghost** [comment]
`!pip install 'litellm[proxy]'` this also seems to work for me on colab - https://colab.research.google.com/drive/17o_lSOIT6SJ2Z_efLlo64IsOvdIhgW1z?usp=sharing
<img width="1360" alt="Screenshot 2024-01-06 at 11 02 50 AM" src="https://github.com/BerriAI/litellm/assets/17561003/d207ac03-a100-4ab5-9133-5013c5abacd1">

**Comment by ghost** [comment]
Testing on my local machine now

**Comment by ghost** [comment]
able to repro this problem on my local machine 

<img width="654" alt="Screenshot 2024-01-06 at 11 04 38 AM" src="https://github.com/BerriAI/litellm/assets/17561003/a1f082b1-6fda-4d08-bff2-ae3f67fd266f">

**Comment by ghost** [comment]
the quotes do work for me: `pip install 'litellm[proxy]'` 


<img width="822" alt="Screenshot 2024-01-06 at 11 06 21 AM" src="https://github.com/BerriAI/litellm/assets/17561003/c3b114ee-a932-42db-9f13-68aae6483e2f">

**Comment by ghost** [comment]
@tylerbrandt can you confirm you're on the latest version of litellm? 

try doing: 
```
pip install --upgrade litellm 

pip install 'litellm[proxy]'
```

?

**Comment by tylerbrandt** [comment]
Not at my machine now but I just installed it yesterday so it’s probably the latest…what are you trying to determine? So far it seems your experience has exactly matched mine (when run on zsh, it only works if quoted). I think that’s fine but probably the documentation and suggested commands emitted from the app should be quoted too.

**Comment by ishaan-jaff** [comment]
I've seen this issue on my machine too

**Comment by ishaan-jaff** [comment]
<img width="1238" alt="Screenshot 2024-01-06 at 11 31 41 AM" src="https://github.com/BerriAI/litellm/assets/29436595/863d7852-9f01-4481-8a75-49f945c76369">


our quick start docs show both ways to do this: https://docs.litellm.ai/docs/proxy/quick_start 

perhaps we should default to `pip install 'litellm[proxy]'` since that works everywhere

**Comment by ghost** [comment]
pushed the commit to fix this - https://github.com/BerriAI/litellm/commit/b51d98c6e3c408fec3318aa5e8fee12efae08826

we know consistently instruct the usage of `pip install 'litellm[proxy]'`

Closing ticket as i believe this should resolve it. @tylerbrandt feel free to reopen if not.

**Comment by tylerbrandt** [comment]
Works for me! Thanks
