### ISSUE TITLE
[Feature]: Why are you serializing the model back to JSON for OpenAI response? Just use model_dump instead 

### ISSUE THREAD

**Issue by espdev** [BerriAI/litellm#1337]
### The Feature

Here is the current code:
https://github.com/BerriAI/litellm/blob/ae54e6d8b0c49e61b084b282a5e720dfe7360e6d/litellm/llms/openai.py#L309-L319

https://github.com/BerriAI/litellm/blob/ae54e6d8b0c49e61b084b282a5e720dfe7360e6d/litellm/llms/openai.py#L529-L538

Why do you make `stringified_response`?
Maybe use the following code:
```
convert_to_model_response_object(response_object=response.model_dump())
```

Now you take a response Pydantic model with **already deserialized JSON**, serialize it to a string again, and then immediately deserialize it back to a dictionary. For what purpose? Imagine you have a batch of 2048 embedding vectors. Just use `response.model_dump` and get a dictionary directly.

### Motivation, pitch

Don't lose performance

**Comment by ghost** [comment]
Yup makes sense - tracking this here: https://github.com/BerriAI/litellm/pull/1344

**Comment by ghost** [comment]
This is now live
