### ISSUE TITLE
[Feature]: Rate-limit awareness across routing strategies + sub-minute accounting

### ISSUE THREAD

**Issue by JPalakapilly** [BerriAI/litellm#1339]
### The Feature

Hey guys, first off: LiteLLM is an awesome project. Saves us a lot of time on building LLM infra. A couple of requests here. We're thinking about building our own routing strategy that incorporates these and wanted to see if they were on your roadmap.

1. It would be great if TPM/RPM checks were enforced on all routing strategies (especially lowest latency). I see some mention of that [here](https://github.com/BerriAI/litellm/issues/872#issuecomment-1873575419) and want to pile on to that sentiment.

2. Azure also calculates rate limits on [sub-minute periods](https://learn.microsoft.com/en-us/answers/questions/1336515/how-do-azure-openai-rate-limits-work). It would be great if we could specify the period of time used in the rate limit calculation for the TPM/RPM checks.

### Motivation, pitch

We want a routing strategy that picks the lowest latency model but ensures that we are still under our rate limit thresholds. We also want rate limit calculation to be as accurate as possible for OpenAI and Azure.

**Comment by ghost** [comment]
Hey @JPalakapilly having rate-limit checks be across strategies is definitely top of mind. 

Re: tpm/rpm calculation: 
- we calculate that when a request is successful -> update cache for the minute it was successful within -  https://github.com/BerriAI/litellm/blob/357c6c56bdfb2b548c205b222405369949bb51dd/litellm/router_strategy/lowest_tpm_rpm.py#L94

How could that be done better? 

DM'ed on linkedin to set up a support channel

**Comment by ghost** [comment]
Noting the headers I see from an azure openai call:

```
Headers({'cache-control': 'no-cache, must-revalidate', 'content-length': '785', 'content-type': 'application/json', 'access-control-allow-origin': '*', 'apim-request-id': 'e37c41c3-f41e-4feb-88e4-d9ea9ad124a7', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'x-content-type-options': 'nosniff', 'x-ms-region': 'East US', 'x-ratelimit-remaining-requests': '118', 'x-ratelimit-remaining-tokens': '119887', 'x-accel-buffering': 'no', 'x-request-id': '41f59816-fc38-4f44-9789-abec7d362662', 'x-ms-client-request-id': 'e37c41c3-f41e-4feb-88e4-d9ea9ad124a7', 'azureml-model-session': 'turbo-0613-9e2e75c5', 'date': 'Wed, 10 Jan 2024 06:13:28 GMT'})
```

**Comment by ghost** [comment]
I see that we have `x-ratelimit-remaining-requests` and `x-ratelimit-remaining-tokens`

**Comment by ghost** [comment]
for successful responses, we could potentially try and include this in the logging object -> can then access this in routing strategies to update the cache value for checking

**Comment by ghost** [comment]
tpm/rpm checks for latency-based routing is now live in v`1.17.0`

@JPalakapilly

**Comment by ghost** [comment]
Azure doesn't expose the time period used. But it does share remaining tokens, remaining requests. We can use them in tpm/rpm calculations. 

Will update ticket once that's added.
