### ISSUE TITLE
setting max_tokens has no effect or will error

### ISSUE THREAD

**Issue by don-tpanic** [BerriAI/litellm#134]
Hi thanks for this helpful code!

I run into a problem when try to set the optional `max_tokens` as shown below. When using "command-nightly", setting `max_tokens` has no effect on how many tokens will be generated. When using "gpt-3.5-turbo", I got `openai.error.InvalidRequestError: Additional properties are not allowed ('max_tokens' was unexpected) - 'messages.0'`

Any pointers? Thanks in advance!
```
prompt = f"{prompt_template}\n"
    messages = [
        {
            "content": prompt, 
            "role": "user",
            "max_tokens": 5,
        }
    ]

    # cohere: "command-nightly"
    response = completion(
        "command-nightly", messages
    )
```

**Comment by ghost** [comment]
Hi, I think you might be setting max_tokens incorrectly. From the code snippet it seems like you're passing it inside `messages`. 

The expected implementation is from lite + openai is - 

```
model="command-nightly"
messages=[{"role":"user", "content": prompt}]
response = completion(model, messages, max_tokens=256)
```

**Comment by ghost** [comment]
Let me know if this works @don-tpanic . Here's a working notebook - https://colab.research.google.com/drive/1NrARfFmUBfjJSZU6sgHvcQC3gm1agzus?usp=sharing

<img width="1202" alt="Screenshot 2023-08-17 at 7 36 06 AM" src="https://github.com/BerriAI/litellm/assets/17561003/b1e0e1ba-e56c-47bc-a5c1-eeabc33f2629">

**Comment by ghost** [comment]
closing issue for now - please reopen if this didn't solve your problem

**Comment by don-tpanic** [comment]
It solved my problem. Thanks @krrishdholakia !
