### ISSUE TITLE
[Bug]: ollama.py prompt_eval_count crushes when is not defined

### ISSUE THREAD

**Issue by mongolu** [BerriAI/litellm#1349]
### What happened?

A bug happened!

**Comment by bgoosmanviz** [comment]
I ran into this too. I have a hacky fix here: https://github.com/Kineviz/litellm/commit/65f335818ea3ca96c5402e3a3b12748d582bcad9

Ollama intermittently omits the prompt_eval_count property. Idk why, but it does.

**Comment by ghost** [comment]
Should be fixed in v`1.17.0`
