### ISSUE TITLE
[Bug]:  prompt_tokens of atext_completion under stream==true is 0 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1354]
### What happened?

cc @langgg0511

**Comment by ghost** [comment]
Should we expect streaming responses to contain usage? @ishaan-jaff @langgg0511

**Comment by ghost** [comment]
Or is this for logging?

**Comment by langgg0511** [comment]
I use it for logging.

**Comment by ghost** [comment]
I believe i have a fix out for this - https://github.com/BerriAI/litellm/commit/9b46412279b887a60b8e82ca4db0d7da81072f7f

With a fix for how messages is passed in

Also pushed a second fix for calculating cost for text completion streaming responses - https://github.com/BerriAI/litellm/commit/6333fbfe5612355460254c21dd37be407d25faeb

These changes should be live in v`1.16.19`

**Comment by ghost** [comment]
If these don't solve your problem, can you share a code for repro @langgg0511 

I can take a look and make sure to include this in testing

**Comment by ishaan-jaff** [comment]
this issue was to assert something like this but for `litellm.atext_completion` 

https://github.com/BerriAI/litellm/blob/f07daa3780e7f45ec20b6c590669dcd9b5b04257/litellm/tests/test_stream_chunk_builder.py#L170C4-L171C72/

see related issue: https://github.com/BerriAI/litellm/issues/1304

**Comment by ghost** [comment]
added the requested test in pr @ishaan-jaff @langgg0511 

Will merge once it's passed testing

**Comment by langgg0511** [comment]
In v1.16.19, the result is correct.
