### ISSUE TITLE
[Feature]: Raise a separate exception for content violations

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1372]
### The Feature

Raise a separate exception (like contextwindowexceedederror) but for content violations. 

### Motivation, pitch

Right now this is returned as a 400 status code (badrequesterror) from azure + openai. But unlike other 400 requests, this one isn't consistent (i.e. the same image when run twice might work, even if initially it raised a 400 error). 

Having this as a separate exception would help more with retry/fallback logic.

**Comment by ishaan-jaff** [comment]
PR to address this here: https://github.com/BerriAI/litellm/pull/1381

**Comment by ghost** [comment]
Love this! This is such a great PR

**Comment by ghost** [comment]
Closing, since PR is merged
