### ISSUE TITLE
[Feature]: Support input/output cost per second - custom pricing 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1374]
### The Feature

Allow user to set input/output cost per second for custom models (e.g. sagemaker) 

### Motivation, pitch

Make it easier to track cost per call

**Comment by ghost** [comment]
Tasks: 
- [x] Support completions 
- [x] Support embedding 
- [x] Add to docs

**Comment by ghost** [comment]
This is now merged and live in v`1.18.9`.
