### ISSUE TITLE
expose a list of supported llm providers via package

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#138]
expose a list of the supported llm providers, useful for creating / mapping backup keys for each provider

**Comment by ishaan-jaff** [comment]
+1 this would be awesome.I believe langchain does this

**Comment by ghost** [comment]
pushed as part of 5ef5af8ddcac6cd6fec10eab72e9a6879abcd932

you can access it as 
`providers = litellm.provider_list`
