### ISSUE TITLE
[Bug]: fix dockerfile to support litellm cli args

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1388]
### What happened?

moving to ./entrypoint.sh removed our users ability to pass in runtime args 

### Relevant log output

```shell
user debug session
```

**Comment by ghost** [comment]
also move num_workers to be a user defined arg 

## reason? 

user faced OOM issues when upgrading docker image b/c num workers was set to 8

**Comment by ishaan-jaff** [comment]
i need to look into this rn - seeing this issue

**Comment by ishaan-jaff** [comment]
i had to bump cloud run to 8gb😓

**Comment by ghost** [comment]
Closing as this is now fixed. Memory issues caused by hardcoding num workers which has also been removed.
