### ISSUE TITLE
[Feature]: Logging to s3 bucket

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#1389]
### The Feature

e.g. 

#### `s3-bucket-name/response/230a7fd1db82cac4831afb01bf2a777b781faef7ba62127ce38bcf536c162dd3.json`

```json
{'timestamp': 1704825357.78105, 'response': {'id': 'chatcmpl-8fBF7xbxwEfs27aB0CYaa4Xd8Rhm0', 'choices': [{'finish_reason': 'stop', 'index': 0, 'message': {'content': '{"message": "Get ready for an exciting new event coming your way! Stay tuned for more details and mark your calendars for an unforgettable experience!"}', 'role': 'assistant'}}], 'created': 1704825357, 'model': 'gpt-35-turbo', 'object': 'chat.completion', 'system_fingerprint': 'fp_50a4261de5', 'usage': {'completion_tokens': 30, 'prompt_tokens': 31, 'total_tokens': 61}}}
```

#### `s3-bucket-name/request/230a7fd1db82cac4831afb01bf2a777b781faef7ba62127ce38bcf536c162dd3.json`

```json
{'role': 'system', 'content': 'Output JSON obeying: {"message": "string"}'}, {'role': 'user', 'content': 'Write a text message announcing a new event!', 'model': "gpt-4-1106-preview", 'seed': 1234, "user": "362f283e-8f45-4edb-9d6b-7fea2743c8f9"}
```

(This isn't the full response, but you get the idea I think.)

Alternatively, we could store both the request and response in a single file like `230a7fd1db82cac4831afb01bf2a777b781faef7ba62127ce38bcf536c162dd3.json`. This might be less flexible for some folks though..

### Motivation, pitch

Two main reasons:

1. Abuse tracking / compliance. Right now we can easily track which key caused an abuse complaint (with Azure and OpenAI), but we don't actually store a copy of the request itself.
2. Troubleshooting / debugging. I noticed very quickly that I love having the responses stored in S3, but wanted to be able to see what the input request was too (without having to search through LiteLLM logs).

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by Manouchehri** [comment]
I _think_ this would require reworking a bit of `get_cache_key` to output value JSON instead of a non-parsable string.

**Comment by ghost** [comment]
Isn't caching the wrong place to be doing long-term logging? @Manouchehri

**Comment by Manouchehri** [comment]
Ish? You could say this is using long-term logging as the cache source, or using the cache source for long-term logging. Either way I think it ends up being nearly the same, just naming conventions I guess. =)

**Comment by ghost** [comment]
Update from conversation on discord: 
- separate buckets for caching and logging
- why? => a 2nd successive call for an invalid cache response, would overwrite the cached response with the response from llm api call. This is fine for caching, but not fine for audit logs.

**Comment by ishaan-jaff** [comment]
Pr here: https://github.com/BerriAI/litellm/pull/1408

**Comment by ishaan-jaff** [comment]
Live here: https://github.com/BerriAI/litellm/releases/tag/v1.17.1
