### ISSUE TITLE
return llm provider as part of the error type 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#139]
useful for identifying which provider is throwing the error - if it's an invalid key i can rotate between backups 
<img width="510" alt="Screenshot 2023-08-17 at 10 38 10 AM" src="https://github.com/BerriAI/litellm/assets/17561003/bac1e66a-3b75-44ac-9623-1fe8ad8d95c7">

**Comment by ghost** [comment]
closing as this is now supported
