### ISSUE TITLE
[Feature]: Latency-based routing should calculate per output token speed

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#1393]
### The Feature

Follow-up to #1369.

When calculating the latency, we should take into account the number of output tokens.

i.e. instead of calculating based on `ms`, we should calculate based on `output tokens / ms`.

### Motivation, pitch

A request that takes longer to complete might actually be "fast" depending on the amount of output tokens used.

https://community.openai.com/t/gpt-3-5-and-gpt-4-api-response-time-measurements-fyi/237394

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by ghost** [comment]
Great idea! will try and pick this up today

**Comment by ghost** [comment]
@Manouchehri how're you using the latency based routing? Will try and repro the scenario, and test the changes.

**Comment by Manouchehri** [comment]
Not in a scientific way. I was just doing interactive chats, and I noticed LiteLLM seemed to have odd/unexpected routing decisions (e.g. picking Australia East during their peak-hours). Didn't feel faster than the random shuffle in my interactive tests.

**Comment by ghost** [comment]
That's good feedback - i'm going to work on this. 

Currently this is how we're testing this - https://github.com/BerriAI/litellm/blob/main/litellm/tests/test_lowest_latency_routing.py

**Comment by Manouchehri** [comment]
I think that test could be improved by having two prompts:

1. A prompt that gives a really short output on `openai-france-1234.openai.azure.com`
2. A prompt that gives a really long output on `my-endpoint-europe-berri-992.openai.azure.com`

If 100% of the time 24/7 you see that `openai-france-1234.openai.azure.com` is faster, that's suspicious. =P

**Comment by ghost** [comment]
Ok, sounds good.  

Also i realized output tokens wouldn't cover why a model is slow -> a large prompt could also slow down model response. 

Opting for total tokens instead of just completion tokens 

Will test and see if that actually helps things

**Comment by Manouchehri** [comment]
> Opting for total tokens instead of just completion tokens

"It depends".

> Intuition: Prompt tokens add very little latency to completion calls. Time to generate completion tokens is much longer, as tokens are generated one at a time.

https://platform.openai.com/docs/guides/production-best-practices/improving-latencies

https://community.openai.com/t/benchmarking-response-time-for-gpt4-by-context-output-tokens/468848/6?u=manouchehri

**Comment by ghost** [comment]
great that's what i was looking for - fixed - https://github.com/BerriAI/litellm/pull/1394/commits/04afed61bdbe6ec9c4299d4bcfe92ecd633188cf

**Comment by ghost** [comment]
live in v`1.17.0`
