### ISSUE TITLE
[Testing]: Test docker builds pre-publish

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1398]
### The Feature

Add testing for docker builds, before publishing releases. 

Test should cover: 
- [x] passing in config.yaml
- [x] handling 10 `/key/generate` queries 
- [x] have multiple workers 

### Motivation, pitch

multiple users had build issues

**Comment by ghost** [comment]
This PR covers the changes - https://github.com/BerriAI/litellm/pull/1402

And has now been merged in

**Comment by ghost** [comment]
This means every commit will now have Dockerfile.database run,

our pypi + docker image publishes will now also require this test to pass before being published
