### ISSUE TITLE
Is petals supported?

### ISSUE THREAD

**Issue by johnd0e** [BerriAI/litellm#141]
I see this https://github.com/BerriAI/litellm/blob/main/cookbook/liteLLM_Petals.ipynb

But no mentions elsewhere (expected at least [here](https://docs.litellm.ai/docs/completion/supported))

And I haven't figured out how to make [proxy-server](https://github.com/BerriAI/litellm/tree/main/cookbook/proxy-server) work with it.

**Comment by ishaan-jaff** [comment]
Yes we support petals 

Does it work normally for you (without the proxy?)

**Comment by ishaan-jaff** [comment]
fixed docs: https://docs.litellm.ai/docs/completion/supported#petals-models

**Comment by ishaan-jaff** [comment]
@johnd0e if it makes sense happy to hop on a call and help with connecting petals to the proxy. Make sure you're using the latest version of litellm for the petals support

**Comment by johnd0e** [comment]
Have not tried yet

**Comment by ishaan-jaff** [comment]
Can you let me know if it works for you just in the notebook once u try it ? Happy to ensure it works on proxy after too

**Comment by johnd0e** [comment]
1. Notebook works fine.
2. I have updated `litellm` in proxy-server requirements (0.1.381 -> 0.1.425), and tried again.
   `got errorUnable to map your input to a model. Check your input - [...]`
   I tried "stabilityai/StableBeluga2" and "StableBeluga2" with same result.
3. I see this error in server console, but nothing happens in caller - it continues to wait response from server.

**Comment by johnd0e** [comment]
@ishaan-jaff 
I still have no idea how to use petals with proxy server.
