### ISSUE TITLE
Make it easy to get help in docs

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#143]
Tremor docs do a decent job of this - easily connecting you to the community if you need help. 

<img width="1436" alt="Screenshot 2023-08-17 at 6 07 54 PM" src="https://github.com/BerriAI/litellm/assets/17561003/b0688cab-b8ba-4b8f-bb22-a12504e3f349">

I think early stripe also let you just provide feedback / ask for help right from the docs. 

Maybe we can just hyperlink - https://github.com/BerriAI/litellm/issues/new + the discord, letting people create issues / dm on discord if they need help

**Comment by ghost** [comment]
crisp chat added to docs
