### ISSUE TITLE
[Bug]: pip install`litellm[extra_proxy]` doesn't work 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1435]
### What happened?

Ran `pip install 'litellm[extra_proxy]'`

### Relevant log output

```shell
Requirement already satisfied: litellm[extra_proxy] in /usr/local/lib/python3.10/dist-packages (1.17.4)
WARNING: litellm 1.17.4 does not provide the extra 'extra_proxy'
```

**Comment by ghost** [comment]
Was going to use it in the error message if user tried to connect to prisma db but didn't succeed b/c it wasn't in their environment

**Comment by ishaan-jaff** [comment]
that's weird it worked fine for me, just tried it 

<img width="555" alt="Screenshot 2024-01-13 at 11 14 03 AM" src="https://github.com/BerriAI/litellm/assets/29436595/3c1f6d3c-2883-4319-8321-95bccf264d17">

**Comment by ishaan-jaff** [comment]
works with pip too 

<img width="1048" alt="Screenshot 2024-01-13 at 11 16 20 AM" src="https://github.com/BerriAI/litellm/assets/29436595/4fb3c758-cc42-4e31-8756-010368efb954">

**Comment by ishaan-jaff** [comment]
bump @krrishdholakia what was the issue here?
