### ISSUE TITLE
How to enable Vision enhancements for Azure Open AI?

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1438]
### Discussed in https://github.com/BerriAI/litellm/discussions/1433

<div type='discussions-op-text'>

<sup>Originally posted by **kishorek** January 12, 2024</sup>
How can we enable Vision enhancements for Azure Open AI GPT 4 Vision preview? It is suggested to enable it for enhancing the OCR - https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/gpt-with-vision#use-vision-enhancement-with-images

The below parameters need to be added to the payload for `chat/completions`:

```json
"enhancements": {"ocr": {"enabled": true}, "grounding": {"enabled": false}},
    "dataSources": [
        {
            "type": "AzureComputerVision",
            "parameters": {
                "endpoint": "https://<endpoint>.cognitiveservices.azure.com",
                "key": "***",
            },
        }
    ]
</div>

**Comment by ishaan-jaff** [comment]
I think we already support this - perhaps we need to verify + add to docs

**Comment by ishaan-jaff** [comment]
okay so from looking at this we need to pass the following in `extra_body` for Azure Requests:

```
"enhancements": {
            "ocr": {
              "enabled": true
            },
            "grounding": {
              "enabled": true
            }
    },
    "dataSources": [
    {
        "type": "AzureComputerVision",
        "parameters": {
            "endpoint": "<your_computer_vision_endpoint>",
            "key": "<your_computer_vision_key>"
        }
    }],
```

**Comment by ishaan-jaff** [comment]
@kishorek can you test this on 1.17.6 and let me know if it works ?

**Comment by ishaan-jaff** [comment]
https://docs.litellm.ai/docs/providers/azure#usage---with-azure-vision-enhancements

**Comment by kishorek** [comment]
Thanks for the response @ishaan-jaff . Unfortunately, I am getting the below error.

```
Traceback (most recent call last):
  File "<home>/.cache/pypoetry/virtualenvs/litellm_test-px-5zgsC-py3.10/lib/python3.10/site-packages/litellm/llms/azure.py", line 250, in completion
    response = azure_client.chat.completions.create(**data, timeout=timeout)  # type: ignore
  File "<home>/.cache/pypoetry/virtualenvs/litellm_test-px-5zgsC-py3.10/lib/python3.10/site-packages/openai/_utils/_utils.py", line 271, in wrapper
    return func(*args, **kwargs)
TypeError: Completions.create() got an unexpected keyword argument 'enhancements'
```

`litellm==1.17.5`

**Comment by kishorek** [comment]
Tested the same in `1.17.6` from `litellm_bedrock_provisioned_throughput` branch. Still the same error
```
litellm.exceptions.APIError: AzureException - Completions.create() got an unexpected keyword argument 'enhancements'
```

**Comment by ishaan-jaff** [comment]
Hi @kishorek can you try this on the latest version of litellm https://github.com/BerriAI/litellm/releases/tag/v1.17.13 

I'm trying to get this set up on my Azure account too, to test

**Comment by ishaan-jaff** [comment]
was able to test this on my Azure account, fix here: https://github.com/BerriAI/litellm/pull/1475

**Comment by ishaan-jaff** [comment]
@kishorek can you try this release and lmk if it works for you: https://github.com/BerriAI/litellm/releases/tag/v1.17.17 

docs: https://docs.litellm.ai/docs/providers/azure#usage---with-azure-vision-enhancements 

Note,`base_url` needs `/extensions` to work on Azure

**Comment by ishaan-jaff** [comment]
bump on this @kishorek ? can you confirm it's working ?

**Comment by kishorek** [comment]
Hi @ishaan-jaff This is perfect! Its working as expected. Thank you so much. We can close this issue
