### ISSUE TITLE
[Feature]: Support LocalAI https://github.com/mudler/LocalAI

### ISSUE THREAD

**Issue by twardoch** [BerriAI/litellm#1443]
### The Feature

LocalAI ( https://github.com/mudler/LocalAI ) offers a local OpenAI-compatible API that interfaces with locally hosted models like GGUF models using llama.cpp. 

It would be great if LocalAI was "officially" supported as a provider, so that the extended LiteLLM proxy (with fallback etc) could be easily used on llama.cpp 

### Motivation, pitch

I believe it's already possible through the "generic" LiteLLM-OpenAI-like client, but LocalAI seems to offer some additional functionality.

### Twitter / LinkedIn details

@twardoch

**Comment by ghost** [comment]
This is also openai compatible - any provider specific params are passed straight through. What additional work is required here? @twardoch
