### ISSUE TITLE
Add code lint tooling

### ISSUE THREAD

**Issue by yujonglee** [BerriAI/litellm#145]
There's lot of type error in the project. Some fixes are made #144.

Unless we have a specific reason not to use code lint tool, I suggest using `mypy`.

![Screenshot 2023-08-18 at 10 30 25 AM](https://github.com/BerriAI/litellm/assets/61503739/f143cc6c-5d1a-4aec-b092-17f5e9d0b3d4)

**Comment by ghost** [comment]
this sounds good - is this blocking you in some way?

**Comment by yujonglee** [comment]
@krrishdholakia 

I set `litellm = { git = "https://github.com/BerriAI/litellm", rev = "d394c77" }` to use https://github.com/BerriAI/litellm/commit/d394c7762368c974d935ab3b97a458d46ee8c361, but I still got `Any` return type.

<img width="400" alt="Screenshot 2023-08-18 at 11 39 52 AM" src="https://github.com/BerriAI/litellm/assets/61503739/61c8080b-406c-4d01-b04a-9a074cbfc8e4">

Specifying return type as `ModelResponse`(#144) fixes the issue, but AFAIK if typing done right, return type should be inferred automatically. That's why I run mypy to see if it catches something. (Although mypy doesn't complain about return type here...)

**Comment by ishaan-jaff** [comment]
@yujonglee I'm working on this

**Comment by ishaan-jaff** [comment]
Started using https://pypi.org/project/black/#description https://github.com/BerriAI/litellm/commit/15b1da9dc8a9739f3365cfbd96c5421da5a5b4e8

**Comment by ishaan-jaff** [comment]
Commit 2 for this: https://github.com/BerriAI/litellm/commit/fbcb6d1c2002bcc6b15d4859a7c0eac28f09ef3e

**Comment by ishaan-jaff** [comment]
going to make all relevant changes and then add it our workflow

**Comment by ishaan-jaff** [comment]
commit 3: https://github.com/BerriAI/litellm/commit/5e7d22512d1920fe1d6312d1f3dcb901ee75b700

**Comment by ishaan-jaff** [comment]
last one with all fixes !: https://github.com/BerriAI/litellm/commit/1bb2aefea17c52f073de4b12dde70566be506462

**Comment by ishaan-jaff** [comment]
part of our deploy workflows now: https://github.com/BerriAI/litellm/blob/main/.circleci/config.yml#L37 

The current version of litellm passes all tests

**Comment by ishaan-jaff** [comment]
@yujonglee thanks for the suggestion, let me know if there's anything else we can add
