### ISSUE TITLE
[Bug]: invalid user key with Postgres database

### ISSUE THREAD

**Issue by abnerjacobsen** [BerriAI/litellm#1451]
### What happened?

I configured a Litellm proxy server with Postgres, I was able to generate a KEY with an expiration of 24 hours, but when I try to use the generated key to query the available models or generate a completion I receive the following from the LiteLLm API:

```
{
   "detail": "invalid user key"
}
```
Any ideas what could be causing this problem?

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/litellm/proxy/proxy_server.py", line 258, in user_api_key_auth
    expiry_time = datetime.fromisoformat(valid_token.expires)
TypeError: fromisoformat: argument must be str
10.0.1.6:58796 - "GET /models HTTP/1.1" 401
```

**Comment by ishaan-jaff** [comment]
Thanks for the issue, can you share the curl request for how you were creating your key @abnerjacobsen ?

**Comment by ghost** [comment]
I'm seeing some other issues as well. I suspect some bug got pushed and our testing missed it. I'll work on this ticket and add better testing here as well.

**Comment by abnerjacobsen** [comment]
@ishaan-jaff @krrishdholakia I used this command:

```
curl -X 'POST' \
  'http://localhost:4000/key/generate' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer esecret_....' \
  -H 'Content-Type: application/json' \
  -d '{
  "duration": "24h",
  "models": ["gpt-3.5-turbo"],
  "aliases": {},
  "config": {},
  "spend": 0,
  "user_id": "xxxxx",
  "max_parallel_requests": 0,
  "metadata": {"user": "xxxxx", "team": "my_team"}
}'

```

**Comment by ishaan-jaff** [comment]
Fixed here @abnerjacobsen https://github.com/BerriAI/litellm/releases/tag/v1.17.17 

Can you try it and let me know if it's fixed

**Comment by abnerjacobsen** [comment]
Thanks @ishaan-jaff I tested with the new version and was able to create key, use it to get models list/info, make a completation with the allowed models for the key and get an without permission return when try to use a model not allowed for the key.

**Comment by ishaan-jaff** [comment]
awesome, @abnerjacobsen any chance we can hop on a call to better understand your use case and improve for you ? 

sharing a link to my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
