### ISSUE TITLE
[Feature]: Support for Vector Database Semantic Caching

### ISSUE THREAD

**Issue by ranjancse26** [BerriAI/litellm#1454]
### The Feature

This feature request is all about the support for Vector Database driven Semantic Caching. It would be great if there's a support for configurable, multiple vector database(s) such as Pinecone, Qdrant, Weaviate etc. the list goes on.

### Motivation, pitch

The key motivation behind of this feature is based on the inspiration of Portkey semantic cache with the vector database. [reducing-llm-costs-and-latency-semantic-cache](https://portkey.ai/blog/reducing-llm-costs-and-latency-semantic-cache/) 

### Twitter / LinkedIn details

https://www.linkedin.com/in/ranjan-dailata/

**Comment by ishaan-jaff** [comment]
Hi @ranjancse26 thanks for the issue, semantic cache is not a focus for us right now. We're still perfecting our exact match cache implementation. 

closing for now, will re-open when we're considering this

**Comment by ranjancse26** [comment]
@ishaan-jaff Sure, your choice or peference. 

Sorry to say that all the below options of caching the LLM response are not a great or viable option. Redis is too costly and not scalable. S3 bucket is not the right candidate for these. In Memory is being the worst of all :(

LiteLLM supports:

- In Memory Cache
- Redis Cache
- s3 Bucket Cache

**Comment by ghost** [comment]
semantic caching is now supported - https://docs.litellm.ai/docs/caching/redis_cache#initialize-cache---in-memory-redis-s3-bucket-redis-semantic-cache
