### ISSUE TITLE
[Feature]: Support MongoDB for Proxy Key Management

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1455]
### The Feature

Support MongoDB Atlas for Proxy Key Management

### Motivation, pitch

user request cc @sfiodorov

**Comment by ghost** [comment]
We already do this via prisma - 
<img width="508" alt="Screenshot 2024-01-16 at 4 36 47 PM" src="https://github.com/BerriAI/litellm/assets/17561003/d5485341-84ba-44c9-914c-b15a651ce356">

**Comment by ghost** [comment]
https://github.com/RobertCraigie/prisma-client-py

**Comment by ishaan-jaff** [comment]
Can you confirm it works with MongoDB Atlas?

 Our docs ask for a PostgreSQL DB url and the user was confused how this would work with our proxy

**Comment by ishaan-jaff** [comment]
not planned
