### ISSUE TITLE
[Bug]:  Token not allowed to access model

### ISSUE THREAD

**Issue by SharmaSamarth1** [BerriAI/litellm#1460]
### What happened?

Trying mistral with LiteLLM proxy server, but encountered this issue. Any resolutions?

![Uploading Screenshot 2024-01-16 at 4.29.04 PM.png…]()

### Relevant log output

```shell
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/litellm/proxy/proxy_server.py", line 294, in user_api_key_auth
    raise Exception(f"Token not allowed to access model")
Exception: Token not allowed to access model
127.0.0.1:60714 - "POST /chat/completions HTTP/1.1" 401
```

**Comment by SharmaSamarth1** [comment]
Another error arises when using mistral-small model

<img width="1512" alt="Screenshot 2024-01-16 at 6 57 51 PM" src="https://github.com/BerriAI/litellm/assets/156169277/12b35ba3-5cfb-4eda-8409-47a74b420a21">

**Comment by SharmaSamarth1** [comment]
![Uploading Screenshot 2024-01-16 at 4.29.04 PM.png…]()

**Comment by ishaan-jaff** [comment]
Hi @SharmaSamarth1 the 1st error you linked is because the API key you sent the proxy was invalid. Was this resolved for you ?

**Comment by ishaan-jaff** [comment]
<img width="1280" alt="Screenshot 2024-01-16 at 7 48 06 AM" src="https://github.com/BerriAI/litellm/assets/29436595/dd827190-a4b1-4089-91c9-6a0b24402d0c">

I tried mistral-small on the proxy and it worked for me. What's the error/stacktrace you're seeing on the proxy ?

**Comment by SharmaSamarth1** [comment]
No, it still gives me the same error. Even after generating a new API, the token isn't allowed to access the model

**Comment by SharmaSamarth1** [comment]
UnprocessableEntityError error for mistral-small

**Comment by SharmaSamarth1** [comment]
can you send me your config.yaml file for mistral models?

**Comment by ishaan-jaff** [comment]
My config.yaml for mistral

```
model_list:
  - model_name: mistral-small
    litellm_params:
      model: mistral/mistral-small
```

**Comment by ishaan-jaff** [comment]
@SharmaSamarth1 want to hop on a call and debug together? I'm here: https://meet.google.com/vaq-ufng-yhf

**Comment by ishaan-jaff** [comment]
can you send the curl command you're using to create the token?

**Comment by SharmaSamarth1** [comment]
curl 'http://0.0.0.0:3000/key/generate' \
--header 'Authorization: Bearer sk-1234' \
--header 'Content-Type: application/json' \
--data-raw '{"models": ["gpt-3.5-turbo","gpt-3.5-turbo-1106", "gpt-4","gpt-4-vision", "bedrock-claude-v1","bedrock-cohere","bedrock-titan","bedrock-ai21","gpt-4-turbo","vllm-model","mistral-tiny","mistral-small","mistral-medium"], "duration": null,"metadata": {"user": "samarth", "team": "core-infra"}}'

**Comment by SharmaSamarth1** [comment]
- model_name: mistral-tiny
    litellm_params:
      model: mistral/mistral-tiny
      # api_base: https://api.mistral.ai/v1/
     
  - model_name: mistral-small
    litellm_params:
      model: mistral/mistral-small
      # api_base: https://api.mistral.ai/v1/
     
  - model_name: mistral-medium
    litellm_params:
      model: mistral/mistral-medium
      # api_base: https://api.mistral.ai/v1/

**Comment by SharmaSamarth1** [comment]
`  - model_name: mistral-tiny
    litellm_params:
      model: mistral/mistral-tiny
      # api_base: https://api.mistral.ai/v1/
     
  - model_name: mistral-small
    litellm_params:
      model: mistral/mistral-small
      # api_base: https://api.mistral.ai/v1/
     
  - model_name: mistral-medium
    litellm_params:
      model: mistral/mistral-medium
      # api_base: https://api.mistral.ai/v1/`

**Comment by ishaan-jaff** [comment]
oh this looks like a bug with our key/generate and authentication. will investigate

**Comment by SharmaSamarth1** [comment]
any updates?

**Comment by SharmaSamarth1** [comment]
Not able to find out the cost of using gpt-4-vision-preview.
Everything else runs smoothly.
<img width="1512" alt="Screenshot 2024-01-17 at 3 20 18 PM" src="https://github.com/BerriAI/litellm/assets/156169277/9d18708a-5f71-46b2-8ed0-4059f0e3ffc9">

**Comment by ghost** [comment]
v1.17.13 should fix the key issue.

Closing this ticket as i believe it's solved and confirmed by user. 

@SharmaSamarth1 i'm tracking the gpt-4-turbo-preview cost tracking on a separate issue - https://github.com/BerriAI/litellm/issues/1470

tagged you there.
