### ISSUE TITLE
[Bug]: VertexAI model "chat-bison-32k" not working on LiteLLM v1.17.9 - VertexAIException - No module named 'vertexai.preview.generative_models'

### ISSUE THREAD

**Issue by MichaelVandi** [BerriAI/litellm#1463]
### What happened?

**What happened**
Upgraded from LiteLLM v0.8.4  to  v1.17.9. in order to try out Gemini Pro
And used to make completion requests to chat-bison-32, but requests started getting Error

```
VertexAIException - No module named 'vertexai.preview.generative_models'
Failed to make completion. Error: VertexAIException - No module named 'vertexai.preview.generative_models'
Error: APIError: VertexAIException - No module named 'vertexai.preview.generative_models',
```

However, Gemini Pro completion requests worked on model ID "gemini/gemini-pro" using Google AI Studio and LiteLLM v1.17.9
Not sure why "gemini/gemini-pro" works but "chat-bison-32k" doesn't.

So I downgraded to LiteLLM v0.8.4 and "chat-bison-32k" started working as normal, but "gemini/gemini-pro" didn't work.

**Steps to replicate**
- Install LiteLLM v0.8.4
- Make the following VertexAI completion request:

```
{
    "model": "chat-bison-32k",
    "messages": [
        {
            "role": "user",
            "content": "write me a joke about a chicken
        }
    ]
}

```
- Observe that it works

-----

- Upgrade to LiteLLM v1.17.9
- Make the same VertexAI completion request
- Observe that it won't work.

### Relevant log output

```shell
VertexAIException - No module named 'vertexai.preview.generative_models'
Failed to make completion. Error: VertexAIException - No module named 'vertexai.preview.generative_models'
Error: APIError: VertexAIException - No module named 'vertexai.preview.generative_models',
```
```


### Twitter / LinkedIn details

_No response_

**Comment by ishaan-jaff** [comment]
this was caused because `vertex_ai/gemini` requires `vertexai.preview.generative_models` as a dep, can you try running `pip install vertexai.preview.generative_models` and see if that fixes it ? 

Once we confirm this fixes it, will think about how to handle this dependency better

**Comment by ghost** [comment]
I think the right pip install is `pip install "google-cloud-aiplatform>=1.38"`

Just pushed a fix to raise a better exception here, with this ^ pip install

**Comment by ghost** [comment]
@MichaelVandi let me know if that solves it

**Comment by MichaelVandi** [comment]
Thank you @ishaan-jaff  and @krrishdholakia. 
```
pip install "google-cloud-aiplatform>=1.38"
```
Fixed the issue.

I'm noticing responses are a little slower but that might just be the model taking longer.
Thank you. Feel free to close the issue when a fix is deployed to pip

**Comment by ishaan-jaff** [comment]
in prod - @MichaelVandi can you verify it's fixed for you on https://github.com/BerriAI/litellm/releases/tag/v1.17.12

**Comment by ishaan-jaff** [comment]
bump @MichaelVandi ?

**Comment by ghost** [comment]
closing as the exception string is now in prod.

**Comment by MichaelVandi** [comment]
Yes! Sorry for the delay @krrishdholakia and @ishaan-jaff - it's fixed!
