### ISSUE TITLE
[Feature]: Proxy Keys - Get all API Keys from user/info endpoint 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1469]
### The Feature

User needs to see all api keys generated for a user id

They were seeing hashed keys, but need to see sk-*** keys 

### Motivation, pitch

-

**Comment by ghost** [comment]
We intentionally **don't** store the original key, see - https://github.com/BerriAI/litellm/issues/983

I believe this was b/c a user (cc: @Manouchehri) was uncomfortable with real keys being stored in a db, and preferred their hashed equivalents be used instead

**Comment by ghost** [comment]
@ishaan-jaff what was the user who wanted to see the sk-.. trying to achieve?

**Comment by Manouchehri** [comment]
I'm not sure why anyone would need to see the non-hashed version.

They can always hash the `sk-*` values themselves and figure out which is which. =)

**Comment by speedyankur** [comment]
I also noticed that in logs, we are also displaying the the full keys. It could be a mojor security threat. All keys in logs should also be hashed

**Comment by ishaan-jaff** [comment]
@speedyankur you're referring the the LLM API keys or the Proxy API keys ? let's track that in a separate issue

**Comment by ghost** [comment]
@speedyankur closing this issue as i don't think this is planned work. 

Can you let me know where in logs you're seeing the full key displayed? Happy to also create a separate issue to track this.
