### ISSUE TITLE
[Bug]: fix cost tracking for gpt-4-vision-preview

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1470]
### What happened?

User not able to see cost for key when using gpt-4-vision-preview
![image](https://github.com/BerriAI/litellm/assets/17561003/dbbe5496-ed93-4acf-871e-3348dd670eb4)

### Twitter / LinkedIn details

cc: @SharmaSamarth1

**Comment by ghost** [comment]
This is now fixed, we were missing `gpt-4-1106-vision-preview` in the model cost map 

Attaching screenshots to show this now works. No updates required for users. 

<img width="753" alt="Screenshot 2024-01-17 at 10 24 11 AM" src="https://github.com/BerriAI/litellm/assets/17561003/7ee8028d-b6b2-44b6-abc0-024925026dea">

<img width="879" alt="Screenshot 2024-01-17 at 10 24 15 AM" src="https://github.com/BerriAI/litellm/assets/17561003/38945ab9-2f50-4d55-8f37-2555f72aa04b">

**Comment by ghost** [comment]
cc: @SharmaSamarth1
