### ISSUE TITLE
[Feature]: give new model to select users (user groups)

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1474]
### The Feature

- Allow admins to create user groups 
- Allow admins to grant model access on a user group level 

### Motivation, pitch

user request

The admin wants to give a bunch of users access to a new model group. The users have keys which have access to specific models. This means admin has to do some sort of batch process to update each key of each user to add support for the new model group.

**Comment by ghost** [comment]
This is now in prod in v`1.18.0`.
