### ISSUE TITLE
[Feature]: Support boto3 auth via sts 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1476]
### The Feature

Allow user to init a boto3 client for bedrock via sts 

```
def get_bedrock_client():
    sts_response = sts.assume_role(
        RoleArn="arn:aws:iam::xxxx:role/role-name",
        RoleSessionName="my-session-name",
    )

    return boto3.client(
        "bedrock-runtime",
        region_name="us-east-1",
        aws_access_key_id=sts_response["Credentials"]["AccessKeyId"],
        aws_secret_access_key=sts_response["Credentials"]["SecretAccessKey"],
        aws_session_token=sts_response["Credentials"]["SessionToken"],
    )
```

### Motivation, pitch

improve user experience (prev. user was doing this before making litellm completion call - becomes complicated as this needs to be called before making api call, so they now need to start mapping model names to providers to know when to call bedrock)

**Comment by ghost** [comment]
Seems like this would be a simple add 
```
session = boto3.Session()
sts = session.client("sts")
```

**Comment by ghost** [comment]
Should be live soon in v`1.17.16`  - https://github.com/BerriAI/litellm/commit/8e9dc0995522d6f44f4f0030f2be92408189360a
