### ISSUE TITLE
[Bug]: failed call with max parallel requests leads to subsequent call fails 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1477]
### What happened?

"""
Hello, I am currently trying to use the max_parallel_requests: 1 option and at first it works fine but if for any reason the user triggers an error message, now all future requests will result in Max parallel request limit reached. is there anyway to fix this issue?

One error that can cause the issue is picking a model that doesn't exist.

"""

**Comment by ghost** [comment]
able to repro this locally

**Comment by ghost** [comment]
This is inconsistent. I don't see it on consecutive tries. 

I think this might be caused b/c the success/failure hooks we listen to are for the litellm sdk, but there might be server level errors which when triggered would go uncaught and therefore the parallel limit count is not correctly updated.

**Comment by ghost** [comment]
Able to repro by first running: 

Malformed request - 

```bash
curl --location 'http://0.0.0.0:8000/v1/chat/completions' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer sk-JCAEMJMMCwYw2-Vp9J6Y0A' \
--data '{
  "model": "bedrock-claude-v1",
  "messages": [
        {
          "role": "user2",
          "content": "As a restaurant owner, write a professional email to the supplier to get these products every week: \n\n- Wine (x10)\n- Eggs (x24)\n- Bread (x12)"
        }
      ]
}'
```

and then 

```bash
curl --location 'http://0.0.0.0:8000/v1/chat/completions' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer sk-JCAEMJMMCwYw2-Vp9J6Y0A' \
--data '{
  "model": "bedrock-claude-v1",
  "messages": [
        {
          "role": "user",
          "content": "As a restaurant owner, write a professional email to the supplier to get these products every week: \n\n- Wine (x10)\n- Eggs (x24)\n- Bread (x12)"
        }
      ]
}'
```

**Comment by ghost** [comment]
Looks like the async failure handler isn't called

**Comment by ghost** [comment]
Fixed the issue. Looks like that was the issue. 

I think we need better unit testing for max parallel requests to prevent this from happening.

**Comment by ghost** [comment]
Will include that as part of the fix.

**Comment by ghost** [comment]
Fixed + added unit testing https://github.com/BerriAI/litellm/commit/1ea3833ef7dad9d8fb6be32d724a5d81e496d358

**Comment by ghost** [comment]
should be live soon in v`1.18.2`

**Comment by ghost** [comment]
Reopening as user says this still wasn't fixed for them. 

Their test: 

Steps I took to test
POST /chat/completions with a valid request
POST /chat/completions with an invalid model
POST /chat/completions with an invalid model once more
POST /chat/completions with a valid request
Now all future requests for the auth token result in
{"detail": "Max parallel request limit reached."}

**Comment by ghost** [comment]
their /key/generate call: 

```
    POST /key/generate
    BODY {
        "max_parallel_requests": 1,
        "duration": null,
        "user_id": "example@example.com"
    }
```

**Comment by ghost** [comment]
Unable to repro with a key generated like this: 

```
POST /key/generate
BODY {"models": ["beta-models"], "aliases": {"mistral-7b": "gpt-3.5-turbo"}, "duration": "1hr"}
```

**Comment by ghost** [comment]
Able to repro with user example 

```
    POST /key/generate
    BODY {
        "max_parallel_requests": 1,
        "duration": null,
        "user_id": "example@example.com"
    }
```

**Comment by ghost** [comment]
looks like this is the issue: 

```
Inside Max Parallel Request Failure Hook
An exception occurred - 'litellm_params'
```

line: 
> user_api_key = kwargs["litellm_params"]["metadata"]["user_api_key"]

**Comment by ghost** [comment]
this is fixed now
