### ISSUE TITLE
Using caching prevents trying multiple LLM providers with the same prompt

### ISSUE THREAD

**Issue by yujonglee** [BerriAI/litellm#148]
https://github.com/BerriAI/litellm/blob/acbb611e8997b5fb00015dbd3c0ccb9546029254/litellm/utils.py#L150

**Comment by ishaan-jaff** [comment]
cc @krrishdholakia

**Comment by ishaan-jaff** [comment]
@yujonglee should we cache using 'model + prompt' as the key ?

**Comment by ghost** [comment]
We can check if a local cache for that model exists and if the prompt exists inside that? 

or a model + prompt key combination - local_cache[model + " " + prompt] 

I can look more into this in a bit. @yujonglee why're you using caching?

**Comment by ishaan-jaff** [comment]
@yujonglee added support for you use case: https://docs.litellm.ai/docs/caching#usage

**Comment by yujonglee** [comment]
@ishaan-jaff  Awesome!
