### ISSUE TITLE
[Feature]: Cost Tracking for individual LLM + Introduction of time in verification table 

### ISSUE THREAD

**Issue by SharmaSamarth1** [BerriAI/litellm#1487]
### The Feature

1. Can you include a feature to track the specific costs spent by an LLM?
2. A time(column) in the verification table would be beneficial to track the total spend of a user over a period of time.

### Motivation, pitch

Cost Tracking

**Comment by ishaan-jaff** [comment]
Hi @SharmaSamarth1 thanks so much for this issue ! 

From my understanding it sounds like we'll need a new Spend Table with the following columns:

- Key (sk-**)
- Cost ($0.12)
- LLM / Model used
- Datetime (12/01/2023 9:00am)

**Comment by ishaan-jaff** [comment]
okay discussed with @krrishdholakia - we're going to go with making a new Spend Tracking Table 

@SharmaSamarth1 any feedback on the table schema, what would be ideal for you?

**Comment by ghost** [comment]
Sharing tentative schema 

```
create table
  public.litellm_logs (
    id bigint generated by default as identity,
    created_at timestamp with time zone null default now(),
    model text null default ''::text,
    messages json null default '{}'::json,
    response json null default '{}'::json,
    end_user text null default ''::text,
    error json null default '{}'::json,
    response_time real null default '0'::real,
    total_cost real null,
    additional_details json null default '{}'::json,
    constraint litellm_logs_pkey primary key (id)
  ) tablespace pg_default;
```

**Comment by ghost** [comment]
Alt schema (we already support most of this for langfuse + dynamodb) 

```
            payload = {
                "id": id,
                "call_type": call_type,
                "startTime": start_time,
                "endTime": end_time,
                "model": kwargs.get("model", ""),
                "user": kwargs.get("user", ""),
                "modelParameters": optional_params,
                "messages": messages,
                "response": response_obj,
                "usage": usage,
                "metadata": metadata,
                "cost": cost
            }
```

**Comment by ishaan-jaff** [comment]
working on this now

**Comment by ishaan-jaff** [comment]
PR here: https://github.com/BerriAI/litellm/pull/1498

**Comment by ishaan-jaff** [comment]
@SharmaSamarth1 This feature is Live here: https://github.com/BerriAI/litellm/releases/tag/v1.18.4 

- Can you try it and let me know if it works for you?
- I'd love to hop on a quick call and better understand your use case - any chance you're free sometime this week, next ? 
Sharing my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by ishaan-jaff** [comment]
@SharmaSamarth1 wanted to follow up - is the SpendLogs table what you were looking for here ?
