### ISSUE TITLE
Allow <provider_name> as part of model name

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#149]
It would be easier for me on the frontend if i could just pass in the custom llm provider as part of the model name. 

Maybe we can just establish convention: <provider_name>_<model_name>?

**Comment by ghost** [comment]
This simplifies my code as i can -> get the available model list from my backend server -> render it to my users with some key mapping -> and then make a call based on what they select, without needing to create conditional logic based on model name - mapping to which provider it should be.

**Comment by ishaan-jaff** [comment]
togetherAI does this pretty well, they do 
`togethercomputer/llama2`

**Comment by ghost** [comment]
closing as this is done in - 6cee3b22abddada80fa2f4895545ce9bebe4443c
