### ISSUE TITLE
Add an example on how to deploy litellm on a render server 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#15]
cc @zakhar-kogan

**Comment by ishaan-jaff** [comment]
We should add a Deploy on Railway button on our Readme or make it easier to discover the proxy

cc @krrishdholakia let's do this after your work on proxy today

**Comment by zakhar-kogan** [comment]
Ugh, I hearted and missed that 👀
Should be workable with a package.json for most providers; will check out, too

**Comment by ishaan-jaff** [comment]
this is done - check litellm proxy or ab testing server
