### ISSUE TITLE
[Feature]: Build and push the docker image for the Admin UI

### ISSUE THREAD

**Issue by ShaunMaher** [BerriAI/litellm#1503]
### The Feature

I'm working on a helm deployment for LiteLLM on Kubernetes.  I'd like to be able to include the Admin UI as an installable option but this project doesn't build an image for the Admin UI.

I could build and host it in my fork of this project but I'd prefer to have the Helm chart merged back into this project (when it's ready) and I don't want it to have references to my fork.

### Motivation, pitch

I haven't worked with Github actions much but I think I can see how the existing builds work.  Copy and paste and tweak some labels is within my skillset.  Hopefully I can implement this myself and submit it back as a PR.

**Comment by ghost** [comment]
Hi @ShaunMaher seeing this now, we're looking at the PR now.

**Comment by ghost** [comment]
Merged! 

How're you trying to use litellm proxy? @ShaunMaher

**Comment by ishaan-jaff** [comment]
done
