### ISSUE TITLE
[Bug]: proxy /routes endpoint does not honor custom_auth

### ISSUE THREAD

**Issue by bufferoverflow** [BerriAI/litellm#1516]
### What happened?

I used the following custom_auth.py function:

```python
from litellm.proxy._types import UserAPIKeyAuth
from fastapi import Request

async def user_api_key_auth(request: Request, api_key: str) -> UserAPIKeyAuth:

    print(request.url)
    print(request.method)

    if str(request.url).endswith("/models") and request.method == "GET":
        return UserAPIKeyAuth()
    elif str(request.url).endswith("/chat/completions") and request.method == "POST":
        return UserAPIKeyAuth()
    elif str(request.url).endswith("/completions") and request.method == "POST":
        return UserAPIKeyAuth()
    else:
        return False
```

with the following within proxy.yml:

```yml
general_settings: 
  custom_auth: custom_auth.user_api_key_auth
```

Somehow the routes endpoint does not reach my custom auth handler.

**Comment by ghost** [comment]
Routes is an unprotected endpoint. Would you rather it be a protected endpoint (meaning it requires passing an auth check)?

**Comment by bufferoverflow** [comment]
I think every endpoint must be handled if a `custom_auth` handler is used. At least from a user perspective I would say this is the expected behavior.

**Comment by ghost** [comment]
Ok, that's helpful to understand. I'll work on this.

**Comment by ghost** [comment]
Curious - how're you using custom auth here? @bufferoverflow

**Comment by ghost** [comment]
Documenting 'unprotected endpoints': 
- [x] `/routes`
- [x] `/`
- [x] `/health/liveliness`
- [x] `/health/readiness`
- [x] `/test`
- [x] `/config/yaml`

**Comment by ghost** [comment]
Hi @bufferoverflow this should now be supported in v`1.18.7`. Can you let me know if this solves your problem?

**Comment by bufferoverflow** [comment]
I just verified, works now perfectly fine. Thanks a lot @krrishdholakia !
