### ISSUE TITLE
[Bug]: litellm doesnt "see" the ollama  serve on wsl on Windows

### ISSUE THREAD

**Issue by HyperUpscale** [BerriAI/litellm#1517]
### What happened?

The issue is - I have ollama running on a wsl, so Dockers, browsers and any other application sees ollama running, only litellm doesn't seem to find it.  
I tried different installations litellm and litellm[proxy] also tried with config file (maybe wrong), also try to install litellm on another docker and also on another wsl, another python virtual environment,  but regardless - litellm can't find the running ollama service.

![image](https://github.com/BerriAI/litellm/assets/126105457/d7261f89-9d18-41bc-922e-f56ade199322)

Always the same persistent problem:
Field "model_list" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(

            **LiteLLM Warning: proxy started with `ollama` model
`ollama serve` failed with Exception[WinError 2] The system cannot find the file specified.
Ensure you run `ollama serve`**

What do I need to do on my Windows?

**Comment by bvac78** [comment]
I am getting the same error . Where you able to find a solution?

**Comment by HyperUpscale** [comment]
I haven't found a solution yet...  ^0_0^

**Comment by matbee-eth** [comment]
try using the hostname: `host.docker.internal`

**Comment by HyperUpscale** [comment]
I really don't get... it is not about the host (even that seem to be the problem if we have many IPs and hostnames) it is something about the defaults.

**litellm --model ollama/mistral** doesn't work... for unknown reason

While I tested with simple python call - then it works: 
```
from litellm import completion
response = completion(
    model="ollama/mistral", 
    messages=[{ "content": "Tell me in two word who are you? ","role": "user"}], 
)
print(response)
```

![image](https://github.com/BerriAI/litellm/assets/126105457/35bd2d1a-eb60-45a7-abe1-28a13ef594e8)


**Which tells me the problem seem to be in the defaults on the litellm "--model" option.**
 IDK

**Comment by HyperUpscale** [comment]
TRIED: using the hostname: host.docker.internal

This fix worked on similar problem of another project... on Dialoqbase, but doesn't work on litellm 😂

**Comment by Colinw2292** [comment]
I too am having the same problem

**Comment by ghost** [comment]
hey, i'm the maintainer - i'm not sure what the solution here is, since i don't have a similar environment to repro. If someone discovers the issue, we'd welcome a pr here!

**Comment by matbeedotcom** [comment]
> TRIED: using the hostname: host.docker.internal This fix worked on similar problem of another project... on Dialoqbase, but doesn't work on litellm 😂

I expose the host network to the containers just to make life easier. `docker run --net=host ...` (if youre running under docker)
I also set the default WSL2 `networkingMode` to "mirrored"
https://learn.microsoft.com/en-us/windows/wsl/wsl-config#configuration-settings-for-wslconfig

```sh
sudo docker run -d --gpus=all --ipc=host --network=host -v /home/matbee/ollama:/root/.ollama -p 11434:11434 ollama/ollama
```

```yaml
(base) matbee@hostname:~/dev/litellm$ cat config.yaml 

model_list:
  - model_name: ollama-codellama
    litellm_params:
      model: ollama/codellama:70b
      api_base: http://0.0.0.0:11434
      rpm: 1440
    model_info: 
      version: 2

litellm_settings:
  drop_params: True
  set_verbose: True

```

```docker-compose.yaml

(base) matbee@hostname:~/dev/litellm$ cat docker-compose.yaml 
version: "3.9"
services:
  litellm:
    network_mode: host
    build:
      context: .
      args:
        target: runtime
    image: ghcr.io/berriai/litellm:main-latest
    ports:
      - "8000:8000"
    volumes:
      - ./config.yaml:/app/config.yaml
    command: [ "--config", "/app/config.yaml", "--port", "8000", "--num_workers", "6" ]

```

**Comment by thiswillbeyourgithub** [comment]
I was struggling a lot to connect my networks and finally figured out it was due do a ufw misconfiguration: `sudo ufw allow 11434/tcp` did the trick!

**Comment by zmdw** [comment]
I want to be able to access the ollama mirror service on an intranet server in the mirror image of a local computer, but the access has been failed, and the code I wrote locally is accessible.
` - model_name: "qwen2.5:72b"
    litellm_params:
      model: "ollama/qwen2.5:72b"
      api_base: "http://10.78.97.33:11434"`  `import litellm
# call async_ollama
import asyncio
async def async_ollama():
    response = await litellm.acompletion(
        model="ollama/qwen2.5:72b",
        messages=[{"content": "what's the weather", "role": "user"}],
        api_base="http://10.78.97.33:11434",
        stream=True
    )
    async for chunk in response:
        print(chunk)


asyncio.run(async_ollama())
`
