### ISSUE TITLE
[Bug]: Router - Fallbacks with Usage Based Routing not working 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1518]
### What happened?

Update: I think the bug can be identified in the log_success_event() function

When I print out this value = https://github.com/BerriAI/litellm/blob/main/litellm/router_strategy/lowest_tpm_rpm.py#L47
It is always for model0, even if the fallbacl model1 or model2 was called. Therefore, the TPM cache for the fallback models is never being updated. Therefore, the tpm_dict is always Nonehttps://github.com/BerriAI/litellm/blob/main/litellm/router_strategy/lowest_tpm_rpm.py#L145. The TPM and RPM of the fallback models should be updated when the system is in a fallback state

**Comment by georgeseifada** [comment]
Code used for test.
Expected behaviour is that the request immediately falls back to `openai-gpt-4`, which validates that the fallback can happen through multiple layers according to the TPM limits and usage. 

```python
iimport os
import litellm
from litellm import Router
from dotenv import load_dotenv

load_dotenv()

# Constants for TPM and RPM allocation
AZURE_FAST_TPM = 3
AZURE_BASIC_TPM = 2
OPENAI_TPM = 2000
ANTHROPIC_TPM = 100000

def get_azure_params(deployment_name: str):
    params = {
        "model": f"azure/{deployment_name}",
        "api_key": os.environ["AZURE_OPENAI_KEY"],
        "api_version": os.environ["AZURE_API_VERSION"],
        "api_base": os.environ["AZURE_OPENAI_ENDPOINT"]
    }
    return params

def get_openai_params(model: str):
    params = {
        "model": model,
        "api_key": os.environ["OPENAI_API_KEY"],
        "organization": os.environ["OPENAI_ORG_ID"],
    }
    return params

def get_anthropic_params(model: str):
    params = {
        "model": model,
        "api_key": os.environ["ANTHROPIC_API_KEY"],
    }
    return params

model_list = [
    {
        "model_name": "azure/gpt-4-fast",
        "params": get_azure_params("gpt-4-fast"),
        "tpm": AZURE_FAST_TPM
    },
    {
        "model_name": "azure/gpt-4-basic",
        "params": get_azure_params("gpt-4-basic"),
        "tpm": AZURE_BASIC_TPM
    },
    {
        "model_name": "openai-gpt-4",
        "params": get_openai_params("gpt-4"),
        "tpm": OPENAI_TPM
    },
    {
        "model_name": "anthropic-claude-instant-1.2",
        "params": get_anthropic_params("claude-instant-1.2"),
        "tpm": ANTHROPIC_TPM
    }
]

fallbacks_list = [
    {"azure/gpt-4-fast": ["azure/gpt-4-basic"]},
    {"azure/gpt-4-basic": ["openai-gpt-4"]},
    {"openai-gpt-4": ["anthropic-claude-instant-1.2"]},
]

router = Router(
    model_list=model_list,
    fallbacks=fallbacks_list,
    set_verbose=True,
    routing_strategy="usage-based-routing",
    redis_url=os.environ["REDIS_URL"]
)

messages = [{'content': 'Tell me a joke.', 'role': 'user'}]

response = router.completion(model="azure/gpt-4-fast", messages=messages, n=10, timeout=5)

```

**Comment by ishaan-jaff** [comment]
This is a bad request, I'm assuming this is intentional @georgeseifada ? 

```
messages = [
    {"content": "Tell me a joke.", "modality": "voice"},
]

response = router.completion(model="azure/gpt-4-fast", messages=messages, n=10, timeout=5)
```

**Comment by georgeseifada** [comment]
My mistake, I copied the code over wrong. Corrected now in the original comment. It should be 

```
messages = [{'content': 'Tell me a joke.', 'role': 'user'}]
```

**Comment by ishaan-jaff** [comment]
Okay, what would you expect to happen here, on the success call it goes to `azure/gpt-4-fast` and works

did you issue 100 requests ?

**Comment by georgeseifada** [comment]
> Okay, what would you expect to happen here, on the success call it goes to `azure/gpt-4-fast` and works
> 
> did you issue 100 requests ?

- The `AZURE_FAST_TPM` and `AZURE_BASIC_TPM` are lower than the actual number of tokens in the first message. Therefore, it should skip those model groups and go to the `openai-gpt-4` group on the first request. 
- As we send many more requests in a row, the TPM will also eventually exceed the `OPENAI_TPM = 2000`, in which case the system should fall back to `anthropic-claude-instant-1.2`

To test this, I just set up a `while` loop sending the same message over and over, with `n=10` which makes the request big.

**Comment by georgeseifada** [comment]
Actually, it's probably even easier to simulate if we set n to a very big number like `n=30`. I just tried it and the total tokens used was 407, so it should hit the limit of the `openai-gpt-4` in a small number of requests

**Comment by ishaan-jaff** [comment]
okay, made some improvements
In this log it tries, azure/gpt-4-fast -> No Models Available, azure/gpt-4-basic -> No Models Available, OpenAI GPT-4. The request works since it has TPM 

@georgeseifada is this correct ? 

```shell
LiteLLM Router - INFO: get_available_deployment for model: azure/gpt-4-fast, No deployment available
LiteLLM Router - INFO: litellm.completion(model=None) Exception No models available.
LiteLLM Router - INFO: get_available_deployment for model: azure/gpt-4-basic, No deployment available
LiteLLM Router - INFO: litellm.completion(model=None) Exception No models available.
LiteLLM Router - INFO: get_available_deployment for model: openai-gpt-4, Selected deployment: {'model_name': 'openai-gpt-4', 'litellm_params': {'model': 'gpt-3.5-turbo', 'api_key': 'sk-PhEM****', 'tpm': 2000}, 'tpm': 2000, 'model_info': {'id': '5a4b95fa-c018-4767-85c2-c4851c57cf34'}} for model: openai-gpt-4
LiteLLM Router - INFO: litellm.completion(model=gpt-3.5-turbo) 200 OK
```

**Comment by ishaan-jaff** [comment]
PR here: https://github.com/BerriAI/litellm/pull/1525

**Comment by georgeseifada** [comment]
Nice! Yes, that looks correct.

To confirm: Let's say that we have `AZURE_BASIC_TPM = 1000` and it has 2 models (we'll call them `model-a` and `model-b`) in the model group. Then at some point, we pass the TPM limit for `model-a`. It should still call `model-b` before going to the fallback, right?

**Comment by ishaan-jaff** [comment]
Can you clarify this a bit more - not sure I fully understood this

**Comment by georgeseifada** [comment]
Sure.

Let's say we have a model group with two models in it, `model-a` and `model-b`. Then at some point, we exceed the TPM limit (set in the `litellm_params`) for `model-a` only; but for `model-b` we are still under the limit. Will `model-b` then be called _before_ going to the fallback of the next group?

**Comment by ishaan-jaff** [comment]
writing a test case for this scenario rn

**Comment by ishaan-jaff** [comment]
Test added here too: https://github.com/BerriAI/litellm/pull/1525/files
