### ISSUE TITLE
[Feature]: Unit Testing for each litellm proxy endpoint 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1521]
### The Feature

Add unit testing for each litellm proxy endpoint 

### Motivation, pitch

stable releases

**Comment by ghost** [comment]
We currently have this for /key/generate and /chat/completions. Documenting the remaining endpoints: 

- [x] /models 
- [x] /model/new
- [x] /model/info
- [x] /model/delete 
- [x] /completions 
- [x] /embeddings 
- [x] /images/generations
- [x] /key/update
- [x] /key/delete 
- [x] /key/info 
- [x] /user/new
- [x] /user/info 
- [x] /health 
- [x] /health/readiness
- [x] /health/liveliness
- [x] /routes

**Comment by ghost** [comment]
Realized we don't allow a user to call `/model/info` to see all models they have access to. 

Just enabled that and added a test to assert it's only info about models they have access to

**Comment by ghost** [comment]
Realized /key/info returns the hashed token. Removing that.

**Comment by ghost** [comment]
Just pushed support - https://github.com/BerriAI/litellm/commit/f5ced089d6f0af05600062e25a981fdabebba815
