### ISSUE TITLE
[Bug]: palm/code-bison missing in the list

### ISSUE THREAD

**Issue by toniengelhardt** [BerriAI/litellm#1522]
### What happened?

`palm/code-bison` model missing in the list.

<img width="664" alt="Screenshot 2024-01-19 at 18 59 15" src="https://github.com/BerriAI/litellm/assets/2703233/83fe31c2-d8dd-4632-b9d2-a47ef4c8fb1c">

**Comment by ishaan-jaff** [comment]
hmm I don't see it here: https://ai.google.dev/models/palm

**Comment by toniengelhardt** [comment]
Ah ok, that means it doesn't exist?

**Comment by ishaan-jaff** [comment]
Yup, I think so or they don't officially support it

**Comment by toniengelhardt** [comment]
Ok, sorry for the confusion. Closing...
