### ISSUE TITLE
vertex ai demo notebook not working

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#154]
I followed the demo notebook - https://github.com/BerriAI/litellm/blob/main/cookbook/liteLLM_VertextAI_Example.ipynb
<img width="944" alt="Screenshot 2023-08-19 at 5 08 04 PM" src="https://github.com/BerriAI/litellm/assets/17561003/78c283eb-0a08-4534-940c-e1b8194021df">

and got this error

I tried to install vertexai (`pip install vertexai`) but still hit this error

**Comment by ishaan-jaff** [comment]
vertex ai works only on local machines not on colab

**Comment by ishaan-jaff** [comment]
@krrishdholakia can you try it on your local env

**Comment by ghost** [comment]
what the ..
