### ISSUE TITLE
[Feature]: Semantic Cache Support GPTCache to OpenAI Proxy and python API

### ISSUE THREAD

**Issue by giyaseddin** [BerriAI/litellm#1541]
### The Feature

This enhancement aims to extend LiteLLM's support for Semantic Cache by integrating GPTCache with Redis. Currently, LiteLLM interacts with various LLM APIs. By incorporating GPTCache, we seek to optimize data retrieval and storage, specifically within the OpenAI Proxy and Python API. This technical improvement aims to enhance performance and responsiveness, providing a more efficient caching mechanism for LiteLLM users.
It's so easy to integrate it, it needs a memory vector db like Chroma config to be setup.

https://github.com/zilliztech/GPTCache

### Motivation, pitch

It's a cost saving feature, and desired in all LLM use cases.

**Comment by ghost** [comment]
Hi @giyaseddin do you already use semantic caching today? 

I remember trying it and didn't find it to be helpful (higher number of inaccurate responses)

**Comment by rootux** [comment]
Yes this is needed. 🙂

Ideally something such as this - see below KNN k nearest neighbor implementation on redis  as a vector db -

https://redis.io/docs/get-started/vector-database/

**Comment by ishaan-jaff** [comment]
Pr here: https://github.com/BerriAI/litellm/pull/1829 @rootux @giyaseddin

**Comment by ishaan-jaff** [comment]
Live @rootux @giyaseddin https://github.com/BerriAI/litellm/releases/tag/v1.22.10 

Can I get help with testing this since it's relatively new

**Comment by ishaan-jaff** [comment]
Hi @giyaseddin @rootux  any chance we can hop on a call to better understand how we can improve litellm for you ?

Link to my cal for your convenience
https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat?month=2024-02
