### ISSUE TITLE
[Feature]: Track token usage per key (spend logs?) 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1549]
### The Feature

Add token usage to spend logs 

### Motivation, pitch

"We are initially going to provide observability at the app level to the admins and the app owners, ie a breakdown of tokens and costs per app (ie per key). Within each app report we’ll then break down usage per user, so that app owners can identify who is driving up their cost."

**Comment by ghost** [comment]
This might be a no-op as we already track usage as part of the spend logs table - https://github.com/BerriAI/litellm/blob/01a2514b98f99344213b0a16fc90c6c73b65f289/schema.prisma#L56

Reached out to user to see if this solves it.

**Comment by ghost** [comment]
Support added for logging this for streaming too
