### ISSUE TITLE
[Bug]: Support Azure GPT-Vision Streaming

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1553]
### What happened?

I tried this and it was not working, Azure GPT Vision returns streaming responses weirdly

**Comment by Manouchehri** [comment]
What issue are you seeing? I ran a few tests locally with streaming enabled and it _seems_ to be working for me.

**Comment by ghost** [comment]
bump? @ishaan-jaff

**Comment by Manouchehri** [comment]
Azure blocked off new deployments completely for GPT-4 Vision temporarily, so I wonder if you were just seeing issues in general due to overloaded servers.

**Comment by ishaan-jaff** [comment]
this works well
