### ISSUE TITLE
[Feature]: completion_cost() support for image generation 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1558]
### The Feature

Have completion_cost support image generation models 

We already have all the pricing in model_cost_map 

### Motivation, pitch

enable consistent spend tracking

**Comment by ghost** [comment]
This is now added - https://github.com/BerriAI/litellm/commit/ac131b382413c1dd520cc4f7c45363e3792923f7

```python
cost = litellm.completion_cost(
        model="dall-e-2", size="1024-x-1024", quality="standard", n=1
    )
```
