### ISSUE TITLE
Fix litellm Docs Image 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#157]
Currently docs appear as the following when they are unfurled on twitter 

<img width="532" alt="Screenshot 2023-08-21 at 7 29 09 AM" src="https://github.com/BerriAI/litellm/assets/29436595/578c7c40-432d-432a-b730-65b05ccf6d43">

cc @NANDINI-star this might be a good issue to tackle based on your previous work on the docs

**Comment by NANDINI-star** [comment]
@ishaan-jaff oops i didn't get a notification for this. sure looking into it.
