### ISSUE TITLE
[Feature]: Proxy - Alerting, show logs for hanging request 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1586]
### The Feature

> ive integrated the Slack alerting in LiteLLM and i face the following slack message
> Level: Medium
> Message: Requests are hanging - 500s+ request time
> any way of customizing the message/making it more detailed? What request exactly took 500+s request time here? lil tough to debug from just the litellm logs

### Motivation, pitch

-

**Comment by ghost** [comment]
@ishaan-jaff i assume you're taking this?

**Comment by ishaan-jaff** [comment]
yes @krrishdholakia

**Comment by ishaan-jaff** [comment]
Tracking what the user asked for :

> So ideally, what i would need is more details on the slack alert provided so that i can understand from a glance which request/attempt is causing this issue
> and i would need some trace in the message so that i can search my LiteLLM logs to see the region where the problem came up for further debugging
> for referring to LiteLLM logs and debugging further
> something as simple as timestamp goes a long way 
> thats all id need to know where in the logs the problem occurred

**Comment by ishaan-jaff** [comment]
- What Request/Attempt is causing the issue 
- Some Trace to search my  LiteLLM logs
- something as simple as timestamp is a good place to start

**Comment by ishaan-jaff** [comment]
We also had a bug where it sends the alert for all requests, it does not even check if the request is returned
