### ISSUE TITLE
[Feature]: Proxy - DynamoDB - allow users to set their ARN Numbers

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1587]
### The Feature

> The reason this happens is that my litellm proxy EKS is deployed in one AWS account, whereas the DynamoDB tables exist in another AWS account, but the policy does allow cross connect of services. So for this to work, I need litellm proxy to use my provided ARN for the other account and assume that role, but just not sure how I can configure or change to make this happen, something in spirit like this:
> 
> 
> import boto3
> 
>  
> 
> # Assume the role
> 
> sts_client = boto3.client('sts')
> 
> assumed_role = sts_client.assume_role(
> 
>     RoleArn='arn:aws:iam::ACCOUNT_ID:role/ROLE_NAME',
> 
>     RoleSessionName='ExampleSessionName'
> 
> )
> 
>  
> 
> # Use the temporary credentials that AssumeRole returns to make a new session
> 
> session = boto3.Session(
> 
>     aws_access_key_id=assumed_role['Credentials']['AccessKeyId'],
> 
>     aws_secret_access_key=assumed_role['Credentials']['SecretAccessKey'],
> 
>     aws_session_token=assumed_role['Credentials']['SessionToken'],
> 
> )
> 
>  
> 
> # Now you can use this session to call AWS services
> 
> dynamodb = session.client(‘dynamodb’)
> 
>  
> 
> I could probably hack code but just wanted to run it by you dealing with this strange predicament.

### Motivation, pitch

-

**Comment by ghost** [comment]
We support this today for Bedrock, would that solve this? 

<img width="1160" alt="Screenshot 2024-01-24 at 10 06 47 AM" src="https://github.com/BerriAI/litellm/assets/17561003/73afd574-4943-4e2b-8b59-b9fb7a02416e">

**Comment by ishaan-jaff** [comment]
how would this solve an issue for dynamoDB that uses `aiodynamo` ? @krrishdholakia

**Comment by ghost** [comment]
you can pass in aws_role_name and session name in the above code snippet - i assume that's what solves the issue?

**Comment by ishaan-jaff** [comment]
closing as not planned
