### ISSUE TITLE
Add Provider name before models 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#159]
<img width="832" alt="Screenshot 2023-08-21 at 8 34 17 AM" src="https://github.com/BerriAI/litellm/assets/29436595/95a7a30d-5134-4b54-b42a-60acf5be64c5">

litellm.model_list does not show what model is openrouter vs anthropic vs hugging face 

cc @zakhar-kogan

**Comment by zakhar-kogan** [comment]
Tried to implement a solution here: f8e072b, please have a look @ishaan-jaff 
- Every model goes in a dict instead of list of lists ⇢ easily callable
- Made a small function to pull Openrouter models (not sure if it should even go into `init.py` though), potentially a solution for #147 ?
