### ISSUE TITLE
[Bug]: Set tpm/rpm limits to none if not set

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1594]
### What happened?

inconsistent setting of tpm/rpm limits (either sys.maxsize or None) 

### Twitter / LinkedIn details

cc: @Manouchehri

**Comment by ghost** [comment]
fix pushed - https://github.com/BerriAI/litellm/commit/39d5407e67e2caacaaa71b3b456dd07853e06489
