### ISSUE TITLE
[Bug]: old keys with undefined budgets are all now considered to be over the limit 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1598]
### What happened?

keys with undefined budgets are assumed to have budget 0, causing any requests to them to be over the limit 

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/litellm/proxy/proxy_server.py", line 416, in user_api_key_auth
    raise Exception(
Exception: ExceededTokenBudget: Current spend for token: 12.01643300000001; Max Budget for Token: 0.0
```

### Twitter / LinkedIn details

@Manouchehri

**Comment by ishaan-jaff** [comment]
Fixed here :https://github.com/BerriAI/litellm/commit/25332b4a60ab406b3a63d4368df29b3ce8d9bc10

**Comment by ishaan-jaff** [comment]
We even had a test for this exact scenario

**Comment by ghost** [comment]
So how did that not catch this? 😕 @ishaan-jaff

**Comment by ghost** [comment]
@ishaan-jaff i don't think your commit would fix this for keys which have already been created. Can we add a flag to ignore max budget if it's set to 0.0?

**Comment by ishaan-jaff** [comment]
> i don't think your commit would fix this for keys which have already been created

Yes it would fix it, `max_budget=0` is a  default only on versions > 1.18.10 and < 1.19.0 
If you had keys prior to that this is not an issue cc @Manouchehri 

> Can we add a flag to ignore max budget if it's set to 0.0?

I don't think this is a good idea, I don't see the value in adding a flag for a very small amount of versions
Open to adding a patch to the repo if other users complain about this

**Comment by ishaan-jaff** [comment]
Pushed a test for this scenario too: https://github.com/BerriAI/litellm/commit/3e59a02dfb451f52c6e3b2a534165ea092c8f38d

where max_budget == None

**Comment by ishaan-jaff** [comment]
will leave this issue open until I hear back from @Manouchehri on setting a flag for ignoring max budget if it's set to 0.0

**Comment by ishaan-jaff** [comment]
closing this, heard from impacted user 

> "yeah i'm gonna reset it regardless"
