### ISSUE TITLE
Sweep: map args to openai-python args for completion + embedding 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#16]
Feels like i have to keep adding one-off args for individual situations - e.g. max tokens. Would be easier to just have the openai-python args at the top level, and then we can figure out the mapping within the functions.

**Comment by ghost** [comment]
just doing this with `completion` as v1 would be great

**Comment by ishaan-jaff** [comment]
this is addressed in the new version litellm, check main.py
