### ISSUE TITLE
Show me the full error on https://admin.litellm.ai 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#160]
<img width="1280" alt="Screenshot 2023-08-21 at 8 58 35 AM" src="https://github.com/BerriAI/litellm/assets/29436595/bc2df489-9eec-447a-abd3-c45023ffd3b3">

I need to see the full error on the admin.litellm.ai

**Comment by NANDINI-star** [comment]
please point me to the code for your admin dashboard.
