### ISSUE TITLE
[Bug]: Proxy - Large Amount of Users created on long running proxy

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1605]
### What happened?
Large amount of Users in Proxy DB 

## Potential Causes:
- New User Created on every `/key/generate` call 

## How to repro 

```shell 
curl --location 'http://localhost:8000/key/generate' \
--header 'Authorization: Bearer sk-1234' \
--header 'Content-Type: application/json' \
--data-raw '{"models": ["azure-gpt-3.5", "azure-embedding-model", "BEDROCK_GROUP", "sagemaker", "tg-ai"],"team_id": "ver-new-team"}'
{"key":"sk-q8JfVZ8WMsIMel1llegngw","expires":"2024-01-25T04:41:40.111277","user_id":"dd6fc3a7-0ccd-4581-a301-9ce063ee2b17"}%     
```

**Comment by ishaan-jaff** [comment]
My Usertable is 1500 records due to this

**Comment by ishaan-jaff** [comment]
Going to drop my table and see what could be causing this

**Comment by ghost** [comment]
@ishaan-jaff that call seems to work as expected - i would expect a user id to be created for a key if one isn't provided, See: https://github.com/BerriAI/litellm/issues/978

There could be a bug though - let me know what you find

**Comment by ishaan-jaff** [comment]
Okay so on my new UserTable Here's the only times a New User was created:

- On calling /key/generate. This is not an issue since https://github.com/BerriAI/litellm/issues/978 required us to have a User ID per key 
- When I call /chat/completions with a `user` not in the UserTable 
- On Litellm 1.18.2 we were creating a new user every time the proxy was started

**Comment by ishaan-jaff** [comment]
<img width="1087" alt="Screenshot 2024-01-25 at 9 10 14 AM" src="https://github.com/BerriAI/litellm/assets/29436595/c9afbdc7-e1ab-467a-b8cc-1bd29af15bba">

**Comment by ishaan-jaff** [comment]
Okay the issue was we were creating a new user the Proxy was started on 1.18.2 and this issue does not occur for me on 1.19.2 - so this is fixed @Manouchehri

**Comment by ishaan-jaff** [comment]
Fixed because @krrishdholakia worked on adding a `litellm-proxy-budget` !🎉
