### ISSUE TITLE
[Feature]: armv64 build for docker image

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1607]
### The Feature

"I wish there were an arm64 build of ghcr.io/berriai/litellm:main"

### Motivation, pitch

user request

**Comment by bgoosmanviz** [comment]
It's worth a try with adding arm64 as a platform to the build script e.g. `linux/amd64,linux/arm64` as the platforms.

Depot.dev makes this easy, and I'm sure buildx can do the same.

**Comment by ishaan-jaff** [comment]
@bgoosmanviz added here: https://github.com/BerriAI/litellm/commit/5b151c8566dfc2bc6b2118a7a042246a026e881e

**Comment by ishaan-jaff** [comment]
this works on our latest version 1.19.2 @bgoosmanviz closing this issue, feel free to re-open if not resolved
