### ISSUE TITLE
Add Search Bar to docs 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#161]

**Comment by zakhar-kogan** [comment]
@ishaan-jaff, can you apply for [Algolia's Open Source program](https://docsearch.algolia.com/apply/)?
Another option is self-hosting something 🤔

Source: [Docusaurus docs](https://docusaurus.io/docs/search#using-algolia-docsearch)

**Comment by ghost** [comment]
algolia looks like a good option - will check it out. thanks for surfacing @zakhar-kogan

**Comment by NANDINI-star** [comment]
> @ishaan-jaff, can you apply for [Algolia's Open Source program](https://docsearch.algolia.com/apply/)? Another option is self-hosting something 🤔
> 
> Source: [Docusaurus docs](https://docusaurus.io/docs/search#using-algolia-docsearch)

Yep Algolia seems a good option in terms of typo tolerance, filtering, sorting, etc.
I've a raised a PR for a solution that we can use temporarily here: https://github.com/BerriAI/litellm/pull/187
