### ISSUE TITLE
[Feature]: Add slack alerting when Keys near their max budget

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1612]
### The Feature

Alerts  when nearing max budget at key level and global level

### Motivation, pitch

user request

**Comment by ishaan-jaff** [comment]
> Would it be possible to get notified on slack when usage is close to the max budget?
> say we get a slack notification when 15% away from exhausting the max budget as warning
> then one more when 5% away from exhausting the max budget

**Comment by ishaan-jaff** [comment]
Slack would be preferred, but email works too 
Would want it to be on the same slack channel as other alerts (such as request hanging alerts, errors etc)
End goal is a heads up in advance of budget being reached so that we can account for it 
Before the budget is fully exhausted and error is thrown

**Comment by Manouchehri** [comment]
> email works too

Email might be better, since you can send emails to Slack. https://slack.com/help/articles/206819278-Send-emails-to-Slack

(We do this a bunch internally for various status notifications.)

**Comment by ishaan-jaff** [comment]
just added slack alerting, will add email alerts if that's useful too @Manouchehri
