### ISSUE TITLE
[Feature]: Support vertex location and project being passed in completion call 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1613]
### The Feature

Accept vertex location and project to be passed in the completion call

### Motivation, pitch

"""
i think in a proxy context it would be helpful if we can specify the project per model instead of a global one

yes but more importantly i have projects for each usecase
""" - user feedback

### Twitter / LinkedIn details

cc: @eslamkarim

**Comment by ghost** [comment]
Live in v`1.19.4`

**Comment by ghost** [comment]
reopening as the problem isn't fixed yet

**Comment by ghost** [comment]
Relevat pr merged
