### ISSUE TITLE
[Feature]: Store abbreviated string of sk-key (sk-...<last-3-digits>) like openai in db 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1614]
### The Feature

Store the abbreviated string of sk-key in db like openai does (can do this in the token and spend logs table) 

<img width="268" alt="Screenshot 2024-01-25 at 9 49 39 AM" src="https://github.com/BerriAI/litellm/assets/17561003/4fa1d422-c014-4c0c-837e-653b18abce16">

### Motivation, pitch

easier for app owner viewing their spend logs to know which sk-key is causing a high spend

**Comment by ghost** [comment]
Checking with users if this is something they'd want

**Comment by ghost** [comment]
Seems like this should be opt-in. 

Since this is for key-owners happiness, and we already gate key-owner specific permissions behind `allow_user_auth` - https://docs.litellm.ai/docs/proxy/ui#step-2-enable-user-auth

We can gate this feature behind that too.

**Comment by ghost** [comment]
Live in v`1.20.0`
