### ISSUE TITLE
[Bug]: Fix OpenAPI spec to use `Authorization: Bearer sk-..` instead of `Authorization: sk-`

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#1619]
### What happened?

The Swagger UI incorrectly adds the header `Authorization: sk-...` instead of `Authorization: Bearer sk-..`.

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by ghost** [comment]
@Manouchehri i was able to use the swagger like this - 
<img width="693" alt="Screenshot 2024-01-26 at 3 04 15 PM" src="https://github.com/BerriAI/litellm/assets/17561003/27f5bda1-5a05-43c4-b948-5383d6f596b1">


Would welcome a PR to simplify this

**Comment by Manouchehri** [comment]
Oooooh. I'm an idiot. =P Not sure why I didn't do that before..
