### ISSUE TITLE
[Feature]: Make `key` optional on `/key/info`

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#1620]
### The Feature

If the `key` query is not provided on a request to `/key/info`, I think LiteLLM should return the info about the current key being used in the `Authorization: Bearer sk-...` header.

### Motivation, pitch

imo this reduces the need for #1614.

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by ghost** [comment]
@Manouchehri that wouldn't solve my problem in #1614 of not being able to display user-friendly keys to users

Scenario: So app owner goes to your dashboard -> you get all the keys associated with their user id -> you display them by the alias'es specified by them / abbreviated keys -> they click on one -> see the logs of their token usage and cost logs for the app -> identify which end-users might be driving high-spend

**Comment by ishaan-jaff** [comment]
live here: https://github.com/BerriAI/litellm/commit/ec3f497db8dc524e7e30a9ec9a2df72d13d6bd53
