### ISSUE TITLE
Add a link to test Endpoint - allow users to go to chat.litellm on Admin dashboard

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#163]
Needed to test out my new app - and needed a quick way to chat / interact with it

**Comment by ghost** [comment]
You want to test if the litellm completion on your server is working?

**Comment by ishaan-jaff** [comment]
yes - I just added baseten support and needed to just test through the admin dashboard

Instead i went to code, ran my discord bot again, made a request

would be much easier to just test if my new baseten model works on the admin dashboard

**Comment by ishaan-jaff** [comment]
If i'm anyway going to give you my keys / model configs - seems pretty easy to run my completion() call for me
