### ISSUE TITLE
[Feature]: Add a new key endpoint to delete keys by hashes

### ISSUE THREAD

**Issue by speedyankur** [BerriAI/litellm#1639]
### The Feature

Add a new endpoint to delete the keys by hashes

### Motivation, pitch

Right now, A key is only deletable if you know the secret. Just imagine we are building a selfserving portal to display a user all of his keys and lets them manage them on their own. So there should also be an endpoint to delete the key by hashes

### Twitter / LinkedIn details

https://www.linkedin.com/in/speedyankur/

**Comment by speedyankur** [comment]
https://github.com/BerriAI/litellm/pull/1637

**Comment by ghost** [comment]
@speedyankur i believe this is addressed with - https://github.com/BerriAI/litellm/commit/e989175c10ac5aa30a20b970b355e95e21eeeedb, 
this enabled `/key/delete` to accept token hashes

Is there anything further required? 

<img width="742" alt="Screenshot 2024-01-26 at 2 55 17 PM" src="https://github.com/BerriAI/litellm/assets/17561003/c12ad773-9191-4432-a7b6-8bf19f85c5de">

**Comment by ghost** [comment]
should be live in v`1.19.5`

**Comment by ghost** [comment]
Closing as this is now live
