### ISSUE TITLE
[Feature]: Allow setting names for keys 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1643]
### The Feature

When I see budget tracking alerts it's quite hard to know which key this is for: 

<img width="887" alt="Screenshot 2024-01-26 at 4 50 01 PM" src="https://github.com/BerriAI/litellm/assets/29436595/702d94f0-2525-429a-8eaf-495281f6d851">

Same for when I view my Key Spend, It would be helpful to know which key drove up spend: - my current UI only shows uuids 

![screenshot-rocks](https://github.com/BerriAI/litellm/assets/29436595/b1dea72f-0a21-4dfe-9ecd-64845b9ae727)

### Motivation, pitch

-

**Comment by ishaan-jaff** [comment]
See OpenAI key gen UI too 

<img width="661" alt="Screenshot 2024-01-26 at 4 52 20 PM" src="https://github.com/BerriAI/litellm/assets/29436595/cefb2c04-9035-41aa-8af6-c1692c9ecb62">

**Comment by ishaan-jaff** [comment]
oh nvm we have this already just saw the table - but it looks like that's the abbreviated key_name sk-12...333 

Would be helpful to have both sk-12344 and human_readable name for the key

**Comment by ishaan-jaff** [comment]
@krrishdholakia does the `key_alias` in your PR address this ? https://github.com/BerriAI/litellm/pull/1642

**Comment by ghost** [comment]
Yep - my PR has 2 fields - key_alias (user-defined) and key_name (abbreviation of sk-..)

**Comment by ghost** [comment]
This is now live in v`1.20.0`
