### ISSUE TITLE
[Feature]: Router -  router returns the assigned API key used on each completion

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1645]
### The Feature

Hi! For example, it would be great if the router returns the assigned API key used on each completion or akin calls (since it behaves as a load balancer, it would be great to know which key was exactly used); or set an in memory database so we can query the spending per api key used within the router without having to mount a full server.

### Motivation, pitch

User Feedback

**Comment by ishaan-jaff** [comment]
we allow you to do this today with Custom Callback functions: https://docs.litellm.ai/docs/observability/custom_callback you can access the api_key in the callback kwargs

**Comment by puntorigen** [comment]
This is a far better approach at solving this small request! Thank you @ishaan-jaff !!!!

**Comment by ghost** [comment]
Assuming this is solved then? @puntorigen

**Comment by ishaan-jaff** [comment]
would this have been helpful to know on the Router docs? @puntorigen

**Comment by ishaan-jaff** [comment]
<img width="803" alt="Screenshot 2024-01-27 at 8 33 48 AM" src="https://github.com/BerriAI/litellm/assets/29436595/bc3d758b-89bb-4dfe-b288-43c69480cdd6">

Added here: https://docs.litellm.ai/docs/routing#custom-callbacks---track-api-key-api-endpoint-model-used 
@puntorigen - feel free to re-open if this doesn't solve your problem well

**Comment by puntorigen** [comment]
Thanks @ishaan-jaff !
