### ISSUE TITLE
[Feature]: Document all proxy yaml settings in one page

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#1656]
### The Feature

It doesn't need to explain each option in detail, but it would be nice if we had a page like https://docs.litellm.ai/docs/proxy/configs that showed all the possible configs.

### Motivation, pitch

I often find myself wondering/asking questions if something is possible to do in the config, and it can be hard to know what to search for.

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by ghost** [comment]
Live now - https://docs.litellm.ai/docs/proxy/configs#all-settings
