### ISSUE TITLE
[Feature]: Allow users to set `organization` for OpenAI on Proxy Config.yaml

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1666]
### The Feature

> Hey, I was looking for it but couldn't find it - Is there's a way to define organization (https://platform.openai.com/docs/api-reference/organization-optional) for an OpenAI model in the model_list of the config yml for the proxy server? I have multiple organizations under OpenAI, and without passing the organization all of the requests go to a default one 

### Motivation, pitch

-

**Comment by ishaan-jaff** [comment]
We already support this on through setting, but user needs it on the model_list 
```
litellm_settings:
  organization: "your-org"
```

**Comment by ghost** [comment]
I believe the user said they have multiple organizations. this seems like it needs to be accepted in the completion() call
