### ISSUE TITLE
[Feature]: Add whisper support 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1672]
### The Feature

Corresponding openai endpoint - https://platform.openai.com/docs/api-reference/audio/createTranscription

### Motivation, pitch

user request

**Comment by ghost** [comment]
This is now supported - https://docs.litellm.ai/docs/audio_transcription

cc: @coolrazor007, @HelloDimension, @andregp

Would love to know how y'all are trying to use the proxy. 

Attaching my calendly, if you have ~10 mins to chat this week - https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
