### ISSUE TITLE
[Feature-UI]: Show users the available models for a Key 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1682]
### The Feature

<img width="1267" alt="Screenshot 2024-01-29 at 2 47 46 PM" src="https://github.com/BerriAI/litellm/assets/29436595/b0e10e7f-ed6b-4247-9cf2-16bd8a48b6a7">

Currently we don't show this on the UI 

### Motivation, pitch

-

**Comment by tylerbrandt** [comment]
Looks like this was fixed!

**Comment by ishaan-jaff** [comment]
closing since fixed
