### ISSUE TITLE
Check if the user has the right permissions to access the model 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#169]
<img width="715" alt="Screenshot 2023-08-21 at 12 25 00 PM" src="https://github.com/BerriAI/litellm/assets/17561003/082d3e41-dff4-4e98-98eb-a2a559e1ab2e">

Just checking if the key exists wouldn't work. In the GPT-4 scenario, I might have an openai key - but it wouldn't be compatible with gpt-4. Maybe for openai run model retrieve, and for others just do a simple key check.

**Comment by ishaan-jaff** [comment]
i believe we now make the completion request to check this
