### ISSUE TITLE
[Feature]: Google Vertex AI Imagen support

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1707]
### The Feature

. 

### Motivation, pitch

user request

**Comment by ghost** [comment]
Blocked on access 
<img width="985" alt="Screenshot 2024-02-03 at 9 54 56 AM" src="https://github.com/BerriAI/litellm/assets/17561003/070e8655-c533-4f31-af47-d3e7bfb4ce9a">

**Comment by ishaan-jaff** [comment]
done
