### ISSUE TITLE
[Feature]: Langfuse allow users to log the upstream LLM models calls (in a separate project) 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1719]
### The Feature

<img width="829" alt="Screenshot 2024-01-31 at 9 49 21 AM" src="https://github.com/BerriAI/litellm/assets/29436595/40622bcc-25f5-44ba-902f-13529de5960e">

### Motivation, pitch

@Manouchehri

**Comment by Manouchehri** [comment]
Langfuse supports Azure OpenAI as well. (Took me a minute to figure out if it did or not.)

https://github.com/langfuse/langfuse/issues/554

**Comment by ghost** [comment]
Hey @Manouchehri we looked into using `with_raw_response` on the openai client to get the headers

issue:
- it doesn't actually support async (the response.parse() to get model response is a sync call which slowed down response calls during testing) 

Would it be sufficient if just logged the model info from config to langfuse, for seeing which region caused the issue?

**Comment by ishaan-jaff** [comment]
closing as not planned for now
