### ISSUE TITLE
[LiteDebugger] Allow me to create new projects / View logs for a particular projects

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#172]
I was using liteDebugger for a new project and needed to see logs for the new project but instead saw logs for all my projs under LITELLM email

**Comment by ishaan-jaff** [comment]
quick hack on this - allow users to create tokens. Each token corresponds to one project + this deals with security

new dashboards can be at admin.litellm.ui/token

**Comment by ghost** [comment]
how would you map the token to the email?

**Comment by ghost** [comment]
how would a user be able to keep track of this :D

**Comment by ishaan-jaff** [comment]
marking this as done with our new implementation with tokens
