### ISSUE TITLE
[Feature]: Allow Proxy Admin to specify success_callback + success_callback params per user 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1725]
### The Feature

Admin wants some end users to have their requests logged to langfuse. They need to set diff API keys for langfuse logging per user 

### Motivation, pitch

-

**Comment by ishaan-jaff** [comment]
> could I set a different LANGFUSE_PUBLIC_KEY and LANGFUSE_SECRET_KEY per user?
> 
> I want to be able to let my coworker see all of his own requests, but ideally not the entire company's requests.
> maybe a more generic way is customizing success_callback per user.
> that would be really powerful

**Comment by ishaan-jaff** [comment]
User wants to set this on `LiteLLM_UserTable`

**Comment by ghost** [comment]
@ishaan-jaff is this now solved with team-specific logging - https://docs.litellm.ai/docs/proxy/logging#team-based-logging

**Comment by ishaan-jaff** [comment]
Ye

Ishaan Jaffer
Co-Founder https://github.com/BerriAI/litellm
