### ISSUE TITLE
[Feature]: Support TGI 'truncate' param 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1739]
### The Feature

TGI supports a truncate param for handling scenarios where max tokens > model limit 

support it 

### Motivation, pitch

user request

**Comment by ghost** [comment]
this wasn't working - https://github.com/huggingface/chat-ui/blob/main/.env#L75

**Comment by ghost** [comment]
no-op our optional param handling seems to work fine 
![image](https://github.com/BerriAI/litellm/assets/17561003/0b7b3a22-467b-4192-9339-13521f87797c)
