### ISSUE TITLE
[Feature]: UI - Quick spin Up 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1742]
### The Feature

Make it very easy to get started with LiteLLM UI 

Current flow:
- go to http://localhost:4000 
- See message requiring `PROXY_BASE_URL` 
- Set `PROXY_BASE_URL`
- See message requiring SSO / UI Auth setup in env 
- Re deploy proxy 

## Improvements 

- [x] Stop requiring setting `PROXY_BASE_URL`
- [x] Have default credentials a user can enter to start UI 
- [ ] Experimental - We can set the proxy root to be the UI like Supabase. (if we make this change the dashboard should maintain a link to swagger)

**Comment by ghost** [comment]
Supabase flow is really smooth -> spin up -> enter default credentials -> start using ui

**Comment by ghost** [comment]
Having a google client setup as a min requirement is a pretty high bar 
<img width="1162" alt="Screenshot 2024-02-01 at 12 36 01 PM" src="https://github.com/BerriAI/litellm/assets/17561003/8bedc5f8-a51d-4a64-bd06-d5173749dceb">

**Comment by ishaan-jaff** [comment]
Documenting the Supabase flow:
- git clone supabase 
- docker compose up 
- visit http://localhost:8000/ 
- enter default credentials  (you can see these credentials on their docs) 
- see admin ui 
<img width="1280" alt="Screenshot 2024-02-01 at 12 44 55 PM" src="https://github.com/BerriAI/litellm/assets/29436595/8b781c5b-54ea-4d00-8460-a7a24a3bc493">

**Comment by ishaan-jaff** [comment]
PR 1: https://github.com/BerriAI/litellm/pull/1746

**Comment by ishaan-jaff** [comment]
New flow with UI 
- click on link on swagger
- see default username, password 
- on UI 
![ui_no_sso_flow](https://github.com/BerriAI/litellm/assets/29436595/355c38a0-44a7-48fd-8668-3e9c8a327c2f)

**Comment by ishaan-jaff** [comment]
I don't know if we should just as yet replace the root of the proxy with the UI - closing this issue since we have quick spin up now
