### ISSUE TITLE
[Feature]: Option to set verify_ssl = False in completion, acompletion methods and in router configuration 

### ISSUE THREAD

**Issue by rakesajar** [BerriAI/litellm#1751]
### The Feature

The proposed feature involves the integration of an option to disable SSL verification (verify_ssl = False) within the completion and acompletion methods, as well as in the broader LiteLLM router configuration. This modification would allow users to bypass SSL certificate verification during HTTP requests. The primary use case for this feature is to facilitate the utilization of LiteLLM in environments with stringent network security policies, such as corporate networks, where SSL certificate verification might impede or restrict access to necessary resources. Implementing this feature would not alter the default secure behavior of the library, but rather offer an optional override for users in specific, controlled environments.

### Motivation, pitch

The inclusion of an option to disable SSL verification is crucial for broadening the accessibility and applicability of LiteLLM in various professional environments, particularly within corporate networks. Corporations often employ rigorous network security measures, including the use of internal certificates and strict SSL inspection policies, which can inadvertently obstruct the standard operation of external libraries like LiteLLM. By offering an option to disable SSL verification, we empower users in these environments to leverage LiteLLM's capabilities without compromising their internal network policies. This feature enhances the flexibility and adaptability of LiteLLM, ensuring that it can be effectively utilized in a wider array of settings, thereby increasing its appeal and utility to a broader user base. This change aligns with our commitment to providing a versatile and accessible tool, adaptable to the unique requirements of various operational environments.

### Twitter / LinkedIn details

https://www.linkedin.com/in/rajasekar-v/

**Comment by rakesajar** [comment]
openai python library supports it in following way that I know of

from openai import AzureOpenAI     # AzureOpenAI or OpenAI
client = AzureOpenAI(api_version="API_VERSION",
azure_endpoint="API_ENDPOINT",
api_key="API_KEY",
http_client=httpx.Client(verify=False),
)

**Comment by ishaan-jaff** [comment]
thinking through this, this seems like a config, when using litellm 

so you'd want to set `litellm.ssl_verify=False` and then expect this to work for all Router/Completion calls 

Am i correct in understanding it does not need to be set per completion/Router init ? @rakesajar

**Comment by Manouchehri** [comment]
@rakesajar Have you tried setting `REQUESTS_CA_BUNDLE` to the bundle of the MITM CAs?

**Comment by ishaan-jaff** [comment]
@rakesajar we already support this for `completion` and `acompletion`. Can you let me know if this works for you ? 
doc: https://docs.litellm.ai/docs/providers/openai#set-ssl_verifyfalse 

```python
        litellm.client_session = httpx.Client(verify=False)
        response = litellm.completion(
            model="gpt-3.5-turbo",
            messages=messages,
            max_tokens=10,
            request_timeout=1,
            metadata={"hi": "bye"},
        )

        litellm.aclient_session = httpx.AsyncClient(verify=False)
        response = litellm.acompletion(
            model="gpt-3.5-turbo",
            messages=messages,
            max_tokens=10,
            request_timeout=1,
            metadata={"hi": "bye"},
        )
```

**Comment by ishaan-jaff** [comment]
PR for doing this on router here: https://github.com/BerriAI/litellm/pull/1755

**Comment by ishaan-jaff** [comment]
closing this since @rakesajar you confirmed this fixed the problem
