### ISSUE TITLE
[Feature]: Set team id specific params in config.yaml 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1753]
### The Feature

![image](https://github.com/BerriAI/litellm/assets/17561003/9db468dc-83d7-4d35-ae20-6534ed7ea0fb)

### Motivation, pitch

User wants to have multiple langfuse accounts - different for different team members 

Also handles things like caching for certain accounts

**Comment by ghost** [comment]
## Thinking 

- have proxyconfig expose a get_team_config()
- have user_api_auth run it, to reinitialize litellm module?? 

Cons:
- this will probably not work during concurrent requests - as they're setting a module level variable

**Comment by ghost** [comment]
V2: 
- support dynamically setting callbacks in the litellm.completion call 
- have proxyconfig expose a get_team_config()
- have a pre_api_hook run it, and update the litellm.completion() call

**Comment by ghost** [comment]
- Support callbacks in the Logging object 
- set them in `function_setup()`

**Comment by ghost** [comment]
Live in v`1.21.0`. 

I think an issue with the existing implementation is that if i set 

```python 
litellm_settings:
  success_callback: ["langfuse"] 
  default_team_settings: 
    - team_id: my-secret-project
      success_callback: []
```

It would still log to langfuse for team id `my-secret-project`. 

Need to fix this, to override the success callback args

**Comment by ghost** [comment]
fix pushed ^

**Comment by ishaan-jaff** [comment]
done right @krrishdholakia ?

**Comment by Manouchehri** [comment]
Yep, I've been using it for a few days.
