### ISSUE TITLE
[Bug]: helicone callback

### ISSUE THREAD

**Issue by RodolfoCastanheira** [BerriAI/litellm#1760]
### What happened?

I'm using the proxy via docker oficial image, with a helicone callback. 

I get this error:

litellm_1      | reaches helicone for logging!
litellm_1      | LiteLLM.LoggingError: [Non-Blocking] Exception occurred while success logging with integrations Traceback (most recent call last):
litellm_1      |   File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 1276, in success_handler
litellm_1      |     messages = kwargs["messages"]
litellm_1      | KeyError: 'messages'

--------------------------------
Other possible relevant confs bellow.

**litellm-config.yaml**
litellm_settings: 
  drop_params: True
  set_verbose: False
  success_callback:
    - langfuse
    - helicone
environment_variables:
  LANGFUSE_PUBLIC_KEY: xx
  LANGFUSE_SECRET_KEY: xx
  LANGFUSE_HOST: https://us.cloud.langfuse.com
  HELICONE_API_KEY: xx

**docker-compose.yaml**

services:
  litellm:
    image: ghcr.io/berriai/litellm-database:main-v1.21.0
    ports:
      - "80:8000"
    volumes:
      - ./litellm-config.yaml:/app/config.yaml # Mount the local configuration file
    command: [ "--config", "/app/config.yaml", "--port", "8000", "--num_workers", "1" ]
    restart: always
    depends_on:
      - litellm.db
    environment:
      DATABASE_URL: postgresql://liteuser:litepass@litellm.db/litedb

  litellm.db
    image: postgres:latest
    environment:
      POSTGRES_DB: litedb
      POSTGRES_USER: liteuser
      POSTGRES_PASSWORD: litepass
    volumes:
      - litellm_postgres:/var/lib/postgresql/data
    restart: always

**Comment by ghost** [comment]
picking up this ticket

**Comment by ghost** [comment]
@RodolfoCastanheira would love to understand how you're trying to use the proxy

Can we do a ~10 min chat this/next week? https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by RodolfoCastanheira** [comment]
Hi!

Thanks for the consideration, but it's just a personal proxy for me to
route different vendors in a unified way, because I'm too lazy to integrate
each one separately (with logging, usage, etc). Faster to just use openai
module for everyone.

For now I'm using it for LibreChat, vim, my hackisch bash/fish completion
and some scripts. Plan to experiment with various models and various tasks
in the cli. You know, the best tools are the tools you make yourself.

I'm doing something wrong, in the configs above?

Ps. Your software is amazing, great work!

Le ven. 2 févr. 2024, 17:47, Krish Dholakia ***@***.***> a
écrit :

**Comment by ghost** [comment]
fix pushed - https://github.com/BerriAI/litellm/commit/31b19a420f7df4e243e06724015c1c442420f757

should be live soon in v`1.21.4`

**Comment by ghost** [comment]
Hi @RodolfoCastanheira 

would love to set up a 1:1 support channel for you. Attaching my linkedin + discord, let me know what works: 

- LinkedIn: https://www.linkedin.com/in/krish-d/
- Discord: https://discord.com/invite/wuPM9dRgDw (just say hi on intros and we'll set up a channel) 

Also connected on linkedin.
