### ISSUE TITLE
[Feature]: Support `DIRECT_URL` (so that `DATABASE_URL` can use pgbouncer)

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#1769]
### The Feature

https://www.prisma.io/docs/orm/prisma-client/setup-and-configuration/databases-connections/pgbouncer

https://github.com/langfuse/langfuse/blob/9783a22abf90ba703d5c4f5121b085526c97ef02/.env.prod.example#L8

### Motivation, pitch

Hoping this might improve perf and scaling.

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by Manouchehri** [comment]
Langfuse has a startup time of 5-10 seconds, while LiteLLM has a 30-45 second startup time for me. The specs of deployment are exactly the same (well, LiteLLM has been given slightly more memory, but otherwise the same), so just shooting out ideas on what could help.

**Comment by Manouchehri** [comment]
This may help with #1714 as well.

**Comment by ghost** [comment]
Acknowledging this issue - worth investigating how we can further improve perf

**Comment by ghost** [comment]
@Manouchehri this is now supported. 

https://github.com/BerriAI/litellm/commit/ff93609453284416f9848229787513ba9e8f4a4e

Live in v`1.23.5`
