### ISSUE TITLE
[Feature]: Extend litellm.image_generation() to stable diffusion (i.e. via bedrock)

### ISSUE THREAD

**Issue by srail** [BerriAI/litellm#1770]
### The Feature

[Bedrock](https://docs.aws.amazon.com/bedrock/latest/userguide/model-ids-arns.html) (and others - i.e. HF) offer support for common image gen models beyond dall-e 3. Would love if the [image_generation api](https://docs.litellm.ai/docs/image_generation) supported other models through other providers.

### Motivation, pitch

Working on building a tool to compare outputs of various models, and this would extend to images as well. Also, litellm is super awesome and the wind beneath the AI community's wings. 

### Twitter / LinkedIn details

@patricksrail

**Comment by ghost** [comment]
@srail acknowledging this - will work on adding this tomorrow

**Comment by ghost** [comment]
PR merged. should be live soon in v`1.22.0`.

**Comment by ghost** [comment]
Hi @srail can you do a 10 min. call this/next week? 

Want to understand how we can improve litellm for your use-case 

https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by patricksrail** [comment]
Sorry, missed this - grabbing some time next week, would love to share some thoughts.
