### ISSUE TITLE
[Bug]: GOOGLE_REDIRECT_URI isn't being used, can't use SSO behind proxy

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#1771]
### What happened?

https://github.com/BerriAI/litellm/blob/8cdb5de6791ce862b88ef38293ee8b11a9e86fff/litellm/proxy/proxy_server.py#L3031-L3043

<img width="389" alt="image" src="https://github.com/BerriAI/litellm/assets/7232674/4d576adc-fbd3-42c4-aedc-40ff89883268">

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by ishaan-jaff** [comment]
this was updated in the latest release to remove the need to set `PROXY_BASE_URL` in the env. What redirect uri did it send you to ? (can you dm me on discord) ? ?

**Comment by Manouchehri** [comment]
Fixed in 071d70ec2d0ad819db8838e2299ed0850f2ef89f, thanks!
