### ISSUE TITLE
[Feature]: Send `id` (from chatcmpl) to Langfuse

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#1773]
### The Feature

Might be me overlooking it, but I don't see the `id` (like `chatcmpl-8nr0EJvkDRpFbAEwsJejnwR1twa6j`) sent to Langfuse anywhere. Would be nice to have that.

### Motivation, pitch

I tried to correlate the S3 logs and Langfuse, and realized I couldn't (well, aside from guessing based on the time) because Langfuse does not get sent things like `chatcmpl-8nr0EJvkDRpFbAEwsJejnwR1twa6j`. 

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by ishaan-jaff** [comment]
@Manouchehri do you want to set Trace ID, or Generation ID to `id` on langfuse ? 

Or both ?

**Comment by ishaan-jaff** [comment]
I think `generation_id` makes the most sense

**Comment by Manouchehri** [comment]
Hmm, I think I'm still too new to Langfuse to have a strong opinion either way.

**Comment by ishaan-jaff** [comment]
The way I interpret langfuse is 
`generation` == 1 LLM / API call 
`trace` - can have multiple generations

**Comment by ishaan-jaff** [comment]
If you're goal is to lookup `chatcmpl-8nr0EJvkDRpFbAEwsJejnwR1twa6j` I think just setting `generation_id` would work 

<img width="1063" alt="Screenshot 2024-02-02 at 1 06 09 PM" src="https://github.com/BerriAI/litellm/assets/29436595/c04cec4b-f9d5-4127-851d-a6c90bbaaaf7">

**Comment by Manouchehri** [comment]
That makes sense. =)

**Comment by ishaan-jaff** [comment]
PR : https://github.com/BerriAI/litellm/pull/1780

**Comment by ishaan-jaff** [comment]
closing this - feel free to re-open if the problem is not solved in the next release

**Comment by Manouchehri** [comment]
@marcklingen: Does Langfuse assume the `generation_id` is going to be unique?

**Comment by Manouchehri** [comment]
Hmm, this does cause some UI weirdness (when you have two identical generation_id's for two different traces), but I think it might make more sense to fix/address on the Langfuse side.

**Comment by marcklingen** [comment]
Yes, `generation_id` is assumed to be unique to allow for easy upserts without needing to also provide the `trace_id`. Why would a `generation_id` be reused across traces?

**Comment by Manouchehri** [comment]
LiteLLM is returning a cached response instead of actually making an API call to somewhere like OpenAI again. They also don't incur any cost.

Is it possible for multiple traces to reference 1 single generation?

I'm not 100% sure what the "right" way of handling and displaying cached responses is in Langfuse, very open to what you think is best!

**Comment by Manouchehri** [comment]
Semi related to https://github.com/langfuse/langfuse/issues/1050 I think (except we're intentionally causing a collision here). =)

**Comment by ishaan-jaff** [comment]
we deal with this on s3 logging by appending the time to the id, but if I understand correctly, you want the same id to be used across generations

**Comment by ishaan-jaff** [comment]
If we added the current time to the generations, you'd still be able to lookup the `chatcmpl-` on langfuse. would that work @Manouchehri ?

**Comment by Manouchehri** [comment]
> If we added the current time to the generations, you'd still be able to lookup the `chatcmpl-` on langfuse. would that work @Manouchehri ?

Correct! That'd work for me.

**Comment by marcklingen** [comment]
That's a great fix, ty

**Comment by Manouchehri** [comment]
Thinking out loud, won't this cause the spend and token usage to be inaccurate when displayed in Langfuse? (Not a _huge_ problem, but yeah.)

**Comment by marcklingen** [comment]
> Thinking out loud, won't this cause the spend and token usage to be inaccurate when displayed in Langfuse? (Not a huge problem, but yeah.)

This could be fixed by overriding the cost of the generation in Langfuse by adding `total_cost=0` on cached responses

**Comment by ishaan-jaff** [comment]
<img width="1073" alt="Screenshot 2024-02-02 at 2 18 52 PM" src="https://github.com/BerriAI/litellm/assets/29436595/72027741-3dcf-46e3-8576-58ddf9140546">

**Comment by Manouchehri** [comment]
> This could be fixed by overriding the cost of the generation in Langfuse by adding `total_cost=0` on cached responses

Nice, I think I prefer that, thanks!

**Comment by ishaan-jaff** [comment]
>Nice, I think I prefer that, thanks!

will add this too

**Comment by Manouchehri** [comment]
If you could use the exact same start_time object as the S3 logging, that would be great. (This way the two will line up perfectly.)

**Comment by marcklingen** [comment]
> > Nice, I think I prefer that, thanks!
> 
> will add this too

thanks @ishaan-jaff

**Comment by ishaan-jaff** [comment]
@Manouchehri like this: https://github.com/BerriAI/litellm/commit/9947b0db96561568fe5910c9f34b44ea1ccf1474 ? it's the same as s3 logging

**Comment by Manouchehri** [comment]
I think that looks good, especially since Langfuse will show the last part of the string. :)

**Comment by ishaan-jaff** [comment]
Tracking the response_cost here: https://github.com/BerriAI/litellm/issues/1783

**Comment by ghost** [comment]
pr pushed for response cost - will update that ticket once it's in prod.
