### ISSUE TITLE
VertexAIException - list index out of range Error from API under high-traffic

### ISSUE THREAD

**Issue by kiwi1236** [BerriAI/litellm#1774]
Following [this usage](https://docs.litellm.ai/docs/providers/vertex)
When the number of queries reach a certain limit (can be several hundreds or several dozens; the longer each individual query prompt, the smaller this limit), there will be an **VertexAIException - list index out of range Error**. I have verified that it's not the quota limit reached error, and caution has been taken to prevent reaching the number of queries per minute quota for Gemini-pro.

**Comment by ghost** [comment]
can you give me a script to repro? @kiwi1236

**Comment by kiwi1236** [comment]
I have tried using the original Vertex AI API, and the same problem persists. I suspect it's not necessarily a problem with liteLLM but a problem with Vertex AI. The liteLLM function I used was:
```
def get_response(model, message):
    """
    Query the LLM model with a message and return the response.
    """
    response = litellm.completion(
        model=model,
        messages=[{"content": message, "role": "user"}],
    )
    return response.choices[0].message.content`
```

And the Vertex AI function I used was:
```
def gemini_response(message: str) -> str:
    # Initialize Vertex AI
    vertexai.init(project="project-id-3456", location="us-central1")

    # Load the model
    model = GenerativeModel("gemini-pro")

    # Query the model
    response = model.generate_content(message)
    return response.text`
```

The error message is:

> File "/Users/user/anaconda3/envs/ml/lib/python3.11/site-packages/vertexai/generative_models/_generative_models.py", line 1315, in text
>     return self.candidates[0].text
>            ~~~~~~~~~~~~~~~^^^
> IndexError: list index out of range

So basically I am just using for loops to call either function with pre-written prompts. Then when a certain number of queries (roughly 56 queries for my current prompt) is reached, this error will appear.

**Comment by ghost** [comment]
sounds good, thanks for the script. I'll try and pick this up today.

**Comment by ghost** [comment]
@kiwi1236 i wasn't able to repro, but i added logic to treat this error as a rate limit error (since it seems to be getting triggered during high-traffic as well) 

This means our existing user-controlled backoff logic should be able to catch and retry when this happens - https://docs.litellm.ai/docs/completion/reliable_completions#retry-failed-requests

**Comment by ghost** [comment]
Curious, how exactly are you using litellm? 

Would love to learn more if you have ~10 mins to chat this/next week 

https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by ghost** [comment]
fix is now merged in main

**Comment by kiwi1236** [comment]
> @kiwi1236 i wasn't able to repro, but i added logic to treat this error as a rate limit error (since it seems to be getting triggered during high-traffic as well)
> 
> This means our existing user-controlled backoff logic should be able to catch and retry when this happens - https://docs.litellm.ai/docs/completion/reliable_completions#retry-failed-requests

I was basically using Gemini-Pro to score qualities of texts. Each prompt will include the text and the instruction for Gemini-Pro to evaluate it. It's basically a for loop to loop through the data set that includes the texts to be evaluated. So each query for Gemini-Pro will basically send it a piece of text and the evaluation instruction for it to give a score.

When the number of queries sent to Gemini-Pro reaches a certain point (the longer each individual query, the smaller this number), there will be such an error. Basically Gemini-Pro will return nothing with error code 500 and the reason is OTHER.

I suspect if you increase the number of tokens for each query (to about 500 tokens per query), and send the queries via a for loop, you may reproduce the same error when you reach, say, 60 or 70 queries.

**Comment by kiwi1236** [comment]
> Curious, how exactly are you using litellm?
> 
> Would love to learn more if you have ~10 mins to chat this/next week
> 
> https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

Do you mean video/audio chat? I kinda prefer communication via text only :)

Simply, do you mind trying something like:

```
import litellm
litellm.vertex_project = "project-id-0123"
litellm.vertex_location = "us-central1"

def get_response(model, message):
    response = litellm.completion(
        model=model,
        messages=[{"content": message, "role": "user"}],
    )
    return response.choices[0].message.content

message = "Given the following long string ... of about 500 tokens, so maybe 500 English words ... please give scores (from range 1 - 5) on its coherence, grammar, and interestingness."

for i in range(500):
    response = get_response('gemini-pro', message)
```
Let me know if you can reproduce the same error.

**Comment by ishaan-jaff** [comment]
@kiwi1236 following up on what Krrish said - yes text would work great. Can we setup a Linkedin / Twitter / Discord Group 

You can contact me here:
Linkedin: https://www.linkedin.com/in/reffajnaahsi/ 
Twitter https://twitter.com/home

**Comment by kiwi1236** [comment]
Yes, we can set up a discord group. How do we get in touch on discord?

**Comment by ishaan-jaff** [comment]
@kiwi1236 this is the litellm discord: https://discord.com/invite/wuPM9dRgDw 

If you introduce yourself on the intros channel I'll start a group chat

**Comment by kiwi1236** [comment]
I think I have figured out the problem. For some query messages, Gemini Pro will not return any response at all, not even some minimal response like "sorry I can't give an answer." This type of problem is entirely reproducible, i.e. if you run a program to just retry the same query with the same query message, Gemini Pro will not return anything and an exception will occur. This type of query can be handled only by completely dropping this query and move onto the next one. Retrying the same query will only lead to no response and error. This is a big problem inherent of the Gemini Pro API compared to other LLM APIs because it does not return any response for certain queries (that you can't predetermine) and even after repeated tries. By the way, I have tried turning off all the message sensitivity restrictions for Gemini Pro and this issue still occurs, so it is not due to the message being sensitive. I think it's a bug of Gemini Pro that is not widely known.

**Comment by ghost** [comment]
@kiwi1236 what's the right error code for this? would it be a 422 (unprocessable entity) error

I'm guessing a 429 or 500 would lead to retries in any normal fallback/load balancing system

**Comment by kiwi1236** [comment]
It's error code 500. Retries won't work. Only way to get around is to just skip the same query.
