### ISSUE TITLE
[Feature]: Admin UI - Quick Spin Up, when no DB URL set 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1778]
### The Feature

User landed on UI when no DB was setup, it failed 

"It's okay to fail, but I still wanted to see the UI". Take me to UI and give me a notice that nothing will work if there is no DB connected 

### Motivation, pitch

cc @krrishdholakia

**Comment by ishaan-jaff** [comment]
Fixed here: https://github.com/BerriAI/litellm/pull/1788 

Now you can land on the UI with no DB URL

**Comment by ghost** [comment]
you dropped this @ishaan-jaff 👑
