### ISSUE TITLE
[liteLLM debugger] Make this compatible with fallbacks :) 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#178]
I can have one litellm request ID but multiple LLM api calls. I need a way to see for this given litellm request ID what fallbacks tried/worked. And which litellm requests actually ended up failing 

<img width="1141" alt="Screenshot 2023-08-21 at 4 31 59 PM" src="https://github.com/BerriAI/litellm/assets/29436595/7e91d604-3c87-45db-a10c-6068af6b0f89">

**Comment by ghost** [comment]
we create a litellm_call_id to track requests - how would you keep the id consistent across calls for fallbacks?

**Comment by ghost** [comment]
imo i think you're trying to see a request log which feels different from the model call logs 

Why not use PostHog / Mixpanel for this?

**Comment by ghost** [comment]
With the new update to the dashboard, you can also filter on success - so maybe there's something there ?
