### ISSUE TITLE
[Feature]: Bypass cache for /health endpoint

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#1784]
### The Feature

On the `/health` endpoint, don't use any cache of any sort. =) 

### Motivation, pitch

The `/health` endpoint currently uses the cache (if enabled) when checking if the model is working, which is a bit misleading.

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by ghost** [comment]
pr created, will update ticket once it's in prod

**Comment by ghost** [comment]
this is now fixed in v`1.21.5`
