### ISSUE TITLE
litellm import_and_install breaks during high traffic 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#179]
<img width="1280" alt="Screenshot 2023-08-21 at 4 31 45 PM" src="https://github.com/BerriAI/litellm/assets/29436595/56338dbe-bf3f-43a3-878a-afadd62c376b">

We should not pip install for every request. 

I'd rather tell users to install the necessary python packages

Checking + importing on every request is really bad and broke during high traffic

**Comment by ishaan-jaff** [comment]
@krrishdholakia thoughts ? 

IMO we can just tell users to install the relevant python package instead of installing it for them

**Comment by zakhar-kogan** [comment]
Is using poetry's [dependency resolver](https://python-poetry.org/docs/cli/#install) an option?
Looks like it's doing exactly that 🤔
If it looks OK for you, I can create a branch + build -> test it in a video.

**Comment by ishaan-jaff** [comment]
deprecating the usage of install_and_import for this

just raising an exception telling users to pip install the necessary packages when there is an error

**Comment by ishaan-jaff** [comment]
this is addressed
