### ISSUE TITLE
[Feature]: Proxy - allow setting user roles for Users

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1793]
### The Feature

we'll need a field for user role. For our ui the `user_role` can be either: 
- `proxy_admin` - maintaining the proxy and owning the overall budget
- `app_owner` - employees maintaining the apps, each owner may own more than one app
- `app_user`  - users who know nothing about the proxy. These users get created when you pass `user` to /chat/completions

**Comment by ghost** [comment]
Question:
- what's `default_user`? 
- How are roles assigned?

**Comment by ishaan-jaff** [comment]
> what's default_user?

Ticket updated 

> How are roles assigned?

It's a request param to `/user/new` . Any other way you'd recommend ?

**Comment by ishaan-jaff** [comment]
Pr here: https://github.com/BerriAI/litellm/pull/1795

**Comment by ishaan-jaff** [comment]
One thing I'm considering,  should we only allow 3 roles or can proxy users define their own roles. 

IMO we should only allow 3 roles since the purpose of this field is to control LiteLLM Admin UI 

If users can set more than the 3 fields we know of, they might see unexpected results on the UI 

eg. sometimes users might pass `proxy-admin` instead of `proxy_admin`. We should probably raise Exceptions when their user_role is invalid

**Comment by ghost** [comment]
Who can call `/user/new`? 

Is this an admin only endpoint? I thought the UI could also call this

**Comment by ghost** [comment]
So is any user created by UI - automatically set to app_owner 

Since app users know nothing about this

**Comment by ghost** [comment]
For v0, i think you just need 2 roles for the UI 
- admin (assume this exists already via the master key on proxy) 
- app_owner (anyone who can auth into the UI) 

You can expose a `role` param in `/user/new` and have it be `admin`, `app_owner`, `app_user` 

- `admin` role used by proxy when upserting the proxy admin into the db 
- `app_owner` role used by UI or admin when creating new users to give keys to 
- `app_user` role used by proxy when adding a new end-user to track spend against, if user param passed in and user not in db

**Comment by ghost** [comment]
Changes: 
- app_owner -> `allow_user_auth` should check if user is app_owner before allowing them to requests to proxy (i believe we should already have this in the user_api_key_auth function since we request the user row 
- admin -> no-op, we already support this today 

For backwards compatibility, we can assume a null role is app_owner
