### ISSUE TITLE
[Feature]: Have admin role defined by `sub` in oath token 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1808]
### The Feature

we should have a super admin set in the yaml, and that admin can delete anyone's key. e.g. if a key on my team created gets breached on a Saturday morning, I would prefer to revoke it myself asap in the UI (which is very convenient vs using the API).

The super admin should be defined by their sub in their OAuth2/OpenID token, not email address (as email addresses are not unique when using SSO).

https://developers.google.com/identity/openid-connect/openid-connect#an-id-tokens-payload

https://learn.microsoft.com/en-us/entra/identity-platform/id-token-claims-reference#payload-claims

### Motivation, pitch

admin wants to delete keys easily 

### Twitter / LinkedIn details

cc: @Manouchehri

**Comment by ghost** [comment]
This is now merged with #1822. Should be live soon in v`1.23.0`
