### ISSUE TITLE
[Feature]: Enable base model for azure cost tracking 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1810]
### The Feature

enable a base model for azure deployments which can be used for cost tracking (i.e. check if the base model is in model cost map before checking if the model returned by azure is in model cost map) 

### Motivation, pitch

gpt 4 1106 preview is gpt turbo and has different pricing to normal gpt 4 requests 

- gpt 4 1106 preview is returned as 'gpt-4' in the model response object

**Comment by ghost** [comment]
@ishaan-jaff we already pass the model info stuff to the litellm.completion() via metadata. 

Can't we just use the base_model in model info (used for `/model/info`) for this?

**Comment by Manouchehri** [comment]
Completed in #1874.

I did have a question, what's the reason for using `azure/gpt-4-1106-preview` instead of `gpt-4-1106-preview`? (Not saying it's "wrong", just wondering!)

**Comment by ghost** [comment]
supported - https://docs.litellm.ai/docs/proxy/cost_tracking

**Comment by ghost** [comment]
@Manouchehri i believe that's how we're splitting an azure deployment cost vs. openai's
