### ISSUE TITLE
[Bug]: Keys will no alias are invisible in the UI

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#1812]
### What happened?

I see way more keys listed in `https://litellm.example.com/user/info?user_id=david@example.com` than the admin UI dashboard displays. Looks like it's being ones without an alias are hidden? I'd rather see them all to understand where the total spend is coming from.

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by ghost** [comment]
@Manouchehri We currently hide temporary keys created by the UI dashboard for auth.

Are those the keys you're referring to? (team name is litellm-dashboard)

**Comment by Manouchehri** [comment]
Yep! I'd like to be able to delete those as well to clean up things. Maybe have a toggle somewhere in the UI to show the hidden keys (with a warning that doing that is unsupported)?

**Comment by ghost** [comment]
@Manouchehri do you want expired keys displayed?

**Comment by Manouchehri** [comment]
I want expired keys and `litellm-dashboard` keys to be displayed. Basically all keys. =)

**Comment by ishaan-jaff** [comment]
fixed on latest
