### ISSUE TITLE
[Bug]: `/health/readiness` shouldn't return 200 until database is connected

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#1814]
### What happened?

I'm using the `/health/readiness` as a startup health check in Google Cloud Run. Because the endpoint doesn't wait for the database to be successfully connected, I end up easily deploying non-functional revisions of LiteLLM.

I made the same mistake in Langfuse (applying a bad config), and the health check failed (as it should), allowing Google Cloud Run to automatically rollback (meaning zero downtime in production). =) 

<img width="634" alt="image" src="https://github.com/BerriAI/litellm/assets/7232674/644fc201-3b96-40a0-99cc-65d6d388b2dc">

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by ghost** [comment]
Hmm we do run a prisma.connect check if the prisma client is initialized. 

What was the response you received from the /health/readiness step?

**Comment by Manouchehri** [comment]
From my messy logs, it looks like `"GET /health/liveliness HTTP/1.1" 200 OK` even when the database socket failed to connect.

![image](https://github.com/BerriAI/litellm/assets/7232674/c8798e0f-4050-4d1f-9967-b231a80b0537)

**Comment by Manouchehri** [comment]
another log that shows that the unix socket couldn't connect (but LiteLLM still thought it was working):

```
Datasource "client": PostgreSQL database "litellm", schema "public" at "localhost"
The database is already in sync with the Prisma schema.
2024/02/05 02:07:07 Reading data from local connection on /tmp/cloudsql-proxy-tmp/removed:us-east4:litellm/.s.PGSQL.5432 had error: read unix /tmp/cloudsql-proxy-tmp/removed:us-east4:litellm/.s.PGSQL.5432->@: read: connection reset by peer
Running generate... (Use --skip-generate to skip the generators)
```

**Comment by ghost** [comment]
@Manouchehri This is pretty serious. Working on this today.

**Comment by ghost** [comment]
Looking at langfuse's approach here. I think this is better than just testing `prisma_db.connected()`. 

They're making a test request. 
<img width="650" alt="Screenshot 2024-02-06 at 12 44 28 PM" src="https://github.com/BerriAI/litellm/assets/17561003/7fd98578-4d99-48a3-9ed4-7e2b9cb989b4">

**Comment by ghost** [comment]
Merged. Should be live in prod in the next release (v`1.22.10`+)
