### ISSUE TITLE
[Discussion]: Cannot set both presence_penalty and frequency_penalty for Perplexity

### ISSUE THREAD

**Issue by toniengelhardt** [BerriAI/litellm#1817]
### What happened?

Seems like there is an error with Perplexity models if both `presence_penalty` and `frequency_penalty` parameters are set.

<img width="902" alt="Screenshot 2024-02-05 at 13 43 48" src="https://github.com/BerriAI/litellm/assets/2703233/0a53df40-033e-4917-a85d-d7eb34fc5290">

**Comment by ghost** [comment]
Hi @toniengelhardt this isn't an error from liteLLM, but from perplexity itself. What would you have us do here?

**Comment by toniengelhardt** [comment]
@krrishdholakia hmm, maybe just omit one of them if both are set and the provider is Perplexity? I could also do that in my code, but the UX would be better IMO if you could run the same prompt with the same settings in LiteLLM and just change the model string without it breaking.

**Comment by ghost** [comment]
how're you setting these? 

can we drop only if it's a default value? 

i would assume if a user is setting both,  then they're trying to experiment with the right params in which case having the error raised back would be helpful to them?

**Comment by toniengelhardt** [comment]
It depends on the use case I think. But fixed it now manually in my code, closing...
