### ISSUE TITLE
[Bug]: PostgreSQL data model deployment not reliably working

### ISSUE THREAD

**Issue by chrbrnracn** [BerriAI/litellm#1818]
### What happened?

The stack is running in a local K3s setup.
* PostgreSQL setup with Zalando PostgreSQL Operator.
  * Operator creates database "litellm" and user "litellm" with superuser and dbcreate permissions
* litellm-database is running as Pod
  * When database is empty there are two variants:
    * Tables are created and everything is working fine
    * Tables are not created and litellm prints error messages (see below in the log output)

I could reproduce it, following these steps:
* Stop litellm
* Delete alles tables in the public schema (LiteLLM_*)
* Start litellm, wait for applicationn to start
  * Error messages in Logs
  * No tables created in public schema (waited a sufficient amount of time but nothing happened)
* Stop litellm and start it again, wait for application to start
  * No error messages in logs
  * Tables created in public schema

Same happens when I delete and recreate the whole database.

A slightly different behavior when I delete the whole database and let litellm create it.
* Stop litellm
* Drop database
* Start litellm
  * Error Message in Log: `{"is_panic":false,"message":"Database 'litellm' does not exist on the database server at 'zoollama-litellm-pgsql:5432'.","meta":{"database_name":"litellm","database_host":"litellm-pgsql","database_port":5432},"error_code":"P1003"}`
  * No database created
* Stop litellm + start litellm
  * Database is created but without tables
  * Message in logs: Error: P1009: Database 'litellm' already exists on the database server at 'litellm-pgsql:5432'
  * Afterwards messages about missing LiteLLM_VerificationToken tables
* Stop litellm + start litellm two times (after first time nothing changed)
  * Tables are created, no errors in the logs.

### Relevant log output

```shell
Datasource "client": PostgreSQL database "litellm", schema "public" at "litellm-pgsql:5432"
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
LiteLLM: Proxy initialized with Config, Set models:
    codellama

#------------------------------------------------------------#
#                                                            #
#           'I get frustrated when the product...'            #
#        https://github.com/BerriAI/litellm/issues/new        #
#                                                            #
#------------------------------------------------------------#

 Thank you for using LiteLLM! - Krrish & Ishaan



Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new


LiteLLM: Proxy initialized with Config, Set models:
    codellama
INFO:     10.42.0.1:48052 - "GET /health/readiness HTTP/1.1" 200 OK
INFO:     10.42.0.1:36782 - "GET /health/readiness HTTP/1.1" 200 OK
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/litellm/proxy/utils.py", line 510, in get_data
    response = await self.db.litellm_verificationtoken.find_many(
  File "/usr/local/lib/python3.9/site-packages/prisma/actions.py", line 1485, in find_many
    resp = await self._client._execute(
  File "/usr/local/lib/python3.9/site-packages/prisma/client.py", line 492, in _execute
    return await self._engine.query(builder.build(), tx_id=self._tx_id)
  File "/usr/local/lib/python3.9/site-packages/prisma/engine/query.py", line 244, in query
    return await self.request(
  File "/usr/local/lib/python3.9/site-packages/prisma/engine/http.py", line 141, in request
    return utils.handle_response_errors(resp, errors_data)
  File "/usr/local/lib/python3.9/site-packages/prisma/engine/utils.py", line 192, in handle_response_errors
    raise exc(error)
prisma.errors.TableNotFoundError: The table `public.LiteLLM_VerificationToken` does not exist in the current database.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/litellm/proxy/utils.py", line 510, in get_data
    response = await self.db.litellm_verificationtoken.find_many(
  File "/usr/local/lib/python3.9/site-packages/prisma/actions.py", line 1485, in find_many
    resp = await self._client._execute(
  File "/usr/local/lib/python3.9/site-packages/prisma/client.py", line 492, in _execute
    return await self._engine.query(builder.build(), tx_id=self._tx_id)
  File "/usr/local/lib/python3.9/site-packages/prisma/engine/query.py", line 244, in query
    return await self.request(
  File "/usr/local/lib/python3.9/site-packages/prisma/engine/http.py", line 141, in request
    return utils.handle_response_errors(resp, errors_data)
  File "/usr/local/lib/python3.9/site-packages/prisma/engine/utils.py", line 192, in handle_response_errors
    raise exc(error)
prisma.errors.TableNotFoundError: The table `public.LiteLLM_VerificationToken` does not exist in the current database.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/litellm/proxy/utils.py", line 510, in get_data
    response = await self.db.litellm_verificationtoken.find_many(
  File "/usr/local/lib/python3.9/site-packages/prisma/actions.py", line 1485, in find_many
    resp = await self._client._execute(
  File "/usr/local/lib/python3.9/site-packages/prisma/client.py", line 492, in _execute
    return await self._engine.query(builder.build(), tx_id=self._tx_id)
  File "/usr/local/lib/python3.9/site-packages/prisma/engine/query.py", line 244, in query
    return await self.request(
  File "/usr/local/lib/python3.9/site-packages/prisma/engine/http.py", line 141, in request
    return utils.handle_response_errors(resp, errors_data)
  File "/usr/local/lib/python3.9/site-packages/prisma/engine/utils.py", line 192, in handle_response_errors
    raise exc(error)
prisma.errors.TableNotFoundError: The table `public.LiteLLM_VerificationToken` does not exist in the current database.
```

**Comment by ishaan-jaff** [comment]
@chrbrnracn recollecting my understanding:

- you stopped litellm
- deleted the litellm tables 
- restarted litellm and it did not work ?

**Comment by chrbrnracn** [comment]
@ishaan-jaff Deletion of databases and tables was just for reproducing the issues.

- I started litellm with an empty database and it did not work. 
- Then I restarted litellm and it worked sometimes. Latest after the third restart it was working.

Bottom line of the whole description:
- litellm doesn't create the tables on the first start and therefore the application fails.
- After the second start it works most of the time.

When I should guess I would suspect some kind of race condition at the start. The database is not yet populated but litellm already tries to access the tables.

**Comment by ishaan-jaff** [comment]
Hi @chrbrnracn any chance we can hop on a quick call to debug this / understand your use case ? 

Sharing a link to my cal for your convenience: 
https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat?month=2024-02

**Comment by chrbrnracn** [comment]
Hi @ishaan-jaff. It's hard to find a slot due to timezone differences.
Are there maybe any debug flags I can enable so we can see what happens in the application?

One possible cause could also be that I'm running the setup locally on my M1 Mac in Rancher Desktop. Maybe the database is responding a bit slow and the application tries to start while the model deployment is still ongoing. This could explain why it works on the second start.

I found "prisma db push" here: https://github.com/BerriAI/litellm/blob/1391490d928f32496298ee002d13d068e4e80b7d/entrypoint.sh#L32

In Dockerfile.database the entrypoint.sh is made executable but not run as entrypoint. I couldn't find the place where prisma deploys the data model to the database.

**Comment by ghost** [comment]
we don't run entrypoint.sh anymore, it's run in the proxy_cli.py before starting the workers - https://github.com/BerriAI/litellm/blob/1391490d928f32496298ee002d13d068e4e80b7d/litellm/proxy/proxy_cli.py#L467

**Comment by ghost** [comment]
Hey @chrbrnracn were you able to resolve this issue? Closing for now as unable to repro
