### ISSUE TITLE
[Feature]: log llm api errors to langfuse

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1820]
### The Feature

langfuse supports error logging - https://langfuse.com/docs/openai#5-track-openai-errors

We should support this too as a failure_handler 

### Motivation, pitch

Allow user to have one place for all their llm monitoring 

### Twitter / LinkedIn details

@sumba101

**Comment by ghost** [comment]
cc: @maxdeichmann can you share how i could do this with the sdk?

**Comment by maxdeichmann** [comment]
@krrishdholakia sure!

```
generation = trace.generation(
    level ="ERROR" # can be any of DEBUG, DEFAULT, WARNING or ERROR
    status_message='error' # can be any string (e.g. stringified stack trace or error body)
)
```

Docs: https://langfuse.com/docs/sdk/python#generation

**Comment by ghost** [comment]
This is now live in prod. 

Just need to add this to docs
