### ISSUE TITLE
[Feature]: Allow proxy admin to view + delete all keys on proxy 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1822]
### The Feature

- see global spend 
- If key is leaked, allow admin to go and delete the key

### Motivation, pitch

more admin controls

**Comment by ghost** [comment]
Related - https://github.com/BerriAI/litellm/issues/1808

**Comment by ghost** [comment]
this is now merged. Should be live soon in v`1.23.0`
