### ISSUE TITLE
[Bug]:Model not in model_prices_and_context_window.json local models

### ISSUE THREAD

**Issue by iplayfast** [BerriAI/litellm#1823]
### What happened?

I'm trying to use ollama/mixtral and it's not listed in the mode_prices_and_context_window.json
Who cares what the prices and context is when using a local model? 
Currently I can't use a package because I guess litellm does. 

All the ollama models listed have the same configuration except vicuna and that difference is minor.
```
    "ollama/orca-mini": {
        "max_tokens": 4096,
        "input_cost_per_token": 0.0,
        "output_cost_per_token": 0.0,
        "litellm_provider": "ollama",
        "mode": "completion"
    },
    "ollama/vicuna": {
        "max_tokens": 2048,
        "input_cost_per_token": 0.0,
        "output_cost_per_token": 0.0,
        "litellm_provider": "ollama",
        "mode": "completion"
    },
```
So wouldn't it make more sense to have a default to fall back to on  local models if it's not in the list than to just give up?

**Comment by snlt** [comment]
File ".../lib/python3.11/site-packages/rawdog/llm_client.py", line 115, in get_script:
```Python
            if custom_llm_provider:
                cost = 0
            else:
                cost = (
                    completion_cost(model=model, messages=messages, completion=text)
                    or 0
                )
```

Fixed:
```Python
            if custom_llm_provider:
                cost = 0
            else:
                try:
                    cost = (
                        completion_cost(model=model, messages=messages, completion=text)
                        or 0
                    )
                except Exception as e:
                    cost = 0
```

Done.

**Comment by ghost** [comment]
This should be fixed now - we use pre-commit hooks to make sure the model maps are consistent
