### ISSUE TITLE
TogetherAI Function Calling support

### ISSUE THREAD

**Issue by s0l4r** [BerriAI/litellm#1827]
Hi,

Using: LiteLLM: Current Version = 1.22.3

I get this error when trying to do a function call to TogetherAI:
`Exception - Function calling is not supported by together_ai. To add it to the prompt, set litellm.add_function_to_prompt = True.`

TogetherAI is supposed to support this now:
https://docs.together.ai/docs/function-calling

For these models:
- mistralai/Mixtral-8x7B-Instruct-v0.1
- mistralai/Mistral-7B-Instruct-v0.1
- togethercomputer/CodeLlama-34b-Instruct

This is my code:

```
tools_togetherai = [
  {
    "type": "function",
    "function": {
      "name": "get_current_weather",
      "description": "Get the current weather in a given location",
      "parameters": {
        "type": "object",
        "properties": {
          "location": {
            "type": "string",
            "description": "The city and state, e.g. San Francisco, CA"
          },
          "unit": {
            "type": "string",
            "enum": [
              "celsius",
              "fahrenheit"
            ]
          }
        }
      }
    }
  }
]

response = await litellm.acompletion(
    model="together_ai/mistralai/Mixtral-8x7B-Instruct-v0.1",
    base_url="https://api.together.xyz/v1",
    tools=tools_togetherai,
    tool_choice="auto",
    verbose=True,
    messages=message_history
)
```

Thanks!

**Comment by ghost** [comment]
Acknowledging, will try and get this out today. 

Curious, @s0l4r why use litellm here? 

Togetherai is already openai compatible - https://docs.together.ai/docs/openai-api-compatibility

**Comment by s0l4r** [comment]
I was using Ollama locally with LiteLLM, but it looks like the Mistral models do not support function calling yet.. then I found that LiteLLM could use TogetherAI as well so I thought I could reuse my code.

**Comment by ghost** [comment]
added - https://github.com/BerriAI/litellm/commit/77fe71ee08515bd391a17737449df314a0926a18

**Comment by ghost** [comment]
will be live in the next release v`1.22.6`+
