### ISSUE TITLE
add support for fine tuned gpt-3.5-turbo 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#183]

**Comment by ishaan-jaff** [comment]
done

**Comment by dpaleka** [comment]
The example in [the docs](https://docs.litellm.ai/docs/tutorials/finetuned_chat_gpt) does not work for me.
It returns 
```
InvalidRequestError: The model `ft:gpt-3.5-turbo-0613...` does not exist or you do not have access to it.
```

even when replacing it with calling the `openai` library works:
```

model_name = "ft:gpt-3.5-turbo-0613..."
response = openai.ChatCompletion.create(
    model=model_name,
    messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Hello!"}
    ],
)
response
```

The code before any of the above is just this:
```
import os
from dotenv import load_dotenv

def api_keys():
    load_dotenv(override=True) # get the .env file in the current directory
    openai.api_key = os.getenv("OPENAI_API_KEY") 
    if os.getenv("OPENAI_ORG_ID"): 
        openai.organization = os.getenv("OPENAI_ORG_ID") 
    print("API key:", openai.api_key)
    print("Organization ID:", openai.organization)

api_keys()
```

@ishaan-jaff

**Comment by dpaleka** [comment]
Seems like it's resolved by setting `litellm.organization=openai.organization`. It's a bit odd that the key is propagated automatically, but the organization isn't.

**Comment by ghost** [comment]
that's odd - thanks for raising this @dpaleka 

it's a bug and i'm reopening this issue to track it.

**Comment by ghost** [comment]
Curious - why use us to just call finetuned openai models? @dpaleka

**Comment by dpaleka** [comment]
I mean, I call different models, currently using it mostly for the "same I/O format and exceptions" guarantee.

**Comment by ishaan-jaff** [comment]
@dpaleka thanks for trying this
we do allow you to set OpenAI org

- I've updated our finetuned gpt-3.5 doc based on your feedback: https://docs.litellm.ai/docs/tutorials/finetuned_chat_gpt#usage---setting-openai-organization-id 

- Also added docs on how to set org id here: 
https://docs.litellm.ai/docs/providers/openai#optional-keys---openai-organization-openai-api-base

**Comment by ishaan-jaff** [comment]
let me know if we can do something better here, will leave the issue open for 24 hours until I here back

**Comment by ghost** [comment]
For context: 

In the code it's written : `os.environ["OPENAI_ORG_ID"] = ...` 

litellm requiress: `os.environ["OPENAI_ORGANIZATION"]=...`

open to feedback on naming convention
