### ISSUE TITLE
[Bug]: Wrong pricing for `ft:gpt-3.5-turbo`

### ISSUE THREAD

**Issue by areibman** [BerriAI/litellm#1840]
### What happened?

A user of our token price library, Tokencost, found this bug. Turns out the finetuning models have been outdated in price. See: https://github.com/AgentOps-AI/tokencost/pull/27#pullrequestreview-1864107052

<img width="670" alt="image" src="https://github.com/BerriAI/litellm/assets/14807319/4ccc0ed6-c925-4359-a011-4e47b238575f">

Correct prices should be:
```
        "input_cost_per_token": 0.000003,
         "output_cost_per_token": 0.000006,
```

**Comment by ghost** [comment]
awesome @areibman just updated - https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json

You should see this live in the next few minutes.

**Comment by ghost** [comment]
Closing as this is now fixed.

**Comment by oulianov** [comment]
Cool thank you ! 

Among other issues:
- pricing for `ft:davinci-002` and `ft:babbage-002` is missing from the file
- perplexity pricing is set to 0$ ?? unsure why. If you know a free LLM api I'm happy to use it lol
<img width="336" alt="Capture d’écran 2024-02-05 à 20 21 05" src="https://github.com/BerriAI/litellm/assets/58109554/947debbd-294e-4a7f-85e1-c6647597a214">
<img width="1163" alt="Capture d’écran 2024-02-05 à 20 21 16" src="https://github.com/BerriAI/litellm/assets/58109554/fa21d31f-3241-4468-a4d5-f6bffc873296">

How is this list built and maintained ? 🤔
