### ISSUE TITLE
[Bug]: Gemini - Google AI Studio workflow possibly requests wrong authentication

### ISSUE THREAD

**Issue by grempire2** [BerriAI/litellm#1841]
### What happened?
The setup here:
proxy: litellm --model gemini/gemini-pro
Uvicorn running on http://0.0.0.0:8000

Autogen model setup: 
Model Specification: gemini/gemini-pro
gemini/gemini-pro
http://127.0.0.1:8000

The response here:
Response: [reason: "ACCESS_TOKEN_SCOPE_INSUFFICIENT"\ndomain: "googleapis.com"\nmetadata {\n key: "service"\n value: "generativelanguage.googleapis.com"\n}\nmetadata {\n key: "method"\n value: "google.ai.generativelanguage.v1beta.GenerativeService.GenerateContent"\n}\n]', 'type': None, 'param': None, 'code': 500}}

/************************************************************
Google AI Studio workflow is as simple as providing an api key, however the server is asking authentications similar to Vertext AI workflow. Given the similarirty of names between the 2 platforms, I'm guessing there's a mixed up in the litellm proxy for calling the correct function or parameter to execute.

**Comment by ghost** [comment]
Can you run this script and confirm if this works for you 
```python
from litellm import completion
import os

os.environ['GEMINI_API_KEY'] = ""
response = completion(
    model="gemini/gemini-pro", 
    messages=[{"role": "user", "content": "write code for saying hi from LiteLLM"}]
)
```

**Comment by ghost** [comment]
Just ran gemini pro and it worked for me @grempire2 
<img width="908" alt="Screenshot 2024-02-06 at 8 21 35 AM" src="https://github.com/BerriAI/litellm/assets/17561003/98e582a5-3a76-437e-9b8b-f720e3223315">


Code: 
```bash
export GEMINI_API_KEY="my-api-key"
```
```bash
litellm --model gemini/gemini-pro 
```

```curl 
curl --location 'http://0.0.0.0:8000/v1/chat/completions' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer sk-myfakekey' \
--data '{
  "model": "gemini-pro",
  "messages": [{"role": "user", "content": "why did world war2 end?"}],
}'
```

**Comment by grempire2** [comment]
@krrishdholakia Thank you for your response. Yes, the script runs perfectly fine. I apologize for not making it obvious that I was running Autogen Studui UI with litellm. Please see the attache image
![image](https://github.com/BerriAI/litellm/assets/148589884/fe0b622d-0acf-468e-b982-2c1fd01abeec)

However, the request send to litellm proxy server returned errors
![image](https://github.com/BerriAI/litellm/assets/148589884/9e7b5520-b22d-48d5-a270-8f6a3a339b7b)

Therefore, I had a conclusion that something could be wrong with litellm. I had written my own simple proxy for AI Studuio that worked fine. I wonder if other people have the same issue?

**Comment by ghost** [comment]
@grempire2 i don't know what that is, but if the proxy / litellm sdk works fine, then the bug is probably on their end. 

Here's a code snippet you can test as well
```python
from litellm import completion
import os

os.environ['GEMINI_API_KEY'] = ""
response = completion(
    model="gemini/gemini-pro", 
    messages=[{"role": "user", "content": "write code for saying hi from LiteLLM"}]
)
```
