### ISSUE TITLE
Openai Error Code 401

### ISSUE THREAD

**Issue by dmater01** [BerriAI/litellm#1845]
I'm get the following error message:  {'model': 'gpt-4', 'prompt': 'PROMPT: hi', 'response': None, 'cost': None, 'error': 'OpenAIException - Error code: 401 - {\'error\': {\'message\': \'Incorrect API key provided: $env:Ope**********************************************************jmg". You can find your API key at https://platform.openai.com/account/api-keys.\', \'type\': \'invalid_request_error\', \'param\': None, \'code\': \'invalid_api_key\'}}'}
Error: Execution error: OpenAIException - Error code: 401 - {'error': {'message': 'Incorrect API key provided: $env:Ope**********************************************************jmg". You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

My Openai api key has been set correctly in Windows 10  workstation.   see below:

(Rawdog) PS E:\Rawdog> Openai

usage: openai [-h] [-v] [-b API_BASE] [-k API_KEY] [-p PROXY [PROXY ...]] [-o ORGANIZATION] [-t {openai,azure}] [--api-version API_VERSION] [--azure-endpoint AZURE_ENDPOINT] [--azure-ad-token AZURE_AD_TOKEN] [-V]
              {api,tools,migrate,grit} ...

positional arguments:
  {api,tools,migrate,grit}
    api                 Direct API calls
    tools               Client side tools for convenience

options:
  -h, --help            show this help message and exit
  -v, --verbose         Set verbosity.
  -b API_BASE, --api-base API_BASE
                        What API base url to use.
  -k API_KEY, --api-key API_KEY
                        What API key to use.
  -p PROXY [PROXY ...], --proxy PROXY [PROXY ...]
                        What proxy to use.
  -o ORGANIZATION, --organization ORGANIZATION
                        Which organization to run as (will use your default organization if not specified)
  -t {openai,azure}, --api-type {openai,azure}
                        The backend API to call, must be `openai` or `azure`
  --api-version API_VERSION
                        The Azure API version, e.g. 'https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#rest-api-versioning'
  --azure-endpoint AZURE_ENDPOINT
                        The Azure endpoint, e.g. 'https://endpoint.openai.azure.com'
  --azure-ad-token AZURE_AD_TOKEN
                        A token from Azure Active Directory, https://www.microsoft.com/en-us/security/business/identity-access/microsoft-entra-id
  -V, --version         show program's version number and exit

**Comment by ghost** [comment]
@dmater01 i don't know what rawdog is. 

You can try testing litellm with this code snippet

```python

import os 
from litellm import completion

os.environ["OPENAI_API_KEY"] = "your-api-key"

# openai call
response = completion(
    model = "gpt-3.5-turbo", 
    messages=[{ "content": "Hello, how are you?","role": "user"}]
)
```

**Comment by ghost** [comment]
closing issue as this doesn't seem to be caused by litellm - https://github.com/AbanteAI/rawdog

@dmater01 please reopen if that isn't the case.
