### ISSUE TITLE
[Feature]: Support azure workload identities to create azure ad tokens on proxy 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1852]
### The Feature

"we use Azure Active Directory Tokens. Those tokens are defined per deployment and are only valid for a certain amount of time. We cannot add the azure_ad_token flag in the config, as the token would expire after a couple of hours."

### Motivation, pitch

User trying to use proxy to call multiple llm's in openai format (in projects in diff languages)

**Comment by ghost** [comment]
Sample code: 
```python
from fastapi import FastAPI
from azure.identity import DefaultAzureCredential
from azure.keyvault.secrets import SecretClient
from azure.core.exceptions import HttpResponseError

app = FastAPI()

# Function to get a secret from Azure Key Vault
def get_secret(secret_name):
    credential = DefaultAzureCredential()
    keyvault_name = "<your-keyvault-name>"
    keyvault_uri = f"https://{keyvault_name}.vault.azure.net"
    client = SecretClient(vault_url=keyvault_uri, credential=credential)
    try:
        secret = client.get_secret(secret_name)
        return secret.value
    except HttpResponseError:
        return None

# Example route to demonstrate obtaining an Azure AD token
@app.get("/get_token")
async def get_token():
    tenant_id = get_secret("AzureAd-TenantId-SecretName")
    client_id = get_secret("AzureAd-ClientId-SecretName")
    credential = DefaultAzureCredential()
    token = credential.get_token("https://graph.microsoft.com/.default")
    return {"access_token": token.token}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)

```

**Comment by konsti** [comment]
Some more inspiration:

```python
from azure.identity import DefaultAzureCredential
import time

class AzureTokenManager:
    def __init__(self, scopes):
        self.scopes = scopes
        self.credential = DefaultAzureCredential()
        self.token = None
        self.expires_on = 0

    def get_token(self, force_refresh=False):
        current_time = time.time()
        # Refresh the token if force_refresh is True or the token is expiring within 720 seconds
        if force_refresh or self.token is None or current_time > self.expires_on - 720:
            result = self.credential.get_token(self.scopes)
            self.token = result.token
            self.expires_on = result.expires_on
        return self.token

# Usage
scopes = "https://cognitiveservices.azure.com/.default"
token_manager = AzureTokenManager(scopes)

token = token_manager.get_token()
token = token_manager.get_token(force_refresh=True)
```

**Comment by olad32** [comment]
Even more inspiration, AzureOpenAI python client actually had this feature built in, example here : https://github.com/LazaUK/AOAI-EntraIDAuth-SDKv1#scenario-3-authenticating-with-entra-id---service-principal

**Comment by RyoYang** [comment]
Do we have any updates on this feature? Like support azure_ad_token_provider in litellm proxy?

**Comment by ghost** [comment]
@RyoYang we already support azure ad token on litellm proxy?

**Comment by Manouchehri** [comment]
See #3505, I think that’s what you want?

**Comment by RyoYang** [comment]
@Manouchehri Thank you for the quick response. From my perspective, this PR indeed supports OIDC authentication for Google, GitHub, and CircleCI but not Azure workload identities. Could you please provide a quick example of how to configure an Azure workload identity case if I misunderstood?

My ideal scenario is to use the Litellm proxy when using the OpenAI SDK, similar to Scenario 4 in this [URL](https://github.com/LazaUK/AOAI-EntraIDAuth-SDKv1?tab=readme-ov-file#scenario-4-authenticating-with-entra-id---managed-identity:~:text=in%20Acacia%20trees.-,Scenario%204%3A%20Authenticating%20with%20Entra%20ID%20%2D%20Managed%20Identity,-Note%3A%20This%20option)

**Comment by Manouchehri** [comment]
Where/what are you running LiteLLM's proxy in?

**Comment by RyoYang** [comment]
Oh. I am running LiteLLM's Proxy in AKS as model proxy, and other pods will use openai SDK to chat with endpoints by using litellm proxy service address.

**Comment by Manouchehri** [comment]
Ah, so all we're missing is fetching an OIDC token I think. We would need to add it to:

https://github.com/BerriAI/litellm/blob/a6a84e57cece367f5ba9d1ebccd42d59649b6a31/litellm/utils.py#L10030-L10097


Right now, the config for using OIDC with Google Cloud Run is like:

```yaml
model_list:
  - model_name: gpt-4-0125-preview
    litellm_params:
      model: azure/gpt-4-0125-preview
      api_version: "2024-05-01-preview"
      azure_ad_token: "oidc/google/https://litellm.example.com"
      api_base: "https://example.openai.azure.com"
    model_info:
      base_model: azure/gpt-4-0125-preview
```

Instead of `google`, we should add support for like `aks`.

**Comment by olad32** [comment]
Hi, i suggest to use official AzureOpenAI python client as it actually had this feature built in (token retrieve and use, via the azure_ad_token_provider parameter), example use here : https://github.com/LazaUK/AOAI-EntraIDAuth-SDKv1#scenario-3-authenticating-with-entra-id---service-principal and https://github.com/LazaUK/AOAI-EntraIDAuth-SDKv1?tab=readme-ov-file#scenario-4-authenticating-with-entra-id---managed-identity

**Comment by Manouchehri** [comment]
Eh, using the official python client like that will make us lose out on being able to authenticate AKS -> Amazon Bedrock I think. It'd also lose out on being able to cache creds.

**Comment by RyoYang** [comment]
> Hi, i suggest to use official AzureOpenAI python client as it actually had this feature built in (token retrieve and use, via the azure_ad_token_provider parameter), example use here : https://github.com/LazaUK/AOAI-EntraIDAuth-SDKv1#scenario-3-authenticating-with-entra-id---service-principal and https://github.com/LazaUK/AOAI-EntraIDAuth-SDKv1?tab=readme-ov-file#scenario-4-authenticating-with-entra-id---managed-identity嗨，我建议使用官方的 AzureOpenAI Python 客户端，因为它实际上已经内置了这个功能（通过 azure_ad_token_provider 参数检索和使用令牌），示例用法在这里：https://github.com/LazaUK/AOAI-EntraIDAuth-SDKv1#scenario-3-authenticating-with-entra-id---service-principal 和 https://github.com/LazaUK/AOAI-EntraIDAuth-SDKv1?tab=readme-ov-file#scenario-4-authenticating-with-entra-id---managed-identity

I have tried to use openai sdk by using azure_ad_token_provider, but it seems like the proxy will still try to use api_key or ad_token to do auth... Can you please show me how to config litellm proxy in the example above?

**Comment by RyoYang** [comment]
> Ah, so all we're missing is fetching an OIDC token I think. We would need to add it to:
> 
> https://github.com/BerriAI/litellm/blob/a6a84e57cece367f5ba9d1ebccd42d59649b6a31/litellm/utils.py#L10030-L10097
> 
> Right now, the config for using OIDC with Google Cloud Run is like:
> 
> ```yaml
> model_list:
>   - model_name: gpt-4-0125-preview
>     litellm_params:
>       model: azure/gpt-4-0125-preview
>       api_version: "2024-05-01-preview"
>       azure_ad_token: "oidc/google/https://litellm.example.com"
>       api_base: "https://example.openai.azure.com"
>     model_info:
>       base_model: azure/gpt-4-0125-preview
> ```
> 
> Instead of `google`, we should add support for like `aks`.

Yea! Exactly! Does the oidc URL will be the oidc issuer from (az aks show --name myAKScluster --resource-group myResourceGroup --query "oidcIssuerProfile.issuerUrl" -o tsv)?

**Comment by Manouchehri** [comment]
I don't need the issuer URL atm, right now I'm trying to figure out how we can get the OIDC token without resorting to the Python SDK if possible.

**Comment by Manouchehri** [comment]
Ah, looks like it might be `AZURE_FEDERATED_TOKEN_FILE`.

**Comment by Manouchehri** [comment]
@RyoYang or @olad32: Could you share `AZURE_AUTHORITY_HOST` and the contents of `AZURE_FEDERATED_TOKEN_FILE` with me?

For `AZURE_FEDERATED_TOKEN_FILE`, make sure to remove the part after the last dot so you don't give me access to your real infrastructure.

e.g. if you have:

```text
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
```

Please only shared with me:

```text
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SIGNATURE_REMOVED
```

**Comment by Manouchehri** [comment]
@RyoYang and @olad32, can you help me over at #3861?
