### ISSUE TITLE
[Bug]: Proxy caching does not work, when redis vars passed on config.yaml 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1853]
### What happened?

with this config, users redis credentials were not getting set. They had to run export `REDIS_HOST=host` to get this to work  
# Config
model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: openai/gpt-3.5-turbo
      api_base: https://api.openai.com
      api_key: sk-example

litellm_settings:
  set_verbose: True
  cache: True
  cache_params:
    type: redis
    supported_call_types: ["completion","acompletion","embedding","aembedding"]
    host: localhost
    port: "6379"
    password: ""

**Comment by oisee** [comment]
Same issue.

None of the requests are cached, but maybe I am missing something?

/healthcheck showed that despite this “cache: True” in the config; status for all models was “no-cache: true”

maybe there is undocumented per-model cache switch?

**Comment by ishaan-jaff** [comment]
Will fix it today

**Comment by ishaan-jaff** [comment]
@oisee this a known issue, can you confirm it works if you set the following in your env

```
REDIS_HOST = ""       # REDIS_HOST='redis-18841.c274.us-east-1-3.ec2.cloud.redislabs.com'
REDIS_PORT = ""       # REDIS_PORT='18841'
REDIS_PASSWORD = ""   # REDIS_PASSWORD='liteLlmIsAmazing'
```

**Comment by oisee** [comment]
@ishaan-jaff workaround works! =) set in .profile

![image](https://github.com/BerriAI/litellm/assets/53392/8ed20ca4-3b15-4387-b17c-c55a71055f09)

**Comment by fullstackwebdev** [comment]
If I simply disable cache, I get this error (on the client side?) 

openai.InternalServerError: Error code: 500 - {'error': {'message': "'str' object has no attribute 'supported_call_types'", 'type': 'None', 'param': 'None', 'code': 500}}

I don't have supported_call_types set at all.

strange. 

Sometimes the calls work. I believe the ones that are cached fail

**Comment by ghost** [comment]
how do you disable cache? @fullstackwebdev

**Comment by ghost** [comment]
this is fixed btw - https://github.com/BerriAI/litellm/commit/f0434350f152fe74f441dd38473c48aee1396089
