### ISSUE TITLE
[Bug]: Q1 can't find image / Q2 after reload page admin UI created virtual keys disappeared 

### ISSUE THREAD

**Issue by kiaev** [BerriAI/litellm#1880]
### What happened?

Q1: We don't install UI (reason we don't found image ghcr.io/berriai/lite-llm-ui )
Were location lite-llm-ui ?
Q2: We faced with issue. After reload page admin UI, created virtual keys disappeared, but keys exist in database and work properly.
see logs bellow and screenshot

### Relevant log output

```shell
Q1 log: phase build on image litellm-ui stage from handler failed: unable to fetch base image "docker-proxy.mydomain.io/berriai/litellm-ui:main-v1.23.0
Q2 log:
INFO:     127.0.0.6:50559 - "GET /ui/?userID=ishaan-litellm&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiaXNoYWFuLWxpdGVsbG0iLCJrZXkiOiJzay1zel80OUNab1JfZFRVVWpBM25fajRRIn0.dCPYzxcXb3VYPxyMKZjpCoIHSm347uKk60fFJ1eM2Mc HTTP/1.1" 200 OK
INFO:     127.0.0.6:50559 - "GET /ui/_next/static/media/c9a5bc6a7c948fb0-s.p.woff2 HTTP/1.1" 200 OK
INFO:     127.0.0.6:50559 - "GET /user/info/?user_id=ishaan-litellm HTTP/1.1" 307 Temporary Redirect
INFO:     127.0.0.6:50559 - "GET /ui.txt?_rsc=acgkz HTTP/1.1" 404 Not Found
```

**Comment by kiaev** [comment]
<img width="1316" alt="Screenshot 2024-02-08 at 17 01 05" src="https://github.com/BerriAI/litellm/assets/74699553/2629dd8d-33a8-400f-8f3a-e222cbe0348e">
created key
<img width="1275" alt="Screenshot 2024-02-08 at 17 02 31" src="https://github.com/BerriAI/litellm/assets/74699553/56e6ff0a-92af-4f15-bd8a-d6dbc6096acd">
after reload page
in logs

**Comment by ghost** [comment]
@kiaev is this with SSO?

**Comment by kiaev** [comment]
@krrishdholakia without SSO

**Comment by ishaan-jaff** [comment]
> Were location lite-llm-ui ? 

It's on the proxy on the `/ui` endpoint

**Comment by kiaev** [comment]
Sorry, I'm talking about the UI image. repository: ghcr.io/berriai/lite-llm-ui
i received code 
<img width="1030" alt="Screenshot 2024-02-09 at 13 11 13" src="https://github.com/BerriAI/litellm/assets/74699553/26bc8b8a-658d-44bc-adec-f5e8c865f827">
404 
where can I find lite-llm-ui image?

**Comment by ghost** [comment]
the ui is built as part of the proxy image - https://github.com/BerriAI/litellm/pkgs/container/litellm-database

curious, why are you asking for a separate ui image? @kiaev

**Comment by kiaev** [comment]
in Helm chart i see this block, could you explain what that mean ?
`ui:
  enabled: false
  replicaCount: 1
  autoscaling:
    enabled: false
  image:
    repository: ghcr.io/berriai/lite-llm-ui
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    # tag: "main-latest"
    # TODO: Switch to BerryAI repo and tags if/when they provide a ui image
    # https://github.com/BerriAI/lite-llm/pull/1505
    tag: ""`

**Comment by ghost** [comment]
cc: @ShaunMaher can you help explain this a bit?

**Comment by ishaan-jaff** [comment]
> ghcr.io/berriai/lite-llm-ui  

the helm chart was made when we used to have a streamlit UI docker container, our UI is now part of the proxy

**Comment by ShaunMaher** [comment]
My apologies.  I have been and am time poor at the moment.  I'll jump in and update the helm chart as soon as the time dimension allows.

**Comment by ishaan-jaff** [comment]
@kiaev this is now fixed on our latest helm charts 

@kiaev any chance we can hop on a call ? I'd love to learn how how we can improve litellm for you.

I reached out to you on Linkedin if DMs work.
Sharing a link to my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
