### ISSUE TITLE
[Feature]: Integrate with AWS Secret Manager https://aws.amazon.com/secrets-manager/ 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1883]
### The Feature

User wants us to read LLM API keys from AWS Secret Manager 

### Motivation, pitch

-

**Comment by ghost** [comment]
+1 second user request for this 

https://boto3.amazonaws.com/v1/documentation/api/1.12.21/reference/services/secretsmanager.html#SecretsManager.Client.get_secret_value

**Comment by ghost** [comment]
this is now supported https://docs.litellm.ai/docs/secret#aws-secret-manager
