### ISSUE TITLE
[Feature]: log input to langfuse during error 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1885]
### The Feature

log the input to the llm api when an error happens on langfuse

### Motivation, pitch

currently user just sees error message, but no way to repro the scenario 

![image](https://github.com/BerriAI/litellm/assets/17561003/6c846dd6-d432-46a8-8e0c-a92e086a2c33)

**Comment by ghost** [comment]
fix is now live (v`1.23.4`+)
