### ISSUE TITLE
[Bug]: slack alerting error - circular reference detected

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1886]
### What happened?

when an llm api call fails (E.g. azure rejects request) the slack alert fires a message like this 

### Relevant log output

```shell
Message: DB read/write call failed: Circular reference detected
```

**Comment by ghost** [comment]
Unable to repro this - 
<img width="1248" alt="Screenshot 2024-02-08 at 5 19 33 PM" src="https://github.com/BerriAI/litellm/assets/17561003/81a3d234-9351-437f-ad22-0404f8d32736">
