### ISSUE TITLE
[Feature]: Allow admin to edit / modify team specific budgets on the UI 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1890]
### The Feature

Allow admin to modify team specific settings like: 
- models they have access to 
- langfuse project used for logging  
- caching on/off
- team-specific budgets

via the UI  

### Motivation, pitch

Different projects require different limits, allow admin to set those easily

**Comment by ghost** [comment]
cc: @Manouchehri would you find this helpful?

**Comment by Manouchehri** [comment]
I think so.

**Comment by Manouchehri** [comment]
I haven't had time to make a ticket about it, but I'd also like to eventually see "read-only" `sk-`'s that are JWTs (meaning they can't be changed in the future, only removed from the database to be blocked).

**Comment by ishaan-jaff** [comment]
this is live now: https://github.com/BerriAI/litellm/pull/2795
