### ISSUE TITLE
[Feature]: restrict proxy to just listed models 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1894]
### The Feature

only allow models in the config list get called by the calls to the proxy 

### Motivation, pitch

user request

**Comment by desinurch** [comment]
Hi Krish, thanks for the fix! however i'm still seeing the proxy calls to the fallback models:
```
pip show litellm
Name: litellm
Version: 1.23.16
```
the log:
```
POST Request Sent from LiteLLM:
curl -X POST \
https://api-inference.huggingface.co/models/mistralai/Mixtral-8x7B-v0.1 \
-H 'content-type: application/json' \
-d '{'inputs': '<s>[INST] why is the bird pretty [/INST] ', 'parameters': {'temperature': 0.01, 'max_new_tokens': 1024, 'details': True, 'return_full_text': False}, 'stream': False}'
```

this model is unfortunately not in our config. Do you have any alternative solution to this issue?

**Comment by ghost** [comment]
@desinurch it's on v`1.24.3` 

It looks like you're on v`1.23.16`. 

Can you upgrade to the latest version, and let me know if the issue persists.

**Comment by desinurch** [comment]
Unfortunately the problem still persists:
```
pip show litellm
Name: litellm
Version: 1.24.3
```
Example call:
```
curl https://[LiteLLM proxy endpoint]/v1/completions \
         -H "Authorization: Bearer $(token)" \
         -H 'Content-Type: application/json' \
         -d '{
    "model": "huggingface/mistralai/Mistral-7B-Instruct-v0.1",
    "prompt": "<s>[INST] why is the sky pretty [/INST] ",
    "max_tokens": 1024,
    "temperature": 0
    }'
```
logs:
```
16:50:19 - LiteLLM:INFO:

POST Request Sent from LiteLLM:
curl -X POST \
https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.1 \
-H 'content-type: application/json' \
-d '{'inputs': '<s>[INST] <s>[INST] why is the sky pretty [/INST]  [/INST]', 'parameters': {'temperature': 0.01, 'max_new_tokens': 1024, 'details': True, 'return_full_text': False}, 'stream': False}'
```

**Comment by ghost** [comment]
@desinurch i don't think it's on /completions yet. Will add. 

Can you test `/chat/completions` and let me know if that works?

**Comment by ghost** [comment]
just pushed the fix for `/completions` @desinurch 

https://github.com/BerriAI/litellm/commit/d97369dcbe282e75d8d80c5719b96534f603741e

should be live soon in v`1.24.5`

**Comment by ghost** [comment]
closing issue for now - please re-open if this persists.

**Comment by desinurch** [comment]
works, thanks a lot!
