### ISSUE TITLE
[Feature]: use `user:` `bot:` chat template for amazon titan model 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1896]
### The Feature

amazon titan responds to `user:` and `bot:` prompted messages (similar to anthropic) 

follow their format 

### Motivation, pitch

better responses

**Comment by dleen** [comment]
I got confirmation from AWS that `User:` and `Bot:` (I see your versions are lowercase... not sure if that matters) are the required prefixes for chat style completions

**Comment by ghost** [comment]
@dleen is this documented somewhere? I wasn't able to find it

**Comment by dleen** [comment]
No this was private communication but they will be updating the documentation soon. It's easy to verify that it's correct as the responses are obviously 10x better

**Comment by ghost** [comment]
Fixed - https://github.com/BerriAI/litellm/commit/cb5a13ed49d33e19a6ed45570491508abfa42cc0

live in v`1.23.14`. Please reopen if this doesn't solve your problem @dleen
