### ISSUE TITLE
modify additional_details for llm_client

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#19]
I don't really want to create and maintain separate dictionaries across my code as i'm calling llm_client.completions.. can i not just set identifiers in one place and be done with it? 

I like how sentry does this 

```
from sentry_sdk import set_user

set_user({"email": "jane.doe@example.com"})
```

**Comment by ghost** [comment]
Why do i need identifiers? 

So when i see a traceback in slack, i have some context on who the user is (can find the right error easily, when they complain via email/discord/etc.), and i know what they asked, what model was called etc.

**Comment by ghost** [comment]
// just accepts and sets a dict object with the identifiers for that llm call 

- `user_id` : For PostHog/Slack,  if you want to map the event to a user id, then pass in the user_id with this key (e.g.: `{...,"user_id": "krrish@berri.ai"}`). By default this will capture the event without setting user_id. 
- `successful_event`: For PostHog, if you want to set a custom event name,  when an LLM API calls works - then pass in the event name with this key (e.g.: `{..., "successful_event_name": "custom_event_name"}` ). By default this will be `litellm.succes_query` .
- `failed_event`: For PostHog, if you want to set a custom event name, when an LLM API call fails - then pass in the event name with this key (e.g.: `{..., "failed_event_name": "custom_event_name"}` ). By default this will be `litellm.failed_query`.


```
from main import set_identifiers 

set_identifiers({"user_id": "jane.doe@example.com"})
```
