### ISSUE TITLE
[Feature]: Show time series cost on UI (global) 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1900]
### The Feature

Allow admins to see a chart for seeing spend 
<img width="1029" alt="Screenshot 2024-02-08 at 6 11 48 PM" src="https://github.com/BerriAI/litellm/assets/17561003/55306194-9276-4465-af89-a35ddeed7879">

### Motivation, pitch

Easier spend tracking

**Comment by ghost** [comment]
this is now live in v`1.23.8`
