### ISSUE TITLE
[Feature]: Admin UI - Show Total Proxy Budget, Current spend on proxy 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1908]
### The Feature

- 

### Motivation, pitch

-

**Comment by ghost** [comment]
@ishaan-jaff this is already done for admin ui

**Comment by ishaan-jaff** [comment]
I don't see it

**Comment by ishaan-jaff** [comment]
It doesn't work for me

**Comment by ghost** [comment]
are you admin via sso?

**Comment by ishaan-jaff** [comment]
<img width="1280" alt="Screenshot 2024-02-09 at 8 56 45 AM" src="https://github.com/BerriAI/litellm/assets/29436595/7ea23bf3-b949-4188-a438-104ae954eb6e">

**Comment by ishaan-jaff** [comment]
Budget on config 

<img width="931" alt="Screenshot 2024-02-09 at 8 57 10 AM" src="https://github.com/BerriAI/litellm/assets/29436595/4fef936b-ed42-45b6-af8a-a8d45fc3ddae">

**Comment by ghost** [comment]
oh - sorry i misunderstood as total spend

**Comment by ishaan-jaff** [comment]
done
