### ISSUE TITLE
[Feature]: Support Microsoft presidio for PII masking 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1927]
### The Feature

Allow user to use Microsoft presidio for PII masking 

https://microsoft.github.io/presidio/

### Motivation, pitch

user request

**Comment by ghost** [comment]
We can provide support via their API - https://microsoft.github.io/presidio/anonymizer/#using-docker-container

<img width="894" alt="Screenshot 2024-02-10 at 5 56 41 PM" src="https://github.com/BerriAI/litellm/assets/17561003/4f59a6d4-e3d4-488a-bf6c-092e7c577007">

**Comment by ghost** [comment]
We'll need a way to allow users to tell us if this is something they want to enable, since this an optional callback. 

Could just be modifying the config.yaml to accept a list of callbacks like the package does 

```yaml
litellm_settings:
       litellm.callbacks = ["presidio", <my_custom_file>] 
```

**Comment by ghost** [comment]
User will also need to give us
- base url of the presidio dockerfile 
- entities to look for and anonymize -> can't pass a list as an env 


```python
os.environ["PRESIDIO_API_BASE"] = "http://localhost:5001"

litellm.presidio_entity_types = ["CREDIT_CARD", "PHONE_NUMBER",..] 
```

**Comment by ghost** [comment]
Thinking out loud, this list is already known - https://microsoft.github.io/presidio/supported_entities/

so maybe for v0 we can start with hardcoded defaults, and expand based on feedback

**Updated input list**

user just needs to give us the presidio api base 

```bash
export PRESIDIO_API_BASE="http://localhost:5001"
```

**Comment by ghost** [comment]
actually just tested again, i don't think we need to explicitly pass the anonymizer, it'll just automatically handle it. i think you only need to pass in if you have some custom strategy for dealing with it. 
<img width="827" alt="Screenshot 2024-02-10 at 6 09 00 PM" src="https://github.com/BerriAI/litellm/assets/17561003/4ea5c07d-9804-4396-a5cc-9a68db52ecca">

**Comment by ghost** [comment]
Seems like: 
- we'll need to first call `/analyze` -> get the results
- call `/anonymize` w/ the analyze results -> get the redacted text

**Comment by bsu3338** [comment]
I am curious about the potential of PII being placed in redis semantic cache.  Would it be possible for another user to view pii information?  It might be nice to detect pii and keep it from being cached. It would also be nice to only send anonymized text to langfuse logging.

**Comment by ghost** [comment]
@bsu3338 can we do a quick call to discuss this further? 

Want to make sure i understand the requirements well here - https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by ghost** [comment]
Closing this ticket as the feature is now merged in main. Should be out soon in v`1.23.10`
