### ISSUE TITLE
Confused about the timeout unit

### ISSUE THREAD

**Issue by yujonglee** [BerriAI/litellm#193]
https://github.com/BerriAI/litellm/blob/6047b8442342256e30c272e2377a4b5b2744e94d/litellm/main.py#L59-L61
https://github.com/BerriAI/litellm/blob/6047b8442342256e30c272e2377a4b5b2744e94d/litellm/main.py#L83

So it said default is 60s, but the value is 600.

https://github.com/BerriAI/litellm/blob/6047b8442342256e30c272e2377a4b5b2744e94d/litellm/timeout.py#L46

But here, time unit is seconds.

I am bit confused here. Am I missing something or it's a bug?

**Comment by ishaan-jaff** [comment]
cc @krrishdholakia

**Comment by ghost** [comment]
We changed it to 10 minutes (600s) as this would cause unforced timeouts for things like calling agents. I'll update the text, thanks for the catch.

**Comment by ghost** [comment]
fixed in latest commit - 67d65272172bd693ac70bbac4bdc9f4afefa88f0
