### ISSUE TITLE
[Bug]: Allow users to set custom table name

### ISSUE THREAD

**Issue by menardorama** [BerriAI/litellm#1972]
### What happened?

Tables are created in mixted case.

It's beautiful but useless on postgres, it force you to encapsulate the tables names with double quote to drop it.
This should remain in lower case

**Comment by ghost** [comment]
@menardorama Can we do a quick call on this?

Want to make sure we understand the issue + get the implementation correct. 

https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by menardorama** [comment]
I don't think it may be necessary; naming convention usally use lowercase in table name or field name.

Tables are created in mixted case which needs to use double-quotes in order to make queries

**Comment by ishaan-jaff** [comment]
closing for now - since it's not planned. Open to re-open if this is a blocker to production for users
