### ISSUE TITLE
[Bug]: Redis cache set regression

### ISSUE THREAD

**Issue by kgrovor** [BerriAI/litellm#1973]
### What happened?

For the same config ie redis cache + LiteLLM proxy I can see keys added to redis for litellm:main-v1.20.3 but not main-latest as docker image.

Even though the log of the async set method is called, the key is not set. Further, no exception log is found like "Got exception from REDIS"

### Relevant log output

```shell
Set ASYNC Redis Cache: key: a7455bf911a0880bcedf4b023c3030209ed01130dd46058c7f76cdff8b1495b9
```

**Comment by ghost** [comment]
@kgrovor acknowledging issue - can we do a live debug? 

On the call now - https://meet.google.com/cbc-zdtr-hpu

**Comment by ishaan-jaff** [comment]
When I set the correct env vars caching works for me 

@kgrovor questions for you

- how do you set your Redis credentials on the proxy (I think this is related to https://github.com/BerriAI/litellm/issues/1853) 
- Are you using a locally hosted redis cache or cloud ? 
- Do you set REDIS_URL or REDIS_HOST = "" , REDIS_PORT = "" , REDIS_PASSWORD = ""

**Comment by ishaan-jaff** [comment]
If you were setting your redis variables on the config.yaml, it's possible that is leading to the regression

**Comment by kgrovor** [comment]
I use REDIS_URL in the environment to set the redis string. Nothing in the config. 
Further, I know the cache variable is being picked since I see a log which prints out my redis host and port. 
I'm using AWS Elasticache.

**Comment by ghost** [comment]
@kgrovor can you use the alt env variables (redis_host, etc.) and see if that works? Seems like this might be specific to redis url 
<img width="1087" alt="Screenshot 2024-02-14 at 9 03 29 PM" src="https://github.com/BerriAI/litellm/assets/17561003/c06ef646-fd71-49eb-b9cd-708d30e9b548">

**Comment by kgrovor** [comment]
@krrishdholakia 
Yeah, it is working with the alt env variables! The problem is limited to passing the REDIS_URL as a whole.

**Comment by ishaan-jaff** [comment]
thanks for the help - we will investigate what cause the bug with redis_url

**Comment by ghost** [comment]
## Thinking 

Seems like we're missing testing for redis_url

Will need to add that to our ci/cd to prevent future regressions.

**Comment by ghost** [comment]
can repro this

**Comment by ghost** [comment]
fix merged. should be live in next release

**Comment by kgrovor** [comment]
Thanks @krrishdholakia @ishaan-jaff!
