### ISSUE TITLE
[Feature]: Team management endpoints 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1975]
### The Feature

POST /team - params(team name,  members,  owner)
POST /team/:id/key - to generate keys for the team. this way we can also have multiple keys with in team as well
PUT /team - update team and members
DELETE /team -
GET /team - (fetch all teams and also user specific team)

### Motivation, pitch

create a key for an app that's independent of the specific user 

### Twitter / LinkedIn details

cc: @speedyankur

**Comment by ghost** [comment]
this now exists - we have `/team/new` and `/team/info`
