### ISSUE TITLE
Calc cost by time for deployment providers - replicate, togetherai, baseten

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#198]
For deployment providers like replicate, together ai, and baseten the cost is not per token but per time (seconds of usage). For our pricing functions, we should account for this.

**Comment by yujonglee** [comment]
Yeah I was wondering about cost difference between replicate and togetherAI. This will be useful.

**Comment by ishaan-jaff** [comment]
looks like TG AI does inference pricing: 
https://together.ai/pricing

**Comment by ishaan-jaff** [comment]
added pricing for TG AI https://docs.litellm.ai/docs/token_usage

**Comment by ishaan-jaff** [comment]
for replicate looks like pricing is based on request time: 
https://replicate.com/pricing

**Comment by ishaan-jaff** [comment]
@yujonglee since we need timing for replicate calls what do you think of this implementation:


from litellm import completion 

```
import time

start = time.time()

response = completion(model="tg-ai/1223", messages = \[{"role": "user", "content" : "hello"}\])

end = time.time()

response_string = response\[0\]\['choices'\]

total_cost = completion_cost(messages=messages, completion_response=response, time=end-start)
```

**Comment by ishaan-jaff** [comment]
alternatively we could add `end_time` to all replicate completion calls (but: this would not work for streaming calls)

**Comment by ishaan-jaff** [comment]
@yujonglee this is done here's a working notebook with demo:
https://github.com/BerriAI/litellm/blob/main/cookbook/LiteLLM_Completion_Cost.ipynb

docs: https://docs.litellm.ai/docs/token_usage 

feel free to re-open if you'd like me to add support for something missing
