### ISSUE TITLE
[Feature]: Allow tracking spend per request tag

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1984]
## Allow users to set requests tags 
```python
openai.chat.create(
    model="text-davinci-003",
    headers={
        "Litellm-Property-Appname": "Prod-App",
        "Litellm-Property-user": "user2",
        "Litellm-Property-model": "gpt-4-turbo",
    }
)

```

## Allow users to define a budget for the tag 
```shell
curl --location 'http://localhost:8000/tag/new' \
-H 'Authorization: Bearer <your-master-key>' \
-H 'Content-Type: application/json' \
-d '{"max_budget": 0, "tag_name": "Appname"}'
```

### Motivation, pitch

better budget tracking

**Comment by ghost** [comment]
do they want to set budgets per tag or just view cost per tag? 

What would setting a budget per tag mean?

**Comment by ghost** [comment]
We already have a way to set tags - https://docs.litellm.ai/docs/observability/langfuse_integration#set-custom-trace-id-trace-user-id-and-tags


I believe you'd probably also need a way to get the list of created tags, so an app owner can know what tags (exact naming scheme) they can use in their app

**Comment by ishaan-jaff** [comment]
done
