### ISSUE TITLE
[Feature]: enable turning pii on/off per key 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1990]
### The Feature

enable admin to turn on/off pii masking for a key 

### Motivation, pitch

user request

**Comment by ghost** [comment]
## Thinking 

We have something today for cache controls that's pretty similar. We can either add a new column in the table or just rename the existing one into 'permissions' and then have it look something like this: 

```python
permissions = {
"cache": {},
"pii": {},
}
```

This will probably make it easier to add any additional permissions to the key down the road as well

**Comment by ghost** [comment]
damn, looks like `allowed_cache_controls` was written to be a list, not a dictionary. 

Can't use that then. Will probably need to just create a new column, but yea let's call it permissions and stick to this structure.

**Comment by ghost** [comment]
this is now live
