### ISSUE TITLE
[Feature]: Allow for the customization of the root path

### ISSUE THREAD

**Issue by Subhrajit-Katonic** [BerriAI/litellm#1999]
### The Feature

Allow for the customization of the root path to eliminate the need for employing multiple DNS configurations during deployment.

### Motivation, pitch

In Kubernetes deployment, it's possible to utilize a shared DNS to host multiple applications by modifying the virtual service. However, the current version lacks this capability.

**Comment by ishaan-jaff** [comment]
@Subhrajit-Katonic can you elaborate what you need from us here ?

- What does root path mean ? 

- We allow you to set host, port https://docs.litellm.ai/docs/proxy/cli

**Comment by ghost** [comment]
Suggested solution

```
root_path = "/"
if os.getenv("ROUTE"):
root_path=os.getenv("ROUTE")

...

app = FastAPI(
root_path=root_path,
)

```

**Comment by ishaan-jaff** [comment]
PR: https://github.com/BerriAI/litellm/pull/2039

**Comment by viniciuspinto** [comment]
There are some hard-coded paths in the source that don't respect the SERVER_ROOT_PATH config. In particular, the health check breaks (it asks for authentication) when the root is not "/".

**Comment by ghost** [comment]
hi @viniciuspinto are you able to share a stacktrace/screenshot ? unclear what 'breaks' means/looks like

**Comment by viniciuspinto** [comment]
> hi @viniciuspinto are you able to share a stacktrace/screenshot ? unclear what 'breaks' means/looks like

It means that when I start the container with LiteLLM, if I call the `/myrootpath/health/readiness`, it returns status 401 instead of 200, because the SERVER_ROOT_PATH is not '/'.

I guess this is related: https://github.com/BerriAI/litellm/blob/53d7b95364042077a47a8db4b22fb0a43ff12bc0/litellm/proxy/proxy_server.py#L523
