### ISSUE TITLE
[Bug]: LLM provider NOT provided when using GGUF file at custom path

### ISSUE THREAD

**Issue by zigabrencic** [BerriAI/litellm#2001]
### What happened?

Hey. 

At the moment I'm responsible for bringing the open LLM support to gpt-engineer [issue 943](https://github.com/gpt-engineer-org/gpt-engineer/issues/943). As one of the option's we are exploring the `LiteLLM` as interface lib. But we hit a bit of a snag.

So I have the model from [The Bloke](https://huggingface.co/TheBloke/Llama-2-7B-GGUF) `llama-2-7b.Q2_K.gguf` and it works fine directly through `llama.cpp` inference engine. 

I also tried it running with `litelllm` proxy:

```bash
litellm --model models/llama-2-7b.Q2_K.gguf
```

And it loaded:

![2024-02-08@20-14](https://github.com/BerriAI/litellm/assets/9954546/718cb079-fa8c-48c6-8c1e-fbdefe7b7dad)

But then when I tried using it as specified at the docs:

```python
import openai 

client = openai.OpenAI(api_key="anything", base_url="http://0.0.0.0:8000") 

response = client.chat.completions.create(
    model="huggingface/meta-llama/Llama-2-7b",
    messages=[
        {
            "role": "user",
            "content": "this is a test request, write a short poem"
        }
    ]
)
```

I get the type of error:

![2024-02-08@20-15](https://github.com/BerriAI/litellm/assets/9954546/34874db9-92dc-4071-8f88-6f95cedff607)

I tried several model names, but neither worked:

- huggingface/meta-llama/Llama-2-7b
- Llama-2
- ollama/llama2

My suspicion is that issue is related to the fact that I'm supplying directly the path to the model `./models/llama-2-7b.Q2_K.gguf`, but I'm surprised that the model loading step doesn't fail when calling step does.

Is there an option with `LiteLLM` to use a model at specific disk path? 

1.) If yes: how? And how can I contribute to improve the docs?

2.) If no: Is there a way to implement it and how? If `litellm` is still missing this interface for model at specific path let me know. I'd be happy to implement and submit a PR to resolve this.

Cheers

**Comment by ghost** [comment]
@zigabrencic we don't support local model loads, we need an api endpoint to make the call. 

Open LLM is openai-compatible, why use litellm here?

**Comment by zigabrencic** [comment]
Thanks for the quick answer. So then if I understand correctly when `litellm` proxy is initiated it's not actually loading/initialising  the model, but sort of offloading the calls to api endpoint where LLM is running? So for example ollama endpoint?

If I have a model at specific path on the disk:

- Does one have so specify the path on the `LiteLLM` side?
- Or on `ollama` end?

I didn't mean `Open LLM` library. I meant adding support for open source large language models. Or were you referring to sth else?

We were looking at the option below ( I think it's your suggestion from a few months ago):

<img width="425" alt="2024-02-08@19-24" src="https://github.com/BerriAI/litellm/assets/9954546/0d257234-beff-446c-a8b2-4798d6e8f1b9">

But we'd like to have the option that the user can supply the path to their LLM.

**Comment by ghost** [comment]
- we initialize the client for making the api calls 
- for ollama specifically, we run an `ollama serve` command in a separate subprocess to start the server, if an api base isn't supplied
- you can specify your own provider + api base (e.g. `litellm --huggingface/<my-hf-model> --api_base <my-endpoint>`) 

does that help @zigabrencic

**Comment by zigabrencic** [comment]
Hey!

It does clarify things yes, thank you. 

Made me realise my mistake that `lite-llm` is API layer library not inference (since it uses other engines) in any capacity.

I would propose to re-clarify this in the main README and in the docs to avoid further confusions. Or at least specify in the docs the lack of support for models at specific path.

If I’m the first one to raise this please feel free to close the issue and thanks a lot for all the help.
