### ISSUE TITLE
[Bug]: UI - Invalid endpoint for Key info

### ISSUE THREAD

**Issue by Lunik** [BerriAI/litellm#2002]
### What happened?

When accessing the UI behind a reverse proxy.
In the "Usage" panel the endpoint is invalid :

![image](https://github.com/BerriAI/litellm/assets/12114079/cbc21a49-e66d-4e2b-aac0-a6c22f19957e)

/key/info is a GET, not a POST.
![image](https://github.com/BerriAI/litellm/assets/12114079/144566ea-a271-4111-a183-a6bc58166120)

I think the issue comes from : https://github.com/BerriAI/litellm/blob/v1.24.3/ui/litellm-dashboard/src/components/networking.tsx#L242

**Comment by ishaan-jaff** [comment]
will look into this today 

@Lunik what would be the 20 star experience with LiteLLM proxy for you ? 

Also sharing a link to my cal, would love to get your feedback on the product if you have some time: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by ghost** [comment]
@Lunik +1 on what ishaan said. We'd **love** to understand how you're using litellm proxy. 

A 10 min chat this/next week would be really helpful.

**Comment by ishaan-jaff** [comment]
Fix here: https://github.com/BerriAI/litellm/pull/2041
