### ISSUE TITLE
[Bug]: for last streaming chunk, don't set delta (delta: {}) instead of (delta: {"content": null, "role": null})

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#2010]
### What happened?

OpenAI streaming's last chunk just has an empty delta dict. 

Our last streaming chunk doesn't. This causes issues - https://github.com/simonw/llm/pull/377

**Comment by ercanucan** [comment]
@krrishdholakia Thanks for creating this issue! We can also confirm this behavior. We have a LiteLLM installation with streaming enabled. When we use the API with an open source UI client such as ChatBox (https://github.com/Bin-Huang/chatbox - v1.2.6) or chatgpt-lite (https://github.com/blrchen/chatgpt-lite), we observe that every response ends with a "null" appended.

@bufferoverflow @fh1ch

**Comment by ercanucan** [comment]
@krrishdholakia Any plans to address this issue in the near future or can we support with a PR? Not very familiar with the code-base but it looks like here is the code responsible for that, is that right? https://github.com/BerriAI/litellm/blob/main/litellm/utils.py#L8762

**Comment by ercanucan** [comment]
@krrishdholakia We are currently on LiteLLM version 1.35.4 and this issue seems to have been resolved. We do not observe this behavior anymore using ChatBox (currently version 1.3.3).

**Comment by ishaan-jaff** [comment]
closing since fixed

**Comment by ercanucan** [comment]
thanks folks!
