### ISSUE TITLE
[Bug]: Response format for Google AI Studio `gemini` with `stream=True` is incompatible with `OpenAI` response format

### ISSUE THREAD

**Issue by afbarbaro** [BerriAI/litellm#2015]
### What happened?

A bug happened!

When calling Google AI Studio `gemini` with `stream=True`, the returned response is not compatible with the `OpenAI` response format. After calling `acompletion` we get the response coming directly from the Google AI API (`google.generativeai.types.generation_types.GenerateContentResponse`).
This breaks everything downstream, which expects the response format to be consistent. See image below.

![image](https://github.com/BerriAI/litellm/assets/18277423/9cecc540-0f07-4309-b156-ce9133fd214e)

**Comment by afbarbaro** [comment]
I'm willing to push a PR to fix this if I'm given some pointers of where the conversion to `OpenAI` should happen.

**Comment by ghost** [comment]
hey @afbarbaro, just saw this - yes that'd be great, do it here - https://github.com/BerriAI/litellm/blob/f7a684c8cad2ea1b1f53542676ced3619c1961e1/litellm/llms/gemini.py#L4

**Comment by ghost** [comment]
We had a 2nd issue on this today, so i can take a look at this as well.

Can we do a quick debug call post pushing the fix (should be out by EOD), I'd like to make sure it works fine for you - https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by afbarbaro** [comment]
cool, I booked a time today
