### ISSUE TITLE
Proxy UI  - Budget failing with error

### ISSUE THREAD

**Issue by vijtad** [BerriAI/litellm#2033]
### What happened?

UI is showing following error after setting the budget in config file for open AI GPT 3.5/4.0  when clicking o usage link .

"Detail  method not allowed".

![image](https://github.com/BerriAI/litellm/assets/6069981/7f87572d-7cac-43a0-a1aa-b5a33594a8d4)

**Comment by ishaan-jaff** [comment]
Hi @vijtad are you on the Admin View for this: https://docs.litellm.ai/docs/proxy/ui#set-admin-view-w-sso 

You need to set `PROXY_ADMIN_ID` in in your env. Can you let me know if this fixes it ? 

If not I can hop on a call and live debug with you - sharing my calendly here for your convenience https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by ishaan-jaff** [comment]
Fix PR is here -  https://github.com/BerriAI/litellm/pull/2041

**Comment by ishaan-jaff** [comment]
@vijtad I've pushed out a new release with the fix, will let you know as soon as it's out

**Comment by vijtad** [comment]
Will this be in the new version of docker like 

FROM  ghcr.io/berriai/litellm:main-v1.24.5

**Comment by ishaan-jaff** [comment]
It will be on 1.25.1, will send it here once it's out

**Comment by ishaan-jaff** [comment]
live here: https://github.com/BerriAI/litellm/releases/tag/v1.25.1 

let me know if this works & you have any feature requests @vijtad (can get them done before we meet on Monday)

**Comment by vijtad** [comment]
I am using docker file to use this version.
Is this correct way of creating docker image ?
This is throwing error when running docker build command

**Dockerfile:1
--------------------
   1 | >>> FROM  github.com/BerriAI/litellm/releases/tag/v1.25.1
   2 |     ADD litellm_config.yaml ./
   3 |     # ADD litellm_custom_auth.py ./
--------------------
ERROR: failed to solve: failed to parse stage name "github.com/BerriAI/litellm/releases/tag/v1.25.1": invalid reference format: repository name must be lowercase**


![image](https://github.com/BerriAI/litellm/assets/6069981/52f4d43c-bde2-4706-8770-1a10af4b8fbe)

**Comment by ishaan-jaff** [comment]
should be `FROM ghcr.io/berriai/litellm:main-v1.25.1`

**Comment by ishaan-jaff** [comment]
did that work @vijtad ?

**Comment by vijtad** [comment]
Yes.

The error of budget failing is fixed in new release.
However I see some more errors - 
1. Page is not refreshing with latest data.

3.  I created two API keys and ran the same chat example with different keys using same model that is provided as an example.
I don't see total amount for second key that I used, it is all being recorded against first key.

![image](https://github.com/BerriAI/litellm/assets/6069981/5a5cfc2d-5324-42eb-a3ee-2654ee8c63e9)

**Comment by ishaan-jaff** [comment]
> Page is not refreshing with latest data. 

I'm aware of this - the spend should get updated after you make an LLM call 
Tracking this here: https://github.com/BerriAI/litellm/issues/2042

**Comment by ishaan-jaff** [comment]
Tracking the 2nd issue here @vijtad https://github.com/BerriAI/litellm/issues/2043

**Comment by ishaan-jaff** [comment]
will continue the convo in the 2 new issues I created

**Comment by vijtad** [comment]
Thank you very much.
