### ISSUE TITLE
[Feature]: Helm Charts - Automate new helm chart releases 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#2040]
### The Feature

when publishing a new release of Litellm, we should automatically deploy a new version of litellm helm charts 

### Motivation, pitch

ci/cd, better infra, easier to start with litellm

**Comment by ishaan-jaff** [comment]
cc @Lunik @ShaunMaher we'd appreciate help on this issue if one of you are able to help

**Comment by ishaan-jaff** [comment]
We already have an action to auto-deploy litellm Docker to ghcr, we'd just need the helm deploy to be in this / get triggered by this: https://github.com/BerriAI/litellm/actions/workflows/ghcr_deploy.yml 

I believe this would test any changes to our helm settings too

**Comment by ShaunMaher** [comment]
Hi all.

https://github.com/BerriAI/litellm/blob/main/.github/workflows/ghcr_helm_deploy.yml exists to build and deploy the helm chart.  It should be easy enough to merge this into ghcr_deploy.yml to combine the processes.

Cheers.
Shaun.

**Comment by ShaunMaher** [comment]
I have added some additional comments over on https://github.com/BerriAI/litellm/pull/2018#issuecomment-1951479455, just to explain some of the decisions I made when creating the chart.  I hope they at least explain the method to my madness. :-)

**Comment by debdutdeb** [comment]
Ah I opened this https://github.com/BerriAI/litellm/issues/2421 before looking. My Bad

**Comment by ishaan-jaff** [comment]
Okay litellm-helm gets released here now: https://github.com/BerriAI/litellm/pkgs/container/litellm-helm 

@debdutdeb @ShaunMaher @Lunik @GuillermoBlasco 

FYI - we had to rename the chart to `litellm-helm` since the litellm docker image is called `litellm` on ghcr
