### ISSUE TITLE
Max budget not showing in UI from Azure but displays in localhost

### ISSUE THREAD

**Issue by vijtad** [BerriAI/litellm#2051]
### What happened?

I setup the max budget param in config as follows- 
![image](https://github.com/BerriAI/litellm/assets/6069981/cb09feb5-77d3-4092-9444-7020956a3079)

It show this value in localhost but not in Azure cloud.
![image](https://github.com/BerriAI/litellm/assets/6069981/2cd770c9-0016-41ac-af45-e64b09e8b28f)

**Comment by ishaan-jaff** [comment]
will work on this today

**Comment by ishaan-jaff** [comment]
@vijtad do you have a user with user_id = `litellm-proxy-budget` in your UserTable in the DB ? Can you confirm the budget there is correct

**Comment by vijtad** [comment]
Yes. I see user in the table.

![image](https://github.com/BerriAI/litellm/assets/6069981/89f77ce3-8c61-4e99-add1-db4decf45994)



Following are the tables - 

![image](https://github.com/BerriAI/litellm/assets/6069981/06c8cae9-be16-4351-826e-e6e49423403d)

**Comment by ishaan-jaff** [comment]
Do you see user with `user_id = litellm-proxy-budget` in LiteLLM_UserTable

**Comment by vijtad** [comment]
Yes. As you can see in my previous screenshot.

**Comment by ishaan-jaff** [comment]
got it, does the other functionality work on Azure cloud - example are you able to create a key, view your models etc
