### ISSUE TITLE
Bearer token sk-1234 failing  

### ISSUE THREAD

**Issue by vijtad** [BerriAI/litellm#2052]
### What happened?

When I setup bearer token as follows, it fails -
![image](https://github.com/BerriAI/litellm/assets/6069981/b7280ccc-9097-422f-a8fa-17395ced4518)

![image](https://github.com/BerriAI/litellm/assets/6069981/48797c0b-60a6-4ede-9f60-91ba9db7464f)

However this works, after adding Bearer text as follows - 
![image](https://github.com/BerriAI/litellm/assets/6069981/d450160e-2ebd-47b5-a03e-b43b255bb38e)

![image](https://github.com/BerriAI/litellm/assets/6069981/a7e4e808-a401-4dd2-aac9-e9e6bbba4fc8)

**Comment by ishaan-jaff** [comment]
This works when you use `Bearer sk-1234`, what is the desired behavior here ?
