### ISSUE TITLE
[Feature]: Admin UI - Allow admin to set max / default values to /key/generate 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#2058]
### The Feature

 Allow admin to set max / default values to /key/generate
 
 The Admin can specify the max_budget allowed to create a key 

### Motivation, pitch

-

**Comment by hoangleitvn** [comment]
When creating as new user with auto create token is true, we are creating a new key with unlimited budget while the budget for the user is limited. So when creating a new key for a new user, we should use the max_budget from the user

**Comment by ishaan-jaff** [comment]
live here: https://docs.litellm.ai/docs/proxy/ui#setup-ssoauth-for-ui
