### ISSUE TITLE
add exception mapping for together ai, baseten, vertexai, ai21, openrouter, petals, ollama

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#207]
We've added a couple new providers recently but are lacking coverage in exception mapping for them - https://github.com/BerriAI/litellm/blob/a42c197e5a6de56ea576c73715e6c7c6b19fa249/litellm/utils.py#L1217. 

**Next Steps**
1. Run testing on these providers - https://github.com/BerriAI/litellm/blob/a42c197e5a6de56ea576c73715e6c7c6b19fa249/litellm/tests/test_exceptions.py, 
2. map the exceptions raised to their corresponding openai type 
3. Update exception mapping table in docs

**Comment by ghost** [comment]
picking up this ticket

**Comment by ghost** [comment]
closing as this is now done
