### ISSUE TITLE
Caching doesn't work as expected

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#208]
Most people ask the same question, on the playground, to the model (whatever the default is). It doesn’t make sense to me, to pay the completion cost each time - especially for the deployed ones like together ai. Tried to enable model-specific caching for this. But it didn't work (i perceived this as the response time was the same when i made 2 subsequent calls to the model - whereas i'd expect it to be faster. I also wasn't able to see if the response was cached and returned via litedebugger.

**Comment by ghost** [comment]
@yujonglee did 

```
litellm.caching_with_models = True
```

work for you?

**Comment by ghost** [comment]
cc: @ishaan-jaff

**Comment by ishaan-jaff** [comment]
Can you show steps to repro your problem ?

**Comment by ishaan-jaff** [comment]
it seems like there are 2 issues here: 

- LiteLLM Caching does not work as expected 
- Add Caching to the LiteLLM debugger for observability

**Comment by ishaan-jaff** [comment]
https://github.com/BerriAI/litellm/issues/new

**Comment by ishaan-jaff** [comment]
lets use this to debug the litellm caching not working as expected

**Comment by ghost** [comment]
did you just link me to the create new link? lol

**Comment by ishaan-jaff** [comment]
that's my bad @krrishdholakia 

I fixed caching. verified it works on a notebook here too: 

https://github.com/BerriAI/litellm/blob/main/cookbook/LiteLLM_Caching.ipynb

**Comment by ishaan-jaff** [comment]
@krrishdholakia can you try it and see if it works for you too !

feel free to re open this if it does not work

**Comment by abhimanyupallavisudhir** [comment]
Wait, I don't get it -- so right now what happens by default? Does sending the same prompt to a different model result in the answer being pulled from the cached answer for the first model?

**Comment by ghost** [comment]
No @abhimanyupallavisudhir 

our caching logic computes a cache key which covers all openai parameters sent in the request - https://github.com/BerriAI/litellm/blob/9f0f2b3f016a334a9e192e056f0c7f51da473f50/litellm/caching/caching.py#L232

so if you sent the same request to a different model or even the same request with different optional params (e.g. temperature) to the same model, caching would not be triggered
