### ISSUE TITLE
[Bug]: Invokation not found in SageMaker since region is `hard-coded`

### ISSUE THREAD

**Issue by hooman-bayer** [BerriAI/litellm#2086]
### What happened?

It seems like due to `aioboto3` enforcing the region, the endpoints deployed in regions other than `us-west-2` (e.g. `eu-central-1`) fail and are not found. Is there a reason that `us-west-2` is hardcoded [here](https://github.com/BerriAI/litellm/blob/89caef30382bab16e5db0961ebf214d25aebca3b/litellm/llms/sagemaker.py#L369) and [here](https://github.com/BerriAI/litellm/blob/89caef30382bab16e5db0961ebf214d25aebca3b/litellm/llms/sagemaker.py#L398) ?

This seems to have happened after `1.24` release.

### Relevant log output

```shell
'An error occurred (ValidationError) when calling the InvokeEndpoint operation: Endpoint <ENDPOINT-NAME> of account <NR> not found.'
```

### Twitter / LinkedIn details

https://www.linkedin.com/in/hooman-s-449b0838

**Comment by ghost** [comment]
Hey @hooman-bayer no - this was not intentional, and was missed during the aioboto3 merge. Thanks for flagging it. I'll have this fixed by tomorrow and add more region testing for our acompletion endpoint.

**Comment by hooman-bayer** [comment]
thanks @krrishdholakia for your quick response :)

**Comment by ghost** [comment]
merged into main, will be out in next release v`v1.26.5`+
