### ISSUE TITLE
[Bug]:  Unexpected Model Deletion in POST /key/update When Updating Team ID

### ISSUE THREAD

**Issue by lucebert** [BerriAI/litellm#2091]
### What happened?

# Issue Summary:
When attempting to update the team_id associated with a key using the POST /key/update endpoint, all models previously associated with the key are unexpectedly deleted. This behavior occurs without any errors being returned by the API, leading to the loss of model associations.

# Steps to Reproduce:

Sent a POST request to /key/update with the following payload to update the team_id for an existing key:
```
{
  "team_id": "new_team_id",
  "key": "sk-..."
}
```

Received the response confirming the update but indicating that the models array is now empty, implying all models have been disassociated from the key:

```
{
  "key": "sk-...",
  "models": [],
  "team_id": "new_team_id",
  "allowed_cache_controls": [],
  "aliases": {},
  "config": {},
  "permissions": {},
  "model_max_budget": {}
}
```

## Expected Behavior:
The team_id for the key is updated without affecting the association of models to the key. The models array should retain all previously associated models unless explicitly modified.

## Actual Behavior:
The models array is returned empty, indicating that all model associations have been removed following the team_id update, which was not the intended action.

**Comment by ishaan-jaff** [comment]
PR here @lucebert
