### ISSUE TITLE
[Feature]: Enable ad-hoc recognizers for presidio 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#2099]
### The Feature

```bash
curl -d '{
  "text": "John Smith AHV number is 756.3026.0705.92. Zip code: 10023",
  "language": "en",
  "ad_hoc_recognizers": [
    {
      "name": "Zip code Recognizer",
      "supported_language": "en",
      "patterns": [
        {
          "name": "zip code (weak)",
          "regex": "(\b\d{5}(?:\-\d{4})?\b)",
          "score": 0.01
        }
      ],
      "context": ["zip", "code"],
      "supported_entity": "ZIP"
    },
    {
      "name": "Swiss AHV Number Recognizer",
      "supported_language": "en",
      "patterns": [
        {
          "name": "AHV number (strong)",
          "regex": "(756\.\d{4}\.\d{4}\.\d{2})|(756\d{10})",
          "score": 0.95
        }
      ],
      "context": ["AHV", "social security", "Swiss"],
      "supported_entity": "AHV_NUMBER"
    }
  ]
}' -H "Content-Type: application/json" -X POST http://localhost:3000/analyze
```

this detects the swiss AHV Number: [{"analysis_explanation": null, "end": 41, "entity_type": "AHV_NUMBER", "recognition_metadata": {"recognizer_identifier": "Swiss AHV Number Recognizer_140453887187744", "recognizer_name": "Swiss AHV Number Recognizer"}, "score": 0.95, "start": 25}, {"analysis_explanation": null, "end": 10, "entity_type": "PERSON", "recognition_metadata": {"recognizer_identifier": "SpacyRecognizer_140453912086800", "recognizer_name": "SpacyRecognizer"}, "score": 0.85, "start": 0}, {"analysis_explanation": null, "end": 58, "entity_type": "ZIP", "recognition_metadata": {"recognizer_identifier": "Zip code Recognizer_140453887187264", "recognizer_name": "Zip code Recognizer"}, "score": 0.4, "start": 53}]

### Motivation, pitch

user request:
- it would be great if you could extent the config to support additional ad-hoc recognizer. It would give everything a huge flexibility without changing the presidio images.

**Comment by ghost** [comment]
No ad-hoc recognizer result: ```<PERSON> AHV number is 756.3026.0705.92. Zip code: <US_DRIVER_LICENSE>```

With ad-hoc recognizer result: ```<PERSON> AHV number is <AHV_NUMBER>. Zip code: <US_DRIVER_LICENSE>```

**Comment by ghost** [comment]
merged into main, will be out in next release v`v1.26.5`+
