### ISSUE TITLE
[Bug]: UI not loading on root URL

### ISSUE THREAD

**Issue by adrien-f** [BerriAI/litellm#2109]
### What happened?

Hey there !

Since v1.26.6, the UI does not load by default on `/ui`. This is caused by these lines: https://github.com/BerriAI/litellm/blob/7f179e13eeac06636e6f839d52dab075a4ed6215/ui/litellm-dashboard/src/app/page.tsx#L72-L74

Which will stop the loading process if there's nothing in session. The redirection that should happen on the default page here: https://github.com/BerriAI/litellm/blob/7f179e13eeac06636e6f839d52dab075a4ed6215/ui/litellm-dashboard/src/components/user_dashboard.tsx#L152-L157

Not sure how it is possible to align the logic between these two pages 🤔

**Comment by ishaan-jaff** [comment]
sorry about this, I pushed out a new feature will fix asap

**Comment by adrien-f** [comment]
No worries!

**Comment by ishaan-jaff** [comment]
Fixed here @adrien-f : https://github.com/BerriAI/litellm/commit/de9336e1fc746577ec884e921a8d1bd2fe7c22b2

**Comment by ishaan-jaff** [comment]
started a new release

**Comment by ishaan-jaff** [comment]
Fix is here: https://github.com/BerriAI/litellm/releases/tag/v1.26.7 @adrien-f can you confirm it's fixed for you too
