### ISSUE TITLE
[LiteDebugger] Debugger + Key manager is weird

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#211]
It's weird to me that you're my debugger and key manager. Right now i have an error due to the debugger - but I can't turn it off since all my model keys are also hosted through the same integration.

**Comment by ghost** [comment]
cc: @ishaan-jaff

**Comment by ghost** [comment]
i hate that i can't turn this off - i perceive there to be some issue with logging which is causing my stream responses to not work but i have no ability to turn this off.

**Comment by ishaan-jaff** [comment]
why do u need to switch off the debugger ?

**Comment by ghost** [comment]
I believe there's an error in logging causing the generator to be read before it's returned. 

<img width="1086" alt="Screenshot 2023-08-26 at 11 04 46 AM" src="https://github.com/BerriAI/litellm/assets/17561003/d51c696d-ace7-4c29-8d36-36331a9ddf15">
<img width="1107" alt="Screenshot 2023-08-26 at 11 04 58 AM" src="https://github.com/BerriAI/litellm/assets/17561003/e6cd43c9-51ca-4c70-bc6e-91f0861c20cc">

**Comment by ghost** [comment]
Just exposed a `litellm.logging` variable. You can set it to false to turn off litedebugger, and still use the key manager. 

Turns out I was right - there was an error with logging for streaming.

**Comment by ghost** [comment]
It wasn't returning an error - just an empty response - so our tests weren't catching it. As a user, being unable to triage this was frustrating (but fixed now :))

**Comment by ghost** [comment]
now i need to fix this b/c i don't want to be in prod without debugging working :)

**Comment by ghost** [comment]
works when `litellm.logging=False` (v0.1.487) 

<img width="1291" alt="Screenshot 2023-08-26 at 11 08 52 AM" src="https://github.com/BerriAI/litellm/assets/17561003/53678e4f-0e03-4243-8927-3e225b076e45">

**Comment by ghost** [comment]
How do we improve here: 
- [x] Exposed logging - allow users to turn off logging and still use the key manager.
- [x] Fix testing -> our test_streaming should have caught this but didn't. Raise an exception on empty responses.

**Comment by ishaan-jaff** [comment]
hmm feels like we have so much bloat of input variables now too

**Comment by ghost** [comment]
Let me know if there's anything else we could / should do here @ishaan-jaff

**Comment by ishaan-jaff** [comment]
input_callback: List[str] = []
success_callback: List[str] = []
failure_callback: List[str] = []
set_verbose = False
email: Optional[str] = None  # for hosted dashboard. Learn more - https://docs.litellm.ai/docs/debugging/hosted_debugging
token: Optional[str] = None  # for hosted dashboard. Learn more - https://docs.litellm.ai/docs/debugging/hosted_debugging
telemetry = True
max_tokens = 256  # OpenAI Defaults
retry = True
api_key: Optional[str] = None
openai_key: Optional[str] = None
azure_key: Optional[str] = None
anthropic_key: Optional[str] = None
replicate_key: Optional[str] = None
cohere_key: Optional[str] = None
openrouter_key: Optional[str] = None
huggingface_key: Optional[str] = None
vertex_project: Optional[str] = None
vertex_location: Optional[str] = None
togetherai_api_key: Optional[str] = None
baseten_key: Optional[str] = None
use_client = False
caching = False
caching_with_models = False  # if you want the caching key to be model + prompt
api_base = None
headers = None
api_version = None
organization = None
config_path = None
####### Secret Manager #####################
secret_manager_client = None

**Comment by ghost** [comment]
I agree, I assume there'll be a period of clean-up - as long as the variables exposed and discussed in documentation are consistent, I don't believe this to be a major issue. Maybe for "unstable" variables we can mark them with "_" before the name. To indicate that they're private variables and subject to change. 

Example `litellm._logging`.

**Comment by ghost** [comment]
testing updated to catch empty responses as well.

**Comment by ishaan-jaff** [comment]
+1 this is pretty weird. Can we put logs on a separate page ?

I find it weird / annoying that the key mgmt stuff is on the logs page 

@krrishdholakia wdyt ?
