### ISSUE TITLE
Manage rate limits on the team level

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#2112]

**Comment by ghost** [comment]
Table + User schemas already have tpm/rpm limits + budgets 

**Missing:**
- Allow `/team/new` to set team tpm/rpm/max_budget values
- Enforce team budgets (tpm/rpm/spend)

**Comment by ghost** [comment]
Splitting this into 2 PR's 

- Allow /team/new to set team tpm/rpm/max_budget values - @krrishdholakia 
- Enforce team budgets (tpm/rpm/spend) - @ishaan-jaff (ties into his work on using a view for quicker queries)

**Comment by ghost** [comment]
We support setting rate limits. 

Now we need to work on enforcing team rate limits. 

- [ ] Check if user db has a view 
- [ ] If no, create a view {key_row, team_row} 
- [ ] Check if team budget (max_budget/tpm/rpm limit) hit when a request is made 
- [ ] Fail request if it has
