### ISSUE TITLE
[Bug]: LITELLM_MASTER_KEY leaked to Langfuse

### ISSUE THREAD

**Issue by dkindlund** [BerriAI/litellm#2114]
### What happened?

Steps to reproduce:
1. Configure the LiteLLM OpenAI Proxy and specify a custom `LITELLM_MASTER_KEY` as an environment variable in the container
2. Setup Langfuse so that the proxy sends all successful completions to Langfuse
3. In the Langfuse Trace UI, see that there's a `user_api_key:XXXX` tag where XXXX contains the full contents of the `LITELLM_MASTER_KEY`

Pretty sure this info shouldn't be sent over to Langfuse.

![image](https://github.com/BerriAI/litellm/assets/85660/e4249871-ab27-4405-9655-eb1f38f06767)

**Comment by ghost** [comment]
is that the raw key or the hashed token? @dkindlund

**Comment by dkindlund** [comment]
@krrishdholakia , that's the *raw* key -- not hashed.

**Comment by ghost** [comment]
Noted - that's a high priority issue. will get this fixed asap. Thanks for flagging @dkindlund

**Comment by ishaan-jaff** [comment]
is this fixed @krrishdholakia ?

**Comment by ghost** [comment]
unfortunately not yet - we should fix this though. attaching it to this week's board. sorry about that @dkindlund

**Comment by Manouchehri** [comment]
What caused this? I'm only seeing a hashed `user_api_key` in our Langfuse logs at the moment.

**Comment by ishaan-jaff** [comment]
> What caused this? I'm only seeing a hashed

@Manouchehri  did you try with the master key ?

**Comment by Manouchehri** [comment]
> did you try with the master key ?

You mean doing a request with the master key? (We have that firewalled off, isn't doable atm thankfully. 😄 )

**Comment by ishaan-jaff** [comment]
> You mean doing a request with the master key? (We have that firewalled off, isn't doable atm thankfully. 😄 )

Yeah I believe that was triggering it

**Comment by ishaan-jaff** [comment]
if your master key does not begin with `sk-` i believe we used to not hash it This might actually be fixed now - but a test should be added for this issue 

iirc we now require master keys to start with `sk-`

**Comment by Manouchehri** [comment]
Does LiteLLM support having _no_ `LITELLM_MASTER_KEY` yet?

**Comment by ghost** [comment]
This issue was caused by not hashing the master key in the UserAPIKeyAuth object. 

We now do this + have unit tests for this
