### ISSUE TITLE
[Feature]: New Models - Support Google Gemma 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#2118]
### The Feature

https://ai.google.dev/gemma/docs/setup 

### Motivation, pitch

-

**Comment by ishaan-jaff** [comment]
I think we already support this since we support Vertex AI model garden. 

Just tried deploying but I don't have quota on GCP :(

**Comment by ghost** [comment]
it's on huggingface and tgi compatible - i believe this is already supported
