### ISSUE TITLE
ban competitor / keywords

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#2121]
if we just allow a user to set a list of banned keywords, we can do quick checks during streaming for simple output moderation 

this would be significantly faster than the user needing to set up an external api for just keyword checking.

**Comment by ghost** [comment]
## Thinking 

How would the user pass this? 

Could be similar to how we do the other moderation stuff on proxy 

```yaml
litellm_settings: 
     banned_keywords: /path/to/banned_keywords.txt 
```

Expected format in .txt

```txt
competitor_1
competitor_2
banned_keyword_1
banned_keyword_2
```

**Comment by ghost** [comment]
mounting files can be a pain, might be easier to start with just a list 

```yaml 
litellm_settings: 
     banned_keywords: ["competitor_1", "competitor_2", "banned_keyword_1"]
```

**Comment by ghost** [comment]
Closing as this is now live
