### ISSUE TITLE
[Feature]: Add support for "completion_start_time" with Langfuse intégration

### ISSUE THREAD

**Issue by Lunik** [BerriAI/litellm#2132]
### The Feature

Langfuse intégration for logging report wrong "latency" when using streaming.

The actual implementation in Litellm only populate `start_time` and `end_time`. When creating a streamed completion trought Litellm we should set the `completion_start_time` to the time when the first token is generated

Documentation référence : https://langfuse.com/docs/sdk/python#generation

### Motivation, pitch

Languse supports for Models latencies supervision : 
![image](https://github.com/BerriAI/litellm/assets/12114079/cbe81693-b695-40c7-9f4e-5f4bc4db9f98)

When making streamed completion, the latencies corresponds to the full completion generation. It should be the time to first token instead to be more accurate to reality

**Comment by ghost** [comment]
picking this up today

**Comment by ghost** [comment]
@Lunik can we do a quick call sometime next week? Want to learn how you're using litellm today 

https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
