### ISSUE TITLE
Tags Block List - block Requests if a tag is in a block list

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#2136]

**Comment by ghost** [comment]
i think we could use openai's `user_id` param for this

**Comment by ghost** [comment]
## Thinking 

How does admin set this list? 

For v1, should this just be a list of banned user_id's? 

```yaml
litellm_settings: 
     blocked_user_id_list: ["user_id_1", "user_id_2", ...] 
```

could make it easier and have it be a txt 

```yaml 
litellm_settings: 
     blocked_user_id_list: ./blocked_user_list.txt 
```

**Comment by ghost** [comment]
Ideally this would be an api or some sort of live updating source, so when a user opts out - the proxy is immediately aware, and any future requests are automatically blocked 

Maybe it could just be via a `/config/update` and the value is set in the config table

**Comment by ghost** [comment]
this is now live
