### ISSUE TITLE
Log key alias as part of langfuse key metadata

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#2137]

**Comment by ghost** [comment]
@dkindlund how would you use this on langfuse? (trying to figure out implementation) 

Is the idea to write a sql query on the data in the db to understand spend per key / team?

**Comment by ghost** [comment]
Updating based on conversation: 
- team_id being logged as part of call metadata is fine 
- key_alias needs to be logged as well

cc: @dkindlund
