### ISSUE TITLE
[Bug]: have azure openai function calling w/ streaming look same as openai 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#2138]
### What happened?

azure openai function calling with streaming has a function arg that's none, which makes it incompatible with a pure openai client receiver

**Comment by dkindlund** [comment]
Ref: https://github.com/langchain-ai/langchainjs/issues/4488

**Comment by ghost** [comment]
I see the issue 

First chunk arguments should be an empty string `''`
```
chunk: ModelResponse(id='chatcmpl-8vC5cyDmxXLyfKKgbh6l8oMjWaTOE', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(function_call=ChoiceDeltaFunctionCall(arguments='', name='get_current_weather'), tool_calls=None, content=None, role='assistant'))], created=1708641860, model='gpt-3.5-turbo', object='chat.completion.chunk', system_fingerprint='fp_86156a94a0', usage=Usage())
```


Azure returns a None chunk `None` 

```
chunk: ModelResponse(id='chatcmpl-8vC4IPvl2UiDeY8KdMySB4L0UBPNN', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(function_call=ChoiceDeltaFunctionCall(arguments=None, name='get_current_weather'), tool_calls=None, content=None, role='assistant'))], created=1708641779, model='gpt-4', object='chat.completion.chunk', system_fingerprint='fp_8abb16fa4e', usage=Usage())
```

**Comment by ghost** [comment]
This is now fixed @dkindlund

**Comment by ghost** [comment]
reopening as the issue wasn't fixed on flowise

**Comment by ghost** [comment]
Steps to fix this 

- Make streaming function call with openai 
- Add format tests for 1st chunk, 2nd chunk, last chunk 
- Run azure openai streaming function call through that test
- Fix any issues that come up

**Comment by dkindlund** [comment]
This is now resolved.  Thanks again, @krrishdholakia !
