### ISSUE TITLE
Replicate error - auth error with REPLICATE_API_KEY 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#214]
requests failed when i set REPLICATE_API_KEY

started working after i used REPLICATE_API_TOKEN

**Comment by ghost** [comment]
that's odd - i use REPLICATE_API_KEY and don't see this 

was the key visible to litellm from your .env?

**Comment by ishaan-jaff** [comment]
i ran in it in a nb and set os.environ['REPLICATE_API_KEY']

**Comment by ishaan-jaff** [comment]
<img width="1192" alt="Screenshot 2023-08-31 at 9 07 38 AM" src="https://github.com/BerriAI/litellm/assets/29436595/3147cad2-0908-4d9d-ad06-32d40a841b0b">

works fine !
