### ISSUE TITLE
[Feature]: fix discord publish workflow for github releases

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#2146]
### The Feature

our publish to discord workflow isn't working 

https://github.com/BerriAI/litellm/blob/21b132cff6105f635ffa95d4916cd0cb6221e5df/.github/workflows/ghcr_deploy.yml#L150

It would be great if somebody could help with this 

### Motivation, pitch

Help users keep up with latest litellm releases

**Comment by H0llyW00dzZ** [comment]
> ### The Feature
> our publish to discord workflow isn't working
> 
> https://github.com/BerriAI/litellm/blob/21b132cff6105f635ffa95d4916cd0cb6221e5df/.github/workflows/ghcr_deploy.yml#L150
> 
> It would be great if somebody could help with this
> 
> ### Motivation, pitch
> Help users keep up with latest litellm releases
> 
> ### Twitter / LinkedIn details
> _No response_

It might be possible to address this by using a RESTful API method, similar to my CI/CD implementation

Example:

![image](https://github.com/BerriAI/litellm/assets/17626300/39f028d8-8a73-4f5a-862d-ebbbb647cc61)

**Comment by H0llyW00dzZ** [comment]
actually its possible by using a RESTful API method

here is the reference:
https://discord.com/developers/docs/resources/webhook#execute-webhook
