### ISSUE TITLE
[Bug]: The JWT encode implementation uses a weak static signing secret of "secret" 

### ISSUE THREAD

**Issue by portswigger-ben** [BerriAI/litellm#2158]
### What happened?

This might not be the correct place to raise security issues but I couldn't see another channel.

The implementation should probably be changed to use a secret supplied at runtime?

https://github.com/BerriAI/litellm/blob/2c378d96b776d512cdec7d87bccceab1189f95e9/litellm/proxy/proxy_server.py#L5232

It's also not best practice to put the JWT in URL query params
https://github.com/BerriAI/litellm/blob/2c378d96b776d512cdec7d87bccceab1189f95e9/litellm/proxy/proxy_server.py#L5235C56-L5235C77

And there’s a suspicious looking use of a secret key inside the JWT that might be worth some investigation.
https://github.com/BerriAI/litellm/blob/2c378d96b776d512cdec7d87bccceab1189f95e9/litellm/proxy/proxy_server.py#L5228

![F8BDD7D8-6601-48A8-9D10-A3E0170B5DB3](https://github.com/BerriAI/litellm/assets/118997693/bb85c95d-d6c8-4bda-a18c-e4f9a1b03eb2)

**Comment by portswigger-ben** [comment]
It's also not best practice to put the JWT in URL query params
https://github.com/BerriAI/litellm/blob/2c378d96b776d512cdec7d87bccceab1189f95e9/litellm/proxy/proxy_server.py#L5235C56-L5235C77

**Comment by ishaan-jaff** [comment]
Thanks for raising this @portswigger-ben - do you use the litellm proxy server today ?

**Comment by ishaan-jaff** [comment]
> It's also not best practice to put the JWT in URL query params

We're moving to storing this as cookies

**Comment by ishaan-jaff** [comment]
> looking use of a secret key inside the JWT

This is a short lived key we generate to access the proxy through the UI

**Comment by portswigger-ben** [comment]
> Thanks for raising this @portswigger-ben - do you use the litellm proxy server today ?

Hi @ishaan-jaff, we are looking at a number of LLM proxies and spotted these couple of issues and wanted to make the project aware.

**Comment by ghost** [comment]
picking up this issue, this week. @portswigger-ben any specific problem you were trying to solve with your proxy?

**Comment by Manouchehri** [comment]
> We're moving to storing this as cookies

Do we have a ticket for this? (I know we talked about it in Discord/Google Meet, not sure if we made a ticket.)

**Comment by tylerbrandt** [comment]
> > We're moving to storing this as cookies
> 
> Do we have a ticket for this? (I know we talked about it in Discord/Google Meet, not sure if we made a ticket.)

#1740 maybe?

**Comment by ghost** [comment]
sorry for the delay here, any help on this would be great! 

Especially now that we have a jwt-auth implementation for the proxy - https://github.com/BerriAI/litellm/blob/a24f32fb5ad4a2f861765f73cae5f44e0dd0e912/litellm/proxy/auth/handle_jwt.py#L4

cc: @tylerbrandt @Manouchehri

**Comment by ishaan-jaff** [comment]
PR to store the JWT in cookies here: https://github.com/BerriAI/litellm/pull/4357

**Comment by ishaan-jaff** [comment]
We've also move to using a hash of the master key as a signing secret https://github.com/BerriAI/litellm/pull/4357

**Comment by ishaan-jaff** [comment]
cc @dlebech @portswigger-ben @tylerbrandt
