### ISSUE TITLE
Allow finetuning in the OpenAI format 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#216]
together AI allows you to finetune models - seems useful if we can standardize finetuning jobs in the OpenAI format

https://docs.together.ai/docs/fine-tuning

**Comment by ghost** [comment]
Who's problem does this solve? 

Together AI also offers a pretty decent UI for doing this. 
<img width="1168" alt="Screenshot 2023-08-26 at 3 58 41 PM" src="https://github.com/BerriAI/litellm/assets/17561003/94839771-cdb2-4ad8-b058-a2aaa265f4ef">


OpenAI's api for doing this was pretty straightforward too.

**Comment by ishaan-jaff** [comment]
closing - seems like a distraction for now
