### ISSUE TITLE
Admin UI - Set a limited list in the models field of a user

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#2162]
## Problem 

Prevent user from creating key for a model that is not allowed to them 

cc: @Lunik

**Comment by ghost** [comment]
## Thinking 

We could do something similar to what we did for keys: 
```
litellm_settings:
  default_user_params:
    modes: ["gpt-3.5-turbo"] # default model everyone has access to 
```

**Comment by ghost** [comment]
When is a new user written to our db? 

- Our sso logic assumes a user already exists when they login, this isn't always true. This means when a user logs in via `/sso/callback` we should be doing an upsert operation to make sure they exist in the litellm db.

**Comment by ghost** [comment]
Documenting issues. 

Created a user on keycloak. 

I'm logged in as app owner, but I can see all models on proxy: 
<img width="1700" alt="Screenshot 2024-02-23 at 2 38 52 PM" src="https://github.com/BerriAI/litellm/assets/17561003/8eff17d9-aa2d-4beb-b3ea-5dff637d5292">

**Comment by ghost** [comment]
Seeing hashed token issue that @Lunik saw
<img width="1709" alt="Screenshot 2024-02-23 at 2 39 53 PM" src="https://github.com/BerriAI/litellm/assets/17561003/4caf0a9c-e658-4ec1-9b14-d8b3610e63fd">

**Comment by ishaan-jaff** [comment]
> I'm logged in as app owner, but I can see all models on proxy: 

This is intentional - you should be able to see all models, even ones you don't have access to. IMO App owners should be able to request models they don't have access to

**Comment by ghost** [comment]
@ishaan-jaff agreed you should see what's available, but it says i have access to all models

**Comment by ghost** [comment]
fixed call issue 
<img width="1180" alt="Screenshot 2024-02-23 at 2 43 25 PM" src="https://github.com/BerriAI/litellm/assets/17561003/c38d95f2-1058-4d9e-a5f6-f2d0b6b347d1">

**Comment by ghost** [comment]
Issue 1: 

new user unable to create keys 
<img width="1342" alt="Screenshot 2024-02-23 at 3 43 56 PM" src="https://github.com/BerriAI/litellm/assets/17561003/ac3160ea-199c-46d1-b137-3d26ce979525">

**Comment by ghost** [comment]
Issue 2: 

new user (not even in proxy db) is able to see all models while creating a key 

<img width="950" alt="Screenshot 2024-02-23 at 3 44 22 PM" src="https://github.com/BerriAI/litellm/assets/17561003/2de76328-a950-4ee9-8ce2-69fc3bfdae9b">

**Comment by ghost** [comment]
Looks like the dropdown calls `/model/info` 

I think this would be solved by just calling the `/models` endpoint - it's written to just return models the user has access to

**Comment by ghost** [comment]
Just pushed fixes for 
- model dropdown for create key 
- Chat Ui 


We now support a default_user_params as a litellm setting, so you can do 

```
litellm_settings: 
      default_user_params: 
          models: ["gemini-pro"] 
```

and all new SSO users will just have access to gemini-pro

**Comment by ghost** [comment]
this is now live
