### ISSUE TITLE
Admin UI - allow admin to create teams on proxy

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#2181]
## Problem 

Give 10 people access to the UI 

Once a user can log in on the UI
    - Create key
    - Request models
    - Automatically assign them teams

cc: @Lunik

**Comment by ghost** [comment]
We could do this similar to Langfuse:
-  allow admin to create a team (set models, rate limits, budget) 
-  add new members (based on email) and assign them roles (admin, user) 
<img width="740" alt="Screenshot 2024-02-24 at 10 38 12 AM" src="https://github.com/BerriAI/litellm/assets/17561003/3d6ccd20-3465-4e0b-9978-d3351d977580">

**Comment by ghost** [comment]
Roughly something like this 

<img width="480" alt="Screenshot 2024-02-24 at 11 50 15 AM" src="https://github.com/BerriAI/litellm/assets/17561003/5ae62d25-4ab7-45e0-8474-a10cd0887759">

And then something like this for adding new members 

<img width="649" alt="Screenshot 2024-02-24 at 11 50 51 AM" src="https://github.com/BerriAI/litellm/assets/17561003/654658fe-e199-4778-9a4a-af3df6204fa9">

**Comment by ghost** [comment]
This is now live
