### ISSUE TITLE
[Feature]: function calling through litellm PROXY for non-OpenAI models

### ISSUE THREAD

**Issue by RomanKoshkin** [BerriAI/litellm#2194]
### The Feature

I'm using a locally run Mixtral exposed through `text-generation-inference`. I'm also useing litellm proxy as an interface between LangChan and TGI. Everything work fine, but not with function calling. I know I can set `litellm.add_function_to_prompt = True`, but I'm only using litellm as a proxy, and I wish I could add this `add_function_to_prompt` parameter when I run the litellm proxy server.

### Motivation, pitch

This feature would enabel function calling for non-openai models called though the litellm proxy.

**Comment by ghost** [comment]
You can @RomanKoshkin 
```yaml
litellm_settings: 
    add_function_to_prompt: true
```

Where in docs would this have been helpful to see?

**Comment by RomanKoshkin** [comment]
> ```yaml
> litellm_settings
> ```

Maybe somewhere [here](https://docs.litellm.ai/docs/proxy/configs)?🙏
