### ISSUE TITLE
[Bug]: Vertex/Gemini streaming chunks always have finish_reason='stop'

### ISSUE THREAD

**Issue by joch** [BerriAI/litellm#2195]
### What happened?

Hi, I'm trying to use Gemini through vertex_ai, and while it works, I'm seeing some weird behavior compared to how other models respond.

I am doing completion using async + streaming, and it seems that when using Gemini, all chunks return `finish_reason='stop'`, which is unexpected. Using gpt3/4 for instance, returns `finish_reason='stop'` after the last chunk.

Here is a simple Python test to verify this:

```python
async def fetch_completion():
  response = await litellm.acompletion(
    model="vertex_ai/gemini-pro",
    messages=[{"content": "Hello, who are you?", "role": "user"}],
    stream=True,
  )
  async for data in response:
    print(data)

if __name__ == "__main__":
  asyncio.run(fetch_completion())
```

### Relevant log output

```shell
returning model_response: ModelResponse(id='chatcmpl-a86e1d52-5525-4409-a734-6bd60187cb51', choices=[StreamingChoices(finish_reason='stop', index=0, delta=Delta(content='I am Gemini, a multimodal AI language model developed by Google. I am designed to understand and generate human language, and to provide information and answer questions to the', role='assistant', function_call=None, tool_calls=None), logprobs=None)], created=1708955003, model='gemini-pro', object='chat.completion.chunk', system_fingerprint=None, usage=Usage())

returning model_response: ModelResponse(id='chatcmpl-a86e1d52-5525-4409-a734-6bd60187cb51', choices=[StreamingChoices(finish_reason='stop', index=0, delta=Delta(content=' best of my abilities.', role=None, function_call=None, tool_calls=None), logprobs=None)], created=1708955003, model='gemini-pro', object='chat.completion.chunk', system_fingerprint=None, usage=Usage())
```

**Comment by ghost** [comment]
Hey @joch, which version of litellm is this on?

**Comment by joch** [comment]
@krrishdholakia tried with the latest (1.27.4)

**Comment by ghost** [comment]
able to repro. working on it now.

**Comment by ghost** [comment]
fix pushed, will update once it's in prod

**Comment by joch** [comment]
I can confirm it's working now. Thanks for the quick turnaround!

**Comment by ghost** [comment]
@joch Awesome. 

Can you chat for ~10 mins this week? Would love to learn how you're using litellm

https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by joch** [comment]
@krrishdholakia hi, a bit difficult this week, especially considering time zones. I’ll reach out on LinkedIn later today. 🙂
