### ISSUE TITLE
[Feature]: support mistral-large

### ISSUE THREAD

**Issue by afbarbaro** [BerriAI/litellm#2200]
### The Feature

Mistral Large was released today: https://mistral.ai/news/mistral-large/
Other models (tiny, small, medium) are already supported. Can we add this new one quickly?
I'm happy to get a PR for it if there's another one I can follow as a reference to make this addition.
Thanks!~

### Motivation, pitch

This new large model gets a lot closer to GPT-4. The more (LLMs) the merrier!

**Comment by ishaan-jaff** [comment]
Done here: https://github.com/BerriAI/litellm/commit/da4832d5a29515d966daf5118ce0f13837900dc9

**Comment by ishaan-jaff** [comment]
There's no need to wait for a new release - it should work on main for you

**Comment by ishaan-jaff** [comment]
can you let me know if it works @afbarbaro ?

**Comment by themrzmaster** [comment]
does function calling work?

**Comment by ghost** [comment]
yes i believe it should. You can test it here: 

```python
from litellm import completion
import os

os.environ['MISTRAL_API_KEY'] = ""

tools = [
  {
    "type": "function",
    "function": {
      "name": "get_current_weather",
      "description": "Get the current weather in a given location",
      "parameters": {
        "type": "object",
        "properties": {
          "location": {
            "type": "string",
            "description": "The city and state, e.g. San Francisco, CA",
          },
          "unit": {"type": "string", "enum": ["celsius", "fahrenheit"]},
        },
        "required": ["location"],
      },
    }
  }
]
messages = [{"role": "user", "content": "What's the weather like in Boston today?"}]
completion = completion(
  model="mistral/mistral-large-latest",
  messages=messages,
  tools=tools,
  tool_choice="auto"
)

print(completion)
```

**Comment by ghost** [comment]
can we close this issue, if this works for y'all? @afbarbaro @themrzmaster

**Comment by themrzmaster** [comment]
with this code i get

APIError: MistralException - Function calling is not supported by mistral. To add it to the prompt, set `litellm.add_function_to_prompt = True`.

**Comment by afbarbaro** [comment]
Thanks for working on this @krrishdholakia. I haven't tried it yet, but we also need the function calling capability as indicated by @themrzmaster.

**Comment by afbarbaro** [comment]
I also left some comments in the code to address an issue with the max content length not being 32k for the new model

**Comment by ghost** [comment]
Mistral's api doesn't support function calling (so far as i can tell) 

Is there something we can do to help here? @themrzmaster @afbarbaro

**Comment by afbarbaro** [comment]
@krrishdholakia I believe it does support function calling, but only with the `tools` and `tool_choice` properties, not with the deprecated `function` and `function_call` properties.

https://docs.mistral.ai/guides/function-calling/

**Comment by ishaan-jaff** [comment]
context window fixed here: https://github.com/BerriAI/litellm/commit/66388f1dfcac200e7c1cb2f48dd8d8dce3fded25

**Comment by ishaan-jaff** [comment]
for function calling we need to support the tools/tool_choice param for mistral

**Comment by ishaan-jaff** [comment]
tool calling here @afbarbaro https://github.com/BerriAI/litellm/commit/a525fca84719e19a20e1df48e6d53b0cd44bbe7a

**Comment by themrzmaster** [comment]
nice, does it work with azure mistral as well?

**Comment by ishaan-jaff** [comment]
yes @themrzmaster just make sure you use it with the `mistral/` prefix

**Comment by themrzmaster** [comment]
@ishaan-jaff still same error. did you try running the example?

**Comment by ishaan-jaff** [comment]
there's no new release out - how did you try it ?

**Comment by ishaan-jaff** [comment]
nvm I see the error on a local test

**Comment by ishaan-jaff** [comment]
fixed here: https://github.com/BerriAI/litellm/pull/2241/commits/13040a97a74155a53d0aaaaddb3c86b9a1f9732a

**Comment by ghost** [comment]
closing as this is now live in v`1.28.0`

**Comment by ishaan-jaff** [comment]
can you confirm this works @themrzmaster @afbarbaro ?
