### ISSUE TITLE
Langchain Integration - Error in COHERE_API_KEY 

### ISSUE THREAD

**Issue by lucken99** [BerriAI/litellm#221]
What's the problem? (if there are multiple - list as bullet points)
Although I am providing API Key  using python String Variable. It is not loading in litellm.

![image](https://github.com/BerriAI/litellm/assets/33358596/1afc69eb-1903-4ad4-9e3d-3bc9017b865c)

**Comment by ishaan-jaff** [comment]
can you try setting os.environ['COHERE_API_KEY'] = 'your-key' and run this

**Comment by ishaan-jaff** [comment]
@lucken99 this looks like a bug in our langchain integration

**Comment by lucken99** [comment]
Yes, it's bug.

**Comment by ishaan-jaff** [comment]
@lucken99 the patch for this is setting ` os.environ['COHERE_API_KEY'] = 'your-key'`

**Comment by ishaan-jaff** [comment]
it takes the langchain team about 1-2 days to merge our fix PR. We're working on improvements in our langchain integration so there's less delay

**Comment by lucken99** [comment]
Thanks

**Comment by ishaan-jaff** [comment]
@lucken99 curious why are you using our langchain integration ? Langchain already has a pretty good Chat() abstraction for most LLMs
