### ISSUE TITLE
[Feature]: Queue messages when exceeding max_parallel_requests

### ISSUE THREAD

**Issue by morgendigital** [BerriAI/litellm#2218]
### The Feature

If **max_parallel_requests** from an API key is exceeded, the API should not fire a 429 "Too Many Requests" error, but rather put the messages that are exceeding the request limit in a queue. As soon as one or more "request slots" are free (meaning, the actual requests are now lower than the max_parallel_requests), the queued message will be processed as usual, first in first out.

Ideally, a timeout for the queue should be settable, in order to test different queuing times and strategies and to not fill up the queue too much in case there is some error happening somewhere.

### Motivation, pitch

The functionality to set **max_parallel_requests** is currently useful to set hard limits on API keys. If it exceeds a specific value, we currently get a 429 error. However, a more graceful handling of it could be to queue the messages that exceed the current request limit and process them as soon as one or more request slots are free.

### Twitter / LinkedIn details

https://www.linkedin.com/in/ivandukic

**Comment by ghost** [comment]
this is supported via the retry mechanism now

**Comment by Manouchehri** [comment]
> this is supported via the retry mechanism now

How do I set RateLimitErrorAllowedFails and RateLimitErrorRetries in the yaml config?

**Comment by ghost** [comment]
https://github.com/BerriAI/litellm/blob/511f4d33d16ea3e6b5ebe8adf371f16393426fd3/litellm/proxy/proxy_server.py#L2856

it's the num_retries set on litellm_settings

**Comment by Manouchehri** [comment]
Ah, is it not possible to set the retries based on the error type? i.e. I only want to increase the RateLimitErrorRetries to like 100, not all types of errors.

**Comment by ghost** [comment]
https://docs.litellm.ai/docs/routing#advanced-custom-retries-cooldowns-based-on-error-type

cc: @ishaan-jaff for how to set this on proxy

**Comment by krrishdholakia** [comment]
i believe you can control this on the UI @Manouchehri
