### ISSUE TITLE
(User Request) Expose log probs for hf calls 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#223]
**Your feature request in one line**
 Expose log probs for hf calls 

**Describe the solution you'd like**
"i gave examples of issues I know are different between OpenAI and HuggingFace - log probs, number of possible stop tokens, repetition penalty parameter.
log probs specifically are quite important, and might worth adding dedicated support for them only for HF"

**Comment by ghost** [comment]
I don't like the idea of one-off changes to the output format - maybe we can have this be a consistent part, and be empty for those that don't return log probs (e..g openai chatcompletions). 

maybe adopt the way they did logprobs here - https://platform.openai.com/docs/api-reference/completions/create

**Comment by ghost** [comment]
done - daa949a539069594b267c37698a2a0e5eb0d3c97
