### ISSUE TITLE
[Feature]: Improve usage loading speeding - postgres db

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#2235]
### The Feature

Improve the speed at which usage logs are loaded for the UI w/ a connected postgres db 

### Motivation, pitch

User has ~1m logs, and unable to see usage due to slow load times

**Comment by ghost** [comment]
At 300k postgres db rows: 
- the monthly spend + top users loaded in 30s 
- top api keys never loaded 

<img width="1503" alt="Screenshot 2024-02-28 at 11 55 12 AM" src="https://github.com/BerriAI/litellm/assets/17561003/66eeb091-c1dc-4598-9ce2-e0520affa9b6">

**Comment by ghost** [comment]
- `spend/logs?start_date=2024-02-01&end_date=2024-02-29` request takes 20.68s to run on 310672 logs

**Comment by ghost** [comment]
Implementing a view over the global spend data reduced time to 4.19s

**Comment by ghost** [comment]
closing as this is now live
