### ISSUE TITLE
[Bug]: Using Mistral-large on Azure has whitespace in the beginning of the responses

### ISSUE THREAD

**Issue by joch** [BerriAI/litellm#2246]
### What happened?

Hi again. :)

See this snippet: `content=' Hello litellm!` (full log below) and notice the white space, which should not be there.

I'm seeing the same issue using both `completion` and `acompletion`.

```
litellm.completion(
    model="mistral/mistral-large-fr",
    api_base="xx",
    api_key="yy",
    messages=[{"role": "user", "content": "hello from litellm"}],
)
```

### Relevant log output

```shell
ModelResponse(id='1f98c810-fc83-4d93-92d9-b4ec6e8fe7cd', choices=[Choices(finish_reason='stop', index=0, message=Message(content=' Hello litellm! How can I assist you today?', role='assistant'))], created=496866, model='mistral-large', object='chat.completion', system_fingerprint=None, usage=Usage(completion_tokens=13, prompt_tokens=14, total_tokens=27))
```

**Comment by ishaan-jaff** [comment]
hmm does querying the endpoint not give you the same error ?

**Comment by ishaan-jaff** [comment]
<img width="912" alt="Screenshot 2024-02-29 at 8 19 34 AM" src="https://github.com/BerriAI/litellm/assets/29436595/26ec9348-70fe-4a87-ad53-8727bbc55ae8">


This is not LiteLLM - it's the endpoint @joch

**Comment by joch** [comment]
Thanks for looking into it! It didn't even cross my mind that the model would return data this way, but I should have confirmed before filing this. 🙂
