### ISSUE TITLE
[Feature]: Improve LiteLLM SpendLogs - Separate key level user vs user passed to request

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#2252]
### The Feature

- Separate key level user vs user passed to request
    - Passes user_id on request level user = “”
    - Separate user_id vs user_api_key_user_id
  ## Goal: User wants to see spend per user for a given key 

### Motivation, pitch

-

**Comment by ghost** [comment]
working on this - 
<img width="1708" alt="Screenshot 2024-02-29 at 2 26 28 PM" src="https://github.com/BerriAI/litellm/assets/17561003/d1dbc6d3-65ba-482f-b7ca-44c6af9dc12c">
