### ISSUE TITLE
[Feature]: UI - use anomaly detection to alert for unusual spend 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#2264]
### The Feature

Alert proxy admin on unusual spend (per project) using some sort of anomaly detection library 

### Motivation, pitch

User Request: 
It would be awesome if you could leverage a forecasting library, as well... check out this project for ideas: https://github.com/ankane/trend-api

### Twitter / LinkedIn details

cc: @dkindlund

**Comment by ishaan-jaff** [comment]
![Uploading litellm_predict_key_spend.gif…]()

done we do this now

**Comment by ishaan-jaff** [comment]
![litellm_predict_key_spend](https://github.com/BerriAI/litellm/assets/29436595/39732c22-1f3c-4c61-bc79-b05496e61afc)
