### ISSUE TITLE
wont allow open interpreter to open properly

### ISSUE THREAD

**Issue by Mr100MD** [BerriAI/litellm#2265]
starting open interpreter on my computer gives me an error message 

"Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'."

idk how to fix this. followed instructions and still doesnt work.

**Comment by ishaan-jaff** [comment]
please file this here: https://github.com/KillianLucas/open-interpreter

**Comment by Mr100MD** [comment]
but it says this:

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.
 

followed instructions and nothing changed.

also super new at this so its very much possible that im doing something wrong.
