### ISSUE TITLE
[Discussion]: batch_embedding

### ISSUE THREAD

**Issue by 7flash** [BerriAI/litellm#2266]
### The Feature

batch_embedding function

### Motivation, pitch

Currently there is a function implemented which allows to pass a list of messages to multiple models and get a list a of multiple answers in a single response. I would like to have similar function batch_embedding but it should accept a list of messages to generate embeddings for using single model. My usecase is an application where I am initializing a list of embeddings for in-memory semantic search loading it from redis cache.

**Comment by ghost** [comment]
you can already pass in a list of strings for embedding 

Did you see an error here?

**Comment by 7flash** [comment]
Thank you it works, my final code considering redis cloud free tier limitation of 30 connections:

```
		batch_size = 30
		unique_texts = []

        batches = [
            unique_texts[i : i + batch_size]
            for i in range(0, len(unique_texts), batch_size)
        ]

        embeddings: List[float] = []

        for batch in batches:
            embeddings.extend(
                it["embedding"]
                for it in (
                    await aembedding(
                        model=embedding_model, input=batch, caching=True
                    )
                )["data"]
            )
            logger.debug(f"...{len(embeddings)} embeddings")

        for i, text in enumerate(unique_texts):
                self.embeddings[text] = embeddings[i]
```
