### ISSUE TITLE
[Bug]: Router - Mistral Large on Azure AI studio returns Not Found

### ISSUE THREAD

**Issue by navidre** [BerriAI/litellm#2279]
### What happened?

The endpoint needs a /v1/ in the end according to this notebook: https://github.com/Azure/azureml-examples/blob/main/sdk/python/foundation-models/mistral/litellm.ipynb

I will update the docs so that others know too

### Twitter / LinkedIn details

@navid_re / https://www.linkedin.com/in/navidrezaei/

**Comment by navidre** [comment]
@ishaan-jaff 

I just did more testing, although in completion, the "/v1" suffix gets added, for some reason, it does not get added automatically in router mode. I am using version 1.28.6 by the way.

Router example that does not work and gives ```Not Found``` error, but when I add '/v1' manually, it works:
```
from litellm import Router

model_list = [
    {
        "model_name": "mistral-large",
        "litellm_params": {
            "model": "mistral/[MODEL_NAME]",
            "api_base": "https://[MODEL_NAME]-serverless.eastus2.inference.ai.azure.com",
            "api_key": "KEY",
        }
    }
]

router = Router(model_list)

response = router.completion(
                            model="mistral-large",
                            messages=[{"content": "Who is the most renowned French painter?", "role": "user"}],
                            )  
response_text = response['choices'][0]['message']['content']
print(response_text)
```

Similar code in completion mode works:
```
import litellm
client = litellm.LiteLLM(
    base_url="https://[MODEL_NAME]-serverless.eastus2.inference.ai.azure.com",
    api_key="KEY",
)

response = client.chat.completions.create(
    messages=[{"content": "Who is the most renowned French painter?", "role": "user"}],
    model="mistral/[MODEL_NAME]",
)
print(response)
```

Am I doing something wrong?

**Comment by ishaan-jaff** [comment]
Because the client gets initialized in the router.py - perhaps we need a check for the api_base if the `custom_llm_provider=="mistral"`

**Comment by ghost** [comment]
Fixed + testing added in - https://github.com/BerriAI/litellm/commit/e05764bdb7dda49127dd4b1c2c4d02fa90463e71

---

@navidre curious, do you want a litellm-hosted proxy for load balancing? 
- What would a good solution here look like for you?
