### ISSUE TITLE
Cross-provider guardrails

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#229]
**Describe the solution you'd like**
When you go cross-provider the response quality changes dramatically - are there libraries we can integrate with that implement guardrails? 

<img width="758" alt="Screenshot 2023-08-28 at 6 33 41 PM" src="https://github.com/BerriAI/litellm/assets/17561003/ad946177-a157-48f6-a2ee-d2a8d69a4dc8">

**Comment by ghost** [comment]
maybe integrate with https://github.com/ShreyaR/guardrails

**Comment by ghost** [comment]
Langchain has pretty good output parsing which seems designed for this situation - https://python.langchain.com/docs/modules/model_io/output_parsers/structured.

**Comment by ishaan-jaff** [comment]
you can use the proxy with guardrails for this
