### ISSUE TITLE
LLMMonitor Integration not working as expected

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#231]
What's the problem? (if there are multiple - list as bullet points)
@vincelwt I'm trying to use llm monitor but the integration doesn't seem to be working. I have it listed in my success + failure callbacks but i don't see it being logged on the llm monitor ui? 

Were you able to get this working? 

I'm also using our promptlayer integration and that seems to be working fine.

**Comment by vincelwt** [comment]
Hey @krrishdholakia! When I sent the PR it was working with my tests.
Let me check again
