### ISSUE TITLE
[Feature]: DAY 1 SUPPORT Add Claude -3 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#2314]
### The Feature

- 

### Motivation, pitch

New model

**Comment by ishaan-jaff** [comment]
We'll need to add the messages endpoint for claude3 - it fails on their completion endpoint 
```shell
Error calling model: AnthropicException - {"type":"error","error":{"type":"invalid_request_error","message":"\"claude-3-opus-20240229\" is not supported on this API. Please use the Messages API instead."}}
 
 ```

**Comment by ghost** [comment]
No bedrock support yet. 
<img width="814" alt="Screenshot 2024-03-04 at 6 48 09 AM" src="https://github.com/BerriAI/litellm/assets/17561003/d105f006-985e-49d6-92a0-e0150e74323c">

**Comment by ghost** [comment]
I don't think the legacy text completion endpoint supports claude 3. We should move to using the anthropic 2.1 endpoint - https://github.com/BerriAI/litellm/issues/1209

**Comment by ghost** [comment]
You can also send images in claude 3 - will need to add pricing for this 

<img width="634" alt="Screenshot 2024-03-04 at 6 49 45 AM" src="https://github.com/BerriAI/litellm/assets/17561003/a40ea966-2699-45ed-b402-bd721299242d">

**Comment by ghost** [comment]
support tool calling - https://github.com/anthropics/anthropic-cookbook/blob/main/function_calling/function_calling.ipynb

**Comment by ishaan-jaff** [comment]
Action Items:
 - Migrate to /messages + add claude-3 @ishaan-jaff 
 - Add tool calling / images @krrishdholakia

**Comment by ishaan-jaff** [comment]
PR to add initial support : https://github.com/BerriAI/litellm/pull/2315

**Comment by ishaan-jaff** [comment]
Model Pricing info here for reference https://docs.anthropic.com/claude/docs/models-overview#meet-claude-3

**Comment by ghost** [comment]
I'll take care of the image + tool calling cost tracking in my PR

**Comment by ghost** [comment]
<img width="560" alt="Screenshot 2024-03-04 at 7 39 44 AM" src="https://github.com/BerriAI/litellm/assets/17561003/231591e9-6bd1-44ca-b7d9-6e8daf27914d">

**Comment by ishaan-jaff** [comment]
## Notes about the /messages endpoint 
- Anthropic Deprecated support for `claude-instant-1` on the new messages endpoint 

1. Anthropic supports roles like "user" and "assistant",
2. The first message always needs to be of role "user"
3. Each message must alternate between "user" and "assistant"

> 3. Each message must alternate between "user" and "assistant"

For v0 PR not addressing no.3

**Comment by ashot** [comment]
Sorry if this is a silly question but does day 1 support mean you guy are hoping to get this done today?  Just wondering if I should attempt to hack something myself.  
This project is awesome btw.

**Comment by ishaan-jaff** [comment]
@ashot it will be live in 1-2 hours, PR for v0 support is here: https://github.com/BerriAI/litellm/pull/2315/files

**Comment by ashot** [comment]
love it, thank you!

**Comment by haseeb-heaven** [comment]
Wow great one waiting to test Claude-3 in my code interpreter.

**Comment by ishaan-jaff** [comment]
Working v0 PR is live here: https://github.com/BerriAI/litellm/commit/14fc8355fb1ce89a143ebb7b3171dfa19cb46d4e

**Comment by ghost** [comment]
@ishaan-jaff is this ready for me to stack the tool calling + image calling PRs on this?

**Comment by ishaan-jaff** [comment]
Yes @krrishdholakia

**Comment by ghost** [comment]
@ishaan-jaff looks like there's a separate param for system prompt 
<img width="714" alt="Screenshot 2024-03-04 at 9 54 08 AM" src="https://github.com/BerriAI/litellm/assets/17561003/65d3330c-a33d-4a92-9d97-48c261ad3962">

**Comment by ghost** [comment]
V1 needs to add: 
- [ ] support for system prompt
- [ ] Support for tool calling 
- [ ] Support for image calls

**Comment by ishaan-jaff** [comment]
confirmed 1.28.13 has v0 support working 
<img width="818" alt="Screenshot 2024-03-04 at 9 57 12 AM" src="https://github.com/BerriAI/litellm/assets/29436595/a19b2e49-35c8-4c6e-9308-b91be428e279">

**Comment by ishaan-jaff** [comment]
> @ishaan-jaff looks like there's a separate param for system prompt

oh missed this, will your v1 PR cover this @krrishdholakia ? else I can make the fix

**Comment by ghost** [comment]
yea i'm fixing it for tool calling

**Comment by ishaan-jaff** [comment]
FYI Anthropic deprecated the following models on `/messages `
- claude-2 (anthropic recommends using `claude-2.1`)
- claude-instant-1 (anthropic recommends using `claude-instant-1.2`)

Since we moved everything to /messages this means litellm will not support `claude-2` and `claude-instant-1`

**Comment by ghost** [comment]
That's funny - claude instant 1.2 works
<img width="982" alt="Screenshot 2024-03-04 at 10 14 50 AM" src="https://github.com/BerriAI/litellm/assets/17561003/a480b1bf-cd59-4c18-b5f9-05f2100b5895">

**Comment by ishaan-jaff** [comment]
Yup - Lets put a notice on the latest release about this and see if users want us to maintain - Claude-instant-1 and Claude-2

**Comment by ghost** [comment]
should we just have backwards compatibility for those 2 models? would be a bit weird to suddenly start failing calls

**Comment by ghost** [comment]
since we have the code, it's just routing no?

**Comment by ghost** [comment]
if claude-instant-1 or claude-2 route to `old_anthropic.py`
else route to `anthropic.py`

**Comment by ghost** [comment]
i always find it a bit stressful when together ai does this - and randomly kills access to models

**Comment by ishaan-jaff** [comment]
>  would be a bit weird to suddenly start failing calls

agree - bedrock did this to me and I didn't like it

**Comment by ishaan-jaff** [comment]
Action item 3: 
Maintain claude-instant-1 or claude-2 @ishaan-jaff

**Comment by ghost** [comment]
cool - let's just have a separate file called old anthropic - can you do this? @ishaan-jaff

**Comment by ghost** [comment]
thanks

**Comment by themrzmaster** [comment]
does it work with bedrock?

**Comment by ghost** [comment]
no - bedrock is not yet supported by anthropic 

![image](https://github.com/BerriAI/litellm/assets/17561003/668864a4-ea20-4e18-ab17-4ad788d143a8)

**Comment by ghost** [comment]
system prompt + tool calling support added - https://github.com/BerriAI/litellm/pull/2320

Now adding vision support

**Comment by themrzmaster** [comment]
what? it is
![image](https://github.com/BerriAI/litellm/assets/852747/1cc51678-b1f0-4a3c-9305-a86ee1f4d6ad)

**Comment by ishaan-jaff** [comment]
@themrzmaster can you share the code snippet to call claude 3 on the AWS console? We don't have access on our AWS account

**Comment by themrzmaster** [comment]
```
{
  "modelId": "anthropic.claude-3-sonnet-20240229-v1:0",
  "contentType": "application/json",
  "accept": "application/json",
  "body": {
    "anthropic_version": "bedrock-2023-05-31",
    "max_tokens": 1000,
    "messages": {
      "role": "user",
      "content": [
        {
          "type": "image",
          "source": {
            "type": "base64",
            "media_type": "image/jpeg",
            "data": "iVBORw..."
          }
        },
        {
          "type": "text",
          "text": "What's in this image?"
        }
      ]
    }
  }
}
```

**Comment by ghost** [comment]
You're right @themrzmaster seems like claude and bedrock have conflicting info 
<img width="1122" alt="Screenshot 2024-03-04 at 10 47 05 AM" src="https://github.com/BerriAI/litellm/assets/17561003/bc2eb741-78f0-46e1-a4d5-3428badaaba2">

**Comment by ghost** [comment]
Will work on adding bedrock support too  @themrzmaster 

might need some help testing it as i'm still waiting on access

can you help?

**Comment by themrzmaster** [comment]
@krrishdholakia yep! thanks

**Comment by ghost** [comment]
Let me finish up the anthropic integration, and i'll cc you on the bedrock pr.

cc: @dleen if you want to test out the bedrock/claude 3 integration as well

**Comment by ghost** [comment]
Got access to claude 3 - i should be able to test this on my end too 
<img width="942" alt="Screenshot 2024-03-04 at 10 51 27 AM" src="https://github.com/BerriAI/litellm/assets/17561003/1ef13774-e21c-4e9b-bfe4-8f398ce99dc6">

**Comment by ishaan-jaff** [comment]
🎢

**Comment by ishaan-jaff** [comment]
PR to maintain support for claude-instant-1 and claude-2 is here: https://github.com/BerriAI/litellm/pull/2321

**Comment by haseeb-heaven** [comment]
Are you trying to add all these Claude-3 Models **Opus** and **Sonnet**

**Comment by xihajun** [comment]
@krrishdholakia may I kindly ask how can we install the draft version and have a test? When I do `poetry install` on that repo, it doesn't help

**Comment by ishaan-jaff** [comment]
It's on here @xihajun https://github.com/BerriAI/litellm/releases/tag/v1.28.13

**Comment by xihajun** [comment]
@ishaan-jaff thanks!

There seemed to be a bug with system prompt enabled + multiple conversations


`[{"role":"system","content":"test"},{"role":"user","content":"test"},{"role":"assistant","content":"te
st"},{"role":"user","content":"test"}]`
```
completion(model="claude-3-opus-20240229", messages=[{"role":"system","content":"test"}, {"role":"user","content":"test"},{"role":"assistant","content":"test"}],stream=True)
```

```
Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

*** litellm.exceptions.BadRequestError: AnthropicException - {"type":"error","error":{"type":"invalid_request_error","message":"messages: roles must alternate between \"user\" and \"assistant\", but found multiple \"assistant\" roles in a row"}}
```

It looks like it has some bugs, `['system', 'user', 'assistant', 'user', 'assistant', 'user']` my role is doing `alternate between \"user\" and \"assistant\"`? Any idea why is that?

**Comment by haseeb-heaven** [comment]
i got this error while testing this API.

Python code:
```python
import os
from litellm import completion
from dotenv import load_dotenv

# load.env file
def init_env():
    load_dotenv()
    
    api_key = os.getenv("ANTHROPIC_API_KEY")
    
    # set env - [OPTIONAL] replace with your anthropic key
    os.environ["ANTHROPIC_API_KEY"] = api_key
    
if __name__ == "__main__":
    init_env()
    try:
        model = "claude-3-sonnet-20240229"
        messages = [{"role": "user", "content": "Hey! how's it going?"}]
        response = completion(model=model, messages=messages)
        print(response)
    except Exception as exception:
        import traceback as tb
        print(tb.format_exc())
        print(exception)


```

```
python claude_demo.py
/opt/homebrew/Caskroom/miniforge/base/envs/heaven-env/lib/python3.11/site-packages/pydantic/_internal/_fields.py:149: UserWarning: Field "model_max_budget" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/heaven-env/lib/python3.11/site-packages/litellm/main.py", line 1028, in completion
    response = anthropic.completion(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/heaven-env/lib/python3.11/site-packages/litellm/llms/anthropic.py", line 170, in completion
    raise AnthropicError(
litellm.llms.anthropic.AnthropicError: {"type":"error","error":{"type":"invalid_request_error","message":"\"claude-3-sonnet-20240229\" is not supported on this API. Please use the Messages API instead."}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/haseeb-mir/Documents/Code/Python/code-interpreter/claude_demo.py", line 19, in <module>
    response = completion(model=model, messages=messages)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/heaven-env/lib/python3.11/site-packages/litellm/utils.py", line 2621, in wrapper
    raise e
  File "/opt/homebrew/Caskroom/miniforge/base/envs/heaven-env/lib/python3.11/site-packages/litellm/utils.py", line 2524, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/heaven-env/lib/python3.11/site-packages/litellm/main.py", line 1908, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/heaven-env/lib/python3.11/site-packages/litellm/utils.py", line 7766, in exception_type
    raise e
  File "/opt/homebrew/Caskroom/miniforge/base/envs/heaven-env/lib/python3.11/site-packages/litellm/utils.py", line 6699, in exception_type
    raise BadRequestError(
litellm.exceptions.BadRequestError: AnthropicException - {"type":"error","error":{"type":"invalid_request_error","message":"\"claude-3-sonnet-20240229\" is not supported on this API. Please use the Messages API instead."}}

AnthropicException - {"type":"error","error":{"type":"invalid_request_error","message":"\"claude-3-sonnet-20240229\" is not supported on this API. Please use the Messages API instead."}}
```

**Comment by haseeb-heaven** [comment]
Python code.

```python
import os
from litellm import completion
from dotenv import load_dotenv

# load.env file
def init_env():
    load_dotenv()
    
    api_key = os.getenv("ANTHROPIC_API_KEY")
    if not api_key:
        raise Exception("Missing ANTHROPIC_API_KEY in.env file")
    
if __name__ == "__main__":
    init_env()
    try:
        model="claude-3-sonnet-20240229",
        prompt = "Write code to find prime number in given range."
        
        messages=[
            {
                "role": "user",
                "content": [
                    {
                        "type": "text",
                        "text": prompt
                    }
                ]
            }
        ]
        
        response = completion(model=model, messages=messages)
        print(response)
    except Exception as exception:
        print(f"Exception occured: {exception}")
        import traceback
        print(traceback.format_exc())

```

Now i tested and got more error from LiteLLM now.

```shell
(heaven-env)% python claude_demo.py
/opt/homebrew/Caskroom/miniforge/base/envs/heaven-env/lib/python3.11/site-packages/pydantic/_internal/_fields.py:149: UserWarning: Field "model_max_budget" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Exception occured: GetLLMProvider Exception - 'tuple' object has no attribute 'split'

original model: ('claude-3-sonnet-20240229',)
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/heaven-env/lib/python3.11/site-packages/litellm/utils.py", line 4981, in get_llm_provider
    model.split("/", 1)[0] in litellm.provider_list
    ^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'split'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/heaven-env/lib/python3.11/site-packages/litellm/main.py", line 601, in completion
    model, custom_llm_provider, dynamic_api_key, api_base = get_llm_provider(
                                                            ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/heaven-env/lib/python3.11/site-packages/litellm/utils.py", line 5148, in get_llm_provider
    raise litellm.exceptions.BadRequestError(  # type: ignore
litellm.exceptions.BadRequestError: GetLLMProvider Exception - 'tuple' object has no attribute 'split'

original model: ('claude-3-sonnet-20240229',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/haseeb-mir/Documents/Code/Python/code-interpreter/claude_demo.py", line 31, in <module>
    response = completion(model=model, messages=messages)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/heaven-env/lib/python3.11/site-packages/litellm/utils.py", line 2621, in wrapper
    raise e
  File "/opt/homebrew/Caskroom/miniforge/base/envs/heaven-env/lib/python3.11/site-packages/litellm/utils.py", line 2524, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/heaven-env/lib/python3.11/site-packages/litellm/main.py", line 1908, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/heaven-env/lib/python3.11/site-packages/litellm/utils.py", line 7767, in exception_type
    raise e
  File "/opt/homebrew/Caskroom/miniforge/base/envs/heaven-env/lib/python3.11/site-packages/litellm/utils.py", line 7735, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: GetLLMProvider Exception - 'tuple' object has no attribute 'split'

original model: ('claude-3-sonnet-20240229',)

```

**Comment by xihajun** [comment]
@haseeb-heaven have you pip installed the latest version

**Comment by haseeb-heaven** [comment]
> @haseeb-heaven have you pip installed the latest version

Yes.
LiteLLM: Current Version = 1.28.13

**Comment by haseeb-heaven** [comment]
Code now working fine .

```python
import os
from litellm import completion
from dotenv import load_dotenv
import litellm

# load.env file
def init_env():
    load_dotenv()
    
    api_key = os.getenv("ANTHROPIC_API_KEY")
    if not api_key:
        raise Exception("Missing ANTHROPIC_API_KEY in.env file")
    
if __name__ == "__main__":
    init_env()
    litellm.set_verbose=True
    try:
        model="claude-3-sonnet-20240229"
        prompt = "Write code to find prime number in given range."
        
        messages=[
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "text",
                            "text": prompt
                        }
                    ]
                }
            ]
        
        response = completion(model=model, messages=messages)
        print(response)
    except Exception as exception:
        print(f"Exception occured: {exception}")

```

**Comment by xihajun** [comment]
If you try with system, and add a few messages it might fail?

**Comment by ghost** [comment]
@xihajun system prompt support + tool calling + image calling just pushed - https://github.com/BerriAI/litellm/pull/2320

Should be out in the next release by EOD

**Comment by CXwudi** [comment]
You guys are just awesome, can't believe a model support with vision and function calling, plus different provider (AWS) are all done in 12 hours

**Comment by SamArgillander** [comment]
Does this already work on the proxy side, or is it just me that gets stuck?

**Comment by ghost** [comment]
@SamArgillander Bedrock just got merged, should be out soon. Anthropic API is already live in https://github.com/BerriAI/litellm/releases/tag/v1.29.1

What's the error?

**Comment by adamrb** [comment]
Also getting errors on Bedrock.  It seems LiteLLM needs to be updated to call the new [messages API](https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-anthropic-claude-messages.html).

> botocore.exceptions.EventStreamError: An error occurred (validationException) when calling the InvokeModelWithResponseStream operation: "claude-3-sonnet-20240229" is not supported on this API. Please use the Messages API instead.

**Comment by haseeb-heaven** [comment]
> Also getting errors on Bedrock. It seems LiteLLM needs to be updated to call the new [messages API](https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-anthropic-claude-messages.html).
> 
> > botocore.exceptions.EventStreamError: An error occurred (validationException) when calling the InvokeModelWithResponseStream operation: "claude-3-sonnet-20240229" is not supported on this API. Please use the Messages API instead.

Try this code format for Messages API.

```python
if __name__ == "__main__":
    try:
        model="claude-3-sonnet-20240229"
        prompt = "Write code to find prime number in given range."
        
        messages=[
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "text",
                            "text": prompt
                        }
                    ]
                }
            ]
        
        response = completion(model=model, messages=messages)
        print(response)
    except Exception as exception:
        print(f"Exception occured: {exception}")
```

**Comment by quan2005** [comment]
1. This code will throw an error when the function does not return its complete output.

![image](https://github.com/BerriAI/litellm/assets/4606750/21d06773-78ac-4f62-bb87-70a55835c512)

2. when the response include function call , the content will lose

**Comment by shaggy2626** [comment]
Not sure if this is the correct location to post on but when using with code interpreter and on the latest version of litellm I'm receiving messages 

{"type":"error","error":{"type":"invalid_request_error","message":"messages: all messages must have non-empty content except for
the optional final assistant message"}}  

interpreter works for the first response but once it executes the codes I'm getting the message about having blank messages being sent. 


```
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "C:\Users\abc40\AppData\Local\Programs\Python\Python312\Lib\site-packages\interpreter\core\core.py", line 148, in
_streaming_chat
    yield from self._respond_and_store()
  File "C:\Users\abc40\AppData\Local\Programs\Python\Python312\Lib\site-packages\interpreter\core\core.py", line 194, in
_respond_and_store
    for chunk in respond(self):
  File "C:\Users\abc40\AppData\Local\Programs\Python\Python312\Lib\site-packages\interpreter\core\respond.py", line 49, in respond
    for chunk in interpreter.llm.run(messages_for_llm):
  File "C:\Users\abc40\AppData\Local\Programs\Python\Python312\Lib\site-packages\interpreter\core\llm\llm.py", line 198, in run
    yield from run_text_llm(self, params)
  File "C:\Users\abc40\AppData\Local\Programs\Python\Python312\Lib\site-packages\interpreter\core\llm\run_text_llm.py", line 19, in
run_text_llm
    for chunk in llm.completions(**params):
  File "C:\Users\abc40\AppData\Local\Programs\Python\Python312\Lib\site-packages\interpreter\core\llm\llm.py", line 229, in
fixed_litellm_completions
    raise first_error
  File "C:\Users\abc40\AppData\Local\Programs\Python\Python312\Lib\site-packages\interpreter\core\llm\llm.py", line 210, in
fixed_litellm_completions
    yield from litellm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abc40\AppData\Local\Programs\Python\Python312\Lib\site-packages\litellm\utils.py", line 2647, in wrapper
    raise e
  File "C:\Users\abc40\AppData\Local\Programs\Python\Python312\Lib\site-packages\litellm\utils.py", line 2550, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abc40\AppData\Local\Programs\Python\Python312\Lib\site-packages\litellm\main.py", line 1936, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "C:\Users\abc40\AppData\Local\Programs\Python\Python312\Lib\site-packages\litellm\utils.py", line 7839, in exception_type
    raise e
  File "C:\Users\abc40\AppData\Local\Programs\Python\Python312\Lib\site-packages\litellm\utils.py", line 6772, in exception_type
    raise BadRequestError(
litellm.exceptions.BadRequestError: AnthropicException -
{"type":"error","error":{"type":"invalid_request_error","message":"messages: all messages must have non-empty content except for
the optional final assistant message"}}


  from datetime import datetime

  current_time = datetime.now()
  print(f"The current time is: {current_time.strftime('%I:%M %p')}")


  The current time is: 03:13 AM

[IPKernelApp] WARNING | Parent appears to have exited, shutting down.
PS C:\Users\abc40>
```

**Comment by themrzmaster** [comment]
I am having a lot of issues as well.

`Erro: BedrockException - An error occurred (ValidationException) when calling the InvokeModel operation: messages.3.tool_calls: Extra inputs are not permitted`

the tool_calls from openai api does not work here

**Comment by themrzmaster** [comment]
I guess it should be handled using the _function_results_  tag, as shown on the notebook https://github.com/anthropics/anthropic-cookbook/blob/main/function_calling/function_calling.ipynb:

```
def construct_successful_function_run_injection_prompt(invoke_results):
    constructed_prompt = (
        "<function_results>\n"
        + '\n'.join(
            f"<result>\n<tool_name>{res['tool_name']}</tool_name>\n<stdout>\n{res['tool_result']}\n</stdout>\n</result>" 
            for res in invoke_results
        ) + "\n</function_results>"
    )
    
    return constructed_prompt

formatted_results = [{
    'tool_name': 'do_pairwise_arithmetic',
    'tool_result': result
}]
function_results = construct_successful_function_run_injection_prompt(formatted_results)
print(function_results)
```

**Comment by ghost** [comment]
@themrzmaster can you confirm which version of litellm your on? This works for me on the latest one: 

```python

def test_bedrock_claude_3_tool_calling():
    try:
        litellm.set_verbose = True
        tools = [
            {
                "type": "function",
                "function": {
                    "name": "get_current_weather",
                    "description": "Get the current weather in a given location",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "location": {
                                "type": "string",
                                "description": "The city and state, e.g. San Francisco, CA",
                            },
                            "unit": {
                                "type": "string",
                                "enum": ["celsius", "fahrenheit"],
                            },
                        },
                        "required": ["location"],
                    },
                },
            }
        ]
        messages = [
            {"role": "user", "content": "What's the weather like in Boston today?"}
        ]
        response: ModelResponse = completion(
            model="bedrock/anthropic.claude-3-sonnet-20240229-v1:0",
            messages=messages,
            tools=tools,
            tool_choice="auto",
        )
        print(f"response: {response}")
        # Add any assertions here to check the response
        assert isinstance(response.choices[0].message.tool_calls[0].function.name, str)
        assert isinstance(
            response.choices[0].message.tool_calls[0].function.arguments, str
        )
    except RateLimitError:
        pass
    except Exception as e:
        pytest.fail(f"Error occurred: {e}")
```

**Comment by ghost** [comment]
hey @themrzmaster @quan2005 @shaggy2626 

noting the issues:
1. I'll move to checking if `function_results` is in the response. 
2. Claude can include the content as part of the function call response - e.g. `"Seems like the weather in boston is <function_call> .. </function_call> might be worth bringing a jacket"` -> how should this be parsed into content? Would you just want the content to include the exact message from claude and the function call to have the extracted values?

**Comment by adamrb** [comment]
I primarily use LiteLLM as a Proxy for LibreChat.  I'm now getting responses from Bedrock for Claude 3, but it seems there's an error with the proxy.


> RAW RESPONSE:
> {"id": "xxxxxxxxxxx", "type": "message", "role": "assistant", "content": [{"type": "text", "text": "Hello! How can I assist you today?"}], "model": "claude-3-sonnet-28k-20240229", "stop_reason": "end_turn", "stop_sequence": null, "usage": {"input_tokens": 275, "output_tokens": 12}}
> 
> raw model_response: {'ResponseMetadata': {'RequestId': 'xxxxxxxxxxxx', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Wed, 06 Mar 2024 17:53:50 GMT', 'content-type': 'application/json', 'content-length': '278', 'connection': 'keep-alive', 'x-amzn-requestid': 'xxxxxxxxxxx', 'x-amzn-bedrock-invocation-latency': '5050', 'x-amzn-bedrock-output-token-count': '12', 'x-amzn-bedrock-input-token-count': '275'}, 'RetryAttempts': 0}, 'contentType': 'application/json', 'body': <botocore.response.StreamingBody object at 0xffff915ff1f0>}
> model_response._hidden_params: {'custom_llm_provider': 'bedrock', 'region_name': 'us-west-2'}
> INFO:     18.246.250.106:0 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> Traceback (most recent call last):
>   File "/home/ec2-user/.local/lib/python3.9/site-packages/litellm/proxy/proxy_server.py", line 2231, in async_data_generator
>     async for chunk in response:
> TypeError: 'async for' requires an object with __aiter__ method, got ModelResponse

**Comment by ghost** [comment]
@ashot working on adding streaming bedrock claude 3 support today - https://github.com/BerriAI/litellm/issues/2362. Will update you once it's out.

**Comment by pchalasani** [comment]
> adding streaming bedrock

Not sure if this is known (I haven't read the full thread above), but  streaming is not working with claude-3, even outside of bedrock. I get an error saying `unable to parse response` when using these kwargs in the completion call:

<img width="1082" alt="image" src="https://github.com/BerriAI/litellm/assets/554347/e87ee6fd-d6fc-4c91-9fa9-4d2d7da9d04e">

this is the error

<img width="740" alt="image" src="https://github.com/BerriAI/litellm/assets/554347/78978ffc-ce4e-45bb-80e5-0546f069018f">

**Comment by pchalasani** [comment]
> streaming is not working with claude-3,

Please ignore, it seems fine now. Might have been an Anthropic API issue.

**Comment by shaggy2626** [comment]
> hey @themrzmaster @quan2005 @shaggy2626
> 
> noting the issues:
> 
>     1. I'll move to checking if `function_results` is in the response.
> 
>     2. Claude can include the content as part of the function call response - e.g. `"Seems like the weather in boston is <function_call> .. </function_call> might be worth bringing a jacket"` -> how should this be parsed into content? Would you just want the content to include the exact message from claude and the function call to have the extracted values?

im not sure how to answer that as im only using it in Open Interpreter. i included the output from terminal for your review. My prompt was "what time is it". I also did see something about my api key being invalid however the key is valid and i confirmed by looking at the usage in the Claude portal. 
[claudeissuePowerShell.txt](https://github.com/BerriAI/litellm/files/14535153/claudeissuePowerShell.txt)

**Comment by ghost** [comment]
closing as the work for this ticket is complete 

https://docs.litellm.ai/docs/providers/anthropic

https://docs.litellm.ai/docs/providers/bedrock
