### ISSUE TITLE
Enhance docs about fallback completion

### ISSUE THREAD

**Issue by yujonglee** [BerriAI/litellm#232]
**Describe the solution you'd like**
I think https://docs.litellm.ai/docs/tutorials/fallbacks needs some details.

> LLM APIs can be unstable, completion() with fallbacks ensures you'll always get a response from your calls

How?  For example, it will be better if some numbers like 45 or `time.time() + 60` is documented.

https://github.com/BerriAI/litellm/blob/8f37caef6d289d59147a851cb092d89f15c8faac/litellm/utils.py#L1725

**Comment by ishaan-jaff** [comment]
sounds good - any controls you're looking for us to expose in the fallbacks function?

**Comment by ishaan-jaff** [comment]
@yujonglee more details added here:
https://docs.litellm.ai/docs/completion/reliable_completions#completion-with-fallbacks

and here:
https://docs.litellm.ai/docs/tutorials/fallbacks

lmk if there's anything else we should add to docs
