### ISSUE TITLE
Adding new model through config

### ISSUE THREAD

**Issue by nlpravi** [BerriAI/litellm#2322]
I'm trying to add a new model through config.  Here is my yaml file. 

model_list:
  model_name: "azure-gpt-3.5-turbo"
  litellm-params:
    model: "azure/xxxxxx"
    api_base: "https://xxxxxx.openai.azure.com/"
    api_key: "xxxxxx"
    api_version: "2023-12-01-preview"

I get the error below when I run litellm --config yaml_file 

  File "opt/anaconda3/envs/oldopenai/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "opt/anaconda3/envs/oldopenai/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/oldopenai/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/oldopenai/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 1802, in load_config
    for k, v in model["litellm_params"].items():
                ~~~~~^^^^^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'

**Comment by nlpravi** [comment]
Never mind, It was a typo in the config file. Thank you.

**Comment by ishaan-jaff** [comment]
@nlpravi can we hop on a call sometime this week? I'd love to learn how we can improve for litellm for you 

Sharing a link to my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/berriai-1-1-onboarding-litellm-hosted-version?month=2023-10

**Comment by arty-hlr** [comment]
@nlpravi Gotta love those issues with "nvm fixed it" that don't mention what the issue was 😆 What was the typo in your config file?
