### ISSUE TITLE
Move litellm_uuid.txt to a better location

### ISSUE THREAD

**Issue by tht99** [BerriAI/litellm#233]
What's the problem? (if there are multiple - list as bullet points)
Based on [this function](https://github.com/BerriAI/litellm/blob/main/litellm/utils.py#L1478), an uuid file is created on the first request.

This will result in an error for a read-only file system. We can temporary solve it by setting `litellm.telemetry = False`, but it would be best to move the file to a public folder like `/tmp`.

**Comment by ishaan-jaff** [comment]
cc @krrishdholakia I believe you worked on this

**Comment by ishaan-jaff** [comment]
im looking into this, it's seems invasive to write a tmp/ dir in the users system cc @tht99 @krrishdholakia what do u think ? 

imo we should try something like this 
if if fails creating a new litellm_uuid.txt file we can then try creating a tmp/litellm_uuid.txt file ?

**Comment by ghost** [comment]
tmp dir makes sense - why do you feel like that's invasive @ishaan-jaff? 

tmp dir is a known location for storing temporary data - e.g. a litellm uuid 
<img width="868" alt="Screenshot 2023-08-29 at 10 24 41 AM" src="https://github.com/BerriAI/litellm/assets/17561003/36e96a5e-a232-400a-ab94-646728104948">


I think chromadb adopts a similar approach - where they use a `chromadb` folder.

**Comment by ishaan-jaff** [comment]
ok sg ! was not aware of tmp dir

**Comment by ghost** [comment]
noob

**Comment by ishaan-jaff** [comment]
addressed in this commit: https://github.com/BerriAI/litellm/commit/bb766c34ca802cdcdc5b4f5767cfc01a01a3ec97 

verified it works locally

**Comment by ishaan-jaff** [comment]
looks good @tht99 @krrishdholakia ? 

feel free to re-open this if not
