### ISSUE TITLE
[Feature]: Add Redis keyspace specific to litellm

### ISSUE THREAD

**Issue by olad32** [BerriAI/litellm#2334]
### The Feature

It would be nice to have all Redis keys managed by Litellm to be prefixed with a specific keyspace like for example "litellm::"

### Motivation, pitch

Redis uses keyspace to differentiate data between different applications that uses the same Redis instance, with RBAC managment access (on recent redis version).

**Comment by ghost** [comment]
Hey @olad32 can you point me to relevant docs on this? Would be helpful to try and repro this on our end

**Comment by olad32** [comment]
sure, the keyspace doc is here : https://redis.io/docs/manual/keyspace/
this is relatively straightforward, you basically just need to add a prefix to all the keys, like "litellm::"

**Comment by ghost** [comment]
this is now live - https://docs.litellm.ai/docs/proxy/caching#optional-step-15-add-redis-namespaces


@olad32 can we please do a ~10 min call this week? Would really love to learn how you're using litellm 

I can make anytime that works for you. Attaching my calendly if that [helps](https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat)

**Comment by olad32** [comment]
thanks, just to be sure does it adds the prefix for tpm/rpm keys also ? as the param is in "cache_params"
i've made an appointment on your calendly.

**Comment by olad32** [comment]
Redis cache related keys are effectively prefixed, but Redis keys related to tpm/rpm are not

**Comment by ghost** [comment]
now supported on v`1.34.18`. same keyspace works
