### ISSUE TITLE
[Feature Request]: could Make a LiteLLM integration into llama_index 

### ISSUE THREAD

**Issue by solyarisoftware** [BerriAI/litellm#234]
I replicate / detailed the proposal here also: 
https://github.com/jerryjliu/llama_index/issues/7458

I see LiteLLM as a possible universal LLMs interface, serving others opensource projects already focused on "application-level" solutions.

Sorry for yet another issue opened.

**Comment by ishaan-jaff** [comment]
Hi @solyarisoftware ! nice to see you here. Thanks for making an issue !

**Comment by ishaan-jaff** [comment]
we have a langchain integration and I believe llama index allows you to use Langchain llms https://python.langchain.com/docs/integrations/chat/litellm

**Comment by ghost** [comment]
is any further action required on this ticket? @solyarisoftware @ishaan-jaff

**Comment by ishaan-jaff** [comment]
from looking at the linked llama index issue looks like they no longer use langchain llms but they're open to a LiteLLM integration

**Comment by ishaan-jaff** [comment]
this is a great first issue for someone in the community to tackle -let's leave this as open 

Action required:
- Make a LiteLLM integration into llama_index

**Comment by ishaan-jaff** [comment]
+1 heard this from another user

**Comment by solyarisoftware** [comment]
So, following the new @krrishdholakia announce on linkedin, Integration is done: https://gpt-index.readthedocs.io/en/latest/examples/llm/litellm.html

I guess we can close the point as "done"!
Thank you for your efforts

**Comment by solyarisoftware** [comment]
So, following the new @krrishdholakia announce on linkedin, Integration is done: https://gpt-index.readthedocs.io/en/latest/examples/llm/litellm.html

I guess we can close the point as "done"!

> BTW, just a suggestion: 
> I'd add a section on LiteLLM documentation / tutorial about LiteLLM integration on other higher level >application frameworks, as LangChain and Llamaindex:
>
 > just linkining the external references and maybe with a simple example as tutorial :
>
> - https://gpt-index.readthedocs.io/en/latest/examples/llm/litellm.html
>  - https://python.langchain.com/docs/integrations/chat/litellm


Thank you for your efforts

**Comment by ghost** [comment]
Yep!
