### ISSUE TITLE
[Bug]: Inconsistent default LiteLLM proxy port between Dockerfile (4000) and documentation (8000)

### ISSUE THREAD

**Issue by nqngo** [BerriAI/litellm#2366]
### What happened?

The default Uvicorn webapp for the LiteLLM proxy runs at port 8000, codified in:
https://docs.litellm.ai/docs/proxy/cli#--port
and
https://github.com/BerriAI/litellm/blob/688b903d195bd0c33d87617f2e899069c136993b/litellm/proxy/proxy_cli.py#L57

The Dockerfile; however, is exposing port 4000 and have the override CMD to start on port 4000.

This bug report is a follow up on:

https://github.com/BerriAI/litellm/pull/2349

As @ishaan-jaff indicates in the PR, it seems a fair amount of LiteLLM proxy in prod is running on port 4000. If that's the case, perhaps, we should move the default LiteLLM port to 4000 instead.

**Comment by ghost** [comment]
@nqngo where did you look on docs for this? i can add the relevant info

**Comment by nqngo** [comment]
> @nqngo where did you look on docs for this? i can add the relevant info

See the above 2 links. I don't think it's just the matter of adding relevant doc. If port 4000 is preferred as the default port, LiteLLM should set that in code as the default.

At the moment, the code says port 8000 is the default; but the Dockerfile says that port 4000 is the default. LiteLLM should pick one port and ensure we are consistent.

**Comment by ishaan-jaff** [comment]
PR here: https://github.com/BerriAI/litellm/pull/2416

**Comment by ishaan-jaff** [comment]
@nqngo can we hop on a call this week to learn how you use litellm proxy. I'd love to learn how we can improve for you 
sharing my cal here for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by nqngo** [comment]
Thanks for the quick fix @ishaan-jaff. With the default port at 4000, you can probably remove the port override in Dockerfile CMD as well. Will definitely reach out once I play around with LiteLLM a bit more.
