### ISSUE TITLE
LiteDebugger broken - does not show errors / tracebacks 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#237]
What's the problem? (if there are multiple - list as bullet points)
<img width="1524" alt="Screenshot 2023-08-29 at 11 31 08 AM" src="https://github.com/BerriAI/litellm/assets/17561003/9af960f1-7aca-466d-b8dc-bd3aa2e5d7a0">

post-call logging is not working as expected, initial calls are getting logged but if they fail, et. those calls are not being logged.

**Comment by ishaan-jaff** [comment]
<img width="1212" alt="Screenshot 2023-08-29 at 12 07 54 PM" src="https://github.com/BerriAI/litellm/assets/29436595/d3c76de5-dcfa-475f-a816-e63743b00971">
 it's not showing me the logs on success either

**Comment by ishaan-jaff** [comment]
works for me now ! seems like it was temporary
