### ISSUE TITLE
[Bug]: Spend is not tracked in proxy if general_settings is empty or None

### ISSUE THREAD

**Issue by parktheredcar** [BerriAI/litellm#2376]
### What happened?

The cost_tracking() setup function doesn't run if general_settings doesn't have at least one key ( {} evaluates to False)
https://github.com/BerriAI/litellm/blob/32adb4e80d0980075121987fe47141b5417800d0/litellm/proxy/proxy_server.py#L1713

This check makes sense for everything else in that block, but cost_tracking() doesn't depend on general_settings, for example if the database_url is in the env instead of config.

**Comment by parktheredcar** [comment]
I think the check makes sense for everything else, but cost_tracking is not dependent on general_settings and should probably be moved.

**Comment by ishaan-jaff** [comment]
Hi @parktheredcar happy to debug this live with you now: https://meet.google.com/pxg-mycb-fiu + understand your use case better

**Comment by ishaan-jaff** [comment]
Following up on this @parktheredcar 
- If you're not tracking cost per Key, what do you need to track costs for
- I'd love to learn how we can improve for your use case + this issue over a call if you have some time this week: 

Sharing a link to my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat?month=2024-03

**Comment by parktheredcar** [comment]
Hi Ishaan,

To clarify, if the `general_settings` object in config is not defined and populated with at least one **property**, cost_tracking() will not run and this bug seems to occur, `key` above was a poor choice in wording on my part, as this is not related to api keys.

creating a mock `general_settings` object with a fake property will resolve it:
```
...config.yml...
general_settings:
  placeholder: 0
```

**Comment by ghost** [comment]
gotcha - since `cost_tracking()` already does a prisma db check before adding the logger, we can just run it on startup, after loading the config (covers the scenario where the db url is in the config) 

Do you mind sharing what your config looks like so i can make sure it works for that? @parktheredcar

**Comment by ghost** [comment]
Created a PR - https://github.com/BerriAI/litellm/pull/2382 to fix this. Let me know if this is what you were looking for @parktheredcar 

P.S.:  If you have ~10 mins happy to hop on a call to debug + learn how you're using litellm - https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat?month=2024-03

**Comment by ghost** [comment]
should be live in the next release - v`1.31.5`+

**Comment by ishaan-jaff** [comment]
following up on this, @parktheredcar if you have time this week for a quick call - we'd love to get your feedback on litellm / learn how we can improve 

link to my cal for your convenience 

https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat?month=2024-03
