### ISSUE TITLE
[LiteDebugger] split the litedebugger from the key manager

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#239]
**Describe the solution you'd like**
I'm currently testing my model keys - seeing what happens if i set the keys incorrectly. For this I need to turn off the key manager (since i need to manually set and switch keys). This also means i lose the debugger. It's currently broken so not the worse issue - but it just feels weird that I can't individually control those. 

However, i would call out - when I'm adding / testing models for playground it's perfect (as i'm not in code at that time).

**Comment by ishaan-jaff** [comment]
I felt similarly ? thoughts on separating the UI pages? 

I was annoyed that the key component took 1/2 the page for the debugger
