### ISSUE TITLE
[Bugs]: Invalid model name passed in

### ISSUE THREAD

**Issue by wac81** [BerriAI/litellm#2398]
### What happened?

Traceback (most recent call last):
  File "/data/miniconda3/envs/py311/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 2397, in chat_completion
    raise HTTPException(
fastapi.exceptions.HTTPException: 400: {'error': 'Invalid model name passed in'}

yaml config:

model_list:
- model_name: "gpt-3.5-turbo"
  litellm_params:
    model: openai/openchat-gpu01
    api_key: noneed
    api_base: http://192.168.1.14:8001/v1

### Relevant log output

```shell
yaml config:

model_list:
- model_name: "gpt-3.5-turbo"
  litellm_params:
    model: openai/openchat-gpu01
    api_key: noneed
    api_base: http://192.168.1.14:8001/v1
```

**Comment by ishaan-jaff** [comment]
@wac81 how do you send a request to the proxy?

**Comment by wac81** [comment]
curl --location 'http://0.0.0.0:8000/v1/chat/completions' --header 'Content-Type: application/json' --data ' {
      "model": "gpt-3.5-turbo",
      "messages": [
        {
          "role": "user",
          "content": "what llm are you"
        }
      ],
    }
'

**Comment by wac81** [comment]
maybe i find out reason, you have to solve as soon as possible

i find llitellm request is wrong endpoint
[GIN] 2024/03/09 - 11:27:38 | 404 |       4.233µs |       127.0.0.1 | POST     "/v1/api/generate"
[GIN] 2024/03/09 - 11:27:41 | 404 |       1.729µs |       127.0.0.1 | POST     "/v1/api/generate"
[GIN] 2024/03/09 - 11:27:43 | 404 |        1.63µs |       127.0.0.1 | POST     "/v1/api/generate

**Comment by wac81** [comment]
i repull ollama and litellm ,it 's  solved now
