### ISSUE TITLE
pypi package Not working for replicate 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#24]
<img width="1258" alt="Screenshot 2023-07-31 at 9 46 10 PM" src="https://github.com/BerriAI/litellm/assets/17561003/d8012df6-25c3-4454-acab-ddece6f51afe">

**Comment by ghost** [comment]
the latest in colab is not the latest in pypi 
<img width="878" alt="Screenshot 2023-07-31 at 9 48 19 PM" src="https://github.com/BerriAI/litellm/assets/17561003/b8a58830-d68e-44ed-8afe-e8149413c88c">

<img width="594" alt="Screenshot 2023-07-31 at 9 48 49 PM" src="https://github.com/BerriAI/litellm/assets/17561003/48a263fd-5211-4292-8627-f367f5323aa6">

**Comment by ghost** [comment]
Looks like an issue with func set timeout. 

<img width="1209" alt="Screenshot 2023-07-31 at 9 51 47 PM" src="https://github.com/BerriAI/litellm/assets/17561003/cedcc10e-90d4-4c39-92cd-129702fce9b8">
