### ISSUE TITLE
[Feature]: helm chart on oci registry (or anywhere else)

### ISSUE THREAD

**Issue by debdutdeb** [BerriAI/litellm#2421]
### The Feature

Making helm chart available on docker hub, or some other public registry.

### Motivation, pitch

Being able to use the chart as a dependency for some other charts.

I can make a PR for either a "helm repo" based on github pages or an oci push where you'd have to add credentials to the repo later. 

### Twitter / LinkedIn details

https://www.linkedin.com/in/debdut-chakraborty/

**Comment by ishaan-jaff** [comment]
Okay litellm-helm gets released here now: https://github.com/BerriAI/litellm/pkgs/container/litellm-helm 

@tylerbrandt @debdutdeb 

FYI - we had to rename the chart to `litellm-helm` since the litellm docker image is called `litellm` on ghcr

**Comment by ishaan-jaff** [comment]
Can you let me know if this works for you? Would appreciate help with testing this

**Comment by ishaan-jaff** [comment]
docs on using the OCI hosted litellm helm chart https://docs.litellm.ai/docs/proxy/deploy#docker-kubernetes-helm-chart @debdutdeb . let me know if this is what you needed
