### ISSUE TITLE
[Bug]: Claude tool calls with streamed response

### ISSUE THREAD

**Issue by jackmpcollins** [BerriAI/litellm#2435]
### What happened?

The [function calling example in the docs for `anthropic/claude-3-opus`](https://litellm.vercel.app/docs/providers/anthropic#usage---function-calling) does not work when `stream=True` is passed as an argument. It returns a streamed response with the `content` field filled out in each chunk instead of the `tool_calls` field.

**Comment by quan2005** [comment]
![image](https://github.com/BerriAI/litellm/assets/4606750/74e2daa9-c6ae-4ca9-be16-56c9a648185b)

The function call message was successfully transmitted to claude3 and was correctly identified and returned. But Litellm doesn't handle the function call that translates to OAI correctly

**Comment by quan2005** [comment]
"stop_sequences": ["</function_calls>"],

I think the stop parameter needs to be added with function_calls to solve its illusion.

**Comment by ghost** [comment]
Picking this up today - thanks for flagging this @jackmpcollins

**Comment by quan2005** [comment]
> litellm-1.31.6

Claude on AWS Bedrock still not work (⊙︿⊙)

**Comment by jackmpcollins** [comment]
Seems to be fixed since https://github.com/BerriAI/litellm/releases/tag/v1.31.6  Thanks!
