### ISSUE TITLE
GROQ via litellm CLI

### ISSUE THREAD

**Issue by mariusgarmhausen** [BerriAI/litellm#2436]
Hi,

I was trying to setup litellm for the use of groq via the CLI.

I tried both exporting (export GROQ_API_KEY="") and passing in the API key (--add_key XXX) and then calling

`litellm --api_base "https://api.groq.com/openai/v1" --model "groq/mixtral-8x7b-32768"`

However, this results for me in continued: 
`INFO:     127.0.0.1:55058 - "GET /ws/socket.io/?EIO=4&transport=polling&t=OugOIsQ HTTP/1.1" 404 Not Found`

messages. 

Any idea what I am doing wrong?

**Comment by ishaan-jaff** [comment]
Hi @mariusgarmhausen can you try

`litellm --model "groq/mixtral-8x7b-32768" --detailed_debug` 

Once started try sending a /chat/completions request and can you send the server logs here ?

**Comment by mariusgarmhausen** [comment]
Thanks Ishaan.  Using your instructions I could pinpoint the problem. I had to reinstall litellm[proxy], which I tried yesterday like 5 times, but I was probably in a different conda environment before. Nevertheless, I works now. Woohoo.

Thank you very much!

**Comment by mariusgarmhausen** [comment]
Done

**Comment by ishaan-jaff** [comment]
great ! @mariusgarmhausen can we hop on a call this week to learn how you're using the proxy and how we can improve for you ?

my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/berriai-1-1-onboarding-litellm-hosted-version?month=2023-10

**Comment by ishaan-jaff** [comment]
Hi @mariusgarmhausen wanted to follow up on this. Any chance we can hop on a call sometime this week. I'd love to learn how we can improve litellm proxy for you
