### ISSUE TITLE
[Feature]: Support mistralai's JSON mode

### ISSUE THREAD

**Issue by EliottZemour** [BerriAI/litellm#2442]
### The Feature

Mistral API now supports [json mode](https://docs.mistral.ai/platform/client/#json-mode), with the usual `response_format` syntax. This is not supported to date in `litellm==1.30.7`.

```
APIError: MistralException - mistral does not support parameters: {'response_format': {'type': 'json_object'}}. To drop these, set `litellm.drop_params=True`.
```

### Motivation, pitch

The json mode for mistral is similar to other providers. This is from their docs:

```python
chat_response = client.chat(
    model=model,
    response_format={"type": "json_object"},
    messages=messages,
)
```

**Comment by ghost** [comment]
fix pushed - https://github.com/BerriAI/litellm/commit/312a9d8c26388b01e21d5025cf6323aa0f293732

should be live in v`1.31.1` @EliottZemour 

Can you do a ~10 min chat this week? @EliottZemour - want to learn how your using litellm 
https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
