### ISSUE TITLE
[Feature]: Retry Policy Backoff for Vertex AI

### ISSUE THREAD

**Issue by H0llyW00dzZ** [BerriAI/litellm#2445]
### The Feature

When an internal server error is encountered, it's worth implementing a mechanism to retry at least 3 times.

### Motivation, pitch

Implementing a retry policy with backoff for Vertex AI can help mitigate these interruptions. By automatically retrying the operation after a brief pause, we can ensure that these temporary issues do not halt the entire process. This feature would significantly enhance the robustness of the system, making it more resilient to temporary server-side issues.

### Twitter / LinkedIn details

https://twitter.com/H0llyW00dzZ

**Comment by ghost** [comment]
hey @H0llyW00dzZ if you set `num_retries` this should already be the case

**Comment by H0llyW00dzZ** [comment]
> hey @H0llyW00dzZ if you set `num_retries` this should already be the case

oh I don't know
