### ISSUE TITLE
[Bug]: DynamoDB proxy setup

### ISSUE THREAD

**Issue by krewi1** [BerriAI/litellm#2457]
### What happened?

Hello,
i have tested setting project with DynamoDB on my environment and i couldn't make it run. I know it is marked as beta, so sorry if it is still WIP.

First thing what i found is that both docker images are missing `aiodynamo` dependency, so i had to rebuild my own docker image, which is based from yours. 

Next what i found is that if i configure everything is [documented](https://docs.litellm.ai/docs/proxy/virtual_keys#beta-dynamo-db) i got an error complaining about missing WebIdentityToken `Invalid type for parameter WebIdentityToken, value: None, type: <class 'NoneType'>, valid types: <class 'str'>`. 

Can you please provide an example how to correctly set up the project with dynamodb.?

**Comment by ghost** [comment]
Hey @krewi1, dynamodb support is deprecated - we found it quite hard to manage features across 2 different db schemas. Are you able to use postgres? 

If you can share your environment, i can find you some relevant solutions

**Comment by krewi1** [comment]
Oh i see, thank you for response. Yeah, i guess i will be able to use PG. It is ok, if the dynamo is deprecated it sounds not correct to use that 👍.  Maybe delete the doc mentioning dynamo? Or mark it as deprecated in the doc? Also feel free to close this issue.

**Comment by ghost** [comment]
Sounds good - what're you trying to use litellm for? 

Happy to help you setup litellm - https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by krewi1** [comment]
Proxy and key management

**Comment by ishaan-jaff** [comment]
Hi @krewi1 wanted to follow up. Can we get on a call sometime this week, we'd love to learn how we can improve litellm proxy for you + help you get setup. Sharing a link to my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat?month=2024-03
