### ISSUE TITLE
[Feature]: Make Users / Keys editable after creation from within the Admin UI

### ISSUE THREAD

**Issue by VfBfoerst** [BerriAI/litellm#2466]
### The Feature

Hi :}  
  
We create users with the Admin UI.  
Unfortunately, there seems to be no option to edit e.g. the allowed models after user creation. I only can see the chosen models:  
![image](https://github.com/BerriAI/litellm/assets/64251549/94723798-99bd-4e78-8c30-2be96e624582)
  
It would be nice to be able to change them or the other user properties on the fly from within the admin ui. A single "edit"-button could solve the issue.
  
Additionally, it would be nice to set the api key to a customized value.  
  
Thank you guys, amazing work!

### Motivation, pitch

As we use other projects where the API-Key can only be set during application startup, we would have to restart the stack everytime after changing the available models for specific users (because the api key changes).

**Comment by ghost** [comment]
hi @VfBfoerst why do you want to set the api key to a customized value?

**Comment by VfBfoerst** [comment]
@krrishdholakia would be an alternative to edit the users, as I then do not need to edit the other dependent projects of the stack (which would require a restart if the api key was changed)

**Comment by ghost** [comment]
Hey @VfBfoerst if you have 10 minutes, can we talk through this?  https://meet.google.com/gep-pfcc-kgh

**Comment by ishaan-jaff** [comment]
@VfBfoerst you can now edit keys / Teams on the admin UI https://github.com/BerriAI/litellm/pull/2795
