### ISSUE TITLE
[Feature]: Rebuff ai api integration 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#2485]
### The Feature

Support using Rebuff for rejecting Prompt Attacks 

### Motivation, pitch

user request

**Comment by krrishdholakia** [comment]
## Thinking 

- Rebuff has no api 
- Rebuff hasn't been updated in 2 months 
- Rebuff's default implementation would require users to setup openai + pinecone for vector storage


We could simplify this by just adopting their work into the proxy.

They have 3 main files:
- heuristics check
- llm check 
- similarity check


How we could implement this: 
- similarity check looks similar to just semantic caching for moderation calls 
- llm check - this seems a bit unstable, as it asks gpt 3.5 turbo to output a structured response. 
- heuristic check - easiest to implement, just simple code checks 


-> user request comes in -> runs through a pre_call hook through `PromptInjectionHandler` -> if it passes, call continues.

## V0 Scope 

- Heuristics check 
- Similarity check

**Comment by ghost** [comment]
## Thinking 

Rebuff has no api
Rebuff hasn't been updated in 2 months
Rebuff's default implementation would require users to setup openai + pinecone for vector storage

Can we just do this ourselves? 

Maybe for v0 

focus on heuristics + using semantic caching for similarity checking
