### ISSUE TITLE
[Feature]: Add support for Fireworks.ai

### ISSUE THREAD

**Issue by aravindputrevu** [BerriAI/litellm#2486]
### The Feature

Add support for Fireworks.ai as a LLM provider

### Motivation, pitch

Fireworks AI is one of the fastest inference platforms with interesting custom LLMs like Fire functions etc. It'd be great add-in for Lite-LLM as well as developer building on Fireworks. 

### Twitter / LinkedIn details

https://twitter.com/fireworksai_hq

**Comment by ishaan-jaff** [comment]
@aravindputrevu can you help us with a contribution here? Example PR: https://github.com/BerriAI/litellm/pull/2168

**Comment by ishaan-jaff** [comment]
Fireworks AI is OpenAI compatible so it would be very similar to #2168

**Comment by ghost** [comment]
PR is created. Will be live in prod by EOD.

**Comment by aravindputrevu** [comment]
Thanks @krrishdholakia
