### ISSUE TITLE
[Feature]: Add support for Gemma-7B model from Groq

### ISSUE THREAD

**Issue by haseeb-heaven** [BerriAI/litellm#2488]
### The Feature

Groq now supports Gemma-7b model and the model name is `gemma-7b-it` please add the support for this.
And this is much more faster like 600 Tokens/Second

Here is sample code from their Docs.

```python
from groq import Groq

client = Groq()
completion = client.chat.completions.create(
    model="gemma-7b-it",
    messages=[
        {
            "role": "user",
            "content": ""
        }
    ],
    temperature=0.1,
    max_tokens=8192,
    top_p=1,
    stream=True,
    stop=None,
)

for chunk in completion:
    print(chunk.choices[0].delta.content or "", end="")

```

### Motivation, pitch

Much faster models than other Groq models and also smaller in size.

**Comment by ishaan-jaff** [comment]
We already support this https://docs.litellm.ai/docs/providers/groq 
- was this not working for you @haseeb-heaven ? 

<img width="674" alt="Screenshot 2024-03-13 at 7 39 57 AM" src="https://github.com/BerriAI/litellm/assets/29436595/8f2041c7-e9eb-4e27-bb94-c7cfb8d0cd2f">

**Comment by ishaan-jaff** [comment]
https://docs.litellm.ai/docs/providers/groq

**Comment by haseeb-heaven** [comment]
> We already support this https://docs.litellm.ai/docs/providers/groq
> 
> * was this not working for you @haseeb-heaven ?
> 
> <img alt="Screenshot 2024-03-13 at 7 39 57 AM" width="674" src="https://private-user-images.githubusercontent.com/29436595/312500177-8f2041c7-e9eb-4e27-bb94-c7cfb8d0cd2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNzA1OTgsIm5iZiI6MTcxMDM3MDI5OCwicGF0aCI6Ii8yOTQzNjU5NS8zMTI1MDAxNzctOGYyMDQxYzctZTllYi00ZTI3LWJiOTQtYzdjZmI4ZDBjZDJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDIyNTEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2YTRkY2M5NjAyOTVmY2Y4Mjk0MWRiMDRhODRhYmNlNTNkMmY2NmQ1NjVhNGQ2NDNiNzQwMWI4ODU4MGM5N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uPgyHMWYZmyrWBjcdwY5OqN7GMXVmu39e7lUj6mvr64">

But Gemma is not working from Groq

**Comment by haseeb-heaven** [comment]
Working now thanks
