### ISSUE TITLE
Connection Error with OpenAI and Claude Model

### ISSUE THREAD

**Issue by mohd-raza** [BerriAI/litellm#2489]
HTTPSConnectionPool(host='api.anthropic.com', port=443): Max retries exceeded with url: /v1/messages (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000222511C2ED0>: Failed to resolve 'api.anthropic.com' ([Errno 11002] getaddrinfo failed)"))

Have faced this error in both Claude and OpenAI.

Please resolve this issue or let us know if there is any solution when there are similar connection errors

**Comment by ishaan-jaff** [comment]
@mohd-raza can you show us code on how to repro this error ?

**Comment by mohd-raza** [comment]
Hey Ishaan thanks for your response.

I can't share the code because of contract signed under the company. 

But whenever I use Completion module from Litellm for Claude or OpenAI I receive this error. Though it is not frequent, it happens 1/10 times.

**Comment by ghost** [comment]
@mohd-raza unable to repro this on our end - we have these tested in our ci/cd. 

Can we do a call to understand and repro this better - https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by ghost** [comment]
bump on this? @mohd-raza

**Comment by mohd-raza** [comment]
Hey @krrishdholakia so we are not facing this error anymore. But I would love to have a chat with you!!

**Comment by ghost** [comment]
great @mohd-raza - reattaching my calendly, feel free to grab any time that works - https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
