### ISSUE TITLE
[Bug]: Empty content for Mistral API

### ISSUE THREAD

**Issue by yesmanmx** [BerriAI/litellm#2490]
### What happened?

# Prerequisites
If configure the Mistral model in `model_list`
```
  - model_name: model1
    litellm_params:
      model: mistral/mistral-tiny
```
# Action
And then call chat completion
```
POST http://0.0.0.0:4000/v1/chat/completions
Content-Type: application/json
Authorization: Bearer 123

{
  "model": "model1",
  "messages": [
    { "role": "system", "content": "You are a helpful assistant." },
    { "role": "user", "content": "What's the weather like today?" }
  ]
}
```
# Issue
In logs you can find, that `content` in `messages` is empty for all messages
```
litellm-litellm-1  | POST Request Sent from LiteLLM:
litellm-litellm-1  | curl -X POST \
litellm-litellm-1  | https://api.mistral.ai/v1/ \
litellm-litellm-1  | -H 'Authorization: Bearer********************' \
litellm-litellm-1  | -d '{'model': 'mistral-tiny', 'messages': [{'role': 'system', 'content': ''}, {'role': 'user', 'content': ''}], 'extra_body': {}}'
```  

# Cause
This is caused by [mistral_api_pt](https://github.com/BerriAI/litellm/blob/9e692d6cce1184258ed82510f55fea04e9f6a44a/litellm/llms/prompt_templates/factory.py#L123) method
Method reformat `content` from `{"type":str, "text":str}` type to string. But if a string was passed - just ignore it. 

# Solution
Update [mistral_api_pt](https://github.com/BerriAI/litellm/blob/9e692d6cce1184258ed82510f55fea04e9f6a44a/litellm/llms/prompt_templates/factory.py#L123) with code below to fix the issue
```
    new_messages = []
    for m in messages:
        texts = ""
        if isinstance(m["content"], list):
            for c in m["content"]:
                if c["type"] == "image_url":
                    return messages
                elif c["type"] == "text" and isinstance(c["text"], str):
                    texts += c["text"]
+        elif isinstance(c["content"], str):
+            texts = c["content"]
        new_m = {"role": m["role"], "content": texts}
        new_messages.append(new_m)
    return new_messages
```

**Comment by ghost** [comment]
able to repro. working on a fix now.

**Comment by ghost** [comment]
fix implemented
<img width="1593" alt="Screenshot 2024-03-13 at 11 34 21 AM" src="https://github.com/BerriAI/litellm/assets/17561003/8c7e9ee9-6bbb-4aaf-b50c-06ff6129f4e7">

**Comment by ghost** [comment]
fix pushed - https://github.com/BerriAI/litellm/commit/dfac742324807b664a2cfee92a1b278a21957efa

should be live soon in v`1.31.7` @yesmanmx

**Comment by ghost** [comment]
Curious @yesmanmx how're you using the proxy today? 

DM'ed on linkedin to start a direct support channel. 

If you have 10 mins, would love to do a call - https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
