### ISSUE TITLE
Cohere API needs to be updated

### ISSUE THREAD

**Issue by tjtanaa** [BerriAI/litellm#2496]
When I run the following examples:
```python
response = litellm.completion(
    model="cohere/command-r", 
    messages = [{ "content": "Hello, how are you?","role": "user"}],
    # stream=True
)

```
The traceback logged the http url request and it is calling the legacy endpoint
```
POST Request Sent from LiteLLM:
curl -X POST \
https://api.cohere.ai/v1/generate \
-H 'accept: application/json' -H 'content-type: application/json' -H 'Authorization: Bearer ' \
-d '{'model': 'command-r', 'prompt': 'Hello, how are you?'}'
```

**Comment by ishaan-jaff** [comment]
@tjtanaa try it with `model="cohere_chat/command-r"`

**Comment by ghost** [comment]
@ishaan-jaff should we maybe move the default cohere route to be their chat route? 

and internally handle if it's one of their deprecated models (like anthropic)

**Comment by ishaan-jaff** [comment]
>  should we maybe move the default cohere route to be their chat route? 

@krrishdholakia yes agree

**Comment by tjtanaa** [comment]
> @tjtanaa try it with `model="cohere_chat/command-r"`

I am getting this error message:
```
litellm.exceptions.APIConnectionError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=cohere_chat/command-r
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers
```

Code snippet ran:
```
response = litellm.completion(
    model="cohere_chat/command-r", 
    messages = [{ "content": "Hello, how are you?","role": "user"}],
    api_key=os.environ["COHERE_API_KEY"] 
    # stream=True
)
```

**Comment by ghost** [comment]
looking into this @tjtanaa

**Comment by ghost** [comment]
@tjtanaa just ran this on a google colab with litellm v`1.31.14`

It works 
<img width="1436" alt="Screenshot 2024-03-15 at 9 47 58 AM" src="https://github.com/BerriAI/litellm/assets/17561003/7d9c434e-6e8f-4616-8fbb-524d50c350fc">
<img width="1059" alt="Screenshot 2024-03-15 at 9 49 05 AM" src="https://github.com/BerriAI/litellm/assets/17561003/56c2e624-923f-45f7-8583-039c7c5653c6">

# Code 
```python
# !pip install litellm
import os
os.environ["COHERE_API_KEY"] = "..."
from litellm import completion
messages = [
    {"role": "system", "content": "You're a good bot"},
    {
        "role": "user",
        "content": "Hey",
    },
]
response = completion(
    model="cohere_chat/command-r",
    messages=messages,
)
print(response)
```

**Comment by ghost** [comment]
Closing this issue as it seems fixed. @tjtanaa please re-open with a way to repro this, if not.
