### ISSUE TITLE
[Bug]: Inconsistent responses across different providers for embedding_response.usage

### ISSUE THREAD

**Issue by phact** [BerriAI/litellm#2510]
### What happened?

I some cases [depending on the provider] I get back a dictionary, in other cases a Usage object. We should be consistent.

I end up doing this sort of thing in my code:

    if type(embedding_response.usage) is dict:
        usage = ...
    else:
        usage = ...

### Twitter / LinkedIn details

@syllogistic

**Comment by ishaan-jaff** [comment]
@phact can you give us two providers you were seeing this on? Will help us repro and fix

**Comment by ghost** [comment]
OpenAI embeddings seem fine 

testing other providers

**Comment by ghost** [comment]
see it on cohere embeddings, investigating

**Comment by ghost** [comment]
fixed cohere.

bedrock works as well.

**Comment by ghost** [comment]
hf seems fine

**Comment by ghost** [comment]
azure works too

Seemed isolated to cohere. @phact let me know if you see it on another provider.

Just pushed a fix for this - https://github.com/BerriAI/litellm/commit/4e1dc7d62e0e99f33e06773e93f0a7ee1a47a6e4

Should be live in next release v`1.31.15+`

**Comment by phact** [comment]
Thanks! was only seeing it in cohere.
