### ISSUE TITLE
fix testing for logging (testing failure scenarios)

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#252]
What's the problem? (if there are multiple - list as bullet points)
Our initial tests involved setting 'bad-key' as the env variable but that led to issues with circle ci testing. This works on local but commented out for now to enable prod deployments. However, we should figure out a way to test for this on circle ci.

**Comment by ghost** [comment]
https://github.com/BerriAI/litellm/blob/258033b672d937e95c5da456906f44b2f9982218/litellm/tests/test_logging.py#L4
