### ISSUE TITLE
sort x-axis for spend tracking chronologically

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#2522]
![image](https://github.com/BerriAI/litellm/assets/17561003/5b576bb5-5772-4822-906e-f7a9f0c146cc)

**Comment by ishaan-jaff** [comment]
working on this + able to repro the issue 
<img width="1163" alt="Screenshot 2024-03-16 at 4 03 41 PM" src="https://github.com/BerriAI/litellm/assets/29436595/b355fb82-e475-4bcb-a8f5-ea2d708d2433">
