### ISSUE TITLE
[Bug]: Helm chart specifies postgres-password but doesn't do anything with it

### ISSUE THREAD

**Issue by tylerbrandt** [BerriAI/litellm#2523]
### What happened?

The [values.yaml file](https://github.com/BerriAI/litellm/blob/517e453adfe5cd9a039c59fc09e00e493b4f6295/deploy/charts/litellm/values.yaml#L161-L164) implies that `postgresql.auth.postgres-password` is required to be set, and it _is_ [built into](https://github.com/BerriAI/litellm/blob/517e453adfe5cd9a039c59fc09e00e493b4f6295/deploy/charts/litellm/templates/secret-dbcredentials.yaml#L8) the `secret-dbcredentials.yaml` artifact, but nothing ever reads that value from that secret. Since it isn't required to set `postgres-password` for any operation of the app, and since if you use the same password when deploying postgres it would result in pods in the cluster having access to that user's password, the chart/values file shouldn't require it. I did confirm that the app works fine with any random garbage in that field.

**Comment by ghost** [comment]
cc: @ishaan-jaff since i know you're looking into helm stuff this week

**Comment by tylerbrandt** [comment]
I think I understand now that this is intended for the postgresql sub chart. I wasn’t seeing it being used because I was using the litellm chart as a dependency in _another_ chart so the litellm-scoped postgresql values weren’t being read.

**Comment by ishaan-jaff** [comment]
@tylerbrandt what can we improve in our helm chart to make this more clear ?

**Comment by tylerbrandt** [comment]
I think documenting how each value is expected to be used and by which chart(s) would help. But I’m a newbie when it comes to Helm, and I think the design of Helm makes some amount of duplication/redundancy/confusion inevitable when combining multiple charts. My more urgent priority is #2421 though since then I could avoid vendoring them in!

I’m ok to close this one.

**Comment by ishaan-jaff** [comment]
ok - will prioritize #2421

**Comment by ishaan-jaff** [comment]
We document the values here @tylerbrandt : https://github.com/BerriAI/litellm/tree/main/deploy/charts/litellm 

- Should we add this somewhere else too ? I'm also new to Helm Charts so your feedback is helpful

**Comment by ishaan-jaff** [comment]
@tylerbrandt litellm helm is released here: https://github.com/BerriAI/litellm/pkgs/container/litellm-helm for #2421 

Usage

```shell
helm pull oci://ghcr.io/berriai/litellm-helm
```

**Comment by ishaan-jaff** [comment]
Here are some docs on using the litellm helm hosted on GHCR https://docs.litellm.ai/docs/proxy/deploy#docker-kubernetes-helm-chart 

lmk if this is what you wanted ? (I tested it on my side)
