### ISSUE TITLE
[Feature]: LiteLLM docker builds - reduce image size 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#2528]
### The Feature

Ignore the /docs folder in our docker builds 

We can make an obvious improvement to our docker builds, Image size is important when considering docker image perf 

From Claude 

<img width="715" alt="Screenshot 2024-03-14 at 8 41 39 PM" src="https://github.com/BerriAI/litellm/assets/29436595/02eacba6-dc51-4247-bbbd-df884f874536">

### Motivation, pitch

-

**Comment by Hitro147** [comment]
Hi @ishaan-jaff,

I'm new to open source and would like to take up this issue. Can you assign this to me?

Thanks!

**Comment by Hitro147** [comment]
I've opened a pull request to address this: https://github.com/BerriAI/litellm/pull/2534.

**Comment by ishaan-jaff** [comment]
done thanks !
