### ISSUE TITLE
[Help]: No connected db.

### ISSUE THREAD

**Issue by chumpblocckami** [BerriAI/litellm#2532]
### What happened?

Using docker, I have the following error

| Traceback (most recent call last):
litellm-1  |   File "/usr/local/lib/python3.9/site-packages/litellm/proxy/proxy_server.py", line 391, in user_api_key_auth
litellm-1  |     raise Exception("No connected db.")
litellm-1  | Exception: No connected db.

With the following config: 
model_list:
  - model_name: my_model
    litellm_params:
      model: ollama/my_model
      api_base: http://ollama:11434
      stream: True

module level litellm settings - https://github.com/BerriAI/litellm/blob/main/litellm/__init__.py
litellm_settings: 
  drop_params: True
  max_budget: 100 
  budget_duration: 30d
  cache: True          # set cache responses to True, litellm defaults to using a redis cache
  cache_params:         # cache_params are optional
    type: "redis"  # The type of cache to initialize. Can be "local" or "redis". Defaults to "local".
    Optional configurations
    supported_call_types: ["acompletion", "completion", "embedding", "aembedding"] # defaults to all litellm call types

general_settings: 
  master_key: sk-1234 # [OPTIONAL] Only use this if you to require all calls to contain this key (Authorization: Bearer sk-1234)
  database_url: "postgresql://<user>:<password>@<host>:<port>/<dbname>" # [OPTIONAL] use for token-based auth to proxy

### Relevant log output

```shell
litellm-1  | INFO:     Started server process [1]
litellm-1  | INFO:     Waiting for application startup.
litellm-1  | INFO:     Application startup complete.
litellm-1  | INFO:     Uvicorn running on http://0.0.0.0:8900 (Press CTRL+C to quit)
litellm-1  | Traceback (most recent call last):
litellm-1  |   File "/usr/local/lib/python3.9/site-packages/litellm/proxy/proxy_server.py", line 391, in user_api_key_auth
litellm-1  |     raise Exception("No connected db.")
litellm-1  | Exception: No connected db.
litellm-1  | LiteLLM: Proxy initialized with Config, Set models:
litellm-1  |     my_model
litellm-1  | 
litellm-1  | #------------------------------------------------------------#
litellm-1  | #                                                            #
litellm-1  | #            'The thing I wish you improved is...'            #
litellm-1  | #        https://github.com/BerriAI/litellm/issues/new        #
litellm-1  | #                                                            #
litellm-1  | #------------------------------------------------------------#
litellm-1  | 
litellm-1  |  Thank you for using LiteLLM! - Krrish & Ishaan
litellm-1  | 
litellm-1  | 
litellm-1  | 
litellm-1  | Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
litellm-1  | 
litellm-1  | 
litellm-1  | LiteLLM: Proxy initialized with Config, Set models:
litellm-1  |     my_model
litellm-1  | INFO:     172.20.0.1:42654 - "POST /chat/completions HTTP/1.1" 401 Unauthorized
litellm-1  | INFO:     172.20.0.1:42654 - "POST /chat/completions HTTP/1.1" 401 Unauthorized
litellm-1  | Traceback (most recent call last):
litellm-1  |   File "/usr/local/lib/python3.9/site-packages/litellm/proxy/proxy_server.py", line 391, in user_api_key_auth
litellm-1  |     raise Exception("No connected db.")
litellm-1  | Exception: No connected db.
```

**Comment by ghost** [comment]
@chumpblocckami 

I can see you're setting a master key:
> general_settings:
master_key: sk-1234

I'm assuming you're making a request to the proxy with a key that is not the master key


If you've set master key and send in a key that is not that, then we check if it's a virtual key - for which you need a connected db. 

That's why the error is raised. 

Can you check the bearer token in the request being made to the proxy?

**Comment by ghost** [comment]
@chumpblocckami tried to dm on linkedin. Did this fix your issue? 

Happy to help debug this week too.

Attached my calendly, but anytime works - https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by chumpblocckami** [comment]
Hi, sorry for the late response.
I resolved the issue, i was something related to my configuration
Thanks for your time :)

**Comment by ishaan-jaff** [comment]
hi @chumpblocckami that's great ! can we get on a call sometime this week to learn how you're using LiteLLM proxy, how we can improve for you ? My cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by corticalstack** [comment]
@chumpblocckami what was the issue with your config, I have the same issue. Thanks. Not sure if it's my setting of master_key (which I seem to need to log into web ui?), but then fdoesn't that force setting this key in bearer_token?

I'm deploying using portainer with docker-compose:

```
version: "3.9"
services:
  litellm:
    container_name: litellm
    build:
      context: .
      args:
        target: runtime
    image: ghcr.io/berriai/litellm:main-latest
    ports:
      - "4000:4000" # Map the container port to the host, change the host port if necessary
    volumes:    
      - /etc/litellm/config.yaml:/app/config.yaml # Mount the local configuration file
    # You can change the port or number of workers as per your requirements or pass any new supported CLI augument. Make sure the port passed here matches with the container port defined above in `ports` value

    command: [ "--config", "/app/config.yaml", "--port", "4000", "--num_workers", "8", "--detailed_debug" ]
```

With UI_USERNAME, UI_PASSWORD, and LITELLM_MASTER_KEY set as enviroment variables.

Output of container logs. Welcome any hints @ishaan-jaff , thanks!

     
```
/usr/local/lib/python3.11/site-packages/pydantic/_internal/_fields.py:160: UserWarning: Field "model_name" has conflict with protected namespace "model_".
You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/usr/local/lib/python3.11/site-packages/pydantic/_internal/_fields.py:160: UserWarning: Field "model_info" has conflict with protected namespace "model_".
You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
INFO:     Started server process [1]
INFO:     Waiting for application startup.
21:36:50 - LiteLLM Proxy:DEBUG: proxy_server.py:1971 - Loaded config YAML (api_key and environment_variables are not shown):
{
  "model_list": [
    {
      "model_name": "gpt-3.5-turbo",
      "litellm_params": {
        "model": "gpt-3.5-turbo",
        "api_key": "sk-....",
        "rpm": 200
      }
    }
  ],
  "general_settings": {
    "master_key": "sk-1234"
  }
}
21:36:50 - LiteLLM:DEBUG: caching.py:22 - set cache: key: 760c0748edebdd8f4799d7683b70ba7673e8138e1b3f50bb8f9d5d3f4afa03ff_max_parallel_requests_client; value: <asyncio.locks.Semaphore object at 0x7f4fb6bf75d0 [unlocked, value:200]>
21:36:50 - LiteLLM:DEBUG: caching.py:22 - InMemoryCache: set_cache
21:36:50 - LiteLLM Router:DEBUG: router.py:2241 - Initializing OpenAI Client for gpt-3.5-turbo, Api Base:None, Api Key:sk-proj-***************
21:36:50 - LiteLLM:DEBUG: caching.py:22 - set cache: key: 760c0748edebdd8f4799d7683b70ba7673e8138e1b3f50bb8f9d5d3f4afa03ff_async_client; value: <openai.AsyncOpenAI object at 0x7f4fb5d55dd0>
21:36:50 - LiteLLM:DEBUG: caching.py:22 - InMemoryCache: set_cache
21:36:50 - LiteLLM:DEBUG: caching.py:22 - set cache: key: 760c0748edebdd8f4799d7683b70ba7673e8138e1b3f50bb8f9d5d3f4afa03ff_client; value: <openai.OpenAI object at 0x7f4fb5af9ed0>
21:36:50 - LiteLLM:DEBUG: caching.py:22 - InMemoryCache: set_cache
21:36:50 - LiteLLM:DEBUG: caching.py:22 - set cache: key: 760c0748edebdd8f4799d7683b70ba7673e8138e1b3f50bb8f9d5d3f4afa03ff_stream_async_client; value: <openai.AsyncOpenAI object at 0x7f4fb5b0c910>
21:36:50 - LiteLLM:DEBUG: caching.py:22 - InMemoryCache: set_cache
21:36:50 - LiteLLM:DEBUG: caching.py:22 - set cache: key: 760c0748edebdd8f4799d7683b70ba7673e8138e1b3f50bb8f9d5d3f4afa03ff_stream_client; value: <openai.OpenAI object at 0x7f4fb5b0f510>
21:36:50 - LiteLLM:DEBUG: caching.py:22 - InMemoryCache: set_cache
21:36:50 - LiteLLM Router:DEBUG: router.py:2397 - 
Initialized Model List [{'model_name': 'gpt-3.5-turbo', 'litellm_params': {'model': 'gpt-3.5-turbo', 'rpm': 200, 'api_key': 'sk-....', 'max_retries': 2}, 'model_info': {'id': '760c0748edebdd8f4799d7683b70ba7673e8138e1b3f50bb8f9d5d3f4afa03ff'}}]
21:36:50 - LiteLLM Router:INFO: router.py:319 - Intialized router with Routing strategy: simple-shuffle
Routing fallbacks: None
Routing context window fallbacks: None
Router Redis Caching=None
21:36:50 - LiteLLM Proxy:DEBUG: utils.py:38 - INITIALIZING LITELLM CALLBACKS!
21:36:50 - LiteLLM:DEBUG: utils.py:1030 - callback: <litellm.proxy.hooks.tpm_rpm_limiter._PROXY_MaxTPMRPMLimiter object at 0x7f4fb5d54890>
21:36:50 - LiteLLM:DEBUG: utils.py:1030 - callback: <bound method SlackAlerting.response_taking_too_long_callback of <litellm.integrations.slack_alerting.SlackAlerting object at 0x7f4fb5d54950>>
21:36:50 - LiteLLM:DEBUG: utils.py:1030 - callback: <bound method Router.deployment_callback_on_failure of <litellm.router.Router object at 0x7f4fb5df9710>>
21:36:50 - LiteLLM:DEBUG: utils.py:1030 - callback: <litellm.proxy.hooks.max_budget_limiter._PROXY_MaxBudgetLimiter object at 0x7f4fb5d548d0>
21:36:50 - LiteLLM:DEBUG: utils.py:1030 - callback: <litellm.proxy.hooks.cache_control_check._PROXY_CacheControlCheck object at 0x7f4fb5d54910>
21:36:50 - LiteLLM:DEBUG: utils.py:1030 - callback: <litellm._service_logger.ServiceLogging object at 0x7f4fb5b12510>
21:36:50 - LiteLLM:DEBUG: utils.py:1030 - callback: <litellm.proxy.hooks.parallel_request_limiter._PROXY_MaxParallelRequestsHandler object at 0x7f4fb6379f90>
21:36:50 - LiteLLM Proxy:DEBUG: proxy_server.py:3213 - prisma_client: None
21:36:50 - LiteLLM Proxy:DEBUG: proxy_server.py:3217 - custom_db_client client - None
21:36:50 - LiteLLM Proxy:DEBUG: proxy_server.py:3268 - custom_db_client client None. Master_key: sk-1234
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:4000 (Press CTRL+C to quit)
#------------------------------------------------------------#
#                                                            #
#               'A feature I really want is...'               #
#        https://github.com/BerriAI/litellm/issues/new        #
#                                                            #
#------------------------------------------------------------#
 Thank you for using LiteLLM! - Krrish & Ishaan
Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM: Proxy initialized with Config, Set models:
    gpt-3.5-turbo
INFO:     192.168.1.132:65069 - "GET /sso/key/generate HTTP/1.1" 200 OK
INFO:     192.168.1.132:65069 - "POST /login HTTP/1.1" 401 Unauthorized
INFO:     192.168.1.132:65070 - "POST /login HTTP/1.1" 401 Unauthorized
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 6071, in user_update
    raise Exception("Not connected to DB!")
Exception: Not connected to DB!
INFO:     192.168.1.132:65075 - "POST /login HTTP/1.1" 400 Bad Request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 6071, in user_update
    raise Exception("Not connected to DB!")
Exception: Not connected to DB!
INFO:     192.168.1.132:65082 - "POST /login HTTP/1.1" 400 Bad Request
```

If I try to log in to the /UI with the UI_USERNAME and UI_PASSWORD configured as env variables, I get the error:
`{"error":{"message":"Invalid credentials used to access UI. Passed in username: jp, passed in password: password.\nCheck 'UI_USERNAME', 'UI_PASSWORD' in .env file","type":"auth_error","param":"invalid_credentials","code":401}}`

If I try to login in with user admin and use the master key sk-1234, I get the error:
`{"error":{"message":"Authentication Error, Not connected to DB!","type":"auth_error","param":"None","code":400}}`

Which DB?

**Comment by ghost** [comment]
> Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 6071, in user_update
    raise Exception("Not connected to DB!")
Exception: Not connected to DB!

This is raised when there's no database url in your config/env 

```bash
export DATABASE_URL="postgres://.."
```

**Comment by corticalstack** [comment]
@krrishdholakia Thanks. 

- Can you cofirm - to be able to use the UI at all, I need to configure a db, e.g. postgres?
- When logging into the UI, should I use the .env configured user name & user password, or admin user and master key?

I kindly suggest the documentation needs improving for the different installation options for a better onboarding experience. It's not clear the features offered by each option, jumping around between documentation for basic install then to what looks like a diff repo here: https://github.com/BerriAI/litellm/pkgs/container/litellm-database.

Thanks again.

**Comment by ghost** [comment]
> Can you cofirm - to be able to use the UI at all, I need to configure a db, e.g. postgres?

Yes. It's right here - https://docs.litellm.ai/docs/proxy/ui#quick-start

Where would you have expected to see this? 


> When logging into the UI, should I use the .env configured user name & user password, or admin user and master key

if you set a UI_USERNAME+ UI_PASSWORD use that. 

The admin + master key is the default way to login. 

I thought this explained it. What could've been made clearer? 
<img width="721" alt="Screenshot 2024-04-26 at 10 48 30 PM" src="https://github.com/BerriAI/litellm/assets/17561003/19ca1837-4f10-49d6-a9c6-4cf57b688fe2">

**Comment by corticalstack** [comment]
So I set environment variable DATABASE_URL as:
`postgresql://admin:mypwd@192.168.1.12:5432/mydbname`

II also have UI_USERNAME and UI_PASSWORD set, attempt to log in with those, get:
{"error":{"message":"Invalid credentials used to access UI. Passed in username: myuiusername, passed in password: myuipassword.\nCheck 'UI_USERNAME', 'UI_PASSWORD' in .env file","type":"auth_error","param":"invalid_credentials","code":401}}

If I try and log in with admin and master key, I get "database not connected" despite configuring DATABASE_URL

**Comment by corticalstack** [comment]
@krrishdholakia  Just to add, this is my docker-compose:
```
version: "3.9"
services:
  litellm:
    container_name: litellm
    build:
      context: .
      args:
        target: runtime
    image: ghcr.io/berriai/litellm:main-latest
    ports:
      - "4000:4000" # Map the container port to the host, change the host port if necessary
    volumes:    
      - /etc/litellm/config.yaml:/app/config.yaml # Mount the local configuration file
    # You can change the port or number of workers as per your requirements or pass any new supported CLI augument. Make sure the port passed here matches with the container port defined above in `ports` value

    command: [ "--config", "/app/config.yaml", "--port", "4000", "--num_workers", "8"]
```

I set the environment variables in Portainer:
![image](https://github.com/BerriAI/litellm/assets/3995321/d3017213-5214-462d-bde2-9395554ca195)

And my config.yaml
```
model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
        model: gpt-3.5-turbo
        api_key: sk-....
        rpm: 200
general_settings: 
  master_key: sk-1234
```

Can reach the postgres container with pg-admin client.

**Comment by corticalstack** [comment]
Finally!

Despite setting the environment variables for DATABASE_URL in portainer, looked like they were not being picked up. Set DATABASE_URL instead in config.yaml general settings, and voila!

![image](https://github.com/BerriAI/litellm/assets/3995321/375e02ee-13e4-4c93-8ae6-539c79d1ba86)

Thanks for your earlier support!

**Comment by ishaan-jaff** [comment]
@corticalstack thanks for using LiteLLM - we now offer a Cloud Hosted LiteLLM Proxy, curious is this something that you would want to use ?
