### ISSUE TITLE
[Bug]: 401 Authentication Error after update

### ISSUE THREAD

**Issue by mackeroo** [BerriAI/litellm#2539]
### What happened?

We just bumped our litellm proxy server version from `v1.27.10` to `v1.31.4` and we started getting 401 errors (server logs attached below).

I confirmed that the `OPENAI_API_KEY` environment variable was being set correctly on the server, and that the proxy server was working once we reverted back to `v1.27.10`

### Relevant log output

```
litellm-1        | INFO:     192.168.96.3:42832 - "POST /chat/completions HTTP/1.1" 401 Unauthorized
litellm-1        | Traceback (most recent call last):
litellm-1        |   File "/usr/local/lib/python3.9/site-packages/litellm/proxy/proxy_server.py", line 371, in user_api_key_auth
litellm-1        |     assert api_key.startswith("sk-")  # prevent token hashes from being used
litellm-1        | AssertionError
```

**Comment by ishaan-jaff** [comment]
Hi @mackeroo i'm on here and can help with this issue live: https://meet.google.com/gnj-vcnv-igq?ijlm=1710534874332&adhoc=1&hs=187

**Comment by JungeAlexander** [comment]
@mackeroo @ishaan-jaff Is there a fix for this or what was the solution? I am seeing the same error with an Azure OpenAI deployment. Since I am a new user, I do not know if this used to work or if I am making a mistake.

**Comment by ghost** [comment]
hey @JungeAlexander we re-ran it on the latest release and it was fixed. 

It had to do with the placing of conditional block for virtual keys. Let me know if the issue is still there for you?

**Comment by ghost** [comment]
@JungeAlexander dm'ed on linkedin to start a direct support channel

**Comment by JungeAlexander** [comment]
Thanks @krrishdholakia, this is excellent support - I replied on LinkedIn :)

**Comment by JungeAlexander** [comment]
My issue is solved thanks to excellent help from @krrishdholakia - thanks again! My problem was that I was using `litellm --test` to test locally while also setting the `master_key`. It turns out that `litellm --test` does not play nicely with a master_key but the following curl command worked to test my locally running litellm proxy:

```shell
curl --location 'http://0.0.0.0:4000/v1/chat/completions' --header 'Content-Type: application/json' --header 'Authorization: Bearer <MASTER_KEY>' --data '{"model": "<MODEL_NAME>", "messages": [{"content": "an advanced critic ai", "role": "system"}, {"content": "what is the value of pi ?", "role": "user"}]}'
```
