### ISSUE TITLE
Add support for VLLM 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#254]
**Describe the solution you'd like**
https://github.com/FastEval/FastEval/pull/81

**Comment by ghost** [comment]
saw this again in another repo 

<img width="264" alt="Screenshot 2023-09-04 at 6 42 04 PM" src="https://github.com/BerriAI/litellm/assets/17561003/7af2f596-a019-4adf-96b1-b759e5582fbb">

**Comment by ishaan-jaff** [comment]
these are local llms ?

**Comment by ghost** [comment]
you're right - but i believe they standardize a lot of the input / output requirements for locally-run LLMs. If we were to support local models, I believe this would be a good way to do it.

**Comment by ghost** [comment]
done - https://docs.litellm.ai/docs/providers/vllm
