### ISSUE TITLE
Docker pull image  throwing error

### ISSUE THREAD

**Issue by vijtad** [BerriAI/litellm#2543]
### What happened?

I see this error when using following in Dockerfile

FROM ghcr.io/berriai/litellm:main-v1.31.14

**ERROR: failed to solve: ghcr.io/berriai/litellm:main-v1.31.14: failed to authorize: failed to fetch oauth token: unexpected status from GET request to https://ghcr.io/token?scope=repository%3Aberriai%2Flitellm%3Apull&service=ghcr.io: 403 Forbidden**

**Comment by ishaan-jaff** [comment]
This is github failing your request

**Comment by ishaan-jaff** [comment]
`docker pull ghcr.io/berriai/litellm:main-v1.31.14` Try this

**Comment by vijtad** [comment]
I get this error

**Error response from daemon: Head "https://ghcr.io/v2/berriai/litellm/manifests/main-v1.31.14": denied: denied**

**Comment by vijtad** [comment]
Thank you.
My problem solved after logging in github successfully.
