### ISSUE TITLE
[Bug]: master key user cost tracking bug (user table) 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#2545]
### What happened?

user put in a master key and saw errors re: cost tracking on the user table

**Comment by ghost** [comment]
> Update User DB call failed to execute 'dict' object has no attribute 'spend'

**Comment by ghost** [comment]
should be fixed - https://github.com/BerriAI/litellm/commit/2c2db9ce8928307f09c93a5c9866ee9a2d18ed0d

Master keys when connecting to db should start with `sk-`.  Since we don't store the raw key, but the hash, we need a way to check this.
