### ISSUE TITLE
Improve acomplete for high traffic scenarions 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#255]
What's the problem? (if there are multiple - list as bullet points)
"ayncio [seems to be implemented](https://github.com/BerriAI/litellm/blob/adcf3dfe74854827938af34f3c59c6329c1ecd72/litellm/main.py#L48) using threads with loop.run_in_executor(None, ...) which https://github.com/FastEval/FastEval/pull/78#issuecomment-1703241377." 

https://github.com/FastEval/FastEval/pull/81

**Comment by filip-michalsky** [comment]
@retry_decorator
    async def _completion_with_retry(**kwargs: Any) -> Any:
        # Use OpenAI's async api https://github.com/openai/openai-python#async-api
>       return await llm.client.acreate(**kwargs)
E       AttributeError: module 'litellm' has no attribute 'acreate'

@krrishdholakia do you have plans on supporting async?

**Comment by filip-michalsky** [comment]
I see https://docs.litellm.ai/docs/completion/stream

that you support stream or async full completion, but not async stream yet

**Comment by ghost** [comment]
Hey @filip-michalsky the way to call it is 

```
from litellm import acreate

acreate(model="gpt-3.5-turbo", messages=[{"role":"user", "content": "Hey, how's it going?"}])
```

Link to code - https://github.com/BerriAI/litellm/blob/94a1f4bd0e621df25798587cfffcb0242a9d873b/litellm/utils.py#L1265

**Comment by ghost** [comment]
Our docs are a bit out of sync - we do have support for async streaming 

Code - https://github.com/BerriAI/litellm/blob/94a1f4bd0e621df25798587cfffcb0242a9d873b/litellm/utils.py#L1881

Thanks to @estill01's great PR - https://github.com/BerriAI/litellm/pull/240


I'll have a tutorial out for this tomorrow morning.

**Comment by ghost** [comment]
Is there a specific model(s) you were trying to do this with? @filip-michalsky

**Comment by ghost** [comment]
Hey @filip-michalsky here's the tutorial on async streaming - 
https://docs.litellm.ai/docs/completion/stream#async-streaming

Let me know if it's missing anything

**Comment by filip-michalsky** [comment]
@krrishdholakia I think you have a typo there?

``from litellm import acompletion``

and then 
```
        response = **completion**(
            model="j2-ultra", messages=messages, stream=True, logger_fn=logger_fn
        )

**Comment by filip-michalsky** [comment]
Also curios why to use Al21? Is their endpoint faster than OpenAI / Anthropic?

**Comment by ghost** [comment]
Hey @filip-michalsky, 
Thanks for the typo. Pushed a fix for that + updated the tutorial to show it with gpt-3.5-turbo. 

```
from litellm import completion
import asyncio

def logger_fn(model_call_object: dict):
    print(f"LOGGER FUNCTION: {model_call_object}")


user_message = "Hello, how are you?"
messages = [{"content": user_message, "role": "user"}]

async def completion_call():
    try:
        response = completion(
            model="gpt-3.5-turbo", messages=messages, stream=True, logger_fn=logger_fn
        )
        print(f"response: {response}")
        complete_response = ""
        start_time = time.time()
        # Change for loop to async for loop
        async for chunk in response:
            chunk_time = time.time()
            print(f"time since initial request: {chunk_time - start_time:.5f}")
            print(chunk["choices"][0]["delta"])
            complete_response += chunk["choices"][0]["delta"]["content"]
        if complete_response == "": 
            raise Exception("Empty response received")
    except:
        print(f"error occurred: {traceback.format_exc()}")
        pass

asyncio.run(completion_call())
```

**Comment by ghost** [comment]
regarding the usage of AI21 - I was using that in our tests to see if it worked for non-openai models and included that in the example. Overall, i do think the j2-ultra model from ai21 is better than cohere's models and you don't need a waitlist to use it (unlike anthropic). 

If you're doing things like model fallbacks and need a backup model in case openai fails, I'd recommend checking that + aleph alpha out.

**Comment by ghost** [comment]
Updated docs - https://docs.litellm.ai/docs/completion/stream#async-streaming
