### ISSUE TITLE
Litellm is not starting the Uvicorn properly, http://0.0.0.0:4000/ cannot be reached 

### ISSUE THREAD

**Issue by accaderi** [BerriAI/litellm#2566]
First of all I need to pip install 'litellm[proxy]' if i am not misstaken,
but despite ollama server is running and mistral is working properly under the conda environment too
when i run litellm --model ollama/mistral i have got the followin message:

INFO:     Started server process [1936]
INFO:     Waiting for application startup.

#------------------------------------------------------------#
#                                                            #
#           'It would help me if you could add...'            #
#        https://github.com/BerriAI/litellm/issues/new        #
#                                                            #
#------------------------------------------------------------#

 Thank you for using LiteLLM! - Krrish & Ishaan

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new

INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:4000 (Press CTRL+C to quit)

when i try to go to http://0.0.0.0:4000 the browser couldnt find the page/address:

This site can’t be reachedThe webpage at http://0.0.0.0:4000/ might be temporarily down or it may have moved permanently to a new web address.
ERR_ADDRESS_INVALID

I have no clue what I am doing wrong.
Thank you for the help in advance

**Comment by ishaan-jaff** [comment]
can you try running `litellm --detailed_debug` and see what logs appear @accaderi

**Comment by accaderi** [comment]
@ishaan-jaff

> can you try running `litellm --detailed_debug` and see what logs appear @accaderi

(freeuiagent) PS F:\0_AI\AutogenStudio\freeuiagent> litellm --detailed_debug
INFO:     Started server process [12560]
INFO:     Waiting for application startup.

#------------------------------------------------------------#
#                                                            #
#            'The thing I wish you improved is...'            #
#        https://github.com/BerriAI/litellm/issues/new        #
#                                                            #
#------------------------------------------------------------#

 Thank you for using LiteLLM! - Krrish & Ishaan



Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new


18:46:59 - LiteLLM Proxy:DEBUG: utils.py:29 - INITIALIZING LITELLM CALLBACKS!
18:46:59 - LiteLLM:DEBUG: utils.py:827 - callback: <litellm.proxy.hooks.parallel_request_limiter._PROXY_MaxParallelRequestsHandler object at 0x000001D4FE35E310>
18:46:59 - LiteLLM:DEBUG: utils.py:827 - callback: <litellm.proxy.hooks.max_budget_limiter._PROXY_MaxBudgetLimiter object at 0x000001D4FE35E350>
18:46:59 - LiteLLM:DEBUG: utils.py:827 - callback: <bound method ProxyLogging.response_taking_too_long_callback of <litellm.proxy.utils.ProxyLogging object at 0x000001D4FE35E250>>
18:46:59 - LiteLLM:DEBUG: utils.py:827 - callback: <litellm.proxy.hooks.cache_control_check._PROXY_CacheControlCheck object at 0x000001D4FE35E390>
18:46:59 - LiteLLM Proxy:DEBUG: proxy_server.py:2557 - prisma client - None
18:46:59 - LiteLLM Proxy:DEBUG: proxy_server.py:2561 - custom_db_client client - None
18:46:59 - LiteLLM Proxy:DEBUG: proxy_server.py:2613 - custom_db_client client None. Master_key: None
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:4000 (Press CTRL+C to quit)

if i run: litellm --model ollama/mistral --detailed_debug, got a similar response:

(freeuiagent) PS F:\0_AI\AutogenStudio\freeuiagent> litellm --model ollama/mistral --detailed_debug
INFO:     Started server process [9880]
INFO:     Waiting for application startup.

#------------------------------------------------------------#
#                                                            #
#            'The thing I wish you improved is...'            #
#        https://github.com/BerriAI/litellm/issues/new        #
#                                                            #
#------------------------------------------------------------#

 Thank you for using LiteLLM! - Krrish & Ishaan



Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new


18:49:16 - LiteLLM Proxy:DEBUG: utils.py:29 - INITIALIZING LITELLM CALLBACKS!
18:49:16 - LiteLLM:DEBUG: utils.py:827 - callback: <litellm.proxy.hooks.parallel_request_limiter._PROXY_MaxParallelRequestsHandler object at 0x000002061CDDDF10>
18:49:16 - LiteLLM:DEBUG: utils.py:827 - callback: <litellm.proxy.hooks.cache_control_check._PROXY_CacheControlCheck object at 0x000002061CDDDF90>
18:49:16 - LiteLLM:DEBUG: utils.py:827 - callback: <bound method ProxyLogging.response_taking_too_long_callback of <litellm.proxy.utils.ProxyLogging object at 0x000002061CDDDE90>>
18:49:16 - LiteLLM:DEBUG: utils.py:827 - callback: <litellm.proxy.hooks.max_budget_limiter._PROXY_MaxBudgetLimiter object at 0x000002061CDDDF50>
18:49:16 - LiteLLM Proxy:DEBUG: proxy_server.py:2557 - prisma client - None
18:49:16 - LiteLLM Proxy:DEBUG: proxy_server.py:2561 - custom_db_client client - None
18:49:16 - LiteLLM Proxy:DEBUG: proxy_server.py:2613 - custom_db_client client None. Master_key: None
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:4000 (Press CTRL+C to quit)

if i run the following python code:
from litellm import completion

response = completion(
    model="ollama/mistral", 
    messages=[{ "content": "wats up?","role": "user"}], 
    api_base="http://localhost:11434"
)
print(response)

the response:
ModelResponse(id='chatcmpl-0ade2dc2-07a9-4c97-ab20-7af1df9f47b5', choices=[Choices(finish_reason='stop', index=0, message=Message(content=' I\'m just a computer program, I don\'t have the ability to "wat up" or feel up. But I\'m here and ready to help answer any questions you might have! Let me know how I can assist you today. 😊️☕️💻', role='assistant'))], created= =1710870794, model='ollama/mistral', object='chat.completion', system_fingerprint=None, usage=Usage(prompt_tokens=13, completion_tokens=63, total_tokens=76), _response_ms=10039.405)

**Comment by ghost** [comment]
looks like it worked

**Comment by accaderi** [comment]
@krrishdholakia, @ishaan-jaff
unfortunately not, since the last python code is using the ollama localhost address, http://localhost:11434/,
but the ```litellm --model ollama/mistral``` which would simulate the openai server type api seems somehow not utilising the model.
When i try to access the http://0.0.0.0:4000/ address, the site is unreachable so it is not loaded:

This site can’t be reached
The webpage at http://0.0.0.0:4000/ might be temporarily down or it may have moved permanently to a new web address.
ERR_ADDRESS_INVALID

I tried it on my other computer and the same is happening.

**Comment by FD01143** [comment]
same issue i am getting, pls anyone solve this

**Comment by ghost** [comment]
if this is running inside a docker image, then you need to expose the port

**Comment by FD01143** [comment]
I am running this in cli, not in docker

**Comment by FD01143** [comment]
still getting same error

**Comment by ghost** [comment]
this implies nothing is running on port 4000 - what are your server logs saying? @FD01143

**Comment by FD01143** [comment]
when i run local debug, i am getting proxy_server not available
