### ISSUE TITLE
[Feature]: JWT-based Auth v2 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#2599]
### The Feature

Tracking improvements / learnings for our jwt-based auth implementation: 

- [x] remove jwt issuer check 
- [x] give multiple examples for the possible route of a jwt keys url (e.g. https://demo.duendesoftware.com/.well-known/openid-configuration/jwks)
- [x] return an error if id making request doesn't exist on proxy 
- [x] make sure spend tracking works when making requests via JWT's 
- [ ] `litellm_proxy_user` scope -> utilizing ai calls. Can fetch own usage. Can not edit budgets

### Motivation, pitch

user needs to use jwt-based auth for openai proxy calls in prod

**Comment by ghost** [comment]
sample JWT - 

```
{
  "exp": 1710956271,
  "iat": 1710955971,
  "jti": "375acaa9-1a98-4624-881d-ac58c4fbc34e",
  "iss": "http://localhost:8080/realms/test-litellm-proxy",
  "aud": "account",
  "sub": "84bd6577-d639-4b51-a4a0-63c64b764885",
  "typ": "Bearer",
  "azp": "litellm-test-client-id",
```


It looks like for an end-user identifier (the person to whom the token was issued), sub is for them

but for a client identifier (the application for which it was issued), the azp is for that. 

in our heirarchy, this seems similar to the user (sub) vs. team (azp).
