### ISSUE TITLE
[Bug]: prompt injection detection heuristics -> flags 'submit' 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#2601]
### What happened?

simple word - submit, trips up our input similarity checking 

![image](https://github.com/BerriAI/litellm/assets/17561003/e3165113-1fde-489f-8dfc-0149a5392be8)

it was present in the data a user was processing, causing a request to be rejected 

### Twitter / LinkedIn details

cc: @sumba101

**Comment by ghost** [comment]
fixed now
