### ISSUE TITLE
[Feature]: Allow a 'Prod' mode flag

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#2610]
### The Feature

There are settings on litellm proxy:
- batch writing to db every 60s
- batch reading from redis cache 

that only make sense in prod, not during local testing (e.g. batch writing every 60s makes it hard to know in quick testing if a spend update worked). 

Allow a user to set a 'LITELLM_MODE="PROD"' flag, to turn on these features. 

### Motivation, pitch

i thought user spend tracking wasn't working, only to realize the proxy was batch writing every 60s.

**Comment by ishaan-jaff** [comment]
you can set `LITELLM_ENVIRONMENT` now
