### ISSUE TITLE
allow user to query `/model/info` for models they have access to

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#2624]

**Comment by ansSanthoshM** [comment]
I am too looking for this feature. For load balancing router when more than one end points are provided, i like to which end point is used or employeed for getting the response. It would be good if we can get this data from router.completion response dictionary.

**Comment by ghost** [comment]
this now works

**Comment by ghost** [comment]
@ansSanthoshM we return the model id in the response -> `response._hidden_params["model_id"]` 

you can get the model info by calling `router.get_model_info(model_id=response._hidden_params["model_id"])`

Let me know if that solves your problem
