### ISSUE TITLE
[Feature]:  Remove f-string formatting from logging

### ISSUE THREAD

**Issue by rlippmann** [BerriAI/litellm#2627]
### The Feature

LiteLLM seems to use a lot of f-string logging.  This can have slight performance impacts as well as being error prone.

### Motivation, pitch

[see here for a more detailed explanation](https://docs.astral.sh/ruff/rules/logging-f-string/#:~:text=Using%20f%2Dstrings%20to%20format,argument%20defers%20formatting%20until%20required.)

**Comment by ghost** [comment]
Great idea @rlippmann, i can run some load tests on this 

Are you using the litellm proxy in prod? Would love to understand your use-case better - https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by rlippmann** [comment]
No, I'm not using it in production.

What I'm looking to do is to write an open source project that will automate porting between languages.  Since I will need to convert many source files, using the router functionality (not necessarily through proxy) would be very useful.  I would like to understand more about how that works.  

It's also the motivation between my enhancement idea for cost based routing, since my main motivation is to do things like convert an open source project in javascript to python (or even C++/Rust/etc).

**Comment by ishaan-jaff** [comment]
PR 1 addressing this: https://github.com/BerriAI/litellm/pull/2683

Will stack 1-2 PRs since it's a significant change to how debugging is done

**Comment by ishaan-jaff** [comment]
closing as done
