### ISSUE TITLE
[Feature]: expose 'api-base' in response headers 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#2631]
### The Feature

return the api base in the response headers 

### Motivation, pitch

addresses - https://github.com/BerriAI/litellm/issues/2440

**Comment by drobiazko** [comment]
@krrishdholakia  any ETA for this one?

**Comment by ghost** [comment]
Hey @drobiazko missed this. Yep - i'll work on it today!

**Comment by ghost** [comment]
PR #3430 addresses this by returning the selected model's api base in the response headers

![image](https://github.com/BerriAI/litellm/assets/17561003/16f7f8b1-9db6-4eba-b9e7-7c7270a25bfb)


We use the 'get_api_base' helper function to extract this from litellm params or construct this (e.g. for vertex ai) 

https://github.com/BerriAI/litellm/blob/e99edaf4e168fd870640ed17f69df353de67fc03/litellm/utils.py#L5795

**Comment by ghost** [comment]
Hey @drobiazko this should be on the next release. 

Would love to understand how you're using litellm. Can we do a 10 min call sometime this / next week? 

https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
