### ISSUE TITLE
[Feature]: Enforce 'user' param for prod apps 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#2634]
### The Feature

Allow admins to enforce 'user' param is set for certain keys 

### Motivation, pitch

user wants apps in prod to always have the 'user' param filled out, for end-user cost tracking

**Comment by ishaan-jaff** [comment]
enforce params is here: https://docs.litellm.ai/docs/proxy/enterprise#enforce-required-params-for-llm-requests
