### ISSUE TITLE
[Feature]: key-based LLM Guard checks 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#2651]
### The Feature

Allow admin to enable keys with llm guard checks enabled 

### Motivation, pitch

1 team wants it's requests to go through llm guard. not all teams do. 

```
teamA needs to filter some topic based on some business logic.

but the rest of the teams do not need to do that

we don't do extra calls to llmguard for teams that do not need this feature
```

**Comment by ghost** [comment]
this is now supported - https://docs.litellm.ai/docs/proxy/enterprise#turn-onoff-per-key
