### ISSUE TITLE
[Feature]: Support claude 3 on vertex ai 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#2658]
### The Feature

Vertex AI has Claude 3. Support it 

### Motivation, pitch

user request

**Comment by Manouchehri** [comment]
Nice!

Off-topic to LiteLLM, but if anyone is wondering, sadly Claude 3 on Vertex AI doesn't qualify for Google Cloud credits. (If it did, the subtotal below would be $0.00.)

<img width="993" alt="image" src="https://github.com/BerriAI/litellm/assets/7232674/456cdbac-2a32-4e0d-b677-661637bffe90">

It's the same deal with Bedrock as well (Claude 3 costs real money, can't use AWS credits).

**Comment by AdithyanI** [comment]
> Nice!
> 
> Off-topic to LiteLLM, but if anyone is wondering, sadly Claude 3 on Vertex AI doesn't qualify for Google Cloud credits. (If it did, the subtotal below would be $0.00.)
> 
> <img alt="image" width="993" src="https://private-user-images.githubusercontent.com/7232674/320199973-456cdbac-2a32-4e0d-b677-661637bffe90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MTQ5ODIsIm5iZiI6MTcxMjYxNDY4MiwicGF0aCI6Ii83MjMyNjc0LzMyMDE5OTk3My00NTZjZGJhYy0yYTMyLTRlMGQtYjY3Ny02NjE2MzdiZmZlOTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDhUMjIxODAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzlhZjI4OGY1NGZhNmE3N2M5MGY0YWQ0ODkzNTgwZmY5YWU4MTFmNmRkYTFiNWQ3OTcyZWE0MmM1MjkwOGY5ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Q770jnsbHKRlwnmPKfYdjzUZXxmBk0wc_IneJcdyI70">
> It's the same deal with Bedrock as well (Claude 3 costs real money, can't use AWS credits).

Thanks for this. Was wondering.

**Comment by ghost** [comment]
Live here - https://docs.litellm.ai/docs/providers/vertex#anthropic
