### ISSUE TITLE
[Optimize LiteLLM] - Remove Redundant Client Initalization in completion calls 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#266]
What's the problem? (if there are multiple - list as bullet points)

see:https://github.com/minimaxir/simpleaichat/pull/74

>  Your implementations for pinging the API and ETLing the I/O are inefficient and would result in a slowdown for simpleaichat.

* For Anthropic, TogetherAI, Aleph Alpha we always initalize a client and follow that with a completion call. [TODO Action: Remove the need to initialize the Client before every completion call]. If we do 100 completion calls we would have initialize the client 100 times
```
 together_ai_client = TogetherAILLM(encoding=encoding, api_key=together_ai_key, logging_obj=logging)
            model_response = together_ai_client.completion(
                model=model,
                messages=messages,
                model_response=model_response,
                print_verbose=print_verbose,
                optional_params=optional_params,
                litellm_params=litellm_params,
                logger_fn=logger_fn,
            )

```

**Comment by ishaan-jaff** [comment]
we should just directly call together_ai.completion()

**Comment by ishaan-jaff** [comment]
- [x] Anthropic
- [x] Together AI 
- [x] AI21LLM
- [x] AlephAlphaLLM
- [x] HuggingfaceRestAPILLM
- [x] BasetenLLM

**Comment by ghost** [comment]
Are we doing anything fancy in here besides just instantiating class variables? Is this what's adding latency? 


The logging object is initialized for each completion call - making it thread safe and logging information specific to that call (e.g. model name details), so just make sure we maintain that.
