### ISSUE TITLE
[Bug]: Router.chat.completions calls litellm.completions

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#2676]
### What happened?

Router.chat.completions calls litellm.completions.

Should call router.completions 

Impacts json instructor usage 

### Twitter / LinkedIn details

cc: @JungeAlexander

https://www.linkedin.com/in/alexanderjunge/

**Comment by ghost** [comment]
fixed - https://github.com/BerriAI/litellm/commit/f98aead60246f23c033f2c806cb2878976201753

should be live soon in v`1.34.1`
