### ISSUE TITLE
[Feature]: mysql database support

### ISSUE THREAD

**Issue by dl942702882** [BerriAI/litellm#2679]
### The Feature

can you guys support mysql database;
cause in china, we offen use mysql  as the first choice for rdms, not postgres;

### Motivation, pitch

can you guys support mysql database;
cause in china, we offen use mysql  as the first choice for rdms, not postgres;

### Twitter / LinkedIn details

https://twitter.com/Ting788066

**Comment by ghost** [comment]
hi @dl942702882 we've explored other db's and found it hard to maintain support for multiple schemas. Closing as this is not something we plan to do right now. 

Curious - how're you trying to use litellm? @dl942702882

**Comment by dl942702882** [comment]
> hi @dl942702882 we've explored other db's and found it hard to maintain support for multiple schemas. Closing as this is not something we plan to do right now.
> 
> Curious - how're you trying to use litellm? @dl942702882


postgres is not the best choice for chinese engineer, we often use mysql as the first choice for RDBMS

i need a database cause i am trying to start  litellm web/ui to manage all stuffs.

**Comment by wuchenhu98** [comment]
Does litellm support mysql now?
