### ISSUE TITLE
Add new models to the model cost map

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#268]
**Describe the solution you'd like**
Add ai21, codellama, wizardcoder, aleph alpha to this

https://github.com/BerriAI/litellm/blob/main/cookbook/community-resources/max_tokens.json

**Comment by ishaan-jaff** [comment]
the file is moved here:
https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json 

it's a great first issue for someone new

**Comment by ghost** [comment]
this is done
