### ISSUE TITLE
[Feature]: litellm proxy for aws bedrock authentication using AWS SDK default credential chain

### ISSUE THREAD

**Issue by jacobnguyenn** [BerriAI/litellm#2682]
### The Feature

As the title suggest, i think it would be beneficial to use aws credential provider chain for litellm proxy instead of access and secret key. Wdyt?

### Motivation, pitch

We're currently running litellm in Kubernetes on EKS, using IAM Role for Service Account would be superior to using access and secret key.

**Comment by phuongdnguyen** [comment]
Closing since it seems to be problem with helm chart, not how litellm authenticate with aws

**Comment by ghost** [comment]
Hey @jacobnguyenn was this on our helm chart?
