### ISSUE TITLE
[Bug]: Async completion ignores provider argument

### ISSUE THREAD

**Issue by JohnnyRacer** [BerriAI/litellm#2688]
### What happened?

Hello, I noticed that using the async `acompletion` instead of the regular `completion` always throws an error that I need to include the provider when I specify a custom model/endpoint (OpenAI compatible endpoint) . However the endpoint I am using does not support appending the provider `openai/` to the model name. And `litellm` does not seem to strip the provider from the actual model name, so it results in a model not found error when I call the endpoint. Using `completion`  I can use the `custom_llm_provider` argument to specify the provider manually which avoids this error as I do not have to append the provider to the front of the model name. However, this argument does not work with `acompletion`.

**Comment by ghost** [comment]
can you share a script for repro? 

acompletion calls completion, which handles this.

**Comment by JohnnyRacer** [comment]
@krrishdholakia 

This works, from [this example](https://docs.litellm.ai/docs/providers/custom_openai_proxy)
```python
import os
from litellm import completion

## set ENV variables
os.environ["OPENAI_API_KEY"] = "anything" #key is not used for proxy

response = completion(
    model="command-nightly", # Just used as an example
    messages=[{ "content": "Hello, how are you?","role": "user"}],
    api_base="https://openai-proxy.berriai.repl.co", # Just used as an example
   custom_llm_provider="openai")

```
This doesn't work:
```python
import os
from litellm import acompletion
import asyncio

loop = asyncio.get_event_loop()

## set ENV variables
os.environ["OPENAI_API_KEY"] = "anything" #key is not used for proxy

response = loop.run_until_complete(acompletion(
    model="command-nightly", # Just used as an example
    messages=[{ "content": "Hello, how are you?","role": "user"}],
    api_base="https://openai-proxy.berriai.repl.co", # Just used as an example
    custom_llm_provider="openai"))
```

**Comment by ghost** [comment]
fixed - https://github.com/BerriAI/litellm/commit/9b7383ac67269841c9e4c27e7144eb9a56c79029

should be out in v`1.34.7`

**Comment by JohnnyRacer** [comment]
@krrishdholakia  I installed from the `master` branch from the GitHub repo and this error still exists, on version `1.34.7`.

**Comment by ghost** [comment]
hey @JohnnyRacer, confused - v`1.34.7` isn't out yet? 

Re: error - this is part of ci/cd now, and i can confirm it passed local testing. 

The issue being caused is that the actual error was being swallowed by the async error. We now raise the right error. 

What is the trace you're seeing now?

**Comment by JohnnyRacer** [comment]
@krrishdholakia I installed using `pip install -U git+https://github.com/BerriAI/litellm` from the `master` branch. When I run `pip show litellm` it returns the following, which shows the version is `1.34.7` :
```
Name: litellm
Version: 1.34.7
Summary: Library to easily interface with LLM API providers
Home-page: 
Author: BerriAI
Author-email: 
License: MIT
Location: /usr/local/lib/python3.10/site-packages
Requires: aiohttp, click, importlib-metadata, jinja2, openai, python-dotenv, requests, tiktoken, tokenizers
Required-by: 
```
Using the `asyncio` snippet provided earlier gives the following following error (same error encountered before the commit you mentioned):
```
Provider List: https://docs.litellm.ai/docs/providers

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/site-packages/litellm/utils.py", line 3268, in wrapper_async
    raise e
  File "/usr/local/lib/python3.10/site-packages/litellm/utils.py", line 3100, in wrapper_async
    result = await original_function(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/litellm/main.py", line 273, in acompletion
    _, custom_llm_provider, _, _ = get_llm_provider(
  File "/usr/local/lib/python3.10/site-packages/litellm/utils.py", line 5623, in get_llm_provider
    raise e
  File "/usr/local/lib/python3.10/site-packages/litellm/utils.py", line 5610, in get_llm_provider
    raise litellm.exceptions.BadRequestError(  # type: ignore
litellm.exceptions.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=command-nightly
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers
```

**Comment by JohnnyRacer** [comment]
@krrishdholakia Any idea when or if this would still be looked into? I just tried on version `1.34.13` and it is still the same problem with `acompletion`.

**Comment by JohnnyRacer** [comment]
@krrishdholakia I fixed the issue and created a PR for it [here](https://github.com/BerriAI/litellm/pull/2758) .

**Comment by FAbrahamDev** [comment]
Until the pr is done. It seems to be the case that you can just write {custom_llm_provider}/{model} in the model field.
