### ISSUE TITLE
Hugging face Bug - The following `model_kwargs` are not used by the model: ['details']

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#269]
What's the problem? (if there are multiple - list as bullet points)
LLM calls fail when using random HF LLMs like "stabilityai/stablecode-completion-alpha-3b-4k"  looks like there's a param called 'details' inserted into optional params that's leading to failures: 

cc @krrishdholakia any idea what models use `details` param ?

**Comment by ghost** [comment]
yes - to return log probs. It's a guaranteed input for text gen interface. https://huggingface.github.io/text-generation-inference/#/Text%20Generation%20Inference/compat_generate.

**Comment by Aelerinya** [comment]
The `details` parameter does not seem to exist anymore in the huggingface API https://huggingface.co/docs/api-inference/detailed_parameters#text-generation-task

I'm getting the following error when running LiteLLM on huggingface models:
```
There was an inference error: The following `model_kwargs` are not used by the model: ['details']
```
