### ISSUE TITLE
Add support for HF Embedding Models [Specifically Hf Leaderboard LLMs]

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#270]
**Describe the solution you'd like**
see this issue:https://github.com/StanGirard/quivr/issues/1104

> Currently, a lot of embedding models listed on the [HuggingFace leaderboard](https://huggingface.co/spaces/mteb/leaderboard) are not supported, and integrating them to work with the desired Large Language Model (LLM) is necessary.

> The [litellm repository](https://github.com/BerriAI/litellm/) does not appear to support embeddings yet, indicating a potential area for enhancement

**Comment by ghost** [comment]
<img width="945" alt="Screenshot 2023-09-04 at 5 51 50 PM" src="https://github.com/BerriAI/litellm/assets/17561003/1617453f-79ee-4839-bb67-e03b1785c71e">

**Comment by ishaan-jaff** [comment]
interesting - what is this screenshot ?
