### ISSUE TITLE
[Feature]: Ability to set a ttl for each redis object type (tpm/rpm, cache...)

### ISSUE THREAD

**Issue by olad32** [BerriAI/litellm#2700]
### The Feature

Ability to set a ttl for each redis object type (tpm/rpm, cache...). 
Idealy each redis object type, i mean tpm/rpm and message cache, must have it's own ttl value. 

### Motivation, pitch

Currently there is no ttl set, so redis size will keep growing. This is particularly useless for tpm/rpm to keep old record.

**Comment by ghost** [comment]
Hey @olad32 do you mean per request? 

This is possible today - https://docs.litellm.ai/docs/proxy/caching#turn-on--off-caching-per-request

Is this what you wanted?

**Comment by ghost** [comment]
Hey @olad32 you can also set ttl now for the message cache - https://docs.litellm.ai/docs/proxy/caching#ttl

**Comment by olad32** [comment]
Hello @krrishdholakia, I want to be able to set a global ttl (and also namespace) for all tpm/rpm redis records

**Comment by olad32** [comment]
Hello @krrishdholakia, I want to be able to set a global ttl (and also namespace) for all tpm/rpm redis record, and independently from message cache redis record.

**Comment by ghost** [comment]
Fixed with - https://github.com/BerriAI/litellm/pull/2789
