### ISSUE TITLE
[Feature]: Support for sending files

### ISSUE THREAD

**Issue by aandis** [BerriAI/litellm#2708]
### The Feature

[OpenAI api](https://platform.openai.com/docs/api-reference/files) supports sending files via the API and so does [claude](https://support.anthropic.com/en/articles/8241126-what-kinds-of-documents-can-i-upload-to-claude). Does litellm have plans to support completion with sending file attachments in the prompt?

### Motivation, pitch

I am working with pdf/doc files wherein the AI is expected to make edits and return the edited documents based on the prompt passed. Having support for files for text completion will greatly simplify this use case.

**Comment by ghost** [comment]
hey @aandis how do you do that on claude? 

i don't see it on their api docs - https://docs.anthropic.com/claude/reference/messages_post

if you can also share mock code for how you expect this to work, that'd be great

**Comment by ishaan-jaff** [comment]
@aandis we support file creation now. Curious do you use the litellm python SDK today ? 

doc here: https://docs.litellm.ai/docs/batches

```python
from litellm
import os 

os.environ["OPENAI_API_KEY"] = "sk-.."

file_name = "openai_batch_completions.jsonl"
_current_dir = os.path.dirname(os.path.abspath(__file__))
file_path = os.path.join(_current_dir, file_name)
file_obj = await litellm.acreate_file(
    file=open(file_path, "rb"),
    purpose="batch",
    custom_llm_provider="openai",
)
print("Response from creating file=", file_obj)
```
