### ISSUE TITLE
Add support for OpenAI Timeout + API Errors 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#271]
**Describe the solution you'd like**
Add support for OpenAI Timeout + API Errors 

<img width="745" alt="Screenshot 2023-09-04 at 6 53 59 PM" src="https://github.com/BerriAI/litellm/assets/17561003/c9b1c10b-ef78-4750-a49e-20f169091223">

**Comment by ghost** [comment]
https://github.dev/neulab/prompt2model/blob/ce8ba9fb63846edab8aa534a4d508d0c0a191607/prompt2model/utils/openai_tools.py#L57

**Comment by KanishkaHalder1771** [comment]
Hey @krrishdholakia ,
I would like to take up this issue if no one is working on it.
thx

**Comment by ghost** [comment]
hey @KanishkaHalder1771 missed this sorry,  this is now implemented but there's a few other issues that we'd really appreciate help on: 

- https://github.com/BerriAI/litellm/issues/328
- https://github.com/BerriAI/litellm/issues/322
- https://github.com/BerriAI/litellm/issues/311
- https://github.com/BerriAI/litellm/issues/319
