### ISSUE TITLE
[Bug]: Persist Alerts

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#2727]
### What happened?

User got spammed on every call b/c their proxy budget had 15% left. 

Need to persist the alert, to prevent this sort of spam. 

User described ideal solution as: 

"Instead, it would make more sense for this to be emitted once per month, once the threshold below 15% is reached"

**Comment by ghost** [comment]
## Thinking 

Can use either db or cache. 

I prefer cache as it's faster and will avoid us re-entering the prisma client problem we're currently fixing. 

Can just store in cache for 30d, once the alert is triggered.

**Comment by ghost** [comment]
Pushed in-memory cache fix. Didn't fix user problem. Need to investigate further. 

- Could try caching via redis.

**Comment by ghost** [comment]
Live in v`1.34.20`
