### ISSUE TITLE
Pick prompt template based on exact match to hf model path

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#273]
What's the problem? (if there are multiple - list as bullet points)
Our current implementation does a partial match. This can lead to errors as there might be variants of the same model (e.g. a finetuned bloke version) which might have similar names but require a different prompt template. 

Move this to be an exact match instead. 
<img width="550" alt="Screenshot 2023-09-05 at 7 24 50 AM" src="https://github.com/BerriAI/litellm/assets/17561003/d4680d71-337e-4344-bfee-5fbc5275533f">

**Comment by ghost** [comment]
this is now fixed.
