### ISSUE TITLE
[Feature]: Terraform Provider for litellm

### ISSUE THREAD

**Issue by ncecere** [BerriAI/litellm#2733]
### The Feature

The creation of a Terraform provider for managing litellm users, models, etc.

### Motivation, pitch

this would allow use to treat models in litellm the same way we treat all other infrastructure that we manage in public clouds.  having a terraform provider would make interactions with litellm feel like working with a platform and any other cloud provider

**Comment by ghost** [comment]
hey @ncecere what does a terraform provider for models mean? 

Do you have any docs i can look at for this? 

Happy to talk through this on call - https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by ghost** [comment]
bump on this? @ncecere

**Comment by Manouchehri** [comment]
@ncecere Could you give an example Terraform config that you wish LiteLLM supported?

My team has created Terraform providers before, but I'm not sure if I see the need for a LiteLLM one.

**Comment by ncecere** [comment]
What I would like if there was a terraform provider created for LiteLLM so that management could be handled that way.  once, I have created a module using another provider that looks like the below.

```hcl
module "llama2_70b" {
  source = "./modules_2/models"

  url   = "https://litellm.endpoint.io"
  token = "sk-1234"

  model_name            = "llama2-70b"
  input_cost_per_token  = 0.0000015
  output_cost_per_token = 0.000002
  max_tokens            = 4096
  params = {
    model                 = "openai/meta-llama/Llama-2-70b-chat-hf"
    api_base              = "http://vllm.instance.web/v1/"
    input_cost_per_token  = 0.0000015
    output_cost_per_token = 0.000002
  }

}
```

**Comment by ncecere** [comment]
with a proper terraform provider you would add models with something like the below

```hcl
resource "litellm_model" "llama2" {
    model_name     = var.model_name
    litellm_params {
        item = value
        item = value
    }
    model_info {
      id                    = "llama2"
      input_cost_per_token  = 0.002
      output_cost_per_token = 0.0002
      max_tokens            = 4096
    }
}
```

**Comment by ishaan-jaff** [comment]
@ncecere any chance you can make a PR to LiteLLM Docs to point to your terraform module? We've had other users ask for this

**Comment by ghost** [comment]
Added here - https://docs.litellm.ai/docs/proxy/deploy#quick-start

thanks for the module @ncecere 
https://github.com/ncecere/terraform-litellm-user-mgmt
