### ISSUE TITLE
Enable support for custom endpoints 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#274]
**Describe the solution you'd like**
This is different from a hf tgi endpoint or openai api base replacement as the input formats can differ. 

https://github.com/autoai-org/GMService/pull/2

<img width="943" alt="Screenshot 2023-09-05 at 7 48 47 AM" src="https://github.com/BerriAI/litellm/assets/17561003/9710d9e4-a668-40d0-9f26-ca4afd8b780c">

**Comment by ishaan-jaff** [comment]
done https://docs.litellm.ai/docs/providers/custom

**Comment by ishaan-jaff** [comment]
notebook with working code:
https://colab.research.google.com/drive/1-LBTmUnGsOjIeZF6XvXf0ud1vwnDLya-?usp=sharing

**Comment by ishaan-jaff** [comment]
done thanks for the request: @xzyaoi
