### ISSUE TITLE
[Feature]: Support for LLama Aws bedrock tool calls in litellm proxy

### ISSUE THREAD

**Issue by vignesh-arivazhagan** [BerriAI/litellm#2744]
### The Feature

we are about to use litellm proxy, but can't able to do function calling
![image](https://github.com/BerriAI/litellm/assets/133187870/d1eec3cc-5360-46a3-a08a-eab3272c73bc)

Start litellm proxy server
```bash
litellm --model bedrock/meta.llama2-70b-chat-v1
```

```python
import os

os.environ["AWS_ACCESS_KEY_ID"] = "<your_access_key_id>"
os.environ["AWS_SECRET_ACCESS_KEY"] = "<your_secret_access_key>"
os.environ["AWS_REGION_NAME"] = "<your_aws_region_name>"

tools = [
        {
            "type": "function",
            "function": {
                "name": "get_current_weather",
                "description": "Get the current weather in a given location",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "location": {
                            "type": "string",
                            "description": "The city and state, e.g. San Francisco, CA",
                        },
                        "unit": {"type": "string", "enum": ["celsius", "fahrenheit"]},
                    },
                    "required": ["location"],
                },
            },
        }
    ]

response = completion(
  model="bedrock/meta.llama2-70b-chat-v1",
  messages=[{ "content": "how was the weather in San Francisco","role": "user"}],
  tools=tools
)
```

### Motivation, pitch

Function calling is a common feature in all agent like applications

**Comment by ghost** [comment]
@vignesh-arivazhagan does llama bedrock support tool calling? 

Any docs here would be great

**Comment by ghost** [comment]
don't see it here - https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-meta.html

**Comment by vignesh-arivazhagan** [comment]
@krrishdholakia , I think llama bedrock won't support tool calling,[ but llama with ollama supports function calling](https://github.com/marklysze/AutoGenCodeTesting/tree/master/function_calling), so it's not about the model, it is about the provider in some cases who prompt engineers to support tool calling to maintain standard openai output structure , I see [litellm also changes the system prompt to support tool calling for anthropic](https://github.com/BerriAI/litellm/blob/97616ee2679fc67b6b7643f3eb6e1fe3113dd221/litellm/llms/prompt_templates/factory.py#L461), it would be very helpful for us if litellm supports tool calling for bedrock llama

**Comment by ghost** [comment]
Hey @vignesh-arivazhagan 

- re: ollama, the provider has a json mode, which guarantees response is json

- re: anthropic: the anthropic translation is based on their own guide for it - https://github.com/anthropics/anthropic-cookbook/blob/main/function_calling/function_calling.ipynb, and it seems to work consistently. 

The bedrock function call w/ llama doesn't guarantee back a json response

Putting this as not planned for now, but please bump me if you see a good way either we can natively support it or a way to let you set this.
