### ISSUE TITLE
Set types of input params to completion()

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#275]
What's the problem? (if there are multiple - list as bullet points)

got this error when trying to assign a float to temperature using litellm completion 

we need to set types of input params in completion 

<img width="630" alt="Screenshot 2023-09-05 at 7 57 44 AM" src="https://github.com/BerriAI/litellm/assets/29436595/a0bc190d-c978-4ff0-9d3b-8145b5662d59">

**Comment by ghost** [comment]
The error looks like the type is being set
<img width="301" alt="Screenshot 2023-09-05 at 9 23 12 AM" src="https://github.com/BerriAI/litellm/assets/17561003/ffab674a-b27c-4a95-9f60-f167b8a8acda">

am i misreading this?

**Comment by ishaan-jaff** [comment]
it's saying argument of type float is being assigned to a param of type int

-> this implies that our temperature is of type int (which is incorrect)

**Comment by ishaan-jaff** [comment]
done
