### ISSUE TITLE
[Bug]: `bedrock/mistral.mixtral-8x7b-instruct-v0:1` is not present in `litellm.model_cost`

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#2753]
### What happened?

Request to litellm:
litellm.completion(model='bedrock/mistral.mixtral-8x7b-instruct-v0:1', messages=[{'role': 'user', 'content': 'Are you here? Answer "Yes."'}], max_tokens=3, stream=True)

### Twitter / LinkedIn details

cc: @GlavitsBalazs

**Comment by ghost** [comment]
fixed - https://github.com/BerriAI/litellm/commit/89471ba4c5c8746c292cdc107c43badbd326fafd
