### ISSUE TITLE
[Bug]: Cannot update duration of existing key

### ISSUE THREAD

**Issue by tylerbrandt** [BerriAI/litellm#2764]
### What happened?

I was trying to update the duration of a key, which should be allowed per the OpenAPI spec:
```
POST /key/update
{
  "duration": "30d",
  "key": "sk-..."
}
```
but I got this error:
```
{
	"error": {
		"message": "Authentication Error, Could not find field at `updateOneLiteLLM_VerificationToken.data.duration`",
		"type": "auth_error",
		"param": "None",
		"code": 400
	}
}
```

**Comment by ghost** [comment]
hmm that's weird. can you see if this persists when you run `prisma generate` in your cli ?

It looks like the generated prisma client can't tell duration is a field

**Comment by ghost** [comment]
testing on my end as well

**Comment by ghost** [comment]
able to repro

**Comment by ghost** [comment]
oh - i get it. we use duration to figure out when the key should expire. e,.g. 1hr duration on create would set expire to be 1hr from now -> the relevant field being `expire`. 

this translation is missing on `/key/update` for duration

**Comment by ghost** [comment]
working on a fix now @tylerbrandt

**Comment by ghost** [comment]
fix pushed @tylerbrandt https://github.com/BerriAI/litellm/commit/af2eabba91cdedb90df850704f170e4cd19cd383

Also updated our `/key/update` unit test to cover this as well

Can confirm it works
<img width="976" alt="Screenshot 2024-03-29 at 9 47 47 PM" src="https://github.com/BerriAI/litellm/assets/17561003/2a72c877-80d5-4ead-8299-3c133e0ef217">

**Comment by ghost** [comment]
should be live soon in v`1.34.16`.

**Comment by tylerbrandt** [comment]
Great, thanks!
