### ISSUE TITLE
Setting litellm.api_key also sets api base for openai 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#277]
What's the problem? (if there are multiple - list as bullet points)
When setting the litellm api key 
`litellm.api_key = ""`

it also sets the openai api base to the api key

**Comment by ishaan-jaff** [comment]
thanks for catching:

i was able to repro this. Also got this error 

```

    raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: Invalid URL 'sk-*************/chat/completions': No scheme supplied. Perhaps you meant https://sk-**********/chat/completions?
```

**Comment by ishaan-jaff** [comment]
this commit fixes it: https://github.com/BerriAI/litellm/commit/8f5e2d001328bb210cbfa251d81a1083e029ea97

**Comment by ishaan-jaff** [comment]
you can see I added a test in the commit for this condition too 

marking as done now @krrishdholakia
