### ISSUE TITLE
[Bug]: Langchain and vertex text models proxy issue

### ISSUE THREAD

**Issue by eslamkarim** [BerriAI/litellm#2777]
### What happened?

When trying to specify a langchain client (AzureOpenAI, OpenAI) it fails with an error message `VertexAIException - 400 The text content is empty.`
to reproduce use a text-bison model with the below code snippet
```python
from langchain_openai import AzureOpenAI, OpenAI

azurellm = AzureOpenAI(
    azure_deployment="text-bison",
    api_key="sk-eh0S**************2Kry",
    azure_endpoint="http://localhost:4000",
    api_version="2024-02-01"
)
openaillm = OpenAI(
    model="text-bison",
    api_key="sk-eh0S5X********************y",
    base_url="http://localhost:4000",
)
print(azurellm.invoke("how are you?"))
print(openaillm.invoke("how are you?"))
```
i raised a pr #2776  after debugging the issue which i think it's related to how langchain sends prompts (as a list) and the code in the pr only accepts text so we either do this here or when we generate the messages for litellm client as always feel free to decide which is the best approach i believe there is something deeper to fix maybe.

**Comment by ghost** [comment]
Addressed - https://github.com/BerriAI/litellm/commit/0d949d71ab6f54f74ddf243f692ed9667b0db324

Should be out soon in v`1.34.21`.
