### ISSUE TITLE
documentation about replicate is not correct

### ISSUE THREAD

**Issue by yujonglee** [BerriAI/litellm#279]
**Describe the solution you'd like**

https://docs.litellm.ai/docs/providers/replicate#replicate-models

<img width="947" alt="Screenshot 2023-09-06 at 8 07 31 PM" src="https://github.com/BerriAI/litellm/assets/61503739/3136ce30-94ee-48bc-9090-a82b60e9d2ae">

We need version info.

**Comment by ishaan-jaff** [comment]
updated here: https://docs.litellm.ai/docs/providers/replicate#replicate-models
