### ISSUE TITLE
[Bug]: text completion returning incomplete response

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#2796]
### What happened?

When using a fine-tuned model, it looks like it's not returning logprobs properly, unless I have the config set up incorrectly.

Hitting openai directly - https://gist.github.com/TranquilMarmot/b5a40ffd8dc0ba96c53f9e88102db3c1

Hitting litellm - https://gist.github.com/TranquilMarmot/fc651cd3ab075d63376af10465bcd1be

### Twitter / LinkedIn details

cc: @TranquilMarmot

**Comment by ghost** [comment]
Seems we need to:
- return all choices 
- return the logprobs

**Comment by ghost** [comment]
fixed - text completion now returns logprobs in v`1.34.22`.
