### ISSUE TITLE
DeprecationWarning in prompt template

### ISSUE THREAD

**Issue by yujonglee** [BerriAI/litellm#280]
**Describe the solution you'd like**

<img width="1407" alt="Screenshot 2023-09-06 at 6 20 20 PM" src="https://github.com/BerriAI/litellm/assets/61503739/1eab08fb-2e17-46a9-bfff-20fc2ba2e1f1">

**Comment by ghost** [comment]
Based on the line number i'm guessing this is the togethercomputer/llama2 model? @yujonglee

**Comment by ghost** [comment]
This should be fixed now as we're using the same llama2 prompt format across meta-llama and togethercomputer (together ai also uses the same format as the original llama2 model). Please re-open if this isn't solved. 

I don't see this error in local testing. 
<img width="1325" alt="Screenshot 2023-09-06 at 1 21 13 PM" src="https://github.com/BerriAI/litellm/assets/17561003/3e0e7702-6c9d-4a70-a06e-2156534a842a">
