### ISSUE TITLE
[feature request/discussion] LLM-independent token counter/prompt analizer

### ISSUE THREAD

**Issue by solyarisoftware** [BerriAI/litellm#281]
Hi all, 
just a thought. Maybe related to closed issue https://github.com/BerriAI/litellm/issues/52

One possible general interesting lite LLM method could be having a token counter, to be called before the completion.
> The reason is to make some preemptive calculations on the context window length, avoiding run-time completion error for max_tokens, etc.

Using Openai API one could use tiktoken. For other models I have no experience. 

Nevertheless I'm perplexed using tiktoken, e.g. the tiktoken reports the exact count of tokens for `text-davinci-003` reported by the online tokenizer: https://platform.openai.com/tokenizer, but i got a different count if I submit a text completion using `gpt-3-5-turbo`, injecting the prompt in as system role. That's weird.

Anyway, in general, it could be useful to foresee a LLM independent token counter (maybe along with simple standard text attributes analyzer, as number of characters, words, lines, etc.
 
 Just an idea.
  
```python
import tiktoken

def num_tokens(text: str, model_name: str) -> int:
    ''' Returns the number of tokens in a text string.
        https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb
    '''
    encoding = tiktoken.encoding_for_model(model_name)
    num_tokens = len(encoding.encode(text))
    return num_tokens


if __name__ == "__main__":
    ''' unit test '''

    prompt = 'La città soprannominata "la superba", in una parola, è'
    print(f'prompt: {prompt}')

    model_name = 'gpt-3.5-turbo'
    print(f'model: {model_name} => tokens: {num_tokens(prompt, model_name)}')

    model_name = 'text-davinci-003'
    print(f'model: {model_name} => tokens: {num_tokens(prompt, model_name)}')

```
```
$ py openai_tiktoken.py
prompt: La città soprannominata "la superba", in una parola, è
model: gpt-3.5-turbo => tokens: 17
model: text-davinci-003 => tokens: 23
```

**Comment by yujonglee** [comment]
@solyarisoftware 
`gpt-3.5-turbo` and `text-davinci-003` use different tokenizer. 

https://platform.openai.com/tokenizer
This does not use tokenizer that `gpt-3.5-turbo` use.

https://tiktokenizer.vercel.app
This playground can help you.

**Comment by yujonglee** [comment]
> One possible general interesting lite LLM method could be having a token counter, to be called before the completion.

And I think litellm already has token counter.
https://docs.litellm.ai/docs/token_usage

**Comment by solyarisoftware** [comment]
I apologize, it slipped my mind. Thank you

**Comment by ishaan-jaff** [comment]
@solyarisoftware marking this as resolved - feel free to reopen if there's something we should add
