### ISSUE TITLE
[Bug]: MacOS: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by nicovank** [BerriAI/litellm#2818]
### What happened?

Seems to be MacOS only, does not reproduce on my Ubuntu setup.

```
% python3 --version
Python 3.12.2

% python3 -m venv env
% source env/bin/activate

# pip install git+https://github.com/BerriAI/litellm.git
% python3 -m pip install litellm

% python3 -c "import litellm"
```

Reproduces on latest release and master.

### Relevant log output

```shell
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/nvankempen/env/lib/python3.12/site-packages/litellm/__init__.py", line 564, in <module>
    from .utils import (
  File "/Users/nvankempen/env/lib/python3.12/site-packages/litellm/utils.py", line 62, in <module>
    from .integrations.lunary import LunaryLogger
  File "/Users/nvankempen/env/lib/python3.12/site-packages/litellm/integrations/lunary.py", line 7, in <module>
    from pkg_resources import parse_version
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by nicovank** [comment]
Bisect points to d4d160353ed1a9fa8677ed7f1ff93d5fa1c982dc, @vincelwt.

**Comment by ghost** [comment]
moved to inside the lunary class - https://github.com/BerriAI/litellm/commit/24d9fcb32cafdc1e79adab97f5db73c09bb5540b

Should be live in next release @nicovank 

@vincelwt feel free to replace pkg_metadata with whatever else might be more appropriate, when you get the chance.

**Comment by raisindetre** [comment]
Tested install on OSX against commit `aa8ec875` (Apr 3 18:37:00 2024) v1.34.23-stable committed 2 hours ago and still producing same error.

**Comment by ghost** [comment]
@raisindetre can you share the stacktrace?

**Comment by ryanlee588** [comment]
I got the same error message. Installing `setuptools` using pip3/pip within the virtual environment seemed to resolve it.

**Comment by raisindetre** [comment]
Exactly the same trace as originally reported:
`Traceback (most recent call last):
  File "/Users/mjb/Documents/Projects/litellm/venv/bin/litellm", line 5, in <module>
    from litellm import run_server
  File "/Users/mjb/Documents/Projects/litellm/venv/lib/python3.12/site-packages/litellm/__init__.py", line 564, in <module>
    from .utils import (
  File "/Users/mjb/Documents/Projects/litellm/venv/lib/python3.12/site-packages/litellm/utils.py", line 62, in <module>
    from .integrations.lunary import LunaryLogger
  File "/Users/mjb/Documents/Projects/litellm/venv/lib/python3.12/site-packages/litellm/integrations/lunary.py", line 7, in <module>
    from pkg_resources import parse_version
ModuleNotFoundError: No module named 'pkg_resources'`

Confirming that `pip install setuptools` also resolved the issue for me.

**Comment by nicovank** [comment]
I'll look into it when I get back to my Mac later today. `pkg_resources` is deprecated so moving away from it is probably the best way to go. I saw another integration uses the `packaging` package which should do the trick.

https://github.com/BerriAI/litellm/blob/dd14b8cbaa7f9bbcff572901532a98a4d09aedbd/litellm/integrations/langfuse.py#L8

**Comment by ghost** [comment]
Hey @raisindetre that error looks like it's from an older version 

> "/Users/mjb/Documents/Projects/litellm/venv/lib/python3.12/site-packages/litellm/integrations/lunary.py", line 7


The import should be moved inside the lunary class to prevent it being raised by default - 
https://github.com/BerriAI/litellm/blob/674499b41a3953b0e7b0148ce8f1246ec7805054/litellm/integrations/lunary.py#L59

Can you update to the latest litellm and see if this persists?

**Comment by ghost** [comment]
@nicovank nice - i think the langfuse approach is a good solution. Will test it on my end and revert back

**Comment by ghost** [comment]
Merged PR @nicovank

**Comment by nscipione-sumer** [comment]
I'm still seeing this issue pop up when I install LiteLLM with `uv`?
