### ISSUE TITLE
[Bug]: async callback function trigger in completion stream call

### ISSUE THREAD

**Issue by wenzhe-log10** [BerriAI/litellm#2819]
### What happened?

Seems the async functions in the custom callback are called for sync completion + stream calls. 

repro code:
```
import litellm
from litellm.integrations.custom_logger import CustomLogger

class MyCustomHandler(CustomLogger):
    def log_pre_api_call(self, model, messages, kwargs): 
        print("Pre-API Call")
    
    def log_post_api_call(self, kwargs, response_obj, start_time, end_time): 
        pass
    
    def log_stream_event(self, kwargs, response_obj, start_time, end_time):
        print("On Stream")
        
    def log_success_event(self, kwargs, response_obj, start_time, end_time): 
        print("On Success")

    def log_failure_event(self, kwargs, response_obj, start_time, end_time): 
        print("On Failure")

    async def async_log_stream_event(self, kwargs, response_obj, start_time, end_time):
        print("Async On Stream")

    async def async_log_success_event(self, kwargs, response_obj, start_time, end_time):
        print("Async On Success")
    

customHandler = MyCustomHandler()

litellm.callbacks = [customHandler]


response = litellm.completion(
    model="gpt-3.5-turbo", messages=[{"role": "user", "content": "Count to 10."}], stream=True
)
for chunk in response:
    if chunk.choices[0].delta.content:
        print(chunk.choices[0].delta.content, end="", flush=True)
```

output from running the code, it shows both `Async On Success` and `On Success`. Expect to only see `On Success`
```
Pre-API Call
1,Async On Stream
Async On Stream
On Stream
On Stream
 Async On Stream
Async On Stream
2On Stream
On Stream
, Async On Stream
Async On Stream
On Stream
On Stream
3Async On Stream
,Async On Stream
On Stream
On Stream
 4Async On Stream
Async On Stream
On Stream
On Stream
,Async On Stream
 Async On Stream
On Stream
On Stream
5,Async On Stream
Async On Stream
On Stream
On Stream
 6Async On Stream
Async On Stream
On Stream
On Stream
, Async On Stream
Async On Stream
On Stream
On Stream
7Async On Stream
,Async On Stream
On Stream
On Stream
 8Async On Stream
Async On Stream
On Stream
On Stream
,Async On Stream
 Async On Stream
On Stream
On Stream
9,Async On Stream
Async On Stream
On Stream
On Stream
 Async On Stream
10Async On Stream
On Stream
On Stream
Async On Success
On Success
```

**Comment by ghost** [comment]
hey @wenzhe-log10 this is intentional - for supporting callbacks e.g. async prisma db writing, which require the async callback for a sync call (e.g. bedrock boto3 calls) 


Why do you perceive this as a bug?

**Comment by wenzhe-log10** [comment]
Thanks for replying.

I got the expectation based on the example code in the [custom callback doc](https://docs.litellm.ai/docs/observability/custom_callback#callback-class)
```
    #### ASYNC #### - for acompletion/aembeddings
```
, thinking the async calls to be triggered by `acompletion` only. 

In my use case, logging the request/response, `async_log_success_event` and `log_success_event` do the same thing. So currently calling it twice is no necessary. What's your recommendation for this case?

> for supporting callbacks e.g. async prisma db writing, which require the async callback for a sync call (e.g. bedrock boto3 calls)

I wonder if this is generally applied to other models. Have you considered to add a separate async function for such cases?

**Comment by ghost** [comment]
Hey @wenzhe-log10  thinking about this a bit more - would it help if there was a param to know the original function called (if it was acompletion or completion)? 

That way you could choose to ignore logging events emitted for completion calls in the async callback

**Comment by ghost** [comment]
I believe kwargs should be returning a value called `call_type` which is one of these values:
<img width="762" alt="Screenshot 2024-04-06 at 1 36 23 PM" src="https://github.com/BerriAI/litellm/assets/17561003/7d8babb5-c3ae-456b-807c-4842e42b0555">


You should be able to do this already

**Comment by ghost** [comment]
Let me know if this solves it

**Comment by wenzhe-log10** [comment]
cool, that should work. Thank you.
