### ISSUE TITLE
Add prompt template for replicate-llama2

### ISSUE THREAD

**Issue by yujonglee** [BerriAI/litellm#283]
**Describe the solution you'd like**

https://github.com/BerriAI/litellm/blob/cc4be8dd73497b02f4a9443b12c514737a657cae/litellm/llms/prompt_templates/factory.py#L88-L117

It seems like `replicate`'s llama2 will be fall to `default`.

They have guide on their blog: https://replicate.com/blog/how-to-prompt-llama

**Comment by ghost** [comment]
Sounds good - i'll take a look at this today

**Comment by ghost** [comment]
Looks like Replicate handles this for you by default: 
<img width="1041" alt="Screenshot 2023-09-06 at 12 46 28 PM" src="https://github.com/BerriAI/litellm/assets/17561003/92c9cf67-53c9-4ae9-adaf-88a55df26c35">

**Comment by ghost** [comment]
Closing this issue based since replicate-llama2 handles prompt formatting, please re-open if that doesn't solve your issue @yujonglee
