### ISSUE TITLE
We need more flexible custom prompt template

### ISSUE THREAD

**Issue by yujonglee** [BerriAI/litellm#284]
**Describe the solution you'd like**

https://github.com/BerriAI/litellm/blob/cc4be8dd73497b02f4a9443b12c514737a657cae/litellm/utils.py#L1310-L1329
https://github.com/BerriAI/litellm/blob/cc4be8dd73497b02f4a9443b12c514737a657cae/litellm/llms/prompt_templates/factory.py#L77-L87

I think we need more flexibility - maybe it's better to accept to callback functions, but I am not very familiar with llama2 prompt formatting, so not sure what is best interface for this.

At least one thing I am sure is that we need to be able to replicate other pre-built template.
https://github.com/BerriAI/litellm/blob/cc4be8dd73497b02f4a9443b12c514737a657cae/litellm/llms/prompt_templates/factory.py#L17-L28

Currently, we can not achieve same with custom prompt.

**Comment by ghost** [comment]
Modified custom prompt: 
https://github.com/BerriAI/litellm/blob/0ace48d719597f101c06cffcaf0eb132da62e635/litellm/llms/prompt_templates/factory.py#L82

This now let's you control the entire prompt, as well as role specific content 


In addition, I'm now running the llama2 prompt from there: https://github.com/BerriAI/litellm/blob/0ace48d719597f101c06cffcaf0eb132da62e635/litellm/llms/prompt_templates/factory.py#L5

I'll move the remaining templates over to using the core function, if you can confirm this is the flexibility you were looking for @yujonglee

**Comment by ghost** [comment]
closing for now as this is now addressed. @yujonglee feel free to reopen if there's something we haven't dealt with yet.
