### ISSUE TITLE
[Feature]: Mistral large on EU Bedrock

### ISSUE THREAD

**Issue by sa-** [BerriAI/litellm#2848]
### The Feature

Add support for Mistral large from bedrock

### Motivation, pitch

Mistral Large is now now available in the paris region
https://aws.amazon.com/blogs/aws/tackle-complex-reasoning-tasks-with-mistral-large-now-available-on-amazon-bedrock/

**Comment by ghost** [comment]
Added - https://github.com/BerriAI/litellm/commit/e424a294a5dbd36e5c138778079226d02939b05d

**Comment by sa-** [comment]
Thank you!
