### ISSUE TITLE
[Feature]: Support Anthropic's latest tool use which supports JSON schema

### ISSUE THREAD

**Issue by lazyhope** [BerriAI/litellm#2853]
### The Feature

Anthropic announced the latest tool use feature: https://docs.anthropic.com/claude/docs/tool-use
We should migrate to the latest API to use JSON schema tool definition.

### Motivation, pitch

It's the first time they introduce tool definition in JSON schema format, which is much more flexible than the previous XML format (e.g. parameter type definition).

**Comment by richloh** [comment]
Great idea! That's a real advancement for action model usage
