### ISSUE TITLE
[Bug]: Verbose information is logged at info level, and with set_verbose false

### ISSUE THREAD

**Issue by enyst** [BerriAI/litellm#2872]
### What happened?

I'm looking to implement logging in a project that uses LiteLLM as a dependency via poetry. I'd love to enable at least INFO and DEBUG logging, but [this commit](https://github.com/BerriAI/litellm/commit/0d949d71ab6f54f74ddf243f692ed9667b0db324#diff-9661b0d8f1d9f48433f2323d1102e963d3098f667f7a25caea79f16fa282f6ddR864) had unexpected consequences: the litellm output now ignores when set_verbose is False, and it even ignores that the level is only INFO. The verbose_logger.info() call prints information like API keys.

Expected behavior with logging enabled:
- that liteLLM needs set_verbose=True to print all or most information sent to LLMs
- that it doesn't log API keys when level is INFO anyway, and TBH even at DEBUG.

It seems I can replicate it even when the only logging-related code in the client app is:
```logging.basicConfig(level=logging.INFO)```

The key below was not redacted. As you can see, it's at INFO.

### Relevant log output

```shell
22:08:49 - LiteLLM:INFO: utils.py:934 - Request to litellm:
22:08:49 - LiteLLM:INFO: utils.py:934 - litellm.completion(model='gpt-3.5-turbo-1106', api_key='sk-XXX', max_retries=0, messages=[{'content': '\nYou\'re a thoughtful robot. Your main task is this:\n\nprint 1\n\nDon\'t expand the scope of your task--just complete...
```

**Comment by ghost** [comment]
Seen this happen before. Tracking the solution here. We can add a check for an env variable being set. This will prevent this from happening. 

This is caused with our logging.info statements via the logging library

```python
import os
import logging

if os.getenv("LOGGING_ENABLED") == "true":
    logging.basicConfig(level=logging.INFO)
    logger = logging.getLogger("example_logger")
    logger.info("Hello, logging is enabled!")

# Other code here...

```

**Comment by ghost** [comment]
Hey @enyst looking deeper - the info flag lets us show the api request being sent by litellm on INFO instead of DEBUG which can get quite noisy
<img width="547" alt="Screenshot 2024-04-05 at 5 15 17 PM" src="https://github.com/BerriAI/litellm/assets/17561003/4abf1c24-14b7-4af9-aa88-475ad964f4b0">


The api key should be getting hidden, so only a couple characters (enough for you to know it's being loaded correctly) are shown. 

I'll add a better check here. Any specific logs causing issues here?

**Comment by enyst** [comment]
Yes, it's on INFO, but the statement contains a lot of things. It seems too many. The next line after these has a set_verbose check. Couldn't that check be applied to these lines too? Or cut them to a few details?

set_verbose = False, level = INFO => the result looks to me like debugging info. It gives the whole request and response, doesn't it. I don't know, is that necessary for liteLLM?

For context, at the moment I'm working to implement our logging system over at OpenDevin project. Because of API keys, I temporarily set liteLLM to WARNING. It's just a draft PR for now.

I'd love to tell folks "dump your logs in a gist and gimme". And even "ok we need the actual request, enable debug, try again, and send us that log".

Of course, for that we need API keys to not be there, even on DEBUG. But the INFO level is so verbose since three days ago, due to everything else.

I'm not sure what you want to display, I can tell I have hesitations to enable INFO from liteLLM by default if it has all the messages of the request, and sadly even response. It's potentially sensitive, folks will want the agent to do stuff they may or may not want public. And, it's huge, with an agent working hard it can hit limits fast!

**Comment by ghost** [comment]
Hey @enyst reverted the change based on your feedback - https://github.com/BerriAI/litellm/commit/30f57e7aa501781d5c501b7fda18cb6c5416536b

Is this what you wanted? Should be out in the next release.

If you can also share specific logs - it would help me understand the issue a bit better.

I know when debugging on the proxy, i just needed to see the raw request/response to check if my args + envs were being passed correctly, and DEBUG was a lot more noisy. So if there's a way to present the information in a safe way on INFO, that would be great.

**Comment by Manouchehri** [comment]
I noticed that some `print` statements have slipped in recently in places like Langfuse.

https://github.com/BerriAI/litellm/blob/30f57e7aa501781d5c501b7fda18cb6c5416536b/litellm/integrations/langfuse.py#L250

<img width="805" alt="image" src="https://github.com/BerriAI/litellm/assets/7232674/628af719-af25-4ed9-953e-c98f27daf6bb">

**Comment by enyst** [comment]
@krrishdholakia Oh I see what you mean. I'll come back with proposals for INFO and DEBUG. But first things first please, the API keys issue:

Running with 
```litellm                                  1.34.29         Library to easily interface with LLM API providers```

Running this branch:
https://github.com/enyst/OpenDevin/tree/test

With this logging config:
https://github.com/enyst/OpenDevin/blob/test/opendevin/_logging.py

I start opendevin and tell our little AI to: "Print 2", and then, once it does it, "Print 3".

Logs:
https://gist.github.com/enyst/a93919393918a7d99c5b9dcd918d579e

The "Print 2" executed fully. I stopped the "Print 3" just before the last line in the log, when it was going to print sensitive info, and took this screenshot:

![Screenshot 2024-04-06 at 14 54 38](https://github.com/BerriAI/litellm/assets/6080905/e46817ab-c238-40f3-994f-cf58aad556d1)

My .env doesn't have DEBUG set. In the screenshot we can see that set_verbose was False, but the code ignores it. My .env did have the same key that got saved in the log. (I manually mangled it now, but it was real).

**Comment by enyst** [comment]
To clarify: it logs at line 936, the info() line.

**Comment by enyst** [comment]
> Hey @enyst reverted the change based on your feedback - [30f57e7](https://github.com/BerriAI/litellm/commit/30f57e7aa501781d5c501b7fda18cb6c5416536b)
> 
> Is this what you wanted? Should be out in the next release.

Thank you for this, you are so quick. I *think* your commit works for the INFO thing, although I am still to test it well. I think we need to fix DEBUG as well, as far as API keys are concerned, but DEBUG can have the rest, I assume.

**Comment by ghost** [comment]
should be live soon in v`1.34.31`

**Comment by ghost** [comment]
closing as completed. please bump me if not
