### ISSUE TITLE
Update exception mapping docs to be more readable 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#288]
What's the problem? (if there are multiple - list as bullet points)
Turn this into a 2-d matrix of provider and exceptions that have been mapped. It'll also make it easier to identify any gaps. 

<img width="1027" alt="Screenshot 2023-09-06 at 10 02 55 AM" src="https://github.com/BerriAI/litellm/assets/17561003/cf7d9700-6352-4ccd-b25c-466c3c0b3de4">

**Comment by pratik9315** [comment]
Hey @krrishdholakia! Would love to work on this. 

From my understanding, the purpose of this issue is to - Modify the above table so that, it just has a 2*2 table with providers and exceptions column right? That or I'm missing something😅

**Comment by ghost** [comment]
Yes exactly - we'd love the help @pratik2315

**Comment by ghost** [comment]
How to run the docs: 
```
git clone https://github.com/BerriAI/litellm.git
cd litellm 
cd docs/my-website
npx docusaurus start
```

**Comment by ghost** [comment]
When you make the PR - just add a link to your twitter + linkedin, and we'll give you a shoutout there!

**Comment by pratik9315** [comment]
> How to run the docs:
> 
> ```
> git clone https://github.com/BerriAI/litellm.git
> cd litellm 
> cd docs/my-website
> npx docusaurus start
> ```

Thanks! was just about to ask this!

One final doubt - What about the other 2 columns? Should I just remove them completely or list the information in them somewhere else in the form of bullet points?

**Comment by ghost** [comment]
I think we can remove them for now and point to the implementation code if anyone's interested - https://github.com/BerriAI/litellm/blob/d7e58d13bf9ba9edbab2ab2f096f3de7547f35fa/litellm/utils.py#L1544

But I trust you to make the right call / do what you think would be useful for you.

**Comment by ghost** [comment]
closing as this is now done
