### ISSUE TITLE
[User Request] Interrupt stream 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#289]
**Describe the solution you'd like**
"Is there a way to interrupt the stream? In JS I can do that with an AbortController and I would need something similar for litellm completions"

<img width="1183" alt="Screenshot 2023-09-06 at 10 21 41 AM" src="https://github.com/BerriAI/litellm/assets/17561003/e1001c4b-0c2b-49bb-a18d-bd37745cc8b7">

**Comment by ghost** [comment]
Will aim to pick this up and have it completed today.

**Comment by ghost** [comment]
closing as the response from a stream is a generator, so a break in for loop should fix this 
```
for chunk in response:
    break
```

**Comment by acertain** [comment]
there should be some way to interrupt the underlying HTTP request
