### ISSUE TITLE
[Feature]: UI Logout Button and SSO multi Login.

### ISSUE THREAD

**Issue by tip-dteller** [BerriAI/litellm#2896]
### The Feature

Hi,
When you set up SSO, there's no logout button or switch users button in the UI.
This would be really helpful so an admin user can switch between SSO and Static User for better moderation.

### Motivation, pitch

Im working on enabling multiple users and administrative user usage across a large user base.

**Comment by ishaan-jaff** [comment]
@tip-dteller we'd love to help out with this issue. Can we hop on a call to better understand what you need here? 

Sharing a link to my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by ghost** [comment]
Hi @tip-dteller sso is behind an enterprise license, 

Have we already spoken? 

Relevant discussion - https://github.com/BerriAI/litellm/discussions/2023

**Comment by ishaan-jaff** [comment]
logout button live now
