### ISSUE TITLE
[Bug]: Empty response when trying to get spend logs

### ISSUE THREAD

**Issue by VfBfoerst** [BerriAI/litellm#2899]
### What happened?

I am getting an empty response when calling the /spend/logs api.  
e.g.  
```bash
curl -X 'GET'   'http://localhost:4000/spend/logs?api_key=sk-1234&start_date=2024-04-04&end_date=2024-04-05'   -H 'accept: application/json'   -H 'Authorization: Bearer sk-1234'
```
  
We need to determine the amount of spent tokens, not only the costs. What is the best way to do so?

### Relevant log output

```shell
Output of above curl command:  
  

[]
```

**Comment by VfBfoerst** [comment]
Is there a way to export the usage directly, based on the user/api/team keys, as for example a csv or pdf file to analyze the usage?

**Comment by ishaan-jaff** [comment]
please use this endpoint for spend reporting @VfBfoerst https://docs.litellm.ai/docs/proxy/cost_tracking#api-endpoints-to-get-spend
