### ISSUE TITLE
add PaLM

### ISSUE THREAD

**Issue by whoiskatrin** [BerriAI/litellm#29]

**Comment by ghost** [comment]
the model is palm-2

**Comment by ghost** [comment]
created a branch for tracking this - https://github.com/BerriAI/litellm/tree/adding-palm-support

@whoiskatrin I don't have a key for PALM yet (hope to get it soon) - would you be able to review this and let me know if this aligns with what you have?

**Comment by ishaan-jaff** [comment]
Marking this as done - we added `VertexAI` support

**Comment by haseeb-heaven** [comment]
> Marking this as done - we added `VertexAI` support

But Vertex AI is different PALM has API Key Setup while Vertex has Google Auth JSON file
