### ISSUE TITLE
[Feature]: New embeddings from voyage and mixedbread ?

### ISSUE THREAD

**Issue by nicolas-geysse** [BerriAI/litellm#2911]
### The Feature

Would you consider integrating these new embeddings models ?
https://docs.voyageai.com/docs/embeddings
voyage-large-2, voyage-law-2, voyage-code-2, voyage-2, voyage-lite-02-instruct
And mxbai-embed-large-v1 from https://www.mixedbread.ai/docs/embeddings/mxbai-embed-large-v1#model-description

### Motivation, pitch

To get the best embeddings available, Open source or not !

**Comment by ishaan-jaff** [comment]
We already support voyage as a provider so should be quite straightforward to add

**Comment by ishaan-jaff** [comment]
@nicolas-geysse added here: https://github.com/BerriAI/litellm/pull/2913

**Comment by ishaan-jaff** [comment]
@nicolas-geysse curious - what do you use litellm for today ?

**Comment by nicolas-geysse** [comment]
Wow, that was fast ! Thanks a lot ! ATM I'm not using LiteLLM yet, but looking for the best solution to build a RAG system !

**Comment by ladrians** [comment]
is `mixedbread-ai` supported? could not find a reference on how to specify it? Based on [the site](https://www.mixedbread.ai/) there are embeddings an rerankers available. thanks,
