### ISSUE TITLE
[Feature]: Add testing/pre-commit hooks for pydantic warnings - You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#2915]
### The Feature

There have 3 instances of this warning coming up, getting fixed and then re-appearing
- we need to add testing to check if this warning appears on importing litellm and starting the proxy 

Warning log
```
You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
```

### Motivation, pitch

better dev experience

**Comment by SmartManoj** [comment]
Again in Version: 1.35.8

**Comment by paneru-rajan** [comment]
Working on it.

**Comment by ishaan-jaff** [comment]
ty  @paneru-rajan  - we want these to be permanently fixed :)

**Comment by CyanideByte** [comment]
Good idea. For now I made a fix PR for the latest ones that popped up.
https://github.com/BerriAI/litellm/pull/3334
Added a pytest for it to my PR.
