### ISSUE TITLE
[Feature]: New Model - `VertexAI/text-embedding-004`

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#2916]
### The Feature

`text-embedding-004, (text-embedding-preview-0409 in [Vertex AI](https://cloud.google.com/vertex-ai/generative-ai/docs/embeddings/get-text-embeddings#latest_models)),` 

https://developers.googleblog.com/2024/04/gemini-15-pro-in-public-preview-with-new-features.html

### Motivation, pitch

-

**Comment by NFuentesC** [comment]
hello! ,[ there are new models in GA](https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/text-embeddings) text-embedding-004
text-multilingual-embedding-002, how can they be included?

**Comment by RoastBeefKazenzakis** [comment]
Just wondering when/if we can expect support for text-embedding-004. Thank you.

**Comment by Manouchehri** [comment]
Hey @ishaan-jaff, this is high priority since DARPA is waiting for this for AIxCC. =)

**Comment by ishaan-jaff** [comment]
hi @Manouchehri @NFuentesC @RoastBeefKazenzakis will add this today :)

**Comment by ishaan-jaff** [comment]
PR here: https://github.com/BerriAI/litellm/pull/4145 

@Manouchehri @NFuentesC @RoastBeefKazenzakis
