### ISSUE TITLE
[Feature]: native bedrock async client

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#2921]
### The Feature

Make bedrock calls via httpx 

similar to anthropic implementation -https://github.com/anthropics/anthropic-sdk-python/blob/bd866a1e837febd05b6f5cea322f1c42e29f2d01/src/anthropic/lib/bedrock/_auth.py

Will allow all bedrock calls to be actually async 

### Motivation, pitch

faster responses

**Comment by ghost** [comment]
Closing in favor of - https://github.com/BerriAI/litellm/issues/3368
