### ISSUE TITLE
[Feature]: Leave imghdr

### ISSUE THREAD

**Issue by leondz** [BerriAI/litellm#2929]
### The Feature

Use something other than `imghdr`, so litellm doesn't break when we hit py 3.13

```
../../anaconda3/envs/garak/lib/python3.12/site-packages/litellm/llms/prompt_templates/factory.py:6
  /home/lderczynski/anaconda3/envs/garak/lib/python3.12/site-packages/litellm/llms/prompt_templates/factory.py:6: 
DeprecationWarning: 'imghdr' is deprecated and slated for removal in Python 3.13
    import imghdr, base64
```

### Motivation, pitch

LLMs move fast, people are coding new things often, so we have a bias towards using recent versions of things. It will be good to be able to move to 3.13 before long. Use of `imghdr` blocks that.

### Twitter / LinkedIn details

https://twitter.com/LeonDerczynski

**Comment by ishaan-jaff** [comment]
fix here: https://github.com/BerriAI/litellm/pull/2956

**Comment by jamesbraza** [comment]
Looks like https://github.com/BerriAI/litellm/pull/5255 brought `imghdr` back

Now in my `pytest` logs I see a `DeprecationWarning`:

```none
.venv/lib/python3.12/site-packages/litellm/utils.py:17: 16 warnings
  /home/runner/work/aviary/aviary/.venv/lib/python3.12/site-packages/litellm/utils.py:17: DeprecationWarning: 'imghdr' is deprecated and slated for removal in Python 3.13
    import imghdr
```

Cc @krrishdholakia

**Comment by ghost** [comment]
hey @jamesbraza thanks for resurfacing. Is there something we could use instead of imghdr. Using it to help get the image type more reliably 

see: https://github.com/BerriAI/litellm/blob/129113143ea23836d9ae63cd96031ff168607c23/litellm/utils.py#L1827

**Comment by jamesbraza** [comment]
Yeah sure, from https://peps.python.org/pep-0594/#deprecated-modules, it looks like some suggestions are [filetype](https://pypi.org/project/filetype/), [puremagic](https://pypi.org/project/puremagic/), [python-magic](https://pypi.org/project/python-magic/).

And thanks, just trying to clean up our CI logs a bit tonight

**Comment by ghost** [comment]
hmm these all look like they'd be additional deps, which is what i was trying to avoid with imghdr usage.

I'll look around for alternatives, open to suggestions here as well.

**Comment by jamesbraza** [comment]
Ah I see, and yes it's good to avoid additional dependencies. For built-in only, I don't have any tips sadly.

In the meantime, if it's cool do you mind reopening this issue?

**Comment by leondz** [comment]
Python-magic also has an external dep on some OSs (eg needs a brew command on osx), fyi

**Comment by leondz** [comment]
Looking at `utils.py`, magic is kinda overkill for the values of img_type actually consumed by the logic in `get_image_dimensions()`, which already is getting its hands dirty with image binary internals. Sniffing png/jpeg/gif headers is surprisingly trivial - easier than extracting dims, imo.

* The first eight bytes of a PNG file always contain the following (decimal) values:  137 80 78 71 13 10 26 10
* the [JFIF standard](https://en.wikipedia.org/wiki/JPEG_File_Interchange_Format#File_format_structure) sounds complex but is also stable - you're looking for something like ff d8 ff e0 00 10 4a 46  49 46 00 01 that can be written with a regex
* GIF files start with a fixed-length header ("GIF87a" or "GIF89a") giving the version
* else return None, None

Happy to draft a PR to replace: https://github.com/BerriAI/litellm/blob/129113143ea23836d9ae63cd96031ff168607c23/litellm/utils.py#L1827 w/ some quick matching over `img_data` which we already have.

**Comment by ghost** [comment]
Hey @leondz we'd welcome a PR here. Just make sure it can pass - https://github.com/BerriAI/litellm/blob/98c34a7e27892d367e507980b6a144d380337d4f/litellm/tests/test_token_counter.py#L368

**Comment by leondz** [comment]
Aight, will line it up. Give me a week max. This test needs more cases, will aim to add them.

**Comment by ghost** [comment]
Thank you @leondz

**Comment by leondz** [comment]
PR sent

**Comment by jamesbraza** [comment]
Confirmed `litellm==1.49.1` resolved the new `DeprecationWarning`, nice. This can be closed out now
