### ISSUE TITLE
Weights & Biases integration 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#293]
allow users to easily post data to weights and biases

**Comment by adi-kmt** [comment]
Could work on this, if you still want.
[This](https://docs.wandb.ai/ref/python/log) is what I'll try to integrate. 
So we could have two functions, init() for wandb init and another for logging

**Comment by ghost** [comment]
+ 1 another user asked for this today

**Comment by ghost** [comment]
@kamathis4 do you know when you plan to submit the PR for this?

**Comment by ishaan-jaff** [comment]
i've added this

**Comment by ishaan-jaff** [comment]
need to add docs for this now

**Comment by ghost** [comment]
i'm proud of you @ishaan-jaff

**Comment by ishaan-jaff** [comment]
done
