### ISSUE TITLE
[Bug]: Azure image generation doesn't support HTTPS_PROXY env 

### ISSUE THREAD

**Issue by krille90** [BerriAI/litellm#2930]
### What happened?

I am trying to use the litellm router (docker image v1.34.39) /images/generations endpoint with an azure dall-e-3 deployment.
This works fine without being behind a company firewall, how it stops working when running on a server, that uses a proxy to communicate with Azure. This does not the affect /chat/completion endpoint.

I was able to create a hotfix that would support my use case, but I guess a PR might not be a solution here. The hotfix is for the file `litellm/llms/azure.py`

line 653:
```py
            if client is None:
                # client_session = litellm.aclient_session or httpx.AsyncClient(
                #     transport=AsyncCustomHTTPTransport(),
                # )
                client_session = litellm.aclient_session
                azure_client = AsyncAzureOpenAI(
                    http_client=client_session, **azure_client_params
                )
            else:
                azure_client = client
```

line 756:
```py
            if client is None:
                # client_session = litellm.client_session or httpx.Client(
                #     transport=CustomHTTPTransport(),
                # )
                client_session = litellm.client_session
                azure_client = AzureOpenAI(http_client=client_session, **azure_client_params)  # type: ignore
            else:
                azure_client = client
```

As I am using docker image v1.34.39, this should include the fix for #1458, however it doesn't seem to affect the image generation for Azure.

**Comment by emerzon** [comment]
Thank you, I have the same problem.

@krrishdholakia would you consider a PR for this issue?

**Comment by ishaan-jaff** [comment]
fix is here: https://github.com/BerriAI/litellm/pull/4293 

We already support this on the litellm router - but we were not using the router level client for image generation requests
