### ISSUE TITLE
[Feature]: Log region to Langfuse

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#2937]
### The Feature

For things like Vertex AI, it'd be useful if we logged the region that was used.

### Motivation, pitch

For troubleshooting/checking perf of regions.

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by ghost** [comment]
makes sense - would this be in the metadata? @Manouchehri

**Comment by Manouchehri** [comment]
I think so. I was debating between metadata and model parameters, but metadata sounds more "correct" to me (since in theory the same model in a different region should always behave the same).

**Comment by Manouchehri** [comment]
I'm working on this, PR incoming soon.

**Comment by ghost** [comment]
Thanks!
