### ISSUE TITLE
[Bug]: Non-Team members have permission to delete a team 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#2955]
### What happened?

>  ran the litellm docker image locally and then used the default administrator account to create a user named user1. After creation, the api-key provided for user1 was sk-EDPWeidMYhR87NOwUwoR6g. Then, I used the administrator account to create a team called team1, with the team ID being 45e3e396-ee08-4a61-a88e-16b3ce7e0849. However, at that time, team1's members included only the default administrator, and user1 was not a member of team1. When I called the API using the key sk-EDPWeidMYhR87NOwUwoR6g for authentication, the system did not check user1's roles and permissions, lacking authorization verification, which resulted in the deletion of team1.

**Comment by powerhouseofthecell** [comment]
I couldn't replicate this issue on my end. I was assuming that the calling the API with the user's key was to call `/team/delete`, but lmk if that wasn't the case and I'll recheck.
