### ISSUE TITLE
Dynamically replace api base for openai 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#296]
**Describe the solution you'd like**
<img width="1345" alt="Screenshot 2023-09-07 at 4 43 04 PM" src="https://github.com/BerriAI/litellm/assets/17561003/ded5f166-7241-498c-96ed-c06d34bf9883">

**Comment by ishaan-jaff** [comment]
it's done but any idea on how we can test this ? 

should we deploy vllm on a server and try hitting it with a request like this

**Comment by ishaan-jaff** [comment]
i don't want to go through the effort of deploying vllm on a gpu so just making an openai proxy on replit

**Comment by ishaan-jaff** [comment]
added this test to verify:

```
def test_completion_hosted_vllm():
    # this tests calling a server where vllm is hosted
    # this should make an openai.Completion() call to the specified api_base
    # send a request to this proxy server: https://replit.com/@BerriAI/openai-proxy#main.py
    # it checks if model == facebook/opt-125m and returns test passed
    try:
        # litellm.set_verbose = True
        response = completion(
            model="facebook/opt-125m", 
            messages=messages,
            temperature=0.2,
            max_tokens=80,
            api_base="https://openai-proxy.berriai.repl.co/v1",
            custom_llm_provider="openai"
        )
        print(response)

        if response['choices'][0]['message']['content'] != "passed":
            # see https://replit.com/@BerriAI/openai-proxy#main.py
            pytest.fail(f"Error occurred: proxy server did not respond")
    except Exception as e:
        pytest.fail(f"Error occurred: {e}")
```

**Comment by ishaan-jaff** [comment]
fyi it looks like VLLM hosted server always expects openai.Completion requests

**Comment by ishaan-jaff** [comment]
verifying this works for me

<img width="1280" alt="Screenshot 2023-09-08 at 2 01 46 PM" src="https://github.com/BerriAI/litellm/assets/29436595/ff392df1-975d-463f-a4ca-a241ae3b2174">

**Comment by ishaan-jaff** [comment]
here's the proxy replit server for future reference:
https://replit.com/@BerriAI/openai-proxy#main.py

**Comment by ishaan-jaff** [comment]
marking this as closed: https://docs.litellm.ai/docs/providers/vllm#calling-hosted-vllm-server 

https://docs.litellm.ai/docs/providers/vllm#calling-hosted-vllm-server

**Comment by ishaan-jaff** [comment]
re-opening this to use openai.ChatCompletion but not openai.Completion()
