### ISSUE TITLE
[LiteLLM Client] Replay prompt with new model

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#297]
**Describe the solution you'd like**
As noted above - awaiting on user for more details

**Comment by ghost** [comment]
this is now enabled for local models - by default it will run the last 50 logs on your local endpoint (needs to be an openai proxy) 

<img width="1710" alt="Screenshot 2023-09-08 at 5 23 28 PM" src="https://github.com/BerriAI/litellm/assets/17561003/4a0a4a1d-1f38-41eb-ba73-adbdfeb283c3">
