### ISSUE TITLE
Exception when libraries are not installed is opaque

### ISSUE THREAD

**Issue by neubig** [BerriAI/litellm#298]
I tried to use a cohere model, but didn't have the library installed, and got the following rather opaque error:

```
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
    488 cohere_key = (
    489     api_key
    490     or litellm.cohere_key
    491     or get_secret("COHERE_API_KEY")
    492     or get_secret("CO_API_KEY")
    493 )
--> 494 co = cohere.Client(cohere_key)
    495 prompt = " ".join([message["content"] for message in messages])

UnboundLocalError: local variable 'cohere' referenced before assignment
```

I looked into the code, and it seems that it actually should be throwing a better error telling me that cohere is not installed, but it's not. Maybe in the following line it should be `raise Exception` instead of `Exception` (and similarly for other providers)?https://github.com/BerriAI/litellm/blob/8acf959430e037d18043e4e2e32db5242b94169c/litellm/main.py#L483

**Comment by ishaan-jaff** [comment]
@neubig thanks for raising this. will make the change and ensure it's reflected for all providers where we try to import their libraries

**Comment by ishaan-jaff** [comment]
confirming I was able to repro this:


<img width="1280" alt="Screenshot 2023-09-08 at 3 12 12 PM" src="https://github.com/BerriAI/litellm/assets/29436595/e8e4370f-5432-4eb8-88f4-b3c6a9097c85">

**Comment by ghost** [comment]
@ishaan-jaff is this fixed already? 

If not happy to take a look

**Comment by ishaan-jaff** [comment]
@krrishdholakia yes. just some cleaning up to do on it now. taking care of it

**Comment by ishaan-jaff** [comment]
this is the error i now see when a lib is not installed. 

<img width="870" alt="Screenshot 2023-09-08 at 5 41 27 PM" src="https://github.com/BerriAI/litellm/assets/29436595/c556bc59-469f-4d53-9e18-2a4d40dc3711">

Also fixed a bug where if you `raise original_exception` it raises another exception saying it's not of BaseException

**Comment by ishaan-jaff** [comment]
thanks so much for raising @neubig 

closing this for now - feel free to re-open if you still run into the error. 

This should be updated litellm version 0.1.564 and higher
