### ISSUE TITLE
Supported models link on the front page is broken

### ISSUE THREAD

**Issue by neubig** [BerriAI/litellm#299]
![Screen Shot 2023-09-08 at 5 40 47 PM](https://github.com/BerriAI/litellm/assets/398875/7ae8326c-52bd-4633-9657-9bd578c3c376)

![Screen Shot 2023-09-08 at 5 41 33 PM](https://github.com/BerriAI/litellm/assets/398875/a9e3fb79-4116-4948-91b4-2ec12ab9cd42)

**Comment by ishaan-jaff** [comment]
fixed, replace the old link with https://docs.litellm.ai/docs/providers 

feel free to re-open if it's not working for you @neubig
