### ISSUE TITLE
[Bug-langfuse]: `Item exceeds size limit (size: 2308149), dropping item.` - langfuse

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#2992]
### What happened?

When using Gemini 1.5 Pro with huge prompts, they aren't logged to Langfuse.

Related to https://github.com/BerriAI/litellm/issues/2055.

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by Manouchehri** [comment]
This was the response for context. :) 

```json
{
  "id": "chatcmpl-e5a91875-5be9-4ee1-9168-79e69dd4e4e5",
  "choices": [
    {
      "finish_reason": "stop",
      "index": 0,
      "logprobs": null,
      "message": {
        "content": "removed",
        "role": "assistant",
        "function_call": null,
        "tool_calls": null
      }
    }
  ],
  "created": 1712955115,
  "model": "gemini-1.5-pro-preview-0409",
  "object": "chat.completion",
  "system_fingerprint": null,
  "usage": {
    "completion_tokens": 650,
    "prompt_tokens": 616179,
    "total_tokens": 616829
  }
}
```

**Comment by ishaan-jaff** [comment]
+1 seeing this on embedding too

**Comment by ishaan-jaff** [comment]
spoke to the langfuse team - they will push a fix for this by end of this week

**Comment by ishaan-jaff** [comment]
closing since this is not litellm related

**Comment by Manouchehri** [comment]
Do you know which ticket was made on the Langfuse side? :)

**Comment by ishaan-jaff** [comment]
cc @marcklingen

**Comment by marcklingen** [comment]
@Manouchehri https://github.com/langfuse/langfuse/issues/1676

**Comment by Manouchehri** [comment]
Hmm, we should just truncate the input to 1MB on LiteLLM to avoid this:

https://github.com/langfuse/langfuse-python/blob/9d027f66eb4db431f46152982a5571c5e18c5241/langfuse/task_manager.py#L27

**Comment by ishaan-jaff** [comment]
fixed here: https://github.com/BerriAI/litellm/pull/5497

**Comment by ishaan-jaff** [comment]
langfuse python sdk made the fix
