### ISSUE TITLE
[Feature]: Use semaphores to make router calls concurrency safe

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#2994]
### The Feature

use a semaphore when a user sets rpm limits on a deployment

Use this to control how many requests can be made simultanously to the deployment 

### Motivation, pitch

Make router concurrency safe

**Comment by ghost** [comment]
Test case: 
- set rpm 1
- make 5 concurrent requests 
Currently all will pass, as the current rpm value in the cache is checked simultaneously and is 0 initially

**Comment by ghost** [comment]
closing as this is now implemented in v`1.35.4`. to have the async calls be concurrency safe use `usage-based-routing-v2`
