### ISSUE TITLE
Guarantee format of exceptions

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#3]
each LLM provider has a diff exception format, most builders need to implement their own try/except handling for each provider they use

**Comment by ghost** [comment]
this seems like a pretty core part of a Model I/O library 

Maybe v0 could just be trying to consistently map the 3 common exceptions: 
- Rate Limit Errors 
- Context Window Errors 
- InvalidAuth errors (key rotation stuff)

**Comment by ghost** [comment]
pushed https://github.com/BerriAI/litellm/pull/30
