### ISSUE TITLE
[Feature]: Databricks LLM serving endpoint support

### ISSUE THREAD

**Issue by amit10may** [BerriAI/litellm#3000]
### The Feature

Is there a plan to support databricks model serving endpoints?

### Motivation, pitch

Databricks model serving is becoming popular and indeed a very easy way to access many models - eg Llama, DBRX and more

**Comment by ghost** [comment]
hey @amit10may yes there is! 

relevant issue: https://github.com/BerriAI/litellm/issues/2160

when do you need this by? 

closing issue as it's a duplicate.
