### ISSUE TITLE
[Bug]: Add model through UI creates a model for each letter of formValues["model"]

### ISSUE THREAD

**Issue by zJuuu** [BerriAI/litellm#3001]
### What happened?

If i add a model through UI it tries to create a model for each letter of formValues["model"].
Maybe split the model names with a comma

https://github.com/BerriAI/litellm/blob/5e171881f431d3a79fa7bd3aea3f5c39f77df163/ui/litellm-dashboard/src/components/model_dashboard.tsx#L259

**Comment by ishaan-jaff** [comment]
fixed on latest
