### ISSUE TITLE
[Bug]: block key created via ui from creating new keys 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#3009]
### The Feature

key created via ui seems to be able to create new keys -> don't allow this without admin permission 

### Motivation, pitch

more secure use of keys

**Comment by ghost** [comment]
User request: "I would like to limit which keys have permission to run /user/new and /key/generate commands to only admin keys (specifically my key)."

**Comment by ghost** [comment]
move route specific checks inside the routes - simplify `user_api_key_auth` -> should just check if user is allowed to call the route

**Comment by ghost** [comment]
could probably simplify our routing logic by just checking if it's an allowed route or not for the user role, and allowing admin to configure any specific allowed routes

**Comment by ghost** [comment]
Fixed with - https://github.com/BerriAI/litellm/commit/ffd3a96fcfe6ae9a8640721db72847e054bf9dbe
