### ISSUE TITLE
Enable users to provide custom callback functions 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#301]
**Describe the solution you'd like**

Based on discussion with @yujonglee - he was trying to send data to providers we don't currently support and had problems doing so. 

expose a way for a user to provide custom callback functions.

**Comment by yujonglee** [comment]
I think LiteLLM can expose Abstract base class for this. Existing code should be refactored though.

**Comment by ishaan-jaff** [comment]
done: https://docs.litellm.ai/docs/observability/custom_callback 
@yujonglee what do you think about this ?

**Comment by yujonglee** [comment]
@ishaan-jaff I think this is great! I don't see any use case that this can not cover.
