### ISSUE TITLE
[Feature]: Is it possible to support function calling via openrouter?

### ISSUE THREAD

**Issue by NeverOccurs** [BerriAI/litellm#3016]
### The Feature

Now the openrouter models do not support function call in Litellm at all. I don't know if it is because openrouter itself does not or the Litellm has not intergrated it yet. I can see setting function-calling part in request schema of openrouter but I don't know if it can be integrated by litellm.

https://openrouter.ai/docs#requests

Or is there anything that can be set on my side to make function calling work?

### Motivation, pitch

Openrouter has many models available, it would be a huge plus if function calling via openrouter is possible.

**Comment by Merlinvt** [comment]
Seems like it supports FC on some models https://discord.com/channels/1091220969173028894/1235991637985984565

**Comment by ghost** [comment]
This should already work - i see tool calls is allowed in the optional params 

<img width="571" alt="Screenshot 2024-05-10 at 7 25 40 PM" src="https://github.com/BerriAI/litellm/assets/17561003/e2966e7d-b59b-4d82-9663-500388ad9db2">

https://github.com/BerriAI/litellm/blob/1aa567f3b52897a97b27d566ca05286fffffd247/litellm/utils.py#L6000
