### ISSUE TITLE
Ensure that using litellm.api_base calls openai.ChatCompletion

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#302]
I believe this is what @yujonglee is trying to do

**Comment by yujonglee** [comment]
Yep.  https://github.com/fastrepl/proxy should handle all request properly from caller that use `litellm` with `api_base` set to `proxy url`.

**Comment by ghost** [comment]
isn't this related? 
https://github.com/BerriAI/litellm/issues/296

seems like you'd just do `completion(model, messages, api_base="your-proxy", custom_llm_provider="openai")`

**Comment by ishaan-jaff** [comment]
here's what i think this architecture should look like:
cc @yujonglee did i understand it correct ? 

We just need to make sure when
```
litellm.completion(
model=model,
api_base ="https://your-api.ai",
messages=messages,
custom_llm_provider="openai"
)
```

`It makes an openai.ChatCompletion request`

<img width="683" alt="Screenshot 2023-09-09 at 3 28 36 PM" src="https://github.com/BerriAI/litellm/assets/29436595/69871ebe-36db-4b1a-aff5-d464d9ba8aa9">

**Comment by ishaan-jaff** [comment]
https://docs.litellm.ai/docs/providers/custom_openai_proxy done


@yujonglee should be good to go. just wait for our new pypi deploy today

**Comment by yujonglee** [comment]
> here's what i think this architecture should look like:

Correct. Thanks!
