### ISSUE TITLE
[Bug]:  User UI empty after creating User via API or UI

### ISSUE THREAD

**Issue by ncecere** [BerriAI/litellm#3021]
### What happened?

On a fresh instance of litellm proxy server, when I create a user via the UI or API the user section stays empty.  The user is created, I can see them via the API, just not in the UI.  I'm not sure if this is a bug in the UI or if I'm doing something wrong.  I was able to see the users in older versions, this seems to be new.  any help is welcome

<img width="1436" alt="image" src="https://github.com/BerriAI/litellm/assets/6109463/15b5a7d6-87da-406b-9776-2a9c310b9dbb">

**Comment by ishaan-jaff** [comment]
@ncecere fixed on #3033. @ncecere can we hop on a call sometime this week? I'd love to learn how we can improve litellm proxy for you

If you can share your email here or on Linkedin - I can send over a meeting invite
Link to my calendly for your convenience - if you prefer to select any time: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat?month=2024-04

Link to my Linkedin if you want to dm me directly: https://www.linkedin.com/in/reffajnaahsi/
