### ISSUE TITLE
[Feature]: Enable Function Calling for Groq

### ISSUE THREAD

**Issue by demux79** [BerriAI/litellm#3023]
### The Feature

Groq now supports function calling directly: https://console.groq.com/docs/tool-use

### Motivation, pitch

It would be great to use it via litellm

**Comment by ishaan-jaff** [comment]
@demux79 done - should be live on the next release. @demux79 can we hop on a call sometime this week? I'd love to learn how we can improve litellm proxy for you

If you can share your email here or on Linkedin - I can send over a meeting invite
Link to my calendly for your convenience - if you prefer to select any time: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat?month=2024-04

Link to my Linkedin if you want to dm me directly: https://www.linkedin.com/in/reffajnaahsi/
