### ISSUE TITLE
[Feature]: Use litellm with mulitple projects in langfuse

### ISSUE THREAD

**Issue by databill86** [BerriAI/litellm#3024]
### The Feature

Hello, 
Thanks you for this great tool. The integration with langfuse is very useful. 
Currently, the configuration of langfuse can be done in the docker compose file: 
```
    environment:
      - LANGFUSE_HOST=http://lf:3000
      - LANGFUSE_PUBLIC_KEY=pk-lf-0160b8f5
      - LANGFUSE_SECRET_KEY=sk-lf-3ccd40
```

using this configuration, `litellm` is hooked with a single `langfuse` project. We have multiple langfuse projects, that we want to observe, is there a way we can manage this in the settings or the way we call the API ? 

### Motivation, pitch

We are running both `litellm` and `langfuse` as docker services. 

litellm is a tool that could be used to manage multiple teams. We have some projects that should be logged separately. 

Is there a way we can manage different `langfuse` projects in `litellm` settings ? 

We use `litellm proxy` along with `openai` sdk by modifying the `base_url`. 

Thanks.

**Comment by widike** [comment]
Yes, you can do that using the proxy. It's a bit hidden in the documentation: https://litellm.vercel.app/docs/proxy/team_based_routing

Just make sure to generate the teams with the API and not via UI (https://github.com/BerriAI/litellm/issues/2995#issuecomment-2053736837)

**Comment by ishaan-jaff** [comment]
> Just make sure to generate the teams with the API and not via UI

hmmm we should support this through the UI too

**Comment by ishaan-jaff** [comment]
@databill86 can we hop on a call sometime this week? I'd love to learn how we can improve litellm proxy for you + talk through what you need for this feature

If you can share your email here or on Linkedin - I can send over a meeting invite
Link to my calendly for your convenience - if you prefer to select any time: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat?month=2024-04

Link to my Linkedin if you want to dm me directly: https://www.linkedin.com/in/reffajnaahsi/

**Comment by ishaan-jaff** [comment]
@databill86 this is live on langfuse docs now too: https://litellm.vercel.app/docs/proxy/logging#team-based-logging-to-langfuse . I'd love to get on a call and learn how we can improve litellm for you 😃 

Feel free to re-open this issue if you feel we have not solved it for you 


> . It's a bit hidden in the documentation: https://litellm.vercel.app/docs/proxy/team_based_routing

@demux79 do you recommend anywhere we should place this information on our docs

**Comment by widike** [comment]
> @demux79 do you recommend anywhere we should place this information on our docs

Maybe add it to the https://litellm.vercel.app/docs/proxy/logging section?

**Comment by databill86** [comment]
> Yes, you can do that using the proxy. It's a bit hidden in the documentation: https://litellm.vercel.app/docs/proxy/team_based_routing
> 
> Just make sure to generate the teams with the API and not via UI ([#2995 (comment)](https://github.com/BerriAI/litellm/issues/2995#issuecomment-2053736837))

Thank you, that's perfect, it was indeed hidden :) 

As @demux79 pointed out, it would be really great if we could do this in the UI, it's super useful! 
https://github.com/BerriAI/litellm/issues/2995 is closed, so I hope it's resolved. I will give it try anyway. 

Thanks again.

**Comment by databill86** [comment]
> @databill86 can we hop on a call sometime this week? I'd love to learn how we can improve litellm proxy for you + talk through what you need for this feature
> 
> If you can share your email here or on Linkedin - I can send over a meeting invite Link to my calendly for your convenience - if you prefer to select any time: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat?month=2024-04
> 
> Link to my Linkedin if you want to dm me directly: https://www.linkedin.com/in/reffajnaahsi/

Glad you asked :) 
We are just starting with litellm, and its integration with other tools such as langfuse, fastchat... And it's really good.

Actually, I'm trying to log scores into langfuse, I'm using [Ragas](https://github.com/explodinggradients/ragas/tree/main) for the evaluation. So far, it's a bit tricky to log both scores and completions in the same place. Logging the completions is automatically done using llmlite. But for the scores, I should have the `trace_id` for each completion, to put the scores in the right place.

Am I doing it right ?
