### ISSUE TITLE
[Bug]: Invalid kwarg `request` used for raising Timeout from a/completion call

### ISSUE THREAD

**Issue by worgarside** [BerriAI/litellm#3025]
### What happened?

When a completion call fails due to a timeout, a `Timeout` instance is raised as expected but with an unexpected kwarg `"request"`. I am using `litellm.acompletion` against an Azure-hosted LLM, however it looks like there are few other instances of invalid kwargs being used within `utils.py`:

- [AnthropicException](https://github.com/BerriAI/litellm/blob/main/litellm/utils.py#L7502)
- [ReplicateException](https://github.com/BerriAI/litellm/blob/main/litellm/utils.py#L7599)
- [HuggingfaceException](https://github.com/BerriAI/litellm/blob/main/litellm/utils.py#L8008)
- [AI21Exception](https://github.com/BerriAI/litellm/blob/main/litellm/utils.py#L8068)
- [NLPCloudException](https://github.com/BerriAI/litellm/blob/main/litellm/utils.py#L8158)
- [TogetherAIException](https://github.com/BerriAI/litellm/blob/main/litellm/utils.py#L8275)
- [AzureException](https://github.com/BerriAI/litellm/blob/main/litellm/utils.py#L8475)

Based on the other places where a `Timeout` is raised, my guess is that the invalid kwarg just needs to be removed?

I'm using `litellm==1.35.5`

### Relevant log output

```shell
File "...", line 61, in generate_acompletion
    async for item in await acompletion(**completion_kwargs):
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/llm-gHYm-Hqm-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 3433, in wrapper_async
    raise e
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/llm-gHYm-Hqm-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 3265, in wrapper_async
    result = await original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/llm-gHYm-Hqm-py3.11/lib/python3.11/site-packages/litellm/main.py", line 338, in acompletion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/llm-gHYm-Hqm-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 8573, in exception_type
    raise e
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/llm-gHYm-Hqm-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 8471, in exception_type
    raise Timeout(
          ^^^^^^^^
TypeError: Timeout.__init__() got an unexpected keyword argument 'request'
```

**Comment by ghost** [comment]
hi @worgarside are you sure about the litellm version? 

The line the error is raised on doesn't map to 8471 in utils.py on the repo 



<img width="1212" alt="Screenshot 2024-04-15 at 10 47 55 AM" src="https://github.com/BerriAI/litellm/assets/17561003/c028da93-0703-4423-8533-8374ed3ebc23">

**Comment by ghost** [comment]
Fixed. Found a couple occurrences of it on other lines. - https://github.com/BerriAI/litellm/commit/068358902918ce8d3d9dc43191c3091035d8453f

**Comment by ghost** [comment]
Should be live soon in v`1.35.6`

**Comment by worgarside** [comment]
@krrishdholakia sorry not sure what happened with the versions, my bad! Thanks for sorting 🙌
