### ISSUE TITLE
add crisp chat to docs

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#303]
**Describe the solution you'd like**
Add crisp chat `<script type="text/javascript">window.$crisp=[];window.CRISP_WEBSITE_ID="be07a4d6-dba0-4df7-961d-9302c86b7ebc";(function(){d=document;s=d.createElement("script");s.src="https://client.crisp.chat/l.js";s.async=1;d.getElementsByTagName("head")[0].appendChild(s);})();</script>`

to docs - making it easy for people to ask questions

**Comment by ghost** [comment]
cc: @NANDINI-star any help here would be great

**Comment by ghost** [comment]
bump @NANDINI-star any thoughts on how we could do this?

**Comment by NANDINI-star** [comment]
whoops missed it. thanks @krrishdholakia. I'll take a look at it.

**Comment by ghost** [comment]
thanks!! @NANDINI-star

**Comment by ghost** [comment]
Closing with @NANDINI-star's help!
