### ISSUE TITLE
[Bug]: Data Loss and Unexpected Database Overwrite During litellm Server Execution

### ISSUE THREAD

**Issue by Swoyam1** [BerriAI/litellm#3035]
### What happened?

While attempting to run the litellm server, we encountered a critical issue where the server emptied our entire PostgreSQL database without any warning and stored litellms database details instead. This unexpected behavior led to severe data loss and disruption of our database operations. We urgently request you to address this bug to prevent such incidents in the future and ensure data integrity and stability.

**Comment by ishaan-jaff** [comment]
Hi @Swoyam1 free to hop on a call? : https://meet.google.com/dsu-gntc-mtb We can help address the issue

**Comment by ishaan-jaff** [comment]
If now does not work sharing a link to my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/berriai-1-1-onboarding-litellm-hosted-version?month=2023-10 

I want to solve this for you asap

**Comment by ghost** [comment]
I believe this is the line https://github.com/BerriAI/litellm/blob/931fe035d6badd6edc721cdb617314c9502cd76c/entrypoint.sh#L32

the intent is to handle db schema updates. Without it, it's hard to control schema updates inside docker images. 

I believe the solution here is to create a db url with limited permissions @Swoyam1 

Open to alternatives. I looked into `prisma migrate` and that dropped tables for my prod db. 


Related prisma issues:
- https://github.com/prisma/prisma/issues/12272
- https://github.com/prisma/prisma/issues/11184

**Comment by ishaan-jaff** [comment]
@Swoyam1 bump?

**Comment by ishaan-jaff** [comment]
closing this issue - feel free to re-open if not resolved

**Comment by ishaan-jaff** [comment]
@Swoyam1 we now offer a Cloud Hosted LiteLLM Proxy, curious is this something that you would want to use ?

**Comment by yx-lamini** [comment]
What's the resolution? This almost destroyed our production cluster.

**Comment by nvinayvarma189** [comment]
Yes, this can be dangerous.

For someone who tries to run litellm for the first time with an existing database as storage for llmlite-specific tables (following this), there is no hint that it wipes out all the tables and data in the public schema.

@krrishdholakia While the best practice is always to create a new user with restricted access while providing DB access to new 3rd party services, it is not often followed.

A better entry point would be to first inform the user that it tries to run migrations on the public schema and can result in loss of data. I would also advocate for [this proposal](https://github.com/BerriAI/litellm/discussions/5370#discussion-7098243) to decouple schema migrations with server initialization.

**Comment by nvinayvarma189** [comment]
@yx-lamini A possible solution is to provide the schema name in which the tables need to be created like this
```
postgresql://username:password@localhost:5432/mydb?schema=myschema
```

This will create the litellm tables in the "myschema" and all the other tables will be unaffected.

**Comment by ghost** [comment]
Hi @nvinayvarma189 I'll try that. I believe today by default it uses the public schema.

**Comment by aguadoenzo** [comment]
@ishaan-jaff this should absolutely be re-opened (unless there's a duplicate I missed), it's very much still an issue, and a massively dangerous one at that.
We lost all data on a test cluster by having both litellm and our app on the same database. When redeploying litellm (i.e creating a new docker container), it wiped the whole database and schema.

There is no mention of this in the [docs](https://docs.litellm.ai/docs/proxy/docker_quick_start#31-set-up-a-database) as well.
