### ISSUE TITLE
[Feature]: Hosted Helm Chart

### ISSUE THREAD

**Issue by eyearian** [BerriAI/litellm#3038]
### The Feature

Hosted helm chart package

### Motivation, pitch

While I see you have the helm chart available in the repo, can we have this hosted on git so I can pull it from something like ArgoCD?

Something like this https://github.com/helm/chart-releaser

Currently, I can point ArgoCD at the github repo itself and it will pull the correct chart but doesn't allow me to set a version (0.2.0 in this case) and keeps my chart synced with HEAD.  Additionally I can't alter the values since i'm pulling it from HEAD.  When trying to pull the helm chart via the repo and setting a version I get an error about a missing `index.yml` which the chart-releaser (or similar utility) would resolve.

In another scenario, it doesn't make sense for me to clone the repo and store the helm chart in my source control when I (imo) should just be able to pull it via a helm chart package, set an appropriate version and fill out a values file on my end.

**Comment by ishaan-jaff** [comment]
@eyearian we have a hosted helm chart here: https://github.com/BerriAI/litellm/pkgs/container/litellm-helm. 

Can we hop on a call sometime this week ? I want to help you get to production / improve litellm for you. I can send a cal invite if you can send me your email 

Here's a link to my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat 
Here's my linkedin: https://www.linkedin.com/in/reffajnaahsi/

**Comment by eyearian** [comment]
@ishaan-jaff Thanks for the quick response.  I've put some time on the cal for a call this week. 

When using the helm chart you provided, I get the following error:

```Error: looks like "https://ghcr.io/berriai/litellm-helm" is not a valid chart repository or cannot be reached: failed to fetch https://ghcr.io/berriai/litellm-helm/index.yaml : 404 Not Found```

Looks like it's still looking for the index.yml file.

**Comment by octera** [comment]
@eyearian LiteLLM Helm chart are stored as OCI layer and not HTTP.
So you have to reference it with OCI protocol : 
`helm pull oci://ghcr.io/berriai/litellm-helm:0.1.182`

**Comment by ghost** [comment]
@eyearian we now have a hosted helm chart via github pages - https://berriai.github.io/litellm/

Let me know if this solves your problem
