### ISSUE TITLE
[14/04/2024 - 19/05/2024] 🐛 💪 Bug Bash \ New Features \ Providers 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#3045]
Aim: bash 50 bugs this week

- [x] https://github.com/BerriAI/litellm/issues/3027
- [x] https://github.com/BerriAI/litellm/issues/3025
- [x] #3049
- [x] #3050
- [x] https://github.com/BerriAI/litellm/issues/3024
- [x] https://github.com/BerriAI/litellm/issues/3021
- [x] https://github.com/BerriAI/litellm/issues/3113
- [x] #3178
- [ ] #3060 
- [x] #3177
- [x] #3051 
- [x] #3064
- [x] #3073
- [x] #3137
- [x] #3138
- [x] #3139
- [x] #3195
- [x] https://github.com/BerriAI/litellm/issues/3018
- [x] https://github.com/BerriAI/litellm/issues/2951
- [x] https://github.com/BerriAI/litellm/issues/2972
- [ ] https://github.com/BerriAI/litellm/issues/2899
- [ ] https://github.com/BerriAI/litellm/issues/2889
- [ ] https://github.com/BerriAI/litellm/issues/2885
- [ ] https://github.com/BerriAI/litellm/issues/2852
- [x] https://github.com/BerriAI/litellm/issues/2834
- [x] https://github.com/BerriAI/litellm/issues/2833
- [ ] https://github.com/BerriAI/litellm/issues/2716
- [ ] https://github.com/BerriAI/litellm/issues/2645
- [x] https://github.com/BerriAI/litellm/issues/2990
- [ ] https://github.com/BerriAI/litellm/issues/2615
- [x] https://github.com/BerriAI/litellm/issues/2584
- [x] https://github.com/BerriAI/litellm/issues/3052
- [x] https://github.com/BerriAI/litellm/issues/3009
- [x] #3070
- [x] https://github.com/BerriAI/litellm/issues/2114
- [x] #3086
- [x] https://github.com/BerriAI/litellm/issues/3100
- [x] https://github.com/BerriAI/litellm/issues/3129
- [x] https://github.com/BerriAI/litellm/issues/3147
- [ ] https://github.com/BerriAI/litellm/issues/3135
- [ ] https://github.com/BerriAI/litellm/issues/3155
- [x] https://github.com/BerriAI/litellm/issues/3158
- [ ] https://github.com/BerriAI/litellm/issues/3128
- [x] #3181
- [x] #3182
- [x] https://github.com/BerriAI/litellm/issues/3090
- [x] https://github.com/BerriAI/litellm/issues/3156
- [ ] https://github.com/BerriAI/litellm/issues/3241
- [x] https://github.com/BerriAI/litellm/issues/3199
- [x] https://github.com/BerriAI/litellm/issues/3156
- [x] https://github.com/BerriAI/litellm/issues/3276
- [ ] https://github.com/BerriAI/litellm/issues/3275
- [x] https://github.com/BerriAI/litellm/issues/3274
- [x] https://github.com/BerriAI/litellm/issues/3288
- [x] https://github.com/BerriAI/litellm/issues/3286

## End-User Cost Tracking 
- [ ] #3514
- [ ] #3515
- [x] #3516
- [x] #3517

## New Models
- [x] #3633

## New Features 
- [x] https://github.com/BerriAI/litellm/issues/3490
- [x] https://github.com/BerriAI/litellm/issues/3362
- [x] https://github.com/BerriAI/litellm/issues/3490
- [x] https://github.com/BerriAI/litellm/issues/3523
- [x] #3524
- [x] #3553

**Comment by ghost** [comment]
link any bugs you find, worth resurfacing this week
