### ISSUE TITLE
[Bug]: Secure `/team/info` endpoint

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#3052]
### What happened?

Currently anyone with a valid proxy key can pull any team's info. 

Fix this:
- only team members or proxy admin should be able to pull this info

**Comment by ghost** [comment]
Fixed with - https://github.com/BerriAI/litellm/commit/3f8abe2754bcfb135723d46ecae05829b2df8c58

ci/cd testing also added.
