### ISSUE TITLE
[Feature]: Need a specific log on UI for Cache Miss/Hit

### ISSUE THREAD

**Issue by Soumen96SC** [BerriAI/litellm#3057]
### The Feature

We were looking to monitor cache hits and misses. However, we were unable to locate a specific log or tracker on litellm that indicates whether our requests are being cached and reused. Even keeping track of the number of model requests did not provide much assistance in this situation, as it increased with every request and led us astray. Therefore, we would like to request a dedicated tracker for the cache.

### Motivation, pitch

We are working on an application which uses multiple LLM hosts. So to stream line this we are interested to use the proxy server of litellm.

**Comment by ishaan-jaff** [comment]
@Soumen96SC this is live on main-latest 

@Soumen96SC any chance we can hop on a call ? I'd love to learn how how we can improve litellm for you.

My linkedin if you prefer DMs: https://www.linkedin.com/in/reffajnaahsi/ 
Sharing a link to my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

<img width="1360" alt="Xnapper-2024-06-21-15 22 47" src="https://github.com/BerriAI/litellm/assets/29436595/15257d33-ffc6-426b-bbf6-1d86dc22915f">
