### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by ncecere** [BerriAI/litellm#3059]
### The Feature

I would like the ability to update user information, like the budget via the API.  

### Motivation, pitch

This would help with automation and allow for user self service.  currently the only way to update user information is via the database.

**Comment by ghost** [comment]
closing as this is already supported in `/user/update` 

also pushed a fix to update the docstring for it - https://github.com/BerriAI/litellm/commit/51a02de4cf4b9660711862bca942b0bb8f94ba43
