### ISSUE TITLE
[Feature]: Support vertex ai embeddings outputDimensionality param

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#3063]
### The Feature

New vertex ai embeddings models support an 'outputDimensionality' param

This is similar to the openai dimensions param

it allows controlling the output embedding size 

### Motivation, pitch

openai compatibility for vertex ai

**Comment by ghost** [comment]
closed as this is now supported - https://docs.litellm.ai/docs/providers/vertex#advanced-use-task_type-and-title-vertex-specific-params
