### ISSUE TITLE
[Feature]: Add Claude 3 Opus on Bedrock

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#3068]
### The Feature

https://twitter.com/AnthropicAI/status/1780269789661065453

### Motivation, pitch

Cause why not. :) 

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by ghost** [comment]
i believe all that's needed here is to add it to the model cost map

**Comment by Manouchehri** [comment]
yep, that's correct. I'm just fighting with Git to bring our fork back up to date at the moment.

**Comment by Manouchehri** [comment]
```
aws bedrock-runtime invoke-model \
--model-id anthropic.claude-3-opus-20240229-v1:0 \
--body "{\"messages\":[{\"role\":\"user\",\"content\":[{\"type\":\"text\",\"text\":\"asdf\"}]}],\"anthropic_version\":\"bedrock-2023-05-31\",\"max_tokens\":2000,\"temperature\":1,\"top_k\":250,\"top_p\":0.999,\"stop_sequences\":[\"\\n\\nHuman:\"]}" \
--cli-binary-format raw-in-base64-out \
--region us-west-2 \
invoke-model-output.txt
```
