### ISSUE TITLE
UI - key info modal shows black screen

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#3070]

**Comment by ghost** [comment]
<img width="1048" alt="Screenshot 2024-04-16 at 11 31 31 AM" src="https://github.com/BerriAI/litellm/assets/17561003/4663be0a-9fc9-4e3d-bdc4-3c2243dcb120">

**Comment by ishaan-jaff** [comment]
oh no :(

**Comment by ishaan-jaff** [comment]
fixed on main latest
