### ISSUE TITLE
Map the finish reason as well 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#308]
**Describe the solution you'd like**
Today, we only map the completion text, but not the finish reason. This is being used by users (e.g. @yujonglee) for handling response / providing certain kinds of feedback to users.
 
<img width="607" alt="Screenshot 2023-09-09 at 11 49 05 AM" src="https://github.com/BerriAI/litellm/assets/17561003/b8e5fad0-7898-4d05-a2aa-0e0bd1d9dade">

**Comment by yujonglee** [comment]
I didn't know it is not mapped! Good to see issue opened.

**Comment by ghost** [comment]
- [x] Anthropic
- [x] AI21 
- [x] Cohere
- [ ] Aleph Alpha ❌ their website is down 
- [x] TogetherAI 
- [x] Huggingface TGI

**Comment by ghost** [comment]
@yujonglee this should now be mapped for most providers. If not, it will default to the openai finish_reason - 'stop'.

If there's any that you're using, and we're missing coverage for - please let me know.

**Comment by ghost** [comment]
Providers we still need to add support for: 
- [x] Aleph Alpha 
- [ ] Replicate  ❌ doesn't return a finish reason 
- [ ] AWS Sagemaker ❌ doesn't return a finish reason 
- [x] Baseten
- [ ] Google Palm/Vertex AI  ❌ doesn't return a finish reason

**Comment by ghost** [comment]
closing issue as all remaining providers either mapped or don't return a finish reason

**Comment by yujonglee** [comment]
@krrishdholakia  Thank you
