### ISSUE TITLE
[Feature]:  Support vision for GPT-4 Turbo

### ISSUE THREAD

**Issue by pbarker** [BerriAI/litellm#3080]
### The Feature

Vision is now supported for gpt-4 turbo, it appears litellm, at least from the docs, does not yet support this

### Motivation, pitch

This is an upgrade to the preview model in a number of areas

### Twitter / LinkedIn details

https://www.linkedin.com/in/patrickbarkerco/

**Comment by ishaan-jaff** [comment]
@pbarker what doc did you look at for this ?

**Comment by ghost** [comment]
<img width="998" alt="Screenshot 2024-04-16 at 5 36 54 PM" src="https://github.com/BerriAI/litellm/assets/17561003/a45b1acf-261d-4d5b-8f28-43fb181ebc5e">

i see this on the openai docs - https://platform.openai.com/docs/guides/vision

@ishaan-jaff

**Comment by ghost** [comment]
Seeing the code now @pbarker, i believe it should work if you just say 

```python
import os 
from litellm import completion

os.environ["OPENAI_API_KEY"] = "your-api-key"

# openai call
response = completion(
    model = "gpt-4-turbo", 
    messages=[
        {
            "role": "user",
            "content": [
                            {
                                "type": "text",
                                "text": "What’s in this image?"
                            },
                            {
                                "type": "image_url",
                                "image_url": {
                                "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/2560px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg"
                                }
                            }
                        ]
        }
    ],
)

```

**Comment by ghost** [comment]
@pbarker can confirm this works for me

Updated docs with this as well - https://github.com/BerriAI/litellm/commit/96e995f53b1aa992e37f72763f44af605e284c76


<img width="1428" alt="Screenshot 2024-04-16 at 5 44 29 PM" src="https://github.com/BerriAI/litellm/assets/17561003/3b248679-b011-4a25-8b94-8f68be521e5a">

**Comment by pbarker** [comment]
thank you for the speedy fix!
