### ISSUE TITLE
[Feature]: Slack Alerting - Show model group, model name, region/api base url on failed message slack alerts

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#3083]
### The Feature

> Message: LLM API call failed: VertexAIException - Error code: 500 - {'error': {'code': 500, 'message': 'Internal error encountered.', 'status': 'INTERNAL'}}

^ e.g. 

### Motivation, pitch

user request

### Twitter / LinkedIn details

cc: @dkindlund

**Comment by ishaan-jaff** [comment]
this is done
