### ISSUE TITLE
[Bug]: Unable to fetch the models list after creating models

### ISSUE THREAD

**Issue by anant996** [BerriAI/litellm#3095]
### What happened?

I was running postgres via docker, then i used this docker command to run proxy server at port 4000 
```
docker run --name litellm-proxy \
-e DATABASE_URL=postgresql://<user>:<password>@<host>:<port>/<dbname> \
-p 4000:4000 \
ghcr.io/berriai/litellm-database:main-latest --config your_config.yaml
```

In my config.yaml, i am having model related details
```
model_list: 
  - model_name: gpt-3.5-turbo # user-facing model alias
    litellm_params: # all params accepted by litellm.completion() - https://docs.litellm.ai/docs/completion/input
      model: azure/<deployment_name>
      api_base: <api_base_url>
      api_key: <api_key>
```

I was not able to set the values of LITELLM_MASTER_KEY, UI_USERNAME, UI_PASSWORD in env, so i set these while running the docker
so my final command looked like this:
`docker run --network host --name litellm-proxy-15 -e LITELLM_MASTER_KEY=sk-1234 -e UI_USERNAME=root -e UI_PASSWORD=admin -e STORE_MODEL_IN_DB=True -e DATABASE_URL=postgresql://<user>:<password>@<host>:<port>/<dbname>-p 4000:4000 ghcr.io/berriai/litellm-database:main-latest --config config.yaml`

I was able to login to the proxy server using the credentials i set while running docker command
With this config file i didn't find my model on the ui, is there anything wrong?
Also when i created the model, the ui displayed "Model created successfully. Wait 60s and refresh on All Models page"
But when i went to All models page, no model was created

Attaching screenshot for model creation and the relevant log output. 
![litellm](https://github.com/BerriAI/litellm/assets/139758290/ba78b91d-357e-4551-b42f-4abac8302407)

### Relevant log output

```shell
17:07:32 - LiteLLM Proxy:ERROR: proxy_server.py:2625 - 'Router' object has no attribute 'model_list'
Traceback:Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 2558, in add_deployment
    await self._delete_deployment(db_models=new_models)
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 2484, in _delete_deployment
    router_model_ids = llm_router.get_model_ids()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2323, in get_model_ids
    for model in self.model_list:
                 ^^^^^^^^^^^^^^^
AttributeError: 'Router' object has no attribute 'model_list'
```

**Comment by amit10may** [comment]
@krrishdholakia @ishaan-jaff any tips/hints?

**Comment by ghost** [comment]
hey @amit10may this should be fixed in the latest release of litellm. let me know if this issue persists.
