### ISSUE TITLE
get_model_info() doesn't seem to accept fully qualified model names like completion() does?

### ISSUE THREAD

**Issue by paul-gauthier** [BerriAI/litellm#3100]
### What happened?

I am unclear about the expected way to name models in litellm, as different functions seem to accept different names for the same models.

For example, I can use the `completion()` function with a fully qualified model name like `anthropic/claude-3-opus-20240229`, which has the provider and the model name specified. Or I can simply use a partially specified model name like `claude-3-opus-20240229`. The `completion()` function seems happy either way.

The `get_model_info()` function will *only* accept the partial `claude-3-opus-20240229` model name. If I use the fully qualified `anthropic/claude-3-opus-20240229` it throws an exception that the model is not mapped yet.

I get the same behavior for `gpt-4-turbo` and `openai/gpt-4-turbo`.

Is this expected? Is there a recommended method to get the model info for a fully qualified model name?

```
import litellm

messages = [{ "content": "Hello, how are you?","role": "user"}]

model = "claude-3-opus-20240229"
response = litellm.completion(model=model, messages=messages)
print(response) # prints out the ModelResponse
print(litellm.get_model_info(model)) # prints out the model_cost dict entry

model = "anthropic/claude-3-opus-20240229"
response = litellm.completion(model=model, messages=messages)
print(response) # prints out the ModelResponse
print(litellm.get_model_info(model)) # throws "Exception: This model isn't mapped yet."
```

**Comment by ghost** [comment]
acknowledging the issue. Will try to have this fixed by EOD. @paul-gauthier

**Comment by ghost** [comment]
fixed + testing added - https://github.com/BerriAI/litellm/commit/53df916f69416c9e556649453b88037cb80cec66

Should be live soon in v`1.35.11+` @paul-gauthier

**Comment by paul-gauthier** [comment]
I updated to 1.35.12 and can confirm this works as expected now. Thanks for the quick fix.
