### ISSUE TITLE
have easier tutorials on docs ❤️

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#311]
**Describe the solution you'd like**
All the tutorials feel like they're super advanced. I just need a simple tutorial / walkthrough of the things i can do with litellm.

**Comment by ishaan-jaff** [comment]
Feature request 
- [ ] Tutorial on migrating from openai.ChatCompletion to litellm.completion

**Comment by ishaan-jaff** [comment]
https://docs.litellm.ai/docs/tutorials/azure_openai

**Comment by ghost** [comment]
@ishaan-jaff could you add some text explaining what's happening in the code blocks? 

Since this a tutorial - a walkthrough would be helpful.

**Comment by ghost** [comment]
also made a quick change renaming the title to replacing openai chatcompletion with litellm

as that's what i think? you're trying to show and it felt simpler to me. Please change it, if not.
