### ISSUE TITLE
Regenerate an API keys

### ISSUE THREAD

**Issue by slmagus** [BerriAI/litellm#3119]
### The Feature

Add a feature to enable users to regenerate API keys. 

This is probably mostly UI feature as you've already have apis for generating keys you just need to enable button to regenerate the key and display the new one as if it were in your key.

### Motivation, pitch

This is a pretty standard feature and allows the configuration for a key to remain while allowing users to regenerate a key if they forgot it or it expires or in case of compromise.

### Twitter / LinkedIn details

@slmagus

**Comment by ghost** [comment]
so the underlying call would be a `/key/generate` call - but the ui flow would just be a 1-click experience vs. the create new form? 

@slmagus

**Comment by ghost** [comment]
cc: @ishaan-jaff

**Comment by ghost** [comment]
i guess it should also run `/key/delete` to remove the old key

**Comment by slmagus** [comment]
> so the underlying call would be a `/key/generate` call - but the ui flow would just be a 1-click experience vs. the create new form? 
> 
> @slmagus 

Correct a regenerate token button that displays the new key dialog box.

**Comment by ishaan-jaff** [comment]
Picking this up: 

V0 scope:
- /key/generate(sk-12345) 
    - sk-12345 stops working 
    - sk-12-new is regenerated key, has the same team_id, key_alias, models etc

Spend, Caching should be tracked with this key
- Caching:
    - it calls /global/activity/cache_hits which uses a "key_alias" 
        -> rengenerated key should have same key alias 
- Spend tracking
    - New key -> same spend and same max budget as old key

**Comment by slmagus** [comment]
Can you make a function to just update the value in the database with a new secret string?
Copying the the settings to a new key means you have all these extra keys in the database and you got to deal with that at some point. 



In the case that you don't have a database I don't know how you're storing this information generally but I would imagine it's just another object in memory that needs to be manipulated.

**Comment by ishaan-jaff** [comment]
> Can you make a function to just update the value in the database with a new secret string?

Sure, I like your suggestion more, it's simpler. Going with this
