### ISSUE TITLE
Add eviction policy for Redis cache

### ISSUE THREAD

**Issue by yujonglee** [BerriAI/litellm#313]
**Describe the solution you'd like**

We need some kind of eviction otherwise it can be a potential problem in server-side litellm like proxy.

For example, `GPTCache` has it. 
https://gptcache.readthedocs.io/en/latest/references/manager.html?highlight=eviction#module-gptcache.manager.eviction.base

**Comment by yujonglee** [comment]
Before we have it in LiteLLM, if anyone want it - Upstash has built-in support.
https://upstash.com/docs/redis/features/eviction

**Comment by ghost** [comment]
Hey @yujonglee,
- are you referring to the gptcache / litellm integration? 
- is there something preventing the usage of the gptcache integration for this?

**Comment by yujonglee** [comment]
@krrishdholakia  Yes, GPTCache has it, but LiteLLM's own cache does not.

In [fastrepl/proxy](https://github.com/fastrepl/proxy/) I am using LiteLLM's cache.

https://github.com/fastrepl/proxy/blob/495f8f2041ef6d478f9b4cafab825292a99d79ce/proxy/llm.py#L12-L36
@ishaan-jaff The above code is there thanks for your help. :) Do you think I can get same functionality with GPTCache?

**Comment by ishaan-jaff** [comment]
@yujonglee can we add upstash to litellm to handle this for us ? looks like upstash supports redis cache too

**Comment by yujonglee** [comment]
@ishaan-jaff  Actually the usage of Upstash is same as Redis, so I can just use it without modification of LiteLLM.

**Comment by ishaan-jaff** [comment]
good to know, would you recommend any action items for this issue in that case then ? @yujonglee

**Comment by yujonglee** [comment]
@ishaan-jaff  No fine. We can close it.

**Comment by ishaan-jaff** [comment]
awesome - sg
