### ISSUE TITLE
[Feature]: Support embedding model from Gemini - Google AI Studio

### ISSUE THREAD

**Issue by demux79** [BerriAI/litellm#3134]
### The Feature

Maybe I am reading this wrong but it sounds like the Google AI Studio is offering their latest embedding model via api.

<img width="855" alt="image" src="https://github.com/BerriAI/litellm/assets/14108031/a73d9e71-4af0-4b5f-87d6-4ccb3ba14142">

Source: https://ai.google.dev/gemini-api/docs/models/gemini#embedding

### Motivation, pitch

It would be nice to add it to the supported models if it actually exists.

**Comment by ishaan-jaff** [comment]
live https://docs.litellm.ai/docs/providers/vertex#embedding-models
