### ISSUE TITLE
[Bug]:  native vertex ai (non-claude) token usage doesn't work for streaming content without if-block.

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#3155]
### What happened?

line 9596 in utils.py, adds 
```
                            if hasattr(chunk._raw_response, "usage_metadata"):
                                model_response.usage.prompt_tokens = chunk._raw_response.usage_metadata.prompt_token_count
                                model_response.usage.completion_tokens = chunk._raw_response.usage_metadata.candidates_token_count
                                model_response.usage.total_tokens = chunk._raw_response.usage_metadata.total_token_count
```
As otherwise it won't capture the token usage metadata from the vertex AI inference, using models like gemini-pro-1.5. It was otherwise skipping the metadata and using the gpt-3.5 tokenizer to estimate (badly) token counts. As there is no client side tokenizer for gemini models, this is the only way to get accurate token consumption counts on gemini pro models.

### Twitter / LinkedIn details

sean ward

**Comment by ghost** [comment]
fixed
