### ISSUE TITLE
Add mock provider responses for unit testing

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#316]
**Describe the solution you'd like**
Customer request: add the ability to return mock responses with litellm. 

E.g. 

```
res = completion.complete(model, messages, stream=True, test=True, test_response='Some output')

for chunk in reponse:
    print(chunk['choices'][0]['delta'])

```

**Comment by ghost** [comment]
Open Questions: 
- should the response be mocked at the top or do you expect it to flow through litellm's e2e pipes?
- what's the purpose?

**Comment by toniengelhardt** [comment]
Maybe it could be simplified to

```python
res = completion.complete(model, messages, stream=True, mock_response='Some output')
```

or something like that...

Ideally it would go through as much of LiteLLM e2e pipes as possible (and validate args/kwargs) without actually sending a request to the LLM API to test possible exceptions, etc. as well.

The purpose is, when you integrate the LiteLLM SDK in your code and want to e2e- or unit test code that uses the `complete` method, that you can do so without incurring cost or delays from the real LLM API.

It should mimic the exact behavior of the function, with chunk generator if `stream=True`, etc.

**Comment by ghost** [comment]
closing as this is now available via mock_completion() 

@toniengelhardt please re-open in case you find something missing https://docs.litellm.ai/docs/budget_manager
