### ISSUE TITLE
[Bug]: Duplicate models when adding a new model in UI

### ISSUE THREAD

**Issue by anhphong22** [BerriAI/litellm#3160]
### What happened?

**Litellm Version**: `v1.35.15`
**Description:**
- Adding a new model via UI (Azure Models), multiple duplicated models will be written in DB. That leads to save single model in several ids in db.
- This is a critical bug I think so @krrishdholakia

**Comment by ghost** [comment]
thanks for this @anhphong22 aiming to have this fixed by EOD

**Comment by ghost** [comment]
@anhphong22 i think we've dealt with this before, this looks like a regression. 

Would love to add unit tests for the UI. Would you be able to help here?

**Comment by ghost** [comment]
fixed in #3260
