### ISSUE TITLE
[Bug]: Teams created using the API don't show up in the dashboard

### ISSUE THREAD

**Issue by databill86** [BerriAI/litellm#3165]
`litellm` used: `image: ghcr.io/berriai/litellm:main-v1.35.12`

### What happened?

When I create teams using the API, they don't show up in the dashboard, even after restarting the docker service. 

here is an example of what's done: 

```
 curl -X 'POST'   'http://localhost:4004/team/new'   -H 'accept: application/json' --header 'Authorization: Bearer sk-litellm-1234'   -H 'Content-Type: application/json'   -d '{
  "team_alias": "test",
  "team_id": "test-show" 
}'  
```

### Relevant log output

Response:  
```shell

{"team_alias":"test","team_id":"test-show","organization_id":null,"admins":[],"members":[],"members_with_roles":[{"role":"admin","user_id":"default_user_id","user_email":null}],"metadata":{},"tpm_limit":null,"rpm_limit":null,"max_budget":null,"models":[],"blocked":false,"spend":0.0,"max_parallel_requests":null,"budget_duration":null,"budget_reset_at":null,"model_id":null}
```

**Comment by ishaan-jaff** [comment]
@databill86 this is fixed - you can test it here https://staging.litellm.ai/ 
 
## Step 1. Create a new Team 

 curl -X 'POST'   'https://staging.litellm.ai/team/new'   -H 'accept: application/json' --header 'Authorization: Bearer sk-54d77cd67b9febbb'   -H 'Content-Type: application/json'   -d '{
  "team_alias": "test-github",
  "team_id": "uuid-github" 
}'  

## Step 2. login to Admin UI
Use the following credentials to view UI
- UI_USERNAME: ishaan-admin
- UI_PASSWORD: 54d77cd67b9febbbb78b8d3129da2038

## Step 3. See new Team on UI
<img width="1280" alt="Screenshot 2024-04-22 at 2 54 40 PM" src="https://github.com/BerriAI/litellm/assets/29436595/9bac3356-360c-45c8-bfa9-cc7df2265aad">


## Curious: @databill86 We're working on a hosted proxy is this something you'd want to use ?

**Comment by databill86** [comment]
Thanks, it's working now. 

@ishaan-jaff isn't litellm a hosted proxy already ? could you explain please what's this hosted proxy about ?

**Comment by ghost** [comment]
@databill86 i guess the q is - would you find it helpful if we managed your LiteLLM proxy deployment?

e.g. if it was hosted on our infra / available via aws marketplace, etc.

**Comment by databill86** [comment]
> @databill86 i guess the q is - would you find it helpful if we managed your LiteLLM proxy deployment?
> 
> e.g. if it was hosted on our infra / available via aws marketplace, etc.

For now, I prefer to host my own proxy internally.
