### ISSUE TITLE
[Bug]: Retrieving API Key from User Table

### ISSUE THREAD

**Issue by neel1549** [BerriAI/litellm#3172]
### What happened?

Not sure if this is a bug or not but the response from the /user/info GET endpoint obscures the api_key(sk-....). My application is using okta auth where I get the email and create a Lite LLM user with that email. I want to retrieve the api key from somewhere to have each user be using their own api key when running the app. How do I get around this?  Thanks in advance!

**Comment by ghost** [comment]
hey @neel1549 

the db doesn't store the key - it stores a hash. 

So the best way to do that would be by storing the keys yourself **or** using jwt-auth https://docs.litellm.ai/docs/proxy/token_auth

**Comment by ghost** [comment]
if you want to talk through this, happy to hop on a call - https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
