### ISSUE TITLE
Show VertexAI api_base, location and project in Vertex `Requests are hanging` Alert

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#3177]

**Comment by ghost** [comment]
@ishaan-jaff you can use `get_api_base()` for this. I wrote it for this 

```python
api_base = litellm.get_api_base(model=model, optional_params=litellm_params)
```

code: https://github.com/BerriAI/litellm/blob/ad05cce8b7276a282275e4552a945cf4cf27bf01/litellm/utils.py#L5398

Example: https://github.com/BerriAI/litellm/blob/ad05cce8b7276a282275e4552a945cf4cf27bf01/litellm/tests/test_alerting.py#L19

**Comment by ishaan-jaff** [comment]
we do this now
