### ISSUE TITLE
[Bug]: LiteLLM Proxy uses cache for completion even if model is different, no-cache parameter does not work

### ISSUE THREAD

**Issue by demux79** [BerriAI/litellm#3199]
### What happened?

1. If I repeat the same prompt but use a different model the cache is used. I would expect the cache only to trigger if the same model is used as the outcome can be quite different depending on model.

Reason: I first trigger a prompt with a cheap/fast model and if I am not happy with the result I trigger it again with a more sophisticated model. But I get the same response back via cache.

2. I am unable to disable cache on demand via curl. `"no-cache": True` it is getting ignored. Only if I add `"s-maxage": 1` I get rid of the cache. 
```
extra_body = {        # OpenAI python accepts extra args in extra_body
        cache: {
          "no-cache": True # will not return a cached response 
      }
    }
```

**Comment by Manouchehri** [comment]
I was running into a similar issue of `no-cache` not working.

**Comment by ghost** [comment]
> If I repeat the same prompt but use a different model the cache is used. I would expect the cache only to trigger if the same model is used as the outcome can be quite different depending on model.


Hey @demux79 this shouldn't be possible since the cache key includes model name, is this for models with the same 'model_name' ?

https://github.com/BerriAI/litellm/blob/305d52614077c6f34efe3db3aeedc2bb0ed70542/litellm/caching.py#L1539

**Comment by AdithyanI** [comment]
This bug is still there for me. 

>           "no-cache": True # will not return a cached response 

I pulled the fastest docker image. And setting this will still return a cached response to me.

**Comment by ghost** [comment]
hey @AdithyanI unable to repro on my end. could you share your server logs?

**Comment by Manouchehri** [comment]
I am not running into the `no-cache` issue anymore from what I can tell.

**Comment by ghost** [comment]
closing then. as this might be a version issue.
