### ISSUE TITLE
[Feature]: Add IBM watsonx Support

### ISSUE THREAD

**Issue by h0rv** [BerriAI/litellm#3204]
### The Feature

Add IBM watsonx support

### Motivation, pitch

Give watsonx access to more tools, specifically (for me) https://github.com/jxnl/instructor/pull/620 compatibility.

### Twitter / LinkedIn details

https://www.linkedin.com/in/robby-horvath/

**Comment by ghost** [comment]
hey @h0rv i believe somebody else from IBM is also working on a PR for this

**Comment by h0rv** [comment]
Hi @krrishdholakia, I searched the repo and did not see any mentions along with discord. 
Do you have a link to where someone said they would implement this? Thanks.

**Comment by h0rv** [comment]
Also, @krrishdholakia I am new to LiteLLM. For the implementation, can I import the watsonx python pkg (which adds it as an optional dependency) or call the API's directly via requests/httpx?

**Comment by ghost** [comment]
Hi @h0rv, wanted to follow up on this. 

Can you chat for ~10 minutes this week? 

Would love to learn how we can improve litellm for your use-case! 

https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by h0rv** [comment]
Hi @krrishdholakia, I mostly wanted to add support for instructor, and LiteLLM seemed like the best approach which would also have other benefits of opening up support for other tools in the LiteLLM ecosystem. I don't have any other use cases for LiteLLM besides instructor use at the moment, but I will reach out if that changes! Thanks!

**Comment by ghost** [comment]
@h0rv i didn't think watsonx supported tool calling? How do you use instructor here 

<img width="960" alt="Screenshot 2024-05-01 at 11 42 13 AM" src="https://github.com/BerriAI/litellm/assets/17561003/8f5a1315-e4d2-4073-9ada-9f325068ea52">

**Comment by h0rv** [comment]
It doesn't but there is tricks to to tell the model to produce json or put it in a code block ```json, which can be extracted. Obviously is sub-optimal solution, so it requires retries, or sending back to the model the errored response, telling it to fix it based on the JSON parse error, etc.

All this functionality is abstracted away by instructor which is really great, so it could work pretty reliably even with API/models that don't support JSON mode or function calling natively

**Comment by h0rv** [comment]
Here is the link to the docs I added to instructor: https://python.useinstructor.com/examples/watsonx/?h=wa#example

Hope this helps 🙂
