### ISSUE TITLE
Allow users to use a local version of max_tokens and cost.json 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#321]
This is currently a hosted file, open interpreter wants to use a local file for their project 

" it looks like litellm tries to download a github file with the costs of various llms. trying to make our thing local so any way to turn this off? shows an error"

**Comment by ghost** [comment]
what was the outcome here @ishaan-jaff

**Comment by ghost** [comment]
@ishaan-jaff can we close this?
