### ISSUE TITLE
[Feature]: Vertex AI - support `tool_choice` for real

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#3235]
### The Feature

https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/function-calling#functioncallingconfig-[preview]

### Motivation, pitch

To be able to control what tool gets used.

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by Manouchehri** [comment]
Eh, probably gonna wait to add this until for the httpx refactor like #2973.

**Comment by ghost** [comment]
closing as this is now supported
