### ISSUE TITLE
[Feature]: Fix + Add testing for Usage in OpenAI Streaming Responses 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#3237]
### The Feature

OpenAI does not return `usage` for streaming responses but litellm returns empty dicts for usage 

- we should match the same format as OpenAI 
- Add unit testing to assert the chunks from litellm == chunks from OpenAI (specifically for usage) 

### Motivation, pitch

-

**Comment by ghost** [comment]
@ishaan-jaff i think their api response has changed. In our testing we should check for that.
