### ISSUE TITLE
[Bug]: Vertex AI - Function Calling isn't logged properly

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#3241]
### What happened?

This will likely be fixed by itself when #3240 is completed.

<img width="758" alt="image" src="https://github.com/BerriAI/litellm/assets/7232674/c4c96148-2a67-43ea-9d20-5708e251ce15">

### Twitter / LinkedIn details

https://twitter.com/DaveManouchehri

**Comment by ghost** [comment]
live now in `vertex_ai_beta/` routes
