### ISSUE TITLE
[Feature]: Azure OpenAI - Log `content_filter_results`

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#3243]
### The Feature

Similar to #3230, it would be great if we could include the `content_filter_results` fields in the logs.

https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/content-filter?tabs=warning%2Cpython-new#sample-response-stream-passes-filters

### Motivation, pitch

Knowing why/when your prompts are filtered is useful during prompt engineering.

### Twitter / LinkedIn details

https://twitter.com/DaveManouchehri

**Comment by ishaan-jaff** [comment]
@Manouchehri logged on langfuse right ?

**Comment by Manouchehri** [comment]
Yeah, and returned to the client who is using LiteLLM as well.

**Comment by ghost** [comment]
we now return prompt filter and content filter results from azure - relevant commit - https://github.com/BerriAI/litellm/commit/09ee8c6e2dc41ffe461d97a49746925446dd1b0f
