### ISSUE TITLE
[Bug]: admin.litellm.ai shows full-screen error after 3-4 seconds, meaning it's fully broken

### ISSUE THREAD

**Issue by AshSourceTable** [BerriAI/litellm#3248]
### What happened?

1. Go to admin.litellm.ai or admin.litellm.ai/[unique_key]
2. Wait 3-4 seconds.
3. Page changes to a full-screen error: "Application error: a client-side exception has occurred (see the browser console for more information)."

Console shows two errors:

`GET https://odbedhwumqldbacdqomo.supabase.co/rest/v1/test_table?select=*&user_email=eq.6d383c99-488d-481d-aa1b-1f94935cec44&order=created_at.desc&limit=1000 500 (Internal Server Error)`

`TypeError: Cannot read properties of null (reading 'props')`

The first may be causing the second -- not sure.

### Relevant log output

```shell
GET https://odbedhwumqldbacdqomo.supabase.co/rest/v1/test_table?select=*&user_email=eq.6d383c99-488d-481d-aa1b-1f94935cec44&order=created_at.desc&limit=1000 500 (Internal Server Error)

{
    "code": "57014",
    "details": null,
    "hint": null,
    "message": "canceling statement due to statement timeout"
}
```

**Comment by ghost** [comment]
@AshSourceTable admin.litellm.ai is deprecated. Where did you find it?

**Comment by AshSourceTable** [comment]
@krrishdholakia here:
https://litellm.vercel.app/docs/debugging/hosted_debugging

Is there an alternative? Thanks!

**Comment by ghost** [comment]
We recommend using other logging solutions - https://litellm.vercel.app/docs/observability/langfuse_integration
