### ISSUE TITLE
[Feature]: OpenAI Batches Endpoint Support 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#3251]
### The Feature

creating a parent ticket to track openai batches endpoint day-1 support 

### Motivation, pitch

being a good openai proxy solution 

Closed https://github.com/BerriAI/litellm/issues/3246, https://github.com/BerriAI/litellm/issues/3247

**Comment by Manouchehri** [comment]
Beat ya to it. =P https://github.com/BerriAI/litellm/issues/3247 <- already posted some of my thoughts on the config here.

**Comment by ishaan-jaff** [comment]
done https://docs.litellm.ai/docs/batches
