### ISSUE TITLE
Could you publish the version releases to github ?

### ISSUE THREAD

**Issue by happysalada** [BerriAI/litellm#327]
publishing versions to github, would make it much easier for linux distributions to use your package.
Thank you again for making the software!

**Comment by ishaan-jaff** [comment]
@happysalada we already publish releases - is there something we're not doing correctly ? 

I'm new to publishing releases please let me know if there's something we're doing incorrectly

**Comment by happysalada** [comment]
On the github interface, if you look at the releases, the last published was 574. The other ones dont appear as releases

**Comment by happysalada** [comment]
This is the last one that is under github releases https://github.com/BerriAI/litellm/releases/tag/v0.1.574
Probably the other ones are not tagged ?

**Comment by ghost** [comment]
that looks correct to me, do you need us to publish releases daily? 

How does the release on github help with usage on linux?

**Comment by happysalada** [comment]
I don't need releases daily, but latest stable one would be amazing.
I had a bug in open-interpreter that was caused by using the latest release published to github. So having the last one working would be amazing.
switching to 590 fixed it, so if you think this is stable enough, feel free to publish.

nixos is a linux flavor that takes the source code from github and builds the dependency. Updates are detected when new versions are published on github.
the whole idea behind it is that using the source code directly could reduce supply chain attacks and is more transparent for audit for anyone.

**Comment by ishaan-jaff** [comment]
for this issue can we consider an action item to automate releases for litellm every Friday

**Comment by ghost** [comment]
@happysalada ?

**Comment by happysalada** [comment]
Im happy with any mechanism that doesnt put too much burden on you but that publishes a stable release to github. Thank you for your consideration on this issue.

**Comment by ghost** [comment]
Sounds good - we'll stick to a Friday release cadence then. Closing this issue if there's no further updates. 

@happysalada would love to understand how we can further improve litellm for your use-case. DM'ed on linkedin but let me know if another way works better.
