### ISSUE TITLE
[Bug]: With a key with access to "All Team Models", list models returns just "all-team-models"

### ISSUE THREAD

**Issue by tylerbrandt** [BerriAI/litellm#3275]
### What happened?

# What happened

I was trying to use the OpenAI SDK `client.models.list` call (which uses `GET /v1/models`) to get a list of models available to a key, which had the default "All Team Models" setting but no team_id (Default Team) set (I hadn't actually created any teams). 

However, only a single model was returned, "all-team-models". Exploring further with the API, it looks like the key is persisted with a `models` property of `["all-team-models"]` which is why that happens (and furthermore, it behaves the same regardless of if there is a `team_id` or not, and whether the team in question has a limited model list or has access to all models), but it limits the usefulness of the above API. Additionally, there is no way (in the UI) to create a key which has access to _all models_ implicitly (what the UI displays as "all-proxy-models"). I was able to work around it by selecting all the models individually but that gets tedious. I can work around it by setting an empty `models` key in the `POST /key/generate` call but that's not allowed in the UI.

# What I expected to happen

Ideally, the setting of "all-team-models" would be dereferenced in the models list to the list of models assigned to the team (or all models, if there is no team_id).

Concretely, what I'd expect when v1/models or equivalent APIs are called:

For a key with an empty "models" list (ideally it'd be possible to create such a key in the UI but for now that is only possible using the API):

- [x] All models that exist are returned

For a key with "all-team-models" in the "models" list:

- [ ] With no `team_id` specified, all models that exist are returned
- [ ] With `team_id` specified, and that team's models list is empty ("All Proxy Models" in the UI), all models that exist are returned
- [ ] With `team_id` specified, and that team's models list is not empty, that team's models are returned

For a key with a non-empty "models" list that doesn't contain "all-team-models":

- [x] Only those models are returned

**Comment by ghost** [comment]
cc: @ishaan-jaff

**Comment by ghost** [comment]
this is now fixed @tylerbrandt

**Comment by primerano** [comment]
@krrishdholakia was it really fixed in #3045 -  it was listed but not checked off

![image](https://github.com/BerriAI/litellm/assets/148409/c0ee5506-377b-4ee7-b1ba-c1a36ce21e03)

@tylerbrandt are you seeing the fix?  I see the issue on 1.38.1

**Comment by ghost** [comment]
hey @primerano yes - it was fixed with this commit - https://github.com/BerriAI/litellm/commit/25a2f00db6fce76ed4a90f5fcf231d0784418b36

can you please upgrade and share if it persists

**Comment by primerano** [comment]
@krrishdholakia - thanks for the commit link.  I'll upgrade to a newer version and confirm it works.  Thanks

**Comment by primerano** [comment]
It is fixed.  I tested on 1.40.5.

**Comment by attilalaszlo** [comment]
it seems, there is a similar issue with 
`no-default-models`

This is the response I get for models endpoint:
```
{
    "data": [
        {
            "id": "no-default-models",
            "object": "model",
            "created": 1677610602,
            "owned_by": "openai"
        }
    ],
    "object": "list"
}
```
@krrishdholakia
