### ISSUE TITLE
[Feature]: Return streaming usage in response headers (proxy) 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#3285]
### The Feature

For the proxy - return the streaming usage in response headers 

this will allow the proxy to be compliant with openai sdk projects like vercel's which expect no streaming usage dict 

but still allow us to return the actual usage for providers that do give it (e.g. anthropic) 

### Motivation, pitch

allow people to see their usage

**Comment by ghost** [comment]
closing as 'stream_options' from openai now solves this
