### ISSUE TITLE
[Bug]: Admin UI stops working if proxy budget has been exceeded

### ISSUE THREAD

**Issue by antoniomdk** [BerriAI/litellm#3293]
### What happened?

If the global budget is exceeded, all the API endpoints throw a 401 error, so the admin UI does not show up anything.

```
{"error":{"message":"Authentication Error, ExceededBudget ...}}
```

Ideally, only the `/completions` and `/embeddings` endpoints should be protected against budget limits.

**Comment by ishaan-jaff** [comment]
Fix here https://github.com/BerriAI/litellm/pull/3335 

@antoniomdk curious, would you find it helpful if we managed your LiteLLM proxy deployment? 
e.g. if it was available through aws marketplace or Cloud Hosted
