### ISSUE TITLE
[Bug]: Gibberish output of Llama-3 models on AWS Bedrock

### ISSUE THREAD

**Issue by aswny** [BerriAI/litellm#3297]
### What happened?

Llama-3 models are not working properly on AWS Bedrock right now and output gibberish. Probably because the instruct models now follow a different template.

```python
response = client.chat.completions.create(
    model="llama-3-8b", 
    messages = [
        {
            "role": "user",
            "content": "hi"
        }
    ],
    max_tokens=16
)

print(response.choices[0].message.content)
```

### Relevant log output

```shell
K, et al. (2014). "A systematic review of the effectiveness
```

**Comment by Manouchehri** [comment]
I noticed this as well. It seems like the same for Llama 2 on Bedrock, not just Llama 3?

**Comment by aswny** [comment]
@Manouchehri I checked with Llama-3 and it's working fine now. Could you check with Llama-2 and let me know if that works too?
