### ISSUE TITLE
UX issue - make it clear you need to pass in huggingface/model provider before model name

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#331]
**Describe the solution you'd like**
<img width="1004" alt="Screenshot 2023-09-11 at 6 28 06 PM" src="https://github.com/BerriAI/litellm/assets/17561003/6d2b0ca5-55a0-4a46-9ef2-9e719a6b58bb">

**Comment by ghost** [comment]
<img width="1436" alt="Screenshot 2023-09-12 at 11 55 32 AM" src="https://github.com/BerriAI/litellm/assets/17561003/b87d91e4-83b4-4e80-a157-df6466825c7d">

done `v0.1.604` onwards
