### ISSUE TITLE
[Bug]: Logging to dynamo db did not work when using SDK

### ISSUE THREAD

**Issue by chakreshkolluru** [BerriAI/litellm#3313]
### What happened?

A bug happened!

I have defined litellm.success_callback as dynamo and passed dynamo db table name. Seems like dynamo db logger has initialized and don't see any logs in dynamo db table.

Code: - 
```
from litellm import completion
import litellm

litellm.set_verbose=True

#set callbacks
litellm.success_callback = ["dynamodb"] # log input/output to lunary, langfuse, supabase
litellm.dynamodb_table_name = "litellm-test"

#openai call
response = completion(model="gpt-3.5-turbo", messages=[{"role": "user", "content": "Hi 👋 - i'm openai"}])
print(response)
```

Anything i'm missing out ? Also i could not see logging to dynamodb section in callbacks [https://docs.litellm.ai/docs/observability/callbacks]. Does it only work when using openai proxy?

### Relevant log output

```shell
Got the llm response no log recorded in the dynamo db table. I have created the table with id as Partition key.
```

**Comment by chakreshkolluru** [comment]
I have tried logging to dynamodb using openai proxy and it worked. Does it work only for openai proxy and not for SDK? Please let me know

i can see dynamo db callback initialized in verbose output when using SDK
callback: dynamodb

But success callbacks: [] is empty after the request. But just for testing i have given athina in success_callback and it was coming in success_callbacks list after the request

**Comment by ishaan-jaff** [comment]
@chakreshkolluru any specific reason to use dynamoDB ? We recommend using langfuse in prod https://litellm.vercel.app/docs/observability/langfuse_integration

**Comment by ishaan-jaff** [comment]
closing as not planned
