### ISSUE TITLE
RateLimitError while using API key for the first time

### ISSUE THREAD

**Issue by blank-whitespace** [BerriAI/litellm#3314]
I'm trying to use my API key after purchasing 5$ worth of credits, during execution I'm getting a RateLimitError with no further indication to what went wrong.
[Receipt-2875-5160.pdf](https://github.com/BerriAI/litellm/files/15129490/Receipt-2875-5160.pdf)
![Screenshot 2024-04-26 161131](https://github.com/BerriAI/litellm/assets/89504443/cabe7cc8-f55e-4a49-a2af-418ace277b7e)

**Comment by ishaan-jaff** [comment]
this is not related to LiteLLM
