### ISSUE TITLE
[Bug]: Vertex AI async not working `safety_settings`?

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#3318]
in proxy mode, seems satety filter is not used in Proxy async completions

_Originally posted by @MichaelZhangCN in https://github.com/BerriAI/litellm/discussions/3287#discussioncomment-9231796_

**Comment by Manouchehri** [comment]
I haven't confirmed this myself, just making a ticket to track it.

**Comment by ghost** [comment]
duplicate #3311
