### ISSUE TITLE
Huggingface TGI Models inconsistent API - hf inference api accepts diff args than TGI 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#332]
What's the problem? (if there are multiple - list as bullet points)
<img width="1356" alt="Screenshot 2023-09-11 at 6 31 13 PM" src="https://github.com/BerriAI/litellm/assets/17561003/a06c2c00-6aa6-4c6d-8e41-ba11fb30d806">

**Comment by ghost** [comment]
fixed v0.1.600 onwards bab36c2c6fb4a25b4e4fd984403c6071c6c0b0f0
