### ISSUE TITLE
[Bug]: Replicate does not support the `version` field in the input

### ISSUE THREAD

**Issue by sabaimran** [BerriAI/litellm#3320]
### What happened?

Hey y'all, maybe Replicate recently made an API spec change on their end, but it looks like the `version` field isn't supported now. I'd suggest dropping this as input for the replicate flow?

### Relevant log output
LiteLLM's `POST` request:

```shell

test-litellm-litellm-1  | 06:18:22 - LiteLLM:INFO: utils.py:1205 -
test-litellm-litellm-1  |
test-litellm-litellm-1  | POST Request Sent from LiteLLM:
test-litellm-litellm-1  | curl -X POST \
test-litellm-litellm-1  | https://api.replicate.com/v1/models/meta/meta-llama-3-70b-instruct \
test-litellm-litellm-1  | -H 'Authorization: Token r*****************************' -H 'Content-Type: application/json' \
test-litellm-litellm-1  | -d '{'version': 'meta/meta-llama-3-70b-instruct', 'input': {'prompt': '<|begin_of_text|><|start_header_id|>user<|end_header_id|>what llm are you<|eot_id|>'}}'
test-litellm-litellm-1  |
test-litellm-litellm-1  |
```

Error logs:
```shell
test-litellm-litellm-1  |
test-litellm-litellm-1  | Traceback (most recent call last):
test-litellm-litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 1130, in completion
test-litellm-litellm-1  |     model_response = replicate.completion(
test-litellm-litellm-1  |                      ^^^^^^^^^^^^^^^^^^^^^
test-litellm-litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/llms/replicate.py", line 290, in completion
test-litellm-litellm-1  |     prediction_url = start_prediction(
test-litellm-litellm-1  |                      ^^^^^^^^^^^^^^^^^
test-litellm-litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/llms/replicate.py", line 137, in start_prediction
test-litellm-litellm-1  |     raise ReplicateError(
test-litellm-litellm-1  | litellm.llms.replicate.ReplicateError: Failed to start prediction {"detail":"- Additional property version is not allowed\n","status":422,"title":"Input validation failed","invalid_fields":[{"type":"additional_property_not_allowed","field":"","description":"Additional property version is not allowed"}]}
```

**Comment by suptejas** [comment]
I'm facing an issue due to the same. Would appreciate help with this. I'll also look into the underlying code and will try to PR if time permits.

**Comment by suptejas** [comment]
> I'm facing an issue due to the same. Would appreciate help with this. I'll also look into the underlying code and will try to PR if time permits.

Not sure if I'll be able to PR up even though I think I know the potential fix. Unable to get the local environment setup to repro this issue on local (stuck on a bunch of pydantic errors and weird behaviour when I set verbose=true)

**Comment by ghost** [comment]
This is fixed in latest - https://github.com/BerriAI/litellm/commit/93463565fb15a15e6b97a97c28f317996bba97ef

let me know if this issue persists for you in v`1.35.30` @sabaimran 

It passes for us on ci/cd - https://github.com/BerriAI/litellm/blob/2d976cfabcd85452a8718e6f9bdfdd19f5cf4ca4/litellm/tests/test_completion.py#L1813
