### ISSUE TITLE
[Feature]: ability to see how much capacity is remaining before hitting quota

### ISSUE THREAD

**Issue by amit10may** [BerriAI/litellm#3323]
### The Feature

some models like openai based ones allow retrieving details like what is the TPM or RPM quota thats used and whats time remaining to reset it  But using it is clumsy and often very model specific. If there is a model agnostic way LiteLLM can expose, it would be a nice add. Esp proactively avoid or route calls to other models/options. Better than hitting limits and then handling errors manually 

### Motivation, pitch

already shared in description

**Comment by ghost** [comment]
Hey @amit10may would you want this returned to you in the headers?

**Comment by ishaan-jaff** [comment]
bump on this @amit10may - do you want this returned in your response headers ?

**Comment by ishaan-jaff** [comment]
done on prometheus: https://docs.litellm.ai/docs/proxy/prometheus#llm-api--provider-metrics
