### ISSUE TITLE
[Feature request] Add credentials without changing environment variables

### ISSUE THREAD

**Issue by duc-phamh** [BerriAI/litellm#335]
**Describe the solution you'd like**

We are building a system with which multiple users would call LLM APIs using different integration. Therefore, if we store credentials as environment variables, there would be conflict between those users.

We would really appreciate if the `completion` function can be modified to take the credential as input, and not set it as environment variable.

**Comment by ghost** [comment]
Hey @duc-phamh this is possible already 

you can set api keys in multiple ways

- approach 1: litellm.api_key
- approach 2: litellm.openai_api_key, .. 
- approach 3: passing in during completion call - `completion(..., api_key="...")` <- this is probably what would work for your use-case i think

**Comment by ghost** [comment]
Let me know if this works for you, i'll wait before closing the issue. 

Also welcome to the community - https://discord.com/invite/wuPM9dRgDw 🎉

**Comment by ghost** [comment]
we've also exposed a new user-based rate limiting option, in case that's helpful to your use-case: https://docs.litellm.ai/docs/budget_manager

**Comment by duc-ph** [comment]
@krrishdholakia it worked, thank you Krish for your support, and for this lovely package!
