### ISSUE TITLE
[Bug]: Async streaming responses using custom callbacks has wrong kwargs sometimes

### ISSUE THREAD

**Issue by joch** [BerriAI/litellm#3352]
### What happened?

Hi!

If I'm using async streaming responses in a custom callback, I'm seeing som weird behavior. According to [the docs](https://docs.litellm.ai/docs/observability/custom_callback#custom-callback-to-track-costs-for-streaming--non-streaming), I'm supposed to do this:

```python
if "complete_streaming_response" in kwargs:
            completion_response=kwargs["complete_streaming_response"]
```

However, I'm seeing that when I'm using async streaming, _sometimes_ the response will look like the following:

```python
if "async_complete_streaming_response" in kwargs:
            completion_response=kwargs["async_complete_streaming_response"]
```

Not sure if this is a bug, or if the docs need updating however. :)

**Comment by ishaan-jaff** [comment]
@joch we actually return the cost in the callbacks now

**Comment by ishaan-jaff** [comment]
@joch would this solve your problem ? 

```python

# Step 1. Write your custom callback function
def track_cost_callback(
    kwargs,                 # kwargs to completion
    completion_response,    # response from completion
    start_time, end_time    # start/end time
):
    try:
        response_cost = kwargs["response_cost"] # litellm calculates response cost for you
        print("regular response_cost", response_cost)
    except:
        pass

# Step 2. Assign the custom callback function
litellm.success_callback = [track_cost_callback]

# Step 3. Make litellm.completion call
response = completion(
    model="gpt-3.5-turbo",
    messages=[
        {
            "role": "user",
            "content": "Hi 👋 - i'm openai"
        }
    ]
)

print(response)
```

**Comment by ishaan-jaff** [comment]
feel free to re-open the issue if not @joch

**Comment by joch** [comment]
@ishaan-jaff Thanks, that simplifies handling cost! We're doing other things in that callback as well (not related to litellm), but I have a good way of handling that now.
