### ISSUE TITLE
Document options for setting api keys 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#336]
**Describe the solution you'd like**
We provide 4 ways of doing this 
- environment variables 
- setting litellm.api_key
- setting litellm.<provider_name>_api_key (e.g. litellm.openai_api_key, litellm.anthropic_api_key, etc.)
- passing in dynamically via completion() call - e.g. completion(..., api_key="...")

This is missing from our docs, so needs to be added to it.

**Comment by ishaan-jaff** [comment]
done https://docs.litellm.ai/docs/set_keys
