### ISSUE TITLE
[Bug]: Table does not exist litellm-spend_logs:main-latest

### ISSUE THREAD

**Issue by superpoussin22** [BerriAI/litellm#3361]
### What happened?

when using litellm-spend_logs:main-latest to seperate logs , I got an error in the output :

### Relevant log output

```shell
Invalid `prisma.liteLLM_SpendLogs.createMany()` invocation in
/app/src/index.ts:41:38

  38   // Repeat for any other DateTime fields you may have
  39 }));
  40
→ 41 await prisma.liteLLM_SpendLogs.createMany(
The table `public.LiteLLM_SpendLogs` does not exist in the current database.
    at In.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:122:6854)
    at In.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:122:6188)
    at In.request (/app/node_modules/@prisma/client/runtime/library.js:122:5896)
    at async l (/app/node_modules/@prisma/client/runtime/library.js:127:11167)
    at Timeout.flushLogsToDb (/app/src/index.ts:41:7) {
  code: 'P2021',
  clientVersion: '5.13.0',
  meta: { modelName: 'LiteLLM_SpendLogs', table: 'public.LiteLLM_SpendLogs' }
}
```

**Comment by superpoussin22** [comment]
doing a prisma migrate dev --name init in the container solve the issue so missing in dockerfile

**Comment by ghost** [comment]
@superpoussin22  Unable to repro this. I can see it in the prisma schema and this works when deploying docker images locally + on aws/render/etc. 

Closing for now. Happy to reopen if you're able to provide a consistent repro for this.

**Comment by namitbhardwaj** [comment]
@krrishdholakia seeing this error whey trying to run with a different schema 

changed   database_url: "postgresql://postgres.wmucvqcydkwkblmzsdme:[PW]@[HOST]/postgres?schema=litellm"
in the config.yaml
