### ISSUE TITLE
[Feature]: Move bedrock calls to being *native* async

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#3368]
### The Feature

Currently async bedrock calls are made via boto3 which is sync (we wrap this). 

Move to making them directly via the httpx client handler https://github.com/BerriAI/litellm/blob/1cd24d890669a0a3e4f08ccbee2369abb8074d4b/litellm/llms/custom_httpx/http_handler.py#L8

### Motivation, pitch

Faster responses

**Comment by StefanKarlsson321** [comment]
Nice! Would it be possible also then to add all AWS credential details as function arguments, I mean to completion and acompletion :) As far as I understand boto3 needs them in env variables.

**Comment by ghost** [comment]
Any specific args? We already support dynamic credentials - https://docs.litellm.ai/docs/providers/bedrock#passing-credentials-as-parameters---completion

**Comment by StefanKarlsson321** [comment]
Oh, I have missed that part. That covers the arguments I was thinking of. Super nice! Thank's for the info. Will try it out immediately.

May I also ask if the plan is to implement "native" async bedrock in the near future, or far?

**Comment by ghost** [comment]
I would love to do it asap. Maybe we can try a v0 with the cohere command r bedrock implementation - will try and do it tomorrow. 

Would welcome a PR here, if you can work on it today @StefanKarlsson321

**Comment by ghost** [comment]
Would also love to learn how you're using litellm @StefanKarlsson321 

Can you do a ~10 min call this/next week? 


Attaching my calendly for convenience

**Comment by Manouchehri** [comment]
@krrishdholakia Before you do the httpx rewrite, could you merge in https://github.com/BerriAI/litellm/pull/3499? I touch Bedrock a little in that, and if you/we could do some cred caching, that'd be awesome. :)

**Comment by ghost** [comment]
Picking this up now. 

Found the bedrock url 
```
curl --location --request POST 'https://bedrock-runtime.us-east-1.amazonaws.com/model/cohere.command-text-v14/invoke' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--user "$AWS_ACCESS_KEY_ID":"$AWS_SECRET_ACCESS_KEY" \
--aws-sigv4 "aws:amz:us-east-1:bedrock" \
--data-raw '{
  "prompt": "Hi",
  "temperature": 0,
  "p": 0.9,
  "max_tokens": 4096
}'
```

**Comment by ghost** [comment]
Ok, i have a working sample 

```
import json
import os
from botocore.auth import SigV4Auth
from botocore.awsrequest import AWSRequest
from botocore.credentials import Credentials
import requests

os.environ["AWS_ACCESS_KEY_ID"] = "my-key-id"
os.environ["AWS_SECRET_ACCESS_KEY"] = "my-secret-access-key"

def post_request():
    credentials = Credentials(
        os.environ['AWS_ACCESS_KEY_ID'],
        os.environ['AWS_SECRET_ACCESS_KEY'],
        # os.environ['AWS_SESSION_TOKEN'],
    )

    sigv4 = SigV4Auth(credentials, 'bedrock', 'us-west-2')
    endpoint = 'https://bedrock-runtime.us-west-2.amazonaws.com/model/anthropic.claude-v2/invoke'
    data = json.dumps({
      "prompt": "\n\nHuman: explain black holes to 8th graders\n\nAssistant:",
      "max_tokens_to_sample": 300,
      "temperature": 0.1,
      "top_p": 0.9,
    })
    headers = {'Content-Type': 'application/json'}
    request = AWSRequest(method='POST', url=endpoint, data=data, headers=headers)
    sigv4.add_auth(request)
    prepped = request.prepare()

    response = requests.post(prepped.url, headers=prepped.headers, data=data)
    print("POST Request: {}".format(response.text))

post_request()
```
