### ISSUE TITLE
[Bug]: Error alerts sent to Slack are empty

### ISSUE THREAD

**Issue by taralika** [BerriAI/litellm#3395]
### What happened?

Error alerts sent to Slack are not helpful

When a bad request is made with say a bad model name such as:
```
curl --request POST \
  --url https://llm-proxy.xyz.com/chat/completions \
  --header 'Authorization: Bearer sk-llkj23jkl122' \
  --header 'Content-Type: application/json' \
  --data ' {
        "model": "bad-model-name",
        "messages": [{"role":"system","content":"you are a helpful assistant"},{"role":"user","content":"what is your name?"}]
    }'
```
as expected, response is `400 Bad Request`:
```
{
	"error": {
		"message": {
			"error": "Invalid model name passed in model=bad-model-name"
		},
		"type": "None",
		"param": "None",
		"code": 400
	}
}
```
however, the alert in Slack looks like this:
```
Level: High
Timestamp: 05:47:18
Message: LLM API call failed:
```

Expected alert in Slack would be:
```
Level: High
Timestamp: 05:47:18
Message: LLM API call failed: "Invalid model name passed in model=bad-model-name"
Key Alias: xyz-team-key
```
The `Message` should provide the error message and add the Key Alias so we know whose API calls are failing

**Comment by ghost** [comment]
Acknowledging. Will pick this up tomorrow. 

i think this happens b/c slack alerting doesn't cover rejected proxy requests yet. 

We instrumented it to catch failing llm api calls. 

@taralika curious, how do you use alerting for rejected requests?

**Comment by taralika** [comment]
> @taralika curious, how do you use alerting for rejected requests?

Great question! Your comment about rejected vs. failing requests makes me wonder if rejected requests should even raise any alerts. It might be better to not raise any alerts for rejected requests (which most likely are due to user error and ideally the request response message should be good enough to get the user back on track), at least not by default. You may let us override the alerting behavior in config by something like:
```
general_settings:
  alerting: ["slack"]
  alerting_include_rejected: True
```
