### ISSUE TITLE
No documentation on caching when using `litellm` as a Python library

### ISSUE THREAD

**Issue by prescod** [BerriAI/litellm#3396]
The code implies that there should be a URL like:

https://docs.litellm.ai/docs/caching

But there isn't.

https://github.com/BerriAI/litellm/blob/fa8a9568aa7e5406c055f33d148212e826fc42d1/litellm/__init__.py#L82C40-L83C1

**Comment by ghost** [comment]
here it is - https://docs.litellm.ai/docs/caching/redis_cache
