### ISSUE TITLE
httpx.Timeout -> timeout = float(timeout)

### ISSUE THREAD

**Issue by Ludwig-Graef** [BerriAI/litellm#3398]
@krrishdholakia 
I have tried to run the code. I ran into these problems:

1. In main.py (line 638): `timeout = float(timeout)` -> This breaks if the timeout is not set as float
2. in bedrock.py (line 595): `config = boto3.session.Config(connect_timeout=timeout, read_timeout=timeout)` -> This also breaks. We would need a check for the type and set it accordingly. 

These two are the only ones that I have tested. We might should add a test for this

_Originally posted by @Ludwig-Graef in https://github.com/BerriAI/litellm/issues/3162#issuecomment-2081996616_

**Comment by ghost** [comment]
in your case of passing in httpx.timeout, how would you expect the translation to work? @Ludwig-Graef

**Comment by Ludwig-Graef** [comment]
@krrishdholakia I want to provide httpx.Timeout(10.0, connect=60.0):

- For Azure, I want that the parameter is directly provided to `AsyncAzureOpenAI()`. Here: https://github.com/BerriAI/litellm/blob/c8ceab872fcb35e90cbfcbc62eb9dbfb43b5777c/litellm/llms/azure.py#L358
- For AWS Bedrock, I want to 
`if isinstance(timeout, httpx.Timeout):`
-> `config = boto3.session.Config(connect_timeout=timeout.connect, read_timeout=timeout.read)` 

Is this possible?

**Comment by ghost** [comment]
ok, that makes sense
