### ISSUE TITLE
Helper function to list all models user has access to 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#340]
**Describe the solution you'd like**
If users are providing keys + selecting models, you don't want to show models they don't have access to (poor UX). 

Expose a helper function to see what models they have access to - from Stan, Quivr

**Comment by ishaan-jaff** [comment]
+1 we got this same request from open-interpreter see: https://github.com/KillianLucas/open-interpreter/pull/288

**Comment by ishaan-jaff** [comment]
for open-interpreter the requirements is to just read the .env and return supported llms

**Comment by ishaan-jaff** [comment]
it's added - we should probably document these utils. they seem useful

**Comment by ishaan-jaff** [comment]
we have another util here too: https://github.com/BerriAI/litellm/pull/346

**Comment by ghost** [comment]
@ishaan-jaff closing this issue as it seems to be implemented, please re-open if not.
