### ISSUE TITLE
[Feature]: Support Amazon Titan Embeddings model V2 

### ISSUE THREAD

**Issue by tekumara** [BerriAI/litellm#3413]
### The Feature

Add support for amazon.titan-embed-text-v2:0 with vector sizes 1,024 (default), 384, 256.

See https://docs.aws.amazon.com/bedrock/latest/userguide/titan-embedding-models.html

### Motivation, pitch

These are latest and greatest Amazon embeddings which we'd like to use.

### Twitter / LinkedIn details

@tweeshan

**Comment by ishaan-jaff** [comment]
working on this :https://github.com/BerriAI/litellm/pull/3432

**Comment by ishaan-jaff** [comment]
@tekumara thanks so much for the issue! I'd love to get on a call and learn how we can improve litellm for you. If you can send me your email I'll setup a meeting

If it's easier - here's my calendly: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat?month=2024-05
if you prefer dms - here's my linkedin https://www.linkedin.com/in/reffajnaahsi/
