### ISSUE TITLE
[Feature]: Add support for Pydantic `Logfire` obeservability

### ISSUE THREAD

**Issue by homanp** [BerriAI/litellm#3414]
### The Feature

Would be amazing to add support for Pydantic's `Logfire` product.

### Motivation, pitch

`Logfire` has some benefits over other observability platforms, primarily in querying generations and traces. Would be good to add support to it. 

### Twitter / LinkedIn details

@pelaseyed

**Comment by elisalimli** [comment]
FYI @krrishdholakia @ishaan-jaff @homanp, I'm working on this.
