### ISSUE TITLE
[User Request] Don't fallback to .env for checking keys 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#344]
**Describe the solution you'd like**

Ref Studio does not want litellm to fallback to checking .env for keys 

See https://github.com/refstudio/refstudio/pull/525

**Comment by ghost** [comment]
i'm not sure i see the part where they talk about keys. 

What's the expected flow?

**Comment by ghost** [comment]
also - what does 'fallback' mean?
