### ISSUE TITLE
Update HuggingFace documentation

### ISSUE THREAD

**Issue by viswavi** [BerriAI/litellm#345]
The tutorial on https://docs.litellm.ai/docs/providers/huggingface incorrectly uses the `role_dict` parameter - looks like this has been renamed to `roles`.

**Comment by viswavi** [comment]
This tutorial also uses the keyword args `post_message_sep` and `pre_message_sep` which have been removed from the `litellm.register_prompt_template` implementation.

**Comment by ishaan-jaff** [comment]
cc @krrishdholakia

**Comment by ghost** [comment]
Looks like the tutorial was out of sync with code. I'll make the update.

Give me 20 minutes. I'll test and give you working code for this. @viswavi

**Comment by ghost** [comment]
This change also impacts
> together ai docs
> vllm docs

**Comment by viswavi** [comment]
@krrishdholakia 

I used these settings to get around this in the meanwhile:

<img width="1119" alt="Screenshot 2023-09-12 at 12 57 49 PM" src="https://github.com/BerriAI/litellm/assets/2577384/66d674e6-9360-416f-92de-6c21ba397009">

(source: https://twitter.com/vijaytarian/status/1701658999697899915)

**Comment by ghost** [comment]
Hey @viswavi that's interesting - we already provide support for Llama2 out of the box, any reason that didn't work for you?

**Comment by ghost** [comment]
https://github.com/BerriAI/litellm/blob/e6d48d91cefdf538286a363f6664481e5d8d4e21/litellm/llms/prompt_templates/factory.py#L5

**Comment by viswavi** [comment]
Oof I should have tried that before posting my tweet 🤦

**Comment by ghost** [comment]
HAHAH - no worries. I think our docs have a way to go. 

We'd love a PR for any prompt templates you'd like native support for!

**Comment by viswavi** [comment]
Yeah please document these nice prompt templates in the docs, since that's what I was using as a basis for my integration

**Comment by ghost** [comment]
docs updated - https://docs.litellm.ai/docs/providers/huggingface#custom-prompt-templates

**Comment by ghost** [comment]
Closing issue, but @viswavi please re-open if you think there's any gap / further details you'd like to see on the docs
