### ISSUE TITLE
FIY the mistral models referenced in your doc are deprecated

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [BerriAI/litellm#3466]
### What happened?

link to mistral: https://docs.mistral.ai/getting-started/models/

The list in your docs is not up to date: https://docs.litellm.ai/docs/providers/mistral#supported-models

**Comment by paneru-rajan** [comment]
Working on it

**Comment by paneru-rajan** [comment]
Thank you @thiswillbeyourgithub for pointing out, I've adjusted that. @krrishdholakia / @ishaan-jaff hading over to you for review+merge.

Pull-Request: https://github.com/BerriAI/litellm/pull/3471
