### ISSUE TITLE
[Bug]: Function calling with `Command R` on `Bedrock` not working. 

### ISSUE THREAD

**Issue by homanp** [BerriAI/litellm#3472]
### What happened?

Getting the following error when trying to run function calling with Command R on AWS Bedrock:

`BedrockException - bedrock does not support parameters {tools: ...}`

### Relevant log output

```shell
`BedrockException - bedrock does not support parameters {tools: ...}`
```

### Twitter / LinkedIn details

@pelaseyed

**Comment by Manouchehri** [comment]
I don't believe LiteLLM has added Command R/R+ support for Bedrock yet, see #3362. Even without `tools`, you'll get a `BedrockException`.

```sh
curl "${OPENAI_API_BASE}/chat/completions" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
    "model": "command-r",
    "messages": [
      {
        "role": "user",
        "content": "Hello!"
      }
    ],
  }' -v
```

**Comment by homanp** [comment]
Hmm, that makes sense then. Perhaps we will contribute this part then.

**Comment by ghost** [comment]
Closing in favour of - https://github.com/BerriAI/litellm/issues/3362
