### ISSUE TITLE
[Bug]: Prometheus seems broken

### ISSUE THREAD

**Issue by rjanovski** [BerriAI/litellm#3475]
### What happened?

followed the instructions of adding prometheus metrics:

      litellm_settings:
        success_callback: [ "prometheus" ]
        failure_callback: [ "prometheus" ]
        service_callback: ["prometheus_system"]

and /metrics just reports `307 Temporary Redirect`

### Relevant log output

```shell
127.0.0.1:60754 - "GET /metrics HTTP/1.1" 307
```

**Comment by ishaan-jaff** [comment]
works for me on latest 

<img width="1023" alt="Screenshot 2024-05-06 at 7 37 04 AM" src="https://github.com/BerriAI/litellm/assets/29436595/df7fa5b2-8e1a-40c8-9863-59b0fbf72914">

**Comment by ishaan-jaff** [comment]
@rjanovski can you try `http://localhost:4000/metrics/` ?

**Comment by rjanovski** [comment]
Thanks Ishaan,

yes, that works (trailing slash) /metrics/
since prometheus can scrape that, I'm happy.

could be better to expose the metrics with both paths: `/metric` and `/metric/`

but since you are [exposing](https://github.com/BerriAI/litellm/blob/main/litellm/proxy/proxy_server.py#L2290) exactly like the prometheus_client [docs](https://prometheus.github.io/client_python/exporting/http/fastapi-gunicorn/), I guess this is the correct way.

great work! thanks again :)
