### ISSUE TITLE
[Feature]: Support vertex ai imagen endpoint 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#3482]
### The Feature

https://console.cloud.google.com/vertex-ai/publishers/google/model-garden/imagegeneration?project=adroit-crow-413218

### Motivation, pitch

user request

### Twitter / LinkedIn details

https://www.linkedin.com/in/rodrigo-alarcon-ingeniero/

**Comment by ghost** [comment]
this is now supported https://docs.litellm.ai/docs/image_generation#vertexai---image-generation-models

**Comment by elabbarw** [comment]
Hey @krrishdholakia , did you happen to include the image_count parameter? how can i use it?

**Comment by ghost** [comment]
Hey @elabbarw i believe you can just pass that in as-is.

```
{
"model": imagen,
"prompt": "hello world", 
"image_count": <value>
}
```

https://github.com/BerriAI/litellm/blob/566d9354aab4215091b2e51ad0333e948125fa1b/litellm/llms/vertex_ai/image_generation/image_generation_handler.py#L98

**Comment by elabbarw** [comment]
> image_count

Hey, thanks for getting back to me @krrishdholakia 😄 

It doesn't look like it works. I keep getting the default 4 images when i use imagen3 and imagen3fast

**Comment by ghost** [comment]
What do your logs show when you do --detailed_debug?

Trying to confirm we're sending this.

**Comment by elabbarw** [comment]
I'm testing with Postman using this body but it still sends 4 images ```json {
  "model": "imagen3fast",
  "prompt": "(Photographic) A Pug in a garden",
  "negative_prompts":"anime,animation,cartoon",
  "image_count": 1
 }```

would be good to pass extra params like image_count or number_of_images (https://cloud.google.com/blog/products/ai-machine-learning/a-developers-guide-to-imagen-3-on-vertex-ai), safety_filter_level and person_generation

**Comment by elabbarw** [comment]
it's `sampleCount` 😄

**Comment by ghost** [comment]
Oh - that should already work. 

I believe there's already translation support for it as well `n` -> `sampleCount` 

https://github.com/BerriAI/litellm/blob/5670a9f8b7f0c2753ebed81908d76a78f090f747/litellm/utils.py#L2424
