### ISSUE TITLE
[Feature]: Support 'Bad Deployment' Slack Reports

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#3483]
### The Feature

Send daily slack reports on deployments with most failed requests, slowest deployments (normalized by latency / output tokens) 

### Motivation, pitch

catch bad deployments before high traffic issues 

### Twitter / LinkedIn details

cc: @dkindlund

**Comment by ghost** [comment]
We can probably just redis cache the perf by deployment 

Check redis cache every 12 hr -> send report

**Comment by ghost** [comment]
```yaml 
general_settings: 
    alert_types: ["daily_reports"] 
```
