### ISSUE TITLE
add coverage for anthropic internal server error

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#35]
<img width="1214" alt="Screenshot 2023-08-02 at 9 27 31 AM" src="https://github.com/BerriAI/litellm/assets/17561003/75e92370-0a74-4ce0-b88e-6a0d418ec2cf">

**Comment by ishaan-jaff** [comment]
cc @krrishdholakia is this resolved now with the new Exception class ?

**Comment by ghost** [comment]
closed as this is done now
