### ISSUE TITLE
Litellm Gorilla

### ISSUE THREAD

**Issue by ranjancse26** [BerriAI/litellm#351]
Which LLMs to prefer? I mean what's the optimized way of choosing the specified LLM based on the specified prompt and various other parameters such as cost, performance etc.

Time to rethink on the Gorilla based approach. This would really help the consumers to decide or choose the best LLMs for solving their problems. 

Please let me know your thoughts.

**Comment by ghost** [comment]
Hey @ranjancse26 if you're trying to use litellm to test models here's a couple relevant tutorials: 

- https://docs.litellm.ai/docs/tutorials/compare_llms
- https://docs.litellm.ai/docs/tutorials/first_playground
- https://docs.litellm.ai/docs/tutorials/ab_test_llms

Was there a specific feature request / bug with the litellm for your use-case? If not, I can close the issue.

**Comment by ranjancse26** [comment]
@krrishdholakia  Sorry, not good! The links which you have mentioned is no way close to what the Gorilla API is doing.

It's not solving the original problem of LLM selection based on the specified criteria or performance for that matter.

The original idea is to mimic what the Gorilla API is doing. Here are links for your reference.

https://gorilla.cs.berkeley.edu/
https://github.com/ShishirPatil/gorilla

Do not let human's to evaluate and manually select the LLMs. That's not a feasible approach

**Comment by ghost** [comment]
Why not just use gorilla to pick the right api?

**Comment by ranjancse26** [comment]
@krrishdholakia Sorry, looks like you are not understanding the true potential or intent of this feature. If your goal is to just make this library compatible with any LLM, then it's fine. If you would like to extend and build an intelligent one which we can choose the best LLM on its own, that's where the true potential comes.

**Comment by ishaan-jaff** [comment]
@ranjancse26 is your proposal to use LiteLLM to automatically select the best LLM for a given task ? 

Can you help us better understand your proposal and how you’d recommend implementing it ?

**Comment by ranjancse26** [comment]
@ishaan-jaff Yes, you got it right.

Imagine the Litellm on a true auto pilot mode, where the user can configure and drive the Litellm to basically choose between the configured LLMs based on the specified context or prompt. With the auto pilot option, the user need not worry or manually select the LLMs for their intended work. 

Imagine the user is intending to perform a series of task either represented with prompts of a high-level language which we can design or think about. Upon which, the Litellm can formulate the tasks, break it down into multiple independent tasks. Again, it can decide which tasks needs to go for which LLM etc. 

The above ones are just high-level thoughts. I am still researching and thinking about the possibilities. Yet to finalize the design.
