### ISSUE TITLE
[06/05/2024 - 12/05/2024]: New Models/Features/Providers 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#3513]
## End-User Cost Tracking 
- [ ] #3514
- [ ] #3515
- [x] #3516
- [x] #3517

## New Features 
- [x] https://github.com/BerriAI/litellm/issues/3490
- [ ] https://github.com/BerriAI/litellm/issues/3362
- [x] https://github.com/BerriAI/litellm/issues/3490
- [x] https://github.com/BerriAI/litellm/issues/3523
- [x] #3524
- [ ] #3553

**Comment by ghost** [comment]
merging in these items with https://github.com/BerriAI/litellm/issues/3045
