### ISSUE TITLE
Add the option to use Hugging Face Endpoint with Conversational task

### ISSUE THREAD

**Issue by PhucTranThanh** [BerriAI/litellm#352]
According to the [doc](https://docs.litellm.ai/docs/providers/huggingface) and some testing, it seems like we are only supporting the [text-generation-inference](https://github.com/huggingface/text-generation-inference) format. Can we add support for the [Conversational](https://huggingface.co/docs/inference-endpoints/supported_tasks#:~:text=%7D%0A%20%20%7D%0A%7D-,Conversational,-Copied) format as well?

**Comment by ghost** [comment]
Hey @PhucTranThanh 

Is there a way to tell if the endpoint is tgi or conversational? 

and Are you deploying a conversational format model or using the default `https://api-inference.huggingface.co/models/{model}` call?

**Comment by PhucTranThanh** [comment]
I'm deploying a conversational format model.

I think there is no direct way to tell the endpoint's type from the endpoint itself. We can try to use the `v2/endpoint/{namespace}` API [here](https://huggingface.co/docs/inference-endpoints/api_reference). However, this assumes that the user selected the correct task when they were deploying the model.

**Comment by ghost** [comment]
hmm, what would your ideal code / flow look like? @PhucTranThanh

**Comment by PhucTranThanh** [comment]
First, I think we can add one argument called something like `task` in `litellm.completion`, which is set to `text-generation` by default. You can change it to `conversational` otherwise. You may have to do this for every single task out there but I think for now text-generation and conversational are the most popular.

For example:
```
response = completion(model="huggingface/WizardLM/WizardCoder-Python-34B-V1.0", messages=messages, api_base="https://ji16r2iys9a8rjk2.us-east-1.aws.endpoints.huggingface.cloud", task="conversational")
```

Alternatively, you can use the `v2/endpoint/{namespace}` API to get the task (generation or conversational) from the endpoint. It can raise an exception for tasks that you've yet to implement.

**Comment by ghost** [comment]
@ishaan-jaff i know we'd explored configs before. 

My preference is to keep litellm.completion as close to the openai call as possible. The 'task' param looks to be huggingface-specific. Do you have any thoughts on how we could simplify this? 

@PhucTranThanh do you anticipate changing between different hf endpoints types? 

if not, we could just do `litellm.huggingface_task="conversational"`

**Comment by ghost** [comment]
@PhucTranThanh either way, i think your solution is valid. I'll have a solution out for you today, so you're not blocked on going to production.

**Comment by ghost** [comment]
are you on linkedin/twitter - would love to give you a shoutout when we announce this feature

**Comment by PhucTranThanh** [comment]
I believe I can change between different HF endpoints either way, can't I? So please choose the option you think is best.  I'll reach you on Linkedin.

**Comment by ghost** [comment]
@PhucTranThanh this is now added - 5b6b9a9fab619a4f1495ea591c86a2bd30e57dba, available on the package from `v.0.1.619` onwards
