### ISSUE TITLE
litellm与vlm相比如何，速度快不》？

### ISSUE THREAD

**Issue by njhouse365** [BerriAI/litellm#3520]
### What happened?

A bug happened!

**Comment by paneru-rajan** [comment]
**Translation:**  How does litellm compare with vlm, is it faster?

**Comment by njhouse365** [comment]
faster? accuracy？

**Comment by ishaan-jaff** [comment]
LiteLLM does load balancing for vLLM endpoints -> using LiteLLM + vLLM allows you to maximize your TPM/RPM
