### ISSUE TITLE
[Bug]:  Anthropic bedrock models are not found in the prices in context. 

### ISSUE THREAD

**Issue by jxnl** [BerriAI/litellm#3521]
### What happened?

missing pricing infromation?

### Relevant log output

```shell
litellm.exceptions.NotFoundError: Model not in model_prices_and_context_window.json. You passed model=bedrock/anthropic.claude-3-haiku-20240307-v1:0. Register pricing for model - https://docs.litellm.ai/docs/proxy/custom_pricing
```

**Comment by ishaan-jaff** [comment]
@jxnl I see it here: https://github.com/BerriAI/litellm/blob/190e2fc3d5e65957a3d433a6b411b9a962947867/model_prices_and_context_window.json#L1981 

Can I see you `completion` call ?

**Comment by ishaan-jaff** [comment]
- confirmed the model works for me locally 
- I think you have an extra `.` at the end @jxnl 


Working code:
```python
response = completion(
    model="bedrock/anthropic.claude-3-haiku-20240307-v1:0.",
    messages=messages,
    max_tokens=10,
    temperature=0.1,
)
```

**Comment by Manouchehri** [comment]
Same, noticed this as well.

**Comment by Manouchehri** [comment]
<img width="821" alt="image" src="https://github.com/BerriAI/litellm/assets/7232674/6a191f3a-1249-4291-953e-cc0e1f33b164">

**Comment by ishaan-jaff** [comment]
hmmm @Manouchehri can you share the curl command / request and what litellm version you're on ?

**Comment by Manouchehri** [comment]
Odd, I can't reproduce it anymore. I'm running v1.36.1 now. Leaving this here for future reference in case it comes back up:

```sh
curl -v "${OPENAI_API_BASE}/chat/completions" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
    "model": "claude-3-haiku-20240307",
    "max_tokens": 4,
    "stream": true,
    "temperature": 0.99,
    "messages": [
      {
        "role": "user",
        "content": "Think of 10 random colors. Then combine them in your head. Then tell me what color you have. You must only say one word."
      }
    ]
  }'
```

**Comment by jxnl** [comment]
The API call works, but getting the cost tokens does not work.

**Comment by jxnl** [comment]
> @jxnl I see it here: https://github.com/BerriAI/litellm/blob/190e2fc3d5e65957a3d433a6b411b9a962947867/model_prices_and_context_window.json#L1981 
> 
> 
> 
> Can I see you `completion` call ? 


Completion works the cost do not because in that dictionary it's missing the version with the bedrock prefix

**Comment by Manouchehri** [comment]
What version of LiteLLM are you running?

**Comment by ishaan-jaff** [comment]
@jxnl are you using `litellm.completion_cost` ?  Can I see some code so I can repro the issue

**Comment by ishaan-jaff** [comment]
fix PR here: https://github.com/BerriAI/litellm/pull/3534

**Comment by ishaan-jaff** [comment]
was able to repro with this - fix + test is in the Pr linked above 

```python
cost = litellm.completion_cost(
        model="bedrock/anthropic.claude-instant-v1",
        completion_response=response,
        messages=[{"role": "user", "content": "Hey, how's it going?"}],
    )
```

**Comment by ishaan-jaff** [comment]
feel free to re-open if not fixed @jxnl - new release will be out by EOD
