### ISSUE TITLE
Pydantic protected namespace spam

### ISSUE THREAD

**Issue by Xirider** [BerriAI/litellm#3522]
### What happened?

The current version now has pydantic warnings whenever run:
```
usr/local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:160: UserWarning: Field "model_group_retry_policy" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
```

The issue seems to be the `litellm.types.router.UpdateRouterConfig` class.

**Comment by ishaan-jaff** [comment]
resolved with: https://github.com/BerriAI/litellm/pull/3519

**Comment by ishaan-jaff** [comment]
@Xirider curious - do you use the litellm SDK or Proxy server ?

**Comment by rawwerks** [comment]
when trying to deploy on render from e1b2445 i'm getting these same namespace errors as soon as i add the environmental variables. (the initial deploy went fine, but not after adding the necessary env vars).

**Comment by ishaan-jaff** [comment]
Hi @Xirider following up on this, curious do you use LiteLLM Proxy in production today If so, I'd love to hop on a call and learn how we can improve LiteLLM for you

- my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
- my linkedin if you prefer DMs: https://www.linkedin.com/in/reffajnaahsi/
