### ISSUE TITLE
Region based routing (per end-user)

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#3524]
Specific users need to have all their llm api calls be within eu 

Allow something like this: 
```
curl --location 'http://0.0.0.0:4000/end_user/new' \
--header 'Authorization: Bearer sk-1234' \ # 👈 Master Key
--header 'Content-Type: application/json' \
--data '{
      "end_user_id" : "ishaan-jaff-3", <- specific customer
    
    "allowed_region": "eu" <- set region for models        

             + 

    "default_model": "azure/gpt-3.5-turbo-eu" <- all calls from this user, use this model? 

}'

# return end-user object
```

**Comment by ghost** [comment]
Currently covers: 
- Azure
- Vertex AI 
- Bedrock

**Comment by ghost** [comment]
Expose - get_provider_region() helper function

**Comment by ghost** [comment]
Expose CRUD endpoints for end-users 

- create
- info 
- update
- delete

**Comment by ghost** [comment]
for v0 - scoping to just create + info

**Comment by ghost** [comment]
Add a pre-call check to filter models by region

**Comment by ghost** [comment]
How to get model region? 

- on `set_client` -> make a blank request to azure deployments -> the headers return the rate limits + region info
