### ISSUE TITLE
[Budget - Manager] use completion(user_id) to update user_id costs 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#353]
the current interface requires me to use `budget_manager.update_cost(completion_obj=response, user=user_id)`

but it would be a lot easier if I i could just pass `user` as a param in `completion()` 

Desired code:
```python
  current_spend_for_user = budget_manager.get_current_cost(user=user_id)
  budget_for_user = budget_manager.get_total_budget(user_id)
  print(f"User: {user_id} has spent ${current_spend_for_user}, budget for user: ${budget_for_user}\n")
  if current_spend_for_user <= budget_for_user:
      response = completion(model="gpt-3.5-turbo", messages=[{"role": "user", "content": "Hey, how's it going?"}], user_id=user_id)
```

remove the need to call: budget_manager.update_cost(completion_obj=response, user=user_id

**Comment by WilliamEspegren** [comment]
#358 Made this PR, probably solves this?
