### ISSUE TITLE
[Bug]: Langfuse integration not supporting Ollama Chat API

### ISSUE THREAD

**Issue by Viktor2k** [BerriAI/litellm#3544]
### What happened?

Using Ollama to run my models and currently trying to integrate it towards langfuse but run into an issue when using the recommended ollama_chat API. Here's a minimal example with the error where the only thin I change between the two completion requests is the provider prefix from `ollama_chat` to `ollama`. 
```
import litellm
from litellm import completion

litellm.success_callback = ["langfuse"] 

completion(
    model = "ollama_chat/llama3:instruct",
    messages = [        
        {"role": "user", "content": "Hello"},
    ],
)
```
> Output:
> Traceback (most recent call last):
>   File "...python3.10/site-packages/litellm/integrations/langfuse.py", line 138, in log_event
>     output = response_obj["choices"][0]["message"].json()
> AttributeError: 'dict' object has no attribute 'json'

```
import litellm
from litellm import completion

litellm.success_callback = ["langfuse"] 

completion(
    model = "ollama/llama3:instruct",
    messages = [        
        {"role": "user", "content": "Hello"},
    ],
)
```
> Output:
> Runs as expected 🥳

### Relevant log output

```shell
Traceback (most recent call last):
  File "...python3.10/site-packages/litellm/integrations/langfuse.py", line 138, in log_event
    output = response_obj["choices"][0]["message"].json()
AttributeError: 'dict' object has no attribute 'json'
```

**Comment by paneru-rajan** [comment]
I was able to replicate it. The message is not Message object in case of chat but dict.

Looking into it.
