### ISSUE TITLE
[Bug]: docker-compose.yaml example doesn't work

### ISSUE THREAD

**Issue by gerjermun** [BerriAI/litellm#3557]
### What happened?

Error then running `docker-compose.yaml` example.
I got 3 main errors

1. image name should be `main` 
2. volumes should be  `- ./litellm-config.yaml:/app/proxy_server_config.yaml`
3. command should be `command: ["--port", "4000", "--num_workers", "8", "--detailed_debug"]`

 

### Relevant log output

```shell
ERROR: for litellm  Cannot start service litellm: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "--config": executable file not found in $PATH: unknown
ERROR: Encountered errors while bringing up the project.
```

**Comment by paneru-rajan** [comment]
Looking into it...

**Comment by paneru-rajan** [comment]
I tried the exact docker-compose file that was in the code, it works as expected.

<img width="376" alt="image" src="https://github.com/BerriAI/litellm/assets/4735661/d04a9c91-7ca1-42bc-9687-e5efc15fb37b">
Figure 1: Folder structure i am using

<img width="858" alt="image" src="https://github.com/BerriAI/litellm/assets/4735661/2bcd0097-1eb1-4ab5-a590-9de9ce15ea29">
Figure 2: Running the exact same docker-compose file as it is

----

_image name should be `main`_
--> The image name seems fine to me 

_volumes should be `- ./litellm-config.yaml:/app/proxy_server_config.yaml`_
--> make sure you've `litellm-config.yaml` in the same dir, it should work just fine

_command should be command: `["--port", "4000", "--num_workers", "8", "--detailed_debug"]`_
--> Looks good as the current command usage the config as well

**Comment by gerjermun** [comment]
You are right, I have tried now again and it works:

![image](https://github.com/BerriAI/litellm/assets/72889087/50a01f07-d574-4ca5-a022-212331d21a9c)

**Comment by paneru-rajan** [comment]
Thank you. Please close the Bug, and PR.

**Comment by ishaan-jaff** [comment]
@gerjermun We'd love to hop on a call to learn how you're using litellm and how we can improve for you. Would sometime this week work ? I reached out on linkedin 


Here's a link to our cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/berriai-1-1-onboarding-litellm-hosted-version?month=2023-10
