### ISSUE TITLE
[Feature]: Enable Azure + OpenAI to be used in parallel 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#356]
### The Feature

Azure openai is currently implemented by remapping the openai module to azure (openai.api_type, api_base, api_key). 

This doesn't work if you want to use openai endpoints + azure endpoints in parallel threads

cc: @filip-michalsky

### Motivation, pitch

```shell
Enable users to call openai + azure in parallel. This is important for phone call use-cases, where you want to call both models and just get the one that responds first.
```

**Comment by ishaan-jaff** [comment]
in order to make openai/azure calls thread safe we need to stop using openai.api_type

all calls should be made by passing the params in the ChatCompletion.create call:
```python
response = openai.ChatCompletion.create(
                model="gpt-3.5-turbo",
                messages=[{ "content": "Hello, how are you?","role": "user"}],
                api_key="sk-NICEONE",
                api_base=None,
                api_version=None,
                api_type="openai",
                organization="org-ik"
            )
```

**Comment by ishaan-jaff** [comment]
this is done

**Comment by ishaan-jaff** [comment]
https://docs.litellm.ai/docs/tutorials/azure_openai

**Comment by ishaan-jaff** [comment]
Tested the following scenarios: 
* Completion - Quick start
* Completion - Streaming
* Completion - Azure, OpenAI in separate threads
* Completion - Stress Test 10 requests in parallel
* Completion - Azure, OpenAI in the same thread
