### ISSUE TITLE
[Bug] User ID in langfuse is missing

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#3560]
### Discussed in https://github.com/BerriAI/litellm/discussions/3539

<div type='discussions-op-text'>

<sup>Originally posted by **qymab** May  9, 2024</sup>
Hi,

I used to receive the User ID from litellm in the Langfuse dashboard, but now it is missing. However, the Trace ID is still there. What are the recent changes to the parameters that would include the User ID as part of the litellm completion?

Thanks</div>

I noticed this as well.

**Comment by ghost** [comment]
reposting 
> can't think of any of the top of my head - but i can look into this + add a test to make sure there's no future regressions @qymab

**Comment by ghost** [comment]
Unable to repro this @Manouchehri @qymab - i see the user being logged in the generations field 

<img width="1309" alt="Screenshot 2024-05-10 at 6 15 05 PM" src="https://github.com/BerriAI/litellm/assets/17561003/845c8784-519c-47cf-8703-49fed37535cf">
<img width="1250" alt="Screenshot 2024-05-10 at 6 15 13 PM" src="https://github.com/BerriAI/litellm/assets/17561003/fd050be2-f6db-4a1c-a8db-fe47fa55362d">

**Comment by ghost** [comment]
Oh i see - it used to be a part of the trace param - https://github.com/BerriAI/litellm/blob/9ac5d30cb7b42750c7e5118c9304236edde90898/litellm/integrations/langfuse.py#L294

But got removed in a recent PR. 

Fixing now. 

To prevent future regressions - i'll also add a unit test on the trace + generation body being sent to langfuse, so things don't get accidentally removed.

**Comment by ghost** [comment]
working now - 
<img width="659" alt="Screenshot 2024-05-10 at 6 21 38 PM" src="https://github.com/BerriAI/litellm/assets/17561003/74b6bd48-3522-48a5-b043-64b159f1760e">
