### ISSUE TITLE
[Bug]: Update Benchmark tutorial 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#357]
### What happened?

This didn't work for a user

### Relevant log output

```shell
n/a
```

**Comment by ishaan-jaff** [comment]
cc @filip-michalsky

**Comment by ishaan-jaff** [comment]
I was able to repro this, `benchmark.py` did not explicitly set `completion_cost(completion_response=response)` which is now fixed 

I also update the docs for benchmarking llms

**Comment by ishaan-jaff** [comment]
Docs updated here: https://docs.litellm.ai/docs/tutorials/compare_llms
