### ISSUE TITLE
[Feature]: Support time to first token for lowest latency routing 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#3574]
### The Feature

support tracking time to first token in lowest latency routing 

### Motivation, pitch

user request

### Twitter / LinkedIn details

https://www.linkedin.com/in/lucasmanchine/

**Comment by ghost** [comment]
Initial thoughts on implementation: 

- track time to first token in logging object 
- return that as part of the success kwarg 
- if present, use that to calculate response time
