### ISSUE TITLE
[Feature]: Add LiteLLM Type stubs for mypy

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#360]
### The Feature

Request from @nsbradford on this

### Motivation, pitch

```shell
-
```

**Comment by Rohxn16** [comment]
can I get some more info on exactly what to do here? I wanna work on this issue.

**Comment by nsbradford** [comment]
You can start by adding type hints to this project and using mypy in CI to check this project's type safety 😄 
https://chat.openai.com/share/e531e4b3-0257-4adf-93b2-bc4318c28f5f

**Comment by mikeslattery** [comment]
A quick thing you can do is simply create a file called `litellm/py.typed`.  The contents don't matter, it's a marker file.

I get this error when I run `mypy app.py`:

```
app.py:17: error: Skipping analyzing "litellm.utils": module is installed, but missing library stubs or py.typed marker  [import-untyped]
app.py:17: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
```

Which I was able to workaround with:

```bash
touch venv/lib/python3.12/site-packages/litellm/py.typed
```

A better method is to generate library stubs,  `*.pyi`.  They speed up mypy analysis.  They can be generated with `stubgen`, but I've not done it before.

**Comment by ishaan-jaff** [comment]
@mikeslattery We'd love a PR on this if possible . Will give you a shoutout on release notes too

**Comment by mikeslattery** [comment]
@ishaan-jaff Done.   Someone else already did it in a more complex PR.  See my PR description.
