### ISSUE TITLE
[Bug]: httpx.Timeout <-> main.py custom_llm_provider needs to be in front of supports_httpx_timeout(custom_llm_provider)

### ISSUE THREAD

**Issue by Ludwig-Graef** [BerriAI/litellm#3627]
### What happened?

Hi,
I was trying to use the `httpx.Timeout` functionality, but what I realised is that it defaults to float because the `custom_llm_provider` is only calculated after calling `supports_httpx_timeout(custom_llm_provider)`.

If not specified, `custom_llm_provider` defaults to `None`. See: https://github.com/BerriAI/litellm/blob/901254d31e0cd605ca89a5c6ae033f4fda37f984/litellm/main.py#L682

The correct value is computed later in the code. See: https://github.com/BerriAI/litellm/blob/901254d31e0cd605ca89a5c6ae033f4fda37f984/litellm/main.py#L716

Thanks for helping out!

**Comment by ghost** [comment]
oh that's interesting - what provider was this for? we should add a unit test for this

**Comment by Ludwig-Graef** [comment]
Hey krrishdholakia,
this is an issue for all providers. I think the pull-request of edwinjosegeorge will fix the issue.
Thanks
