### ISSUE TITLE
[Bug]: Broken UI  1.37.7 and 1.37.9

### ISSUE THREAD

**Issue by superpoussin22** [BerriAI/litellm#3628]
### What happened?

A bug happened!
The ui is no more available after the 1.37.5

### Relevant log output

```shell
Error Page 404
```

**Comment by ishaan-jaff** [comment]
This works for us on staging @superpoussin22

**Comment by ishaan-jaff** [comment]
<img width="1111" alt="Screenshot 2024-05-14 at 9 56 13 AM" src="https://github.com/BerriAI/litellm/assets/29436595/92dc9c01-70f1-40ee-b1b3-b571246824ed">

**Comment by superpoussin22** [comment]
@ishaan-jaff :
I'm with litellm-database docker image:  works fine with previous version but with the latest  I see errors like: 
404 not found https://xxxxx/ui/_next/static/media/c9a5bc6a7c948fb0-s.p.woff2 
I'm on cloudrun

**Comment by superpoussin22** [comment]
@ishaan-jaff 
Removing the SERVER_ROOT_PATH variable solve the issue !
