### ISSUE TITLE
[Bug]: Model Cost dictionary missing remaining cohere, anthropic, etc. models 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#363]
### What happened?

The model cost dictionary - https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json

does not cover all the default litellm models (e.g. cohere) https://github.com/BerriAI/litellm/blob/1913d36e053cc1d6cd8d26b70d6a175d88a1f42c/litellm/__init__.py#L95

This needs to be updated to reflect that

**Comment by ghost** [comment]
support for cohere models added

**Comment by ishaan-jaff** [comment]
@krrishdholakia anything left here?

**Comment by ghost** [comment]
closing as this is now added
