### ISSUE TITLE
[Feature]:  Intergration with Lago

### ISSUE THREAD

**Issue by ncecere** [BerriAI/litellm#3639]
### The Feature

Integration with [Lago](https://www.getlago.com/) for billing.  this would be similar to the existing integration you have with Open Meter

- [ ] 

### Motivation, pitch

Lago is a billing platform like Stripe and allows for users to setup subscriptions.  integration with light llm and allowing users to setup budgets for there keys would be amazing.  Other AI companies like mistral are using this as there billing processor too.

**Comment by ghost** [comment]
tracking here - https://docs.getlago.com/templates/per-token/openai#step-3-ingest-usage-in-real-time

**Comment by ghost** [comment]
@ncecere how would you want this integration to work? 

mock code / flow would be helpful - i'll try and get a v1 out for feedback from you, tomorrow.

**Comment by ghost** [comment]
Lago exposes multiple ways of doing spend tracking 

Noting the tentative object i think we can log to Lago, to allow a user to price how they want: 

```
{
    "event": {
      "transaction_id": "<unique_id>",
      "external_customer_id": <litellm_end_user_id>, # passed via `user` param in /chat/completion call - https://platform.openai.com/docs/api-reference/chat/create
      "code": "openai_tokens",
      "properties": {
          "input_tokens": <number>,
          "output_tokens": <number>,
          "model": <string>,
          "response_cost": <number>, # 👈 LITELLM CALCULATED RESPONSE COST 
      }
    }
}
```

**Comment by Mte90** [comment]
It is not clear when those data are sent to Lago from the code.

**Comment by ghost** [comment]
it's sent on call success - 

<img width="646" alt="Image" src="https://github.com/user-attachments/assets/7e2739b6-a99c-4b18-87ad-367cf7c6b3d3" />

**Comment by Mte90** [comment]
Yes After some testing I saw that, I was expecting that request not at every single request but like Daily.
As it is today can be a bottleneck if you have tons of token used.

**Comment by ghost** [comment]
Feel free to migrate it to BatchLogger like we do for langsmith - https://github.com/BerriAI/litellm/blob/346d8a91320646c5b9da0623ad63978d1543ab4a/litellm/integrations/langsmith.py#L36

**Comment by Mte90** [comment]
But your documentation says for billing to use Lago.
