### ISSUE TITLE
[Feature]: Add support for NLP Cloud 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#364]
### The Feature

Their dolphin model is decent and cost effective: https://docs.nlpcloud.com/#chatbot-and-conversational-ai. There's also the python API: https://github.com/nlpcloud/nlpcloud-python

### Motivation, pitch

```shell
User request
```

**Comment by ghost** [comment]
cc: @Pipboyguy

**Comment by ghost** [comment]
NLP Cloud support added from v`0.1.625` onwards 


Docs - https://docs.litellm.ai/docs/providers/nlp_cloud

cc: @Pipboyguy

**Comment by Pipboyguy** [comment]
Fantastic! 🚀🚀 Incredible speed of delivery Thank you

**Comment by ghost** [comment]
@Pipboyguy would love to know how we could make litellm better for you / your team. If you have a few minutes to chat this/next week, that'd be great! 

https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by ghost** [comment]
also if you're not already there - would love to have you join our community - https://discord.com/invite/wuPM9dRgDw
