### ISSUE TITLE
[Feature]: Integration with DeepEval

### ISSUE THREAD

**Issue by ColabDog** [BerriAI/litellm#366]
### The Feature

With DeepEval, it allows LiteLLM users to answer questions like: 
- [ ] which LLM is the best factually consistent, provides the most relevant answers, least biased
- [ ] provides ways to create synthetic data as well to measure with both LiteLLM and DeepEval

### Motivation, pitch

I see a number of developers looking into DeepEval to answer questions like: 
- [ ] Which LLM is best?
- [ ] Does my finetuned LLM have issues with factual consistency
- [ ] Is there any hidden bias?

I think LiteLLM is a natural extension to DeepEval because developers can quickly test which ones they want to use. It falls in line with our strategy of helping developers choose the right LLMs. 

### Twitter / LinkedIn details

https://twitter.com/ColabDog

**Comment by ishaan-jaff** [comment]
Are you suggesting adding LiteLLM to DeepEval ? Or adding DeepEval as an
integration to LiteLLM

**Comment by jwongster2** [comment]
To me, I think a DeepEval integration into LiteLLM makes more sense. I think most developers would do this:
- Try out LiteLLM
- Curious to see how it performs on a performance-basis (outside of measuring things like latency/cost which I think LiteLLM does already oob)
- Start trying out DeepEval to examine things like factual consistency etc. 

So I imagine deepeval would integrate nicely with litellm. I'd love to set up a quick call to talk about this - mind if I book something in your calendly fellas?

**Comment by ghost** [comment]
yup - go for it @ColabDog

**Comment by ghost** [comment]
closing as resolution here is to get on a call
