### ISSUE TITLE
[Feature]: Custom response instead of HTTPException in precall hooks

### ISSUE THREAD

**Issue by Venukiran004** [BerriAI/litellm#3671]
### The Feature

When integrating our application with Litellm, relying solely on HTTP exceptions may not suffice; employing custom responses instead of exceptions could be more effective.

"error": "Violated content safety policy", this is exception. Instead of HTTP exception, we need to send a standard response in the API (during failure) response as if it is sent by the LLM. **But there should not be any call to LLM.**

![image](https://github.com/BerriAI/litellm/assets/64799594/1c7f4a15-0d87-4a99-a807-24ff441f2598)

### Motivation, pitch

**User Action:** A user attempts to upload content through your application.
**Pre-Call Hook Invocation:** Before processing the upload, your application invokes the pre-call hook provided by Litellm to check the content safety.
**Content Safety Violation Detected:** The pre-call hook detects that the content violates the safety policy. Specifically, it identifies a violation related to "Violated content safety policy".
**Custom Response Generation:**
Instead of letting the exception propagate as an HTTP exception, your application catches the pre-call hook exception.
Your application generates a custom response following a standard format, mimicking the structure of responses sent by Litellm's API.

### Twitter / LinkedIn details

https://www.linkedin.com/in/venukiran-sankar/

**Comment by ghost** [comment]
picking this up today
