### ISSUE TITLE
[Feature]: Log `x-litellm-version` to Langfuse (and other loggers)

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#3673]
### The Feature

The `x-litellm-version: 1.37.12` header is great, but doesn't appear to be logged persistently in places like Langfuse like I was hoping.

### Motivation, pitch

When I look at old Langfuse logs, it'd be really helpful to know what version of LiteLLM was running. :) 

Related to #3528. 

### Twitter / LinkedIn details

https://twitter.com/DaveManouchehri

**Comment by ishaan-jaff** [comment]
+1 can this be logged to slack / sentry alerting too
