### ISSUE TITLE
[Feature/Minor Bug]: Omit null/empty `x-litellm-*` headers

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#3675]
### What happened?

Typically, null/empty headers aren't included in HTTP responses. It's a bit odd and unconventional that LiteLLM sends them; we probably shouldn't.

### Relevant log output

```shell
x-litellm-cache-key: df3eae57253e30f847558e2493a58812fc79bf9923d5cc83a13b841ed6738dcc
x-litellm-model-api-base:
x-litellm-model-id:
x-litellm-model-region:
x-litellm-version: 1.37.12
```

### Twitter / LinkedIn details

https://twitter.com/DaveManouchehri

**Comment by paneru-rajan** [comment]
Hi @Manouchehri, agreed no header is better if there is no value, working on it.

I will be fixing all the places where we've assigned the custom header. In my opinion. this is better approach than patching from the middleware to remove empty value headers.

**Comment by paneru-rajan** [comment]
Headers are only available on the `proxy_server.py`, attaching the fix.

Implementing the dataclass would have been a good idea, but could not find dataclass being used, i will implement a custom function that generates a clean header.

**Comment by paneru-rajan** [comment]
Hi @Manouchehri, I've raise a PR please have it reviewed.

CC: @ishaan-jaff / @krrishdholakia
