### ISSUE TITLE
[Bug]: Don't require HF token when setting huggingface api base

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#368]
### What happened?

I can deploy a huggingface model to my custom endpoint. In that case, i don't need the api_key to be set. 

### Relevant log output

```shell
User-Feedback
```

**Comment by ghost** [comment]
reviewed code + tested further, i don't think we actually do raise an error if api_key is not set. 

<img width="1104" alt="Screenshot 2023-09-14 at 7 07 08 AM" src="https://github.com/BerriAI/litellm/assets/17561003/b1c8985a-91cf-4c47-a8ba-ac667f8d8904">

**Comment by ghost** [comment]
closing as this works based on testing. Also updated docs to make it clear setting api key is optional.
