### ISSUE TITLE
[Feature]: Anthropic - Support new anthropic-beta: tools-2024-05-16

### ISSUE THREAD

**Issue by demux79** [BerriAI/litellm#3683]
### The Feature

Finally, forced tool use and more: https://docs.anthropic.com/en/docs/tool-use

**Comment by ishaan-jaff** [comment]
It looks like the only thing we need to support is allow users to pass a custom `anthropic-beta` header 

anything else @demux79 ?

**Comment by ishaan-jaff** [comment]
PR here: https://github.com/BerriAI/litellm/pull/3694 @demux79

**Comment by widike** [comment]
Thanks. In order to keep completion code independent from the chosen model it would be nice to just use the latest Anthropic version by default.

**Comment by ishaan-jaff** [comment]
wouldn't it be a breaking change if we change the default `anthropic-beta` version on litellm? Users will suddenly start seeing a difference in response quality

**Comment by widike** [comment]
Do you have an idea? Otherwise, there will never be progress for Anthropic models in Litellm for users who are not aware of this very specific setting.
