### ISSUE TITLE
Add GPT-4o to vision docs

### ISSUE THREAD

**Issue by pbarker** [BerriAI/litellm#3689]
https://docs.litellm.ai/docs/providers/openai#openai-vision-models doesn't show gpt-4o

**Comment by ishaan-jaff** [comment]
done: https://github.com/BerriAI/litellm/commit/3351c5f11d0881c3dc6921acc91a5a1f92d9fc2d 

@pbarker curious do you use the litellm SDK or Proxy Server ?
