### ISSUE TITLE
[Types]: mock_completion  response type incorrect when stream=False 

### ISSUE THREAD

**Issue by toniengelhardt** [BerriAI/litellm#369]
### What happened?

When `stream=True` the `completion` response has the correct type `Generator[...]`, but when `stream=False` the response also has type `Generator[...]` which is not correct, it's a dict, see:

![Screenshot 2023-09-14 at 15 15 02](https://github.com/BerriAI/litellm/assets/2703233/e9867a2e-1565-48c7-9de3-7067ece87166)

**Comment by ghost** [comment]
Can you show me the completion call? @toniengelhardt i can't repro this with cohere 

<img width="622" alt="Screenshot 2023-09-14 at 7 36 48 AM" src="https://github.com/BerriAI/litellm/assets/17561003/fbaca445-a8eb-4a72-a098-242b7722b798">

**Comment by toniengelhardt** [comment]
Ah, it actually seems to be in the `mock_completion` method, not in `completion`:

![Screenshot 2023-09-14 at 15 51 19](https://github.com/BerriAI/litellm/assets/2703233/10e4548c-5732-4e1c-a6ae-ace405640b41)

**Comment by ghost** [comment]
Fixed in e2ea4adb84bb569529f5be2f177e85e7e2bc1632 - should be available in `v0.1.625` onwards

<img width="682" alt="Screenshot 2023-09-14 at 10 04 42 AM" src="https://github.com/BerriAI/litellm/assets/17561003/2e6b7d67-735f-44c8-bf8b-be744ddcc712">

**Comment by ghost** [comment]
Published @toniengelhardt
