### ISSUE TITLE
Add price per token / usage -- Anthropic

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#37]
e.g. implementation

<img width="949" alt="Screenshot 2023-08-02 at 4 17 47 PM" src="https://github.com/BerriAI/litellm/assets/17561003/ce22dd22-bd6a-481f-8555-1d0844af4822">
<img width="682" alt="Screenshot 2023-08-02 at 4 17 53 PM" src="https://github.com/BerriAI/litellm/assets/17561003/c10ab836-31e1-4b27-a068-84d58b62c3cc">

**Comment by ghost** [comment]
version 0.1.341  now returns token usage across all providers. Where possible it uses the providers own tokenizer (E.g. anthropic) else it defaults to tiktoken.

Need to now build on this to expose a pricing functionality - required for aispend ticket as well 

https://github.com/BerriAI/litellm/issues/44

**Comment by ghost** [comment]
closing as this is added now
