### ISSUE TITLE
[Feature]: Move to calling cohere endpoint

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#370]
### The Feature

Call cohere endpoint instead of the package

### Motivation, pitch

When i run the quick start it's annoying to hit the pip install cohere error.

**Comment by ishaan-jaff** [comment]
good catch on the quick start - in the meantime we should probably replace cohere with anthropic on the quick start

**Comment by ishaan-jaff** [comment]
actually most people can't get access to anthropic keys rn so perhaps we should leave cohere on there

**Comment by ghost** [comment]
maybe huggingface?

**Comment by ghost** [comment]
I don't like huggingface, since it requires you to set api base to use larger models, and you don't need a key to call the inference endpoint for smaller models (can be a confusing quick start - do i set key? when do i not? etc.) 

I'll just prioritize moving cohere to an http request later today

**Comment by ishaan-jaff** [comment]
okay awesome - thanks

**Comment by ghost** [comment]
done here - 3b4064a58faa0c70ed32aedb252123a9c183d3d4, will close issue once it's successfully published

**Comment by ghost** [comment]
closing as this is now published

**Comment by ghost** [comment]
`v0.1.626`
