### ISSUE TITLE
[Feature]: Add Premp AI provider

### ISSUE THREAD

**Issue by tuanlv14** [BerriAI/litellm#3722]
### The Feature

I suggest to add Premp provider under OpenAI compatibility:
curl --request POST \
  --url https://app.premai.io/v1/chat/completions \
  --header 'Authorization: API_KEY' \
  --header 'Content-Type: application/json' \
  --data '{
  "project_id": PRO_ID,
  "messages": [
    {
      "role": "user",
      "content": "Who are you ?"
    }
  ],
  "model": "gpt-4-eu"
}'

### Motivation, pitch

Add more a good provider with gpt4 free trial.

**Comment by ghost** [comment]
doesn't this already work? @tuanlv14 

https://docs.litellm.ai/docs/providers/openai_compatible

**Comment by tuanlv14** [comment]
> doesn't this already work? @tuanlv14
> 
> https://docs.litellm.ai/docs/providers/openai_compatible

Yes. I had tried but current method was not working. Based on Premp API document, it required payload with project_user_ID. I did not know how I can custom project_ID with liteLLM parameters. Pls help me.

>  import requests
> 
> url = "https://app.premai.io/v1/chat/completions"
> 
> payload = {
>     **"project_id": 123,**
>     "session_id": "<string>",
>     "repositories": {
>         "ids": [123],
>         "limit": 3,
>         "similarity_threshold": 0.5
>     },
>     "messages": [
>         {
>             "role": "user",
>             "content": "<string>",
>             "template_id": "3c90c3cc-0d44-4b50-8888-8dd25736052a",
>             "params": {}
>         }
>     ],
>     "model": "<string>",
>     "system_prompt": "<string>",
>     "max_tokens": 1,
>     "stream": True,
>     "temperature": 1
> }
> headers = {
>     "Authorization": "<api-key>",
>     "Content-Type": "application/json"
> }
> 
> response = requests.request("POST", url, json=payload, headers=headers)
> 
> print(response.text)
