### ISSUE TITLE
[Bug]: budget alert sent on each request 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#3738]
### What happened?

if a budget threshold is hit - the slack alerts fire on each subequent request 

this leads to the slack channel being spammed with alerts 

Steps to repro:

```
that’s a maxBudget of $20 on the team, and the key is running a routine of embedding generation, because of that it triggered a lot of the times, but it would be important to avoid this repetitive warning, as we scale
```

**Comment by gzamboni** [comment]
maybe you should think about have some kind of alert state machine for this... when a budget alert happens it stays active until it get solved.

**Comment by ghost** [comment]
we have caching for an alert, to prevent spam for other alerts - https://github.com/BerriAI/litellm/blob/25df95ab102eecf66bfb4155114a429804860059/litellm/integrations/slack_alerting.py#L4

is that what you wanted? @gzamboni
