### ISSUE TITLE
[Bug]: Upgrading litellm on poetry failed due to openai dependancy 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#374]
### What happened?

I was trying to update the version of litellm on open-interpreter and couldn't because of openai versioning problem. 

<img width="1225" alt="Screenshot 2023-09-14 at 2 51 06 PM" src="https://github.com/BerriAI/litellm/assets/17561003/106c13d5-3713-40fc-acf6-727950655147">

**Comment by ghost** [comment]
cc: @ishaan-jaff 

are you moving to http endpoint calls b/c of azure? maybe this could be rolled into that work?

**Comment by ishaan-jaff** [comment]
nope we don't need to move to http for azure 

this just seems like a poetry dependency manager problem

**Comment by ishaan-jaff** [comment]
added this pyproject.toml:

`openai = "^0.28.0 || ^0.27.0"` 

will test on new version and see if it works okay

**Comment by ishaan-jaff** [comment]
<img width="839" alt="Screenshot 2023-09-15 at 2 30 14 PM" src="https://github.com/BerriAI/litellm/assets/29436595/c7ad1b12-456a-4ab4-a9d9-252bc517093d">

this fixed the problem
