### ISSUE TITLE
[Feature]: Router abatch_completion to be more similar to the non-router batch_completion implementation

### ISSUE THREAD

**Issue by albertyusun** [BerriAI/litellm#3744]
### The Feature

Hey team! Thanks for all the awesome work on the product, it's been awesome using it. 

Here's a quick question. Would it be possible to have a method like `litellm.batch_completion()` implemented for the router?

I wish to use the `litellm.Router.abatch_completion()` method (recently implemented in #3585 by @ishaan-jaff) the same way that `litellm.batch_completion()` is implemented. 

Specifically, I want to use answer __multiple conversations with one model__ in a batch, which is how I use `litellm.batch_completion()`. However, the implementation of `litellm.Router.abatch_completion()`seems to be set up for answering __one conversation with multiple models__ in a batch. 

For example, I use `litellm.batch_completion()` to prompt a model like `gpt-3.5-turbo` to answer a list of different set messages like "good morning" and "what's the time" as a faster way to prompt a model to answer a series of questions than simply prompting `generate_completion` sequentially, one-by-one.
``` 
responses = batch_completion(
    model="claude-2",
    messages = [[{"role": "user", "content": "good morning? "}], [{"role": "user", "content": "what's the time? "}]]
)
```

Unfortunately, in the implementation of `litellm.Router.abatch_completion`, the `messages` parameter asks for `List[Dict[str, str]]`, indicating that the method expects only one conversation, not multiple. Multiple conversations would be `List[List[Dict[str, str]]]` instead. The method also asks for a list of models instead of one model like `litellm.batch_completion()` does. 

`litellm.Router.abatch_completion` method signature: 
```
    async def abatch_completion(
        self, models: List[str], messages: List[Dict[str, str]], **kwargs
    ):
```
Thank you so much!

### Motivation, pitch

One of my biggest use cases for `litellm` is the ease of batching that `batch_generate` offers. I'd like to start using the `Router` feature as well, so I want a similar feature for the router setting. 

### Twitter / LinkedIn details

@albertyusun / https://www.linkedin.com/in/albertyusun/

**Comment by ishaan-jaff** [comment]
@albertyusun does this mean:
-> model[0], message[0] -> response 0
-> model[1], message[1] -> response 1 

?

**Comment by albertyusun** [comment]
Yes, it could mean that! Or, I was thinking that model parameter is actaully `str`, not a `List[str]`, such that model, message[i] -> response i for all messages.

This would be similar to the [`batch_completion` functionality](https://litellm.vercel.app/docs/completion/batching#send-multiple-completion-calls-to-1-model), which accepts only one model (`str`) and multiple mesages (`List[List[Dict[str, str]]]`).

The goal here would be that it would try all instances of `model_name="gpt-3.5-turbo"` in the model_list that was used to initialized the Router until one works.

**Comment by ghost** [comment]
@albertyusun can you share a mock code snippet for how you'd want to do this with the router? 

Would help us a lot

**Comment by ishaan-jaff** [comment]
How's this @albertyusun :https://github.com/BerriAI/litellm/pull/3751 

Is this what you wanted?

**Comment by ishaan-jaff** [comment]
```python
response = await abatch_completion_one_model_multiple_requests(
    model="gpt-3.5-turbo",
    messages=[
        [{"role": "user", "content": "hello"}, {"role": "user", "content": "tell me something funny"}],
        [{"role": "user", "content": "hello good mornign"}],
    ]
)
```

**Comment by albertyusun** [comment]
Yes! Here's an example. Suppose we want to try gpt-3.5-turbo from an OpenAI account and a Azure account. Sometimes, one client may be down and the other may be up, so routing could help us figure out which one to use. 

And suppose you also want your model to answer a series of questions. In this example, we'll use a simple list of 2 questions, "How are you?" and "What's 9 + 10?" for sake of demonstration.

```
from litellm import Router

model_list = [
{
    "model_name": "gpt-3.5-turbo", 
    "litellm_params": { # params for litellm completion/embedding call 
        "model": "gpt-3.5-turbo", 
        "api_key": API_KEY_ONE,
    },
    "tpm": 100000,
    "rpm": 1000,
}, { 
        "model_name": "gpt-3.5-turbo", # model alias 
        "litellm_params": { 
            "model": AZURE_MODEL_ALIAS,
            "api_key": AZURE_API_KEY,
            "api_version": AZURE_API_VERSION,
            "api_base": AZURE_API_BASE_URL
        }, 
        "tpm": 100000,
        "rpm": 10000,
    }, 
]
router = Router(model_list=model_list)

# Now, let's inputting 2 separate conversations: 
batch = [
   [{"role": "user", "content": "Hey, how's it going?"}], 
   [{"role": "user", "content": "9 + 10 = "}]
] 

response = await router.abatch_completion(model="gpt-3.5-turbo", messages=batch)
for i in response: 
    print(i)
```
Ideally, this would return two responses: 
```
[
   ModelResponse(id=..., choices=[Choices(message=Message(content="Hello! I'm just a computer program, so I don't have feelings, but I'm here to help you. How can I assist you today?", role='assistant'))], model='gpt-3.5-turbo'),
   ModelResponse(id=..., choices=[Choices(message=Message(content="19.", role='assistant'))], model='gpt-3.5-turbo')
]
```

**Comment by albertyusun** [comment]
Yup, that seems exactly it! Thanks :D

**Comment by ishaan-jaff** [comment]
Cool ! @albertyusun can we setup a direct slack support channel for your team What's the best email to send an invite to?
