### ISSUE TITLE
[Bug]: Problems encountered when saving logs with certain models such as azure/whisper.

### ISSUE THREAD

**Issue by Yeison-Buritica** [BerriAI/litellm#3746]
### What happened?

Debugging within ../litellm/proxy/utils.py in the function: get_logging_payload(...), when using certain models like whisper, logging is not being performed within the database. This issue arises because the model response does not contain **USAGE**, with the values, ```usage=Usage(completion_tokens=0, prompt_tokens=0, total_tokens=0)```

Steps to repro:
```
from openai import OpenAI
f_path = "file_path"

client = openai.OpenAI(
    api_key="sk-1234",
    base_url="http://0.0.0.0:4000"
)


audio_file = open(f"{f_path}/audio-1.wav", "rb")
transcript = client.audio.transcriptions.create(
  model="whisper",
  file=audio_file
)
```
**"It doesn't save the event inside the LiteLLM_SpendLogs table."**

**Comment by ishaan-jaff** [comment]
fix here: https://github.com/BerriAI/litellm/pull/4427

**Comment by ishaan-jaff** [comment]
@Yeison-Buritica  any chance we can hop on a call ? I'd love to learn how how we can improve litellm for you.

I reached out to you on Discord if DMs work.
Sharing a link to my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat[[@lolsborn]
