### ISSUE TITLE
[Feature]: Add support for Anthropic LLMs on Bedrock

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#375]
### The Feature

use claude llms on bedrock 

currently waiting on aws for access to claude on bedrock

### Motivation, pitch

claude + bedrock are great for companies in production

**Comment by ghost** [comment]
this is now generally available - https://www.anthropic.com/index/amazon-bedrock-general-availability

we should be able to add support for this today

**Comment by ishaan-jaff** [comment]
done + on docs
