### ISSUE TITLE
[Bug]: Replicate input validation failing

### ISSUE THREAD

**Issue by joshreini1** [BerriAI/litellm#3766]
### What happened?

When calling a replicate model, such as llama-3 with the code below:

```python
from litellm import completion
import os
## set ENV variables
os.environ["REPLICATE_API_KEY"] = "replicate key"

# replicate llama-3 call
response = completion(
    model="replicate/meta/meta-llama-3-8b-instruct", 
    messages = [{ "content": "Hello, how are you?","role": "user"}]
)
```

I get the following bad request error indicating that litellm is passing an invalid field. This error is present across multiple Replicate models.

### Relevant log output

```shell
`BadRequestError: ReplicateException - Failed to start prediction {"detail":"- Additional property version is not allowed\n","status":422,"title":"Input validation failed","invalid_fields":[{"type":"additional_property_not_allowed","field":"","description":"Additional property version is not allowed"}]}`
```

### Twitter / LinkedIn details

@_jreini

**Comment by ghost** [comment]
@joshreini1 unable to repro, which version of litellm are you on? 
<img width="1659" alt="Screenshot 2024-05-21 at 2 27 08 PM" src="https://github.com/BerriAI/litellm/assets/17561003/31266abf-8f93-429d-bd8c-d5117677c878">


## Code: 
```python
from litellm import completion
import os
## set ENV variables
os.environ["REPLICATE_API_KEY"] = "my-replicate-key"

# replicate llama-3 call
response = completion(
    model="replicate/meta/meta-llama-3-8b-instruct", 
    messages = [{ "content": "Hello, how are you?","role": "user"}]
)

print(response)
```

**Comment by joshreini1** [comment]
Thanks @krrishdholakia - I was using 1.33.1. As you suggested, this is resolved by upgrading LiteLLM.
