### ISSUE TITLE
[Feature]: filter out deployments which don't support request params  

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#3769]
### The Feature

If litellm.drop_params = False, filter out deployments which don't support request params - e.g. 'response_format' 

Without this, requests get routed to bad deployments and fail -> returning '400' errors 

### Motivation, pitch

gpt-3.5-turbo-16k and gpt-4 don't support 'response_format', this means if they're in a loadbalancing/fallback group with gpt-3.5 / gpt-4-turbo models, they fail requests with 'response_format' in them 

Eg. error: 
```
Message: LLM API Failure - OpenAIException - Error code: 400 - {'error': {'message': "Invalid parameter: 'response_format' of type 'json_object' is not supported with this model.", 'type': 'invalid_request_error', 'param': 'response_format', 'code': None}}
Model: gpt-3.5-turbo-16k
API Base: https://api.openai.com/
model_group: gpt-3.5-turbo-16k
deployment: gpt-3.5-turbo-16k
```

**Comment by ghost** [comment]
I guess as a follow up to this - we should also allow you to define fallbacks for json mode, function calling, and vision
