### ISSUE TITLE
[Feature]: Add Amazon Titan Text Premier

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#3774]
### The Feature

```
aws bedrock-runtime invoke-model-with-messages \
--model-id "amazon.titan-text-premier-v1:0" \
--messages '[{"role":"user","content":[{"text":"good morning"}]}]' \
--inference-config '{"maxTokens":512,"stopSequences":[],"temperature":0.7,"topP":0.9}' \
--additional-model-request-fields '{}' \
--region us-east-1
```

https://docs.aws.amazon.com/bedrock/latest/userguide/titan-text-models.html#titantx-premier

### Motivation, pitch

More models.

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by ghost** [comment]
hey @Manouchehri does this not work currently? I can see it in our mapping - https://github.com/BerriAI/litellm/blob/47e12802df4177c48ab53f13cea6d1aabcd339e0/model_prices_and_context_window.json#L5061

**Comment by FireballDWF** [comment]
Ok, I successfully tested "amazon.titan-text-premier-v1:0" with v1.55.11 thus this issue can be closed
