### ISSUE TITLE
[Bug]: keyerror when handling anthropic responses

### ISSUE THREAD

**Issue by morgante** [BerriAI/litellm#3776]
### What happened?

LiteLLM fails with a `KeyError` when attempting to use function calling with Anthropic

### Relevant log output

```shell
DEFAULT 2024-05-22T04:01:38.309081Z File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 395, in acompletion
DEFAULT 2024-05-22T04:01:38.309087Z response = await self.async_function_with_fallbacks(**kwargs)
DEFAULT 2024-05-22T04:01:38.309092Z ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
DEFAULT 2024-05-22T04:01:38.309098Z File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 1217, in async_function_with_fallbacks
DEFAULT 2024-05-22T04:01:38.309103Z raise original_exception
DEFAULT 2024-05-22T04:01:38.309108Z File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 1140, in async_function_with_fallbacks
DEFAULT 2024-05-22T04:01:38.309113Z response = await self.async_function_with_retries(*args, **kwargs)
DEFAULT 2024-05-22T04:01:38.309118Z ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
DEFAULT 2024-05-22T04:01:38.309123Z File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 1276, in async_function_with_retries
DEFAULT 2024-05-22T04:01:38.309134Z raise original_exception
DEFAULT 2024-05-22T04:01:38.309140Z File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 1234, in async_function_with_retries
DEFAULT 2024-05-22T04:01:38.309144Z response = await original_function(*args, **kwargs)
DEFAULT 2024-05-22T04:01:38.309149Z ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
DEFAULT 2024-05-22T04:01:38.309154Z File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 482, in _acompletion
DEFAULT 2024-05-22T04:01:38.309158Z raise e
DEFAULT 2024-05-22T04:01:38.309163Z File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 458, in _acompletion
DEFAULT 2024-05-22T04:01:38.309168Z response = await litellm.acompletion(
DEFAULT 2024-05-22T04:01:38.309173Z ^^^^^^^^^^^^^^^^^^^^^^^^^^
DEFAULT 2024-05-22T04:01:38.309177Z File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 3235, in wrapper_async
DEFAULT 2024-05-22T04:01:38.309182Z raise e
DEFAULT 2024-05-22T04:01:38.309186Z File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 2798, in wrapper_async
DEFAULT 2024-05-22T04:01:38.309191Z logging_obj, kwargs = function_setup(start_time, *args, **kwargs)
DEFAULT 2024-05-22T04:01:38.309196Z ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
DEFAULT 2024-05-22T04:01:38.309202Z File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 2445, in function_setup
DEFAULT 2024-05-22T04:01:38.309206Z raise e
DEFAULT 2024-05-22T04:01:38.309210Z File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 2381, in function_setup
DEFAULT 2024-05-22T04:01:38.309215Z input="".join(
DEFAULT 2024-05-22T04:01:38.309219Z ^^^^^^^^
DEFAULT 2024-05-22T04:01:38.309228Z File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 2384, in <genexpr>
DEFAULT 2024-05-22T04:01:38.309233Z if isinstance(m["content"], str)
DEFAULT 2024-05-22T04:01:38.309238Z ~^^^^^^^^^^^
DEFAULT 2024-05-22T04:01:38.312269Z KeyError: 'content'
```
```


### Twitter / LinkedIn details

_No response_

**Comment by ghost** [comment]
Can you share a code snippet to repro? 

Seems like there's no content in the message

**Comment by morgante** [comment]
I'm using the proxy, so there's not really any code to share.

Question: do you just assume the responses are valid from the LLM, or do you run a schema validation?

**Comment by ghost** [comment]
1. If you can share a sample curl being sent to proxy for repro, that'd help
2. can you confirm your on the latest version? i can't see the reported line in utils.py - https://github.com/BerriAI/litellm/blob/main/litellm/utils.py#L2384
3. re: validation, we assume the request is in the openai format - we don't do schema validation on our end, but that's a good idea!

**Comment by morgante** [comment]
I can't get good logs because LiteLLM doesn't provide them. If the logs provided aren't sufficient for reproduction, you should add more logs.

I did some more debugging and this is the underlying error

> messages: roles must alternate between "user" and "assistant", but found multiple "user" roles in a row

it gets stripped along the way with all the code LiteLLM uses.

**Comment by morgante** [comment]
@krrishdholakia How do I log *just the raw responses*. I do not want to log after any of your code has done any processing. All the documentation seems to focus on logging after processing, which is exactly what I don't want.

**Comment by ghost** [comment]
Please confirm you're on litellm latest - the code block in your error trace doesn't exist in utils.py anymore 

For debugging:
1. see in cli -> https://docs.litellm.ai/docs/proxy/debugging#detailed-debug
2. you should see raw response emitted - https://github.com/BerriAI/litellm/blob/5d7d63849426baffdc2e8414e0ea5b1db4a7509e/litellm/llms/anthropic.py#L191
3. For logging original response, this is also available in the 'log_post_call' or 'log_success_event' hooks as the 'original_response' value in kwargs https://github.com/BerriAI/litellm/blob/5d7d63849426baffdc2e8414e0ea5b1db4a7509e/litellm/utils.py#L1384

**Comment by ghost** [comment]
Closing as code snippet doesn't exist on latest.
