### ISSUE TITLE
[Bug]: async_post_call_streaming_hook doesn't seem to be called

### ISSUE THREAD

**Issue by brandonchoe** [BerriAI/litellm#3786]
### What happened?

I followed the documentation to create custom callbacks. They all seem to work, except for `async_post_call_streaming_hook`. Looking at the code, I don't see `post_call_streaming_hook` being called at all. As a comparison, I do see `post_call_success_hook` being called for `async_post_call_success_hook`.

**Comment by ishaan-jaff** [comment]
@brandonchoe are you using this on the litellm SDK or Proxy server ?

**Comment by brandonchoe** [comment]
I am using the callbacks on the proxy server.

**Comment by ishaan-jaff** [comment]
Able to repro @brandonchoe - working on a fix rn

**Comment by ishaan-jaff** [comment]
Fix PR here: https://github.com/BerriAI/litellm/pull/3797

**Comment by ishaan-jaff** [comment]
@brandonchoe are you trying to modify the chunks as they come in ? Trying to understand this better so I fix the issue well. 

Also DM'd on Linkedin if you prefer chatting there

**Comment by ishaan-jaff** [comment]
<img width="1280" alt="Screenshot 2024-05-23 at 9 59 06 AM" src="https://github.com/BerriAI/litellm/assets/29436595/228215ad-8c73-47c4-b851-d743a4e5e6fa">
 
 
 with #3797 I can see the litellm chunk in the streaming hook, open to your feedback on how we can further improve this too

**Comment by ishaan-jaff** [comment]
closing since this is resolved - feel free to re-open if not @brandonchoe

**Comment by brandonchoe** [comment]
Sorry about the delayed response! I've been swamped. I was just exploring LiteLLM proxy callbacks, and I noticed that the streaming hook wasn't being called.

**Comment by ishaan-jaff** [comment]
no worries - @brandonchoe can we setup a 1:1 slack support channel with you ? What's the best email to send an invite to 

If you want to dm me - here's my linkedin https://www.linkedin.com/in/reffajnaahsi/
