### ISSUE TITLE
[Bug]: User TPM limit is not enforced

### ISSUE THREAD

**Issue by varungup90** [BerriAI/litellm#3788]
### What happened?

I set the TPM limit for a user 
<img width="752" alt="image" src="https://github.com/BerriAI/litellm/assets/12226243/1b384498-248d-4a55-836b-1091a4ee536c">

On querying, I do not see TPM limit enforced. I also tried RPM and it works as expected.
<img width="1630" alt="image" src="https://github.com/BerriAI/litellm/assets/12226243/b37fc943-c8b6-4924-945c-e7e32459877d">

<img width="1632" alt="image" src="https://github.com/BerriAI/litellm/assets/12226243/e52bcf92-e2e1-46fd-9893-52c10fa0e6a4">

**Comment by ishaan-jaff** [comment]
Hi @varungup90 

- Are you running this across multiple instances of LiteLLM
- Can we hop on a call to quickly debug / solve this? What's the best email to send an invite to 

Here's my cal if you prefer: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by ishaan-jaff** [comment]
I see it enforced for me @varungup90 
<img width="1275" alt="Screenshot 2024-05-22 at 8 42 40 PM" src="https://github.com/BerriAI/litellm/assets/29436595/0586b82e-ff80-4323-9e21-85b8ec3f41fe">


<img width="1280" alt="Screenshot 2024-05-22 at 8 42 12 PM" src="https://github.com/BerriAI/litellm/assets/29436595/ead05253-1d28-4408-9484-eee8957fc8c1">

**Comment by ishaan-jaff** [comment]
ohh mind trying the latest version and seeing if it's fixed @varungup90 ? 

https://github.com/BerriAI/litellm/releases/tag/v1.38.0

**Comment by ghost** [comment]
bump on this? @varungup90 is this issue resolved on v`1.38.0`

**Comment by varungup90** [comment]
Below is the result and observation.

TPM Limit = 10
<img width="1472" alt="image" src="https://github.com/BerriAI/litellm/assets/12226243/16baa8fb-9f9d-42b3-91e6-f825d4a0e517">

First request is successful. Question here, total tokens = 281, where as TPM limit is 10. Should not it violate?
<img width="1452" alt="image" src="https://github.com/BerriAI/litellm/assets/12226243/76dbd181-12bb-41e5-bfbd-3f1ec265f3b5">

Second request is also successful.
<img width="1453" alt="image" src="https://github.com/BerriAI/litellm/assets/12226243/fffe1d29-e8af-4672-8d6c-4a7c8e602907">

Third and onward requests fail. Question here, on TPM violation, is the error message "Max parallel request limit reached."? If yes, then response is not intuitive. 
<img width="931" alt="image" src="https://github.com/BerriAI/litellm/assets/12226243/be4fff6b-0839-4637-acbd-144e2be01f7b">
<img width="1373" alt="image" src="https://github.com/BerriAI/litellm/assets/12226243/f3cc809d-d078-4d78-93d5-e597e00900ed">

**Comment by ghost** [comment]
@varungup90  Yes - `Max parallel request limit reached` is the error str raised for this. What would a better string here be?

to understand your setup better 

- is this across multiple workers? 
- is the proxy connected to a redis cache?

**Comment by varungup90** [comment]
Simple message can be: "Token limit per minute reached". A better one can be: "User X configured, token limit per minute Y is reached".

Setup
- One worker
- Proxy connected to postgres.

I had another question, how is token limit calculated? Because for the first two successful requests, output has total tokens more than token limit configured.

**Comment by ghost** [comment]
It should just be getting written to and read from the cache - https://github.com/BerriAI/litellm/blob/bcd753415305998ec4d5bbf666bd137fce06e09c/litellm/proxy/hooks/parallel_request_limiter.py#L161

updated on success/failure

**Comment by ghost** [comment]
i'll test this on my end as well, thanks.
