### ISSUE TITLE
[Feature]: Map stream responses exactly to openai 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#379]
### The Feature

We need to ensure we return stream responses in exactly the format openai does 

This is what our current completion response chunks look like:
```
{
  "choices": [
    {
      "finish_reason": null,
      "index": 0,
      "delta": {
        "content": ".",
        "role": "assistant"
      }
    }
  ],
  "created": null,
  "model": null,
  "usage": {
    "prompt_tokens": null,
    "completion_tokens": null,
    "total_tokens": null
  }
}

```

- looks like we don't fill in litellm call id
- model is not included 
- created is empty 

For this ticket please compare the chunk outputs from OpenAI to litellm and modify CustomStreamWrapper on litellm

### Motivation, pitch

Open interpreter uses us in production with streaming. We've broken 1-2 times already let's ensure we map exactly to openai for future users

**Comment by WilliamEspegren** [comment]
Should LiteLLM stream chunk:

```
{
  "choices": [
    {
      "finish_reason": null,
      "index": 0,
      "delta": {
        "role": "assistant",
        "content": "Thi"
      }
    }
  ],
  "created": null,
  "model": null,
  "usage": {
    "prompt_tokens": null,
    "completion_tokens": null,
    "total_tokens": null
  }
```

become the openAI stream completion chunk:

```
{
  "id": "chatcmpl-7zKW6GKeFtDl7nEj8sZrWgLOzswwT",
  "object": "chat.completion.chunk",
  "created": 1694851230,
  "model": "gpt-3.5-turbo-0613",
  "choices": [
    {
      "index": 0,
      "delta": {
        "role": "assistant",
        "content": ""
      },
      "finish_reason": null
    }
  ]
}
```

**Comment by WilliamEspegren** [comment]
@ishaan-jaff The chunk that mock_completion returns is this:

```
{
  "choices": [
    {
      "finish_reason": null,
      "index": 0,
      "delta": {
        "role": "assistant",
        "content": "ues"
      }
    }
  ],
  "created": null,
  "model": null,
  "usage": {
    "prompt_tokens": null,
    "completion_tokens": null,
    "total_tokens": null
  }
```

The chunk that completion() returns is this:

```
{
  "id": "chatcmpl-7zLRyNfOr1zR6JUMWdVdMg4pndiR8",
  "object": "chat.completion.chunk",
  "created": 1694854818,
  "model": "gpt-3.5-turbo-0613",
  "choices": [
    {
      "index": 0,
      "delta": {},
      "finish_reason": "length"
    }
  ]
}
```

which is the same as what openAI returns:

```
{
  "id": "chatcmpl-7zLTLaZj8yF9pAOhLgfNSbkttI4fN",
  "object": "chat.completion.chunk",
  "created": 1694854903,
  "model": "gpt-3.5-turbo-0613",
  "choices": [
    {
      "index": 0,
      "delta": {
        "content": " Texas"
      },
      "finish_reason": null
    }
  ]
}
```

Do you want the mock_completion() to return the same as openAI?

**Comment by ishaan-jaff** [comment]
@WilliamEspegren what about non openai llms ? is it exact for that ?

**Comment by WilliamEspegren** [comment]
I don't know how many other LLM's offer [function-calling](https://platform.openai.com/docs/guides/gpt/function-calling) like openAI does, but open-interpreter depends on function calls from openAI @ishaan-jaff

**Comment by ghost** [comment]
@ishaan-jaff i think we can close this after the improvements to `test_streaming.py`. We are now checking the exact output format for different stream chunks (first, second, last) for both normal calls + function calling. 

@WilliamEspegren is correct, since only openai returns streaming + function calling, we're testing openai only for function calling output.
