### ISSUE TITLE
[Feature]: better model hub 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#3817]
### The Feature

API Gateway users can be shown the available models, descriptions, whether or not it has fine-tuning, etc. as metadata, a kind of catalog of available models, or if you know a solution for that, thinking about a model hub

### Motivation, pitch

make it easier for users to know what models are available, and select the models to use

**Comment by ghost** [comment]
We already have a lot of this information on a per model basis (`/model/info`) 

But i think this needs to be shown at the model group level, b/c that's the string value an app owner will use when calling the proxy

**Comment by ghost** [comment]
i think if we just allow people to attach metadata for the model group, that could be a good first start

**Comment by yujonglee** [comment]
@krrishdholakia 

Resolved in #3869

**Comment by ghost** [comment]
Thanks! @yujonglee
