### ISSUE TITLE
[Feature]: Outage alerting for a model/provider/region if it fails a threshold of calls 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#3818]
### The Feature

Slack alert user if a model/provider/region fails X % of calls in a given timespan 

default can be 3 calls (LLM API returns -> 400 error for model or multiple 500 errors for provider/region)

### Motivation, pitch

For model -> helps user know if they have a badly configured model or a region is currently down so they can contact their azure/gcp account manager

**Comment by ghost** [comment]
For v0, let's focus on provider/region alerting 

For the badly configured use-case, i think it's probably fixed by adding a 'test_model' button on the UI

**Comment by ghost** [comment]
<img width="886" alt="Screenshot 2024-05-24 at 1 16 57 PM" src="https://github.com/BerriAI/litellm/assets/17561003/ff25bad5-7a14-4646-82d6-6829b30a80ee">

^ e.g. slack outage alert
