### ISSUE TITLE
[Feature]: Attach litellm exception in error string 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#3819]
### The Feature

Attach the litellm exception type in the error string. This allows user to try-except exceptions correctly + for admin ui, tells user which exception to set higher retries on 

### Motivation, pitch

user saw slack alert for azure content policy violation, but wasn't sure which router setting to configure for this

**Comment by ghost** [comment]
@ishaan-jaff did you already do this?

**Comment by ishaan-jaff** [comment]
yeah I have a PR here: https://github.com/BerriAI/litellm/pull/3824/files
