### ISSUE TITLE
[Feature]: Helper function to rebuild streaming + function calling object

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#383]
### The Feature

If you want a complete object after doing a streamed function call, it can get pretty complicated 

there's 3 streaming chunk structures
- first chunk
- mid chunk (after first, before last streamed chunk)
- last chunk 

So you need to find a way to merge the 3 formats into 1 unified chunk. 

Look at test_streaming for output examples - https://github.com/BerriAI/litellm/blob/15bc5f2bdc96923394e75e6e4a9c8f81b8078313/litellm/tests/test_streaming.py#L441

It would be helpful to expose a helper function to let people rebuild their stream objects 

possible solution:
```
from litellm import stream_chunk_builder 

response = completion(..., stream=true) 
chunks = []
for chunk in response: 
  chunks.append(chunk)

print(stream_chunk_builder(chunks))
```

### Motivation, pitch

Needed it for final output validation testing

**Comment by ghost** [comment]
@WilliamEspegren if you're looking for a good issue, let me know if this resonates

**Comment by WilliamEspegren** [comment]
@krrishdholakia yes thank you, just what I was looking for. Will take a peak at it tomorrow 🤝
