### ISSUE TITLE
[Bug]:  budget_duration  and budget_reset_at  are all null in `/team/new` response 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#3830]
### What happened?

```
curl -X 'POST' \
  'https://localhost:4000/team/new' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer KEY_GOES_HERE' \
  -H 'Content-Type: application/json' \
  -d '{
  "team_alias": "t3",
  "team_id": "t3",
  "organization_id": null,
  "admins": [],
  "members": [],
  "members_with_roles": [],
  "metadata": {},
  "tpm_limit": 0,
  "rpm_limit": 0,
  "max_budget": 0,
  "models": [],
  "blocked": false,
  "model_aliases": {}
}'
```

**Comment by ncecere** [comment]
just to add more context here, teams are created but `budget_duration`  and `budget_reset_at`  are all null.  There is nothing in the UI or API to let me set this after the team is created.  it would be nice if the `budget_duration` could be set during creation but have a default of like 30 days or 1 month.  also the ability to modify later with team update.

**Comment by ishaan-jaff** [comment]
fixed here: https://github.com/BerriAI/litellm/pull/3842 @ncecere 

- you can pass `budget_duration` on `/team/new` and `/team/update`

**Comment by ishaan-jaff** [comment]
<img width="453" alt="Screenshot 2024-05-25 at 3 45 28 PM" src="https://github.com/BerriAI/litellm/assets/29436595/da329e60-5bd4-4b2f-b33d-75edfe743048">


re `budget_reset_at` this is not something we expose on the endpoints - curious is this something you wanted to set ?

**Comment by ishaan-jaff** [comment]
fixed
