### ISSUE TITLE
[Bug]: `ChatLiteLLM` in `langchain_community` does not support function calling

### ISSUE THREAD

**Issue by s-jse** [BerriAI/litellm#3837]
### What happened?

Hi,

I have been trying to use LiteLLM in LangChain for function calling.
According to the documentation at https://api.python.langchain.com/en/latest/chat_models/langchain_community.chat_models.litellm.ChatLiteLLM.html#langchain_community.chat_models.litellm.ChatLiteLLM.bind_tools, I should be able to call `bind_tools()` on a `ChatLiteLLM` instance. However, this raises a `NotImplemented` error from the parent class.
ChatLiteLLM's source code at https://api.python.langchain.com/en/latest/_modules/langchain_community/chat_models/litellm.html#ChatLiteLLM seems to suggest that this implementation is indeed missing.

Thank you in advance.

**Comment by ghost** [comment]
hey @s-jse thanks for raising this - we'd welcome a PR to improve the langchain integration - https://github.com/langchain-ai/langchain/blob/cccc8fbe2fe59bde0846875f67aa046aeb1105a3/libs/community/langchain_community/chat_models/litellm.py#L163 . Let me know how i can help!
