### ISSUE TITLE
[DX]: Method parameters should be documented

### ISSUE THREAD

**Issue by toniengelhardt** [BerriAI/litellm#384]
### The Feature

Ideally all parameters in the source code would be annotated with doc strings, but I think for ambiguous values and values with units it is essential.

### Motivation, pitch

E.g. `prompt` or `total_time` in the `completion_cost` method. It should be clear without digging further into the code what those parameters are and whether the value for `total_time` is in seconds, milliseconds, or something else.

**Comment by ghost** [comment]
That's a good idea - @toniengelhardt, what's a good way to start doing this? 

We've started trying to use linting (thanks to @yujonglee) to make it easy to see what the expected i/o should be. 

Open to further ideas / suggestions for this!

**Comment by toniengelhardt** [comment]
The best way IMO is to use doc strings and type hints.

For instance, in this example, when you hover over the `diff_arrays` method you see at a glance what the method and the parameters are doing:

![Screenshot 2023-09-17 at 17 05 39](https://github.com/BerriAI/litellm/assets/2703233/c8cfe98c-bac1-4054-beff-d2edc131c4c5)

Method with docstrings and type hints:

![Screenshot 2023-09-17 at 17 05 52](https://github.com/BerriAI/litellm/assets/2703233/6ebac060-c62d-4ace-9071-7b0d03acd07f)

This improves DX significantly and one does not need to consult the web docs or the source code.

Dostrings also serve as a kind of requirement or specification for methods or classes, meaning that it should always be the source of truth. If the code is not doing what the docstring says, the code is wrong, or the docstring needs to be updated.

It is much harder to create ambiguity with text than with code.

**Comment by ghost** [comment]
Ok, makes sense. Let's start with docstrings for the `completion_cost` function and go from there. 

cc: @ishaan-jaff

**Comment by toniengelhardt** [comment]
Great, I might throw in some docstrings as well as I encounter things that are unclear.

**Comment by ishaan-jaff** [comment]
done for completion_cost in this commit: https://github.com/BerriAI/litellm/commit/4a17a6c2b360d4c58c66fd3162b7287f3af4f63b

**Comment by ishaan-jaff** [comment]
one for acompletion: https://github.com/BerriAI/litellm/commit/d684f75683a242a18c007665d5faa4a4c84a5aa3

**Comment by ishaan-jaff** [comment]
mock completion & completion: https://github.com/BerriAI/litellm/commit/a5425df91f327089bfa3298a0ab59c8bb251a8d5

**Comment by ishaan-jaff** [comment]
Thanks for the issue @toniengelhardt closing this for now since we've added doc strings

Feel free to re-open if i missed any functions that are important
