### ISSUE TITLE
[Bug]: clarifai provider in litellm[proxy] not work 

### ISSUE THREAD

**Issue by tuanlv14** [BerriAI/litellm#3862]
### What happened?

My config.yaml:
- model_name: clarifai-gpt-4o
    litellm_params:
      model: clarifai/openai.chat-completion.gpt-4o
      api_base: https://clarifai.com/v1/
      api_key: CLARIFAI_API_KEY
      rpm: 100

Athought python code worked well but liteLLM proxy did not work successfully.
import os
from litellm import completion

os.environ["CLARIFAI_API_KEY"] = MY_KEY

response = completion(
  model="clarifai/openai.chat-completion.openai-gpt-4o",
  messages=[{ "content": "Who you are ?","role": "user"}]
)

print(response)

So pls help me fix this issue.

### Relevant log output

```shell
HTTP 500 Internal Server Error from http://127.0.0.1:4000/v1/chat/completions {"error":{"message":"sequence item 0: expected str instance, list found\nNumber Retries = 1","type":null,"param":null,"code":500}} Code: undefined Error number: undefined Syscall: undefined Type: undefined Error: HTTP 500 Internal Server Error from http://127.0.0.1:4000/v1/chat/completions {"error":{"message":"sequence item 0: expected str instance, list found\nNumber Retries = 1","type":null,"param":null,"code":500}} at customFetch
```

**Comment by ishaan-jaff** [comment]
@mogith-pn one more issue - any idea why we're seeing so many clarifai bugs ?

**Comment by ishaan-jaff** [comment]
@tuanlv14 can you try removing `api_base: https://clarifai.com/v1/` from your config.yaml 

are you actually setting `api_key: XXXXx` to your api key here

**Comment by mogith-pn** [comment]
> ### What happened?
> My config.yaml:
> 
> * model_name: clarifai-gpt-4o
>   litellm_params:
>   model: clarifai/openai.chat-completion.gpt-4o
>   api_base: https://clarifai.com/v1/
>   api_key: CLARIFAI_API_KEY
>   rpm: 100
> 
> Athought python code worked well but liteLLM proxy did not work successfully. import os from litellm import completion
> 
> os.environ["CLARIFAI_API_KEY"] = MY_KEY
> 
> response = completion( model="clarifai/openai.chat-completion.openai-gpt-4o", messages=[{ "content": "Who you are ?","role": "user"}] )
> 
> print(response)
> 
> So pls help me fix this issue.
> 
> ### Relevant log output
> ```shell
> HTTP 500 Internal Server Error from http://127.0.0.1:4000/v1/chat/completions {"error":{"message":"sequence item 0: expected str instance, list found\nNumber Retries = 1","type":null,"param":null,"code":500}} Code: undefined Error number: undefined Syscall: undefined Type: undefined Error: HTTP 500 Internal Server Error from http://127.0.0.1:4000/v1/chat/completions {"error":{"message":"sequence item 0: expected str instance, list found\nNumber Retries = 1","type":null,"param":null,"code":500}} at customFetch
> ```
> 
> ### Twitter / LinkedIn details
> _No response_



> ### What happened?
> My config.yaml:
> 
> * model_name: clarifai-gpt-4o
>   litellm_params:
>   model: clarifai/openai.chat-completion.gpt-4o
>   api_base: https://clarifai.com/v1/
>   api_key: CLARIFAI_API_KEY
>   rpm: 100
> 
> Athought python code worked well but liteLLM proxy did not work successfully. import os from litellm import completion
> 
> os.environ["CLARIFAI_API_KEY"] = MY_KEY
> 
> response = completion( model="clarifai/openai.chat-completion.openai-gpt-4o", messages=[{ "content": "Who you are ?","role": "user"}] )
> 
> print(response)
> 
> So pls help me fix this issue.
> 
> ### Relevant log output
> ```shell
> HTTP 500 Internal Server Error from http://127.0.0.1:4000/v1/chat/completions {"error":{"message":"sequence item 0: expected str instance, list found\nNumber Retries = 1","type":null,"param":null,"code":500}} Code: undefined Error number: undefined Syscall: undefined Type: undefined Error: HTTP 500 Internal Server Error from http://127.0.0.1:4000/v1/chat/completions {"error":{"message":"sequence item 0: expected str instance, list found\nNumber Retries = 1","type":null,"param":null,"code":500}} at customFetch
> ```
> 
> ### Twitter / LinkedIn details
> _No response_

Hi @tuanlv14,

gpt0 support is not yet added in clarifai, could you please try with other models ?

**Comment by tuanlv14** [comment]
> * clarifai

I am sure that I used right API key due to that key still worked well with python code.
I also tried to remove `api_base: https://clarifai.com/v1/ ` but it seem not working.

About support model, I tried all gpt0 or other with python to confirm API will support before I build liteLLM proxy. So I do not think I have problem with model. I concerned about api_base but I do know why ? And How to fix. Pls help me.

**Comment by mogith-pn** [comment]
> > * clarifai
> 
> I am sure that I used right API key due to that key still worked well with python code. I also tried to remove `api_base: https://clarifai.com/v1/ ` but it seem not working.
> 
> About support model, I tried all gpt0 or other with python to confirm API will support before I build liteLLM proxy. So I do not think I have problem with model. I concerned about api_base but I do know why ? And How to fix. Pls help me.

@tuanlv14 , Can you share your proxy code ?

**Comment by tuanlv14** [comment]
Yes.
1/ Python code:
```
import os
from litellm import completion

os.environ["CLARIFAI_API_KEY"] = "MY_KEY"

response = completion(
  model="clarifai/openai.chat-completion.gpt-4-turbo",
  messages=[{ "content": "Who you are ?","role": "user"}]
)

print(response)
```

Results:
`ModelResponse(id='chatcmpl-ca2962c8-81b9-4aff-8ef7-094cbabb8fe2', choices=[Choices(finish_reason='stop', index=1, message=Message(content='I am an AI digital assistant designed to provide information, answer questions, and assist with tasks to the best of my abilities based on the data and programming I have been equipped with. How can I assist you today?', role='assistant'))], created=1716833416, model='https://api.clarifai.com/v2/users/openai/apps/chat-completion/models/gpt-4-turbo/outputs', object='chat.completion', system_fingerprint=None, usage=Usage(prompt_tokens=4, completion_tokens=43, total_tokens=47))`

And My config.yaml:

` model_name: clarifai-gpt-4-turbo
    litellm_params:
      model: clarifai/openai.chat-completion.gpt-4-turbo
      api_key: My_key
      rpm: 100`

I tried within api_base and wihout api_base. All of them are not working.
My concern is about how we define api_base in right format or right structure ?

**Comment by tuanlv14** [comment]
Update:

```
import os
from litellm import completion

os.environ["CLARIFAI_API_KEY"] = MY_KEY

response = completion(
  model="clarifai/deepseek-ai.deepseek-chat.deepseek-V2-Chat",
  base_url = "https://api.clarifai.com/v2",
  messages=[{ "content": "Who you are ?","role": "user"}]
)

print(response)
```
Response:
`ModelResponse(id='chatcmpl-2d51936d-5104-4b3b-82bb-063eecc8b280', choices=[Choices(finish_reason='stop', index=1, message=Message(content='I am an AI language model, here to assist you with information, answer questions, and provide helpful responses. How can I assist you today?', role='assistant'))], created=1716914217, model='https://api.clarifai.com/v2/users/deepseek-ai/apps/deepseek-chat/models/deepseek-V2-Chat/outputs', object='chat.completion', system_fingerprint=None, usage=Usage(prompt_tokens=4, completion_tokens=29, total_tokens=33))`

So I thought that base_url = "https://api.clarifai.com/v2" is right config.
Then I put:
```
- model_name: Clarifai-deepseek-V2-Chat
    litellm_params:
      model: clarifai/deepseek-ai.deepseek-chat.deepseek-V2-Chat
      api_base: https://api.clarifai.com/v2
      api_key: MY_KEY
      rpm: 10
```

This config inside _config.yaml_  had been validated healthy is GOOD.
But when I called:
```
curl --location 'http://localhost:4000/chat/completions' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer local_KEY' \
--data '{
"model": "Clarifai-deepseek-V2-Chat",
"stream": false,
"messages": [
{
"role": "user",
"content": "what llm are you"
}
]
}'
```
I GOT ERROR: Internal Server Errorr
I saw other guy who was facing with same issue: GOOD in python code BUT FAIL in litellm-proxy calling.
Hope that the team can fix this issue soon.

**Comment by ghost** [comment]
what does your proxy server log say? @tuanlv14

**Comment by tuanlv14** [comment]
@krrishdholakia : This is proxy error log:

`Malformed JSON sent from server: {"error": {"message": "'async for' requires an object with __aiter__ method, got coroutine\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py\", line 3554, in async_data_generator\n    async for chunk in response:\nTypeError: 'async for' requires an object with __aiter__ method, got coroutine\n", "type": "None", "param": "None", "code": 500}}`

**Comment by tuanlv14** [comment]
@krrishdholakia 
Code:
```
import openai
client = openai.OpenAI(

    api_key="MY_KEY",
    base_url="http://localhost:4000" # LiteLLM Proxy is OpenAI compatible, Read More: https://docs.litellm.ai/docs/proxy/user_keys
)

response = client.chat.completions.create(
    model="clarifai-deepseek-V2-Chat", # model to send to the proxy
    messages = [
        {
            "role": "user",
            "content": "Who are you ?"
        }
    ]
)

print(response)
```

Error:
```
Exception has occurred: InternalServerError
Internal Server Error
httpx.HTTPStatusError: Server error '500 Internal Server Error' for url 'http://localhost:4000/chat/completions'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500

During handling of the above exception, another exception occurred:

httpx.HTTPStatusError: Server error '500 Internal Server Error' for url 'http://localhost:4000/chat/completions'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500

During handling of the above exception, another exception occurred:

httpx.HTTPStatusError: Server error '500 Internal Server Error' for url 'http://localhost:4000/chat/completions'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500

During handling of the above exception, another exception occurred:

  File "\\WSL.LOCALHOST\UBUNTU\root\llmproxy\testProxy\testClarify.py", line 8, in <module>
    response = client.chat.completions.create(
openai.InternalServerError: Internal Server Error
```

**Comment by tuanlv14** [comment]
@krrishdholakia , @ishaan-jaff , @mogith-pn  do we have any update to fix this issue ?
I got some other cases that I can run well with liteLLM package & python, but when I try to config proxy, it allway have the error with same problem: InternalServerError.

When the model is not existing support, I try to custom proxy via openai as bellow:

```
- model_name: AIML-gpt
    litellm_params:
      model: openai/gpt-4
      api_base: https://api.aimlapi.com/v1
      api_key: MY_KEY
      rpm: 10
```
Althought healthy model checking is GOOD. But when I call LLM model via proxy & local url, it was not working.
So hope that the team can support to fix issue with custom  OPEN API Server.

**Comment by edwinjosegeorge** [comment]
@tuanlv14 Trying to replicate this issue, I tried the following...

#### litellm `config.yml`
```yaml
model_list:
  - model_name: Clarifai-gpt-4-turbo
    litellm_params:
      model: clarifai/openai.chat-completion.gpt-4-turbo
      api_key: <secret>
      rpm: 10
```

#### start the server
```bash
litellm --config config.yml
```

#### Post request from powershell
```powershell
$headers = @{
    "Authorization" = "Bearer <secret>"
}
Invoke-WebRequest -Uri "http://localhost:4000/v1/chat/completions" `
    -Method Post `
    -Headers $headers `
    -ContentType "application/json" `
    -Body "{ `"steam`": `"false`", `"model`": `"Clarifai-gpt-4-turbo`", `"messages`": [ { `"role`": `"user`", `"content`": `"what llm are you`" } ] }"

```


Its true that when the same call is made via SDK, it succeeds, but in proxy server, it fails. However the failure reason is `ValueError: [TypeError("'coroutine' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]` , which is a duplicate issue mentioned at https://github.com/BerriAI/litellm/issues/3357. 

Could you provide the steps to replicate `TypeError: 'async for' requires an object with __aiter__ method, got coroutine` ?

**Comment by ishaan-jaff** [comment]
Fix PR here: https://github.com/BerriAI/litellm/pull/4158 @tuanlv14

**Comment by ishaan-jaff** [comment]
@tuanlv14 any chance we can hop on a call ? I'd love to learn how how we can improve litellm for you.

My linkedin if you prefer DM: https://www.linkedin.com/in/reffajnaahsi/
Sharing a link to my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
