### ISSUE TITLE
[Feature]: Support sharing admin access via email + password

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#3863]
### The Feature

Allow admins to share ui access with others via email/password 

### Motivation, pitch

allow users on free tier to share admin ui access

**Comment by ghost** [comment]
<img width="720" alt="Screenshot 2024-05-27 at 9 53 28 AM" src="https://github.com/BerriAI/litellm/assets/17561003/8c5531c4-d7b1-406a-89e8-1b066f082429">

<img width="664" alt="Screenshot 2024-05-27 at 9 53 31 AM" src="https://github.com/BerriAI/litellm/assets/17561003/2a89d706-60c6-40a7-9d04-b2bd936f5b9f">

**Comment by ghost** [comment]
- admin sets user email
- admin invites user to proxy via invite link 
- user clicks on link 
- if user exists in db w/ password or w/ sso -> show login page 
- if user exists in db w/out password and no sso -> show sign up page
- user enters email + password 
- if email not in db => reject 
- if email in db => set values -> allow new user into proxy ui

**Comment by ghost** [comment]
invite link concept: 
{ 
"id": uuid,
"email": string, -> who is this invite for? 
"status": 0,1 -> accepted, pending
"accepted_at": datetime -> when link is claimed (user successfully onboards via link) 
"expires_at": datetime -> till when is link valid 
"created_at": datetime -> when did user create the link 
"updated_at": datetime -> when was invite status updated 
}
<img width="822" alt="Screenshot 2024-05-27 at 7 27 43 PM" src="https://github.com/BerriAI/litellm/assets/17561003/a2d73803-965c-4141-b5f7-3c6b3dd0b5cc">

https://github.com/getlago/lago-api/blob/e54c1227ce897c0b0d30eabb63ab89917507cfb3/db/schema.rb#L614
