### ISSUE TITLE
[Bug]: `extra_headers` doesn't seem to work in bedrock_httpx.py?

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#3864]
### What happened?

Doesn't seem like the extra headers are being passed along?

### Relevant log output

```shell
TBD, making this ticket now before I forget.
```

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by Manouchehri** [comment]
Same with Azure OpenAI, not sure if it's working.

**Comment by ghost** [comment]
unable to repro this @Manouchehri 

Just made a call 
<img width="819" alt="Screenshot 2024-05-27 at 6 48 03 PM" src="https://github.com/BerriAI/litellm/assets/17561003/b6914ddd-cca7-49fe-8e4f-a3b93dd27600">
<img width="1576" alt="Screenshot 2024-05-27 at 6 48 00 PM" src="https://github.com/BerriAI/litellm/assets/17561003/2f06b85e-492c-40de-bbea-241213f87de2">

**Comment by Manouchehri** [comment]
How do you do that with the OpenAI Python client?

**Comment by ghost** [comment]
Here's how:
<img width="725" alt="Screenshot 2024-05-27 at 7 10 40 PM" src="https://github.com/BerriAI/litellm/assets/17561003/21e6284f-f06c-4898-a5c0-ebbce7999995">


I also saw the issue which caused the extra headers in async calls to not be passed through. Fixed here - https://github.com/BerriAI/litellm/commit/6b50e656b8c0be3762f740baee036f4349ac205b

**Comment by Manouchehri** [comment]
Looks fixed for me, thanks!
