### ISSUE TITLE
[Feature]: Support gemini pdf mime type  

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#3890]
### The Feature

Allow user to pass gcp bucket pdf's to gemini https://cloud.google.com/vertex-ai/generative-ai/docs/samples/generativeaionvertexai-gemini-pdf?hl=es-419#generativeaionvertexai_gemini_pdf-python

### Motivation, pitch

user request

**Comment by ghost** [comment]
added with - https://github.com/BerriAI/litellm/commit/58bd2b4ea620b23f6e3d4771c18ca95f342b0112
