### ISSUE TITLE
add retries w/ exponential backoff 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#39]
https://github.com/reworkd/AgentGPT/pull/1146/files/ff3d52d4a7abd848b6691af75e115f477db3d4f9#r1276947112
<img width="780" alt="Screenshot 2023-08-03 at 9 22 56 AM" src="https://github.com/BerriAI/litellm/assets/17561003/a2991d8a-d2dd-4e1b-9c05-a650ce7849e4">

**Comment by ghost** [comment]
tried adding but then faced issues with raising exceptions - commented out for now. Will need to investigate and re-implement.

**Comment by ishaan-jaff** [comment]
we have completion with retries now
