### ISSUE TITLE
[Bug]: Issues with Perplexity and Mistral models in Litellm proxy

### ISSUE THREAD

**Issue by seandearnaley** [BerriAI/litellm#3918]
### What happened?

I'm not 100% if this related to litellm directly or open webui which perhaps hasn't updated its dependencies, but my perplexity models and mistral models were working up until recently.  I get similar error messages.  Looks like the role params have been updated.

### Relevant log output

```shell
MistralException - Error code: 400 - {'object': 'error', 'message': 'Expected last role to be one of: [user, tool] but got assistant', 'type': 'invalid_request_error', 'param': None, 'code': None}

External: PerplexityException - Error code: 400 - {'error': {'message': 'Last message must have role `user`.', 'type': 'invalid_message', 'code': 400}}
```

### Twitter / LinkedIn details

@seandearnaley

**Comment by ishaan-jaff** [comment]
@seandearnaley can you run the proxy with `--detailed_debug` and then send the raw CURL request sent from litellm ? 

You should see this in your logs

**Comment by seandearnaley** [comment]
@ishaan-jaff it seems the litellm proxy works on it's own, it must be an issue with open-webui's implementation of the proxy.   Closing for now.
