### ISSUE TITLE
[Bug]: Anthropic models return arguments from function calls unreliably after proxy update

### ISSUE THREAD

**Issue by demux79** [BerriAI/litellm#3919]
### What happened?

I upgraded the proxy container from the version that was current on 2024-05-24 15:29 UTC to the version that was current on 2024-05-29 19:21 UTC.
Now, all of a sudden, Anthropic Function Calls return parameters very unreliably. Either empty parameters or missing ones.

Are you aware of any change in the past six days that might have caused the loss of function call performance for Anthropic? Or did Anthropic change anything? Using gpt-35 everything works as expected.

I am using the extra-headers parameter to use tools-2024-05-16. By the way, the documentation is missing that key:
<img width="732" alt="image" src="https://github.com/BerriAI/litellm/assets/14108031/1f7b1c0c-37c8-4cd4-ab80-2222c2aac091">

**Comment by ghost** [comment]
@demux79 no change on our end 

can you rollback and see if there's a repro'able error here? 

Re: anthropic-beta  header, we've always set it on our end - https://github.com/BerriAI/litellm/blob/9ef83126d71c25b7917b778ab8e0a2dcc1a90544/litellm/llms/anthropic.py#L519

**Comment by widike** [comment]
The reason was me adjusting to the special function call formats of anthropic while the proxy now does it by itself. One question: how do you handle the tool_choice = "any" that Anthropic allows but OpenAI doesn't?

**Comment by ghost** [comment]
Great! closing the issue. 

> how do you handle the tool_choice = "any" that Anthropic allows but OpenAI doesn't?

I believe it's identical to the openai 'required' tool choice, so we just map to that - https://github.com/BerriAI/litellm/blob/c5df662e0f071247a4d2b7e5b52af93c79b704cb/litellm/llms/anthropic.py#L112

how could we have made this easier to discover? @demux79

**Comment by agnivabanerjee** [comment]
`{'message': 'litellm.BadRequestError: VertexAIException BadRequestError - {"type":"error","error":{"type":"invalid_request_error","message":"Unexpected value(s) `tools-2024-05-16` for the `anthropic-beta` header. Please consult our documentation at docs.anthropic.com or try again without the header."}`

this change is breaking deployments.
