### ISSUE TITLE
[Bug]: `user` field and `user_api_key_*` is sometimes omitted randomly

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#3920]
### What happened?

Run this 5-10 times with a virtual key:

```
curl -v "${OPENAI_API_BASE}/chat/completions" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
    "model": "gpt-3.5-turbo-0125",
    "max_tokens": 100,
    "seed": 31337,
    "messages": [
      {
        "role": "user",
        "content": "what is 1 plus 1?"
      }
    ],
    "cache": {
      "no-cache": true
    },
    "extra_headers": {
      "cf-skip-cache": "True"
    }
  }'
```

And sometimes, the `user` field isn't passed at all.

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by ghost** [comment]
i don't see the `user` field in this call 

what would you expect to happen here? @Manouchehri

**Comment by Manouchehri** [comment]
It should be pulled from the key alias. I think it's more than just `user` that is racy. See the screenshot below, these are _identical_ requests, but the name is changing at random sometimes.

<img width="854" alt="image" src="https://github.com/BerriAI/litellm/assets/7232674/faaef610-0ee4-4a97-ab42-a9d096496f0e">

**Comment by ghost** [comment]
<img width="1140" alt="Screenshot 2024-06-01 at 10 08 21 AM" src="https://github.com/BerriAI/litellm/assets/17561003/c975235f-cf2a-4965-af9d-69e2fe8cd74f">

i can see the line of code in the server, the only this would happen is if: 
- user_id is being passed by the request (seems unlikely) 
- user_id isn't being passed by user_api_key_auth (possible)

**Comment by ghost** [comment]
do you have a consistent repro of this? @Manouchehri

**Comment by Manouchehri** [comment]
> do you have a consistent repro of this? @Manouchehri

Nope. Super confused why sometimes the `user_api_key_*` fields are missing, I don't see any pattern to it. Here's two identical requests I sent:

Good request shows this:

<img width="449" alt="image" src="https://github.com/BerriAI/litellm/assets/7232674/0dd8114b-d797-449e-bf26-f19f6482d069">


Bad request shows this:

<img width="275" alt="image" src="https://github.com/BerriAI/litellm/assets/7232674/c0aa17c8-c83e-484f-9009-60aa4c86457c">

**Comment by ishaan-jaff** [comment]
Are you on cloud run with 2 instances? It just looks like one instance has an older version

**Comment by Manouchehri** [comment]
I'm 98% sure all instances are up to date. Can't confirm retroactively though cause of #3673. 😅

**Comment by ishaan-jaff** [comment]
can you restart / re-deploy on cloud run and see if the issue persists ? 

I'm unable to repro your problem locally

**Comment by ghost** [comment]
closing as unable to repro but bump us to reopen if this isn't a suspected version issue 

i'll try and add the langfuse version id logging today @Manouchehri

**Comment by Manouchehri** [comment]
Sorry, I confirmed that I am indeed only running 1 instances. I'm able to reproduce it with this loop:

```sh
for i in {1..50} ; do curl -v "${OPENAI_API_BASE}/chat/completions" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
    "model": "gpt-3.5-turbo-0125",
    "max_tokens": 10,
    "seed": 31337,
    "messages": [
      {
        "role": "user",
        "content": "what is 1 plus 1?"
      }
    ],
    "cache": {
      "no-cache": true
    },
    "extra_headers": {
      "cf-skip-cache": "True"
    }
  }' ; done
```

The first request works, not the following ones though.

<img width="826" alt="image" src="https://github.com/BerriAI/litellm/assets/7232674/8ec90f97-1921-40b1-b3a3-d5ca61cf5705">

**Comment by Manouchehri** [comment]
I am using 1.39.6 100% everywhere, the Cloud Run instances don't stick around idle more than 15 minutes worst case. So that should never be an issue for me. =)

**Comment by ghost** [comment]
oh! that's interesting - thanks for this @Manouchehri

**Comment by Manouchehri** [comment]
Seems like a API key caching issue of some sort?

```sh
for i in {1..10} ; do curl -v "${OPENAI_API_BASE}/chat/completions" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
    "model": "gemini-1.5-flash-001",
    "max_tokens": 10,
    "messages": [
      {
        "role": "user",
        "content": "what is 1 plus 1?"
      }
    ],
    "cache": {
      "no-cache": true
    }
  }' ; done
```

This is *not* because of the OIDC caching I've added in the recent PRs. In the test case above, you can see I'm using `gemini-1.5-flash-001` on Vertex AI, which I haven't worked on at all for that feature. :) 

<img width="817" alt="image" src="https://github.com/BerriAI/litellm/assets/7232674/55954747-aaeb-4ade-9c2e-be5b7753820c">

**Comment by Manouchehri** [comment]
Are you caching anything for about a minute? It kinda looks like that's related to this issue. If I sleep for 61 seconds between requests, it works perfectly.

Repro that *doesn't* trigger the bug:

```sh
for i in {1..10} ; do sleep 61 && curl -v "${OPENAI_API_BASE}/chat/completions" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
    "model": "gemini-1.5-flash-001",
    "max_tokens": 10,
    "messages": [
      {
        "role": "user",
        "content": "what is 1 plus 1?"
      }
    ],
    "cache": {
      "no-cache": true
    }
  }' ; done
```
<img width="815" alt="image" src="https://github.com/BerriAI/litellm/assets/7232674/388110bc-4896-439a-a6b4-81f39c5b32f6">





Repro that *does* trigger the bug:

```sh
for i in {1..10} ; do sleep 55 && curl -v "${OPENAI_API_BASE}/chat/completions" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
    "model": "gemini-1.5-flash-001",
    "max_tokens": 10,
    "messages": [
      {
        "role": "user",
        "content": "what is 1 plus 1?"
      }
    ],
    "cache": {
      "no-cache": true
    }
  }' ; done
```

See below how everything beyond the first request is broken?

<img width="803" alt="image" src="https://github.com/BerriAI/litellm/assets/7232674/c010bc4b-236c-48a6-bac3-c5bf64017f41">

**Comment by matthiaslau** [comment]
I am experiencing the same issue and it seems this is really a caching bug.

When the hashed api token does not exist as key in the cache, an empty LiteLLM_VerificationTokenView object is created with only the token (https://github.com/BerriAI/litellm/blob/e96d2e3b1bb9e3193a181fbc925a250da70a9875/litellm/proxy/proxy_server.py#L1932) and this is set to the cache (https://github.com/BerriAI/litellm/blob/e96d2e3b1bb9e3193a181fbc925a250da70a9875/litellm/proxy/proxy_server.py#L2001).

Now it seems this cache entry with the api token key is used somewhere else when loading the api key object, not 100% sure yet where this happens exactly. This object from the cache now only contains the token and api_key, missing all other data:

```
token='d514bb211d49d8c135f13c8bd9d4022b37e3a4a18c659b09892b1c62959e1088' key_name=None key_alias=None spend=0.00114 max_budget=None expires=None models=[] aliases={} config={} user_id=None team_id=None max_parallel_requests=None metadata={} tpm_limit=None rpm_limit=None budget_duration=None budget_reset_at=None allowed_cache_controls=[] permissions={} model_spend={} model_max_budget={} soft_budget_cooldown=False litellm_budget_table=None org_id=None team_spend=None team_alias=None team_tpm_limit=None team_rpm_limit=None team_max_budget=None team_models=[] team_blocked=False soft_budget=None team_model_aliases=None team_member_spend=None end_user_id=None end_user_tpm_limit=None end_user_rpm_limit=None end_user_max_budget=None api_key='8bb0465eb6a148ba9d969368fe55a2c23bdb63d937c61c5fa4749d95490eded3' user_role=<LitellmUserRoles.INTERNAL_USER: 'internal_user'> allowed_model_region=None
```

After 60s (default in_memory_cache_ttl) this cache entry is invalid and it works again for one single request.

I will continue debugging, perhaps @krrishdholakia has an idea if this is the right direction and where the cache is used as api key and how to fix this?

**Comment by matthiaslau** [comment]
I think the cache retrieval happens here: https://github.com/BerriAI/litellm/blob/e96d2e3b1bb9e3193a181fbc925a250da70a9875/litellm/proxy/proxy_server.py#L816

The hashed token is used as a cache key as well and now the full api key object is expected, but the _update_key_cache function set the incomplete object to the cache.

**Comment by ishaan-jaff** [comment]
<img width="1166" alt="Screenshot 2024-06-20 at 3 37 41 PM" src="https://github.com/BerriAI/litellm/assets/29436595/628b5e5d-a3b0-4b5c-be30-84725d5facaf">


unable to repro this @Manouchehri 


here's what I ran 

```
for i in {1..50} ; do curl -v "http://localhost:4000/chat/completions" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer sk-_oIj3pgDjCxMRk7gKCuw_A" \
  -d '{
    "model": "llama3",
    "max_tokens": 10,
    "seed": 31337,
    "messages": [
      {
        "role": "user",
        "content": "what is 1 plus 1?"
      }
    ],
    "cache": {
      "no-cache": true
    }
  }' ; done
```

**Comment by ishaan-jaff** [comment]
do you see this on main-latest @Manouchehri @matthiaslau ?

**Comment by Manouchehri** [comment]
It's not fixed in v1.40.19.

```sh
for i in {1..10}; do curl -v "${OPENAI_API_BASE}/chat/completions" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
    "model": "gpt-3.5-turbo-0125",
    "max_tokens": 100,
    "seed": 31337,
    "messages": [
      {
        "role": "user",
        "content": "what is 1 plus 1?"
      }
    ],
    "cache": {
      "no-cache": true
    }
  }' ; done
```

<img width="624" alt="image" src="https://github.com/BerriAI/litellm/assets/7232674/b1f38af7-ce5e-4f7d-b376-d917c678d878">

**Comment by ishaan-jaff** [comment]
hmm that's weird i'm unable to repro

**Comment by Manouchehri** [comment]
Are you using `gpt-3.5-turbo-0125` on Azure OpenAI?

**Comment by ishaan-jaff** [comment]
using llama3, I can try using `gpt-3.5-turbo-0125`  I doubt the model is causing this issue

**Comment by ghost** [comment]
> $OPENAI_API_KEY

is this a master key? @Manouchehri

**Comment by Manouchehri** [comment]
> I doubt the model is causing this issue

It might be the provider, `azure/*`.

> is this a master key?

No.

**Comment by ishaan-jaff** [comment]
Okay I have a repro

- send a failing request with Key=`sk-jaDVJ0VGUArOp_Jj_amb3Q` 
- send a success request with Key=`sk-jaDVJ0VGUArOp_Jj_amb3Q`  it uses an incorrect value for team_id

**Comment by ishaan-jaff** [comment]
closing since this is resolved. + @matthiaslau also confirmed this worked
