### ISSUE TITLE
[Feature]: Flexible get_max_tokens

### ISSUE THREAD

**Issue by iwamot** [BerriAI/litellm#3921]
### The Feature

It would be nice if `get_max_tokens` would accept the same `model` string as `completion` as much as possible.

```
from litellm import completion, get_max_tokens

model = "bedrock/anthropic.claude-3-haiku-20240307-v1:0"

response = completion(model=model, messages=[{"role": "user", "content": "Hello"}])
max_tokens = get_max_tokens(model)  # Returns a number instead of throwing an Exception
```

### Motivation, pitch

It is annoying to have to adjust the `model` value just to call `get_max_tokens`.

If I may be greedy, it would be even more appreciated if the same value of `model` could be passed to those functions even when using Azure OpenAI.

```
model = "azure/gpt-4-0125-preview"

max_tokens = get_max_tokens(model)

response = completion(
    model=model,
    deployment_name="<your_deployment_name>", 
    messages=[{"role": "user", "content": "Hello"}],
)
```

### Twitter / LinkedIn details

@iwamot / https://www.linkedin.com/in/iwamot/

**Comment by ghost** [comment]
Hey @iwamot seeing `get_max_tokens` 

https://github.com/BerriAI/litellm/blob/main/litellm/utils.py#L7064

it has the same model checking logic as completion, where does it break for you?

**Comment by iwamot** [comment]
Hi @krrishdholakia, thank you for your reply.

An Exception will be raised if `custom_llm_provider` is not `huggingface` in the subsequent process:

https://github.com/BerriAI/litellm/blob/main/litellm/utils.py#L7065-L7069
```python
        if custom_llm_provider == "huggingface":
            max_tokens = _get_max_position_embeddings(model_name=model)
            return max_tokens
        else:
            raise Exception()
```

**Comment by ghost** [comment]
Got it - just pushed a fix @iwamot 

Curious - how're you using litellm today? 

DM'ed on linkedin to setup a direct support channel as well @iwamot

**Comment by iwamot** [comment]
Thank you for your quick response. I replied on LinkedIn about my usage.
