### ISSUE TITLE
[Feature]: Add Codestral API provider 

### ISSUE THREAD

**Issue by SamArgillander** [BerriAI/litellm#3922]
### The Feature

Please add Codestral.

Codestral is available in select code-completion plugins but can also be queried directly. See the documentation for more details.
Completion Endpoint:  https://codestral.mistral.ai/v1/fim/completions
Chat Endpoint: https://codestral.mistral.ai/v1/chat/completions

https://docs.mistral.ai/capabilities/code_generation/
https://docs.mistral.ai/api/#operation/createFIMCompletion

### Motivation, pitch

Codestral is a cutting-edge generative model that has been specifically designed and optimized for code generation tasks, including fill-in-the-middle and code completion. Codestral was trained on 80+ programming languages, enabling it to perform well on both common and less common languages.

**Comment by ghost** [comment]
Noted - should natively supported on litellm by end of week!

**Comment by ghost** [comment]
in the meantime, both should be accessible already via the openai compatible endpoint call - https://docs.litellm.ai/docs/providers/openai_compatible

**Comment by shuther** [comment]
I can't make it work using the openai compatible endpoint, I tried with apibase:
- https://codestral.mistral.ai
- https://codestral.mistral.ai/v1

and model=openai/codestral

I keep getting the error:
`litellm.exceptions.NotFoundError: NotFoundError: OpenAIException - Error code: 404 - {'message': 'no Route matched with those values', 'request_id': 'bb2ca66f11ef6c5d3307671a9215a852'}
`
but I can't see the url that is tried, not sure if there is a specific debug statement to get it in the log?

**Comment by ghost** [comment]
@shuther codestral is a text completion model

do `text-completion-openai/codestral`

**Comment by ishaan-jaff** [comment]
This is live here: https://docs.litellm.ai/docs/providers/codestral 

 @SamArgillander @okotek @isavita @bcgalvin @Spiritdude
