### ISSUE TITLE
[Bug]: "Exception No deployments available for selected model" for gemini-1.5-pro-001 and gemini-1.5-flash-001

### ISSUE THREAD

**Issue by NFuentesC** [BerriAI/litellm#3933]
### What happened?

Hello!, 
Apparently models with stable version 001 are not yet supported.

this is my config.yaml
```
- model_name: gemini-1.5-pro-001
    litellm_params:
      model: vertex_ai/gemini-1.5-pro-001
      vertex_project: "os.environ/PROJECT_ID"
      vertex_location: "us-central1"

- model_name: gemini-1.5-flash-001
  litellm_params:
    model: vertex_ai/gemini-1.5-flash-001
    vertex_project: "os.environ/PROJECT_ID"
    vertex_location: "us-central1
```

### Relevant log output

```shell
For gemini flash

21:42:01 - LiteLLM Router:INFO: router.py:658 - litellm.acompletion(model=None) Exception No deployments available for selected model, Try again in 1 seconds. Passed model=gemini-1.5-flash-001. pre-call-checks=False, allowed_model_region=n/a

and for pro version.

21:42:28 - LiteLLM Router:INFO: router.py:658 - litellm.acompletion(model=None) Exception No deployments available for selected model, Try again in 1 seconds. Passed model=gemini-1.5-pro-001. pre-call-checks=False, allowed_model_region=n/a
```

**Comment by ishaan-jaff** [comment]
@NFuentesC what do you see when hit `/health` ?  This exception just means both deployments are in cooldown by the litellm load balancer

**Comment by ghost** [comment]
added - https://github.com/BerriAI/litellm/commit/20bd9332d42b29ae75711d2ea7fd30d139079f1c

should be live for you in the next few minutes @NFuentesC, no upgrades required

**Comment by dhruv-anand-aintech** [comment]
I'm getting this error while using AWS Bedrock via the LiteLLM SDK (no proxy server involved).

Is there a better error message that can be thrown in this case?

**Comment by hanhaiszw** [comment]
I saw the same error, but it returned to normal after a while. I want to know how to avoid this problem. 


Error Log:
litellm.BadRequestError: You passed in model=doubao-1.5-lite-32k. There are no healthy deployments for this model. Received Model Group=doubao-1.5-lite-32k
Available Model Group Fallbacks=None
