### ISSUE TITLE
[Feature]: LiteLLM.INFO 

### ISSUE THREAD

**Issue by anmolbhatia05** [BerriAI/litellm#3937]
### The Feature

LiteLLM.INFO currently logs curl requests made to llm endpoints, like such - 
```
10:24:07 - LiteLLM:INFO: 
POST Request Sent from LiteLLM:
curl -X POST \
https://abc.openai.azure.com//openai/ \
-H 'Authorization: Bearer 1a7fac2********************' \
-d '{'model': 'abc-gpt4-32k', 'messages': [{'content': 'whats the meaning of life', 'role': 'user'}], 'stream': True, 'extra_body': {}}'
```
In our usecases, the messages.content can have some private data. We don't want this to be logged when our service is hosted on AWS/GCP.  

1) Is there a way to redact this information ? 
2) Can this be part of LiteLLM.DEBUG instead of INFO ?

### Motivation, pitch

The motivation behind this issue is the privacy of our private data. We don't want this to be logged by the hosting providers.

**Comment by ghost** [comment]
hey @anmolbhatia05 what do you use litellm.info for? 

the reason behind keeping this in info, is to make it easy to see raw request/response without navigating debug logs (it's quite verbose right now).

**Comment by Manouchehri** [comment]
What does your config look like? By default, this is what we see in our logs when using `/v1/chat/completions`:

<img width="737" alt="image" src="https://github.com/BerriAI/litellm/assets/7232674/2c87bdee-fcf6-4368-a167-3e522e75089a">

i.e. nothing.

**Comment by ishaan-jaff** [comment]
<img width="1071" alt="Screenshot 2024-06-05 at 8 57 50 AM" src="https://github.com/BerriAI/litellm/assets/29436595/2c0b5969-d4a5-4fb9-81dc-a6d53498f3a2">
these are our logs in production. Can confirm we don't see the raw request / response 



@anmolbhatia05 can we hop on a call to see the issue / help out. We'll be able to solve this faster. What's the best email to send an invite to @anmolbhatia05 ? 

If it's easier here's my cal: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
My linkedin if you want to DM: https://www.linkedin.com/in/reffajnaahsi/

**Comment by ishaan-jaff** [comment]
this is fixed @anmolbhatia05 had another user ask for this 

https://github.com/BerriAI/litellm/pull/2980 

Can we hop on a call @anmolbhatia05 I want to improve litellm for you. Sharing a link to my cal for your convenience:

https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
