### ISSUE TITLE
[Feature]: add support for gpt-3.5-instruct + pricing + context window 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#394]
### The Feature

^ 

### Motivation, pitch

new LLM :)

**Comment by WilliamEspegren** [comment]
@ishaan-jaff Is this model even out yet?

**Comment by ishaan-jaff** [comment]
<img width="623" alt="Screenshot 2023-09-18 at 10 48 28 AM" src="https://github.com/BerriAI/litellm/assets/29436595/c726e860-6c71-4c5a-a307-a39bf29dd7b8">

**Comment by WilliamEspegren** [comment]
@ishaan-jaff Amazing 🔥

**Comment by ishaan-jaff** [comment]
done

**Comment by WilliamEspegren** [comment]
@ishaan-jaff How was the instruct model feeling? Better or worse then chat completion?
