### ISSUE TITLE
[Docs]: OIDC configs / usage

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#3946]
### The Feature

There's 8 different combos that LiteLLM's OIDC auth supports.

- [ ] CircleCI (v2) -> Amazon Bedrock
- [ ] CircleCI (v2) -> Azure OpenAI
- [ ] Google Cloud Run -> Amazon Bedrock
- [ ] Google Cloud Run -> Azure OpenAI
- [ ] GitHub Actions Runner -> Amazon Bedrock
- [ ] GitHub Actions Runner -> Azure OpenAI
- [ ] Azure -> Amazon Bedrock
- [ ] Azure -> Azure OpenAI

Misc notes:

For CircleCI (v2), this is what the token looks like on AWS :
```json
{
  "eventVersion": "1.08",
  "userIdentity": {
    "type": "WebIdentityUser",
    "principalId": "arn:aws:iam::ACCOUNT_ID_REMOVED_BY_DAVID:oidc-provider/oidc.circleci.com/org/c5a99188-154f-4f69-8da2-b442b1bf78dd:c5a99188-154f-4f69-8da2-b442b1bf78dd:org/c5a99188-154f-4f69-8da2-b442b1bf78dd/project/2d1b2d2b-1fa1-475a-8c24-ed94faeb5c96/user/e8b04548-eeeb-4164-a71d-65d5b6776256/vcs-origin/github.com/BerriAI/litellm/vcs-ref/refs/heads/main",
    "userName": "org/c5a99188-154f-4f69-8da2-b442b1bf78dd/project/2d1b2d2b-1fa1-475a-8c24-ed94faeb5c96/user/e8b04548-eeeb-4164-a71d-65d5b6776256/vcs-origin/github.com/BerriAI/litellm/vcs-ref/refs/heads/main",
    "identityProvider": "arn:aws:iam::ACCOUNT_ID_REMOVED_BY_DAVID:oidc-provider/oidc.circleci.com/org/c5a99188-154f-4f69-8da2-b442b1bf78dd"
  },
  "eventTime": "2024-05-31T16:54:55Z",
  "eventSource": "sts.amazonaws.com",
  "eventName": "AssumeRoleWithWebIdentity",
  "awsRegion": "us-east-1",
  "sourceIPAddress": "44.201.170.191",
  "userAgent": "Boto3/1.34.34 md/Botocore#1.34.34 ua/2.0 os/linux#5.15.0-1056-aws md/arch#x86_64 lang/python#3.11.9 md/pyimpl#CPython cfg/retry-mode#legacy Botocore/1.34.34",
  "requestParameters": {
    "roleArn": "arn:aws:iam::ACCOUNT_ID_REMOVED_BY_DAVID:role/litellm-github-unit-tests-circleci",
    "roleSessionName": "my-test-session",
    "durationSeconds": 3600
  },
  "responseElements": {
    "credentials": {
      "accessKeyId": "REMOVED_BY_DAVID",
      "sessionToken": "REMOVED_BY_DAVID",
      "expiration": "May 31, 2024, 5:54:55 PM"
    },
    "subjectFromWebIdentityToken": "org/c5a99188-154f-4f69-8da2-b442b1bf78dd/project/2d1b2d2b-1fa1-475a-8c24-ed94faeb5c96/user/e8b04548-eeeb-4164-a71d-65d5b6776256/vcs-origin/github.com/BerriAI/litellm/vcs-ref/refs/heads/main",
    "assumedRoleUser": {
      "assumedRoleId": "TEMP_THING_REMOVED_BY_DAVID:my-test-session",
      "arn": "arn:aws:sts::ACCOUNT_ID_REMOVED_BY_DAVID:assumed-role/litellm-github-unit-tests-circleci/my-test-session"
    },
    "provider": "arn:aws:iam::ACCOUNT_ID_REMOVED_BY_DAVID:oidc-provider/oidc.circleci.com/org/c5a99188-154f-4f69-8da2-b442b1bf78dd",
    "audience": "c5a99188-154f-4f69-8da2-b442b1bf78dd"
  },
  "requestID": "64884936-6a00-48ea-af69-19ac481f971a",
  "eventID": "b4585ede-6fe7-4e53-b82e-93df202609a6",
  "readOnly": true,
  "resources": [
    {
      "accountId": "ACCOUNT_ID_REMOVED_BY_DAVID",
      "type": "AWS::IAM::Role",
      "ARN": "arn:aws:iam::ACCOUNT_ID_REMOVED_BY_DAVID:role/litellm-github-unit-tests-circleci"
    }
  ],
  "eventType": "AwsApiCall",
  "managementEvent": true,
  "recipientAccountId": "ACCOUNT_ID_REMOVED_BY_DAVID",
  "eventCategory": "Management",
  "tlsDetails": {
    "tlsVersion": "TLSv1.3",
    "cipherSuite": "TLS_AES_128_GCM_SHA256",
    "clientProvidedHostHeader": "sts.amazonaws.com"
  }
}
```

### Motivation, pitch

Docs are needed :) 

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by ghost** [comment]
hey @Manouchehri any updates on this?

**Comment by Manouchehri** [comment]
@krrishdholakia: I've already done a fair amount of informal docs in PRs:

https://github.com/BerriAI/litellm/pull/3507#issue-2284141057

https://github.com/BerriAI/litellm/pull/3688#issuecomment-2142220554

https://github.com/BerriAI/litellm/pull/3861#issue-2319503043

You can see you're using it a lot with Bedrock unit tests already.

https://github.com/BerriAI/litellm/blob/fa045953287682ce849b485b7b6615c84fb29f63/litellm/tests/test_bedrock_completion.py#L527C5-L545

This is the joy of OIDC, you're using ai.moda's AWS account without me ever having to give you static keys.

**Comment by ghost** [comment]
@Manouchehri can I ask for a formal doc on this? 

It would help me + others a lot

**Comment by Manouchehri** [comment]
This is very much an enterprise-y thing, so I'll admit it's pretty hard to justify spending an unpaid day to create detailed docs on how to configure all of these different providers.

I will document how to use the GitHub Action Runner OIDC flow with Azure OpenAI, since we have a paying client that is going to be using LiteLLM in part of their project. That said, that part of the project is a few weeks out.

**Comment by Manouchehri** [comment]
Working on this now.

**Comment by ghost** [comment]
Thank you! @Manouchehri
