### ISSUE TITLE
[Bug]: Azure gpt-4o context not defined

### ISSUE THREAD

**Issue by sauravpanda** [BerriAI/litellm#3947]
### What happened?

Hey, so I am using Litellm in my project and passing the configuration of the model via JSON:

Is there a way to pass the relevant data via arg?

```
"default_model_config": {
    "model": "azure/gpt-4o",
    "input_cost_per_token": 0.000005,
    "output_cost_per_token": 0.000015
}
```

But when using my azure deployment I am getting the following error:

```
Traceback (most recent call last):
  File "/app/github_app/github_helper/pull_requests.py", line 64, in process_pull_request
    review_data = reviewer.review_pull_request(
  File "/root/.cache/pypoetry/virtualenvs/cloudcode-bot-9TtSrW0h-py3.9/lib/python3.9/site-packages/kaizen/reviewer/code_review.py", line 64, in review_pull_request
    if self.provider.is_inside_token_limit(PROMPT=prompt):
  File "/root/.cache/pypoetry/virtualenvs/cloudcode-bot-9TtSrW0h-py3.9/lib/python3.9/site-packages/kaizen/llms/provider.py", line 42, in is_inside_token_limit
    > litellm.get_max_tokens(self.model) * percentage
  File "/root/.cache/pypoetry/virtualenvs/cloudcode-bot-9TtSrW0h-py3.9/lib/python3.9/site-packages/litellm/utils.py", line 7059, in get_max_tokens
    raise Exception(
Exception: Model gpt-4o isn't mapped yet. Add it here - https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json
```

### Twitter / LinkedIn details

https://x.com/sauravpanda24 | https://www.linkedin.com/in/pandasaurav/

**Comment by ghost** [comment]
hey @sauravpanda that looks right to me - 

i think you're error is being raised by `get_max_tokens` which you're using inside `is_inside_token_limit` 

for custom model values in the helper, just register it first - https://docs.litellm.ai/docs/completion/token_usage#9-register_model (let me know if we can simplify this further) 


i also added gpt-4o pricing on our end as well - https://github.com/BerriAI/litellm/commit/668c894e9a33f62d2758754cd73e37e0629441b1

curious - how're you using litellm in your package?

**Comment by sauravpanda** [comment]
Hey, thanks for the update. I was wondering if we can pass the custom model values using args like we pass `input_cost_per_token. ' This way, you don't need to add all the custom model mapping.

I'm not sure if it makes sense, as I mostly use Azure. If I can pass the model names directly without needing to register the model, it would be great. By the way, thanks for helping with the issue; I am not well-versed in all the functionality that Litellm offers.

**Comment by ghost** [comment]
> wondering if we can pass the custom model values using args like we pass `input_cost_per_token

is this to `get_max_tokens`? 

why pass input_cost_per_token to `get_max_tokens`?

**Comment by sauravpanda** [comment]
Sorry for the confusion, I am not passing the `input_cost_per_token` in `get_max_tokens`.I am using get_max_tokens to check if I need to chunk the code diff or if I can pass it directly. 

I was just referring to how we can pass the `input_cost_per_token` as an argument in `litellm.completion`; I was wondering if we can have something similar.

**Comment by ghost** [comment]
oh that's already supported 

just pass it in `completion(...input_cost_per_token=<your-custom-cost>)`

https://github.com/BerriAI/litellm/blob/a0fe3a8d256a4f169ea414e9d4f355f0759fb456/litellm/main.py#L574
