### ISSUE TITLE
[Feature]: Refactor `/health` to call `/v1/chat/completions`,  `/v1/embeddings`, etc

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#3957]
### The Feature

https://www.python-httpx.org/advanced/transports/#asgi-transport

Instead of having custom ahealth functions, it would make a lot more sense to actually call the endpoints.

### Motivation, pitch

Right now, it's possible (and does happen) where the health check code fail but the endpoint is working fine.

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by ghost** [comment]
@Manouchehri we already call the actual LLM API endpoints with `/health`. 

To check for health of proxy endpoints - you should call `/health/liveliness`

**Comment by Manouchehri** [comment]
You sureeeee? :P 

https://github.com/BerriAI/litellm/blob/b7c6f0500b35d6e6afd0d09d6b644365da8445b4/litellm/llms/azure.py#L1187-L1279

**Comment by Manouchehri** [comment]
`ahealth_check` doesn't look like `acompletion` to me. 😛 

```json
{
  "unhealthy_endpoints": [
    {
      "model": "azure/gpt-4-turbo-2024-04-09",
      "api_version": "2024-05-01-preview",
      "azure_ad_token": "oidc/google/https://example.com",
      "api_base": "https://gateway.ai.cloudflare.com/v1/removed/removed/azure-openai/removed",
      "temperature": 1,
      "error": "Missing credentials. Please pass one of `api_key`, `azure_ad_token`, `azure_ad_token_provider`, or the `AZURE_OPENAI_API_KEY` or `AZURE_OPENAI_AD_TOKEN` environment variables. stack trace: Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/litellm/main.py\", line 4362, in ahealth_check\n    response = await azure_chat_completions.ahealth_check(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/litellm/llms/azure.py\", line 1146, in ahealth_check\n    client = AsyncAzureOpenAI(\n             ^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/openai/lib/azure.py\", line 410, in __init__\n    raise OpenAIError(\nopenai.OpenAIError: Missing credentials. Please pass one of `api_key`, `azure_ad_token`, `azure_ad_token_provider`, or the `AZURE_OPENAI_API_KEY` or `AZURE_OPENAI_AD_TOKEN` environment variables.\n"
    }
  ],
  "healthy_count": 0,
  "unhealthy_count": 1
}
```

This endpoint has been working perfectly (including right now) when using the actual `/v1/chat/completions` endpoint.

**Comment by ghost** [comment]
@Manouchehri for azure and openai specifically we call the endpoints with the `with_raw_response` call 

https://github.com/BerriAI/litellm/blob/2ce5dc0dfdc7c56471b06d2c66c83e2fa98e772a/litellm/llms/azure.py#L1239

this is done so we can return remaining tokens, etc. as part of the health response, which we can't do in a regular chat completion call b/c with_raw_response makes a blocking call. 

for the rest it **is** an acompletion call. 

See code: https://github.com/BerriAI/litellm/blob/2ce5dc0dfdc7c56471b06d2c66c83e2fa98e772a/litellm/main.py#L4422
