### ISSUE TITLE
[Feature]: Finetuning wrapper for openai, hf, etc. 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#396]
### The Feature

@shauryr request: [finetuning wrapper](https://gpt-index.readthedocs.io/en/latest/examples/finetuning/knowledge/finetune_knowledge.html) for [openai](https://platform.openai.com/docs/guides/fine-tuning), huggingface etc.

### Motivation, pitch

@shauryr could you add some more details on the 'why'?

**Comment by shauryr** [comment]
As many fine-tuning studies and experiments have demonstrated, fine-tuning on a specific dataset can lead to better results. Moreover, there can be scenarios where developers would like to fine-tune on private data. To support this, I suggest that we should enhance our framework to support fine-tuning using local LLMs like ollama or huggingface models.

Additional resources that can help provide a broader context are:
- This tweet explains the concept of fine-tuning: https://twitter.com/RLanceMartin/status/1694402095376658726 
- This Langchain blog post provides valuable insights: https://blog.langchain.dev/using-langsmith-to-support-fine-tuning-of-open-source-llms/
- Currently, Langchain only supports OpenAI, as indicated on this page: https://blog.langchain.dev/chatopensource-x-langchain-the-future-is-fine-tuning-2/

I envision leveraging litellm over toolkit like OpenAI or Huggingface and would like the ability to implement fine-tuning directly through litellm.

Looking forward to your thoughts on this.

**Comment by ghost** [comment]
can you give me a sample code snippet of how you'd expect this to work 

Eg.: 
```
import litellm 

litellm.finetuning(model, dataset) 
```

Note: Different models have different dataset requirements 

Any specific hf models you're looking at?

**Comment by ghost** [comment]
@shauryr think this might be relevant - https://docs.autoblocks.ai/

**Comment by shauryr** [comment]
Have a look at this notebook - https://colab.research.google.com/drive/1YCyDHPSl0d_ULubCVshrP5hLqUCorr7d?usp=sharing&ref=blog.langchain.dev#scrollTo=C7HeoOjhwVm-

Specifically the line 

`job = openai.FineTuningJob.create(training_file=training_file.id, model="gpt-3.5-turbo")`

Something like this for litellm? If I could just change the name of the model here to lets say a huggingface model?

what do you think?

**Comment by ghost** [comment]
Any specific hf models you're trying to use? will be helpful for testing @shauryr

**Comment by shauryr** [comment]
That makes sense. You can start with small chat model - `daryl149/llama-2-7b-chat-hf`

mentioned [here](https://colab.research.google.com/drive/1tpywvzwOS74YndNXhI8NUaEfPeqOc7ub?usp=sharing&ref=blog.langchain.dev#scrollTo=kCACPc3lRJAr)

Thanks for looking into this!

**Comment by ghost** [comment]
@shauryr the huggingface finetuning is local model finetuning. It looks like there's more complexity + params involved there than the openai finetuning endpoint. 

Is there a reason you want both merged in 1 abstraction layer? 

I'm unsure how you'd map across the 2, so any advice/suggestions here are welcome.

**Comment by ghost** [comment]
Example params i'm looking at 
<img width="706" alt="Screenshot 2023-09-20 at 4 52 39 PM" src="https://github.com/BerriAI/litellm/assets/17561003/80347a05-3fab-4c00-86e4-6fc8797bcc6b">

**Comment by ishaan-jaff** [comment]
closing as not planned
