### ISSUE TITLE
[Feature]: Include Git hash in `x-litellm-version`

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#3968]
### The Feature

e.g. I would like to see this if I was running `1.39.6` / b8df5d1a012a687caec0cf35bf8f728a037421e0.

```
< HTTP/2 200
< date: Wed, 08 May 2024 16:09:26 GMT
< content-type: text/event-stream; charset=utf-8
< x-litellm-model-id: b8f273501bcf8ca2dc6d3d30f02ab1a0c8fa860c166d3038bd0a48f61d38a042
< x-litellm-model-version: 1.39.6-b8df5d1a012a687caec0cf35bf8f728a037421e0
```

Expanding on #3528. Related to #3673.

### Motivation, pitch

We run a forked version of LiteLLM; it's _extremely_ close to upstream LiteLLM, mostly with just a few PRs cherry-picked early.

When troubleshooting #3920, I had to spend a minute or two thinking about which version of `v1.39.6` I was running, because I had multiple extra commits cherry-picked in. If we had the Git hash included in `x-litellm-version`, it would have been obvious immediately that the cherry-picked commits didn't cause an new issues.

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by ghost** [comment]
@Manouchehri which PR's are blocking you from using main? 

sdk isn't aware of git commit.

**Comment by Manouchehri** [comment]
> sdk isn't aware of git commit.

I should be able to do this during the Docker build. I did it a few years ago for a different project. I need to do it for an unrelated internal project, so I don't mind contributing it to LiteLLM too.

> which PR's are blocking you from using main?

It's a rolling thing. I really don't think you should be merging in all of my PRs into a tagged release before testing. e.g. as of today it's #3958, #3712, and #3691; next week it will probably be a different set of PRs. 😄
