### ISSUE TITLE
[Bug]: Division by zero error when accessing model metric on proxy server UI

### ISSUE THREAD

**Issue by dlebech** [BerriAI/litellm#3977]
### Problem

- Visit the proxy UI
- Access Models -> Model Analytics
- Certain models throws an Internal Server Error when fetching the `/model/metrics` endpoint
- Looking at the stacktrace, it seems to be a Division by Zero error during fetching of the metrics

The final error: `prisma.errors.RawQueryError: ERROR: division by zero`

### Proposed fix

The problem is this line: https://github.com/BerriAI/litellm/blob/93c9ea160d1926b49b067e487f511fbe172c95a4/litellm/proxy/proxy_server.py#L11563

If "completion_tokens" is 0, then the calculation fails, even with the `HAVING` clause.

Introducing a `NULLIF` will make the calculation work, but it will effectively ignore the rows in the table that have 0 in completion_tokens field. If this is acceptable, then the line should be:

```sql
AVG(EXTRACT(epoch FROM ("endTime" - "startTime")) / NULLIF("completion_tokens", 0)) AS avg_latency_per_token
```

Thank you.

### Relevant log output

```shell
File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 10696, in model_metrics
    db_response = await prisma_client.db.query_raw(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by ghost** [comment]
can you share some example rows with 0 completion_tokens @dlebech 

i wonder when this is the case

**Comment by dlebech** [comment]
@krrishdholakia yes of course. It seems to be text-embedding-ada-002 (on Azure). Here's the newest rows in the `LiteLLM_SpendLogs` table:

| call_type  | spend      | total_tokens | prompt_tokens | completion_tokens | startTime            | endTime              | model                  | cache_hit | completionStartTime   | model_group           |
|------------|------------|--------------|---------------|-------------------|----------------------|----------------------|------------------------|-----------|-----------------------|-----------------------|
| aembedding | 0.0000004  | 4            | 4             | 0                 | 2024-06-02 22:09:11.998 | 2024-06-02 22:09:12.212 | text-embedding-ada-002 | None      | 2024-06-02 22:09:12.212 | text-embedding-ada-002 |
| aembedding | 0.0000004  | 4            | 4             | 0                 | 2024-06-02 21:55:29.961 | 2024-06-02 21:55:30.331 | text-embedding-ada-002 | None      | 2024-06-02 21:55:30.331 | text-embedding-ada-002 |
| acompletion| 0.001129   | 711          | 586           | 125               | 2024-06-02 19:02:32.112 | 2024-06-02 19:02:33.588 | gpt-35-turbo           | None      | 2024-06-02 19:02:33.588 | gpt-3.5-turbo         |
| acompletion| 0.0008885  | 592          | 591           | 1                 | 2024-06-02 19:02:31.557 | 2024-06-02 19:02:31.842 | gpt-35-turbo           | None      | 2024-06-02 19:02:31.842 | gpt-3.5-turbo         |
| acompletion| 0.0008565  | 568          | 559           | 9                 | 2024-06-02 19:02:30.873 | 2024-06-02 19:02:31.260 | gpt-35-turbo           | None      | 2024-06-02 19:02:31.260 | gpt-3.5-turbo         |
| aembedding | 0.0000427  | 427          | 427           | 0                 | 2024-06-02 19:02:30.362 | 2024-06-02 19:02:30.605 | text-embedding-ada-002 | None      | 2024-06-02 19:02:30.605 | text-embedding-ada-002 |
| acompletion| 0.0040865  | 2663         | 2479          | 184               | 2024-06-02 19:00:42.889 | 2024-06-02 19:00:44.743 | gpt-35-turbo           | None      | 2024-06-02 19:00:44.743 | gpt-3.5-turbo         |
| acompletion| 0.003728   | 2485         | 2484          | 1                 | 2024-06-02 19:00:42.383 | 2024-06-02 19:00:42.612 | gpt-35-turbo           | None      | 2024-06-02 19:00:42.612 | gpt-3.5-turbo         |
| acompletion| 0.00369    | 2458         | 2452          | 6                 | 2024-06-02 19:00:41.639 | 2024-06-02 19:00:42.044 | gpt-35-turbo           | None      | 2024-06-02 19:00:42.044 | gpt-3.5-turbo         |
| aembedding | 0.0000112  | 112          | 112           | 0                 | 2024-06-02 19:00:40.981 | 2024-06-02 19:00:41.202 | text-embedding-ada-002 | None      | 2024-06-02 19:00:41.202 | text-embedding-ada-002 |

My model config for this model is specified like this:

```yaml
  - model_name: text-embedding-ada-002
    litellm_params:
      model: azure/text-embedding-ada-002
      api_base: ...
      api_key: ...
      api_version: "2024-02-01"
      tpm: 240000
    model_info:
      base_model: azure/text-embedding-ada-002
```

**Comment by ghost** [comment]
oh! got it - thanks, i'll look into this 

curious - how do you use model analytics today? @dlebech

**Comment by dlebech** [comment]
@krrishdholakia In this case I was just clicking around the interface and noticed the error, so I thought I would report.

It's definitely good to know the latency and spend per model, but it's more of a nice-to-have than a need-to-have for me. The killer feature for your project is still the unified API for LLMs (and simple load balancing). If it did nothing else than that, that would be enough for my use cases.

Thanks for looking into this!

**Comment by ghost** [comment]
Can we do a 10minute call this week? @dlebech 

would **love** to learn how to improve for you - https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by ishaan-jaff** [comment]
fix PR is here: https://github.com/BerriAI/litellm/pull/4021 @dlebech we'd love to get on a call. What's the best email to send an invite to. ?I can set a call up 


I also sent a Linkedin invite if that's easier

**Comment by dlebech** [comment]
@ishaan-jaff @krrishdholakia  thanks for looking into this! I would prefer not sharing my email here. I've previously been in contact with @krrishdholakia on Linkedin, and let's keep any conversation beyond this issue there -- I hope that's ok :slightly_smiling_face:
