### ISSUE TITLE
[Bug]: Keys with budget set throw unauthorized error

### ISSUE THREAD

**Issue by anshuman852** [BerriAI/litellm#3979]
### What happened?
Version - litellm:main-v1.38.12 running with postgres and redis on kuberentes
So i created a new key in the default team 
![image](https://github.com/BerriAI/litellm/assets/31951186/be440d01-e6cb-4418-91e9-b6bc62ffd5f4)
Then when i send a request to it. i get unauthorized 401 
and this is printed in the logs 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 1087, in user_api_key_auth
    specific_user_id_information = user_id_information[0]
                                   ~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by ishaan-jaff** [comment]
@anshuman852 can you bump to 1.40.2 and see if you see the same issue ?

**Comment by ishaan-jaff** [comment]
<img width="640" alt="Screenshot 2024-06-05 at 8 44 46 AM" src="https://github.com/BerriAI/litellm/assets/29436595/b7dfc426-04ca-46eb-a370-4e64d10b67cb">


we have logic to prevent the error you're seeing

**Comment by ishaan-jaff** [comment]
@anshuman852 curious do you use LiteLLM proxy with realtime + batch workloads ?

**Comment by anshuman852** [comment]
> @anshuman852 can you bump to 1.40.2 and see if you see the same issue ? 
> 

Ye seems to be resolved now thanks, also no i don't use any batching. I was just trying a normal test call with a budget limited key

**Comment by ishaan-jaff** [comment]
@anshuman852 can we setup a direct support channel with you ? What's the best email to send an invite to ? 

Here's my linkedin if you prefer DMs: https://www.linkedin.com/in/reffajnaahsi/
