### ISSUE TITLE
[Feature]: Add petals 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#399]
### The Feature

cc @smig23

### Motivation, pitch

-

**Comment by ishaan-jaff** [comment]
> Specifically for my aims, I'm running a private swarm as a experiment with a view to implementing with in private organization, who have idle GPU resources, but it's distributed. The initial target would be inferencing and if litellm was able to be the abstraction layer, it would allow flexibility to go another direction with hosting in the future.

**Comment by ishaan-jaff** [comment]
@smig23 I'm working on this issue now - what models on Petals do you plan on using ? 

Mind sharing a code snippet of how you're calling petals currently ? 


I found this on how to use petals:

```python
import torch
from transformers import AutoTokenizer
from petals import AutoDistributedModelForCausalLM

model_name = "petals-team/StableBeluga2"
# You could also use "meta-llama/Llama-2-70b-chat-hf" or any other supported model from 🤗 Model Hub

tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=False, add_bos_token=False)
model = AutoDistributedModelForCausalLM.from_pretrained(model_name)
model = model.cuda()

inputs = tokenizer('A cat in French is "', return_tensors="pt")["input_ids"].cuda()
outputs = model.generate(inputs, max_new_tokens=3)
print(tokenizer.decode(outputs[0]))

```

**Comment by ishaan-jaff** [comment]
here's the interface of how to use petals with litellm:

```python
from litellm import completion
import litellm

response = completion(model="petals/petals-team/StableBeluga2", messages=[{ "content": "Hello, how are you?","role": "user"}])

print(response)
```

**Comment by ishaan-jaff** [comment]
docs: https://docs.litellm.ai/docs/providers/petals

**Comment by ishaan-jaff** [comment]
notebook: https://colab.research.google.com/github/BerriAI/litellm/blob/main/cookbook/LiteLLM_Petals.ipynb

**Comment by ishaan-jaff** [comment]
@smig23 can you let me know if this works for you ? 


closing this issue feel free to re-open😃

**Comment by smig23** [comment]
Excellent thank you! 
Sorry I didn't get back sooner but appreciate the quick work. I'll give it a test and let you know. 
Cheers.
