### ISSUE TITLE
[Feature]: Return rate limit for open ai responses

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#400]
### The Feature

see https://github.com/novex-ai/parallel-parrot/pull/7 

- They make http requests to openai and then read response.headers to access the users rate limit. 

We need to add this functionality to litellm to ensure they don't have any regressions

### Motivation, pitch

-

**Comment by ghost** [comment]
Seems like this is an open issue on the openai-python client sdk. 
https://github.com/openai/openai-python/issues/416

**Comment by ghost** [comment]
Potential solution: 
Get the response header from the request as is: https://github.com/openai/openai-python/issues/416#issuecomment-1623205537

What people want
```
x-ratelimit-limit-requests: 3500
x-ratelimit-remaining-requests: 3499
x-ratelimit-reset-requests: 17ms
```

Potential DX: 
```
from litellm import completion 

response = completion(model, messages) 

print(response.response_headers)
```

**Comment by ghost** [comment]
This *would* require us to move to the openai http endpoint instead of the package.
