### ISSUE TITLE
[Feature]: Using the Amazon Bedrock Converse API

### ISSUE THREAD

**Issue by iwamot** [BerriAI/litellm#4000]
### The Feature

Amazon Bedrock has launched a Converse API.
https://aws.amazon.com/about-aws/whats-new/2024/05/amazon-bedrock-new-converse-api/
https://docs.aws.amazon.com/bedrock/latest/userguide/conversation-inference.html

I think it is a good idea to take advantage of this.

### Motivation, pitch

It is exactly like the Bedrock version of LiteLLM, and the unified interface should make it easier to replace models.
https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_Converse.html
https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_ConverseStream.html

It should also make Tools easier to use by eliminating the need for XML processing for Claude.

### Twitter / LinkedIn details

@iwamot / https://www.linkedin.com/in/iwamot/

**Comment by ghost** [comment]
Thanks for this issue - ~~planning on adding this today~~ the change looks larger than expected. will get it done by tomorrow.

**Comment by ghost** [comment]
this looks relevant - https://docs.aws.amazon.com/bedrock/latest/userguide/conversation-inference.html#conversation-inference-supported-models-features

**Comment by Ozennefr** [comment]
+1 thanks for the awesome reactivity to releases !

**Comment by ghost** [comment]
looks like we can call anthropic for tool calling on bedrock without converse as well - https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-anthropic-claude-messages.html

**Comment by ghost** [comment]
it's not clear how tool choice is required - 
https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_ToolChoice.html
https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_AnyToolChoice.html

is 'any' a string or a typed dict with k-v pairs? 

assuming it's a string like openai for now

**Comment by ghost** [comment]
Tests will need to cover

- normal call
- streaming
- function calling
- image calling (url + b64 image)

**Comment by ghost** [comment]
PR is now live - https://github.com/BerriAI/litellm/pull/4033

Hoping to have this merged by tomorrow.

**Comment by ghost** [comment]
facing a couple of issues with converse. 

E.g. - here, they don't handle multiple messages for cohere text models. So we'd need to handle this on top of them, to ensure calls don't fail (i.e. maintain the existing implementation of concatenating messages) 
<img width="1105" alt="Screenshot 2024-06-06 at 10 07 34 PM" src="https://github.com/BerriAI/litellm/assets/17561003/5126a544-9890-4be3-ab9b-3810389cc805">


there's multiple examples like this 
- e.g. toolconfig -> unsupported by cohere command r, but tool calling is. so we still need to handle this on top of converse

**Comment by ghost** [comment]
the thing their implementation does well is solve the anthropic tool calling problem, so i think for v0 scope it might make sense to begin there, and expand gradually
