### ISSUE TITLE
[Feature]: Support Azure OpenAI in Text-To-Speech

### ISSUE THREAD

**Issue by lurebat** [BerriAI/litellm#4002]
### The Feature

Great work on #3928 , but currently it only supports openai and compatible endpoints, and not azure's API.

### Motivation, pitch

I use litellm's proxy to use azure's openapi with plenty of compatible software, but currently there is no workaround for text-to-speech.

The api is very similar obviously, it just needs the minor adjusments all azure apis have

**Comment by ghost** [comment]
hey @lurebat curious how do you plan on using litellm proxy w/ azure tts? 

if there's a specific software / e2e flow you had in mind, that would help me test it out 


also is this the azure tts - https://learn.microsoft.com/en-us/azure/ai-services/speech-service/rest-text-to-speech?tabs=streaming#request-body-1? 

it seems to require some sort of separate query language (SSML)

**Comment by lurebat** [comment]
Hey, I want to use it with https://github.com/danny-avila/LibreChat and homeassistant.

What you linked is another service and not what I'm referring to, I want to use the openai speech api: https://learn.microsoft.com/en-us/azure/ai-services/openai/text-to-speech-quickstart?tabs=command-line#rest-api

**Comment by ghost** [comment]
Got it, thanks for clarifying

**Comment by Manouchehri** [comment]
Likewise, I want to use tts-1-hd on Azure OpenAI through LiteLLM for LibreChat.

https://www.librechat.ai/docs/configuration/stt_tts#openai-compatible-tts-services

**Comment by ghost** [comment]
Hi @lurebat PR for this is now live - https://github.com/BerriAI/litellm/pull/4449

---
Can we do a 10min call this week? Would love to learn how you're using litellm, so we can improve 

https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
