### ISSUE TITLE
[Bug]: Fixing non-admin role UI Flow 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#4013]
### What happened?

Creating a parent issue to track some issues in the non-admin ui role flow 

- [x] When setting user to internal user type/role, user can't create key
- [x] for new user, it seems to default to view-only permissions 
- [x] default role should be only from the `LiteLLMRoles` enum, by default it shows 'app_user' 
- [x] invite email doesn't use custom logo (It doesn't appear to use the logo i put in the EMAIL_LOGO_URL)

cc: @ncecere

**Comment by ghost** [comment]
I see the issue re: create keys 

<img width="1573" alt="Screenshot 2024-06-05 at 4 03 01 PM" src="https://github.com/BerriAI/litellm/assets/17561003/e90f1d0f-df95-4050-bc31-5d7bd701cf32">

**Comment by ghost** [comment]
> for new user, it seems to default to view-only permissions

fixed with - https://github.com/BerriAI/litellm/pull/4028/commits/7bef67c4868d4714d490463c89d55e998cec8708
<img width="860" alt="Screenshot 2024-06-05 at 4 11 40 PM" src="https://github.com/BerriAI/litellm/assets/17561003/e8a5ade2-06ac-4d0a-8dac-a2b4b3f44eb0">

**Comment by ghost** [comment]
newer users don't show the old (deprecated) app_user role 

<img width="1105" alt="Screenshot 2024-06-05 at 4 13 47 PM" src="https://github.com/BerriAI/litellm/assets/17561003/c0236d0c-6c97-41f8-9f76-61280f56a6a6">

**Comment by ghost** [comment]
fixed email logo url issue - https://github.com/BerriAI/litellm/pull/4028/commits/847cf3111d6a61e19f14ff0edc78ddb32c870c8a

we support images that are 150 (w) x 50 (h)
<img width="723" alt="Screenshot 2024-06-05 at 4 30 16 PM" src="https://github.com/BerriAI/litellm/assets/17561003/42e35387-95d2-4eeb-9848-2cc4d20c986d">
