### ISSUE TITLE
[Bug]: Run `litellm --config config.yaml` but wait for a long time and nothing happened

### ISSUE THREAD

**Issue by syGOAT** [BerriAI/litellm#4017]
### What happened?

I ran `litellm --config config.yaml`: 
```
# litellm --config config.yaml 
Prisma schema loaded from schema.prisma
Datasource "client": PostgreSQL database "postgres", schema "public" at "aws-0-us-west-1.pooler.supabase.com:6543"
```
But waited for a long time and nothing happened.

### Relevant log output

```shell
# litellm --config config.yaml 
Prisma schema loaded from schema.prisma
Datasource "client": PostgreSQL database "postgres", schema "public" at "aws-0-us-west-1.pooler.supabase.com:6543"
```

**Comment by ishaan-jaff** [comment]
@syGOAT can you try `litellm --config config.yaml --detailed_debug`

**Comment by syGOAT** [comment]
@ishaan-jaff Thanks for your reply! But still the same. 
![image](https://github.com/BerriAI/litellm/assets/102606613/3a7cd65d-7319-48a1-9bf6-65b4a0afc74f)

**Comment by ishaan-jaff** [comment]
looks DB related, can you try:

- use my DB: `postgresql://ishaan:HogdJCvK89Xe@ep-bitter-fog-a573fgz9.us-east-2.aws.neon.tech/ishaan-test2?sslmode=require` 

- if that does not work - try our docker quickstart https://docs.litellm.ai/docs/proxy/deploy

**Comment by syGOAT** [comment]
@ishaan-jaff I used your DB and every thing was all right. 
My DB is [supabase](https://supabase.com/). It seems that litellm donnt even attempt to connect the db because there is no `httpx.ConnectError: All connection attempts failed`. But a supabase db created several days ago by another account can be used now.

**Comment by ishaan-jaff** [comment]
closing since this is not litellm related

**Comment by ishaan-jaff** [comment]
@syGOAT can you use a neon DB ? It might be how you've setup your Supabase DB

**Comment by ishaan-jaff** [comment]
If it's easier we can discuss this over call too. I promise to get to a resolution / fix for you by end of the call: 

sharing a link to my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by arkadiy-telegin** [comment]
Facing the same problem currently. @syGOAT did you find a workaround for connecting supabase?
