### ISSUE TITLE
[Bug]: Authentication Error, No module named 'nacl'.

### ISSUE THREAD

**Issue by sha-ahammed** [BerriAI/litellm#4018]
### What happened?

Steps to reproduce.

1. Start litellm proxy using vscode dev container.
2. navigate to models in ui and try adding a model via the ui.

![Screenshot_5-6-2024_152140_localhost](https://github.com/BerriAI/litellm/assets/24320540/6bb8360f-b078-49fd-a7c4-eec036b0b773)

### Relevant log output

```shell
###### Error shown in UI ###############################################################
Failed to create key: {"error":{"message":"Authentication Error, No module named 'nacl'","type":"auth_error","param":"None","code":400}}

###### Server Output ###################################################################
Traceback (most recent call last):
  File "/workspaces/litellm/litellm/proxy/proxy_server.py", line 11308, in add_new_model
    encrypted_value = encrypt_value(value=v, master_key=master_key)  # type: ignore
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/litellm/litellm/proxy/utils.py", line 2674, in encrypt_value
    import nacl.secret
ModuleNotFoundError: No module named 'nacl'
```

**Comment by ghost** [comment]
how did you start the proxy? @sha-ahammed

**Comment by sha-ahammed** [comment]
> how did you start the proxy? @sha-ahammed

On a dev container, poetry run litellm

**Comment by ghost** [comment]
Got it - i believe it was missing from the pyproject.toml but it is in our docker image 

curious - why not just use our docker image? @sha-ahammed https://docs.litellm.ai/docs/proxy/deploy

**Comment by sha-ahammed** [comment]
@krrishdholakia Using Dev Containers on VS Code is easy for me. For Deployment we use your docker image.
