### ISSUE TITLE
[Feature]: Allow Proxy Admin to Enforce Certain Params

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#4029]
### The Feature

on litellm config - switch litellm_setting
Reject all calls to the proxy without generation_name

```shell

litellm_settings:
  enforced_params: `metadata["generation_name"]
 ```

### Motivation, pitch

-

**Comment by ishaan-jaff** [comment]
working on this 

here's how I think we can move to defining this:

```yaml
  enforced_params:  
  - user
  - max_tokens
  - metadata
  - metadata.generation_name
```

**Comment by ishaan-jaff** [comment]
We already have `enforce_user_param` I imagine we can refactor that doc to just be `enforce_params` (while maintaining backwards compat)

**Comment by kwekewk** [comment]
does it include individual model_list? currently, when i set stream: false, but it got override from user

**Comment by ishaan-jaff** [comment]
@kwekewk wdym ? you want to disable users from sending streaming requests ?

**Comment by kwekewk** [comment]
> @kwekewk wdym ? you want to disable users from sending streaming requests ?

yes

**Comment by ishaan-jaff** [comment]
@kwekewk wouldn't something like this work for you? 

https://docs.litellm.ai/docs/proxy/call_hooks
