### ISSUE TITLE
[Bug]: Demo Playground is not working

### ISSUE THREAD

**Issue by ranjancse26** [BerriAI/litellm#403]
### What happened?

Sorry, I just realized the demo playground doesn't seem to work. It throws an error "API request failed".

https://[litellm.ai/playground](https://litellm.ai/playground)

![image](https://github.com/BerriAI/litellm/assets/2565797/cdaf79e9-eed2-4f01-95f6-83677054a191)

**Comment by ghost** [comment]
It's been deprecated. I should remove it from the readme. Thanks for letting me know.

**Comment by ghost** [comment]
removed

**Comment by ranjancse26** [comment]
@krrishdholakia  One more place where I found the references to the playground.

https://docs.litellm.ai/docs/
