### ISSUE TITLE
[Bug]: Cookbook updates required for the latest version of ChromaDB

### ISSUE THREAD

**Issue by ranjancse26** [BerriAI/litellm#404]
### What happened?

I just noticed the cookbook updates required for the latest version of ChromaDB. Here's the sample code.

https://github.com/BerriAI/litellm/blob/main/cookbook/liteLLM_ChromaDB_Cache.ipynb

Here's the existing usage

client = chromadb.Client()

Here's the documentation that needs to be followed for updating the client creation.

# before
import chromadb
client = chromadb.Client()

# after
import chromadb
client = chromadb.EphemeralClient()

https://docs.trychroma.com/migration

**Comment by ghost** [comment]
Thanks for the callout. I'll fix this. @ranjancse26

**Comment by ghost** [comment]
fix pushed - f9316dfd1a7b3aaa48a53f4747847a508c86552c, thanks for letting us know @ranjancse26
