### ISSUE TITLE
[Feature]: Support Azure AI Studio models

### ISSUE THREAD

**Issue by emerzon** [BerriAI/litellm#4051]
### The Feature

Support for (more) Azure AI Studio models, listed at https://ai.azure.com/explore/models

Currently, only "azure/command-r" and "azure/command-r-plus" work.

### Motivation, pitch

Allow usage with different models.

### Twitter / LinkedIn details

@emersongomesma

**Comment by ghost** [comment]
cc: @ishaan-jaff shouldn't all models already work?

**Comment by emerzon** [comment]
@krrishdholakia other models are not routed corretly, probably due to the incorrect URI.
Here's an example of a llama-3 deployment:

```
$ curl http://localhost:4000/v1/chat/completions --header "Authorization: Bearer <api_key>" --header 'Content-Type: application/json' -d '{
           "model": "llama-3-70b-instruct",
           "messages": [{"role": "user", "content": "Who are you?"}],
           "temperature": 0.7
         }'
{"error":{"message":"AzureException APIError - Method not allowed: POST https://127.0.0.1/openai/deployments/llama3-70b-instruct/chat/completions?api-version=2023-07-01-preview\nNumber Retries = 2, Max Retries=2\nCooldown Deployments=[]","type":null,"param":null,"code":405}}
```

**Comment by ghost** [comment]
got it - i think we'll probably need a separate provider route for azure_ai since it's openai compatible, not azure-openai compatible (:/)

**Comment by ghost** [comment]
DM'ed on linkedin to setup a support channel and make sure our incoming fix solves the issue @emerzon
