### ISSUE TITLE
[Bug]: infinite loop if role is not recognized

### ISSUE THREAD

**Issue by dleen** [BerriAI/litellm#4056]
### What happened?

Calling anthropic claude 3 with a role like "asst" will cause litellm to get stuck in the while loop here: https://github.com/BerriAI/litellm/blob/main/litellm/llms/prompt_templates/factory.py#L793

This loop only breaks if the msg counter increases, but the counter only increases inside clauses like: `messages[msg_i]["role"] in user_message_types` so it never escapes

**Comment by ghost** [comment]
should be fixed soon with - https://github.com/BerriAI/litellm/pull/4033

**Comment by dleen** [comment]
Ah good timing!

**Comment by dleen** [comment]
Confirm that it fixes it
