### ISSUE TITLE
[Feature]: Flexible supports_vision

### ISSUE THREAD

**Issue by iwamot** [BerriAI/litellm#4057]
### The Feature

Similar to https://github.com/BerriAI/litellm/issues/3921.

```python
from litellm import supports_vision

print(supports_vision("anthropic.claude-3-opus-20240229-v1:0"))          # True
print(supports_vision("bedrock/anthropic.claude-3-opus-20240229-v1:0"))  # False
```

### Motivation, pitch

It would be useful to be able to specify the same `model` value for `supports_vision` method as for `completion` method.

### Twitter / LinkedIn details

@iwamot / https://www.linkedin.com/in/iwamot/

**Comment by ghost** [comment]
hey @iwamot curious how would you use this in your code?

**Comment by iwamot** [comment]
Hi @krrishdholakia, thank you for your interest.

Current usage:
```bash
export LITELLM_MODEL=bedrock/anthropic.claude-3-opus-20240229-v1:0
export LITELLM_MODEL_TYPE=anthropic.claude-3-opus-20240229-v1:0
```

Expected usage:
```bash
export LITELLM_MODEL=bedrock/anthropic.claude-3-opus-20240229-v1:0
```

Current code (from https://github.com/iwamot/collmbo):
```python
# From app/env.py
DEFAULT_LITELLM_MODEL = "gpt-4o"
LITELLM_MODEL = os.environ.get("LITELLM_MODEL", DEFAULT_LITELLM_MODEL)

DEFAULT_LITELLM_MODEL_TYPE = LITELLM_MODEL
LITELLM_MODEL_TYPE = os.environ.get("LITELLM_MODEL_TYPE", DEFAULT_LITELLM_MODEL_TYPE)

# From app/slack_ops.py
def can_send_image_url_to_litellm(context: BoltContext) -> bool:
    if IMAGE_FILE_ACCESS_ENABLED is False:
        return False
    bot_scopes = context.authorize_result.bot_scopes or []
    can_access_files = context and "files:read" in bot_scopes
    if can_access_files is False:
        return False
    return supports_vision(model=LITELLM_MODEL_TYPE)
```

**Comment by ghost** [comment]
Hey @iwamot i believ `litellm.supports_vision()` already exists 

see here: https://github.com/BerriAI/litellm/blob/090f350169b8f51639e146d6a5e812e030dd3b32/litellm/utils.py#L4806

i also see it on docs - https://docs.litellm.ai/docs/completion/vision#checking-if-a-model-supports-vision

Where would this have been useful to see?

**Comment by iwamot** [comment]
@krrishdholakia Yes, I am suggesting that it would be helpful to change the behavior of that `supports_vision`.

```python
from litellm import supports_vision

print(supports_vision("anthropic.claude-3-opus-20240229-v1:0"))          # True
print(supports_vision("bedrock/anthropic.claude-3-opus-20240229-v1:0"))  # False, expected: True
```
