### ISSUE TITLE
[Feature]: Allow 'team admin' role for controlling management endpoints for a team 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#4064]
### The Feature

Allow users to assign 'team admins' 

### Motivation, pitch

user request - "We want to create the “teams”, give to them the power to manage that scope, and have logs to investigate anything unexpected that could happen."

**Comment by ghost** [comment]
> the ideal use it would be something like to call the LiteLLM apis with an Admin token, and a second header like “on behalf of” the Team Admin ID or email

**Comment by ghost** [comment]
asana api could be a good reference here: 

```
curl -X POST "https://app.asana.com/api/1.0/tasks" \
     -H "Authorization: Bearer your_access_token_here" \
     -H "Asana-Change-By: user_id_of_the_user_you_act_on_behalf_of" \
     -H "Content-Type: application/json" \
     -d '{
           "data": {
             "name": "New Task",
             "projects": ["project_id_here"]
           }
         }'

```

**Comment by ishaan-jaff** [comment]
Example litellm request 

```shell
curl --location 'http://0.0.0.0:4000/key/generate' \
     --header 'Authorization: Bearer sk-1234' \
     --header 'litellm-changed-by: krrish' \
     --header 'Content-Type: application/json' \
     --data '{
         "user_id" : "ishaan-jaff-3"
     }'
```

**Comment by ishaan-jaff** [comment]
done https://docs.litellm.ai/docs/proxy/multiple_admins
