### ISSUE TITLE
[Feature]: Proxy: Support `API-Key` header in addition to `Authorization` header

### ISSUE THREAD

**Issue by msabramo** [BerriAI/litellm#4077]
### The Feature

Some older versions of the openai Python package will send an `API-Key` header with just the API key instead of `Authorization: Bearer <API key>` when the API type is set to `azure`. Azure OpenAI supports this. LiteLLM proxy doesn’t support this yet so this makes it a little bit harder to get old code using Azure OpenAI to use LiteLLM seamlessly. 

LiteLLM complains with:

```
Authentication Error, No api key passed in.
```

### Motivation, pitch

Would help LiteLLM proxy to be a drop-in replacement for Azure OAI in more situations

**Comment by ishaan-jaff** [comment]
Fix PR here: https://github.com/BerriAI/litellm/pull/4088 @msabramo any idea what OpenAI version was being used ? will help me test it

**Comment by msabramo** [comment]
> Fix PR here: #4088 @msabramo any idea what OpenAI version was being used ? will help me test it

Thanks!

openai 0.27.0

**Comment by ishaan-jaff** [comment]
closing since fixed
