### ISSUE TITLE
[Feature]: add metadata logging to PromptLayer/Helicone

### ISSUE THREAD

**Issue by nsbradford** [BerriAI/litellm#408]
### The Feature

litellm.integrations.prompt_layer and litellm.integrations.helicone are missing ability to log metadata

### Motivation, pitch

Monitoring libraries are basically useless without logging metadata (otherwise finding your request is a needle in a haystack)

### Impl
adding this to PromptLayer is straightforward (docs https://docs.promptlayer.com/languages/rest-api), I can't find any official docs on Helicone REST API, and less sure how to thread through the callbacks, would need to look closer at litellm code

**Comment by ghost** [comment]
Hey @nsbradford, 

What sort of metadata are you looking to log? 


### Additional Notes
Here's the helicone implementation - i did it based off their async code. https://github.com/BerriAI/litellm/blob/main/litellm/integrations/helicone.py
We also let you write your own custom callback (just on success for now, but happy to add on failure/input, etc. if you need it) - https://docs.litellm.ai/docs/observability/custom_callback

**Comment by ghost** [comment]
Is this what you're referring to? 
https://github.com/BerriAI/litellm/blob/31fc90b23946d2d06188feaab610375c5aeeec45/litellm/integrations/prompt_layer.py#L37

**Comment by ghost** [comment]
bump on this @nsbradford

**Comment by ishaan-jaff** [comment]
It looks like we're missing sending the following vars 

```
"prompt_id": "<PROMPT ID>",
"prompt_input_variables": "<Dictionary of variables for prompt>",
"prompt_version": "<Integer of prompt version>"
"tags": ["hello", "world"],
```
IMO i think we could do this in one of three ways:
- since we expose the ability to now make callback functions maybe making your own callback function is the correct abstraction

- we could add a new completion_variable called `callback_vars` and it's defined like
```python
{name:"promptlayer", "vars": {"prompt_id": "<PROMPT ID>",
"prompt_input_variables": "<Dictionary of variables for prompt>",
"prompt_version": "<Integer of prompt version>"
"tags": ["hello", "world"],}
```
- we could allow you to set 
```python
litellm.succes_callback = [{name:"promptlayer", "vars": {"prompt_id": "<PROMPT ID>",
"prompt_input_variables": "<Dictionary of variables for prompt>",
"prompt_version": "<Integer of prompt version>"
"tags": ["hello", "world"],}}]
```

cc @yujonglee since you had some good guidance around callbacks

**Comment by nsbradford** [comment]
For helicone, this line  https://github.com/BerriAI/litellm/blob/main/litellm/integrations/helicone.py#L89 appears to log the API key as request metadata, which is really not what you want/security bug (though I think it simply doesn't show up now because helicone metadata headers must be prefixed with `Helicone-Property-{X}`. 

For promptlayer, we'd need to add the "metadata" key https://docs.promptlayer.com/reference/track-metadata

personally, i'd add a `metadata: dict[str,str]` parameter to the top-level `completion` endpoint and have the various callbacks figure it out (e.g. the Helicone callback would do the `Helicone-Property-{X}` conversion), given the idea of request metadata as KV strings seems standard-ish

**Comment by ghost** [comment]
Would an example completion call w/ metadata be: 

```
completion(model, messages, metadata={"tag1": "hello", "tag2": "world"})
```

**Comment by nsbradford** [comment]
in promptlayer, metadata and [tags](https://docs.promptlayer.com/features/prompt-history/tagging-requests) are different (though IMHO not really sure how they're supposed to be used differently, I've only ever used metadata)

but yes, something like that I think would work pretty well 😄

**Comment by ghost** [comment]
Hey @nsbradford - pushed a change to enable this here - b76372cee0bf7c46e7e84e270f8758296dfe6a55

If you pass in metadata, it'll also log that to promptlayer. 
<img width="492" alt="Screenshot 2023-09-21 at 10 46 14 AM" src="https://github.com/BerriAI/litellm/assets/17561003/de1c4c55-f0c3-45a8-ab40-3295cf189c48">


Added a tutorial for it in the docs: https://docs.litellm.ai/docs/observability/promptlayer_integration#logging-metadata

Also gave you + vim-gpt a shoutout for making the suggestion. Appreciate all the feedback - excited to hear more ways we can improve! 

<img width="754" alt="Screenshot 2023-09-21 at 10 48 58 AM" src="https://github.com/BerriAI/litellm/assets/17561003/ba19086f-9217-4648-8d60-6cef4ab29895">

**Comment by ghost** [comment]
Will close the issue once this is live in pypi - @nsbradford please reopen if this doesn't solve your issue.

**Comment by ghost** [comment]
live in pypi - https://pypi.org/project/litellm/

**Comment by nsbradford** [comment]
thanks - this looks great! 😄
