### ISSUE TITLE
[Bug]: Fix `/team/member..` endpoint issues 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#4081]
### What happened?

parent ticket to track a few issues with the `/team/member..` endpoints 

- [x] delete a user through /team/member_delete  →  add them back later threw /team/member_add  → get a 500 error: https://github.com/BerriAI/litellm/commit/5c4abcbdb4516fe64c6fa855f894d435a7cf33a2
- [x] Try to add 3 new members via /team/member_add → only one will be applied
- [x] wish: batch add new team members → accept a list of members with roles in /team/member_add 

### Twitter / LinkedIn details

@ncecere

**Comment by ghost** [comment]
team member delete endpoint fixed - https://github.com/BerriAI/litellm/commit/5c4abcbdb4516fe64c6fa855f894d435a7cf33a2

**Comment by ghost** [comment]
there's a concurrency issue when you need to pull a json, modify it and then push it back (occurs with `/team/member_add` when trying to concurrently add members to the same team). 

To handle this and not cause a breaking change, added support for passing in a list of members to add via `/team/member_add` - https://github.com/BerriAI/litellm/pull/4084

@ncecere i believe this should solve your problem, let me know if not
