### ISSUE TITLE
Error using rigging module

### ISSUE THREAD

**Issue by jonesLevin** [BerriAI/litellm#4092]
import rigging as rg
from rigging.model import CommaDelimitedAnswer as Answer

chat = rg.get_generator('gpt-4').chat(
    f'Give me three famours authors between {Answer.xml_tags()} tags.'
)

chat = await chat.run()

This is the error:
AttributeError: 'coroutine' object has no attribute 'last'

**Comment by ishaan-jaff** [comment]
not related to litellm - closing

**Comment by jonesLevin** [comment]
Thats the support link I was directed to.
