### ISSUE TITLE
[Feature]: callback when model RPM/TPM limits are reached

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#4096]
### The Feature

Expose a callback when a model tpm/rpm limit is being reached

### Motivation, pitch

User request - eventually we could trigger a new instance for a high demand model

**Comment by tarujg** [comment]
@krrishdholakia are we going to get this feature soon? Hitting limits on certain endpoints.

**Comment by ghost** [comment]
@tarujg happy to prioritize this, curious - what's your use-case // how do you plan on using the callback?

**Comment by ghost** [comment]
Working on this now - i imagine this would be noisy if the callback was called every time a individual model raised a 429 

if the initial goal is to know if your model group has enough tpm/rpm capacity, then it makes sense to have a callback when we raise the no healthy deployments available error
