### ISSUE TITLE
[Feature]: Handle backend api disconnect errors

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#4097]
### The Feature

If a backend api raises a disconnect error (e.g. predibase, azure, etc.) 

Create an entirely new session object and then do the retry.

Reference: https://github.com/predibase/lorax/blob/main/clients/python/lorax/client.py#L124-L127

### Motivation, pitch

User seeing disconnect errors from predibase calls

**Comment by ghost** [comment]
creating a new http client would be bad as we currently provision a pool of clients, to handle concurrent requests. 

recreating client would disconnect all existing calls
