### ISSUE TITLE
[Bug]: crash when select model on demo website

### ISSUE THREAD

**Issue by okisdev** [BerriAI/litellm#410]
### What happened?

Please see video

https://github.com/BerriAI/litellm/assets/66008528/069cfecb-5b88-4d57-8318-5bce8390a483

### Twitter / LinkedIn details

@okisdev

**Comment by ghost** [comment]
hi @okisdev we were planning on deprecating it. How did you come across it? Any specific model you were trying to use?

**Comment by okisdev** [comment]
Hi @krrishdholakia. Just browsing this project cos my colleague mentioned.

**Comment by ghost** [comment]
If you're looking for a quick way to explore the package via code, here's a snippet that should work
```
!pip install litellm
from litellm import completion

## set ENV variables
os.environ["OPENAI_API_KEY"] = "sk-litellm-7_NPZhMGxY2GoHC59LgbDw" # [OPTIONAL] replace with your openai key
os.environ["COHERE_API_KEY"] = "sk-litellm-7_NPZhMGxY2GoHC59LgbDw" # [OPTIONAL] replace with your cohere key

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# cohere call
response = completion("command-nightly", messages)
```

**Comment by ghost** [comment]
We've had a couple people mention the playground issue - so i think it might be worth revisiting how to bring it back in an easier to maintain fashion 

cc: @ishaan-jaff
