### ISSUE TITLE
[Feature]: exposing model provider from model name logic

### ISSUE THREAD

**Issue by jamesbraza** [BerriAI/litellm#4100]
### The Feature

[`litellm.main.completion`](https://github.com/BerriAI/litellm/blob/v1.40.7/litellm/main.py#L907) has a lot of logic to infer the model provider. It would be useful to expose this capability as something like:
- `classmethod` entrypoint to a provider `Enum`
- `is_openai` or `is_anthropic`-like free functions

### Motivation, pitch

When using `litellm.drop_params = False`, LiteLLM will throw a `litellm.exceptions.APIError` when parameters aren't implemented by a provider. This `APIError` gets thrown at runtime, not at construction time.

I am trying to build some simple validator functions to enable my app to blow up at start-time when not configured properly. Exposing the ability to infer model provider would be a first step towards this

**Comment by ishaan-jaff** [comment]
@jamesbraza we expose `get_llm_provider` . Is this what you needed ? 


```python


def get_llm_provider(
    model: str,
    custom_llm_provider: Optional[str] = None,
    api_base: Optional[str] = None,
    api_key: Optional[str] = None,
    litellm_params: Optional[LiteLLM_Params] = None,
) -> Tuple[str, str, Optional[str], Optional[str]]:
    """
    Returns the provider for a given model name - e.g. 'azure/chatgpt-v-2' -> 'azure'

    For router -> Can also give the whole litellm param dict -> this function will extract the relevant details

    Raises Error - if unable to map model to a provider
    """
```

**Comment by jamesbraza** [comment]
Yeah I am aware of that, it gets me most of the way there, and thanks for sharing that 👍 .

One thing I want to validate is if `logprobs = True` can be used for a `completion` call. There is still a lot of downstream logic after `get_llm_provider` in LiteLLM: https://github.com/BerriAI/litellm/blob/v1.40.7/litellm/main.py#L1037-L1050

So I guess `get_llm_provider` is what I am asking for here, but do you have advice on how to connect that to validating parameters like `logprobs`?

**Comment by ishaan-jaff** [comment]
@jamesbraza can you use 

```python
def get_supported_openai_params(
    model: str,
    custom_llm_provider: str,
    request_type: Literal["chat_completion", "embeddings"] = "chat_completion",
) -> Optional[list]:
```

Example usage 
```python
  supported_openai_params = litellm.get_supported_openai_params(
      model=model, custom_llm_provider=custom_llm_provider
  )
```

**Comment by jamesbraza** [comment]
Thank you @ishaan-jaff ! That is exactly what I need 👍 .

Maybe two ideas to do it better would be:
- Moving `custom_llm_provider` to center on a `StrEnum` instead of `str`
- Allowing `litellm.get_supported_openai_params` to accept `None` for `custom_llm_provider`

```python
def get_supported_openai_params(
    model: str,
    custom_llm_provider: Optional[str] = None,
    request_type: Literal["chat_completion", "embeddings"] = "chat_completion",
) -> Optional[list]:
    if not custom_llm_provider:
        custom_llm_provider = get_llm_provider(model)[1]
    ...
```

Happy to open a PR for the second suggestion if you like it

**Comment by ishaan-jaff** [comment]
> Thank you @ishaan-jaff ! That is exactly what I need 👍 .

Which doc did you expect to see this on ? 

> Allowing litellm.get_supported_openai_params to accept None for custom_llm_provider

It already accepts None for `custom_llm_provider`

**Comment by jamesbraza** [comment]
> > Allowing litellm.get_supported_openai_params to accept None for custom_llm_provider
> 
> It already accepts None for `custom_llm_provider`

Are you sure? https://github.com/BerriAI/litellm/blob/v1.40.7/litellm/utils.py#L6444 doesn't accept `None` from what I am seeing

> Which doc did you expect to see this on ?

I guess I was directly reading the source code, and since `litellm.main` didn't have mentions of `get_supported_openai_params`, I didn't become aware of its existence.

Now that I am aware of `get_supported_openai_params`'s existence, I see it's quite clearly documented: https://docs.litellm.ai/docs/completion/input#translated-openai-params

So sorry for the false positive request in this case, I will make sure to read the docs more closely in the future
