### ISSUE TITLE
[Feature]: Know if cache was hit or not in the modelResponse (also in langfuse)

### ISSUE THREAD

**Issue by rahulgoel** [BerriAI/litellm#4109]
### The Feature

When setting cache = True, return a way to know that the response came from a cache. If there is a recommended way let me know. 

Langfuse also says cache_hit=False but i can see the cache hit happening. 

### Motivation, pitch

Will help in debugging.

**Comment by ghost** [comment]
working to repro

**Comment by ghost** [comment]
<img width="314" alt="Screenshot 2024-06-11 at 1 41 07 PM" src="https://github.com/BerriAI/litellm/assets/17561003/16c97642-d58a-4e38-82a5-bc185a25a3d3">

i can see 'cache_hit' as true on langfuse - where are you seeing the false? @rahulgoel

**Comment by ghost** [comment]
i believe we stopped logging 'cache_hit' as a tag for the trace, since a trace has multiple generations (litellm calls) 

https://github.com/BerriAI/litellm/commit/33a6647fac4e539f7ee3678615687e88b726bc1d


Is it possible to log tags to a generation? just tried a version locally and no luck

**Comment by rahulgoel** [comment]
I am using litellm like this

      ```
  litellm.success_callback = ["langfuse"]
        litellm.failure_callback = ["langfuse"]  # logs errors to langfuse

       resp: dict = litellm.completion(
            messages=messages,
            stream=True,
            *args,
            **kwargs,
            model=self.model_name,
            base_url=self.base_url,
            api_version=self.api_version,
            max_tokens=self.max_output_tokens,
            caching=True,
        )
        for chunk in resp:
            yield chunk.choices[0].delta.content

```

what variable can I track to know if the cache was hit?

**Comment by ghost** [comment]
we already log if it's a cache hit to langfuse @rahulgoel 

see - https://github.com/BerriAI/litellm/blob/5eb2822d31ff4d45016e12f90b35b437cc05bd7d/litellm/integrations/langfuse.py#L466

**Comment by ghost** [comment]
what do you see in the metadata for your generation on langfuse?

**Comment by rahulgoel** [comment]
I see cache_hit false:
The 2 traces in question:
 https://us.cloud.langfuse.com/project/clx9cb0q2000of3espnbh8j1y/traces/97091c3c-ec1a-40e4-981a-fbf932a8df61?observation=time-16-17-24-700297_chatcmpl-9YgilpvGGY0CA2wWKZQ53lKwwiG85

https://us.cloud.langfuse.com/project/clx9cb0q2000of3espnbh8j1y/traces/f4f13811-9302-4654-bd64-d7597c83dc81

I am assuming, the cache hits because i get the same response back instantly in the test

**Comment by ghost** [comment]
interesting - i wonder if this is an edge-case with streaming cache hits, do you see the same for non-streaming? @rahulgoel

**Comment by rahulgoel** [comment]
Yes, doesnt happen with stream=False
