### ISSUE TITLE
[Feature]: Dynamic tpm quota (multiple projects) 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#4124]
### The Feature

Allow setting a `dynamic_quote: true` flag for a dynamic tpm budget dependent on how many simultaneous apps there are

### Motivation, pitch

prevent apps from exhausting tpm quota 

### Twitter / LinkedIn details

cc: @jeromeroussin

**Comment by ghost** [comment]
for example you'd have to define how long an app is considered "active" after their last call, so you can accurately compute a number of "simultaneous" apps

**Comment by ghost** [comment]
can we do this similar to latency ttl? 

check the number of active apps -> divide the available tpm capacity by number of active apps -> return that as the available tpm for that call

**Comment by ghost** [comment]
this probably wouldn't be in router.py 

as it doesn't really have anything to do with the load balancing between models

**Comment by ghost** [comment]
would probably be a call hook on the proxy

similar to parallel_request_limiter.py - https://github.com/BerriAI/litellm/blob/c0540e764dcc4b462b501d9fb702127d2b8deefe/litellm/proxy/hooks/parallel_request_limiter.py#L4

**Comment by ghost** [comment]
Basic test cases: 
- If 1 'active' project => give all tpm 
- If 2 'active' projects => divide tpm in 2

**Comment by ghost** [comment]
For v0 considering tracking 'active apps' by model with ttl = 60s

**Comment by ghost** [comment]
E2E case - "I am more concerned about apps gobbling up all the quota" 

base case:
1 project -> gets all quota 

advanced case:
2 projects -> each gets equal quota
