### ISSUE TITLE
[Bug]: Langfuse metadata now always includes litellm_response_cost & raw_request 

### ISSUE THREAD

**Issue by alexanderepstein** [BerriAI/litellm#4128]
### What happened?

I have recently updated litellm and now all of my langfuses traces include the `raw_request` and the `litellm_response_cost` in the metadata. 

Not sure where the response cost one came from, but as far as I can tell something about https://github.com/BerriAI/litellm/pull/3983 is bugged. I do not include `log_raw_request` in the metadata and it is still being captured. 

My guess is that this was tested using the litellm proxy server which I am not currently using.

**Comment by ishaan-jaff** [comment]
we heard a couple users ask for `raw_request` in the metadata by default. would you prefer this be opt in ? 

Open to your feedback here @alexanderepstein

**Comment by alexanderepstein** [comment]
@ishaan-jaff interesting, maybe I am missing something, but having the raw request only feels like it lends itself to debugging. I am unsure why by default I would want it there as when things are working okay its usually just a replication of the data present in the trace already. 

Also whats the reasoning for having `litellm_response_cost` in the metadata? I assume this is a proxy server thing?

**Comment by ishaan-jaff** [comment]
> maybe I am missing something

LiteLLM translates requests, many users asked us to show them the RAW API Request sent to the Provider. (Example: If a function call fails or result is unexpected -> users wanted to see how litellm translated the params) 

> Also whats the reasoning for having litellm_response_cost

We're making it easier for users to view cost per response: We've gotten a couple issues like this https://github.com/BerriAI/litellm/discussions/3982

**Comment by alexanderepstein** [comment]
Okay I guess I am a bit more onboard that it is debatable if raw_requests should be kept by default, I will just update my code to turn it off (assuming I can, the original feature pr looked like I could, but reading the latest code it doesn't seem like I can turn this off without turning off all message logging) 

So the cost per response thing, that seems more applicable if you are using the proxy, but if I am not is this information any different from the cost of the generation that is already present in langfuse?

**Comment by ghost** [comment]
>  cost of the generation that is already present in langfuse

We log the cost of generation to langfuse. 

It's not different, but we saw langfuse ui would sometimes show the value as 0 if it was too small, so added to request to make it easier to debug if it shows up as 0 (i.e. did the cost get logged and just obscured, or not logged at all)

**Comment by ghost** [comment]
> I will just update my code to turn it off 

@ishaan-jaff given the reaction here, why not make this an opt-in behind a flag

**Comment by ghost** [comment]
Working on this now @alexanderepstein

**Comment by ghost** [comment]
fixed - https://github.com/BerriAI/litellm/commit/7eae0ff7e3e655d723fbdc2ac8f3b5839a8abd8d 

@alexanderepstein 


You now explicitly opt-in to logging raw request/response to your logging provider (e.g. langfuse)

```python
litellm.log_raw_request_response=True
```

**Comment by ghost** [comment]
live soon in v`1.40.9`

**Comment by ghost** [comment]
does this solve your problem? @alexanderepstein

**Comment by alexanderepstein** [comment]
Haven't tested it out yet, but based on your comments of this now being opt-in it should resolve my issue. Thanks for the quick turnaround!

**Comment by ghost** [comment]
of course - thanks for using us!

**Comment by Manouchehri** [comment]
Is it possible to enable it in the yaml config like this?

```yaml
litellm_settings:
  log_raw_request_response: True
```

**Comment by ghost** [comment]
yes that should already work @Manouchehri
