### ISSUE TITLE
[Bug]: Tutorial hyperlink error about 'https://litellm.vercel.app/docs/index'

### ISSUE THREAD

**Issue by CellCS** [BerriAI/litellm#4135]
### What happened?

A bug happened!

<img width="788" alt="image" src="https://github.com/BerriAI/litellm/assets/16886624/d73c796e-3f6b-4ecf-bf63-4e7d907cfb74">

### Relevant log output

```shell
https://litellm.vercel.app/docs/index.html
```
instead of 

```shell
https://litellm.vercel.app/docs/index
```

**Comment by ishaan-jaff** [comment]
fixed here @CellCS : https://github.com/BerriAI/litellm/commit/bf9d77eeb18abc994f22583ddee162c677905679

**Comment by ishaan-jaff** [comment]
@CellCS curious do you use litellm in production today ?

**Comment by CellCS** [comment]
@ishaan-jaff  thanks for your kind help and support.  LiteLLM is very useful tool. I am still exploring LiteLLM and getting familiar with more functions by using docker env. Will testing prod env in host server level.

**Comment by ishaan-jaff** [comment]
@CellCS can we setup a slack support channel ? I'd love to provide dedicated support to you

**Comment by BetDev1** [comment]
@ishaan-jaff  thanks a lot. no worries, I just join your Discord

**Comment by CellCS** [comment]
@ishaan-jaff  thanks a lot. no worries, i just join in your Discord
