### ISSUE TITLE
[Bug]: Langfuse prompt Object of type TextPromptClient is not JSON serializable

### ISSUE THREAD

**Issue by ivanviragine** [BerriAI/litellm#4140]
### What happened?

Hi everyone!
I don't know if I'm missing something, but when passing a LangFuse prompt retrieved like (as per documentation - https://langfuse.com/docs/prompts/get-started#use-prompt):

```
def get_langfuse_prompt(name: str) -> TextPromptClient:
    try:
        return langfuse.get_prompt(name)
    except Exception as e:
        logger.exception(e)

        raise Exception(f"Error getting prompt: {e}")

```
to the acompletion method (as per documentation: https://litellm.vercel.app/docs/observability/langfuse_integration#generation-specific-parameters) like:

```
                response = await acompletion(
                    api_key=settings.LITELLM_MASTER_KEY,
                    api_base=settings.LITELLM_HOST,
                    model=model,
                    temperature=self.TEMPERATURE,
                    messages=messages,
                    timeout=settings.OPENAI_API_TIMEOUT_SECONDS,
                    extra_body={
                        "metadata": {
                            "tags": [model, self.AIProvider.name, ai_model_id],
                            "prompt": prompt
                        }
                    },
                )
```

I am getting a "Object of type TextPromptClient is not JSON serializable" error.
Indeed if we call json.dumps(prompt) it returns the error.

How can I make it work?

**Comment by ishaan-jaff** [comment]
taking a look @ivanviragine

**Comment by ivanviragine** [comment]
Thank you @ishaan-jaff !

I've ended up making a dict with hardcoded keys 
and passing the values from the object to it. But it would be better do make it serializable.
If you want I can try to fix it and open a PR.

**Comment by ishaan-jaff** [comment]
@ivanviragine you're making this request to the litellm proxy server correct ?

**Comment by ivanviragine** [comment]
Yes! The key settings.LITELLM_HOST has the litellm proxy URL, but the error is when sending the request, that is, in the python library (acompletion function).

**Comment by ishaan-jaff** [comment]
fixed here @ivanviragine 
https://github.com/BerriAI/litellm/pull/4275
