### ISSUE TITLE
[Bug]: "GET /v2/model/info HTTP/1.1" 500 Internal Server Error

### ISSUE THREAD

**Issue by Lh111d** [BerriAI/litellm#4143]
### What happened?

A bug happened!When I use the ui to view the model function, the message {"detail":{"error":"Invalid llm model list. llm_model_list=None"}} is displayed. How do I add the llm model

### Relevant log output

```shell
"GET /v2/model/info HTTP/1.1" 500 Internal Server Error
```

**Comment by ishaan-jaff** [comment]
hi @Lh111d 
- what litellm version are you on? 
- how do you add models on the proxy through the config.yaml or did you directly add it on the UI

**Comment by DennyDai** [comment]
I had the same issue after updating to the latest version and I believe it's related to 3c6bc031de7299caf2bdc4f5429e3aa791cd44d4

Once I manually add `command: ["--config", "/app/config.yaml", "--port", "4000"]` to my docker-compose.yml it works

**Comment by ishaan-jaff** [comment]
Fixed the error to clearly say how to add models:
https://github.com/BerriAI/litellm/pull/4447

**Comment by ishaan-jaff** [comment]
@Lh111d  any chance we can hop on a call ? I'd love to learn how how we can improve litellm for you.

Sharing a link to my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
My linkedin if you prefer DM: https://www.linkedin.com/in/reffajnaahsi/
