### ISSUE TITLE
[Feature]: Azure gpt-4o support

### ISSUE THREAD

**Issue by dcieslak19973** [BerriAI/litellm#4147]
### The Feature

I see on https://docs.litellm.ai/docs/providers/azure#azure-openai-chat-completion-models that the new `gpt-4o` model is not currently supported.  Would like to see support for it (including image support)

### Motivation, pitch

Keeping up with the latest available models!

**Comment by ghost** [comment]
hey @dcieslak19973 it's already supported

**Comment by ghost** [comment]
i'll clarify the docs to indicate that

**Comment by ishaan-jaff** [comment]
Added here: https://github.com/BerriAI/litellm/commit/30d76293ccd32935958aa649b54546231aea9207

**Comment by ishaan-jaff** [comment]
@dcieslak19973 any chance we can hop on a call ? I'd love to learn how how we can improve litellm for you.

My linkedin if you prefer DM: https://www.linkedin.com/in/reffajnaahsi/
Sharing a link to my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
