### ISSUE TITLE
[Bug]: Error selecting model provider from UI

### ISSUE THREAD

**Issue by emerzon** [BerriAI/litellm#4163]
### What happened?

When trying to add a new model from the UI, it's not possible to select any provider with a click.

The following exception happens in the JS console:

### Relevant log output

```shell
received provider string: Azure
page-bd882aee817406ff.js:1 mappingResult: azure
fd9d1056-f960ab1e6d32b002.js:1 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at l_ (page-bd882aee817406ff.js:1:35076)
    at onClick (page-bd882aee817406ff.js:1:47608)
    at onClick (131-6a03368053f9d26d.js:8:26807)
    at Object.aS (fd9d1056-f960ab1e6d32b002.js:1:71760)
    at aN (fd9d1056-f960ab1e6d32b002.js:1:71914)
    at fd9d1056-f960ab1e6d32b002.js:1:138575
    at sw (fd9d1056-f960ab1e6d32b002.js:1:138674)
    at sS (fd9d1056-f960ab1e6d32b002.js:1:139088)
    at fd9d1056-f960ab1e6d32b002.js:1:145231
```

### Twitter / LinkedIn details

@emersongomesma

**Comment by ishaan-jaff** [comment]
@emerzon can you share a screenshot / gif of what you see ?

**Comment by emerzon** [comment]
Sure thing:

![image](https://github.com/BerriAI/litellm/assets/26816375/4b0bc2b8-0355-4784-91aa-d12faacb723f)

Clicking any item in the dropdown menu won't select and/or close the dropdown menu.
Hitting "Enter" will select the current entry, however, "openai" provider is passed to the submission regardless of the actual value.

**Comment by ishaan-jaff** [comment]
![select_models](https://github.com/BerriAI/litellm/assets/29436595/d84f31d9-01e1-4e18-9cc5-636d2bcfa15c)
 

It's clickable on my side 🤔

**Comment by ishaan-jaff** [comment]
@emerzon can you try this link. Does it work for you? That's a hosted proxy by us I can see it clickable 

[Hosted Proxy Server UI Link](https://staging.litellm.ai/ui/?userID=ishaan-admin&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiaXNoYWFuLWFkbWluIiwia2V5Ijoic2stSDVYQmhmRk9jcHBIb2I1OEZFZ0hUdyIsInVzZXJfZW1haWwiOiJpc2hhYW4tYWRtaW4iLCJ1c2VyX3JvbGUiOiJhcHBfYWRtaW4iLCJsb2dpbl9tZXRob2QiOiJ1c2VybmFtZV9wYXNzd29yZCIsInByZW1pdW1fdXNlciI6ZmFsc2V9.8iVO5LZmBYZNiVkzu20_EUJlx1_zTF-up-cvw3MR_No)

**Comment by emerzon** [comment]
Ok, I figured out the issue. The problem happens if the browser cannot fetch this URL: https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json.

In my case, I am accessing the UI from an isolated browser, with no access to external URLs.
So it's a bit of a corner case.

**Comment by ishaan-jaff** [comment]
> he problem happens if the browser cannot fetch this URL: https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json.

I'm working on a fix for this now

**Comment by ishaan-jaff** [comment]
fix PR here: https://github.com/BerriAI/litellm/pull/4166
