### ISSUE TITLE
[Bug]: Add testing to ensure there are no random print statements

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#417]
### What happened?

A bug happened!
when caling litellm.completion and printing response I got this. It had two extra print statements below - I have no idea what caused it 

<img width="1280" alt="Screenshot 2023-09-20 at 8 47 49 PM" src="https://github.com/BerriAI/litellm/assets/29436595/a18efcbc-02b7-4c24-b1c6-d207ee1cb368">

**Comment by ghost** [comment]
We can have all print_verbose print with "LiteLLM:" 

then we can check the stdout to see if any print statements *don't* contain that, and flag it that way. 

Thoughts @ishaan-jaff

**Comment by ghost** [comment]
bumping priority. Just had a user from the OI community think the replicate call was erroring due to a print statement on our end.

**Comment by ishaan-jaff** [comment]
we have pre commit checks now
