### ISSUE TITLE
[Bug]: fix response_ms attribute 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#418]
### What happened?

Currently you can access response_ms from the object as a key in a dictionary - response["response_ms"] 

this doesn't follow the openai format - response.response_ms 

<img width="713" alt="Screenshot 2023-09-20 at 8 56 17 PM" src="https://github.com/BerriAI/litellm/assets/17561003/43ecaf7f-7bde-4657-b6a3-554af99034f1">

**Comment by ishaan-jaff** [comment]
done
added to our tests too
```python
def test_completion_claude():
    try:
        response = completion(
            model="claude-instant-1", messages=messages, max_tokens=10
        )
        # Add any assertions here to check the response
        print(response)
        print(response.response_ms)
```
