### ISSUE TITLE
[Bug]: Openrouter - poor DX for litellm integration. OpenAI, Anthropic calls fail

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#419]
### What happened?

Followed our docs:
https://docs.litellm.ai/docs/providers/openrouter

open router fails for anthropic, openai. IMO we should standardize openrouter llms to be openrouter/openai/gpt-3.5-turbo 
<img width="1232" alt="Screenshot 2023-09-20 at 9 32 52 PM" src="https://github.com/BerriAI/litellm/assets/29436595/62ee5c07-eee7-4bb1-87f7-76cf56195ff6">

<img width="1223" alt="Screenshot 2023-09-20 at 9 31 34 PM" src="https://github.com/BerriAI/litellm/assets/29436595/ac1c58fd-6cfa-4e4c-9915-dd14be616ee6">

**Comment by ranjancse26** [comment]
I was able to run the below tests successfully with no failures.

https://colab.research.google.com/github/BerriAI/litellm/blob/main/cookbook/LiteLLM_OpenRouter.ipynb

**Comment by ghost** [comment]
Ok sounds good, issue seems fixed then.
