### ISSUE TITLE
[Bug]: Failed Tracking Cost forerror in tracking cost callback

### ISSUE THREAD

**Issue by sauravpanda** [BerriAI/litellm#4193]
### What happened?

I am getting a Slackbot alert in a proxy that says the webhook URL is not set, but I don't know why, as all other Slack alerts are working!

### Relevant log output

```shell
Message: Failed Tracking Cost forerror in tracking cost callback - Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 1760, in _PROXY_track_cost_callback
    await proxy_logging_obj.slack_alerting_instance.customer_spend_alert(
  File "/usr/local/lib/python3.11/site-packages/litellm/integrations/slack_alerting.py", line 792, in customer_spend_alert
    await self.send_webhook_alert(webhook_event=event)
  File "/usr/local/lib/python3.11/site-packages/litellm/integrations/slack_alerting.py", line 1166, in send_webhook_alert
    raise Exception("Missing webhook_url from environment")
Exception: Missing webhook_url from environment
 Args to _PROXY_track_cost_callback
```

**Comment by ghost** [comment]
@sauravpanda did you set `alerting: ["webhook"]` ? 

this is raised when entering the webhook alerting block

**Comment by sauravpanda** [comment]
No for my litellm proxy setup its:   

`alerting: ["slack"]      # Setup slack alerting - get alerts on LLM exceptions, Budget Alerts, Slow LLM Responses
`

**Comment by ghost** [comment]
able to repro, fixed - https://github.com/BerriAI/litellm/commit/74d8605f5c377241368a64855051cf25b35ccaf0

will be live soon in v`1.40.14`
