### ISSUE TITLE
Add the ability to set the key based on the model

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#42]
## Usage
`litellm.set_key(model)`

Reason:
Not everyone sets their keys in OPENAI_API_KEY, eg `openai.api_key = get_api_key("OPENAI")`

litellm should handle setting the appropriate env variables for a given model

**Comment by ghost** [comment]
should it just be `litellm.api_key` ? like on openai

**Comment by ghost** [comment]
nvm you're right.. how about this 

```
import litellm 

litellm.api_keys = {"openai": key, "azure": key..}
```

**Comment by ghost** [comment]
```
import litellm 

litellm.openai_key = "sk-..."

litellm.azure_key = "..."
```

alternative.. i think thisi is a bit cleaner

**Comment by ghost** [comment]
better for cases where you have maybe 1-2 alt keys, probably less ideal for a batch but i presume that case is lesser

**Comment by ghost** [comment]
https://github.com/BerriAI/litellm/commit/499d626c76c781749febd9a1f38f55f14395d2d3 

should address this

**Comment by ghost** [comment]
@ishaan-jaff close the ticket if this works for your case
