### ISSUE TITLE
[Feature]: Add ibm-generative-ai Support

### ISSUE THREAD

**Issue by rfazeli** [BerriAI/litellm#4218]
### The Feature

I would like to request adding support for ibm-generative-ai service. This is the link to the service https://bam.res.ibm.com/ and this is its python sdk https://github.com/IBM/ibm-generative-ai

### Motivation, pitch

I want to use ibm-generative-ai using openai-compatible end points

**Comment by rfazeli** [comment]
Some reference pointers: 
- The main api end point: https://github.com/IBM/ibm-generative-ai/blob/main/documentation/source/faq.rst#which-api-endpoint-should-i-use
- Text generation end point: https://github.com/IBM/ibm-generative-ai/blob/86a715da0169a7060d6652942f325513dc0476cc/src/genai/schema/_endpoints.py#L394
- Request parameters: https://github.com/IBM/ibm-generative-ai/blob/86a715da0169a7060d6652942f325513dc0476cc/src/genai/extensions/localserver/schema.py#L9-L17

**Comment by ghost** [comment]
Hey @rfazeli i believe this is already supported - https://docs.litellm.ai/docs/providers/watsonx

**Comment by rfazeli** [comment]
Hi @krrishdholakia, no these are different services with slightly different endpoints, request parameters, etc.

**Comment by XReyRobert-IBM** [comment]
Hi Reza, this is IBM research platform for IBMers and partners.... 
I'm not sure how the apis differs but now that watsonx.ai is supported it shouldn't be too difficult to adapt the code to target it but as it is a tech preview...
