### ISSUE TITLE
[Bug]: Crash if lago is defined as callback with last main branch

### ISSUE THREAD

**Issue by superpoussin22** [BerriAI/litellm#4224]
### What happened?

just test the last main branch and have a crash of litellm when lago is used as callback

### Relevant log output

```shell
File "/usr/local/lib/python3.11/site-packages/litellm/proxy/utils.py", line 247, in _init_litellm_callbacks
"NameError: name 'LagoLogger' is not defined",
```

**Comment by ishaan-jaff** [comment]
cc @krrishdholakia might be related to recent changed in utils.py

**Comment by ghost** [comment]
Fixed here - https://github.com/BerriAI/litellm/commit/2623bb260f351d459e0d3a8abf149a335585a98e

should be live in v`1.40.16+`. 

@superpoussin22 can we setup a direct support channel? Would love to learn how you're using litellm today

**Comment by superpoussin22** [comment]
@krrishdholakia 
no more error, will see if lago receive the infos but I'm confident.
No prob to exchange on litellm

**Comment by ghost** [comment]
@superpoussin22 how do you use litellm today? 

(want to learn so we can improve for a specific use-case)
