### ISSUE TITLE
[Feature]: Use configs in test library

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#423]
### The Feature

We make tons of completion calls across our test library (litellm/litellm/tests). 

Use configs to set num_retries = 3, so all completion calls read from this and retry a couple times before failing. 

### Motivation, pitch

circle ci testing will fail b/c of one-off errors from models.

**Comment by ishaan-jaff** [comment]
we use `litellm.num_retries ` in ci/cd now
