### ISSUE TITLE
[Bug]: unauthorized error with codestral api 

### ISSUE THREAD

**Issue by guyomes** [BerriAI/litellm#4232]
### What happened?

The codestral api has changed. The free tier doesn't work with "https://api.mistral.ai". The endpoint should now be: 
"https://codestral.mistral.ai"

The documentation also recommends "If you're building a plugin, or anything that exposes these endpoints directly to the user, and expect them to bring their own API keys, you should also target codestral.mistral.ai"
https://docs.mistral.ai/capabilities/code_generation/

Thank you for this great tool.

**Comment by ishaan-jaff** [comment]
doing this today

**Comment by ishaan-jaff** [comment]
@guyomes we now support codestral API, live on main-latest: https://docs.litellm.ai/docs/providers/codestral

**Comment by ishaan-jaff** [comment]
@guyomes  any chance we can hop on a call ? I'd love to learn how how we can improve litellm for you.

Sharing a link to my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
If you prefer DMs i'm also sharing a link to my linkedin: https://www.linkedin.com/in/reffajnaahsi/

**Comment by guyomes** [comment]
Thank you for the patch. Is it also possible to update this file with the new codestral/codestral-latest provider and model:
https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json

**Comment by ishaan-jaff** [comment]
yes @guyomes

**Comment by ishaan-jaff** [comment]
tracking here: https://github.com/BerriAI/litellm/issues/4432
