### ISSUE TITLE
FATAL:  role "root" does not exist

### ISSUE THREAD

**Issue by jmikedupont2** [BerriAI/litellm#4234]
docker compose up, on the db container gives me
FATAL:  role "root" does not exist

**Comment by felixdsml** [comment]
What was the solution?

**Comment by ishaan-jaff** [comment]
hi @felixerlacher - happy to debug this over call with you 

here's my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/berriai-1-1-onboarding-litellm-hosted-version?month=2023-10

My linkedin if you want to DM: https://www.linkedin.com/in/reffajnaahsi/

**Comment by alecswan** [comment]
I ran into the same issue - what was the resolution for "FATAL:  role "root" does not exist" during docker compose startup?

**Comment by alecswan** [comment]
Answering this after some research and experimentation. Adding "user: postgres" in docker compose yaml fixed this for me. See https://stackoverflow.com/a/67865761 for details.
