### ISSUE TITLE
[Feature]:  Support OpenAI's `parallel_tool_calls`

### ISSUE THREAD

**Issue by minhduc0711** [BerriAI/litellm#4235]
### The Feature

OpenAI recently added a new [`parallel_tool_calls` parameter](https://platform.openai.com/docs/api-reference/chat/create#chat-create-parallel_tool_calls).

> `parallel_tool_calls`: boolean, Optional, Defaults to true
> 
> Whether to enable [parallel function calling](https://platform.openai.com/docs/guides/function-calling/parallel-function-calling) during tool use.

Would be nice if we add the same parameter to the `completion` function.

### Motivation, pitch

This is useful when I want only one tool call returned, without extra completion tokens being used for redundant tool calls.

**Comment by ghost** [comment]
doesn't this already work? @minhduc0711

**Comment by minhduc0711** [comment]
My bad, I wasn't aware that LiteLLM has already supported provider-specific params.

From https://docs.litellm.ai/docs/completion/input#provider-specific-params:

> Providers might offer params not supported by OpenAI (e.g. top_k). You can pass those in 2 ways:
> 
>  * via completion(): We'll pass the non-openai param, straight to the provider as part of the request body.
>         e.g. completion(model="claude-instant-1", top_k=3)
>  * via provider-specific config variable (e.g. litellm.OpenAIConfig()).
