### ISSUE TITLE
[Bug]: Post-API Call occurs before Pre-API Call in CustomLogger

### ISSUE THREAD

**Issue by RyoYang** [BerriAI/litellm#4236]
### What happened?

In https://github.com/BerriAI/litellm/blob/3a35a58859a145a4a568548316a1930340e7440a/litellm/proxy/custom_callbacks.py
Post-API Call always occurs before Pre-API Call in CustomLogger, is that expected?
```
Router Redis Caching=None
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:4000 (Press CTRL+C to quit)
Post-API Call
Pre-API Call
INFO:     127.0.0.1:44244 - "POST /openai/deployments/azure/gpt-35-turbo/chat/completions?api-version=2023-07-01-preview HTTP/1.1" 200 OK
ishaan async_log_success_event
```

### Relevant log output

```shell
Router Redis Caching=None
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:4000 (Press CTRL+C to quit)
Post-API Call
Pre-API Call
INFO:     127.0.0.1:44244 - "POST /openai/deployments/azure/gpt-35-turbo/chat/completions?api-version=2023-07-01-preview HTTP/1.1" 200 OK
ishaan async_log_success_event
```
```


### Twitter / LinkedIn details

_No response_

**Comment by ghost** [comment]
no that's weird. Thanks for raising this.

**Comment by ghost** [comment]
@RyoYang can we setup a support channel over linkedin/discord? 

Want to make sure we can debug this + solve any future issues quickly 

Discord: [link](https://discord.com/invite/wuPM9dRgDw), just wave (👋 ) on #general, and i'll set it up. 

LinkedIn: [link](https://www.linkedin.com/in/krish-d/)

**Comment by ishaan-jaff** [comment]
able to repro - working on a fix

**Comment by ishaan-jaff** [comment]
fixed here: https://github.com/BerriAI/litellm/pull/4451

**Comment by ishaan-jaff** [comment]
hi @RyoYang Can we hop on a quick call sometime this week? I’d love to learn how we can improve litellm for you 

My cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/berriai-1-1-onboarding-litellm-hosted-version?month=2023-10 
My linkedin if you prefer DMs: https://www.linkedin.com/in/reffajnaahsi/
