### ISSUE TITLE
[Bug]: LiteLLM returns 500 in case of Quota exceeded for anthropic-claude-3-haiku

### ISSUE THREAD

**Issue by kmyczkowska-hypatos** [BerriAI/litellm#4259]
### What happened?

LiteLLM returns 500 error code in case of Quota exceeded for `anthropic-claude-3-haiku`.
In this case 429 should be returned (as it is in the inner response).

### Relevant log output

```shell
InternalServerError. Cause: Error code: 500 - {'error': {'message': "Error code: 429 - {'error': {'code': 429, 'message': 'Quota exceeded for aiplatform.googleapis.com/online_prediction_tokens_per_minute_per_base_model with base model: anthropic-claude-3-haiku. Please submit a quota increase request. https://cloud.google.com/vertex-ai/docs/generative-ai/quotas-genai.', 'status': 'RESOURCE_EXHAUSTED'}}", 'type': None, 'param': None, 'code': 500}}
```
version: `main-v1.37.20`

**Comment by ishaan-jaff** [comment]
working on a fix

**Comment by ishaan-jaff** [comment]
Fixed here @kmyczkowska-hypatos https://github.com/BerriAI/litellm/pull/4263

**Comment by ishaan-jaff** [comment]
@kmyczkowska-hypatos any chance we can hop on a call ? I'd love to learn how how we can improve litellm for you.

Sharing a link to my cal for your convenience: [https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-cha](https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat)
