### ISSUE TITLE
[Feature]: Add feedback on docs button to topnav

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#426]
### The Feature

Add feedback on docs button to topnav

<img width="414" alt="Screenshot 2023-09-22 at 1 25 55 PM" src="https://github.com/BerriAI/litellm/assets/17561003/c5d39c8f-378e-4353-81ba-c46fef3697cc">

### Motivation, pitch

Have received user feedback that they can't find things they're looking for on our docs. I want to make things easier / better. Looking for ways to get more feedback, as we make changes.

**Comment by ghost** [comment]
cc: @NANDINI-star if this looks interesting to you

**Comment by ranjancse26** [comment]
Time to analyze 3rd party user feedback integrations like https://usersnap.com/

**Comment by NANDINI-star** [comment]
@krrishdholakia sure I'll take a look into it.
