### ISSUE TITLE
[Feature]: Add coverage for Azure + VertexAI in validate_environment()

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#427]
### The Feature

> when someone does like, interpreter --model claude-2, i want to check if they have all the right shit for it, and if they don't, prompt them for it.
> right now we do that kinda manually like with azure. we literally step through and do input("enter deployment...")
> but I need it to be like, "ok the user is doing azure. they did interpreter --model azure/something. so deployment ID is 'something', but they didn't set an API base! and we need that for azure, so, let's ask the user for it..."
> any way to just check like, given a model, what is all the required vars? 

### Motivation, pitch

-

**Comment by ghost** [comment]
Requirements: 
Move to os env variables 
- VertexAI: vertex_project + vertex_location
- Huggingface: api base
- Ollama: api base

Expose a helper function that given a model name - checks if it has the required env variables, returns the model, provider, required variables if not.

**Comment by ghost** [comment]
moved to env variables
