### ISSUE TITLE
[Bug]: Vertex AI httpx - candidatesTokenCount is in the response optionally?

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#4270]
### What happened?

`vertex_ai_beta/` is really buggy. Seems to be throwing an error now because of a missing key?

https://cloud.google.com/vertex-ai/generative-ai/docs/reference/nodejs/latest/vertexai/usagemetadata

### Relevant log output

```shell
openai.InternalServerError: Error code: 500 - {'error': {'message': 'litellm.APIConnectionError: \'candidatesTokenCount\'\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 378, in acompletion\n    response = await init_response\n               ^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/litellm/llms/vertex_httpx.py", line 615, in async_completion\n    return self._process_response(\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/litellm/llms/vertex_httpx.py", line 410, in _process_response\n    completion_tokens=completion_response["usageMetadata"][\n                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nKeyError: \'candidatesTokenCount\'\n', 'type': None, 'param': None, 'code': 500}}
```

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by ghost** [comment]
it looks like an expected key - `candidatesTokenCount` isn't in the response. 

How do i repro this? @Manouchehri

**Comment by ghost** [comment]
can you also share the server logs (looking for the raw response from Vertex AI, to see what we should be expecting here)

**Comment by ghost** [comment]
Added better exception messages around the response processing - https://github.com/BerriAI/litellm/commit/aef5cf3f223c7360ce49c3f52925520848822b8c

So we can see the raw response in the exception message

**Comment by ghost** [comment]
able to repro with this - 

```
messages = [
        {
            "role": "user",
            "content": """
    
List 5 popular cookie recipes.

Using this JSON schema:
```json
{'$defs': {'Recipe': {'properties': {'recipe_name': {'examples': ['Chocolate Chip Cookies', 'Peanut Butter Cookies'], 'maxLength': 100, 'title': 'The recipe name', 'type': 'string'}, 'estimated_time': {'anyOf': [{'minimum': 0, 'type': 'integer'}, {'type': 'null'}], 'default': None, 'description': 'The estimated time to make the recipe in minutes', 'examples': [30, 45], 'title': 'The estimated time'}, 'ingredients': {'examples': [['flour', 'sugar', 'chocolate chips'], ['peanut butter', 'sugar', 'eggs']], 'items': {'type': 'string'}, 'maxItems': 10, 'title': 'The ingredients', 'type': 'array'}, 'instructions': {'examples': [['mix', 'bake'], ['mix', 'chill', 'bake']], 'items': {'type': 'string'}, 'maxItems': 10, 'title': 'The instructions', 'type': 'array'}}, 'required': ['recipe_name', 'ingredients', 'instructions'], 'title': 'Recipe', 'type': 'object'}}, 'properties': {'recipes': {'items': {'$ref': '#/$defs/Recipe'}, 'maxItems': 11, 'title': 'The recipes', 'type': 'array'}}, 'required': ['recipes'], 'title': 'MyRecipes', 'type': 'object'}
```
            """,
        }
    ]

    response = completion(
        model="vertex_ai_beta/gemini-1.5-flash",
        messages=messages,
        response_format={"type": "json_object"},
    )

```
```

Looks like vertex ai will randomly omit token counts - 

<img width="1605" alt="Screenshot 2024-06-18 at 6 20 48 PM" src="https://github.com/BerriAI/litellm/assets/17561003/0843bc3b-cc5a-49fb-b02a-bf44aa414a5a">

**Comment by ghost** [comment]
<img width="914" alt="Screenshot 2024-06-18 at 6 22 43 PM" src="https://github.com/BerriAI/litellm/assets/17561003/17a2e715-9d9d-44df-8b41-64f2048cac00">

looks like the request is being flagged by vertex ai @Manouchehri 
<img width="375" alt="Screenshot 2024-06-18 at 6 22 58 PM" src="https://github.com/BerriAI/litellm/assets/17561003/dfd70e96-48ec-4cd0-9320-7ad011cf7138">
