### ISSUE TITLE
[Bug]: Proxy with MYSQL db

### ISSUE THREAD

**Issue by sarathsurpur** [BerriAI/litellm#4273]
### What happened?

can we setup the litellm proxy server with mysql db, i see only postgresql and redis is being supported at the moment

**Comment by ishaan-jaff** [comment]
Hi @sarathsurpur this is not planned anytime soon. Can we hop on a call to understand what you need / how we can help unblock your team ? 


Sharing a link to my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
My linkedin if you prefer DMs: https://www.linkedin.com/in/reffajnaahsi/
