### ISSUE TITLE
[Bug]: `gemini-1.5-pro-001` and `gemini-1.5-flash-001` missing from prices

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#4283]
### What happened?

Only for the `vertex_ai_beta/*` routes.

### Relevant log output

```shell
Unable to identify if system message supported. Defaulting to 'False'. Received error message - Model not in model_prices_and_context_window.json. You passed model=gemini-1.5-pro-001, custom_llm_provider=vertex_ai_beta.
```

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by ghost** [comment]
fixed - we just needed to check for vertex_ai instead of vertex_ai_beta

**Comment by ghost** [comment]
live soon in v`1.40.17`.
