### ISSUE TITLE
[Bug]: Under high concurrency requests, the number of traces is inaccurate, more than the number of requests.

### ISSUE THREAD

**Issue by ZhuoRoger** [BerriAI/litellm#4297]
### What happened?

We use Locust for stress testing. The number of requests in both Locust and litellm logs is 476, but the number of traces in the litellm database is 487.

**Comment by ZhuoRoger** [comment]
<img width="765" alt="image" src="https://github.com/BerriAI/litellm/assets/4162226/80a62a67-d0ce-4ae7-b032-0dc969c8a96d">
![image](https://github.com/BerriAI/litellm/assets/4162226/3fc0a7c1-35e4-42c9-98c2-c4c02272eddd)

**Comment by ZhuoRoger** [comment]
![image](https://github.com/BerriAI/litellm/assets/4162226/8a5cb29f-632e-4791-8dc8-465ee7b26bb2)

<img width="770" alt="image" src="https://github.com/BerriAI/litellm/assets/4162226/3c6eb36b-23fa-4c16-b5f7-af3dbe0b3c77">

**Comment by ishaan-jaff** [comment]
we don't have any table called `traces` - what are you referring to ? @ZhuoRoger

**Comment by ZhuoRoger** [comment]
it's traces table in Postgre database.

**Comment by ghost** [comment]
@ZhuoRoger  traces is not a litellm table 

i suspect you have a custom integration that's logging to your own table. 

here's our table schema for reference (see: no traces table) - https://github.com/BerriAI/litellm/blob/5cb0c1ad707dc9572d6b363b1025a67a6b5fe47f/schema.prisma#L4

**Comment by ghost** [comment]
bump on this @ZhuoRoger

**Comment by ghost** [comment]
closing for now - but would be helpful if you can share steps for repro @ZhuoRoger
