### ISSUE TITLE
[Feature]: Disable logging to langfuse per team

### ISSUE THREAD

**Issue by superpoussin22** [BerriAI/litellm#4299]
### The Feature

Currently the turn_off_message_logging: True option is global , meaning that you enable or disable message logging for all teams.

It would be fine in my opinion to have a default value to false  and to be able to activate logging per team

### Motivation, pitch

I think it is important for GDPR

**Comment by ishaan-jaff** [comment]
Hi @superpoussin22 - any chance we can hop on a call ? I'd love to learn how how you want this to work + improve litellm for you 

Sharing a link to my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
My linkedin if you prefer DMs: https://www.linkedin.com/in/reffajnaahsi/

**Comment by ishaan-jaff** [comment]
done here @superpoussin22

**Comment by ishaan-jaff** [comment]
is this what you wanted @superpoussin22 ? 

## Disable Logging for a Team

To disable logging for a specific team, you can use the following endpoint:

`POST /team/{team_id}/disable_logging`

This endpoint removes all success and failure callbacks for the specified team, effectively disabling logging.

### Step 1. Disable logging for team

```shell
curl -X POST 'http://localhost:4000/team/YOUR_TEAM_ID/disable_logging' \
    -H 'Authorization: Bearer YOUR_API_KEY'
```
Replace YOUR_TEAM_ID with the actual team ID

**Response**
A successful request will return a response similar to this:
```json
{
    "status": "success",
    "message": "Logging disabled for team YOUR_TEAM_ID",
    "data": {
        "team_id": "YOUR_TEAM_ID",
        "success_callbacks": [],
        "failure_callbacks": []
    }
}
```

### Step 2. Test it - `/chat/completions`

Use a key generated for team = `team_id` - you should see no logs on your configured success callback (eg. Langfuse)

```shell
curl -i http://localhost:4000/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer sk-KbUuE0WNptC0jXapyMmLBA" \
  -d '{
    "model": "gpt-4",
    "messages": [
      {"role": "user", "content": "Hello, Claude gm!"}
    ]
}'
```

### Debugging / Troubleshooting

- Check active callbacks for team using `GET /team/{team_id}/callback`

Use this to check what success/failure callbacks are active for team=`team_id`

```shell
curl -X GET 'http://localhost:4000/team/dbe2f686-a686-4896-864a-4c3924458709/callback' \
        -H 'Authorization: Bearer sk-1234'
```

**Comment by superpoussin22** [comment]
@ishaan-jaff many thanks will test :)

**Comment by ishaan-jaff** [comment]
@superpoussin22 - we'd really love to setup a support channel with you. We'd love to collaborate closely with your team and work on your issues even faster. What's the best place for you ? 

Sharing my socials for your convenience: 

My linkedin: https://www.linkedin.com/in/reffajnaahsi/
LiteLLM discord - just wave and i'll make a private group: https://discord.com/invite/wuPM9dRgDw
