### ISSUE TITLE
[Bug]: Setting max_tokens doesn't work with Claude 2

### ISSUE THREAD

**Issue by basicthinker** [BerriAI/litellm#430]
### What happened?

To our understanding, `max_tokens` is translated to `max_tokens_to_sample` for Claude 2. But while we set it to, say, 20000, Claude 2 still cuts the response to around 256 tokens. We are using Anthropic's API, of course.

**Comment by ishaan-jaff** [comment]
taking a look👀

**Comment by ishaan-jaff** [comment]
fixed here: https://github.com/BerriAI/litellm/commit/d12fadd032303b2829f93a82499a25d4aa5883a3 thanks for raising 

will push a new version of litellm

**Comment by ishaan-jaff** [comment]
litellm 0.1.738 has the fix 

@basicthinker feel free to re-open if it's not fixed for you
