### ISSUE TITLE
[Feature]: GCP Bucket support

### ISSUE THREAD

**Issue by mdziedzic-zoe** [BerriAI/litellm#4300]
### The Feature

Support for GCP Buckets alongside S3

### Motivation, pitch

We'd be interested in having a dedicated support for google buckets on GCP, with GCP Native IAM implemented. 

The ask here is to add an option to gcp buckets instead of AWS and use dedicated [gcp sdk](https://cloud.google.com/python/docs/reference/storage/latest) to manage the bucket operations.

**Comment by Manouchehri** [comment]
This is actually supported by the S3 API, if you're okay with using HMAC!

https://dzlab.github.io/gcp/2022/02/26/gs-with-s3-sdk/

Currently using GCS in production with LiteLLM. =)

**Comment by mdziedzic-zoe** [comment]
Thanks for the callout! This is the approach we've also adopted. 
However, we're not that happy about HMAC and would like to see an option to use Native GCP IAM.

**Comment by ghost** [comment]
hey @mdziedzic-zoe how would you want this to work? mock configuration for this would help

**Comment by ishaan-jaff** [comment]
GCP Bucket support here: https://github.com/BerriAI/litellm/pull/4999 @mdziedzic-zoe , works with Native GCP IAM
