### ISSUE TITLE
[Feature]: Custom Routing Strategy

### ISSUE THREAD

**Issue by anetbnd** [BerriAI/litellm#4302]
### The Feature

We would like to have the possibility to plugin a custom routing strategy, instead of using the hardcoded ones. 

### Motivation, pitch

In our use case we have many metrics about the models we deployed. So we would like to use those metrics which are external to litellm to make a routing decision. In order to achieve this, we would like to implement just our own routing class and plug it in to the litellm router.

**Comment by ghost** [comment]
Hey @anetbnd curious - what sort of additional metrics are you looking at?

**Comment by anetbnd** [comment]
@ishaan-jaff Thanks! This was fast :)

**Comment by anetbnd** [comment]
> Hey @anetbnd curious - what sort of additional metrics are you looking at?

We get certain metrics from our LLM deployment system, for example the number of requests in the queue. We would like to incorporate those information into the routine decision.

**Comment by ishaan-jaff** [comment]
Hi @anetbnd any chance we can hop on a call ? I'd love to learn how how we can improve litellm for you.

My linkedin if you prefer DM: https://www.linkedin.com/in/reffajnaahsi/ 
Sharing a link to my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by ghost** [comment]
@anetbnd is this similar to request prioritization? https://docs.litellm.ai/docs/scheduler

Would love to learn, so we can improve here!

**Comment by anetbnd** [comment]
@ishaan-jaff Sure! I will discuss today with my team and afterwards I will come back to you. Thanks for that offer. 

@krrishdholakia No, it is not about the prioritization of certain requests, it is more about to prioritize certain models, depending on their load and the day schedule. We were searching for something in between a soft fallback and latency routing with prioritization of certain model deployments.

**Comment by ghost** [comment]
@anetbnd curious 

- what provider is this (azure/vllm/etc.)? 
- how do you know model load?

**Comment by anetbnd** [comment]
@krrishdholakia I'm not sure, how much I'm allowed to write about details in public. But I'm currently aligning with my team about a call with @ishaan-jaff. Will you join? Then we can discuss in more details.

**Comment by therealtimex** [comment]
I feel like we can learn a lot from https://github.com/lm-sys/RouteLLM

**Comment by olad32** [comment]
> I feel like we can learn a lot from https://github.com/lm-sys/RouteLLM

i agree, i created another feature issue for RouteLLM as it is a slightly different use case than this current issue, https://github.com/BerriAI/litellm/issues/4727
