### ISSUE TITLE
[Bug]: Incorrect pricing for "azure/gpt-35-turbo-1106", "llama3-8b-8192" & "llama3-70b-8192"?

### ISSUE THREAD

**Issue by yannbu** [BerriAI/litellm#4305]
### What happened?

See Microsoft pricing:

https://azure.microsoft.com/en-us/pricing/details/cognitive-services/openai-service/

![Screenshot 2024-06-20 at 13 13 08](https://github.com/BerriAI/litellm/assets/8428699/3719f36d-02a5-4560-81aa-3082c7a5bcf0)

See what is currently configured in LiteLLM:

```
"azure/gpt-35-turbo-1106": {
        "max_tokens": 4096,
        "max_input_tokens": 16384,
        "max_output_tokens": 4096,
        "input_cost_per_token": 0.0000015,
        "output_cost_per_token": 0.000002,
        "litellm_provider": "azure",
        "mode": "chat",
        "supports_function_calling": true,
        "supports_parallel_function_calling": true
    },
```

`"input_cost_per_token": 0.0000015,` may be wrong and may be  `0.0000010` instead

**Comment by yannbu** [comment]
Also it seems "llama3-70b-8192" and "llama3-8b-8192" prices are wrong.

See https://console.groq.com/settings/billing

![Screenshot 2024-06-20 at 14 33 13](https://github.com/BerriAI/litellm/assets/8428699/54010562-b389-4f17-9f1d-dc7e4e521d33)

Current prices in the LiteLLM price map are:

- 0.00000064/0.00000080 for "llama3-70b-8192"
- 0.00000010/0.00000010 for "llama3-8b-8192

**Comment by ghost** [comment]
got it - thanks @yannbu 

will have this fixed today

**Comment by guillaq** [comment]
@krrishdholakia looks like the pricing of gemini pro vision is also not up to date

```
        "input_cost_per_token": 0.00000025, 
        "output_cost_per_token": 0.0000005,
```
vs

<img width="762" alt="Screenshot 2024-06-20 at 12 58 34 PM" src="https://github.com/BerriAI/litellm/assets/4003862/da52532c-beae-4856-a106-e46b0fc70070">

Would it help if I opened a PR ?

**Comment by ghost** [comment]
yes that would be very helpful @guillaq

**Comment by ghost** [comment]
azure prices fixed - https://github.com/BerriAI/litellm/commit/473509aed36f5f47a27d5c1374169744857babdd

groq prices fixed - https://github.com/BerriAI/litellm/commit/db2cf5b5a53fcafce60e36dacb1e47f047f5eb5f


@yannbu @guillaq can we do a 10min call sometime next week? 

Would love to learn how you're using litellm - https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
