### ISSUE TITLE
[Feature]:  add claude 3.5 sonnet support

### ISSUE THREAD

**Issue by olbychos** [BerriAI/litellm#4309]
### The Feature

Add support for Claude 3.5 Sonnet:
"claude-3.5-sonnet-20240620"

For more information, visit:
https://www.anthropic.com/news/claude-3-5-sonnet

### Motivation, pitch

This is the newest model from Anthropic and can be very useful for testing with your framework.

**Comment by ishaan-jaff** [comment]
it's live already @olbychos
