### ISSUE TITLE
[Bug]: vllm runtime issues

### ISSUE THREAD

**Issue by ranjancse26** [BerriAI/litellm#431]
### What happened?

Noticed a strange behavior with the execution of vllm based completions. It worked fine for the first time and subsequent time, it failed. Here's the error.

![image](https://github.com/BerriAI/litellm/assets/2565797/9d6ebfd5-d0fc-42d5-9fd8-fe2a25a908fd)

```import litellm 
from litellm import completion

messages = [{"role": "user", "content": "How you doing?"}]

response = completion(
            model="vllm/Xwin-LM/Xwin-LM-7B-V0.1", # add a vllm prefix so litellm knows the custom_llm_provider==vllm
            messages=messages,
            temperature=0.2,
            max_tokens=80)

print(response)

**Comment by ghost** [comment]
Hey @ranjancse26 acknowledging the issue. This is how vllm runs, let me see if there's a workaround for this. I'm assuming you see this in a colab cell not a python script?

**Comment by ranjancse26** [comment]
@krrishdholakia Right on the google colab usage for testing it out.

**Comment by ranjancse26** [comment]
Open issue on vllm - https://github.com/vllm-project/vllm/issues/549

**Comment by shivam-51** [comment]
Getting the same error.
```
File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/vllm/model_executor/parallel_utils/parallel_state.py:116, in initialize_model_parallel(tensor_model_parallel_size, pipeline_model_parallel_size, virtual_pipeline_model_parallel_size, pipeline_model_parallel_split_rank)
    114 global _DATA_PARALLEL_GROUP
    115 global _DATA_PARALLEL_GLOBAL_RANKS
--> 116 assert _DATA_PARALLEL_GROUP is None, 'data parallel group is already initialized'
    117 all_data_parallel_group_ranks = []
    118 for i in range(pipeline_model_parallel_size):

AssertionError: data parallel group is already initialized
```

**Comment by edwinjosegeorge** [comment]
@ranjancse26  the issue seems fixed at https://github.com/vllm-project/vllm/issues/549 .

We can close this issue

@krrishdholakia

**Comment by ghost** [comment]
thanks @edwinjosegeorge
