### ISSUE TITLE
[Feature]: Proxy langfuse requests 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#4315]
### The Feature

Proxy langfuse api to remove need for dev to maintain both langfuse + litellm keys for their project 

### Motivation, pitch

"Currently, our applications require separate keys and interactions for both Langfuse and LiteLLM, where we use the Langfuse SDK directly for some functions while forwarding all generations to Langfuse via the LiteLLM integration. If LiteLLM could function as a proxy for the Langfuse API, it would streamline operations by eliminating the need for multiple system interactions and reduce potential errors" - user request

**Comment by ishaan-jaff** [comment]
https://github.com/BerriAI/litellm/pull/4465

**Comment by ishaan-jaff** [comment]
done in linked PR
