### ISSUE TITLE
[Feature]: Provide a hosted cache

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#432]
### The Feature

Currently we only do local caching and require users to set up their own hosted cache on redis. 

This leads to people needing other solutions if they want a hosted caching solution - https://github.com/nsbradford/SemanticSearch. 

Could we simplify this by providing our own hosted cache? 

### Motivation, pitch

Seeing user code

**Comment by ghost** [comment]
cc: @ishaan-jaff @nsbradford

**Comment by ghost** [comment]
cc: @yujonglee as i think you're using caching on fastrepl too

**Comment by ishaan-jaff** [comment]
this is done: https://docs.litellm.ai/docs/caching/caching_api 
we provide a cache on api.litellm.ai
