### ISSUE TITLE
[Feature]: Support bedrock offician tool usage

### ISSUE THREAD

**Issue by luccazifood** [BerriAI/litellm#4326]
### The Feature

https://docs.aws.amazon.com/bedrock/latest/userguide/tool-use.html

### Motivation, pitch

Instead of modifying the prompt, aws api supports direct tool usage. performance and token usage is better.
would be nice to use that way in litellm

**Comment by luccazifood** [comment]
if i find time, i can try to contribute

**Comment by ghost** [comment]
we already support it @luccazifood 
https://github.com/BerriAI/litellm/blob/dfd5882c313be35b0c62c726df69b338e5951b1a/litellm/llms/bedrock_httpx.py#L1765

**Comment by ghost** [comment]
Where in docs should we have had this? 


P.S.: If you're free for 10mins this/next week - would love to learn how you're using litellm 

https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
