### ISSUE TITLE
[Feature]: Replicate model - get most recent version if none passed in 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#433]
### What happened?

When i passed in 
```
response = completion(
            model="replicate/meta/llama-2-70b-chat", messages=messages, stream=True, max_tokens=50
        )
```

I was just expecting it to work 

It seems like I need to also pass in a version id: 
`meta/llama-2-70b-chat:02e509c789964a7ea8736978a43525956ef40397be9033abf9fd2badfe68c9e3`

But if none passed in, just grab the most recent one. 

### Relevant log output

```shell
Traceback (most recent call last):
  File "/Users/krrishdholakia/Documents/litellm/litellm/tests/test_streaming.py", line 363, in <module>
    test_completion_replicate_stream()
  File "/Users/krrishdholakia/Documents/litellm/litellm/tests/test_streaming.py", line 362, in test_completion_replicate_stream
    pytest.fail(f"Error occurred: {e}")
  File "/opt/homebrew/lib/python3.11/site-packages/_pytest/outcomes.py", line 198, in fail
    raise Failed(msg=reason, pytrace=pytrace)
Failed: Error occurred: Failed to start prediction {"title":"Invalid version or not permitted","detail":"The specified version does not exist (or perhaps you don't have permission to use it?)","status":422}
```

**Comment by nabeelahmedshaikh** [comment]
I have the same problem, don't know what the solution is!

**Comment by ghost** [comment]
Replicate actually expects you to pass in the model id: 
<img width="1064" alt="Screenshot 2023-10-04 at 9 06 21 AM" src="https://github.com/BerriAI/litellm/assets/17561003/e3f14b50-eaec-4fb1-b060-e762230cb05b">

So go to the api tab of the model and copy the full name. Yea i think it would be simpler to just get the model id

**Comment by nabeelahmedshaikh** [comment]
Ah no, I had the same error but the reason was slightly different. I was passing in all the correct info that is the full model name etc but it still gave me the same error as above. It turned out in the client.py file under replicate it tries to pick up os.environ.get("REPLICATE_API_TOKEN") on line 28 and fails, some how it returns None, I am setting it correctly in my .env file and am also able to retrieve it in my code (Just for testing) but when it comes to replicates own client.py file, it fails! don't really know why, I have just for the short term put in my Key there so now it works, but will try and search for a proper reason later.

**Comment by ghost** [comment]
@nabeelahmedshaikh we're not retrieving the REPLICATE_API_TOKEN in replicate.py, can you point me to the file you're looking at? https://github.com/BerriAI/litellm/blob/0f7256533fc00a985f897f4f3b51090703b7135e/litellm/llms/replicate.py#L28

**Comment by nabeelahmedshaikh** [comment]
Hey, as you guys are litellm, I wouldn't know. The problem is in client.py file within the replicate module itself, if you are using the replicate library then you are inheriting the problem.

**Comment by ghost** [comment]
@nabeelahmedshaikh we don't use the replicate client library. Did you face this issue with litellm or replicate's python sdk? 

If it's replicate's python sdk i'd recommend making an issue there (or switching to litellm 😄) 

```
# !pip install litellm
from litellm import completion
import os
## set ENV variables
os.environ["REPLICATE_API_KEY"] = "replicate key"

messages = [{ "content": "Hello, how are you?","role": "user"}]

# replicate llama-2 call
response = completion(
        model="replicate/llama-2-70b-chat:2796ee9483c3fd7aa2e171d38f4ca12251a30609463dcfd4cd76703f22e96cdf", 
        messages=messages
    )
```

**Comment by nabeelahmedshaikh** [comment]
Apologies, yes it's Replicate SDK but very similar error message.

**Comment by krrishdholakia** [comment]
closing issue then 😄
