### ISSUE TITLE
[Bug]: Langfuse logger doesn't work for tts models

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#4330]
### What happened?

https://litellm.vercel.app/docs/text_to_speech

```sh
curl "$OPENAI_API_BASE/audio/speech" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{
    "model": "tts-1",
    "input": "The quick brown fox jumped over the lazy dog.",
    "voice": "alloy"
  }' -v | mpv -
```

### Relevant log output

```shell
LiteLLM:ERROR[0m: langfuse.py:232 - Langfuse Layer Error(): Exception occured - cannot access local variable 'output' where it is not associated with a value
```

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by ghost** [comment]
how exactly would the output of tts be logged? @Manouchehri 

it's speech right? so like a set of bytes?

**Comment by ghost** [comment]
bump on this? @Manouchehri

**Comment by ishaan-jaff** [comment]
this is fixed on latest - feel free to reopen if not @Manouchehri
