### ISSUE TITLE
[Bug]: Spend tags metadata storage in `v1.40.9-stable` is broken

### ISSUE THREAD

**Issue by rahulvbrahmal-sigtech** [BerriAI/litellm#4334]
### What happened?

When you assign metadata to a completions request in `v1.40.9-stable`, it does not store the metadata spend tags in the DB. This can be validated by trying to query the `/spend/tags` endpoint after running several completions requests, where the response body comes in as `[]`.

### Relevant log output

```shell
No logs - it just doesn't save
```

**Comment by ghost** [comment]
@rahulvbrahmal-sigtech do you mean spend tags or spend metadata? 

spend metadata is stored separately in the db. 

can you share a sample completion request?

**Comment by ishaan-jaff** [comment]
@rahulvbrahmal-sigtech you're right, i'm able to repro this. Working on a fix

**Comment by ishaan-jaff** [comment]
fixed + added testing here: https://github.com/BerriAI/litellm/pull/4345
