### ISSUE TITLE
Add response cost in model response (headers/hidden params)

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#4335]
proxy response could be : 
```
{
...
"usage": {
    "completion_tokens": 163,
    "prompt_tokens": 14684,
    "total_tokens": 14847,
    "cost": 1.123 <-- new
   }
}
```

This may be controlled by a new proxy config parameter

_Originally posted by @olad32 in https://github.com/BerriAI/litellm/discussions/3982_

**Comment by ghost** [comment]
Addressed with https://github.com/BerriAI/litellm/pull/4436


@superpoussin22 can we do a 10min call sometime this/next week? 

https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

Would love to learn how you're using litellm proxy, so we can improve
