### ISSUE TITLE
[Bug]: liteLLM proxy /moderations  endpoint returns 500 error when model is not specified

### ISSUE THREAD

**Issue by malagna-amplify** [BerriAI/litellm#4336]
### What happened?

If you try to hit the moderations endpoint without specifying a model, you get the following error:
`{"error":{"message":"'model'","type":"None","param":"None","code":500}}`

Expected behavior: Model should be optional. When hitting openAI directly without model, it defaults to `text-moderation-latest`.  

EDIT: It also appears that if I try to specify the model, I instead get a 400 error...
`"model": "text-moderation-latest"`
error:
`{"error":{"message":"400: {'error': 'moderations: Invalid model name passed in model=text-moderation-latest'}","type":"None","param":"None","code":400}}`

**Comment by ishaan-jaff** [comment]
working on this

**Comment by ishaan-jaff** [comment]
Fix PR here: https://github.com/BerriAI/litellm/pull/4342

**Comment by ishaan-jaff** [comment]
also added testing to ensure we don't push a regression on this

**Comment by ishaan-jaff** [comment]
@malagna-amplify  any chance we can hop on a call ? I'd love to learn how how we can improve litellm for you.

I reached out to you on Linkedin if DMs work.
Sharing a link to my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by malagna-amplify** [comment]
@ishaan-jaff  Thanks for reaching out! I put time on your calendar to discuss.
