### ISSUE TITLE
[Bug]: Bedrock throttling errors don't seem to report to Langfuse?

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#4338]
### What happened?

I ran into a `throttlingException` when using Bedrock, and oddly nothing showed up in Langfuse for the request or error. Only noticed it because of Sentry.

### Relevant log output

```shell
LiteLLM Proxy:ERROR[0m: proxy_server.py:2523 - litellm.proxy.proxy_server.async_data_generator(): Exception occured - Bad response code, expected 200: {'status_code': 400, 'headers': {':exception-type': 'throttlingException', ':content-type': 'application/json', ':message-type': 'exception'}, 'body': b'{"message":"Too many requests, please wait before trying again. You have sent too many requests.  Wait before trying again."}'}
```

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by ghost** [comment]
this looks like it happened midway through streaming

**Comment by ghost** [comment]
Confirmed https://github.com/BerriAI/litellm/commit/cea630022e86468c1ebe0e2116d6c7ae72a61403 fixes this 

See: bedrock streaming error - 
<img width="1283" alt="Screenshot 2024-06-22 at 9 26 51 PM" src="https://github.com/BerriAI/litellm/assets/17561003/2f6a8d35-8f5f-4a5e-87db-94f52e95cbf1">

Langfuse trace - 
<img width="1007" alt="Screenshot 2024-06-22 at 9 26 46 PM" src="https://github.com/BerriAI/litellm/assets/17561003/43d217d9-db79-4e95-a9e2-f2a6eab4de62">

**Comment by ghost** [comment]
cc: @sfarthin 

if you were seeing missing traces for streaming errors on langfuse, this might be it
