### ISSUE TITLE
[Feature]: Add support for cohere chat

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#434]
### The Feature

cohere has a chat endpoint - https://docs.cohere.com/reference/post_chat

We should add support for it 

### Motivation, pitch

user request - cc: @ranjancse26

**Comment by ishaan-jaff** [comment]
this link says page not found ?

**Comment by ishaan-jaff** [comment]
looks like it's here: https://docs.cohere.com/reference/chat-1
