### ISSUE TITLE
[Feature]: Bedrock httpx to support 'AWS_SESSION_TOKEN'

### ISSUE THREAD

**Issue by bschulth** [BerriAI/litellm#4346]
### The Feature

The legacy boto3 client support is deprecated because you cannot use async.  However the new httpx support does not allow you to pass in your `aws_session_token`.

#### Patch Part 1

Please support `aws_session_token` as an argument here:
https://github.com/BerriAI/litellm/blob/55a20c7cce99a93d36a82bf3ae90ba3baf9a7f89/litellm/llms/bedrock_httpx.py#L284-L292
```python
    def get_credentials(
        self,
        aws_access_key_id: Optional[str] = None,
        aws_secret_access_key: Optional[str] = None,
        #--------------------------------------------------------------------
        aws_session_token: Optional[str] = None,
        #--------------------------------------------------------------------
        aws_region_name: Optional[str] = None,
        aws_session_name: Optional[str] = None,
        aws_profile_name: Optional[str] = None,
        aws_role_name: Optional[str] = None,
        aws_web_identity_token: Optional[str] = None,
    ):
```

and here:
https://github.com/BerriAI/litellm/blob/55a20c7cce99a93d36a82bf3ae90ba3baf9a7f89/litellm/llms/bedrock_httpx.py#L360

This block should do the trick I think:

```python
#--------------------------------------------------------------------
elif (
    aws_access_key_id is not None
    and aws_secret_access_key is not None
    and aws_session_token is not None
):
    credentials = Credentials(
        access_key=aws_access_key_id,
        secret_key=aws_secret_access_key,
        token=aws_session_token,
    )
    return credentials
#--------------------------------------------------------------------
```

#### Patch Part 2

This block of code would also need to be updated to check for `aws_session_token`:
https://github.com/BerriAI/litellm/blob/55a20c7cce99a93d36a82bf3ae90ba3baf9a7f89/litellm/llms/bedrock_httpx.py#L691-L730

**Patched code:**

```python
        ## CREDENTIALS ##
        # pop aws_secret_access_key, aws_access_key_id, aws_region_name from kwargs, since completion calls fail with them
        aws_secret_access_key = optional_params.pop("aws_secret_access_key", None)
        aws_access_key_id = optional_params.pop("aws_access_key_id", None)
        #--------------------------------------------------------------------------
        aws_session_token = optional_params.pop("aws_session_token", None)
        #--------------------------------------------------------------------------
        aws_region_name = optional_params.pop("aws_region_name", None)
        aws_role_name = optional_params.pop("aws_role_name", None)
        aws_session_name = optional_params.pop("aws_session_name", None)
        aws_profile_name = optional_params.pop("aws_profile_name", None)
        aws_bedrock_runtime_endpoint = optional_params.pop(
            "aws_bedrock_runtime_endpoint", None
        )  # https://bedrock-runtime.{region_name}.amazonaws.com
        aws_web_identity_token = optional_params.pop("aws_web_identity_token", None)

        ### SET REGION NAME ###
        if aws_region_name is None:
            # check env #
            litellm_aws_region_name = get_secret("AWS_REGION_NAME", None)

            if litellm_aws_region_name is not None and isinstance(
                litellm_aws_region_name, str
            ):
                aws_region_name = litellm_aws_region_name

            standard_aws_region_name = get_secret("AWS_REGION", None)
            if standard_aws_region_name is not None and isinstance(
                standard_aws_region_name, str
            ):
                aws_region_name = standard_aws_region_name

            if aws_region_name is None:
                aws_region_name = "us-west-2"

        credentials: Credentials = self.get_credentials(
            aws_access_key_id=aws_access_key_id,
            aws_secret_access_key=aws_secret_access_key,
            #--------------------------------------------------------------------------
            aws_session_token=aws_session_token,
            #--------------------------------------------------------------------------
            aws_region_name=aws_region_name,
            aws_session_name=aws_session_name,
            aws_profile_name=aws_profile_name,
            aws_role_name=aws_role_name,
            aws_web_identity_token=aws_web_identity_token,
        )
```

#### Example http call of service with STS token
Example code demonstrating the credential object can take a token:

```python
import json
import os
from botocore.auth import SigV4Auth
from botocore.awsrequest import AWSRequest
from botocore.credentials import Credentials
import requests

# My company mechanism for getting an STS credential
# creds = secrets.get_aws_iam_credentials('bedrock-role')

os.environ["AWS_ACCESS_KEY_ID"]     = creds.get('access_key',     "my-key-id")
os.environ["AWS_SECRET_ACCESS_KEY"] = creds.get('secret_key',     "my-secret-access-key")
os.environ["AWS_SESSION_TOKEN"]     = creds.get('security_token', "my-sts-token")
os.environ["AWS_REGION"]            = "us-west-2"
os.environ["BEDROCK_MODEL"]         = "anthropic.claude-3-haiku-20240307-v1:0"

def post_request():
    credentials = Credentials(
        access_key = os.environ['AWS_ACCESS_KEY_ID'],
        secret_key = os.environ['AWS_SECRET_ACCESS_KEY'],
        token      = os.environ['AWS_SESSION_TOKEN'],
    )
    region = os.environ["AWS_REGION"]
    model  = os.environ["BEDROCK_MODEL"]
    
    sigv4 = SigV4Auth(credentials, 'bedrock', region)
    endpoint = f'https://bedrock-runtime.{region}.amazonaws.com/model/{model}/invoke'
    data = json.dumps({
      "anthropic_version": "bedrock-2023-05-31",
      "messages": [{"role": "user", "content": "explain black holes to 8th graders"}],
      "max_tokens": 300,
      "temperature": 0.1,
      "top_p": 0.9,
    })
    headers = {'Content-Type': 'application/json'}
    request = AWSRequest(method='POST', url=endpoint, data=data, headers=headers)
    sigv4.add_auth(request)
    prepped = request.prepare()

    response = requests.post(prepped.url, headers=prepped.headers, data=data)
    print("POST Request: {}".format(response.text))

post_request()
```

### Motivation, pitch

My company uses the HashiCorp Vault solution to provide user with STS tokens for an assumed identity (see https://developer.hashicorp.com/vault/docs/secrets/aws#sts-credentials).

We cannot directly assume the role, but we can call the hashicorp service to return the trio of:
- aws_access_key_id
- aws_secret_access_key
- and aws_session_token

Without this feature, I will need to continue to use the legacy/deprecated service where I create my own boto3 bedrock client and pass that into litellm.

**Comment by Manouchehri** [comment]
> My company uses the HashiCorp Vault solution to provide user with STS tokens for an assumed identity

Could you configure Vault to hand out a OIDC token?

https://developer.hashicorp.com/vault/tutorials/auth-methods/oidc-identity-provider

If so, I could add a generic HashiCorp Vault OIDC provider for LiteLLM, so you would be able to use it with Bedrock and Azure.

**Comment by bschulth** [comment]
@Manouchehri possibly, but I am guessing it would not be a quick turn around. It could be a longer term strategy.

When do you plan to remove the deprecated boto3 client?

**Comment by bschulth** [comment]
As another possiblity, rather than deprecating/removing the boto3.client, if someone passes in a boto3 client, would you be opposed to using a private boto3.client function to extract the credentials, and  use these with  the async httpx functionality?

```python
creds = boto3_client._get_credentials().get_frozen_credentials()
creds.access_key
creds.secret_key
creds.token
```

**Comment by Manouchehri** [comment]
Yeah, that’s totally doable. It could be tested too by getting a token
through OIDC manually in the unit test.

**Comment by bschulth** [comment]
@Manouchehri : 
I took a pass at this in a PR: https://github.com/BerriAI/litellm/pull/4371 if you are interested in looking at it.

**Comment by ghost** [comment]
@bschulth 

> , if someone passes in a boto3 client, would you be opposed to using a private boto3.client function to extract the credentials

This would be amazing! That would totally solve the issue re: passing in your own boto3 client.

**Comment by bschulth** [comment]
@krrishdholakia I will be in and out today, but let me take a look at reducing this to the bare minimum.

My main issue is that I need the aws_session_token to pass through, but maybe I can minimize the changes to my single use-case...I was just trying to make a complete pass on the session token usability.

**Comment by ghost** [comment]
Closing, as support for this is now added with https://github.com/BerriAI/litellm/pull/4371
