### ISSUE TITLE
[Bug]: Anthropic not throwing`BadRequestError` when bad tool calls

### ISSUE THREAD

**Issue by jamesbraza** [BerriAI/litellm#4348]
### What happened?

When misconfiguring responses to a tool call with `litellm==1.40.12`

OpenAI correctly throws a `BadRequestError`:

```none
litellm.exceptions.BadRequestError: litellm.BadRequestError: BadRequestError: OpenAIException - Error code: 400 - {'error': {'message': "Missing parameter 'tool_call_id': messages with role 'tool' must have a 'tool_call_id'.", 'type': 'invalid_request_error', 'param': 'messages.[2].tool_call_id', 'code': None}}
```

Anthropic incorrectly throws a `APIConnectionError`:

```none
litellm.exceptions.APIConnectionError: litellm.APIConnectionError: Client error '400 Bad Request' for url 'https://api.anthropic.com/v1/messages'
```

It's actually connected. Looking at the actual `response.text`:

```none
'{"type":"error","error":{"type":"invalid_request_error","message":"messages.2.content.0.tool_result.tool_use_id: Input should be a valid string"}}'
```

So LiteLLM is incorrectly handling this response text, it should be throwing a `BadRequestError` for Anthropic as well

**Comment by ghost** [comment]
what was the request sent? @jamesbraza

**Comment by jamesbraza** [comment]
Thank you @krrishdholakia ! I confirmed your fix works by installing current `main` branch. Nice job and thank you!
