### ISSUE TITLE
[Feature]: Support new Amazon Multimodal Embedding model 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#4353]
### The Feature

Amazon titan has a new multimodal embedding model - 

https://us-east-1.console.aws.amazon.com/bedrock/home?region=us-east-1#/providers?model=amazon.titan-embed-image-v1

support it 

### Motivation, pitch

user request

**Comment by harshil1973** [comment]
Is this beginner-friendly? I may want to work on this if some headstart given.
