### ISSUE TITLE
[Feature]: .patch pattern & API - similar to what Instructor does

### ISSUE THREAD

**Issue by ChristianWeyer** [BerriAI/litellm#4367]
### The Feature

It would be very feasible to have a client.patch(...) method which gives us an OpenAI SDK client instance with the LiteLLM features enabled. Similar to what [Instructor](https://github.com/BerriAI/litellm/blob/769c60e4f6e6e98e91e0619b5c20906d1c43cb20/docs/my-website/docs/tutorials/instructor.md?plain=1#L15) does.

Ideally, LiteLLM and Instructor would still be able to seamlessly work together.

### Motivation, pitch

Ease of use, homogenized programming model. Interoperability with other libs (which accept OpenAI clients).

### Twitter / LinkedIn details

https://x.com/christianweyer

**Comment by ghost** [comment]
you can already use us with instructor @ChristianWeyer  - https://github.com/jxnl/instructor?tab=readme-ov-file#using-litellm
