### ISSUE TITLE
[Bug]: cannot login after recent update

### ISSUE THREAD

**Issue by mmolinari** [BerriAI/litellm#4368]
### What happened?

After my container was updated I'm not able to login anymore.

To replicate:
- I visit http://192.168.1.101:4000/ui
- I'm forwarded to http://192.168.1.101:4000/sso/key/generate
- I see the UI to login
- I enter "admin" and the master key as usual
- I see `{"detail":{"error":"No master key set, please set LITELLM_MASTER_KEY"}}`

I see these messages were added in this PR: https://github.com/BerriAI/litellm/pull/4357

The container is running on a Synology server; the master key is set as a `LITELLM_MASTER_KEY` env variable.

**Comment by mmolinari** [comment]
Also reported in https://github.com/BerriAI/litellm/issues/4369

**Comment by lolsborn** [comment]
This is a bug, one workaround currently is to include the general_settings section in your configuration (even if it's blank) which causes the right code path to be executed.

**Comment by mmolinari** [comment]
@lolsborn thank you for the reply.

I actually didn't have any config.yaml at all, `/app` was empty. I tried to mount it as described in https://docs.openwebui.com/tutorial/litellm/#initial-setup
just as
```
general_settings:
```
but I still experience the issue.

I also noticed an empty `LiteLLM_Config` table in the database. I tried adding a new record, `param_name: general_settings` , no value, but this also didn't help.

Any help is appreciated. Thanks!

**Comment by ishaan-jaff** [comment]
fixing

**Comment by ishaan-jaff** [comment]
fixedhere: https://github.com/BerriAI/litellm/pull/4382

**Comment by ishaan-jaff** [comment]
Hi @mmolinari I fixed the issue you reported  https://github.com/BerriAI/litellm/pull/4382  - Can we hop on a call sometime this week. I’d love to learn how I can improve litellm for you + setup a 1:1 support channel 

My cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

My linkedin if you prefer DM: https://www.linkedin.com/in/reffajnaahsi/
