### ISSUE TITLE
[Bug]: UI Authentication Bugs

### ISSUE THREAD

**Issue by krinlove99** [BerriAI/litellm#4369]
### What happened?

非常感谢您的努力，您在最近的某次commit提交中修复了一些bug，但貌似出现了另外一个bug：
我正在使用render部署LiteLLM，随着您的commit提交render自动化程序进行了数次自动构建，但是我于2024年6月23日尝试登录UI时遗憾地发现无法登录，提示"error": "No master key set, please set LITELLM_MASTER_KEY"——尽管我已经设置了LITELLM_MASTER_KEY，因为昨日的时候我还可以正常登录。
麻烦您检查一下问题所在，目前我已经回滚到[b4d95e7]版本，该版本是我最后一次手动构建的commit版本，可以正常使用。

Thank you very much for your efforts. You fixed some bugs in a recent commit, but it seems that another bug has appeared:
I am using render to deploy LiteLLM. As your commit was submitted, the render automation program performed several automatic builds. However, when I tried to log in to the UI on June 23, 2024, I unfortunately found that I could not log in. The prompt "error": "No master key set, please set LITELLM_MASTER_KEY" - although I have set LITELLM_MASTER_KEY, because I could log in normally yesterday.
Please check the problem. At present, I have rolled back to the [b4d95e7] version, which is the last commit version I manually built and can be used normally.

**Comment by lolsborn** [comment]
This is a bug, one workaround currently is to include the `general_settings` section in your configuration (even if it's blank) which causes the right code path to be executed.

**Comment by ishaan-jaff** [comment]
Hi @krinlove99 I fixed the issue you reported  https://github.com/BerriAI/litellm/pull/4382  - Can we hop on a call sometime this week. I’d love to learn how I can improve litellm for you + setup a 1:1 support channel 

My cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
My linkedin if you prefer DM: https://www.linkedin.com/in/reffajnaahsi/

**Comment by luizhsalazar** [comment]
> This is a bug, one workaround currently is to include the `general_settings` section in your configuration (even if it's blank) which causes the right code path to be executed.

Thanks, this worked for me. But, I had to include the `master_key` in `general_settings`, keeping blank didn't work.

**Comment by ishaan-jaff** [comment]
it's fixed on main-latest @luizhsalazar

**Comment by ishaan-jaff** [comment]
you need a master_key either on config or in your .env
