### ISSUE TITLE
[Bug]: LiteLLM:ERROR: litellm_logging.py

### ISSUE THREAD

**Issue by nextzard** [BerriAI/litellm#4372]
### What happened?

I'm using Fadora 40 and installed it today.

I am using ollama model: codegemma, but at the end after answering 
I get this message
                                           
`22:42:02 - LiteLLM:ERROR: litellm_logging.py:1266 - Model=codegemma not found in completion cost map. Setting 'response_cost' to None`

If I use it with llama3, there is no error.

Maybe https://github.com/BerriAI/litellm/blob/main/litellm/model_prices_and_context_window_backup.json

json file, I wonder if the error occurs if the model is not in there. 
I'm using it well, thanks.

**Comment by ishaan-jaff** [comment]
fixed here https://github.com/BerriAI/litellm/pull/4424

**Comment by ishaan-jaff** [comment]
@nextzard curious - what do you use LiteLLM for today ?

**Comment by Harry989** [comment]
I am having this issue with phi3 and llava-phi3 using ollama.
