### ISSUE TITLE
[Bug]: Make dependencies less strict

### ISSUE THREAD

**Issue by AjayP13** [BerriAI/litellm#438]
### What happened?

```bash
The conflict is caused by:
    The user requested tiktoken==0.5.1
    litellm 0.1.743 depends on tiktoken<0.5.0 and >=0.4.0
```

While this is easy to fix by doing the installs separately, it prevents LiteLLM from being integrated into a downstream library's requirements.txt as I am trying to do.

**Comment by AjayP13** [comment]
Also this is another issue,

```bash
The conflict is caused by:
transformers 4.33.2 depends on tokenizers!=0.11.3, <0.14 and >=0.11.1
litellm 0.1.743 depends on tokenizers<0.15.0 and >=0.14.0
```

There is currently no version of transformers on PyPI that satisfies the requirements set by litellm 0.1.743, this makes it impossible to add litellm as a dependency properly in a requirements.txt.

**Comment by ghost** [comment]
Hey @AjayP13 thanks for surfacing this. What do you suggest we could do here? 

We added tokenizers to support token counting for cohere and anthropic. What's a good way to loosen the version requirement here?

**Comment by AjayP13** [comment]
Makes sense, for requirements I generally would prefer they be “>= (widely
used stable version)” with no upper version limit (to always allow end
users the freedom to use a newer version of a dependency that may have a
critical bug fix / security patch / new feature).

For tiktoken that would mean >=0.4.0.

For tokenizers you could you potentially do >= 0.14.0 and raise a
RuntimeError to gate any code that requires 0.15.0 features.

I realize it’s not the ideal solution, because loosening dependencies means
litellm may not be compatible with those versions, but unfortunately with
the way pip works, it’s generally the best solution for avoiding conflicts
like this downstream usage since the Python ecosystem doesn’t have nested
dependencies like Node.js.

**Comment by ishaan-jaff** [comment]
addressed here: https://github.com/BerriAI/litellm/commit/b0c05d0ef3c899365e95753a35b145862cd3e196

**Comment by AjayP13** [comment]
Thanks for the quick fix. Still getting errors because of this:

```bash
transformers 4.33.2 depends on tokenizers!=0.11.3, <0.14 and >=0.11.1
    petals 2.1.0 depends on tokenizers>=0.13.3
    litellm 0.1.745 depends on tokenizers>=0.14.0
```

Could you make `tokenizers>=0.13.0` instead, didn't realize `transformers` is enforcing <0.14 and not <=0.14. Could you also do the same `>=` with the other dependencies in `pyproject.toml` like `openai`?

**Comment by ghost** [comment]
Can you test with `0.1.746`? @AjayP13 
<img width="627" alt="Screenshot 2023-09-25 at 9 19 12 AM" src="https://github.com/BerriAI/litellm/assets/17561003/63cb4526-7cbd-46a3-9285-424990c5d584">


Would love to give you a shoutout once we've announced the fix. do you have a twitter/linkedin?

**Comment by AjayP13** [comment]
That version fixes the conflicts! Thanks @krrishdholakia and @ishaan-jaff for the fast updates. I'm on Twitter here (@ajayp95). I see you guys are also YC :), small world, will reach out separately offline to show you what I'm putting together if you're interested! But LiteLLM looks like it'll be really helpful piece to help take care of integrations.
