### ISSUE TITLE
[Bug]: I get error litellm' has no attribute 'validate_environment'

### ISSUE THREAD

**Issue by ramsey-coding** [BerriAI/litellm#4393]
### What happened?

I get `AttributeError: module 'litellm' has no attribute 'validate_environment'`

### Relevant log output

```shell
litellm==1.40.21
```

**Comment by ishaan-jaff** [comment]
I see it right here: https://github.com/BerriAI/litellm/blob/37f2712bba03e25a47544fef59c0b3814f1b9d6f/litellm/__init__.py#L755

**Comment by ishaan-jaff** [comment]
do you see the same issue on older versions @ramsey-coding ?

**Comment by ramsey-coding** [comment]
what version should I be using?

**Comment by ghost** [comment]
the latest one
