### ISSUE TITLE
[Feature]: NVIDIA NIM provider

### ISSUE THREAD

**Issue by Victorivus** [BerriAI/litellm#4397]
### The Feature

NVIDIA just released in their NGC, access to plenty of LLMs with their NIM containers. It would be nice to have them integrated as other cloud providers such as Bedrock.

Interest URLs:

- https://build.nvidia.com/google/gemma-7b
- https://integrate.api.nvidia.com/v1/models
- https://docs.nvidia.com/nim/large-language-models/latest/api-reference.html#openapi-schema

### Motivation, pitch

NVIDIA est très cool and they just released this, it would be awesame to have even more choice of providers in LiteLLM ! 🤯

**Comment by ishaan-jaff** [comment]
adding this today

**Comment by ishaan-jaff** [comment]
@Victorivus this is done in the linked PR + doc here https://docs.litellm.ai/docs/providers/nvidia_nim 

Any chance we can hop on a call ? I'd love to learn how how we can improve litellm for you.

Sharing a link to my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
My linkedin for your convenience: https://www.linkedin.com/in/reffajnaahsi/
