### ISSUE TITLE
[Feature]: Allow list of string in mock_response

### ISSUE THREAD

**Issue by NikolasWolke** [BerriAI/litellm#4399]
### The Feature

To test completions with n>1, mock response should support a list of string with message texts.

### Motivation, pitch

Currently, when setting `n>1` and using a mock response one can only get a single choice (and thus message) in the model response. Thus, this behaves differently from an actual model that will return `n` choices.

**Comment by ishaan-jaff** [comment]
instead of passing a list it returns `n` choices when `n` is provided 
PR here: https://github.com/BerriAI/litellm/issues/4399 


works like this 

```python

def test_mock_request_n_greater_than_1():
    try:
        model = "gpt-3.5-turbo"
        messages = [{"role": "user", "content": "Hey, I'm a mock request"}]
        response = litellm.mock_completion(model=model, messages=messages, n=5)
        print("response: ", response)

        assert len(response.choices) == 5
        for choice in response.choices:
            assert choice.message.content == "This is a mock request"

    except:
        traceback.print_exc()

```

**Comment by ishaan-jaff** [comment]
Hi @NikolasWolke this is fixed in the linked PR

@NikolasWolke any chance we can hop on a call ? I'd love to learn how how we can improve litellm for you.

Sharing a link to my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
My linkedin if you prefer DM: https://www.linkedin.com/in/reffajnaahsi/

**Comment by ishaan-jaff** [comment]
FYI - I thought it would be neater to just use `n` to send multiple response choices as opposed to introducing a list of strings 

open to your feedback on this

**Comment by NikolasWolke** [comment]
Great! Thanks for the speedy resolution :rocket: 

> FYI - I thought it would be neater to just use n to send multiple response choices as opposed to introducing a list of strings

This solution certainly works as well. I was referring to the `mock_response` argument in the `completion` function. It is currently an optional string. My suggestion was to use `mock_response: list[str] | str | None` and if n>1, you can use the `n` elements from `mock_response` if it is a list or just repeat the string `n` times.

But by calling `mock_completion` I can achieve the same outcome, so I am happy :+1: 

> any chance we can hop on a call ? I'd love to learn how how we can improve litellm for you.

Sounds great. I have chosen a spot for tomorrow. But don't expect too much - we are currently using litellm in a very basic way.
