### ISSUE TITLE
[Feature]: Accept multiple API Keys 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#440]
### The Feature

Allow user to pass multiple api keys for openai. 

"Let's say I have multiple accounts on OpenAI. And I have multiple keys, one for each account. Then is it possible to pass multiple keys to litellm and litellm uses different keys in round robin style or randomly."  - user request. 

### Motivation, pitch

Users have multiple accounts to deal with token limit issues

**Comment by ghost** [comment]
cc: @bgokden

**Comment by ghost** [comment]
This is now possible via Router

**Comment by Jai-Samyukth** [comment]
@krrishdholakia, I'm having trouble configuring multiple API keys for a single provider using `config.yaml`. I'm unsure if my configuration is correct and whether the keys are actually rotating. Any help would be appreciated.
Please let me know if this is possible, and if so, how to set it up.
