### ISSUE TITLE
[Bug]: Discrepancy between `tool_choice="required"/"any"` prevents me from using the proxy

### ISSUE THREAD

**Issue by ZanSara** [BerriAI/litellm#4416]
### What happened?

I'm trying to use LiteLLM's proxy to route calls to gpt-4o to [`fireeworks_ai/firefunction-v2`](https://fireworks.ai/blog/firefunction-v2-launch-post). For my application, I need to force the models to call a tool. The feature is available on both models, however OpenAI API's require setting `tool_choice="required"` while FireFunction expects `tool_choice="any"`.

I've been doing this swap in my code so far, but now I want to use your proxy, which means that I can't do it anymore, because I can't tell of the proxy will call gpt-4o or firefunction behind the scenes. 

Is this a fix that can be implemented on your end?

### Relevant log output

```shell
openai.BadRequestError: Error code: 400 - {'error': {'message': 'litellm.BadRequestError: BadRequestError: Fireworks_aiException - Error code: 400 - {\'error\': {\'object\': \'error\', \'type\': \'invalid_request_error\', \'message\': "2 request validation errors: Input should be \'auto\', \'none\' or \'any\', field: \'tool_choice.literal[\'auto\',\'none\',\'any\']\', value: \'required\'; Input should be a valid dictionary or object to extract fields from, field: \'tool_choice.FunctionSelection\', value: \'required\'"}}', 'type': None, 'param': None, 'code': 400}}
```

### Twitter / LinkedIn details

@zansara_dev  https://www.linkedin.com/in/sarazanzottera

**Comment by ZanSara** [comment]
PS: I'm happy to contribute on this issue if you are happy with it and can give me a pointer on where to start

**Comment by ishaan-jaff** [comment]
hi @ZanSara will get this fixed today

**Comment by ZanSara** [comment]
@ishaan-jaff Thank you!

**Comment by ishaan-jaff** [comment]
Okay so here's my understanding 

On fireworks AI 
To specify that any function call is a good function call, and a function call should always be made, you can use the `any`


On OpenAI 
To force the model to always call one or more functions, you can set tool_choice: "required". The model will then select which function(s) to call.

**Comment by ishaan-jaff** [comment]
so when you pass `tool_choice="required"` to litellm -> we should send fireworks ai `tool_choice="any"`

correct @ZanSara ?

**Comment by ZanSara** [comment]
Yes this is exactly what I'm trying to do

**Comment by ZanSara** [comment]
I'm not sure if this applies to all models or to `firefunction-v2` specifically though, I haven't tested any other model.

**Comment by ishaan-jaff** [comment]
looks like all other models on fireworks ai @ZanSara https://docs.fireworks.ai/guides/function-calling#tool-choice

**Comment by ishaan-jaff** [comment]
pr here @ZanSara https://github.com/BerriAI/litellm/pull/4418

**Comment by ishaan-jaff** [comment]
@ZanSara any chance we can hop on a call ? I'd love to learn how how we can improve litellm for you.

I reached out to you on Linkedin if DMs work.
Sharing a link to my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by ZanSara** [comment]
Thank you for this lightning-fast fix! Sure, happy to talk :blush:
