### ISSUE TITLE
[Bug]: LiteLLM Proxy Traceparent header is not forwarded to backends

### ISSUE THREAD

**Issue by aloababa** [BerriAI/litellm#4419]
### What happened?

It seems that the Traceparent header is not forwarded to backends (vllm) when proxying with LiteLLM.
It would be nice if it can be forwarded to the backends so the backend traces can have the LiteLLM traces as parent.

### Relevant log output

```shell
Here is a dump of the request send to vllm by LiteLLM:

POST /v1/chat/completions HTTP/1.1
Host: mimproxy:6060
Accept: application/json
Accept-Encoding: gzip, deflate
Authorization: Bearer -
Connection: keep-alive
Content-Length: 144
Content-Type: application/json
User-Agent: AsyncOpenAI/Python 1.27.0
X-Stainless-Arch: x64
X-Stainless-Async: async:asyncio
X-Stainless-Lang: python
X-Stainless-Os: Linux
X-Stainless-Package-Version: 1.27.0
X-Stainless-Runtime: CPython
X-Stainless-Runtime-Version: 3.11.8
```

**Comment by ishaan-jaff** [comment]
is this with OTEL @aloababa ? So when you pass a traceparent header in the request -> litellm should add the traceparent header in the response

**Comment by aloababa** [comment]
Yes this is with OTEL, it successfully parse the Traceheader if there is one in the request so i can link my trace from frontend to LiteLLM, but after this Traceparent header is not forwarded to the backend (vllm) so my trace stops at LiteLLM and i got a new trace for vllm that is not linked to it.

**Comment by ishaan-jaff** [comment]
got it -> so if a traceparent is in the request header -> we should forward this to vLLM ?

**Comment by ishaan-jaff** [comment]
fix here @aloababa https://github.com/BerriAI/litellm/pull/4423

**Comment by ishaan-jaff** [comment]
I can see it forwards the traceparent to the provider 

<img width="1280" alt="Screenshot 2024-06-26 at 12 34 39 PM" src="https://github.com/BerriAI/litellm/assets/29436595/e10fef25-ebb4-4e1f-beb7-af4459329e03">

**Comment by ishaan-jaff** [comment]
@aloababa any chance we can hop on a call ? I'd love to learn how how we can improve litellm for you.

I reached out to you on Linkedin if DMs work.
Sharing a link to my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by aloababa** [comment]
Thank you very much for your reactivity.
It works well if i provide the Traceparent header in the request to LiteLLM.
Is it also possible that you forward the Traceparent header even if the Traceparent header is not provided in the original request ? so you put the trace id generated by the LiteLLM otel integration in the Traceparent header.

**Comment by ishaan-jaff** [comment]
hi @aloababa we had to make this opt in behavior since Bedrock calls were failing when forwarding traceparent. Here is the change you need to make in your config.yaml to continue using this 

```yaml
litellm_settings:
  forward_traceparent_to_llm_provider: True

```

**Comment by heisaman** [comment]
Hi @ishaan-jaff , just curious about other Otel trace http header's support(like b3?). I don't see any config setting like: forward_b3_to_llm_provider, or maybe one setting "forward_client_headers_to_llm_api=True" is just enough for all types?

The official docs is not clear about this. 
[traceparent-header](https://docs.litellm.ai/docs/proxy/logging#traceparent-header)
[All settings](https://docs.litellm.ai/docs/proxy/config_settings#general_settings---reference)
