### ISSUE TITLE
[Feature]: Support Vertex Imagen2 

### ISSUE THREAD

**Issue by emerzon** [BerriAI/litellm#4425]
### The Feature

Add support for Imagen2 image generation model in Vertex:
https://console.cloud.google.com/vertex-ai/publishers/google/model-garden/imagegeneration

### Motivation, pitch

Would be awesome :)
Not really a blocker for any use case.

### Twitter / LinkedIn details

@emersongomesma

**Comment by ishaan-jaff** [comment]
already supported @emerzon https://docs.litellm.ai/docs/providers/vertex#image-generation-models 

feel free to re-open if im mistaken
