### ISSUE TITLE
How to pass access token/authorization key to run ollama through litellm

### ISSUE THREAD

**Issue by PhilipAmadasun** [BerriAI/litellm#4426]
I am using a server to run ollama securely if I provide an access token (not an openai api_key), If I use ollama directly, I can use the `headers` parameter to provide the access token when using RestFul API. How can I do the same thing when using ollama through litellm?. I'm using  `litellm.completion()`.

**Comment by ghost** [comment]
hey @PhilipAmadasun we let you pass in the api key when calling ollama 

just add it like this: 

```
litellm.completion(.., api_key=<my-ollama-api-key>) 
```

this is the relevant code - https://github.com/BerriAI/litellm/blob/8fa2cf15eee0a8b8c062960edae2aa3716b29091/litellm/llms/ollama_chat.py#L199
