### ISSUE TITLE
[Bug]: Overly strict validation of chunks results in missing tool name

### ISSUE THREAD

**Issue by ZanSara** [BerriAI/litellm#4440]
### What happened?

I'm using `firefunction-v2` for streamed tool calls. There seems to be a validation issues with the response chunks: the chunk that contains the function name sets `function.arguments` to `None` instead of an empty string, LiteLLM fails to parse it, and the result is that the name of the function to invoke gets lost.

### Relevant log output

```shell
10:48:11 - LiteLLM:ERROR: utils.py:9203 - litellm.CustomStreamWrapper.chunk_creator(): Exception occured - 1 validation error for ChatCompletionDeltaToolCall
function.arguments
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.7/v/string_type
```

### Twitter / LinkedIn details

https://www.linkedin.com/in/sarazanzottera @zansara_dev

**Comment by ghost** [comment]
Hey @ZanSara pushed a fix - https://github.com/BerriAI/litellm/commit/010b55e6db7edcc5cba56813eed8ff696d16505f

live soon in v`1.40.29`.

---
can you let me know if this solves it for you? I saw some other weird stuff with the fireworks streaming call as well
