### ISSUE TITLE
[Bug]: Allow 2,097,152 tokens with Gemini 1.5 Pro

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#4450]
### What happened?

I think this is just for Google AI Studio atm, not sure about Vertex AI.

<img width="281" alt="image" src="https://github.com/BerriAI/litellm/assets/7232674/8b48ede7-c8ab-4815-a28a-8e44b407beb2">

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by emerzon** [comment]
Also true for Vertex

**Comment by Manouchehri** [comment]
Ah yep, I see it's 2M on Vertex AI now too!

<img width="430" alt="image" src="https://github.com/BerriAI/litellm/assets/7232674/42a08ad5-c621-4ae1-9ef0-3216b5b39649">

**Comment by ghost** [comment]
@Manouchehri can you clarify - what's the bug? Your screenshot is that of google ai studio

**Comment by Manouchehri** [comment]
@krrishdholakia https://github.com/BerriAI/litellm/blob/76490690a15af8c3b53a03878d7f268d0bf225af/model_prices_and_context_window.json#L1468

https://github.com/BerriAI/litellm/blob/76490690a15af8c3b53a03878d7f268d0bf225af/model_prices_and_context_window.json#L1493

**Comment by ghost** [comment]
added - https://github.com/BerriAI/litellm/commit/8b1bd749ffec45b44f3b0f1a8c4f8bbf1370af7f
