### ISSUE TITLE
[Feature]: Integrate Azure Monitor into LiteLLM

### ISSUE THREAD

**Issue by RyoYang** [BerriAI/litellm#4453]
### The Feature

As this document introduced: https://learn.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-enable?tabs=python
![image](https://github.com/BerriAI/litellm/assets/24616097/08bb20e3-1c14-4472-8680-d1e8c3ca18bf)

Are we able to config azure-monitor in Litellm, like add connectionstring in configuration to collect all the traces data from python logging module and ingest data into azure monitor/application insight.

### Motivation, pitch

Support azure monitor in LiteLLM

**Comment by ishaan-jaff** [comment]
This is OTEL compatible - we already have an OTEL collector https://docs.litellm.ai/docs/proxy/logging#logging-proxy-inputoutput-in-opentelemetry-format 

@RyoYang let me know if this does not work for you

**Comment by ishaan-jaff** [comment]
feel free to re-open this issue too

**Comment by RyoYang** [comment]
Hey @ishaan-jaff , I just checked the exporters in Litellm, but it seems like only support `http_exporter` and `grpc_exporter`, for azure monitor, we need to use `AzureMonitorLogExporter` in this [doc](https://learn.microsoft.com/en-us/python/api/overview/azure/monitor-opentelemetry-exporter-readme?view=azure-python-preview#:~:text=Logging%20(experimental)-,NOTE%3A%20The%20logging%20signal%20for%20the%20AzureMonitorLogExporter%20is%20currently%20in%20an%20EXPERIMENTAL%20state.%20Possible%20breaking%20changes%20may%20ensue%20in%20the%20future.,-The%20following%20sections). Also, I would like to use opentelemetry in customized logging I created.
Could you please reopen this issue?
