### ISSUE TITLE
[Feature]: Add langsmith integration

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#446]
### The Feature

add langsmith integration for observability/monitoring 

### Motivation, pitch

nick needs it

**Comment by ishaan-jaff** [comment]
done

**Comment by ishaan-jaff** [comment]
https://docs.litellm.ai/docs/observability/langfuse_integration

**Comment by ghost** [comment]
@ishaan-jaff i assume you mean this - https://docs.litellm.ai/docs/observability/langsmith_integration
