### ISSUE TITLE
[Feature]: Support global 'response_schema' param 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#4473]
### The Feature

Similar to the gemini specific implementation - https://docs.litellm.ai/docs/providers/vertex#json-schema

"for models that support it directly forward it along.  For models that don't we would append it to the prompt. 

and then validate the schema on return and if it fails treat it as any other failure with retries

we could do the validation, but having it in LiteLLM so falbacks work is better." - @lolsborn 

v0  coverage: 
- gemini
- claude 3-5 sonnet 
- azure gpt-4o 

### Motivation, pitch

user request, to enable fallbacks/retries to work for json mode calls

**Comment by ghost** [comment]
e.g. of how gemini response schema works 

```python
from litellm import completion 
import json 

## SETUP ENVIRONMENT
# !gcloud auth application-default login - run this to add vertex credentials to your env

messages = [
    {
        "role": "user",
        "content": "List 5 popular cookie recipes."
    }
]

response_schema = {
        "type": "array",
        "items": {
            "type": "object",
            "properties": {
                "recipe_name": {
                    "type": "string",
                },
            },
            "required": ["recipe_name"],
        },
    }


completion(
    model="vertex_ai_beta/gemini-1.5-pro", 
    messages=messages, 
    response_format={"type": "json_object", "response_schema": response_schema} # 👈 KEY CHANGE
    )

print(json.loads(completion.choices[0].message.content))
```

**Comment by ghost** [comment]
v0:
- if model not supported, add as user message 
- validate the output for fallback/retries on router 
- support claude 35 sonnet on vertex ai

Bonus:
- azure gpt-4o support

**Comment by lolsborn** [comment]
@andrazk is likely to be the person to follow up on this and do the testing on our end.  He was already implementing some of this validation.

**Comment by ghost** [comment]
Rough thoughts re: implementation: 

---
If `response_schema` is set, litellm will validate the response against the schema, and raise a JSONSchemaValidationError if the response does not match the schema. 

JSONSchemaValidationError inherits from `openai.APIError` 

Access the raw response with `e.raw_response`

```python
from litellm import completion, JSONSchemaValidationError
try: 
	completion(
    model="vertex_ai_beta/gemini-1.5-pro", 
    messages=messages, 
    response_format={"type": "json_object", "response_schema": response_schema} # 👈 KEY CHANGE
	)
except JSONSchemaValidationError as e: 
	print("Raw Response: {}".format(e.raw_response))
	raise e
```

**Comment by ghost** [comment]
anthropic seems really poor at executing this

**Comment by ghost** [comment]
scoped to just vertex ai - this is now live https://docs.litellm.ai/docs/providers/vertex#json-schema
