### ISSUE TITLE
[Bug]: openrouter anthropic doesn't support `n` -> don't show it does 

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [BerriAI/litellm#4488]
### What happened?

The supported_openai_params value for claude sonnet via openrouter is inconsistent:

``` python
In [12]: litellm.get_model_info("anthropic/claude-3-5-sonnet-20240620")["supported_openai_params"]
Out[12]: 
['stream',
 'stop',
 'temperature',
 'top_p',
 'max_tokens',
 'tools',
 'tool_choice',
 'extra_headers']
```

And
``` python
In [13]: litellm.get_model_info("openrouter/anthropic/claude-3.5-sonnet")["supported_openai_params"]
Out[13]: 
['functions',
 'function_call',
 'temperature',
 'top_p',
 'n',
 'stream',
 'stop',
 'max_tokens',
 'presence_penalty',
 'frequency_penalty',
 'logit_bias',
 'user',
 'response_format',
 'seed',
 'tools',
 'tool_choice',
 'max_retries']
```

I learned this the hard way because I was detecting wether `n` parameter was supported before an API call and kept having issue with sonnet.

When looking at [the code](https://github.com/BerriAI/litellm/blob/46fe08920409816e631956cf0ad88021d132ca6a/litellm/utils.py#L3843) I see that the value is just based on the provider not the model.

A couple of things:
1. I think that "supported_openai_params" is somewhat misleading if it's not the model's params but the backend params. I'm sure there are other providers than openrouter that support different parameters depending on the model. I think it would be best to call it `supported_backend_params`.
2. FYI openrouter.ai [allows checking the supported arguments via API](https://openrouter.ai/docs/parameters-api) but it needs a valid key. If we already have an openrouter api key in the env, maybe it would be a good hotfix to ask openrouter directly for the params and if we lack the API key return the currently hardcoded ones.
3. I think the best fix would be to: on each new litellm release, query the parameters for each models of openrouter and update the hardcoded dict. (I can't remember which file but IIRC you have a hardcoded json file in the code which maintains all information about each model right? You could just update the params there on each release).

**Comment by ghost** [comment]
@thiswillbeyourgithub looks like openrouter just doesn't support the `n` param, even if the backend provider does (see gpt-4o vs. anthropic) 

<img width="579" alt="Screenshot 2024-07-01 at 8 20 16 AM" src="https://github.com/BerriAI/litellm/assets/17561003/75429fe3-3685-4baf-850d-4a663498a314">
<img width="629" alt="Screenshot 2024-07-01 at 8 20 24 AM" src="https://github.com/BerriAI/litellm/assets/17561003/4c1293d3-b6d6-495b-976b-3a058a3af85e">

**Comment by ghost** [comment]
Updated our list to reflect openrouter's correct parameter list - https://openrouter.ai/docs/parameters
