### ISSUE TITLE
[Bug]: Docs in openai compatible endpoints are missing a quotation mark in "model" parameter

### ISSUE THREAD

**Issue by neubig** [BerriAI/litellm#4490]
### What happened?

https://github.com/BerriAI/litellm/blob/46fe08920409816e631956cf0ad88021d132ca6a/docs/my-website/docs/providers/openai_compatible.md?plain=1#L21

**Comment by ishaan-jaff** [comment]
fixed here: https://github.com/BerriAI/litellm/commit/19464b2521cf330d729cc1f6d0f71e5cf1e5ea32
