### ISSUE TITLE
(bug) Not raising OpenAI Exceptions

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#45]
litellm v 0.1.231 (latest)
<img width="666" alt="Screenshot 2023-08-04 at 3 01 37 PM" src="https://github.com/BerriAI/litellm/assets/29436595/344e39af-538f-4116-bd4d-2dbe07559fe1">

cc @krrishdholakia

**Comment by ghost** [comment]
ok - so the way to repro this is to set it as bad key? 

Will test and see what might be causing this. Thanks for surfacing.

**Comment by ghost** [comment]
fixed in 0.1.3 @ishaan-jaff 

<img width="1309" alt="Screenshot 2023-08-05 at 10 32 22 AM" src="https://github.com/BerriAI/litellm/assets/17561003/c6acfa55-7d87-4687-a8d5-cbaf10791669">
