### ISSUE TITLE
[Bug]: Unknow LiteLLM Error

### ISSUE THREAD

**Issue by PierrunoYT** [BerriAI/litellm#4509]
### What happened?

A bug happened!

### Relevant log output

```shell
I will post a screenshot
```

**Comment by PierrunoYT** [comment]
![grafik](https://github.com/BerriAI/litellm/assets/95778421/59e88217-097d-45ae-bff1-78fc8e2618fd)

**Comment by PierrunoYT** [comment]
I used Aider.chat for it

**Comment by Harry989** [comment]
Man, posting a screenshot of your error instead of copying and pasting it, is like punching someone in the face.

**Comment by PierrunoYT** [comment]
Sorry but I already closd the terminal and so I posted this screenshot

**Comment by ghost** [comment]
how can i repro this?

**Comment by PierrunoYT** [comment]
It happened randomly in Aider

**Comment by ghost** [comment]
it looks like the error was raised by Mistral api which raised an error 
<img width="1062" alt="Screenshot 2024-07-03 at 1 11 43 PM" src="https://github.com/BerriAI/litellm/assets/17561003/2b483156-da60-4b37-938a-7d597a8e0e8d">

**Comment by PierrunoYT** [comment]
But I used Sonnet 3.5

**Comment by ghost** [comment]
the error indicates the backend api failed while streaming (see: `finish_reason: error`). 

is this openrouter? @PierrunoYT
