### ISSUE TITLE
[Bug]: Anthropic prompt factory,  anthropic_messages_pt_xml,  hangs with no error when role is not user, tool or assistant.

### ISSUE THREAD

**Issue by Joseph-Cardwell** [BerriAI/litellm#4512]
### What happened?

Issue: Infinite loop in message processing code
Description: When processing messages, the code skips messages with roles other than "user" or "assistant". However, the iterator count (msg_i) is not incremented in this case, causing the loop to get stuck in an infinite loop.
Impact: The code will hang indefinitely, failing to process any further messages.
Root Cause: The iterator count is not incremented when messages are skipped.

Fix: Add an else clause to increment msg_i regardless of whether the message is processed or skipped or throw an error.

### Twitter / LinkedIn details

https://www.linkedin.com/in/josephcardwell/

**Comment by ghost** [comment]
hey @Joseph-Cardwell do you have a code sample i can run to repro this? 

I don't think anthropic_messages_pt_xml is used anymore
