### ISSUE TITLE
Successfully installed litellm-0.1.749 tokenizers-0.14.0

### ISSUE THREAD

**Issue by CodeAKrome** [BerriAI/litellm#452]
Successfully installed litellm-0.1.749 tokenizers-0.14.0
lite-llm.py PygmalionAI/metharme-1.3b "Hello, how are you?"
```
litellm.exceptions.InvalidRequestError: HuggingfaceException - The following `model_kwargs` are not used by the model: ['details'] (note: typos in the generate arguments will also show up in this list)
```

```python
#!env python
from litellm import completion
import os
import sys

if len(sys.argv) > 1:
    model = "huggingface/" + sys.argv[1]
    text = sys.argv[2]
else:
    model = "huggingface/cerebras/btlm-3b-8k-base"
    text = "Hello, how are you?"

print(f"model:\t{model}\n")
messages = [{ "content": text,"role": "user"}]
response = completion(model, messages=messages)
print(f"{type(response)}")
print(response)
```

_Originally posted by @CodeAKrome in https://github.com/BerriAI/litellm/issues/334#issuecomment-1734794380_

**Comment by CodeAKrome** [comment]
I also get errors about not finished downloading for other models.
```
litellm.exceptions.APIError: HuggingfaceException - Model cerebras/btlm-3b-8k-base is currently loading
```
I couldn't find anything about this one.

**Comment by ishaan-jaff** [comment]
re: downloading models that looks like an error from the Huggingface API

**Comment by ishaan-jaff** [comment]
can you try modifying your completion call to this, adding the `task=None` to completion should fix the problem - please let me know if not 
```python
from litellm import completion
import os
import sys

if len(sys.argv) > 1:
    model = "huggingface/" + sys.argv[1]
    text = sys.argv[2]
else:
    model = "huggingface/cerebras/btlm-3b-8k-base"
    text = "Hello, how are you?"

print(f"model:\t{model}\n")
messages = [{ "content": text,"role": "user"}]
response = completion(model, messages=messages, task=None)
print(f"{type(response)}")
print(response)
```

**Comment by CodeAKrome** [comment]
That did it. Thx. :)
```
model:	huggingface/PygmalionAI/metharme-1.3b

<class 'litellm.utils.ModelResponse'>
{
  "object": "chat.completion",
  "choices": [
    {
      "finish_reason": "stop",
      "index": 0,
      "message": {
        "content": "Hello, how are you?\n\nI'm good, how are you?\n\nI'm",
        "role": "assistant",
        "logprobs": null
      }
    }
  ],
  "id": "chatcmpl-da7b1915-7b44-4125-a998-1f4ebfa3887f",
  "created": 1695703252.0047903,
  "model": "PygmalionAI/metharme-1.3b",
  "usage": {
    "prompt_tokens": 6,
    "completion_tokens": 16,
    "total_tokens": 22
  }
}
```

**Comment by ishaan-jaff** [comment]
Awesome - I think this experience of setting `task` is a bad DX and we have an open issue to make this better. 

any suggestions on what could have been done better for you ?

**Comment by CodeAKrome** [comment]
I don't see task listed as an argument on this [page](https://litellm.vercel.app/docs/completion/input), assuming I got the right one.
Also, how do I pass arguments to huggingface through your API?
```
litellm.exceptions.APIError: HuggingfaceException - The repository for cerebras/btlm-3b-8k-base contains custom code which must be executed to correctly load the model. You can inspect the repository content at https://hf.co/cerebras/btlm-3b-8k-base. Please pass the argument `trust_remote_code=True` to allow custom code to be run.
```
I add then
```
completion() got an unexpected keyword argument 'trust_remote_code'
```

**Comment by ghost** [comment]
hey @CodeAKrome i'm looking at this right now. Didn't have support for that, i'll add it now.

**Comment by ghost** [comment]
Hey @CodeAKrome there doesn't seem to be a param we can pass in to huggingface to set this flag - looking at this: 
https://huggingface.co/docs/api-inference/detailed_parameters

If you're able to get this to work via a curl command to the hf endpoint, can you let me know? I tried a couple variants and wasn't able to get hf to accept the value

**Comment by CodeAKrome** [comment]
I haven't used their inference API yet. Looking.

**Comment by CodeAKrome** [comment]
The sample code from the model card does endless calculations for some reason and my system kills it as a runaway, Lol.
Save me lite-llm, you're my only hope!

**Comment by ghost** [comment]
how can we help here @CodeAKrome
