### ISSUE TITLE
[Bug]: LiteLLM:ERROR: litellm_logging.py for ollama deepseek-coder-v2

### ISSUE THREAD

**Issue by danividalg** [BerriAI/litellm#4521]
### What happened?

I am using ollama model: deepseek-coder-v2, but at the end after answering
I get this message

00:02:19 - LiteLLM:ERROR: litellm_logging.py:1265 - Model=deepseek-coder-v2 not found in completion cost map. Setting 'response_cost' to None

If I use it with llama3, there is no error.

Maybe need to add to
- https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json
- https://github.com/BerriAI/litellm/blob/main/litellm/model_prices_and_context_window_backup.json
this code:

    "ollama/deepseek-coder-v2": {
        "max_tokens": 4096,
        "max_input_tokens": 32000,
        "max_output_tokens": 4096,
        "input_cost_per_token": 0.0,
        "output_cost_per_token": 0.0,
        "litellm_provider": "ollama",
        "mode": "chat"
    },

Thanks a lot in advance for add it as soon as possible :)

**Comment by ghost** [comment]
Saw you were able to resolve your issue - https://github.com/paul-gauthier/aider/issues/781
