### ISSUE TITLE
Error code: 404

### ISSUE THREAD

**Issue by jangiliashok** [BerriAI/litellm#4526]
`import litellm

client = litellm.LiteLLM(
    base_url="/v1",
    api_key="",
)
response = client.chat.completions.create(
    messages=[{"content": prompt, "role": "user"}],
    model="azureai",
    custom_llm_provider="custom_openai",
)`

Iam facing litellm.NotFoundError: NotFoundError: Custom_openaiException - Error code: 404 - {'object': 'error', 'message': 'The model `azureai` does not exist.', 'type': 'NotFoundError', 'param': None, 'code': 404} issue . Previously I was able to use the PHI3 model with same code but now Iam unable to use .

**Comment by ghost** [comment]
> object': 'error', 'message': 'The model azureai does not exist.'

this is coming from your backend provider. So wherever your model is hosted, is raising this.
