### ISSUE TITLE
[Feature]: Turn off or tune down noisy library logging

### ISSUE THREAD

**Issue by AshSourceTable** [BerriAI/litellm#4528]
### The Feature

LiteLLM is so noisy! It clogs up our logs, super hard to debug the app as a whole. We don't use the proxy, just the library, and have found no way to get it to quieten down. Its default logging level is way too verbose, and setting logging level to WARN or ERROR does nothing.

### Motivation, pitch

Makes it hard to see what's going on in our app outside LiteLLM

**Comment by ishaan-jaff** [comment]
hi @AshSourceTable sorry for this can you show me

- what litellm version are you on? do you see noisy logging on latest version of litellm 
- are you switching on debugging / `litellm.set_verbose=True` ? 
- what noisy logs are you seeing ? Can I see an example

**Comment by ghost** [comment]
bump on this? @AshSourceTable 

We run the library in prod, and without `LITELLM_DEBUG` our logs are pretty empty 
<img width="830" alt="Screenshot 2024-07-04 at 4 33 27 PM" src="https://github.com/BerriAI/litellm/assets/17561003/609452d5-82d0-4636-bb56-34311b447f3c">
