### ISSUE TITLE
[Feature]: Proxy OpenAI functions to Cloude tools

### ISSUE THREAD

**Issue by delfer** [BerriAI/litellm#4544]
### The Feature

OpenAI support functions.
Cloude support the same feature - tools.
LiteLLM also supports using tools. It would be nice to to proxy Functions into Tool. Now it's drops by "LITELLM_DROP_PARAMS=True" 

### Motivation, pitch

I'am using telegram bot https://github.com/n3d1117/chatgpt-telegram-bot . It's very nice and have a lot of functions, but works only with OpenAI API. Proxy can help.

**Comment by ghost** [comment]
do you mean claude? 

We already support tool calling for claude @delfer https://docs.litellm.ai/docs/providers/anthropic#usage---function-calling

**Comment by delfer** [comment]
@krrishdholakia Claude, sure)
LiteLLM supports tool calling, but does not support Proxy functions calls to tools calls.

**Comment by ghost** [comment]
What do you mean? @delfer 

Here's a curl for tool calling with litellm 

```bash
curl -X POST 'http://0.0.0.0:4000/chat/completions' \
-H 'Content-Type: application/json' \
-H 'Authorization: Bearer sk-Ot5iy8bg8bzuUrLkvURLiA' \
-D '{
  "model": "anthropic-claude-3",
  "messages": [
    {
      "role": "user",
      "content": "What'\''s the weather like in Boston today?"
    }
  ],
  "tools": [
    {
      "type": "function",
      "function": {
        "name": "get_current_weather",
        "description": "Get the current weather in a given location",
        "parameters": {
          "type": "object",
          "properties": {
            "location": {
              "type": "string",
              "description": "The city and state, e.g. San Francisco, CA"
            },
            "unit": {
              "type": "string",
              "enum": ["celsius", "fahrenheit"]
            }
          },
          "required": ["location"]
        }
      }
    }
  ],
  "tool_choice": "auto",
}'
```


Where would it have been helpful to see this?
