### ISSUE TITLE
[Feature]: Support vLLM offline inference arguments

### ISSUE THREAD

**Issue by jantrienes** [BerriAI/litellm#4556]
### The Feature

Add support for vLLM engine arguments in completion calls (i.e., `completion(model='vllm/...')`).

Currently only the `model` argument is passed to vllm.LLM:

https://github.com/BerriAI/litellm/blob/c425cba93a1f40352a5140ac0adc79847f5f8373/litellm/llms/vllm.py#L30-L31

Possible arguments: https://github.com/vllm-project/vllm/blob/ea4b5704833cb31377bcbc2f00959f6c09909099/vllm/entrypoints/llm.py#L24-L87

Potential API:

```py
litellm.completion(
    model='vllm/meta-llama/Meta-Llama-3-70B-Instruct',
    messages=messages,
    vllm_args={
        'tensor_parallel_size': 2,
    }
)
```

### Motivation, pitch

This is helpful in many ways, for example to run models on multiple GPUs.

**Comment by ghost** [comment]
hey @jantrienes any non-openai params are already sent straight through as kwargs in the request body 

see more: https://docs.litellm.ai/docs/completion/input#provider-specific-params
<img width="984" alt="Screenshot 2024-07-05 at 11 50 41 AM" src="https://github.com/BerriAI/litellm/assets/17561003/4efd0174-cb03-49b6-b4ed-1f7cd931c5dc">

**Comment by ghost** [comment]
closing for now as this seems supported already. Let me know if i missed anything.

**Comment by jantrienes** [comment]
Hi @krrishdholakia, if I'm not mistaken, vLLM is initialized/loaded upon the first call of completion, but only the `model` parameter is passed through at this point. Here's the full code snippet of the function I believe is related:

https://github.com/BerriAI/litellm/blob/017af348667b9262988b675871b0c10f6150bc7d/litellm/llms/vllm.py#L24-L34
