### ISSUE TITLE
[Bug]: Incorrect Parameters for Nvidia NMI Models

### ISSUE THREAD

**Issue by kyleavery** [BerriAI/litellm#4558]
### What happened?

I have tried a couple of different models hosted on Nvidia NMI, but none of them support system messages, frequency penalty, or presence penalty. This is causing errors that (I think) should be mitigated by `litellm.drop_params = True`.

### Relevant log output

- Presence/Frequency penalty:
```
litellm.exceptions.BadRequestError: litellm.BadRequestError: BadRequestError: Nvidia_nimException - data:{"type":"urn:inference-service:problem-details:unprocessable-entity","title":"Unprocessable Entity","status":422,"detail":"body -> frequency_penalty\n  Extra inputs are not permitted (type=extra_forbidden)\nbody -> presence_penalty\n  Extra inputs are not permitted (type=extra_forbidden)","instance":"/v2/nvcf/pexec/functions/1136f83f-7706-49f3-970b-67499c26724e","requestId":"2230b3a0-fa60-4121-81fc-1ae4c5946083"}
```

- System role:
```
litellm.exceptions.APIError: litellm.APIError: APIError: Nvidia_nimException - data:{"type":"urn:inference-service:problem-details:internal-server-error","title":"Internal Server Error","status":500,"detail":"System role not supported","instance":"/v2/nvcf/pexec/functions/1136f83f-7706-49f3-970b-67499c26724e","requestId":"3a622dca-c61c-49d1-81c0-f625f76388f2"}
```

**Comment by kyleavery** [comment]
Passing `supports_system_message=False` results in a new error:

```
litellm.exceptions.APIError: litellm.APIError: APIError: Nvidia_nimException - data:{"type":"urn:inference-service:problem-details:internal-server-error","title":"Internal Server Error","status":500,"detail":"Conversation roles must alternate user/assistant/user/assistant/...","instance":"/v2/nvcf/pexec/functions/1136f83f-7706-49f3-970b-67499c26724e","requestId":"3d6971ec-91d8-4ba0-ba87-34bf3486e5c9"}
```

My application passes two sequential "user" messages. This hasn't caused issues with other providers or models.

**Comment by ishaan-jaff** [comment]
acknowledging this - aiming to fix today

**Comment by ishaan-jaff** [comment]
@kyleavery I can see nvidia docs say they support `frequency penalty and presence penalty.`

https://build.nvidia.com/mistralai/mixtral-8x22b-instruct

**Comment by ishaan-jaff** [comment]
This works perfectly for me @kyleavery 

```python
response = completion(
            model=model_name,
            messages=[
                {
                    "role": "user",
                    "content": "What's the weather like in Boston today in Fahrenheit?",
                }
            ],
            presence_penalty=0.5,
            frequency_penalty=0.1,
        )
```

**Comment by kyleavery** [comment]
@ishaan-jaff  Maybe it's different for some models then? I tested `gemma-2-9b-it` and `nemotron-4-340b-instruct`.

**Comment by ishaan-jaff** [comment]
you're right 😅

**Comment by ishaan-jaff** [comment]
Fix PR here https://github.com/BerriAI/litellm/pull/4565 

@kyleavery curious do you use the LiteLLM SDK or Proxy Server ?

**Comment by kyleavery** [comment]
Nice, thank you! I just use the Python library, no proxy server.

Does this also fix the issue with system messages?

> Passing `supports_system_message=False` results in a new error:
> 
> ```
> litellm.exceptions.APIError: litellm.APIError: APIError: Nvidia_nimException - data:{"type":"urn:inference-service:problem-details:internal-server-error","title":"Internal Server Error","status":500,"detail":"Conversation roles must alternate user/assistant/user/assistant/...","instance":"/v2/nvcf/pexec/functions/1136f83f-7706-49f3-970b-67499c26724e","requestId":"3d6971ec-91d8-4ba0-ba87-34bf3486e5c9"}
> ```
> 
> My application passes two sequential "user" messages. This hasn't caused issues with other providers or models.

**Comment by ishaan-jaff** [comment]
we already handle this @kyleavery https://github.com/BerriAI/litellm/blob/c99a5a58ec3dad70cc3c0b74be58c6c0b3d247c3/litellm/llms/openai.py#L830

**Comment by ishaan-jaff** [comment]
confirmed it worked for me too

```
litellm.drop_params=True
    litellm.set_verbose = True
    model_name = "nvidia_nim/google/gemma-2-9b-it"
    try:
        response = completion(
            model=model_name,
            messages=[
                {
                    "role": "user",
                    "content": "What's the weather like in Boston today in Fahrenheit?",
                },
                {
                    "role": "user",
                    "content": "What's the weather like in Boston today in Fahrenheit?",
                },
            ],
            presence_penalty=0.5,
            frequency_penalty=0.1,
        )
        # Add any assertions here to check the response
        print(response)
```

**Comment by kyleavery** [comment]
Ah perfect, thank you!

**Comment by ishaan-jaff** [comment]
> Passing supports_system_message=False results in a new error:

You should not be passing this in your request - since `google/gemma-2-9b-it` does actually support a system_message

**Comment by kyleavery** [comment]
I think I needed it for `nemotron-4-340b-instruct`
