### ISSUE TITLE
[Bug]: LiteLLM doesn't report Anthropic streaming errors

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#4562]
### What happened?

<img width="728" alt="image" src="https://github.com/BerriAI/litellm/assets/7232674/b26de760-5bf1-4fb3-98d9-c4fd56af63be">

When there's an error event, `chunk_parser` does not look for `error` blocks.

### Relevant log output

```shell
event: content_block_delta
data: {"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"d with a replacement character"}             }

event: content_block_delta
data: {"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":" ("} }

event: error
data: {"type":"error","error":{"details":null,"type":"api_error","message":"Internal server error"}      }
```

### Twitter / LinkedIn details

https://twitter.com/DaveManouchehri

**Comment by ishaan-jaff** [comment]
what provider is this on? Anthropic API, Bedrock, Vertex ?

**Comment by Manouchehri** [comment]
Anthropic API

**Comment by ishaan-jaff** [comment]
should we raise an exception mid stream when this happens ?

**Comment by ishaan-jaff** [comment]
Fix here: https://github.com/BerriAI/litellm/pull/4566
