### ISSUE TITLE
[Feature]: Add setup wizard to proxy server

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#457]
### The Feature

Add a setup wizard to guide users on what key is required for a given model name / provider 

### Motivation, pitch

When a user runs `litellm --model <model-name>`, we expect them to have already put in the relevant api keys in their .env. 

This isn't always the case, and can be frustrating to experience.

**Comment by ghost** [comment]
if api key / any required env is missing - ask for those too

**Comment by vxacezxcv** [comment]
I have several concerns about the proxy server deployment:
1. How the api base and key information is secured when deployed to `litellm.ai`?
2. Is there a way to cancel the deployment?
3. Why ALL the environment variables are saved to a file and sent to `litellm.ai`?

**Comment by ghost** [comment]
hey @vxacezxcv the proxy server runs locally. 

you can choose to deploy it when you run `litellm --deploy`. 

is it deploying without you running `litellm --deploy`?

**Comment by vxacezxcv** [comment]
Hello @krrishdholakia 
I understand that it can be deployed local or remote, and the local deployment lgtm.

For the remote deployment option, why all the environment variables are sent to remote (seems not neccessary, and it may contain some sensitive information):
https://github.com/BerriAI/litellm/blob/10ad137b2ec82312f58afd6f0114cda61cd5fddc/litellm/proxy/proxy_server.py#L80-L82

**Comment by ghost** [comment]
Hey @vxacezxcv i agree- i think we should improve the implementation. Are you on linkedin/discord? Would help to know how you're using it

**Comment by ghost** [comment]
fixing this today @vxacezxcv

**Comment by ghost** [comment]
code removed
