### ISSUE TITLE
[Bug]: Fireworks models are missing from `model_prices_and_context_window.json`

### ISSUE THREAD

**Issue by nehiljain** [BerriAI/litellm#4570]
### What happened?

I was trying to use Fireworks https://fireworks.ai/models/fireworks/phi-3-vision-128k-instruct model with litellm but the `litellm.completion_cost` fails because the model is missing from the pricing map

### Twitter / LinkedIn details

@nehiljain

**Comment by ghost** [comment]
looking at it now

It looks like they do pricing similar to together ai (based on model size) - https://fireworks.ai/pricing

**Comment by ghost** [comment]
curious, what're you doing with the completion_cost info? @nehiljain
