### ISSUE TITLE
[Question]: Loading model file throws error

### ISSUE THREAD

**Issue by SerialIterator** [BerriAI/litellm#4573]
### What happened?

I am trying to use a model file to quiet down warning messages and use Repo-map according to [https://aider.chat/docs/config/adv-model-settings.html](https://aider.chat/docs/config/adv-model-settings.html). My model file is 
```
{
    "ollama/deepseek-coder-v2": {
        "max_tokens": 4096,
        "max_input_tokens": 32000,
        "max_output_tokens": 4096,
        "input_cost_per_token": 0.0,
        "output_cost_per_token": 0.0,
        "litellm_provider": "ollama",
        "mode": "chat"
        }
}
```
and I saved it in `.aider.model.metadata.json` at the base of my working directory but it wasn't used. I pointed to it with `aider --model ollama/deepseek-coder-v2 --edit-format diff --model-settings-file .aider.model.metadata.json` and it shows an error that it cannot use it.

I ignored the errors and tested the model and the model appears to prepend filenames with `path/to/` which I want to check if it is a `Repo-map` issue before troubleshooting that. I'm not sure if they are connected.

### Relevant log output

```shell
aider --model ollama/deepseek-coder-v2 --edit-format diff --model-settings-file .aider.model.metadata.json
Error loading aider model settings: Error loading model settings from .aider.model.metadata.json: 
aider.models.ModelSettings() argument after ** must be a mapping, not str
Model ollama/deepseek-coder-v2: Unknown context window size and costs, using sane defaults.
For more info, see: https://aider.chat/docs/llms/warnings.html


Aider v0.42.0
Model: ollama/deepseek-coder-v2 with diff edit format
Git repo: .git with 1 files
Repo-map: disabled
VSCode terminal detected, pretty output has been disabled.
Use /help to see in-chat commands, run with --help to see cmd line args
```

**Comment by ghost** [comment]
Hey @SerialIterator wouldn't a better place for this be aider's github? https://github.com/paul-gauthier/aider


curious what this was though: 
> it shows an error that it cannot use it

**Comment by SerialIterator** [comment]
I'm sorry! I had both pages up for the model settings template and meant to post over there. The error was

'''
Error loading aider model settings: Error loading model settings from .aider.model.metadata.json: 
aider.models.ModelSettings() argument after ** must be a mapping, not str
'''


It's as if the model settings file was not being read in as a key:value pair correctly. 

Sorry for formatting errors. I'm replying on mobile.
