### ISSUE TITLE
[Bug]: fastapi imported but not a dep

### ISSUE THREAD

**Issue by piotrm0** [BerriAI/litellm#458]
### What happened?

Install and import litellm. Get error that fastapi needs to be installed.

**Comment by ghost** [comment]
Hey @piotrm0 let me test to see what's happening

**Comment by ghost** [comment]
fix pushed - try v`0.1.7701`

**Comment by ghost** [comment]
@piotrm0 please reopen issue if that doesn't work for you

**Comment by brauliolomeli** [comment]
works for me now! thank you.

**Comment by ghost** [comment]
@piotrm0 @brauliolomeli how did you guys find us 😄 

Welcome to the [community](https://discord.com/invite/wuPM9dRgDw)
