### ISSUE TITLE
[Feature]: SQLite backend support

### ISSUE THREAD

**Issue by rcarmo** [BerriAI/litellm#4583]
### The Feature

It would be nice to be able to use SQLite instead of Postgres for small deployments

### Motivation, pitch

Setting up and maintaining Postgres seems overkill for low usage or test scenarios, and Prisma supports it out of the box.

**Comment by ghost** [comment]
Hey @rcarmo we've looked into supporting other db's before, and decided against it, as it was hard to maintain and added additional complexity. 

Closing as not planned

**Comment by freehuntx** [comment]
Sqlite is (takes a look at his notes) hard to maintain and complex. Noted.
