### ISSUE TITLE
[Bug]: Drop `parallel_tool_calls` for other provider than OpenAI

### ISSUE THREAD

**Issue by Clad3815** [BerriAI/litellm#4584]
### What happened?

We need to drop this parameter when `drop_params: true`, this work only with OpenAI

**Comment by ghost** [comment]
Hey @Clad3815 fix pushed - https://github.com/BerriAI/litellm/commit/bb905d72439ea7b9147f0a90ea082a4d41d6c141

Can we setup a 1:1 support channel? Would love to improve litellm for you 

[LinkedIn](https://www.linkedin.com/in/krish-d/)
[Discord](https://discord.com/invite/wuPM9dRgDw)
