### ISSUE TITLE
[Feature]: Integration with Arize AI callback / logging

### ISSUE THREAD

**Issue by meetzuber** [BerriAI/litellm#4585]
### The Feature

opentelemetry is already supported Arize also works on opentelemetry. 
I think minor changes will make it work.
https://docs.arize.com/arize/large-language-models/tracing/manual-instrumentation/python

### Motivation, pitch

wanted to arize as logging platform it works on opentelemetry. but unable to integrate with litellm.
I think minor changes will make it work. also increase the number of litellm integrations.

**Comment by ishaan-jaff** [comment]
picking this up
