### ISSUE TITLE
[Bug]: Send PDF in base64 to gemini-1.5-pro

### ISSUE THREAD

**Issue by 04cfb1ed** [BerriAI/litellm#4589]
### What happened?

I would like to send PDF in base 64 to litellm through OpenAI Langchain integration

Currently, I'm using a snippet like this https://github.com/langchain-ai/langchain-google/issues/215#issuecomment-2131242198

I know that is possible to use a gs URI, but with langchain VertexAI integration is possible to use like that
https://github.com/langchain-ai/langchain-google/blob/main/libs/vertexai/langchain_google_vertexai/chat_models.py#L184-L232

I suppose that the provided code enables audio and video too, but I haven't tested yet.

Sample configuration
```yaml
- model_name: gemini-1.5-pro
    litellm_params:
      model: vertex_ai/gemini-1.5-pro
      vertex_project: "os.environ/PROJECT_ID"
      vertex_location: "us-central1"
```

Sample working snippet
````python
import base64
import httpx
from langchain_google_vertexai import ChatVertexAI
from langchain_core.messages import HumanMessage

model = ChatVertexAI(
    model_name="gemini-1.5-pro",
    project="project",
    location="us-central1",
)

pdf_url = (
    "https://dagrs.berkeley.edu/sites/default/files/2020-01/sample.pdf" # Max size 7MB
)
pdf_data = base64.b64encode(httpx.get(pdf_url).content).decode("utf-8")

content = [
    {
        "type": "text",
        "text": "Summary of the document provided",
    },
    {"type": "media", "mime_type": "application/pdf", "data": pdf_data},
]
message = [HumanMessage(content=content)]
response = model.invoke(message)

print(response.content)
print(response.response_metadata)
````

Thanks

### Relevant log output

```shell
RateLimitError: Error code: 429 - {'error': {'message': 'No deployments available for selected model, Try again in 60 seconds. Passed model=gemini-1.5-pro. pre-call-checks=False, allowed_model_region=n/a, cooldown_list=[(\'9e30f58fca7e74245f49287cfcfe2077d11406b3fcf4f379edf3b4123f18b44f\', {\'Exception Received\': \'litellm.InternalServerError: VertexAIException InternalServerError - Image url not in expected format. Example Expected input - "image_url": "data:image/jpeg;base64,{base64_image}". Supported formats - [\\\'image/jpeg\\\', \\\'image/png\\\', \\\'image/gif\\\', \\\'image/webp\\\'] \', \'Status Code\': \'500\'})]', 'type': 'None', 'param': 'None', 'code': 429}}
```

**Comment by ishaan-jaff** [comment]
looking into this 👀

**Comment by ishaan-jaff** [comment]
@04cfb1ed can you share the request you're sending to litellm proxy ?

**Comment by ghost** [comment]
let me test this

**Comment by ghost** [comment]
Hey @04cfb1ed fixed on our end - 

works for VertexAI

GoogleAIStudio raises an internal server error (might be an issue on their end).

**Comment by ghost** [comment]
Can we setup a 1:1 support channel? @04cfb1ed 

Would like to improve litellm for your use-case 

[LinkedIn](https://www.linkedin.com/in/krish-d/)
[Discord](https://discord.com/invite/wuPM9dRgDw) (just 👋 wave on #general, and i'll setup the support channel)
