### ISSUE TITLE
[Feature]: Add langchain + llama index tutorials on docs

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#459]
### The Feature

make it easier for our users to see how to use litellm in those frameworks 

### Motivation, pitch

user feedback

**Comment by alhridoy** [comment]
Hi @krrishdholakia can I pick this?

**Comment by ghost** [comment]
i believe this is now done. 

seeing your comment late @alhridoy sorry. We have a few others marked as 'good first issues' feel free to check them out.
