### ISSUE TITLE
[Bug]: Using `response_format` with proxy fails for ollama

### ISSUE THREAD

**Issue by AlexanderLill** [BerriAI/litellm#4592]
### What happened?

Hi everyone,
I am using litellm as proxy to call a locally running ollama instance.
When calling `/chat/completions` with the `response_format` parameter it fails with the error that key `name` is undefined.

I am using LiteLLM: Current Version = 1.40.25

Here is the code to reproduce:
```sh
curl -X 'POST' \
  'http://$MYURL:$MYPORT/chat/completions' \
  -H 'accept: application/json' \
  -H 'API-Key: sk-$MYTOKEN' \
  -d '{
     "model": "ollama/$MYMODEL",
     "messages": [{"role": "user", "content": "Say \"this is a test\" in JSON!"}],
     "temperature": 0.0,
     "response_format": { "type": "json_object" }
   }'
```

This is the error shown as response:

```
{"error":{"message":"litellm.APIConnectionError: 'name'
Traceback (most recent call last):
  File \"/home/ubuntu/.local/lib/python3.8/site-packages/litellm/main.py\", line 378, in acompletion
    response = await init_response
  File \"/home/ubuntu/.local/lib/python3.8/site-packages/litellm/llms/ollama.py\", line 487, in ollama_acompletion
    raise e
  File \"/home/ubuntu/.local/lib/python3.8/site-packages/litellm/llms/ollama.py\", line 454, in ollama_acompletion
    \"name\": function_call[\"name\"],
KeyError: 'name'
","type":null,"param":null,"code":500}}%
```

When using `ollama_chat`, the error and response are very similar:
```
{"error":{"message":"litellm.APIConnectionError: 'name'
Traceback (most recent call last):
  File \"/home/ubuntu/.local/lib/python3.8/site-packages/litellm/main.py\", line 378, in acompletion
    response = await init_response
  File \"/home/ubuntu/.local/lib/python3.8/site-packages/litellm/llms/ollama_chat.py\", line 539, in ollama_acompletion
    raise e
  File \"/home/ubuntu/.local/lib/python3.8/site-packages/litellm/llms/ollama_chat.py\", line 504, in ollama_acompletion
    \"name\": function_call[\"name\"],
KeyError: 'name'
","type":null,"param":null,"code":500}}%
```

**Comment by ghost** [comment]
hey @AlexanderLill do you see this issue with `ollama_chat`?

**Comment by AlexanderLill** [comment]
Dear @krrishdholakia, thank you very much for your reply! I was not aware of `ollama_chat`, and using it solves *other* issues I had. However, unfortunately for the `response_format` parameter, I receive the same error message:

```
{"error":{"message":"litellm.APIConnectionError: 'name'
Traceback (most recent call last):
  File \"/home/ubuntu/.local/lib/python3.8/site-packages/litellm/main.py\", line 378, in acompletion
    response = await init_response
  File \"/home/ubuntu/.local/lib/python3.8/site-packages/litellm/llms/ollama_chat.py\", line 539, in ollama_acompletion
    raise e
  File \"/home/ubuntu/.local/lib/python3.8/site-packages/litellm/llms/ollama_chat.py\", line 504, in ollama_acompletion
    \"name\": function_call[\"name\"],
KeyError: 'name'
","type":null,"param":null,"code":500}}%
```

I checked the documentation why I was not aware of the recommended `ollama_chat` alternative, and found that there is only a (red) note at the beginning of the ollama doc, but from 30 shown examples, only one uses the `ollama_chat`. It might be helpful for future users to maybe have more examples (or at leat the first one) use the `ollama_chat` model prefix :)

**Comment by ericmjl** [comment]
I'm facing a similar issue here.

Within LlamaBot, if we try to use `litellm==1.35.38`, because [this line wasn't present](https://github.com/BerriAI/litellm/pull/3469/files#diff-f1fc2b8b06c0fa1a363c360b97b365d5629f0d3402d69d2554a1f7795f1f34b0R276) before, LlamaBot's `json_mode=True` did not fail. A reproducible example if you use `llamabot==0.4.6` (which has no upper-bound pin on litellm) looks like this:

```python
from llamabot import SimpleBot

bot = SimpleBot("You are a bot proficient at returning JSON.", model_name="ollama/mistral", json_mode=True)
bot("What is the weather like today? Return in JSON with the following structure: {'location': 'City Name', 'temperature': 'Temperature in Celsius', 'description': 'Weather Description'}")
```

The output that we get is like this:


<details>
<pre>
<code>
{
	"name": "KeyError",
	"message": "'name'",
	"stack": "---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[1], line 4
      1 from llamabot import SimpleBot
      3 bot = SimpleBot(\"You are a bot proficient at returning JSON.\", model_name=\"ollama/mistral\", json_mode=True)
----> 4 bot(\"What is the weather like today? Return in JSON with the following structure: {'location': 'City Name', 'temperature': 'Temperature in Celsius', 'description': 'Weather Description'}\")

File ~/github/software/llamabot/llamabot/bot/simplebot.py:73, in SimpleBot.__call__(self, human_message)
     71 match self.stream_target:
     72     case \"stdout\":
---> 73         return self.stream_stdout(messages)
     74     case \"panel\":
     75         return self.stream_panel(messages)

File ~/github/software/llamabot/llamabot/bot/simplebot.py:87, in SimpleBot.stream_stdout(self, messages)
     85 response = _make_response(self, messages)
     86 message = \"\"
---> 87 for chunk in response:
     88     delta = chunk.choices[0].delta[\"content\"]
     89     if delta is not None:

File ~/anaconda/envs/llamabot/lib/python3.11/site-packages/litellm/llms/ollama.py:368, in ollama_completion_stream(url, data, logging_obj)
    366             yield transformed_chunk
    367 except Exception as e:
--> 368     raise e

File ~/anaconda/envs/llamabot/lib/python3.11/site-packages/litellm/llms/ollama.py:353, in ollama_completion_stream(url, data, logging_obj)
    340 response_content = \"\".join(
    341     chunk.choices[0].delta.content
    342     for chunk in chain([first_chunk], streamwrapper)
    343     if chunk.choices[0].delta.content
    344 )
    346 function_call = json.loads(response_content)
    347 delta = litellm.utils.Delta(
    348     content=None,
    349     tool_calls=[
    350         {
    351             \"id\": f\"call_{str(uuid.uuid4())}\",
    352             \"function\": {
--> 353                 \"name\": function_call[\"name\"],
    354                 \"arguments\": json.dumps(function_call[\"arguments\"]),
    355             },
    356             \"type\": \"function\",
    357         }
    358     ],
    359 )
    360 model_response = first_chunk
    361 model_response.choices[0].delta = delta  # type: ignore

KeyError: 'name'"
}
</code>
</pre>
</details>

However, once we pin the LiteLLM version to `litellm==1.35.38`, we get the following output:

```text
{
  "location": "New York",
  "temperature": "20",
  "description": "Sunny"
}
```

I'm not 100% sure but it may be the case that these changes impose too strong of an assumption on the presence of function calls when using JSON requests. (I am inferring this point from this line comment (https://github.com/BerriAI/litellm/pull/3469/files#diff-f1fc2b8b06c0fa1a363c360b97b365d5629f0d3402d69d2554a1f7795f1f34b0R260).) Some of us would like to just have JSON returned without assuming a function call is required.

**Comment by Umpire2018** [comment]
I'm facing a similar issue here.

```python
import litellm
litellm.set_verbose=True

response = litellm.completion(
    model="ollama_chat/phi3:3.8b-mini-128k-instruct-q8_0", 
    api_base="http://localhost:11434",
    messages=[{ "content": "respond in 20 words. who are you?","role": "user"}], 
    format = "json"
)

print(response)
```

Output:

```python
Request to litellm:
litellm.completion(model='ollama_chat/phi3:3.8b-mini-128k-instruct-q8_0 ', api_base='http://localhost:11434', messages=[{'content': 'respond in 20 words. who are you?', 'role': 'user'}], format='json')


08:06:05 - LiteLLM:WARNING: utils.py:343 - `litellm.set_verbose` is deprecated. Please set `os.environ['LITELLM_LOG'] = 'DEBUG'` for debug logs.
SYNC kwargs[caching]: False; litellm.cache: None; kwargs.get('cache')['no-cache']: False
Final returned optional params: {'format': 'json'}


POST Request Sent from LiteLLM:
curl -X POST \
http://localhost:11434/api/chat \
-d '{'model': 'phi3:3.8b-mini-128k-instruct-q8_0 ', 'messages': [{'content': 'respond in 20 words. who are you?', 'role': 'user'}], 'options': {}, 'stream': False, 'format': 'json'}'


RAW RESPONSE:
{"model":"phi3:3.8b-mini-128k-instruct-q8_0 ","created_at":"2024-07-14T08:06:15.3792689Z","message":{"role":"assistant","content":"{\"response\": \"I'm an AI digital assistant designed to help answer questions and perform tasks.\"}\n\n\n"},"done_reason":"stop","done":true,"prompt_eval_count":14,"prompt_eval_duration":26142000,"eval_count":26,"eval_duration":343729000}



Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Logging Details: logger_fn - None | callable(logger_fn) - False
Traceback (most recent call last):
  File "./.cache/pypoetry/virtualenvs/agentless-VIuzEMka-py3.11/lib/python3.11/site-packages/litellm/main.py", line 2448, in completion
    generator = ollama_chat.get_ollama_response(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./.cache/pypoetry/virtualenvs/agentless-VIuzEMka-py3.11/lib/python3.11/site-packages/litellm/llms/ollama_chat.py", line 309, in get_ollama_response
    "name": function_call["name"],
            ~~~~~~~~~~~~~^^^^^^^^
KeyError: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./.cache/pypoetry/virtualenvs/agentless-VIuzEMka-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 1003, in wrapper
    raise e
  File "./.cache/pypoetry/virtualenvs/agentless-VIuzEMka-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 883, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./.cache/pypoetry/virtualenvs/agentless-VIuzEMka-py3.11/lib/python3.11/site-packages/litellm/main.py", line 2642, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "./.cache/pypoetry/virtualenvs/agentless-VIuzEMka-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 7838, in exception_type
    raise e
  File "./.cache/pypoetry/virtualenvs/agentless-VIuzEMka-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 7811, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: litellm.APIConnectionError: 'name'
Traceback (most recent call last):
  File "./.cache/pypoetry/virtualenvs/agentless-VIuzEMka-py3.11/lib/python3.11/site-packages/litellm/main.py", line 2448, in completion
    generator = ollama_chat.get_ollama_response(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./.cache/pypoetry/virtualenvs/agentless-VIuzEMka-py3.11/lib/python3.11/site-packages/litellm/llms/ollama_chat.py", line 309, in get_ollama_response
    "name": function_call["name"],
            ~~~~~~~~~~~~~^^^^^^^^
KeyError: 'name'
```

**Comment by ericmjl** [comment]
@krrishdholakia and @ishaan-jaff just wondering if this issue has caught your attention by any chance? It'd be nice to fix this one, as it'd allow me to unpin the version of LiteLLM that we depend on, allowing LlamaBot to track the innovations coming into LiteLLM.

**Comment by ghost** [comment]
hey @ericmjl missed this - i'll investigate this today - thanks for the bump

**Comment by ghost** [comment]
This seems fixed on latest @ericmjl @AlexanderLill 

Just ran the same curl with ollama model 
<img width="1124" alt="Screenshot 2024-07-24 at 7 21 59 PM" src="https://github.com/user-attachments/assets/d3ea95f5-fd3e-4075-a686-99f98624289d">

**Comment by AlexanderLill** [comment]
Can confirm this works in version `1.42.1` using `ollama_chat`, thank you! :)
