### ISSUE TITLE
[Bug]: RateLimitErro in Audio transcription with response_format="srt"

### ISSUE THREAD

**Issue by tzsombor95** [BerriAI/litellm#4595]
### What happened?

When I add response_format="srt" (or "vtt") to the transcription parameters, I got immediately RateLimitError from litellm proxy. Without response_format, its working without problem.

client = openai.OpenAI(
    api_key="sk-1234",
    base_url="http://0.0.0.0:8000"
)

audio_file = open("speech.mp3", "rb")
transcript = client.audio.transcriptions.create(
  model="whisper",
  file=audio_file,
  response_format="srt"
)

### Relevant log output

```shell
Exception: Error code: 500 - {'error': {'message': 'litellm.RateLimitError: AzureException RateLimitError - Requests to the Audio_Transcriptions Operation under Azure OpenAI API version 2024-02-01 have exceeded call rate limit of your current OpenAI S0 pricing tier. Please retry after 33 seconds. Please go here: https://aka.ms/oai/quotaincrease if you would like to further increase the default rate limit. LiteLLM Retried: 1 times, LiteLLM Max Retries: 2', 'type': 'None', 'param': 'None', 'code': 500}}
```

**Comment by ishaan-jaff** [comment]
@tzsombor95 this looks like you exceeded your Azure OpenAI quota. Does not look litellm related 

```
 Requests to the Audio_Transcriptions Operation under Azure OpenAI API version 2024-02-01 have exceeded call rate limit of your current OpenAI S0 pricing tier
```

**Comment by tzsombor95** [comment]
@ishaan-jaff  No. Its a dedicated model deployment. If i delete the response_format i got response multiple times without problem. Or if i call my whisper model directly with AzureChatOpenai, its also working. It doesn't work only if i use litellm and with response_format parameter together.

**Comment by ghost** [comment]
trying to repro

**Comment by ghost** [comment]
looks like openai is inconsistent in the response format. 

for response_format=json it's a pydantic object, in other cases it's a string

**Comment by tzsombor95** [comment]
@krrishdholakia And what's the solution or can you make an update in the next release? I really need the srt format in my use case.

**Comment by ghost** [comment]
yes - working on it now

**Comment by ghost** [comment]
Live soon in v`1.41.12`

**Comment by ghost** [comment]
<img width="1223" alt="Screenshot 2024-07-08 at 9 11 25 AM" src="https://github.com/BerriAI/litellm/assets/17561003/410ec47c-0cd4-4e7a-a66d-08b4750ea1c0">

**Comment by ghost** [comment]
@tzsombor95 dm'ed on linkedin as well, to setup the support channel

**Comment by tzsombor95** [comment]
Thanks your quick solution!
