### ISSUE TITLE
[Bug]: Can't change api_base per model when using completion_with_fallbacks, litellm version 1.41.11

### ISSUE THREAD

**Issue by miquelferrarons** [BerriAI/litellm#4597]
### What happened?

For testing purposes, I'm changing api_base parameter in the fallbacks section of the completion call. But whatever I pass on api_base, it is not used. The real api_base from the provider is used instead. This makes my tests fail because they contact the real provider without the credentials. Similarly, if I were to implement a proxy, this woudn't work.

It seems to work fine if you just define litellm.base_url, but I need two different base_urls, one per provider, so this will not work.

```
from litellm import completion

completion(
    model='model-x',
    fallbacks={
        {'model':'model-x', 'api_base':'http://localhost/model-x', 'api_key':'api_key_1'},
        {'model':'model-y', 'api_base':'http://localhost/model-y', 'api_key':'api_key_2'} 
    },
    ...
)

```
In my case, I'm using Mixtral-8x7B instruct with openrouter as a primary model, and the same model with deepinfra as a fallback.

"openrouter/mistralai/mixtral-8x7b-instruct"
"deepinfra/mistralai/Mixtral-8x7B-Instruct-v0.1"

While debugging, I found that the issue appears to be here, when 'api_base' is being correctly passed to the function 'get_llm_provider' but its value it's overwritten for deepinfra:

https://github.com/BerriAI/litellm/blob/v1.41.11/litellm/utils.py#L4146

**Comment by miquelferrarons** [comment]
I'm providing a small script to reproduce the issue.

Note that if you use 'openrouter' as a fallback model, it does work. The bug happens for deepinfra, and judging from the codebase, I guess it will also happen for any model in this if-elif block https://github.com/BerriAI/litellm/blob/v1.41.11/litellm/utils.py#L4136.

```
import litellm
litellm.set_verbose = True

import json
from pytest_httpserver import HTTPServer

def format_mock_response(mock_response):
    return json.dumps({"choices": [{"message": {"role": "assistant","content": mock_response},"logprobs": None,"finish_reason": "stop","index": 0}]})

fallback_model_response = 'Fallback model response.'

http_server = HTTPServer()
http_server.start()
http_server.expect_request(uri="/model_0/chat/completions", method="POST").respond_with_data(
    "Service unavailable", status=503, content_type="text/plain"
)
http_server.expect_request(uri="/model_1/chat/completions", method="POST").respond_with_data(
    format_mock_response(fallback_model_response)
)

litellm.base_url = http_server.url_for("/model_0/")
response = litellm.completion(
    model="openrouter/mistralai/mixtral-8x7b-instruct",
    fallbacks=[
        {
            "model": "openrouter/mistralai/mixtral-8x7b-instruct",
            "api_base": http_server.url_for("/model_0/"),
            "api_key": "api_key",
        },
        {
            # "model": "openrouter/mistralai/mixtral-8x7b-instruct",
            "model": "deepinfra/mistralai/Mixtral-8x7B-Instruct-v0.1",
            "api_base": http_server.url_for("/model_1/"),
            "api_key": "api_key",
        },
    ],
    messages=[
        {
            "content": "This is a test prompt.",
            "role": "user",
        }
    ],
)
try:
    assert response["choices"][0]["message"]["content"] == fallback_model_response, "The fallback model was not used."
    print("Fallback model used as expected!")
finally:
    http_server.stop()
```

**Comment by ghost** [comment]
Hey @miquelferrarons this should be fixed now. Dynamic api bases weren't being set for openai compatible endpoints

**Comment by ghost** [comment]
Closing as this should be fixed on latest. Please reopen if the issue persists.
