### ISSUE TITLE
[Bug]: don't hardcode hf models to hf inference endpoints as provider

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#460]
### What happened?

hf models can be deployed on multiple providers (together ai, deepinfra, etc.)

don't assume when a user passes in a hf model (e.g. meta-llama) they're trying to call huggingface inference endpoints

### Relevant log output

```shell
seen on user issues
```

**Comment by ishaan-jaff** [comment]
is the fix here to only run the HF branch when `custom_llm_provider == "huggingface" `

**Comment by ghost** [comment]
yup - this is now fixed.
