### ISSUE TITLE
[Bug/Feature]: Langfuse should be sent `input_cost`, `output_cost`, and `total_cost`

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#4604]
### What happened?

When using the Anthropic API, requests that error out should be have a $0 cost. Right now Langfuse is incorrectly billing as if it didn't error out, because LiteLLM isn't telling Langfuse what the actual cost was, only the tokens.

The way to solve this is to use  `input_cost`, `output_cost`, and `total_cost` in `langfuse.py`.

https://langfuse.com/docs/model-usage-and-cost#ingest

<img width="1117" alt="image" src="https://github.com/BerriAI/litellm/assets/7232674/2a726f74-4982-469b-9e26-9482aae1add3">

<img width="461" alt="image" src="https://github.com/BerriAI/litellm/assets/7232674/c49be469-6224-4d7c-9394-05742158578e">

https://discord.com/channels/1072196207201501266/1114305545478877377/1259564975845015572

### Twitter / LinkedIn details

https://twitter.com/DaveManouchehri

**Comment by Manouchehri** [comment]
Note: I have *not* confirmed at all if this is the case for Amazon Bedrock or Vertex AI, so do *not* globally make this a thing for all providers (unless there's confirmation like this from a specific provider).

**Comment by ghost** [comment]
@Manouchehri can you share what the `response_cost` value is in your metadata? I'm surprised a response_cost is logged from litellm on error

**Comment by Manouchehri** [comment]
<img width="1136" alt="image" src="https://github.com/BerriAI/litellm/assets/7232674/84f2557d-4e5f-4dbd-a769-b0be176b544c">

**Comment by ghost** [comment]
@Manouchehri i see `litellm_response_cost` as null 

this makes me think this is a langfuse calculation, not litellm 

let me know if you see it differently

**Comment by Manouchehri** [comment]
I thought LiteLLM provided Langfuse with an override of the costs?

**Comment by Manouchehri** [comment]
https://langfuse.com/docs/model-usage-and-cost#ingest

We can provide it this way.

**Comment by ghost** [comment]
we do provide the cost @Manouchehri 

it seems like they're ignoring it - https://github.com/BerriAI/litellm/blob/cb52c59481ddf604ffee5b26d5877873f3c589ed/litellm/integrations/langfuse.py#L445

https://github.com/BerriAI/litellm/blob/cb52c59481ddf604ffee5b26d5877873f3c589ed/litellm/integrations/langfuse.py#L505

**Comment by Manouchehri** [comment]
I think you need to provide the input and output price too?

**Comment by ghost** [comment]
can you confirm if just setting response_cost to 0 in `langfuse.py` fixes the problem? 

i suspect if it's None, then it uses the default calc

**Comment by Manouchehri** [comment]
I don't think it worked doing just that.

![image](https://github.com/BerriAI/litellm/assets/7232674/a3a96cf0-8fcd-4558-ad24-e6eeb0f4b89f)
