### ISSUE TITLE
[Bug]: LiteLLM_UserTable doesn't create new user when `/team/member_add` is called

### ISSUE THREAD

**Issue by andresrguzman** [BerriAI/litellm#4608]
### What happened?

when `/team/member_add` is called it tries to update the `LiteLLM_UserTable` however if a user doesn't exist it doesn't automatically creates a new row (in the same way the user is created when `/team/new` is called).

### Relevant log output

None

**Comment by andresrguzman** [comment]
For this one case I think the fix is just to:

from 
```python
await prisma_client.db.litellm_usertable.update(
    where={"user_id": new_member.user_id},
    data={"teams": {"push": [team_id]}},
)
```
to 
```python
await prisma_client.db.litellm_usertable.upsert(
    where={"user_id": new_member.user_id},
    data={
        "update": {
            "teams": {"push": [team_id]}
        },
        "create": {
            "user_id": new_member.user_id, 
            "teams": [team_id]
        }
    },
)
```

https://github.com/BerriAI/litellm/blob/cb52c59481ddf604ffee5b26d5877873f3c589ed/litellm/proxy/management_helpers/utils.py#L30-L35

**Comment by ghost** [comment]
Hey @andresrguzman pr looks good. 

Can we setup a 1:1 support channel? Would like to improve litellm for your use-case 

[LinkedIn](https://www.linkedin.com/in/krish-d/)
[Discord](https://discord.com/invite/wuPM9dRgDw) (just 👋 wave on #general)

**Comment by andresrguzman** [comment]
sounds good @krrishdholakia I'll ping you tomorrow morning

**Comment by ishaan-jaff** [comment]
hi @andresrguzman wanted to follow up on this

> Can we setup a 1:1 support channel? Would like to improve litellm for your use-case

**Comment by andresrguzman** [comment]
Hello. I reached out on [discord](https://discord.com/channels/1123360753068540065/1135612850749067324/1260269658699989132)
