### ISSUE TITLE
[Bug]: Prometheus monitors the number of requests collected in Azure OpenAI

### ISSUE THREAD

**Issue by Huyueeer** [BerriAI/litellm#4617]
### What happened?

My configuration is this:
  - model_name: gpt-35-turbo-16k
    litellm_params:
      model: azure/bdcgpt3516
      api_base: https://XXXXXXXXXX.com/
      api_key: XXXXXXXXXXXXXXXXXXXXXXX
      api_version: "2024-02-15-preview"
      input_cost_per_token: 0.000003
      output_cost_per_token: 0.000004

This configuration is actually one model, not two, and the number of requests does not match.

![image](https://github.com/BerriAI/litellm/assets/40758588/b79363b9-da17-4fe0-b46a-4e038f1f41e7)
![image](https://github.com/BerriAI/litellm/assets/40758588/97dd8f12-3ad6-44da-b13f-c40e44a02b32)

In fact, I only made 105 requests, but in the monitoring, I saw that these two models (actually one model) made many requests respectively, but there was no connection between them.

**Comment by ghost** [comment]
@Huyueeer how do i repro this?

**Comment by Huyueeer** [comment]
> @Huyueeer how do i repro this?

@krrishdholakia Use Azure to build an openai model. The deployment name and model name are inconsistent. Use litellm-litellm:v1.41.11.dev1 docker deployment, enable prometheus monitoring, copy https://github.com/BerriAI/litellm/tree/main/cookbook/litellm_proxy_server/grafana_dashboard, enable monitoring in grafana, and concurrently request the Azure openai model just deployed, and you can see it.

**Comment by Huyueeer** [comment]
I wonder if it has something to do with the `sum by (model) (increase(litellm_requests_metric_total[5m]))` statement in grafana. I am not very familiar with this statement.
