### ISSUE TITLE
[Bug]: Not able to pass image in microsoft/Phi-3-vision-128k-instruct 

### ISSUE THREAD

**Issue by tusharraskar** [BerriAI/litellm#4620]
### What happened?

I hosted vllm on the ec2 instance. How can I pass the image to the model?

prompt_1 = "Give me subject from given image"
image = Image.open("invoice_data_images/Screenshot 2024-05-02 160946_page_1.png")
prompt = f"<|user|>\n<|image|>\n{prompt_1}<|end|>\n<|assistant|>\n"

response = litellm.completion(
    model="openai/microsoft/Phi-3-vision-128k-instruct",
    api_key="sk-1234",
    api_base="http://103.12.2.6:8888/v1",
    messages=[
        {
            "role": "user",
            "content": prompt,
        }
    ],
)
print(response['choices'][0]['message']['content'])

### Relevant log output

```shell
Sorry, but I am not able to view images. I am just a text-based program.
```

**Comment by ghost** [comment]
that looks like it's being sent to the model, and phi is saying no. 

this doesn't look like a litellm issue. Let me know if there's anything we can do here.
