### ISSUE TITLE
[Feature]: Support Vertex Multimodal embeddings

### ISSUE THREAD

**Issue by 04cfb1ed** [BerriAI/litellm#4622]
### The Feature

Vertex Multimodal embeddings allows sending image, text and video

It can be used through REST endpoint or Vertex AI SDK in Python

https://cloud.google.com/vertex-ai/generative-ai/docs/embeddings/get-multimodal-embeddings#aiplatform_sdk_text_image_embedding-drest

Sample code from reference
```python
import vertexai
from vertexai.vision_models import Image, MultiModalEmbeddingModel

# TODO(developer): Update values for project_id, image_path & contextual_text
vertexai.init(project=project_id, location="us-central1")

model = MultiModalEmbeddingModel.from_pretrained("multimodalembedding")
image = Image.load_from_file(image_path)

embeddings = model.get_embeddings(
    image=image,
    contextual_text=contextual_text,
    dimension=dimension,
)
print(f"Image Embedding: {embeddings.image_embedding}")
print(f"Text Embedding: {embeddings.text_embedding}")
```

### Motivation, pitch

Multimodal embeddings enable multimodal processing in RAG combining video, audio or images

**Comment by ghost** [comment]
That's interesting. Happy to add support for this.

**Comment by ghost** [comment]
@04cfb1ed can we setup a 1:1 support channel? Noticed you'd had a couple issues, want to prioritize correctly for your use-case

[LinkedIn](https://www.linkedin.com/in/krish-d/)
[Discord](https://discord.com/invite/wuPM9dRgDw) (just 👋 wave on #general and i'll setup a channel)
