### ISSUE TITLE
[Bug]: Exception occured - model info for model=textembedding-gecko does not have 'input_cost_per_character'-pricing

### ISSUE THREAD

**Issue by MitchelHsu** [BerriAI/litellm#4630]
### What happened?

I'm calling `litellm.embedding` with `model=textembedding-gecko` (vertex ai) which triggers call `input_cost_per_charater`. However, the `textembedding-gecko` model info does not support character based cost.

https://github.com/BerriAI/litellm/blob/cab057da4ade0c6cfce265bd0d29b3f7fa961329/litellm/model_prices_and_context_window_backup.json#L1517

Thanks!

### Relevant log output

```shell
google.py:133 - litellm.litellm_core_utils.llm_cost_calc.google.cost_per_character(): Exception occured - model info for model=textembedding-gecko does not have 'output_cost_per_character'-pricing
```

**Comment by ghost** [comment]
is this calling calls to fail? @MitchelHsu or just showing up in console logs

**Comment by MitchelHsu** [comment]
Just showing up in console logs, but if making multiple calls, the exceptions will flood the logs.

**Comment by ghost** [comment]
makes sense - picking this up today

**Comment by ghost** [comment]
Hey @MitchelHsu push fixed - https://github.com/BerriAI/litellm/commit/2163434ff3bf2e482d6dca31d0673c191976a935

this will be live later today in v`1.41.16`+

Let me know if this solves your problem

**Comment by MitchelHsu** [comment]
Hey @krrishdholakia, I think the problem is fixed now. Thanks!
