### ISSUE TITLE
Can a secondary api be added?

### ISSUE THREAD

**Issue by DavidKotykOfficial** [BerriAI/litellm#465]
Running GPT-4 to switch folders is expensive, can a secondary api be integrated for switching folders?

**Comment by ishaan-jaff** [comment]
Can you elaborate on this ? 

Do you want to send completion calls to a cheaper model

**Comment by ghost** [comment]
Hey @DavidKotykOfficial do you want to do it as a fallback? if that errors out 

if so - https://docs.litellm.ai/docs/completion/reliable_completions#switch-modelsapi-keysapi-bases

If not - can you elaborate on the use-case further?

**Comment by DavidKotykOfficial** [comment]
I am trying to build projects with gpt4, just an option to put a smaller model in to switch folders while working would save on costs (or a local model), but this option would also complicate the software a lot so maybe not a good idea.

**Comment by ishaan-jaff** [comment]
can you help me understand what interface you're looking for ?

 (Here's what I understood)
```python
response = litellm.completion(models=["gpt-4", "ollama/llama2"], messages=messages)
```

**Comment by DavidKotykOfficial** [comment]
Honestly, I don't know much about how the API interface works. Thus, if it disrupts the conversation and loses context during a project, that isn't ideal. I appreciate having GPT-4 make complex decisions and code. However, I feel like switching folders might be overkill for GPT-4. It would be more efficient if such tasks could be performed by a local model to save on costs

**Comment by DavidKotykOfficial** [comment]
But when Open Interpreter was first released, the AI consistently attempted to run Windows commands on Mac and vice versa. If this issue resurfaces, I wouldn't mind incurring a higher cost to utilize GPT-4 for all tasks.

**Comment by ghost** [comment]
closing as this sounds like an open interpreter idea - @KillianLucas 

but @DavidKotykOfficial please re-open in case there's something litellm might be able to do to help here
