### ISSUE TITLE
[Bug]: Completions response no longer matches OpenAI format because `created` field has changed to decimal

### ISSUE THREAD

**Issue by alexvanolst** [BerriAI/litellm#4654]
### What happened?

I recently upgraded to `v1.41.15` from `main-v1.41.2-stable` and some OpenAI client libraries no longer can parse responses.

This is because the `created` field no longer [exactly matches the openai response format ](https://platform.openai.com/docs/guides/text-generation/chat-completions-response-format)

The change is in the `created` field. 

Output on `main-v1.41.2-stable`:

```
{
    "id": "chatcmpl-ddc88fbd-9b9f-43da-852e-c68d83fc5dbc",
    "choices": [
        {
            "finish_reason": "stop",
            "index": 0,
            "message": {
                "content": "Some content",
                "role": "assistant"
            }
        }
    ],
    "created": 1720688079,
    "model": "meta-llama/llama-3-70b-instruct",
    "object": "chat.completion",
    "system_fingerprint": null,
    "usage": {
        "prompt_tokens": 26,
        "completion_tokens": 36,
        "total_tokens": 62
    },
    "finish_reason": "eos_token"
}
```
has changed to 
```
{
    "id": "chatcmpl-6dba1160-f619-42af-aa19-86c84604808a",
    "choices": [
        {
            "finish_reason": "stop",
            "index": 0,
            "message": {
                "content": "Some content",
                "role": "assistant"
            }
        }
    ],
    "created": 1720687853.935,
    "model": "meta-llama/llama-3-70b-instruct",
    "object": "chat.completion",
    "system_fingerprint": null,
    "usage": {
        "prompt_tokens": 26,
        "completion_tokens": 36,
        "total_tokens": 62
    },
    "finish_reason": "eos_token"
}
```

This difference (i.e. ` "created": 1720687853.935` vs ` "created": 1720688079`) breaks some libraries that expect the number to be an integer e.g. https://crates.io/crates/openai

I've only tested this on the following config:

```
  - model_name: llama-3-70b
    litellm_params:
      model: watsonx/meta-llama/llama-3-70b-instruct
      api_key: "os.environ/WATSONX_API_KEY"
```

So I'm not 100% sure whether this is watsonx related, or a general issue

**Comment by Clad3815** [comment]
The version `1.41.15` > `1.41.2-stable`, you downgrade

**Comment by alexvanolst** [comment]
No, I went from 1.41.2 up to 1.41.15, and the issue occurs now in 1.41.15 which is the newest version according to the releases on github.

**Comment by ghost** [comment]
thanks for this @alexvanolst i'll look into it 

we should also have stronger parsing checks to make sure if a float is passed in, it's still converted to int

**Comment by ghost** [comment]
@alexvanolst  dm'ed on linkedin to setup a 1:1 support channel as well

**Comment by ghost** [comment]
This was specific to the ibm watsonx implementation. 

The pr bypassed linting checks (created is of type int) by setting the pydantic obj as a json item 

this commit - https://github.com/BerriAI/litellm/commit/8fa2cf15eee0a8b8c062960edae2aa3716b29091, 

- resets the check to use the pydantic set `response_obj.created = ..` vs. `response_obj["created"]` 
- converts the timestamp to int (prev. float)
- removes the ability to set our pydantic objects as json, to prevent this from happening in the future 

this fixes the issue
