### ISSUE TITLE
[Bug]: Deepifra + instructor error (no support for tool_choice)

### ISSUE THREAD

**Issue by agamm** [BerriAI/litellm#4655]
### What happened?

A bug happened when using deepifra.
> litellm.exceptions.BadRequestError: litellm.BadRequestError: DeepinfraException - Deepinfra doesn't support tool_choice={'type': 'function', 'function': {'name': 'AnswerWithSource'}}. To drop unsupported deepinfra params from the call, set `litellm.drop_params = True`

using with [instructor](https://github.com/jxnl/instructor).

### Relevant log output

```shell
https://github.com/BerriAI/litellm/issues/4255#issuecomment-2220641859
```

### Twitter / LinkedIn details

https://linkedin.com/in/agamm

**Comment by ghost** [comment]
hey @agamm deepinfra doesn't support json objects as tool choice params - 
<img width="990" alt="Screenshot 2024-07-11 at 9 05 07 AM" src="https://github.com/BerriAI/litellm/assets/17561003/4b77856f-2b53-4622-bd16-e9b14d27f29c">


https://deepinfra.com/docs/advanced/function_calling

**Comment by ghost** [comment]
you can drop the tool_choice param if you'd like 

```python
litellm.drop_params = True
```

**Comment by ghost** [comment]
what would you want us to do here? @agamm
