### ISSUE TITLE
[Feature]: `/models` response should include model mode

### ISSUE THREAD

**Issue by krrishh-org** [BerriAI/litellm#4657]
### The Feature

`/models` API currently returns all models configured in the proxy. 
Few of those models can be used with `/chat/completions` API, few can be used with `/embeddings` API etc.
 
It will be better if the response of `/models` includes model mode so that the compatibility can be mapped easily.

### Motivation, pitch

We have proxied lots of LLMs and Embedding models running on different providers using litellm proxy. It becomes difficult to filter out non-chat models from the `/models` response.

**Comment by ghost** [comment]
hey @krrishh-org use `/model/info` for this. 

The `/models` matches the openai spec.

**Comment by ghost** [comment]
Where in our docs should we have added this @krrishh-org 


updated here - https://docs.litellm.ai/docs/proxy/model_management#get-model-information
