### ISSUE TITLE
[Feature]: Token counting for function calling and image requests for OpenAI

### ISSUE THREAD

**Issue by pamelafox** [BerriAI/litellm#4664]
### The Feature

I saw that you have some token counting support. Does that include logic for function calling and image requests to gpt models? I have implemented that in https://github.com/pamelafox/openai-messages-token-helper/tree/main but am looking to see if other packages also support it. 

### Motivation, pitch

This would allow me to use litellm and move away from my own packages.

### Twitter / LinkedIn details

pamelafox

**Comment by ghost** [comment]
Hey @pamelafox yes, we cover both - https://github.com/BerriAI/litellm/blob/88eb25da5c536ef3f95759acfa1db84a7b260c86/litellm/utils.py#L1627


Does this solve your problem?

**Comment by pamelafox** [comment]
Ah, I see the image_url, thanks! I don't see the code for function calling computation, but maybe you figured out a different way to do it? Trying to find your equivalent of-
https://github.com/pamelafox/openai-messages-token-helper/blob/main/src/openai_messages_token_helper/function_format.py#L4

**Comment by ghost** [comment]
Here - https://github.com/BerriAI/litellm/blob/88eb25da5c536ef3f95759acfa1db84a7b260c86/litellm/utils.py#L1828

We currently just extract arguments - your implementation looks really good. 

Would you be open to making a pr to help us improve here?

**Comment by pamelafox** [comment]
Sure, I can send a PR

**Comment by ghost** [comment]
Great, here's the relevant tests - https://github.com/BerriAI/litellm/blob/fd743aaefd23ae509d8ca64b0c232d25fe3e39ee/litellm/tests/test_token_counter.py#L26

**Comment by pamelafox** [comment]
PR sent!
