### ISSUE TITLE
[Feature]: Move from requests to aiohttp 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#467]
### The Feature

- if you do multiple threads with the requests library → the only time you can do multiple requests on an async io op
- async io does this more efficiently at the os level → registers handlers at the socket event instead of polling
- when you run 1k+ calls, requests library gets p slow but async io is really useful b/c it’s built for this

### Motivation, pitch

feedback from dev that chose not to use litellm

**Comment by ghost** [comment]
cc: @phlogisticfugu thanks for this

**Comment by ghost** [comment]
Azure + Openai now support aiohttp calling - https://github.com/BerriAI/litellm/commit/86ef2a02f7c9177c175dce58ba55c015674127d6

This requires no changes on the client interface, and flow will work when someone uses acompletion.

**Comment by ishaan-jaff** [comment]
we load test the litellm router for this scenario, our current implementation handles 1k+ requests/ second 

Docs on using litellm router: https://docs.litellm.ai/docs/routing
