### ISSUE TITLE
[Feature]: LiteLLM doesn't support Redis sentinel !!!

### ISSUE THREAD

**Issue by cheng92hao** [BerriAI/litellm#4674]
### What happened?

A bug happened!
LiteLLM doesn't support Redis sentinel !!!

**Comment by acuciureanu** [comment]
This can't be a bug if it doesn't support Redis Sentinel. Isn't this more like a feature request?

Also, this is a dup of #4381

**Comment by ghost** [comment]
Thanks @acuciureanu closing as Duplicate of #4381
