### ISSUE TITLE
[Bug]: bedrock claude error

### ISSUE THREAD

**Issue by aldwnesx** [BerriAI/litellm#4690]
### What happened?

:31   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 9947, in exception_type
2024-07-13 15:13:31     raise APIConnectionError(
2024-07-13 15:13:31 litellm.exceptions.APIConnectionError: Attempted to access streaming response content, without having called `read()`.

**Comment by ghost** [comment]
hey @aldwnesx can you bump to latest? 

The error shown seems like an error occurred midstream and it wasn't raised correctly. But the line number (9947) looks outdated. 

For context this is what line 9947 in utils.py is on latest - https://github.com/BerriAI/litellm/blob/66cedccd6b4e7211863847887c44da7368def326/litellm/utils.py#L9947

**Comment by aldwnesx** [comment]
> hey @aldwnesx can you bump to latest?
> 
> The error shown seems like an error occurred midstream and it wasn't raised correctly. But the line number (9947) looks outdated.
> 
> For context this is what line 9947 in utils.py is on latest -
> 
> https://github.com/BerriAI/litellm/blob/66cedccd6b4e7211863847887c44da7368def326/litellm/utils.py#L9947

Updated latest but got

Uh-oh! There was an issue connecting to sonnet-3.5.
litellm.BadRequestError: BedrockException - Client error '400 Bad Request' for url 'https://bedrock-runtime.us-west-2.amazonaws.com/model/anthropic.claude-3-5-sonnet-20240620-v1:0/converse-stream'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400

**Comment by ghost** [comment]
hey @aldwnesx i don't think you're on latest, reason:

I re-ran with the same model name - and i got the correct error: 
```
litellm.BadRequestError: BedrockException - b'{"message":"The provided model identifier is invalid."}'
```

do you have access to claude 3-5 in `us-west-2`? 
<img width="1392" alt="Screenshot 2024-07-13 at 6 57 55 PM" src="https://github.com/user-attachments/assets/f824ec3c-b2c4-4410-9723-a108a4731b8a">
