### ISSUE TITLE
[Bug]: SERVER_ROOT_PATH doesn't seem to work with ui. Works only for openapi swagger page. 

### ISSUE THREAD

**Issue by ashutoshsaboo** [BerriAI/litellm#4691]
### What happened?

Configured SERVER_ROOT_PATH="/litellm" while spawning the server, i can access http://loadbalancer_url/litellm/ openapi swagger page correctly, but cant access /loadbalancer/litellm/ui/ page. saw browser console logs, main js file seems to be 404ing. Can this be please fixed? Other ui specific calls also seems to be 404ing. 

![Screenshot 2024-07-13 at 1 03 17 PM](https://github.com/user-attachments/assets/3c3cf6a5-708e-4e32-982c-a547f3844f62)

**Comment by ghost** [comment]
cc: @ishaan-jaff ?

**Comment by ashutoshsaboo** [comment]
I did briefly try setting basePath and assetPrefix in the next config under ui/litellm-dashboard/ to `/${SERVER_ROOT_PATH}/ui` , i'm not sure if it was a result of that change, or if it was originally happening same way as well - but it atleast deployed all webpack minified files, favicon, and a couple other static assets from _next to the correct ${SERVER_ROOT_PATH}//ui/<relevant path>, but browser was still requesting those files from /ui/<relevant path> only, i.e, it was requesting the resource without the path prefix which results in the error. cc: @krrishdholakia @ishaan-jaff

**Comment by ishaan-jaff** [comment]
fixed via https://github.com/BerriAI/litellm/pull/4142 @ashutoshsaboo - should see this on today's release

**Comment by ishaan-jaff** [comment]
fixed here: https://github.com/BerriAI/litellm/pull/5056
