### ISSUE TITLE
[Bug]: Prompts to Perplexity increase memory consumption by >100%

### ISSUE THREAD

**Issue by bachya** [BerriAI/litellm#4700]
### What happened?

I am using `litellm` 1.41.20
I have a simple FastAPI app running in a Docker container. That FastAPI app has one route, which makes a streaming, async completion call to Perplexity (specifically, the `llama-3-sonar-large-32k-chat` model). Before making the call, the container uses approximately 228.4MiB of memory; after a single completion call to the Perplexity API, that memory usage jumps to 470.1MiB. Subsequent calls to the Perplexity API make little impact: the memory may go up half a MiB or so.

For comparison, completion calls to the Anthropic provider increase memory from approximately 228.4MiB to 243.2MiB.

**Comment by ishaan-jaff** [comment]
- do you have any litellm.callbacks set
- if you don't mind can you share the fast api app code with me so i can repro

**Comment by bachya** [comment]
No callbacks.

Let me put together a minimally reproducible example for you. I'm traveling at the moment, so may be a day or two.

**Comment by ishaan-jaff** [comment]
okay @bachya - this is probably because we init an OpenAI client for Perplexity 

I suspect you won't see this on the 2nd request

**Comment by bachya** [comment]
> okay @bachya - this is probably because we init an OpenAI client for Perplexity 
> 
> 
> 
> I suspect you won't see this on the 2nd request 

Correct: subsequent requests don't consume any more memory after the first request.

I didn't mention this, but for whatever it's worth, when I submit completions to the OpenAI provider, I don't see the same memory jump; does that one not also instantiate a client?

**Comment by ishaan-jaff** [comment]
it would help if you can share some code here @bachya

**Comment by ishaan-jaff** [comment]
bump on this @bachya

**Comment by bachya** [comment]
@ishaan-jaff As I mentioned, I've been traveling—please be patient. I'll get back to you today.

**Comment by bachya** [comment]
I just upgraded to 1.41.22 and noticed that the jump in my current app is far less: approximately 229MiB to 330MiB.

---

After creating a stripped-down minimally reproducible example (small FastAPI app in a Docker image), I notice that the memory increase is very small (14MiB), so there must be something going on in my app. I'll close this for now. Thanks!
