### ISSUE TITLE
BUG: Missing "None" check before using logging_obj.pre_call in ollama.py embedding function

### ISSUE THREAD

**Issue by NickPowers43** [BerriAI/litellm#4707]
I was getting the following error trying to use the embedding function:

`AttributeError: 'EmbeddingResponse' object has no attribute 'pre_call'`

Here is where I think you need to add a None check

https://github.com/BerriAI/litellm/blob/2bf1f06a0eff18d41066aacc635fb06003f8cc91/litellm/llms/ollama.py#L540

**Comment by ghost** [comment]
Unable to repro. This works just fine for me - 
<img width="1180" alt="Screenshot 2024-07-15 at 7 00 59 PM" src="https://github.com/user-attachments/assets/7ff2fc99-af4d-45e9-b7da-953a4251648b">


config: 
```yaml
model_list:
  - model_name: ollama-mistral
    litellm_params:
      model: ollama/mistral
```


Curl for testing: 
```bash
curl -X POST 'http://0.0.0.0:4000/embeddings' \
-H 'Authorization: Bearer sk-1234' \
-H 'Content-Type: application/json' \
-D '{"input": ["Are you authorized to work in United States of America?"], "model": "ollama-mistral"}'
```

**Comment by ghost** [comment]
closing as unable to repro. Feel free to bump/reopen if you have a consistent repro on latest. @NickPowers43
