### ISSUE TITLE
[Bug]: custom async_log_failure_event callback not passed much data when max_parallel_request is hit

### ISSUE THREAD

**Issue by jeromeroussin** [BerriAI/litellm#4708]
### What happened?

I am adding an async_log_failure to my proxy. I am noticing that when the failure is due to max_parallel_request getting reached, the callback is not passed kwargs['optional_params'], or kwargs['additional_arg']s, or much in kwargs['litellm_params']. This severely limits the usefulness of the custom async_log_failure callback.

### Twitter / LinkedIn details

https://www.linkedin.com/in/jeromeroussin/

**Comment by ghost** [comment]
i believe this is due to where the error originates from (before the call enters `.completion()`). 

What is your failure callback trying to do?

**Comment by ghost** [comment]
can you share the error message you're getting? @jeromeroussin, this will help trace the issue
