### ISSUE TITLE
[Bug]: Cohere Chat does not support parameters: {'extra_headers'}

### ISSUE THREAD

**Issue by maamalama** [BerriAI/litellm#4709]
### What happened?

Got exception `litellm.exceptions.ServiceUnavailableError: litellm.ServiceUnavailableError: CohereException - cohere_chat does not support parameters: {'extra_headers': {'Helicone-Property-Locale': 'ko'}}` when trying to pass custom headers to Cohere command-r model

How to reproduce: 

```
litellm.headers = {
  "Helicone-Property-Locale": "ko",
  }

response = litellm.completion(
    model="command-r",
    messages=[{"role": "user", "content": "testing - 0000"}],
    extra_headers={"Helicone-Property-Locale": "ko"},
)
print(response)
```

### Relevant log output

```shell
litellm.exceptions.ServiceUnavailableError: litellm.ServiceUnavailableError: CohereException - cohere_chat does not support parameters: {'extra_headers': {'Helicone-Property-Locale': 'ko'}}, for model=command-r. To drop these, set `litellm.drop_params=True` or for proxy:

`litellm_settings:
 drop_params: true`
```

**Comment by ghost** [comment]
is this a bug? I don't think cohere chat does support extra_headers, 

what should happen here?

**Comment by ghost** [comment]
unclear what the issue is, and this doesn't seem like a bug (since the param isn't supported). 

If this is related to a helicone implementation, then @maamalama please feel free to re-open with the helicone-specific problem that needs to be fixed on our end.

**Comment by Manouchehri** [comment]
> I don't think cohere chat does support extra_headers

All providers should support `extra_headers`.

> what should happen here?

The header of `Helicone-Property-Locale: ko` should be sent in the upstream LLM request.
