### ISSUE TITLE
[Bug]: openai_params is not mapped for Ollama but for Ollama Chat

### ISSUE THREAD

**Issue by SmartManoj** [BerriAI/litellm#4710]
### What happened?

[A bug happened!](https://www.diffchecker.com/ACrjtf42/)

**Comment by ghost** [comment]
hi @SmartManoj yes we do map the openai params for ollama 

https://github.com/BerriAI/litellm/blob/9cc2daeec911f3e2fb324ff34c7b8c7106306d39/litellm/utils.py#L3142
