### ISSUE TITLE
[Bug]: LiteLLM does not support  custom rerank model server.

### ISSUE THREAD

**Issue by cheng92hao** [BerriAI/litellm#4712]
### What happened?

A bug happened!
I  add a new  model:  bge-reranker-large.

but the API  response is :
{
   "detail": "Not Found"
}

**Comment by ishaan-jaff** [comment]
@cheng92hao you can create a pass through endpoint : https://docs.litellm.ai/docs/proxy/pass_through#tutorial---pass-through-cohere-re-rank-endpoint

**Comment by S1LV3RJ1NX** [comment]
@ishaan-jaff I am trying to use [infinity-server](https://github.com/michaelfeil/infinity), that helps hosting hugging face reranker models, but this server does not provide `meta` dict that causes API to fail how to solve for that?

**Comment by i-makashev** [comment]
> @cheng92hao you can create a pass through endpoint : https://docs.litellm.ai/docs/proxy/pass_through#tutorial---pass-through-cohere-re-rank-endpoint

Hi, could you specify example how to make it to work. I really can't figure out how to configure pass-through to my vLLM endpoint
