### ISSUE TITLE
[Bug]: column `requester_ip_address` does not exist in the current database

### ISSUE THREAD

**Issue by msabramo** [BerriAI/litellm#4717]
### What happened?

Our Slack alerts channel is filled with messages about a missing database column. This seems like a LiteLLM bug because launching LiteLLM Proxy should automatically apply database migrations, right?

### Relevant log output

```shell
Message: DB read/write call failed: The column requester_ip_address does not exist in the current database.LiteLLM Prisma Client Exception - update spend logs: The column requester_ip_address does not exist in the current database.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/utils.py", line 2589, in update_spend
    await prisma_client.db.litellm_spendlogs.create_many(
  File "/usr/local/lib/python3.11/site-packages/prisma/actions.py", line 9489, in create_many
    resp = await self._client._execute(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prisma/client.py", line 525, in _execute
    return await self._engine.query(builder.build(), tx_id=self._tx_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prisma/engine/query.py", line 244, in query
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prisma/engine/http.py", line 141, in request
    return utils.handle_re
```

Cc: @taralika

**Comment by ghost** [comment]
Hey @msabramo can you share your server startup logs? A prisma migration is applied on startup - https://github.com/BerriAI/litellm/blob/ff1bcdd3b5ce32812bc349f27c22defce58cb17e/litellm/proxy/utils.py#L753

**Comment by ghost** [comment]
bump on this? @msabramo

**Comment by msabramo** [comment]
I think it's not happening anymore. I wonder if it's related to having multiple versions of the app running using the same database. Some of those may have been old versions. I recently deleted some of those and that might be why we're not seeing the error anymore. I'll close.
