### ISSUE TITLE
[Bug]: ContextWindowExceededError with gpt-4o

### ISSUE THREAD

**Issue by vinchg** [BerriAI/litellm#4735]
### What happened?

When calling `gpt-4o` with a tool description that exceeds 1024 length, I get this error, but I don't understand where/why this is being called. If I directly call gpt-3.5-turbo or gpt-4o with a long description - the llm handles it with no issue.
```
litellm.exceptions.ContextWindowExceededError: litellm.BadRequestError: litellm.ContextWindowExceededError: ContextWindowExceededError: OpenAIException - Error code: 400 - {'error': {'message': "Invalid 'tools[1].function.description': string too long. Expected a string with maximum length 1024, but got a string with length 1103 instead.", 'type': 'invalid_request_error', 'param': 'tools[1].function.description', 'code': 'string_above_max_length'}}
```
I wasn't able to find any information about this in litellm docs or OpenAI's docs. Is this considered a bug or an intended restriction with litellm?

**Comment by ishaan-jaff** [comment]
@vinchg this is the response / exception from the LLM provider not from LiteLLM

**Comment by ishaan-jaff** [comment]
OpenAI is raising this exception
