### ISSUE TITLE
[Feature]: Add `stream=True` for LiteLLM proxy server for TGI

### ISSUE THREAD

**Issue by abhinavkulkarni** [BerriAI/litellm#476]
Hi,

Thanks for the great work!

I have a local TGI installation. 

```bash
$ text-generation-launcher 
  --model-id abhinavkulkarni/codellama-CodeLlama-7b-Instruct-hf-w4-g128-awq \
  --trust-remote-code --port 8080 \
  --max-input-length 5376 --max-total-tokens 6144 --max-batch-prefill-tokens 6144 \
  --quantize awq
```

I have a LiteLLM proxy server on top of that.

```bash
$ litellm \
  --model huggingface/abhinavkulkarni/codellama-CodeLlama-7b-Instruct-hf-w4-g128-awq \
  --api_base http://localhost:8080
```

I am able to successfully obtain responses from `openai.ChatCompletion.create` endpoint as follows:

```python
>>> import openai
>>> openai.api_key = "xyz"
>>> openai.api_base = "http://0.0.0.0:8000"
>>> model = "huggingface/abhinavkulkarni/codellama-CodeLlama-7b-Instruct-hf-w4-g128-awq"
>>> completion = openai.ChatCompletion.create(model=model, messages=[{"role": "user", "content": "How are you?"}])
>>> print(completion)
{
  "object": "chat.completion",
  "choices": [
    {
      "finish_reason": "length",
      "index": 0,
      "message": {
        "content": "I'm fine, thanks. I'm glad to hear that.\n\nI'm",
        "role": "assistant",
        "logprobs": -18.19830319
      }
    }
  ],
  "id": "chatcmpl-7f8f5312-893a-4dab-aff5-3a97a354c2be",
  "created": 1695869575.316254,
  "model": "abhinavkulkarni/codellama-CodeLlama-7b-Instruct-hf-w4-g128-awq",
  "usage": {
    "prompt_tokens": 4,
    "completion_tokens": 15,
    "total_tokens": 19
  }
}
```

However, I am not able to obtain responses when `stream=True`:

```python
>>> response = openai.ChatCompletion.create(model=model, messages=[{"role": "user", "content": "How are you?"}], steam=True)
Traceback (most recent call last):
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/openai/api_requestor.py", line 403, in handle_error_response
    error_data = resp["error"]
TypeError: string indices must be integers
```

Thanks!

**Comment by ghost** [comment]
We should already be supporting streaming -  https://github.com/BerriAI/litellm/blob/361bf02e53f04d66ab3c39a9118d741ff528f9b7/litellm/proxy/proxy_server.py#L37

--
Ran it myself: 

For `meta-llama/Llama-2-70b-chat-hf` hosted on HF PRO Inference endpoints: 
`litellm --model huggingface/meta-llama/Llama-2-70b-chat-hf`

Here's my code running with streaming: 
<img width="881" alt="Screenshot 2023-09-27 at 8 30 00 PM" src="https://github.com/BerriAI/litellm/assets/17561003/33c65355-ee50-4bdc-a763-9ac5fb77798b">

**Comment by ghost** [comment]
Here's my proxy server printing the response. 
<img width="1096" alt="Screenshot 2023-09-27 at 8 32 26 PM" src="https://github.com/BerriAI/litellm/assets/17561003/f04b105e-a4d0-498d-9d5e-3c2af3248fe7">


@abhinavkulkarni can you share what your server console logs are showing?

**Comment by ghost** [comment]
Closing as this was resolved via DM's @abhinavkulkarni
