### ISSUE TITLE
[Feature]: It seems we can't rely on securitygroups configured on the Azure Web App via Enterprise App autorization

### ISSUE THREAD

**Issue by fransbe** [BerriAI/litellm#4768]
### The Feature

Fully rely on Entra ID security

### Motivation, pitch

There is now not enough granularity besides the Entra ID Token.

**Comment by ghost** [comment]
hey @fransbe can you share what the gap is / how you'd expect this to work? 

Happy to do a call to understand your setup, if that helps 

https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by Manouchehri** [comment]
This is doable already with OIDC. My team has been using this for several weeks in prod.

See https://github.com/BerriAI/litellm/pull/4836.

**Comment by ishaan-jaff** [comment]
@fransbe you can also use Entrata ID now: https://docs.litellm.ai/docs/providers/azure#usage---litellm-proxy-server 

<img width="708" alt="Screenshot 2024-08-23 at 6 23 01 PM" src="https://github.com/user-attachments/assets/4bfbcaf8-9cab-45af-b817-e8daa47dc4f1">

**Comment by ishaan-jaff** [comment]
closing since we support Entrata ID for Azure OpenAI
