### ISSUE TITLE
[Bug]: Performance issues with Bedrock streaming

### ISSUE THREAD

**Issue by dshvadskiy** [BerriAI/litellm#4774]
### What happened?

Calling Bedrock models under load cause significant performance issues. It is about 10 times slower (depending on the load) to call lietllm.completion or litellm.acompletion  with stream=True vs stream=False 
I was able to trace the issue to this call
https://github.com/BerriAI/litellm/blob/main/litellm/llms/bedrock_httpx.py#L2150
If call to get_response_stream_shape() is cached the performance with stream=True vs stream=False is about the same

**Comment by dshvadskiy** [comment]
To reproduce run Load Test LiteLLM Proxy - 1500+ req/s  from https://litellm.vercel.app/docs/load_test pointing to bedrock models with stream=True vs stream=False

**Comment by ghost** [comment]
Thanks @dshvadskiy just pushed a fix based on your suggestion for caching response_stream_shape. 

Curious, how're you trying to use litellm proxy?

**Comment by dshvadskiy** [comment]
@krrishdholakia Thank you for quick turnaround with the fix. We are not currently using litellm proxy but plan to test it in the future. We use litellm library inside fastapi server to provide backward compatibility with our older API. litelllm proxy test was the easiest way to check the issue is with the library itself and not with our code
