### ISSUE TITLE
GPT-4 is called by default in Ubantu, and the API cannot be entered

### ISSUE THREAD

**Issue by Sixdots09** [BerriAI/litellm#479]
(testnewthings) sixdots09@天真:/mnt/d/open-interpreter$ interpreter

▌ Model set to GPT-4

Open Interpreter will require approval before running code. Use interpreter -y to bypass this.

Press CTRL-C to exit.

> can you opemn edge

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new

**Comment by ishaan-jaff** [comment]
@Sixdots09 Open interpreter by default calls gpt-4 this is their decision

**Comment by ishaan-jaff** [comment]
what do you mean by API cannot be entered ?

**Comment by ghost** [comment]
try doing this instead - https://docs.litellm.ai/docs/proxy_server

**Comment by ghost** [comment]
@Sixdots09

**Comment by Sixdots09** [comment]
I use Powershell and Ubuntu respectively. I can input my API on Powershell, but I can’t do it on Ubuntu.
I have taken screenshots separately, below is the picture link.
https://sixdots09-1320291132.cos.ap-chengdu.myqcloud.com/Sixdots09/PowerShell.png
https://sixdots09-1320291132.cos.ap-chengdu.myqcloud.com/Sixdots09/Ubuntu.png

**Comment by Sixdots09** [comment]
Thanks for everyone’s responses!
