### ISSUE TITLE
[Bug]: Error 422: drop_params Not Working with mistral-large and mistral-small Models in Azure AI

### ISSUE THREAD

**Issue by seonghobae** [BerriAI/litellm#4800]
### What happened?

# Bug Report: drop_params Not Working with mistral-large and mistral-small

## Description

When using the **`mistral-large`** and **`mistral-small`** models, the **`drop_params`** functionality is not working as expected. The following error message is encountered:

```python
jsonlitellm.BadRequestError: Azure_aiException - Error code: 422 - {'detail': [{'type': 'extra_forbidden', 'loc': ['body', 'frequency_penalty'], 'msg': 'Extra inputs are not permitted', 'input': 0.0}, {'type': 'extra_forbidden', 'loc': ['body', 'presence_penalty'], 'msg': 'Extra inputs are not permitted', 'input': 0.0}]}
```

## Steps to Reproduce

1. Attempt to use the **`mistral-large`** or **`mistral-small`** models with **`drop_params`**.
2. Observe the error message indicating that extra inputs are not permitted.

## Expected Behavior

The **`drop_params`** functionality should work without causing any errors, and the models should process the input as expected.

## Actual Behavior

The following error message is returned, indicating that extra inputs are not permitted:

```python
jsonlitellm.BadRequestError: Azure_aiException - Error code: 422 - {'detail': [{'type': 'extra_forbidden', 'loc': ['body', 'frequency_penalty'], 'msg': 'Extra inputs are not permitted', 'input': 0.0}, {'type': 'extra_forbidden', 'loc': ['body', 'presence_penalty'], 'msg': 'Extra inputs are not permitted', 'input': 0.0}]}
```

## Environment

- Model: **`mistral-large`**, **`mistral-small`**
- Error Code: 422
- Error Message: Extra inputs are not permitted

## Additional Information

It appears that the **`frequency_penalty`** and **`presence_penalty`** parameters are being treated as extra inputs, which are not allowed by the models. This issue needs to be addressed to ensure that **`drop_params`** works correctly with these models.

## Suggested Fix

Review the implementation of **`drop_params`** for the **`mistral-large`** and **`mistral-small`** models to ensure that extra inputs are not being passed, or update the models to handle these parameters appropriately.

Thank you for your attention to this matter.

**Comment by ghost** [comment]
Azure AI schema shows support for frequency penalty and presence penalty - https://learn.microsoft.com/en-us/azure/machine-learning/reference-model-inference-chat-completions?view=azureml-api-2

**Comment by ghost** [comment]
Able to repro 

<img width="1221" alt="Screenshot 2024-07-20 at 2 47 55 PM" src="https://github.com/user-attachments/assets/913ab3d4-c337-4401-8ec7-abfca36c9cb2">

**Comment by ghost** [comment]
it looks like azure ai is inconsistent with the params supported by model

**Comment by ghost** [comment]
Fixed. If `drop_params` is set, and a 422 is received, we'll retry the request without the invalid params 

<img width="1149" alt="Screenshot 2024-07-20 at 3 05 57 PM" src="https://github.com/user-attachments/assets/fb5072f7-818a-47b0-89aa-25e09227f399">
