### ISSUE TITLE
[Bug]: The variable used to change the Anthropic API URL isn't standard

### ISSUE THREAD

**Issue by hourianto** [BerriAI/litellm#4803]
### What happened?

LiteLLM supports changing the default API URL for different providers, and it does so for Anthropic as well. However, in case of Anthropic the way it's done in LiteLLM is different from how it's done for e.g. OpenAI, and different from what the official Anthropic Python packages do.

All official Anthropic packages support specifying the `base_url` parameter when creating a client, and it's used the exact same way OpenAI does it. You can check the code here, for example:
https://github.com/anthropics/anthropic-sdk-python/blob/fda45a6eae139003656fda08b57ce2e9bfab8974/src/anthropic/_client.py#L116

So the standard way for Anthropic is to specify `ANTHROPIC_BASE_URL` pointing to the _base_ API url, not `ANTHROPIC_API_BASE` pointing to the exact API endpoint, like LiteLLM does it.

I think it'll be a good idea to change it to use the same variable name as official packages do.

Oh, and also, the custom API url isn't documented in LiteLLM for Anthropic, had to search in code to find how to pass it since I'm using LiteLLM through aider :)

**Comment by ghost** [comment]
so is the ask to support `ANTHROPIC_BASE_URL` as well?

**Comment by hourianto** [comment]
@krrishdholakia thanks for doing the patch, but it's wrong - `ANTHROPIC_BASE_URL` points to the base URL, not the actual API method, so it should be used like `get_secret("ANTHROPIC_BASE_URL") + "/v1/messages"` - hopefully there's a method for better URL joining, so that both of those will work the same:

```
ANTHROPIC_BASE_URL=https://api.anthropic.com
ANTHROPIC_BASE_URL=https://api.anthropic.com/
```
