### ISSUE TITLE
[Feature]: Better documentation for defining models in config

### ISSUE THREAD

**Issue by viraptor** [BerriAI/litellm#4813]
### The Feature

Currently the config description is not great. There are some examples, but trying to figure out specifically: "how to add Claude to the config" is pretty hard.

The error messages point at https://docs.litellm.ai/docs/providers which really talks about code, not configuration.

If a bare module name is specified, the error prompts to include a provider which is not made explicit - is it a separate key? prefix of the model? is it "anthropic"? "Anthropic"? Something else?

Are there default API urls or are they required? (the example contains them)

Ideally there should be an example for the config in each of the providers section.

### Motivation, pitch

I'm a happy litellm user from the code point of view, but found trying to setup the proxy really confusing and lacking proper documentation.

**Comment by ghost** [comment]
Hey @viraptor thank you for this! where did you look on docs? What would you have wanted to see?

Asking as I can see proxy usage example on the Anthropic docs - https://docs.litellm.ai/docs/providers/anthropic#openai-proxy-usage

**Comment by viraptor** [comment]
🤦‍♂️ I've read that page many times and completely missed the tab with the config example 😂

**Comment by ishaan-jaff** [comment]
@viraptor updated here: https://github.com/BerriAI/litellm/pull/4838 

What other providers do you use - i'll make sure we have examples using the config.yaml there

**Comment by ishaan-jaff** [comment]
@viraptor can we setup a 1:1 support channel - I'd love to continue addressing your issues and provide fast support 

My linkedin is here: https://www.linkedin.com/in/reffajnaahsi/
LiteLLM discord - if you wave i'll setup a support channel: https://discord.com/invite/wuPM9dRgDw 
My cal if you'd like to hop on a call: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat 
(I'd love to learn how we can improve litellm for you @viraptor )
