### ISSUE TITLE
[Bug]: Num_Retries

### ISSUE THREAD

**Issue by narenedara** [BerriAI/litellm#4814]
### What happened?

Hi,
I am currently trying to use LiteLLM to make multiple parrallel requests at one time in an ensemble. However, after about 50 requests I eventually receive "None" as an answer from the LLM for each request from there on. I realize that is likely due to a rate limit but I was wondering if there is any feature that LiteLLm supports which will wait a minute until the rate limit resets and then retry. I have already tried increasing the num_retries but this has been not been completely effective.

**Comment by knowsuchagency** [comment]
I'd suggest tenacity for this https://tenacity.readthedocs.io/en/latest/

**Comment by ghost** [comment]
Yes @narenedara try using the router - https://docs.litellm.ai/docs/routing
