### ISSUE TITLE
[Bug]: Deployment Name Case Sensitivity Issue in LiteLLM Proxy with Azure OpenAI Model

### ISSUE THREAD

**Issue by seonghobae** [BerriAI/litellm#4816]
### What happened?

# **Bug Report: Deployment Name Case Sensitivity Issue in LiteLLM Proxy with Azure OpenAI Model**

**Description:** There is a bug in the LiteLLM Proxy when deploying an Azure OpenAI model. If the deployment name contains mixed case letters, the health check incorrectly identifies the model as Unhealthy.

**Steps to Reproduce:**

1. Deploy an Azure OpenAI model using LiteLLM Proxy with a deployment name that includes mixed case letters (e.g., **`MyModelDeployment`**).
2. Perform a health check on the deployed model.

**Expected Behavior:** The health check should correctly identify the model as Healthy regardless of the case used in the deployment name.

**Actual Behavior:** The health check incorrectly identifies the model as Unhealthy when the deployment name contains mixed case letters.

**Environment:**

- LiteLLM Proxy version: 1.41.26
- Deployment name:
  ![image](https://github.com/user-attachments/assets/fd88bda9-cdca-46a9-8086-bc0407695f6e)

**Additional Information:** This issue seems to be related to case sensitivity in the deployment name handling within the health check logic. Ensuring that the deployment name is treated in a case-insensitive manner should resolve this issue.

**Suggested Fix:** Modify the health check logic to handle deployment names in a case-insensitive manner.

Thank you for addressing this issue. Please let me know if you need any further information.

Best regards,

Seongho Bae

**Comment by ghost** [comment]
Unable to repro. @seonghobae I suspect you do in fact have bad deployments. Given your previous issue as well, i think you have incorrect credentials in your environment. 

```yaml
model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: azure/CaseSensitiveGPT
      api_key: os.environ/AZURE_CANADA_API_KEY
      api_base: os.environ/AZURE_CANADA_API_BASE
```

Curl for testing:

```bash
curl --location 'http://0.0.0.0:4000/health' \
--header 'Authorization: Bearer sk-1234'
```

<img width="1198" alt="Screenshot 2024-07-22 at 2 25 23 PM" src="https://github.com/user-attachments/assets/9848cc17-f142-4b33-892d-6a5a3866966c">

**Comment by seonghobae** [comment]
@krrishdholakia I discovered the issue while testing the addition of environments to the database through the admin UI. I do not want to set this environment in the environment variable. Considering the Kubernetes deployment environment, I believe that requiring a Persistent Volume for the env environment is not an ideal design. In any case, I am experiencing this issue when adding it to the database (PostgreSQL).

**Comment by ghost** [comment]
Hey @seonghobae i believe the issue might be in how the model was added. 

Can we do a call for helping debug this? Will also help me understand your suggestion here

https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by seonghobae** [comment]
> Hey @seonghobae i believe the issue might be in how the model was added.
> 
> Can we do a call for helping debug this? Will also help me understand your suggestion here
> 
> https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

Okay, I made a schedule for it.
