### ISSUE TITLE
[Bug]: LiteLLM keys not working on demo completion call

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#482]
### What happened?

Tried copy pasting code on docs and it failed with this exception:

https://docs.litellm.ai/docs/ 

## Code to repro
```
from litellm import completion
import os

## set ENV variables
os.environ["OPENAI_API_KEY"] = "sk-litellm-7_NPZhMGxY2GoHC59LgbDw" # [OPTIONAL] replace with your openai key

response = completion(
  model="gpt-3.5-turbo", 
  messages=[{ "content": "Hello, how are you?","role": "user"}]
)
```

## Exception 

<img width="1205" alt="Screenshot 2023-09-28 at 8 03 09 AM" src="https://github.com/BerriAI/litellm/assets/29436595/59386f2c-09e1-4468-8f30-17bdca641269">

**Comment by ishaan-jaff** [comment]
Also I have no idea what this error message means. It should probably tell me that the keys are invalid 

<img width="1231" alt="Screenshot 2023-09-28 at 8 04 27 AM" src="https://github.com/BerriAI/litellm/assets/29436595/054320c6-bb4a-4224-84b1-c5735a53a9ef">

**Comment by ghost** [comment]
the package is working fine -> it's making the openai proxy call -> the server is returning an error -> openai's python package is raising it as an invalid response error

**Comment by ghost** [comment]
what would you expect here @ishaan-jaff

**Comment by ishaan-jaff** [comment]
As a user of LiteLLM - shouldn't it just tell me invalid API key ? 

Also for this ticket the issue im raising is to fix the proxy - it should not be throwing errors
