### ISSUE TITLE
[Feature]: Support Gemini api format (work with vertex ai client sdk) 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#4824]
### The Feature

Support requests received in the Gemini api format. 

Add an example of how to call proxy with vertex ai sdk 

### Motivation, pitch

This would allow users to call the proxy with the vertex ai client sdk.

Vertex AI SDK seems to support a way to add proxy - see `client_options` 
<img width="361" alt="Screenshot 2024-07-22 at 11 05 23 AM" src="https://github.com/user-attachments/assets/10946178-424a-4997-b0bf-77684fa08bd1">

**Comment by ishaan-jaff** [comment]
We support this now https://litellm-api.up.railway.app/#/Vertex%20AI%20endpoints
