### ISSUE TITLE
[Bug]: rpm/tpm limits are not followed

### ISSUE THREAD

**Issue by taralika** [BerriAI/litellm#4829]
### What happened?

The following key has `tpm_limit` set to 100, but I can make requests over this limit (up to model max of 16k tokens) in a single request. I expect a request over the specified `tpm_limit` to fail.

## Info of the key & user being used:
```
curl --request GET \
  --url 'https://custom-litellm.xyz.com/user/info?user_id=sk-123%40xyz.com' \
  --header 'Authorization: Bearer {$ADMIN_API_KEY}'
```
### Response:
```
{
   "user_id":"sk-123@xyz.com",
   "user_info":{
      "user_id":"sk-123@xyz.com",
      "user_alias":"sk-123",
      "team_id":null,
      "organization_id":null,
      "password":null,
      "teams":[
         
      ],
      "user_role":"internal_user_viewer",
      "max_budget":5.0,
      "spend":1.3299665,
      "user_email":"sk-123@xyz.com",
      "models":[
         
      ],
      "max_parallel_requests":1,
      "tpm_limit":100,
      "rpm_limit":3,
      "budget_duration":"24h",
      "budget_reset_at":null,
      "allowed_cache_controls":[
         
      ],
      "model_spend":{
         
      },
      "model_max_budget":{
         
      },
      "litellm_organization_table":null,
      "invitations_created":null,
      "invitations_updated":null,
      "invitations_user":null
   },
   "keys":[
      {
         "token":"f3983094ilkejfkljsdf8ukjb23883ujf...",
         "key_name":"sk-123",
         "key_alias":"sk-123",
         "soft_budget_cooldown":false,
         "spend":1.3299665,
         "expires":null,
         "models":[
            
         ],
         "aliases":{
            
         },
         "config":{
            
         },
         "user_id":"sk-123@xyz.com",
         "team_id":null,
         "permissions":{
            
         },
         "max_parallel_requests":1,
         "metadata":{
            "use_case":"Test key for quick testing"
         },
         "tpm_limit":100,
         "rpm_limit":3,
         "max_budget":5.0,
         "budget_duration":"24h",
         "budget_reset_at":null,
         "allowed_cache_controls":[
            
         ],
         "model_spend":{
            
         },
         "model_max_budget":{
            
         },
         "budget_id":null,
         "litellm_budget_table":null,
         "team_alias":"None"
      }
   ],
   "teams":[
      
   ]
}
```
## The `completions` call that should have failed:
```
curl --request POST \
  --url https://custom-litellm.xyz.com/chat/completions \
  --header 'Authorization: Bearer sk-123' \
  --header 'Content-Type: application/json' \
  --data '{
	"model": "gpt-35-turbo-0125",
	"messages": [
		{
			"role": "user",
			"content": "Double this text in size: There is no one .. and we did it. (truncated but actually has 10k tokens)"
		}
	]
}'
```
### Response:
```
{
   "id":"chatcmpl-9nw0ceYWxqUXwvA8hRClLI9MGmYlj",
   "choices":[
      {
         "finish_reason":"length",
         "index":0,
         "message":{
            "content":"{long answer of 4k tokens}",
            "role":"assistant",
            "tool_calls":null,
            "function_call":null
         }
      }
   ],
   "created":1721688086,
   "model":"gpt-35-turbo",
   "object":"chat.completion",
   "system_fingerprint":"fp_811936bd4f",
   "usage":{
      "completion_tokens":4096,
      "prompt_tokens":10130,
      "total_tokens":14226
   }
}
```

Similar issues also observed with `rpm_limit`

**Comment by ghost** [comment]
hey @taralika so is the issue that there should be a pre-call check to make sure the request doesn't exceed tpm limits?

**Comment by ghost** [comment]
how was this issue observed with the rpm limit?

**Comment by taralika** [comment]
> hey @taralika so is the issue that there should be a pre-call check to make sure the request doesn't exceed tpm limits?

the issue is that this /completions call itself should have failed as it ends up using over the tpm_limit of 100 tokens.

> how was this issue observed with the rpm limit?

I am able to make same /completions requests more than 3 times in a minute, when `rpm_limit` is set to 3 - the 4th request onwards should have failed until 1 minute passes

**Comment by ghost** [comment]
Hey @taralika i'm not able to repro the rpm limit behaviour locally. Is this on latest? 

Could you email me your server logs? @ krrishdholakia@berri.ai? 

Will help me debug what might be happening

**Comment by taralika** [comment]
We're on [v1.41.19](https://github.com/BerriAI/litellm/releases/tag/v1.41.19)
@msabramo can you help with server logs?
@krrishdholakia Like I showed in my previous messages, the sk-123 key has rpm_limit of 3, but I can make several requests using this key within a minute, so the litellm is not adhering to the limit of 3.

Are you able to repro the issue with tpm_limit? how soon would you be able to fix that?

**Comment by ghost** [comment]
Hi @taralika I tried both 

- tpm_limit: https://drive.google.com/file/d/1A_MOGwg4yu-ncRQhPqurozhpbzSeQYeM/view?usp=sharing
- rpm_limit: https://drive.google.com/file/d/1gIQRILaDucBu_mfCR8Xas5l5xnFmuhfp/view?usp=sharing

Both work for me. Can we do a quick call to repro this? 

https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by taralika** [comment]
Ok we'll investigate tpm_limit and rpm_limit further on our end.

By the way, if we set `max_budget` and want it to reset daily, we set it and here is our test key's info:
```
"max_budget": 5.0,
"spend": 5.227709000000001,
"user_email": "sk-123@xyz.com",
"max_parallel_requests": 1,
"tpm_limit": 100,
"rpm_limit": 3,
"budget_duration": "24h",
"budget_reset_at": null,
```

we were expecting the budget will reset after 24hrs, but it did not and even after 24hrs still getting error about max budget reached. What do we need to do differently here to achieve this?

**Comment by ghost** [comment]
i see budget_reset_at is null - it should've been set to some value (presumably time it was initially set to) 

how was this set? @taralika 

https://github.com/BerriAI/litellm/blob/cb4c42e06177858867af33a2093045cdfec02545/litellm/proxy/management_endpoints/key_management_endpoints.py#L785

**Comment by ghost** [comment]
@taralika a 10min call this week would help us repro your issues

**Comment by taralika** [comment]
> how was this set?

it was set in the UI:
<img width="887" alt="image" src="https://github.com/user-attachments/assets/2778034a-7ec2-4c0f-aa19-e989d9afe4bc">

but that didn't have the setting for reset, so the rest api call to update the key was used, but that doesn't set the `budget_reset_at` so what's the right way to do this?

**Comment by ghost** [comment]
able to repro - happens when budget is set on `/key/update`

**Comment by ghost** [comment]
confirmed this works now 
<img width="1151" alt="Screenshot 2024-07-24 at 3 00 58 PM" src="https://github.com/user-attachments/assets/34363764-64f9-481d-917c-eb3d2c506ae8">

**Comment by taralika** [comment]
we'll try out `budget_reset_at` once we take the new version

as for tpm_limit and rpm_limit, the issue was that we have litellm deployed via k8s which has 3 pods, so the limits were per pod, this was fixed by turning on redis cache and since we didn't want caching of llm calls, we ended up doing this:
```
cache: true
cache_params: # set cache params for redis
    type: redis
    namespace: "xyz-litellm-cache"
    ttl: 600 # will be cached on redis for 600s
    supported_call_types: [] # no call types will be cached, just turning cache on for tpm/rpm limits
```
Feel free to close this issue.
