### ISSUE TITLE
[Bug]: UI - Azure Ai Studio not allowing entering model name.

### ISSUE THREAD

**Issue by Gyarbij** [BerriAI/litellm#4851]
### What happened?

As the title says, i get a list of three drops downs without the ability to enter the actual deployment.

**Comment by ghost** [comment]
@Gyarbij can you share a screenshot? this looks fine to me 

<img width="1497" alt="Screenshot 2024-07-24 at 8 19 21 AM" src="https://github.com/user-attachments/assets/a85c034b-768a-462b-b329-ddf75109436e">

**Comment by Gyarbij** [comment]
![Screenshot_24-7-2024_20448](https://github.com/user-attachments/assets/002ac6b6-a081-46e4-9aed-7114863aa296)
![Screenshot_24-7-2024_2051](https://github.com/user-attachments/assets/36ae240b-519d-42c9-8c6c-706846ddf035)
@krrishdholakia

**Comment by ishaan-jaff** [comment]
fixed here: https://github.com/BerriAI/litellm/pull/4951

**Comment by ishaan-jaff** [comment]
@Gyarbij 
<img width="1224" alt="Screenshot 2024-07-29 at 3 56 50 PM" src="https://github.com/user-attachments/assets/29e29404-3fd7-4840-b89b-c3217110eb6f">
<img width="1274" alt="Screenshot 2024-07-29 at 3 56 58 PM" src="https://github.com/user-attachments/assets/5fcbd8f4-c986-4454-af5b-df95c677b3b0">

**Comment by ishaan-jaff** [comment]
Hi @Gyarbij , curious do you use LiteLLM Proxy in production today If so, I'd love to hop on a call and learn how we can improve LiteLLM for you

my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
my linkedin if you prefer DMs: https://www.linkedin.com/in/reffajnaahsi/

**Comment by Gyarbij** [comment]
> Hi @Gyarbij , curious do you use LiteLLM Proxy in production today If so, I'd love to hop on a call and learn how we can improve LiteLLM for you
> 
> my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
> my linkedin if you prefer DMs: https://www.linkedin.com/in/reffajnaahsi/

Yes I do and it's no problem, I'll check the Cal, later on but I've sent you a req on LinkedIn as its faster to arrange something there.
