### ISSUE TITLE
[Feature]: Add support for huggingface chat templating

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#487]
### The Feature

Huggingface now has chat templating for a bunch of open source models (including the new mistral ones), I think it's fairly important that we add support for this. 

https://huggingface.co/docs/transformers/main/chat_templating

### Motivation, pitch

Ensure we give users good results

**Comment by ghost** [comment]
also being used by the mistral models currently being used by quivr

**Comment by ishaan-jaff** [comment]
this is done right @krrishdholakia ?

**Comment by ghost** [comment]
yes
