### ISSUE TITLE
[Bug]: clean up any bos and eos tokens showing up in messages

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#488]
### What happened?

<img width="272" alt="Screenshot 2023-09-28 at 3 58 28 PM" src="https://github.com/BerriAI/litellm/assets/17561003/07a70028-4685-4815-9b3f-dcddd159abb4">

### Relevant log output

```shell
repro by using https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.1

with litellm
```

**Comment by ghost** [comment]
cc: @StanGirard

**Comment by ishaan-jaff** [comment]
should we be cleaning out the output by default ? or should the users opt in to this ?

**Comment by ghost** [comment]
this is now resolved - @ishaan-jaff it was a streaming issue, and caused by a bug with how we were reading an end of stream. Now we don't do a manual cleanup - just stop when stream ends correctly, and that fixes this.
