### ISSUE TITLE
[Bug]: Authentication Error, No connected db.

### ISSUE THREAD

**Issue by merlijn** [BerriAI/litellm#4880]
### What happened?

I am encountering an error when trying trying to do api calls
```
 curl -H "Authorization: Bearer <MY_LITELLM_TOKEN>" localhost:4000/v1/models
 
 {"error":{"message":"Authentication Error, No connected db.","type":"auth_error","param":"None","code":401}}
```
What could be wrong, I don't want to use a db, I am following the "Basic (no DB)"  docs.

I am starting the docker image like this
```
docker run -v $(pwd)/my_config.yaml:/app/config.yaml --env-file ./.env -p 4000:4000 ghcr.io/berriai/litellm:main-latest
```
The `.env` file looks like this
```
LITELLM_MASTER_KEY="<MY_LITELLM_TOKEN>"
OPENAI_API_KEY="<MY_OPENAI_API_KEY>"
```
The config file looks like this
```
model_list:
  - model_name: "*"
    litellm_params:
      model: "openai/*"
```

### Relevant log output

```shell
18:14:52 - LiteLLM Proxy:ERROR: user_api_key_auth.py:1192 - litellm.proxy.proxy_server.user_api_key_auth(): Exception occured - No connected db.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/auth/user_api_key_auth.py", line 530, in user_api_key_auth
    raise Exception("No connected db.")
Exception: No connected db.

INFO:     172.17.0.1:38414 - "GET /v1/models HTTP/1.1" 401 Unauthorized
```

**Comment by ghost** [comment]
> LITELLM_MASTER_KEY="<MY_LITELLM_TOKEN>"

if you set a master key, and the api key passed in is not the master key, then we assume it's a key created from the db, and are making a check from there.

**Comment by ghost** [comment]
to solve this, either make the request with the master key or remove the master key

**Comment by merlijn** [comment]
I am confused, I thought I was using the master key in the curl request? I think in my code examples the wording was a bit off. I actually did this. 
```
curl -H "Authorization: Bearer <MY_LITELLM_MASTER_KEY>" localhost:4000/v1/models
```
and in the `.env`
```
LITELLM_MASTER_KEY="<MY_LITELLM_MASTER_KEY>"
```

Anyway, for my use case authentication is not really required so I think I will opt to remove it for now. 

Thank you for your answer!
