### ISSUE TITLE
[Feature]: Unified API for prefill/prefix to stuff the start of the assistant's chat response

### ISSUE THREAD

**Issue by paul-gauthier** [BerriAI/litellm#4881]
### The Feature

Claude models allow you to "prefill" the start of the assistant's response. Now DeepSeek has a beta of similar "prefix" functionality (see link and translation below).

Have you considered having litellm provide a unified API for this very useful functionality?

Translation of [deepseek's announcment](https://platform.deepseek.com/api-docs/news/news0725/#3-%E5%AF%B9%E8%AF%9D%E5%89%8D%E7%BC%80%E7%BB%AD%E5%86%99beta%E6%9B%B4%E7%81%B5%E6%B4%BB%E7%9A%84%E8%BE%93%E5%87%BA%E6%8E%A7%E5%88%B6) below.

> 3. Dialogue prefix continuation (Beta), more flexible output 
The conversation prefix continuation follows the API format of [conversation completion](https://platform.deepseek.com/api-docs/api/create-chat-completion) , allowing users to specify the prefix of the last assistant message so that the model can complete the message according to the prefix. This function can also be used to max_tokenssplice truncated messages after the output length reaches truncated, and resend the request to continue the truncated content.

> To use the conversation prefix continuation feature, you need to:

> Set base_urlto to https://api.deepseek.com/betaenable Beta features
Make sure that the last message in the messages list roleis assistant, and set the parameter of the last message prefixto True, such as:{"role": "assistant": "content": "在很久很久以前，", "prefix": True}

> The following is an example of using the conversation prefix continuation feature. In this example, the assistant message starts with '```python\n', to force it to start with a code block, and the stop parameter is set to '```', so that the model does not output redundant content.

### Motivation, pitch

Models like Claude 3.5 Sonnet can now output so much quality code that they exceed the output token limit. It seems like the latest Deepseek is approaching that level of code quality.

The prefill/prefix feature makes it possible to seamlessly continue the assistant's response when it hits the output token limit.

See the aider blog for a discussion of this topic wrt Sonnet:

https://aider.chat/2024/07/01/sonnet-not-lazy.html

**Comment by ghost** [comment]
hey @paul-gauthier how would you want something like this to work? (psuedo code would be helpful!)

**Comment by ghost** [comment]
seems related to this: https://github.com/BerriAI/litellm/issues/4882

**Comment by paul-gauthier** [comment]
Anthropic has a good API for this. You simply send the chat messages with the final message as `role="assistant"` and `content="...whatever you want to prefill..."`.

It would be very powerful if litellm accepted such chat completion requests and adapted them to whatever prefill/prefix API the underlying provider supports.

**Comment by ghost** [comment]
got it - i understand the recommendation here to be to follow how anthropic handles this? @paul-gauthier

**Comment by ghost** [comment]
will try to do a v0 on this today

**Comment by paul-gauthier** [comment]
Just checking back to see if you're likely to support this feature?

**Comment by ghost** [comment]
yup - i'll pick this up today @paul-gauthier

**Comment by ghost** [comment]
apologies for the delay on this - working on it today

got pushed back due to the openai json_schema announcement.

**Comment by ghost** [comment]
For v0, aiming to cover: 
- deepseek
- mistral
- anthropic

**Comment by ghost** [comment]
Deepseek has a `prefix:bool` param in their assistant message - 
<img width="781" alt="Screenshot 2024-08-10 at 1 10 17 PM" src="https://github.com/user-attachments/assets/a9a0c296-327c-4d51-902b-7018c1fcbe12">


Mistral has a `prefix:bool` param in their assistant message - 
<img width="722" alt="Screenshot 2024-08-10 at 1 11 14 PM" src="https://github.com/user-attachments/assets/c383a3ef-9510-46b6-9636-7d17621ad58c">

Claude just lets you pass in an assistant message as the last message and assumes it's a prefix 
<img width="807" alt="Screenshot 2024-08-10 at 1 11 54 PM" src="https://github.com/user-attachments/assets/7b65dda6-a75e-4364-a6d3-0ceb04b70b72">

**Comment by ghost** [comment]
Checking how deepseek/mistral react to last message being an assistant message, when `prefix` is not set ..

**Comment by ghost** [comment]
Deepseek call still works -> **we need user to specify if this is a prefix**
<img width="1187" alt="Screenshot 2024-08-10 at 1 14 51 PM" src="https://github.com/user-attachments/assets/59af3607-b0f0-4feb-a90f-266d3fe5b425">

**Comment by ghost** [comment]
This seems reasonable, we can just allow the user to specify if `prefix: True` and drop it for the anthropic call

**Comment by ghost** [comment]
this feels like something that should already work

**Comment by ghost** [comment]
`prefix: true` already automatically dropped when calling anthropic 
<img width="1163" alt="Screenshot 2024-08-10 at 1 17 44 PM" src="https://github.com/user-attachments/assets/0d66d26f-1f1a-4e03-9351-163a4131bc73">

**Comment by ghost** [comment]
I'll add a doc on this - is there anything else you think we should do here? @paul-gauthier

**Comment by ghost** [comment]
Will add this to our model info map, so you can use `.get_model_info()` to check if a model/provider supports prefix

**Comment by paul-gauthier** [comment]
Thanks, this looks great.

Is litellm supposed to respect the `DEEPSEEK_API_BASE` env var? It looks like the code does `get_secret("DEEPSEEK_API_BASE")`. But it doesn't seem to actually read it from the env?

This code:

```
model = "deepseek/deepseek-coder"
message = "What is a famous quote from literature?"
messages=[
    {"role": "user", "content": message},
    {"role": "assistant", "content": "It was the best", "prefix": True},
]
comp = litellm.completion(model=model, messages=messages)
```

Throws this error even with `export DEEPSEEK_API_BASE=https://api.deepseek.com/beta`:

```
litellm.exceptions.BadRequestError: litellm.BadRequestError: DeepseekException - Error code: 400 - {'error': {'message': 'prefix is only available when using beta api (set base_url="https://api.deepseek.com/beta")', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_request_error'}}
```


But explicitly setting `base_url=os.environ["DEEPSEEK_API_BASE"]` makes it work fine.

**Comment by ghost** [comment]
which version is this? @paul-gauthier - i can see even our default deepseek url uses `/beta` https://github.com/BerriAI/litellm/blob/fdd9a070514921539395d06db6f43dbfcf6efa04/litellm/utils.py#L4588

so even if it wasn't being respected (which it is - here's our test - https://github.com/BerriAI/litellm/blob/fdd9a070514921539395d06db6f43dbfcf6efa04/litellm/tests/test_get_llm_provider.py#L61) 

it should still work

**Comment by ghost** [comment]
do you have the older deepseek url somewhere in your env?

**Comment by paul-gauthier** [comment]
I was on an older version, sorry. On `litellm==1.43.7` deepseek does prefill without me needing to touch the base url.

But I can't find `supports_assistant_prefill` in any model info entries. Not for deepseek or sonnet. I see that data in the json file in the main branch though.

These all fail with a `KeyError`

```
params = get_model_info(model="deepseek/deepseek-chat")
assert params["supports_assistant_prefill"] is True

params = get_model_info(model="deepseek/deepseek-coder")
assert params["supports_assistant_prefill"] is True

params = get_model_info(model = "anthropic/claude-3-5-sonnet-20240620")
assert params["supports_assistant_prefill"] is True
```

**Comment by ghost** [comment]
hmm i can see this passes our testing as well - @paul-gauthier 

https://github.com/BerriAI/litellm/blob/fdd9a070514921539395d06db6f43dbfcf6efa04/litellm/tests/test_get_model_info.py#L51

let me try this on a clean vm to confirm

**Comment by ghost** [comment]
oh! i think this missed the v`1.43.7` release train 

<img width="1706" alt="Screenshot 2024-08-12 at 3 49 22 PM" src="https://github.com/user-attachments/assets/0cff5c6d-c33f-4542-bc7e-de9ad0ddbe4f">

Will be live by eod today @paul-gauthier 

bumping version now

**Comment by paul-gauthier** [comment]
Ok, thanks for all the help with this!

**Comment by ghost** [comment]
Thanks for using litellm!
