### ISSUE TITLE
[Feature]: Support `prefix` in Mistral AI API

### ISSUE THREAD

**Issue by jmpaz** [BerriAI/litellm#4882]
https://docs.mistral.ai/guides/prefix/

In Mistral's API, `prefix` needs to be set when the last message is an assistant message. `litellm.completion` doesn't seem to include this when calling the API.

I believe it would be nice to support passing this if specified, and/or automatically set `prefix` for the user when the last message in the messages list is an assistant message.

**Comment by ghost** [comment]
> > needs to be set when the last message is an assistant message 

Hi @jmpaz, can you share a code snippet to repro the error you're seeing? 


> it would be nice to support passing this if specified, and/or automatically set prefix for the user when the last message in the messages list is an assistant message

Reading docs now, how is a prefix is different from a normal assistant message?
