### ISSUE TITLE
[Bug]: logfire integration calls load_dotenv() no matter what

### ISSUE THREAD

**Issue by entropi** [BerriAI/litellm#4888]
### What happened?

[It appears](https://github.com/BerriAI/litellm/blob/711496e2600adc8510d6f0cdc8f0a482856b3e4c/litellm/integrations/logfire_logger.py#L8) that the logfire integration calls load_dotenv() no matter what.

I strongly prefer that no third party library (including the litellm module) ever call `load_dotenv()` on my process's behalf since it can have such broad impact on the operating process, instead simply letting me know what environment variables I can set for configuration and I can choose to use load_dotenv() if I want to in my operating environment.

Regardless, I believe at a bare minimum this load probably should be wrapped in the same check for LITELLM_MODE that the core module uses (though I'd still prefer its removal and just expect environment variables however they may be set, but I'll take what I can get ;) ).

Thanks!

**Comment by ishaan-jaff** [comment]
fixed here: https://github.com/BerriAI/litellm/pull/4894 

I believe we need a linting check to make sure we don't call `load_dotenv`

**Comment by ishaan-jaff** [comment]
tracking the linting check for `load_dotenv` usage here: https://github.com/BerriAI/litellm/issues/4895

**Comment by entropi** [comment]
Thank you for the quick fix!
