### ISSUE TITLE
[Feature]: easy repro of http requests

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#489]
### The Feature

make it easy for me to see what the original http request was (maybe even a pretty print in curl) when i set `litellm.set_verbose = True`

### Motivation, pitch

I was trying to debug my huggingface starcoder call. I had set temperature to 0.0001 and was seeing empty results. I wasn't sure if this was a huggingface issue or a litellm issue. Huggingface has really poor documentation of how to call their inference endpoint, and so it took me 30mins - 1 hr to reconstruct the http call litellm was actually making and then make it - figure out the problem (huggingface doesn't handle extremely low temperatures well) and set it to an acceptable number.

**Comment by namansharma18899** [comment]
Hey @krrishdholakia I don't unerstand why you would need a curl when you would ( supposedly ) have a stacktrace or a tracebuffer of the whole transaction. The params, auth headers, api-key etc. are all passed as variables to **huggingface_restapi.completion( )** so why need an explicit curl ??

Maybe I'm missing a point, please feel free to correct me.

**Comment by ghost** [comment]
When the response fails - it's just helpful to know what the exact call being made is. Open to your thoughts on this @namansharma18899

**Comment by ghost** [comment]
+1 for this pain again. felt it while reading proxy logs. there's a lot of junk. just need to know exactly what got sent (in exact format) to the llm api, so i can repro the call on my end. just need this saved easily in our logger object, so i can access it.

**Comment by ishaan-jaff** [comment]
we do this now, you can see the POST request with litellm.set_verbose=True
