### ISSUE TITLE
(docs) add docs on how to use stream=true, acompletion

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#49]

**Comment by ghost** [comment]
even setting api_base etc.

**Comment by ghost** [comment]
stuff you can control via variables in __init__.py

**Comment by ghost** [comment]
also need docs on logging / observability

**Comment by ishaan-jaff** [comment]
cc @krrishdholakia closing this since docs on using stream and acompletion are added

**Comment by ghost** [comment]
@ishaan-jaff 
![alt text](https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExenB1cWIwdnRtaTE5NXZ1ZWhoaG0yNmpvOGNlbG54NmVzNzFzNHdwZSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/5t1YusAYxmRn474Sid/200.gif)
