### ISSUE TITLE
[Bug]: Batches API not working via litellm proxy

### ISSUE THREAD

**Issue by haley-keplar** [BerriAI/litellm#4902]
### What happened?

When testing Batches API with the litellm proxy, I get back this response:

```{"error":{"message":"acreate_batch() missing 3 required positional arguments: 'completion_window', 'endpoint', and 'input_file_id'","type":"None","param":"None","code":500}}%```

This is from copying the example curl command in the official documentation with the correct fields. This is possibly because of the usage of `form_data = await request.form()` instead of `form_data = await request.json()` in https://github.com/BerriAI/litellm/blob/b376ee71b01e3e8c6453a3dd21421b365aaaf9f8/litellm/proxy/proxy_server.py#L4777

The arguments in -d flag are not retrieved properly. 

### Relevant log output

```shell
{"error":{"message":"acreate_batch() missing 3 required positional arguments: 'completion_window', 'endpoint', and 'input_file_id'","type":"None","param":"None","code":500}}%
```

**Comment by ishaan-jaff** [comment]
looking into this @haley-keplar

**Comment by ishaan-jaff** [comment]
fixed here: https://github.com/BerriAI/litellm/pull/4914

**Comment by ishaan-jaff** [comment]
this is fixed - should be live in tonights litellm release

@haley-keplar @bill-keplar could we hop on a call sometime this week?  I'd love to learn how we can improve litellm for your use case + setup a 1:1 support channel 

Link to my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
If you prefer DMs 
- My linkedin: https://www.linkedin.com/in/reffajnaahsi/
- LiteLLM Discord (just wave and i'll dm you) : https://discord.com/invite/wuPM9dRgDw
