### ISSUE TITLE
[Feature]: Include `prompt_tokens` when streaming

### ISSUE THREAD

**Issue by petergchang** [BerriAI/litellm#4904]
### The Feature

Currently, when using `completion` or `acompletion` with `stream=True`, the resulting streaming responses do not include the token counts. AFAICT, the `prompt_tokens` count should be independent of the choice to stream, if this could be included in the streamed response that'd be great.

### Motivation, pitch

In our code, we have to use a custom prompt token counter when `stream = True`, which feels awkward and if there could be a `litellm` native solution for this, that'd be awesome!

**Comment by ghost** [comment]
hi @petergchang, this is already supported 

just set `stream_options: {"include_usage": true}` 

this is the same flow as openai (helps maintain compatibility with existing client code)

**Comment by petergchang** [comment]
Ah my bad, thanks for letting me know!
