### ISSUE TITLE
[Bug]: `acompletion.stream_options.include_usage` not working with Anthropic models.

### ISSUE THREAD

**Issue by petergchang** [BerriAI/litellm#4905]
### What happened?

`litellm.completion` works as expected:
```py
response1 = litellm.completion(
    model = "claude-3-5-sonnet-20240620", 
    messages=[
        {
            "role": "user",
            "content": [
                {
                    "type": "text",
                    "text": "Hello world."
                },
            ]
        }
    ],
    stream=True,
    stream_options = {
        "include_usage": True,
    }
)
```
the last chunk includes a `Usage` object with the token counts.

But if we use `litellm.acompletion`:
```py
response2 = await litellm.acompletion(
    model = "claude-3-5-sonnet-20240620", 
    messages=[
        {
            "role": "user",
            "content": [
                {
                    "type": "text",
                    "text": "Hello world."
                },
            ]
        }
    ],
    stream=True,
    stream_options = {
        "include_usage": True,
    }
)
```
the `Usage` object is not included in the streamed response. This seems to be an Anthropic-specific issue, since if we use openai models, the `Usage` object is included in both `completion` and `acompletion` outputs.

**Comment by ghost** [comment]
unable to repro, this works just fine for me - 
<img width="814" alt="Screenshot 2024-07-27 at 9 40 59 AM" src="https://github.com/user-attachments/assets/b0f717b9-8e91-44c5-895f-5274ae867bc2">

@petergchang can you confirm you're on the latest version?

**Comment by ghost** [comment]
Tested on colab, can confirm it works there too - https://colab.research.google.com/drive/17iSOmM9a7hueiHRCpPmETxGz98lNVz_v?usp=sharing

<img width="916" alt="Screenshot 2024-07-27 at 9 44 57 AM" src="https://github.com/user-attachments/assets/c7838064-1d26-4998-8ece-9f0daa0f812b">

**Comment by petergchang** [comment]
Thanks @krrishdholakia - realized our litellm version has been pinned to `<=1.40.12` because of https://github.com/BerriAI/litellm/issues/4032
