### ISSUE TITLE
[Feature]: Allow custom prompt templates to be set for litellm proxy

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#491]
### The Feature

let user set custom prompt templates for litellm proxy

### Motivation, pitch

user request

**Comment by ghost** [comment]
cc: @abhinavkulkarni

**Comment by ghost** [comment]
This is now live 

```
litellm --config
```
opens up a model config - you can modify the model's specific prompt template and save it 

We will read this whenever you run 
```
litellm --model <your-model-name> .. 
```
again, for that model

**Comment by lukolszewski** [comment]
How to use this? When i run litellm --config I get:
Error: Option '--config' requires an argument.

As it is expecting a yaml file, but it is unclear how to add a prompt template in a yaml file.
