### ISSUE TITLE
[Bug]: Helm Chart - restart pod on config change

### ISSUE THREAD

**Issue by chris-sanders** [BerriAI/litellm#4910]
### What happened?

Updates to the configmap don't cause the pod to restart and litellm doesn't appear to live reload. You can set this up with an annotation based on the sha of the configmap.

I actually have an example of this you can see it here: https://github.com/replicatedhq/platform-examples/blob/af1f47c3a50fdb277c0cd409f4cc4e9e44c3adfc/applications/mlflow/charts/mlflow/templates/deployment.yaml#L44

That's the line where the annotation is added but you can see the configmap and helpers as well in the example repo.

**Comment by ishaan-jaff** [comment]
done here @chris-sanders https://github.com/BerriAI/litellm/pull/5318

**Comment by ishaan-jaff** [comment]
Hi @chris-sanders, curious do you use LiteLLM Proxy in production today If so, I'd love to hop on a call and learn how we can improve LiteLLM for you

- my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
- my linkedin if you prefer DMs: https://www.linkedin.com/in/reffajnaahsi/
