### ISSUE TITLE
[Bug]: Azure pass LiteLLM Proxy /health check on UI, but failed to use

### ISSUE THREAD

**Issue by xingyaoww** [BerriAI/litellm#4912]
### What happened?

I created an Azure deployment on LiteLLM proxy on Web UI, and run the `/health` check, it is displayed as healthy.

![8ead8752662ea23d95a97b4f2b03d17b](https://github.com/user-attachments/assets/8eb48c8a-929f-4419-aea4-8e0b3873d987)

Here's my model info:
```json
{
  "model_name": "gpt-4o-2024-05-13",
  "litellm_params": {
    "custom_llm_provider": "azure",
    "api_base": "https://XXXX.openai.azure.com",
    "api_version": "2024-06-01",
    "model": "azure/gpt-4o-2024-05-13"
  },
  "model_info": {
    "id": "bd21d5fe-c38f-4b1b-abb7-20cf98ea8b92",
    "db_model": true,
    "base_model": "azure/gpt-4o",
    "max_tokens": 4096,
    "max_input_tokens": 128000,
    "max_output_tokens": 4096,
```

Yet, when i make API calls locally to the litellm proxy, it doesn't work:
```python
import openai

client = openai.OpenAI(
    api_key="TODO_KEY",
    base_url="https://MYPROXYURL/"
)
MODEL = "gpt-4o-2024-05-13"

response = client.chat.completions.create(
    model=MODEL,
    messages = [
        {
            "role": "user",
            "content": "this is a test request, write a short poem"
        }
    ]
)
print(response)
print("="*100)
print(response.choices[0].message.content)
```

I got:

```
openai.NotFoundError: Error code: 404 - {'error': {'message': 'litellm.APIError: AzureException APIError - Resource not found\nReceived Model Group=gpt-4o-2024-05-13\nAvailable Model Group Fallbacks=None', 'type': None, 'param': None, 'code': 404}}
```

I am using

**Comment by ghost** [comment]
@xingyaoww it looks like this error is coming from azure. it's unclear to me what key is being used. can you check your server logs - `--detailed_debug` and look for something like this:

```
POST Request Sent from LiteLLM:
curl -X POST \
https://api.openai.com/v1/chat/completions \
-H 'content-type: application/json' -H 'Authorization: Bearer sk-qnWGUIW9****************************************' \
-d '{"model": "gpt-3.5-turbo", "messages": [{"role": "user", "content": "this is a test request, write a short poem"}]}'
```

can you use this to confirm if the right api key / base url / deployment name is being used for azure? 

Azure returns a 404 if any of these is incorrect. 

---
Also updated our debug docs with this- https://docs.litellm.ai/docs/proxy/debugging#debug-logs

Where would you have wanted to see this?

**Comment by xingyaoww** [comment]
Hey @krrishdholakia, thanks for the note!

I'm getting this from the debug log:
```
POST Request Sent from LiteLLM:
curl -X POST \
https://MYENDPOINT.openai.azure.com/openai/ \
-H 'Authorization: *****' \
-d '{'model': 'azure/gpt-4o-2024-05-13', 'messages': [{'role': 'user', 'content': 'this is a test request, write a short poem'}], 'stream': False, 'extra_body': {}}'
```


Is this expected? The API key and the endpoint URL is correct, but the "model" name does looks like weird. The deployment name should be "gpt-4o-2024-05-13" but not "azure/gpt-4o-2024-05-13".

What's weirder is that when I ran the `/health` check in the UI, I didn't spot requests to Azure in the log.

**Comment by xingyaoww** [comment]
Ok i think i figured it out...

![4262ee31a14c784fe9d095ce013c661c](https://github.com/user-attachments/assets/d45bdfdc-ab6d-4c13-8df3-397230a68192)

I should put in my deployment directly into the red box, instead of `azure/<my deployment name>'
After changing it, everything work as expected.

**Comment by xingyaoww** [comment]
Well, after switching from `azure/<my deployment name>` to `<my deployment name>` - now the `/health` check for azure model failed, but the API is actually usable.. I think it is probably a bug somewhere?

**Comment by seonghobae** [comment]
This is a symptom I'm experiencing too.

**Comment by ghost** [comment]
able to repro

**Comment by seonghobae** [comment]
In which version was this symptom resolved?

**Comment by ghost** [comment]
v1.43.0 @seonghobae

**Comment by seonghobae** [comment]
> v1.43.0 @seonghobae

Okay, I’ll wait to release that update;)

**Comment by ghost** [comment]
it's already live @seonghobae - https://github.com/BerriAI/litellm/releases

**Comment by seonghobae** [comment]
> it's already live @seonghobae - https://github.com/BerriAI/litellm/releases

Oh, it's not `litellm:main-stable` yet ;) 
I'll try that.
