### ISSUE TITLE
[Feature]: Add budget manager to local proxy

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#492]
### The Feature

create spend-limited keys for the proxy, so you can use it in applications and make sure you don't get a high bill for a hosted endpoint

### Motivation, pitch

if i'm testing a new project and don't want to get a crazy bill, creating a budgeted key seems like a good way to do it. 

All the openai calls require you to set an api key anyways, so why not use it

**Comment by ghost** [comment]
this should probably be optional though, so maybe by default use a general key / don't care what it is, but if it's one of the budgeted ones then use the logic

**Comment by ghost** [comment]
closing as the local/cli proxy is deprecated.
