### ISSUE TITLE
[Bug]: Fireworks fine-tuned model not found

### ISSUE THREAD

**Issue by psimm** [BerriAI/litellm#4923]
### What happened?

Hi, I would like to use litellm with a fine-tuned model deployed on Fireworks AI but it fail to find the model.

- When I run a completion with the fine-tuned model with litellm I get the error message 404 model not found
- Using a standard model like llama-v3-70b-instruct works
- Calling the fine-tuned model directly with requests works

Code example with litellm and directly with requests:

```python
import os
import requests
from litellm import completion

model = "accounts/paul-simmering-bad0cc/models/absa-sample" # this doesn't work with litellm
model2 = "accounts/fireworks/models/llama-v3-70b-instruct" # this works with litellm
prompt = "the food is great"

response = completion(
    model="fireworks_ai/" + model,
    messages=[{"role": "user", "content": prompt}],
)
print(response)


# Making a direct request works
response = requests.post(
    "https://api.fireworks.ai/inference/v1/completions", 
    headers={
        "Authorization": f"Bearer {os.environ["FIREWORKS_AI_API_KEY"]}",
        "Content-Type": "application/json",
    },
    json={"model": model, "prompt": prompt},
)

response.content
```

### Relevant log output

```shell
NotFoundError: litellm.NotFoundError: NotFoundError: Fireworks_aiException - Error code: 404 - {'error': 'Model not found'}
```

**Comment by ghost** [comment]
hi @psimm when you set `litellm.set_verbose=True` what's the raw request you see? 

is the correct model being called?

**Comment by psimm** [comment]
Logs with `litellm.set_verbose=True`

22:59:00 - LiteLLM:WARNING: utils.py:350 - `litellm.set_verbose` is deprecated. Please set `os.environ['LITELLM_LOG'] = 'DEBUG'` for debug logs.

Request to litellm:
litellm.completion(model='fireworks_ai/accounts/paul-simmering-bad0cc/models/absa-sample', messages=[{'role': 'user', 'content': 'the food was great'}])


SYNC kwargs[caching]: False; litellm.cache: None; kwargs.get('cache')['no-cache']: False
Final returned optional params: {'extra_body': {}}

POST Request Sent from LiteLLM:
curl -X POST \
https://api.fireworks.ai/inference/v1/ \
-d '{'model': 'accounts/fireworks/models/accounts/paul-simmering-bad0cc/models/absa-sample', 'messages': [{'role': 'user', 'content': 'the food was great'}], 'extra_body': {}}'


openai.py: Received openai error - Error code: 404 - {'error': 'Model not found'}
RAW RESPONSE:
Error code: 404 - {'error': 'Model not found'}

---

`accounts/fireworks/models/accounts/paul-simmering-bad0cc/models/absa-sample` is not correct. It should be `accounts/paul-simmering-bad0cc/models/absa-sample`. The problem is that `accounts/fireworks/models/` is added at the start

**Comment by ghost** [comment]
i see the issue. Pushing a fix + adding test to prevent future regressions.
