### ISSUE TITLE
Fix "gpt-4o" entry in "model_prices_and_context_window.json"

### ISSUE THREAD

**Issue by dleen** [BerriAI/litellm#4930]
Hey team, I was using the very nice max_tokens filter, and I noticed that no openai/gpt models show up when filtering by >= 100,000. But gpt-4o is 128k. I think the issue is:

```
  "max_tokens": 4096,
  "max_input_tokens": 128000,
  "max_output_tokens": 4096,
  ```

Not entirely sure what `max_tokens` means in this context. If you compare to llama 3.1:

```
  "max_tokens": 128000,
  "max_input_tokens": 128000,
  "max_output_tokens": 4096,
  ```

How is it computed from input/output tokens?

-----

https://github.com/BerriAI/litellm/blob/21eea287230af8cc7f4a45a348f7a4e9b1323a2d/model_prices_and_context_window.json#L12-L23

We also need to update [model_prices_and_context_window_backup.json](https://github.com/BerriAI/litellm/blob/21eea287230af8cc7f4a45a348f7a4e9b1323a2d/litellm/model_prices_and_context_window_backup.json).

**Comment by ghost** [comment]
max_tokens = max_output_tokens @dleen 

it's the openai param - https://platform.openai.com/docs/api-reference/chat/create#chat-create-max_tokens

it's a legacy param on the model map, but we maintain it to avoid breaking changes for people

**Comment by ghost** [comment]
what would have been useful to see here? should we have a legend on the site? @dleen

**Comment by ishaan-jaff** [comment]
<img width="1263" alt="Screenshot 2024-07-29 at 8 45 57 AM" src="https://github.com/user-attachments/assets/ba117307-c425-4ff6-85b6-405fb51c2c80">


for context this is the issue @dleen is referring too

**Comment by ishaan-jaff** [comment]
the filter on `model.litellm.ai` is checking `max_tokens`

**Comment by ghost** [comment]
oh - my bad, thanks for the call out @ishaan-jaff

**Comment by ghost** [comment]
just fixed it - https://github.com/fastrepl/contextlengthof/commit/9a56646605fde1d03d2ebc10988232be88fcf698

it should now let you filter by input / output tokens
