### ISSUE TITLE
Error when using trim_messages and tool calling

### ISSUE THREAD

**Issue by aantn** [BerriAI/litellm#4931]
When using trim_messages and tool calling, the trimming can remove the message requesting a tool call, which makes a response with tool call results invalid:

```
openai.py: Received openai error - Error code: 400 - {'error': {'message': "Invalid         main.py:4607
parameter: messages with role 'tool' must be a response to a preceeding message with                    
'tool_calls'.", 'type': 'invalid_request_error', 'param': 'messages.[1].role', 'code':              
```

**Comment by ghost** [comment]
hey @aantn can you give me a sample call for repro

**Comment by ghost** [comment]
Was able to repro + fixed. we now check if the last messages are tool calls, and ignore them from the trimming 

let me know if there's a better way for us to handle this @aantn

**Comment by aantn** [comment]
Thanks, I will test as soon as there is a new release that includes this.

**Comment by almajo** [comment]
I ran into an issue today regarding this.

```bash
litellm.exceptions.BadRequestError: litellm.BadRequestError: Azure_aiException - Error code: 400 - {'object': 'Error', 'message': 'Expected last role to be one of: [tool, user] but got assistant', 'type': 'invalid_request_error', 'code': 3230}
````

The reason is because in `trim_messages` we remove the tool results (line 11156): 

```python
# # Remove the collected tool messages from the original list
        if len(tool_messages):
            messages = messages[: -len(tool_messages)]
```

Why would this be done @krrishdholakia ? This needs to be reopened

**Comment by ghost** [comment]
Hey @almajo tool messages are passed in as-is https://github.com/BerriAI/litellm/blob/afb00a27cbd139722bd9532f0fe951b9055b6393/litellm/utils.py#L11149

if you look further down, you'll see they're re-added back to the final list 

https://github.com/BerriAI/litellm/blob/afb00a27cbd139722bd9532f0fe951b9055b6393/litellm/utils.py#L11191

---

If you're seeing an error can you file a new issue with a sample code snippet for repro?
