### ISSUE TITLE
[Bug]: Router Providing None Completions

### ISSUE THREAD

**Issue by bhairavmehta95** [BerriAI/litellm#4932]
### What happened?

Switched to `Router` over `completion`, and started to see weird behavior inside of the router.completion calls sometimes returning `None`, having never had this issue when using raw LLM APIs or ever `litellm.completion`. When enabling DEBUG logs, I can see that the call was generated correctly, and even the response object looks fine 

```
{"id": "chatcmpl-9q05hGr8uoUA59znUVDbKMtQEP4ik", "choices": [{"finish_reason": "stop", "index": 0, "logprobs": null, "message": {"content": null, "role": "assistant", "function_call": null, "tool_calls": [{"id": "call_g1wKDjUI2SqLg2MDKFTaVch2", "function": {"arguments": "{\"works_at_company\":true,\"accurate_company_match\":true,\"persona_profile_fit\":\"medium\"}", "name": "WorksAtCompanyResult"}, "type": "function"}]}}], "created": 1722180433, "model": "gpt-4o-mini-2024-07-18", "object": "chat.completion", "system_fingerprint": "fp_ba606877f9", "usage": {"completion_tokens": 20, "prompt_tokens": 3774, "total_tokens": 3794}}
```

But when it returns back from:

```
response = router.completion(updated_model, messages, temperature=temperature)
return response["choices"][0]["message"]["content"]
```

I **sometimes** get back `None`.  I don't always see Nones, rather, the first few calls I get the correct output (in my case, a JSON dictionary with three keys) returned from the router.

I don't see an error coming from LiteLLM regarding that I'm being rate limited (especially since in the debug logs, I seem to be actually getting the response back).

### Relevant log output

```shell
model_list = [
    {  # list of model deployments
        "model_name": "json-output",  # model alias -> loadbalance between models with same `model_name`
        "litellm_params": {  # params for litellm completion/embedding call
            "model": "gpt-4o-mini",  # actual model name
            "api_key": os.getenv("OPENAI_API_KEY"),
        },
    },
    {
        "model_name": "json-output",
        "litellm_params": {  # params for litellm completion/embedding call
            "model": "gpt-4o",
            "api_key": os.getenv("OPENAI_API_KEY"),
        },
    },
    {
        "model_name": "reasoning",
        "litellm_params": {  # params for litellm completion/embedding call
            "model": "claude-3-5-sonnet-20240620",
            "api_key": os.getenv("ANTHROPIC_API_KEY"),
        },
    },
    {
        "model_name": "reasoning",
        "litellm_params": {  # params for litellm completion/embedding call
            "model": "claude-3-5-sonnet-20240620",
            "api_key": os.getenv("ANTHROPIC_CHARACTERQUILT_API_KEY"),
        },
    },
    {
        "model_name": "reasoning",
        "litellm_params": {  # params for litellm completion/embedding call
            "model": "vertex_ai_beta/gemini-pro",
            "vertex_credentials": os.getenv("VERTEX_CREDENTIALS_JSON"),
        },
    },
    {
        "model_name": "reasoning",
        "litellm_params": {  # params for litellm completion/embedding call
            "model": "gpt-4o",
            "api_key": os.getenv("OPENAI_API_KEY"),
        },
    },
    {
        "model_name": "long-context",
        "litellm_params": {  # params for litellm completion/embedding call
            "model": "vertex_ai_beta/gemini-pro",
            "vertex_credentials": os.getenv("VERTEX_CREDENTIALS_JSON"),
        },
    },
]


load_vertex_ai_credentials()
router = Router(
    model_list=model_list,
    fallbacks=[
        {"reasoning": ["long-context"]},
        {"json-output": ["long-context"]},
    ],
)
```

**Comment by ghost** [comment]
hey @bhairavmehta95 can you run the query with `litellm.set_verbose=True`? 

If you're seeing a None response, it would help to see the trace for the None call

**Comment by ghost** [comment]
Oh wait, 

> {"id": "chatcmpl-9q05hGr8uoUA59znUVDbKMtQEP4ik", "choices": [{"finish_reason": "stop", "index": 0, "logprobs": null, "message": {"content": null, "role": "assistant", "function_call": null, "tool_calls": [{"id": "call_g1wKDjUI2SqLg2MDKFTaVch2", "function": {"arguments": "{\"works_at_company\":true,\"accurate_company_match\":true,\"persona_profile_fit\":\"medium\"}", "name": "WorksAtCompanyResult"}, "type": "function"}]}}], "created": 1722180433, "model": "gpt-4o-mini-2024-07-18", "object": "chat.completion", "system_fingerprint": "fp_ba606877f9", "usage": {"completion_tokens": 20, "prompt_tokens": 3774, "total_tokens": 3794}}

your example shows a None in the content 


this makes sense to me, 

you're indexing into `["content"] 

> return response["choices"][0]["message"]["content"]

and content is null - `{"content": null,..}`

what should happen here? @bhairavmehta95 

Closing for now, as this doesn't seem like a bug. Please reopen/bump me if i'm mistaken here
