### ISSUE TITLE
[Bug]: Llama 3.1 405b can't go over 4097 tokens on Together.ai

### ISSUE THREAD

**Issue by ryunuck** [BerriAI/litellm#4934]
### What happened?

I don't think that's normal, context window for this model is 128k

### Relevant log output

```shell
BadRequestError: litellm.BadRequestError: Together_aiException - Error code: 400 - {'error': {'message': 'Input validation
error: `inputs` tokens + `max_new_tokens` must be <= 4097. Given: 80125 `inputs` tokens and 4096 `max_new_tokens`', 'type':
'invalid_request_error', 'param': 'max_tokens', 'code': None}}
```
```


### Twitter / LinkedIn details

_No response_

**Comment by aella-m** [comment]
@ryunuck Together Ai has a smaller context size for llama 3.1 405b, as seen here -> https://docs.together.ai/docs/chat-models
This seems to be why you face this issue.

**Comment by ishaan-jaff** [comment]
this is from Together AI not LiteLLM. Verify by running with `litellm.set_verbose=True`
