### ISSUE TITLE
[Feature]: Bedrock's guardrails with LiteLLM 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#4938]
### The Feature

<img width="551" alt="Screenshot 2024-07-29 at 7 45 15 AM" src="https://github.com/user-attachments/assets/42e268b6-16c1-4677-999e-c29fb987cd0f">

User wants to do this: [Use a guardrail with the Converse API - Amazon Bedrock](https://docs.aws.amazon.com/bedrock/latest/userguide/guardrails-use-converse-api.html)

### Motivation, pitch

-

**Comment by Manouchehri** [comment]
Duplicate of https://github.com/BerriAI/litellm/issues/3879#issuecomment-2135571027.

Confirmed solved in https://github.com/BerriAI/litellm/issues/3879#issuecomment-2143346496.

**Comment by ishaan-jaff** [comment]
added here: https://docs.litellm.ai/docs/providers/bedrock#usage---bedrock-guardrails
