### ISSUE TITLE
[Feature]: map finish reason across providers

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#494]
### The Feature

different providers return different finish reasons 

This makes it hard to do take action based on the finish reason (e.g. - 
<img width="609" alt="Screenshot 2023-09-29 at 8 49 48 AM" src="https://github.com/BerriAI/litellm/assets/17561003/22d198c3-4e47-4cc3-bcb4-675bd876208b">)

Map finish reason across providers (similar to exception mapping)

### Motivation, pitch

improve users lives

**Comment by ghost** [comment]
cc: @yujonglee

**Comment by yujonglee** [comment]
Thank you for raising this.

For OpenAI, they have `stop`, `length`, `function_call`, `content_filter`, and `null`. (https://platform.openai.com/docs/guides/gpt/chat-completions-response-format)

I am not sure that reasons other than `stop` and `length` can be mapped for other providers. 
(Maybe `null` too?)

But honestly, all I care about is the `length`.

**Comment by ghost** [comment]
this is now supported - https://github.com/BerriAI/litellm/blob/d0c89ddbe3a69b8ffef9c717446dbb97bd55e3a6/litellm/litellm_core_utils/core_helpers.py#L5
