### ISSUE TITLE
can not get response from completion

### ISSUE THREAD

**Issue by YPH015** [BerriAI/litellm#4958]
after i call the completion， i get 
Request to litellm:
11:58:21 - LiteLLM:WARNING
POST Request Sent from LiteLLM:
and this：
Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Logging Details: logger_fn - None | callable(logger_fn) - False

，but this call not get the response， pls give me some advice？

**Comment by ghost** [comment]
Hi @YPH015 closing this ticket. please create one with a specific issue + steps to repro. 

Are you on the latest version of litellm? The 'POST Request Sent from LiteLLM:' i see in code is a debug message - https://github.com/BerriAI/litellm/blob/c64b44aa0eb9f2338ca02ca4fb18d9225905e3ca/litellm/litellm_core_utils/litellm_logging.py#L308
