### ISSUE TITLE
[Bug]: LiteLLM doesn't close database conections

### ISSUE THREAD

**Issue by juanluis17** [BerriAI/litellm#4959]
### What happened?

After performing a stress test, LiteLLM proxy has not closed database connections 12 hours later.
![image](https://github.com/user-attachments/assets/df101387-b21c-4bc7-a5a3-e0a6390a3e42)

**Comment by michaeltinsley** [comment]
Also seeing this behaviour

**Comment by Manouchehri** [comment]
Likewise.

**Comment by ishaan-jaff** [comment]
@juanluis17 @michaeltinsley @Manouchehri have you tried setting `database_connection_pool_limit` 

https://docs.litellm.ai/docs/proxy/configs#configure-db-pool-limits--connection-timeouts

**Comment by juanluis17** [comment]
I use the default values ​​(60s according to the documentation). However, the database connections were open for 24 hours.

**Comment by ghost** [comment]
hmm - is there some specific code block we're missing here ? using [prisma](https://github.com/RobertCraigie/prisma-client-py?tab=readme-ov-file) to handle db calls - i believe this should be handled by them. 

@juanluis17 what is the pool limit you've set? (60s is the timeout, but what's the default limit? it might be prisma reserving a high number of connections for that instance x number of instances)

**Comment by ghost** [comment]
bump on this? @Manouchehri @juanluis17 @michaeltinsley

**Comment by juanluis17** [comment]
> hmm - is there some specific code block we're missing here ? using [prisma](https://github.com/RobertCraigie/prisma-client-py?tab=readme-ov-file) to handle db calls - i believe this should be handled by them.
> 
> @juanluis17 what is the pool limit you've set? (60s is the timeout, but what's the default limit? it might be prisma reserving a high number of connections for that instance x number of instances)

I used the default parameters listed in the documentation. Is there a parameter to close connections after a certain time? In the end it closed the connections after 24 hours.
