### ISSUE TITLE
[Bug]: Petals streaming not supported 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#496]
### What happened?

Need to add support for petals streaming 

### Relevant log output

```shell
user request
```

**Comment by ishaan-jaff** [comment]
added 
usage:
```python

response = completion(
    model="petals/petals-team/StableBeluga2", 
    messages=[{ "content": "Hello, how are you?","role": "user"}],
    stream=True
)

print(response)
for chunk in response:
  print(chunk)
```
<img width="1225" alt="Screenshot 2023-10-02 at 9 01 49 AM" src="https://github.com/BerriAI/litellm/assets/29436595/fcac20b3-ba93-455d-adc1-04fbec6672fc">

**Comment by ishaan-jaff** [comment]
done + on docs
