### ISSUE TITLE
[Feature]: How can I customize max_input_tokens,  max_output_tokens by proxy Config.yaml file

### ISSUE THREAD

**Issue by tuanlv14** [BerriAI/litellm#4960]
### The Feature

Sometime I add new model via proxy Config.yaml file under OpenAI-Compatible Endpoints. If I do not any configuration info, I saw max_input_tokens = N/A ; max_output_tokens = N/A.
I cannot find any instruction to guide how I can customize max_input_tokens, max_output_tokens and other information with Config.yaml file.

I think I can try to modify:
```
{
  "model_name": "my_awesome_model",
  "litellm_params": {
    "some_parameter": "some_value",
    "another_parameter": "another_value",
    "max_input_tokens" = "xxxx",                       // I do not know this is right or not ?
    "max_output_tokens" = "xxxx"                     // I do not know this is right or not ?
  },
  "model_info": {
    "author": "Your Name",
    "version": "1.0",
    "description": "A brief description of the model.,
     "max_input_tokens" = "xxxx",         // I do not know this is right or not ?
    "max_output_tokens" = "xxxx         // // I do not know this is right or not ?
  }
}
```

### Motivation, pitch

It support to define model info for a new model which had not been updated in litellm as default.

**Comment by ghost** [comment]
yes - the way you suggested, should already work @tuanlv14

**Comment by tuanlv14** [comment]
@krrishdholakia , you mean I should add max_input_tokens, max_output_tokens to "litellm_params" or "model_info" or both of two way is feasiable. Yesterday I try to add "max_input_tokens, max_output_tokens" into model_info", then i run docker, everything worked well but when I jump to Model Hub in web, I still saw max_input_tokens = N/A  and max_output_tokens = N/A, nothing did change. So I am not sure that my config is good or not good ? Pls help me clear this point.
