### ISSUE TITLE
when I run"litellm --model ollama_chat/llama3",it goes to the problem . how to deal with this problem？thx

### ISSUE THREAD

**Issue by eeeeson207720** [BerriAI/litellm#4962]
LiteLLM Warning: proxy started with `ollama` model
`ollama serve` failed with Exception[WinError 2] 系统找不到指定的文件。.
Ensure you run `ollama serve`

INFO:     Started server process [18248]
INFO:     Waiting for application startup.

**Comment by ghost** [comment]
duplicate #4961
