### ISSUE TITLE
[Feature]: GET /v1/batches to return list of batches

### ISSUE THREAD

**Issue by dannyboland** [BerriAI/litellm#4966]
### The Feature

`GET /v1/batches` [should return a list of batches](https://platform.openai.com/docs/api-reference/batch/list).

Currently only POST is supported to create a batch, or GET with a specific batch ID. Attempting `GET /v1/batches` returns 405 Method Not Allowed.

### Motivation, pitch

Listing batches is important for management of created batches, otherwise the client must keep track of all batch IDs and not fully benefit from OpenAI's batch management.

**Comment by ishaan-jaff** [comment]
picking this up today 😁

**Comment by ishaan-jaff** [comment]
PR here: https://github.com/BerriAI/litellm/pull/4969

**Comment by Manouchehri** [comment]
Related to #3246 for reference. :)
