### ISSUE TITLE
[Bug]: gpt-35-turbo-instruct triggers an error message when used in Router

### ISSUE THREAD

**Issue by okotek** [BerriAI/litellm#4968]
### What happened?

When callling gpt-35-turbo-instruct using Router.atext_completion(), an exception is triggered in deployment_callback_on_success(). The following line assumes "total_tokens" in completion_response:

                total_tokens = completion_response["usage"]["total_tokens"]
                
 An error is printed to the console and otherwise everything works normally, however for cleaning the log it's better to handle this case more gracefully. 

Thanks!

### Relevant log output

```shell
17:46:25 - LiteLLM Router:ERROR: router.py:2969 - litellm.proxy.hooks.prompt_injection_detection.py::async_pre_call_hook(): Exception occured - 'total_tokens'
Traceback (most recent call last):
  File "/Users/ori/miniconda3/envs/fresh/lib/python3.10/site-packages/litellm/router.py", line 2947, in deployment_callback_on_success
    total_tokens = completion_response["usage"]["total_tokens"]
KeyError: 'total_tokens'
```

**Comment by ghost** [comment]
Hey @okotek do you have a consistent repro for this? I can see gpt-3.5-turbo-instruct consistently returning `total_tokens` and i see it's also part of the openai text completion response object 

<img width="1156" alt="Screenshot 2024-07-30 at 3 11 35 PM" src="https://github.com/user-attachments/assets/0482ec6b-c34f-47f9-bb73-5eeaad59718c">

<img width="788" alt="Screenshot 2024-07-30 at 3 11 55 PM" src="https://github.com/user-attachments/assets/e57e3375-d113-4147-b78f-258093117a73">


My concern here is that, if this is a guaranteed field we should be ensuring it's always present

**Comment by ghost** [comment]
I'll add graceful handling for now - but if you have a way to repro this, it would be helpful in tracing the underlying issue

**Comment by okotek** [comment]
Hi I was under the weather this last week, I'll try to reproduce and update here
Thanks
