### ISSUE TITLE
[Bug]: Callbacks not showing up in UI 

### ISSUE THREAD

**Issue by VfBfoerst** [BerriAI/litellm#4980]
### What happened?

Hi. I noticed callbacks are not showing up in the admin ui. Either configured via the UI it self nor via environment variables, they are not showing up:  
![image](https://github.com/user-attachments/assets/c8aa4581-394e-45cc-aa3e-2ff1330e4477)
  
Logs tell about successful added config.  

### Relevant log output

```shell
INFO:     10.89.10.149:39882 - "GET /get/config/callbacks HTTP/1.1" 200 OK
07:33:22 - LiteLLM Proxy:INFO: utils.py:1533 - Data Inserted into Config Table
INFO:     10.89.10.149:55810 - "POST /config/update HTTP/1.1" 200 OK
```

**Comment by ghost** [comment]
just pushed a commit to fix this - https://github.com/BerriAI/litellm/commit/d8a8cd2961b62206e6eda380274127a26828ce2b
