### ISSUE TITLE
[Feature]: Add support for return_citations model option for perplexity models

### ISSUE THREAD

**Issue by akshat-g** [BerriAI/litellm#4981]
### The Feature

Models supported by perplexity can take return_citations as the model option. In response, chat completion also returns citations if return_citations parameter is passed.

`{
    "id": "a8f37485-026e-45da-81a9-cf0184896840",
    "model": "llama-3-sonar-small-32k-online",
    "created": 1722186391,
    "usage": {
        "prompt_tokens": 17,
        "completion_tokens": 65,
        "total_tokens": 82
    },
    "citations": [
        "https://www.sciencedirect.com/science/article/pii/S007961232200156X",
        "https://www.britannica.com/event/World-War-II",
        "https://www.loc.gov/classroom-materials/united-states-history-primary-source-timeline/great-depression-and-world-war-ii-1929-1945/world-war-ii/",
        "https://www.nationalww2museum.org/war/topics/end-world-war-ii-1945",
        "https://en.wikipedia.org/wiki/World_War_II"
    ],
    "object": "chat.completion",
    "choices": [
        {
            "index": 0,
            "finish_reason": "stop",
            "message": {
                "role": "assistant",
                "content": "World War II was won by the Allied powers, which included the United States, the Soviet Union, Great Britain, France, China, and other countries. The war concluded with the surrender of Germany on May 8, 1945, and Japan on September 2, 1945[2][3][4]."
            },
            "delta": {
                "role": "assistant",
                "content": ""
            }
        }
    ]
}`

### Motivation, pitch

We have a few clients who use perplexity models. This addition would be of a great help to them.

### Twitter / LinkedIn details

https://www.linkedin.com/in/akshat-gupta-b6b7a0119/

**Comment by ghost** [comment]
Done!

**Comment by okaeiz** [comment]
Where should I pass this `return_citations` param? Should I pass this as a LiteLLM parameter?
