### ISSUE TITLE
[Bug]: async for chunk in await router.acompletion breaks for aws bedrock models 

### ISSUE THREAD

**Issue by anmolbhatia05** [BerriAI/litellm#4993]
### What happened?

A bug happened! I am using litellm 1.40.4. 

The following code - 
```
async for chunk in await router.acompletion(
    model=router_model, messages=messages, stream=True, metadata={"ptu": key[2]}, **kwargs
):
    resp_part = chunk["choices"][0]["delta"]["content"]
    if resp_part is not None and len(resp_part) > 0:
        yield json.dumps(chunk.model_dump())
break
```
works for azure openai and google streaming but breaks for aws bedrock (claude v2, v2:1, v3 sonnet irregardless) 

i get the following in sentry - `TypeError: 'async for' requires an object with __aiter__ method, got generator` 

i would assume that async acompletion + stream would return an asynchronous iterator regardless of the provider/model combo.

**Comment by ghost** [comment]
@anmolbhatia05 unable to repro. we also have testing on this. can you try bumping to latest - v`1.42.8` and seeing if this issue persists. 

If so - can you run with `litellm.set_verbose=True` and share your server logs.

**Comment by anmolbhatia05** [comment]
bumping fixed the issue!
