### ISSUE TITLE
[Bug]: ignore `aws_region_name` parameter for openai image generation calls

### ISSUE THREAD

**Issue by dleen** [BerriAI/litellm#5009]
### What happened?

When using bedrock models with image generation the `aws_region_name` parameter (same as chat completion) is not recognized:

### Relevant log output

```shell
22:45:42 - LiteLLM:DEBUG: litellm_logging.py:205 - self.optional_params: {'aws_region_name': 'us-east-1'}
2024-08-01 22:45:42,561 DEBUG    LiteLLM.litellm_logging 205 self.optional_params: {'aws_region_name': 'us-east-1'}
22:45:42 - LiteLLM:DEBUG: utils.py:237 - RAW RESPONSE:
AsyncImages.generate() got an unexpected keyword argument 'aws_region_name'
```

**Comment by ghost** [comment]
> AsyncImages.generate() got an unexpected keyword argument 'aws_region_name'

this looks like it's going to the wrong route. how're you calling litellm? @dleen

**Comment by dleen** [comment]
Calling via:
```
litellm.aimage_generation(model="dall-e-3", prompt="image of an image", aws_region_name="us-east-1")
```

**Comment by dleen** [comment]
For `acompletion` it is able to ignore the `aws_region_name` parameter successfully
