### ISSUE TITLE
[Bug]: bedrock image response model is different from expected

### ISSUE THREAD

**Issue by dleen** [BerriAI/litellm#5010]
### What happened?

The response model should be the same whether we use openai or bedrock: https://github.com/BerriAI/litellm/blob/main/litellm/types/utils.py#L944

However the bedrock response looks like:

```
ImagesResponse(created=None, data={'url': 'iVBORw0KGgoAAAANSUhE
```

where we see that `data={'url': '...'}` is a dict but it should be a list of `ImageObject` where `url` is a member

**Comment by ghost** [comment]
Hi @dleen what bedrock model is this?

**Comment by ghost** [comment]
able to repro on stable diffusion
