### ISSUE TITLE
[Bug]: ghcr.io/berriai/litellm-database:main-v1.42.9-stable displays v1.42.10 ?

### ISSUE THREAD

**Issue by EricAntidot** [BerriAI/litellm#5012]
### What happened?

This is not big deal but I deployed my LiteLLM instance using litellm-helm with 
```yaml
repository: ghcr.io/berriai/litellm-database
tag: "main-v1.42.9-stable"
```
and the front page UI displays 1.42.10.

**Comment by ghost** [comment]
there's an issue with `-stable` where it's picking up the most recent commit @EricAntidot 

We're working on fixing it now. I'll leave this ticket open for now 

cc: @ishaan-jaff can you close once this is fixed?

**Comment by ghost** [comment]
this is now fixed

**Comment by ishaan-jaff** [comment]
Hi @EricAntidot , curious do you use LiteLLM Proxy in production today If so, I'd love to hop on a call and learn how we can improve LiteLLM for you

- my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
- my linkedin if you prefer DMs: https://www.linkedin.com/in/reffajnaahsi/
