### ISSUE TITLE
Custom API Server (Custom Format)

### ISSUE THREAD

**Issue by guleng** [BerriAI/litellm#5013]
@krrishdholakia 
My image generation model is deployed locally and does not support the API specifications of OpenAI. I configured it according to the documentation, but it was not successful

Reference Documents：
https://docs.litellm.ai/docs/providers/custom_llm_server
https://docs.litellm.ai/docs/image_generation

custom_handler.py
```
import litellm
from litellm import CustomLLM, completion, get_llm_provider, image_generation


class MyCustomLLM(CustomLLM):
    def image_generation(self, *args, **kwargs) -> litellm.ModelResponse:
        url = "http://zbe09-7860.proxy.x-gpu.com/sdapi/v1/txt2img"
        data = {
            "prompt": kwargs.get("prompt", ""),
            "other_parameters": kwargs.get("other_parameters", {})
        }
        response = requests.post(url, json=data)
        response_data = response.json()
        return litellm.image_generation(
            choices=[litellm.Choice(text=response_data.get("result", ""))],
            usage=litellm.Usage(
                total_tokens=response_data.get("usage", {}).get("total_tokens", 0)
            )
        )

    async def aimage_generation(self, *args, **kwargs) -> litellm.ModelResponse:
        url = "http://zbe09-7860.proxy.x-gpu.com/sdapi/v1/txt2img"
        data = {
            "prompt": kwargs.get("prompt", ""),
            "other_parameters": kwargs.get("other_parameters", {})
        }
        response = requests.post(url, json=data)
        response_data = response.json()
        return litellm.image_generation(
            choices=[litellm.Choice(text=response_data.get("result", ""))],
            usage=litellm.Usage(
                total_tokens=response_data.get("usage", {}).get("total_tokens", 0)
            )
        )


my_custom_llm = MyCustomLLM()
```
config.yaml
```
model_list:
  - model_name: "my-custom-model"
    litellm_params:
      model: "my-custom-llm/my-model"
litellm_settings:
  custom_provider_map:
  - {"provider": "my-custom-llm", "custom_handler": custom_handler.my_custom_llm}
```
```
curl 'http://100.29.6.215:4000/v1/images/generations' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer sk-7TKke_a-J5RFKZ8oSJF6Sg' \
--data '{
  "model": "my-custom-model",
  "prompt": "A cute baby sea otter"
}'
```
Error log
```
litellm-1  | 07:06:50 - LiteLLM:WARNING: cost_calculator.py:738 - litellm.cost_calculator.py::response_cost_calculator - Returning None. Exception occurred - Model=1024-x-1024/my-model not found in completion cost model map/nTraceback (most recent call last):
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/cost_calculator.py", line 712, in response_cost_calculator
litellm-1  |     response_cost = completion_cost(
litellm-1  |                     ^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/cost_calculator.py", line 665, in completion_cost
litellm-1  |     raise e
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/cost_calculator.py", line 595, in completion_cost
litellm-1  |     raise Exception(
litellm-1  | Exception: Model=1024-x-1024/my-model not found in completion cost model map
litellm-1  | 
litellm-1  | INFO:     124.205.197.30:61835 - "POST /v1/images/generations HTTP/1.1" 200 OK
```
What I want is Image Generation, and I want to call the local image generation model through Litellm. Can you help me write an example of a custom API for image generation? I am not a developer, but an operations specialist, so I am not very good at this. Thank you.

**Comment by ghost** [comment]
> litellm-1  | INFO:     124.205.197.30:61835 - "POST /v1/images/generations HTTP/1.1" 200 OK

i see a 200-status code response @guleng what did you receive client side

**Comment by ghost** [comment]
@guleng reading further 

>  async def aimage_generation(self, *args, **kwargs) -> litellm.ModelResponse:
        url = "http://zbe09-7860.proxy.x-gpu.com/sdapi/v1/txt2img"
        data = {
            "prompt": kwargs.get("prompt", ""),
            "other_parameters": kwargs.get("other_parameters", {})
        }
        response = requests.post(url, json=data)
        response_data = response.json()
        return litellm.image_generation(
            choices=[litellm.Choice(text=response_data.get("result", ""))],
            usage=litellm.Usage(
                total_tokens=response_data.get("usage", {}).get("total_tokens", 0)
            )
        )

you're code just calls `litellm.image_generation()` - **why** - this is **already happening by default when you hit `/image/generations`**

> Can you help me write an example of a custom API for image generation

@guleng I believe the best way to do this would be to just write your own openai-compatible fastapi server. 

Here's our code for reference - https://github.com/BerriAI/litellm/blob/48419ca8bcccfb9d4670a29c5b1fb73c10312d0c/litellm/proxy/proxy_server.py#L3557

**Comment by ghost** [comment]
Happy to add support for calling custom image_generation endpoints if this becomes a common need

**Comment by guleng** [comment]
@krrishdholakia  Thank you very much. Many image generation models are not manufacturer's models. There are too many models that have been modified and developed by oneself, and the model effects are very good. There are too many practical scenarios that require this kind of calling. I hope to have this function. Tools such as dify can support direct calling by default, which is very good.

**Comment by guleng** [comment]
Does this customization only support custom APIs for text to text or can it also be implemented for text to graphics? I'm a bit confused

**Comment by tan-yong-sheng** [comment]
Comment here for future notification

- Actually I am interested to use image generation wtih Cloudflare Workers AI and LiteLLM: https://developers.cloudflare.com/workers-ai/models/stable-diffusion-v1-5-img2img/

**Comment by ghost** [comment]
@tan-yong-sheng imge gen is supported - https://docs.litellm.ai/docs/providers/custom_llm_server#image-generation

**Comment by tan-yong-sheng** [comment]
@krrishdholakia Hi, thanks for info.

But the problem is the image output of cloudflare workers ai is in binary string not in URL format

The example: https://developers.cloudflare.com/workers-ai/models/stable-diffusion-xl-base-1.0/

![Image](https://github.com/user-attachments/assets/8c2e13ee-2b7d-4af4-98b9-ff84bedc51d0)

![Image](https://github.com/user-attachments/assets/f36a7df9-40e9-451b-b6ba-54f4ff98de01)

What in LiteLLM custom api server:

![Image](https://github.com/user-attachments/assets/ec2b9cb0-7a8f-4d24-814d-668eeea8c113)

That's why a bit quite hard to modify this to adapt LiteLLM custom api server.

**Comment by ghost** [comment]
@tan-yong-sheng the ImageObject value can be a binary str - https://github.com/BerriAI/litellm/blob/8de6e7c292a5284403eb45ace908e83ef9c2e6f0/litellm/types/utils.py#L1307

**Comment by tan-yong-sheng** [comment]
I see, thanks for the info @krrishdholakia 

I tried to use b64_json for ImageObject, but still fail to get image output and no error messages popped out:

![Image](https://github.com/user-attachments/assets/39b5da4b-f0f3-4491-bb46-32cbd997379c)

Here is the code I put to create custom API server for image generation via LiteLLM

File location: `custom_handler.py`
```python
import time
import httpx
import litellm
from litellm import CustomLLM
from litellm.types.utils import ImageResponse, ImageObject

CLOUDFLARE_API_KEY="<CLOUDFLARE_API_KEY>"
CLOUDFLARE_ACCOUNT_ID="<CLOUDFLARE_ACCOUNT_ID>"

URL = f"https://api.cloudflare.com/client/v4/accounts/{CLOUDFLARE_ACCOUNT_ID}/ai/run/@cf/stabilityai/stable-diffusion-xl-base-1.0"

headers = {
    "Authorization": f"Bearer {CLOUDFLARE_API_KEY}",
    "Content-Type": "application/json"
}

class MyCustomLLM(CustomLLM):
    async def aimage_generation(
        self,
        model: str,
        prompt: str,
        model_response: ImageResponse,
        optional_params: dict,
        logging_obj: any,
        timeout: float = 60.0,
        client: httpx.AsyncClient = None,
    ) -> ImageResponse:

        data = {
            "prompt": prompt,
        }

        async with httpx.AsyncClient(timeout=timeout) as client:
            try:
                response = await client.post(URL, json=data, headers=headers)
                response.raise_for_status()
            except Exception as e:
                return None

        # Return an ImageResponse that litellm can use
        return ImageResponse(
            created=int(time.time()),
            data=[ImageObject(b64_json=response.content)]
        )

my_custom_llm = MyCustomLLM()
```

To verify if my previous code is working or not, I've created another async code to get the `reponse.content` output for my previous code, and ya, I got the image output in binary string: 

![Image](https://github.com/user-attachments/assets/2ee51d17-3d3d-4381-9cff-f37fcc6848de)

```python

import asyncio
import httpx

CLOUDFLARE_API_KEY="<CLOUDFLARE_API_KEY>"
CLOUDFLARE_ACCOUNT_ID="<CLOUDFLARE_ACCOUNT_ID>"
URL = f"https://api.cloudflare.com/client/v4/accounts/{CLOUDFLARE_ACCOUNT_ID}/ai/run/@cf/stabilityai/stable-diffusion-xl-base-1.0"

headers = {"Authorization": f"Bearer {CLOUDFLARE_API_KEY}", "Content-Type": "application/json"}
data = {"prompt": "a cute baby"}

async def aimage_generation():
    async with httpx.AsyncClient(timeout=60.0) as client:
        try:
            response = await client.post(URL, json=data, headers=headers)
            response.raise_for_status()
            return response.content
        except Exception as e:
            return None

if __name__ == "__main__":
    result = asyncio.run(aimage_generation())
    print(result if result else "Image generation failed.")
```

**Comment by tan-yong-sheng** [comment]
Just to show an alternative - use a proxy instead, hosted on cloudflare workers: https://github.com/tan-yong-sheng/cloudflare-image-mcp
