### ISSUE TITLE
[Bug]: Langfuse hardcoded credentials

### ISSUE THREAD

**Issue by juancarlosm** [BerriAI/litellm#5015]
### What happened?

Langfuse integration is not using ENV credentials, it's using hardcoded credentials in code:

![image](https://github.com/user-attachments/assets/0d02f62c-82ff-4391-b16f-0765f0c25be0)

https://github.com/BerriAI/litellm/blob/4c2ef8ea64a04f2b0859df92b4303a1724d7d1a3/litellm/integrations/langfuse.py#L47

Docker:
ghcr.io/berriai/litellm:main-stable
Tag: 1.42.9-stable

**Comment by ishaan-jaff** [comment]
fixed here: https://github.com/BerriAI/litellm/commit/75fba18c9f13dc1e611caed90017382cdd45a046

**Comment by ishaan-jaff** [comment]
thanks for raising this @juancarlosm

**Comment by ghost** [comment]
We've identified an issue for `-stable` releases in our ci/cd which picked up the most-recent-commit instead of the one that passed testing. Working on fixing that as well @juancarlosm 

if you use v`1.42.9` (without -stable tag) this issue should not occur

**Comment by ishaan-jaff** [comment]
Hi @juancarlosm , curious do you use LiteLLM Proxy in production today If so, I'd love to hop on a call and learn how we can improve LiteLLM for you

- my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
- my linkedin if you prefer DMs: https://www.linkedin.com/in/reffajnaahsi/
