### ISSUE TITLE
Support deepseek call caching - s/o @arvinxx

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#5017]

**Comment by ghost** [comment]
deepseek usage returns - `"usage": {"completion_tokens": 40, "prompt_tokens": 11, "total_tokens": 51, "prompt_cache_hit_tokens": 0, "prompt_cache_miss_tokens": 11}`

**Comment by ghost** [comment]
will need to expand the litellm usage object to cover this

**Comment by ghost** [comment]
the token cost calculation should also account for this

**Comment by ghost** [comment]
gemini has something similar, seeing how they do it: 
```
print(response.usage_metadata)

# The output should look something like this:
#
# prompt_token_count: 696219
# cached_content_token_count: 696190
# candidates_token_count: 214
# total_token_count: 696433

```
