### ISSUE TITLE
[Feature]: Use commetized for commit description

### ISSUE THREAD

**Issue by linediconsine** [BerriAI/litellm#502]
### The Feature

Maybe its just me that I used at work so I like it 
but I would recommend/ask if makes sense to use 
https://pypi.org/project/commitizen/

Just sharing the idea

### Motivation, pitch

Commentize make comments easy to read and the looks professional

**Comment by ghost** [comment]
woah that's pretty cool - are there any examples of projects using it today? would love to see it live

**Comment by ishaan-jaff** [comment]
@linediconsine thanks for the suggestion I just saw https://commitizen-tools.github.io/commitizen/ 

Where were you thinking of adding this? In pre commit hooks ? 

- I like the idea of to make commitizen available the system of contributors 
- I dont think we should add commitizen as another dependency to litellm though

**Comment by ghost** [comment]
Hey @linediconsine thanks for this. 

I just added commitizen to my local env as well. Here's the first commit i've done with it - 
<img width="1300" alt="Screenshot 2023-10-05 at 11 44 47 AM" src="https://github.com/BerriAI/litellm/assets/17561003/0a5289f3-bceb-44b5-b21d-25a684c1dfa7">

Is there any further we need to do here?

**Comment by linediconsine** [comment]
We should be good, 
Let me take a look
