### ISSUE TITLE
[Bug]: API has changed after integration to SalesGPT

### ISSUE THREAD

**Issue by filip-michalsky** [BerriAI/litellm#503]
### What happened?

A bug happened!

Original usage:

from langchain.chat_models import ChatLiteLLM

Now throws an error.

Can you please specify which version removed ChatLiteLLM module? It is quite painful to have litellm as a dependency if the API will keep changing and will need to version gate it.

### Relevant log output

```shell
ImportError                               Traceback (most recent call last)
Cell In[1], line 18
     16 from pydantic import BaseModel, Field
     17 from langchain.chains.base import Chain
---> 18 from langchain.chat_models import ChatOpenAI, ChatLiteLLM
     19 from langchain.agents import Tool, LLMSingleActionAgent, AgentExecutor
     20 from langchain.text_splitter import CharacterTextSplitter

ImportError: cannot import name 'ChatLiteLLM' from 'langchain.chat_models' (/Users/filipmichalsky/anaconda3/envs/langchain/lib/python3.10/site-packages/langchain/chat_models/__init__.py)
```

**Comment by ghost** [comment]
Hey @filip-michalsky did this get resolved? We haven't changed chatlitellm so surprised you're seeing this
