### ISSUE TITLE
[Bug]: Cannot add model to database

### ISSUE THREAD

**Issue by yangg** [BerriAI/litellm#5033]
### What happened?

Cannot add model to database, STORE_MODEL_IN_DB is set to 'True',
and tried master key and ui username login, neither works.

LiteLLM: Current Version = 1.42.11 
installed via pip

### Relevant log output

```shell
0|llm  | 15:39:27 - LiteLLM:WARNING: user_api_key_auth.py:488 - Team doesn't exist in cache + check_cache_only=True. Team=litellm-dashboard. Create team via `/team/new` call.
0|llm  | 15:39:27 - LiteLLM Proxy:ERROR: proxy_server.py:6505 - litellm.proxy.proxy_server.add_new_model(): Exception occured - No module named 'nacl'
0|llm  | INFO:     100.99.100.10:57015 - "POST /model/new HTTP/1.1" 400 Bad Request
```
```


### Twitter / LinkedIn details

_No response_

**Comment by ghost** [comment]
> Exception occured - No module named 'nacl'
you're missing a requirement

Please re-run with `pip install pynacl`
