### ISSUE TITLE
[Feature]: If optional param not mapped - raise exception

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#504]
### The Feature

If optional param is not mapped to the provider - e.g. they don't support that param, raise an exception

### Motivation, pitch

user request

**Comment by ghost** [comment]
One way of tackling this is to check what are all the optional params we currently accept across providers. Then we can compare what's accepted with what's passed in, and raise an exception if a param that's not accepted is passed in.

**Comment by ghost** [comment]
Published in v`0.1.813`
