### ISSUE TITLE
[Feature]: Gemini - Google AI Studio | Add all the supported models 

### ISSUE THREAD

**Issue by AdithyanI** [BerriAI/litellm#5043]
### The Feature

First we ❤️ litellm.

We use Google AI studio via the proxy server. These are the current models supported via [litellm](https://docs.litellm.ai/docs/providers/gemini) : 

![image](https://github.com/user-attachments/assets/db4381b6-2b61-49ed-a342-aa47c3a5d37c)

But google ai studio supports more models now, 

![image](https://github.com/user-attachments/assets/ee3bea1f-2639-4dc9-897a-dfcdd48bf545)
![image](https://github.com/user-attachments/assets/07b246ee-8741-4a5f-882b-227a3df73bb2)

Add support for these other models for the proxy server.

### Motivation, pitch

We would like to use other models, especially the flash for cost reasons. There's a significant difference in pricing.

**Comment by ghost** [comment]
Hi @AdithyanI we already support all gemini models. I'll update docs to make this clear 

just do `gemini/<your-model-name`

**Comment by zengbo** [comment]
> Hi @AdithyanI we already support all gemini models. I'll update docs to make this clear
> 
> just do `gemini/<your-model-name`

I got the error:
```
{"error":{"message":"Authentication Error, Only proxy admin can be used to generate, delete, update info for new keys/users/teams. Route=/gemini/v1beta/models/gemini-1.5-pro:streamGenerateContent. Your role=internal_user. Your user_id=16d3038e-423d-42f9-b1b2-158c216a03af","type":"auth_error","param":"None","code":"401"}}
```
How to deal with this?

**Comment by ghost** [comment]
Hey @zengbo 

> Route=/gemini/v1beta/models/gemini-1.5-pro:streamGenerateContent. Your role=internal_user

Looks like your role is not allowed to make this call. Are you the maintainer of your litellm proxy?

**Comment by ghost** [comment]
@zengbo the route shown is a pass-through route - https://docs.litellm.ai/docs/pass_through/google_ai_studio

If you're trying to make the call in the openai format, you need to call the `/chat/completions` route - https://docs.litellm.ai/docs/proxy/user_keys#chatcompletions

**Comment by zengbo** [comment]
> Hey @zengbo 
> 
> > Route=/gemini/v1beta/models/gemini-1.5-pro:streamGenerateContent. Your role=internal_user
> 
> Looks like your role is not allowed to make this call. Are you the maintainer of your litellm proxy? 

whitch roles are allowed to call the route?

**Comment by ishaan-jaff** [comment]
Hi @AdithyanI , curious do you use LiteLLM Proxy in production today If so, I'd love to hop on a call and learn how we can improve LiteLLM for you

- my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
- my linkedin if you prefer DMs: https://www.linkedin.com/in/reffajnaahsi/
