### ISSUE TITLE
Fix "gpt-4o-mini-2024-07-18" entry in "model_prices_and_context_window.json"

### ISSUE THREAD

**Issue by attilalaszlo** [BerriAI/litellm#5045]
as per Microsoft's documentation *gpt-4o-mini (2024-07-18)* has **16384** max output tokens:
https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#gpt-4-and-gpt-4-turbo-models
![image](https://github.com/user-attachments/assets/b8ebd76c-c313-4c4e-acfe-fa5afc09cc08)

https://github.com/BerriAI/litellm/blob/1c747f3ad372399c5b95cc5696b06a5fbe53186b/model_prices_and_context_window.json#L36-L47

We also need to update [model_prices_and_context_window_backup.json](https://github.com/BerriAI/litellm/blob/1c747f3ad372399c5b95cc5696b06a5fbe53186b/litellm/model_prices_and_context_window_backup.json).

**Comment by ghost** [comment]
Done - thanks for the callout @attilalaszlo 

Curious - how do you use litellm today?
