### ISSUE TITLE
[Bug]: ollama_chat api_key header is string when expecting dict

### ISSUE THREAD

**Issue by MNic** [BerriAI/litellm#5046]
### What happened?

We're attempting to pass an api_key through the litellm api to ollama behind nginx.  When litellm creates the authentication header, we're getting the CIMultiDict error log included here.

As best we can tell.  https://github.com/BerriAI/litellm/blob/1c747f3ad372399c5b95cc5696b06a5fbe53186b/litellm/llms/ollama_chat.py#L296
Lines 296, 361, 423, 495 are all replacing the header dict, with a "Bearer <api_key>" string.

The asyncio client session is expecting a dict. 

### Relevant log output

```shell
"error": "litellm.APIConnectionError: CIMultiDict takes either dict or list of (key, value) pairs
```

**Comment by ghost** [comment]
Fixed! thanks for the callout @MNic

**Comment by ghost** [comment]
Will be live in new release by EOD

**Comment by MNic** [comment]
Tested this morning, works great. Thanks for the quick fix!
