### ISSUE TITLE
[Bug]: Fix replicate param mapping 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#505]
### What happened?

[Replicate params inconsistently mapped](https://docs.google.com/document/d/1HzeLkKU1npHrd2EZQIhLcvWIyY4G4Fok_YEltoPjRdg/edit)

- System prompt not passed
- Max tokens hard coded to 500 
- Errors are not properly handled (if an error occurs leading to status “failed” or “canceled”) this method will act as if the model returned “” (empty string) vs properly throwing an error

**Comment by ghost** [comment]
test on this - https://replicate.com/meta/llama-2-13b-chat

**Comment by ghost** [comment]
Params that replicate supports for this model:
- [ ] prompt 
- [ ] system prompt 
- [ ] max new tokens 
- [ ] min new tokens 
- [ ] temperature 
- [ ] top p 
- [ ] top k 
- [ ] stop sequences 
- [ ] seed

**Comment by ghost** [comment]
params we currently support: ["stream", "temperature", "max_tokens", "top_p", "stop"]


we also support prompt

**Comment by ghost** [comment]
Looks like system prompt is only for meta-llama/llama-2 

E.g. for codellama this doesn't seem supported: https://replicate.com/meta/codellama-13b/api

**Comment by ghost** [comment]
even seed isn't consistently map
https://replicate.com/meta/codellama-13b/api

**Comment by ghost** [comment]
Closing as the max tokens bug is now fixed.
