### ISSUE TITLE
[Bug]: Unable to have Gemini call a function without any parameters

### ISSUE THREAD

**Issue by Ashwin27** [BerriAI/litellm#5055]
### What happened?

Currently I am unable to leverage Gemini function calling without any parameters. Tested the latest version of litellm & google-generativeai.

Model: gemini/gemini-1.5-pro

Function description (example):
```
{
  "type": "function"
  "function" : {
      "name": "plot",
      "description": "Generate plots",
  },
}
```

Two issues:
- Error during function calling since we pass empty param list: `<BadRequestError: litellm.BadRequestError: VertexAIException BadRequestError - b'{\n  "error": {\n    "code": 400,\n    "message": "* GenerateContentRequest.tools[0].function_declarations[0].parameters.type: must be specified\\n",\n    "status": "INVALID_ARGUMENT"\n  }\n}\n'>`
- Error after the function has been called and we try to put it into the message stack for the subsequent call: `Exception: Unable to convert openai tool calls=[{'id': 'acb437c1-54f9-4a76-875e-b702b23530c2', 'type': 'function', 'function': {'name': 'plot', 'arguments': '{}'}}] to gemini tool calls. Received error=local variable 'function_call' referenced before assignment`

### Relevant log output

```shell
Error 1:
<BadRequestError: litellm.BadRequestError: VertexAIException BadRequestError - b'{\n  "error": {\n    "code": 400,\n    "message": "* GenerateContentRequest.tools[0].function_declarations[0].parameters.type: must be specified\\n",\n    "status": "INVALID_ARGUMENT"\n  }\n}\n'>


Error 2:
Exception: Unable to convert openai tool calls=[{'id': 'acb437c1-54f9-4a76-875e-b702b23530c2', 'type': 'function', 'function': {'name': 'plot', 'arguments': '{}'}}] to gemini tool calls. Received error=local variable 'function_call' referenced before assignment
```

### Twitter / LinkedIn details

https://www.linkedin.com/in/avraman

**Comment by ghost** [comment]
We have testing for gemini function calling - https://github.com/BerriAI/litellm/blob/b2e182a42ca5bb74839ee3ad2c7d6afbcf272007/litellm/tests/test_function_calling.py#L55


trying to understand the gap

**Comment by ghost** [comment]
oh! i think you're passing in 'function' param not the 'tool' param, which is what we were missing coverage for. got it.

**Comment by ghost** [comment]
nevermind, this looks like a tool call 

```
{
  "type": "function"
  "function" : {
      "name": "plot",
      "description": "Generate plots",
  },
}
```

**Comment by ghost** [comment]
able to repro

**Comment by ghost** [comment]
```
messages = [{"role": "user", "content": "What is the weather like in Boston?"}]
        response = completion(
            model=model,
            messages=messages,
            tools=[
                {
                    "type": "function",
                    "function": {
                        "name": "plot",
                        "description": "Generate plots",
                    },
                }
            ],
            tool_choice="auto",
        )
        print(f"response: {response}")
```

**Comment by ghost** [comment]
i believe the 2nd issue was fixed recently as well
