### ISSUE TITLE
[Bug]: Anthropic tool calls when stream=True and no tool arguments, results in parse error

### ISSUE THREAD

**Issue by jcheng5** [BerriAI/litellm#5063]
### What happened?

This reprex invites Claude 3.5 Sonnet to call a tool that takes no arguments. When `stream=True`, attempting to continue the conversation after a successful tool call results in a JSON parse error.

```python
import dotenv
import litellm

dotenv.load_dotenv()

model = "claude-3-5-sonnet-20240620"


messages = [
    {"role": "user", "content": "Hit the snooze button."},
]

tools = [
    {
        "type": "function",
        "function": {
            "name": "snooze",
            "parameters": {
                "type": "object",
                "properties": {},
                "required": [],
            },
        },
    }
]

stream = litellm.completion(model, messages, tools=tools, stream=True)
response = litellm.stream_chunk_builder([*stream]).choices[0].message
assert response.tool_calls is not None
assert len(response.tool_calls) == 1

tool_call_msg = {
    "tool_call_id": response.tool_calls[0].id,
    "role": "tool",
    "name": response.tool_calls[0].function.name,
    "content": "null",
}

messages.append(response)
messages.append(tool_call_msg)

# This line errors
response = litellm.completion(model, messages, tools=tools).choices[0].message
```

In streaming mode Claude sends `"arguments": ""`, while in non-streaming it sends `"arguments": "{}"` which works fine.

### Relevant log output

```shell
Traceback (most recent call last):
  File "/Users/jcheng/Development/BerriAI/litellm/litellm/llms/anthropic.py", line 919, in completion
    messages = prompt_factory(
  File "/Users/jcheng/Development/BerriAI/litellm/litellm/llms/prompt_templates/factory.py", line 2483, in prompt_factory
    return anthropic_messages_pt(
  File "/Users/jcheng/Development/BerriAI/litellm/litellm/llms/prompt_templates/factory.py", line 1322, in anthropic_messages_pt
    convert_to_anthropic_tool_invoke(messages[msg_i]["tool_calls"])
  File "/Users/jcheng/Development/BerriAI/litellm/litellm/llms/prompt_templates/factory.py", line 1207, in convert_to_anthropic_tool_invoke
    anthropic_tool_invoke = [
  File "/Users/jcheng/Development/BerriAI/litellm/litellm/llms/prompt_templates/factory.py", line 1212, in <listcomp>
    input=json.loads(
  File "/Users/jcheng/.pyenv/versions/3.10.6/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/jcheng/.pyenv/versions/3.10.6/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/jcheng/.pyenv/versions/3.10.6/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jcheng/Development/BerriAI/litellm/litellm/main.py", line 1489, in completion
    response = anthropic_chat_completions.completion(
  File "/Users/jcheng/Development/BerriAI/litellm/litellm/llms/anthropic.py", line 923, in completion
    raise AnthropicError(status_code=400, message=str(e))
litellm.llms.anthropic.AnthropicError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jcheng/Development/BerriAI/litellm/repro2.py", line 43, in <module>
    response = litellm.completion(model, messages, tools=tools).choices[0].message
  File "/Users/jcheng/Development/BerriAI/litellm/litellm/utils.py", line 1029, in wrapper
    raise e
  File "/Users/jcheng/Development/BerriAI/litellm/litellm/utils.py", line 909, in wrapper
    result = original_function(*args, **kwargs)
  File "/Users/jcheng/Development/BerriAI/litellm/litellm/main.py", line 2711, in completion
    raise exception_type(
  File "/Users/jcheng/Development/BerriAI/litellm/litellm/utils.py", line 8168, in exception_type
    raise e
  File "/Users/jcheng/Development/BerriAI/litellm/litellm/utils.py", line 6645, in exception_type
    raise BadRequestError(
litellm.exceptions.BadRequestError: litellm.BadRequestError: AnthropicException - Expecting value: line 1 column 1 (char 0)
```

**Comment by krrishdholakia** [comment]
it looks like this happens when claude responds with text not a tool call

**Comment by ghost** [comment]
> complete response = Message(content='Certainly! I can help you hit the snooze button using the available "snooze" function. This function doesn\'t require any parameters, so we can proceed with the call right away.\n\nHere\'s how we\'ll use the snooze function:', role='assistant', tool_calls=[ChatCompletionMessageToolCall(index=1, function=Function(arguments='', name='snooze'), id='toolu_01NzHtsi379nskaW6dVxms7C', type='function')], function_call=None)

example

**Comment by ghost** [comment]
> ModelResponse(id='chatcmpl-e82e57f5-7a76-49c6-9c09-5b198eb8b224', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content='', role=None, function_call=None, tool_calls=[ChatCompletionDeltaToolCall(id='toolu_01NzHtsi379nskaW6dVxms7C', function=Function(arguments='', name='snooze'), type='function', index=1)]), logprobs=None)], created=1723044491, model='claude-3-5-sonnet-20240620', object='chat.completion.chunk', system_fingerprint=None), 

> ModelResponse(id='chatcmpl-e82e57f5-7a76-49c6-9c09-5b198eb8b224', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content='', role=None, function_call=None, tool_calls=[ChatCompletionDeltaToolCall(id=None, function=Function(arguments='', name=None), type='function', index=1)]), logprobs=None)], created=1723044491, model='claude-3-5-sonnet-20240620', object='chat.completion.chunk', system_fingerprint=None),

it looks like anthropic would yield multiple chunks for a tool call, we can treat it like we do with hf - where if we see an empty arg for a tool call - wait till a non-empty chunk is returned or till block ends - and if still empty - return {}

**Comment by ghost** [comment]
nvm gpt-3.5-turbo also return empty arguments - ""

**Comment by ghost** [comment]
> [ModelResponse(id='chatcmpl-9td8whMfNn4XYICs6usMpZGfMChwa', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(refusal=None, content=None, role='assistant', function_call=None, tool_calls=[ChatCompletionDeltaToolCall(id='call_5dDPKakZxB6gfWAZPDj9ammC', function=Function(arguments='', name='snooze'), type='function', index=0)]), logprobs=None)], created=1723045535, model='gpt-3.5-turbo', object='chat.completion.chunk', system_fingerprint=None), ModelResponse(id='chatcmpl-9td8whMfNn4XYICs6usMpZGfMChwa', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=None, role='assistant', function_call=None, tool_calls=[ChatCompletionDeltaToolCall(id=None, function=Function(arguments='{}', name=None), type='function', index=0)]), logprobs=None)], created=1723045535, model='gpt-3.5-turbo', object='chat.completion.chunk', system_fingerprint=None), ModelResponse(id='chatcmpl-9td8whMfNn4XYICs6usMpZGfMChwa', choices=[StreamingChoices(finish_reason='tool_calls', index=0, delta=Delta(content=None, role=None, function_call=None, tool_calls=None), logprobs=None)], created=1723045535, model='gpt-3.5-turbo', object='chat.completion.chunk', system_fingerprint=None)]

gpt-3.5-turbo response

**Comment by ghost** [comment]
i guess a more appropriate test would be to check if - given a tool call with id, if that tool call contains a non-empty argument

**Comment by ghost** [comment]
updated test - 

```python
@pytest.mark.parametrize(
    "model", [
        "gpt-3.5-turbo",
        "claude-3-5-sonnet-20240620"
    ]
)
def test_streaming_tool_calls_valid_json_str(model):
    messages = [
        {"role": "user", "content": "Hit the snooze button."},
    ]

    tools = [
        {
            "type": "function",
            "function": {
                "name": "snooze",
                "parameters": {
                    "type": "object",
                    "properties": {},
                    "required": [],
                },
            },
        }
    ]

    stream = litellm.completion(model, messages, tools=tools, stream=True)
    chunks = [*stream]
    print(chunks)
    tool_call_id_arg_map = {}
    curr_tool_call_id = None
    curr_tool_call_str = ""
    for chunk in chunks:
        if chunk.choices[0].delta.tool_calls is not None:
            if chunk.choices[0].delta.tool_calls[0].id is not None: 
                # flush prev tool call 
                if curr_tool_call_id is not None: 
                    tool_call_id_arg_map[curr_tool_call_id] = curr_tool_call_str
                curr_tool_call_id = chunk.choices[0].delta.tool_calls[0].id
                tool_call_id_arg_map[curr_tool_call_id] = ""
            if chunk.choices[0].delta.tool_calls[0].function.arguments is not None: 
                curr_tool_call_str += chunk.choices[0].delta.tool_calls[0].function.arguments
    # flush prev tool call 
    if curr_tool_call_id is not None: 
        tool_call_id_arg_map[curr_tool_call_id] = curr_tool_call_str
    
    for k, v in tool_call_id_arg_map.items(): 
        json.loads(v) # valid json str
    
```

**Comment by ghost** [comment]
Great - checking raw output, i can see that anthropic returns tool calls in content blocks 

```

Raw chunk:
{'type': 'content_block_start', 'index': 1, 'content_block': {'type': 'tool_use', 'id': 'toolu_01NwJkiQjeP8B1dSPgnb1C9v', 'name': 'snooze', 'input': {}}}



Raw chunk:
{'type': 'content_block_delta', 'index': 1, 'delta': {'type': 'input_json_delta', 'partial_json': ''}}



Raw chunk:
{'type': 'content_block_stop', 'index': 1}


```

**Comment by ghost** [comment]
> 'input': {}}}

i can also see they give us an empty dictionary

**Comment by ghost** [comment]
nvm, looks like it's always an empty dictionary - leading to {}{<real-args>} in cases where partial_json has content

**Comment by ghost** [comment]
Example (with the openai what's the weather in boston? tool calling example) 

```
Raw chunk:
{'type': 'content_block_start', 'index': 0, 'content_block': {'type': 'tool_use', 'id': 'toolu_01NUtLATC9gQf2pyshw9MSa7', 'name': 'get_current_weather', 'input': {}}}



Raw chunk:
{'type': 'ping'}



Raw chunk:
{'type': 'content_block_delta', 'index': 0, 'delta': {'type': 'input_json_delta', 'partial_json': ''}}



Raw chunk:
{'type': 'content_block_delta', 'index': 0, 'delta': {'type': 'input_json_delta', 'partial_json': '{"l'}}



Raw chunk:
{'type': 'content_block_delta', 'index': 0, 'delta': {'type': 'input_json_delta', 'partial_json': 'ocation":'}}



Raw chunk:
{'type': 'content_block_delta', 'index': 0, 'delta': {'type': 'input_json_delta', 'partial_json': ' "Boston'}}



Raw chunk:
{'type': 'content_block_delta', 'index': 0, 'delta': {'type': 'input_json_delta', 'partial_json': ', MA'}}



Raw chunk:
{'type': 'content_block_delta', 'index': 0, 'delta': {'type': 'input_json_delta', 'partial_json': '"'}}



Raw chunk:
{'type': 'content_block_delta', 'index': 0, 'delta': {'type': 'input_json_delta', 'partial_json': ', "unit":'}}



Raw chunk:
{'type': 'content_block_delta', 'index': 0, 'delta': {'type': 'input_json_delta', 'partial_json': ' "fahr'}}



Raw chunk:
{'type': 'content_block_delta', 'index': 0, 'delta': {'type': 'input_json_delta', 'partial_json': 'enheit"}'}}



Raw chunk:
{'type': 'content_block_stop', 'index': 0}
```

**Comment by ghost** [comment]
so at content_block_stop what we can do is check if the content block was a tool call - (input type = "input_json_delta") and if any args were returned so far - if none, we can return an empty dictionary to ensure a valid json string is always returned when claude is making tool calls

**Comment by ghost** [comment]
We should also probably check if this works for anthropic on vertex + bedrock

**Comment by ghost** [comment]
same issue on bedrock converse endpoint

**Comment by ghost** [comment]
Works with vertex after our anthropic iterator fixes
