### ISSUE TITLE
[Bug]: Streaming chat completion not calling success callback

### ISSUE THREAD

**Issue by tomasmcm** [BerriAI/litellm#5065]
### What happened?

I'm trying to implement a custom logger for a LiteLLM Router. Everything is working for non-stream completions. But when I tested with streaming it does not seem to be triggering all events.

In particular, if streaming with a CustomLogger, I can see `log_stream_event` and `async_log_stream_event` are getting triggered, but not `log_success_event` or `async_log_success_event`

If I use a method and override `litellm.success_callback` it is being called for every stream event, but not when the stream ends. I would expect the last call to have `"finish_reason":"stop"` but they all have `finish_reason` as `None`.

This is happening with openai, anthropic and cohere models.

Looking at the LiteLLM code, seems there is a `complete_streaming_response` parameter that is not working as intended so the success event is never called.

`litellm==1.42.9`

**Comment by ghost** [comment]
> I  would expect the last call to have "finish_reason":"stop" but they all have finish_reason as None

That's probably what's causing the issue. I don't see this behaviour though - (on v1.43.0) 

<img width="1175" alt="Screenshot 2024-08-06 at 8 11 59 AM" src="https://github.com/user-attachments/assets/e4cf4478-7397-4c52-90de-18bb9d357430">

**Comment by ghost** [comment]
Anthropic working fine as well 
<img width="1164" alt="Screenshot 2024-08-06 at 8 13 18 AM" src="https://github.com/user-attachments/assets/18400442-ace0-4c4c-abd7-3a318de9419c">

**Comment by ghost** [comment]
cohere working fine as well 

<img width="1161" alt="Screenshot 2024-08-06 at 8 13 46 AM" src="https://github.com/user-attachments/assets/1fc7acf5-c34d-4065-ac7a-7e90a63c1227">

**Comment by ghost** [comment]
Closing as unable to repro @tomasmcm 

If you still see this on latest - can you share a way to repro this behaviour?

**Comment by tomasmcm** [comment]
@krrishdholakia This is an issue with the python sdk (LiteLLM Router) not the proxy.

**Comment by tomasmcm** [comment]
@krrishdholakia some extra context. Indeed if I copy the code to an isolated python file, the callbacks are all being called.
So this issue might be a conflict within my codebase which is a Flask project. Any ideas?

**Comment by tomasmcm** [comment]
but if I add a `time.sleep(1)` after the `for chunk in response` the success callback is called. So something is cutting off litellm from running

**Comment by ghost** [comment]
@tomasmcm the proxy just calls the python sdk in a fastapi app - https://github.com/BerriAI/litellm/blob/511f4d33d16ea3e6b5ebe8adf371f16393426fd3/litellm/proxy/proxy_server.py#L2968

This seems specific to how flask is running - is there a chunk being yielded causing the loop to close before completion?

**Comment by tomasmcm** [comment]
I think I found the culprit! I wanted to reduce the amount of logs and had these lines in my code:
```
litellm.no_logs = True
logging.getLogger("LiteLLM").setLevel(logging.INFO)
logging.getLogger("LiteLLM Router").setLevel(logging.INFO)
```

When I removed the first one `litellm.no_logs` it started working 💥 
The odd thing is why was it affecting only the success callback and not the on stream callbacks

**Comment by ghost** [comment]
what is `no_logs` @tomasmcm that doesn't look like a known litellm attribute

**Comment by tomasmcm** [comment]
~@krrishdholakia https://github.com/BerriAI/litellm/blob/main/litellm/main.py#L713~

**Comment by ghost** [comment]
that's not `litellm.no_logs` @tomasmcm 

it's `completion(..., no-log=True)`

**Comment by tomasmcm** [comment]
sorry, quick search copy paste 🙈 Seems I can't find where I got that from, it was either from the source code somewhere, or from an issue here on github, but can't find it now
