### ISSUE TITLE
[Feature]: Add support for DEEPSEEK_API_BASE

### ISSUE THREAD

**Issue by paul-gauthier** [BerriAI/litellm#5066]
### The Feature

Deepseek now has a beta API endpoint. Currently you need to use it to get 8k output tokens.

https://platform.deepseek.com/api-docs/pricing/

> (2) The 8K output tokens limit of the [Chat Completion API](https://platform.deepseek.com/api-docs/api/create-chat-completion) is in Beta and requires user to set base_url="https://api.deepseek.com/beta". If the base_url is not set to the Beta url, or max_tokens parameter is not set, the limit is 4K tokens.​

### Motivation, pitch

n/a

**Comment by ghost** [comment]
hey @paul-gauthier - will add support for the env var, but you can also pass the base dynamically via `completion(...,api_base="..")` 

https://docs.litellm.ai/docs/set_keys#api_base

Curious - why not do that?

**Comment by paul-gauthier** [comment]
Aider supports ~all the litellm providers & models. Users can specify any model with `--model <provider>/<model>`. Aider expects all needed keys/params for the given provider to be set by the user in env vars where litellm can find them.

Aider users can use 2 different models at the same time, switch between models dynamically during a session, etc. This all works smoothly with the mental model of "just name the model to use, all its config will be present in the env".
