### ISSUE TITLE
[Feature]: Support upstream batching on Azure OpenAI

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#5073]
### The Feature

Basically the same as #3247, but for Azure OpenAI.

Related to #3734; IMO all batch providers should look the "same" to LiteLLM users.

https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/batch?tabs=standard-input&pivots=programming-language-ai-studio

### Motivation, pitch

Cost savings, better rate limits, etc.

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by havingzou** [comment]
same issue

**Comment by ghost** [comment]
missed this. thanks for the link to this issue @Manouchehri

**Comment by ghost** [comment]
Not sure  what the best way of specifying which provider you're trying to call is

For v0, keeping it to be read in from url - 

For openai, either the default or 
```
http://0.0.0.0:4000/v1/batches
```

provider specified 

```
http://0.0.0.0:4000/openai/v1/batches
```

azure needs to specified 

```
http://0.0.0.0:4000/azure/v1/batches
```

**Comment by ghost** [comment]
@Manouchehri let me know if you have a cleaner approach here (ideally it works with openai sdk)

**Comment by ghost** [comment]
This is now supported - https://docs.litellm.ai/docs/batches#azure-batches-api
