### ISSUE TITLE
About the second bug from cost calculator, it is because `prompt_tokens` in the response from Voyage API is `None`.

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#5087]
About the second bug from cost calculator, it is because `prompt_tokens` in the response from Voyage API is `None`.
> CreateEmbeddingResponse(data=[Embedding(embedding=[], index=0, object='embedding')], model='voyage-code-2', object='list', usage=Usage(prompt_tokens=None, total_tokens=7))

_Originally posted by @elkotito in https://github.com/BerriAI/litellm/issues/4720#issuecomment-2273733018_

**Comment by ghost** [comment]
this is now fixed with - https://github.com/BerriAI/litellm/commit/1553f7fa4844ea4d4117c7a75d165ca2e747b81a
