### ISSUE TITLE
[Bug]: Test helicone integration works when switching from azure to openai

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#509]
### What happened?

make sure our helicone integration works  (caching+logging) when switching from azure to openai 

### Relevant log output

```shell
churned user feedback
```

**Comment by ghost** [comment]
<img width="617" alt="Screenshot 2023-10-02 at 2 22 57 PM" src="https://github.com/BerriAI/litellm/assets/17561003/9fdc9e95-16ed-429a-8fb0-53a49ed5bc4b">
