### ISSUE TITLE
Model load balancing problem

### ISSUE THREAD

**Issue by guleng** [BerriAI/litellm#5094]
The correlation between the previous and next problems during model load balancing has failed. How can we handle this in Litellm? Otherwise, the error rate of the model's answers will be too high

<img width="1044" alt="image" src="https://github.com/user-attachments/assets/849aebde-0f41-4830-bc37-68ed6f0e820b">

I can't use any of these three methods
Thank you for your response

**Comment by ghost** [comment]
> The correlation between the previous and next problems

What does this mean? @guleng can you please create a new issue following our format for submitting bug reports
