### ISSUE TITLE
[Feature]: support personal user budgets

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#5097]
### The Feature

Allow setting a budget on a user and having it only apply when the key is for personal user 

If the key belongs to the team and is attributed to the user, then the user's personal budget shouldn't apply to it 

### Motivation, pitch

Make it easier to give keys for dev vs. prod

**Comment by ghost** [comment]
This could be as simple as respecting team budgets / team member budgets over personal user budgets, if a key belongs to a team
