### ISSUE TITLE
[Feature]: Add documentation on input param mapping

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#510]
### The Feature

Have a table in https://docs.litellm.ai/docs/completion/input

showing which params get mapped for which models / providers. 

### Motivation, pitch

Make it clear to the user what gets mapped where. + Help us identify gaps we need to make sure we've added the mapping for.

**Comment by ghost** [comment]
Done -

**Comment by ghost** [comment]
<img width="1081" alt="Screenshot 2023-10-05 at 11 46 10 AM" src="https://github.com/BerriAI/litellm/assets/17561003/79143f75-ad5c-4a43-973d-852699a7ea88">
