### ISSUE TITLE
[Bug]: Cannot use openai gpt-4o-2024-08-06 from UI 

### ISSUE THREAD

**Issue by mcathena** [BerriAI/litellm#5102]
### What happened?

![Snipaste_2024-08-08_10-33-18](https://github.com/user-attachments/assets/1eb4f5e3-417c-4b46-bef2-9226b9ea5775)
Added gpt-4o-2024-08-06 model from openai. 

when testing model returned the following error
`
Error occurred while generating model response. Please try again. Error: Error: 400 LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=gpt-4o-2024-08-06 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers
`

**Comment by superpoussin22** [comment]
are you sing the last version ? , I don't have the issue on my side

**Comment by ghost** [comment]
Unable to repro on my end @mcathena 

I added a model via ui (see "db_model: true") and was able to make calls to it (see screenshot of post request) 

<img width="1065" alt="Screenshot 2024-08-08 at 9 04 57 AM" src="https://github.com/user-attachments/assets/1555c3ab-3e54-4b4d-ad9d-0743eaec483d">
<img width="1207" alt="Screenshot 2024-08-08 at 9 05 03 AM" src="https://github.com/user-attachments/assets/4d0a3501-3e5b-48b3-ac4a-de32ce71c07e">

**Comment by ghost** [comment]
@mcathena if the issue persists on the latest version, can you share more debug information - e.g. what you see when hitting `/model/info`

**Comment by ghost** [comment]
> You passed model=gpt-4o-2024-08-06

I also suspect not all your instances have been restarted, since this looks like an outdated model_cost_map is being used.

**Comment by mcathena** [comment]
Thank you all for your help. I restarted my docker container and now works like a charm!

**Comment by ishaan-jaff** [comment]
Hi @mcathena, curious do you use LiteLLM Proxy in production today If so, I'd love to hop on a call and learn how we can improve LiteLLM for you

- my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
- my linkedin if you prefer DMs: https://www.linkedin.com/in/reffajnaahsi/
