### ISSUE TITLE
[Bug]: `max_internal_user_budget` not applied as expected

### ISSUE THREAD

**Issue by johnson-liang** [BerriAI/litellm#5106]
### What happened?

`max_budget` is not set when `max_internal_user_budget` is provided in `litellm_settings` when new users are created.

Both `/user/new` and Enterprise SSO do not work.

# Steps to reproduce
1. Start a litellm proxy server with following config:
    ```
    litellm_settings:
      max_internal_user_budget: 0.001
      budget_duration: 5m
    ```
    and the following env:
    - LITELLM_MASTER_KEY (required for UI)
    - DATABASE_URL
    - LITELLM_LICENSE (following envs are required for Google sign in)
    - GOOGLE_CLIENT_ID
    - GOOGLE_CLIENT_SECRET
    - PROXY_BASE_URL
   
2. Create a user using `/user/new`
    ```
    curl -XPOST 'http://localhost:4000/user/new' \
      --header 'Authorization: Bearer <master-key>' \
      --header 'Content-Type: application/json' \
      --data-raw '{
        "user_id": "test-user",
        "user_alias": "Test User",
        "user_role": "internal_user"
    }'
    ```

3. Create another user via Google sign in by visiting `localhost:4000/ui`
4. Inspect DB via `DATABASE_URL=postgresql://... npx prisma studio --schema=./schema.prisma`

# Expected
- In `LiteLLM_UserTable` we should see 2 users, both with `max_budget` and `budget_duration` column set.
- When logging into UI, we should be able to see "Max Budget" as [documented here](https://github.com/BerriAI/litellm/pull/5099/files#diff-0f8e98ba4e655f85c79a21d5d9913739d638e9454ad55fdd7a5250d38771b025)

# Actual
`max_internal_user_budget` is not set for SSO user.
`budget_duration` are not set for both users.
![圖片](https://github.com/user-attachments/assets/350d31bc-b316-4eba-b43d-4a8db10e8078)

Thus no "Max Budget" in UI for SSO user
![圖片](https://github.com/user-attachments/assets/ef637cb2-a1c8-49b3-b106-9917a9d65e5a)

# Suspected root cause
1. In #5009 the logic that applies `max_internal_user_budget` only exists in `/user/new` handler, but not in `/sso/callback` handler (or more specifically, the user creation logic for the `generate_key_helper_fn` method)
2. `budget_duration` seems to not processed in both `/user/new` and `/sso/callback`.

# Affected version
1.43.3

**Comment by johnson-liang-appier** [comment]
Another thing is that if the user is inserted into user table when adding team members (`/team/member_add`), the `max_budget` are not set either.

**Comment by ghost** [comment]
Unable to repro the issue on `/user/new` @johnson-liang 

Curl - 
<img width="1160" alt="Screenshot 2024-08-08 at 10 44 57 AM" src="https://github.com/user-attachments/assets/14ff3b31-53fe-4986-947f-6060ac4f63d7">

Config: 
```yaml
model_list:
  - model_name: "gpt-3.5-turbo"
    litellm_params:
      model: "gpt-3.5-turbo"

litellm_settings:
  max_internal_user_budget: 0.001
```

**Comment by ghost** [comment]
The UI issue should be fixed here - https://github.com/BerriAI/litellm/commit/ee8d2f25b93cdccc2fe6377a51c63c5bc7927b43

**Comment by krrishdholakia** [comment]
i see on the deployed docker image that this isn't working as expected 
<img width="1171" alt="Screenshot 2024-08-08 at 10 49 40 AM" src="https://github.com/user-attachments/assets/aa26fbe1-fb96-4b66-9105-46f83ea68169">


Testing further - could this be ci/cd picking up the wrong commit during docker publish?

**Comment by ghost** [comment]
Confirmed the `/user/new` max budget limit works on a deployed container running v`1.43.3` 

Hosted endpoint - https://post-release-load-test-proxy.onrender.com/
<img width="1190" alt="Screenshot 2024-08-08 at 10 54 48 AM" src="https://github.com/user-attachments/assets/86b340a6-9d68-4167-afa8-15f9465db42f">

**Comment by ghost** [comment]
fixing sso issue now

**Comment by MrOrz** [comment]
Sorry that the first sentence is a bit misleading. I forgot to update the description after my experiments.

What I really meant was, when `max_internal_user_budget` and `budget_duration` are set in `litellm_settings`:
- SSO users don't get `max_budget` and `budget_duration` set when first registered
- `/user/new` sets the `max_budget` correctly (aligns with the screenshot), but also no `budget_duration`

Not sure if I understand the `budget_duration` correctly though. Does it work even if it's not written in the user table?

Another thing I found is that `/team/member_add` seems to also create users when the specified `user_id` and `user_email` does match an existing user. I haven't tried it out yet, but [from the source code](https://github.com/BerriAI/litellm/blob/5d664c0441098e17436546de6ca40ff47683de81/litellm/proxy/management_helpers/utils.py#L44-L65) I don't see `max_budget` is written when `/team/member_add` creates new users.

**Comment by ghost** [comment]
Breaking down the issues: 
- SSO users don't get max_budget and budget_duration set when first registered
- `/user/new` doesn't set `budget_duration` correctly

**Comment by ghost** [comment]
@MrOrz @johnson-liang unable to repro the issue re: budget_duration either - 
<img width="1125" alt="Screenshot 2024-08-08 at 12 56 32 PM" src="https://github.com/user-attachments/assets/92d6bb97-6fdb-4c1e-9ca7-b1b31ac7ae6d">


do you have a sample call to repro the problem?

**Comment by ghost** [comment]
oh i see - you set it in the litellm_settings

**Comment by ghost** [comment]
i believe that applies for keys, not users. I'll expose a similar flag for internal users

**Comment by ghost** [comment]
would it help if we just exposed something like -

```yaml
litellm_settings:
    default_internal_user_params:
         max_budget: .. 
         budget_duration: .. 
```

@johnson-liang

**Comment by ghost** [comment]
Just added support for the `litellm.internal_user_budget_duration` flag 

```yaml
model_list:
  - model_name: "gpt-3.5-turbo"
    litellm_params:
      model: "gpt-3.5-turbo"

litellm_settings:
  max_internal_user_budget: 0.001
  internal_user_budget_duration: "5m"
```

**Comment by ghost** [comment]
confirmed it works as expected for `/user/new` 
<img width="1198" alt="Screenshot 2024-08-08 at 1 06 46 PM" src="https://github.com/user-attachments/assets/69953769-12ed-4167-bd1f-38feabd85f32">
