### ISSUE TITLE
[Bug]: Cannot add user to team using email

### ISSUE THREAD

**Issue by johnson-liang** [BerriAI/litellm#5112]
### What happened?

# Step to reproduce
1. In the UI, add a user to a team using email
2. User check team dropdown in UI

# Expected
- The user should see the team they are newly added to in the dropdown

# Actual

Following the steps in reproduction step, the user cannot see the team in the UI
https://github.com/user-attachments/assets/d0aa85ee-9e45-459d-b124-630b4d8bb3e4

# Suspected root cause
If we add team member by user ID, the user can see themselves in the dropdown.

The root cause is very likely in `add_new_member` method. 
When we add member via User ID, the `teams` field is correctly updated.
However, the upsert logic does not exist when we add user via email.
![圖片](https://github.com/user-attachments/assets/e7c46766-199a-4b2b-b4a5-0feda4522ada)

Also, note that there is no single point of truth for membership -- we need to update both the user table and the team table in order to add an existing user to a team. The bug could have been avoided if we only store the membership information in either the team table or the user table.

**Comment by ghost** [comment]
able to repro issue
