### ISSUE TITLE
[Bug]: max_retries hard coded to 2

### ISSUE THREAD

**Issue by ogunoz** [BerriAI/litellm#5124]
### What happened?

I noticed that no matter which value i pass for max_retries, it becomes None in completion function then due to the hardcoded default `max_retries = data.pop("max_retries", 2)` it always passed to openai library as 2.

Any reason it is passed as 2? Even if it was passed as None would be way better because one can redefine/update DEFAULT_MAX_RETRIES variable in openai library to change the default behavior.

So i suggest changing 

```python
max_retries = data.pop("max_retries", 2)
```
to
```python
max_retries = data.pop("max_retries", None)
```

If for some reason an integer necessary then can we can read it from a module level variable e.g., existing `num_retries` in `__init__.py` so we/consumers can update the value of that.

**Comment by ogunoz** [comment]
I am using instructor library as well so my usage is 
```python
client = instructor.from_litellm(completion=litellm.completion)
```

Even if I send max_retries
```python
client.chat.completions.create(..., max_retries=0)
```

It is becoming None in litellm.completion (probably instructor takes max_retries and send rest of kwargs to completion) therefore I have a need to set a default at least

**Comment by motin** [comment]
I was also passing max_retries, but the docs actually says num_retries as the parameter that LiteLLM uses to configure retries: https://docs.litellm.ai/docs/completion/reliable_completions#retry-failed-requests

**Comment by ogunoz** [comment]
Wow thank you! I will give it a try, i wonder what happens if i give then num_retries to instructor client

**Comment by ogunoz** [comment]
In the source code however it is deprecated (at least internally)
```python
num_retries = kwargs.get("num_retries", None)  ## deprecated
max_retries = kwargs.get("max_retries", None)
```

**Comment by ogunoz** [comment]
I can confirm that it doesn't work with num_retries as well. Seems like it would work if I use completion function directly not through instructor wrapping

**Comment by ghost** [comment]
i can repro this behaviour

**Comment by ghost** [comment]
Instructor doesn't pass `max_retries` to us. Confirmed via `litellm.set_verbose=True` 

My call to instructor 
```python
import instructor

from litellm import completion
from pydantic import BaseModel


class User(BaseModel):
    name: str
    age: int


client = instructor.from_litellm(completion)

litellm.set_verbose = True

resp = client.chat.completions.create(
    model="gpt-3.5-turbo",
    max_tokens=1024,
    messages=[
        {
            "role": "user",
            "content": "Extract Jason is 25 years old.",
        }
    ],
    response_model=User,
    max_retries=10,
)

assert isinstance(resp, User)
assert resp.name == "Jason"
assert resp.age == 25

```

LiteLLM Received: 
> litellm.completion(messages=[{'role': 'user', 'content': 'Extract Jason is 25 years old.'}], model='gpt-3.5-turbo', max_tokens=1024, tools=[{'type': 'function', 'function': {'name': 'User', 'description': 'Correctly extracted `User` with all the required parameters with correct types', 'parameters': {'properties': {'name': {'title': 'Name', 'type': 'string'}, 'age': {'title': 'Age', 'type': 'integer'}}, 'required': ['age', 'name'], 'type': 'object'}}}], tool_choice={'type': 'function', 'function': {'name': 'User'}})

<img width="1480" alt="Screenshot 2024-08-09 at 4 51 36 PM" src="https://github.com/user-attachments/assets/3ede9946-ad30-4d6c-a421-2ecbce54d331">

**Comment by ghost** [comment]
Instructor **does pass** `num_retries` 

This should be a quick fix

**Comment by ogunoz** [comment]
Thank you so much for very quick support. I also tried with your released version and it works as expected 🎉🙌, before i had to do some hacky patching for `litellm.main.get_optional_params` to pass retry count, now i don't need anymore, very appreciated!
