### ISSUE TITLE
[Bug]: Add Cohere embeddings models on Admin UI 

### ISSUE THREAD

**Issue by guleng** [BerriAI/litellm#5133]
### What happened?

I added the coal model in the graphical interface, but it doesn't work properly when added in OpenAI compatibility mode. How can I configure the embedded and Rerank type models?
![WX20240809-232307@2x](https://github.com/user-attachments/assets/83f74779-3311-4942-b9f0-25b8686a937a)

### Relevant log output

```shell
{"error":{"message":"litellm.UnsupportedParamsError: Setting user/encoding format is not supported by cohere. To drop it from the call, set `litellm.drop_params = True`.\nReceived Model Group=embed-english-v2.0\nAvailable Model Group Fallbacks=None","type":"None","param":null,"code":"400"}}%
```
```


### Twitter / LinkedIn details

_No response_

**Comment by ishaan-jaff** [comment]
working on this

**Comment by ishaan-jaff** [comment]
done here @guleng https://github.com/BerriAI/litellm/pull/5136

**Comment by ishaan-jaff** [comment]
For Rerank we support setting it up as a pass through on the config yaml https://docs.litellm.ai/docs/proxy/pass_through 

would that work @guleng or do you prefer setting it on the UI

**Comment by ishaan-jaff** [comment]
Adding Cohere embedding models will be live on 1.43.5
