### ISSUE TITLE
[Bug]: Function calling with fireworks.ai

### ISSUE THREAD

**Issue by Clad3815** [BerriAI/litellm#5157]
### What happened?

Fireworks handle tools: https://docs.fireworks.ai/guides/function-calling#supported-models
Can we make it work with LiteLLM ?

**Comment by ishaan-jaff** [comment]
this is already supported @Clad3815 - did you run into a bug ?

**Comment by Clad3815** [comment]
Ok it's my bad, llama 405b don't support tools. But there is no error from their API about that

**Comment by ghost** [comment]
what did you see instead? @Clad3815

**Comment by ishaan-jaff** [comment]
Hi @Clad3815 , curious do you use LiteLLM Proxy in production today If so, I'd love to hop on a call and learn how we can improve LiteLLM for you

- my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
- my linkedin if you prefer DMs: https://www.linkedin.com/in/reffajnaahsi/
