### ISSUE TITLE
You exceeded your current quota, please check your plan and billing details.

### ISSUE THREAD

**Issue by lgkiet** [BerriAI/litellm#516]
Conversation history: 

Ted Lasso:
openai 2023-10-03 20:09:00,995 - INFO - error_code=insufficient_quota error_message='You exceeded your current quota, please check your plan and billing details.' error_param=None error_type=insufficient_quota message='OpenAI API error received' stream_error=False

Can you help me ? I tried different OPENAI_API_KEY already but it does not work for me

**Comment by ghost** [comment]
@lgkiet this looks like an issue with your billing account on openai. 

As an alternative try https://openrouter.ai/
