### ISSUE TITLE
[Bug]: validation error for UserAPIKeyAuth after upgrading litellm from 1.41.13 -> 1.42.12

### ISSUE THREAD

**Issue by vdubovets** [BerriAI/litellm#5164]
### What happened?

Hi Team, 
We have an Authentication issue (see logs below) after upgrading Litellm version from 1.41.13 to 1.42.12.
Rolling back to previous version helped to remediate the issue.

Can you please help to identify which changes made such impact?

### Relevant log output

```shell
Cannot execute prompt - GptAPIError. Cause: Error code: 401 - {'error': {'message': "Authentication Error, 1 validation error for UserAPIKeyAuth\nuser_role\n  Input should be <LitellmUserRoles.PROXY_ADMIN: 'proxy_admin'>, <LitellmUserRoles.PROXY_ADMIN_VIEW_ONLY: 'proxy_admin_viewer'>, <LitellmUserRoles.INTERNAL_USER: 'internal_user'>, <LitellmUserRoles.INTERNAL_USER_VIEW_ONLY: 'internal_user_viewer'>, <LitellmUserRoles.TEAM: 'team'> or <LitellmUserRoles.CUSTOMER: 'customer'> [type=literal_error, input_value='app_user', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.7/v/literal_error", 'type': 'auth_error', 'param': 'None', 'code': '401'}}
```

**Comment by ghost** [comment]
hey @vdubovets i can't tell what line in server logs this originates from. Can you confirm this issue exists on v`1.43.7` and share the stacktrace from server, if so?

**Comment by ghost** [comment]
I believe we've added handling for older user roles here - https://github.com/BerriAI/litellm/blob/b3c7d63ec15703970132fd290941a4b5d6398cdb/litellm/proxy/auth/user_api_key_auth.py#L1192

(v1.43.3 onwards)

**Comment by ghost** [comment]
@vdubovets can we setup a direct support channel for your team, to help solve these issues? 

Here's a [Slack invite](https://join.slack.com/share/enQtNzU4NzA3MjQzMTAwOC01MjNlN2ZiZjdiNTI2Y2IwMzIyMTM4Mjg5OTNmMjE1ZDhhOWRjY2IxOTE1NmI2Y2NjNGIxYzU5NzAyNDMyYWFk), let me know if that works!

**Comment by ghost** [comment]
I can confirm keys for users with `role=app_user` works on v1.43.7 
<img width="1186" alt="Screenshot 2024-08-12 at 11 44 18 AM" src="https://github.com/user-attachments/assets/fa11a3d6-83c9-4091-85bb-d0a290691c76">

<img width="1217" alt="Screenshot 2024-08-12 at 11 44 39 AM" src="https://github.com/user-attachments/assets/df494d99-867c-43c0-95fc-c0e1fa8ee0c9">

**Comment by vdubovets** [comment]
Thanks @krrishdholakia ,
Now it's clear. The issue was related to old role (app_user) usage which is not supported in 1.42.12 version.
I will update the user role to the newer  and upgrade LiteLLM to the latest version

**Comment by ghost** [comment]
Hi @vdubovets we've made it backwards compatible already - no change needed on your end

**Comment by ishaan-jaff** [comment]
Hi @vdubovets , curious do you use LiteLLM Proxy in production today If so, I'd love to hop on a call and learn how we can improve LiteLLM for you

- my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
- my linkedin if you prefer DMs: https://www.linkedin.com/in/reffajnaahsi/
