### ISSUE TITLE
[DevOps] Add Testing for langchain integration + huggingface models

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#517]
What happened? 
We pushed an update to raise exceptions if a param wasn't mapped. This led to errors for people using our langchain integration as langchain passes in a bunch of default openai values to litellm. 

What is the proposed solution? 
Have a `test_langchain.py` file that replicates the call langchain is making via litellm. Ensure it works for openai + non-openai models (cohere, anthropic, huggingface, etc.)

**Comment by ghost** [comment]
@ishaan-jaff i believe you added this.
