### ISSUE TITLE
[Feature]: Allow logging to different langfuse projects by key 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#5170]
### The Feature

The same team might have different langfuse projects. Allow logging to different projects by key, not just team. 

### Motivation, pitch

User request

### Twitter / LinkedIn details

@elvis-cai

**Comment by ghost** [comment]
I assume the simplest way to do this, is to just add this when creating a new key 

```bash
curl -X POST 'http://0.0.0.0:4000/key/generate' \
-H 'Authorization: Bearer sk-1234' \
-H 'Content-Type: application/json' \
-d '{
    "metadata": {
        "logging": {
            "callback_name": "langfuse", # 'otel', 'langfuse', 'lunary'
            "callback_type": "success" # set, if required by integration - future improvement, have logging tools work for success + failure by default 
            "callback_vars": {
                "langfuse_public_key": "pk",
                "langfuse_secret_key": "sk_",
                "langfuse_host": "https://cloud.langfuse.com"
            }
        }
    }
}'

```

**Comment by krrishdholakia** [comment]
i don't think it's great that langfuse keys would be stored this way (in metadata in db), ideally we could point this value (like we do in config) to an existing environment variable

**Comment by ghost** [comment]
It is too unsafe to pass in langfuse / logging credentials this way. Including support for adding env var names to the v0 scope. 

This allows setting the environment variable as a key value - which prevents the raw credentials from being accidentally logged anywhere (langfuse, otel, etc.) 

<img width="727" alt="Screenshot 2024-08-12 at 8 56 54 PM" src="https://github.com/user-attachments/assets/e832294f-6bcf-4e84-8de9-2eddfee2ccfd">
