### ISSUE TITLE
[Feature]: Support LangSmith "extra" field

### ISSUE THREAD

**Issue by MarkRx** [BerriAI/litellm#5179]
### The Feature

The "extra" field can be used to pass in custom metadata.

Example:
```
"extra": {
    "metadata": {
        "my-key": "my-value"
    }
},
```

See
[REST API](https://api.smith.langchain.com/redoc#tag/run/operation/create_run_api_v1_runs_post)
[Documentation](https://docs.smith.langchain.com/old/tracing/faq/customizing_trace_attributes)
#4853

### Motivation, pitch

The ability to pass in custom metadata using LangSmith with LiteLLM isn't possible at the moment.

**Comment by ishaan-jaff** [comment]
hi @MarkRx - thanks for the issue do you want to do this through the LiteLLM proxy or on the LiteLLM python SDK ?

**Comment by MarkRx** [comment]
> hi @MarkRx - thanks for the issue do you want to do this through the LiteLLM proxy or on the LiteLLM python SDK ?

The python SDK

**Comment by ghost** [comment]
great idea!
