### ISSUE TITLE
[Feature]: Map additional openai params to providers

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#519]
### The Feature

Add support for openai params across all providers

### Motivation, pitch

Today there's a bunch of missing param translations - https://docs.litellm.ai/docs/completion/input. 

<img width="1081" alt="Screenshot 2023-10-03 at 9 28 46 AM" src="https://github.com/BerriAI/litellm/assets/17561003/15427f65-c2e8-455b-9091-111fb3014d55">

Eg. mapping `n` to Anthropic, etc.

**Comment by ghost** [comment]
Mapping needs to be done here - https://github.com/BerriAI/litellm/blob/512769e84105a24fd7118ba18b71805ab94c28d3/litellm/utils.py#L930

**Comment by ghost** [comment]
just added mappings for ai21 - 851cb86daa835a48be5ab42eb14fa0be6e633567

**Comment by ghost** [comment]
done - https://docs.litellm.ai/docs/completion/input
