### ISSUE TITLE
[Bug]: Logging of exceptions is quite unpythonic and doesn't play nice with existing tools

### ISSUE THREAD

**Issue by fingon** [BerriAI/litellm#5194]
### What happened?

Currently the code has lots of patterns like this (~330 of them):

```
try:
...
except Exception as e:
  verbose_logger.error(f"LiteLLM Cache: Excepton async add_cache: {str(e)}")
  verbose_logger.debug(traceback.format_exc())
```

(Note that that same error message is used for all exceptions in that class, another 'feature')

While modern way of doing it would be simply to do:
```
try:
...
except Exception:
  verbose_logger.exception("LiteLLM Cache: async_add_cache")
```

This has number of benefits, e.g. Sentry will actually work correctly, and the code looks cleaner. 

Example what I did to fix my local use: https://github.com/BerriAI/litellm/commit/b589a8f4a02b5888231c7765e1bd99d5b54703c4 (I didn't make PR as there's 300+ places and they should be ideally fixed and identified with e.g. semgrep).

In general there seems to be lots of blanket exception catching (without reraise) which is problematic - we frequently see problems in production only by looking at logs.

**Comment by ghost** [comment]
That looks much better - i'll work on refactoring our code for this. Testing to see if i can still see the stacktrace for debugging locally

**Comment by ghost** [comment]
confirmed i still see the stacktrace locally (which is good). Ok, working on the refactor. Thanks for the catch! @fingon

**Comment by fingon** [comment]
Note that if you want eg debug level, you can call that with exc_info kwarg with the exception.

**Comment by ghost** [comment]
oh - can you share an example? @fingon

**Comment by fingon** [comment]
https://stackoverflow.com/questions/192261/how-do-i-log-an-exception-at-warning-or-info-level-with-traceback-using-the-pyt#193153

```
try:
  …
except Exception:
  logger.debug(“something bad happened but not enough for error severity”, exc_info=True)
```
