### ISSUE TITLE
[Bug]: Return better health endpoint failure error message - indicate 'base_model' being set is required 

### ISSUE THREAD

**Issue by stronk7** [BerriAI/litellm#5196]
### What happened?

I've a number of models defined (config.yaml) and when I run the /health check it correctly reports as healthy_endpoints:
-  OpenAI models.
-  Anthropic models.
- OpenAI embedding models (openai/text-embedding-3-small)
- A custom model deployed for testing purposes.

But I always get Ollama embedding models reported as unhealthy_endpoints:
- ollama/nomic-embed-text
- ollama/all-minilm

That renders the health check unrealistic (certainly all the models are working ok).

Maybe it's normal and expected (if the models don't support whatever is being used to check them, although it surprises to me that the OpenAI embeddings one is being reported ok.

So, not sure if the solution would imply to change the check for embedding models, or move them away from the check or do nothing, heh. For your consideration.

Ciao :-)

### Relevant log output

```shell
10:26:36 - LiteLLM:ERROR: main.py:4898 - litellm.ahealth_check(): Exception occured - litellm.APIConnectionError: {"error":"\"all-minilm\" does not support generate"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 401, in acompletion
    response = await init_response
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/ollama.py", line 507, in ollama_acompletion
    raise e
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/ollama.py", line 446, in ollama_acompletion
    raise OllamaError(status_code=resp.status, message=text)
litellm.llms.ollama.OllamaError: {"error":"\"all-minilm\" does not support generate"}

10:26:36 - LiteLLM:ERROR: main.py:4898 - litellm.ahealth_check(): Exception occured - litellm.APIConnectionError: {"error":"\"nomic-embed-text\" does not support generate"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 401, in acompletion
    response = await init_response
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/ollama.py", line 507, in ollama_acompletion
    raise e
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/ollama.py", line 446, in ollama_acompletion
    raise OllamaError(status_code=resp.status, message=text)
litellm.llms.ollama.OllamaError: {"error":"\"nomic-embed-text\" does not support generate"}
```

**Comment by ghost** [comment]
Hi @stronk7 i believe you're missing the base_model - https://docs.litellm.ai/docs/proxy/health#embedding-models

since we don't have all the ollama models mapped - we aren't able to tell what call we need to make to check model health 

I believe on our end, we can return a better error message, to make it clear what the change required is

**Comment by ghost** [comment]
does that work?

**Comment by stronk7** [comment]
Awesome, that did the trick. I had read that page, some days ago, but did not see it, thanks!

**Comment by ishaan-jaff** [comment]
Hi @stronk7, curious do you use LiteLLM Proxy in production today If so, I'd love to hop on a call and learn how we can improve LiteLLM for you

- my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
- my linkedin if you prefer DMs: https://www.linkedin.com/in/reffajnaahsi/
