### ISSUE TITLE
[Bug]: max_token Cannot exceed 4096

### ISSUE THREAD

**Issue by HGladiator** [BerriAI/litellm#5198]
### What happened?

When the input characters of the large model exceed 4096, has error log : [handleAbortError] AI response error; aborting request: Prompt token count of 4662 exceeds max token count of 4095.

set  litellm.yaml
```
      max_tokens: 8192
      max_input_tokens: 6144
      max_output_tokens: 2048
```
not working properly

### Relevant log output

```shell
error: [OpenAIClient] Error summarizing messages 400 litellm.BadRequestError: OpenAIException - Invalid max_tokens value, the valid range of max_tokens is [1, 4096]
```

**Comment by ghost** [comment]
> litellm.BadRequestError: OpenAIException - Invalid max_tokens value, the valid range of max_tokens is [1, 4096]

This isn't an error from us, but from the backend api provider. What is the ask here? @HGladiator

**Comment by HGladiator** [comment]
error log from  librechat . I have found the reason

**Comment by ghost** [comment]
hey @HGladiator what was the fix? will be useful reference for the future

**Comment by HGladiator** [comment]
The discussion content is in [ this link. ](https://github.com/danny-avila/LibreChat/discussions/3652)       @krrishdholakia
