### ISSUE TITLE
Do you address token counting?

### ISSUE THREAD

**Issue by basicthinker** [BerriAI/litellm#52]
Not sure if litellm is in the right layer to count tokens. But if we switch to using litellm rather than implement our own support for multiple models, it is not as simple as replacing the completion function calls. We also need to count tokens used by different models while they rely on different tokenizers.

In any event, please keep litellm as a thin layer as possible. Don't take it if you believe it is not the right job for litellm. That would ruin litellm easier than lacking functionality. Consider adding some util functions? Happy to discuss.

Note: we are building [DevChat](https://github.com/devchat-ai/devchat), a potential user of litellm. Thanks for your great work!

**Comment by ishaan-jaff** [comment]
@basicthinker yes ! litellm will be returning input / output tokens used for all supported models. Was there a specific model / provider you had in mind for tracking usage ?

**Comment by ghost** [comment]
i'll work on this ticket - will update repo once it's done

**Comment by ghost** [comment]
Hey @basicthinker `version 0.1.341` deals with this (commit: 7575d7ea47666055c708d246fbb817fdc4d4105c) 

version 0.1.341  now returns token usage across all providers. Where possible it uses the providers own tokenizer (E.g. anthropic) else it defaults to tiktoken.

We're posting more regular updates on our discord if you'd like to join - https://discord.com/invite/wuPM9dRgDw

**Comment by ghost** [comment]
@basicthinker / @ishaan-jaff  Closing ticket for now - reopen if it isn't yet addressed.
