### ISSUE TITLE
[Feature]: Add Day-0 support for Anthropic Prompt Caching 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#5207]
### The Feature

https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching#how-prompt-caching-works 

### Motivation, pitch

-

**Comment by ishaan-jaff** [comment]
working on this

**Comment by ishaan-jaff** [comment]
Need to add for both litellm sdk + Proxy 

- Large Context Caching Examples
- Caching tools definitions 
- Continuing Multi-Turn Convo 
- Returning Cache usage - streaming + non-streaming 
- Doc

**Comment by ishaan-jaff** [comment]
done here: https://github.com/BerriAI/litellm/pull/5210 

release queued

**Comment by ishaan-jaff** [comment]
doc here: https://docs.litellm.ai/docs/providers/anthropic#prompt-caching 

This feature will be live on 1.43.13

**Comment by ishaan-jaff** [comment]
would appreciate feedback on this from litellm users when it's live 😄

**Comment by neubig** [comment]
Hey @ishaan-jaff , thanks for the super swift implementation, we're excited to try this! 

Gemini support through the same interface could also be helpful whenever you have a moment: https://ai.google.dev/gemini-api/docs/caching?lang=python

**Comment by ishaan-jaff** [comment]
google ai studio or vertex AI @neubig ?

**Comment by neubig** [comment]
AI studio is easier to use, but either way I guess

**Comment by ishaan-jaff** [comment]
tracking here: https://github.com/BerriAI/litellm/issues/5213 @neubig
