### ISSUE TITLE
[Feature]: Support creating pass-through endpoints on the UI

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#5212]
### The Feature

Allow user to add pass-through endpoints via Proxy UI 

### Motivation, pitch

Make it easy for developer to create pass through endpoints for langfuse - so they don't need to expose their langfuse keys in projects

**Comment by ghost** [comment]
~~- Need a way to get pass-through spec (populate UI with this) -> can re-use `/config/field/info`~~
- Need a way to get pass-through endpoints -> GET `/config/pass_through_endpoint`
- Need a way to create pass-through endpoints -> POST `/config/pass_through_endpoint`
- Need a way to delete pass-through endpoints -> DELETE `/config/pass_through_endpoint`
