### ISSUE TITLE
[Feature]: Allow synchronous logging of success events

### ISSUE THREAD

**Issue by B-Step62** [BerriAI/litellm#5216]
### The Feature

(Re-bumping the request that seems to be considered once in https://github.com/BerriAI/litellm/issues/897)

The `log_success_event` handler for logging is called in a separate thread that is never joined ([code](https://github.com/BerriAI/litellm/blob/main/litellm/utils.py#L927-L930)). This makes a lot sense for performance perspective.

However, sometimes synchronous logging is also useful. For example, if we want to show some message/log based on success event on a notebook, the logging call has to be made synchronously, because the notebook does not update cell output after the main thread completes.

<img width="402" alt="Screenshot 2024-08-15 at 14 01 11" src="https://github.com/user-attachments/assets/165565ba-9567-4eaf-913d-bc651ce48a09">

Also, the `log_failure_event` is handled synchronously, meaning that the success and failure events arrives in different order than they occur.

Thereby, it would be useful if there is a configuration / env variable with which we can make success event logging synchronously.

### Motivation, pitch

Enable custom logging that requires synchronous event handling.

**Comment by ghost** [comment]
Hey @B-Step62 log_failure_event is handled sync very carefully, to because the event is needed for reliable error handling - e.g. in router, to manage model cooldowns. 

log_success_event is handled in a separate thread, as the call is often made for different logging integrations - which slow down perf when used in the same thread. 

to deal with the notebook scenario, why not just add a 3s time.sleep? it would be reasonable to expect the event to be called by then.

**Comment by ghost** [comment]
Closing for now as not planned, please feel free to reopen/file a new issue if the suggested solution doesn't work for you.

**Comment by B-Step62** [comment]
Thank you for the reply, @krrishdholakia.

Yes, we understand the performance downside so the proposal is to add a switch e.g. env variable to let users choose with acknowledging it. We are not proposing to make it default behavior.

> to deal with the notebook scenario, why not just add a 3s time.sleep? it would be reasonable to expect the event to be called by then.

Unfortunately, this solution does not work. The logging operation does not take fixed time, especially when it includes expensive operation such as DB write, network call. The actual overhead is dynamic, so the fixed value will sacrifice either reliability or efficiency.

Another option we looked at is [log_post_api_call](https://github.com/BerriAI/litellm/blob/398295116f38346333d1dee2bd7cc09e6ec72e96/litellm/litellm_core_utils/litellm_logging.py#L493-L498). This handler ruins in synchronous way and we thought it could be used for our use case. However, one blocking issue was it does not provide a reliable way to check the prediction is success or failure. What to be passed to the `response_obj` field is up to the integration provider and there is no standard - it can be `response.text`, pydantic object, JSON string, etc. Therefore, we need to rely on the success/failure handlers.

**Comment by B-Step62** [comment]
@krrishdholakia Btw it seems I don't have a permission to reopen the issue.

**Comment by ghost** [comment]
> The logging operation does not take fixed time, especially when it includes expensive operation such as DB write, network call

you're writing to the db as part of a sync llm call?

**Comment by B-Step62** [comment]
@krrishdholakia Sorry for getting back late. There were some urgent work on my plate.

To give you more context, we've been trying to add integration of [MLflow Tracing](https://mlflow.org/docs/latest/llms/tracing/index.html) with LiteLLM. One requirement for this feature is it needs to work within Databricks notebook environment. In Databricks notebook, MLflow will render a trace inline in the output cell, which is very convenient for users to debug LLM calls within notebook.

However, the problem is that generating a trace on Databricks notebook involves a synchronous network request due to backend reason which we cannot change right now. If we run this operation asynchronously, the notebook cell execution might finish earlier than the trace generation. In such case, the trace cannot be rendered in the cell output.

While I understand it is not an ideal experience to add overhead of synchronous network request to the LLM call, but we believe it won't be too bad UX because it only happens in Databricks notebook. In other environments we typically have very small overhead (less than tens of ms).

Also, we only propose to add a switch to enable synchronous logging, not asking for changing the default behavior. Therefore, there is no impact for customers who don't use MLflow logger. Since the [downside](https://github.com/BerriAI/litellm/issues/5216#issuecomment-2295546941) of using `post_call` handler is large, it would be awesome if you could reconsider this requeest.

Thank you so much.

**Comment by B-Step62** [comment]
@krrishdholakia Would you mind providing some guidance on this?

**Comment by B-Step62** [comment]
@ishaan-jaff @krrishdholakia I would appreciate it if you could provide your thoughts on this when you have a moment.

**Comment by B-Step62** [comment]
@krrishdholakia I went ahead to implementing logger  https://github.com/BerriAI/litellm/pull/6147, but this is still a blocking issue. Would appreciate if you could help on resolving this. Thanks.
