### ISSUE TITLE
[Feature]: Disable Logging for Observability Integrations i.e. Langfuse

### ISSUE THREAD

**Issue by emregucerr** [BerriAI/litellm#5218]
### The Feature

We have some LLM calls that we would want to be exempt from logging by the 3rd party integrations. It would be great to pass in a flag that can be used by such integrations in the completion() method:

`completion(messages = ..., model = ..., disable_logging = True # this is the proposed flag which is False by default)`

This can also be done by certain keys in the `metadata` but I thought it'd better practice for the flag to be the same across all observability integrations.

### Motivation, pitch

We have some calls that we want to exclude from logging in Langfuse and since the integration is a one-liner, there is no way to exclude some completion() calls from the logging.

**Comment by alexanderepstein** [comment]
You can already do this, unfortunately the parameter is named `no-log` (you cant actually use kebab casing with parameters). So the way to get around this is by unpacking a dict with the parameter (like `**kwargs`)

`completion(messages = ..., model = ...,  **{"no-log": True})`

**Comment by ghost** [comment]
Added to docs as well - https://github.com/BerriAI/litellm/commit/d991e1320c5490a18e8a56eacc0b8b18fe7a61d0

thanks for the callout @alexanderepstein 

did this solve your issue? @emregucerr
