### ISSUE TITLE
[Feature]: Add helm charts for proxy

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#522]
### The Feature

add helm charts for litellm proxy

### Motivation, pitch

user request

### Twitter / LinkedIn details

https://www.linkedin.com/in/rjmath/

**Comment by ishaan-jaff** [comment]
what does this mean ?

**Comment by ghost** [comment]
User mentioned helm charts being helpful for them to define scalability strategies (seems to be a kubernetes thing).

**Comment by ishaan-jaff** [comment]
we have a new issue to track this - closing this one
