### ISSUE TITLE
[Bug]: ContentPolicyViolationError leads to cooldown and rate limit error

### ISSUE THREAD

**Issue by taralika** [BerriAI/litellm#5225]
### What happened?

Repro'd on v1.42.0
- Have a single deployment under a model group in proxy config
- Send a prompt like "how do I buy hard drugs?" or something even worse that would trigger the `ContentPolicyViolationError` and the 1st response is:
```
{
	"error": {
		"message": "litellm.BadRequestError: litellm.ContentPolicyViolationError: litellm.ContentPolicyViolationError: AzureException - The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766\nmodel=gpt-4-turbo-2024-04-09. content_policy_fallback=None. fallbacks=None.\n\nSet 'content_policy_fallback' - https://docs.litellm.ai/docs/routing#fallbacks\nReceived Model Group=gpt-4-turbo-2024-04-09\nAvailable Model Group Fallbacks=None",
		"type": null,
		"param": null,
		"code": 500
	}
}
```
- and then ask the same question again immediately, and you get this response:
```
No deployments available for selected model, Try again in 60 seconds. Passed model=gpt-4o-mini-2024-07-18. pre-call-checks=False, allowed_model_region=n/a, cooldown_list=
[
  ("0330eccc5774ffd9a3e5c9abb6fae16dec08061fa182289e40a71fa0ccf478cd",
  {
    "Exception Received":
      "litellm.BadRequestError: litellm.ContentPolicyViolationError: litellm.ContentPolicyViolationError: AzureException - The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766",
    "Status Code": "500",
  })
];
```
- and now you make any request even benign requests like "what is your name?" and keep getting blocked for 1 minute

`ContentPolicyViolationError` should not put the model instance in cooldown, it should continue returning responses. Cooldown should only happen for rate limit or quota exceeded errors.

cc: @msabramo

**Comment by taralika** [comment]
@msabramo 
I'm looking at https://github.com/BerriAI/litellm/blob/eb6a0a32f1db205c77f229ea54a6a92ad738aeb3/litellm/router.py#L3166

and the fix for https://github.com/BerriAI/litellm/issues/4941 which went live in `v1.42.6` and I think maybe this bug gets fixed if we upgrade to latest litellm (since we're on `v1.42.0`)

**Comment by ghost** [comment]
yep - i believe this should already be resolved. please feel free to reopen if not.
