### ISSUE TITLE
[Feature]: Support specifying `api-version` in query string

### ISSUE THREAD

**Issue by msabramo** [BerriAI/litellm#5228]
### The Feature

LiteLLM doesn't support specifying the API version in the request -- e.g.: /openai/deployments/gpt-4-0125-preview/chat/completions?api-version=2024-07-01-preview

In more concrete terms, I would want the following to use the specified OpenAI API version, but it doesn't:

```shell
curl -sSL --request POST \
  --url 'http://0.0.0.0:4000/openai/deployments/gpt-35-turbo-1106/chat/completions?api-version=2024-06-01' \
  --header "Authorization: Bearer $LLM_PROXY_API_KEY" \
  --header 'Content-Type: application/json' \
  --data '{
  "logprobs": true,
  "messages": [{"role":"system","content":"you are a helpful assistant named Michaelangelo who answers questions about art"},{"role":"user","content":"what is your name? What can you help with?"}]
}' | jq '.'
```

This currently results in an error:

```
litellm.BadRequestError: AzureException BadRequestError - This model does not support the 'logprobs' parameter.
```

because it doesn't use API version `2024-06-01`. It uses the default API version of `2024-02-01` and this doesn't support the `logprobs` parameter.

From what I saw in the code, this doesn't work because LiteLLM looks at the model list on startup and creates some objects early on for accessing the models that is already bound to an API version. I didn't see an easy way to make this work.

### Motivation, pitch

Users can decide at runtime which OpenAPI API version they want to use instead of relying on a hard-coded value in the config. When new API versions are available, they can go ahead and use them without any config changes.

Cc: @taralika

**Comment by ghost** [comment]
Fix pushed @msabramo @taralika 

this should be live in prod by EOD

**Comment by msabramo** [comment]
Thanks, @krrishdholakia!

**Comment by msabramo** [comment]
This is not in 1.43.18-stable or 1.43.19-stable, right?

**Comment by ghost** [comment]
Not merged in yet - was waiting on main to be stable @msabramo
