### ISSUE TITLE
[Bug]: Anthropic context caching not working on LiteLLM proxy

### ISSUE THREAD

**Issue by AdithyanI** [BerriAI/litellm#5230]
### What happened?

I followed this : https://docs.litellm.ai/docs/providers/anthropic#caching---large-context-caching

to try the prompt caching released by Claude. I get an error as attached in the logs. I run with the 

```
REPOSITORY                TAG           IMAGE ID       CREATED        SIZE
ghcr.io/berriai/litellm   main-latest   9d9dc221379d   18 hours ago   1.28GB
```

Maybe the latest docker still not have the commits related to this? Please let me know, thanks.

### Relevant log output

```shell
{"type":"error","error":{"type":"invalid_request_error","message":"system.1.cache_control: Extra inputs are not permitted"}
```
```


### Twitter / LinkedIn details

_No response_

**Comment by ishaan-jaff** [comment]
- Can you share code of how you're sending the request to litellm @AdithyanI 
- what version does the swagger say you're on

**Comment by AdithyanI** [comment]
@ishaan-jaff thanks for the reply. I run it via the proxy. And I sent the request like so : 

<img width="724" alt="image" src="https://github.com/user-attachments/assets/d95ec498-da51-47f5-b863-f5418f880e90">


Model name in proxy config : 

<img width="373" alt="image" src="https://github.com/user-attachments/assets/62964f54-e234-488b-bf72-1d2836555014">

**Comment by AdithyanI** [comment]
Swagger version : 
<img width="908" alt="image" src="https://github.com/user-attachments/assets/5b69df9f-22b9-4cb9-bbaf-0c1bcc4c5cb1">

**Comment by ishaan-jaff** [comment]
fixed here: https://github.com/BerriAI/litellm/pull/5238

**Comment by ishaan-jaff** [comment]
does it work on this @AdithyanI https://github.com/BerriAI/litellm/releases/tag/v1.43.15-stable
