### ISSUE TITLE
[Bug]: "created" from litellm openai proxy is float but should be int64

### ISSUE THREAD

**Issue by barakplasma** [BerriAI/litellm#524]
### What happened?

A bug happened when I tried using sashabaranov/go-openai with the litellm proxy because completions from openai are always int64 but python time.time() which litellm uses returns floats.

I was able to fix it locally by changing time.time() to int(time.time()) . I can make a pr if desired 

### Twitter / LinkedIn details

https://il.linkedin.com/in/michaelsalaverry

**Comment by ghost** [comment]
Hey @barakplasma will get this fixed today - thanks!

**Comment by ghost** [comment]
How were you using this with the go-openai repo? @barakplasma

**Comment by ghost** [comment]
@barakplasma change pushed - f99c49e224cb178e8bac1bb07495ec76bc78a32d

I assume you meant the issue was for litellm-proxy? https://github.com/BerriAI/liteLLM-proxy

**Comment by ghost** [comment]
Please re-open if this doesn't solve your issue @barakplasma

**Comment by barakplasma** [comment]
https://github.com/piqoni/matcha/pull/35 context on why I was using litellm: to summarize RSS feeds with Mistral 

My setup was
```mermaid
graph TD
    Matcha --> litellm
    litellm --> ollama
    ollama --> mistralai
```

I didn't realize there was another repo with the openai compatible endpoint.

Your fix is exactly what I wanted ❤️. Thanks!

**Comment by ghost** [comment]
@barakplasma it's a bit confusing right now, but we're working to clean it up. 

I believe if you ran it via our local cli tool, that wouldn't have been an issue as we're hardcoding time - https://github.com/BerriAI/litellm/blob/2cd2c6c486bf791b2f1acb58eb61c6440cbeefb2/litellm/proxy/proxy_server.py#L115


Code: 
```
$ litellm --model ollama/llama2 --api_base http://localhost:11434/
```

Docs: https://docs.litellm.ai/docs/proxy_server#start-proxy

**Comment by ghost** [comment]
Was there a reason you were using the self-hosted implementation vs. the cli tool?

**Comment by barakplasma** [comment]
I used the `pip install litellm` method and ran something very similar to you but with Mistral rather than llama2. 

Why self-hosted: I just didn't want to pay for summarization when I have a Nvidia 1060 GPU lying around

**Comment by ghost** [comment]
Oh - so this was an issue hit via the cli tool? That's interesting, can't see how that got triggered then. Thanks for surfacing it.

**Comment by ishaan-jaff** [comment]
hi @barakplasma thanks for using litellm - we're working on making the cli proxy better for your use case **Any chance you're free for a quick call this week?**

sharing my cal for your convenience: https://calendly.com/ishaan-berri/30min?month=2023-11

**Comment by barakplasma** [comment]
sorry, not available for a call
