### ISSUE TITLE
[Feature]: team-based pass through endpoints

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#5242]
### The Feature

there will be multiple projects in Langfuse and each team will have langfuse project assigned. Currently, callback is there with team based logging and each team has its own litellm proxy key. I was thinking if team proxy key be used for pass through endpoint.

### Motivation, pitch

Allow developers to log to separate langfuse projects even for pass-through endpoints

**Comment by ghost** [comment]
This is now fixed with - https://github.com/BerriAI/litellm/commit/f9640d8a58d9d1e5fce9c685078eb715386de5bd
