### ISSUE TITLE
[Feature]: Enable passing provider-specific parameters

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#526]
### The Feature

Allow me to pass parameters supported by that specific provider

### Motivation, pitch

Not all providers support the same parameters. The **kwargs implementation is a hack, but still introduces conditional logic. 
Enable users to pass provider-specific parameters (e.g. top_k for anthropic).

**Comment by ghost** [comment]
Picking this up now. 

List of providers we need to add support for: 
- [x] Huggingface 
- [x] Anthropic
- [x] Replicate
- [x] Cohere 
- [x] AI21 
- [x] TogetherAI 
- [x] Palm 
- [x] NLP Cloud
- [x] AlephAlpha
- [x] Petals
- [x] VertexAI 
- [x] Sagemaker
- [x] Bedrock

**Comment by ghost** [comment]
<img width="873" alt="Screenshot 2023-10-05 at 2 08 09 PM" src="https://github.com/BerriAI/litellm/assets/17561003/34cca6e3-dd5f-456a-b177-feb10598034c">

**Comment by ghost** [comment]
Got the integrations written. Now writing unit tests.

**Comment by ghost** [comment]
Pushed dd7e397650acbe18ec8e5610ab05fc584a3c73c9

Will update ticket once this is in prod

**Comment by ghost** [comment]
in prod.
