### ISSUE TITLE
[Bug]: Missing mode when adding a model via UI

### ISSUE THREAD

**Issue by stelterlab** [BerriAI/litellm#5270]
### What happened?

When adding a model via admin UI Models -> Add new model it is not possible to add a mode (model_info).

The UI reports success: _Model created successfully. Wait 60s and refresh on 'All Models' page_

When you run an health check afterwards, you will get an:

_"error": "Missing `mode`. Set the `mode` for the model - https://docs.litellm.ai/docs/proxy/health#embedding-models"_

### Relevant log output

```shell
{"message": "litellm.ahealth_check(): Exception occured - Connection error.", "level": "ERROR", "timestamp": "2024-08-19T07:56:32.784815"}
```

**Comment by mikes-bowden** [comment]
Same issue. It seems only to happen when adding OpenAI-Compatible Endpoints.

**Comment by ishaan-jaff** [comment]
Hi @stelterlab can we hop on a quick call to discuss what you need. Happy to get this implemented for you this week? 

Hoping to understand the following on call 
1. What e2e flow you want for adding a model via UI
2. Any other pending issues you have 

my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
my linkedin if you prefer DMs: https://www.linkedin.com/in/reffajnaahsi/
