### ISSUE TITLE
[Bug]: /v1/models returns hardcoded owned_by and created

### ISSUE THREAD

**Issue by AlexanderYastrebov** [BerriAI/litellm#5275]
### What happened?

Model list uses hardcoded `owned_by` and `created` fields:
https://github.com/BerriAI/litellm/blob/398295116f38346333d1dee2bd7cc09e6ec72e96/litellm/proxy/proxy_server.py#L2948-L2959

**Comment by ghost** [comment]
hi @AlexanderYastrebov the `/v1/models` endpoint is used for allowing the proxy to work with openai projects like aider.

To get *real* model info - would advise using `/v1/model/info`

**Comment by ghost** [comment]
How do you use this endpoint? Happy to work on a better solution here

**Comment by ghost** [comment]
bump on this? @AlexanderYastrebov

**Comment by AlexanderYastrebov** [comment]
@krrishdholakia
Hi, thank you for the prompt follow up.
I saw this while playing with the proxy and decided to report.
I am not sure how critical it is (or how useful `/v1/models` API is).

**Comment by ghost** [comment]
sounds good. Closing as not planned for now, since this can be resolved with `/v1/model/info`. 

I'll update the docstring to make this clear too.
