### ISSUE TITLE
[Bug]: Health check fails for new Azure Batch Models

### ISSUE THREAD

**Issue by taralika** [BerriAI/litellm#5279]
### What happened?

- add a new [batch deployment model](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/batch?tabs=standard-input&pivots=programming-language-python#global-batch-deployment) in Azure OpenAI
- Make a new entry in proxy-config.yaml of litellm proxy for the newly added batch model
- Run health checks

Health check fails with below error:
```
{
  "api_base": "https://xyz.openai.azure.com",
  "model": "azure/gpt-4o-2024-05-13-batch",
  "error": "Error code: 400 - {
  "error": {
    "code": "OperationNotSupported",
    "message": "The chatCompletion operation does not work with the specified model, gpt-4o. Please choose different model and try again. You can learn more about which models can be used with each operation here: https://go.microsoft.com/fwlink/?linkid=2197993."
  }
}
```

You probably need to add a new mode like "batch" (just like you have for [embedding etc. modes](https://docs.litellm.ai/docs/proxy/health#embedding-models)) so health check knows how it should perform some batching specific health checks instead of the real-time chat/completions health checks like it's trying to do now - which obviously fail since this is a batch only model and doesn't support the real-time apis.
cc: @msabramo

**Comment by Manouchehri** [comment]
I don't believe LiteLLM supports batching on Azure OpenAI yet? https://github.com/BerriAI/litellm/issues/5073

**Comment by superpoussin22** [comment]
batch mode not available using API only ai studio in preview mode 
https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/batch?tabs=standard-input&pivots=programming-language-ai-studio

**Comment by taralika** [comment]
> batch mode not available using API only ai studio in preview mode https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/batch?tabs=standard-input&pivots=programming-language-ai-studio

I don't think this is true, it's available as REST API as well as Python SDK: https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/batch?tabs=standard-input&pivots=rest-api#create-batch-job

**Comment by Manouchehri** [comment]
> batch mode not available using API only ai studio in preview mode

Not true, my team has been using it with the Python SDK and TypeScript SDK for awhile now.

**Comment by ghost** [comment]
Hey @taralika reading this further - why does the proxy needs to know about a batch deployment model ?

the model name looks like it's part of the jsonl file, not the request body. And i assume? the proxy isn't reading jsonl file

This is the client code i see on azure docs 

```python
import os
from openai import AzureOpenAI
    
client = AzureOpenAI(
    api_key=os.getenv("AZURE_OPENAI_API_KEY"),  
    api_version="2024-07-01-preview",
    azure_endpoint = os.getenv("AZURE_OPENAI_ENDPOINT")
    )

# Upload a file with a purpose of "batch"
file = client.files.create(
  file=open("test.jsonl", "rb"), 
  purpose="batch"
)

print(file.model_dump_json(indent=2))
file_id = file.id
```

So we'd probably just need to know the azure account credentials, and route it accordingly, right?

**Comment by ghost** [comment]
Or is the ask here to read the jsonl -> replace the model name with the azure deployment name -> send it along

**Comment by taralika** [comment]
I was thinking the proxy would do load balancing across multiple azure deployments of a batch model, but for now if proxy can only support one deployment, that might also be fine. In that case, I see that there would be no need to add a batch model to the proxy model_list. Just adding the files_settings for azure should be enough, but you'd still need to support the purpose=batch and /batches api for azure.

**Comment by ghost** [comment]
Oh - what would loadbalancing multiple batch models look like?

**Comment by taralika** [comment]
> Oh - what would loadbalancing multiple batch models look like?

gpt-4-turbo for example supports up to 300M tokens enqueued in batch mode, and a batch can take up to 24hrs to process. Let's say I have multiple azure subscriptions and/or resources in various regions, then I can add say 2 more gpt-4-turbo batch deployments and let my users, via proxy, enqueue jobs up to total of 3*300M tokens in total across all 3 deployments.

**Comment by ghost** [comment]
> Let's say I have multiple azure subscriptions and/or resources in various regions 

do files work across subscriptions/accounts?

**Comment by taralika** [comment]
> do files work across subscriptions/accounts?

I don't think so. You'd need to persist this info in proxy i.e., once a file has been sent to a specific deployment, the batch job must be created on that deployment/resource. So the load balancing (picking the deployment) would need to happen at time of file upload.

**Comment by ghost** [comment]
You can now set health checks for azure batch models - https://docs.litellm.ai/docs/proxy/health#batch-models-azure-only

```yaml
model_list:
  - model_name: "batch-gpt-4o-mini"
    litellm_params:
      model: "azure/batch-gpt-4o-mini"
      api_key: os.environ/AZURE_API_KEY
      api_base: os.environ/AZURE_API_BASE
    model_info:
      mode: batch
```

**Comment by taralika** [comment]
Thanks @krrishdholakia - so are you also supporting multiple batch deployments within a model group and load balancing? otherwise like you mentioned earlier, why does the proxy care about the model names for batch? as long as file upload to an azure resource works, and if you can have the batches api support azure, that should be enough

**Comment by ghost** [comment]
> why does the proxy care about the model names for batch

I assumed your developers would need to know the name of the azure deployments - you can expose this via `/v1/model/info`

**Comment by ghost** [comment]
>  if you can have the batches api support azure, that should be enough

This is live as well @taralika https://docs.litellm.ai/docs/batches#azure-batches-api

**Comment by Manouchehri** [comment]
What does the batch endpoint check to be considered "healthy"? 

Fundamentally, I'm not sure how well LiteLLM will be able to verify (quickly) that Azure's batch API is working. e.g. if 100% of batch requests to Azure end with a failure after an hour, the health endpoint check here wouldn't be able to spot that.

**Comment by ghost** [comment]
> What does the batch endpoint check to be considered "healthy"?

It runs a get batches call to verify if it's working correctly

**Comment by ghost** [comment]
> batch requests to Azure end with a failure after an hour

That's fair - is there anything you'd expect litellm to do here / to do better?

**Comment by Manouchehri** [comment]
Na, I think LiteLLM is doing fine. :)

**Comment by taralika** [comment]
@krrishdholakia creating a batch https://docs.litellm.ai/docs/batches#2-create-a-batch is not working for me on v1.44.4
```
curl --request POST \
  --url https://llmproxy.xyz.com/azure/v1/batches \
  --header 'Authorization: Bearer ${PROXY_KEY}' \
  --header 'Content-Type: application/json' \
  --data '{
    "input_file_id": "file-id123",
    "endpoint": "/chat/completions",
    "completion_window": "24h"
}'
```
response is `405 Method Not Allowed`
```
{
	"detail": "Method Not Allowed"
}
```

Is it possible you have not implemented POST method on path `/azure/v1/batches`? The same works on GET but I think this request should be a POST (also it's POST as per Azure docs at: https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/batch?tabs=standard-input&pivots=rest-api#create-batch-job )

**Comment by ghost** [comment]
Found the issue. pushing a fix now @taralika

**Comment by taralika** [comment]
> Found the issue. pushing a fix now @taralika

thanks @krrishdholakia I was able to validate the fix in 1.44.5

By the way, the way https://docs.litellm.ai/docs/batches#azure-batches-api is set up currently, it points to a single Azure endpoint/api-base for all batch models. What if I wanted to add another or even a few more Azure endpoints where I have different batch models. I can imagine in future Azure might release certain batch models in certain regions needing us to use more than 1 endpoints to get coverage. Is there a way you can support more than 1 Azure endpoints for batch api?

**Comment by ghost** [comment]
hey @taralika how would you want this to work?

**Comment by taralika** [comment]
`proxy-config.yaml` would have a section like this:
```
batch_model_list:
  - model_name: gpt-4-turbo-2024-04-09-batch
    litellm_params:
      model: azure/gpt-4-turbo-2024-04-09-batch
      api_base: os.environ/AOAI_BASE_US_E
      api_key: os.environ/AOAI_KEY_US_E
  - model_name: gpt-4-turbo-2024-04-09-batch
    litellm_params:
      model: azure/gpt-4-turbo-2024-04-09-batch
      api_base: os.environ/AOAI_BASE_US_W
      api_key: os.environ/AOAI_KEY_US_W
  - model_name: gpt-4o-batch
    litellm_params:
      model: azure/gpt-4o-batch
      api_base: os.environ/AOAI_BASE_US_W3
      api_key: os.environ/AOAI_KEY_US_W3
  - model_name: gpt-4o-batch
    litellm_params:
      model: azure/gpt-4o-batch
      api_base: os.environ/AOAI_BASE_CA_W
      api_key: os.environ/AOAI_KEY_CA_W
```
You should not need to specify the `files_settings` section in `proxy-config.yaml` for batch api feature.

When client makes the request to upload the batch job input file, they should also specify which model they intend to use so that proxy can figure out which Azure endpoint to use to upload this file:
```
curl http://localhost:4000/azure/v1/files \
    -H "Authorization: Bearer sk-1234" \
    -F purpose="batch" \
    -F file="@mydata.jsonl"
    -F model="gpt-4o-batch"
```
So in this example, proxy will pick/load-balance between the 2 possible Azure endpoints where `gpt-4o-batch` is available: either `AOAI_BASE_US_W3` or `AOAI_BASE_CA_W`. Proxy should persist the endpoint it picked for this file as a tuple in the database `(input_file_id, batch_id, azure_endpoint)`

Next, request to fetch status of the file upload will be:
```
curl https://localhost:4000/azure/v1/files/file-id123 \
  -H "Authorization: Bearer sk-1234"
```
proxy will use the `file-id123` passed on this request to lookup which `azure_endpoint` to use to pass along this request, and get the file upload status.

Next, request to create a batch:
```
curl http://localhost:4000/azure/v1/batches \
  -H "Authorization: Bearer sk-1234" \
  -H "Content-Type: application/json" \
  -d '{
    "input_file_id": "file-id123",
    "endpoint": "/chat/completions",
    "completion_window": "24h"
  }'
```
Augment the entry in the database with the `batch_id` returned in the response to the above "create batch" request, so that subsequent calls to retrieve batch job status and batch job output that pass the `batch_id` on the request can be used by proxy to look up appropriate `azure_endpoint` to pass the request to.

It'd be fine to clean up the entry in database after a week or so of the batch request, whatever's reasonable.

**Comment by ghost** [comment]
hey @taralika 
> curl http://localhost:4000/azure/v1/files \
    -H "Authorization: Bearer sk-1234" \
    -F purpose="batch" \
    -F file="@mydata.jsonl"
    -F model="gpt-4o-batch"

We'd need to modify the .jsonl to point to the correct deployment. Is that something you'd be okay with?

**Comment by taralika** [comment]
The expectation would be that the client/caller should make sure to use the correct deployment in the `.jsonl` (same as what they pass in the `model="gpt-4o-batch"` param on the file upload request  - I don't think proxy needs to do anything there.

**Comment by ghost** [comment]
got it - so the responsibility is on admin, to have the azure deployment name across regions, match the model name

**Comment by taralika** [comment]
correct, for example, for `batch_model_list` I pasted above, the admin would ensure an azure deployment of the name `gpt-4o-batch` which is a global batch deployment model is available in both azure resources with endpoints `AOAI_BASE_US_W3` and `AOAI_BASE_CA_W` and so on

and the caller/user of the batch api in proxy will need to ensure they use the same model name (in this example `gpt-4o-batch`) when uploading the file and also inside the `.jsonl` file

**Comment by ghost** [comment]
hmm - this feels like it puts a lot of responsibility on the admin to get things right 

Can we begin by reading from .jsonl? This would remove the need for an additional param client-side (complicating any openai/azure client code) and reduce work for admin

**Comment by taralika** [comment]
> hmm - this feels like it puts a lot of responsibility on the admin to get things right

not sure how this is any more work for admin than what they are already doing to set up all the models listed under `model_list` in the `proxy-config.yaml`

> Can we begin by reading from .jsonl? This would remove the need for an additional param client-side (complicating any openai/azure client code) and reduce work for admin

Yes, doing this should should reduce work for the client of proxy, not the admin. You can read the `.jsonl` to pull out the `"model"` field from the first line of the input `.jsonl` file then client doesn't need to pass the model as a param like this `-F model="gpt-4o-batch"`
This assumes that all lines in the input `.jsonl` use the same `model` which may or may not be true but as long as models listed in the `.jsonl` are available at the same azure endpoint, it should be fine.

This'd still give me a lot of what we need.

**Comment by taralika** [comment]
@krrishdholakia checking if you'll be deploying the changes we discussed above anytime soon? If you can provide an ETA that'll help us decide if we should wait or roll out azure batch support to our users in its current form

**Comment by ghost** [comment]
Hey @taralika - i can do it this week. can you create a new issue with the ask described above?

**Comment by taralika** [comment]
> Hey @taralika - i can do it this week. can you create a new issue with the ask described above?

Done @krrishdholakia, in #5396
