### ISSUE TITLE
[Feature]: unify prompt caching information across anthropic + deepseek

### ISSUE THREAD

**Issue by paul-gauthier** [BerriAI/litellm#5285]
### The Feature

It would be nice for litellm to unify the different `completion.usage` data formats, compute the cost and provide `.usage` for `stream=True` completions.

### Motivation, pitch

Deepseek returns these values:

```
Usage(completion_tokens=9, prompt_tokens=21530, total_tokens=21539, prompt_cache_hit_tokens=320, prompt_cache_miss_tokens=21210)

# prompt_cache_hit_tokens + prompt_cache_miss_tokens == prompt_tokens == total tokens that were sent
```

Anthropic returns these values:

```
Usage(completion_tokens=7, prompt_tokens=194, total_tokens=201, cache_creation_input_tokens=9474, cache_read_input_tokens=0)

# cache_creation_input_tokens + cache_read_input_tokens + prompt_tokens == total tokens that were sent
```

Notice that for Anthropic the `prompt_tokens` value is *not* the total number of sent tokens as it is for Deepseek. This makes it quite difficult to compute the number of sent tokens without hardcoding cases for each provider.

It would be nice for litellm to unify all this.

Even better, it would be nice for litellm to accurately compute the cost of a completion.usage result. Including the various caching cost adjustments. Perhaps returning it in the .usage structure? Right now the json model database doesn't have enough per-model data to do this, but that seems easy to update.

Finally, it would be great if this level of token and cost data was available when `stream=True`. Right now, I don't think we can get any `.usage` info back from the completion? Let alone cost data.

**Comment by ghost** [comment]
that's funny - i was thinking of something similar 

cc: @ishaan-jaff 


@paul-gauthier which format do you prefer?

**Comment by paul-gauthier** [comment]
I don't think I have a preference. Any sane unification would be a big win.

**Comment by ghost** [comment]
> Even better, it would be nice for litellm to accurately compute the cost of a completion.usage result. Including the various caching cost adjustments. Perhaps returning it in the .usage structure? Right now the json model database doesn't have enough per-model data to do this, but that seems easy to update.



this is an important callout. our cost calc should be accurate, so this important to do

**Comment by ghost** [comment]
how're you using the prompt caching usage information? @paul-gauthier

**Comment by paul-gauthier** [comment]
Users really appreciate that aider gives them visibility into their token usage and costs. So aider prints a short summary of per-message and per-session data after each chat interaction.

```
Aider v0.50.2-dev
Model: anthropic/claude-3-haiku-20240307 with whole edit format, prompt cache, infinite output
Git repo: .git with 308 files
Repo-map: disabled
Use /help <question> for help, run "aider --help" to see cmd line args
───────────────────────────────────────────
README.md> what is this app? one sentence.

Aider is an AI pair programming assistant that allows you to edit code in your local git
repository by interacting with large language models like GPT-4o and Claude 3.5 Sonnet.

Tokens: 2,937 sent, 2,728 cache hit, 45 received. Cost: $0.00018 message, $0.00018 session.
───────────────────────────────────────────
README.md>
```

**Comment by ghost** [comment]
We've begun the work on this - for prompt caching information

we now have 2 private variables 

```
class Usage(CompletionUsage):
    _cache_creation_input_tokens: int = PrivateAttr(
        0
    )  # hidden param for prompt caching. Might change, once openai introduces their equivalent.
    _cache_read_input_tokens: int = PrivateAttr(
        0
    )  # hidden param for prompt caching. Might change, once openai introduces their equivalent.
```

Anthropic calls are already mapped to this, will also now add deepseek support @paul-gauthier

**Comment by ghost** [comment]
Deepseek prompt caching output 

```
ModelResponse(id='1d9cb691-edda-4082-a3de-aa6cbf567b11', choices=[Choices(finish_reason='stop', index=0, message=Message(content='Answer: The Shang Dynasty fell around 1046 BC with the rise of the Zhou Dynasty.', role='assistant', tool_calls=None, function_call=None))], created=1725412014, model='deepseek/deepseek-chat', object='chat.completion', system_fingerprint='fp_7e0991cad4', usage=Usage(completion_tokens=21, prompt_tokens=112, total_tokens=133, prompt_cache_hit_tokens=64, prompt_cache_miss_tokens=48), service_tier=None)
```

Anthropic prompt caching output:

```
response= ModelResponse(id='chatcmpl-ab5a8bfc-bf17-45eb-af6a-e0803267476f', choices=[Choices(finish_reason='length', index=0, message=Message(content='I apologize, but I made a mistake in', role='assistant', tool_calls=None, function_call=None))], created=1725412067, model='claude-3-5-sonnet-20240620', object='chat.completion', system_fingerprint=None, usage=Usage(completion_tokens=10, prompt_tokens=4, total_tokens=14, cache_creation_input_tokens=0, cache_read_input_tokens=4854))
```

**Comment by ghost** [comment]
Note: 

value of `prompt_tokens` for anthropic is all input tokens - cache_read_input_tokens

value of `prompt_tokens` for deepseek is all input tokens

**Comment by ghost** [comment]
to map this correctly to the anthropic format, 

we would do `prompt_tokens` = `prompt_cache_miss_tokens` 

this would make sense, and also allow for more accurate cost tracking (we can assume value of prompt tokens is the value to multiply the normal price by)

**Comment by ghost** [comment]
This behaviour should be publicly documented. Will also add a doc on this here - https://docs.litellm.ai/docs/completion

**Comment by ghost** [comment]
Now that openai's prompt caching is live - i believe we might need to make some updates https://platform.openai.com/docs/guides/prompt-caching

It looks like the `prompt_tokens` field is the total prompt tokens (including cached tokens)  

and the `cached_tokens` field is the cached tokens
