### ISSUE TITLE
[Feature]: When an exception is raised tell user they can debug via 'litellm.set_verbose=True'

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#529]
### The Feature

When an exception is raised tell user they can debug via 'litellm.set_verbose=True'

### Motivation, pitch

make it easy for people to figure out how to debug an error.

**Comment by vedant-z** [comment]
@krrishdholakia I would like to work on this. Are the changes required to be made in doc?

**Comment by ghost** [comment]
Might be worth adding the print statement here - https://github.com/BerriAI/litellm/blob/69a0a775f85319da0016b345718e4b36cdc03d44/litellm/utils.py#L2206

**Comment by vedant-z** [comment]
What exact message would be relevant? 

Something like: Remember you can always debug via 'litellm.set_verbose=True'

Sorry if this is not required solution or if I am misunderstanding the issue. Please let me know if I am wrong I will try to solve this issue.

If it's alright then please allow me to make a PR. 

Thanks

**Comment by ghost** [comment]
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

**Comment by vedant-z** [comment]
Should I make a PR?

**Comment by yogesh93522** [comment]
![image](https://github.com/BerriAI/litellm/assets/148770923/98bad533-b063-44fd-a294-0f4e0b79d768)
can you please check the screenshot , I am getting this error when I am using OPEN-interpreter

**Comment by ghost** [comment]
@yogesh93522 can you help me understand the issue?
