### ISSUE TITLE
[Bug]: Incorrect Password is disclosed when login to UI

### ISSUE THREAD

**Issue by superpoussin22** [BerriAI/litellm#5290]
### What happened?

if you made a mistake on credentials : values are displayed .
think the output should be less verbose 

### Relevant log output

```shell
{"error":{"message":"Invalid credentials used to access UI. Passed in username: test_user, passed in password: 2JMDBDXgtGds44NFBdskkRncA.\nCheck 'UI_USERNAME', 'UI_PASSWORD' in .env file","type":"auth_error","param":"invalid_credentials","code":"401"}}
```

**Comment by ghost** [comment]
Based on the message, it looks like that is the password which is passed in by the user but is incorrect - `passed in password: 2JMDBDXgtGds44NFBdskkRncA`

What should be getting showed here instead? @superpoussin22

**Comment by ghost** [comment]
Removed the passed in username, pwd from the error message @superpoussin22
