### ISSUE TITLE
[Bug]: asyncio.exceptions.CancelledError with langsmith callback

### ISSUE THREAD

**Issue by MarkRx** [BerriAI/litellm#5293]
### What happened?

Using LangSmith with LiteLLM always fails with asyncio.exceptions.CancelledError.

Works in 1.41.23
Broke in [1.41.24](https://github.com/BerriAI/litellm/releases/tag/v1.41.24)

Python 3.11.9
Windows 10

Code to reproduce (example uses Azure OpenAI):
```
import asyncio
import os

import litellm
from litellm import acompletion

os.environ["LANGSMITH_API_KEY"]='<langsmith key>'

litellm.azure_key='<key>'
litellm.api_version='2023-07-01-preview'
litellm.api_base='<url>'
litellm.success_callback=['langsmith']

async def run() -> bool:
    response = await acompletion(
        model='azure/gpt-3.5-turbo-16k',
        deployment_id='gpt-4o',
        messages=[{"role": "user", "content": "Hi 👋 - i'm openai"}]
    )
    print(response)

    return True

if __name__ == '__main__':
    asyncio.run(run())
```

> pip list
> Package                       Version
> ----------------------------- -----------
> aiohappyeyeballs              2.3.5
> aiohttp                       3.9.4
> aiosignal                     1.3.1
> annotated-types               0.7.0
> anthropic                     0.21.3
> anyio                         4.4.0
> atlassian-python-api          3.41.4
> attrs                         24.2.0
> azure-core                    1.30.2
> azure-devops                  7.1.0b3
> azure-identity                1.15.0
> boto3                         1.33.6
> botocore                      1.33.13
> cachetools                    5.4.0
> certifi                       2024.7.4
> cffi                          1.17.0
> charset-normalizer            3.3.2
> click                         8.1.7
> colorama                      0.4.6
> coverage                      7.6.1
> cryptography                  43.0.0
> decorator                     5.1.1
> Deprecated                    1.2.14
> distro                        1.9.0
> dnspython                     2.6.1
> dynaconf                      3.2.4
> email_validator               2.2.0
> fastapi                       0.111.0
> fastapi-cli                   0.0.5
> filelock                      3.15.4
> frozenlist                    1.4.1
> fsspec                        2024.6.1
> gitdb                         4.0.11
> GitPython                     3.1.41
> google-api-core               2.19.1
> google-auth                   2.33.0
> google-cloud-aiplatform       1.38.0
> google-cloud-bigquery         3.25.0
> google-cloud-core             2.4.1
> google-cloud-resource-manager 1.12.5
> google-cloud-storage          2.10.0
> google-crc32c                 1.5.0
> google-resumable-media        2.7.2
> googleapis-common-protos      1.63.2
> grpc-google-iam-v1            0.13.1
> grpcio                        1.65.4
> grpcio-status                 1.62.3
> gunicorn                      22.0.0
> h11                           0.14.0
> httpcore                      1.0.5
> httptools                     0.6.1
> httpx                         0.27.0
> huggingface-hub               0.24.5
> idna                          3.7
> ijson                         3.3.0
> importlib_metadata            8.2.0
> iniconfig                     2.0.0
> isodate                       0.6.1
> Jinja2                        3.1.2
> jiter                         0.5.0
> jmespath                      1.0.1
> jsonschema                    4.23.0
> jsonschema-specifications     2023.12.1
> langsmith                     0.1.99
> litellm                       1.41.24
> loguru                        0.7.2
> markdown-it-py                3.0.0
> MarkupSafe                    2.1.5
> mdurl                         0.1.2
> msal                          1.30.0
> msal-extensions               1.2.0
> msrest                        0.7.1
> multidict                     6.0.5
> numpy                         2.0.1
> oauthlib                      3.2.2
> openai                        1.40.6
> orjson                        3.10.7
> packaging                     24.1
> pip                           24.2
> pluggy                        1.5.0
> portalocker                   2.10.1
> proto-plus                    1.24.0
> protobuf                      4.25.4
> py                            1.11.0
> pyasn1                        0.6.0
> pyasn1_modules                0.4.0
> pycparser                     2.22
> pydantic                      2.8.2
> pydantic_core                 2.20.1
> PyGithub                      1.59.1
> Pygments                      2.18.0
> PyJWT                         2.9.0
> PyNaCl                        1.5.0
> pytest                        7.4.0
> pytest-cov                    5.0.0
> python-dateutil               2.9.0.post0
> python-dotenv                 1.0.1
> python-gitlab                 3.15.0
> python-multipart              0.0.9
> pywin32                       306
> PyYAML                        6.0.1
> referencing                   0.35.1
> regex                         2024.7.24
> requests                      2.32.3
> requests-oauthlib             2.0.0
> requests-toolbelt             1.0.0
> retry                         0.9.2
> rich                          13.7.1
> rpds-py                       0.20.0
> rsa                           4.9
> s3transfer                    0.8.2
> setuptools                    68.2.0
> shapely                       2.0.5
> shellingham                   1.5.4
> six                           1.16.0
> smmap                         5.0.1
> sniffio                       1.3.1
> starlette                     0.37.2
> starlette-context             0.3.6
> tenacity                      8.2.3
> tiktoken                      0.7.0
> tokenizers                    0.20.0
> tqdm                          4.66.5
> typer                         0.12.3
> typing_extensions             4.12.2
> ujson                         5.8.0
> urllib3                       2.0.7
> uvicorn                       0.22.0
> watchfiles                    0.23.0
> websockets                    12.0
> wheel                         0.41.2
> win32-setctime                1.1.0
> wrapt                         1.16.0
> yarl                          1.9.4
> zipp                          3.20.0
> 

### Relevant log output

```shell
←[92mRequest to litellm:←[0m
←[92mlitellm.acompletion(model='<model>', deployment_id='gpt-4o', messages=[{'role': 'user', 'content': "Hi � - i'm openai"}])←[0m


←[92m11:54:57 - LiteLLM:WARNING←[0m: utils.py:357 - `litellm.set_verbose` is deprecated. Please set `os.environ['LITELLM_LOG'] = 'DEBUG'` for debug logs.
ASYNC kwargs[caching]: False; litellm.cache: None; kwargs.get('cache'): None
Final returned optional params: {'extra_body': {}}
←[92m

POST Request Sent from LiteLLM:
curl -X POST \
<url> \
-H 'Authorization: *****' \
-d '{'model': 'gpt-4o', 'messages': [{'role': 'user', 'content': "Hi � - i'm openai"}], 'extra_body': {}}'
←[0m

RAW RESPONSE:
{"id": "chatcmpl-9yLUAG4x8dRZqqZhR6aTPsSgYpdAZ", "choices": [{"finish_reason": "stop", "index": 0, "logprobs": null, "message": {"content": "Hello! It looks like there might be a mix-up\u2014I'm actually OpenAI's language model. How can I assist you today?", "refusal": null, "role": "assistant", "function_call": null, "tool_calls": null}, "content_filter_results": {"hate": {"filtered": false, "severity": "safe"}, "self_harm": {"filtered": false, "severity": "safe"}, "sexual": {"filtered": false, "severity": "safe"}, "violence": {"filtered": false, "severity": "safe"}}}], "created": 1724169298, "model": "gpt-4o-2024-05-13", "object": "chat.completion", "service_tier": null, "system_fingerprint": "fp_abc28019ad", "usage": {"completion_tokens": 27, "prompt_tokens": 14, "total_tokens": 41}, "prompt_filter_results": [{"prompt_index": 0, "content_filter_results": {"hate": {"filtered": false, "severity": "safe"}, "jailbreak": {"filtered": false, "detected": false}, "self_harm": {"filtered": false, "severity": "safe"}, "sexual": {"filtered": false, "severity": "safe"}, "violence": {"filtered": false, "severity": "safe"}}}]}


Looking up model=azure/gpt-4o in model_cost_map
Success: model=azure/gpt-4o in model_cost_map
prompt_tokens=14; completion_tokens=27
Returned custom cost for model=azure/gpt-4o - prompt_tokens_cost_usd_dollar: 7.000000000000001e-05, completion_tokens_cost_usd_dollar: 0.00040500000000000003
Async Wrapper: Completed Call, calling async_success_handler: <bound method Logging.async_success_handler of <litellm.litellm_core_utils.litellm_logging.Logging object at 0x00000282ACE57A10>>
Looking up model=azure/gpt-4o in model_cost_map
ModelResponse(id='chatcmpl-9yLUAG4x8dRZqqZhR6aTPsSgYpdAZ', choices=[Choices(finish_reason='stop', index=0, message=Message(content="Hello! It looks like there might be a mix-up—I'm actually OpenAI's language model. How can I assist you today?", role='assistant', tool_calls=None, function_call=None))], created=1724169298, model='gpt-4o-2024-05-13', object='chat.completion', system_fingerprint='fp_abc28019ad', usage=Usage(completion_tokens=27, prompt_tokens=14, total_tokens=41), service_tier=None, prompt_filter_results=[{'prompt_index': 0, 'content_filter_results': {'hate': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'filtered': False, 'detected': False}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}}}])
Success: model=azure/gpt-4o in model_cost_map
Logging Details LiteLLM-Async Success Call, cache_hit=None
prompt_tokens=14; completion_tokens=27
Looking up model=azure/gpt-4o in model_cost_map
Returned custom cost for model=azure/gpt-4o - prompt_tokens_cost_usd_dollar: 7.000000000000001e-05, completion_tokens_cost_usd_dollar: 0.00040500000000000003
Success: model=azure/gpt-4o in model_cost_map
prompt_tokens=14; completion_tokens=27
Returned custom cost for model=azure/gpt-4o - prompt_tokens_cost_usd_dollar: 7.000000000000001e-05, completion_tokens_cost_usd_dollar: 0.00040500000000000003
[92m09:52:31 - LiteLLM:ERROR[0m: langsmith.py:162 - Langsmith Layer Error - Traceback (most recent call last):
  File "C:\workspace\venv\Lib\site-packages\litellm\integrations\langsmith.py", line 146, in async_log_success_event
    response = await self.async_httpx_client.post(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\workspace\venv\Lib\site-packages\litellm\llms\custom_httpx\http_handler.py", line 89, in post
    response = await self.client.send(req, stream=stream)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\workspace\venv\Lib\site-packages\httpx\_client.py", line 1661, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\workspace\venv\Lib\site-packages\httpx\_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\workspace\venv\Lib\site-packages\httpx\_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\workspace\venv\Lib\site-packages\httpx\_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\workspace\venv\Lib\site-packages\httpx\_transports\default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\workspace\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "C:\workspace\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\workspace\venv\Lib\site-packages\httpcore\_async\connection.py", line 99, in handle_async_request
    raise exc
  File "C:\workspace\venv\Lib\site-packages\httpcore\_async\connection.py", line 74, in handle_async_request
    async with self._request_lock:
  File "C:\workspace\venv\Lib\site-packages\httpcore\_synchronization.py", line 76, in __aenter__
    await self._anyio_lock.acquire()
  File "C:\workspace\venv\Lib\site-packages\anyio\_core\_synchronization.py", line 179, in acquire
    await cancel_shielded_checkpoint()
  File "C:\workspace\venv\Lib\site-packages\anyio\lowlevel.py", line 55, in cancel_shielded_checkpoint
    await get_async_backend().cancel_shielded_checkpoint()
  File "C:\workspace\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 2074, in cancel_shielded_checkpoint
    await sleep(0)
  File "C:\Python\Python311\Lib\asyncio\tasks.py", line 630, in sleep
    await __sleep0()
  File "C:\Python\Python311\Lib\asyncio\tasks.py", line 624, in __sleep0
    yield
asyncio.exceptions.CancelledError
```

**Comment by ghost** [comment]
@MarkRx this is working in v`1.43.18`. 
<img width="1614" alt="Screenshot 2024-08-20 at 9 19 30 AM" src="https://github.com/user-attachments/assets/5c924dd1-ac36-4045-ad7c-796cac23b37c">

**Comment by MarkRx** [comment]
It fails for me in `1.43.18` with the same error.

If I call
```
client = httpx.AsyncClient()
    await client.post('<url>', data={}, json={})
```

in `async_log_success_event` it fails with the CancelledError.

If I disable the langsmith callback and call the above code in my `run()` method it does not error. It thus seams something is in an unhealthy state when the `async_log_success_event` `httpx` client is called.

This code reproduces the issue. It's independent of LangSmith:

```
class MyLogger(CustomLogger):
    async def async_log_success_event(self, kwargs, response_obj, start_time, end_time):
        try:
            print(f"On Async Success!")
            client = httpx.AsyncClient()
            await client.post("https://google.com", data={})
        except:
            print(f"Failed!")
            print(traceback.format_exc())

custom_handler=MyLogger()
litellm.callbacks=[custom_handler]

async def run() -> bool:
    response = await acompletion(
        model='azure/gpt-3.5-turbo-16k',
        deployment_id='gpt-4o',
        messages=[{"role": "user", "content": "Hi 👋 - i'm openai"}]
    )
    print(response)

    return True

if __name__ == '__main__':
    asyncio.run(run())
```

**Comment by MarkRx** [comment]
Not sure if https://github.com/python/cpython/issues/102780 relates to this at all

**Comment by ghost** [comment]
i believe this might be related to your environment @MarkRx 

If your seeing an async task being cancelled, it might be getting closed by your ide earlier than expected

**Comment by MarkRx** [comment]
I tracked it down. The [wrapper_async](https://github.com/BerriAI/litellm/blob/main/litellm/utils.py#L1081) function [adds tasks](https://github.com/BerriAI/litellm/blob/main/litellm/utils.py#L1486) to the end of the event queue without awaiting them. They thus may not run if simply waiting for the original LLM task to complete.

In long running server situations this is not a problem as they will eventually run. It may be a problem in short lived invocations such as through the CLI or through some FaaS system.

Workaround is to ensure the entire event queue is empty before completing:
```
    async def inner():
        asyncio.create_task(run())
        while len(asyncio.all_tasks()) > 1:
            await asyncio.sleep(0.1)

    loop = asyncio.get_event_loop()
    loop.run_until_complete(inner())
    loop.close()
```
