### ISSUE TITLE
[Bug]: structured output not working with gpt-4o-mini

### ISSUE THREAD

**Issue by almajo** [BerriAI/litellm#5295]
### What happened?

I wanted to replicate the example from https://docs.litellm.ai/docs/completion/json_mode with pydantic using my Azure OpenAI gpt-4o-mini with version 2024-07-18 but all I got is an error.

Also the documentation is a little confusing as it states 

```
To use Structured Outputs, simply specify

response_format: { "type": "json_schema", "json_schema": … , "strict": true 
}
```

However, in the example below we are using the pydantic model directly. Also , the 'json_schema:...' confused me as there is no information about the type of the schema (str or dict?). 

Here I recommend adding the 2 possibilities clearly: 1.) the dict approach with clear data types and 2.) pydantic model

### Relevant log output

```shell
BadRequestError: litellm.BadRequestError: AzureException BadRequestError - Error code: 400 - {'error': {'message': "Invalid parameter: 'response_format' must be one of 'json_object', 'text'.", 'type': 'invalid_request_error', 'param': 'response_format', 'code': None}}

$ pip freeze | grep litellm
litellm==1.43.18
```

**Comment by ghost** [comment]
The error seems to come from the Azure API. I don't believe azure has support for json schema yet - https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#chat-completions

Do you see this working for you locally? 

Have a PR to add support on older models - https://github.com/BerriAI/litellm/pull/5296
