### ISSUE TITLE
[Feature]: Permissions for a team admin

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#5300]
### The Feature

Allow team admins to: 
    - Add and remove team members 
    - Create, re-generate keys for the users

### Motivation, pitch

User request 

### Twitter / LinkedIn details

https://www.linkedin.com/in/bopowers9/

**Comment by ghost** [comment]
I would assume the user must already exist in db as an 'internal_user' before the team admin can add them to a team

**Comment by ghost** [comment]
To complete this issue for the user, we'd probably need to: 

- [ ] allow assigning team admin on ui 
- [ ] allow team admin to add member to team on ui
