### ISSUE TITLE
[Bug]: Cloud Run Button Fails

### ISSUE THREAD

**Issue by sysgenerated** [BerriAI/litellm#5311]
### What happened?

Attempting to deploy to Cloud Run using the deploy button from the [documentation](https://docs.litellm.ai/docs/proxy/deploy) link fails at the final step in GCP with this message:
`denied: Unauthenticated request. Unauthenticated requests do not have permission "artifactregistry.repositories.uploadArtifacts" on resource "projects/<project-id>/locations/us/repositories/gcr.io" (or it may not exist)`

It is a known [issue](https://github.com/GoogleCloudPlatform/cloud-run-button/issues/247) in the cloud-run-button repo. A proposed fix is to include an app.json file in the project root containing the following:
```
{
    "name": "app",
    "hooks": {
        "prebuild": {
            "commands": [
                "gcloud auth configure-docker"
            ]
        }
    }
}
```

**Comment by ishaan-jaff** [comment]
working on this

**Comment by ishaan-jaff** [comment]
fixed here: https://github.com/BerriAI/litellm/pull/5317

**Comment by ishaan-jaff** [comment]
We're moving away from the button - since a lot of our users want to add their own litellm config.yaml

**Comment by ishaan-jaff** [comment]
@sysgenerated any chance we could hop on a call sometime this week ? Would love to learn how we can improve litellm for you 

Here is a link to my cal for your convenience
https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by ishaan-jaff** [comment]
Hi @sysgenerated, curious do you use LiteLLM Proxy in production today If so, I'd love to hop on a call and learn how we can improve LiteLLM for you

- my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
- my linkedin if you prefer DMs: https://www.linkedin.com/in/reffajnaahsi/
