### ISSUE TITLE
Fix "groq/llama-3.1-405b-reasoning" entry in "model_prices_and_context_window.json"

### ISSUE THREAD

**Issue by djh00t** [BerriAI/litellm#5312]
https://github.com/BerriAI/litellm/blob/91aac0533b6c67972ea224eccb2464175cfb69db/model_prices_and_context_window.json#L1214-L1223

We also need to update [model_prices_and_context_window_backup.json](https://github.com/BerriAI/litellm/blob/91aac0533b6c67972ea224eccb2464175cfb69db/litellm/model_prices_and_context_window_backup.json).

Model 404's
```
Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.


Provider List: https://docs.litellm.ai/docs/providers

Failed to generate commit message with model groq/llama-3.1-405b-reasoning: litellm.NotFoundError: GroqException - Error code: 404 - {'error': {'message': 'The model `llama-3.1-405b-reasoning` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'code': 'model_not_found'}}
Model: groq/llama-3.1-405b-reasoning
```

**Comment by ishaan-jaff** [comment]
oh it looks like groq just removed this model https://console.groq.com/docs/models

**Comment by ishaan-jaff** [comment]
fixed here: https://github.com/BerriAI/litellm/commit/42df6b42c9f878fa0f8f1a1d40ba9bdf2cea55b5 

it looks like groq deprecated support for this

**Comment by ishaan-jaff** [comment]
@djh00t curious do you use LiteLLM Proxy server today ?
