### ISSUE TITLE
[Feature]: Support LangSmith ID fields

### ISSUE THREAD

**Issue by MarkRx** [BerriAI/litellm#5320]
### The Feature

There are a few more fields that should get added to the LiteLLM LangSmith implementation:
* parent_run_id
* trace_id
* session_id

These will allow the records to properly be associated to other LangSmith records.

See
[REST API](https://api.smith.langchain.com/redoc#tag/run/operation/create_run_api_v1_runs_post)
[Documentation](https://docs.smith.langchain.com/old/tracing/faq/customizing_trace_attributes)

### Motivation, pitch

The ability to pass IDs through LiteLLM to LangSmith allows for better integration with LangChain and LangSmith libraries.

**Comment by ghost** [comment]
Closing as #5323  is now merged

**Comment by ghost** [comment]
Great work @MarkRx
