### ISSUE TITLE
[Feature]: Add enable and disable features for the model and Virtual Keys

### ISSUE THREAD

**Issue by guleng** [BerriAI/litellm#5328]
### The Feature
How about adding enable and disable features for the model and virtual key?

Because managing many Virtual Keys and models requires enabling and disabling these two functions, sometimes when customers do not want to use a certain model or Virtual Keys, they can disable them. This way, they can continue to use them the next time they want to, without repeatedly deleting and rebuilding them

### Motivation, pitch

<img width="1150" alt="image" src="https://github.com/user-attachments/assets/3d44877f-4a6f-4166-b8a7-122160623dd4">

**Comment by ghost** [comment]
Hi @guleng 

> Because managing many Virtual Keys and models requires enabling and disabling these two functions

are you asking to enable/disable virtual keys?

**Comment by guleng** [comment]
@krrishdholakia Yes, we need to enable and disable the key and model functions
