### ISSUE TITLE
[Feature]: Docs - for litellm version upgrades, add tags in docs

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#533]
### The Feature

<img width="276" alt="Screenshot 2023-10-04 at 7 52 29 PM" src="https://github.com/BerriAI/litellm/assets/29436595/beaa2deb-6881-42d6-95fa-34a5b3a1d5b8">

cc @yujonglee thanks for the suggestion 

### Motivation, pitch

-

**Comment by ghost** [comment]
I've added migration docs - https://docs.litellm.ai/docs/migration. 

Nothing on it for now, but i assume we'll probably have to publish our move to raising exceptions for unmapped params, here. 

cc: @yujonglee

**Comment by ghost** [comment]
is there a good way to do this release / documentation mapping with docusaurus?

**Comment by ghost** [comment]
<img width="1069" alt="Screenshot 2023-10-05 at 11 48 40 AM" src="https://github.com/BerriAI/litellm/assets/17561003/810bb5ce-e587-4c33-ab7f-7999cbdb1a3e">

**Comment by ishaan-jaff** [comment]
we addressed this issue with our migration guides on docs
