### ISSUE TITLE
[Feature]: Support Jamba 1.5

### ISSUE THREAD

**Issue by themrzmaster** [BerriAI/litellm#5333]
### The Feature

https://techcommunity.microsoft.com/t5/ai-ai-platform-blog/introducing-ai21-labs-jamba-1-5-large-and-jamba-1-5-mini-on/ba-p/4220040

### Motivation, pitch

nice models, supports function calling.

**Comment by ishaan-jaff** [comment]
we already do @themrzmaster https://github.com/Azure/azureml-examples/blob/main/sdk/python/foundation-models/ai21-labs/jamba-instruct/litellm.ipynb

**Comment by themrzmaster** [comment]
nice! is the pricing correct?

**Comment by ghost** [comment]
@themrzmaster do you see different pricing?

**Comment by themrzmaster** [comment]
any version of jamba should be referenced as azure_ai/ai21-jamba-instruct ?

**Comment by ghost** [comment]
the model name doesn't matter for azure ai - it's the api base + api key

@themrzmaster
