### ISSUE TITLE
[Bug]: AttributeError: 'PrometheusLogger' object has no attribute 'litellm_remaining_api_key_requests_for_model'

### ISSUE THREAD

**Issue by themrzmaster** [BerriAI/litellm#5334]
### What happened?

19:25:30 - LiteLLM:ERROR: litellm_logging.py:1517 - LiteLLM.LoggingError: [Non-Blocking] Exception occurred while success logging Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/litellm_core_utils/litellm_logging.py", line 1449, in async_success_handler
    await callback.async_log_success_event(
  File "/usr/local/lib/python3.11/site-packages/litellm/integrations/prometheus.py", line 323, in async_log_success_event
    self.litellm_remaining_api_key_requests_for_model.labels(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PrometheusLogger' object has no attribute 'litellm_remaining_api_key_requests_for_model'

on proxy image: ghcr.io/berriai/litellm:main-v1.43.19-stable

**Comment by ishaan-jaff** [comment]
@themrzmaster do you have prometheus logging on ?

**Comment by ishaan-jaff** [comment]
fixed here: https://github.com/BerriAI/litellm/commit/65c0626aa4c01f387b02cf0238880dfa5bd21593
