### ISSUE TITLE
[Bug]: OpenAI  reject api request in some regions.

### ISSUE THREAD

**Issue by liudhzhyym** [BerriAI/litellm#5340]
### What happened?

In some regions, accessing the API of OpenAI may reject api request that it cannot be accessed in that region . It needs to be accessed through HTTP proxy or Socks proxy. How to configure HTTP proxy or Socks proxy in Litellm.

```
curl https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer sk-xxx" \
  -d '{
     "model": "gpt-3.5-turbo",
     "messages": [{"role": "user", "content": "Say this is a test!"}],
     "temperature": 0.7,
     "stream":true
   }' -x 'http://127.0.0.1:8091'
```

**Comment by krrishdholakia** [comment]
@liudhzhyym we use the openai sdk to make the call which uses httpx. 

Here's how to set httpx proxies - https://www.python-httpx.org/advanced/proxies/
