### ISSUE TITLE
[bug] sagemaker messages api streaming - unexpected end of data 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#5372]
Hi @krrishdholakia, thank you for your contribution and for fixing the previous bug. Your efforts are greatly appreciated. However, I've encountered another issue with the latest version. When [describe the steps to reproduce the bug], [explain the observed behavior]. I've attached a screenshot for reference.
![image](https://github.com/user-attachments/assets/064b9218-dd9a-4e26-985f-343066c69b10)

If possible, could you please look into this new bug? I think it's might be caused by the iter_bytes func, I think it might be caused by the iter_bytes func. You could reference the following code to solve it:
```
import io
import json

class TokenIterator:
    def __init__(self, stream):
        self.byte_iterator = iter(stream)
        self.buffer = io.BytesIO()
        self.read_pos = 0

    def __iter__(self):
        return self

    def __next__(self):
        while True:
            self.buffer.seek(self.read_pos)
            line = self.buffer.readline()

            # print(line)
            if line and line[-1] == ord("\n"):
                self.read_pos += len(line)
                full_line = line[:-1].decode("utf-8")
                # print(full_line)
                line_data = json.loads(full_line.lstrip("data:").rstrip("/n"))
                return line_data["token"].get("text", "")
            chunk = next(self.byte_iterator)
            self.buffer.seek(0, io.SEEK_END)
            self.buffer.write(chunk["PayloadPart"]["Bytes"])


def get_realtime_response_stream(sagemaker_runtime, endpoint_name, payload):
    response_stream = sagemaker_runtime.invoke_endpoint_with_response_stream(
        EndpointName=endpoint_name,
        Body=json.dumps(payload),
        ContentType="application/json",
        CustomAttributes='accept_eula=false'
    )
    return response_stream
    
prompt = ""

parameters = {
        "max_new_tokens":1024, 
        "do_sample": True,
    }

payload = {
    "inputs":  prompt,
    "parameters": parameters,
    "stream": True ## <-- to have response stream.
}
response_stream = get_realtime_response_stream(smr_client, endpoint_name, payload)
# print_response_stream(response_stream)
for token in TokenIterator(response_stream["Body"]):
    # pass
    print(token, end="", flush=True)
```
Full sample codes could find in https://github.com/aws-samples/llm_deploy_gcr/blob/main/sagemaker/deepseek_coder_6.7_instruct.ipynb.

Thank you for your time and attention to this matter again, and also thank you for supporting SageMaker. Looking forward to your feedback and continued improvements to the project.

_Originally posted by @xqun3 in https://github.com/BerriAI/litellm/issues/5178#issuecomment-2309738455_

**Comment by ghost** [comment]
able to repro
