### ISSUE TITLE
Allow `json_schema` for Azure OpenAI 2024-08-01-preview API

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#5377]
@krrishdholakia This seems to be used even when newer models like gpt-4o-mini are used with the new Azure OpenAI 2024-08-01-preview API.

_Originally posted by @Manouchehri in https://github.com/BerriAI/litellm/issues/5296#issuecomment-2311234598_

**Comment by ghost** [comment]
Hey @Manouchehri i'm looking at their docs and it doesn't look like they support json_schema yet - https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#request-body-2

Should i be looking somewhere else?

**Comment by ghost** [comment]
even their preview api doesn't document this yet - https://learn.microsoft.com/en-us/azure/ai-services/openai/reference-preview#properties-for-response_format

**Comment by ghost** [comment]
does the json_schema param work for you for azure openai directly? 
Will test on my end to confirm @Manouchehri

**Comment by Manouchehri** [comment]
The preview docs are chronically outdated. It was added in 2024-08-01-preview, which just went live recently.

**Comment by Manouchehri** [comment]
See https://github.com/Azure/azure-rest-api-specs/pull/30147#issuecomment-2297461685 for the PR that has the spec. It went live sometime in the last 7 days.

**Comment by ghost** [comment]
Hi @Manouchehri it looks like 'json_schema' isn't supported in 2024-08-01-preview
<img width="1662" alt="Screenshot 2024-08-26 at 8 44 57 PM" src="https://github.com/user-attachments/assets/aed6c188-2689-46c4-a7cc-48b758e00f03">


Code for repro: 
```python
data = {
    "messages": [
      {
        "role": "system",
        "content": "You are a helpful math tutor. Guide the user through the solution step by step."
      },
      {
        "role": "user",
        "content": "how can I solve 8x + 7 = -23"
      }
    ],
    "response_format": {
      "type": "json_schema",
      "json_schema": {
        "name": "math_reasoning",
        "schema": {
          "type": "object",
          "properties": {
            "steps": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "explanation": { "type": "string" },
                  "output": { "type": "string" }
                },
                "required": ["explanation", "output"],
                "additionalProperties": False
              }
            },
            "final_answer": { "type": "string" }
          },
          "required": ["steps", "final_answer"],
          "additionalProperties": False
        },
        "strict": True
      }
    }
}
from openai import AzureOpenAI

# gets the API Key from environment variable AZURE_OPENAI_API_KEY
client = AzureOpenAI(
    api_version="2024-08-01-preview",
    azure_endpoint="https://openai-gpt-4-test-v-1.openai.azure.com",
    api_key="my-key"
)

completion = client.chat.completions.create(
    model="my-gpt-4o-mini",  # e.g. gpt-35-instant
    **data
)
print(completion.to_json())
```

**Comment by ghost** [comment]
Closing as not planned for now. But if you find it working, feel free to reopen

**Comment by Manouchehri** [comment]
Oh weird, you're right...

Odd. I guess it will be added in a few days hopefully, since it is in the spec

https://github.com/yuanzhuangyuanzhuang/azure-rest-api-specs/blob/1d79406e246a8423012a6d642f9e84715a919da0/specification/cognitiveservices/data-plane/AzureOpenAI/inference/preview/2024-08-01-preview/inference.yaml#L2491

**Comment by Manouchehri** [comment]
This now supported by Azure OpenAI on `gpt-4o-2024-08-06`, just tested it myself. (`gpt-4o-mini-2024-07-18` on Azure OpenAI does *not* support it.)

https://techcommunity.microsoft.com/t5/ai-azure-ai-services-blog/introducing-gpt-4o-2024-08-06-api-with-structured-outputs-on/ba-p/4232684
