### ISSUE TITLE
[Bug]: claude-2 fails with request_timeout 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#538]
### What happened?

request_timeout is an openai supported feature, autogen uses request_timeout like this in their code:

```python
if "request_timeout" in config:
    response = litellm.completion(**config)
else:
    response = litellm.completion(request_timeout=request_timeout, **config)
```

**Comment by ishaan-jaff** [comment]
when passing request_timeout to anthropic, I got an exception from the Anthropic API 
```shell
Failed: Error occurred: AnthropicException - {'type': 'invalid_request_error', 'message': 'request_timeout: extra fields not permitted'}
```

**Comment by ishaan-jaff** [comment]
this means that my code will look like this on autogen:

```python
if config["model"] in litellm.anthropic_models:
  if "request_timeout" in config:
      config.pop("request_timeout")
      response = litellm.completion(**config)
  else:
      response = litellm.completion(**config)
else:

  if "request_timeout" in config:
      response = litellm.completion(**config)
  else:
      response = litellm.completion(request_timeout=request_timeout, **config)
```

**Comment by ishaan-jaff** [comment]
IMO we should support the request_timeout param for all providers, but pass it to our wrapper. Since not all apis support the timeout param

**Comment by krrishdholakia** [comment]
can you see if this works if you set `litellm.drop_params = True` @ishaan-jaff

**Comment by ishaan-jaff** [comment]
same error raise Failed(msg=reason, pytrace=pytrace)
Failed: Error occurred: AnthropicException - {'type': 'invalid_request_error', 'message': 'request_timeout: extra fields not permitted'}

Here's my code:
```python
litellm.set_verbose = True
litellm.drop_params = True


# test setting max tokens for claude-2
user_message = "tell me everything about YC - be verbose"
messages = [{"content": user_message, "role": "user"}]

response = completion(
  model="claude-instant-1", messages=messages, max_tokens=1200, request_timeout=10
)
```

**Comment by ghost** [comment]
Looks like the underlying issue is that request_timeout is not stored as an openai_param (not in completion). 

This leads to it being passed as a kwarg to the model. 

Let's add it back to the completion() function, and handle this logic in that manner.

**Comment by ghost** [comment]
@ishaan-jaff are you working on this? assigning it to you now. Let me know if not.

**Comment by ishaan-jaff** [comment]
yes working on this

**Comment by ishaan-jaff** [comment]
fixed !
