### ISSUE TITLE
[Bug]: Unexpected types returned by `Router.aembedding`

### ISSUE THREAD

**Issue by mserek** [BerriAI/litellm#5383]
### What happened?

When using `aembedding` method from `Router`, the returned type is not the expected type. According to type hints, it should be a `Union[List[float], None]`, however, when calling, the actual type is `<class 'litellm.types.utils.EmbeddingResponse'>`.

Example:
```python
from litellm.router import Router
import asyncio
model_list = [
    {
        "model_name": "ada",
        "litellm_params": {
            "model": "azure/text-embedding-ada-002",
            "api_key": AZURE_OPENAI_API_KEY,
            "api_version": "2024-06-01",
            "api_base": AZURE_OPENAI_API_BASE,
        },
    },
]
router = Router(
    model_list=model_list,
    default_litellm_params={
        "acompletion": True,
    },
)
async def async_get_embedding():
    response = await router.aembedding(model="ada", input="test")
    print(type(response))

loop = asyncio.get_event_loop()
loop.run_until_complete(async_get_embedding())
```
Output:
`<class 'litellm.types.utils.EmbeddingResponse'>`
Expected:
`<class 'NoneType'>` or `<class 'list'>`
<img width="440" alt="Screenshot 2024-08-27 at 12 27 01" src="https://github.com/user-attachments/assets/09c0a92e-24ad-41da-beb0-3fbcdd9f4fd7">

**Comment by ghost** [comment]
The type hint seems incorrect. Thanks for the callout @mserek
