### ISSUE TITLE
[Not a Bug]: GitHub Models - Supported Params?

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#5386]
### What happened?

Where in LiteLLM is the supported parameters defined for the GitHub Models / Marketplace provider?

e.g. right now logprobs doesn't work (due to a limitation on GitHub's end, not LiteLLM), but I can't actually find where in the source that LiteLLM limits the parameters.

```sh
curl "${OPENAI_API_BASE}/chat/completions" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
    "model": "gpt-4o-mini-2024-07-18-github",
    "messages": [
      {
        "role": "user",
        "content": "Hello!"
      }
    ],
    "logprobs": true,
    "top_logprobs": 2,
    "cache": {"no-cache": true}
  }' -v | jq
```

### Relevant log output

```shell
{
  "error": {
    "message": "litellm.BadRequestError: GithubException - This model does not support the 'logprobs' parameter.No fallback model group found for original model_group=gpt-4o-mini-2024-07-18-github. Fallbacks=[{'gpt-4o-mini': ['gpt-4o-mini-2024-07-18-oai']}, {'gpt-4o-mini-2024-07-18': ['gpt-4o-mini-2024-07-18-oai']}]\nReceived Model Group=gpt-4o-mini-2024-07-18-github\nAvailable Model Group Fallbacks=None\nError doing the fallback: litellm.BadRequestError: GithubException - This model does not support the 'logprobs' parameter.No fallback model group found for original model_group=gpt-4o-mini-2024-07-18-github. Fallbacks=[{'gpt-4o-mini': ['gpt-4o-mini-2024-07-18-oai']}, {'gpt-4o-mini-2024-07-18': ['gpt-4o-mini-2024-07-18-oai']}] LiteLLM Retried: 1 times, LiteLLM Max Retries: 2",
    "type": null,
    "param": null,
    "code": "400"
  }
}
```

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by ghost** [comment]
i couldn't find their list of supported providers, so it currently uses the openai defaults - https://github.com/BerriAI/litellm/blob/bd3057e4959b6977a2e58535b8a93e5bef1aa4b0/litellm/utils.py#L3801

**Comment by ghost** [comment]
can you find their list of supported params?

**Comment by Manouchehri** [comment]
> can you find their list of supported params?

Na; GitHub appears to be using Azure OpenAI behind the scenes, so tbh I don't really understand why the support is different. That might change in the (near) future IMO.

**Comment by ghost** [comment]
What would you want to happen here? @Manouchehri

**Comment by Manouchehri** [comment]
Nothing, the default settings look correct to me. :)
