### ISSUE TITLE
[Bug]: Message with a tool's response, fails using Claude

### ISSUE THREAD

**Issue by WilliamEspegren** [BerriAI/litellm#5388]
### What happened?

Second response using where the model can see the function response fails with claude.

I found an example of tool calling on https://docs.litellm.ai/docs/completion/function_call. If you change out the model to "claude-3-5-sonnet-20240620", the tool call will work, but  it fails if you send another requests where you include the tool's response.

### Relevant log output

```shell
(venv) litellm_guide$ python testing_example_on_litellm.py 

First LLM Response:
 ModelResponse(id='chatcmpl-6cabead7-c21b-4d19-9819-6dc3480aa8de', choices=[Choices(finish_reason='tool_calls', index=0, message=Message(content="To provide you with the current weather information for San Francisco, Tokyo, and Paris, I'll need to use the weather tool for each city. Let me fetch that information for you.", role='assistant', tool_calls=[ChatCompletionMessageToolCall(index=1, function=Function(arguments='{"location": "San Francisco, CA"}', name='get_current_weather'), id='toolu_01Y6w6vHWmkntyMSEERqnZLx', type='function'), ChatCompletionMessageToolCall(index=2, function=Function(arguments='{"location": "Tokyo, Japan"}', name='get_current_weather'), id='toolu_01BuPdHZXmB2idpmNLrKFgKa', type='function'), ChatCompletionMessageToolCall(index=3, function=Function(arguments='{"location": "Paris, France"}', name='get_current_weather'), id='toolu_01XcNodahB13ntSNBxWTkyP6', type='function')], function_call=None))], created=1724768774, model='claude-3-5-sonnet-20240620', object='chat.completion', system_fingerprint=None, usage=Usage(completion_tokens=176, prompt_tokens=411, total_tokens=587))

Length of tool calls 3

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Error occurred: litellm.BadRequestError: AnthropicException - {"type":"error","error":{"type":"invalid_request_error","message":"Requests which include `tool_use` or `tool_result` blocks must define tools."}}
```

### Twitter / LinkedIn details

https://x.com/WilliamEspegren

**Comment by Penagwin** [comment]
Can you include specific examples of what you're requesting on the first message and the second message?

This usually means you didn't include the tool definitions `tools: [getCurrentWeatherToolDefinition ]` on the second call

**Comment by WilliamEspegren** [comment]
Thanks! Just thought that it should work when just changing the model. Do you think there is a way to do this or maybe log a warning that you should specify tools?

**Comment by ghost** [comment]
Hey @WilliamEspegren we explored this briefly - we could store the tool call. the feedback we got at the time was that the user would rather know the actual provider error, instead of litellm modifying their input

**Comment by Penagwin** [comment]
I think the litellm proxy should be as transparent as possible.

Or have a transparent mode

Otherwise it could get confusing if litellm is modifying the prompts or errors

**Comment by ghost** [comment]
@Penagwin agreed. if this ever does get supported, it would be feature flagged. We shouldn't be messing with your prompts unless you're opting into it via `litellm.modify_params` or some equivalent flag.

**Comment by mperezjodal** [comment]
Having the same problem, could you understand the issue or find a workaround?

Thanks for the help

**Comment by WilliamEspegren** [comment]
@mperezjodal if you have a message history with a tools result, you must include the tool definition in every single call to anthropic. Hope this helps :)

**Comment by ghost** [comment]
reopening as this is probably something we should help solve
