### ISSUE TITLE
[Bug]: Broken compatibility since deprecating boto3 aws_bedrock_client parameter

### ISSUE THREAD

**Issue by btemplep** [BerriAI/litellm#5389]
### What happened?

Since passing in the `aws_bedrock_client` parameter to completion is deprecated, the boto3 client is no longer used behind the scenes.  This breaks scenarios where the endpoint URL was updated as well as any [custom event functions](https://boto3.amazonaws.com/v1/documentation/api/1.9.41/guide/events.html).  
I do see that you can set the bedrock endpoint URL [in the code](https://github.com/BerriAI/litellm/blob/main/litellm/llms/bedrock_httpx.py#L689), but it's not in the docs from what I could see. 
There is still a lot of lost functionality.  
For instance the ability to set headers after the request is prepped.  Like overriding the `Authorization` header for custom URLs.

**Comment by ghost** [comment]
Hi @btemplep the boto3 client is still used for handling auth. 

It's not used for making the request, as it's not async. 

---
I've noted your 2 action items: 
- [x] retain ability to set headers after the request is prepped -> this is already supported via the openai `extra_headers` param. -> I'll add an example for this to docs as well 
- [x] show how to set bedrock endpoint url on docs

**Comment by ghost** [comment]
Covered here - https://docs.litellm.ai/docs/providers/bedrock#passing-extra-headers--custom-api-endpoints

appreciate the feedback @btemplep, please let me know how we can further improve here!

**Comment by btemplep** [comment]
@krrishdholakia 
That works for headers that are not set when preparing the request, but doesn't work for  the`Authorization` header since that is overwritten when `sigv4.add_auth(request)`  is called.
Extra headers are added before auth is added. 
https://github.com/BerriAI/litellm/blob/main/litellm/llms/bedrock_httpx.py#L890-L897C9
https://github.com/BerriAI/litellm/blob/main/litellm/llms/bedrock_httpx.py#L1655-L1662

`add_auth()` overrides the `Authorization` header:
https://github.com/boto/botocore/blob/develop/botocore/auth.py#L421
https://github.com/boto/botocore/blob/develop/botocore/auth.py#L446


I believe if it is updated to add the headers after the auth is added but before `request.prepare()` is called it will solve the issue since that can only change the transfer-encoding or content-length headers
https://github.com/boto/botocore/blob/develop/botocore/awsrequest.py#L366-L407

**Comment by btemplep** [comment]
> Covered here - https://docs.litellm.ai/docs/providers/bedrock#passing-extra-headers--custom-api-endpoints
> 
> appreciate the feedback @btemplep, please let me know how we can further improve here!

This makes it much easier to find :smiley:

**Comment by ghost** [comment]
Fixed the auth check @btemplep

**Comment by btemplep** [comment]
I was just looking at creating a PR but you beat me to it.  Much appreciated @krrishdholakia!
