### ISSUE TITLE
[Bug]: Streaming chunks attribute access fails 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#539]
### What happened?

> a minor thing I had to change in my code is in streaming, I was accessing chunk.choices[0].finish_reason, but with litellm those had to be changed to dict access rather than attribute access.

**Comment by ghost** [comment]
More context - 
<img width="892" alt="Screenshot 2023-10-05 at 4 19 40 PM" src="https://github.com/BerriAI/litellm/assets/17561003/beceff7f-9711-4c7f-90f3-3b0c33d2dd33">

**Comment by ishaan-jaff** [comment]
just tested - works fine for palm, openai, etc
