### ISSUE TITLE
[Feature]: ai21/jamba-1.5 from Google Vertex AI

### ISSUE THREAD

**Issue by jguokion** [BerriAI/litellm#5399]
### The Feature

I would like to use Jamba 1.5 Model Family from vertex ai. 

[Jamba 1.5 Mini](https://console.cloud.google.com/vertex-ai/publishers/ai21/model-garden/jamba-1.5-mini): AI21’s most efficient and lightweight model, engineered for speed and efficiency in tasks including customer support, document summarization, and text generation.

[Jamba 1.5 Large](https://console.cloud.google.com/vertex-ai/publishers/ai21/model-garden/jamba-1.5-large): AI21’s most advanced and largest model that can handle advanced reasoning tasks — such as financial analysis — with exceptional speed and efficiency.

### Motivation, pitch

The models are very efficient and have novel Mamba architecture. This is appealing to me.

**Comment by traderpedroso** [comment]
Have you test it using custom model - vertex_ai-language-models/jamba-1.5

**Comment by ghost** [comment]
Supported with this PR - https://github.com/BerriAI/litellm/pull/5391

Will be live in today's release
