### ISSUE TITLE
[Feature]: add litellm.proxy, like openai.proxy

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#540]
### The Feature

some repos use openai.proxy and we can't entirely replace openai for their usage 

example
```python
    def __init_openai(self, config):
        if self.proxy != '':
            openai.proxy = self.proxy
```

### Motivation, pitch

-

**Comment by ghost** [comment]
i'm confused @ishaan-jaff how are we unable to help b/c of this? are you suggesting a module variable called `proxy`? 

Tbh i'm not clear on what openai.proxy does v/s. api_base

**Comment by ishaan-jaff** [comment]
we fail for the repo when you try to set litellm.proxy because we don't even have a variable like that

**Comment by ishaan-jaff** [comment]
that's a good starting place ^ 


If we're a drop in replacement for openai and openai.proxy exists we should probably have the same functionality for the variable litellm.proxy

**Comment by ghost** [comment]
That's fair - what does proxy do though? besides openai do we send it to any other provider?

**Comment by usathyan** [comment]
can you provide a network proxy for openai calls? many companies have their firewalls and use proxy to reach hosted models!

**Comment by ishaan-jaff** [comment]
@usathyan we already do this you can try it here: https://docs.litellm.ai/docs/proxy_server

**Comment by usathyan** [comment]
This is different. I am not asking for openai API translator for other
hosted models. I am looking for a network proxy tunnel through company
firewalls to reach azure openai models

**Comment by ishaan-jaff** [comment]
@usathyan can you help me better understand what you're hoping for litellm to do ? Would love to add what you're looking for to litellm

Our proxy allows you to create a server for calling azure openai
```shell
litellm --model azure/chat-gpt
```

**Comment by usathyan** [comment]
Well, here is the situation -
I am interested in using open-interpreter(
https://github.com/KillianLucas/open-interpreter). I found out that that
project uses liteLLM. The situation is that in order for me to use an
open-interpreter requires me to route all network traffic via a http proxy
server. for example - the openai endpoint is only accessible via the
network proxy. see here for reference -
https://github.com/openai/openai-node/tree/v4#configuring-an-https-agent-eg-for-proxies

Thanks!

**Comment by ishaan-jaff** [comment]
got it @usathyan I should have something ready for you in 24 hrs

**Comment by ishaan-jaff** [comment]
here's my understanding of what youre looking for:

Open interpreter -> Proxy -> OpenAI GPT-4 

The proxy should make your OpenAI GPT-4 calls for you 


Do you want us to help you create the proxy for you ? or do you simply just want to set litellm.proxy and make the call ? 
@usathyan

**Comment by usathyan** [comment]
Yes, please!

**Comment by usathyan** [comment]
Hello me find all images to edit and tweak to make it work

**Comment by usathyan** [comment]
Sorry. Help me find

**Comment by usathyan** [comment]
Thank you!
