### ISSUE TITLE
[Bug]: streaming completions always incorrectly logs cache_hit=None

### ISSUE THREAD

**Issue by ajeetdsouza** [BerriAI/litellm#5401]
### What happened?

See this code, lifted almost verbatim from https://docs.litellm.ai/docs/caching/local_caching#caching-with-streaming:

<details>

<summary>
Code
</summary>

```python
import litellm
from litellm import completion
from litellm.caching import Cache
import time

litellm.cache = Cache()
litellm.set_verbose = True

# Make completion calls
now = time.time()
response = completion(
    model="gpt-3.5-turbo",
    messages=[{"role": "user", "content": "Tell me a joke."}],
    stream=True,
    caching=True)
for chunk in response:
    print(chunk)
print(f"elapsed1: {time.time() - now}")

time.sleep(5)

now = time.time()
response = completion(
    model="gpt-3.5-turbo",
    messages=[{"role": "user", "content": "Tell me a joke."}],
    stream=True,
    caching=True)
for chunk in response:
    print(chunk)
print(f"elapsed2: {time.time() - now}")
```

</details>

In the log output, I see `Logging Details LiteLLM-Async Success Call, cache_hit=None` - which gives the impression that caching isn't working correctly. But if you look at the elapsed time, it's `0.8s` and `0.006s` - the second attempt has come from the cache after all.

**Comment by ghost** [comment]
able to repro
