### ISSUE TITLE
[Bug]: Can't mute LiteLLM:WARNING: vertex_httpx.py:1328 - Unable to identify if system message supported

### ISSUE THREAD

**Issue by paul-gauthier** [BerriAI/litellm#5403]
### What happened?

I have `suppress_debug_info = True` and `set_verbose = False` but am still getting warnings printed to the terminal with `gemini/gemini-1.5-pro-exp-0827`.

### Relevant log output

```shell
06:36:34 - LiteLLM:WARNING: vertex_httpx.py:1328 - Unable to identify if system message supported. Defaulting to 'False'. Received error message - Model not in model_prices_and_context_window.json. You passed model=gemini-1.5-pro-exp-0827, custom_llm_provider=gemini.

$ pip freeze | grep litellm
litellm==1.44.7
```

**Comment by ghost** [comment]
side note - i think we can also look if a known substring is in the name - e.g. we know `gemini-1.5-pro` supports system message, so it would make sense that `gemini-1.5-pro-exp-0827` also does

**Comment by ghost** [comment]
is `gemini-1.5-pro-exp-0827` documented somewhere? @paul-gauthier 

will help to add it to the model cost map

**Comment by paul-gauthier** [comment]
I'm not sure about the parameters for that model.

But regardless of that specific model, can I make litellm stop printing all warning to the terminal? I thought suppress_debug_info = True and set_verbose = False would do that?

**Comment by ghost** [comment]
@paul-gauthier we need to do this manually today - .warning messages are emitted at different parts of the codebase to make litellm behaviour clear/more observable. 

If we use a wrapper function, then we'll lose the line in the codebase the error / issue actually happened in. How can we make this easier to control? 

Currently i can think of manually adding this flag in all our verbose_logger.warning checks, but it can lead to the issue happening again

**Comment by paul-gauthier** [comment]
I poked around the repo and it looks like I can just do `litellm._logging._disable_debugging()` and that silences everything.
