### ISSUE TITLE
[Bug]: Deleting a model from Model Management on a web page will not automatically remove the model from Fallbacks

### ISSUE THREAD

**Issue by guleng** [BerriAI/litellm#5405]
### What happened?

After adding the model in Fallbacks, I deleted it. However, the model that has already been deleted in Fallbacks still exists. I hope that after deleting the model, it can be automatically deleted from Fallbacks

**Comment by ghost** [comment]
This makes sense. you set fallbacks on the 'model_name'. Not on an individual model.
