### ISSUE TITLE
[Bug]: Non working link

### ISSUE THREAD

**Issue by superpoussin22** [BerriAI/litellm#5408]
### What happened?

on the documentation web page for vertex ai endpoint ( https://docs.litellm.ai/docs/pass_through/vertex_ai ) the link "Looking for the Unified API (OpenAI format) for VertexAI ? "  is pointing to https://docs.litellm.ai/docs/docs/providers/vertex.md. what does not exist 

### Relevant log output

```shell
Page Not Found
We could not find what you were looking for.

Please contact the owner of the site that linked you to the original URL and let them know their link is broken.
```

**Comment by ghost** [comment]
Thanks for the callout. Fixed now.
