### ISSUE TITLE
[Feature]: LLMMonitor Integration - allow passing in user id

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#541]
### The Feature

Allow passing in user-id for llm monitor integration

### Motivation, pitch

user request cc:@paulpierre

**Comment by ghost** [comment]
cc: @vincelwt any help on this?

**Comment by vincelwt** [comment]
Hi! 

Seems like @ishaan-jaff fixed it here: https://github.com/BerriAI/litellm/commit/1897a1ee46b993c3e47c4e986e19ac8530bed761 ? 

Seems like it has changed how you guys handle user IDs since the integration
