### ISSUE TITLE
[Bug]: api_base masking for Gemini insufficient to mask API keys in logs

### ISSUE THREAD

**Issue by cheahjs** [BerriAI/litellm#5433]
### What happened?

Masking the first 5 characters of a Google API key is insufficient, as API keys are always prefixed with the same 4 letters (`AIza`), leaving only a single character that is masked, allowing for trivial recovery of the API key.

https://github.com/BerriAI/litellm/blob/559a6ad826b5daef41565f54f06c739c8c068b28/litellm/litellm_core_utils/litellm_logging.py#L276-L287

Example metadata from a Langfuse trace:
![image](https://github.com/user-attachments/assets/f135298d-a786-4d19-b57e-a9e6fc52cc77)

**Comment by Manouchehri** [comment]
@cheahjs Sent you a private email about this one.

**Comment by ishaan-jaff** [comment]
Hi @cheahjs, curious do you use LiteLLM Proxy in production today If so, I'd love to hop on a call and learn how we can improve LiteLLM for you

- my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
- my linkedin if you prefer DMs: https://www.linkedin.com/in/reffajnaahsi/
