### ISSUE TITLE
[Feature]: `json_schema` support for Bedrock Anthropic

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#5434]
### The Feature

Similar to how Claude via Vertex AI supports `json_schema`, it'd be great if Amazon Bedrock's Claude also supported that.

Related to #5172.

### Motivation, pitch

Same as #5172.

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by ghost** [comment]
I believe as long as a model supports tool calling on bedrock, we should be able to support this
