### ISSUE TITLE
[Feature]: Add support for Cloudflare Workers AI 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#544]
### The Feature

https://blog.cloudflare.com/workers-ai/?utm_source=substack&utm_medium=email

### Motivation, pitch

Better model support

**Comment by Manouchehri** [comment]
Would love to have this as well, since Cloudflare has been adding a fair amount of new models. 😄

**Comment by shuther** [comment]
extra links: [website](https://developers.cloudflare.com/ai-gateway/get-started/connecting-applications/)
While they do provide endpoints similar to openAI that is model specific, they also provide a generic API.
The point to be cautious during the implementation is that the number of allowed tokens depend on  the type of call (sync/async/stream). Stream is prefered so a wrapper migth be needed.
Given it is kind of 'free' use for now, this end point is quite important.

**Comment by shuther** [comment]
As a temporary appoach, I was able to make it work using:
`litellm  --config config.yaml`
and cat config.yaml

```
model_list:
  - model_name: mistral-7b
    litellm_params:
      model: gpt-3.5-turbo # fake openai
      api_base: "https://api.cloudflare.com/client/v4/accounts/tobefilled/ai/run/@cf/meta/llama-2-7b-chat-int8"
      api_key: dummy
      headers: {
#        "HTTP-Referer": "litellm.ai",  
        "X-Auth-Key": "to be filled"
      }
```
api_key has to be set to a value, otherwise the openai module is complaining.
the api base enforces the model name; the model field is ignored.
The model can be set as per [link](https://developers.cloudflare.com/workers-ai/models/text-generation/)

**Comment by ishaan-jaff** [comment]
we support Cloudflare Workers AI now @shuther @Manouchehri 

https://docs.litellm.ai/docs/providers/cloudflare_workers
