### ISSUE TITLE
[Feature]: Reintroduce api_base, api_key etc. as params to completion()

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#545]
### The Feature

Add back the api_base, api_key, etc. as params to completion. This is helpful as hints while typing in vscode

### Motivation, pitch

by removing them, i no longer know they exist as options and need to refer to docs to see what's possible. It would be helpful to have them.

I understand the initial motivation for removing them as explicit args was to clean up completion, but maybe there's a way of having them be there when i need them as hints, while still keeping the code clean. <- potentially via the client wrapper?

**Comment by ishaan-jaff** [comment]
+1

**Comment by ishaan-jaff** [comment]
i looked into this it looks like adding it to the client wrapper does not make it show up in the type hints

**Comment by ishaan-jaff** [comment]
I think api_base, api_key and api_version are widely used so I'd be open to adding it back in completion

**Comment by ishaan-jaff** [comment]
done
