### ISSUE TITLE
[Bug]: When creating vertex cache content, the wrong endpoint is called

### ISSUE THREAD

**Issue by supmind** [BerriAI/litellm#5460]
### What happened?

model_list:
  - model_name: gemini-1.5-flash
    litellm_params:
      model: vertex_ai/gemini-1.5-flash-001
      vertex_project: "xxxxx"
      vertex_location: "europe-west3"
      vertex_credentials: "/app/key.json"
  - model_name: gemini-1.5-pro
    litellm_params:
      model: vertex_ai/gemini-1.5-pro-001
      vertex_project: "xxxxx"
      vertex_location: "europe-west3"
      vertex_credentials: "/app/key.json"
default_vertex_config:
  vertex_project: "nxxxxx"
  vertex_location: "europe-west3"
  vertex_credentials: "/app/key.json"
litellm_settings:
    vertex_ai_safety_settings:
      - category: HARM_CATEGORY_HARASSMENT
        threshold: BLOCK_NONE
      - category: HARM_CATEGORY_HATE_SPEECH
        threshold: BLOCK_NONE
      - category: HARM_CATEGORY_SEXUALLY_EXPLICIT
        threshold: BLOCK_NONE
      - category: HARM_CATEGORY_DANGEROUS_CONTENT
        threshold: BLOCK_NONE
general_settings:
  master_key: sk-94

### Relevant log output

```shell
- "POST /vertex-ai/cachedContents HTTP/1.1" 404 Not Found
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/pass_through_endpoints/pass_through_endpoints.py", line 464, in pass_through_request
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '404 Not Found' for url 'https://europe-west3-aiplatform.googleapis.com/cachedContents'
```

**Comment by ishaan-jaff** [comment]
@supmind  - this looks like you're calling our pass through endpoint on the proxy server. Can you share your code you're using to make the call ?

**Comment by ghost** [comment]
your url looks incorrect @supmind it's missing the project id + location

This is how it should look: 
> POST https://LOCATION-aiplatform.googleapis.com/v1beta1/projects/PROJECT_ID/locations/LOCATION/cachedContents

**Comment by ghost** [comment]
i can see that's what **our** example says to do though, so i assume this is an error on our end - https://docs.litellm.ai/docs/pass_through/vertex_ai#context-caching

**Comment by ghost** [comment]
Able to repro
