### ISSUE TITLE
[Feature]: List all supported bedrock models

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#547]
### The Feature

There's a known set of bedrock models, we should just list all of them 

### Motivation, pitch

make it easy for users to get started with bedrock

**Comment by ryanh-ai** [comment]
link to doc, I have a partial commit in my fork I need to clean up and verify with most of these in it:

https://docs.aws.amazon.com/bedrock/latest/userguide/model-ids-arns.html



Provider | Model name | Version | Model Id
-- | -- | -- | --
AI21 Labs | Jurassic-2 Mid | 1.x | ai21.j2-mid-v1
AI21 Labs | Jurassic-2 Ultra | 1.x | ai21.j2-ultra-v1
Amazon | Titan Text G1 - Lite | 1.x | amazon.titan-text-lite-v1
Amazon | Titan Embeddings G1 - Text | 1.x | amazon.titan-embed-text-v1
Amazon | Titan Text G1 - Express | 1.x | amazon.titan-text-express-v1
Amazon | Titan Text G1 - Agile | 1.x | amazon.titan-text-agile-v1
Anthropic | Claude | 1.x | anthropic.claude-v1
Anthropic | Claude | 2.x | anthropic.claude-v2
Anthropic | Claude Instant | 1.x | anthropic.claude-instant-v1
Cohere | Command | 14.x | cohere.command-text-v14
Stability AI | Stable Diffusion XL | 0.x | stability.stable-diffusion-xl-v0

**Comment by ghost** [comment]
Looks like i didn't close out the issue. I updated the list based on the text gen models they had 
https://github.com/BerriAI/litellm/blob/413097f0a7b73a2e773ec1c8c4687548c736a5ba/model_prices_and_context_window.json#L469

I believe i have everything covered besides the g1 agile - feel free to add it

**Comment by ryanh-ai** [comment]
ahh, I assumed this issue was meant for the `__init__.py`, specifically this code:

```
bedrock_models: List = [
    "ai21.j2-mid-v1",
    "ai21.j2-ultra-v1",
    "amazon.titan-text-lite-v1",
    "amazon.titan-text-express-v1",
    "amazon.titan-text-agile-v1",
    "anthropic.claude-v1",
    "anthropic.claude-v2",
    "anthropic.claude-instant-v1",
    "cohere.command-text-v14",
]
```

Is this now pulling straight from `model_prices_and_context_window.json`?

**Comment by ghost** [comment]
yep - https://github.com/BerriAI/litellm/blob/3e40ba39bf1f648d493923e94d69a0d60f196220/litellm/__init__.py#L125

which version is that from?

**Comment by ghost** [comment]
more context on why we did this - https://github.com/BerriAI/litellm/issues/412

**Comment by ryanh-ai** [comment]
love it :)

**Comment by ghost** [comment]
this is done.
