### ISSUE TITLE
[Bug]: itellm.BadRequestError: BedrockException - {"message":"1 validation error detected: Value '' at 'system.1.member.text' failed to satisfy constraint: Member must have length greater than or equal to 1"}

### ISSUE THREAD

**Issue by lmcmahi** [BerriAI/litellm#5470]
### What happened?

Hi all,
I am making 2 functions calls  and I get this error. If I make one function there is not exception

### Relevant log output

```shell
litellm.exceptions.BadRequestError: litellm.BadRequestError: BedrockException - {"message":"1 validation error detected: Value '' at 'system.1.member.text' failed to satisfy constraint: Member must have length greater than or equal to 1"}
```

**Comment by ghost** [comment]
Can i have a script to repro this? @lmcmahi

**Comment by ghost** [comment]
I can see there is already checking for this @lmcmahi, can you confirm you're on the latest version of litellm? 
<img width="1198" alt="Screenshot 2024-09-02 at 7 50 15 AM" src="https://github.com/user-attachments/assets/12a03f40-37eb-4838-8e26-524472b104ec">

**Comment by ghost** [comment]
bump on this? @lmcmahi

**Comment by dipakparmar** [comment]
@krrishdholakia i'm seeing similar error:

```
21:42:13 - LiteLLM Proxy:ERROR: proxy_server.py:3033 - litellm.proxy.proxy_server.async_data_generator(): Exception occured - litellm.BadRequestError: BedrockException - {"message":"1 validation error detected: Value '[<fim_prefix>, <fim_suffix>, <fim_middle>, <file_sep>, <|endoftext|>, </fim_middle>, </code>, /src/, #- coding: utf-8, ```]' at 'inferenceConfig.stopSequences' failed to satisfy constraint: Member must have length less than or equal to 4"}
```

**Comment by ghost** [comment]
Hi @dipakparmar can you share steps to repro?

**Comment by dipakparmar** [comment]
@krrishdholakia 
I currently don't have that, as it does not indicate which user's request is failing. Is there a way for me to find out?
