### ISSUE TITLE
[Bug]: Add support for AI21 Jamba models

### ISSUE THREAD

**Issue by toniengelhardt** [BerriAI/litellm#5475]
### What happened?

Getting "Not found" errors for Jamba 1.5 large / mini models

This is the output with `verbose=True`, no error details given:

![Screenshot 2024-09-02 at 16 55 10](https://github.com/user-attachments/assets/58e3472a-5e81-4311-be61-9a40507dba50)

![Screenshot 2024-09-02 at 16 55 24](https://github.com/user-attachments/assets/a1cbb00e-be49-4881-bac0-f115ada790c7)

I also tried for model names `ai21/jamba-1.5-large` and `ai21/jamba-1.5-large@001`.

**Comment by ishaan-jaff** [comment]
working on this - we need to add support for their new chat endpoint

**Comment by ishaan-jaff** [comment]
Pr here: https://github.com/BerriAI/litellm/pull/5478
