### ISSUE TITLE
[Bug]: Lago Events Do Not Contain Customer ID

### ISSUE THREAD

**Issue by rawwerks** [BerriAI/litellm#5477]
### What happened?

following: https://docs.litellm.ai/docs/proxy/billing, i am using `LAGO_API_CHARGE_BY` = `end_user_id`:
![CleanShot 2024-09-02 at 13 09 46@2x](https://github.com/user-attachments/assets/5b181893-0491-4e0d-956a-45e5bdce1bb5)

and i have lago configured correctly finally, and i am receiving events...

...but the received Lago event payload has null for `external_customer_id`:
```
{
  "event": {
    "transaction_id": "my-transaction-id",
    "external_customer_id": null,
    "external_subscription_id": null,
    "code": "mixtcha-test",
    "timestamp": 1725289694,
    "properties": {
      "model": "gpt-4o",
      "total_tokens": 100,
      "prompt_tokens": 17,
      "response_cost": 0.00133,
      "completion_tokens": 83
    }
  }
}
```

this is how the proxy is being called: 

```
# request sent to model set on litellm proxy, `litellm --model`
response = client.chat.completions.create(model="test-openrouter", messages = [
    {
        "role": "user",
        "content": "this is a test request, write a short poem"
    }
], user="test-myself") # 👈 whatever your customer id is

print(response.choices[0].message.content)
```

and to be very clear, the user is correctly being accounted for in the proxy, it's just not being sent to lago: 

![CleanShot 2024-09-02 at 13 21 37@2x](https://github.com/user-attachments/assets/837c295d-345e-404b-9fcb-dfb98cb58ff1)

**Comment by rawwerks** [comment]
i also tried billing by team_id:
![CleanShot 2024-09-02 at 14 02 21@2x](https://github.com/user-attachments/assets/5d79bdff-a62e-4678-ac23-4af6a424a0a6)

this also leads to null values in the lago event payload: 
```
{
  "event": {
    "transaction_id": "9219dbd6-7e2f-4cff-b4b9-e5d31a81a3e0",
    "external_customer_id": null,
    "external_subscription_id": null,
    "code": "mixtcha-test",
    "timestamp": 1725300092,
    "properties": {
      "model": "gpt-4o",
      "total_tokens": 44,
      "prompt_tokens": 13,
      "response_cost": 0.0005300000000000001,
      "completion_tokens": 31
    }
  }
}
```

**Comment by rawwerks** [comment]
looking through the verbose logs, the external customer id is not set: 

![CleanShot 2024-09-02 at 14 06 26@2x](https://github.com/user-attachments/assets/50a93915-c78d-4dd3-9ff8-ce83816b5bb4)

**Comment by ghost** [comment]
trying to repro

**Comment by ghost** [comment]
Unable to repro, this works as expected

**Comment by ghost** [comment]
Config used for testing: 

```yaml
model_list:
  - model_name: "gpt-3.5-turbo"
    litellm_params:
      model: "gpt-3.5-turbo"


litellm_settings:
  callbacks: ["lago"]
```

Request made: 

```bash
curl -L -X POST 'http://0.0.0.0:4000/chat/completions' \
-H 'Content-Type: application/json' \
-H 'Authorization: Bearer sk-1234' \
-d '{
    "model": "gpt-3.5-turbo",
    "messages": [
      {
        "role": "user",
        "content": "how can I solve 8x + 7 = -23"
      }
    ],
    "user": "my-test-user"
}'
```

Logged Lago Object: 

```bash
15:29:00 - LiteLLM:DEBUG: lago.py:119 - Logged Lago Object:
{'event': {'transaction_id': '325f2f68-298a-40ff-99eb-b02b4e50bc22', 'external_customer_id': 'my-test-user', 'code': 'openai_tokens', 'properties': {'model': 'gpt-3.5-turbo', 'response_cost': 0.0002275, 'prompt_tokens': 20, 'completion_tokens': 145, 'total_tokens': 165}}}

```

**Comment by ghost** [comment]
Updating our lago error message to be more verbose for debugging @rawwerks

**Comment by rawwerks** [comment]
the only meaningful difference i can think of is that i only have this in my config.yaml, all the model details were set in the UI
![CleanShot 2024-09-03 at 18 38 05@2x](https://github.com/user-attachments/assets/d228bd4c-08f7-4c51-9658-a52373590429)

but unfortunately adding a model to config.yaml didn't change the result. 

can you think of any reason why the `litellm_params` might not be correctly retrieved from the kwargs of lago.py? https://github.com/BerriAI/litellm/blob/19dbfff620c9ae6a8632922e1dee400fa25661a6/litellm/integrations/lago.py#L78C1-L83C77

hopefully the extra lago object debugging can help...

**Comment by rawwerks** [comment]
fairly certain this is Lago's problem: https://github.com/getlago/lago/issues/397

**Comment by rawwerks** [comment]
new lago API requirement: https://docs.getlago.com/guide/migration/migration-to-v1.2.0#2-mandatory-external-subscription-id-field-in-event-payloads

> Making “events.external_subscription_id” required Sending event.external_subscription_id will be mandatory starting July 9, 2024.

**Comment by rawwerks** [comment]
from raffi in their slack: 

> The external_customer_id field is not supported anymore, for multiple reasons:
> 
> As a customer can have multiple subscriptions, the required field is the external_subscription_id. You can even set your own external id for a subscription.
> We ingest up to 10k events per second, and there is no post processing anymore. Even if your customer does have only 1 subscription, our system require to directly pass the external_subscription_id so we can directly map the right event to the right subscription, without having to map the subscriptions of a customer.
> 
> On our side, it's intended and definitely not a bug (updated couple of months ago)

**Comment by ghost** [comment]
Got it - thanks for the catch @rawwerks 

I'll fix the log to lago

**Comment by rawwerks** [comment]
https://github.com/BerriAI/litellm/pull/5495

**Comment by jdenquin** [comment]
👋 guys, Jeremy from Lago!

what version do you use for your tests @krrishdholakia ? Since our `v1.2.0` , `external_customer_id` on events is no more supported and you should now use `external_subscription_id`

**Comment by ghost** [comment]
we use mock calls @jdenquin 


Will update our tests to reflect this

**Comment by ghost** [comment]
This is now live in v1.44.16+
