### ISSUE TITLE
[Bug]: bug on Google AI Studio parsing chuck on stream

### ISSUE THREAD

**Issue by traderpedroso** [BerriAI/litellm#5479]
### What happened?

`litellm.APIConnectionError: Error parsing chunk: Expecting property name enclosed in double quotes: line 1 column 2 (char 1), Received chunk: { Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/litellm/llms/vertex_ai_and_google_ai_studio/gemini/vertex_and_google_ai_studio_gemini.py", line 1851, in __anext__ json_chunk = json.loads(chunk) ^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads return _default_decoder.decode(s) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode obj, end = self.scan_once(s, idx) ^^^^^^^^^^^^^^^^^^^^^^ json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 10819, in __anext__ async for chunk in self.completion_stream: File "/usr/local/lib/python3.11/site-packages/litellm/llms/vertex_ai_and_google_ai_studio/gemini/vertex_and_google_ai_studio_gemini.py", line 1865, in __anext__ raise RuntimeError(f"Error parsing chunk: {e},\nReceived chunk: {chunk}") RuntimeError: Error parsing chunk: Expecting property name enclosed in double quotes: line 1 column 2 (char 1), Received chunk: {`

**Comment by ghost** [comment]
how do i repro this? @traderpedroso

**Comment by traderpedroso** [comment]
> how do i repro this? @traderpedroso

This error is not a perfect science to explain how to reproduce it, sorry, especially because it occurs randomly, particularly when you have a long context. I've experienced this error on several platforms compatible with OpenAI, one example of a platform where the error is constant is OpenWebUI. I've been using it for a few months with a Gemini Go proxy and there are no errors, even using a 2 million token context size. With LiteLLM, this error always occurs.

**Comment by ghost** [comment]
What is the received chunk value? @traderpedroso This line looks cut-off 

> raise RuntimeError(f"Error parsing chunk: {e},\nReceived chunk: {chunk}") RuntimeError: Error parsing chunk: Expecting property name enclosed in double quotes: line 1 column 2 (char 1), Received chunk: {

**Comment by ghost** [comment]
Looks like an invalid json is returned as part of the streamed response `{`

**Comment by ghost** [comment]
Looks like google will occasionally return invalid json even with `alt=sse`

So we should have logic for handling this

**Comment by ishaan-jaff** [comment]
sharing if this helps- I had to do this for sagemaker too, we basically needed to collect the string / chunk until it's a valid json

**Comment by ghost** [comment]
It's unclear to me if gemini proceeds to return rest of the chunks as valid json

@traderpedroso if you can share any request which throws this error it would help. 

Unable to repro with the basic streaming example from gemini 

```bash
curl "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:streamGenerateContent?alt=sse&key=${GOOGLE_API_KEY}" \
        -H 'Content-Type: application/json' \
        --no-buffer \
        -d '{ "contents":[{"parts":[{"text": "Write a story about a magic backpack."}]}]}'
```

**Comment by ghost** [comment]
@ishaan-jaff sounds good. I'll write it to enter your custom parser logic if the initial chunk is invalid json
