### ISSUE TITLE
[Feature]: Update petals docs to show api usage

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#548]
### The Feature

Show how to use api base for petals

### Motivation, pitch

we added the feature, now show people how to use it -- i needed it as i didn't have a gpu and wanted to use the petals api

**Comment by gaborkukucska** [comment]
How how how???? Please please please!!!! 🙏🙏🙏🙌🙌🙌🙌

**Comment by gaborkukucska** [comment]
I have found the limited docs [HERE](https://docs.litellm.ai/docs/providers/petals) but this does not explain how to connect to a locally hosted private Petals swarm.

I figured to use --api_base and try a few URLs but nothing worked so far... Does LiteLLM connect to the Petals CPU Backbone directly or does it need the chat.petals.dev running for the /api/v2/generate API ?
