### ISSUE TITLE
[Bug]: litellm proxy - Vertex /image/generation not logged on Langfuse 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#5486]
### What happened?

A bug happened!
<img width="767" alt="Screenshot 2024-09-03 at 7 22 38 AM" src="https://github.com/user-attachments/assets/a5b414aa-b900-476f-a9f5-a5225afeddd3">

### Relevant log output

```shell
-
```

**Comment by ghost** [comment]
@ishaan-jaff are you picking this up?

**Comment by ishaan-jaff** [comment]
yes @krrishdholakia

**Comment by ishaan-jaff** [comment]
this was caused because of the "item exceeded size error" from langfuse. 

Fixed by bumping langfuse version: https://github.com/BerriAI/litellm/pull/5497
