### ISSUE TITLE
[Feature]: Cross-region inference profile AWS Bedrock

### ISSUE THREAD

**Issue by koenvaneijk** [BerriAI/litellm#5492]
### The Feature

AWS has enabled cross-region inference profile for AWS Bedrock in Europe.
https://aws.amazon.com/about-aws/whats-new/2024/08/amazon-bedrock-cross-region-inference/

However, LiteLLM does not yet work for the Inference Profile ID as instructed by AWS Bedrock cross-region inference docs:

litellm.exceptions.NotFoundError: litellm.NotFoundError: BedrockException - 
Bedrock HTTPX: Unknown provider=eu, 
model=eu.anthropic.claude-3-5-sonnet-20240620-v1:0

More information on:
https://aws.amazon.com/blogs/machine-learning/getting-started-with-cross-region-inference-in-amazon-bedrock/

### Motivation, pitch

If LiteLLM supports cross-region inference profile IDs for AWS Bedrock, response times can be improved for EU users.

### Twitter / LinkedIn details

@koenvaneijk

**Comment by ghost** [comment]
@koenvaneijk this already works for me 
<img width="1684" alt="Screenshot 2024-09-03 at 3 52 18 PM" src="https://github.com/user-attachments/assets/d6c73c47-75a6-426e-a40b-f99ec5e4971c">

ran in google colab on v`1.44.15` 
<img width="861" alt="Screenshot 2024-09-03 at 3 52 43 PM" src="https://github.com/user-attachments/assets/5a4526df-815d-4660-a51a-c967dc4f90db">

**Comment by ghost** [comment]
Will update our docs to reflect this
