### ISSUE TITLE
[Documentation]: input callback is not well explained 

### ISSUE THREAD

**Issue by yujonglee** [BerriAI/litellm#550]
### The Feature

`input_callback` is mentioned [here](https://docs.litellm.ai/docs/observability/sentry), but not [here](https://docs.litellm.ai/docs/observability/callbacks).

### Motivation, pitch

.

**Comment by ishaan-jaff** [comment]
@krrishdholakia do we support input_callbacks too ?

**Comment by ghost** [comment]
yea - we added for sentry + litedebugger. 

Will update callback docs - thanks @yujonglee 

What're you using input_callback for?

**Comment by ghost** [comment]
added to docs
