### ISSUE TITLE
[Bug]: Proxy config - model specific drop_params doesn't work

### ISSUE THREAD

**Issue by kresimirfijacko** [BerriAI/litellm#5501]
### What happened?

Version: ghcr.io/berriai/litellm:main-v1.44.14

I have problem setting 'drop_params' on specific model, which should be supported by documentation
https://docs.litellm.ai/docs/completion/drop_params

example proxy_config file:
`
model_list:
  - model_name: embedding
    litellm_params:
      model: bedrock/amazon.titan-embed-text-v1
      **drop_params: True # THIS DOESN'T WORK - either True or true**
      aws_access_key_id: os.environ/aws_access_key_id
      aws_secret_access_key: os.environ/aws_secret_access_key
      aws_region_name: os.environ/aws_region_name

litellm_settings:
  **drop_params: True  # THIS WORKS**

`

**Comment by patricksrail** [comment]
On a potentially related note, seeding a seed parameter for vertex/llama 3.1 405 errors out when with drop_params set to true. Same parameter works for azure / gpt-4 calls.

**Comment by ghost** [comment]
missed this @kresimirfijacko, i believe drop param support for embedding was added in a recent version - can you confirm this persists on latest?

**Comment by ghost** [comment]
Hi @kresimirfijacko unable to repro, this works for me as expected. 

## Output
<img width="1193" alt="Screenshot 2024-09-06 at 9 50 51 AM" src="https://github.com/user-attachments/assets/24ad6ed6-c2b7-421c-aad9-1a1557757ba1">

## Curl 

```bash
curl -L -X POST 'http://0.0.0.0:4000/embeddings' \
-H 'Authorization: Bearer sk-1234' \
-H 'Content-Type: application/json' \
-d '{"input": ["hello world"], "model": "embedding", "dimensions": 3}'
```

## Config 

```yaml
model_list:
  - model_name: embedding
    litellm_params:
      model: bedrock/amazon.titan-embed-text-v1
      drop_params: True 
```

**Comment by ghost** [comment]
@srail vertex ai llama3.1 works with seed param (see below) 
<img width="1150" alt="Screenshot 2024-09-06 at 10 05 28 AM" src="https://github.com/user-attachments/assets/0f10a25c-b2f9-42f4-b404-610c5d4cc9a0">

Vertex Llama3.1 is currently assumed to be completely openai compatible - https://github.com/BerriAI/litellm/blob/4626c5a365c725ed21292376bb1d9ba3a74fdfab/litellm/llms/vertex_ai_and_google_ai_studio/vertex_ai_partner_models/llama3/transformation.py#L52

as I can't find any docs on the complete list of vertex llama 3 param docs (e.g. their example on vertex shows max_tokens, but their playground has max_tokens, top_p, top_k and temperature)

**Comment by ishaan-jaff** [comment]
Hi @kresimirfijacko , curious do you use LiteLLM today ? If so, I'd love to hop on a call and learn how we can improve LiteLLM for you

- my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
- my linkedin if you prefer DMs: https://www.linkedin.com/in/reffajnaahsi/
