### ISSUE TITLE
[Bug]: bedrock_httpx.py does not support Cloudflare AI Gateway support via api_base

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#5504]
### What happened?

#4587 was working great for me, but was not merged. Instead, #5436 was merged, but this does not sign requests properly at all; it's signing with the wrong URL.. e.g. when api_base is set to a Cloudflare URL, we still *must* sign the original URL.

This went unnoticed because the requests were mocked and weren't actually checking to see if the signatures were valid or not.

https://github.com/BerriAI/litellm/pull/5436/commits/1d3af668b5c2731771dd01b85b8924ecc12c9938#r1743876736

### Relevant log output

```
{"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."}
```

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by ghost** [comment]
Oh - what are we doing wrong in our current implementation? 

https://github.com/BerriAI/litellm/blob/be3c7b401ef69297247fa56aa8ff07549e3451b2/litellm/llms/bedrock/chat.py#L731

**Comment by Manouchehri** [comment]
I'll try to fix it, one moment.
