### ISSUE TITLE
[Feature]: Datadog config - allow setting dev, prod, staging environment 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#5507]
### The Feature

> In the payload LiteLLM sends to DataDog, the source is currently hardcoded as “litellm”. (I believe right here: https://github.com/BerriAI/litellm/blob/be3c7b401ef69297247fa56aa8ff07549e3451b2/litellm/integrations/datadog.py#L134)

As a result, it is very difficult for us to differentiate which logs originate in dev and which ones originate in production. If there were a way to overwrite the source in our LiteLLM configuration, it’d make our DataDog logs have much more value for us.

### Motivation, pitch

-

**Comment by ghost** [comment]
duplicate #5508
