### ISSUE TITLE
[Typing]: temperature param is int, but it should be float

### ISSUE THREAD

**Issue by yujonglee** [BerriAI/litellm#551]
### The Feature

.

### Motivation, pitch

.

**Comment by HeetVekariya** [comment]
Can you locate the error in the codebase ?

**Comment by ghost** [comment]
@yujonglee where are you seeing this?

**Comment by ghost** [comment]
<img width="545" alt="Screenshot 2023-10-06 at 10 32 10 AM" src="https://github.com/BerriAI/litellm/assets/17561003/3156dc3d-f43e-4595-8014-63377ee32f68">

**Comment by yujonglee** [comment]
@HeetVekariya 

Sorry, I have old version of litellm installed. 
<img width="824" alt="Screenshot 2023-10-06 at 10 29 19 AM" src="https://github.com/BerriAI/litellm/assets/61503739/f07c2625-ea3a-4ff7-b761-7b334e17aa62">

it is inferred as int because of =1

It is not a problem with the latest version of litellm.
