### ISSUE TITLE
Add Amazon Code Whisperer

### ISSUE THREAD

**Issue by ngoiyaeric** [BerriAI/litellm#552]
### The Feature

Add Amazon Code Whisperer

### Motivation, pitch

its free

**Comment by ishaan-jaff** [comment]
@ngoiyaeric thanks for the issue, I could not find an API endpoint for CodeWhisperer: https://docs.aws.amazon.com/codewhisperer/latest/userguide/sagemaker-setup.html

Have you come across one ?

**Comment by ishaan-jaff** [comment]
looks like there's no API https://repost.aws/questions/QUIsQHA-01RYm8pNFtHeXC7g/do-we-offer-codewhisperer-service-as-an-api

**Comment by ghost** [comment]
Closing as it's not possible for us to call it. @ngoiyaeric was there another approach?

<img width="966" alt="Screenshot 2023-10-06 at 3 03 29 PM" src="https://github.com/BerriAI/litellm/assets/17561003/8d5dc4d3-8467-41d0-92e7-e0b9063392cc">
