### ISSUE TITLE
[Bug]: CERTIFICATE_VERIFY_FAILED error happened while calling get_azure_ad_token_from_oidc

### ISSUE THREAD

**Issue by gckjdev** [BerriAI/litellm#5522]
### What happened?

CERTIFICATE_VERIFY_FAILED error happened while calling get_azure_ad_token_from_oidc in the usage of Azure AD Token

    req_token = httpx.post(
        f"{azure_authority_host}/{azure_tenant_id}/oauth2/v2.0/token",
        data={
            "client_id": azure_client_id,
            "grant_type": "client_credentials",
            "scope": "https://cognitiveservices.azure.com/.default",
            "client_assertion_type": "urn:ietf:params:oauth:client-assertion-type:jwt-bearer",
            "client_assertion": oidc_token,
        },
    )

### Relevant log output

```shell
azure_ad_token = get_azure_ad_token_from_oidc (azure_ad_token)
 File "...\site-packages\litellm\llms\azure.py", line 410, in get_azure_ad_token_from_oidc
 req_token = httpx.post(...

 httpx.ConnectError : [SSL : CERTIFICATE_VERIFY_FAILED] certificate verify failed : self signed certificate in certificate chain (_ssl.c:1007)
```

**Comment by ishaan-jaff** [comment]
cc @Manouchehri you might have some more context on this

**Comment by gckjdev** [comment]
I can fix it locally by adding verify=False

req_token = httpx.post(
    f"{azure_authority_host}/{azure_tenant_id}/oauth2/v2.0/token",
    data={
        "client_id": azure_client_id,
        "grant_type": "client_credentials",
        "scope": "https://cognitiveservices.azure.com/.default",
        "client_assertion_type": "urn:ietf:params:oauth:client-assertion-type:jwt-bearer",
        "client_assertion": oidc_token,
    }, verify=False
)

**Comment by gckjdev** [comment]
Also can be fixed by

ssl_verify = os.getenv(
    "SSL_VERIFY",
    litellm.ssl_verify
)

req_token = httpx.post(
        f"{azure_authority_host}/{azure_tenant_id}/oauth2/v2.0/token",
        data={
        "client_id": azure_client_id,
        "grant_type": "client_credentials",
        "scope": "https://cognitiveservices.azure.com/.default",
        "client_assertion_type": "urn:ietf:params:oauth:client-assertion-type:jwt-bearer",
        "client_assertion": oidc_token,
        }, 
        verify=ssl_verify
)

**Comment by Manouchehri** [comment]
@gckjdev What network are you running LiteLLM in? This looks like you're subject to a MITM attack on your network with a self-signed cert, definitely not something we ideally want to see ever.

@ishaan-jaff Does LiteLLM have a config flag somewhere that is recommended for users to disable and/or provide custom SSL certs for upstream requests? If so, that would be a good idea for us to use.

**Comment by ghost** [comment]
looks like we just needed this request to be handled by our HTTPHandler, which already supports this ssl_verify logic

**Comment by ishaan-jaff** [comment]
Hi @gckjdev, curious do you use LiteLLM Proxy in production today If so, I'd love to hop on a call and learn how we can improve LiteLLM for you

- my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
- my linkedin if you prefer DMs: https://www.linkedin.com/in/reffajnaahsi/
