### ISSUE TITLE
[Feature]: Tracking spend of Cohere rerank

### ISSUE THREAD

**Issue by weiyong1024** [BerriAI/litellm#5523]
### The Feature

Glad to see the support of cohere rerank api. As changing the calling part from cohere SDK to LiteLLM, shall LiteLLM also support spending tracking into existing dashboard. So that we do not need to maintain the according logic on our own.

### Motivation, pitch

Spend tracking is very sensitive for application based on LLM.

### Twitter / LinkedIn details

https://www.linkedin.com/in/yong-wei-0a1383167/

**Comment by ishaan-jaff** [comment]
yes @weiyong1024 - we will add this. Do you use it through the LiteLLM Proxy server or python sdk ?

**Comment by ishaan-jaff** [comment]
done https://github.com/BerriAI/litellm/pull/5573

**Comment by weiyong1024** [comment]
Thanks for the work!

**Comment by ishaan-jaff** [comment]
Hi @weiyong1024 , curious do you use LiteLLM Proxy in production today If so, I'd love to hop on a call and learn how we can improve LiteLLM for you

- my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
- my linkedin if you prefer DMs: https://www.linkedin.com/in/reffajnaahsi/

**Comment by realmorrisliu** [comment]
Hi @ishaan-jaff, I’m trying to use this new feature, but I’m unsure how to configure the Cohere rerank models to track spend. Could you please provide detailed documentation or instructions on how to properly set up spend tracking for Cohere rerank? It would be really helpful to have the correct steps or configuration guidelines for usage.

Thanks in advance!

**Comment by ishaan-jaff** [comment]
here you go @realmorrisliu  https://docs.litellm.ai/docs/rerank#litellm-proxy-usage

**Comment by realmorrisliu** [comment]
> here you go @realmorrisliu https://docs.litellm.ai/docs/rerank#litellm-proxy-usage

Thanks!
