### ISSUE TITLE
[Feat] Add custom callbacks for input_callback + failure_callback

### ISSUE THREAD

**Issue by yujonglee** [BerriAI/litellm#553]
https://github.com/BerriAI/litellm/blob/035c65ed4a812dba09a89b1a17af8270f374161c/litellm/__init__.py#L6-L8

I guess it should be

```python
input_callback: List[Union[str, Callable]] = []
success_callback: List[Union[str, Callable]] = []
failure_callback: List[Union[str, Callable]] = []
```
?

Not sure for `input_callback` though

**Comment by ghost** [comment]
Currently we only have custom callbacks for `success_callback`. I think the underlying issue is have it implemented for all.

**Comment by ghost** [comment]
this is now done
