### ISSUE TITLE
[Bug]: Perplexity model w/ stream=true and return_citations=true doesn't work

### ISSUE THREAD

**Issue by amolpsingh** [BerriAI/litellm#5535]
### What happened?

You guys have done a great job building out support for so many different models and I am a huge fan of your product.

One issue is that when I set stream=True and return_citation=True, the [returned CustomStreamWrapper object](https://github.com/BerriAI/litellm/blob/main/litellm/utils.py#L8227) does not seem to include the citations. I checked by directly hitting the perplexity API and I can confirm that the output of a stream=true and return_citations=true does contain the with the citations in it. The response.text looks like:

data: {"id": "xxx", "model": "llama-3.1-sonar-small-128k-online", "created": 1725494279, "usage": {"prompt_tokens": 15, "completion_tokens": 1, "total_tokens": 16}, "citations": ["https://x.com/bizzabo?lang=ur", "https://apps.apple.com/my/app/bizzabo/id408705047", "https://www.bizzabo.com/blog/maximize-event-data-strategies-for-success"], "object": "chat.completion", "choices": [{"index": 0, "finish_reason": null, "message": {"role": "assistant", "content": "B"}, "delta": {"role": "assistant", "content": "B"}}]}

Would like to request for this fix to be made so that streaming can return citations like the underlying endpoint does.

### Relevant log output

```shell
<litellm.utils.CustomStreamWrapper object at 0x7af5bbfe46d0>

ModelResponse(id='a9864226-c7dd-470b-8ebd-96e2a3b60b1d', choices=[StreamingChoices(message={'role': 'assistant', 'content': 'Redis'}, finish_reason=None, index=0, delta=Delta(refusal=None, content='Redis', role='assistant', function_call=None, tool_calls=None), logprobs=None)], created=1725556070, model='perplexity/llama-3.1-sonar-small-128k-online', object='chat.completion.chunk', system_fingerprint=None)
```

### Twitter / LinkedIn details

https://x.com/amolsingh01

**Comment by ghost** [comment]
Hi @amolpsingh thanks for including the perplexity raw response. I'll add a test for this

**Comment by amolpsingh** [comment]
Thanks @krrishdholakia. Would appreciate if you can keep me updated as this issue gets resolved. Thanks!
