### ISSUE TITLE
[Bug]: Unsupported `|` type annotations in python3.9

### ISSUE THREAD

**Issue by matthewgrossman** [BerriAI/litellm#5545]
### What happened?

I'm running a python3.9 process and I'm trying to import some modules from `litellm`. Here's the reproduction:
```
» $(pyenv which python3.9) -m venv venv && source venv/bin/activate
» python --version                                     
Python 3.9.16
» pip install opentelemetry-sdk litellm
» python -c 'import litellm.integrations.opentelemetry'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mg/src/litellm_repro/venv/lib/python3.9/site-packages/litellm/integrations/opentelemetry.py", line 41, in <module>
    class OpenTelemetryConfig:
  File "/Users/mg/src/litellm_repro/venv/lib/python3.9/site-packages/litellm/integrations/opentelemetry.py", line 44, in OpenTelemetryConfig
    exporter: str | SpanExporter = "console"
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

This happens because python3.9 doesn't yet support type hints with `X | Y`: https://github.com/BerriAI/litellm/blob/8e25ba8de125136df64f17e8ca2a00d4f6afa0dd/litellm/integrations/opentelemetry.py#L44

If you want to use `X | Y` as opposed to `Union[X, Y]` in a backwards compatible way, you can insert `from __future__ import annotations` at the top of the file. However, this example module doesn't have that line, so we get this error.

In my mind there's a few options:
1. Explicitly not support python versions <3.10. AFAICT, this project currently supports >3.8: [pyproject.toml](https://github.com/BerriAI/litellm/blob/main/pyproject.toml#L19)
2. Add `from __future__ import annotations` to relevant files
3. Use `Union[X, Y]` instead of `X | Y` where necessary

(2) is probably simplest in that it can be done with a quick `sed` or script, and it also seems that's what other projects like [pydantic](https://github.com/search?q=repo%3Apydantic%2Fpydantic%20from%20__future__&type=code) do.

**Comment by ishaan-jaff** [comment]
fixed here @matthewgrossman https://github.com/BerriAI/litellm/pull/5548

**Comment by matthewgrossman** [comment]
Thanks for the quick fix! If I run into this issue with other files in the future, would you recommend just submitting a PR with a similar fix?

Also, curious why you decided to use the Union as opposed to the __future__ approach?

**Comment by ishaan-jaff** [comment]
> would you recommend just submitting a PR with a similar fix?

We'd love a PR to test instaling / using litellm on python 3.9 - we do this for python 3.8 https://github.com/BerriAI/litellm/blob/b5349e97c739a85b5ebf83e7eeabe26c04094db1/.circleci/config.yml#L179C13-L179C19

**Comment by ishaan-jaff** [comment]
>  why you decided to use the Union

our codebase has `Union` used in several places, that seemed like the best approach

**Comment by ishaan-jaff** [comment]
Hi @matthewgrossman , curious do you use LiteLLM proxy in production ? If so, I'd love to hop on a call and learn how we can improve LiteLLM for you

- my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
- my linkedin if you prefer DMs: https://www.linkedin.com/in/reffajnaahsi/
