### ISSUE TITLE
[Bug]: cache does not support password protected Redis Clusters

### ISSUE THREAD

**Issue by Kakadus** [BerriAI/litellm#5552]
### What happened?

I try to use the litellm cache in redis cluster mode. However, my cluster is protected by a password. There is no way to set the password for the `RedisCuster` client which is created by litellm:

All provided redis cluster parameter keys are filtered via the `_get_redis_cluster_kwargs()` function. It uses `inspect.getfullargspec` to retrieve the constructor arguments. However, this is not the complete list of supported arguments, as the majority of the arguments of `RedisCluster` are passed via `**kwargs`[1]. These parameters are not detected by `inspect.getfullargspec`.

With the `password` parameter, exactly this is the case and litellm filters it out before passing the rest to `RedisCluster`.

An alternative to manually building a list of supported arguments is to use `cleanup_kwargs` from `redis.cluster` directly.5

### Relevant log output

```shell
File "/app/.venv/lib/python3.12/site-packages/litellm/router.py", line 307, in __init__
    redis_cache = RedisCache(**cache_config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/caching.py", line 239, in __init__
    self.redis_client = get_redis_client(**redis_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/_redis.py", line 159, in get_redis_client
    return redis.RedisCluster(startup_nodes=new_startup_nodes, **cluster_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/redis/cluster.py", line 632, in __init__
    self.nodes_manager = NodesManager(
                         ^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/redis/cluster.py", line 1332, in __init__
    self.initialize()
  File "/app/.venv/lib/python3.12/site-packages/redis/cluster.py", line 1598, in initialize
    raise RedisClusterException(
redis.exceptions.RedisClusterException: Redis Cluster cannot be connected. Please provide at least one reachable node: Authentication required.
```
```


### Twitter / LinkedIn details

_No response_

**Comment by ishaan-jaff** [comment]
done here @Kakadus https://github.com/BerriAI/litellm/pull/5579/commits/9a9c0e42eb6792478996f8b3fda5fd9b94a36fa6 

I tried using the `cleanup_kwargs` as you did in your PR but that did not work for me
