### ISSUE TITLE
[Bug]: support returned multiple response from multiple input for fireworks ai.completion()

### ISSUE THREAD

**Issue by WillyRL** [BerriAI/litellm#5558]
### What happened?

I found that the response returned is different if using LiteLLM for multiple input on completions API, see the example below:

**Using LiteLLM**
> prompt=["halo", "hi", "halo", "hi"],
> text='Hello! Why are you saying "halo" and "hi" back and forth?')

**Direct hit to the fireworks**
> response = client.completions.create(
>    prompt=["halo", "hi", "halo", "hi"],
>   model='llama-v3p1-8b-instruct',
> )
>
>  choices=[
>         CompletionChoice(finish_reason='length', index=0, logprobs=None, text='" as the reference image.\nIf you want to create an image that shows the'),
>         CompletionChoice(finish_reason='length', index=1, logprobs=None, text=' echang.\n* (kategorisasi: jenis obat penghilang r'),
>         CompletionChoice(finish_reason='length', index=2, logprobs=None, text=' density profiles, which in turn affect the formation of central cluster galaxies.\n\n\\item'),
>         CompletionChoice(finish_reason='length', index=3, logprobs=None, text=" echang I can't find any evidence of a movie titled &quot;The Return")
>     ],

The expected response it should returned multiple response from multiple input instead of appending it as single sentence input.

**Comment by ghost** [comment]
Fixed with https://github.com/BerriAI/litellm/commit/67b8043e640504f3bd96f905c34ed807b4724451

**Comment by ghost** [comment]
Curious @WillyRL why use litellm for fireworks ai text completions?

**Comment by WillyRL** [comment]
> Curious @WillyRL why use litellm for fireworks ai text completions?

Hi @krrishdholakia, We can't just rely on fireworks, we need to load balance multiple providers.
