### ISSUE TITLE
Add "Amazon Titan Text Premier" in "model_prices_and_context_window.json"

### ISSUE THREAD

**Issue by henninglebbaeus** [BerriAI/litellm#5560]
Source: [AWS Bedrock Pricing](https://aws.amazon.com/bedrock/pricing/)

We need to update both [model_prices_and_context_window.json](https://github.com/BerriAI/litellm/blob/b5349e97c739a85b5ebf83e7eeabe26c04094db1/model_prices_and_context_window.json) and [model_prices_and_context_window_backup.json](https://github.com/BerriAI/litellm/blob/b5349e97c739a85b5ebf83e7eeabe26c04094db1/litellm/model_prices_and_context_window_backup.json) to reflect the new model.

**Comment by ishaan-jaff** [comment]
Hi @henninglebbaeus , curious do you use LiteLLM today ? If so, I'd love to hop on a call and learn how we can improve LiteLLM for you

- my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
- my linkedin if you prefer DMs: https://www.linkedin.com/in/reffajnaahsi/
