### ISSUE TITLE
[Bug]: Bytes64-encoded api calls still failing with azure/gpt-4o

### ISSUE THREAD

**Issue by srail** [BerriAI/litellm#5584]
### What happened?

(Was not able to reopen https://github.com/BerriAI/litellm/issues/5515, apologies for creating a duplicate).

1.45.19 still seems to struggle with images. Note that I tested using gpt-4o (not mini). For convenience I'm including full log including call with encoded image. This exact call works on 1.43.12 but not 1.45.19, zero other changes. Given this exact call, are you seeing same error?

The test image I'm using is this one to keep it smalL: https://dummyimage.com/100/100/fff&text=Test+image

[Attached]([Image error.md](https://github.com/user-attachments/files/16911874/Image.error.md)) log with a successful and failed call with no changes other than package version.

**Comment by ghost** [comment]
This seems related to an api version issue.

**Comment by patricksrail** [comment]
@krrishdholakia Intuitively that sounds right, but which version worked for you? I didn't make any changes to API_VERSION between the two versions of litellm.

**Comment by ghost** [comment]
Just tried with `2024-07-01-preview`
