### ISSUE TITLE
[Bug]: Stop does not work with bedrock Mistral

### ISSUE THREAD

**Issue by eruniyule** [BerriAI/litellm#5592]
### What happened?

When using acompletion and "bedrock/mistral.mistral-large-2407-v1:0", using stop = ["stop sequence"] yields a validationexception error

### Relevant log output

```shell
{'status_code': 400, 'headers': {':exception-type': 'validationException', ':content-type': 'application/json', ':message-type': 'exception'}, 'body': b'{"message":"The model returned the following errors: Validation Error"}'
```

**Comment by ghost** [comment]
Fixed here - https://github.com/BerriAI/litellm/pull/5602/commits/32a8d137a0f8bbe211f4f35dee702ef13cfee263

@eruniyule 

Curious, how're you using litellm proxy today?
