### ISSUE TITLE
Encountered an error when running ‘appworld run react_deepseekcoder_test_normal‘.

### ISSUE THREAD

**Issue by Yingnan1234** [BerriAI/litellm#5594]
<img width="537" alt="issue" src="https://github.com/user-attachments/assets/9c1f9e92-21c5-493c-9d1b-e69173b08521">

Hello, I followed the instructions in the README to run pip install appworld[experiments] and set the OPENAI_API_KEY in the environment variables. However, I am still encountering this error. Could you please help me understand why this is happening?

**Comment by ghost** [comment]
wrong repo - it looks like appworld is using litellm
