### ISSUE TITLE
Pydantic V2 'underscore_attrs_are_private'

### ISSUE THREAD

**Issue by linuxreitt** [BerriAI/litellm#5596]
I'm sorry if I'm just blind but I can't seem to find anything to help me solve this warning:

litellm --model ollama/llama3.1
/home/<user>/anaconda3/envs/litellm/lib/python3.11/site-packages/pydantic/_internal/_config.py:334: UserWarning: Valid config keys have changed in V2:
* 'underscore_attrs_are_private' has been removed
  warnings.warn(message, UserWarning)
INFO:     Started server process [44383]
INFO:     Waiting for application startup.

#------------------------------------------------------------#
#                                                            #
#           'I get frustrated when the product...'            #
#        https://github.com/BerriAI/litellm/issues/new        #
#                                                            #
#------------------------------------------------------------#

 Thank you for using LiteLLM! - Krrish & Ishaan

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new

INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:4000 (Press CTRL+C to quit)

**Comment by ishaan-jaff** [comment]
picking this up

**Comment by CyanideByte** [comment]
I ran into this too when i was using OpenInterpreter.
Made a PR for it here: https://github.com/BerriAI/litellm/pull/5635

**Comment by ishaan-jaff** [comment]
fixed
