### ISSUE TITLE
[Bug]: "litellm.BadRequestError: LLM Provider NOT provided" from litellm.cost_calculator.py::response_cost_calculator

### ISSUE THREAD

**Issue by okhat** [BerriAI/litellm#5597]
### What happened?

Thanks for the awesome library. The error is easy to reproduce:

```python
import os 
import litellm

os.environ["DATABRICKS_API_KEY"] = token
os.environ["DATABRICKS_API_BASE"] = url

from litellm.caching import Cache
litellm.cache = Cache(disk_cache_dir=".litellm_cache", type="disk")

model, messages = 'databricks/databricks-dbrx-instruct', [{'role': 'user', 'content': 'What is 2+2?'}]
litellm.completion(model=model, messages=messages) # works fine
litellm.completion(model=model, messages=messages) # breaks because this is a cache hit
```

### Relevant log output

The second line produces a `Cache Hit!` when verbose, then errs:
```
06:47:07 - LiteLLM:WARNING: cost_calculator.py:834 - litellm.cost_calculator.py::response_cost_calculator - Returning None. Exception occurred - litellm.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=dbrx-instruct-071224
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers/nTraceback (most recent call last):
  File "/opt/anaconda3/envs/jun2024_py310/lib/python3.10/site-packages/litellm/cost_calculator.py", line 814, in response_cost_calculator
    response_cost = completion_cost(
  File "/opt/anaconda3/envs/jun2024_py310/lib/python3.10/site-packages/litellm/cost_calculator.py", line 744, in completion_cost
    raise e
  File "/opt/anaconda3/envs/jun2024_py310/lib/python3.10/site-packages/litellm/cost_calculator.py", line 725, in completion_cost
    ) = cost_per_token(
  File "/opt/anaconda3/envs/jun2024_py310/lib/python3.10/site-packages/litellm/cost_calculator.py", line 159, in cost_per_token
    _, custom_llm_provider, _, _ = litellm.get_llm_provider(model=model)
  File "/opt/anaconda3/envs/jun2024_py310/lib/python3.10/site-packages/litellm/litellm_core_utils/get_llm_provider_logic.py", line 492, in get_llm_provider
    raise e
  File "/opt/anaconda3/envs/jun2024_py310/lib/python3.10/site-packages/litellm/litellm_core_utils/get_llm_provider_logic.py", line 469, in get_llm_provider
    raise litellm.exceptions.BadRequestError(  # type: ignore
litellm.exceptions.BadRequestError: litellm.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=dbrx-instruct-071224
```

I don't get errors with OpenAI models. I don't get errors if I turn off the caching. If you rerun the whole thing, the first `completion` request will crash now, due to the cache hit.

(Incidentally, why should `cost_calculator.py` crash the program anyway? I'd rather get a warning rather than an error out of failure to calculate cost.)

### Context

We're trying to make DSPy 2.5 rely almost entirely on LiteLLM for LM clients. Fantastic work! This is a (simple) blocker at the moment.

**Comment by ishaan-jaff** [comment]
picking this up

**Comment by ghost** [comment]
> (Incidentally, why should cost_calculator.py crash the program anyway? I'd rather get a warning rather than an error out of failure to calculate cost.)


agreed - it shouldn't. Will see what's happening.

**Comment by ghost** [comment]
hmm, i see error logs, but the calls seem to work fine

**Comment by ghost** [comment]
<img width="1694" alt="Screenshot 2024-09-09 at 3 18 05 PM" src="https://github.com/user-attachments/assets/c29a0c9f-6ba4-4cba-b2e4-cfe3c3af71e1">

**Comment by ghost** [comment]
Confirmed on colab - this works (doesn't fail call) - just produces a lot of error logs 
<img width="1662" alt="Screenshot 2024-09-09 at 3 20 00 PM" src="https://github.com/user-attachments/assets/887e67ca-d574-4ef3-bdeb-d6e3a421634d">

**Comment by okhat** [comment]
Thank you!! What if you don’t change my cache type?

**Comment by ghost** [comment]
works - just a lot of error logs 
<img width="1660" alt="Screenshot 2024-09-09 at 3 29 44 PM" src="https://github.com/user-attachments/assets/f9bfd3fb-3265-409f-8876-450afc4a97d7">

**Comment by ghost** [comment]
@okhat this error is caused because databricks returns a different model name (`dbrx-instruct-071224`) to the one passed in (`databricks-dbrx-instruct`) 

Would you prefer if we return the model name passed in instead? (can attach raw model name as a hidden param)

**Comment by ghost** [comment]
Adding a handler in cost calculation to treat models with `dbrx-instruct-*` as `databricks-dbrx-instruct`

**Comment by okhat** [comment]
Thank you for the great and super fast help, @krrishdholakia and @ishaan-jaff !

> Would you prefer if we return the model name passed in instead? 

That sounds reasonable to me! But you know better about the current LiteLLM patterns. As long as things work correctly and don't raise errors/warnings, I'm happy.

**Comment by okhat** [comment]
Btw the issue isn’t only about dbrx-instruct. It applies to other models like llama
