### ISSUE TITLE
Add support for AWS bedrock

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#56]

**Comment by Div-Infinity** [comment]
+1

**Comment by ishaan-jaff** [comment]
+1 heard this from another user yesterday

**Comment by ishaan-jaff** [comment]
@Div99 just saw your +1 on this - will get it done asap

**Comment by ishaan-jaff** [comment]
@Div99 
- is there a specific AWS bedrock LLM you're using? 
- we're waiting on AWS to give us access to bedrock, can you help us with testing our bedrock integration?

**Comment by ishaan-jaff** [comment]
Here's the bedrock commit: https://github.com/BerriAI/litellm/commit/2bf9ee4ecfe9625bfa76c415685464b2f132b573

**Comment by ghost** [comment]
@Div99 please re-open if this didn't solve your issue
