### ISSUE TITLE
[Feature]: Add Additional Provider Prefixed Entries for Anthropic and OpenAI in the Model cost JSON

### ISSUE THREAD

**Issue by ColeMurray** [BerriAI/litellm#5608]
## Context 
In the current model pricing json, https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json, most providers are prefixed such as "azuire/claude".

Anthropic and OpenAI models are not prefixed this way, and have a model only name https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json#L14

This creates users of liteLLM to special case model handling, where sometimes it may have the provider, and other times it does not.

## Feature request 
To simplify this and be backwards compatible, add openai/gpt-* and anthropic/claude-* entries

### Motivation, pitch

We are experiencing this issue in the OpenHands repository when checking which models have vision enabled
https://github.com/All-Hands-AI/OpenHands/issues/3792

### Twitter / LinkedIn details

@_colemurray

**Comment by ColeMurray** [comment]
@ishaan-jaff @krrishdholakia , it looks like both of you are active within the repo. Thoughts on this?
Happy to make the change if onboard.

**Comment by ghost** [comment]
@ColeMurray happy to help here. can you share your client code where the issue is caused? there's an entry in the dictionary called `litellm_provider` which can be used to identify the model. 

Adding multiple copies of the same model is undesirable as it makes it harder to maintain over time

**Comment by ColeMurray** [comment]
Thanks Krish,

Can you provide a code reference link to the mentioned parameter?

Sure, the flow is a bit tricky to track as it spans the frontend and backend, but will send over the relevant snippets.

The specific call of interest is failing here: https://github.com/All-Hands-AI/OpenHands/blob/main/openhands/llm/llm.py#L458

where `self.config.model` is `anthropic/claude-3-5-sonnet-20240620`

This is being sent from the frontend via a model selector here:
https://github.com/All-Hands-AI/OpenHands/blob/main/frontend/src/components/modals/settings/ModelSelector.tsx#L53

which is joining the provider and model name. This is by-design as other providers used within the system are following the provider/model_name pattern, similar to the non-OAI/non-anthropic models within the model_cost.json file

There's some contextually useful discussion going on here: https://github.com/All-Hands-AI/OpenHands/pull/3773, but most is not relevant to litellm.

We'd prefer to not special case to handle these two models providers due to the differing patterns. I also see the perspective of the litellm team, as maintaining duplicate config entries is asking for future pain / maintainability issues.

**Comment by ghost** [comment]
Oh! @ColeMurray have you tried the `get_model_info()` function? 

It handles this scenario already 

I believe `supports_vision` is the only one missing get_model_info support 

i can add it tomorrow if you can confirm for me it solves your problem - https://github.com/BerriAI/litellm/blob/98c34a7e27892d367e507980b6a144d380337d4f/litellm/utils.py#L2196

**Comment by ghost** [comment]
example usage - https://github.com/BerriAI/litellm/blob/98c34a7e27892d367e507980b6a144d380337d4f/litellm/utils.py#L2108

custom_llm_provider is an optional param here

**Comment by ColeMurray** [comment]
Yes, this looks like it would solve the issue as the underlying get_llm_provider call will resolve the model and custom_provider with `claude-..` and `anthropic` 

and handle correctly here to retrieve the model info post-split

https://github.com/BerriAI/litellm/blob/98c34a7e27892d367e507980b6a144d380337d4f/litellm/utils.py#L4830
https://github.com/BerriAI/litellm/blob/98c34a7e27892d367e507980b6a144d380337d4f/litellm/utils.py#L4921

**Comment by ColeMurray** [comment]
@krrishdholakia , looking at the issues it looks like o1 caused in influx and is probably higher priority.
I've made the changes here:
https://github.com/BerriAI/litellm/pull/5688

Note: I did not make the changes on the parallel function calling, as this is not currently supported within the ModelInfo model and wanted to keep out of the scope of this change.

**Comment by ColeMurray** [comment]
Issue resolved with merged PR. Released in https://github.com/BerriAI/litellm/releases/tag/v1.48.4
