### ISSUE TITLE
[Bug]: TPM and RPM accumulate with Redis Cache as keys don't have TTL

### ISSUE THREAD

**Issue by eladsegal** [BerriAI/litellm#5609]
### What happened?

When using the "Rate-Limit Aware v2 (ASYNC)" routing strategy (`usage-based-routing-v2`) with Redis cache, the TPM and RPM keys are persisted indefinitely, causing accumulation of their values as days go by.
This means that the capacity perceived by litellm per model decreases from day to day.

---
### Concrete Example
TPM and RPM are saved in the Redis cache per model ID and per minute (in the format of HH-MM), such that the relevant keys for some model are `{model_id}:tpm:{minute}` and `{model_id}:rpm:{minute}`.
Starting with a fresh cache, at 10:37:00 for model X we will have 0 TPM and RPM and no key.
With the first successful request the keys `X:tpm:10-37` and `X:rpm:10-37` will be set.
As more requests complete, the values will be updated. Let's assume that by the end of the minute we have:
```
# Day 0
X:tpm:10-37 = 70000
X:rpm:10-37 = 1000
```

On the next day when we get to time 10:37 again, the first request won't reset the values for the keys, but will add on top of the values from the day before.
This means that if the TPM rate limit for model X is 120k TPM, litellm will think we have only 50k TPM left, and if we need 70k TPM, we will incorrectly get rate limit errors.
From this point onwards we won't be able to make requests at all to the model at 10:37.
```
# Day 1, Day 2, Day 3, ..
X:tpm:10-37 = 120000
X:rpm:10-37 = 1700
```  

---

## Solution
A quick solution would be to add a 60 seconds TTL to the keys.
However, a better solution should be considered overall - the current implementation is sub-optimal as providers don't use timestamp to keep track of the rate limits, but a sliding window (OpenAI has a window of 60 seconds, Azure has a window of 10 seconds).

**Comment by ghost** [comment]
hmm i see us setting ttl already https://github.com/BerriAI/litellm/blob/ce5182710ff961ee6d424c4de8c68ff317f7072b/litellm/router_strategy/lowest_tpm_rpm_v2.py#L305

**Comment by ghost** [comment]
which version of litellm are you on? @eladsegal

**Comment by ghost** [comment]
testing to confirm caching works as expected

**Comment by ghost** [comment]
> However, a better solution should be considered overall - the current implementation is sub-optimal as providers don't use timestamp to keep track of the rate limits, but a sliding window (OpenAI has a window of 60 seconds, Azure has a window of 10 seconds).

Agreed. We've begun the work on this by passing through the azure/openai response headers, and already begun using this in the cooldown logic.

**Comment by ghost** [comment]
i see the issue, the ttl wasn't being passed correctly to the redis client

**Comment by ghost** [comment]
missing in `async_increment` on redis
