### ISSUE TITLE
[Bug]: Creating a user does not set "user_alias" nor "metadata"

### ISSUE THREAD

**Issue by Jacobh2** [BerriAI/litellm#5612]
### What happened?

According to the swagger docs, it should be possible to set an alias for an internal user:
![image](https://github.com/user-attachments/assets/90206ab1-2815-475c-b527-35b6495a82c0)

The API successfully accepts a JSON body that has this field set, but does not provide it back in the response. If connected to a Postgres database, this columnd is also not set, and the user has the value `null` for the column `user_alias`.

Furthermore: The "example value" shown in the swagger docs shows a `metadata` field, which _is_ returned in the API response when creating a user, but this is not saves in the database table either and doesn't even have a column for it.

Is `user_alias` and `metadata` valid properties of the user? If so, I would expect these to be set and properly stored. If not, they should be removed from the swagger docs description + example data.

**Comment by ghost** [comment]
I can repro the `user_alias` issue. But metadata seems to work fine 
<img width="1190" alt="Screenshot 2024-09-10 at 3 14 23 PM" src="https://github.com/user-attachments/assets/1adbdc9e-4db3-459d-9ca6-7f0f5105f3ae">

**Comment by ghost** [comment]
Fixed https://github.com/BerriAI/litellm/commit/554c5bd14576a72647be523969d46e62d0b1b037

Will be live in prod by EOD @Jacobh2 

---
Curious - how're you trying to use litellm proxy?

**Comment by Jacobh2** [comment]
Thanks for the quick response @krrishdholakia!

The response when creating a user correctly returns the metadata field provided in the body, but not when later getting eg all users from the user GET endpoint. 

So it seems like the metadata is simply echoed back during creation but not persisted.

**Comment by ghost** [comment]
> So it seems like the metadata is simply echoed back during creation but not persisted.

Can you check your db. The response in the `/user/new` is from the db not from the initial data.

**Comment by Jacobh2** [comment]
Ok I think I understand how it works: The `metadata` field is not a property of the user, but instead a property of the API key that is generated for the created user.

The confusion is that the metadata isn't something that is directly connected to the user (since the `LiteLLM_UserTable` db table does not have the column), but instead the info is just a proxy for the key creation.

For example for the "teams", it also has a metadata field but that one is a property of the team object.

**Comment by ishaan-jaff** [comment]
Hi @Jacobh2 , curious do you use LiteLLM today ? If so, I'd love to hop on a call and learn how we can improve LiteLLM for you

- my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
- my linkedin if you prefer DMs: https://www.linkedin.com/in/reffajnaahsi/

**Comment by ishaan-jaff** [comment]
@Jacobh2  - `metadata` added to Users here: https://github.com/BerriAI/litellm/pull/5856 

Would love to hop on a call with you and learn how we can improve LiteLLM for you

**Comment by Jacobh2** [comment]
@ishaan-jaff: How will the `metadata` for Users work? Will the current user endpoint take the `metadata` and now put it in the User table instead of the table holding the tokens? Or will there be a new property in the API endpoint?
