### ISSUE TITLE
[Bug]: Tool-calling doesn't seem to work with Ollama

### ISSUE THREAD

**Issue by aantn** [BerriAI/litellm#5617]
### What happened?

Tool calling isn't working for me with Ollama (it technically works but all the tool parameters are hallucinated), and I'm wondering if its because I didn't call `litellm.register_model`. The docs are unclear on if this is actually necessary or if just calling the model without it will work.

Here is what the docs say:
```
## [OPTIONAL] REGISTER MODEL - not all ollama models support function calling, litellm defaults to json mode tool calls if native tool calling not supported.

# litellm.register_model(model_cost={
#                 "ollama_chat/llama3.1": { 
#                   "supports_function_calling": true
#                 },
#             })
```

[...And supposedly Ollama itself supports tool calling](https://ollama.com/blog/tool-support), yet when using Ollama with HolmesGPT (which uses LiteLLM) [via the instructions here](https://github.com/robusta-dev/holmesgpt/blob/154c910b87d48ab87b7ba124de847b629b970a01/README.md#getting-an-api-key) then all the tool (function) parameters that Ollama returns are hallucinations.

Is it necessary to do something specific to get this working? I'm on the HolmesGPT team and we can update the way that we use LiteLLM if necessary to make this work? Or is this just broken and Ollama technically supports tool calling but in practice it hallucinates tool parameters regularly?

**Comment by ghost** [comment]
@aantn unable to repro the issue. this works fine for me. Testing with the basic openai example - 

<img width="1142" alt="Screenshot 2024-09-10 at 3 03 54 PM" src="https://github.com/user-attachments/assets/f8a3c082-a526-4153-86b2-7c497721525c">

Response
```
{
    "id": "chatcmpl-e45cbee8-a7e4-4911-a642-8f2d23df46a7",
    "choices": [
        {
            "finish_reason": "stop",
            "index": 0,
            "message": {
                "content": "",
                "role": "assistant",
                "tool_calls": [
                    {
                        "function": {
                            "arguments": "{\"location\": \"Boston, MA\", \"unit\": \"fahrenheit\"}",
                            "name": "get_current_weather"
                        },
                        "id": "1a38f8fb-d9b0-423d-a233-4f599834c54b",
                        "type": "function"
                    }
                ],
                "function_call": null
            }
        }
    ],
    "created": 1726005827,
    "model": "ollama_chat/llama3.1",
    "object": "chat.completion",
    "system_fingerprint": null,
    "usage": {
        "completion_tokens": 27,
        "prompt_tokens": 185,
        "total_tokens": 212
    }
}
```



Request
```
{
    "model": "ollama-llama-3.1",
  "messages": [
    {
      "role": "user",
      "content": "What's the weather like in Boston today?"
    }
  ],
  "tools": [
    {
      "type": "function",
      "function": {
        "name": "get_current_weather",
        "description": "Get the current weather in a given location",
        "parameters": {
          "type": "object",
          "properties": {
            "location": {
              "type": "string",
              "description": "The city and state, e.g. San Francisco, CA"
            },
            "unit": {
              "type": "string",
              "enum": ["celsius", "fahrenheit"]
            }
          },
          "required": ["location"]
        }
      }
    }
  ],
  "tool_choice": "auto"
}
```

**Comment by aantn** [comment]
@krrishdholakia what exactly are you testing there? Is that the LiteLLM proxy? If so, does the same apply to the LiteLLM client library?

**Comment by ghost** [comment]
the proxy uses the client library - so yes.
