### ISSUE TITLE
[Bug]: Message role always = assistant

### ISSUE THREAD

**Issue by yiyangnlp** [BerriAI/litellm#5621]
### What happened?

This line of code: https://github.com/BerriAI/litellm/blob/b1ecfe065c850dc77c1f5de5434a5f92d26343b6/litellm/types/utils.py#L328

Should be "role": role

**Comment by ghost** [comment]
This is not a bug. The role of the llm response message is always `assistant`. 

If you see a counterexample, please share it @yiyangnlp

**Comment by yiyangnlp** [comment]
If you do:
```
msg = Message(role="user", content="Hi! How can I help you today?")
print (msg)

>>> Message(role="assistant", content="Hi! How can I help you today?")
```
The role of msg is always "assistant"

Is this expected?

**Comment by yiyangnlp** [comment]
BTW, this makes Bedrock not work with Message. I had to use Dict instead of Message

**Comment by ghost** [comment]
Oh! i see what you mean - you're trying to use the Message object yourself

**Comment by yiyangnlp** [comment]
I now ran into this error that is related:

```
pydantic_core._pydantic_core.ValidationError: 1 validation error for Message
role
  Input should be 'assistant' [type=literal_error, input_value='system', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/literal_error
  ```
