### ISSUE TITLE
[Feature]: Allow user to drop params from proxy

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#564]
### The Feature

allow user to drop params from proxy. 
```
litellm --drop_params 
```

### Motivation, pitch

user-request

user trying to use ollama with librechat

**Comment by ghost** [comment]
cc: @mjtechguy

**Comment by ghost** [comment]
this is now pushed to the proxy - 3d809707c08f31ecb25619b058e0691f8d4e23b9

will update once this is in prod

**Comment by mjtechguy** [comment]
Tested with Librechat and it is working on LiteLLM `0.6.1` using the `--drop_params` argument. Thank you!

**Comment by ghost** [comment]
No worries
