### ISSUE TITLE
[Feature]: Hypercorn support (http/2 support)

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#5641]
### The Feature

Run proxy with hypercorn to support http/2 

### Motivation, pitch

Google Cloud Run caps request size to 32MB if http/1 used (uvicorn) but no limit on http/2 (hypercorn)

**Comment by Manouchehri** [comment]
So this seems like a good idea, but in practice, my team found the perf was _worse_ than HTTP/1.1. =( 

Definitely do some benchmarks before making HTTP/2 the default.

**Comment by ghost** [comment]
i was thinking of a similar implementation as gunicorn, where it's a cli arg e.g. `--run_hypercorn`

**Comment by ghost** [comment]
Do you have an alternative approach for larger requests to the proxy? @Manouchehri
