### ISSUE TITLE
[Bug]: I can't pass blob data to litellm

### ISSUE THREAD

**Issue by Gekko0114** [BerriAI/litellm#5644]
### What happened?

When I sent blob data via the gemini API, I got an error that this field doesn't include `role`.

```python

            file = genai.types.BlobDict(
                data=data
            )
            litellm.acompletion(messages=[file], model="gemini/gemini-pro")

```

### Relevant log output

```shell
app-1         |   File "/usr/local/lib/python3.12/site-packages/litellm/llms/vertex_ai_and_google_ai_studio/gemini/transformation.py", line 201, in _transform_system_message
app-1         |     if message["role"] == "system":
app-1         |        ~~~~~~~^^^^^^^^
app-1         | KeyError: 'role'
```

### Twitter / LinkedIn details

@Yamori_ds (twitter)

**Comment by ghost** [comment]
what is this @Gekko0114 

Your message isn't valid, there's no role set. 

litellm.completion is in the openai format. https://docs.litellm.ai/docs/completion/input
<img width="1044" alt="Screenshot 2024-09-12 at 8 26 59 AM" src="https://github.com/user-attachments/assets/99a0abea-5cc3-41fa-9d47-10090e6d8dba">


Did you look at the gemini docs? https://docs.litellm.ai/docs/providers/gemini

What was missing?

**Comment by Gekko0114** [comment]
My question is how to pass image data, audio data etc to litellm for using gemini api.

**Comment by Gekko0114** [comment]
Hi @krrishdholakia 
Could you let me know how to pass image or audio data? I couldn’t find how to do it

**Comment by ghost** [comment]
here's the example @Gekko0114 https://docs.litellm.ai/docs/providers/vertex#usage---pdf--videos--etc-files

**Comment by ghost** [comment]
use the `image_url` field

**Comment by ghost** [comment]
i'll add it to the gemini (google ai studio) docs too

**Comment by Gekko0114** [comment]
`image_url` doesn't work for my case, therefore I created a new issue https://github.com/BerriAI/litellm/issues/5674
