### ISSUE TITLE
[Bug]: `UserWarning: Valid config keys have changed in V2` in CI logs

### ISSUE THREAD

**Issue by jamesbraza** [BerriAI/litellm#5649]
### What happened?

https://github.com/BerriAI/litellm/commit/d1342c59917acdc633938d1ff4e36a95638e7b23 added in `underscore_attrs_are_private ` for Pydantic, which is removed.

### Relevant log output

```shell
/home/runner/work/ldp/ldp/.venv/lib/python3.12/site-packages/pydantic/_internal/_config.py:341: UserWarning: Valid config keys have changed in V2:
  * 'underscore_attrs_are_private' has been removed
```

**Comment by anderpru** [comment]
How to solve?
![image](https://github.com/user-attachments/assets/4e3ea1c5-e246-4112-9de5-a44790de4069)

**Comment by anjanesh** [comment]
For now I just suppressed the warning :
```
import warnings
warnings.filterwarnings("ignore", message=".*Valid config keys have changed in V2.*")

```
