### ISSUE TITLE
[Feature]: Have links to docs to litellm proxy 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#565]
### The Feature

link to the openai compatible server docs in the proxy

### Motivation, pitch

user request

user wasn't sure where in litellm docs to go for their docs

**Comment by ghost** [comment]
cc: @mjtechguy

**Comment by ghost** [comment]
this is pushed - c3e4c3e3f001593cbe554f0b65455c96e46f2db5

will update ticket once this is in prod

**Comment by ghost** [comment]
in prod with v`0.6.2`
