### ISSUE TITLE
[Bug]: end-user budget_duration doesn't seem to reset

### ISSUE THREAD

**Issue by krinlove99** [BerriAI/litellm#5651]
### What happened?

I have some questions. I have a budget_id, max_budget=1. The spend of a certain end_user is 2. When I set its budget_duration to 24h, why can't the end_user still request after 24h, and the spend is still 2. When calling "/customer/info?end_user_id=", the same spend is always returned.

### Relevant log output

```shell
{
    "user_id": "7b417efc-XXX",
    "blocked": false,
    "alias": null,
    "spend": 2.37654,
    "allowed_model_region": null,
    "default_model": null,
    "litellm_budget_table": null
}
```

**Comment by krinlove99** [comment]
I read the previous issue and set the budget_duration to 1m, and did not change the refresh frequency of the project (default). After a period of time (more than 10 minutes), it still returns a 400 error indicating that the limit has been exceeded. Does this mean that resetting the budget did not take effect?
 {
    "error": {
        "message": "Budget has been exceeded! Current cost: 2.37654, Max budget: 2.0",
        "type": "budget_exceeded",
        "param": null,
        "code": "400"
    }
}

**Comment by ghost** [comment]
hi @krinlove99 where's the budget id / max budget? your debug log doesn't seem to show that

**Comment by krrishdholakia** [comment]
similar to this - https://github.com/BerriAI/litellm/issues/5479

**Comment by krinlove99** [comment]
@krrishdholakia Yes, that's what I wanted to point out: the response for the litellm_budget_table parameter in the /customer/info?end_user_id= endpoint is always null, even though I can see in the database end_user table that I have set the budget_id and can find the corresponding parameter in the budget_table table.
Also, in the budget_table, the max_budget for that budget_id is 1, budget_duration=1m. 
I have tried everything I could find in the documentation and issues: including changing the server refresh rate in config.yaml to 1, and trying to change the bool value of disabling the reset task, and I also tried to re-pull the deployment based on the main-stable image, but nothing worked. And there is no output in the server logs that can be referenced. 
This is manifested by: when I call /customer/info?end_user_id=, it always returns the above content, and when calling the chat endpoint, it always prompts me 400, budget limit exceeded. This is very confusing. 
I'm sorry that I can't post a screenshot because I don't have a suitable device to open my database at this time.

**Comment by krinlove99** [comment]
I added the detailed parameters of the budget I talked about before：
The EndUserID information in the database ‘LiteLLM_EndUserTable’：
![image](https://github.com/user-attachments/assets/e8b3490f-ebee-412e-905b-f336e8b5bc17)

/budget/settings?budget_id=test0.01pd

```
[
    {
        "field_name": "max_budget",
        "field_type": "Float",
        "field_description": "Requests will fail if this budget (in USD) is exceeded.",
        "field_value": 2.0,
        "stored_in_db": true,
        "field_default_value": null,
        "premium_field": false,
        "nested_fields": null
    },
    {
        "field_name": "soft_budget",
        "field_type": "Float",
        "field_description": "Requests will NOT fail if this is exceeded. Will fire alerting though.",
        "field_value": null,
        "stored_in_db": true,
        "field_default_value": null,
        "premium_field": false,
        "nested_fields": null
    },
    {
        "field_name": "max_parallel_requests",
        "field_type": "Integer",
        "field_description": "Max concurrent requests allowed for this budget id.",
        "field_value": null,
        "stored_in_db": true,
        "field_default_value": null,
        "premium_field": false,
        "nested_fields": null
    },
    {
        "field_name": "tpm_limit",
        "field_type": "Integer",
        "field_description": "Max tokens per minute, allowed for this budget id.",
        "field_value": null,
        "stored_in_db": true,
        "field_default_value": null,
        "premium_field": false,
        "nested_fields": null
    },
    {
        "field_name": "rpm_limit",
        "field_type": "Integer",
        "field_description": "Max requests per minute, allowed for this budget id.",
        "field_value": null,
        "stored_in_db": true,
        "field_default_value": null,
        "premium_field": false,
        "nested_fields": null
    },
    {
        "field_name": "budget_duration",
        "field_type": "String",
        "field_description": "Max duration budget should be set for (e.g. '1hr', '1d', '28d')",
        "field_value": "1m",
        "stored_in_db": true,
        "field_default_value": null,
        "premium_field": false,
        "nested_fields": null
    }
]
``` 
/customer/info?end_user_id=7b417efc：
``` 
{
    "user_id": "7b417efc",
    "blocked": false,
    "alias": null,
    "spend": 2.004108,
    "allowed_model_region": null,
    "default_model": null,
    "litellm_budget_table": null
}
```

**Comment by gregoryboue** [comment]
Hi, i am facing the same issue with litellm 1.48.17.
The budget can't be used with customer (end user) because there are nether reset.
The `budget_reset_at` attribute fetch from `/budget/info` is always null

**Comment by gregoryboue** [comment]
Hi any news or workaround about this issue ? @krrishdholakia

**Comment by ghost** [comment]
hi, still no news about this issue ?

**Comment by superpoussin22** [comment]
@krrishdholakia  I also see the bug, any ETA ?

**Comment by ghost** [comment]
hi all, will aim to repro and push a fix for this by tomorrow

**Comment by ghost** [comment]
This seems to occur if `budget_duration` is passed via `/customer/new` endpoint, which was not previously supported. 

Adding support now.

**Comment by superpoussin22** [comment]
@krrishdholakia  you have the same issue for teams , if you can check also

**Comment by gregoryboue** [comment]
Hi,

I have wait for 1.52.15-stable to test the fix and that's not ok for me.
I create a budget from rest api endpoint with the following attributes :

```
 {
    "budget_id": "test-fix",
    "max_budget": 0.3,
   "budget_duration": "12m",
 }
```

Then i updated a customer to affect this budget with `customer/update` endpoint and i made request to raise BudgetExceededError.

I waited 20 minutes and i still have the BudgetExceededError.

Maybe is it links to this issue : https://github.com/BerriAI/litellm/issues/6601 so if the budget is not created through UI with daily/weekly/monthly values it is not working ?

I try to create a budget through UI with daily value and i will wait until tomorrow.

**Comment by gregoryboue** [comment]
Anyone has the same problem with version 1.52.15-stable ?
@krrishdholakia is it possible to check and reopen issue if it's not fixed ?

**Comment by gregoryboue** [comment]
@krrishdholakia ?

**Comment by gregoryboue** [comment]
I opened #7129
