### ISSUE TITLE
[Bug]: Tool responses to Anthropic models on Bedrock don't support content blocks 

### ISSUE THREAD

**Issue by mehertz** [BerriAI/litellm#5652]
### What happened?

Hi. When providing tool responses as a content blocks to LiteLLM, Bedrock will return an error:

```
BadRequestError: litellm.BadRequestError: BedrockException - b'{}'
```

As in, providing the following to LiteLLM as an input dictionary for a message does **not work**:

```
{
        'content': [{
            'text': '{"files":[],"page":"*","num_pages":0,"metadata":null}',
            'type': 'text'
        }],
        'name': 'list_files',
        'role': 'tool',
        'tool_call_id': 'tooluse_5RHhZgc4R0Kg30FH0E58Pg'
}
```

It sends the following to Bedrock as the payload:

```
{
	"role": "user",
	"content": [
		{
			"toolResult": {
				"content": [{
					"text": [{
						"text": "{\"files\ ":[],\"page\":\"*\",\"num_pages\":0,\"metadata\":null}",
						"type": "text"
					}]
				}],
				"toolUseId": "tooluse_5RHhZgc4R0Kg30FH0E58Pg"
			}
		}
	]
}
```

This looks pretty obviously wrong. However, that exact input dictionary does work when hitting OpenAI models on Azure. 

Note, the following input does work:

```
{
        'content': '{"files":[],"page":"*","num_pages":0,"metadata":null}',
        'name': 'list_files',
        'role': 'tool',
        'tool_call_id': 'tooluse_5RHhZgc4R0Kg30FH0E58Pg'
    }
```

For now we're just converting contents blocks to be strings as a workaround. I can provide the full payload to help debug if required, but think this is sufficient to reproduce.

If this is not a bug and this is just the wrong input format then happy to close - but would then like to know what the acceptable cross-llm input format for multimodal tool responses should be. 

Thanks

**Comment by ghost** [comment]
hi @mehertz can you share the full payload? It'll speed up debug on our end

**Comment by krrishdholakia** [comment]
Hi @mehertz i believe you might be on an older version of litellm. This works correctly for me on the latest version of litellm. 

Here's the test I ran: 

```python

from litellm.llms.prompt_templates.factory import _bedrock_converse_messages_pt


def test_bedrock_converse_translation_tool_message():
    litellm.set_verbose = True
    tool_msg = {
        "content": [
            {
                "text": '{"files":[],"page":"*","num_pages":0,"metadata":null}',
                "type": "text",
            }
        ],
        "name": "list_files",
        "role": "tool",
        "tool_call_id": "tooluse_5RHhZgc4R0Kg30FH0E58Pg",
    }

    messages = [tool_msg]

    translated_msg = _bedrock_converse_messages_pt(
        messages=messages, model="", llm_provider=""
    )

    print(translated_msg)

    assert translated_msg == [
        {
            "role": "user",
            "content": [
                {
                    "toolResult": {
                        "content": [
                            {
                                "text": [
                                    {
                                        "text": '{"files":[],"page":"*","num_pages":0,"metadata":null}',
                                        "type": "text",
                                    }
                                ]
                            }
                        ],
                        "toolUseId": "tooluse_5RHhZgc4R0Kg30FH0E58Pg",
                    }
                }
            ],
        }
    ]

```

## Translated Message
```bash
[{'role': 'user', 'content': [{'toolResult': {'content': [{'text': [{'text': '{"files":[],"page":"*","num_pages":0,"metadata":null}', 'type': 'text'}]}], 'toolUseId': 'tooluse_5RHhZgc4R0Kg30FH0E58Pg'}}]}]
```

**Comment by ghost** [comment]
nvm, able to repro issue when i make an actual bedrock call

**Comment by krrishdholakia** [comment]
> 						"text": "{\"files\ ":[],\"page\":\"*\",\"num_pages\":0,\"metadata\":null}",

it looks like this because of the json.dump() which happens before sending the data to bedrock

>pre-json dump data: {'messages': [{'role': 'user', 'content': [{'text': 'What do you know?'}, {'toolResult': {'content': [{'text': [{'text': '{"files":[],"page":"*","num_pages":0,"metadata":null}', 'type': 'text'}]}], 'toolUseId': 'tooluse_5RHhZgc4R0Kg30FH0E58Pg'}}]}], 'additionalModelRequestFields': {}, 'system': [{'text': 'Be a good bot!'}], 'inferenceConfig': {}}

> post-json dump data: {"messages": [{"role": "user", "content": [{"text": "What do you know?"}, {"toolResult": {"content": [{"text": [{"text": "{\"files\":[],\"page\":\"*\",\"num_pages\":0,\"metadata\":null}", "type": "text"}]}], "toolUseId": "tooluse_5RHhZgc4R0Kg30FH0E58Pg"}}]}], "additionalModelRequestFields": {}, "system": [{"text": "Be a good bot!"}], "inferenceConfig": {}}

**Comment by ghost** [comment]
found the issue - we expect content for a tool result to be a string

**Comment by ishaan-jaff** [comment]
Hi @mehertz , curious do you use LiteLLM today ? If so, I'd love to hop on a call and learn how we can improve LiteLLM for you

- my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
- my linkedin if you prefer DMs: https://www.linkedin.com/in/reffajnaahsi/
