### ISSUE TITLE
[Feature]: Support `max_completion_tokens` for OpenAI (`o1-*`)

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#5663]
### The Feature

https://platform.openai.com/docs/api-reference/chat/create#chat-create-max_completion_tokens

### Motivation, pitch

https://platform.openai.com/docs/guides/reasoning/controlling-costs

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by ishaan-jaff** [comment]
picking this up

**Comment by ishaan-jaff** [comment]
done here: https://github.com/BerriAI/litellm/pull/5691
