### ISSUE TITLE
[Feature]: Pass bytes data directly to gemini

### ISSUE THREAD

**Issue by Gekko0114** [BerriAI/litellm#5674]
### The Feature

I would like to pass bytes data directly to gemini, as shown below.

https://ai.google.dev/gemini-api/docs/audio?lang=python#inline-data

```python
# Initialize a Gemini model appropriate for your use case.
model = genai.GenerativeModel('models/gemini-1.5-flash')

# Create the prompt.
prompt = "Please summarize the audio."

# Load the samplesmall.mp3 file into a Python Blob object containing the audio
# file's bytes and then pass the prompt and the audio to Gemini.
response = model.generate_content([
    prompt,
    {
        "mime_type": "audio/mp3",
        "data": pathlib.Path('samplesmall.mp3').read_bytes()
    }
])

# Output Gemini's response to the prompt and the inline audio.
print(response.text)
```

### Motivation, pitch

Currently the `image_url` option helps uploading files. However it only works when the file is already uploaded to `gs` or hosted via `http`.

**Comment by ghost** [comment]
@Gekko0114 are you trying to use the litellm sdk or the proxy? 

If proxy, you can do it this way already via pass-through  - https://docs.litellm.ai/docs/pass_through/google_ai_studio

**Comment by Gekko0114** [comment]
Unfortunately I am using python sdk.

**Comment by ghost** [comment]
Hi @Gekko0114 this is already supported. Just encode the data to base64 and pass it in like this - 

```python
from pathlib import Path
import base64

litellm.set_verbose = True # 👈 See Raw call 

audio_bytes = Path("speech_vertex.mp3").read_bytes()
encoded_data = base64.b64encode(audio_bytes).decode("utf-8")
print("Audio Bytes = {}".format(audio_bytes))
model = "gemini/gemini-1.5-flash"
response = litellm.completion(
    model=model,
    messages=[
        {
            "role": "user",
            "content": [
                {"type": "text", "text": "Please summarize the audio."},
                {
                    "type": "image_url",
                    "image_url": "data:audio/mp3;base64,{}".format(encoded_data), # 👈 SET MIME_TYPE + DATA
                },
            ],
        }
    ],
)
```

**Comment by ghost** [comment]
just tested locally and can confirm it works 
<img width="1676" alt="Screenshot 2024-09-12 at 7 32 46 PM" src="https://github.com/user-attachments/assets/7d6d38d2-d073-4c95-8620-a863f2bf73bb">

**Comment by ghost** [comment]
> Unfortunately I am using python sdk.


curious - why are you using the sdk?

**Comment by Gekko0114** [comment]
Hi @krrishdholakia 
Thanks, I tried this, but didn't work. I got an error below.
```
python3.12/site-packages/litellm/llms/vertex_ai_and_google_ai_studio/vertex_ai_non_gemini.py", line 161, in _gemini_convert_messages_with_history
    image_url = element["image_url"]["url"]  # type: ignore
           
string indices must be integers, not 'str'
```

> curious - why are you using the sdk?

I've just started using litellm recently, so we don't plan to rely on it heavily like proxy.
We are using sdk for investigation purpose.

**Comment by ghost** [comment]
just added support for image_url as a str in this commit - https://github.com/BerriAI/litellm/pull/5658/commits/4e853dfbf2e2e27f12f486fcaa81278301252785

for now just do: 

```
messages=[
        {
            "role": "user",
            "content": [
                {"type": "text", "text": "Please summarize the audio."},
                {
                    "type": "image_url",
                    "image_url": {"url": "data:audio/mp3;base64,{}".format(encoded_data),} # 👈 SET MIME_TYPE + DATA
                },
            ],
        }
    ],
```

**Comment by ghost** [comment]
> We are using sdk for investigation purpose.

what are you investigating? @Gekko0114

**Comment by Gekko0114** [comment]
Ah I see, thanks for quick implementation! I will try it after releasing this version.

> what are you investigating?

I am investigating whether litellm is useful. Also I don't want to use proxy to avoid making my code too complex.
