### ISSUE TITLE
[Feature]: Proxy - User Management: If user assigned to a team don't show Default Team

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#5696]
### The Feature

- If team assigned don't show default team 
- If no team assigned then they should see Default Team

### Motivation, pitch

> We look deeper in the virtual key. We have an issue with the feature allowing anybody to create virtual if part of a team or not.  The feature allows users to create key under Default Team that cannot be recharge to the user's team.  is it possible to set the default Team with the bugdet to Zero or remove the possibilty to create a virtual if we are not part to a team ? Because, I think we cannot create user without a team id.

**Comment by ghost** [comment]
This sounds like a configurable flag

**Comment by ishaan-jaff** [comment]
picking this up
