### ISSUE TITLE
expose error types

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#57]
expose error types so people can try-except based off of them, instead of needing to import from openai 

<img width="716" alt="Screenshot 2023-08-07 at 11 28 33 AM" src="https://github.com/BerriAI/litellm/assets/17561003/d5afc0f2-2e96-4f10-b7f9-a407c9cb83b0">

**Comment by ghost** [comment]
1a4044091a2d122df1b8226b4f113840d01c4d32 attempts to deal with this.

**Comment by ghost** [comment]
closed as this is now done
