### ISSUE TITLE
[Feature]: Enable customize http request

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#570]
### The Feature

Enable user to customize http call for proxy use cases. 

<img width="696" alt="Screenshot 2023-10-09 at 4 10 58 PM" src="https://github.com/BerriAI/litellm/assets/17561003/88b13fd7-55c5-4183-9d85-570e6ffb35c9">

### Motivation, pitch

"One thing that would actually be completely necessary now that I'm looking through it is the ability to customize the request session. We do this [here](https://github.com/continuedev/continue/blob/815627b167e4bf06308b51c6756e33c36b17b631/continuedev/src/continuedev/libs/llm/__init__.py#L173), and without being able to do this we couldn't support people who have to go through a proxy, use custom certificates, etc."

**Comment by ghost** [comment]
pushed here: b50013386f024dfa56331eb75fab1a8b62f9d35d

This allows a user to control the ca_bundle_path and verify_ssl flag when calling an openai proxy server.

**Comment by ghost** [comment]
awaiting on nate to see if this solves his issue
