### ISSUE TITLE
[Feature]: Support Perplexity AI pplx-api

### ISSUE THREAD

**Issue by taomanwai** [BerriAI/litellm#572]
### The Feature

Can add Perplexity AI pplx-api as one of supported providers?

### Motivation, pitch

Perplexity AI pplx-api currently supports Mistral 7B, Llama 13B, **Code Llama 34B, Llama 70B**, and Replit 3b. 

I am working on a RAG for computer science academic papers and would like simultaneously supporting both Code Llama 34B and Llama 70B to be possible through Perplexity AI pplx-api.

Thanks in advance.

**Comment by ghost** [comment]
Hey @taomanwai isn't the perplexity ai api openai compatible? Why doesn't 

`litellm.completion(model="openai/<perplexity-model-name>, messages=[{"role":"user","content":"Hello world"}], api_base="https://<your-perplexity-api-base>"`

Work?

**Comment by ghost** [comment]
bump @taomanwai

**Comment by ghost** [comment]
We now have default support for perplexity - just pass in the api.perplexity.ai url in the api base and it'll work - without needing to explicitly set `openai/` to the model name

**Comment by ghost** [comment]
this is done
