### ISSUE TITLE
[Bug]: litellm_settings.upperbound_key_generate_params.duration configuration does not work as documented

### ISSUE THREAD

**Issue by martinskeem** [BerriAI/litellm#5720]
### What happened?

The documentation mentions that `duration` can be specified as an upperbound:

https://github.com/BerriAI/litellm/blob/5fb270a559ab9ac26a1c0328ff822c0cc04418f9/docs/my-website/docs/proxy/ui.md?plain=1#L72-L77

Yet, when specified, the `duration` upper bound is not effective. 

Possible cause:

`budget_duration` upper bound is implemented in the code, but it does not appear that `duration` is:

https://github.com/BerriAI/litellm/blob/5fb270a559ab9ac26a1c0328ff822c0cc04418f9/litellm/proxy/management_endpoints/key_management_endpoints.py#L158-L173

**To Reproduce**

1. Set `litellm_settings.upperbound_key_generate_params.duration` to `"14d"` in the configuration.
2. Reload configuration
3. Create a key with no duration or a duration which exceeds the specified upper bound duration.
4. Observe that the upperbound is not implemented.

**Expected behavior**
That the duration is always less than or equal to litellm_settings.upperbound_key_generate_params.duration. Either an error is returned by the API or the value is capped.

**Comment by ishaan-jaff** [comment]
picking this up today

**Comment by ishaan-jaff** [comment]
done here: https://github.com/BerriAI/litellm/pull/5727 

thanks for the detailed issue - really appreciate it
