### ISSUE TITLE
[Feature]: support dbrx client for getting credentials in spark notebooks 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#5732]
### The Feature

Allow users to use litellm in spark notebooks without needing to explicitly set api key / api base. 

### Motivation, pitch

Make it easier for users to use DSPy in databricks notebooks 

### Twitter / LinkedIn details

cc: @dbczumar

**Comment by ghost** [comment]
Creating a ticket to track the issue given recent conversations on https://github.com/BerriAI/litellm/pull/5725

**Comment by dbczumar** [comment]
Thanks @krrishdholakia :D

**Comment by ghost** [comment]
from linkedin conversation w/ @dbczumar looks like we might be able to use `w.config.authenticate()` to update the headers with the correct config

**Comment by dbczumar** [comment]
Filed https://github.com/BerriAI/litellm/pull/5733 to adopt `w.config.authenticate()` :). Thanks @krrishdholakia !

**Comment by ghost** [comment]
do you mean https://github.com/BerriAI/litellm/pull/5746 ? @dbczumar

**Comment by dbczumar** [comment]
> do you mean #5746 ? @dbczumar

Yeah #5746 :)

**Comment by ghost** [comment]
Closing as this is now live - https://github.com/BerriAI/litellm/commit/d46660ea0f4a4c888e618456363a04b60077c41f
