### ISSUE TITLE
[Bug]: VertexAI models parallel tool calling

### ISSUE THREAD

**Issue by hsleiman1** [BerriAI/litellm#5734]
### What happened?

Hello;
There is an issue with the parallel calling with Gemini, I see that you are still using google-cloud-aiplatform version 1.47.0, which is outdated.
Thank you;

**Comment by ghost** [comment]
> There is an issue with the parallel calling with Gemini, I see that you are still using google-cloud-aiplatform version 1.47.0, which is outdated.

We don't use google sdk for handling the calling portion - this is done via an httpx client to the vertex/google ai studio rest api - https://github.com/BerriAI/litellm/blob/ab153c3e8dab6be093eba3726ada19da176ee8cc/litellm/llms/vertex_ai_and_google_ai_studio/gemini/vertex_and_google_ai_studio_gemini.py#L1092


What is the issue you see? if you can share a minimal script for repro, that would be great.

**Comment by ghost** [comment]
Hey @hsleiman1 i just ran our test for parallel streaming + parallel tool calling for vertex_ai/gemini-1.5-pro

and they both passed for me. Closing as unable to repro for now, please feel free to reopen/bump me, if you have a minimal script for repro 

<img width="1671" alt="Screenshot 2024-09-27 at 5 48 14 PM" src="https://github.com/user-attachments/assets/7722e251-8aac-4159-950f-ab4be43142ff">
<img width="1705" alt="Screenshot 2024-09-27 at 5 48 23 PM" src="https://github.com/user-attachments/assets/bbb91f7b-bdd2-4968-a97c-a1ce26eb7fa9">


## Tests
https://github.com/BerriAI/litellm/blob/789ce6b7476cd5e92da81ed240005aca205c8d20/litellm/tests/test_function_calling.py#L56
https://github.com/BerriAI/litellm/blob/789ce6b7476cd5e92da81ed240005aca205c8d20/litellm/tests/test_streaming.py#L1538
