### ISSUE TITLE
[Feature]: Langchain / Smith Logging Integration doesn't appear to expose errors/metadata

### ISSUE THREAD

**Issue by andrewbolster** [BerriAI/litellm#5738]
### The Feature

It's tagged as 'community supported', but the [Langsmith Integration](https://docs.litellm.ai/docs/observability/langsmith_integration) doesn't appear to be logging errors or api-user metadata in the langchain view. 

### Motivation, pitch

While litellm is great for cost tracking, it would be beneficial to have centralised logging, altering, and feedback within langsmith (i.e. creating new data stores out of 'failed' or 'timed out' requests)

### Twitter / LinkedIn details

@bolster / https://www.linkedin.com/in/andrewbolster/

**Comment by ghost** [comment]
hmm i can see the user api key metadata in the langsmith metadata view 
<img width="751" alt="Screenshot 2024-09-17 at 9 10 50 AM" src="https://github.com/user-attachments/assets/14b64cd2-74c2-499e-8b18-b71de2c68b85">

**Comment by ghost** [comment]
Just tried on latest, and i still see user/api key metadata logged. What are you seeing? @andrewbolster 

<img width="1642" alt="Screenshot 2024-09-17 at 10 03 29 AM" src="https://github.com/user-attachments/assets/6b5546f8-6d71-4bfb-81a8-0e7551737d3e">

**Comment by ghost** [comment]
> logging errors

Will add error logging for langsmith
