### ISSUE TITLE
[Bug]: Docker Compose docs unclear in terms of config.yaml if NOT using DB

### ISSUE THREAD

**Issue by tidalvirus** [BerriAI/litellm#5739]
### What happened?

This seems to be in between a bug and a feature request, and I did a coin toss on reporting this as a bug rather than a feature request.

This setup caused me a fair bit of confusion that took me longer than I care to admit to work out - the documentation at https://docs.litellm.ai/docs/proxy/deploy for the docker compose setup, and the use of `config.yaml` was a bit confusing. I rarely use `docker run`, so I missed that `--config /app/config.yaml` in the `docker run` commands on the above page was missing in the [docker-compose.yaml](https://github.com/BerriAI/litellm/blob/main/docker-compose.yml) file.

It would likely be helpful to others if a sample docker-compose.yaml file had the following in it (commented out), so that others could see what to do if they were not using a DB. What do you think?

e.g. something like this:

```
  litellm:
[... snip ...]
    image: ghcr.io/berriai/litellm:main-stable
    #########################################
    ## Uncomment these lines to start proxy with a config.yaml file ##
    # volumes:
    #  - ./config.yaml:/app/config.yaml <<- this is missing in the docker-compose file currently
    # The below two are my suggestion
    # command:
    #  - "--config=/app/config.yaml"
    ##############################################
```

Side note - it was confusing not seeing any errors due to there not being any success or error that a config.yaml file was loaded when looking at `docker-compose logs litellm` - as I saw no errors, I didn't realise this was where the problem lay.

**Comment by ishaan-jaff** [comment]
Hi @tidalvirus  curious do you use LiteLLM Proxy in production today If so, I'd love to hop on a call and learn how we can improve LiteLLM for you

- my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
- my linkedin if you prefer DMs: https://www.linkedin.com/in/reffajnaahsi/

**Comment by tidalvirus** [comment]
> Hi @tidalvirus curious do you use LiteLLM Proxy in production today If so, I'd love to hop on a call and learn how we can improve LiteLLM for you

I’m actually just using it at home with Open WebUI (previously ollama) so the family can use multiple LLM models. Definitely not production. Good luck with the project, it’s kinda awesome :)
