### ISSUE TITLE
[Bug]: litellm.identify not setting end_user in Supabase integration

### ISSUE THREAD

**Issue by Raidus** [BerriAI/litellm#575]
### What happened?

I am setting 

```python
litellm.identify({"end_user": "krrish@berri.ai"})
```

but instead of `krrish@berri.ai` => `Hello world` is stored in the database

![image](https://github.com/BerriAI/litellm/assets/8803882/21f73bce-d91f-470f-971e-eb96fcc21701)

according to the docs: https://docs.litellm.ai/docs/observability/supabase_integration

**Comment by ishaan-jaff** [comment]
Hi @Raidus thanks for raising ! taking a look👀

**Comment by ghost** [comment]
Hey @Raidus - thanks for filing this! do you have a twitter/linkedin? would love to give a shoutout once we publish the fix

**Comment by ishaan-jaff** [comment]
Fixed,
@Raidus you can identify your users in the completion call itself like this - please let me know if you'd rather use `litellm.identify({"end_user": "krrish@berri.ai"})` happy to expose that interface too 

```python
response = completion(
  model="gpt-3.5-turbo", 
  messages=[{"role": "user", "content": "Hi 👋 - i'm openai"}],
  user="ishaan22" # identify users
) 
```

docs: https://docs.litellm.ai/docs/observability/supabase_integration

**Comment by ishaan-jaff** [comment]
waiting for a version bump: https://github.com/BerriAI/litellm/commit/6d81bcc248ece6dfbf63d092365c60fccb422c8a

**Comment by ishaan-jaff** [comment]
0.6.6 should have the fix @Raidus. lmk if it works for you

**Comment by ghost** [comment]
@Raidus did this work for you?

**Comment by ghost** [comment]
closing for now @Raidus please re-open if your issue isn't fixed

**Comment by ishaan-jaff** [comment]
Hi @Raidus thanks so much for your issue ! 

We're spending this week improving our logging integrations 

I'd love to get your feedback on LiteLLM. Do you have some time this week for a quick call? 

My [calendly](https://calendly.com/ishaan-berri/30min) for your convenience
