### ISSUE TITLE
[Feature]: Convert OpenAI list-content into open-source compatible string type

### ISSUE THREAD

**Issue by James4Ever0** [BerriAI/litellm#5755]
### The Feature

For some libraries calling OpenAI APIs, they will submit something like this:

```json
{"role": "user", "content": [{"type": "text", "text": "<text_1>"},{"type": "text", "text": "<text_2>"}]}
```

This means "content" can be of type `Union[str, dict, str]`.

LiteLLM will convert this into format below:

```json
[{"role": "user", "content": "<text_1>"}, {"role": "user", "content": "<text_2>"}]
```

Currently LiteLLM can only support "content" of type `str`.

### Motivation, pitch

https://github.com/yetone/avante.nvim/issues/600

**Comment by ghost** [comment]
Hi @James4Ever0 litellm supports content as a list of dictionaries as well. Where did you see the issue? 

https://github.com/BerriAI/litellm/blob/8600ec77042dacad324d3879a2bd918fc6a719fa/litellm/types/llms/openai.py#L348

**Comment by James4Ever0** [comment]
I use LiteLLM to proxy to VLLM.

https://docs.litellm.ai/docs/providers/vllm

In the VLLM server environment:

```
vllm version: 0.3.2
litellm version: 1.27.14
```

In the proxy LiteLLM environment:

```
litellm version: 1.46.6
```

So how about adding a flag like `--legacy` or `--text-only`, to do the conversion in the middle?

**Comment by ishaan-jaff** [comment]
Hi @James4Ever0 , thanks for using LiteLLM. Any chance we can hop on a call to learn how we can improve LiteLLM Proxy for you ? 

We’re planning roadmap and I’d love to get your feedback 

- my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
- my linkedin if you prefer DMs: https://www.linkedin.com/in/reffajnaahsi/

**Comment by James4Ever0** [comment]
Are you hiring? @ishaan-jaff Seen hundreds of similar comments in your repo since last year.

I don't like this kind of close-and-talk fasion. I am more of open-and-talk. Please open this issue again. @krrishdholakia
