### ISSUE TITLE
[Bug]: The 429 error code hides the real cause.

### ISSUE THREAD

**Issue by kmyczkowska-hypatos** [BerriAI/litellm#5764]
### What happened?

Hello,
Would it be possible to return the `529` error code (as originally provided by the vendor) instead of mapping it to `429`, which indicates the issue is on our side?

### Relevant log output

```shell
Error code: 429 - {'error': {'message': 'No deployments available for selected model, Try again in 60 seconds. Passed model=vertex-claude-3-5-sonnet. pre-call-checks=False, allowed_model_region=n/a, cooldown_list=[(\'...\', {\'Exception Received\': \'litellm.APIConnectionError: Server error \\\'529 Internal Server Error\\\' for url \\\'..../anthropic/models/claude-3-5-sonnet@
```

**Comment by ghost** [comment]
@kmyczkowska-hypatos if you bump to latest, this issue re: cooldowns is now fixed.

**Comment by ghost** [comment]
Please feel free to re-open / create a new issue, with minimal repro steps, if this persists
