### ISSUE TITLE
[Feature]: JSON can be passed to the Gemini API

### ISSUE THREAD

**Issue by Gekko0114** [BerriAI/litellm#5766]
### The Feature

When calling the Gemini API using Litellm, it is necessary to pass an API key. However, the raw Gemini API can also be called using JSON. Therefore, I would like to request that Litellm allows calling the Gemini API using JSON as well.

### Motivation, pitch

Written in the feature section

**Comment by ghost** [comment]
> However, the raw Gemini API can also be called using JSON

What does this mean? @Gekko0114 can you point to relevant docs here?

**Comment by Gekko0114** [comment]
I mean that Gemini can be called using GOOGLE_APPLICATION_CREDENTIALS.

```python
os.env["GOOGLE_APPLICATION_CREDENTIALS"] = "./google_credentials.json"
genai.GenerativeModel(
                model_name="xxx",
                generation_config="yyy",
                system_instruction="zzz",
            )
response = model.generate_content(messages)
```

**Comment by ghost** [comment]
this is already supported @Gekko0114 

If you're seeing an issue, can you please share it

**Comment by Gekko0114** [comment]
Really? Then I will try it
