### ISSUE TITLE
[Bug]: Docs don't appear to include the /fallback/login endpoint

### ISSUE THREAD

**Issue by andrewbolster** [BerriAI/litellm#5778]
### What happened?

Documentation doesn't currently show the fallback url for when you inadvertently mess up your SSO

Should probably go here https://docs.litellm.ai/docs/proxy/ui#setup-ssoauth-for-ui

### Twitter / LinkedIn details

@bolster / https://www.linkedin.com/in/andrewbolster/

**Comment by ishaan-jaff** [comment]
done: https://docs.litellm.ai/docs/proxy/ui#sign-in-with-username-password-when-sso-is-on 

<img width="761" alt="Screenshot 2024-09-18 at 4 43 29 PM" src="https://github.com/user-attachments/assets/be41aac7-5d53-47d6-8526-b10c350c9407">
