### ISSUE TITLE
[Bug]: Remove logprobs from response object

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#579]
### What happened?

Remove logprobs, it doesn't follow the openai format. This is causing issues for users trying to integrate litellm into repos. 
<img width="852" alt="Screenshot 2023-10-10 at 6 28 14 PM" src="https://github.com/BerriAI/litellm/assets/17561003/3fdd28d7-4c60-45d6-a3bd-d90591e80150">

Since the initial ask for adding log probs was also a user request, we could move it to being a private attribute similar to response_ms.

**Comment by ghost** [comment]
https://github.com/OpenBMB/ChatDev/pull/53#issuecomment-1756591369

**Comment by ghost** [comment]
wasn't able to repro - closing for now.
