### ISSUE TITLE
[Feature]: infer provider from api base

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#580]
### The Feature

User assumed we weren't working with perplexity because they didn't know to set `openai/` in front of the model name.
<img width="1105" alt="Screenshot 2023-10-10 at 8 42 31 PM" src="https://github.com/BerriAI/litellm/assets/17561003/445a00b1-8c5c-45c9-ac33-efbde9c161a9">

We can fix this by just maintaining a list of known openai compatible endpoints e.g. `api.perplexity.ai`

### Motivation, pitch

improve UX

**Comment by ghost** [comment]
pushed here for perplexity - d280a8c434023392bc13f5c562b8506276b3e480
