### ISSUE TITLE
[Bug]: Latest release broke virtual key creation

### ISSUE THREAD

**Issue by gamerXI1** [BerriAI/litellm#5820]
### What happened?

Error - Only enterprise users are allowed to add tags to Models.. when creating virtual key. 
  - cryptic message - even when using with Default Team 

### Relevant log output

```shell
error in UI does not register in debug logs.
```

**Comment by ishaan-jaff** [comment]
looking into this

**Comment by ishaan-jaff** [comment]
fixed https://github.com/BerriAI/litellm/pull/5826

**Comment by ishaan-jaff** [comment]
Hi @gamerXI1 , thanks for using LiteLLM. Any chance we can hop on a call to learn how we can improve LiteLLM Proxy for you ? 

We’re planning roadmap and I’d love to get your feedback 

- my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
- my linkedin if you prefer DMs: https://www.linkedin.com/in/reffajnaahsi/
