### ISSUE TITLE
[Bug]: Model Status Healthy |Curl works - But when called from application using litellm completions or openai completion - ServiceUnavailableError

### ISSUE THREAD

**Issue by gamerXI1** [BerriAI/litellm#5822]
### What happened?

Turned off everything - Single Pod deployment on kubernetes - No routing - No load Balancing. Still error when request takes longer.. 
looks like proxy is only working for request that responds within ms. 

### Relevant log output

```shell
│ {"message": "updated_value in failure call: {'current_requests': 0, 'current_tpm': 0, 'current_rpm': 0}", "level": "DEBUG", "timestamp": "2024-09-21T16:04:50.43 │
│ {"message": "async set cache: cache key: 93a430cc4eaf96ee37e96df994482658b8280dbb0398232fb3731e5ed393307e::2024-09-21-16-04::request_count; local_only: False; v │
│ {"message": "InMemoryCache: set_cache. current size= 12", "level": "DEBUG", "timestamp": "2024-09-21T16:04:50.438062"}                                           │
│ {"message": "inside _PROXY_failure_handler kwargs=", "level": "DEBUG", "timestamp": "2024-09-21T16:04:50.438168"}                                                │
│ {"message": "litellm.acompletion(model=together_ai/mistralai/Mixtral-8x22B-Instruct-v0.1)\u001b[31m Exception litellm.ServiceUnavailableError: ServiceUnavailabl │
│ {"message": "initial list of deployments: [{'model_name': 'mistralai/Mixtral-8x22B-Instruct-v0.1', 'litellm_params': {'api_key': 'REDACTED │
│ {"message": "retrieve cooldown models: []", "level": "DEBUG", "timestamp": "2024-09-21T16:04:50.450182"}                                                         │
│ {"message": "TracebackTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/litellm/llms/OpenAI/openai.py\", line 961, in acomple │
│ {"message": "Trying to fallback b/w models", "level": "DEBUG", "timestamp": "2024-09-21T16:04:50.473808"}                                                        │
│ {"message": "inside model fallbacks: [{}]", "level": "DEBUG", "timestamp": "2024-09-21T16:04:50.474773"}                                                         │
│ {"message": "retrieve cooldown models: []", "level": "DEBUG", "timestamp": "2024-09-21T16:04:50.490948"}                                                         │
│ {"message": "litellm.router.py::async_function_with_fallbacks() - Error occurred while trying to do fallbacks - list index out of range\nTraceback (most recent  │
│ {"message": "litellm.proxy.proxy_server.chat_completion(): Exception occured - litellm.ServiceUnavailableError: ServiceUnavailableError: Together_aiException -  │
│ {"message": "\u001b[1;31mAn error occurred: litellm.ServiceUnavailableError: ServiceUnavailableError: Together_aiException - Error code: 503 - {'error': {'messa │
│ {"message": "{\"event\": \"giveup\", \"exception\": \"\"}", "level": "INFO", "timestamp": "2024-09-21T16:04:50.496777"}                                          │
│ {"message": "Giving up chat_completion(...) after 1 tries (litellm.proxy._types.ProxyException)", "level": "ERROR", "timestamp": "2024-09-21T16:04:50.571296"}
```

**Comment by gamerXI1** [comment]
Service reachable test using curl. 

curl --location 'http://0.0.0.0:4000/v1/chat/completions' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer REDACTED' \
--data '{
  "model": "together_ai/mistralai/Mixtral-8x7B-Instruct-v0.1",
  "messages": [{"role":"user","content":"This is a test of logging into Langfuse, What is your purpose?"}],
  "temperature": 0.7,
  "max_tokens": 1000, "stream":False
}'
{"id":"8c6b49abfbf51757-IAD","choices":[{"finish_reason":"eos","index":0,"message":{"content":" I don't have the ability to log into Langfuse or any other websites, as I'm a text-based AI language model and don't have a physical interface or credentials to log in with. My purpose is to assist you by providing information, answering questions, and helping you with language-related tasks to the best of my ability. Is there a way I can help you with Langfuse or any other topic?","role":"assistant","tool_calls":null,"function_call":null}}],"created":1726934633,"model":"together_ai/mistralai/Mixtral-8x7B-Instruct-v0.1","object":"chat.completion","system_fingerprint":null,"usage":{"completion_tokens":90,"prompt_tokens":25,"total_tokens":115,"completion_tokens_details":null},"service_tier":null,"prompt":[]}%

**Comment by ghost** [comment]
> {"message": "litellm.proxy.proxy_server.chat_completion(): Exception occured - litellm.ServiceUnavailableError: ServiceUnavailableError: Together_aiException -  │



This looks like together ai raises a service unavailable error. 

> Error code: 503 - {'error': {'messa

i can't see what the entire 503 message raised is, but it looks like it's coming from the provider, not litellm. 

Closing as this doesn't currently look like a litellm issue. Please feel free to reopen/bump me if there's something i'm missing here.
