### ISSUE TITLE
[Bug]: Match OpenAI v1 Scheme for proxy

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#583]
### What happened?

Match openai v1 schema 
<img width="997" alt="Screenshot 2023-10-11 at 11 19 17 AM" src="https://github.com/BerriAI/litellm/assets/17561003/0b7f6f6a-dd81-4126-90d4-d66e12096ba0">

- https://github.com/danny-avila/LibreChat/issues/1026

cc: @mjtechguy

**Comment by ishaan-jaff** [comment]
i tried adding a /v1 to all our endpoints it basically broke things:

error:
```
127.0.0.1:53410 - "POST /chat/completions HTTP/1.1" 404 Not Found
```

**Comment by ishaan-jaff** [comment]
we added /v1 endpoints to this: https://github.com/BerriAI/litellm/commit/329d27d1fae61469f536e7eac0c00106c2a21020

**Comment by ishaan-jaff** [comment]
cc @mjtechguy
