### ISSUE TITLE
[Bug]: Groq - Tool / Function Calling Example throws function_call is not nullable error

### ISSUE THREAD

**Issue by timlrx** [BerriAI/litellm#5839]
### What happened?

Following the example provided in the [docs for groq tool usage](https://docs.litellm.ai/docs/providers/groq#groq---tool--function-calling-example) throws the following error:

```
litellm.exceptions.BadRequestError: litellm.BadRequestError: GroqException - Error code: 400 - {'error': {'message': "'messages.2' : for 'role:assistant' the following must be satisfied[('messages.2.function_call' : Value is not nullable)]", 'type': 'invalid_request_error'}}
```

Simple work around is to just update the docs pass back a dict without `function_call`. E.g:
```py
d = response_message.model_dump()
message.append({"role": d.get("role"), "tool_calls": d.get("tool_calls")})
 ```

Or you could consider modifying `Message` and not add `function_call` by default.

**Comment by ghost** [comment]
Looks like their api might've changed - will test and fix

**Comment by ghost** [comment]
able to repro
