### ISSUE TITLE
[Feature]: Add Ollama models to model list

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#586]
### The Feature

See: https://github.com/refstudio/refstudio/issues/578
<img width="918" alt="Screenshot 2023-10-11 at 11 54 24 AM" src="https://github.com/BerriAI/litellm/assets/17561003/180d4e04-3b77-417d-b7c7-2dc1298414a0">

### Motivation, pitch

improve UX

**Comment by ishaan-jaff** [comment]
done: https://github.com/BerriAI/litellm/commit/d09486f93b2af506a928ecacc4aba102b33aa46a

**Comment by ishaan-jaff** [comment]
another thing we can do for refstudio ollama 

" when a user enters an invalid model, to warn them that the model is invalid (or needs to be installed)"

**Comment by ishaan-jaff** [comment]
leaving this issue open until that's done too

**Comment by ishaan-jaff** [comment]
this is done now
