### ISSUE TITLE
[Bug]: tokenizer its not tokenizing all the words properly for both mode Stream and Non-stream

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#587]
### What happened?

user mentioned issue here: https://github.com/AntonOsika/gpt-engineer/issues/710

**Comment by haseeb-heaven** [comment]
@krrishdholakia Check Response from GPT-Engineer
![image](https://github.com/AntonOsika/gpt-engineer/assets/11544739/74617242-ddb3-45cb-854d-a10e36a80d5f)


And response from my own Custom GPT is fine.

![image](https://github.com/AntonOsika/gpt-engineer/assets/11544739/90fd213f-c497-430f-bff4-4db9bdaeab5e)

**Comment by ghost** [comment]
@haseeb-heaven can you please share a code snippet for repro with litellm. I can't tell what the issue is based on the screenshots.

**Comment by haseeb-heaven** [comment]
Here is the Feature Repo i am working on [GPT Engineer - API Base Support](https://github.com/haseeb-heaven/gpt-engineer/tree/feat/api-base-support)

**Comment by haseeb-heaven** [comment]
> @haseeb-heaven can you please share a code snippet for repro with litellm. I can't tell what the issue is based on the screenshots.

Here is the Feature Repo i am working on [GPT Engineer - API Base Support](https://github.com/haseeb-heaven/gpt-engineer/tree/feat/api-base-support)

**Comment by ghost** [comment]
@haseeb-heaven can you please give me a snippet of code i can run and test that's litellm-specific. There's a lot in that repo. 

If there's a streaming error - a stacktrace would be helpful.

**Comment by haseeb-heaven** [comment]
> @haseeb-heaven can you please give me a snippet of code i can run and test that's litellm-specific. There's a lot in that repo.
> 
> If there's a streaming error - a stacktrace would be helpful.

Its not using Lite-LLM here. its using LangChain in codebase.

**Comment by ghost** [comment]
so this isn't a streaming error due to litellm? 
<img width="895" alt="Screenshot 2023-10-11 at 4 40 02 PM" src="https://github.com/BerriAI/litellm/assets/17561003/6e3ae33b-5ba4-4ae7-a05d-2d05c3adf4d9">

**Comment by haseeb-heaven** [comment]
> so this isn't a streaming error due to litellm? <img alt="Screenshot 2023-10-11 at 4 40 02 PM" width="895" src="https://user-images.githubusercontent.com/17561003/274442245-6e3ae33b-5ba4-4ae7-a05d-2d05c3adf4d9.png">

No its not using LiteLLM, i suggested to use LiteLLM for this solution that works better because for Base API change it also set API key to Empty , but in this project we are using LangChain,

So this issue is not with LiteLLM.

**Comment by ghost** [comment]
@haseeb-heaven if you could clarify that on the gpt-engineer issue as well that'd be great - thanks.

**Comment by haseeb-heaven** [comment]
> @haseeb-heaven if you could clarify that on the gpt-engineer issue as well that'd be great - thanks.

Okay no worries
