### ISSUE TITLE
[Bug]: LiteLLM ProxyConfig behaves abnormally when using vllm OpenAI-Compatible Endpoints

### ISSUE THREAD

**Issue by mickymics** [BerriAI/litellm#5876]
### What happened?

apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  namespace: litellm
data:
  proxy_config.yaml: |
    model_list:
      - model_name: Meta-Llama-3.1-8B-Instruct
        litellm_params:
          model: "openai/meta-llama/Meta-Llama-3.1-8B-Instruct"
          api_base: "http://txt2txt-gen-meta-llama-3-1-8b-instruct.fm.svc.cluster.local/v1"
          api_key: "sk-211111"
      - model_name: Meta-Llama-3.1-8B-Instruct
        litellm_params:
          model: "text-completion-openai/meta-llama/Meta-Llama-3.1-8B-Instruct"
          api_base: "http://txt2txt-gen-meta-llama-3-1-8b-instruct.fm.svc.cluster.local/v1"
          api_key: "sk-211111"
    litellm_settings:
      drop_params: True
      num_retries: 3
      request_timeout:
      allowed_fails: 3
      cache: False

With this configmap: 

http://txt2txt-gen-meta-llama-3-1-8b-instruct.fm.svc.cluster.local/v1 endpoints are having vLLM runtime engine which supports both /completions and /chat/completions endpoint. But when I send the following curl request, it is not consistent, sometimes it calls /completions and sometimes /chat/completions endpoints.

curl --location 'http://<litellmproxy_service>/chat/completions' --header 'Content-Type: application/json' --data '{
    "model": "Meta-Llama-3.1-8B-Instruct",
    "messages": [
        {
            "role": "system",
            "content": "You are an assistant that speaks like Shakespeare."
        },
        {
            "role": "user",
            "content": "Write a poem about colors in english"
        }
    ],
    "max_tokens": 30,
    "stream": false
}'

Now if this is because of the load balancer, then how should I use the only one entry to work both for these endpoints.
Surprisingly, after remopving the following entry from the config still /completions endpoint works.

- model_name: Meta-Llama-3.1-8B-Instruct
        litellm_params:
          model: "text-completion-openai/meta-llama/Meta-Llama-3.1-8B-Instruct"
          api_base: "http://txt2txt-gen-meta-llama-3-1-8b-instruct.fm.svc.cluster.local/v1"
          api_key: "sk-211111"

**Comment by ghost** [comment]
> how should I use the only one entry to work both for these endpoints

set both to `openai/`. 

I'll update our docs to clarify this.

**Comment by ghost** [comment]
updating our docs to clarify this as well.
