### ISSUE TITLE
[Bug]: Setting Cache per API Key in Docs is Not Clear

### ISSUE THREAD

**Issue by yigitkonur** [BerriAI/litellm#5883]
The documentation at https://docs.litellm.ai/docs/proxy/caching#turn-on--off-caching-per-key suggests that it's possible to enable caching for specific API keys in proxy mode. However, following these instructions results in an error, indicating that the API expects a different request body structure.

Steps to Reproduce:
1. Set up LiteLLM in proxy mode
2. Attempt to enable caching for a specific API key using the following curl command (as per the docs):

```bash
curl -X POST 'https://0.0.0.0/key/generate' \
-H 'Authorization: Bearer master-key' \
-H 'Content-Type: application/json' \
-D '{
    "user_id": "222",
    "metadata": {
        "cache": {
            "no-cache": true
        }
    }
}'
```

Expected Behavior:
The API should accept the request and enable caching for the specified API key.

Actual Behavior:
The API returns a 422 Unprocessable Entity error with the following message:

```json
{
  "detail": [
    {
      "type": "missing",
      "loc": ["body"],
      "msg": "Field required",
      "input": null
    }
  ]
}
```

This error suggests that the API is expecting a different request body structure than what is provided in the documentation.

Additional Context:
- The error message indicates that a required field is missing in the body, but it's unclear what field is expected.
- The documentation may need to be updated to reflect the correct request body structure.

Additional Questions:
1. Is there a different endpoint or method to enable caching for specific API keys?
2. Are there any additional headers or parameters required for this request that aren't mentioned in the documentation?

**Comment by ishaan-jaff** [comment]
docs had a typo - here's the correct command @yigitkonur 

```
curl -X POST 'http://0.0.0.0:4000/key/generate' \
-H 'Authorization: Bearer sk-1234' \
-H 'Content-Type: application/json' \
-d '{
    "user_id": "222",
    "metadata": {
        "cache": {
            "no-cache": true
        }
    }
}'
```
