### ISSUE TITLE
[Feature]: Improve turn_off_message_logging + add better testing

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#5890]
### The Feature

- [ ] move to using Standard Logging Payload for message / response logging for relevant Logging callbacks:
- [ ] Move OTEL to use Standard Logging Payload
- [ ] Move Datadog to use Standard Logging Payload
- [x] Move s3  to use Standard Logging Payload
- [ ] Move Langsmith to use Standard Logging Payload
- [ ] Move GCS Bucket to use Standard Logging Payload 
- [x] Do redaction at the standard logging payload level when `turn_off_message_logging` is True 
- [ ] Do redaction at the standard logging payload level when `callback_settings` are set 
- [x] Testing: Add turn_off_message_logging / callback_settings redaction tests for OTEL/Datadog/s3/Langsmith/GCS Bucket ensuring no message or response is logged 

### Motivation, pitch

-

**Comment by ghost** [comment]
@ishaan-jaff s3 bucket already uses the standard logging payload 

AND we already do message redaction on the standard logging payload - https://github.com/BerriAI/litellm/blob/58171f35ef1a1d231d9072c2a19e70629b4b55aa/litellm/tests/test_custom_callback_input.py#L1183

**Comment by ghost** [comment]
i believe the output redaction is what's missing
