### ISSUE TITLE
[Bug]: don't initialize prometheus logger if non-premium user (leads to incorrect errors) 

### ISSUE THREAD

**Issue by themrzmaster** [BerriAI/litellm#5897]
### What happened?

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/integrations/prometheus.py", line 559, in async_post_call_success_hook
    self.litellm_proxy_total_requests_metric.labels(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PrometheusLogger' object has no attribute 'litellm_proxy_total_requests_metric'

this error again on proxy...

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/integrations/prometheus.py", line 559, in async_post_call_success_hook
    self.litellm_proxy_total_requests_metric.labels(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PrometheusLogger' object has no attribute 'litellm_proxy_total_requests_metric'
```

**Comment by ishaan-jaff** [comment]
have you set it as a callback @themrzmaster  ?

**Comment by ghost** [comment]
Unable to repro this @themrzmaster 

This is my config 

```yaml
litellm_settings:
  success_callback: ["langfuse", "prometheus"]
  failure_callback: ["prometheus"]
```

I can also see `litellm_proxy_total_requests_metric` is initialized on Prometheus init, which makes this error surprising - https://github.com/BerriAI/litellm/blob/2444d76fda2ddfb5756100286f4961592b8b6472/litellm/integrations/prometheus.py#L62

Can you please share steps to repro

**Comment by ghost** [comment]
Closing as unable to repro

**Comment by themrzmaster** [comment]
Really? You cant reproduce a bug that was reported 1 hour ago and you close the issue?

**Comment by themrzmaster** [comment]
litellm_settings:
  num_retries: 3
  fallbacks: [{"llama-v3-70b-instruct-hf": ["llama-v3-70b-instruct-together"]}, {"gemini-1.5-flash": ["gemini-1.5-flash-studio"]}]
  success_callback: ["prometheus"]
  failure_callback: ["prometheus"]

**Comment by ghost** [comment]
tried with your config. not seeing this on the latest version of litellm. I even see the metric emitted on prometheus. 

<img width="1596" alt="Screenshot 2024-09-25 at 3 35 54 PM" src="https://github.com/user-attachments/assets/d9c09fe7-40e5-44ef-88cc-635bc1b4eb6f">

**Comment by themrzmaster** [comment]
more logs:
```

00:23:51 - LiteLLM Proxy:ERROR: spend_tracking_utils.py:158 - Error creating spendlogs object - Object of type CompletionTokensDetails is not JSON serializable
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/spend_tracking/spend_tracking_utils.py", line 138, in get_logging_payload
    metadata=json.dumps(clean_metadata),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type CompletionTokensDetails is not JSON serializable
00:23:51 - LiteLLM:ERROR: litellm_logging.py:1644 - LiteLLM.LoggingError: [Non-Blocking] Exception occurred while success logging Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/litellm_core_utils/litellm_logging.py", line 1576, in async_success_handler
    await callback.async_log_success_event(
  File "/usr/local/lib/python3.11/site-packages/litellm/integrations/prometheus.py", line 357, in async_log_success_event
    self.litellm_requests_metric.labels(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PrometheusLogger' object has no attribute 'litellm_requests_metric'

00:23:51 - LiteLLM:ERROR: prometheus.py:569 - prometheus Layer Error(): Exception occured - 'PrometheusLogger' object has no attribute 'litellm_proxy_total_requests_metric'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/integrations/prometheus.py", line 559, in async_post_call_success_hook
    self.litellm_proxy_total_requests_metric.labels(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PrometheusLogger' object has no attribute 'litellm_proxy_total_requests_metric'
```

now on version 1.48.0

**Comment by themrzmaster** [comment]
no error when downgrading back to v1.44.10-stable

**Comment by themrzmaster** [comment]
I will be honest with you. I was considering getting the Enterprise. But that does not transmit trust to your customers.

**Comment by ishaan-jaff** [comment]
Prometheus is an enterprise feature and it's enforced now which is why you're seeing the error

**Comment by ishaan-jaff** [comment]
<img width="974" alt="Screenshot 2024-09-26 at 9 57 21 AM" src="https://github.com/user-attachments/assets/cfc854db-55e8-4389-b37c-b379bb435068">

See this code - if you're not an enterprise user the metrics will not get created

**Comment by ghost** [comment]
fixed to prevent initialization + return a warning message here - https://github.com/BerriAI/litellm/commit/acd8facf9899014a76d5cb053176bb3e33cb0162
