### ISSUE TITLE
[Feature]: Support Bedrock's Cross Region Inference feature

### ISSUE THREAD

**Issue by taralika** [BerriAI/litellm#5899]
### The Feature

Certain new models in Bedrock (e.g., llama3.2) are only available via the new cross-region inference profile. What this means is now Bedrock models can have model IDs that start with model provider (like before e.g., "meta") or they can start with a region code (e.g., "us", "eu"). This scenario needs to be handled as currently proxy assumes the bedrock model IDs always start with the provider name.
More details here: https://docs.aws.amazon.com/bedrock/latest/userguide/cross-region-inference.html

### Motivation, pitch

Without this we can't use newer Bedrock models like llama3.2

**Comment by ghost** [comment]
Hi @taralika i believe this is already supported - https://github.com/BerriAI/litellm/blob/2444d76fda2ddfb5756100286f4961592b8b6472/litellm/tests/test_bedrock_completion.py#L1232

On docs - https://docs.litellm.ai/docs/providers/bedrock#cross-region-inferencing

**Comment by taralika** [comment]
> Hi @taralika i believe this is already supported -
> 
> https://github.com/BerriAI/litellm/blob/2444d76fda2ddfb5756100286f4961592b8b6472/litellm/tests/test_bedrock_completion.py#L1232
> 
> On docs - https://docs.litellm.ai/docs/providers/bedrock#cross-region-inferencing

@krrishdholakia it's not working for me, I get:
```
litellm.NotFoundError: BedrockException - Bedrock HTTPX: Unknown provider=us, model=us.meta.llama3-2-1b-instruct-v1:0
```
And I see it's because of this line wich assumes the provider is always the first part but it's not the case here. https://github.com/BerriAI/litellm/blob/2444d76fda2ddfb5756100286f4961592b8b6472/litellm/llms/bedrock/chat/invoke_handler.py#L325

**Comment by taralika** [comment]
`'error': 'error:litellm.NotFoundError: BedrockException - Bedrock HTTPX: Unknown provider=us, model=us.amazon.nova-micro-v1:0.` Looks like this issue has not been addressed yet. @krrishdholakia @ishaan-jaff

**Comment by taralika** [comment]
even tried this https://litellm.vercel.app/docs/providers/bedrock#set-converse--invoke-route like this:
```
- model_name: amazon.nova-micro-v1:0
    litellm_params:
      model: bedrock/converse/us.amazon.nova-micro-v1:0
      aws_region_name: us-west-2
```

but still getting error:
`{'aws_region_name': 'us-west-2', 'model': 'bedrock/converse/us.amazon.nova-micro-v1:0', 'cache': {'no-cache': True}, 'error': 'error:litellm.NotFoundError: BedrockException - Bedrock HTTPX: Unknown provider=converse/us, model=converse/us.amazon.nova-micro-v1:0.`

**Comment by ghost** [comment]
> even tried this https://litellm.vercel.app/docs/providers/bedrock#set-converse--invoke-route like this:


this is live from `v`1.53.5`. Your new ticket indicates your on an older version
