### ISSUE TITLE
[bug] Support bedrock meta cross region inferencing

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#5901]
> Hi @taralika i believe this is already supported -
> 
> https://github.com/BerriAI/litellm/blob/2444d76fda2ddfb5756100286f4961592b8b6472/litellm/tests/test_bedrock_completion.py#L1232
> 
> On docs - https://docs.litellm.ai/docs/providers/bedrock#cross-region-inferencing

@krrishdholakia it's not working for me, I get:
```
litellm.NotFoundError: BedrockException - Bedrock HTTPX: Unknown provider=us, model=us.meta.llama3-2-1b-instruct-v1:0
```
And I see it's because of this line wich assumes the provider is always the first part but it's not the case here. https://github.com/BerriAI/litellm/blob/2444d76fda2ddfb5756100286f4961592b8b6472/litellm/llms/bedrock/chat/invoke_handler.py#L325

_Originally posted by @taralika in https://github.com/BerriAI/litellm/issues/5899#issuecomment-2375360951_

**Comment by taralika** [comment]
@krrishdholakia #5898 should fix this issue, can you get it merged/released?

**Comment by ghost** [comment]
re-opened. can you add some tests to make sure it doesn't introduce any regressions to the existing cross inferencing logic for anthropic

**Comment by ghost** [comment]
Hi @taralika i don't believe meta llama is supported for cross region inferencing - https://docs.aws.amazon.com/bedrock/latest/userguide/cross-region-inference-support.html


looking at the table you shared. 

Is it just undocumented?

**Comment by taralika** [comment]
>Is it just undocumented?

yeah, it's undocumented, we have access to meta llama models with cross region inferencing like I mentioned earlier with the example: `us.meta.llama3-2-1b-instruct-v1:0` and going forward any/all bedrock models may have the same nomenclature

**Comment by ghost** [comment]
makes sense - i'll add some mock tests too. Thanks for raising this @taralika

**Comment by steffen-sbt** [comment]
Can confirm as well, we got access to the new 3.2 models, but they are only available via cross region, which means we can't currently use them through litellm right now.
