### ISSUE TITLE
[Feature]: Add cost tracking for Fireworks AI llama 3.2 vision models / requests with images 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#5906]
### The Feature

https://fireworks.ai/blog/llama32-with-fireworks

Image input is counted as `6400 prompt tokens`  on fireworks llama 32 

> We’re also happy to announce new, competitive pricing for text and multimodal models, especially for the Llama 3.2 - 11B and Llama 3.2 - 90B multimodal models which will be the same price as the text-only models. Images will be charged as text tokens. The exact number of tokens depends on image resolution and model. Images for the Llama 3.2 vision models are typically counted as 6400 text tokens.

### Motivation, pitch

-

**Comment by ghost** [comment]
I just added cost tracking support @ishaan-jaff https://github.com/BerriAI/litellm/blob/main/litellm/llms/fireworks_ai/cost_calculator.py

Or is the request to have `token_counter()` handle the fireworks ai specific scenario?

**Comment by ishaan-jaff** [comment]
nvm this is a no-op. we already support this
