### ISSUE TITLE
[Bug]: Exception import enterprise features No module named 'litellm.proxy.enterprise'

### ISSUE THREAD

**Issue by guiramos** [BerriAI/litellm#5909]
### What happened?

This is the log message I am getting in my python application.

DEBUG - Exception import enterprise features No module named 'litellm.proxy.enterprise'

The enterprise package is nowhere to be seem:

<img width="345" alt="image" src="https://github.com/user-attachments/assets/99d849f9-53cb-4981-b2f5-29425cf4d8ff">

I am using version `1.48.1`

### Relevant log output

```shell
DEBUG - Exception import enterprise features No module named 'litellm.proxy.enterprise'
```

**Comment by ishaan-jaff** [comment]
hi @guiramos there's not been any recent change around this folder / any imports from it 
- does your proxy start ? is this just a warning 
- can you give me steps to repro this ? how do you start litellm ? 
- can you try and check if our docker container works fine for you ?

**Comment by guiramos** [comment]
@ishaan-jaff hey, I am not using a docker for this project. It's a desktop application.
And I am not using the proxy server at all. 
Just regular completion:

```
response = completion(
            model="groq/llama-3.1-70b-versatile",
            messages=[
                {"role": "user", "content": prompt}
            ],
        )
```

**Comment by ghost** [comment]
@guiramos the error you're showing seems to be a debug log, shown if debug is enabled - https://github.com/BerriAI/litellm/blob/a1d9e96b310770838bab03fa9a967940d4a45a72/litellm/litellm_core_utils/litellm_logging.py#L100

I can confirm this doesn't show up in a sample colab, making me think you've enabled the debug logs from the `logging` library (either via an env var or from their python module) 

This isn't a bug, as the GenericAPILogger is an enterprise feature for the litellm proxy. 

I'll modify the debug log to make this more clear.

**Comment by ghost** [comment]
Confirmed running litellm python sdk in a clean vm, does not emit this log by default. 

<img width="1657" alt="Screenshot 2024-09-26 at 5 31 01 PM" src="https://github.com/user-attachments/assets/f06cd902-86eb-4b56-a994-40c055250878">

**Comment by opyate** [comment]
My .env has `LITELLM_LOG=INFO` and I still see this.
