### ISSUE TITLE
[Feature]: Easy way to get environment variable names for providers

### ISSUE THREAD

**Issue by SamDc73** [BerriAI/litellm#5929]
### The Feature

Enhance the `get_model_info` function in LiteLLM to include the environment variable name for the provider's API key. For example, when calling `get_model_info("groq/llama3-8b-8192")`, the returned dictionary would include a new key like `"env_var": "GROQ_API_KEY"`. This addition would make it easy for users to programmatically determine the correct environment variable name for any supported model's API key.

### Motivation, pitch

I'm building an app that uses LLMs. I'd love for my users to be able to add new models as soon as LiteLLM supports them, without needing me to update the app. A simple way to get the correct environment variable name for each provider would make this seamless. It'd let users easily configure their API keys for new models, keeping my app flexible and future-proof.

### Twitter / LinkedIn details

@samdc73

**Comment by ghost** [comment]
hey @SamDc73 this is already supported through `validate_environment` - https://github.com/BerriAI/litellm/blob/ab153c3e8dab6be093eba3726ada19da176ee8cc/litellm/utils.py#L5254
