### ISSUE TITLE
[Bug]: OpenAI TTS throws errors while logging 

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#5939]
### What happened?

<img width="730" alt="image" src="https://github.com/user-attachments/assets/9db6383b-8e71-431d-b347-fdf0af9c4add">

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by ghost** [comment]
This is already fixed on a later version of litellm @Manouchehri 

https://github.com/BerriAI/litellm/blob/ab153c3e8dab6be093eba3726ada19da176ee8cc/litellm/cost_calculator.py#L439
