### ISSUE TITLE
[Document Bug]: Incorrect RPM Definition (Azure) in Routing Documentation

### ISSUE THREAD

**Issue by yigitkonur** [BerriAI/litellm#5945]
### What happened?

Description:
The routing documentation for litellm contains an error in the definition of RPM (Requests Per Minute).

Current Definition:
RPM is defined as TPM / 6

Correct Information:
The correct relationship is 6 RPM per 1000 TPM

Location of the Issue:
https://github.com/BerriAI/litellm/blob/46c850994175bc3ecaac9b040be7430be13c3d59/docs/my-website/docs/routing.md#routing-strategies---weighted-pick-rate-limit-aware-least-busy-latency-based-cost-based

Source of Correct Information:
https://stackoverflow.com/questions/77368844/what-is-the-request-per-minute-rate-limit-for-azure-openai-models-for-gpt-3-5-tu

Suggested Fix:
Update the documentation to correctly state the relationship between RPM and TPM. The corrected text should indicate that there are 6 RPM per 1000 TPM, or provide an equivalent, accurate representation of this relationship.

**Comment by ishaan-jaff** [comment]
done here @yigitkonur https://github.com/BerriAI/litellm/commit/bbf4db79c131f4af1b1e2d23d5952292cec354db
