### ISSUE TITLE
[Feature]: document units on `litellm.request_timeout`

### ISSUE THREAD

**Issue by jamesbraza** [BerriAI/litellm#5948]
### The Feature

Let's put a code comment next to this stating the units (e.g. seconds, milliseconds)

### Motivation, pitch

Making it easy to read and understand code/timeouts

**Comment by jamesbraza** [comment]
Also, the source and the docs at https://docs.litellm.ai/docs/proxy/cli#--request_timeout differ on the default value, those should be standardized

**Comment by ghost** [comment]
> Let's put a code comment next to this stating the units (e.g. seconds, milliseconds)


is there a line of code you meant to be pointing to out here? @jamesbraza

**Comment by jamesbraza** [comment]
Ah crap, yeah sorry my bad. This one: https://github.com/BerriAI/litellm/blob/v1.48.3/litellm/__init__.py#L271

**Comment by ghost** [comment]
Fixed https://github.com/BerriAI/litellm/commit/1f51159ed20278f23a3d7bfe2d67fd3a8aed5e8a
