### ISSUE TITLE
[Feature]: Make docker image proxy work for cors 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#595]
### The Feature

<img width="1067" alt="Screenshot 2023-10-13 at 12 40 00 PM" src="https://github.com/BerriAI/litellm/assets/17561003/8e5e5ff7-c8b2-4ee2-b88d-3bdf24da898a">

### Motivation, pitch

user request

**Comment by ghost** [comment]
cc: @ishaan-jaff does the ollama docker image pull our latest proxy?

**Comment by ghost** [comment]
@DanielLaberge

**Comment by DanielLaberge** [comment]
Thank you, can't wait to try it out!

**Comment by ishaan-jaff** [comment]
yes it uses the latest version of litellm

**Comment by ishaan-jaff** [comment]
what do we need to do to add cors support ? any suggestions ?

**Comment by DanielLaberge** [comment]
Normally it should be sufficient to do something like the following code, which allows all origins to talk to the API and which [litellm does already](https://github.com/BerriAI/litellm/blob/c09104e577bb88e380c63ee0fb91fc05b7ddb5b2/cookbook/codellama-server/main.py#L33). 

That said, I haven’t taken a deep look at your code base, so I don’t know if there’s another middleware involved that may be stripping the headers that should be returned.

```
from flask import Flask
from flask_cors import CORS

app = Flask(__name__)
CORS(app)
```

**Comment by ghost** [comment]
i believe our proxy is a fastapi not flask, but yes i believe something similar to that is what we need to add to our proxy.

**Comment by ghost** [comment]
hey @DanielLaberge a fix for this is currently running through testing - https://github.com/BerriAI/litellm/commit/3fc0375e346e8c453c06361c9fc0bc9598d38048

will update once it's in prod (~10 mins)

**Comment by ghost** [comment]
in prod v`0.8.2` @DanielLaberge let me know if this works (just pull a new image)

**Comment by DanielLaberge** [comment]
Confirmed working. It is returning the expected access-control-* headers.
Thanks for the fast turnaround!

```
curl -X OPTIONS -i localhost:8000/chat/completions \
-H 'Origin: https://example.com' \
-H 'Access-Control-Request-Method: POST' \
-H 'Access-Control-Request-Headers: Content-Type' \
-H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36'

HTTP/1.1 200 OK
date: Sat, 14 Oct 2023 15:14:50 GMT
server: uvicorn
vary: Origin
access-control-allow-methods: DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT
access-control-max-age: 600
access-control-allow-credentials: true
access-control-allow-origin: https://example.com
access-control-allow-headers: Content-Type
content-length: 2
content-type: text/plain; charset=utf-8

OK
```
