### ISSUE TITLE
[Feature]: not including `tests` in PyPI package

### ISSUE THREAD

**Issue by jamesbraza** [BerriAI/litellm#5951]
### The Feature

I observed in `litellm==1.48.2` that `tests` are included in the package.

Can we exclude `tests` from the package? It bloats the size of `litellm`.

### Motivation, pitch

Having `tests` messes with CTRL-F

**Comment by ghost** [comment]
Duplicate https://github.com/BerriAI/litellm/issues/486

I moved some tests recently and it was a pretty simple migration, can work on this tomorrow.

**Comment by jamesbraza** [comment]
Sounds good, thanks
