### ISSUE TITLE
health check documentation language problems

### ISSUE THREAD

**Issue by curious-broccoli** [BerriAI/litellm#5979]
I think in https://github.com/BerriAI/litellm/blob/main/docs/my-website/docs/proxy/health.md the sentences 

> We need some way to know if the model is an [type] model when running checks, if you have this in your config, specifying mode it makes an [type] health check

don't make sense grammatically.

and for the chat completion it says

> it makes an embedding health check

but it should of course say chat completion rather than embedding

**Comment by ishaan-jaff** [comment]
fixed here @curious-broccoli https://github.com/BerriAI/litellm/pull/5984

**Comment by ishaan-jaff** [comment]
curious @curious-broccoli do you use LiteLLM Proxy in production today ? If so can we hop on a call to get your feedback on LiteLLM proxy ? 

- my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
- my linkedin if you prefer DMs: https://www.linkedin.com/in/reffajnaahsi/

**Comment by curious-broccoli** [comment]
not up for a call but I suppose it works nice, but we are not running it for for-profit purposes. I also don't administer it a lot or set it up myself. only thing I dislike is that the admin UI (/ui) is weirdly made, e.g. buttons aren't really buttons. but it works

**Comment by ishaan-jaff** [comment]
sounds good thanks for the response @curious-broccoli
