### ISSUE TITLE
Embedding  with Python SDK is slower than using the native Vertex client

### ISSUE THREAD

**Issue by ahmedbesbes** [BerriAI/litellm#5993]
Hi!

Thanks for this great library.
I'm currently using the python SDK to embed hundreds of thousands of chunks using VertexAI embedding model: text-embedding-004.

The issue here is that calling this model from LiteLLM is slower than using the native vertex client. About 2 / 3 times slower.

To embed a single text, it takes

- 200-300ms with the native client
- 700-900ms with litellm

This obviously becomes a scalability issue.

FYI:
I'm using google application default credentials to authenticate.

Has anyone experienced this problem before? (Again, it's the SDK I'm using not the proxy)

Thanks for your help

I

**Comment by ishaan-jaff** [comment]
hi @ahmedbesb can you send me some details

- how are you calling this with the litellm sdk (can you share code so I can repro) 
- are you on the latest version of litellm, if not can you bump to latest and see if you still see this diff

**Comment by ishaan-jaff** [comment]
Okay I can see this is because we're not using the vertex httpx route for our embeddings calls - which we should be doing. Will take care of this

**Comment by ahmedbesbes** [comment]
Thank you, appreciate it ! if it's not top priority for you, can you please tell me how to fix it?

**Comment by ishaan-jaff** [comment]
this is on my priority list and I'm aiming to have this resolved in 24 hours @ahmedbesbes

**Comment by ishaan-jaff** [comment]
pr here https://github.com/BerriAI/litellm/pull/6000

**Comment by ishaan-jaff** [comment]
@ahmedbesbes were you using `litellm.aembedding()` ?
