### ISSUE TITLE
come up with a better solution for accepting api keys 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#60]
This **doesn't suck**. But **could it be better**?
<img width="847" alt="Screenshot 2023-08-07 at 11 41 06 AM" src="https://github.com/BerriAI/litellm/assets/17561003/12f51792-13f9-4fba-a70f-7ac116925ca8">

**Comment by ishaan-jaff** [comment]
standardized to PROVIDER_API_KEY
