### ISSUE TITLE
[Bug]: Responses Cut Off at 16 Tokens for gpt-3.5-turbo-instruct

### ISSUE THREAD

**Issue by nirmittumeryk** [BerriAI/litellm#6006]
### What happened?

**What happened?**
Responses using the gpt-3.5-turbo-intruct model are cut off after 16 tokens when no max_tokens parameter is specified.

**What did you expect to happen?**
I expected the responses to continue until the model's natural completion without an arbitrary cut-off.

**Comment by olli-olesia** [comment]
I am facing the same issue. @nirmittumeryk why did you close it?

**Comment by nirmitashar** [comment]
This is unrelated to litellm. With the Completions endpoint for  gpt-3.5-turbo-instruct, the default max_tokens is 16.
