### ISSUE TITLE
[Bug]: Issue when use with Claude Dev

### ISSUE THREAD

**Issue by hongbo-miao** [BerriAI/litellm#6007]
### What happened?

I tried to use Claude models (provided by AWS Bedrock) through LiteLLM proxy in the VSCode plugin Claude Dev, but got error:

> APl Request Failed
> 400 litellm.BadRequestError: BedrockException - {"message":"A conversation must alternate between user and assistant roles. Make sure the conversation alternates between user and assistant roles and try again."}
Received Model Group=claude-3-opus
Available Model Group Fallbacks=None

![image](https://github.com/user-attachments/assets/8e8ad850-942d-4872-96e9-0512d60c3fc5)

I created a ticket on Claude Dev side with more details at https://github.com/saoudrizwan/claude-dev/issues/433

I am not sure if related with LiteLLM, so I opened one here as well, and hopefully both sides can help resolve it together, thanks! ☺️

### Twitter / LinkedIn details

@hongbo_miao

**Comment by Manouchehri** [comment]
I've also ran into this using Continue.dev.

**Comment by ghost** [comment]
Hey @hongbo-miao can you share what the request received by litellm looked like? it should be easy to see when running `--detailed_debug`

**Comment by hongbo-miao** [comment]
Thanks @Manouchehri @krrishdholakia !

I saw @juancarlosm found a workaround way at https://github.com/saoudrizwan/claude-dev/issues/433#issuecomment-2388970137 Does it help? And maybe we could follow up there? Thanks!

**Comment by hongbo-miao** [comment]
Hi @krrishdholakia , here is the error log: https://gist.github.com/hongbo-miao/5ab5cdbb082d529e62f6f08cce2d1f3a
Also, I saw @juancarlosm may have a workaround way at https://github.com/saoudrizwan/claude-dev/issues/433#issuecomment-2388970137 which may help as well, thanks!

**Comment by ghost** [comment]
thanks - able to repro this

**Comment by ghost** [comment]
found the issue, we didn't merge the last 2 chunks correctly 
<img width="593" alt="Screenshot 2024-10-02 at 9 54 54 PM" src="https://github.com/user-attachments/assets/fcc2e64a-7995-453c-a99a-bd0ff0bd7792">
