### ISSUE TITLE
[Feature]: add docs on add keys via cli for proxy

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#601]
### The Feature

you can now save keys locally to for the proxy cli by just running 

```shell
litellm --add_key OPENAI_API_KEY=my-key
```

and it'll save it to a local file, so it persists across shell restarts. Need to add this to our docs. 

### Motivation, pitch

i hate having to re-add keys for my proxy cli tool

**Comment by ghost** [comment]
docs should also include all the possible keys you can add today
<img width="920" alt="Screenshot 2023-10-13 at 10 32 59 PM" src="https://github.com/BerriAI/litellm/assets/17561003/5d696d90-c9f0-4a19-b7de-3e564d4f8a00">

**Comment by ShatilKhan** [comment]
Hi can I work on this one please?

**Comment by ghost** [comment]
hey @ShatilKhan saw this late sorry - just pushed docs fc757dc1b47d2eb9d0ea47d6ad224955b705059d

**Comment by ghost** [comment]
feel free to grab another issue. Are you using litellm today?
