### ISSUE TITLE
Retry mechanism not pausing for set delay after rate limit is hit

### ISSUE THREAD

**Issue by NEWbie0709** [BerriAI/litellm#6011]
I'm using the LiteLLM proxy and attempting to implement a retry mechanism. I've set the retry count to 3 with a delay of 30 seconds between each retry. My goal is to handle rate-limiting issues (e.g., when the rate limit per minute is hit), ensuring that the system pauses for 30 seconds before retrying the request. However, I noticed that while the system retries, it doesn't wait the full 30 seconds between attempts.

Problem: Despite configuring a 30-second delay between retries, the system only seems to not pausing at all before retrying. This results in it quickly reaching the retry limit without respecting the delay period. The system still hits the rate limit multiple times instead of waiting properly between retries.
![image](https://github.com/user-attachments/assets/d9e992c0-4918-4a06-85a0-f8d3690a2e50)
![image](https://github.com/user-attachments/assets/15605d1c-94ef-40af-8a6a-f01cf1809f82)

**Comment by ghost** [comment]
Hi @NEWbie0709 this was fixed in a recent version of litellm - https://github.com/BerriAI/litellm/commit/8039b95aaf61d363a7f3f381d2071fe6a8e203e9#diff-b0c899fae4bf607df1d0d1a3b170246a0f9d2b5dfe230c48e4539c78222ecc57R3373

Bump to v1.47.2+ and this will work as expected

**Comment by NEWbie0709** [comment]
Can I know if the retry-after is set correctly? I set it to 30 seconds, but it didn't wait for 30 seconds before trying again

**Comment by NEWbie0709** [comment]
Can I know if the retry-after is set correctly? I set it to 30 seconds, but it didn't wait for 30 seconds before trying again
![image](https://github.com/user-attachments/assets/e9323aed-dc72-4659-bfe8-1d1a3207f863)
