### ISSUE TITLE
[Bug]: claude models tool use without "parameters" fails with anthropic and bedrock

### ISSUE THREAD

**Issue by vedpatwardhan** [BerriAI/litellm#6012]
### What happened?

Claude models fail with anthropic and bedrock if we pass tools where the schema doesn't contain the parameters,
e.g.
```python

from litellm import completion

# fails with either model
model = "anthropic/claude-3-5-sonnet-20240620"
# model = "bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0"
tools = [
    {
        "type": "function",
        "function": {
            "name": "get_current_weather",
            "description": "Get the current weather in New York",
        },
    }
]
messages = [{"role": "user", "content": "What is the current temperature in New York?"}]
completion(model=model, messages=messages, tools=tools, tool_choice="auto")
```

However, the same passes with `gpt-4o`. The `parameters` is optional as per the [OpenAI Standard](https://platform.openai.com/docs/api-reference/chat).

> Omitting parameters defines a function with an empty parameter list.

**Comment by ghost** [comment]
I can confirm passing a dummy tool fixes the issue. 

I believe we can gate this behind a `litellm.modify_params` flag, so the behaviour is opt-in.

**Comment by ghost** [comment]
We'll also need to fix the validation checks in a few places.
