### ISSUE TITLE
[Feature]: Ability to monitor prompt caching with Anthropic

### ISSUE THREAD

**Issue by iuliaturc** [BerriAI/litellm#6021]
### The Feature

I'm trying to use [prompt caching with Anthropic models](https://docs.litellm.ai/docs/providers/anthropic#prompt-caching). I'd like to double-check that caching is indeed happening and, according to the [Anthropic documentation](https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching), this information is encoded in the `usage` field of their response (`cache_creation_input_tokens` and `cache_read_input_tokens`).

However, the response I'm getting from LiteLLM doesn't seem to contain this information anywhere.

Here's how I'm calling it:
```
from litellm import completion

system_turn = {
  "role": "system",
  "content": [
      {
          "type": "text",
          "text": sys_prompt,
          "cache_control": {"type": "ephemeral"},
      }
  ]
}
user_turn = {
  "role": "user",
  "content": user_query,
}
messages = [system_turn, user_turn]
response = completion(model="claude-3-5-sonnet-20240620", messages=messages)
```

And here's how I'm looking at the response:
```
import pprint
pprint.pprint(vars(response))
```

The output doesn't seem to include the caching information:
```
{'_hidden_params': {'model_id': None},
 '_response_headers': None,
 'chunks': [],
 'complete_response': '',
 'completion_stream': None,
 'custom_llm_provider': 'anthropic',
 'holding_chunk': '',
 'is_function_call': False,
 'logging_loop': None,
 'logging_obj': <litellm.litellm_core_utils.litellm_logging.Logging object at 0x2baf1bb90>,
 'make_call': [REMOVED]
 'model': 'claude-3-5-sonnet-20240620',
 'received_finish_reason': None,
 'response_id': None,
 'response_uptil_now': '',
 'rules': <litellm.utils.Rules object at 0x2baf44fe0>,
 'sent_first_chunk': False,
 'sent_last_chunk': False,
 'sent_stream_usage': False,
 'special_tokens': ['<|assistant|>',
                    '<|system|>',
                    '<|user|>',
                    '<s>',
                    '</s>',
                    '<|im_end|>',
                    '<|im_start|>'],
 'stream_options': None,
 'system_fingerprint': None,
 'tool_call': False}
```

### Motivation, pitch

Self-contained above.

### Twitter / LinkedIn details

https://x.com/juliarturc

**Comment by ghost** [comment]
Hi @iuliaturc you might be on an older version of litellm. Can you try bumping. 

I can see it when running in a clean colab environment - 
<img width="1451" alt="Screenshot 2024-10-02 at 4 25 55 PM" src="https://github.com/user-attachments/assets/a07d16e9-92c2-4972-aa83-34cf2ff8fbbc">
