### ISSUE TITLE
[Feature]: Allow to set Langfuse Generation Name

### ISSUE THREAD

**Issue by Goktug** [BerriAI/litellm#603]
### The Feature

It would be helpful to improve traceability by setting a unique `Langfuse Generation Name` for each trace. Currently, all traces are saved as `litellm-completion`, making it difficult to differentiate their origin without examining the details.

![Screenshot 2023-10-14 at 12 17 23](https://github.com/BerriAI/litellm/assets/534426/eabd227a-9cb3-4487-b545-889d8291ab23)

The name is hard-coded in this section as you see:
https://github.com/BerriAI/litellm/blob/b6a6bf65aff5c0646342750dc12d38c2dbf6cfc0/litellm/integrations/langfuse.py#L41C17-L41C43

### Motivation, pitch

When we have different endpoints that use different agents for different purposes, having separate traces would improve traceability and observability. Currently, all of the requests have the same generation and trace name.

**Comment by ghost** [comment]
@Goktug i was thinking about how we handle integrations - what if we let you instantiate a langfuse client and pass that to litellm - would that help solve this? 

i'm assuming you use langfuse in other parts of your code.

example code: 
```
import langfuse, litellm 

langfuseClient = langfuse.init()


litellm.callbacks = [langfuseClient] 
```

**Comment by ghost** [comment]
picking this up

**Comment by ghost** [comment]
Hey @Goktug 

You can pass in additional metadata into your completion call, and access it via custom callbacks. 

Since you're passing in a custom callback function, let me know if this solves your problem. 

```python
import litellm, os
from litellm import completion

# set env var
os.environ["OPENAI_API_KEY"]="your-api-key"

def custom_callback(
    kwargs,                 # kwargs to completion
    completion_response,    # response from completion
    start_time, end_time    # start/end time
):
    print(kwargs["litellm_params"]["metadata"])
    

# Assign the custom callback function
litellm.success_callback = [custom_callback]

response = completion(model="gpt-3.5-turbo", messages=messages, metadata={"hello": "world"})
```

Docs: https://docs.litellm.ai/docs/observability/custom_callback#log-additional-metadata
