### ISSUE TITLE
How to use Azure Open AI endpoint

### ISSUE THREAD

**Issue by PriyalPN** [BerriAI/litellm#6033]
Hi, I'm trying to run DocETL but it's throwing me access error
| |       original_exception = OpenAIError("Error code: 401 - {'error':     | |
| |                            {'message': 'Incorrect API key provided:     | |
| |                            ***************************4. You can    | |
| |                            find your API key at                         | |
| |                            [https://platform.openai.com/account/api-key…](https://platform.openai.com/account/api-key%E2%80%A6) | |
| |                            'type': 'invalid_request_error', 'param':    | |
| |                            None, 'code': 'invalid_api_key'}}")          | |
| +-------------------------------------------------------------------------+ |
+-----------------------------------------------------------------------------+
AuthenticationError: litellm.AuthenticationError: AuthenticationError: 
OpenAIException - Error code: 401 - {'error': {'message': 'Incorrect API key 
provided: ***************************4. You can find your API key at 
https://platform.openai.com/account/api-keys.', 'type': 
'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

I want to use AZURE OPEN AI, how to do it

**Comment by ishaan-jaff** [comment]
usage example https://docs.litellm.ai/docs/providers/azure
