### ISSUE TITLE
[Bug]: Changing `max_tokens_to_sample` to `max_tokens` for anthropic models in bedrock

### ISSUE THREAD

**Issue by vedpatwardhan** [BerriAI/litellm#6035]
### What happened?

Anthropic bedrock models don't seem to work if we pass in the `max_tokens`,
```python
from litellm import completion

completion(
    "bedrock/us.anthropic.claude-3-5-sonnet-20240620-v1:0",
    [{"role": "user", "content": "hello world"}],
    max_tokens=100
)
```
That's probably because `max_tokens_to_sample` needs to be renamed to `max_tokens` as we [transition to the messages API](https://docs.anthropic.com/en/api/migrating-from-text-completions-to-messages#specifying-max-tokens) (which is what bedrock uses)

**Comment by ghost** [comment]
This is a duplicate issue and fixed in the latest release. https://github.com/BerriAI/litellm/issues/6003
