### ISSUE TITLE
[Feature]: Add OpenAI prompt Caching 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#6038]
### The Feature

- [x] #6046
- [x] Return  `prompt_tokens_details` in responses streaming 
- [x] #6056
- [ ] #6057

### Motivation, pitch

-

**Comment by ghost** [comment]
openai doesn't return 'null' value in usage. If the value doesn't exist, it's not returned 

<img width="668" alt="Screenshot 2024-10-03 at 5 15 36 PM" src="https://github.com/user-attachments/assets/bb5a4d31-ebcf-4bfe-8e1c-b92edacfb145">

**Comment by ghost** [comment]
> CompletionUsage(completion_tokens=5, prompt_tokens=12, total_tokens=17, completion_tokens_details=CompletionTokensDetails(audio_tokens=None, reasoning_tokens=0), prompt_tokens_details=PromptTokensDetails(audio_tokens=None, cached_tokens=0))

But the openai sdk does
