### ISSUE TITLE
[Bug]: Open in Colab Link dead

### ISSUE THREAD

**Issue by biplobsd** [BerriAI/litellm#604]
### What happened?

When click on the open in colab from https://github.com/BerriAI/litellm#usage
Notebook not found error shown.

![image](https://github.com/BerriAI/litellm/assets/43641536/0be760e9-04e6-450e-bb4e-e1878e44f904)

### Relevant log output

```shell
Could not find liteLLM_OpenAI.ipynb in https://api.github.com/repos/BerriAI/litellm/contents/cookbook?per_page=100&ref=main
```

### Twitter / LinkedIn details

@biplobsd11 / https://www.linkedin.com/in/biplob-sutradhar

**Comment by biplobsd** [comment]
@krrishdholakia

Could I make a PR to update the dead link? 

https://colab.research.google.com/github/BerriAI/litellm/blob/main/cookbook/LiteLLM_Azure_and_OpenAI_example.ipynb

**Comment by ghost** [comment]
@biplobsd that'd be great!
