### ISSUE TITLE
[Feature]: Support new openai `/v1/realtime` websocket endpoints 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#6045]
### The Feature

Used by OpenAI for their new gpt-4o audio model - `gpt-4o-realtime-preview-2024-10-01`

### Motivation, pitch

OpenAI-compatibility

**Comment by ghost** [comment]
Able to get azure endpoint working. 

OpenAI giving 401/403 errors.

**Comment by ghost** [comment]
Initial working commit made. 

Todo: 
- [x] Expose abstraction `litellm.arealtime(..)` 
- [x] Expose on Router `router.arealtime(..)` -> enables eventual loadbalancing b/w openai + azure 
- [x] Refactor proxy `/v1/realtime` endpoint to use router
