### ISSUE TITLE
[Bug]: Using Claude Dev: Conversation blocks and tool result blocks cannot be provided in the same turn.

### ISSUE THREAD

**Issue by hongbo-miao** [BerriAI/litellm#6053]
### What happened?

I tried to use Claude models (provided by AWS Bedrock) through LiteLLM proxy in the VSCode plugin Claude Dev.

Thanks @krrishdholakia for fixing https://github.com/BerriAI/litellm/issues/6007

I have deployed new `ghcr.io/berriai/litellm:main-v1.48.11`

Now I have a new error:

> APl Request Failed
> 400 litellm.BadRequestError: BedrockException - {"message":"messages.2.content: Conversation blocks and tool result blocks cannot be provided in the same turn."}
Received Model Group=claude-3-opus
Available Model Group Fallbacks=None

![image](https://github.com/user-attachments/assets/1da6b7f0-2fbb-42a1-be81-ecc44800e28a)

### Relevant log output

https://gist.github.com/hongbo-miao/8577107aba2db2cff0b577cede63e12b

### Twitter / LinkedIn details

@hongbo_miao

**Comment by ghost** [comment]
Added support for a dummy assistant message to prevent this error. Just do `litellm_settings::modify_params: true` and it should fix the issue - https://github.com/BerriAI/litellm/commit/52357a147cf3e75bd7ab45525789070b539b82ae
