### ISSUE TITLE
[Feature]: Have SageMaker Streaming adapter return error code instead of 200

### ISSUE THREAD

**Issue by mwl38765** [BerriAI/litellm#6054]
### The Feature

When using a SageMaker adapter in streaming mode, if an error is returned by the SageMaker endpoint, the response always returns as 200, while the error is embedded in the streamed data.  Is it possible to instead have the request return as the error code of the SageMaker error?

The desired behavior would be the same as what the OpenAI adapter does.  When making a streaming request to an OpenAI adapter, if the OpenAI endpoint returns an error, the request returns as the error code, not 200.

### Motivation, pitch

There are third party tools/sdks that are only checking the returned status code and not parsing the data stream.  For these tools, the current behavior can break them because they are expecting the streamed response of an LLM and not an error message.

**Comment by ishaan-jaff** [comment]
Hi @mwl38765 Can we do a ~10min call this/next week? Would love to learn how you're using litellm

Attaching our calendly for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by ishaan-jaff** [comment]
hi @mwl38765 - just following up on this, would love to get your feedback on LiteLLM
