### ISSUE TITLE
[Feature]: Add '--save' to proxy cli

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#606]
### The Feature

Add a '--save' flag to the cli command, to automatically persist params across restarts. 

cli flow: 
```shell
litellm --model ollama/llama2 \
  --api_base http://localhost:11434 \
  --max_tokens 250 \
  --temperature 0.5 \
  --save
```

### Motivation, pitch

It's a bit odd to need to create a config file just to persist model/litellm params across restarts, when the cli flow is so much smoother.

**Comment by isaac-chung** [comment]
Hi, spoke with Ishaan briefly on LinkedIn so decided to take a look and see if I can contribute. Seems like this is already completed?

**Comment by ghost** [comment]
closing as this is deprecated.
