### ISSUE TITLE
[Feature]: Add callbacks / logging for /realtime api 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#6081]
### The Feature

<img width="593" alt="Screenshot 2024-10-05 at 5 14 06 PM" src="https://github.com/user-attachments/assets/2ffc4148-1e54-45fa-8072-cf294c06328e">

### Motivation, pitch

-

**Comment by yuyuma** [comment]
@ishaan-jaff responding to your Discord question here.

Regarding your question on litellm proxy vs python SDK, I think proxy?  For chat completions endpoint we use essentially this setup (https://docs.litellm.ai/docs/observability/langfuse_integration), except we set the success_callback to langfuse in the proxy yaml that we deploy ourselves. We pass in custom langfuse metadata so each trace in langfuse is tagged appropriately.

For realtime API I think everyone is still trying to figure out how to work with events over websockets. I would love basic logging as soon as success_callback is set.  Just like chat completions I'm also interested in passing in custom langfuse params so we can customize how these traces are stored in langfuse.
