### ISSUE TITLE
[Feature]: Have `additional_drop_params` accept nested params

### ISSUE THREAD

**Issue by michielree** [BerriAI/litellm#6088]
### The Feature

Have the `additional_drop_params` parameter accept nested parameters.

### Motivation, pitch

Currently, `completion`'s `additional_drop_params` only allows you to drop top-level keyword arguments from the OpenAI calls. I'm running into issues where I have proxy in front of a vLLM instance that does not accept the following:

```
tools = [
    {
        "type": "function",
        "function": {
            "name": "structure_output",
            "description": "Send structured output back to the user",
            "strict": True,
            "parameters": {
                "type": "object",
                "properties": {
                    "reasoning": {"type": "string"},
                    "sentiment": {"type": "string"},
                },
                "required": ["reasoning", "sentiment"],
                "additionalProperties": False,
            },
            "additionalProperties": False,
        },
    }
]
tool_choice = {"type": "function", "function": {"name": "structure_output"}}
prompt = """
Analyze the sentiment of the following text: 'I'm feeling good'.
Classify it as either positive, negative, or neutral.
Provide your reasoning as well.
"""
response = client.chat.completions.create(
    model=model,
    messages=[{"role": "user", "content": prompt}],
    tools=tools,
    tool_choice=tool_choice,
)
```
because vLLM does not accept arguments `additionalProperties` and `strict` at the `function` level.  Ideally, users would be able to define `additional_drop_params` as `[["tools", "function", "strict"], ["tools", "function", "additionalProperties"]]` in their LiteLLM proxy config file or the Python SDK.

### Twitter / LinkedIn details

https://www.linkedin.com/in/michiel-van-der-ree-8669482a/

**Comment by ghost** [comment]
Maybe we can also just expose a `hosted_vllm/` route, so we can handle such edge cases out of the box @michielree

**Comment by ghost** [comment]
> [["tools", "function", "strict"],

this is a bit off since tools is a list, so technically it would be `tools[0]["function"]["strict"]`

**Comment by michielree** [comment]
You're completely right re: tools being a list, oversight on my part. A `hosted_vllm/` route would be great!

**Comment by ghost** [comment]
Pushed here - https://github.com/BerriAI/litellm/commit/e3d84fd42ccb0b14b8dae7c2641c073d4bb8e235

Should be live by EOD. 

---
@michielree can we do a ~10min call sometime this/next week? Would love to learn how we can improve litellm for you/your team! 

Attaching my calendly for convenience - https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by michielree** [comment]
Thanks so much @krrishdholakia! I scheduled a call through calendly, closing this issue for now.

**Comment by ghost** [comment]
This is now live @michielree

**Comment by michielree** [comment]
Thanks so much @krrishdholakia!
