### ISSUE TITLE
[Bug]: LitelLLM Proxy Custom API Server not working for image generation

### ISSUE THREAD

**Issue by mickymics** [BerriAI/litellm#6097]
### What happened?

I have deployed stabilityai/stable-diffusion-xl-base-1.0 model with onnx runtime image serving through kServe ML Server. LiteLLM proxy seats in front of the KServe ML Server to route the request based on the model name in proxy config.

Even I have added debugging log but that just showing one entry -- RESPONSE OK.
**No other log statement. Is the following function even getting called when I invoke the curl command:**

_curl 'http://litellm-service.litellm.svc.cluster.local:4000/images/generations' \
--header 'Content-Type: application/json' \
--data '{
  "model": "my-custom-model",
  "prompt": "A cute baby sea otter"
}'_

This is the sample mock **custom_handler.py**
import logging
import litellm
from litellm import CustomLLM
logging.basicConfig(filename='/app/debug.log', level=logging.INFO)
    
class MyCustomLLM(CustomLLM):
    def __init__(self):
        super().__init__()

    def image_generation(self, *args, **kwargs) -> dict:
            logging.info("1")
            logging.info("Received args:", args)
            url = "**http://text2image.fm.svc.cluster.local/v1/models/stable-diffusion-xl-base-1.0:predict**"
            data = {
                "prompt": kwargs.get("prompt", ""),
                "other_parameters": kwargs.get("other_parameters", {})
            }
            response = requests.post(url, json=data)
            logging.info("Raw response content:", response.text)
            response_data = response.json()
            logging.info("Parsed response data:", response_data)
            return response_data

custom_image_llm = MyCustomLLM()

**proxy_config.yaml:**

apiVersion: v1
data:
  proxy_config.yaml: |
    model_list:
      - model_name: my-custom-model
        litellm_params:
          model: my-custom-llm/my-model
    litellm_settings:
      drop_params: True
      num_retries: 3
      request_timeout:
      allowed_fails: 3
      cache: False
      custom_provider_map:
      - {"provider": "my-custom-llm", "custom_handler": custom_handler.my_custom_llm}
kind: ConfigMap

This is very urgent blocker. We are using LiteLLM proxy heavily for OPEN AI compantible endpoints with vLLM. But this is where we stuck.

**Comment by ghost** [comment]
Will add support for custom image generation calls
