### ISSUE TITLE
fake stream output if model doesn't support it but stream=True

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#61]
<img width="600" alt="Screenshot 2023-08-07 at 1 13 55 PM" src="https://github.com/BerriAI/litellm/assets/17561003/7c20ea22-3bdb-4743-8ea3-80f4a4eda743">

**Comment by ghost** [comment]
if somebody used us assuming we'd return a stream (generator object i believe) and we returned a dict, we'd break in code for them.

**Comment by zakhar-kogan** [comment]
Does this need a separate model flag, e.g., `supports_streaming = True`, to distinguish?

**Comment by ghost** [comment]
Not really - we already have a customstreamwrapper, we can just add this as default logic and send all model results there if stream=true

**Comment by ghost** [comment]
done
