### ISSUE TITLE
[Bug]: /user/info API endpoint - `page_size` not respected

### ISSUE THREAD

**Issue by Jacobh2** [BerriAI/litellm#6100]
### What happened?

Not sure when it happened, but when I pulled the latest `ghcr.io/berriai/litellm-database:main-latest` image, the `/user/info` endpoint stopped working as expected:

1. The swagger docs are out of sync: Mentions a previously available parameter `view_all`, which no longer is available in the swagger docs. Is this a valid flag any more?

    <img width="1430" alt="image" src="https://github.com/user-attachments/assets/6832faf8-065c-41f9-866c-180def92144c">

2. When doing a call to `http://localhost:4000/user/info?page_size=100&page=0` or `http://localhost:4000/user/info?page_size=100&page=20000` yields the same result, which makes no sense. Previous logic returned an empty list when requesting a page where there weren't any more users to show.

    With this logic, it _seems_ like all users are always returned? If that is the case, please remove the `page_size` and `page` parameters since they are very confusing.

**How to reproduce:**

1. Spin up the latest docker image mentioned above
2. Make request to `http://localhost:4000/user/info?page_size=100&page=0` and `http://localhost:4000/user/info?page_size=100&page=20000` and notice that you get the same result.

**Proposed solution:**

Please make it very clear in the documentation what endpoint is meant to be used for what: The LiteLLM Proxy Swagger docs seems to be in need of some love ❤️  and also to update/cleanup the pydantic objects used for the endpoints such that the swagger docs does not render into what the provided screenshot shows.

**Comment by ghost** [comment]
I believe the `view_all` functionality has been migrated to a separate `/user/list` endpoint - i can see page_Size is used + respected there. - https://litellm-api.up.railway.app/#/Internal%20User%20management/get_users_user_list_get

As an action item, i will clean up the params, and update the docstring to make the change clear.

**Comment by Jacobh2** [comment]
Switching to using the user/list works, and is more similar to the other object's endpoints. But the api is currently very confusing and a bit cluttered. Having clear crud functionality using proper restful naming + http method useage would be great.

This means using put for updates, delete for delete etc. Also very common to have the endpoints not named "list" but instead simply the respective object and with no filters applied, it returns the list of objects.
