### ISSUE TITLE
[Bug]: Using Claude Dev: Conversation blocks and tool result blocks cannot be provided in the same turn.

### ISSUE THREAD

**Issue by hongbo-miao** [BerriAI/litellm#6105]
### What happened?

I tried to use Claude models (provided by AWS Bedrock) through LiteLLM proxy in the VSCode plugin Claude Dev.

Thanks @krrishdholakia for fixing at https://github.com/BerriAI/litellm/issues/6053 (I saw it published in v1.48.15)

I deployed latest `ghcr.io/berriai/litellm:main-v1.48.18` which I think include the fix.

However, I still have error:

> APl Request Failed
> 400 litellm.BadRequestError: BedrockException - {"message":"messages.2.content: Conversation blocks and tool result blocks cannot be provided in the same turn."}
. Enable 'litellm.modify_params=True' (for PROXY do: `litellm_settings::modify_params: True`) to insert a dummy assistant message and fix this error.
Received Model Group=claude-3-opus
Available Model Group Fallbacks=None

![image](https://github.com/user-attachments/assets/f99fb2d3-45e9-4a45-ac3e-2b42a12c8f8c)

![image](https://github.com/user-attachments/assets/a257b537-ef18-47e6-8a42-c99eb4b77acb)

### Relevant log output

The log using latest version v1.48.18 is at https://gist.github.com/hongbo-miao/03b3bb1dd9585d185611e4b848123df6

### Twitter / LinkedIn details

@hongbo_miao

**Comment by hongbo-miao** [comment]
To reproduce this error, you could clone this repo https://github.com/hongbo-miao/hongbomiao.com
In Claude Dev, I am asking "What is this file?" question on this file `computer-vision/hm-open3d/src/main.py`

**Comment by ghost** [comment]
This is not a bug. Read the error message. You have to enable liteLLM to modify the params. 

If you're using the proxy do:

```
litellm_settings:
   modify_params: true 
```

**Comment by hongbo-miao** [comment]
Thanks @krrishdholakia ! It works now!
I tried to search `modify_params`, however it is not listed at https://docs.litellm.ai/docs/proxy/configs#litellm_settings---reference
It would be great to include that, thanks!

**Comment by satyaloka93** [comment]
Is this on the server side or client? I tried with Autogen's [OpenAIChatCompletionClient](https://microsoft.github.io/autogen/dev//user-guide/core-user-guide/components/model-clients.html), as 'extra_create_args', however it didn't overcome this error message, and failure after a couple of agent interactions. Code works fine with local llms served by llama-server.

**Comment by ghost** [comment]
Hey @satyaloka93 this is a currently a global param only, so needs to be done server side 

Are you trying to set this dynamically (i.e. per request)?

**Comment by satyaloka93** [comment]
Hi, I don't control the server as it's hosted by our organization. They are running an instance of Claude 3.5 Sonnet. The only thing I could think to do on my end is using the extra_create_args in the Autogen client. Perhaps this just one work, if it's server only.
