### ISSUE TITLE
[Bug]: Default Team still rendered Even when disabled

### ISSUE THREAD

**Issue by ncecere** [BerriAI/litellm#6116]
### What happened?

We have deployed LiteLLM and disabled the default team and have SSO enabled.  All users are assigned to the team "navigator".  When users first login and try to create a key they only see the single team they are assigned to.

![image](https://github.com/user-attachments/assets/e747145f-7339-4aa9-ba51-48cc67b9eb06)

but if navigate to a different section such as test key and back to virtual keys it will now show me the "Default Team" even though it is disabled.

![image](https://github.com/user-attachments/assets/bd6b4636-2dac-4294-bde0-c49c4cdcda6a)

Users can also create keys in the Default team, which should be there, and use them.

The expected behavior I would expect is that the Default team would never be visible since it is disabled.  I don't know what specific I can provide to help with this, i seems to be an issue only in the UI.  Please let me know if I need to provide any additional information.

**Comment by ncecere** [comment]
Sorry I can't spell :( it's a problem

**Comment by ishaan-jaff** [comment]
I have the same problem @ncecere, @krrishdholakia can confirm

**Comment by ghost** [comment]
@ishaan-jaff are you picking up this issue?

**Comment by ishaan-jaff** [comment]
@krrishdholakia sure I can do it - will have it done in 24 hours

**Comment by ishaan-jaff** [comment]
fixed here @ncecere  https://github.com/BerriAI/litellm/pull/6134
