### ISSUE TITLE
[Feature]: Use member_max_budget or default_internal_user_max_budet for Key generation Max Budget

### ISSUE THREAD

**Issue by ncecere** [BerriAI/litellm#6117]
### The Feature

When generating a Key in the UI if `member_max_budget` or `default_internal_user_max_budget` are set use them as the Max Budget limit when generating a key.  

- `default_internal_user_max_budget` would be used for the default team
- `member_max_budget` would be used for created teams

![image](https://github.com/user-attachments/assets/a3a4f05c-934e-477a-b634-e4380d3312c0)

### Motivation, pitch

When generating key in a self service method it would prevent confusion for users.  Th current pattern uses team_max_budget not user limits.  this allows users to generate keys that have a higher higher budget then is allocated to them. for example:

- A team could have a max budget of $100 dollars
- A member in that team could have a max budget of $10 set for them in that team
- When the user goes to create a key in that team, they can set the budget of the key to $100 dollars even though they can only use $10
- This will cause confusion for the user because they will think that they still have $90 dollars available to them not knowing they have hit a limit.

I think this will help clear up confusion for Self Service users loging into the UI.

**Comment by krrishdholakia** [comment]
I think what we can do is return the `Default Team` values, as a part of the `/team/list` endpoint. 

This would allow the ui to then index into that object, and get the default values for the user.

**Comment by ghost** [comment]
fixed default team to use user's max budget 
<img width="654" alt="Screenshot 2024-10-08 at 3 25 17 PM" src="https://github.com/user-attachments/assets/b5efbd1a-09a0-4d5a-94ef-ec9c80caee18">

**Comment by ghost** [comment]
now showing user's max budget within a team, if it's set 
<img width="819" alt="Screenshot 2024-10-08 at 4 36 15 PM" src="https://github.com/user-attachments/assets/13124ea0-c43b-4883-9110-f4204a995ae6">
