### ISSUE TITLE
[Feature]: precise google gemini token counts

### ISSUE THREAD

**Issue by jguokion** [BerriAI/litellm#6118]
### The Feature

Use the info about token counts directly provided by google gemini api, not approximation

### Motivation, pitch

Currently the cost for google model is estimated based on  4 chars per token, which is a very rough approximation. 
https://github.com/BerriAI/litellm/issues/4165
Can you use the token counts info directly from google api? 
https://ai.google.dev/gemini-api/docs/tokens?lang=python
https://www.googlecloudcommunity.com/gc/AI-ML/Please-share-Gemini-tokenize-information/m-p/709495

**Comment by ghost** [comment]
@jguokion 

>Use the info about token counts directly provided by google gemini api, not approximation

We use the token counts given by gemini. Character-based cost tracking if required (e.g. by vertex ai) is done by counting characters. 

See here - https://github.com/BerriAI/litellm/blob/d1760b1b049daf5faf1e51ac05ba32112a281b9e/litellm/litellm_core_utils/llm_cost_calc/google.py

**Comment by ghost** [comment]
I've updated my comment on the previous issue as well. Let me know if there's anything more that we need to do here.

**Comment by jguokion** [comment]
where is the code snippet that you call the method token counts or something like that? How do you feed `prompt_tokens` and `completion_tokens`?

**Comment by ghost** [comment]
> you call the method token counts or something

We don't need to. Gemini returns the token information in the response. https://ai.google.dev/api/generate-content#UsageMetadata
