### ISSUE TITLE
[Bug]: LiteLLM ddtrace incompatibility

### ISSUE THREAD

**Issue by doudoujay** [BerriAI/litellm#6123]
### What happened?

![image](https://github.com/user-attachments/assets/828fbd51-3dd8-4e4f-9684-da55a1beea65)

we got lot of error due to the new ratelimit thing introduced and incompatible with ddtrace.
This could be related to https://github.com/BerriAI/litellm/issues/5957

LiteLLM proxy ver: `1.48.9`

**Comment by ishaan-jaff** [comment]
cc @krrishdholakia any chance you could take a look at this

**Comment by ghost** [comment]
i'm confused - this error doesn't look like it's coming from within the litellm library 

<img width="599" alt="Screenshot 2024-10-08 at 12 25 26 PM" src="https://github.com/user-attachments/assets/525ddd8c-b66c-4a7e-9970-cc080f658cb2">

what does your client code look like?

**Comment by ghost** [comment]
i believe this is caused by us returning 'None' if the key isn't present. 

<img width="928" alt="Screenshot 2024-10-08 at 12 26 42 PM" src="https://github.com/user-attachments/assets/549e645d-ae42-4a23-b79b-41574a901937">


Seeing how the client code is working will probably help figure out what would work here instead

**Comment by doudoujay** [comment]
<img width="1236" alt="image" src="https://github.com/user-attachments/assets/6d851692-5fe2-4b5e-9d96-611d7af15bc5">
x-ratelimit-limit-requests is `None`

![image](https://github.com/user-attachments/assets/50c33b54-cd6d-41da-9546-f0df25b0789a)

and this is causing problem from side of ddtrace - 
![image](https://github.com/user-attachments/assets/0db138b0-7868-4125-866a-c1d982b91a5b)

In this case int(None) would throw error
![image](https://github.com/user-attachments/assets/f2c0e5b5-2bd5-4710-a845-47b0ed162c93)

@krrishdholakia

**Comment by ghost** [comment]
Oh! it's the fact that it's stringified, which makes it assert True on the None check

**Comment by ghost** [comment]
although i guess the assumption is that if the value isn't provided, don't return the field

**Comment by doudoujay** [comment]
can we make the default behavior returning None rather than returning "None"?
or just done set anything if the value is None or "None" on litellm side @krrishdholakia

**Comment by ghost** [comment]
> or just done set anything if the value is None

i think this is what we'll need to do. don't think we can return non-str headers

**Comment by doudoujay** [comment]
> > or just done set anything if the value is None
> 
> 
> 
> i think this is what we'll need to do. don't think we can return non-str headers 

Do you have an ETA on this? @krrishdholakia

**Comment by ghost** [comment]
probably EOD @doudoujay
