### ISSUE TITLE
[Bug]: Starting and using an Ollama local model (like mistral-openorca) takes 'forever' on MBP M1 Max

### ISSUE THREAD

**Issue by ChristianWeyer** [BerriAI/litellm#613]
### What happened?

I am running
`litellm --model ollama/mistral-openorca`

And it takes several minutes to start up.

Then I do
`litellm --test`
in another terminal window, and it also takes forever to complete.

### Relevant log output

```shell
No log output.
```

**Comment by ChristianWeyer** [comment]
A reboot of the machine solved it 🤷🏼‍♂️

**Comment by ghost** [comment]
Sounds good! @ChristianWeyer
