### ISSUE TITLE
[Bug]: Gemini cost not being calculated correctly. 

### ISSUE THREAD

**Issue by pedroallenrevez** [BerriAI/litellm#6133]
### What happened?

The cost is not being calculated correctly. There are no warnings, no errors, nothing. The input price is always 0 for gemini models, when using tokens

I don't get why the interface is so random. 
Better not to give a price than counting tokens wrong.

### Relevant log output

```shell
cost_per_token(model="gemini-1.5-pro-002", prompt_tokens=1000, completion_tokens=1000, custom_llm_provider="vertex_ai_beta")
(0.005, 0.015000000000000001)
```

Expected Error and well
```shell
cost_per_token(model="gpt-4o", prompt_tokens=1000, completion_tokens=1000, custom_llm_provider="vertex_ai")
<Error>
```

Random Price for an unknown provider, no error, no nothing :joy:
```shell
cost_per_token(model="gpt-4o", prompt_tokens=1000, completion_tokens=1000, custom_llm_provider="adsfdsafdsafdsaf")
(0.005, 0.015000000000000001)
```

Input cost 0
```shell
cost_per_token(model="gemini-1.5-pro-002", prompt_tokens=1000, completion_tokens=1000)
(0.0, 0.0037500000000000003)
```

Putting characters, as per gemini documentation, they count by tokens. Only works for inputs tho :shrug:
```shell
cost_per_token(model="gemini-1.5-pro-002", prompt_characters=1000, completion_characters=1000, prompt_tokens=1000, completion_tokens=1000)
(0.00125, 0.0037500000000000003)
```

provider/model_name
```shell
cost_per_token(model="vertex_ai/gemini-1.5-pro-002", prompt_tokens=1000, completion_tokens=1000)
(0.0, 0.0037500000000000003)
```

**Comment by ghost** [comment]
if you enable `litellm.set_verbose=True` you can see the debug statements for this

**Comment by ghost** [comment]
> cost_per_token(model="gemini-1.5-pro-002", prompt_tokens=1000, completion_tokens=1000, custom_llm_provider="vertex_ai_beta")

```
Looking up model=gemini-1.5-pro-002 in model_cost_map
Success: model=gemini-1.5-pro-002 in model_cost_map
prompt_tokens=1000; completion_tokens=1000
Returned custom cost for model=gemini-1.5-pro-002 - prompt_tokens_cost_usd_dollar: 0.005, completion_tokens_cost_usd_dollar: 0.015000000000000001
```

Your output is using the mapped cost (which is a conversion of google's cost per character to tokens where 1 char ~ 4 tokens) - https://github.com/BerriAI/litellm/blob/60baa65e0ec4827d27c3b15c14a4f921b1e66121/model_prices_and_context_window.json#L2138

**Comment by ghost** [comment]
in the gpt-4o case, again it looks like it found the model in the model cost map, and used the mapped pricing. 
```
Looking up model=gpt-4o in model_cost_map
Success: model=gpt-4o in model_cost_map
prompt_tokens=1000; completion_tokens=1000
Returned custom cost for model=gpt-4o - prompt_tokens_cost_usd_dollar: 0.005, completion_tokens_cost_usd_dollar: 0.015000000000000001
```

https://github.com/BerriAI/litellm/blob/60baa65e0ec4827d27c3b15c14a4f921b1e66121/model_prices_and_context_window.json#L26

The issue here seems to be that it should have considered the llm provider given (adsfdsafdsafdsaf) != the mapped llm provider (openai)

**Comment by ghost** [comment]
> cost_per_token(model="gemini-1.5-pro-002", prompt_tokens=1000, completion_tokens=1000)

and 

> cost_per_token(model="vertex_ai/gemini-1.5-pro-002", prompt_tokens=1000, completion_tokens=1000)
(0.0, 0.0037500000000000003)

Caused by prompt_character default value being 0. fixing now.

**Comment by ghost** [comment]
> cost_per_token(model="gemini-1.5-pro-002", prompt_tokens=1000, completion_tokens=1000)
(0.0, 0.0037500000000000003)

another issue was double counting the *4 conversion b/w cost per char and cost per token for google. fixing now.

**Comment by ghost** [comment]
> Putting characters, as per gemini documentation, they count by tokens. Only works for inputs tho 🤷

cost_per_token(model="gemini-1.5-pro-002", prompt_characters=1000, completion_characters=1000, prompt_tokens=1000, completion_tokens=1000)
(0.00125, 0.0037500000000000003)

not sure what you mean by this @pedroallenrevez 

This seems to calculate correctly. 

1000 * 0.00000125 (input_cost_per_character for gemini-1.5-pro-002) = 0.00125

1000 * 0.00000375 (output_cost_per_character for gemini-1.5-pro-002) = 0.00375

**Comment by ghost** [comment]
Oh i see, it seems like the gemini-1.5-pro pricing got updated 2 days ago - 
<img width="991" alt="Screenshot 2024-10-09 at 1 37 38 PM" src="https://github.com/user-attachments/assets/b02e89cd-f343-4ec2-8122-cb5b4539cad8">


is this what you were referring to? @pedroallenrevez
