### ISSUE TITLE
[Bug]: Docs claim only async success callbacks

### ISSUE THREAD

**Issue by entropi** [BerriAI/litellm#6137]
### What happened?

[The custom callback docs](https://docs.litellm.ai/docs/observability/custom_callback#async-callback-functions) claim that only succcess_callback can be async, but looks like this is out of date. I didn't check all, but it looks like at least input_callback supports async now as well.

**Comment by ghost** [comment]
> least input_callback supports

Nope not yet. 

Not sure i follow the issue, but i can see the custom callback shows the async functions 

<img width="1035" alt="Screenshot 2024-10-09 at 9 18 29 AM" src="https://github.com/user-attachments/assets/041e83af-59dc-41bf-af83-642e3c8437e9">

**Comment by ghost** [comment]
Closing for now as i think? the docs already address this, but let me know if i'm mistaken @entropi

**Comment by entropi** [comment]
@krrishdholakia I read the docs as saying that you can only use async callbacks for .success_callback, but not the others (and that used to be true from looking at the util.py commit history)

> LiteLLM currently supports just async success callback functions for async completion/embedding calls.

But it looks like the other call back properties also support them.

**Comment by ghost** [comment]
<img width="877" alt="Screenshot 2024-10-09 at 9 49 33 AM" src="https://github.com/user-attachments/assets/17cb2576-7467-4c4c-b3ef-4da953d99475">

Hey @entropi this is if you want to pass the old custom function approach (where it's just 1 function being passed in), not the customlogger class

Our docs can be better here. What would have made this clearer?

**Comment by entropi** [comment]
hey @krrishdholakia yup, that's what we're doing, passing single functions to success_callback and input_callback, and I am currently updating our `input_callback` to be async.

**Comment by ghost** [comment]
hey @entropi we don't currently support input_callback as async - it'll require some instrumentation

curious how're you using `input_callback`? trying to see if there's a way we can help here

**Comment by entropi** [comment]
Thanks for the info. Our entire backend is now asyncio, so for consistency it would be nice if all callbacks supported async (be it via the custom callback class or the more specific callback fields). This specific one isn't pressing now as we cleared any of the I/O from the callback. 

Right now we do some metadata cleanup before the api call to remove some noise for tracing and the like.
