### ISSUE TITLE
[Feature]: Add new Anthropic features

### ISSUE THREAD

**Issue by Clad3815** [BerriAI/litellm#6148]
### The Feature

They made an update yesterday

![image](https://github.com/user-attachments/assets/e74f5dc2-7537-452d-bd72-ed9a5bcf7cde)

https://x.com/alexalbert__/status/1844039706524422585

### Motivation, pitch

This will avoid to doing workaround

**Comment by ghost** [comment]
is there something specific we need to change here? `disable_parallel_tool_use` should just work 

@Clad3815

**Comment by Clad3815** [comment]
@krrishdholakia The disable_parallel_tool_use is dropped with Anthropic no ? https://github.com/BerriAI/litellm/blob/main/litellm/llms/anthropic/chat/transformation.py#L76


And for the other one, i saw that in the code: https://github.com/BerriAI/litellm/blob/main/litellm/llms/anthropic/chat/transformation.py#L76

That's why I suggest it, but I'm not sure if it's used or not

**Comment by Clad3815** [comment]
Wrong second url, I mean this one: https://github.com/BerriAI/litellm/blob/d28c6b390ca19d50ba52985988b4e005383ae281/litellm/llms/prompt_templates/factory.py#L831

**Comment by ghost** [comment]
Closing in favor of https://github.com/BerriAI/litellm/issues/6456
