### ISSUE TITLE
[Bug]: text_completion please remove the debug message / add response_ms

### ISSUE THREAD

**Issue by solyarisoftware** [BerriAI/litellm#615]
### What happened?

Hi
Some minor bugs on the text_completion funtion:

1
please remove the (maybe for debug) print:
https://github.com/BerriAI/litellm/blob/abd12e1e9b43633787eee8d2d57bff7f6d91f8b8/litellm/main.py#L1559

2
The response returned by the text_completion has these attributes:

```python
{'id': 'chatcmpl-89yXo1qWLb6nHwNDoMKkfBZpzxIWR', 'object': 'text_completion', 'created': 1697388376, 'model': 'gpt-35-turbo', 'choices': [{'text': '"Benvenuti alla taverna italiana, dove il cibo è come la famiglia" (Welcome to the Italian tavern, where the food is like family)', 'index': 0, 'logprobs': None, 'finish_reason': 'stop'}], 'usage': <OpenAIObject at 0x7f7a03d12f30> JSON: {
  "completion_tokens": 33,
  "prompt_tokens": 20,
  "total_tokens": 53
}}
```
In the response I do not see the attribute `response_ms` you added in the completion function, see:
https://github.com/BerriAI/litellm/issues/389#issuecomment-1728728554

For coherence I thin the text completion response could be contains the reponse_ms attribute too.

Thanks
giorgio

### Twitter / LinkedIn details

twitter: @solyarisoftare linkedin: www.linkedin.com/in/giorgiorobino

**Comment by ghost** [comment]
print statement removed - 4424aaf69fcf977e74bd81828724b5f1790b1b88

thanks for raising this @solyarisoftware
