### ISSUE TITLE
[Feature]: Add output format for text_completion() to docstring. 

### ISSUE THREAD

**Issue by solyarisoftware** [BerriAI/litellm#616]
LiteLLM home page states:

> Guarantees [consistent output](https://docs.litellm.ai/docs/completion/output), text responses will always be available at ['choices'][0]['message']['content']

The detail is described here: https://docs.litellm.ai/docs/completion/output

Following the above documentation, text response are available at `['choices'][0]['message']['content']` 
but this is not true in case of text_completion() LiteLLM function, where output is available at `['choices'][0]['text']`

Is not clear to me the output format LiteLLM requirement: 
A => the UNIQUE LiteLLM output format is `['choices'][0]['message']['content']`
B=>  the LiteLLM output format FOLLOWS OpenaI formats.

So, if A is true, 
the text_completion function would return `['choices'][0]['message']['content']`

Instead if B is true, text_completion is fine but the https://docs.litellm.ai/docs/completion/output documentation page would be updated explaining that 2 different outputs are available.

Last but not least I'd add in the documentation the availability of `response_ms` attribute, just with an request / response complete example. See: https://github.com/BerriAI/litellm/issues/389#issuecomment-1728728554

Thanks
giorgio

twitter: @solyarisoftare linkedin: www.linkedin.com/in/giorgiorobino

**Comment by ghost** [comment]
@solyarisoftware Not a bug. text_completion maps to the Openai.Completion.create format, which has a different I/O (accepts prompt, returning `["choices"]["text"]`. 

See: https://platform.openai.com/docs/api-reference/completions/object

I understand this wasn't clear to you, so maybe we can add this in our docstring.

**Comment by ghost** [comment]
Done - 1a09bbd4a9c08d77d0cc6150561aa5e71e3be834.

**Comment by solyarisoftware** [comment]
thanks @krrishdholakia adding the docstring helps. Neverthelss I'd also integrate the tutorial page: 
https://docs.litellm.ai/docs/tutorials/text_completion#using-litellm-in-the-text-completion-format

with a simple usage example. 
thanks again
giorgio
