### ISSUE TITLE
[Bug]: Requests to azure/gpt-4o Not Logged in LiteLLM_SpendLogs After Upgrade to 1.48.17-stable

### ISSUE THREAD

**Issue by realmorrisliu** [BerriAI/litellm#6164]
### What happened?

**Issue Summary:**
After upgrading from 1.44.7 to 1.48.17-stable, requests to `azure/gpt-4o` are no longer logged in `LiteLLM_SpendLogs`, while other models are unaffected.

**Details:**
From some preliminary investigation, I **suspect** the issue might be related to the `cost_per_token` function in `litellm/llms/AzureOpenAI/cost_calculation.py`. This is just my guess to help in troubleshooting the root cause. 

The function calls `get_model_info`, and in the case of `azure/gpt-4o`, it tries to fetch the model info from `model_prices_and_context_window_backup.json`. However, when the model is `azure/gpt-4o`, the API response looks like this:
```python
ChatCompletion(id='chatcmpl-XXXXX', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content="In twilight's gentle, fading light,\nWhere day and night embrace,\nThe world turns soft, the stars ignite,\nIn heaven's vast, calm space.\n\nWhispers of the evening breeze,\nDance through the fields of green,\nAmong the rustling, swaying trees,\nA tranquil, silver sheen.\n\nNight arrives on velvet wings,\nWith dreams in soft array,\nAnd in the hush, the heart now sings,\nOf promises made at day.", refusal=None, role='assistant', function_call=None, tool_calls=None))], created=1728644164, model='gpt-4o-2024-05-13', object='chat.completion', service_tier=None, system_fingerprint='fp_xxxxxxxxxx', usage=CompletionUsage(completion_tokens=88, prompt_tokens=17, total_tokens=105), prompt_filter_results=[{'prompt_index': 0, 'content_filter_results': {'jailbreak': {'filtered': False, 'detected': False}}}])
```

The response shows `model='gpt-4o-2024-05-13'`, which could cause `get_model_info` to query `azure/gpt-4o-2024-05-13` instead of `azure/gpt-4o`. However, `model_prices_and_context_window_backup.json` doesn't contain `azure/gpt-4o-2024-05-13`, so `cost_per_token` cannot correctly retrieve the `input_cost_per_token` and `output_cost_per_token`, resulting in the failure to log spending data for this model.

**Request:**
Please investigate this issue and determine the true cause, as my analysis may not be fully accurate. A fix for this would be highly appreciated.

**Comment by realmorrisliu** [comment]
@ishaan-jaff any suggestion to solve this problem?

**Comment by ishaan-jaff** [comment]
hi @realmorrisliu  - this should fix it https://github.com/BerriAI/litellm/pull/6174
