### ISSUE TITLE
[Feature]: Berock Llama 3.2 support

### ISSUE THREAD

**Issue by jleatham** [BerriAI/litellm#6168]
### The Feature

Add model support for AWS Bedrock Llama 3.2 using Cross Regional Inference Support.
[Bedrock Llama 3.2](https://aws.amazon.com/blogs/aws/introducing-llama-3-2-models-from-meta-in-amazon-bedrock-a-new-generation-of-multimodal-vision-and-lightweight-models/)

### Motivation, pitch

Several customers are using LiteLLM as a proxy and are interested in production workloads using Bedrock with Llama 3.2 as the preferred model.

**Comment by ghost** [comment]
This is already supported + tested. https://github.com/BerriAI/litellm/blob/11f9df923a7d52f120ab452c4d447c89e8921f86/tests/local_testing/test_bedrock_completion.py#L1233

Where in docs did you look for this? @jleatham

**Comment by ghost** [comment]
closing as this is already supported

**Comment by dotalchemy** [comment]
> This is already supported + tested.
> 
> https://github.com/BerriAI/litellm/blob/11f9df923a7d52f120ab452c4d447c89e8921f86/tests/local_testing/test_bedrock_completion.py#L1233
> 
> Where in docs did you look for this? @jleatham

Top of [this page](https://docs.litellm.ai/docs/providers/bedrock) states "Anthropic, Amazon Titan, A121 LLMs are Supported on Bedrock"

Though, granted, the list further down under https://docs.litellm.ai/docs/providers/bedrock#supported-aws-bedrock-models lists many more. Perhaps just needs the sentence at the top of that page updated to reflect supported LLM providers.

**Comment by jleatham** [comment]
Thanks.  I updated to latest and see that it is available.
