### ISSUE TITLE
[Bug]: how to use prompt caching with GPT-4o?

### ISSUE THREAD

**Issue by ramsey-coding** [BerriAI/litellm#6171]
### What happened?

How to use prompt caching with GPT-4o? Litellm does not seem to support prompt cachching for LLMs such as GPT-4o, GPT-4o mini.

**Comment by ishaan-jaff** [comment]
We support prompt caching @ramsey-coding https://docs.litellm.ai/docs/completion/prompt_caching

**Comment by ghost** [comment]
prompt caching happens automatically by openai. no changes are required to your client code. https://docs.litellm.ai/docs/completion/prompt_caching#quick-start
