### ISSUE TITLE
[Bug]: Paging on "Internal Users"

### ISSUE THREAD

**Issue by wcw-cmu-edu** [BerriAI/litellm#6188]
### What happened?

A bug happened!

Prev/Next on the Internal Users page is getting the count wrong.  It may start off with the wrong count (i.e. 'Showing Page 2 of 1'). It allows you to click next even though  and then when you click next, you'll get 'Showing Page 8 of 0'
<img width="439" alt="Screenshot - prev next" src="https://github.com/user-attachments/assets/1c42e67a-5f8f-4f0a-87fd-389dbcd9d0a7">

**Comment by ishaan-jaff** [comment]
this is fixed on the latest main-stable version 1.50.0 + @wcw-cmu-edu , can you try bumping and see if it's fixed for you ?

**Comment by ishaan-jaff** [comment]
marking this as fixed on latest
