### ISSUE TITLE
[Bug]: Internal Users UI missing delete

### ISSUE THREAD

**Issue by wcw-cmu-edu** [BerriAI/litellm#6191]
### What happened?

A bug happened!

The Internal Users UI list is missing a delete button. There appears to be no way to delete a user from the web UI.

**Comment by ishaan-jaff** [comment]
<img width="1280" alt="Screenshot 2024-10-26 at 8 31 26 AM" src="https://github.com/user-attachments/assets/a1ee15ce-a52e-48aa-841a-f9d8dc7a2240">
<img width="1173" alt="Screenshot 2024-10-26 at 8 32 00 AM" src="https://github.com/user-attachments/assets/2f14cc62-d60d-45dd-b257-55e968761616">
