### ISSUE TITLE
[Feature]: WebUI show timestamp on virtual keys

### ISSUE THREAD

**Issue by wcw-cmu-edu** [BerriAI/litellm#6196]
### The Feature

In the Web UI, it would be nice if the creation timestamp for the visual key would be displayed as a column and/or included in the 'info' pop up.

### Motivation, pitch

helps find keys.

**Comment by ishaan-jaff** [comment]
picking this up, we need to

- [x] Add created_at, updated_at in the DB schema 
- [x] Display created_at on the UI for virtual keys
