### ISSUE TITLE
[Feature]: Add Argilla logging integration 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#6201]
### The Feature

Allow user to sample logs and log them to https://argilla.io/

Also add a hook for allowing user to first run the request through an llm call (llm-as-a-judge) 

### Motivation, pitch

get better for mlops/ds teams

**Comment by ghost** [comment]
- will need user to tell us their argilla dataset name 
- will need user to map our payload to their dataset fields 
- need to allow user to set a sampling rate (not all logs should be sent to argilla for annotating)
