### ISSUE TITLE
[Bug]: Last LiteLLM minor version moved Prometheus metrics to Premium

### ISSUE THREAD

**Issue by max-wittig** [BerriAI/litellm#6209]
### What happened?

Last LiteLLM version moved Prometheus metrics to Premium

This caused it to be incompatible with our current configuration and hence crashes

I understand that you need to commercialize this for you to survive, but moving free features to Premium in a minor release is not the way imo.

**Comment by ishaan-jaff** [comment]
thanks for the feedback @max-wittig, I hear your feedback and we will do a better job of this in the future 

Is there something you want me to address in this issue before closing it ? @max-wittig 

As a note we had communicated this
on this announcement: https://github.com/BerriAI/litellm/discussions/5163 
on docs: https://docs.litellm.ai/docs/proxy/prometheus

**Comment by max-wittig** [comment]
No that's all. Thanks for the response!
