### ISSUE TITLE
[Bug]: `v1.49.3` broke `litellm.caching` imports

### ISSUE THREAD

**Issue by jamesbraza** [BerriAI/litellm#6216]
### What happened?

https://github.com/BerriAI/litellm/pull/6208 broke `from litellm.caching import Cache`

Can you add an `__init__.py` to avoid breaking LiteLLM's interface

### Relevant log output

```shell
apy:7:1: error: Module "litellm.caching" has no attribute
"Cache"  [attr-defined]
    from litellm.caching import Cache
    ^
```

**Comment by ishaan-jaff** [comment]
thanks for raising - will have this fixed in 24 hours @jamesbraza

**Comment by ishaan-jaff** [comment]
fixed here: https://github.com/BerriAI/litellm/pull/6219

**Comment by ishaan-jaff** [comment]
As a heads up @jamesbraza we're working on refactoring / code quality improvements / increased testing coverage for the next 2 weeks 

as a side effect there might be some regressions - I'd recommend pinning to a `-stable` version so this does not impact you

**Comment by jamesbraza** [comment]
@ishaan-jaff pulling `v1.49.4` in, at a separate place:

```none
error: Module "litellm.caching" has no attribute
"InMemoryCache"  [attr-defined]
    from litellm.caching import InMemoryCache
```

**Comment by ishaan-jaff** [comment]
fixed here @jamesbraza https://github.com/BerriAI/litellm/pull/6279
