### ISSUE TITLE
[Feature]: forward headers to API Hosts configured in `model_list`

### ISSUE THREAD

**Issue by dogacancolak-kensho** [BerriAI/litellm#6217]
### The Feature

it seems that the header passed into the Python SDK `completions` method as `extra_headers` are not passed onto the API host.

Apparently Pass through Endpoints support forwarding headers, but we'd like the model_list to support as well.

### Motivation, pitch

We have our self-hosted load balancers that we use as the API Host in `config.yaml`, which then load balances between our Azure subscriptions.

Our load balancers need a header from the requesting application in order to create metrics.

**Comment by ghost** [comment]
hi @dogacancolak-kensho extra_headers should be getting sent along. 

Can you share sample code to repro the error?
