### ISSUE TITLE
Using LiteLLM in Production ? 1:1 Support, Breaking Changes  

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#623]
If you're using LiteLLM in production - we want to provide dedicated 1:1 support channels and always communicate breaking changes

👉 Schedule time with us here: https://calendly.com/d/4mp-gd3-k5k/berriai-1-1-onboarding-litellm-hosted-version

**Comment by ghost** [comment]
@ishaan-jaff 👋
