### ISSUE TITLE
[Bug]: Newlines not working in code snippets in docs

### ISSUE THREAD

**Issue by satwikkansal** [BerriAI/litellm#6235]
### What happened?

![CleanShot 2024-10-15 at 19 12 29](https://github.com/user-attachments/assets/a222a3fe-099c-47ab-88b2-81f40c91cca7)

https://docs.litellm.ai/

Checked in both chrome and firefox

**Comment by ghost** [comment]
i'm seeing something similar.

cc: @ishaan-jaff @yujonglee 
<img width="1017" alt="Screenshot 2024-10-16 at 4 03 28 PM" src="https://github.com/user-attachments/assets/cc4a79de-aa8b-41fb-af75-c8e4f3629154">
