### ISSUE TITLE
[Bug]: Function calling to Azure OpenAI models without parameters fails but is allowed as per OpenAI spec

### ISSUE THREAD

**Issue by domg8man** [BerriAI/litellm#6241]
### What happened?

We discovered an issue with function calls to Azure OpenAI models.

When using the `/chat/completions` or `/v1/chat/completions` endpoints with the `function_call` syntax, the call will fail with:
`{"error":{"message":"litellm.BadRequestError: AzureException BadRequestError - Missing required parameter: 'messages[2].function_call.arguments'."}}`

Here's a curl to reproduce this:
```bash
curl '<litellm base url>/v1/chat/completions' \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer <token>" \
  -d '{
    "model": "gpt-4o",
    "messages": [
      {"role": "system", "content": "You are a helpful assistant."},
      {"role": "user", "content": "What is the weather in Copenhagen?"},
      {
        "role": "assistant",
        "function_call": {
          "name": "get_weather"
        }
      }
    ],
    "functions": [
      {
        "name": "get_weather",
        "description": "Fetches weather information for a given location.",
        "parameters": {
          "type": "object",
          "properties": {
            "location": {"type": "string"}
          },
          "required": ["location"]
        }
      }
    ]
  }'
  ```

The OpenAI API spec does not require the `arguments` field:
[https://platform.openai.com/docs/api-reference/chat/create#chat-create-function_call](https://platform.openai.com/docs/api-reference/chat/create#chat-create-function_call)

But Azure does:
[https://learn.microsoft.com/da-dk/azure/ai-services/openai/reference#chatcompletionfunctioncall](https://learn.microsoft.com/da-dk/azure/ai-services/openai/reference#chatcompletionfunctioncall)

Above issue can probably be fixed by checking, if `function_call.arguments` is a key on the dict and else add it with value empty string, since the type on the API seems to be of type string and required.

Hope someone can look into this 🙏

### Relevant log output

```
{"error":{"message":"litellm.BadRequestError: AzureException BadRequestError - Missing required parameter: 'messages[2].function_call.arguments'."}}
```

**Comment by ghost** [comment]
Just tested - passing an empty argument value works

**Comment by domg8man** [comment]
Thanks for the quick fix, can confirm this works 🚀
