### ISSUE TITLE
[Feature]: Support databricks `/llm/v1/chat` endpoint - work with Mosaic AI Agent Framework

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#6244]
### The Feature

work with mosaic ai agent framework - https://docs.databricks.com/en/generative-ai/create-log-agent.html#simple-chain-notebook

### Motivation, pitch

user request

**Comment by ghost** [comment]
Seems like a no-op. 

Mosaic AI Agent framework just uses langchain models, so it should be pretty easy to just use a chatopenai model instead 

Added a notebook on using litellm proxy inside databricks notebooks with mlflow logging - https://github.com/BerriAI/litellm/blob/litellm_dev_10_17_2024/cookbook/mlflow_langchain_tracing_litellm_proxy.ipynb
