### ISSUE TITLE
Make `meta` in rerank API Response optional

### ISSUE THREAD

**Issue by S1LV3RJ1NX** [BerriAI/litellm#6246]
https://github.com/BerriAI/litellm/blob/19941000284fad3bc3a5f3d48008efaae8a18291/litellm/types/rerank.py#L25

The `meta` key causes issues when integrating with custom reranking service like [`infinity`](https://github.com/michaelfeil/infinity). We can make this `meta` dict an optional arg in response, as not all opensource APIs may send `meta`

**Comment by ishaan-jaff** [comment]
done here @S1LV3RJ1NX https://github.com/BerriAI/litellm/pull/6248
