### ISSUE TITLE
[Feature]: Default option for alternating message roles (e.g., user -> assistant -> user ...)

### ISSUE THREAD

**Issue by arthursn** [BerriAI/litellm#6257]
### The Feature

Certain LLMs require messages with alternating roles (user -> assistant -> user -> assistant, etc.). This can be problematic for applications that do not ensure this by default (e.g., [aider](https://aider.chat/), [crewAI](https://www.crewai.com/)). I propose adding a default option in litellm (for any LLM instance) to insert filler messages to ensure proper alternation of roles, similar to what has been already implemented for AWS Bedrock (https://docs.litellm.ai/docs/providers/bedrock#alternate-userassistant-messages).

### Motivation, pitch

I particularly struggle with Llama 3.1 in instruct mode (`databricks/databricks-meta-llama-3-1-70b-instruct`) served in Databricks. This LLM requires strict alternation of user and assistant messages, and without a built-in mechanism to enforce this, it can lead to errors and inconsistencies in the interactions.

I have created workaround solutions that ensure the message roles alternation, but it would desirable to have this feature implemented by default in litellm.

### Benefits

- **Consistency:** Ensures that all messages follow the required format, preventing errors and improving the reliability of interactions.
- **Ease of Use:** Simplifies the implementation for developers, reducing the need for manual message handling.
- **Precedent:** Similar functionality has been implemented for AWS Bedrock, as detailed in your documentation [here](https://docs.litellm.ai/docs/providers/bedrock#alternate-userassistant-messages).

### Proposal

Implement a default option in litellm that automatically inserts filler messages to maintain the required alternation of user and assistant roles.

**Comment by ghost** [comment]
Hi @arthursn we do this already for certain providers- https://github.com/BerriAI/litellm/blob/8530000b44241f949580e1f38a49088627ea2c88/litellm/llms/prompt_templates/factory.py#L57

How do you want to set this option?

**Comment by arthursn** [comment]
Indeed. I pointed that out in my request. While I understand you could enable it for the `*-instruct` or Databricks models, I believe that this should be a default option for any provider.
Could be something like:

```python
litellm.completion(
    **{
        "model": "databricks/databricks-meta-llama-3-1-70b-instruct",
        "messages": [
            {"role": "user", "content": "Hello!"},
            {"role": "assistant", "content": "Hello! How can I assist you today?"},
            {"role": "user", "content": "What is Databricks?"},
            {"role": "user", "content": "What is Azure?"},
        ],
        "user_continue_message": {
            "role": "user",
            "content": "Ok",
        },
        "assistant_continue_message": {
            "role": "assistant",
            "content": "Please continue",
        },
        "ensure_alternating_roles": True,
    }
)
```

If `ensure_alternating_roles` is set to True then the default messages are used, unless they are overridden by the user (as in the example above).

**Comment by ghost** [comment]
Thinking out loud - instead of inserting dummy messages, why not just merge the consecutive blocks? 

This would also solve the alternating user/assistant issue @arthursn

**Comment by ghost** [comment]
Nvm, this way guarantees it works across all providers

i don't think all providers today support content as a list
