### ISSUE TITLE
[Bug]: Network Request to Github is Required for Completion Costs

### ISSUE THREAD

**Issue by jsherer** [BerriAI/litellm#626]
### What happened?

I was trying to experiment with `litellm` and my network connection to GitHub was having issues for some reason. This produced an interesting error in that the token cost computations were returning "empty" and causing problems with message trimming and the like. 

I was spelunking through the code and noticed that the [`get_model_cost_map` function](https://github.com/BerriAI/litellm/blob/8fa9dab9fecba19cc4fd55b1624c4186c641119b/litellm/__init__.py#L49) retrieves a JSON file over HTTP from this repo at this URL: https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json. This is a clever use of GitHub hosting to deliver the most up to date prices. However, this functionality breaks budget management when the network request cannot be completed (no network, network failure, etc).

What do we think about introducing a fallback to load a cached copy installed with the package and/or defaulting to the cached copy and "upgrading" to the most recent with a fetch to the GitHub repo?

I'd be happy to pull together a PR for either.

**Comment by ghost** [comment]
@jsherer that's a great idea. A PR here would be amazing. Reaching out via linkedin to provide any help on our end.

**Comment by ghost** [comment]
@jsherer implemented your idea of using a cached copy for fallbacks - https://github.com/BerriAI/litellm/commit/b69449a81174a3b9de7a7dd9df0cb2f931251c35.

**Comment by ghost** [comment]
can you let me know if this solves your issue?

**Comment by jsherer** [comment]
Thanks @krrishdholakia This should help. I sent you a [comment](https://github.com/BerriAI/litellm/commit/b69449a81174a3b9de7a7dd9df0cb2f931251c35#r130343149) on the test.

Further, Is there a way we could add an environment variable or something to prevent the initial request from happening altogether? Or for directing it to a different URL (say a fork repo or other hosted json blob)? I'm just imagining wanting to be able to control this exactly in a production environment.

**Comment by ghost** [comment]
Hey @jsherer, I want to understand this better can you chat for 10 minutes today? 

Attaching my calendly if that helps - https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by ghost** [comment]
@jsherer updated our testing based on your comment - https://github.com/BerriAI/litellm/commit/50a3c9768bc1a69884a8e705a262ddefb5c6bd36

**Comment by jsherer** [comment]
> Hey @jsherer, I want to understand this better can you chat for 10 minutes today? 
> 
> 
> 
> Attaching my calendly if that helps - https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

Happy to talk through it. I snagged a spot for tomorrow.

**Comment by ghost** [comment]
Great - speak then!
