### ISSUE TITLE
[Feature]: litellm's integration with langfuse for prompt management 

### ISSUE THREAD

**Issue by GildeshAbhay** [BerriAI/litellm#6269]
### The Feature

I want to track traces for prompts for litellm with langfuse but the integration ends with successive callback which doesn't allow me to use langfuse.prompts with litellm tracking

### Motivation, pitch

People use langfuse.purely for prompt management and litellm is a barrier to that

**Comment by ghost** [comment]
Hi @GildeshAbhay can you share how you'd want this to work? Example code here would be helpful

**Comment by ghost** [comment]
Closing for now as no user response. We'd be happy to help here if anyone wants this. @GildeshAbhay please reopen / create a new ticket if this is still an issue

**Comment by tiagoefreitas** [comment]
This is mentioned in the litellm documentation but apparently doesn't work:
https://github.com/orgs/langfuse/discussions/3780

https://litellm.vercel.app/docs/observability/langfuse_integration
Generation Specific Parameters
"prompt - Langfuse prompt object used for the generation, defaults to None"

@krrishdholakia @GildeshAbhay  can you reopen? I would like to use it too
