### ISSUE TITLE
[Docs]: No code_of_conduct.md & CONTRIBUTING.md File in repo

### ISSUE THREAD

**Issue by mohitd404** [BerriAI/litellm#627]
### The Feature

Code_Of_Conduct.md
We propose adding a comprehensive Code of Conduct to our repository to ensure a safe, respectful, and inclusive environment for all contributors and users. This code will serve as a guideline for behavior, promoting diversity, reducing conflicts, and attracting a wider range of perspectives.

CONTRIBUTING.md
A CONTRIBUTING.md file is important because it provides guidelines and instructions for contributors to your project, making it easier for them to understand how to contribute effectively. It helps maintain consistency, quality, and a smooth collaborative process, fostering a welcoming and productive open-source community.

### Motivation, pitch

Kindly assign me this issue, I would love to work on this issue! thank you!

### Twitter / LinkedIn details

https://www.linkedin.com/in/mohit-dhote-117568213/

**Comment by mohitd404** [comment]
@krrishdholakia Kindly assign me this issue, I would love to work on this issue! thank you!

**Comment by ghost** [comment]
We have a contributing section - https://github.com/BerriAI/litellm#contributing, 

Anything further you'd like to add @mohitd404 ?

**Comment by mohitd404** [comment]
> We have a contributing section - https://github.com/BerriAI/litellm#contributing,
> 
> Anything further you'd like to add @mohitd404 ?

still, the code of conduct for this repository is missing !!

**Comment by ghost** [comment]
what's the point of it?

**Comment by mohitd404** [comment]
> We propose adding a comprehensive Code of Conduct to our repository to ensure a safe, respectful, and inclusive environment for all contributors and users. This code will serve as a guideline for behavior, promoting diversity, reducing conflicts, and attracting a wider range of perspectives.
