### ISSUE TITLE
[Feature]: Add load balancer to proxy 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#629]
### The Feature

Enable users to pass in multiple azure deployments, and load balance across them on proxy 

### Motivation, pitch

this is a repeated user pattern that we've seen. We should just have an implementation to make users lives better.

**Comment by ghost** [comment]
cc: @ishaan-jaff is there anything from the rate limit manager i can use for this?

**Comment by ghost** [comment]
closing as cli is deprecated.
