### ISSUE TITLE
P0: Support `audio` param in responses streaming

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#6301]

**Comment by ghost** [comment]
<img width="703" alt="Screenshot 2024-10-18 at 6 52 03 PM" src="https://github.com/user-attachments/assets/eedc9b72-1f40-4444-bb2f-c4d57120dd9f">


@ishaan-jaff this already works for me, anything we're missing?

**Comment by ishaan-jaff** [comment]
nope - closing as completed
