### ISSUE TITLE
Add cost tracking for gpt-4o-audio

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#6302]

**Comment by ghost** [comment]
support for streaming cost calc is also needed here

**Comment by ghost** [comment]
Looks like openai doesn't return streaming audio token usage yet. 
<img width="790" alt="Screenshot 2024-10-18 at 6 43 16 PM" src="https://github.com/user-attachments/assets/d44cd752-0c2c-4313-b5df-bf3f0ab35d91">
