### ISSUE TITLE
[Bug]: Exception: This model isn't mapped yet. model=qwen2.5:32b, custom_llm_provider=ollama. Add it here - https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json.

### ISSUE THREAD

**Issue by CRCODE22** [BerriAI/litellm#6322]
### What happened?

Exception: This model isn't mapped yet. model=qwen2.5:32b, custom_llm_provider=ollama. Add it here - https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json.

Since the provider is Ollama why does it needs to be mapped when that model works in other software on my computer that uses Ollama?

### Relevant log output

```shell
Traceback (most recent call last):
  File "K:\Users\CRCODE22\pinokio\api\ditto.git\app\env\lib\site-packages\litellm\utils.py", line 4815, in get_model_info
    raise ValueError(
ValueError: This model isn't mapped yet. Add it here - https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\Users\CRCODE22\pinokio\api\ditto.git\app\env\lib\site-packages\litellm\utils.py", line 1824, in supports_function_calling
    model_info = litellm.get_model_info(
  File "K:\Users\CRCODE22\pinokio\api\ditto.git\app\env\lib\site-packages\litellm\utils.py", line 4902, in get_model_info
    raise Exception(
Exception: This model isn't mapped yet. model=qwen2.5:32b, custom_llm_provider=ollama. Add it here - https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\Users\CRCODE22\pinokio\bin\miniconda\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "K:\Users\CRCODE22\pinokio\bin\miniconda\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "K:\Users\CRCODE22\pinokio\api\ditto.git\app\main.py", line 279, in run_main_loop
    if not supports_function_calling(MODEL_NAME):
  File "K:\Users\CRCODE22\pinokio\api\ditto.git\app\env\lib\site-packages\litellm\utils.py", line 1832, in supports_function_calling
    raise Exception(
Exception: Model not found or error in checking function calling support. You passed model=qwen2.5:32b, custom_llm_provider=ollama. Error: This model isn't mapped yet. model=qwen2.5:32b, custom_llm_provider=ollama. Add it here - https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json.
```

**Comment by bgeneto** [comment]
> ### What happened?
> Exception: This model isn't mapped yet. model=qwen2.5:32b, custom_llm_provider=ollama. Add it here - https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json.
> 
> Since the provider is Ollama why does it needs to be mapped when that model works in other software on my computer that uses Ollama?

It should work in litellm, even with the mentioned error. It will not compute spend/costs although. If it is not working maybe it is how you configured the model. I suggest like this, give it a try (don't use custom provider):
```
model_list:
  - model_name: "qwen2.5:32b"
    litellm_params:
      model: "ollama/qwen2.5-coder:latest"
      api_base: "http://localhost:1234"
      api_type: "open_ai"
      input_cost_per_token: 0.00
      output_cost_per_token: 0.00
```

**Comment by CRCODE22** [comment]
> > ### What happened?
> > Exception: This model isn't mapped yet. model=qwen2.5:32b, custom_llm_provider=ollama. Add it here - https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json.
> > Since the provider is Ollama why does it needs to be mapped when that model works in other software on my computer that uses Ollama?
> 
> It should work in litellm, even with the mentioned error. It will not compute spend/costs although. If it is not working maybe it is how you configured the model. I suggest like this, give it a try (don't use custom provider):
> 
> ```
> model_list:
>   - model_name: "qwen2.5:32b"
>     litellm_params:
>       model: "ollama/qwen2.5-coder:latest"
>       api_base: "http://localhost:1234"
>       api_type: "open_ai"
>       input_cost_per_token: 0.00
>       output_cost_per_token: 0.00
> ```

Thank you for your reply I am trying to use it in ditto which uses litellm for model loading.

https://github.com/pinokiofactory/ditto

Pinokio uses a custom environment:

OPENAI_API_KEY=
LITELLM_MODEL=ollama/qwen2.5:32b

**Comment by ghost** [comment]
> Exception: Model not found or error in checking function calling support

The error you're seeing is from ditto, as it can't validate if the model provided supports function calling. 

This is a good point. I think we should handle this by checking if the model is unmapped, if the provider supports this (ollama does)

**Comment by ghost** [comment]
Actually i'm wrong - from the ollama docs, it's clear not all models support function calling. They have a list here - https://ollama.com/search?c=tools

**Comment by CRCODE22** [comment]
Qwen 2.5 does support function calling:

https://qwen.readthedocs.io/en/latest/framework/function_call.html

The problem is the model is not mapped here:Exception: This model isn't mapped yet. model=qwen2.5:32b, custom_llm_provider=ollama. Add it here - https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json.

I tried to map it locally but still it insists on checking that file on Github instead: 

This would be the info needed to map it I think

    "ollama/qwen2.5:32b": {
        "max_tokens": 32768,
        "max_input_tokens": 32768,
        "max_output_tokens": 32768,
        "input_cost_per_token": 0.0,
        "output_cost_per_token": 0.0,
        "litellm_provider": "ollama",
        "mode": "chat"
        "supports_function_calling": true,
    },

**Comment by ghost** [comment]
We now check if an ollama model supports function calling by hitting the `/api/show` endpoint exposed by ollama. 

Just make sure your ollama api base is set in the environment, and this should work - `OLLAMA_API_BASE`

**Comment by suxyu** [comment]
> Qwen 2.5 does support function calling:
> 
> https://qwen.readthedocs.io/en/latest/framework/function_call.html
> 
> The problem is the model is not mapped here:Exception: This model isn't mapped yet. model=qwen2.5:32b, custom_llm_provider=ollama. Add it here - https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json.
> 
> I tried to map it locally but still it insists on checking that file on Github instead:
> 
> This would be the info needed to map it I think
> 
> ```
> "ollama/qwen2.5:32b": {
>     "max_tokens": 32768,
>     "max_input_tokens": 32768,
>     "max_output_tokens": 32768,
>     "input_cost_per_token": 0.0,
>     "output_cost_per_token": 0.0,
>     "litellm_provider": "ollama",
>     "mode": "chat"
>     "supports_function_calling": true,
> },
> ```

having the same issue here. I just could not find file  https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json. locally, i can only see model_prices_and_context_window_backup.json

**Comment by ghost** [comment]
Hey @suxyu - we're checking your ollama instance for the supported function calling model - https://github.com/BerriAI/litellm/blob/99c85e5a60cf181ecc368e67751a2cb1c6036f81/litellm/llms/ollama/completion/transformation.py#L223


But you can override this by just setting it on model_info - 

```
model_list:
  - model_name: "qwen2.5:32b"
    litellm_params:
      model: "ollama/qwen2.5-coder:latest"
      api_base: "http://localhost:1234"
      api_type: "open_ai"
      input_cost_per_token: 0.00
      output_cost_per_token: 0.00
   model_info:
      supports_function_calling: true
```
