### ISSUE TITLE
[Bug]: Fix anthropic formatting 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#633]
### What happened?

1) Anthropic’s formatting is still broken. I sent the prompt “Who was the first president?”. I checked what got sent to the Anthropic API and "\n\nHuman: \n\nHuman: Who was the first president?\n\nAssistant: " got sent. It should be "Human: Who was the first president?\n\nAssistant: "
 
2) Anthropic on Bedrock is similarly broken, it turns it into: "\n\nHuman: Who was the first president?\n\nAssistant: " it should be " Human: Who was the first president?\n\nAssistant:"

**Comment by ghost** [comment]
Looks like it should always be `\n\nHuman:` for anthropic 
<img width="564" alt="Screenshot 2023-10-20 at 9 51 32 AM" src="https://github.com/BerriAI/litellm/assets/17561003/dc12999e-4d90-4dcf-9c6f-6a21b62dceed">

**Comment by ghost** [comment]
resolved here: https://github.com/BerriAI/litellm/commit/4b48af7c3cf77efde2243fdb437c2b16925b469d
