### ISSUE TITLE
Support jinaai/jina-embeddings-v3 natively 

### ISSUE THREAD

**Issue by bgeneto** [BerriAI/litellm#6337]
### The Feature

jina-embeddings-v3 has much better price and  performance than e.g. openai text-embedding-3-large. It would be fine if litellm could support it directly, like a Jina provider.
A free api key with 1 million tokens can be obtained here without even registering, for testing purposes. I've tried to use it like an openai embedding but it fails with some weard error: extra parameter not allowed. 

https://jina.ai/embeddings/

### Motivation, pitch

jina-embeddings-v3 has much better price and  performance than e.g. openai text-embedding-3-large.

**Comment by ghost** [comment]
Looks like the openai client by default passes this value - 

```
options: method='post' url='/embeddings' params={} headers={'X-Stainless-Raw-Response': 'true'} max_retries=NOT_GIVEN timeout=600 files=None idempotency_key=None post_parser=<function AsyncEmbeddings.create.<locals>.parser at 0x112b38040> json_data={'input': ['hello world'], 'model': 'jina-embeddings-v3', 'encoding_format': 'base64'} extra_json=None
```

https://github.com/openai/openai-python/blob/fc4fce30aff7620c32e57301d3c40b4883810825/src/openai/resources/embeddings.py#L105
