### ISSUE TITLE
[Bug]: configure api_base for ollama via config

### ISSUE THREAD

**Issue by tabergma** [BerriAI/litellm#6342]
### What happened?

Rasa uses liteLLM to call different LLMs. For the provider `ollama` we pass the configuration on to liteLLM to create a client. 
Looking at the docs it looks like that you can define the `api_base` through code for ollama. 
```
from litellm import completion

response = completion(
    model="ollama/llama2", 
    messages=[{ "content": "respond in 20 words. who are you?","role": "user"}], 
    api_base="http://localhost:11434/"
)
print(response)
```

However, when using a config like this in Rasa
```
  llm:
    provider: ollama
    model: llama3.2
    api_base: "https://localhost:11434/"
```
I'm getting the following error
```
2024-10-21 11:16:48 ERROR    rasa.shared.providers.llm._base_litellm_client  - [error    ] Environment variables: ['OLLAMA_API_BASE'] not set. Required for API calls. event_key=base_litellm_client.validate_environment_variables missing_environment_variables=['OLLAMA_API_BASE']
```
Only when I set `OLLAMA_API_BASE` everything is working. 

Is it not possible to set the `api_base` for `ollama` inside the configuration, e.g. code, instead of using an environment variable?

**Comment by ghost** [comment]
@tabergma it looks like `validate_environment` is being called by rasa. 

This is a helper utility to check if the relevant keys are in the environment. I'd recommend reaching out to the rasa team to ask them to enable passing through the keys dynamically.

**Comment by tabergma** [comment]
Ok, thanks for pointing this out. In that case we can close this issue. Thanks!
