### ISSUE TITLE
How we can disable the api_log file?

### ISSUE THREAD

**Issue by antonio-castellon** [BerriAI/litellm#635]
We would like to disable the creation of the local log_api, and another question is, how much space can take this log by default.

Many thanks

**Comment by ghost** [comment]
Hey @antonio-castellon, i'm confused - why do you not want logs? 

Also followed up via linkedin - so i can better understand the scenario.

**Comment by antonio-castellon** [comment]
I want to limit the size of the logs, ones it's working well I dont care about the logs anymore for this side of the app

**Comment by ghost** [comment]
Oh - are you deploying the proxy? @antonio-castellon 

I'll work on making it optional as well.

**Comment by ghost** [comment]
you can now set it by setting local_logging = false in the secrets_template.toml

https://github.com/BerriAI/litellm/commit/3863920ea52c9cd2426b1fc14148004ead0738e2

**Comment by antonio-castellon** [comment]
Many thanks!
