### ISSUE TITLE
[Feature]: Add X.ai's Grok 2 AI Support

### ISSUE THREAD

**Issue by yigitkonur** [BerriAI/litellm#6357]
### The Feature

Elon Musk tweeted this: https://x.com/Replit/status/1848409439008649336 (could not find where API key is but will update here)

### Motivation, pitch

Elon Musk is enough.

**Comment by rokbenko** [comment]
@yigitkonur
Sign up here: https://accounts.x.ai/sign-in
See docs here: https://docs.x.ai/docs

**Comment by ishaan-jaff** [comment]
chat completions added here: https://github.com/BerriAI/litellm/pull/6373
