### ISSUE TITLE
Declared format = json for Ollama models throws a function `name` not found error

### ISSUE THREAD

**Issue by sarora-roivant** [BerriAI/litellm#6359]
When trying to declare format = json for Ollama model, I get a function name keyerror. I think this is the code which is trying to implement a function call. 
https://github.com/BerriAI/litellm/blob/199896f9128981160c1bc806a15ffe7e3a1aeeff/litellm/llms/ollama.py#L336-L356

**Comment by dspyrhsu** [comment]
Thanks for duplicating [my issue](https://github.com/BerriAI/litellm/issues/6353) ...

**Comment by Clad3815** [comment]
#6135 Also my problem

**Comment by s4r0ra** [comment]
Closing this issue as similar ones already exist
