### ISSUE TITLE
[Bug]: get_max_tokens incorrect docstring/IntelliSense

### ISSUE THREAD

**Issue by matteo-mistri** [BerriAI/litellm#636]
### What happened?

The docs correclty reports that the function returns a dict, and so it does, but the docstring has an int return type, so IntelliSense uncorreclty detect the return type

**Comment by ishaan-jaff** [comment]
done https://github.com/BerriAI/litellm/commit/0c090e3675610ce731081529a0a3b8302275f7c3 

@matteo-mistri does this look good to you ?

**Comment by matteo-mistri** [comment]
Looks good to me. I still find the function name a little misleading (i would expect to obtain just the max_token value as an integer). Isn't it now just a copy of the "model_cost" function?

**Comment by ishaan-jaff** [comment]
what do you think of `get_max_tokens_and_cost()` open to suggestions on the function name @matteo-mistri

**Comment by mistrello96** [comment]
I would suggest to make get_max_tokens return only an integer representig the max_tokens of a given model, and maybe add a get_model_info function returning the currenct dict with all the info!

**Comment by ishaan-jaff** [comment]
one concern is that users use `get_max_tokens` and this would be a breaking change for them 

cc @krrishdholakia thoughts on refactoring `get_max_tokens` to only return an int ?

**Comment by ghost** [comment]
If we anticipate making any other breaking changes in the near future, let's bundle them, to minimize user pain. 


@ishaan-jaff @mistrello96 @matteo-mistri i think this refactor is worth doing, but doesn't seem to be an immediate issue. Could we track these in a breaking change backlog, and revisit that list at the end of the month (oct 30th). That way, if there's any other changes we need to make, we can bundle them in a single change vs. several breaking changes.

**Comment by ghost** [comment]
Tracking this here - https://github.com/BerriAI/litellm/discussions/648. 

@matteo-mistri @mistrello96 we appreciate your feedback on this issue. If there's any other things we can improve on litellm, feel free to either add them to the discussion (if it seems like a breaking change) or create an issue for it.

**Comment by ghost** [comment]
closing this issue as this is now being tracked as part of the discussion
