### ISSUE TITLE
[Bug]: `tools-2024-05-16` in anthropic-beta header is breaking calls made to Sonnet3.5 on Vertex

### ISSUE THREAD

**Issue by agnivabanerjee** [BerriAI/litellm#6370]
### What happened?

While using litellm to call Sonnet3.5 model deployed in VertexAI, we see an error: 

`{'error': {'message': 'litellm.BadRequestError: VertexAIException BadRequestError - {"type":"error","error":{"type":"invalid_request_error","message":"Unexpected value(s) `tools-2024-05-16` for the `anthropic-beta` header. Please consult our documentation at docs.anthropic.com or try again without the header."}}`

Is there any way to suppress adding this to the header for now while making calls to Anthropic models?

**Comment by ggallotti** [comment]
Same here. This Issue started yesterday night. 

This JSON is failing on VertexAI since yesterday on all Anthropic models. 
```
{
    "model": "vertex_ai/claude-3-sonnet-20240229",
    "stream": false,
    "messages": [
        {
            "role": "user",
            "content": "What's the weather like in Boston today?"
        }
    ],
    "tools": [
        {
            "type": "function",
            "function": {
                "name": "get_current_weather",
                "description": "Get the current weather in a given location",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "location": {
                            "type": "string",
                            "description": "The city and state, e.g. San Francisco, CA"
                        },
                        "unit": {
                            "type": "string",
                            "enum": [
                                "celsius",
                                "fahrenheit"
                            ]
                        }
                    },
                    "required": [
                        "location"
                    ]
                }
            }
        }
    ]
}
```

**Comment by ghost** [comment]
I think vertex made a backend change - the fix is on main already - https://github.com/BerriAI/litellm/commit/a5fe87d6a525c79d349465f49716f76f0a79aa00

will be live soon in v`1.50.2` 

---
pinning this issue, so others can track this as well

**Comment by ghost** [comment]
This has been fixed - please bump to latest!
