### ISSUE TITLE
Add "voyage-finance-2" in "model_prices_and_context_window.json"

### ISSUE THREAD

**Issue by OliverT1** [BerriAI/litellm#6371]
Source: <SOURCE_URL>

We need to update both [model_prices_and_context_window.json](https://github.com/BerriAI/litellm/blob/a0c5fee61d9115b8df44a64dda8c4c9fd26b034a/model_prices_and_context_window.json) and [model_prices_and_context_window_backup.json](https://github.com/BerriAI/litellm/blob/a0c5fee61d9115b8df44a64dda8c4c9fd26b034a/litellm/model_prices_and_context_window_backup.json) to reflect the new model.

**Comment by ishaan-jaff** [comment]
Hi @OliverT1 , thanks for using LiteLLM. Any chance we can hop on a call to learn how we can improve LiteLLM Proxy for you ? 

We’re planning roadmap and I’d love to get your feedback 

my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
my linkedin if you prefer DMs: https://www.linkedin.com/in/reffajnaahsi/
