### ISSUE TITLE
[Bug]:  Failed to convert text into a pydantic model due to the following error: litellm.AuthenticationError: AuthenticationError: OpenAIException - The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable Using raw output instead.

### ISSUE THREAD

**Issue by amansingh0311** [BerriAI/litellm#6375]
### What happened?

**Issue Description:** While using Crew AI with the litellm package in a GCP Cloud Run environment, the following error occurred when attempting to convert text into a Pydantic model:
`litellm.AuthenticationError: AuthenticationError: OpenAIException - The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable. Using raw output instead.`

This error arises due to the OPENAI_API_KEY not being accessible in the cloud environment. The code works locally, where the API key is pulled from environment variables stored in a .env file, but it fails in the GCP Cloud Run environment, where environment variables are stored in Google Cloud Secret Manager. The issue seems to be internal to the litellm package, which does not provide an external method to inject the API key, making it difficult to resolve at the package level.

Cause: In the GCP Cloud Run setup, the environment variables are stored in Secret Manager and cannot be automatically accessed by the litellm package as it does in the local environment. Since the OPENAI_API_KEY is not directly injected, it triggers the authentication error when trying to connect to the OpenAI API.

**Workaround:** To solve the issue, the following workaround was implemented:
1. Fetch the OPENAI_API_KEY from GCP Secrets.
2. Set the environment variable programmatically using os.environ to ensure it is available to the litellm package when making API requests.

```Import os
from config import Settings

settings = Settings()
OPENAI_API_KEY = settings.OPENAI_API_KEY

if OPENAI_API_KEY:
    print(f"OPENAI_API_KEY: inside the _init_.py file: {OPENAI_API_KEY}")
    # Set the environment variable
    os.environ["OPENAI_API_KEY"] = OPENAI_API_KEY
    print(f"OPENAI_API_KEY: inside the _init_.py file: {os.environ['OPENAI_API_KEY']}")
```

**Proposed Solution:** A permanent solution would be to modify the litellm package to allow explicitly passing the API key during function calls, or allowing better integration with environment management tools like GCP Secret Manager, so that it can dynamically fetch and use environment variables without manual intervention.

### Relevant log output

```shell
Failed to convert text into a pydantic model due to the following error: litellm.AuthenticationError: AuthenticationError: OpenAIException - The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable Using raw output instead.
```

### Twitter / LinkedIn details

@amansingh_india / https://www.linkedin.com/in/amansingh31/

**Comment by ghost** [comment]
> allow explicitly passing the API key during function calls

this is already supported @amansingh0311 https://docs.litellm.ai/docs/set_keys#passing-args-to-completion

**Comment by ghost** [comment]
> Failed to convert text into a pydantic model due to the following error

This error is raised by the openai sdk. We do pass the api key dynamically if it's set. 


Closing as this flow is already supported. It's likely your issue is caused due to env var not being present in the environment when the query is run. 

Here's a minimal script to confirm this - 

```python
from litellm import completion

messages = [{ "content": "Hello, how are you?","role": "user"}]

response = completion(model="groq/llama3-8b-8192",  messages, api_key="my_groq_key")
```
