### ISSUE TITLE
Add `claude-3-5-sonnet-20241022`

### ISSUE THREAD

**Issue by invakid404** [BerriAI/litellm#6377]
### The Feature

Anthropic just announced a new version of Claude 3.5 Sonnet: `claude-3-5-sonnet-20241022`. It should be added to Litellm.

### Motivation, pitch

Self-explanatory.

**Comment by ghost** [comment]
Closed with #6380

**Comment by ghost** [comment]
> Self-explanatory.

Love this bit @invakid404 😄
