### ISSUE TITLE
Infisical integration not working

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#64]
<img width="730" alt="Screenshot 2023-08-07 at 7 31 13 PM" src="https://github.com/BerriAI/litellm/assets/17561003/1b8069f4-28e9-4008-9f75-c61434ee9334">
<img width="1320" alt="Screenshot 2023-08-07 at 7 31 48 PM" src="https://github.com/BerriAI/litellm/assets/17561003/4d8c9c32-80ed-42e8-b06d-e267e9935e45">

@ishaan-jaff i followed the documentation but my code isn't working

**Comment by zakhar-kogan** [comment]
Please have a look at [this commit](https://github.com/BerriAI/litellm/commit/6f7ca2e9ae3e8f9a615397e30ba5679a0a917634) ⇢ this way the tests work for me:
<img width="1024" alt="image" src="https://github.com/BerriAI/litellm/assets/36503576/2efacf9e-e8df-4c22-99fa-156067e50de5">

**Comment by ishaan-jaff** [comment]
@zakhar-kogan are you using the infisical integration? did it work for you ? 

Any feedback on the process of setting it up ?

**Comment by ishaan-jaff** [comment]
@krrishdholakia can you share your code ? I need steps to repro since it works for me

**Comment by ghost** [comment]
I was trying to set it up in a flask app - so i had a .env and main.py and i was trying to run `python3 main.py`

**Comment by zakhar-kogan** [comment]
> @zakhar-kogan are you using the infisical integration? did it work for you ?
> 
> Any feedback on the process of setting it up ?

@ishaan-jaff, actually just tried rewriting a wee bit + tested in test_secrets.py 👀

Will check it out later!
