### ISSUE TITLE
[Bug]: OpenAI requests have unexpected `extra_headers`.

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#6410]
### What happened?

I did not set `extra_headers` in my prompt at all, yet for some reason, I see `extra_headers` in Langfuse. Not sure if LiteLLM is logging wrong, or if it's something else that's more wrong happening.

<img width="847" alt="image" src="https://github.com/user-attachments/assets/1a2f33f3-8155-4486-a8dc-fc9a0e91a490">

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by ghost** [comment]
Hi @Manouchehri this isn't a bug, we support forwarding client-id headers to the backend llm api 

this was done to support passing client side values like openai organization - i acknowledge the feedback here though

We can move to feature flag this 

https://github.com/BerriAI/litellm/blob/c731ba4044b45007619ea2c7d3dbad8c84323765/litellm/proxy/litellm_pre_call_utils.py#L162

**Comment by Manouchehri** [comment]
This is weird though, do all of the LLM providers do this? I only see it happening with OpenAI.
