### ISSUE TITLE
[Feature]: document new cache behaviour 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#642]
### The Feature

We've added the ability to pass in a key for your cache when you run `add_cache()` and `get_cache()`

example usage: 
```python
import litellm

tmp_cache = litellm.Cache() 

tmp_cache.add_cache(result="hello world", cache_key="1234") 

tmp_cache.get_cache(cache_key="1234")
```

### Motivation, pitch

needed it for routing.py.

**Comment by Rohxn16** [comment]
i wanna work on this issue, never worked much on documentation before so a brief on what to do would be useful

**Comment by ghost** [comment]
This is now done. 

@Rohxn16 apologies - seeing this late.
