### ISSUE TITLE
[Bug]: 🆘 usage and spending treacking is not working

### ISSUE THREAD

**Issue by RRaphaell** [BerriAI/litellm#6432]
### What happened?

trecking and usage is not working. 
spend is always 0 and usage tab throws an error:

<img width="159" alt="Screenshot 2024-10-25 at 12 49 44" src="https://github.com/user-attachments/assets/48e21ec8-c1b5-4957-9e8a-b649a72ebc2e">
<img width="2041" alt="Screenshot 2024-10-25 at 12 50 04" src="https://github.com/user-attachments/assets/d37e8afb-d4f1-40f3-b580-ed1a9a16b00b">

**Comment by ghost** [comment]
the monthly global spend should be fixed on v`1.50.4` 

the spend issue - can you share your server logs? (run proxy with `--detailed_debug`) 

This should show any errors that might be happening

**Comment by RRaphaell** [comment]
as it seems model name changed in the configs. I had my llm so in the config it should be:
hosted_vllm/model_name

now it's fixed thanks
