### ISSUE TITLE
[Feature]: add token cost for Amazon Titan Multimodal Embeddings

### ISSUE THREAD

**Issue by pharindoko** [BerriAI/litellm#6435]
### The Feature

I`m missing the costs in the cost map for bedrock/amazon.titan-embed-image-v1.

### Motivation, pitch

get the costs for it.

**Comment by ishaan-jaff** [comment]
done here @pharindoko https://github.com/BerriAI/litellm/pull/6444

**Comment by ishaan-jaff** [comment]
Hi @pharindoko , thanks for using LiteLLM. Any chance we can hop on a call to learn how we can improve LiteLLM Proxy for you ? 

We’re planning roadmap and I’d love to get your feedback 

my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
my linkedin if you prefer DMs: https://www.linkedin.com/in/reffajnaahsi/
