### ISSUE TITLE
[Feature]: Expose tokenizer encoding and decoding function

### ISSUE THREAD

**Issue by mistrello96** [BerriAI/litellm#646]
### The Feature

Each LLM model has it's own tokenizer, and the library already uses the appropriate one in functions like "token_counter".
It wolud be helpfull to expose the encode/decode function given a model name, so if an input needs to be cropped to a specific size, the correct tokenizer can be used.

### Motivation, pitch

Let's suppose the LLM has a maximim context of 4000 tokens. I have a very long chat history that I want to crop at 3000 token so that the other 1000 token can be used for copletion.
I shoud encode the history with the appropriate tokenizer, pick the first 3000 tokens and then decode them before passing it to the LLM.

**Comment by ghost** [comment]
Hey @mistrello96 how would this function different from token_counter does today? 

some sample code here might help

**Comment by mistrello96** [comment]
I'll try to give you an example.
Let's suppose you want to crop a string of an arbitrary lenght to a fixed number of **token** (let's say 50).
The string must be encoded in a list of integers by the tokenizer, only the first 50 tokens will be kept and then the list of tokens must be decoded by the tokenizer to get back the string.

This operation must be done with a tokenizer that is consistent with the LLM that we are going to use, since different tokenizer might divide the string in a different way.
Also, the encode function would be beneficial for some other use, as for example the utilization of the "logit_bias" parameter for OpenAI models.

So, what i was thinking about, was to export a pair of function that, given the model name, will be able to encode a string or decode a list of token with the appropriate Tokenizer

Here is a pseudo-code of the two function
```
def encode(model: str, text: str):
    # get the correct Tokenizer for the model as done in litellm:utils:token_counter
    return tokenizer.encode(text)

def decode(model: str, tokens: List[int]):
    # get the correct Tokenizer for the model as done in litellm:utils:token_counter
    return tokenizer.decode(tokens)
```

I already dug into your codebase and in the following function https://github.com/BerriAI/litellm/blob/123c0f41f892eb0f5ba02691a2019aae647ce56b/litellm/utils.py#L872 you already load the appropriate tokenizer for each model and use the encode function of that Tokenizer to count the tokens in a string. The only thing that needs to be done should be to encapsulate the flow of getting the appropriate Tokenizer given a model in a different function and create 2 more functions that simply retrieve the tokenizer and encode/decode the user input

**Comment by ghost** [comment]
ok sounds good - i'll do this now. 

Would be helpful to understand how you're using litellm. Can you chat for 10 minutes today/this week? 

https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by ghost** [comment]
Pushed - https://github.com/BerriAI/litellm/commit/4eeadd284a7f582fc7dedbaae1388d7372de4f4b.
