### ISSUE TITLE
[Bug]: Cannot specify aws_session_token for /model/update

### ISSUE THREAD

**Issue by sbhal** [BerriAI/litellm#6463]
### What happened?

A bug happened!

### Relevant log output

```shell
curl -X 'POST' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "model_name": "xxx",
  "litellm_params": {
    "aws_access_key_id": xxx,
    "aws_secret_access_key": xxx,
    "aws_session_token": xxx
  },
  "model_info": {
	  "id": xxx
  }
}'
```

**Comment by ghost** [comment]
what's the error?

**Comment by sbhal** [comment]
aws_session_token isn't listed in Swagger UI and model isn't getting updated with new aws_session_token. I don't get any error.
Example schema only shows
```
"aws_access_key_id": "string",
"aws_secret_access_key": "string",
"aws_region_name": "string",
```
omitting `aws_session_token`.

Looking at https://github.com/BerriAI/litellm/blob/44e7ffd05cc65a461cbd407527244002f4f8a69a/litellm/types/router.py#L162 does seem like `aws_session_token` is missing.

**Comment by sbhal** [comment]
Updated to latest build and I can update `aws_session_token`. I was using outdated build.
