### ISSUE TITLE
[Feature]: Adding extra headers support for embedding, image generation, and other Azure provider functions

### ISSUE THREAD

**Issue by jasonkuoWT** [BerriAI/litellm#6465]
### The Feature

I noticed that the completion feature already supports adding extra headers effectively, as #4833 . However, I couldn't find this parameter implemented for other functionalities in the Azure provider within the source code.

### Motivation, pitch

Since completion already supports this, I hope other functionalities can support it as well. This would be very helpful for handling integrations with Azure APIM.

**Comment by ishaan-jaff** [comment]
hi @jasonkuoWT  - curious do you use LiteLLM Proxy in production or are you evaluating it ?

If yes, we'd love to hop on a call to get your feedback on how we can improve. Sharing our calendly for your convenience https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by jasonkuoWT** [comment]
Yes, we are using LiteLLM Proxy in our production environment. We appreciate how quickly you have adapted to meet our needs. We have also successfully integrated the backend with Azure APIM.

**Comment by ghost** [comment]
Got it - can we do a 10min call this/next week to learn how you're using litellm? 


https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by jasonkuoWT** [comment]
Okay, I'll discuss with my team and book a time. Thank you!
