### ISSUE TITLE
[Bug]: Prompt tokens different in streaming/non-streaming request to vision model

### ISSUE THREAD

**Issue by noobHappylife** [BerriAI/litellm#6488]
### What happened?

When using vision language model, I noticed different providers (inference engine) can have un-matched prompt token counts in the usage in streaming v.s. non-streaming request. I'm using litellm==1.51.0

| Provider    | usage from                                      | Prompt Tokens |
|-------------|-------------------------------------------------|---------------|
| vllm        | stream_options={"include_usage": True}          | 725           |
| vllm        | non-stream                                      | 725           |
| openai      | stream_options={"include_usage": True}          | 19847         |
| openai      | non-stream                                      | 19847         |
| hyperbolic  | stream_options={"include_usage": True}          | 28            |
| hyperbolic  | non-stream                                      | 725           |
| anthropic   | stream_options={"include_usage": True}          | 98            |
| anthropic   | non-stream                                      | 730           |
| together_ai | stream_options={"include_usage": True}          | 17            |
| together_ai | non-stream                                      | 17            |

Same image across all queries, it's clear that the usage from vLLM and OpenAI is consistent. But the usage from Hyperbolic, Anthropic is wrong when streaming, much lower than the usage when it is non-streaming (perhaps image tokens are not counted?). While Together_AI seems like missing image tokens count. 

May I know is this an expected behavior?

**Comment by ishaan-jaff** [comment]
@noobHappylife can you share the requests non-streaming and streaming your sending anthropic so we can repro

**Comment by noobHappylife** [comment]
The code i use to test the prompt tokens count.

```python
from litellm import completion, Router, stream_chunk_builder
import asyncio, os, traceback

messages = [
    {
        "role": "user",
        "content": [
            {
                "type": "text",
                "text": "What’s in this image?"
            },
            {
                "type": "image_url",
                "image_url": {
                    "url": "https://th.bing.com/th/id/OIP.EGNstT4uilQv7zcc_kIEBAHaSC?rs=1&pid=ImgDetMain",
                }
            }
        ]
    }
]

model_list = [
    {
        "model_name": "vllm", # this is a vLLM service we self-hosted
        "litellm_params": {
            "model": "openai/ELLM/Qwen2-VL-7B",
            "api_key": "dummy",
            "api_base": VLLM_API_BASE
        }
    },
    {
        "model_name": "anthropic",
        "litellm_params": {
            "model": "anthropic/claude-3-haiku-20240307", 
            "api_key": ANTHROPIC_KEY,
        }
    },
    {
        "model_name": "openai",
        "litellm_params": {
            "model": "openai/gpt-4o-mini",
            "api_key": OPENAI_KEY,
        }
    },
    { 
        "model_name": "together_ai",
        "litellm_params": {
            "model": "together_ai/meta-llama/Llama-3.2-11B-Vision-Instruct-Turbo",
            "api_key": TOGETHER_AI_KEY
        }
    },
    { 
        "model_name": "hyperbolic", 
        "litellm_params": {
            "model": "openai/Qwen/Qwen2-VL-7B-Instruct", 
            "api_key": HYPERBOLIC_KEY,
            "api_base": "https://api.hyperbolic.xyz/v1",
        }
    },
]

router = Router(model_list=model_list)

async def completion_call(model,stream):
    try:
        response = await router.acompletion(
            model=model,
            messages=messages,
            stream=stream,
            stream_options={"include_usage": True} if stream else None,
            max_tokens=15,
        )
        parts = []
        if stream:
            async for part in response:
                parts.append(part)
            print("last chunk", parts[-1].usage)
            completion = stream_chunk_builder(parts, messages=messages)
            print("from stream_chunk_builder", completion.usage)
        else:
            print("non-stream", response.usage)
        return parts
    except:
        print(f"error occurred: {traceback.format_exc()}")
        pass

for model in ["vllm", "openai", "hyperbolic", "anthropic", "together_ai"]:
    print(f"TEST PROVIDER:{model}")
    for stream in [True, False]:
        parts = asyncio.run(completion_call(model, stream))
```

**Comment by ghost** [comment]
This is caused by us doing token estimations for streaming. Fixed here -  https://github.com/BerriAI/litellm/commit/e693386049f424cf2a1466951e5aa46c4685a785
