### ISSUE TITLE
[Feature]: Add token trimming to proxy server 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#649]
### The Feature

Enable user to turn on token trimming for models used via proxy server 

### Motivation, pitch

<img width="1038" alt="Screenshot 2023-10-19 at 9 25 08 AM" src="https://github.com/BerriAI/litellm/assets/17561003/7997eaa4-8f95-4548-8a78-1e611e8e63f1">

**Comment by ldavis9000aws** [comment]
Thank you. Apologies for the rant, lol. Here is some additional context: 
![image](https://github.com/BerriAI/litellm/assets/42821964/625d9e8f-9889-4c88-8673-a87ebaabeb12)

**Comment by ghost** [comment]
closing as cli is deprecated.
