### ISSUE TITLE
[Bug]: STORE_MODEL_IN_DB broken

### ISSUE THREAD

**Issue by chibitomo2** [BerriAI/litellm#6490]
### What happened?

When deploying a new Docker container, the following error occurs when adding a model:

**LiteLLM Proxy:ERROR: proxy_server.py:6716 - litellm.proxy.proxy_server.add_new_model(): Exception occured - 500: {'error': "Set `'STORE_MODEL_IN_DB='True'` in your env to enable this feature."}**

However, the STORE_MODEL_IN_DB environment variable is set correctly to True.

The regression is confirmed in the latest version v1.51.0. When I used an older version of LiteLLM v1.50.4 with the same env variables the issue was not reproducible and models are added successfully.

### Relevant log output

```shell
LiteLLM Proxy:ERROR: proxy_server.py:6716 - litellm.proxy.proxy_server.add_new_model(): Exception occured - 500: {'error': "Set `'STORE_MODEL_IN_DB='True'` in your env to enable this feature."}
```

**Comment by ishaan-jaff** [comment]
able to repro - working on a fix

**Comment by ishaan-jaff** [comment]
patched here @chibitomo2 https://github.com/BerriAI/litellm/pull/6492 


a root cause PR will be done this week to address the underlying issue

**Comment by ishaan-jaff** [comment]
hi @chibitomo2 - curious do you use LiteLLM Proxy in production or are you evaluating it ?

If yes, we'd love to hop on a call to get your feedback on how we can improve. Sharing our calendly for your convenience https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
