### ISSUE TITLE
[Bug]: Invitation link is invalid in user invitation process

### ISSUE THREAD

**Issue by sasanyasari** [BerriAI/litellm#6493]
### What happened?

I encountered a problem when trying to invite a user using the panel. After clicking "Create User," the generated invitation link does not include an "id" parameter, which seems to prevent the link from functioning correctly.

**Steps to Reproduce:**

Navigate to the "Internal Users" tab.
Click on the "Invite User" button.
Fill in the relevant details for the new user.
Click on "Create User" to generate the invitation link.
Observe the generated invitation link, which is missing the "id" parameter: <base_url>/ui

Thank you for looking into this issue. Please let me know if you need any further information.

**Comment by ishaan-jaff** [comment]
hi @sasanyasari  - curious do you use LiteLLM Proxy in production or are you evaluating it ?

If yes, we'd love to hop on a call to get your feedback on how we can improve. Sharing our calendly for your convenience https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
