### ISSUE TITLE
.env file read error -- flask app

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#65]
until i did
```
import os, dotenv
dotenv.load_dotenv()
```

in my main.py, litellm wasn't able to read my environment variables - seems like some sort of bug.

**Comment by ghost** [comment]
faced this issue while trying to create a flask app

**Comment by zakhar-kogan** [comment]
Looks like the default use case? 🤔

[From here](https://pypi.org/project/python-dotenv/):
```python
from dotenv import load_dotenv
load_dotenv()  # take environment variables from .env.
```

**Comment by ishaan-jaff** [comment]
works when you use dotenv
