### ISSUE TITLE
[Feature]: expose register model for litellm

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#650]
### The Feature

Expose a way for a user to register a new model w/ cost, provider, etc. 

```
import litellm 

# on import litellm runs get_cost_model_map() 

custom_json_file = {
"anthropic.claude-2": {
"pricing": # 
"max_tokens": # 
}
}

litellm.register_model(models=custom_json_file) # re-runs the list initialization
```

### Motivation, pitch

cc: @jsherer

**Comment by ghost** [comment]
pushed here: https://github.com/BerriAI/litellm/commit/8dda69e2165a3e410855b0fd4b784f7d341fc823

will update this ticket once feature is in prod.

**Comment by ghost** [comment]
this is in prod in v`0.11.1`
