### ISSUE TITLE
[Feature]: expose api base for all providers

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#651]
### The Feature

have `completion(...api_base=..)` work for all providers. Including anthropic. 

### Motivation, pitch

When using proxy servers, they need the api url to be in http://, instead of https://.

**Comment by ghost** [comment]
anthropic api base can now be set - https://github.com/BerriAI/litellm/commit/76bf8c4be333242e2bf6eaf37f8f91874b145329

@ishaan-jaff  i believe that was the min requirement for this ticket, unless i'm missing anything

**Comment by ghost** [comment]
Providers we still need to add support for: 

- [x] TogetherAI 
- [x] Replicate
- [x] NLP Cloud 
- [x] Aleph Alpha 
- [x] Cohere
- [x] DeepInfra
- [ ] Palm
- [ ] VertexAI 
- [x] AI21
- [ ] Sagemaker
- [ ] Bedrock


I don't believe we can support it for: 
- Palm
- VertexAI
- Sagemaker
- Bedrock 

as we use client libraries (google_genai and boto3 respectively) for them.

**Comment by ghost** [comment]
addressed here - https://github.com/BerriAI/litellm/commit/00993f3575970143a9392dd8d76eb4f9f3fec060.

**Comment by ghost** [comment]
Will update ticket once this is in prod

**Comment by ghost** [comment]
this is in prod in v`0.11.1`
