### ISSUE TITLE
[Bug]: drop_params=True not working for dimensions parameter with OpenAI-compatible endpoints

### ISSUE THREAD

**Issue by NolanTrem** [BerriAI/litellm#6516]
### What happened?

When using OpenAI-compatible endpoints, setting `litellm.drop_params = True` does not prevent the `dimensions` parameter from being passed to the API, resulting in an UnsupportedParamsError. Would love to get this fixed [so that we could better support LM Studio in R2R.](https://github.com/SciPhi-AI/R2R/issues/1495)

Example output when running without/with dimensions set:
![Screenshot 2024-10-30 at 11 39 56 AM](https://github.com/user-attachments/assets/2d4a8309-1558-40a8-8df0-49f8e68e3156)

And the code to replicate:
```
import litellm
import logging
from typing import Dict, Any
import json

logging.basicConfig(
    level=logging.INFO,
    format='%(message)s'  # Simplified logging format
)
logger = logging.getLogger(__name__)

def test_embedding(test_name: str, params: Dict[str, Any]) -> None:
    print(f"\n=== Test: {test_name} ===")
    print(f"Parameters: {json.dumps(params, indent=2)}")
    print(f"litellm.drop_params is set to: {litellm.drop_params}")
    
    try:
        response = litellm.embedding(**params)
        print("\nResponse received successfully!")
        
        if response and hasattr(response, 'data') and response.data:
            embeddings = [d['embedding'] for d in response.data if 'embedding' in d]
            if embeddings:
                print(f"Success! First embedding length: {len(embeddings[0])}")
            else:
                print("No embeddings found in response data")
            
    except Exception as e:
        print(f"\nError occurred:")
        print(f"Error message: {str(e)}")
        print(f"Error type: {type(e)}")

def main():
    # Base parameters
    base_params = {
        "model": "openai/text-embedding-nomic-embed-text-v1.5-embedding",
        "api_base": "http://localhost:1234/v1",
        "api_key": "fake-api-key-123",
        "input": ["This is a test sentence for embeddings."]
    }
    
    # Set drop_params to True as recommended in the error message
    litellm.drop_params = True
    print(f"Setting litellm.drop_params = {litellm.drop_params}")
    
    # Test 1: Without dimensions parameter
    test_embedding("Without dimensions parameter", base_params.copy())
    
    # Test 2: With dimensions parameter
    params_with_dimensions = base_params.copy()
    params_with_dimensions["dimensions"] = 768
    test_embedding("With dimensions parameter", params_with_dimensions)

if __name__ == "__main__":
    main()
```

### Relevant log output

```shell
Error message: litellm.UnsupportedParamsError: Setting dimensions is not supported for OpenAI `text-embedding-3` and later models. To drop it from the call, set `litellm.drop_params = True`.
Error type: <class 'litellm.exceptions.UnsupportedParamsError'>
```

**Comment by ghost** [comment]
that's not a bug though - since `dimensions` is an openai param, i would expect it to be passed along

**Comment by ghost** [comment]
you can work around this today with this - https://docs.litellm.ai/docs/completion/drop_params#specify-params-to-drop


but i guess the real ask is to have native support for LM Studio. So, closing in favor of #3755

**Comment by NolanTrem** [comment]
I see. This gets a little messy in our implementation then, since we try to just have a generic litellm class that routes the requests. It feels a bit tacky to conditionally check if it is truly an OpenAI request (which we do use, and in many cases specify the dimensions) vs. an OpenAI-like request...

[For reference](https://github.com/SciPhi-AI/R2R/blob/main/py/core/providers/embeddings/litellm.py)

Is native support on the near-term roadmap?

**Comment by ghost** [comment]
that's reasonable - yes we can add it this weekend. 

For future integrations (other openai-like api's that might need some param add/drop logic) what would the ideal flow be?

**Comment by ghost** [comment]
Closing in favor of https://github.com/BerriAI/litellm/issues/3755
