### ISSUE TITLE
[Bug]: Unexpected Model Reference in LiteLLM API Call Logs – Clarification Needed on Model Cost Mapping

### ISSUE THREAD

**Issue by lightmatmul** [BerriAI/litellm#6518]
### What happened?

I'm experiencing some confusion with the API call through LiteLLM. I'm sending a POST request with the following parameters:
```bash
curl -X POST \
https://api.together.xyz/v1/ \
-d '{'model': 'meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo'
```
LiteLLM Success Log Details:
```python
Logging Details LiteLLM-Success Call: Cache_hit=None
Looking up model=together-ai-41.1b-80b in model_cost_map
```

My question is whether LiteLLM is mistakenly calling `together-ai-41.1b-80b` instead of `meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo` or if this is simply related to model cost mapping in the logs.

**Comment by ghost** [comment]
no. the look up is for cost calc. 

there is no such model called 'together-ai-41.1b-80b'
