### ISSUE TITLE
[Feature]: Add better docs for function calling 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#653]
### The Feature

OpenAI doesn't really explain function calling that well. 

It would be helpful to have good docs on this. 

Maybe from this announcement - https://openai.com/blog/function-calling-and-other-api-updates

### Motivation, pitch

user request

**Comment by ghost** [comment]
<img width="546" alt="Screenshot 2023-10-19 at 2 26 16 PM" src="https://github.com/BerriAI/litellm/assets/17561003/88b76dc7-0bf1-4529-a3d8-f14810f6e775">

Make it clear that the "----" is required, also how many dashes ("-") need to exist.

**Comment by ghost** [comment]
cc: @dfs99

**Comment by Fakamoto** [comment]
Where is the documentation?

**Comment by ghost** [comment]
https://docs.litellm.ai/docs/completion/function_call
