### ISSUE TITLE
[Feature]: Allow callers to pass an httpx client to acompletion()

### ISSUE THREAD

**Issue by nvonpentz** [BerriAI/litellm#6538]
### The Feature

I'd like to pass an httpx client I've already instantiated in my application to the acompletion calls.  I've managed to do this for open AI APIs by creating my own open AI client and passing my httpx client to that, and then passing the open AI client to the acompletion call.  However, the same does not work for AWS Bedrock calls.

### Motivation, pitch

The httpx client has been instrumented with custom behavior, e.g. it collects prometheus metrics - that's why I want to use this one specifically.

**Comment by nvonpentz** [comment]
Looks like this is the line - https://github.com/BerriAI/litellm/blob/b73039b28337c04ac87eea8e0be11186f142f38f/litellm/llms/bedrock/chat/converse_handler.py#L169

The httpx_client I pass to acompletion as `client` is not an instance of AsyncHTTPHandler.

By creating a custom AsyncHTTPHandler class, I was able to get the functionality I wanted.

```
class CustomAsyncHTTPHandler(AsyncHTTPHandler):
    def __init__(
        self,
        existing_client: httpx.AsyncClient,
        timeout: Optional[Union[float, httpx.Timeout]] = None,
        event_hooks: Optional[Mapping[str, List[Callable[..., Any]]]] = None,
        concurrent_limit=1000,
    ):
        self.timeout = timeout
        self.event_hooks = event_hooks
        self.client = existing_client  # Use the existing client instead of creating a new one
```

**Comment by ghost** [comment]
so this is a no-op then? 

looks like you have a solution

**Comment by nvonpentz** [comment]
@krrishdholakia I do have a workaround - but it's a bit of a hack.

In order to pass a custom httpx client for openAI calls, bedrock calls, and Anthropic calls, I need to do three different things - 

* openAI - create a custom async openAI client, pass the httpx_client to that, pass the openai client to the `client` parameter
* Anthropic - simply pass the custom httpx_client to `client` parameter
* Bedrock - wrap my httpx client in a custom AsyncHTTPHandler class, pass that as the `client` parameter

Seems like the `client` object can be expected to be multiple things (entire open AI clients, httpx_clients, or this AsyncHTTPHandler) in different contexts.  It's not clear what to pass there - I had to work it out from trial and error.
