### ISSUE TITLE
[Bug]: When calling cohere-embed-v3 models via Azure AI, the model name in response is always `Cohere-embed-v3-multilingual`

### ISSUE THREAD

**Issue by taralika** [BerriAI/litellm#6540]
### What happened?

Make a request to cohere-embed-v3-english model via litellm proxy:
```
curl https://proxy-host/embeddings \
  -H 'Content-Type: application/json' \
  -H "api-key: $api_key" \
  -d '{"model":"cohere-embed-v3-english","input":["Cats are my friends"]}'
```
response:
```
{
	"model": "Cohere-embed-v3-multilingual",
	"data": [
		{
			"embedding": [
				0.00928497314453125,
				0.007843017578125,
				...
			],
			"index": 0,
			"object": "embedding"
		}
	],
	"object": "list",
	"usage": {
		"completion_tokens": 0,
		"prompt_tokens": 4,
		"total_tokens": 4,
		"completion_tokens_details": null,
		"prompt_tokens_details": null
	}
}
```

Expected that the model in response should be `embed-english-v3.0` since this is the exact model name I get when calling the Azure AI endpoint directly (not thru litellm proxy)

The cause for this issue is: https://github.com/BerriAI/litellm/blob/b73039b28337c04ac87eea8e0be11186f142f38f/litellm/llms/azure_ai/embed/cohere_transformation.py#L25

You shouldn't need to do any model name mapping or look in header for model name like this: https://github.com/BerriAI/litellm/blob/b73039b28337c04ac87eea8e0be11186f142f38f/litellm/llms/azure_ai/embed/cohere_transformation.py#L92 because the Azure API response already has the `model` field in it, just pass this as is to the client thru the proxy and this bug should get fixed.

**Comment by ghost** [comment]
Fixed with - https://github.com/BerriAI/litellm/commit/c5833129706323a391272f4f599b34e461301486. We need consistent model names for cost calculation - that's why we're trying to use the header to infer this. Open to suggestions here @taralika
