### ISSUE TITLE
[Feature]: Need "/v1/embeddings" endpoint

### ISSUE THREAD

**Issue by tranhoangnguyen03** [BerriAI/litellm#656]
### The Feature

A new endpoint that allows users to generate embeddings for text, code, or other data formats. Embeddings are vector representations of data that can be used for a variety of tasks, such as machine learning, natural language processing, and information retrieval.

### Motivation, pitch

The ability to generate embeddings is a valuable tool for a wide range of tasks:
- RAG pipeline
- Sentiment analysis
- Topic modeling

Also, llama.cpp Python API has it.

**Comment by ghost** [comment]
Hi @tranhoangnguyen03 this already exists - https://docs.litellm.ai/docs/embedding/supported_embedding

what am i missing?

**Comment by tranhoangnguyen03** [comment]
It doesn't appear as an endpoint on the FastAPI server.

**Comment by ghost** [comment]
gotcha. @tranhoangnguyen03 is there a specific problem you need the proxy to have embeddings for as well? 

i'd initially written it to focus on translating between openai and non-openai completion calls. 

Would love to learn more about your use-case: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by tranhoangnguyen03** [comment]
Well, Llama-index modules make use of both the completion api as well as the embedding api to construct vector indexes. I set the llm to be the mock OpenAI server, and it was able to handle the text summary part, but got stuck on the embedding generation part. And the proxy server was outputting 400 response errors for the request to v1/embedding endpoint.

**Comment by ghost** [comment]
oh that makes sense, do you have some test code for llama index that i can run and make sure we have all the required coverage? @tranhoangnguyen03

**Comment by ghost** [comment]
picking this up tomorrow @tranhoangnguyen03

**Comment by tranhoangnguyen03** [comment]
@krrishdholakia Please have a look at [this notebook](https://colab.research.google.com/drive/1ZH-D3tvMTUOL48QIm6-lHniuwEuEzsNB?usp=sharing).

The part relevant to the embedding endpoint is this part:
```
# setup LLM
llm = OpenAI(
    temperature=0.0,
    max_tokens=4000,
    api_base='https://fbf3-34-125-247-203.ngrok-free.app/v1', 
    api_key='fake_key'
)

# setup embedding model 
embedding_model = HuggingFaceEmbedding("sentence-transformers/all-mpnet-base-v2")

# define service context
service_context = ServiceContext.from_defaults(
    chunk_size=1000,
    llm=llm,
    # embed_model=embedding_model, # if not set, then defaults to embedding endpoint from llm
)
```

**Comment by ghost** [comment]
Live now - https://github.com/BerriAI/litellm/commit/822b0b55e82ba062bfa470f534b443b2b6c7a2a8

@tranhoangnguyen03 how would you call sentence-transformers via the endpoint? wouldn't you need to host it somewhere?

**Comment by ghost** [comment]
Closing issue as the endpoint is now live on proxy. @tranhoangnguyen03 Please reopen if this didn't solve your problem.
