### ISSUE TITLE
[Bug]: Tool_choice not supported with watsonx.ai.

### ISSUE THREAD

**Issue by yobens5** [BerriAI/litellm#6562]
### What happened?

In the updated watsonx.ai API, tool_choice and tools parameters are avaible but not mapped with liteLLM.
More documentation to use it here: https://cloud.ibm.com/apidocs/watsonx-ai#text-chat
<img width="544" alt="Screenshot 2024-10-31 at 11 02 51" src="https://github.com/user-attachments/assets/c295ff3a-79f7-41a1-817f-8741f4919260">

Looks because the litellm only whitelists certain parameters for each LLM including watsonx (per what they support or not according to [this page](https://urldefense.proofpoint.com/v2/url?u=https-3A__docs.litellm.ai_docs_completion_input&d=DwMGaQ&c=BSDicqBQBDjDI9RkVyTcHQ&r=GuvHJfo8e33rY54DZP5Hk6oVgNXHkQfAh6rAZEf1KP8&m=4Bw__0xh4u7Od3mxoEBcR7Vb9lFS79PYpnTPJTLwT9gsd6PUqZOEFAZwePpRC3V7&s=RICuMx7gE4742ow_AdxcRrKh-bYAXmG6MLxDtO3EUkc&e=)). 
![image](https://github.com/user-attachments/assets/9a6732b8-09e7-4795-b66b-e17a914240b1)

**Comment by ghost** [comment]
Interesting - looks like a new api from watsonx - `/text/chat`

**Comment by ghost** [comment]
this is a broader than expected ticket - but a good one. 

It looks like the watsonx `/text/chat` endpoint is a lot more capable (supports messages, tool role, etc.) 

I'm not sure if this is a beta endpoint or not, so we can begin by exposing it via a `watsonx_chat/` route, and make it the default route if this ends up being the more stable option

**Comment by yobens5** [comment]
Thank you for that!
