### ISSUE TITLE
[Bug]: raise validation error for anthropic message input on `.completion` call 

### ISSUE THREAD

**Issue by markokraemer** [BerriAI/litellm#6565]
### What happened?

Anthropic output:
<img width="1093" alt="Screenshot 2024-11-03 at 23 42 14" src="https://github.com/user-attachments/assets/e9a2d53d-fb5c-4813-80b7-c09b83134e61">

LiteLLM output:
<img width="1101" alt="Screenshot 2024-11-03 at 23 42 26" src="https://github.com/user-attachments/assets/a2aee7ba-a3f5-40de-9c1c-eaf25a641f4e">

Commit with LiteLLM code:
https://github.com/markokraemer/claude-vision-ui-detection/tree/38e15cfc779622752edbb894e5477c7652a12a4b with LiteLLM 

Repo with Anthropic:
https://github.com/markokraemer/claude-vision-ui-detection with Anthropic SDK

I use LiteLLM for everything, but this is making me worry. Its probably just some defaults that are different. 

### Twitter / LinkedIn details

https://twitter.com/markokraemer

**Comment by markokraemer** [comment]
Its not just variance in one-time outputs. Its over and over again, even when I change the temperature around on both – just two different types of outputs.

**Comment by ghost** [comment]
can you please share a minimal script for repro - i'm not sure what the expected inputs for the repo you've shared should be, and i'd like to make sure i'm using your e2e flow

**Comment by ghost** [comment]
You can see our defaults here @markokraemer  - https://github.com/BerriAI/litellm/blob/587d5fe2773441cebed8a4a68be84e0c1860adc0/litellm/llms/anthropic/chat/transformation.py#L28

the only thing we set is `max_tokens`, if you haven't set it. 


if you run your call with `litellm.set_verbose = True`, you should be able to see the raw request being made by litellm to anthropic

**Comment by markokraemer** [comment]
There is just the single main.py – you can just python main.py run it in both versions & see the difference to reproduce

**Comment by markokraemer** [comment]
The input is just path towards like test1.png from the repo for example.

**Comment by ghost** [comment]
Here's the raw request sent by anthropic sdk vs litellm sdk (i got this by setting up a fake anthropic server, to receive the call from both) https://gist.github.com/krrishdholakia/b19f7b65ca46f1d2791abcf4d782a7be

**Comment by ghost** [comment]
the image object sent by you is not in the openai format. this means litellm is skipping this as it does the openai -> anthropic translation @markokraemer 

<img width="719" alt="Screenshot 2024-11-04 at 12 58 10 PM" src="https://github.com/user-attachments/assets/00e032e6-9005-4e0b-9788-ad446e66c55f">


i believe the action item here should be to raise a validation error, so this error is easy to identify.

**Comment by markokraemer** [comment]
Oh god, I should´ve caught that. Thanks. Great support <3
