### ISSUE TITLE
[Bug]:  LLMonitor integration does not consider function call responses

### ISSUE THREAD

**Issue by paulpierre** [BerriAI/litellm#657]
### What happened?

Issue:
`The llmonitor integration assumes all chat completion responses are messages with the "content" key populated. In the case of function call responses, this is not the case.`

Expected:
`The llmonitor integration should include function call responses as part of its logging cases`

Steps:
1. Setup Azure model credentials with litellm (`gpt-4-0613`)
1. Add llmonitor to success callbacks
2. Create completion with litellm
3. Include `functions` and `functions_call` (auto)
4. Set `user` message to trigger function call

### Relevant log output

```shell
tests/services/test_llm_router.py::test_llmrouter_get_chat_completion_with_function LiteLLM: LLMonitor Logging - Logging request for model azure/gpt4-e2-1
LiteLLM: LLMonitor Logging Error - Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/litellm/integrations/llmonitor.py", line 107, in log_event
    "output": parse_messages(output),
  File "/usr/local/lib/python3.9/site-packages/litellm/integrations/llmonitor.py", line 39, in parse_messages
    return clean_message(input[0])
  File "/usr/local/lib/python3.9/site-packages/litellm/integrations/llmonitor.py", line 30, in clean_message
    return clean_message(message["message"])
  File "/usr/local/lib/python3.9/site-packages/litellm/integrations/llmonitor.py", line 34, in clean_message
    "text": message["content"],
KeyError: 'content'
```

### Twitter / LinkedIn details

https://twitter.com/paulpierre

**Comment by ishaan-jaff** [comment]
fixed here: https://github.com/BerriAI/litellm/commit/8e9340f3b9e846e098ef828462e1ab81fc11a521
