### ISSUE TITLE
[Bug]: ensure Anthropic prometheus token tracking

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#6599]
### What happened?

User reported inaccurate token tracking b/w anthropic console and litellm prometheus metrics (litellm_total_tokens) - investigate this 

Checking 4 cases:
- success
- success on streaming 
- failure
- clientside timeout

**Comment by ghost** [comment]
## Success

Works correctly

1. anthropic console 
<img width="1207" alt="Screenshot 2024-11-05 at 6 17 33 PM" src="https://github.com/user-attachments/assets/ddf3a058-b50f-44c8-bbbe-6f1d5c6ecec9">

2. returned api response 
<img width="1159" alt="Screenshot 2024-11-05 at 6 17 13 PM" src="https://github.com/user-attachments/assets/f2bffb38-fea0-47cb-96e9-7406d318e571">

3. logged prometheus value 
<img width="1611" alt="Screenshot 2024-11-05 at 6 17 09 PM" src="https://github.com/user-attachments/assets/762968be-6298-4278-abfc-df0ce122ea3b">

**Comment by ghost** [comment]
## Failure 

Anthropic doesn't track token cost for a failed llm call 
<img width="1544" alt="Screenshot 2024-11-05 at 6 29 45 PM" src="https://github.com/user-attachments/assets/26b25064-3ff8-4284-beb8-71fdedeccde5">

**Comment by ghost** [comment]
## Clientside Request timeout 

1. no tokens returned via api 
<img width="1154" alt="Screenshot 2024-11-05 at 6 34 25 PM" src="https://github.com/user-attachments/assets/80072d7e-d2d4-4873-9a6d-57d7de28cd30">


2. No tokens tracked on prometheus 
<img width="833" alt="Screenshot 2024-11-05 at 6 30 56 PM" src="https://github.com/user-attachments/assets/8efd330c-04a9-4ecd-bcaa-9e5a5c6a188d">


3. No usage tracked for a request when there's a timeout 
<img width="1481" alt="Screenshot 2024-11-05 at 6 34 40 PM" src="https://github.com/user-attachments/assets/c8bb22e4-a385-4568-8d07-2c5cb3698255">

**Comment by ghost** [comment]
## Streaming

1. Anthropic console usage for streaming request (total_tokens=53)
<img width="1223" alt="Screenshot 2024-11-05 at 6 38 30 PM" src="https://github.com/user-attachments/assets/8332233b-16b0-4336-beb4-c873b0c45eb2">

2. Prometheus metrics using estimated token values (57) 
<img width="1603" alt="Screenshot 2024-11-05 at 6 37 54 PM" src="https://github.com/user-attachments/assets/3f976649-571c-4941-9f00-6e684a7ab75b">

**Comment by ghost** [comment]
## Streaming + timeouts 

Anthropic doesn't count total tokens if client disconnects
<img width="1303" alt="Screenshot 2024-11-05 at 6 39 52 PM" src="https://github.com/user-attachments/assets/94be5c9a-ba23-47da-b2d4-cb7e7b88d08d">
