### ISSUE TITLE
[Bug]: Internal User (View Only) permissions not working, user can make keys

### ISSUE THREAD

**Issue by tkg61** [BerriAI/litellm#6626]
### What happened?

When creating a new user with internal viewer permissions it would be assumed they can not create a key but they currently can: 

here is the admin view
![image](https://github.com/user-attachments/assets/0fe3eafd-e182-4a92-bc15-3e98d2806690)

here is what is seen when the user logs in:

![image](https://github.com/user-attachments/assets/358d91d5-3454-46ec-bda5-239e2f8dbe1d)

Also there are 2 keys listed on the admin page and an automated key created when the user didn't even make a key yet...

**Comment by ishaan-jaff** [comment]
fixed here @tkg61 https://github.com/BerriAI/litellm/pull/6764

**Comment by ishaan-jaff** [comment]
hi @tkg61 - curious do you use LiteLLM Proxy in production or are you evaluating it ?

If yes, we'd love to hop on a call to get your feedback on how we can improve. Sharing our calendly for your convenience https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
