### ISSUE TITLE
In case of multiple deployments ? 

### ISSUE THREAD

**Issue by jalotra** [BerriAI/litellm#666]
hey devs, 
was looking at this piece of code, I think the idea was 
```
if there are multiple deployments of same model X, then make N parallel calls using a ThreadPoolExecutor and wait on the 1st one that takes least time and return the result.
```
The master code is doing something else : 
line : https://github.com/BerriAI/litellm/blob/8f586b3913c034b2c787192491f69c70d0cb9c83/litellm/main.py#L1402

**Comment by jalotra** [comment]
Q : Why are the main logic lines commented ?

**Comment by jalotra** [comment]
@krrishdholakia please check once !

**Comment by ghost** [comment]
hey @jalotra  where is it commented out? 
<img width="519" alt="Screenshot 2023-10-21 at 10 49 59 AM" src="https://github.com/BerriAI/litellm/assets/17561003/8e0e0950-3fc3-4351-ab8d-1e6eda8ee715">

**Comment by jalotra** [comment]
hey @krrishdholakia 
the .result() is a blocking call afaik, so what is happening here is it will block on the 1st future and then just return the result. 
Even if some other future has already completed. 

What happens in .result() -> https://github.com/python/cpython/blob/6c23635f2b7067ef091a550954e09f8b7c329e3f/Lib/concurrent/futures/_base.py#L428

**Comment by ghost** [comment]
great catch - @jalotra, pushed a fix - https://github.com/BerriAI/litellm/commit/cd0e699bcfdde3be5795ba0312fbfbe6abdfc25f

I believe this should resolve it. Let me know if this works for you. 

Are you currently using multiple azure deployments?

**Comment by jalotra** [comment]
thanks, not using multiple deployments; was just reading code after your linkedin post !
