### ISSUE TITLE
issues report

### ISSUE THREAD

**Issue by dingyouming** [BerriAI/litellm#668]
In [4]: response = completion(
   ...:   model="huggingface/WizardLM/WizardCoder-Python-34B-V1.0",
   ...:   messages=[{ "content": "Hello, how are you?","role": "user"}],
   ...:   #api_base="https://my-endpoint.huggingface.cloud"
   ...: )

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

---------------------------------------------------------------------------
HuggingfaceError                          Traceback (most recent call last)
File ~\anaconda3\envs\litellm\lib\site-packages\litellm\main.py:780, in completion(model, messages, functions, function_call, temperature, top_p, n, stream, stop, max_tokens, presence_penalty, frequency_penalty, logit_bias, user, deployment_id, request_timeout, api_base, api_version, api_key, **kwargs)
    776 hf_headers = (
    777     headers
    778     or litellm.headers
    779 )
--> 780 model_response = huggingface_restapi.completion(
    781     model=model,
    782     messages=messages,
    783     api_base=api_base, # type: ignore
    784     headers=hf_headers,
    785     model_response=model_response,
    786     print_verbose=print_verbose,
    787     optional_params=optional_params,
    788     litellm_params=litellm_params,
    789     logger_fn=logger_fn,
    790     encoding=encoding,
    791     api_key=huggingface_key,
    792     logging_obj=logging,
    793     custom_prompt_dict=litellm.custom_prompt_dict
    794 )
    795 if "stream" in optional_params and optional_params["stream"] == True:
    796     # don't try to access stream object,

File ~\anaconda3\envs\litellm\lib\site-packages\litellm\llms\huggingface_restapi.py:292, in completion(model, messages, api_base, headers, model_response, print_verbose, encoding, api_key, logging_obj, custom_prompt_dict, optional_params, litellm_params, logger_fn)
    291     print_verbose(f"response.status_code: {response.status_code}")
--> 292     raise HuggingfaceError(
    293         message=completion_response["error"],
    294         status_code=response.status_code,
    295     )
    296 else:

HuggingfaceError: Model WizardLM/WizardCoder-Python-34B-V1.0 is currently loading

During handling of the above exception, another exception occurred:

APIError                                  Traceback (most recent call last)
Cell In[4], line 1
----> 1 response = completion(
      2   model="huggingface/WizardLM/WizardCoder-Python-34B-V1.0",
      3   messages=[{ "content": "Hello, how are you?","role": "user"}],
      4   #api_base="https://my-endpoint.huggingface.cloud"
      5 )

File ~\anaconda3\envs\litellm\lib\site-packages\litellm\utils.py:827, in client.<locals>.wrapper(*args, **kwargs)
    823     if (
    824         liteDebuggerClient and liteDebuggerClient.dashboard_url != None
    825     ):  # make it easy to get to the debugger logs if you've initialized it
    826         e.message += f"\n Check the log in your dashboard - {liteDebuggerClient.dashboard_url}"
--> 827 raise e

File ~\anaconda3\envs\litellm\lib\site-packages\litellm\utils.py:786, in client.<locals>.wrapper(*args, **kwargs)
    783             return cached_result
    785 # MODEL CALL
--> 786 result = original_function(*args, **kwargs)
    787 end_time = datetime.datetime.now()
    788 if "stream" in kwargs and kwargs["stream"] == True:
    789     # TODO: Add to cache for streaming

File ~\anaconda3\envs\litellm\lib\site-packages\litellm\timeout.py:53, in timeout.<locals>.decorator.<locals>.wrapper(*args, **kwargs)
     51     local_timeout_duration = kwargs["request_timeout"]
     52 try:
---> 53     result = future.result(timeout=local_timeout_duration)
     54 except futures.TimeoutError:
     55     thread.stop_loop()

File ~\anaconda3\envs\litellm\lib\concurrent\futures\_base.py:446, in Future.result(self, timeout)
    444     raise CancelledError()
    445 elif self._state == FINISHED:
--> 446     return self.__get_result()
    447 else:
    448     raise TimeoutError()

File ~\anaconda3\envs\litellm\lib\concurrent\futures\_base.py:391, in Future.__get_result(self)
    389 if self._exception:
    390     try:
--> 391         raise self._exception
    392     finally:
    393         # Break a reference cycle with the exception in self._exception
    394         self = None

File ~\anaconda3\envs\litellm\lib\site-packages\litellm\timeout.py:42, in timeout.<locals>.decorator.<locals>.wrapper.<locals>.async_func()
     41 async def async_func():
---> 42     return func(*args, **kwargs)

File ~\anaconda3\envs\litellm\lib\site-packages\litellm\main.py:1259, in completion(model, messages, functions, function_call, temperature, top_p, n, stream, stop, max_tokens, presence_penalty, frequency_penalty, logit_bias, user, deployment_id, request_timeout, api_base, api_version, api_key, **kwargs)
   1256     return response
   1257 except Exception as e:
   1258     ## Map to OpenAI Exception
-> 1259     raise exception_type(
   1260         model=model, custom_llm_provider=custom_llm_provider, original_exception=e, completion_kwargs=args,
   1261     )

File ~\anaconda3\envs\litellm\lib\site-packages\litellm\utils.py:3303, in exception_type(model, original_exception, custom_llm_provider, completion_kwargs)
   3301 # don't let an error with mapping interrupt the user from receiving an error from the llm api calls
   3302 if exception_mapping_worked:
-> 3303     raise e
   3304 else:
   3305     raise original_exception

File ~\anaconda3\envs\litellm\lib\site-packages\litellm\utils.py:2958, in exception_type(model, original_exception, custom_llm_provider, completion_kwargs)
   2956     else:
   2957         exception_mapping_worked = True
-> 2958         raise APIError(
   2959             status_code=original_exception.status_code,
   2960             message=f"HuggingfaceException - {original_exception.message}",
   2961             llm_provider="huggingface",
   2962             model=model
   2963         )
   2964 exception_mapping_worked = True
   2965 raise APIError(status_code=500, message=error_str, model=model, llm_provider=custom_llm_provider)

APIError: HuggingfaceException - Model WizardLM/WizardCoder-Python-34B-V1.0 is currently loading

   ...:    1256     return response
   ...:    1257 except Exception as e:
   ...:    1258     ## Map to OpenAI Exception
   ...: -> 1259     raise exception_type(
   ...:    1260         model=model, custom_llm_provider=custom_llm_provider, original_exception=e, completion_kwargs=a
   ...: rgs,
   ...:    1261     )
   ...:
   ...: File ~\anaconda3\envs\litellm\lib\site-packages\litellm\utils.py:3303, in exception_type(model, original_except
   ...: ion, custom_llm_provider, completion_kwargs)
   ...:    3301 # don't let an error with mapping interrupt the user from receiving an error from the llm api calls
   ...:    3302 if exception_mapping_worked:
   ...: -> 3303     raise e
   ...:    3304 else:
   ...:    3305     raise original_exception
   ...:
   ...: File ~\anaconda3\envs\litellm\lib\site-packages\litellm\utils.py:2958, in exception_type(model, original_except
   ...: ion, custom_llm_provider, completion_kwargs)
   ...:    2956     else:
   ...:    2957         exception_mapping_worked = True
   ...: -> 2958         raise APIError(
   ...:    2959             status_code=original_exception.status_code,
   ...:    2960             message=f"HuggingfaceException - {original_exception.message}",
   ...:    2961             llm_provider="huggingface",
   ...:    2962             model=model
   ...:    2963         )
   ...:    2964 exception_mapping_worked = True
   ...:    2965 raise APIError(status_code=500, message=error_str, model=model, llm_provider=custom_llm_provider)
   ...:
   ...: APIError: HuggingfaceException - Model WizardLM/WizardCoder-Python-34B-V1.0 is currently loading
  Cell In[5], line 1
    Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
         ^
SyntaxError: invalid syntax

**Comment by ishaan-jaff** [comment]
This is an error from the hugging face API  `Model WizardLM/WizardCoder-Python-34B-V1.0 is currently loading` 

You can retry the request after 1-2 min once the model has loaded
