### ISSUE TITLE
[Bug]: SambaNova AI model missing in model_prices_and_context_window.json

### ISSUE THREAD

**Issue by jacksonkasi1** [BerriAI/litellm#6687]
### What happened?

The LiteLLM documentation mentions support for SambaNova (refer to [documentation](https://docs.litellm.ai/docs/providers/sambanova)). However, SambaNova models are not listed in the `model_prices_and_context_window.json` file. This causes an issue when trying to use SambaNova as a provider, specifically with the model `Meta-Llama-3.1-8B-Instruct`.

**Expected Behavior**:
The model should be recognized in LiteLLM's `model_prices_and_context_window.json`, allowing it to be loaded and function calls to be supported without errors.

**Actual Behavior**:
When attempting to use the `Meta-Llama-3.1-8B-Instruct` model with the SambaNova provider, I receive the following error:

**Traceback (most recent call last):**
```sh
  File "/home/gitpod/.pyenv/versions/3.12.6/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/DevKic/main.py", line 293, in run_main_loop
    if not supports_function_calling(MODEL_NAME):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/litellm/utils.py", line 1794, in supports_function_calling
    raise Exception(
Exception: Model not found or error in checking function calling support. You passed model=Meta-Llama-3.1-8B-Instruct, custom_llm_provider=sambanova. Error: This model isn't mapped yet. model=Meta-Llama-3.1-8B-Instruct, custom_llm_provider=sambanova. Add it here - https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json.
```

**Steps to Reproduce**:
1. Attempt to use LiteLLM with the SambaNova provider and specify a SambaNova model (e.g., `Meta-Llama-3.1-8B-Instruct`).
2. Observe the error regarding missing model mapping in `model_prices_and_context_window.json`.

**Suggested Solution**:
Please add support for the SambaNova provider and the relevant models to `model_prices_and_context_window.json`. This would help avoid authentication and compatibility issues when using LiteLLM with SambaNova models.

**Additional Information**:
- You can reproduce this issue using this repository: [DevKic repo](https://github.com/jacksonkasi1/DevKic/blob/main/main.py#L21).
- Relevant log output is included above.
- My environment is set up as specified in the LiteLLM documentation, and other providers are working without issues.

### Twitter / LinkedIn details

https://www.linkedin.com/in/jacksonkasi

**Comment by rodrigo-92** [comment]
there's a PR here https://github.com/BerriAI/litellm/pull/7187 that hopefully gets reviewed and merged soon

**Comment by rodrigo-92** [comment]
@ishaan-jaff could you give us a hand here please?

**Comment by ishaan-jaff** [comment]
hi @rodrigo-92  ack on this - will take a look today
