### ISSUE TITLE
pydantic output is not working when the selected llm is gemini

### ISSUE THREAD

**Issue by mamueed** [BerriAI/litellm#6698]
Failed to convert text into a pydantic model due to the following error: litellm.AuthenticationError: geminiException - {
  "error": {
    "code": 400,
    "message": "API key not valid. Please pass a valid API key.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "API_KEY_INVALID",
        "domain": "googleapis.com",
        "metadata": {
          "service": "generativelanguage.googleapis.com"
        }
      }
    ]
  }
}
 Using raw output instead.

**Comment by ishaan-jaff** [comment]
the error is clearly telling you that your API Key for gemini is invalid `API key not valid. Please pass a valid API key.`
