### ISSUE TITLE
[Bug]: get_model_info() blows up for ollama models?

### ISSUE THREAD

**Issue by paul-gauthier** [BerriAI/litellm#6703]
### What happened?

Calls to `litellm.get_model_info()` with ollama models raise an exception.

I can run `litellm.completion()` just fine with those models.

```
$ pip freeze | egrep 'litellm|ollama'
litellm==1.52.4
ollama==0.3.3
```

### Relevant log output

```shell
import litellm

os.environ["OLLAMA_API_BASE"] = "http://127.0.0.1:11434"

model = "ollama/llama3.1:8b-instruct-q8_0"

messages=[{"role": "user", "content": "say 'hi!'"}]
comp = litellm.completion(model=model, messages=messages)
print(comp)

info = litellm.get_model_info(model)



##### Output ...

ModelResponse(id='chatcmpl-1bb46b8f-64ce-443a-a277-7120e3ef605d', created=1731368001, model='ollama/llama3.1:8b-instruct-q8_0', object='chat.completion', system_fingerprint=None, choices=[Choices(finish_reason='stop', index=0, message=Message(content='Hi!', role='assistant', tool_calls=None, function_call=None))], usage=Usage(completion_tokens=3, prompt_tokens=20, total_tokens=23, completion_tokens_details=None, prompt_tokens_details=None))
Traceback (most recent call last):
  File "/Users/gauthier/Projects/aider/.venv/lib/python3.12/site-packages/litellm/llms/ollama.py", line 191, in get_model_info
    response = litellm.module_level_client.post(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gauthier/Projects/aider/.venv/lib/python3.12/site-packages/litellm/llms/custom_httpx/http_handler.py", line 389, in post
    raise e
  File "/Users/gauthier/Projects/aider/.venv/lib/python3.12/site-packages/litellm/llms/custom_httpx/http_handler.py", line 375, in post
    response.raise_for_status()
  File "/Users/gauthier/Projects/aider/.venv/lib/python3.12/site-packages/httpx/_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '404 Not Found' for url 'http://127.0.0.1:11434/api/show'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gauthier/Projects/aider/./tmp.py", line 59, in <module>
    info = litellm.get_model_info(model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gauthier/Projects/aider/.venv/lib/python3.12/site-packages/litellm/utils.py", line 4659, in get_model_info
    raise e
  File "/Users/gauthier/Projects/aider/.venv/lib/python3.12/site-packages/litellm/utils.py", line 4460, in get_model_info
    return litellm.OllamaConfig().get_model_info(model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gauthier/Projects/aider/.venv/lib/python3.12/site-packages/litellm/llms/ollama.py", line 196, in get_model_info
    raise Exception(
Exception: OllamaError: Error getting model info for ollama/llama3.1:8b-instruct-q8_0. Set Ollama API Base via `OLLAMA_API_BASE` environment variable. Error: Client error '404 Not Found' for url 'http://127.0.0.1:11434/api/show'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404
```

**Comment by ghost** [comment]
> Exception: OllamaError: Error getting model info for ollama/llama3.1:8b-instruct-q8_0. Set Ollama API Base via `OLLAMA_API_BASE` environment variable. Error: Client error '404 Not Found' for url 'http://127.0.0.1:11434/api/show'


The error being raised is that there is no ollama api base for us to query and get the model info from 

we use the `/api/show` endpoint to check if the model supports function calling + max tokens. 

this doesn't seem like a litellm bug - unless i'm missing something

**Comment by paul-gauthier** [comment]
I see that is what the error is claiming. But look at the code and the output. The code successfully does a `.completion()` and immediately afterward explodes on a `.get_model_info()`.

**Comment by sirus20x6** [comment]
my call to /api/show returns a 404 from ollama. I think it's because the model name it's asking for is "ollama/*model_name*" when it should be "*model_name*"

**Comment by ghost** [comment]
fix will be live in tomorrow's release

**Comment by paul-gauthier** [comment]
I am still seeing this with `litellm==1.52.6`?

**Comment by sirus20x6** [comment]
> I am still seeing this with `litellm==1.52.6`?

it looks like he did it in branch litellm_dev_11_14_2024 and from his wording sounds like he intends to merge that branch into main today

**Comment by ghost** [comment]
yup - exactly. 

gemini and anthropic are being unstable, which is slowing the current ci/cd pipeline - i still plan to have this live today.

**Comment by sirus20x6** [comment]
litellm==1.52.8 still doesn't seem to work. haven't used netcat to man in the middle it yet though

**Comment by sirus20x6** [comment]
also seeing it with llama-cpp-python when I use aider

```
aider
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Warning for llama-cpp-python/qwen2.5-coder:32b-instruct-q8_0: Unknown context window size and costs, using sane defaults.
Did you mean one of these?
- llama-cpp-python/qwen2.5-coder:32b-instruct-q8_0
You can skip this check with --no-show-model-warnings

https://aider.chat/docs/llms/warnings.html
Open documentation url for more info? (Y)es/(N)o/(D)on't ask again [Yes]:
```

**Comment by paul-gauthier** [comment]
My small reproduction script works with litellm==1.52.8. Thanks!

**Comment by Ludecan** [comment]
Had this issue running `aider` with qwen2.5-coder 32B via Ollama: `export OLLAMA_API_BASE=http://127.0.0.1:11434 && aider --model ollama/qwen2.5-coder:32b-instruct-q4_K_M`.

Aider hasn't updated yet but if I manually `pip install litellm==1.52.8` the issue goes away!
Thanks for fixing this!

Edit: aider already has 1.52.8 on their [main branch](https://github.com/Aider-AI/aider/blob/0bf17a48f72de15d9af9a50a2b5c73bb7a6501d4/requirements.txt#L99), they haven't made a new release yet.

**Comment by paul-gauthier** [comment]
FYI, aider is updated on the main branch:

```
aider --install-main-branch
```
