### ISSUE TITLE
[Bug]: The latest docker image does not support HTTP/2 (hypercorn)

### ISSUE THREAD

**Issue by james0hargreaves** [BerriAI/litellm#6708]
### What happened?

HTTP/2 support via use of the `hypercorn` module was added in https://github.com/BerriAI/litellm/pull/5950.

However, the latest Docker image errors when the `--run_hypercorn` CLI parameter is provided, indicating that the `hypercorn` module is missing.

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/local/bin/litellm", line 8, in <module>
    sys.exit(run_server())
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_cli.py", line 808, in run_server
    from hypercorn.asyncio import serve
ModuleNotFoundError: No module named 'hypercorn'
```

**Comment by ishaan-jaff** [comment]
this is intentional - we want to keep the core docker image light. If you need to use hypercorn please use a custom docker image @james0hargreaves

**Comment by crondab** [comment]
@ishaan-jaff That’s fine and that’s what I did for the timebeing. But perhaps the docs could be updated to reflect this? It had me confused for a while as the docs currently suggest the main docker image works with this flag.

https://docs.litellm.ai/docs/proxy/deploy#3-using-http2-with-hypercorn

**Comment by james0hargreaves** [comment]
https://docs.litellm.ai/docs/proxy/deploy#3-using-http2-with-hypercorn

**Comment by ishaan-jaff** [comment]
thanks for the feedback, fixed here: https://docs.litellm.ai/docs/proxy/deploy#3-using-http2-with-hypercorn

Curious do you use LiteLLM in production for your company @james0hargreaves ?

**Comment by psjamesh** [comment]
@ishaan-jaff I don't at the moment but I'm looking at it as a potential replacement for a home-made LLM proxy.

**Comment by crondab** [comment]
@ishaan-jaff Not at the moment, but I'm looking at it as a replacement for a home-made LLM proxy.
