### ISSUE TITLE
[Bug]: APIConnectionError for Gemini with prompt caching

### ISSUE THREAD

**Issue by enyst** [BerriAI/litellm#6738]
### What happened?

Over at `openhands`, we use litellm SDK to help us support all the LLM APIs you offer. Prompt caching is very important for users, and it's great that liteLLM has adapted Gemini to have a format closer to others. There's still an incompatibility though:
- we try to have both Anthropic and Gemini available with prompt caching enabled
- we are sending the cache marker in messages for up to 4 checkpoints like Anthropic beta is specified (it doesn't need all 4, but it needs more than 1 afaik)
- but Gemini fails with more than 1.

Is it possible for liteLLM to accept up to 4 cache prompt markers on messages, and fix it with some rule like "for Gemini, only the last one will be actually sent to Google"? Just eliminate the others.

Original report [on openhands repo](https://github.com/All-Hands-AI/OpenHands/issues/4975)

### Relevant log output

```shell
litellm.APIConnectionError: GeminiException - Gemini Context Caching only supports 1 message/block of continuous messages. Your idx, messages were - [(0, {'content': [{'type': 'text', 'text': 'A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed answers to the user\'s questions.\n\n[1] The assistant can use a Python environment with <execute_ipython>...
```

**Comment by enyst** [comment]
Please note also that https://docs.litellm.ai/docs/providers/gemini#context-caching shows an example of Gemini code with 2 messages with `"cache_control": {"type": "ephemeral"}`, but that doesn't work, it results in the above GeminiException.

**Comment by ghost** [comment]
able to repro - it sounds like the ask here is to just use the last message item, if there are multiple cache points.
