### ISSUE TITLE
[Bug]: Incorrect coordinates with `computer tool` in Anthropic computer use

### ISSUE THREAD

**Issue by hongquando** [BerriAI/litellm#6747]
### Description 

When using the Anthropic computer tool, the model fails to correctly identify the location of the Firefox icon, even when provided a valid base64 image

### Process
I tested feature computer user with this request: "Open a new Firefox window, navigate to google.com.", model decide use `computer tool` with action screenshot. So, I took screenshot  and resized to (1280, 800) and image is encoded in base64 and sent as a message. 
```
{
  'tool_call_id': 'toolu_01Tour7YxyXkwhuSP25dQEP7',
  'role': 'tool',
  'name': 'computer',
  'content': [
    {
      'type': 'image',
      'source': {
        'type': 'base64',
        'media_type': 'image/png',
        'data': '..' # base64_image
      }
    }
  ]
}
```

### Expected Behavior: 
The model should correctly identify and use the coordinates for icons or elements in the screenshot.

### Observed Behavior:
Regardless of the image data (base64 or empty string), the coordinates for locating the Firefox icon are incorrect

I think the problem come from `content` is always string.
https://github.com/BerriAI/litellm/blob/8600ec77042dacad324d3879a2bd918fc6a719fa/litellm/types/llms/openai.py#L327

#### Incorrect coordinates with `computer tool` (using litellm):
```
message=Message(content="Now I'll move the cursor to the Firefox icon and click it:", role='assistant'
tool_calls=[ChatCompletionMessageToolCall(index=1, function=Function(arguments='{"action": "mouse_move", "coordinate": [24, 35]}', name='computer')), id='toolu_019S4uBhMSyujH73xDWnfzFn', type='function')]
```
#### Correct coordinates with Same Process (using Anthropic sdk):
```
TextBlock(text="I see the Firefox icon in the middle of the screen. I'll move the cursor there and click it.", type='text'), 
ToolUseBlock(id='toolu_01CJqKqmfoHm3DrWQDDbw1Ct', input={'action': 'mouse_move', 'coordinate': [607, 377]}, name='computer', type='tool_use')
```
## Full input 
```
messages = [{'role': 'user',
  'content': 'Open a new Firefox window, navigate to google.com.'},
 {'content': "I'll help you open Firefox and navigate to Google. First, let me check the desktop with a screenshot to locate the Firefox icon.",
  'role': 'assistant',
  'tool_calls': [{'index': 1,
    'function': {'arguments': '{"action": "screenshot"}', 'name': 'computer'},
    'id': 'toolu_01Tour7YxyXkwhuSP25dQEP7',
    'type': 'function'}],
  'function_call': None},
 {'tool_call_id': 'toolu_01Tour7YxyXkwhuSP25dQEP7',
  'role': 'tool',
  'name': 'computer',
  'content': [{'type': 'image',
    'source': {'type': 'base64',
     'media_type': 'image/png',
     'data': '' }}]}
     ]
tools = [
    {
        "type": "computer_20241022",
        "function": {
            "name": "computer",
            "parameters": {
                "display_width_px": 1280,
                "display_height_px": 800,
            },
        },
    },
    {
        "type": "text_editor_20241022",
        "function": {
            "name": "str_replace_editor",
        },
    },
    {
        "type": "bash_20241022",
        "function": {
            "name": "bash",
        },
    }
]
```

**Comment by ghost** [comment]
can you give the full 'data' param?

**Comment by ghost** [comment]
nvm i see it

**Comment by ishaan-jaff** [comment]
hi @hongquando - curious do you use LiteLLM Proxy in production or are you evaluating it ?

If yes, we'd love to hop on a call to get your feedback on how we can improve. Sharing our calendly for your convenience https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
