### ISSUE TITLE
[Feature]: Support acompletion in Router

### ISSUE THREAD

**Issue by mc-marcocheng** [BerriAI/litellm#676]
### The Feature

I expect `litellm.acompletion` can be substituted by `router.acompletion` directly.

### Motivation, pitch

Currently, `AttributeError: 'Router' object has no attribute 'acompletion'`.

### Twitter / LinkedIn details

You can link my Github account.

**Comment by ghost** [comment]
working on it.

**Comment by ghost** [comment]
Support added here in this commit - https://github.com/BerriAI/litellm/commit/0f08335eddd17c697d0dc57e7e58c5984cd84622 @mc-marcocheng 

should be in prod in v`0.12.5` soon.

**Comment by ghost** [comment]
Will update this ticket once it's in prod.

**Comment by ghost** [comment]
available in v`0.12.5`.
