### ISSUE TITLE
[Bug]: migration fails when .Values.db.useExisting is true

### ISSUE THREAD

**Issue by stevencrake-nscale** [BerriAI/litellm#6791]
### What happened?

When `.Values.db.useExisting` is true, the migration job is unable to connect to the DB, because the .Values.db.url references env vars that the migration job does not have access to. As a result, the env vars are not replaced, and the url looks like `postgresql://$(DATABASE_USERNAME):$(DATABASE_PASSWORD)@$(DATABASE_HOST)/$(DATABASE_NAME)` verbatim.

This is because the [migration template](https://github.com/BerriAI/litellm/blob/main/deploy/charts/litellm-helm/templates/migrations-job.yaml) does not include them, whereas the [deployment template](https://github.com/BerriAI/litellm/blob/b854f6c07b526ce1c1cd827c9a77df24b32081c5/deploy/charts/litellm-helm/templates/deployment.yaml#L60-L77) does.

I propose that we simply add the missing env vars to the migration template.

### Relevant log output

```shell
kubectl logs litellm-migrations-xw76p -n litellm --previous
Attempt 1...
Retrying in 10 seconds...
Attempt 2...
Retrying in 10 seconds...
Attempt 3...
Unable to push database changes after 3 retries.


Shelling into the migration job highlights the missing env vars:

root@litellm-migrations-xw76p:/app# env | sort
DATABASE_URL=postgresql://$(DATABASE_USERNAME):$(DATABASE_PASSWORD)@$(DATABASE_HOST)/$(DATABASE_NAME)
DISABLE_SCHEMA_UPDATE=false
...


After this change applied:

kubectl logs litellm-migrations-nw7gh -n litellm
Attempt 1...
Database push successful!
```

**Comment by justinthelaw** [comment]
Related to #6985, since previous issue was closed, and I'd like to track this PR and fix

**Comment by ishaan-jaff** [comment]
hi @stevencrake-nscale - curious do you use LiteLLM Proxy in production or are you evaluating it ?

If yes, we'd love to hop on a call to get your feedback on how we can improve. Sharing our calendly for your convenience https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
