### ISSUE TITLE
Add support for ollama, hugging face, hf inference endpoint 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#68]
Get to parity with https://github.com/continuedev/continue

**Comment by ishaan-jaff** [comment]
Added support for HF Inference APIs

**Comment by ishaan-jaff** [comment]
investigated using ollama, it's really hard to install / use. It failed twice after trying for 15-20 mins, closing this for now since HF is supported by us 

<img width="1048" alt="Screenshot 2023-08-08 at 4 24 31 PM" src="https://github.com/BerriAI/litellm/assets/29436595/a62b8ed3-eda2-4705-bd25-86e0ffa14f7b">

**Comment by hammer** [comment]
@ishaan-jaff maybe worth revisiting `ollama`, I've found it in September 2023 to be the easiest way to get a local LLM working on macOS.

**Comment by hammer** [comment]
Nevermind, just found https://github.com/BerriAI/litellm/blob/main/cookbook/liteLLM_Ollama.ipynb

**Comment by ishaan-jaff** [comment]
@hammer we support Ollama, looks like you found the notebook 😃

is there something particular you're trying to use LiteLLM for ?

**Comment by ishaan-jaff** [comment]
link to docs for ollama: https://docs.litellm.ai/docs/providers/ollama

**Comment by hammer** [comment]
> is there something particular you're trying to use LiteLLM for ?

Supporting multiple LLMs in https://github.com/refstudio/refstudio

**Comment by ishaan-jaff** [comment]
made a PR to refstudio: https://github.com/refstudio/refstudio/pull/520
