### ISSUE TITLE
[Bug]: Text parsing for VertexAI models

### ISSUE THREAD

**Issue by mc-marcocheng** [BerriAI/litellm#681]
### What happened?

`litellm.completion("chat-bison", messages=[{'role': 'user', 'content': 'hi'}]).choices[0].message.content`
gives the following string:
`"MultiCandidateTextGenerationResponse(text=' Hello. How may I help you? \\n', _prediction_response=Prediction(predictions=[{'candidates': [{'content': ' Hello. How may I help you? \\n', 'author': '1'}], 'citationMetadata': [{'citations': []}], 'safetyAttributes': [{'blocked': False, 'scores': [], 'categories': []}]}], deployed_model_id='', model_version_id='', model_resource_name='', explanations=None), is_blocked=False, safety_attributes={}, candidates=[ Hello. How may I help you? \n])"`

It should be `" Hello. How may I help you? \\n"` for our convenience.

**Comment by ghost** [comment]
woah that's unexpected. Thanks for the catch @mc-marcocheng. I'll fix this asap.

**Comment by ghost** [comment]
that's odd - i don't see this 
<img width="716" alt="Screenshot 2023-10-24 at 8 32 40 AM" src="https://github.com/BerriAI/litellm/assets/17561003/8c09998d-3e0c-4f0a-8d8b-fca44e319774">

**Comment by ghost** [comment]
<img width="812" alt="Screenshot 2023-10-24 at 8 33 37 AM" src="https://github.com/BerriAI/litellm/assets/17561003/9fafd4b3-4ec5-4b00-9ebd-7dd2cd49e7b0">
<img width="670" alt="Screenshot 2023-10-24 at 8 33 44 AM" src="https://github.com/BerriAI/litellm/assets/17561003/da1a5890-c5b2-43ff-918d-99cdd5912550">

**Comment by ghost** [comment]
@mc-marcocheng this is my version of the google-cloud-aiplatform which is what we use to make the call. What is yours? 
```
Name: google-cloud-aiplatform
Version: 1.31.1
Summary: Vertex AI API client library
```

**Comment by ghost** [comment]
Ran on v`1.35.0` and it worked:

Code for repro:
```python
try:
            print("making request", model)
            response = completion(model="chat-bison", messages=[{'role': 'user', 'content': 'hi'}])
            print(response)
            assert type(response.choices[0].message.content) == str
except Exception as e:
            pytest.fail(f"Error occurred: {e}")
```

```
Name: google-cloud-aiplatform
Version: 1.35.0
Summary: Vertex AI API client library
Home-page: https://github.com/googleapis/python-aiplatform
```
<img width="636" alt="Screenshot 2023-10-24 at 8 36 21 AM" src="https://github.com/BerriAI/litellm/assets/17561003/ca248139-aa73-41e2-a5b4-e225fa8dfa6d">

**Comment by rhysviz** [comment]
I am also getting this issue and for me:

```
google-cloud-aiplatform==1.35.0
```

**Comment by ghost** [comment]
@rhysviz what version of litellm are you on? I'm going to try and repro this in a clean environment

**Comment by rhysviz** [comment]
```litellm==0.11.1```

**Comment by ghost** [comment]
Ok - on it now.

**Comment by ghost** [comment]
Hmm, still unable to repro.
<img width="1049" alt="Screenshot 2023-10-24 at 8 44 36 AM" src="https://github.com/BerriAI/litellm/assets/17561003/3e27b101-9c72-475b-8ee0-3ad362f653c3">

**Comment by mc-marcocheng** [comment]
I am using `google-cloud-aiplatform==1.35.0`. Still getting this problem on both `litellm==0.11.1` and `litellm==0.12.3`

**Comment by ghost** [comment]
i'm going to work on a dev release for vertex http calls. Let's see if that helps 

@rhysviz / @mc-marcocheng would either of y'all be available for a live debug in a couple hours?

**Comment by mc-marcocheng** [comment]
![image](https://github.com/BerriAI/litellm/assets/57459045/e2228841-a427-4c52-bd49-2e7f5ed13afa)

> would either of y'all be available for a live debug in a couple hours?

It is getting late for me

**Comment by ghost** [comment]
Ok, I believe this is where the issue being triggered from. We're expecting the package to return a string here, but it's the response object that's being 'stringified'. 

I'll test parsing the response object, and start from there. 
<img width="771" alt="Screenshot 2023-10-24 at 8 48 57 AM" src="https://github.com/BerriAI/litellm/assets/17561003/43dcb7b8-6f4b-488d-81a3-b221d2574997">

**Comment by ghost** [comment]
Hey @rhysviz @mc-marcocheng i have a patch out in v`0.12.4.dev1`. 

Can you test this by upgrading to it with `pip install litellm==0.12.4.dev1`

**Comment by ghost** [comment]
no other code changes required

**Comment by mc-marcocheng** [comment]
Thanks. This fixes the problem

**Comment by rhysviz** [comment]
Also fixes it for me. Thank you for the speedy fix!

**Comment by ghost** [comment]
ok great! I'll run this through our ci/cd and get a proper build going for this.
