### ISSUE TITLE
[Bug]: numpydoc must be either explicit litellm dependency or eliminated

### ISSUE THREAD

**Issue by antonkulaga** [BerriAI/litellm#6810]
### What happened?

I noticed that in some cases litellm uses NumpyDocString but it is not mandatory dependencies in litellm pip package. Please, either drop numpydoc or make it mandatory

### Relevant log output

```shell
File "/home/antonkulaga/sources/just-agents/.micromamba/envs/just-agents/lib/python3.11/site-packages/litellm/utils.py", line 4722, in function_to_dict
    numpydoc = NumpyDocString(docstring)
```

**Comment by ghost** [comment]
it's used in a helper function called `function_to_dict`

this function is not used in the critical path of an llm api call, and is therefore not a mandatory requirement for using litellm.
