### ISSUE TITLE
[Bug]: Cannot disable logging properly

### ISSUE THREAD

**Issue by Seluj78** [BerriAI/litellm#6813]
### What happened?

I want to disable the entire logging from `litellm` or at least set it to `logging.WARNING` for the python SDK.

I've tried everything, and there's no documentation about it.

**Comment by ghost** [comment]
i believe you can just do `litellm._logging.disable_debugging()` 

https://github.com/BerriAI/litellm/blob/ddfe687b13e9f31db2fb2322887804e3d01dd467/litellm/_logging.py#L88

**Comment by MichaelMcAleer** [comment]
Is there a way to do this that isn't via a protected method?

```
litellm._logging._disable_debugging()
```

**Comment by Abhishek21k** [comment]
is there a env that i can set?

**Comment by Tavernari** [comment]
I tried 

```
litellm.log_raw_request_response = False
litellm.suppress_debug_info = True
litellm.turn_off_message_logging=True
litellm.logging = False
```

And nothing :(

**Comment by krrishdholakia** [comment]
Our logging is not enabled by default (we typically just do .debug logs which can be enabled via `litellm._turn_on_debug()`. What logs are you seeing?
