### ISSUE TITLE
[Bug]: Setting `PROXY_BASE_URL` does not work.

### ISSUE THREAD

**Issue by dipakparmar** [BerriAI/litellm#6815]
### What happened?

Setting `PROXY_BASE_URL` does not work.

I see https://github.com/BerriAI/litellm/blob/1890fde3f377b0896e7ca5908953ef948ec1c8a7/ui/litellm-dashboard/src/app/page.tsx#L73-L76 here it's not looking at any env var to populate the state.

**Comment by ghost** [comment]
@dipakparmar it's loaded in from env here - https://github.com/BerriAI/litellm/blob/ddfe687b13e9f31db2fb2322887804e3d01dd467/litellm/proxy/management_endpoints/ui_sso.py#L645

and sent to the client via the `/sso/get/ui_settings` endpoint 

please share a minimal repro of a specific issue you face.

**Comment by dipakparmar** [comment]
@krrishdholakia This is the issue with model hub config, in the screenshot code it still shows localhost:4000

![Image](https://github.com/user-attachments/assets/9b0c0164-e433-4b45-94f4-bb2f22323e1f)
