### ISSUE TITLE
[Bug]: Bedrock stability ultra getting error message

### ISSUE THREAD

**Issue by rasodu** [BerriAI/litellm#6826]
### What happened?

```
[ERROR: litellm.BadRequestError: BedrockException - {"message":"{\"detail\":\"Invalid field in request. Available fields: ['prompt', 'negative_prompt', 'mode', 'strength', 'seed', 'output_format', 'image', 'aspect_ratio']\"}"} Received Model Group=sd_ultra_v1 Available Model Group Fallbacks=None]
```

**Comment by rasodu** [comment]
#6722 : I had required the support for new model here. Getting different error message now. The way I use model is explained in the the previous issue.

**Comment by ghost** [comment]
> [ERROR: litellm.BadRequestError: BedrockException - {"message":"{\"detail\":\"Invalid field in request. Available fields: ['prompt', 'negative_prompt', 'mode', 'strength', 'seed', 'output_format', 'image', 'aspect_ratio']\"}"} Received Model Group=sd_ultra_v1 Available Model Group Fallbacks=None]


This error looks like it came from bedrock. Can you share a minimal script to repro this issue?

**Comment by ghost** [comment]
> max_tokens: 10000
      max_input_tokens: 10000                              # Defined on bedrock page

these values do not look like either openai image params or bedrock image gen params 

remove this
