### ISSUE TITLE
[Feature]: Helm chart repository

### ISSUE THREAD

**Issue by mohittalele** [BerriAI/litellm#6828]
### The Feature

Currently helm chart is hosted on github repo and its not a helm chart repo. 
is there a plan or create a separate helm chart repo for litellm ? 

### Motivation, pitch

if there is helm chart repo, I do not have pull the whole helm chart code.

**Comment by ghost** [comment]
Hey @mohittalele 

> if there is helm chart repo, I do not have pull the whole helm chart code.

what exactly does this mean? 

currently all you need to do is run helm oci right? 

```
helm pull oci://ghcr.io/berriai/litellm-helm
```

https://docs.litellm.ai/docs/proxy/deploy#step-1-pull-the-litellm-helm-chart-1

**Comment by mohittalele** [comment]
Hey @krrishdholakia , 

ahh I missed that info in docs. Now its works. thanks.
