### ISSUE TITLE
[Bug]: `extra_headers` regression on litellm.aembeddings (openai provider)

### ISSUE THREAD

**Issue by hspak** [BerriAI/litellm#6836]
### What happened?

At some point between versions 1.41.2 and 1.52.5, litellm stopped supporting `extra_headers` on `litellm.aembeddings` for the openai provider.

We depend on this for some custom auth.

Example usage:
```
response = await litellm.aembedding(
    model=EMBEDDING_MODEL,
    input=strs,
    dimensions=EMBEDDING_NUM_DIMENSIONS,
    metadata=<custom>,
    extra_headers=<custom-headers>,
) 
```

**Comment by hspak** [comment]
I was able to workaround this by setting `litellm.aclient_session = httpx.AsyncClient(headers=headers)`.

**Comment by hspak** [comment]
Nvm, `litellm.aclient_session` seems to lose the `authorization` header for both completion and embedding calls.

**Comment by ghost** [comment]
what's the error you see? @hspak

**Comment by ghost** [comment]
```
response = embedding(
            model="cohere/embed-english-v3.0",
            input=input,
            extra_headers={"my-test-param": "hello-world"},
        )
```

this works for me @hspak, how can i repro this?

**Comment by hspak** [comment]
Hey! So some extra context:
- We have the litellm proxy running in Cloud Run with the builtin auth enabled.
- (We're still running the litellm client as well, 😬)
- We set the required `authorization` header for the Cloud Run service-to-service auth via `litellm.headers = { 'authorization: Bearer ...' }`
- This works for the `litellm.acompletion` method just fine.
- For `litellm.aembeddings` we were working around by setting `extra_headers = litellm.headers` to ensure that required `authorization` header is set.

With the version bump to 1.52.5, the calls didn't have the necessary `authorization` header anymore.

It's difficult to repro this locally, but I suppose a possible proxy would be to ensure that the `authorization` header that we pass doesn't get overwritten.

**Comment by ghost** [comment]
hey @hspak can you share an example including the model name (will help me know the route)

**Comment by hspak** [comment]
Something like this?
```python
        response = await litellm.aembedding(
            model="text-embedding-3-large",
            input=strs,
            dimensions=2000,
            extra_headers=litellm.headers,
        )
```

**Comment by ghost** [comment]
Found it
