### ISSUE TITLE
[Feature]: Move VertexAI to http call 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#684]
### The Feature

Call vertex ai through the http call instead of the package. https://cloud.google.com/vertex-ai/docs/generative-ai/language-model-overview

### Motivation, pitch

This customer issue is hard to repro due to uncertainty on which underlying version of the cloud ai library is being used - https://github.com/BerriAI/litellm/issues/681

**Comment by ishaan-jaff** [comment]
after gemini it looks like we've doubled down on using the google package, cc @krrishdholakia can we close this issue ?

**Comment by ghost** [comment]
Yea I agree, I don't think we'd be making users lives better by doing this.
