### ISSUE TITLE
Is there any repo for "docs.litellm.ai"?

### ISSUE THREAD

**Issue by GPTLocalhost** [BerriAI/litellm#6849]
sure - feel free to submit a pr for this

_Originally posted by @krrishdholakia in https://github.com/BerriAI/litellm/issues/6841#issuecomment-2490757011_

Thanks for your reply. May I know the repo for the following so that I can create a pr?

https://docs.litellm.ai/docs/project

**Comment by ghost** [comment]
here you go - https://github.com/BerriAI/litellm/tree/main/docs/my-website/docs
