### ISSUE TITLE
[Bug]: Langsmith async integration doesn't register traces

### ISSUE THREAD

**Issue by tomukmatthews** [BerriAI/litellm#6862]
### What happened?

I ran this, following the [docs](https://docs.litellm.ai/docs/observability/langsmith_integration) but it didn't register any trace.

Using langsmith's `@traceable` decorator does pick up the traces, but i currently can't send in metadata dynamically with litellm.

```
import asyncio
import os
import litellm

os.environ["LANGSMITH_API_KEY"] = "..."
os.environ["LANGSMITH_PROJECT"] = "test"  # defaults to litellm-completion
os.environ["LANGSMITH_TRACING_V2"] = "true"
# LLM API Keys
os.environ["OPENAI_API_KEY"] = "..."


# set langsmith as a callback, litellm will send the data to langsmith
litellm.success_callback = ["langsmith"]

async def main():
    # openai call
    response = await litellm.acompletion(
        model="gpt-3.5-turbo",
        messages=[{"role": "user", "content": "Hi 👋 - i'm openai"}],
        metadata={
            "run_name": "litellmRUN",  # langsmith run name
            "project_name": "test",  # langsmith project name
            "run_id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",  # langsmith run id
            "parent_run_id": "f8faf8c1-9778-49a4-9004-628cdb0047e5",  # langsmith run parent run id
            "trace_id": "df570c03-5a03-4cea-8df0-c162d05127ac",  # langsmith run trace id
            "session_id": "1ffd059c-17ea-40a8-8aef-70fd0307db82",  # langsmith run session id
            "tags": ["model1", "prod-2"],  # langsmith run tags
            "metadata": {"key1": "value1"},  # langsmith run metadata
            "dotted_order": "20240429T004912090000Z497f6eca-6276-4993-bfeb-53cbbbba6f08",
        },
    )
    print(response)


if __name__ == "__main__":
    asyncio.run(main())
```

**Comment by ghost** [comment]
this seems to work as expected for me @tomukmatthews 

what metadata is missing?

**Comment by ghost** [comment]
> 16:32:34 - LiteLLM:ERROR: langsmith.py:401 - Langsmith HTTP Error: 400 - {"detail":"dotted_order must contain at least two parts for child runs for run_id:699e8cd6-4286-49e8-8a2a-a029ea923086 trace_id:d2118924-12a7-4620-9b24-2cdc398d80b7 dotted_order:20240429T004912090000Z497f6eca-6276-4993-bfeb-53cbbbba6f08 parent_run_id:063d207c-c5f8-4a40-9b80-a79e4467adc0"}

your dotted order seems malformed @tomukmatthews

**Comment by ghost** [comment]
i see `run_id` isn't supported - instead we were expecting `id`. I'll fix that.

**Comment by tomukmatthews** [comment]
This is so strange, i've updated to the latest langsmith version (`0.1.147`) and the latest litellm version (`1.53.1`). Yet this still doesn't work for me - i find that no traces even appear in langsmith.

Whereas they do when i try langsmiths example with the openai client:
```python
import openai
from langsmith import traceable
from langsmith.wrappers import wrap_openai

# Auto-trace LLM calls in-context
client = wrap_openai(openai.Client())


@traceable  # Auto-trace this function
def pipeline(user_input: str):
    result = client.chat.completions.create(
        messages=[{"role": "user", "content": user_input}], model="gpt-4o-mini"
    )
    return result.choices[0].message.content


pipeline("Hello, world!")
```

**Comment by tomukmatthews** [comment]
@krrishdholakia for me this issue is still unresolved, can you share what litellm and langsmith versions you were running that worked for you?

**Comment by ghost** [comment]
hi @tomukmatthews i'm on the latest version of litellm. 

i don't have langsmith in my env. the litellm integration uses httpx

**Comment by ghost** [comment]
happy to do a call to help debug this - https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by tomukmatthews** [comment]
thanks Krrish! booked some time in

**Comment by MarkRx** [comment]
I am also receiving this error. In my case I don't set dotted_order at all it gets automatically added.

> 12:19:36 - LiteLLM:ERROR: langsmith.py:401 - Langsmith HTTP Error: 400 - {"detail":"dotted_order must contain at least two parts for child runs for run_id:ec05e50e-c1fa-47cc-bdc6-52f4501ef554 trace_id:ec05e50e-c1fa-47cc-bdc6-52f4501ef554 dotted_order:20241209T191931975523Zec05e50e-c1fa-47cc-bdc6-52f4501ef554 parent_run_id:e3587937-c5fa-45d0-80ae-2fd4730a35e9"}

**Comment by ghost** [comment]
dotted order is a required param and automatically added if missing by the integration - https://github.com/BerriAI/litellm/blob/51ead67b4f5e829c5f57a0ec7208b7051c3371a3/litellm/integrations/langsmith.py#L198

can you share your client-side request? @MarkRx

**Comment by MarkRx** [comment]
Do runs with parent_run_id need to do something different for dotted_order? 

python kwargs:

```
{
    'model': 'azure/gpt-4o',
    'deployment_id': 'gpt-4o',
    'messages': [{
            'role': 'system',
            'content': '...'
        }, {
            'role': 'user',
            'content': '...'
        }
    ],
    'temperature': 0.2,
    'timeout': 120,
    'api_base': None,
    'metadata': {
        'run_name': 'describe',
        'tags': ['bitbucket_server', 'describe', 'version:0.2.6'],
        'extra': {
            'metadata': {
                'command': 'describe',
                'pr_url': '<redacted>'
            }
        },
        'parent_run_id': '82889dff-18a0-4f99-b371-a62c402983fe'
    }
}
```

**Comment by MarkRx** [comment]
Looks like [make_dotted_order](https://github.com/BerriAI/litellm/blame/main/litellm/integrations/langsmith.py#L491) needs to account for parent_run_id. Maybe even the whole hierarchy.

[documentation](https://docs.smith.langchain.com/reference/data_formats/run_data_format)

See https://github.com/BerriAI/litellm/issues/7140

**Comment by Eunchan24** [comment]
I also have this problem, is this solved???

**Comment by jonas-lyrebird-health** [comment]
Problem is still existing for me.
