### ISSUE TITLE
[Feature]: gemini-1.5-flash-8b support

### ISSUE THREAD

**Issue by vuongngo** [BerriAI/litellm#6894]
### The Feature

Hi, thanks for the awesome library. Wondering if you are able to support "gemini-1.5-flash-8b" as it's now available on production.

### Motivation, pitch

Looking to switch some agents to use gemini 8b flash for data processing as it is really fast and cheap.

### Twitter / LinkedIn details

https://www.linkedin.com/in/vuong-ngo/?originalSubdomain=au

**Comment by ishaan-jaff** [comment]
already supported https://github.com/BerriAI/litellm/blob/04238cd9a97e802b2637924b8eed46c9012878c6/model_prices_and_context_window.json#L3463
