### ISSUE TITLE
revert azure implementation

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#69]
We recently updated the azure implementation to be: 
if azure -> require the deployment_id to be passed in. 

But in azure, the deployment is = the model. (i deploy a model and give that deployment a name which is the deployment id). So you don't need to pass in both. 

Revert change to old implementation: 
`completion(model="<deployment_id",...)`

**Comment by ghost** [comment]
do before PH launch.

**Comment by ishaan-jaff** [comment]
We need to improve this
