### ISSUE TITLE
[Bug]: litellm.BadRequestError

### ISSUE THREAD

**Issue by yidasanqian** [BerriAI/litellm#6937]
### What happened?

Running the following code results in an error. How can it be fixed?

code:
```
import litellm
from litellm import CustomLLM, completion, get_llm_provider

class Qwen(CustomLLM):
    def completion(self, *args, **kwargs) -> litellm.ModelResponse:         
        print(kwargs)   
        return litellm.completion(
            model=kwargs["model"],
            api_key=kwargs["api_key"],
            api_base=kwargs["api_base"],
            messages=kwargs["messages"]
        )

qwen = Qwen()

litellm.custom_provider_map = [
        {"provider": "dashscope", "custom_handler": qwen}
    ]

resp = completion(
        model="dashscope/qwen-max",
        messages=[{"role": "user", "content": "你是谁"}],
        api_base = "https://dashscope.aliyuncs.com/compatible-mode/v1",
        api_key = "XXX"
    )

print(resp.choices[0].message.content)

```

### Relevant log output

```shell
File "d:\Develop\conda\envs\rag-evaluator\Lib\site-packages\litellm\utils.py", line 1006, in wrapper
    raise e
  File "d:\Develop\conda\envs\rag-evaluator\Lib\site-packages\litellm\utils.py", line 896, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Develop\conda\envs\rag-evaluator\Lib\site-packages\litellm\main.py", line 3009, in completion
    raise exception_type(
  File "d:\Develop\conda\envs\rag-evaluator\Lib\site-packages\litellm\main.py", line 906, in completion
    model, custom_llm_provider, dynamic_api_key, api_base = get_llm_provider(
                                                            ^^^^^^^^^^^^^^^^^
  File "d:\Develop\conda\envs\rag-evaluator\Lib\site-packages\litellm\litellm_core_utils\get_llm_provider_logic.py", line 313, in get_llm_provider
    raise e
  File "d:\Develop\conda\envs\rag-evaluator\Lib\site-packages\litellm\litellm_core_utils\get_llm_provider_logic.py", line 290, in get_llm_provider
    raise litellm.exceptions.BadRequestError(  # type: ignore
litellm.exceptions.BadRequestError: litellm.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=qwen-max
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers
```

**Comment by yidasanqian** [comment]
ref: https://docs.litellm.ai/docs/providers/custom_llm_server#quick-start

**Comment by ghost** [comment]
@yidasanqian this is working as expected. 

Your error is coming from your own return statement. 

> return litellm.completion(
            model=kwargs["model"],

Litellm is saying it doesn't know how to route `qwen-max` 

> LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=qwen-max

This is not a bug - it's working as expected

**Comment by yidasanqian** [comment]
> @yidasanqian this is working as expected.
> 
> Your error is coming from your own return statement.
> 
> > return litellm.completion(
> > model=kwargs["model"],
> 
> Litellm is saying it doesn't know how to route `qwen-max`
> 
> > LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=qwen-max
> 
> This is not a bug - it's working as expected

Why does it throw an error when referring to the official documentation link above? Where is the issue?

**Comment by ghost** [comment]
the model="qwen-max" is not a known model. 

the official example uses `gpt-3.5-turbo` which is a known model - https://models.litellm.ai/

you should write your api logic inside the function.

**Comment by yidasanqian** [comment]
> the model="qwen-max" is not a known model.
> 
> the official example uses `gpt-3.5-turbo` which is a known model - https://models.litellm.ai/
> 
> you should write your api logic inside the function.

My question is how to add my own provider and model?
