### ISSUE TITLE
Not able to extract the text

### ISSUE THREAD

**Issue by Bhavani-Shanker** [BerriAI/litellm#6939]
<html><body>
<span class="stHelp st-emotion-cache-ohzeps ejycmjn6" data-testid="stHelp" width="704"><div class="st-emotion-cache-1396xke ejycmjn5"><span class="st-emotion-cache-11qqkrw ejycmjn10"><span data-testid="stHelpName" class="st-emotion-cache-35ezg3 ejycmjn9">result</span><span data-testid="stHelpType" class="st-emotion-cache-3qgivb ejycmjn8">ZeroxOutput</span><span data-testid="stHelpValue" class="st-emotion-cache-0 ejycmjn7">ZeroxOutput(completion_time=10002.756,
 file_name='temp_upload', input_tokens=0, output_tokens=0, 
pages=[Page(content='', content_length=0, page=1), Page(content='', 
content_length=0, page=2), Page(content='', content_length=0, page=3), 
Page(content='', content_length=0, page=4)])</span></span></div><div data-testid="stHelpDoc" class="st-emotion-cache-aw8jfu ejycmjn4">Dataclass to store the output of the Zerox class.</div>
completion_timefloat | 10002.756
-- | --
file_namestr | 'temp_upload'
input_tokensint | 0
output_tokensint | 0
pageslist | [Page(content='',  content_length=0, page=1), Page(content='', content_length=0, page=2),  Page(content='', content_length=0, page=3), Page(content='',  content_length=0, page=4)]

</span>
</body>
</html>

**Comment by ghost** [comment]
this doesn't look litellm related - please file this ticket on the relevant project repo. 

If this is litellm related, please share a minimal code sample to repro the issue.
