### ISSUE TITLE
[Feature]: Allow Dynamic Editing of model_aliases

### ISSUE THREAD

**Issue by vkochev** [BerriAI/litellm#6956]
### The Feature

Implement a feature that allows users to dynamically edit existing `model_aliases` within LiteLLM. This would enable users to update the target model for a given alias without needing to recreate the entire team or command.

### Motivation, pitch

Currently, LiteLLM allows users to define `model_aliases` during team creation ([Team-based Routing](https://docs.litellm.ai/docs/proxy/team_based_routing)). However, there is no mechanism to modify these aliases after the team is created. This limitation poses a challenge for users who need to switch between different model versions or update the target model for an alias without disrupting existing workflows.

**Comment by ghost** [comment]
I believe we just need to add this to '/team/update'
