### ISSUE TITLE
[Bug]: Fix docker image for multiple deployment Router 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#696]
### What happened?

Our openai-proxy docker image no longer supports multiple model deployments. This is what we're currently directing users too - https://docs.litellm.ai/docs/routing#handle-multiple-azure-deployments-via-openai-proxy-server.

**Comment by ghost** [comment]
Support for routing between multiple deployments added to the openai-proxy endpoint: 
<img width="401" alt="Screenshot 2023-10-25 at 11 20 11 AM" src="https://github.com/BerriAI/litellm/assets/17561003/9ae7960e-a945-4103-b74c-15686dd4be45">

<img width="456" alt="Screenshot 2023-10-25 at 11 20 17 AM" src="https://github.com/BerriAI/litellm/assets/17561003/c1e8e85f-4a89-4fe2-977f-13fa06e91d1d">

also added support for accepting the model list either via a config.yaml - https://github.com/BerriAI/litellm/blob/751e9f07f358b8726dee10aefa2b1df0488dbb7e/openai_proxy/utils.py#L26

or from the model_list param in the request body: https://github.com/BerriAI/litellm/blob/e118ce50e12a6abcafa1cee1d54c60ce7a748159/openai_proxy/main.py#L114

## Remaining Work: 
- need to update dockerfile to accept the config.yaml as a build param (and not raise an error if it's not passed in)

**Comment by ghost** [comment]
cc: @alabrashJr @mc-marcocheng

**Comment by ghost** [comment]
This is live now. 

### How to deploy router 

1. Clone repo
```shell
 git clone https://github.com/BerriAI/litellm
```

2. Create + Modify router_config.yaml (save your azure/openai/etc. deployment info)

```shell
cp ./router_config_template.yaml ./router_config.yaml
```

3. Build + Run docker image 

```shell
docker build -t litellm-proxy . --build-arg CONFIG_FILE=./router_config.yaml 
```

```shell
docker run --name litellm-proxy -e PORT=8000 -p 8000:8000 litellm-proxy
```

## Test

```curl
curl 'http://0.0.0.0:8000/router/completions' \
--header 'Content-Type: application/json' \
--data '{
    "model": "gpt-3.5-turbo",
    "messages": [{"role": "user", "content": "Hey"}]
}'
```

**Comment by ghost** [comment]
docs updated as well.

@alabrashJr  can you let me know if this solves your problem?
