### ISSUE TITLE
[Bug]: Helm chart - DB migration job can only handle passwords in plain text

### ISSUE THREAD

**Issue by vikiscience** [BerriAI/litellm#6966]
### What happened?

Hi All, I noticed that the DB migration job is not handling the DB password in the same way as the main deployment.
Cf.:
https://github.com/BerriAI/litellm/blob/main/deploy/charts/litellm-helm/templates/migrations-job.yaml#L20
and
https://github.com/BerriAI/litellm/blob/main/deploy/charts/litellm-helm/templates/deployment.yaml#L60

So the logic of the DB migration job manifest is the following:
1) If the external DB is used, then only `DATABASE_URL` is used in the manifest, and it is set to `.Values.db.url`. However, the default value for `.Values.db.url` is using other environment variables (see [here](https://github.com/BerriAI/litellm/blob/main/deploy/charts/litellm-helm/values.yaml#L141)), which are not set for the DB migration container. Thus, the only way to make it work is to overwrite the value of `.Values.db.url` with a plain text URL containing the DB password.

2) Else if Postgres DB was deployed using the dependency chart, then DATABASE_URL is set using the values from `.Values.postgresql.auth` block - also including a plain text password. 

So in both cases, passwords are passed in plain text, which is not great. 
It would be better to enable passing them from a secret, analog to the main manifest: see https://github.com/BerriAI/litellm/blob/main/deploy/charts/litellm-helm/templates/deployment.yaml#L66
and
https://github.com/BerriAI/litellm/blob/main/deploy/charts/litellm-helm/templates/deployment.yaml#L51

P.S.: I can contribute a PR if needed...

**Comment by ghost** [comment]
i assume this is fixed with - https://github.com/BerriAI/litellm/pull/6792

**Comment by vikiscience** [comment]
@krrishdholakia Great, thanks for the quick fix! 
From 2 cases mentioned above, the 1st is indeed fixed. For the sake of consistency, the 2nd case could be fixed as well, but as the password is passed to the dependency Postgres chart in plain text anyway, it would require a bigger change - so maybe something for the upcoming features...

**Comment by ishaan-jaff** [comment]
hi @vikiscience  curious do you use LiteLLM Proxy in production or are you evaluating it ?

If yes, we'd love to hop on a call to get your feedback on how we can improve. Sharing our calendly for your convenience https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
