### ISSUE TITLE
[Bug]: LiteLLM >=1.44.8 using Azure OpenAI, breaks with SentrySDK < 2 

### ISSUE THREAD

**Issue by memben** [BerriAI/litellm#6967]
### What happened?

Hey there, 

after upgrading our dependencies, we noted, that LiteLLM stopped working and started responding with `AzureException APIError - argument 'text': 'list' object cannot be converted to 'PyString'`. 

Fast-forward after some debugging I could pinpoint the issue to be occurring only after version v1.44.7.

Investigating the git diff https://github.com/BerriAI/litellm/compare/v1.44.7...v1.44.8

The problematic line changed turned out to be

```
response = azure_client.embeddings.create(**data, timeout=timeout) # type: ignore
``` 
to
```
raw_response = azure_client.embeddings.with_raw_response.create(**data, timeout=timeout) # type: ignore
```

As we could not reproduce this locally and after some more investigations it turns out Sentry is causing this problem (being active/logging only in staging and production and thus apparently not patching the openai sdk locally). 

The original exception (happening in the sentry sdk), was then unfortunately caught by litellm making it seem like a litellm / azure problem.

The solution to solve it to simply upgrade the sentry_sdk (worked for us with litellm > 1.5 and sentry-sdk==2.19.0

### Relevant log output

```shell
error = {
    "type": "litellm.APIError",
    "message": "AzureException APIError - argument 'text': 'list' object cannot be converted to 'PyString'",
    "traceback": """
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/litellm/llms/azure.py", line 1133, in embedding
    raw_response = azure_client.embeddings.with_raw_response.create(**data, timeout=timeout)  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/openai/_legacy_response.py", line 356, in wrapped
    return cast(LegacyAPIResponse[R], func(*args, **kwargs))
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/openai.py", line 294, in new_embeddings_create
    prompt_tokens = count_tokens(kwargs["input"] or "")
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/openai.py", line 30, in count_tokens
    return len(enc.encode_ordinary(s))
  File "/usr/local/lib/python3.10/site-packages/tiktoken/core.py", line 69, in encode_ordinary
    return self._core_bpe.encode_ordinary(text)
TypeError: argument 'text': 'list' object cannot be converted to 'PyString'
    """
}
```

**Comment by ishaan-jaff** [comment]
We pin to `sentry_sdk==2.2.1 # for sentry error handling` so this is not an issue on litellm side

**Comment by ishaan-jaff** [comment]
hi @memben - curious do you use LiteLLM Proxy in production or are you evaluating it ? 

If yes, we'd love to hop on a call to get your feedback on how we can improve. Sharing our calendly for your convenience https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by ArindamRoy23** [comment]
Facing the same issue with litellm>=1.59.9 and latest sentry. Rolling back sentry to the mentioned versions (2.19.0 / Cant go to 2.2.1 for some required sentry funcs)also does not help. Need latest litellm for a few features. Assistance requested.
