### ISSUE TITLE
Together AI JSON Mode Support

### ISSUE THREAD

**Issue by adam-simple** [BerriAI/litellm#6972]
https://github.com/BerriAI/litellm/blob/d2b123eef73a5cda5e6f3663a5c15c2482cf5125/litellm/llms/together_ai/chat.py#L12-L13

We are currently defaulting to get_supported_openai_params from OpenAIGPTConfig in TogetherAIConfig. But Together has a different set of models which support the 'response_format' parameter (https://docs.together.ai/docs/json-mode). A 400 error is returned if your model is not one of the supported models but you still provide response_format.

**Comment by ghost** [comment]
interesting - thanks for this ticket, i'll work on it tomorrow @adam-simple

**Comment by ghost** [comment]
i'm thinking we should add these models to our model map - https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json

that way if new models get added, people don't need to keep bumping litellm versions for them to work
