### ISSUE TITLE
[Feature]: discerning models that support JSON mode vs structured outputs

### ISSUE THREAD

**Issue by jamesbraza** [BerriAI/litellm#6998]
### The Feature

JSON mode is different than structured outputs. See https://stackoverflow.com/a/79046821 for more details.

Currently, `litellm.get_supported_openai_params` returns `response_format` for both `gpt-3.5-turbo` and `gpt-4o-2024-11-20`. However, using `litellm==1.53.2` it seemingly not possible to discern if a model supports structured outputs via the supported parameters.

The request is for `litellm` to support some way of checking if a model uses JSON mode or structured outputs.

---

https://docs.litellm.ai/docs/completion/json_mode#check-model-support should be updated to mention how to discern a model's JSON mode support vs structured output support.

### Motivation, pitch

The way you build a `response_format` depends on knowledge if a model supports JSON mode or structured outputs mode:
- If you know the model supports structured outputs, you can use `response_format=type_to_response_format_param()`
- Otherwise, you need to use `response_format={"type": "json_object"}`

### Are you a ML Ops Team?

No

**Comment by ghost** [comment]
hi @jamesbraza we already have a field for this - `supports_response_schema` 

if you do `get_model_info()` or `supports_response_schema()` it'll tell you if a model supports it

**Comment by ghost** [comment]
i'll update our docs to indicate this
