### ISSUE TITLE
accept batch prompts

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#70]
[Spacy LLM](https://github.com/explosion/spacy-llm/blob/main/spacy_llm/models/rest/anthropic/model.py) has workarounds for the cohere and anthropic api endpoints because they don't accept batch requests. 

<img width="676" alt="Screenshot 2023-08-08 at 9 35 46 AM" src="https://github.com/BerriAI/litellm/assets/17561003/00d66edc-01bb-476d-92d7-7b8760168a2b">
<img width="632" alt="Screenshot 2023-08-08 at 9 35 38 AM" src="https://github.com/BerriAI/litellm/assets/17561003/e68ef747-24b8-40b6-ad41-b8463092d857">

Since they use a for loop approach, they have to wait on each response to complete before sending the next one. Why not do this in an async / threaded manner.

**Comment by ishaan-jaff** [comment]
looks like cohere has a batch_generate: https://cohere-sdk.readthedocs.io/en/latest/cohere.html#client 

we can implement a `batch_completion()`

**Comment by ghost** [comment]
Link to discussion: https://github.com/explosion/spacy-llm/discussions/258#discussioncomment-6677912
<img width="914" alt="Screenshot 2023-08-09 at 5 28 36 AM" src="https://github.com/BerriAI/litellm/assets/17561003/319302d1-fc1f-49be-b131-bc6848ed6a73">

**Comment by ghost** [comment]
they still get user complaints about this though 
- https://github.com/explosion/spacy-llm/discussions/224
- https://github.com/explosion/spacy-llm/discussions/212

**Comment by ghost** [comment]
i believe this is now done via `batch_completion()`
