### ISSUE TITLE
[Bug]: Setting `max_retries` when calling `litellm.embedding` with an Azure model has no effect

### ISSUE THREAD

**Issue by minhduc0711** [BerriAI/litellm#7003]
### What happened?

When I make this call to Azure OpenAI:
```python
embedding_response = await litellm.aembedding(
    input=input,
    model=f"azure/{deployment}",
    api_key=key,
    api_base=endpoint,
    api_version="2024-09-01-preview",
    max_retries=0,
)
```
I expect that the retrying logic implemented in the OpenAI python lib would be disabled, but that doesn't seem to be the case when I tested with a heavily rate-limited deployment. No rate limit errors were raised, and the response time increased after the first call:
```
call 0 took 0.58s
call 1 took 11.28s
call 2 took 11.15s
call 3 took 11.23s
call 4 took 11.27s
call 5 took 11.12s
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.53.2

**Comment by ghost** [comment]
does it work if `num_retries` is used instead? @minhduc0711

**Comment by minhduc0711** [comment]
The issue is still present with `max_retries=0`, due to this particular line:
https://github.com/BerriAI/litellm/commit/5a8b53791934d11a0173c4bb10234ff22afbde10#diff-3b1744593dd8314bae4bdbdb9a89483bd3cd16f149657e557b7f56689f265724R1226
