### ISSUE TITLE
[Bug]: Spend logs are not saved correctly when using stream=true with stream_options: { include_usage: true } 

### ISSUE THREAD

**Issue by bravomark** [BerriAI/litellm#7023]
### What happened?

rel: #6633

After setting specific request parameters, some LLMs（eg: azure/gpt-4o-mini） do not provide a valid request-id for the first token.

----
![image](https://github.com/user-attachments/assets/b85cac6b-cfd5-4307-9378-5a8041bfcb8e)
----

Consequently, because the `id` attribute of the `litellm.ModelResponse` object is an empty string, when attempting to retrieve the request-id using `id = response_obj.get("id", kwargs.get("litellm_call_id"))`, an empty string is still obtained. As a result, when writing to the `LiteLLM_SpendLogs` table, the `request_id` field is written with an empty string. This field's value is unique, which prevents subsequent logs from being written to the database.

----
![image](https://github.com/user-attachments/assets/15e499f0-f02c-49e0-93e3-7cb7b26aab25)
![image](https://github.com/user-attachments/assets/8154995b-de79-4db7-86ed-fa2283e07935)

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.53.4

**Comment by ghost** [comment]
looks like there's 2 issues here

- when first id is an empty str (but exists in subsequent chunks) 
- when id = "" in `get_logging_payload()`
