### ISSUE TITLE
[Bug]Failed to call Azure Openai: Access denied due to invalid subscription key or wrong API endpoint.

### ISSUE THREAD

**Issue by aijcool** [BerriAI/litellm#703]
below is my code, when I run it, it returns the error as following picture, while I tested using autogen it works, is the way I setup parameters not right or because of some other reason. sincerely need your help!

`from litellm import completion
import litellm
litellm.set_verbose=True
import os

use_azure = True
model = "azure/gpt-4-32k"
api_key = "6c8******************1fea0"
azure_api_base = "https://opena*********************penai.azure.com/"
azure_api_version = "2023-07-01-preview"
azure_deployment_name = "gpt-4-3********************tion-2"
azure_api_type = "azure"

os.environ["AZURE_API_KEY"]=api_key
os.environ["AZURE_API_BASE"]= azure_api_base
os.environ["AZURE_API_VERSION"] = azure_api_version

messages = [{ "content": "Hello, how are you?","role": "user"}]
response = completion("azure/gpt-4-32k", messages)
print(response)`
***************************************************

and below is the error screenshot
![image](https://github.com/BerriAI/litellm/assets/19369037/b99b729d-3fc7-4466-8ea4-f9951cefa97f)

**Comment by ghost** [comment]
@aijcool seems like you're azure resource isn't live yet

**Comment by aijcool** [comment]
> @aijcool seems like you're azure resource isn't live yet

thanks for your response @krrishdholakia 

I dont quite understand, how to define live, any other way I can debug?
The resource is from company, works and I tested on autogen, langchain framework already.

**Comment by aijcool** [comment]
this has been solved, I configure 3 AZURE related varibles in windows system and then only set this in python code:
model = "azure/<deployment_name>"

it is very tricky you need to setup model with deployment_name rather than model name
