### ISSUE TITLE
[Feature]: Support bedrock prompt caching 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#7030]
### The Feature

Bedrock now supports prompt caching - https://docs.aws.amazon.com/bedrock/latest/userguide/prompt-caching.html

Support translating b/w the anthropic caching format we support to the bedrock caching format 

### Motivation, pitch

cheaper llm calls 

### Are you a ML Ops Team?

No

**Comment by yigitkonur** [comment]
If you could automatically cache previous messages from previous conversations like in OpenAI, that would be great actually. I think in OpenAI we don't have to create cache entries one by one, it caches automatically, but in Anthropic we have to do this manually. As a chat application, we're having a lot of problems with this - for example, when a user has 100 messages in a conversation, I don't know if we should manually write the 99 messages above to the cache, but I wish litellm would do this automatically.
