### ISSUE TITLE
Diff b/w max_output_tokens and max_tokens?

### ISSUE THREAD

**Issue by SmartManoj** [BerriAI/litellm#7034]
Is `max_tokens = max_input_tokens + max_output_tokens?`

```python
import litellm
print(litellm.get_model_info('openrouter/qwen/qwen-2.5-coder-32b-instruct'))
```

Gives: {'key': 'openrouter/qwen/qwen-2.5-coder-32b-instruct', 'max_tokens': 33792, 'max_input_tokens': 33792, 'max_output_tokens': 33792, ...}

Version: 1.53.5

_Originally posted by @SmartManoj in https://github.com/BerriAI/litellm/issues/4711#issuecomment-2228577570_

**Comment by ghost** [comment]
max_tokens = max_output_tokens. 

It's the old term for it, following the openai param name. 

More details - https://github.com/BerriAI/litellm/blob/12dfd14b5281bed673e284b300d148eea35c9d65/model_prices_and_context_window.json#L3

**Comment by SmartManoj** [comment]
Model: `openrouter/google/gemma-2-27b-it:free`

```BadRequestError: litellm.BadRequestError: OpenrouterException - This endpoint's maximum context length is 8192 tokens. However, you requested about 10556 tokens (2364 of text input, 8192 in the output). Please reduce the length of either one, or use the "middle-out" transform to compress your prompt automatically.```


Is `context_window = max_input_tokens + max_output_tokens`?
