### ISSUE TITLE
ChatLiteLLM with OpenRouter throws unexpected 'proxies' keyword argument error

### ISSUE THREAD

**Issue by HamdiBarkous** [BerriAI/litellm#7050]
### Description
When using `ChatLiteLLM` with OpenRouter, the code that was working a few hours ago is now throwing an unexpected keyword argument error for 'proxies'.

### Error Message
Retrying langchain_community.chat_models.litellm.ChatLiteLLM.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIError: litellm.APIError: APIError: OpenrouterException - __init__() got an unexpected keyword argument 'proxies'.

### Code Sample
```python
import os
from langchain_community.chat_models import ChatLiteLLM
from langchain_core.messages import HumanMessage

os.environ["OPENROUTER_API_KEY"] = "sk-or-v1-xxx"

chat = ChatLiteLLM(
    model="openrouter/openai/gpt-4o-mini",
    verbose=True
)

messages = [
    HumanMessage(
        content="what model are you?"
    )
]
chat.invoke(messages)
```

**Comment by ghost** [comment]
this is an error raised by a specific openai version - https://github.com/openai/openai-python/issues/1903

bump your openai version, that should fix it
