### ISSUE TITLE
[Bug]: 'NoneType' object is not iterable in _get_user_info_for_proxy_admin() 

### ISSUE THREAD

**Issue by bgeneto** [BerriAI/litellm#7060]
### What happened?

Every time I log-in to the LiteLLM Admin Panel ui I've got the following error notification message:

![image](https://github.com/user-attachments/assets/8bc079e9-4d1f-4cc9-a3f7-04fa299c136c)

Looking at the stack trace, the error originates in `litellm/proxy/management_endpoints/internal_user_endpoints.py`. 

Specifically:

1. The `user_info()` function calls `_get_user_info_for_proxy_admin()`.
2. Inside `_get_user_info_for_proxy_admin()`, there's a `for` loop: `for key in _keys_in_db:`.
3. The error occurs because `_keys_in_db` is `None` at the time the loop is executed.  This means that whatever logic is supposed to populate `_keys_in_db` before the loop is not working correctly and is returning `None` instead of an iterable (like a list).

Here is the relevant log output in json format:

```json
{"message": "litellm.proxy.proxy_server.user_info(): Exception occured - 'NoneType' object is not iterable", "level": "ERROR", "timestamp": "2024-12-06T13:45:06.592580", "stacktrace": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/litellm/proxy/management_endpoints/internal_user_endpoints.py\", line 308, in user_info\n    return await _get_user_info_for_proxy_admin()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/litellm/proxy/management_endpoints/internal_user_endpoints.py\", line 431, in _get_user_info_for_proxy_admin\n    for key in _keys_in_db:\nTypeError: 'NoneType' object is not iterable"}
```

### Relevant log output

```shell
{"message": "litellm.proxy.proxy_server.user_info(): Exception occured - 'NoneType' object is not iterable", "level": "ERROR", "timestamp": "2024-12-06T13:45:06.592580", "stacktrace": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/litellm/proxy/management_endpoints/internal_user_endpoints.py\", line 308, in user_info\n    return await _get_user_info_for_proxy_admin()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/litellm/proxy/management_endpoints/internal_user_endpoints.py\", line 431, in _get_user_info_for_proxy_admin\n    for key in _keys_in_db:\nTypeError: 'NoneType' object is not iterable"}
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.53.7

**Comment by ishaan-jaff** [comment]
fixed here: https://github.com/BerriAI/litellm/pull/7042 

it will be live v1.53.8
