### ISSUE TITLE
[Bug]: add groq/llama3.3 models

### ISSUE THREAD

**Issue by qymab** [BerriAI/litellm#7075]
### What happened?

add groq/llama3.3 to [model prices](https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json).

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.53.1

**Comment by ishaan-jaff** [comment]
done here: https://github.com/BerriAI/litellm/pull/7076
