### ISSUE TITLE
[Bug]:  Can't use Amazon Nova models

### ISSUE THREAD

**Issue by farconada** [BerriAI/litellm#7077]
### What happened?

I've this error through CrewAI
litellm.exceptions.BadRequestError: litellm.BadRequestError: BedrockException - {"message":"Invocation of model ID amazon.nova-micro-v1:0 with on-demand throughput isn’t supported. Retry your request with the ID or ARN of an inference profile that contains this model."}

llm="bedrock/amazon.nova-micro-v1:0"

using litellm 1.53.9 
crewai 0.86.0

the access to Nova is enabled in AWS Bedrock and I can use it from the aws playground on-demand

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.53.9

**Comment by ghost** [comment]
This seems like it's coming from bedrock @farconada 

> Invocation of model ID amazon.nova-micro-v1:0 with on-demand throughput isn’t supported. Retry your request with the ID or ARN of an inference profile that contains this model.


I would try and make the same request via boto3 sdk and see if that works

**Comment by farconada** [comment]
closing the issue, I had AWS_DEFAULT_REGION instead of AWS_REGION
Sorry

**Comment by ishaan-jaff** [comment]
hi @farconada - curious do you use LiteLLM Proxy in production or are you evaluating it ? 

If yes, we'd love to hop on a call to get your feedback on how we can improve. Sharing our calendly for your convenience https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
