### ISSUE TITLE
Docstring not matching input parameters

### ISSUE THREAD

**Issue by hyamanieu** [BerriAI/litellm#709]
Hello!

It seems your trim_messages function docstring says something about system_prompt as an argument, while actually it's not an input parameter.

I can see it's actually extracted from the messages.
See here: https://github.com/BerriAI/litellm/blob/895cb5d0f906eb2d3c7078800043df43afabcd13/litellm/utils.py#L4206C9-L4206C23

**Comment by ishaan-jaff** [comment]
fixed: https://github.com/BerriAI/litellm/commit/1aa53f632236185a3c3f532f7950132a7d02968d 

thanks for raising @hyamanieu

**Comment by ghost** [comment]
Thanks for raising this @hyamanieu!
