### ISSUE TITLE
expose a tokenizer function

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#71]
Part of the abstraction class for a model is `get_cost`. To calculate this you need to know both the price per token + have the tokenizer. 

It makes sense to me that lite expose a tokenizer abstraction function that returns the correct tokenizer based on the model. 

Example implementation: https://github.com/refuel-ai/autolabel/blob/06893f8ee348a4d01c5904a8888a2c4c44a4be8a/src/autolabel/models/anthropic.py#L12

<img width="641" alt="Screenshot 2023-08-08 at 10 22 40 AM" src="https://github.com/BerriAI/litellm/assets/17561003/79b732e6-88a5-40c4-9683-bce7ae45d53d">

**Comment by ghost** [comment]
this now exists - https://docs.litellm.ai/docs/token_usage
