### ISSUE TITLE
[Feature]: Add latency tracking to router

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#711]
### The Feature

If i have 2 azure deployments + openai, call the quickest deployment. 

Do this by keeping track of expected latency across a day, and adjusting model order accordingly. 

### Motivation, pitch

user request.

**Comment by ghost** [comment]
To be good for the user, I believe this needs to support time to first token for streaming

**Comment by ghost** [comment]
v1 now pushed - https://github.com/BerriAI/litellm/commit/f2d0d5584a53daa99ea2aefdca5ec65134895f4f
