### ISSUE TITLE
[Feature]:  Adding Code of Conduct file to Repository.

### ISSUE THREAD

**Issue by Kalyanimhala** [BerriAI/litellm#712]
### The Feature

Adding Code of Conduct file to the Repository, for better implementation of contributions.

### Motivation, pitch

[code of condt importance.txt](https://github.com/BerriAI/litellm/files/13196548/code.of.condt.importance.txt)

### Twitter / LinkedIn details

https://www.linkedin.com/in/kalyani-mhala-59647921b

**Comment by Kalyanimhala** [comment]
@krrishdholakia  Kindly assign me this issue, I want to work on it.

**Comment by ghost** [comment]
Hey @Kalyanimhala appreciate the enthusiasm. Refer to this PR https://github.com/BerriAI/litellm/pull/692

We have other issues tagged as 'good first issue', i'd recommend picking those up if you're looking to contribute!

**Comment by Kalyanimhala** [comment]
okay, Thanks!
