### ISSUE TITLE
[Feature]: Improve model fallbacks 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#714]
### The Feature

- If the exception is an instance of: 
 openai.error.ServiceUnavailableError,
                        openai.error.APIConnectionError,
                        openai.error.APIError,
                        openai.error.Timeout,
                        openai.error.TryAgain,

then:  retry 

- if the exception is an instance of openai.error.RateLimitError: 

then use fallback model 

- If the exception is a context window error fallback to a separate model 

Reference: https://github.com/uptrain-ai/uptrain/blob/0c28f1c2e11dc4ab08b90dc597a086da8674328d/uptrain/operators/language/llm.py#L66

### Motivation, pitch

Make our existing utilities, actually good.

**Comment by ghost** [comment]
retry mechanism implemented - 125642563cd442711535339b068d95e12d8d4500

**Comment by ghost** [comment]
context window fallback dict now pushed - 7762ae7762bfc067e1086d2102bbecce6f677649

This enables users to pass in their context window fallback, and litellm will fallback to the mapped model if a model which fails due to context window error is a key in the dictionary
