### ISSUE TITLE
[Feature]: Return original response in response object

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#715]
### The Feature

return the original message response for providers in the response object (this can be a private variable) 

### Motivation, pitch

user request

**Comment by ghost** [comment]
cc: @mc-marcocheng

**Comment by ghost** [comment]
hmm since this already exists in `litellm.set_verbose` + the custom callback function, what else is required here? 

@mc-marcocheng

**Comment by mc-marcocheng** [comment]
Sorry, didn't know about the custom callback function feature. Probably can close this issue as invalid.
