### ISSUE TITLE
[Bug]: Inconsistency with base64 image format

### ISSUE THREAD

**Issue by augustfr** [BerriAI/litellm#7207]
### What happened?

For gpt-4o the following message content works fine: 

```
type:"image_url"
url:"data:image/png;base64,/9j/4AAQ..."
```

When I run this with claude-3.5-sonnet-20240620 I get:

```
litellm.BadRequestError: AnthropicException - {"type":"error","error":{"type":"invalid_request_error","message":"messages.0.content.1.image.source.base64.data: The image specified was not valid"}}
```

In the [Anthropic LiteLLM docs](https://docs.litellm.ai/docs/providers/anthropic) it mentions using type 'image'. But when I switch to that and then try to use gpt-4o, I get:

```
litellm.BadRequestError: BadRequestError: OpenAIException - Invalid value: 'image'. Supported values are: 'text', 'image_url', 'input_audio', 'refusal', and 'audio'.
```

How can I configure this so that I can easily swap between models without having to have custom code that is changing the message thread format on my end?

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

1.41.3

**Comment by ishaan-jaff** [comment]
was this resolved @augustfr  ?
