### ISSUE TITLE
[Bug]: docker-images not available for amd64

### ISSUE THREAD

**Issue by chymian** [BerriAI/litellm#723]
### What happened?

both container images:

ghcr.io/berriai/litellm:latest
https://hub.docker.com/r/litellm/ollama

are only available for arm64

pls. provide amd64 images

**Comment by ghost** [comment]
@chymian reviewing this now - can you give me a way to repro this issue?

**Comment by chymian** [comment]
I followed the docu to get litellm working with ollama:
```bash
docker run --name ollama litellm/ollama
```
Downloaded the image but instead of amd64 it got the arm64.
checking the tags on docker-hub: there is no amd64 image avail.

2nd try to get the proxy up and running with the same result:
```bash
 docker run -e PORT=8000 -e OLLAMA_API_BASE=<your-ollama-api-base> -p 8000:8000 ghcr.io/berriai/litellm:latest
```

**Comment by ghost** [comment]
thanks for sharing @chymian. 

I think, AMD64 implies you're trying to deploy this on a pre-apple silicon Mac? 

is this just a local deploy? if you're using a cloud platform, i can run testing against it and make sure it works.

**Comment by chymian** [comment]
> I think, AMD64 implies you're trying to deploy this on a pre-apple silicon Mac?

MAC? no, not at all.
it's a Linux system: Ubu:20.04, 4 x GPU 3070 (8GB) , i5-7400, (fromer crypto rig)

> is this just a local deploy? if you're using a cloud platform, i can run testing against it and make sure it works.

local

**Comment by ishaan-jaff** [comment]
Hi @chymian I want to make sure we solve this issue for you - i'm the co maintainer of litellm 

Can we hop on a quick call to resolve this issue ? 

sharing my cal for your convenience: https://calendly.com/ishaan-berri/30min?month=2023-11

**Comment by chymian** [comment]
hello @ishaan-jaff ,
trying to get amd64 images resulted in:

```
image with reference ghcr.io/berriai/litellm:latest was found but does not match the specified platform: wanted linux/amd64, actual: linux/arm64/v8
```

and the same here:
```
image with reference docker.io/litellm/ollama:latest was found but does not match the specified platform: wanted linux/amd64, actual: linux/arm64
```

so still no amd64 images available from both repos.

**Comment by ghost** [comment]
Hey @chymian reached out via dm's for next steps on this.

**Comment by ianpurton** [comment]
Looks like you're docker CI is not working.
![image](https://github.com/BerriAI/litellm/assets/36966/9c25617b-1a8c-4cee-ba4b-72b2078098f3)

**Comment by ghost** [comment]
Hey, @ianpurton which docker image is that for?

**Comment by ianpurton** [comment]
@krrishdholakia linux/amd64

**Comment by ishaan-jaff** [comment]
@ianpurton looking into this

**Comment by ishaan-jaff** [comment]
@chymian @ianpurton new dockerfile here:
https://github.com/BerriAI/litellm/blob/main/Dockerfile 

it users `python:3.9-slim` which i believe is compatible with amd64 

Can you verify it works for you ?

**Comment by ishaan-jaff** [comment]
https://hub.docker.com/_/python/tags

**Comment by ishaan-jaff** [comment]
<img width="1280" alt="Screenshot 2023-11-30 at 9 42 39 AM" src="https://github.com/BerriAI/litellm/assets/29436595/b24f06d3-05cc-467c-8350-f9ef838014c7">

**Comment by ianpurton** [comment]
@ishaan-jaff This looks great thanks.

On more ask, could you tag the version of the image you publish on github container registry?

At the moment it's only tagged as latest which makes it difficult for us to know which users are on what version.

Again, many thanks.

**Comment by ghost** [comment]
tracking the new issue here - @ianpurton https://github.com/BerriAI/litellm/issues/972
