### ISSUE TITLE
[Bug]: ContextWindowExceededError is not mapped correctly (via proxy)

### ISSUE THREAD

**Issue by enyst** [BerriAI/litellm#7259]
### What happened?

When using the LiteLLM SDK in `OpenHands` with the LiteLLM proxy for the LLMs, context window exceeded errors get wrapped in a generic BadRequestError, making it harder to handle these errors specifically.

### Current Behavior

When the LLM returns a context window exceeded error, it gets wrapped multiple times, losing the specific error type:

```
litellm.BadRequestError: Litellm_proxyException - Error code: 400 - {'error': {'message': 'litellm.BadRequestError: litellm.ContextWindowExceededError: AnthropicError - {"type":"error","error":{"type":"invalid_request_error","message":"prompt is too long: 200480 tokens > 200000 maximum"}}\nReceived Model Group=anthropic/claude-3-5-sonnet-20241022\nAvailable Model Group Fallbacks=None\nError doing the fallback: litellm.BadRequestError: litellm.ContextWindowExceededError: AnthropicError - {"type":"error","error":{"type":"invalid_request_error","message":"prompt is too long: 200480 tokens > 200000 maximum"}}', 'type': None, 'param': None, 'code': '400'}}
```

### Expected Behavior

The proxy should preserve the original `ContextWindowExceededError` type, allowing clients to handle this specific error case appropriately. For example:

```python
try:
    response = await litellm.acompletion(...)
except litellm.ContextWindowExceededError as e:
    # Handle context window error specifically
    pass
```

### Technical Details

I think this happens because:
1. LiteLLM SDK correctly maps Anthropic's error to `ContextWindowExceededError`
2. But the proxy's error handler wraps everything in `ProxyException` with a `400` status code

### Suggestion

Either return the original types, or add an option to preserve them?
```yaml
general_settings:
  preserve_original_exceptions: true  # Return original LiteLLM exceptions
```

If something like this exists already, sorry I haven't seen it, thank you for pointing it to me!

### Relevant log output

```shell
litellm.BadRequestError: Litellm_proxyException - Error code: 400 - {'error': {'message': 'litellm.BadRequestError: litellm.ContextWindowExceededError: AnthropicError - {"type":"error","error":{"type":"invalid_request_error","message":"prompt is too long: 200480 tokens > 200000 maximum"}}\nReceived Model Group=anthropic/claude-3-5-sonnet-20241022\nAvailable Model Group Fallbacks=None\nError doing the fallback: litellm.BadRequestError: litellm.ContextWindowExceededError: AnthropicError - {"type":"error","error":{"type":"invalid_request_error","message":"prompt is too long: 200480 tokens > 200000 maximum"}}', 'type': None, 'param': None, 'code': '400'}}
```

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

v1.54.1

**Comment by ghost** [comment]
able to repro 

<img width="1139" alt="Screenshot 2024-12-27 at 10 52 06 AM" src="https://github.com/user-attachments/assets/2a4f67e4-5d44-4e7f-ab22-0866d5f0c741" />
