### ISSUE TITLE
[Bug]: unable to pass `input_type` parameter to Voyage AI embedding model

### ISSUE THREAD

**Issue by JamesGuthrie** [BerriAI/litellm#7271]
### What happened?

According to the documentation [here](https://docs.litellm.ai/docs/embedding/supported_embedding#provider-specific-params):
> Any non-openai params, will be treated as provider-specific params, and sent in the request body as kwargs to the provider.

Additionally, the Voyage AI embedding API supports the `input_type` parameter: https://docs.voyageai.com/docs/embeddings#python-api.

I expect that the following should work:

```python
import litellm
litellm.embedding("voyage/voyage-3-lite", ["hello world"], input_type="document")
```

Instead I see the following error:
```
TypeError: Embeddings.create() got an unexpected keyword argument 'input_type'
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.55.3

**Comment by ishaan-jaff** [comment]
fixed here @JamesGuthrie https://github.com/BerriAI/litellm/pull/7276
