### ISSUE TITLE
Langfuse Logging: Avoid including full Prompt in requester_metadata to Reduce Log Size

### ISSUE THREAD

**Issue by kienvu58** [BerriAI/litellm#7274]
# Description
When integrating Langfuse with the litellm proxy server, the current implementation includes the full prompt and its configuration inside the requester_metadata. While this helps link the trace to the prompt version, it significantly increases the log size unnecessarily.

# Context

Here's an example of the current setup when generating a trace:

```python
from langfuse import Langfuse
from openai import OpenAI

client = OpenAI()
langfuse = Langfuse()

prompt = langfuse.get_prompt("test-prompt")

response = client.chat.completions.create(
    model=prompt.config["model"],
    messages=prompt.compile(content="Hello, 1 + 3 = ?"),
    extra_body={
        "metadata": {
            "trace_user_id": "test-user",
            "prompt": prompt.__dict__,  # Full prompt and config included here
        }
    }
)
```

In Langfuse, the trace correctly links to the prompt name and version. However, the requester_metadata field contains the full prompt (prompt.__dict__), which adds unnecessary verbosity to the logs.

# Suggestion

To address this, I propose modifying the `litellm/integrations/langfuse/langfuse.py` file as follows:

Current implementation:

```python
generation_params = {
    "name": generation_name,
    "id": clean_metadata.pop("generation_id", generation_id),
    "start_time": start_time,
    "end_time": end_time,
    "model": kwargs["model"],
    "model_parameters": optional_params,
    "input": input if not mask_input else "redacted-by-litellm",
    "output": output if not mask_output else "redacted-by-litellm",
    "usage": usage,
    "metadata": log_requester_metadata(clean_metadata),
    "level": level,
    "version": clean_metadata.pop("version", None),
}

if supports_prompt:
    generation_params = _add_prompt_to_generation_params(
        generation_params=generation_params, clean_metadata=clean_metadata
    )
```

Proposed update:

```python
generation_params = {
    "name": generation_name,
    "id": clean_metadata.pop("generation_id", generation_id),
    "start_time": start_time,
    "end_time": end_time,
    "model": kwargs["model"],
    "model_parameters": optional_params,
    "input": input if not mask_input else "redacted-by-litellm",
    "output": output if not mask_output else "redacted-by-litellm",
    "usage": usage,
    "level": level,
    "version": clean_metadata.pop("version", None),
}

if supports_prompt:
    generation_params = _add_prompt_to_generation_params(
        generation_params=generation_params, clean_metadata=clean_metadata
    )

generation_params["metadata"] = log_requester_metadata(clean_metadata)
```

The `prompt` key is popped from `clean_metadata` inside `_add_prompt_to_generation_params`. By moving the `generation_params["metadata"]` assignment after this step, the metadata no longer includes the full prompt.

# Rationale

1. Reduced Log Size: The full prompt is already linked via the trace and does not need to be duplicated in the metadata.
2. Cleaner Logs: requester_metadata will only contain relevant details like user ID or any other explicitly passed metadata.

# Expected Behavior

- requester_metadata should no longer include the full prompt configuration but retain relevant metadata.
- The prompt will still be linked via the trace (name, version).

**Comment by kienvu58** [comment]
I found a workaround. Instead of sending `prompt.__dict__`, send a trimmed promt:
```python
trimmed_prompt = {
    "name": prompt.name,
    "version": prompt.version,
    "prompt": "",
}
```
Now, requester_metadata only contains trimmed_prompt and generation is still linked to the prompt.

**Comment by kienvtv3** [comment]
I found a workaround. Instead of sending `prompt.__dict__`, send a trimmed promt:
```python
trimmed_prompt = {
    "name": prompt.name,
    "version": prompt.version,
    "prompt": "",
}
```
Now, requester_metadata only contains trimmed_prompt and generation is still linked to the prompt.
