### ISSUE TITLE
[Bug]: Team Model dont use the model_name specifyed

### ISSUE THREAD

**Issue by superpoussin22** [BerriAI/litellm#7305]
### What happened?

curl  --location 'http://0.0.0.0:4000/model/new' \
--header "Authorization: Bearer sk-xxxxxxxxxxxxxxx" \
--header "Content-Type: application/json" \
--data-raw '{
  "model_name": "vincent",
  "litellm_params": {
    "model": "openai/gpt-4o",
    "custom_llm_provider": "openai",
    "api_key": "klklklklkccb07",
    "api_base": "https://my-endpoint-sweden-berri992.openai.azure.com",
    "api_version": "2023-12-01-preview"
  },
  "model_info": {
    "team_id": "cc5f3e95-faa2-4f1d-baa3-ef6d677cc1c1",
    "id": "vincent"
  }
}'

### Relevant log output

```shell
{"model_id":"vincent","model_name":"model_name_cc5f3e95-faa2-4f1d-baa3-ef6d677cc1c1_2595fa9a-2073-4862-949a-2f6956e57644","litellm_params":{"model":"aDtNrKN+vkpl/zbmXb9OzQVvRN+A60yny1K+Ylc0Ut3KK9lI1s5JYRh5xVdEtui8EQi8oxg=","api_key":"JxrzDzFRAhqHc2r0fORhVP3GZmjJ8HBDm4r4iAMU4hc8SknG6jFGBhm1tb90HTpY/BlZmAP+","api_base":"226w3oD+WZIty+MhZz8Nnf/6jKacj9fVz6f4XFYHGQLuRpwj3AtQbU1EjRqmzRlZ1HMxIxR9yw1YJGMfmHbNSbBOlef+YR5ri9sXU/HJ9yaoaFtSIb8RS9j0YNc=","api_version":"OJ5gxMmi/KXYzF4WG1o+XYiUAM3ZfIGXLv5wOmGDNTa2J5p9dcrBR/5P2ovLHqye/VLJ3xIyiaIF2Q==","custom_llm_provider":"L1L0VF6Tr+mmbmARqZzzeDnoGvu/vSAchpOPimvboWgbQnQj2uZai9vVaTUe1g=="},"model_info":{"id":"vincent","team_id":"cc5f3e95-faa2-4f1d-baa3-ef6d677cc1c1","db_model":false},"created_at":"2024-12-19T07:05:04.166000Z","created_by":"default_user_id","updated_at":"2024-12-19T07:05:04.166000Z","updated_by":"default_user_id"}%
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

V1.55.5/1.55.6

**Comment by ghost** [comment]
hey @superpoussin22 this is **not** a bug. 

The model name stored in db is a uuid. the name submitted is used as an alias to that model to handle uniqueness (e.g. multiple teams using the same model name)
