### ISSUE TITLE
[Bug]: (proxy) Accept single quotes for http request body

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#731]
### What happened?

the JSON generated by requests.post() contains single quotes, and that gives a 500 server error.

**Comment by ghost** [comment]
![image](https://github.com/BerriAI/litellm/assets/17561003/9929ae8f-1fa5-42fa-922b-519c4d05176b)

![image](https://github.com/BerriAI/litellm/assets/17561003/dd564ad7-1347-4c8f-b7eb-2877b20a1ece)

**Comment by ghost** [comment]
Unable to repro this. Reaching out to user who raised issue. 

<img width="1330" alt="Screenshot 2023-11-01 at 3 51 53 PM" src="https://github.com/BerriAI/litellm/assets/17561003/9e92322d-69a1-4757-bdcb-76efd89f84bf">

**Comment by ghost** [comment]
this is fixed.
