### ISSUE TITLE
[Bug]: Internal Users able to generate keys using other user's user_id (Vulnerability)

### ISSUE THREAD

**Issue by mirodrr2** [BerriAI/litellm#7336]
### What happened?

It seems like non admin users are able to generate keys using other user's `user_id`.

The following works:

Request
```
curl -X POST "https://<DeploymentUrl>/user/new" \
-H "Content-Type: application/json" \
-H "Authorization: Bearer <Admin or Master Key>" \
-d '{
     "user_id": "testuser@mycompany.com",
     "user_email": "testuser@mycompany.com",
     "user_role": "internal_user"
}'
```
Response

```
{"key_alias":null,"duration":null,"models":[],"spend":0.0,"max_budget":1000000000.0,"user_id":"testuser@mycompany.com","team_id":null,"max_parallel_requests":null,"metadata":{},"tpm_limit":null,"rpm_limit":null,"budget_duration":"1mo","allowed_cache_controls":[],"soft_budget":null,"config":{},"permissions":{},"model_max_budget":{},"send_invite_email":null,"model_rpm_limit":null,"model_tpm_limit":null,"guardrails":null,"blocked":null,"aliases":{},"key":"<New_User_Key>","key_name":null,"expires":null,"token_id":null,"user_email":"testuser@mycompany.com","user_role":"internal_user","teams":null,"user_alias":null}
```

And now we use that key to try to create a key for a different `user_id`

Request
```
curl -X POST "https://<DeploymentUrl>/key/generate" \
-H "Content-Type: application/json" \
-H "Authorization: Bearer <New_User_Key>" \
-d '{
     "user_id": "testuser2@mycompany.com"
 }'
```

Response
```
{"key_alias":null,"duration":null,"models":[],"spend":0.0,"max_budget":null,"user_id":"testuser2@mycompany.com","team_id":null,"max_parallel_requests":null,"metadata":{},"tpm_limit":null,"rpm_limit":null,"budget_duration":null,"allowed_cache_controls":[],"soft_budget":null,"config":{},"permissions":{},"model_max_budget":{},"send_invite_email":null,"model_rpm_limit":null,"model_tpm_limit":null,"guardrails":null,"blocked":null,"aliases":{},"key":"<Second New Key>","key_name":"sk-...tSXg","expires":null,"token_id":"78ccab11279deabc5c7f8e0dd2d5faeae69a8e78938fce93e044710794976918"}
```

Unless I'm misunderstanding something here, this seems like a major security bug

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.55.0

**Comment by mirodrr2** [comment]
I am now pretty convinced this is a bug, because there _is_ a check to make sure a non-admin user cannot delete another user's api keys, but there is not a similar check to make sure a user cannot create an api key using another user's `user_id`

chatgpt gave a pretty good summary, which I verified is accurate
https://chatgpt.com/share/67660996-edd0-8006-aff6-515de4a3cf51

Relevant code file: https://github.com/BerriAI/litellm/blob/main/litellm/proxy/management_endpoints/key_management_endpoints.py

**Comment by ghost** [comment]
investigating. thank you for this issue @mirodrr2

**Comment by ghost** [comment]
able to repro. working on a fix

**Comment by ghost** [comment]
this seems specific to the `internal_user` role, as internal users are allowed to create keys for themselves

**Comment by ghost** [comment]
Fixed
<img width="1163" alt="Screenshot 2024-12-26 at 7 00 36 PM" src="https://github.com/user-attachments/assets/b91f00e7-a823-4537-9a5a-689cc38ce04a" />

**Comment by ghost** [comment]
Hey @mirodrr2 can we do a quick call sometime this/next week? 

Would love to understand how you use litellm proxy, so we can improve here! 

Calendly - https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
