### ISSUE TITLE
[Feature]: Hi please support system message for gemini 2.0 flash exp thinking

### ISSUE THREAD

**Issue by dat-lequoc** [BerriAI/litellm#7341]
### The Feature

https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json

### Motivation, pitch

https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json

### Are you a ML Ops Team?

No

**Comment by ghost** [comment]
This is already marked as supported - https://github.com/BerriAI/litellm/blob/78fe124c142aeb481702b155c996776c21a57e41/model_prices_and_context_window.json#L3235

let me know if i'm missing something @dat-lequoc

**Comment by dat-lequoc** [comment]
@krrishdholakia hi,
I was referring to the gemini 2.0 flash thinking , which is the reasoning version of flash 2.0 :

gemini-2.0-flash-thinking- exp-1219

![Screenshot_20241225-190856.png](https://github.com/user-attachments/assets/25e129b1-345b-4246-a33c-b33c7d298454)

**Comment by ghost** [comment]
Hi @dat-lequoc i don't think this is on their api yet - https://ai.google.dev/gemini-api/docs/models/gemini#gemini-2.0-flash

let me know if i should check somewhere else

**Comment by fzfz** [comment]
> Hi @dat-lequoc i don't think this is on their api yet - https://ai.google.dev/gemini-api/docs/models/gemini#gemini-2.0-flash-----------谷歌翻译mobile-----------你好@dat-lequoc 我认为这还没有在他们的 API 上 -
> 
> let me know if i should check somewhere else-----------谷歌翻译mobile-----------如果我应该去别处看看请告诉我

https://ai.google.dev/gemini-api/docs/thinking-mode?hl=en

**Comment by dat-lequoc** [comment]
There's an OpenRouter version too. It's free and super good

**Comment by theurs** [comment]
> This is already marked as supported -
> 
> [litellm/model_prices_and_context_window.json](https://github.com/BerriAI/litellm/blob/78fe124c142aeb481702b155c996776c21a57e41/model_prices_and_context_window.json#L3235)
> 
> Line 3235 in [78fe124](/BerriAI/litellm/commit/78fe124c142aeb481702b155c996776c21a57e41)
>  "supports_system_messages": true, 
> 
> let me know if i'm missing something [@dat-lequoc](https://github.com/dat-lequoc)

In the original library, the response is divided into thoughts and a final answer. In litellm, there is no separation. It is impossible to manually separate the different parts after litellm has combined them.

**Comment by ghost** [comment]
ah so it's the response translation we need to do. Got it. 

How would you want us to handle this? @theurs

**Comment by theurs** [comment]
> ah so it's the response translation we need to do. Got it.
> 
> How would you want us to handle this? [@theurs](https://github.com/theurs)

Need to add one more field to the response. Or two, like in the google-genai library.

```python
                response = litellm.completion(
                    api_key=get_key(),
                    model=model_,
                    temperature=int(temperature/2),
                    max_tokens=max_tokens,
                    timeout=timeout,
                    messages=mem,
                    # response_format=response_format,
                    safety_settings = SAFETY_SETTINGS,
                )
                text = response.choices[0].message.content
                think = response.choices[0].message.content_details
                both = response.choices[0].message.content_details+content
```

**Comment by ghost** [comment]
Hey @theurs i believe we can actually handle this now - as we had to expose a new field - `reasoning_content` due to deepseek_r1 

Do you have a consistent way we can get the gemini model to return thinking content?

**Comment by theurs** [comment]
> Hey [@theurs](https://github.com/theurs) i believe we can actually handle this now - as we had to expose a new field - `reasoning_content` due to deepseek_r1
> 
> Do you have a consistent way we can get the gemini model to return thinking content?

https://ai.google.dev/gemini-api/docs/thinking#use-thinking-models
The Flash Thinking model is an experimental model and has the following limitations:

No JSON mode or Search Grounding
**Thoughts are only shown in Google AI Studio**

**Comment by ghost** [comment]
i believe they have a separate api endpoint for this

**Comment by theurs** [comment]
> i believe they have a separate api endpoint for this

I think that thoughts are somewhere inside the history object of the chat, which can be saved and replaced in the code, but I can't find it. It is not visible either with pprint or with a debugger.

```

import google.generativeai as genai
...
model_ = genai.GenerativeModel(
                    model,
                    # tools="code_execution",
                    generation_config = GENERATION_CONFIG,
                    safety_settings=SAFETY_SETTINGS,
                    system_instruction = system,
                )
mem = pickle_load()
...
chat = model_.start_chat(history=mem, enable_automatic_function_calling=True)
...
pickle_save(chat.history)

```
