### ISSUE TITLE
[Bug]: Database UI - TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by vykhand** [BerriAI/litellm#7346]
### What happened?

I created a deployment in OpenShift with no internet access using the [latest non_root ](https://github.com/BerriAI/litellm/pkgs/container/litellm-non_root) image. The database set up seems to be working OK, database objects are there and the views were created by me manually.

When I go to the database UI, create the virtual keys, they are not displayed afterwards. Instead, when I open the virtual keys menu, I see this flashing error :

<img width="902" alt="image" src="https://github.com/user-attachments/assets/620c3e0a-9455-4ffc-bae5-00fc0c96154a" />

The keys that I created are working and I see them stored in database. I tried to create a team as well and teams are not displayed either. 

The error message in the logs is as follows:

```
16:45:35 - LiteLLM Proxy:ERROR: internal_user_endpoints.py:395 - litellm.proxy.proxy_server.user_info(): Exception occured - 'NoneType' object is not iterable
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/litellm/proxy/management_endpoints/internal_user_endpoints.py", line 308, in user_info
return await _get_user_info_for_proxy_admin()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/litellm/proxy/management_endpoints/internal_user_endpoints.py", line 431, in _get_user_info_for_proxy_admin
for key in _keys_in_db:
TypeError: 'NoneType' object is not iterable
```

I tried to dig deeper into the problem and seems to be that the following query seems to be the cause of the problem:

SELECT
            (SELECT json_agg(t.*) FROM "LiteLLM_TeamTable" t) as teams,
            (SELECT json_agg(k.*) FROM "LiteLLM_VerificationToken" k WHERE k.team_id != 'litellm-dashboard') as keys

It returns

<img width="374" alt="image" src="https://github.com/user-attachments/assets/ea5a6c1b-89b4-4755-b8a0-ecc078c77d52" />

Is it a bug or somehow is a problem on my side?

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.55.9

**Comment by ishaan-jaff** [comment]
this is fixed - you're not on the latest version. We handle this @vykhand  

<img width="483" alt="Screenshot 2024-12-21 at 3 08 36 PM" src="https://github.com/user-attachments/assets/9adba8ab-1555-470e-b067-e6d3c3afbe72" />
