### ISSUE TITLE
[Bug]: gpt-4o-audio-preview-2024-12-17 is not available on litellm

### ISSUE THREAD

**Issue by ahmed-mohamed-sn** [BerriAI/litellm#7367]
### What happened?

When I try to use `gpt-4o-audio-preview-2024-12-17`, I get an error that it isn't avaiable.`gpt-4o-mini-audio-preview-2024-12-17` works as expected.

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.55.8

**Comment by ghost** [comment]
what's the error?

**Comment by ghost** [comment]
nvm i see we don't have it mapped yet. Fixing now.
