### ISSUE TITLE
[Bug]: New o1 model not supported by litellm?

### ISSUE THREAD

**Issue by cpath-ukk** [BerriAI/litellm#7375]
### What happened?

A bug happened!

I use litellm from crewai. Everything works well with using model openai/o1-preview, but does not work
with o1 or o1-2024-12-17. 
They seems to be now officially available via API from OpenAI. 

I updated litellm to the last version via pip before trying and I am Tier 5 user supposed to have no restrictions for OpenAI API.

litellm.exceptions.NotFoundError: litellm.NotFoundError: OpenAIException - Error code: 404 - {'error': {'message': 'The model `o1-2024-12-17` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}

### Relevant log output

```shell
litellm.exceptions.NotFoundError: litellm.NotFoundError: OpenAIException - Error code: 404 - {'error': {'message': 'The model `o1-2024-12-17` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v.1.55.9

**Comment by lawliet19189** [comment]
Can you access the new O1 model directly through the OpenAI sdk? If not, you likely don't have access to the newer models.

I can confirm that newer O1 models on litellm works (fyi, it also doesn't require upgrading litellm). Hope this helps!

**Comment by cpath-ukk** [comment]
Thank you. I tried over openAI sdk - it seems that I don't have the access there as well. Obviously the roll out is in several waves for Tier 5 users. I am not there yet. Thank you for helping with this.

**Comment by glenn-jocher** [comment]
Same here. Tier 5 but no access to o1. Do have access to o1-mini though.

**Comment by cpath-ukk** [comment]
> Same here. Tier 5 but no access to o1. Do have access to o1-mini though.

I received response from o1 that they had to roll back o1 for many users due to some technical issues and it will be accessible at some time point later. 

I in the meanwhile just check periodically, if it appears by me in Playground in API dashboard.

You can access at something like https://platform.openai.com/playground/chat?models=o1-mini
And see on the right side in the list of models if it appeared or not
