### ISSUE TITLE
[Bug]: vertex_ai does not support parameters 'presence_penalty', 'frequency_penalty'

### ISSUE THREAD

**Issue by mbukeRepo** [BerriAI/litellm#7378]
### What happened?

I'm building a GenAI client sourcing models from my google cloud vertex_ai, turns out litellm does not support  'presence_penalty', 'frequency_penalty' parameters which I think is an unexpected behavior. 

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

ghcr.io/berriai/litellm:main-stable

**Comment by mbukeRepo** [comment]
@ishaan-jaff

**Comment by ghost** [comment]
@mbukeRepo this is already documented here - https://github.com/BerriAI/litellm/blob/bd4ab1449e78a2d4bc209ef7c781c018add9f8e1/litellm/llms/vertex_ai/gemini/vertex_and_google_ai_studio_gemini.py#L343

how do you see this issue?

**Comment by morliont** [comment]
Still seem to have this error while using Claude 3.7 Sonnet through LiteLLM. I use this in an AI Agent in N8N, but I get this error: 

```
litellm.UnsupportedParamsError: vertex_ai does not support parameters: {'presence_penalty': 0, 'frequency_penalty': 0}, for model=claude-3-7-sonnet@20250219. To drop these, set `litellm.drop_params=True` or for proxy: `litellm_settings: drop_params: true` . Received Model Group=claude-3-7-sonnet Available Model Group Fallbacks=None
```

**Comment by ghost** [comment]
Hey @morliont that makes sense, anthropic does not support those parameters - https://docs.anthropic.com/en/api/messages

**Comment by ghost** [comment]
You can drop them - https://docs.litellm.ai/docs/completion/drop_params

**Comment by morliont** [comment]
Oh, I see. Thank you very much for the guidelines. Much appreciated. 🙏
