### ISSUE TITLE
After running the command python3 run.py --verbose --config examples/example_agent_setup.json, an error occurred.I waited for a long time.

### ISSUE THREAD

**Issue by xingchang1** [BerriAI/litellm#7382]
I updated the openai package from version 1.7.0 to 1.58.1. Since I encountered an error with verbose=True, I ran the command python3 run.py --verbose --config examples/example_agent_setup.json. The result is that the conversation history is printed, but after waiting for a long time, I cannot interact with the AI.

**Comment by ishaan-jaff** [comment]
>  python3 run.py --verbose --config examples/example_agent_setup.json. 

wrong repo
