### ISSUE TITLE
[Bug]: Bedrock cross-region-inference for Llama not working

### ISSUE THREAD

**Issue by shadi-fsai** [BerriAI/litellm#7385]
### What happened?

I am using a cross region inference on bedrock, the llama one isn't working, the claude one is:

my_model = "bedrock/us.meta.llama3-3-70b-instruct-v1:0"
my_model = "bedrock/us.anthropic.claude-3-5-sonnet-20240620-v1:0"

Getting the following:
....\Cache\virtualenvs\weekly-pZ1uoPvO-py3.12\Lib\site-packages\litellm\litellm_core_utils\exception_mapping_utils.py", line 856, in exception_type
    raise NotFoundError(
litellm.exceptions.NotFoundError: litellm.NotFoundError: BedrockException - Bedrock HTTPX: Unknown provider=us, model=us.meta.llama3-3-70b-instruct-v1:0

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

1.55.7

**Comment by ghost** [comment]
able to repro. the region should be getting stripped out, working on a fix
