### ISSUE TITLE
Azure OpenAI call with litellm 

### ISSUE THREAD

**Issue by Amit080696** [BerriAI/litellm#7398]
Error occurred while calling Azure API: litellm.APIError: AzureException APIError - Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}
Azure OpenAI call with litellm completed successfully.

**Comment by ghost** [comment]
> Resource not found'

this seems like your azure credentials are misconfigured. 
Please check the api key, api base and api version (if set)
