### ISSUE TITLE
[Bug]: stopSequences param not mapped correctly for PaLM 2

### ISSUE THREAD

**Issue by toniengelhardt** [BerriAI/litellm#740]
### What happened?

For the PaLM 2 models the `stopSequences` parameter is not mapped correctly. For all other models I can pass `stop` to define stop sequences, but not for PaLM.

IMO the param should be mapped to be consistent, aka. for PaLM completions both `stop` and `stopSequences` should  work as a parameter.

### Relevant log output

```python
generate_text() got an unexpected keyword argument 'stopSequences'
```

**Comment by ghost** [comment]
fix pushed - https://github.com/BerriAI/litellm/commit/f9ff03d5afe77c3f69a814ef37101341e3576034.
