### ISSUE TITLE
WatsonX - api key header overriden by default + chat route deployment url error 

### ISSUE THREAD

**Issue by jezell** [BerriAI/litellm#7408]
### What happened?

WatsonX is broken for two reasons:

1) Passing api_key generates a header with a bearer token, but then the base LLM provider wipes out the token

```python

   if api_key is not None:
            headers.update({"Authorization": "Bearer {}".format(api_key)})

```

This fixes the problem:

```python

   if api_key is not None and "Authorization" not in headers:
            headers.update({"Authorization": "Bearer {}".format(api_key)})

```

2) The chat provider has invalid logic here which always uses deployment URLs (completion provider has correct idea, but seems like a bad cut and paste here):

```python

      if model.startswith("deployment/"):
            # deployment models are passed in as 'deployment/<deployment_id>'
            if optional_params.get("space_id") is None:
                raise WatsonXAIError(
                    status_code=401,
                    message="Error: space_id is required for models called using the 'deployment/' endpoint. Pass in the space_id as a parameter or set it in the WX_SPACE_ID environment variable.",
                )
            deployment_id = "/".join(model.split("/")[1:])
            endpoint = (
                WatsonXAIEndpoint.DEPLOYMENT_CHAT_STREAM.value
                if stream
                else WatsonXAIEndpoint.DEPLOYMENT_CHAT.value
            )
            endpoint = endpoint.format(deployment_id=deployment_id)
        else:
            endpoint = (
                WatsonXAIEndpoint.DEPLOYMENT_CHAT_STREAM.value
                if stream
                else WatsonXAIEndpoint.DEPLOYMENT_CHAT.value
```            

should be:

```python
   url = self._get_base_url(api_base=api_base)
        if model.startswith("deployment/"):
            # deployment models are passed in as 'deployment/<deployment_id>'
            if optional_params.get("space_id") is None:
                raise WatsonXAIError(
                    status_code=401,
                    message="Error: space_id is required for models called using the 'deployment/' endpoint. Pass in the space_id as a parameter or set it in the WX_SPACE_ID environment variable.",
                )
            deployment_id = "/".join(model.split("/")[1:])
            endpoint = (
                WatsonXAIEndpoint.DEPLOYMENT_CHAT_STREAM.value
                if stream
                else WatsonXAIEndpoint.DEPLOYMENT_CHAT.value
            )
            endpoint = endpoint.format(deployment_id=deployment_id)
        else:
            endpoint = (
                WatsonXAIEndpoint.CHAT_STREAM.value
                if stream
                else WatsonXAIEndpoint.CHAT.value
            )
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.55

**Comment by jezell** [comment]
@krrishdholakia maybe related to your recent refactoring?

**Comment by ghost** [comment]
> The chat provider has invalid logic here which always uses deployment URLs (completion provider has correct idea, but seems like a bad cut and paste here):


@jezell i don't follow this. The chat route only uses deployment url if the model starts with `deployment/` 

is there an example you can share of triggering this incorrectly?

**Comment by ghost** [comment]
>    if api_key is not None:
            headers.update({"Authorization": "Bearer {}".format(api_key)})


what code are you looking at, for this? @jezell 

this is our code - https://github.com/BerriAI/litellm/blob/2e86a4806dab1833c4a3b2e25795c7082a8771f2/litellm/llms/watsonx/common_utils.py#L173

**Comment by ghost** [comment]
oh i see it's in the openai_like handler, got it - fixing the custom header issue now.

**Comment by ghost** [comment]
it looks like we need better testing for watsonx. I had tested this locally, since our ci/cd credentials stopped working with watsonx. will include better unit tests as part of the pr

**Comment by ghost** [comment]
able to repro the chat endpoint issue too

**Comment by jezell** [comment]
@krrishdholakia thanks!
