### ISSUE TITLE
Huggingface Space Deployment Issue

### ISSUE THREAD

**Issue by Hivra1** [BerriAI/litellm#7413]
Thank you for creating a wonderful project. Could you kindly share with me the procedure of deploying the litellm project in huggingface space? The Litellm Docs appears to be rather complicated.

**Comment by ghost** [comment]
not sure - litellm also provides an sdk if that's what you're trying to use -https://docs.litellm.ai/docs/#basic-usage


for the proxy, i'm not sure how an hf space would work. A contribution here is welcome!
