### ISSUE TITLE
I wish there was vision support for LLM providers that provide vision support through their official documentation. Case in point- Groq. Reference: https://console.groq.com/docs/vision

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#7433]
I wish there was vision support for LLM providers that provide vision support through their official documentation. Case in point- Groq. Reference: https://console.groq.com/docs/vision

_Originally posted by @githubuser16384 in https://github.com/BerriAI/litellm/issues/361#issuecomment-2562936045_

**Comment by githubuser16384** [comment]
@krrishdholakia  While LiteLLM does provide models with vision support, it seems that running `print(litellm.supports_vision(model="groq/llama-3.2-90b-vision-preview"))` and `print(litellm.supports_vision(model="groq/llama-3.2-11b-vision-preview"))` returns `False`. This might indicate that vision support isn’t currently enabled or recognized for these models through LiteLLM.
