### ISSUE TITLE
[Feature]: LiteLLM only support Google Vertex-AI APIs?

### ISSUE THREAD

**Issue by 345ishaan** [BerriAI/litellm#7444]
### The Feature

I want to try out latest Gemini models and seems like there are two ways to access them. 
1) Google AI API
2) Vertext AI API

I think I created my API key using the 1) and when i run:

```
from litellm import completion
import os

os.environ['GEMINI_API_KEY'] = ""
response = completion(
    model="gemini-1.5-flash", 
    messages=[{"role": "user", "content": "write code for saying hi from LiteLLM"}]
)
```

I get the following error:
```
APIConnectionError: litellm.APIConnectionError: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
```

I am able to use my API key though if i run like this:

```
import google.generativeai as google_genai


google_genai.configure(api_key="")

llm = google_genai.GenerativeModel("gemini-1.5-flash")
response = llm.generate_content(["write code for saying hi from LiteLLM"])
```

### Motivation, pitch

Standardize Litellm for google models.

### Are you a ML Ops Team?

No

### Twitter / LinkedIn details

https://x.com/Ishan345

**Comment by ishaan-jaff** [comment]
Hi ishaan - pass `model="gemini/gemini-1.5-flash"` - re open the issue if that does not work
