### ISSUE TITLE
[Bug]: Calling the embedding method returns empty embeddings

### ISSUE THREAD

**Issue by homanp** [BerriAI/litellm#745]
### What happened?

```
import litellm

embedding = litellm.embedding(
    model="huggingface/sentence-transformers/all-MiniLM-L6-v2", input=["Hello there"]
)
```

### Relevant log output

```shell
{
  "object": "list",
  "data": [
    {
      "object": "embedding",
      "index": 0,
      "embedding": "e"
    }
  ],
  "model": "sentence-transformers/all-MiniLM-L6-v2",
  "usage": {
    "prompt_tokens": 11,
    "total_tokens": 11
  }
}
```
```


### Twitter / LinkedIn details

@pelaseyed

**Comment by ghost** [comment]
looks like we're decoding it incorrectly - i'll fix this. Thanks for flagging @homanp

**Comment by krrishdholakia** [comment]
unable to repro this @homanp 
<img width="806" alt="Screenshot 2023-11-01 at 3 22 28 PM" src="https://github.com/BerriAI/litellm/assets/17561003/6b3df8bb-ab83-4a31-ad22-1ac2b0dccb78">

**Comment by homanp** [comment]
@krrishdholakia 

Where is the embedding? It only says "e". Should be a vector?
<img width="652" alt="Screenshot 2023-11-01 at 23 29 55" src="https://github.com/BerriAI/litellm/assets/2464556/774d4ebb-2681-47af-ac78-dcbdadf1903b">

**Comment by homanp** [comment]
@krrishdholakia I see the issue now. You only support the following models:

https://github.com/huggingface/text-embeddings-inference#supported-models

**Comment by ghost** [comment]
sentence-bert should still work as it's the same parent class. Your passing a dict in input: 
```
inputs: { 
"source_sentence": ...,
...
}
```

Can you point me to the docs you saw that in?

**Comment by homanp** [comment]
> sentence-bert should still work as it's the same parent class. Your passing a dict in input:
> 
> ```
> inputs: { 
> "source_sentence": ...,
> ...
> }
> ```
> 
> Can you point me to the docs you saw that in?


Again, if you are using the huggingface package for inference only certain models are supported.

**Comment by ghost** [comment]
We call the rest api - so that's not an issue for us 

Just pushed a fix - https://github.com/BerriAI/litellm/commit/2c4cb76ce5ec7baa96a22c3bf96017dfc0d20fa2

**Comment by ghost** [comment]
Will update ticket once it's in prod - P.S.: You should probably change the token from the screenshot @homanp

**Comment by homanp** [comment]
> Will update ticket once it's in prod - P.S.: You should probably change the token from the screenshot @homanp 

Thanks!
