### ISSUE TITLE
Fix how replicate models are used/checked

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#75]
Replicate has several models that don't start with `replicate`, see: https://replicate.com/collections/streaming-language-models . We would not be able to support them 

handle replicate models in a similar way hugging face models are handled

make sure to not break the older v that @krrishdholakia is using

**Comment by ishaan-jaff** [comment]
done 

```
model_name = "stability-ai/stablelm-tuned-alpha-7b:c49dae362cbaecd2ceabb5bd34fdb68413c4ff775111fea065d259d577757beb"
response = completion(model=model_name, messages=messages, replicate=True)
```

**Comment by ghost** [comment]
Lol nice hack, we should figure out a better way to identify providers if it's not obvious from the model name - since it's either something we have to deal with or our user integrating lite into their app has to deal with.
