### ISSUE TITLE
[Feature]: increase throughput of proxy server

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#750]
### The Feature

add a `--num_workers` flag and use gunicorn to spin up multiple workers, this should make it faster to process batch requests instead of having all requests queued behind a single worker. 

### Motivation, pitch

https://github.com/stanford-crfm/helm/pull/358/files#diff-f6c6854db5eeb1a1f1f2b39e1145d503f890a55026773c08d178a23cad189f17

**Comment by ghost** [comment]
This is now in prod `v0.13.0`
