### ISSUE TITLE
[Feature]: Working TGI/Ollama Docker image for Runpod 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#752]
### The Feature

Have a working TGI/Ollama w/ litellm proxy image on runpod

### Motivation, pitch

People host the TGI/Ollama models on runpod for full benchmarking. They then need a way to configure the litellm proxy to point to this (locally). 

Could simplify things by just having a way to spin up ollama/tgi with the litellm compatible endpoint on runpod

**Comment by ghost** [comment]
closing as user did not want this
