### ISSUE TITLE
[Feature]: Checking default ~/.aws/credentials locations for Bedrock credentials

### ISSUE THREAD

**Issue by ChrisDryden** [BerriAI/litellm#759]
### The Feature

Typically most AWS users have their credentials stored in a file instead of in the path and then have a set of credentials in that path. If there was functionality to check this when there was nothing in the path that would be more efficient.

### Motivation, pitch

This would allow users to have less friction when adopting this product, will also make automated deployments of LiteLLM easier since that is how credentials are typically stored on hosts.

### Twitter / LinkedIn details

chrisdryden

**Comment by ishaan-jaff** [comment]
hi @ChrisDryden ! thanks for the issue (and for helping us this week) 

we use boto3 for bedrock so this should be supported already: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#aws-config-file

**Comment by ghost** [comment]
Hey @ChrisDryden - to understand this better, are you saying to check if 

the following keys: 
```
os.environ["AWS_ACCESS_KEY_ID"] = ""  # Access key
os.environ["AWS_SECRET_ACCESS_KEY"] = "" # Secret access key
os.environ["AWS_REGION_NAME"] = "" # us-east-1, us-east-2, us-west-1, us-west-2
```

are in the `~/.aws/credentials` if they're not present in the os.environ?

**Comment by ishaan-jaff** [comment]
perhaps an action item here is adding this to bedrock docs and letting users know they can set `AWS_CONFIG_FILE` 

did using  ~/.aws/credentials not work for you ?

**Comment by ghost** [comment]
@ishaan-jaff chris was trying to run this with litellm proxy, in which case litellm needs to be doing this checking

I don't think we run this check today, but i could be wrong.

**Comment by ishaan-jaff** [comment]
I'm confused boto3 docs say

> "Boto3 can also load credentials from ~/.aws/config. You can change this default location by setting the AWS_CONFIG_FILE environment variable." 

https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#aws-config-file

**Comment by ishaan-jaff** [comment]
boto3 itself can read the ~/.aws/config

i'll try this myself and see what happens

**Comment by ChrisDryden** [comment]
This worked! I think the issue earlier was that the AWS region error wasn't surfacing so when I started manually setting the credentials it was looking for those first and wouldn't default to the credentials.
