### ISSUE TITLE
[Bug]: "--drop_params" drops mandatory "top_p" as well for Hugging Face Models

### ISSUE THREAD

**Issue by DebajitKumarPhukan** [BerriAI/litellm#762]
### What happened?

**Problem**
After launching LiteLLM server (as shown below) with "--drop_params" flag, the server drops the mandatory "top_p" param as well. This results in a HuggingFaceException and blank result to the requestor. The reason for adding "--drop_params" was because HuggingFace model don't understand the params "frequency_penalty" and "presence_penalty" leading to another exception.

`litellm --model "huggingface/mistralai/Mistral-7B-Instruct-v0.1" --drop_params`

**Proposed Solution**
`--drop_params` should be configurable and allow the user to pass the params (separated by spaces or comma etc.) which needs to be dropped or a constant value "ALL" to drop all params.

### Relevant log output

```shell
LiteLLM Server Output:

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

HuggingfaceException - Input validation error: `top_p` must be > 0.0 and < 1.0
LiteLLM.Exception: HuggingfaceException - Input validation error: `top_p` must be > 0.0 and < 1.0

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

HuggingfaceException - Input validation error: `top_p` must be > 0.0 and < 1.0
LiteLLM.Exception: HuggingfaceException - Input validation error: `top_p` must be > 0.0 and < 1.0

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

HuggingfaceException - Input validation error: `top_p` must be > 0.0 and < 1.0
LiteLLM.Exception: HuggingfaceException - Input validation error: `top_p` must be > 0.0 and < 1.0

INFO:     49.205.249.7:0 - "POST /v1/chat/completions HTTP/1.1" 200 OK
```

**Comment by ishaan-jaff** [comment]
@DebajitKumarPhukan can you give me steps to repro this

- Can I see the request you're sending to the model ? 
- What tool are you using with the proxy ?

**Comment by ghost** [comment]
Hey @DebajitKumarPhukan `top_p` is **not** being dropped. It seems like the value being passed is outside the acceptable range. 
<img width="879" alt="Screenshot 2023-11-04 at 10 10 50 AM" src="https://github.com/BerriAI/litellm/assets/17561003/8a036f6f-bffc-4555-bee8-d3a6d18af13f">

**Comment by ghost** [comment]
I am closing this issue as this is incorrect. I'm happy to continue the conversation over the 'expected behaviour' potentially in this issue - https://github.com/BerriAI/litellm/issues/725
