### ISSUE TITLE
[Feature]: Return max tokens for huggingface hub models + whisper

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#770]
### The Feature

in `get_max_tokens()` return the max tokens for models that are on hub but not in our model/price list. 

### Motivation, pitch

We can tell max tokens by looking at max_position_embeddings in the config.json. It's hard to figure this out (took me a bit to figure this out), and especially annoying for each model. 

This will make my life better.

**Comment by ghost** [comment]
updating to also include whisper here, following @paulpierre's request

**Comment by ghost** [comment]
Added functionality to retrieve max tokens for huggingface hub models (even if it's not in model cost map) - https://github.com/BerriAI/litellm/commit/f84db3ce14bde551641b5118096882738abc0cfe
