### ISSUE TITLE
[Bug]: litellm.error.RateLimitError not catching openai rate limit errors 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#775]
### What happened?

Steps to repro:

## Using litellm.errors
        response = completion(
            model="gpt-4-1106-preview", 
            messages=messages,
            max_tokens=10,
        )
        print(response)
    except litellm.RateLimitError:
        print("got a rate liimt error")
        pass
 This does not print `got a rate liimt error` and does not catch the exception 

## This code works:
        response = completion(
            model="gpt-4-1106-preview", 
            messages=messages,
            max_tokens=10,
        )
        print(response)
    except openai.error.RateLimitError:
        print("got a rate liimt error")
        pass
 
 This prints `got a rate liimt error` and catches the exception

**Comment by ghost** [comment]
@ishaan-jaff that's because we don't exception map openai. Should we?

**Comment by jchencxh** [comment]
It seems perhaps openai has removed some errors?

**Comment by ishaan-jaff** [comment]
docs are updated for this, you need to catch using openai.RateLimitError: https://docs.litellm.ai/docs/exception_mapping
