### ISSUE TITLE
[Feature]: add helm charts for litellm cli proxy 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#778]
### The Feature

- 

### Motivation, pitch

user request

**Comment by ghost** [comment]
"use flux for git-ops and flux relies on HELM charts"

**Comment by ShaunMaher** [comment]
I have made a start on a helm chart over here: https://github.com/ShaunMaher/litellm/tree/litellm_add_helm_chart

It's not up to a MVP level yet.  Still lots of TODOs.  When it's up to the point where it's usable, I'll open a PR.

**Comment by ShaunMaher** [comment]
PR Created: #1602
