### ISSUE TITLE
[Bug]: Failed to handle non-chat resulting in None return value for inputs

### ISSUE THREAD

**Issue by zhiyuanhe-indeed** [BerriAI/litellm#780]
Note that for non chat llama2 model, the function `prompt_factory` will return None due to the else condition is not handled for line [283](https://github.com/BerriAI/litellm/blob/193cbe632f50156f985b18667506c980533c9af4/litellm/llms/prompt_templates/factory.py#L283). From the comments on line 305, I think you will want to raise an exception in the else branch to be handled by line 304

**Comment by ghost** [comment]
Thanks for raising this @zhiyuanhe-indeed - just pushed the fix - https://github.com/BerriAI/litellm/commit/ce27e08e7df970c9be7dda7bf8e4641fe8e4d4ce

for non-chat models, the prompt template is just the normal string.

Curious, how're you using litellm today?

**Comment by zhiyuanhe-indeed** [comment]
We've just started looking into this to use as an adaptor and also as an abstraction that provides users with a consistent interface without noticing the backend llm model switch.

**Comment by ghost** [comment]
Nice @zhiyuanhe-indeed  - why're you using non-openai models? Want to make sure we're great for your use-case

**Comment by zhiyuanhe-indeed** [comment]
I don't think I know the exact answer. And since this is not a technical question, I am not certain about what I can tell you without an NDA.

**Comment by zhiyuanhe-indeed** [comment]
Hi @krrishdholakia, we still have some issue. In your current fix, the non-chat model will use `hf_chat_template`, however we would really want to use `default_pt`
