### ISSUE TITLE
[Feature]: Specify number of Pool connections in Router

### ISSUE THREAD

**Issue by PrathamSoni** [BerriAI/litellm#785]
### The Feature

Specify number of Pool connections in Router

### Motivation, pitch

Getting some warnings about discarded connections after API calls when using Router. Ideally, would like to reuse these threads by specifying larger connection pool for router

**Comment by ishaan-jaff** [comment]
Thanks for the issue @PrathamSoni - well take a look at this today 

cc @krrishdholakia since your working on the router

**Comment by ghost** [comment]
@PrathamSoni isn't this already possible by passing in a custom client session object? 

https://github.com/BerriAI/litellm/blob/b9e6989e41be01c937ea2c45fd421538e2513c22/litellm/__init__.py#L47

**Comment by ghost** [comment]
```
import requests

# Create a session with a pool of 50 connections
custom_session = requests.Session()
adapter = requests.adapters.HTTPAdapter(pool_connections=50, pool_maxsize=50)
custom_session.mount('http://', adapter)
custom_session.mount('https://', adapter)

# Assign the custom session to your variable
litellm.client_session = custom_session

# Now you can use litellm.client_session to make requests

# Don't forget to close the session when you're done
custom_session.close()
```

**Comment by PrathamSoni** [comment]
i see will experiment and follow up.
