### ISSUE TITLE
[Bug]: Support All Ollama Models

### ISSUE THREAD

**Issue by kylemclaren** [BerriAI/litellm#786]
### What happened?

I would like to use `ollama/yarn-llama2:7b-128k`: https://ollama.ai/library/yarn-llama2

Running the latest version of LiteLLM (as an OpenAI proxy):

```json
POST https://<ENDPOINT>/v1/completions
{
     "model": "ollama/yarn-llama2:7b-128k",
     "prompt": "What is AI?",
     "temperature": 0.7
}
```

But any of the other ["supported" models](https://docs.litellm.ai/docs/providers/ollama#ollama-models) return fine.

### Relevant log output

<details>
<summary>Click for error:</summary>
<br>
"error": "You cannot set content to an empty string. We interpret empty strings as None in requests.You may set {\n  \"content\": null,\n  \"role\": \"assistant\"\n}.content = None to delete the property\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/litellm/main.py\", line 1266, in completion\n    model_response[\"choices\"][0][\"message\"][\"content\"] = response_string\n  File \"/usr/local/lib/python3.10/dist-packages/openai/openai_object.py\", line 71, in __setitem__\n    raise ValueError(\nValueError: You cannot set content to an empty string. We interpret empty strings as None in requests.You may set {\n  \"content\": null,\n  \"role\": \"assistant\"\n}.content = None to delete the property\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/litellm/proxy/proxy_server.py\", line 604, in completion\n    return litellm_completion(\n  File \"/usr/local/lib/python3.10/dist-packages/litellm/proxy/proxy_server.py\", line 538, in litellm_completion\n    response = litellm.text_completion(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/litellm/main.py\", line 1922, in text_completion\n    response = completion(*args, **kwargs) # assume the response is the openai response object\n  File \"/usr/local/lib/python3.10/dist-packages/litellm/utils.py\", line 962, in wrapper\n    raise e\n  File \"/usr/local/lib/python3.10/dist-packages/litellm/utils.py\", line 899, in wrapper\n    result = original_function(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/litellm/timeout.py\", line 53, in wrapper\n    result = future.result(timeout=local_timeout_duration)\n  File \"/usr/lib/python3.10/concurrent/futures/_base.py\", line 458, in result\n    return self.__get_result()\n  File \"/usr/lib/python3.10/concurrent/futures/_base.py\", line 403, in __get_result\n    raise self._exception\n  File \"/usr/local/lib/python3.10/dist-packages/litellm/timeout.py\", line 42, in async_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/litellm/main.py\", line 1403, in completion\n    raise exception_type(\n  File \"/usr/local/lib/python3.10/dist-packages/litellm/utils.py\", line 3574, in exception_type\n    raise e\n  File \"/usr/local/lib/python3.10/dist-packages/litellm/utils.py\", line 3556, in exception_type\n    raise APIError(status_code=500, message=str(original_exception), llm_provider=custom_llm_provider, model=model)\nlitellm.exceptions.APIError: You cannot set content to an empty string. We interpret empty strings as None in requests.You may set {\n  \"content\": null,\n  \"role\": \"assistant\"\n}.content = None to delete the property\n"
</details>

**Comment by ishaan-jaff** [comment]
thanks for the issue @kylemclaren will take a look at this

**Comment by ishaan-jaff** [comment]
<img width="833" alt="Screenshot 2023-11-09 at 8 53 07 AM" src="https://github.com/BerriAI/litellm/assets/29436595/0125a90c-251f-41a3-8e3f-cd0dae0b6435">

@kylemclaren does ollama run on your local machine ? 

I can't get it to run / respond to my requests

**Comment by kylemclaren** [comment]
@ishaan-jaff I'm not running on my local machine (I can try). This is running in a Docker container. Here is my Dockerfile:

```Dockerfile
FROM ollama/ollama:latest

RUN apt-get update && apt-get install -y python3-pip

# Install litellm
RUN pip install litellm

WORKDIR /app

COPY start.sh /app
COPY config.yaml /app
RUN chmod +x /app/start.sh

ENTRYPOINT ["/app/start.sh"]
```

start.sh:
```sh
exec /bin/ollama serve & litellm --config /app/config.yaml --temperature 0.0 --telemetry False --debug
```

config.yaml
```yml
model_list:
  - model_name: yarn-llama2
    litellm_params:
      model: ollama/yarn-llama2:7b-128k
      api_base: http://0.0.0.0:11434
```

**Comment by ishaan-jaff** [comment]
don't you need to do `ollama run yarn-llama2:7b-128k` before running start.sh ?

**Comment by ishaan-jaff** [comment]
@kylemclaren I was able to repro your error, this happens when model has not been pulled,

pushed a commit to litellm to improve the error message seen: https://github.com/BerriAI/litellm/commit/2f0746033319373e6ee85abc1798c5bde167b8c5

**Comment by ishaan-jaff** [comment]
your problem should be fixed if you run `ollama run yarn-llama2:7b-128k` before running ollama serve

**Comment by ishaan-jaff** [comment]
will leave this issue open till you confirm this was the fix @kylemclaren

**Comment by kylemclaren** [comment]
This looks to potentially be an ollama/hardware issue:
```sh
$ ollama run yarn-llama2:7b-128k 
Error: llama runner process has terminated
```
...closing for now. Thanks for the help @ishaan-jaff
