### ISSUE TITLE
[Bug]: Fix caching with async calls on router

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#792]
### What happened?

Results aren't being cached 
<img width="1028" alt="Screenshot 2023-11-10 at 9 51 17 AM" src="https://github.com/BerriAI/litellm/assets/17561003/0b04358a-0a37-4fbe-908b-09d21508639a">

**Comment by ghost** [comment]
cc: @PrathamSoni @nathankim7, I was able to repro the issue and i'm tracking this here.

**Comment by ghost** [comment]
Fix pushed - https://github.com/BerriAI/litellm/commit/a4c9e6bd468be4389a31077ebe1e9ed1bb5a6466 


Just needed to convert cached responses to modelresponse objects.
