### ISSUE TITLE
[Bug]: return function calls on router.completion/acompletion

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#793]
### What happened?

router doesn't return function calls on acompletion and completion 
<img width="804" alt="Screenshot 2023-11-10 at 10 12 24 AM" src="https://github.com/BerriAI/litellm/assets/17561003/59950af5-e3e5-4e18-b88c-91215a5b5fd0">

**Comment by ghost** [comment]
cc: @PrathamSoni @nathankim7 i'm able to repro this issue. Tracking it here.

**Comment by ghost** [comment]
Found the bug - this function was dropping the function from the response object 

<img width="959" alt="Screenshot 2023-11-10 at 10 52 10 AM" src="https://github.com/BerriAI/litellm/assets/17561003/da4f6ab9-1648-431a-af1c-6b2cfcad8a7c">

**Comment by ghost** [comment]
Fixed - https://github.com/BerriAI/litellm/commit/18a8bd5543c1945da4210f33124da619fc5b0bde

**Comment by ishaan-jaff** [comment]
closing since fixed
