### ISSUE TITLE
[Feature]: Add GPT-4 vision cost tracking

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#794]
### The Feature

https://platform.openai.com/docs/guides/vision/calculating-costs 

for gpt-4 vision well need to translate input images to track costs

### Motivation, pitch

-

**Comment by ghost** [comment]
this is now added

**Comment by ghost** [comment]
re-opening as i realize that we need to add this to the token_counter + completion_cost

**Comment by ghost** [comment]
completion_cost uses token_counter

just added image token counting support - https://github.com/BerriAI/litellm/commit/0fffcc15791860c1c0685e29ce87cbbdbf691a8c
