### ISSUE TITLE
[Feature]: dependabot automated migration to last packages

### ISSUE THREAD

**Issue by shuther** [BerriAI/litellm#797]
### The Feature

the proposal is to benefit from the github offer to automatically review the packages
see: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates

### Motivation, pitch

build confidence in the security/version used

**Comment by ishaan-jaff** [comment]
this is added @shuther ! https://github.com/BerriAI/litellm/pull/804
