### ISSUE TITLE
[Bug]: Fix proxy cli --test for new openai v1 sdk 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#803]
### What happened?

proxy cli uses 

```
response = openai.Completion.create(model="gpt-3.5-turbo", prompt='this is a test request, write a short poem')
        print(response)

        response = openai.ChatCompletion.create(model="gpt-3.5-turbo", messages = [
            {
                "role": "user",
                "content": "this is a test request, write a short poem"
            }
        ])
```

when `litellm --test` is called. Switch to new format. 

### Relevant log output

```shell
n/a
```

### Twitter / LinkedIn details

darinkishore

**Comment by ghost** [comment]
cc: @darinkishore

**Comment by ishaan-jaff** [comment]
fix here: https://github.com/BerriAI/litellm/commit/cf0ab7155e8acec02f9371442f0f389c48d8fa16

**Comment by ishaan-jaff** [comment]
needed to also fix some thing for text completion response

**Comment by ishaan-jaff** [comment]
looks like the proxy has some errors with streaming, looking into this

**Comment by ishaan-jaff** [comment]
done - https://github.com/BerriAI/litellm/commit/e125414611347c5291c1c175c0bf370a56fea110 

works with streaming and openai v1.0.0
