### ISSUE TITLE
[Feature] Handling High-traffic - LoadBalancer, Caching, etc. 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#809]
### The Feature

Starting this issue to improve LiteLLM for high-traffic scenarios

## The main goal of this issue: 

If a user is seeing high-traffic, litellm calls should not fail

## Secondary Goal

Improving our existing Router implementation for this scenario - https://docs.litellm.ai/docs/routing#manage-multiple-deployments

Currently the router just does 3 things: 
- Accepts multiple deployments for a model name 
- Load Balancing: picks a random deployment 
- Caching: supports Redis caching

### How can we make it better?

**Comment by ghost** [comment]
Potential Improvements: 
- Health Checks: knowing when an endpoint is overloaded
- Slow endpoint starts: preventing recently overloaded endpoints from being overloaded again

**Comment by ghost** [comment]
cc: @PrathamSoni @karvetskiy @paulpierre

feel free to suggest improvements for the router. 

I believe 2 i have so far are: 
- have router caching working with [instructor](https://github.com/jxnl/instructor)
-  fix async streaming for function calling

**Comment by krrishdholakia** [comment]
@PrathamSoni litellm now exposes a `LiteLLM()` class - similar to OpenAI's for use with Instructor 

https://github.com/BerriAI/litellm/blob/9d8f872f380e527261abcb5ba53fba6e7e545920/litellm/tests/test_class.py#L18

**Comment by ghost** [comment]
@PrathamSoni fixed router caching + enabled wrapping [instructor](https://github.com/jxnl/instructor) with Router

```python
import sys, os
import traceback
import litellm
litellm.set_verbose = True
from litellm import Router
import instructor
from pydantic import BaseModel

# This enables response_model keyword
# from client.chat.completions.create
client = instructor.patch(Router(model_list=[{
    "model_name": "gpt-3.5-turbo", # openai model name 
    "litellm_params": { # params for litellm completion/embedding call 
        "model": "azure/chatgpt-v-2", 
        "api_key": os.getenv("AZURE_API_KEY"),
        "api_version": os.getenv("AZURE_API_VERSION"),
        "api_base": os.getenv("AZURE_API_BASE")
    }
}]))

class UserDetail(BaseModel):
    name: str
    age: int

user = client.chat.completions.create(
    model="gpt-3.5-turbo",
    response_model=UserDetail,
    messages=[
        {"role": "user", "content": "Extract Jason is 25 years old"},
    ]
)

assert isinstance(user, UserDetail)
assert user.name == "Jason"
assert user.age == 25

print(f"user: {user}")
```

**Comment by ghost** [comment]
> need to hash the cache key to handle Redis 'key too long' errors: File "/Users/psoni/miniconda3/envs/endex-dev/lib/python3.11/site-packages/redis/connection.py", line 524, in read_response
raise response
redis.exceptions.ResponseError: key too long

Tracking issue: https://github.com/BerriAI/litellm/issues/810

**Comment by ghost** [comment]
Enabling users to control how long to wait before retrying requests due to server overloaded errors (e.g. RateLimitError):

Tracking issue https://github.com/BerriAI/litellm/issues/812

**Comment by ghost** [comment]
closing as the relevant issues have been fixed
