### ISSUE TITLE
[Feature]: expose time.sleep control for retrying requests

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#812]
### The Feature

expose a control for controlling how long to wait before retrying requests when it fails due to server overload 

### Motivation, pitch

if the server is overloaded retry requests after waiting for a period of time

**Comment by PrathamSoni** [comment]
callout to enable async sleep for async timeouts

**Comment by ghost** [comment]
This is now pushed - https://github.com/BerriAI/litellm/commit/4882325c354dde63f67f33535d4356f75d6fbbea

We enable a `retry_after` param on the router. This is set as the min timeout to wait before retrying a failed request. By default this is 0.

**Comment by ghost** [comment]
@PrathamSoni is this what you were looking for ?
