### ISSUE TITLE
[Bug]: First run with --config fails because it doesn't import yaml in the except case

### ISSUE THREAD

**Issue by kfsone** [BerriAI/litellm#819]
### What happened?

Trying to build a container, using a cloned repos of litellm. The cause is that litellm/proxy/proxy_server.py has a try-import-catch block but not all the imports were duplicated in the except block, specifically 'yaml', and something higher in the import list is not in the requirements.txt, so on the first run, it has to pip install it.

Fix to follow.

### Twitter / LinkedIn details

@kfsone / https://www.linkedin.com/in/osmith/

**Comment by ghost** [comment]
@kfsone closing the issue as the PR is merged (will update the ticket with the release version). 

How're you using litellm in the docker container?

**Comment by kfsone** [comment]
```
cd /workspace
ollama serve &
sleep 2
ollama pull llama2

cd /app  # where litellm is extracted
. /app/venv/bin/activate
pip install -r requirements.txt fastapi tomli tomli_w backoff pyyaml  # <- haven't absorbed the fix yet
litellm --config /workspace/ollama.yaml --api_base http://localhost:11434/ --port 11111 &
sleep 2
deactivate
```

ollama.yaml:

```
model_list:
  - model_name: llama2  # vicuna
    litellm_params:
      model: ollama/llama2  # vicuna:7b-16k
      api_base: http://localhost:11434
```

the plan is to use memgpt either inside the container via a jupyter notebook also inside the container, or from outside (I'm exposing the 11111 and jupyter ports). except, memgpt is having its own unrelated issues :)

and litellm --test works. Or it did, yesterday. Hmm.

**Comment by kfsone** [comment]
I'd posted more detail on the pr:

> @krrishdholakia Actually, for reasons, a single container with both, using my fork of litellm to try adding a few more of the ollama models (mmm that vicuna 16k, and mistral).

> https://gist.github.com/kfsone/988ebccdefd2caa4a0adc58533392605

> (the args at the top of the dockerfile: I run apt-cacher-ng and a devpi instance on my nas so I never have to pull a package off the wire twice :)

Today it's fighting me getting --test to run,


```
litellm --test --port ${LITELLM_PORT}
```
fails, it goes off to the openai port https://gist.github.com/kfsone/380c0ac738a059f213bfeea1b45dabe4

I have OPENAI_API_BASE set to http://localhost:11434, I've tried passing --config to a .yaml file with an api_base pointing there, and I've tried providing --api_base http://localhost:11434.

**Comment by ishaan-jaff** [comment]
@kfsone can you run it with `--debug` and send the log

**Comment by kfsone** [comment]
@ishaan-jaff never mind, tracked this last thing down to my having `pip install -r requirements.txt` but not `pip install .`

https://github.com/kfsone/ollama-litellm-docker or the docker image kfsone/ollama-litellm

**Comment by kfsone** [comment]
I must have not configured that right, because both the proxy and memgpt throw various exceptions when I try a simple memgpt run on it.
