### ISSUE TITLE
adding new model - claude-instant-1.2

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#82]
it's weird i need to make changes to our model list (fixed strings) to add a new model, when no other change is really required. Can this not just work out of the box in some way?

**Comment by ishaan-jaff** [comment]
I agree with this sentiment - I was missing a llm for AI21 And now I need to add it to init.py

**Comment by ishaan-jaff** [comment]
@krrishdholakia any suggestions on how to improve this process ?
