### ISSUE TITLE
[Bug]: Temperature parameter for non openai models don't work if the temperature is 0

### ISSUE THREAD

**Issue by whathelll** [BerriAI/litellm#822]
### What happened?

This get_optional_params method 
https://github.com/BerriAI/litellm/blob/f5abde775b034b777607384825a15d53b0b48eed/litellm/utils.py#L1679C18-L1679C18
evaluates temperature with 
```
        if temperature:
            optional_params["temperature"] = temperature
```
all over the place

when temperature is 0, it evaluates to False so temperature value is not passed down to the model/api .

**Comment by ghost** [comment]
hey @whathelll thanks for the catch. I'll fix this today.

**Comment by ghost** [comment]
@whathelll just pushed a fix - https://github.com/BerriAI/litellm/commit/60d2dff74ae197d70f707028f2867b6401fd40d7

we now explicitly check if the value is None 

Should be out later today, will update ticket with release details.

**Comment by ghost** [comment]
@whathelll would love to understand how you're using litellm. 

Attaching my calendly if that helps: 
https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
