### ISSUE TITLE
[Bug]: System prompt setting?

### ISSUE THREAD

**Issue by ftmtk** [BerriAI/litellm#827]
### What happened?

I host my llama2 model with tgi and want to use litellm.

I notice that one can set custom prompt template in `.env.template`

however as I cannot find where in the code that variables like `MODEL_SYSTEM_MESSAGE_START_TOKEN` is used. 

It seems that it's used in `proxy_server.load_config` but it has been deprecated. So I guess these environment variables aren't used in litellm?

Can someone explain how I can set my custom template?

**Comment by ghost** [comment]
@ftmtk we've moved to using config.yaml instead (more flexible). You can set the prompt template like this - https://docs.litellm.ai/docs/simple_proxy#set-custom-prompt-templates

For huggingface models, we automatically check if the chat template is available on huggingface_hub and apply it - https://docs.litellm.ai/docs/completion/prompt_formatting

Let me know if this solves your issue.
