### ISSUE TITLE
[Feature]: Add HF Transformers 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#831]
### The Feature

> One thing that came up now: I have some old code using the OpenAI API, and I would like to use a huggingface model instead. 
> 
> I mean use the transformers library to run the hf model locally but keeping the same API as OpenAI.
> 
> Here is a quick hack doing something like what what I want:
> https://github.com/metareflection/certified-reasoning/commit/4919ee9fa799b9adde998fdc594a04af411d5744
> 
> I didn't want to change the code using the API so I stubbed the API very partially. It would be great if litellm allowed to call a local LLM based on huggingface as if it were using the usual completion API.

### Motivation, pitch

user request /

**Comment by ishaan-jaff** [comment]
+1 heard this from another user

**Comment by ghost** [comment]
Calling HF Transformers locally involves working dealing with batch inference, etc. You can see how much work ollama, llama cpp python, etc. have to do to just do that 1 thing well. 

This seems like a distraction from the focus of the library which is to handle the translation between different api formats.

**Comment by ishaan-jaff** [comment]
it's for a benchmarking use case - the user does not need  it to be robust - this was their code snippet
seems quite straightforward to me unless i'm missing something 
see users code snippet below 
 
<img width="393" alt="Screenshot 2023-11-16 at 8 18 32 AM" src="https://github.com/BerriAI/litellm/assets/29436595/6afb0eff-ce04-4fdf-8252-c62d389334db">

**Comment by ghost** [comment]
> the user does not need it to be robust 

feels weird for a library to commit to tell users we're providing them with jank integrations 😄

**Comment by ghost** [comment]
If the user already has an implementation, and it works - maybe we can provide them with an adapter to call their local implementation through the litellm proxy? 

so they're responsible for their integration, and can modify it if necessary

curious though, if they have something and it works - why do they need us here?

**Comment by ishaan-jaff** [comment]
asked the user to respond on this thread

**Comment by namin** [comment]
Thanks for looking into this.

The main value I imagined would be to provide all the use cases of how the API can be called. For example, how would I set the logit_bias when going from the OpenAI API to the HuggingFace model?

I was hoping that by using LiteLLM I could be shielded by such details.

Providing an adapter that I could implement would be great if I could just give the HuggingFace model, but not so great if I have to translate the generate function.

Does it make sense?

Thanks, again.

**Comment by ghost** [comment]
@namin any reason why you can't use something like TGI / VLLM here? 

https://vllm.readthedocs.io/en/latest/getting_started/quickstart.html; https://vllm.readthedocs.io/en/latest/getting_started/quickstart.html#openai-compatible-server

**Comment by namin** [comment]
VLLM seems interesting, thanks. I definitely want a drop-in replacement for OpenAI. I'd also probably want to customize the model, but that's not strictly necessary especially at first, so I might give it a shot.

Anyways, I understand if this is out of scope for LiteLLM!

**Comment by ishaan-jaff** [comment]
hi @namin 
- why is it important to be a drop in replacement for OpenAI for you ?

**Comment by namin** [comment]
It's important to be a drop-in replacement so that I can use code that calls OpenAI and make it call a local LLM instead.

**Comment by ishaan-jaff** [comment]
@namin but what are you hoping to do by easily swapping between OpenAI and a Local LLM 

(I would love to be helpful here)

**Comment by namin** [comment]
In general, I think it's really useful to be able to take a working system that calls to OpenAI and easily change it to call an open model. I'd rather use an open model because it's free for me (I have access to a multi-GPU machine). So in this particular case, I wanted to take these benchmarks written for OpenAI and run them with an open model to understand what the system is doing. I really believe it will be a generally useful capability for anyone who has access to a multi-GPU machine.

Maybe VLLM will do for this use case, but I would like to have more control over the model that is called (say using a PEFT layer, etc.).

**Comment by ishaan-jaff** [comment]
@namin what is the ideal solution for you here?  I want to make litellm great for your use case 

**Sounds like there are 3 approaches:**
- Use Hugging Face TGI deployed on a GPU + litellm ✅(supported already)
- Use Hugging Face Transformers + we make an integration on litellm to call HF transformers 
- vLLM + litellm ✅(supported already) (seems like this is not an ideal level of control for you)

**Comment by namin** [comment]
Thanks. (2) is the most convenient for my use case (I don't want to start a server, and I do want to support a custom model).

**Comment by ishaan-jaff** [comment]
hi @namin will be working on this today ! will get back to you with an update

**Comment by ghost** [comment]
hey @namin quick q, what is 'the system' in this case? 
> I wanted to take these benchmarks written for OpenAI and run them with an open model to understand what the system is doing.

**Comment by namin** [comment]
This is the system that triggered this need:
https://github.com/metareflection/certified-reasoning
And I have an attempt here:
https://github.com/metareflection/certified-reasoning/tree/open
But I am not taking into account all the parameters that I should.
In particular, there is this logit_bias parameter that comes from the OpenAI API, that I am not 100% sure how to fulfill:
https://github.com/metareflection/certified-reasoning/blob/open/learning/lm_tool_open.py#L192

**Comment by superkelvint** [comment]
@krrishdholakia if this issue is about providing support for running HF transformer and embeddings locally rather than using the HF API, then I'm a +1 on it. 

One of LiteLLM's key value props to users is a viable, lightweight alternative to LangChain. LangChain [does support this local use-case](https://python.langchain.com/docs/integrations/providers/huggingface) and it is really nice to be able to switch between OpenAI and a local HF model without any change in client code.

Happy to discuss more if it'd be helpful.

**Comment by sandangel** [comment]
I'm also interested in calling HF transformer locally as we can have the control over the hardware and network. We can run the model on devices without internet access. That is a critical business use case for us.

**Comment by ghost** [comment]
Quick update: You can now call custom APIs within litellm (no need to spin up openai server) - https://docs.litellm.ai/docs/providers/custom_llm_server

@superkelvint @sandangel feel free to make a PR if you have an implementation that works well for you!
