### ISSUE TITLE
Interpreter issues

### ISSUE THREAD

**Issue by DenisMio** [BerriAI/litellm#833]
Hello,

I have issues with importing OPEN AI INTERPRETER.

""LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.""

I saw your fixed code, but I got still this error. What should I do? 

I work on windows.

Cheers!

**Comment by ghost** [comment]
@DenisMio what's the error?

**Comment by DenisMio** [comment]
I am encountering a JSONDecodeError while using the Open Interpreter with OpenAI's API, where a non-JSON response is being returned. Additionally, a Cloudflare HTTP 520 error suggests a connection issue with the API server. This error prevents the use of the GPT-4 model and affects critical operations.

________________________________

**Comment by DenisMio** [comment]
I fixed it! Thank you anyway for the fast response!


________________________________
