### ISSUE TITLE
[Bug]: requests being swallowed

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#834]
### What happened?

in high traffic on the router for async calls, some requests are being swallowed / responses not returned. 

### Relevant log output

```shell
n/a
```

**Comment by ghost** [comment]
cc: @PrathamSoni tracking this here. feel free to add more details, i'll look into this today.

**Comment by ghost** [comment]
fixed in this commit - https://github.com/BerriAI/litellm/commit/0ab6b2451d052b42d71ca83e10849f6b81d5d975
