### ISSUE TITLE
[Feature]: support ollama json mode for function calling

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#835]
### The Feature

ollama has a json mode - support parsing the output to the function calling output 

### Motivation, pitch

enable benchmarking use-cases for function calling with open source models

**Comment by ishaan-jaff** [comment]
thanks for making this issue @krrishdholakia excited to support this

**Comment by ishaan-jaff** [comment]
added : https://docs.litellm.ai/docs/providers/ollama#example-usage---json-mode

**Comment by ishaan-jaff** [comment]
closing this issue since this is added
