### ISSUE TITLE
[Feature]: bring back rpm/tpm monitoring

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#837]
### The Feature

I think we made a mistake by removing this functionality. It's not needed for non-openai models / self-deployments, but definitely helpful when managing multiple azure deployments. 

We should bring this back. 

### Motivation, pitch

user request.

**Comment by ghost** [comment]
cc: @PrathamSoni

**Comment by ghost** [comment]
this is now supported from v`1.1.0` onwards
