### ISSUE TITLE
[Feature]: Use OpenAI's AsyncClient to handle network I/O calls across providers

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#839]
### The Feature

OpenAI's v1 sdk has an async client which manages httpx to make async calls. This is pretty helpful, as it handles managing the event loop, closing the httpx connection etc. for you.

We should use this to handle async calls across all providers. Currently for non-openai, azure, huggingface endpoints, we wrap our sync calls in asyncio threads, but this means we don't benefit from any perf gains from async network calls. 

### Motivation, pitch

make async calls across providers faster + Feature parity with openai.

**Comment by ghost** [comment]
Any help on this would be amazing. 

Here's the relevant class - https://github.com/openai/openai-python/blob/90aa5eb3ed6b92d9a1de89c0ee063f4768f92256/src/openai/_base_client.py#L1107

**Comment by ishaan-jaff** [comment]
this is completed @ianpurton
