### ISSUE TITLE
fix sentry - anthropic error

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#84]
Sentry uses pydantic > 2

Anthropic uses pydantic < 2

This means i'm unable to use sentry alongside the anthropic python sdk.

**Comment by ishaan-jaff** [comment]
note for the future - once we make the fix we should let Anthropic know

**Comment by ghost** [comment]
I faced this error again today. You **cannot** be a production system and have this happen. 

Interestingly though - this isn't an error that happens on my local machine -> however i'm able to consistently repro this within a docker container. 

@ishaan-jaff

**Comment by ghost** [comment]
closing as fixed - we've moved to the anthropic rest endpoint.
