### ISSUE TITLE
[Bug]: Trying to wrap text-generation-inference

### ISSUE THREAD

**Issue by kulbinderdio** [BerriAI/litellm#840]
### What happened?

I used the following to run TGI

model=TheBloke/Yarn-Mistral-7B-128k-AWQ

sudo docker run --net=host --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:latest --model-id $model  --num-shard $num_shard --max-batch-prefill-tokens 2048 --quantize awq

This runs fine and I can call it using curl

I then try and wrap it using litellm using
litellm   --model huggingface/TheBloke/Yarn-Mistral-7B-128k-AWQ  --api_base http://0.0.0.0:80/generate --host localhost --port 6789

I then connect to http://localhost:6789
and try and execute the commands on the page but keep getting exceptions

When i run litellm --test, I get the log shown below

I've have tried many different combinations, including different models but none seem to work.
Have I completely misunderstood what litellm is meant to do or can someone help me resolve this?

many thanks

### Relevant log output

```shell
litellm --test

LiteLLM: Making a test ChatCompletions request to your proxy
Traceback (most recent call last):
  File "/home/dio/anaconda3/bin/litellm", line 8, in <module>
    sys.exit(run_server())
             ^^^^^^^^^^^^
  File "/home/dio/anaconda3/lib/python3.11/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dio/anaconda3/lib/python3.11/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/dio/anaconda3/lib/python3.11/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dio/anaconda3/lib/python3.11/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dio/anaconda3/lib/python3.11/site-packages/litellm/proxy/proxy_cli.py", line 129, in run_server
    response = client.chat.completions.create(model="gpt-3.5-turbo", messages = [
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dio/anaconda3/lib/python3.11/site-packages/openai/_utils/_utils.py", line 299, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dio/anaconda3/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 598, in create
    return self._post(
           ^^^^^^^^^^^
  File "/home/dio/anaconda3/lib/python3.11/site-packages/openai/_base_client.py", line 1055, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dio/anaconda3/lib/python3.11/site-packages/openai/_base_client.py", line 834, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/dio/anaconda3/lib/python3.11/site-packages/openai/_base_client.py", line 877, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'detail': 'Not Found'}
```

**Comment by ishaan-jaff** [comment]
Hi @kulbinderdio, i'm the maintainer of litellm - sorry for the poor experience 

- yes litellm is supposed to handle exactly this 

1. can you run with the `--debug` flag ? 
```
litellm --model huggingface/TheBloke/Yarn-Mistral-7B-128k-AWQ --api_base http://0.0.0.0:80/generate--host localhost --port 6789 --debug
```

2. If 1 fails can you try setting api_base to `http://0.0.0.0:80`
```
litellm --model huggingface/TheBloke/Yarn-Mistral-7B-128k-AWQ --api_base http://0.0.0.0:80 --host localhost --port 6789 --debug
```

**Comment by kulbinderdio** [comment]
Hi @ishaan-jaff thanks for the quick reply

I tries those and still not working, below are is the log output
I tried get models first followed by completions, one with full model name and one with just the last part

litellm --model huggingface/TheBloke/Yarn-Mistral-7B-128k-AWQ --api_base http://0.0.0.0:80 --host localhost --port 6789 --debug
INFO:     Started server process [127876]
INFO:     Waiting for application startup.

#------------------------------------------------------------#
#                                                            #
#            'This product would be better if...'             #
#        https://github.com/BerriAI/litellm/issues/new        #
#                                                            #
#------------------------------------------------------------#

 Thank you for using LiteLLM! - Krrish & Ishaan



Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new

Docs: https://docs.litellm.ai/docs/simple_proxy

LiteLLM: Test your local endpoint with: "litellm --test" [In a new terminal tab]


INFO:     Application startup complete.
INFO:     Uvicorn running on http://localhost:6789 (Press CTRL+C to quit)
INFO:     127.0.0.1:36656 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:36656 - "GET /openapi.json HTTP/1.1" 200 OK
Traceback (most recent call last):
  File "/home/dio/anaconda3/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dio/anaconda3/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/dio/anaconda3/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dio/anaconda3/lib/python3.11/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/dio/anaconda3/lib/python3.11/site-packages/urllib3/connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/dio/anaconda3/lib/python3.11/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/home/dio/anaconda3/lib/python3.11/http/client.py", line 1286, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/dio/anaconda3/lib/python3.11/http/client.py", line 1332, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/dio/anaconda3/lib/python3.11/http/client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/dio/anaconda3/lib/python3.11/http/client.py", line 1041, in _send_output
    self.send(msg)
  File "/home/dio/anaconda3/lib/python3.11/http/client.py", line 979, in send
    self.connect()
  File "/home/dio/anaconda3/lib/python3.11/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
           ^^^^^^^^^^^^^^^^
  File "/home/dio/anaconda3/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f5d831d49d0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dio/anaconda3/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/dio/anaconda3/lib/python3.11/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/dio/anaconda3/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='0.0.0.0', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d831d49d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dio/anaconda3/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 497, in model_list
    response = requests.get("http://0.0.0.0:11434/api/tags")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dio/anaconda3/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dio/anaconda3/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dio/anaconda3/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dio/anaconda3/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dio/anaconda3/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d831d49d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
INFO:     127.0.0.1:36656 - "GET /v1/models HTTP/1.1" 200 OK
An error occurred: Expecting value: line 1 column 1 (char 0)

 Debug this by setting `--debug`, e.g. `litellm --model gpt-3.5-turbo --debug`
Expecting value: line 1 column 1 (char 0)

Traceback (most recent call last):
  File "/home/dio/anaconda3/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 526, in completion
    data = json.loads(body_str)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/dio/anaconda3/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dio/anaconda3/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dio/anaconda3/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

INFO:     127.0.0.1:51376 - "POST /v1/completions?model=huggingface%2FTheBloke%2FYarn-Mistral-7B-128k-AWQ HTTP/1.1" 200 OK
An error occurred: Expecting value: line 1 column 1 (char 0)

 Debug this by setting `--debug`, e.g. `litellm --model gpt-3.5-turbo --debug`
Expecting value: line 1 column 1 (char 0)

Traceback (most recent call last):
  File "/home/dio/anaconda3/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 526, in completion
    data = json.loads(body_str)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/dio/anaconda3/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dio/anaconda3/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dio/anaconda3/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

INFO:     127.0.0.1:49724 - "POST /v1/completions?model=Yarn-Mistral-7B-128k-AWQ HTTP/1.1" 200 OK

thanks

**Comment by kulbinderdio** [comment]
Actually do you have a non apple silicon docker container I could try?

**Comment by ghost** [comment]
@kulbinderdio can you confirm your TGI container is running? 

> requests.exceptions.ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d831d49d0>: Failed to establish a new connection: [Errno 111] Connection refused'))


seems like your endpoint isn't receiving the calls on port 11434

**Comment by kulbinderdio** [comment]
@krrishdholakia I don't understand why it is looking at port 11434 when I specified --api_base http://0.0.0.0:80

I did the following curl on TGI container and that works

curl 0.0.0.0:80/generate \
    -X POST \
    -d '{"inputs":"What is Deep Learning?","parameters":{"max_new_tokens":2000}}' \
    -H 'Content-Type: application/json'

**Comment by kulbinderdio** [comment]
Hi, I've cleaned down other services running and ran the following commands, hope this might help figure out what I have done wrong

1. Start TGI container
echo $model
TheBloke/Yarn-Mistral-7B-128k-AWQ
sudo docker run  --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:latest --model-id $model  --num-shard $num_shard --max-batch-prefill-tokens 2048 --quantize awq

2. Start LiteLLM
litellm --model TheBloke/Yarn-Mistral-7B-128k-AWQ --api_base http://0.0.0.0:8080/generate --host 0.0.0.0 --port 6789 --debug

I have also tried the following combinations
litellm --model Yarn-Mistral-7B-128k-AWQ --api_base http://0.0.0.0:8080/generate --host 0.0.0.0 --port 6789 --debug

litellm --model TheBloke/Yarn-Mistral-7B-128k-AWQ --api_base http://0.0.0.0:8080 --host 0.0.0.0 --port 6789 --debug

3. Test TGI using curl
curl 0.0.0.0:8080/generate     -X POST     -d '{"inputs":"What is Deep Learning?","parameters":{"max_new_tokens":200}}'     -H 'Content-Type: application/json'

4. Test LiteLLM via the web front end. Tested models, v1/models, v1/completions

All throw some sort of error.
Completions:
An error occurred: Expecting value: line 1 column 1 (char 0)

 Debug this by setting `--debug`, e.g. `litellm --model gpt-3.5-turbo --debug`
Expecting value: line 1 column 1 (char 0)

Traceback (most recent call last):
  File "/home/dio/anaconda3/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 526, in completion
    data = json.loads(body_str)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/dio/anaconda3/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dio/anaconda3/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dio/anaconda3/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


Models:
Traceback (most recent call last):
  File "/home/dio/anaconda3/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dio/anaconda3/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/dio/anaconda3/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dio/anaconda3/lib/python3.11/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/dio/anaconda3/lib/python3.11/site-packages/urllib3/connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/dio/anaconda3/lib/python3.11/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/home/dio/anaconda3/lib/python3.11/http/client.py", line 1286, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/dio/anaconda3/lib/python3.11/http/client.py", line 1332, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/dio/anaconda3/lib/python3.11/http/client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/dio/anaconda3/lib/python3.11/http/client.py", line 1041, in _send_output
    self.send(msg)
  File "/home/dio/anaconda3/lib/python3.11/http/client.py", line 979, in send
    self.connect()
  File "/home/dio/anaconda3/lib/python3.11/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
           ^^^^^^^^^^^^^^^^
  File "/home/dio/anaconda3/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f813f6c3b10>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dio/anaconda3/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/dio/anaconda3/lib/python3.11/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/dio/anaconda3/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='0.0.0.0', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f813f6c3b10>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dio/anaconda3/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 497, in model_list
    response = requests.get("http://0.0.0.0:11434/api/tags")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dio/anaconda3/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dio/anaconda3/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dio/anaconda3/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dio/anaconda3/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dio/anaconda3/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f813f6c3b10>: Failed to establish a new connection: [Errno 111] Connection refused'))
INFO:     127.0.0.1:36158 - "GET /v1/models HTTP/1.1" 200 OK

**Comment by kulbinderdio** [comment]
@krrishdholakia do you have a docker container I can try this with?

**Comment by ghost** [comment]
hey @kulbinderdio my bad - i fell behind on this issue. I'm creating a support channel to get this issue debugged, as it's not one i'm able to repro on my end - dm'ed on linkedin, let me know if somewhere else works better.

**Comment by ghost** [comment]
I'm also happy to fix this via pair programming. Attaching my calendly, please grab anytime that works for you: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by ghost** [comment]
@kulbinderdio closing as this was fixed yesterday

**Comment by shailja-imw** [comment]
@krrishdholakia I am facing the Similar error I am  posting my error logs here


11:05:44 - LiteLLM Router:DEBUG: Model openai/gpt-3.5-turbo had 7 exception
litellm-1     | 11:05:44 - LiteLLM:DEBUG: Custom Logger - final response object: None
litellm-1     | 11:05:44 - LiteLLM Proxy:DEBUG: Inside Max Parallel Request Failure Hook
litellm-1     | 11:05:44 - LiteLLM Router:INFO: litellm.acompletion(model=openai/gpt-3.5-turbo) Exception OpenAIException - Error code: 404 - {'detail': 'Not Found'}
litellm-1     | 11:05:44 - LiteLLM Router:DEBUG: TracebackTraceback (most recent call last):
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/litellm/main.py", line 274, in acompletion
litellm-1     |     response = await init_response
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/litellm/llms/openai.py", line 412, in acompletion
litellm-1     |     raise e
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/litellm/llms/openai.py", line 397, in acompletion
litellm-1     |     response = await openai_aclient.chat.completions.create(
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/openai/resources/chat/completions.py", line 1330, in create
litellm-1     |     return await self._post(
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 1725, in post
litellm-1     |     return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 1428, in request
litellm-1     |     return await self._request(
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 1519, in _request
litellm-1     |     raise self._make_status_error_from_response(err.response) from None
litellm-1     | openai.NotFoundError: Error code: 404 - {'detail': 'Not Found'}
litellm-1     | 
litellm-1     | During handling of the above exception, another exception occurred:
litellm-1     | 
litellm-1     | Traceback (most recent call last):
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 862, in async_function_with_fallbacks
litellm-1     |     response = await self.async_function_with_retries(*args, **kwargs)
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 998, in async_function_with_retries
litellm-1     |     raise original_exception
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 956, in async_function_with_retries
litellm-1     |     response = await original_function(*args, **kwargs)
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 433, in _acompletion
litellm-1     |     raise e
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 412, in _acompletion
litellm-1     |     response = await litellm.acompletion(
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 2896, in wrapper_async
litellm-1     |     raise e
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 2745, in wrapper_async
litellm-1     |     result = await original_function(*args, **kwargs)
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/litellm/main.py", line 287, in acompletion
litellm-1     |     raise exception_type(
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 7501, in exception_type
litellm-1     |     raise e
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 6369, in exception_type
litellm-1     |     raise NotFoundError(
litellm-1     | litellm.exceptions.NotFoundError: OpenAIException - Error code: 404 - {'detail': 'Not Found'}
litellm-1     | 
litellm-1     | 11:05:44 - LiteLLM Router:DEBUG: Trying to fallback b/w models
litellm-1     | Traceback (most recent call last):
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/litellm/main.py", line 274, in acompletion
litellm-1     |     response = await init_response
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/litellm/llms/openai.py", line 412, in acompletion
litellm-1     |     raise e
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/litellm/llms/openai.py", line 397, in acompletion
litellm-1     |     response = await openai_aclient.chat.completions.create(
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/openai/resources/chat/completions.py", line 1330, in create
litellm-1     |     return await self._post(
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 1725, in post
litellm-1     |     return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 1428, in request
litellm-1     |     return await self._request(
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 1519, in _request
litellm-1     |     raise self._make_status_error_from_response(err.response) from None
litellm-1     | openai.NotFoundError: Error code: 404 - {'detail': 'Not Found'}
litellm-1     | 
litellm-1     | During handling of the above exception, another exception occurred:
litellm-1     | 
litellm-1     | Traceback (most recent call last):
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/litellm/proxy/proxy_server.py", line 2338, in chat_completion
litellm-1     |     response = await llm_router.acompletion(**data)
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 368, in acompletion
litellm-1     |     raise e
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 364, in acompletion
litellm-1     |     response = await self.async_function_with_fallbacks(**kwargs)
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 939, in async_function_with_fallbacks
litellm-1     |     raise original_exception
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 862, in async_function_with_fallbacks
litellm-1     |     response = await self.async_function_with_retries(*args, **kwargs)
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 998, in async_function_with_retries
litellm-1     |     raise original_exception
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 956, in async_function_with_retries
litellm-1     |     response = await original_function(*args, **kwargs)
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 433, in _acompletion
litellm-1     |     raise e
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 412, in _acompletion
litellm-1     |     response = await litellm.acompletion(
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 2896, in wrapper_async
litellm-1     |     raise e
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 2745, in wrapper_async
litellm-1     |     result = await original_function(*args, **kwargs)
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/litellm/main.py", line 287, in acompletion
litellm-1     |     raise exception_type(
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 7501, in exception_type
litellm-1     |     raise e
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 6369, in exception_type
litellm-1     |     raise NotFoundError(
litellm-1     | litellm.exceptions.NotFoundError: OpenAIException - Error code: 404 - {'detail': 'Not Found'}
litellm-1     | 11:05:44 - LiteLLM Proxy:DEBUG: An error occurred: OpenAIException - Error code: 404 - {'detail': 'Not Found'}
litellm-1     | 
litellm-1     |  Debug this by setting `--debug`, e.g. `litellm --model gpt-3.5-turbo --debug`
litellm-1     | 11:05:44 - LiteLLM Proxy:DEBUG: Results from router
litellm-1     | 11:05:44 - LiteLLM Proxy:DEBUG: 
litellm-1     | Router stats
litellm-1     | 11:05:44 - LiteLLM Proxy:DEBUG: 
litellm-1     | Total Calls made
litellm-1     | 11:05:44 - LiteLLM Proxy:DEBUG: openai/gpt-3.5-turbo: 7
litellm-1     | 11:05:44 - LiteLLM Proxy:DEBUG: 
litellm-1     | Success Calls made
litellm-1     | 11:05:44 - LiteLLM Proxy:DEBUG: 
litellm-1     | Fail Calls made
litellm-1     | 11:05:44 - LiteLLM Proxy:DEBUG: openai/gpt-3.5-turbo: 7
