### ISSUE TITLE
Add support for new input param for gpt turbo-4: response-format

### ISSUE THREAD

**Issue by rishik2504** [BerriAI/litellm#841]
### The Feature

GPT-4 turbo allows a specification for output format to parasable json through the response-type param into a completion obj. Currently I don't believe the litellm completion obj supports this

### Motivation, pitch

This is a huge addition to gpt 4 as it enforces output format which is very applicable to the application I am working on and many other GPT based products.

**Comment by rishik2504** [comment]
[https://mattmazur.com/2023/11/07/experimenting-with-gpt-4-turbos-json-mode/](url)

**Comment by ishaan-jaff** [comment]
looking into this @rishik2504

**Comment by ishaan-jaff** [comment]
https://github.com/BerriAI/litellm/commit/7abb65d53f02876a70914a0870cdb2d3457e4eac 

added

**Comment by ishaan-jaff** [comment]
this is added

**Comment by ishaan-jaff** [comment]
done on v 1.1.0 - can you try it @rishik2504 feel free to re-open
