### ISSUE TITLE
[Feature]: Have router maintain state of server response times (v2)

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#842]
### The Feature

Have the router maintain a dictionary mapping of server + most recent round trip time. This can be used to route requests to servers that are faster / have smaller queues. 

Can use Redis as the store for this. 

### Motivation, pitch

Our current implementation is by doing a live probe and putting a 1 token request on the queue. This requires using a 2nd thread in the background and can be unreliable.

**Comment by shuther** [comment]
Maybe the most recent/average speed could be captured by an observability module/third party, and we could build up a "better" strategy module that would prefer lower roud trip (should we take into account the daily average, the last 5 minutes average?) vs overall latency vs cost vs basic robin approach. I am not sure there is a one size fits all best strategy but if we could select a different one and have it "externalized", it could be easier to experiment and propose multiple appraoches?

**Comment by ghost** [comment]
great set of ideas @shuther

**Comment by ghost** [comment]
the latency based round-trip idea is now pushed to prod - https://github.com/BerriAI/litellm/commit/76f46902edce1ed03b562cbab9f8e54a6e17ef9d; will close this issue once it's in prod with docs

We already provide the call start + end times via custom callbacks for logging - https://docs.litellm.ai/docs/observability/custom_callback

@shuther what does 'cost' based routing mean?

**Comment by shuther** [comment]
as per wikipedia:

> In voice telecommunications, least-cost routing (LCR) is the process of selecting the path of outbound communications traffic based on cost. Within a telecoms carrier, an LCR team might periodically (monthly, weekly or even daily) choose between routes from several or even hundreds of carriers.

More technical answer, see [cost path](https://www.cisco.com/c/en/us/support/docs/ip/enhanced-interior-gateway-routing-protocol-eigrp/8651-21.html)

In practice, you want to push internet traffic through fiber/cable vs. satelite because of the cost, except when you cable connection is down.
