### ISSUE TITLE
[Bug]: tests are failing at first installation

### ISSUE THREAD

**Issue by filopedraz** [BerriAI/litellm#847]
### What happened?

When installing `litellm` for the first time for contributing, tests are failing.

![image](https://github.com/BerriAI/litellm/assets/29598954/2960dc4d-72e5-46f7-b572-287831cc813c)

Seems related to the fact that I didn't provide any auth key. Probably tests should use `Mock` calls.

**Comment by ishaan-jaff** [comment]
Hi @filopedraz, you can run the test file for the feature you changed

**Comment by ishaan-jaff** [comment]
for now we want out ci/cd pipeline to actually make LLM api calls

**Comment by ishaan-jaff** [comment]
closing this issue for now since you can run individual test files for the feature you change when contributing
