### ISSUE TITLE
Reading keys in Streamlit app did not work

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#85]
Tried building a streamlit app with litellm, added my .env file and assumed it would work

eventually needed to do something like this to load my .env file. It's slightly un-intuitive how liteLLM reads api keys / where it's read from. 
<img width="466" alt="Screenshot 2023-08-09 at 9 07 56 PM" src="https://github.com/BerriAI/litellm/assets/29436595/309836fc-3d01-40c2-9255-ad4b118ebe3e">

**Comment by ishaan-jaff** [comment]
@krrishdholakia I think you saw a similar issue with keys

**Comment by ghost** [comment]
yep

**Comment by ghost** [comment]
seems like a load_dotenv bug
