### ISSUE TITLE
[Bug]: _response_ms in completion but not in acompletion

### ISSUE THREAD

**Issue by engineerA314** [BerriAI/litellm#856]
### What happened?

In `completion`, `ModelResponse` have `_response_ms`.  
However in `acompletion`, there is no `_response_ms`.

In `utils.py`, `client.wrapper` have this line of code
```
result._response_ms = (end_time - start_time).total_seconds() * 1000 # return response latency in ms like openai
```
after the thread starts,
but in `client.wrapper_async` don't have this.

Full test code is below.
```
from litellm import completion

messages = [
    {"role": "user", "content": "What is the weather like in Boston?"}
]
response = completion(model="gpt-3.5-turbo-0613", messages=messages)
print(response._response_ms)

async_response = await acompletion(model="gpt-3.5-turbo-0613", messages=messages)
print(async_response._response_ms)
```

Additionally, I'm curious to know if the intention is to remove response_ms altogether or not. Personally, I would prefer that it remains available.

**Comment by ghost** [comment]
will take care of this today - since we have both hidden_params and openai dropped support for response_ms in v1, i'm not quite sure what the right call here is. Open to your thoughts here @engineerA314

**Comment by ghost** [comment]
This is now pushed - https://github.com/BerriAI/litellm/commit/381fdcd37bce9a35a145f3aed26670a968467734

**Comment by ghost** [comment]
@engineerA314 let me know if this solves your problem

**Comment by aschung01** [comment]
Hi, I just checked it out - it looks perfect! Thanks a lot for your help :) @krrishdholakia
