### ISSUE TITLE
Add support for Google Palm

### ISSUE THREAD

**Issue by superkelvint** [BerriAI/litellm#86]
Hi there, is support for [Google Palm](https://developers.generativeai.google/products/palm) on the roadmap?

**Comment by superkelvint** [comment]
Oh, I just saw this in the README:
```
# openrouter call
response = completion("google/palm-2-codechat-bison", messages)
```

but the README also doesn't explicitly mention Google in the list of supported LLM providers.

**Comment by ghost** [comment]
hey @superkelvint - here's the PR but we're blocked on a key for testing. Any help here would be great

**Comment by ghost** [comment]
if you have time for a quick call - i can give you context and see how we can get this to prod quickly

https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by superkelvint** [comment]
Scheduled! Thanks for the quick response.

**Comment by ghost** [comment]
Ofc @superkelvint - thanks for the help. Speak soon! 

Would also recommend joining the Discord - https://discord.com/invite/wuPM9dRgDw
