### ISSUE TITLE
[Feature]: Llama.cpp backend support

### ISSUE THREAD

**Issue by wendlerc** [BerriAI/litellm#860]
### The Feature

Add [llama.cpp](https://github.com/ggerganov/llama.cpp) as a backend.  

### Motivation, pitch

[llama.cpp](https://github.com/ggerganov/llama.cpp) provides an amazing way to run quantized versions of LLMs on CPU, is well maintained and has seen dramatic growth recently. For nearly each llama-like model: llama, llama2, mistral, zephyr there are checkpoints in the GGUF-format compatible with this library available on hugginface:
* [llama2-7B-chat](https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGUF)
* [llama2-70B-chat](https://huggingface.co/TheBloke/Llama-2-70B-Chat-GGUF)
* [zephyr-7B-beta](https://huggingface.co/TheBloke/zephyr-7B-beta-GGUF)
* ...

### Twitter / LinkedIn details

https://twitter.com/wendlerch
https://www.linkedin.com/in/wendlerc/

**Comment by ghost** [comment]
@wendlerc they already provide an openai compatible endpoint, so you could call it today with `openai/` in front of the model name - https://docs.litellm.ai/docs/providers/custom_openai_proxy

closing the issue for now as it seems to be already work with litellm, but please re-open if not.

**Comment by wendlerc** [comment]
but their endpoint requires openai==0.28 no?

**Comment by shakfu** [comment]
@krrishdholakia @wendlerc Has anyone gotten llama.cpp openai-compatible endpoint to work?

It's not working from my end. Would appreciate re-opening this issue.

**Comment by shakfu** [comment]
Scratch that, I posted too soon, indeed, just as I posted the question above, I got it to work fine:

```python
"""
An example of using litellm with llama.cpp's openai compatible llama-server endpoint

This example assumes that `llama-server -m models/Llama-3.2-1B-Instruct-Q8_0.gguf` is running
in the background.
"""

import litellm
import os

response = litellm.completion(
   model='openai/llama3.2',         # "openai/" prefix is required
   api_key="-",                     # this should not be empty or it will not work
   api_base='http://0.0.0.0:8080',  # the default llama.cpp llama-server endpoint
   messages=[{
      'role': 'user', 
      'content': "What is the age of the universe?",
   }]
)

print(response)


```
