### ISSUE TITLE
[Bug]: Anyscale models have context length 4k in LiteLLM, but much more on Anyscale

### ISSUE THREAD

**Issue by sebderhy** [BerriAI/litellm#861]
### What happened?

I realized that all Anyscale models endpoints have a context limitation of 4k in Litellm (as written here: https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json )

However, on Anyscale, they say that the context length of Mistral 7B and Zephyr 7B are 16K:
![image](https://github.com/BerriAI/litellm/assets/13600027/9559540f-06ea-407e-9b42-d78c47fdc674)
(source: FAQ https://app.endpoints.anyscale.com/ )

Btw, I don't mind switching to another provider if needed. In general, what's the best way to call those 2 models with Litellm? I need something scalable, and with no cold start issues (like Replicate has)

**Comment by ishaan-jaff** [comment]
Fixed @sebderhy : https://github.com/BerriAI/litellm/commit/c4f9ef86c987499898ca514c0e8c98afddbf8a1f
