### ISSUE TITLE
[Bug]: Missing /embeddings route in proxy

### ISSUE THREAD

**Issue by jeromeroussin** [BerriAI/litellm#869]
### What happened?

The older server had an /embeddings route but I am not seeing one for the newer proxy? I am getting a 404 when connecting to /embeddings on the proxy. The proxy documentation does mention such a route though:

> Server Endpoints
> 
> - POST /chat/completions - chat completions endpoint to call 100+ LLMs
> - POST /completions - completions endpoint
> - POST /embeddings - embedding endpoint for Azure, OpenAI, Huggingface endpoints
> - GET /models - available models on server

Is this an oversight perhaps? Are am I missing something? We very much need such a route to make use of the proxy.

Thanks

Jerome

**Comment by ghost** [comment]
Hey @jeromeroussin i'll add it today. 

Curious - What're you using the proxy for?

**Comment by jeromeroussin** [comment]
Thanks Krrish! I replied to you on LinkedIn.

**Comment by ghost** [comment]
closing as this is now implemented.
