### ISSUE TITLE
[Feature]: Router pre-call checks - context window, tpm/rpm limits, function calling support

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#872]
### The Feature

Pick the right model group based on the context size message context size

### Motivation, pitch

user request 

### Twitter / LinkedIn details

@shuther

**Comment by ghost** [comment]
2nd user request about doing something similar but for function calling (i.e. if it's a function calling request, route to the function calling model group) 

cc: @paulpierre

**Comment by ghost** [comment]
I felt something similar while working on tpm-rpm routing. 

The tpm-rpm check for hitting rate limits, shouldn't be isolated to just 1 routing strategy, it can be used across all routing strategies, if the user has set this value in their model list.

**Comment by ghost** [comment]
we now support tpm/rpm checks for latency based routing as well

**Comment by georgeseifada** [comment]
Love this feature idea +1

**Comment by ghost** [comment]
+2 second user asked for this

**Comment by ishaan-jaff** [comment]
done in #2669 @georgeseifada
