### ISSUE TITLE
[Bug]: Latency based routing taking longer than simple shuffle 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#873]
### What happened?

- 1k requests, 3 deployments, 100 workers, random shuffle → ELAPSED TIME: 35.93206310272217
- 1k requests, 3 deployments, 100 workers, latency-based routing → n/a (takes >5min).

### Relevant log output

```shell
N/A
```

**Comment by ishaan-jaff** [comment]
fixed + used in prod now
