### ISSUE TITLE
[Feature]: move to async calls on proxy

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#874]
### The Feature

Use async calls on proxy. This will allow for parallel calls to be made. 

### Motivation, pitch

make the proxy faster.

**Comment by ghost** [comment]
the main piece of work is moving from this
<img width="935" alt="Screenshot 2023-11-22 at 10 21 55 AM" src="https://github.com/BerriAI/litellm/assets/17561003/07e2dc67-aec1-4771-ae97-d8d6b662f579">

to using async completions / text completions.

**Comment by ghost** [comment]
Since litellm itself doesn't support async text completions today, perhaps for v1 scope we can begin with at least moving completions to `llm_router.acompletions(..)` and `litellm.acompletion()`

**Comment by ghost** [comment]
closing as this is now done.
