### ISSUE TITLE
[Bug]: GPT-4-Turbo max tokens != max output tokens - fix model cost map 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#878]
### What happened?

GPT 4 Turbo has a max output token of 4096. It's max input token is ~128k. 

this triggers errors - "So it looks like it complains if the limit is higher than the output token limit." 
![image](https://github.com/BerriAI/litellm/assets/17561003/608939ec-981f-40f1-80f5-e4785b0b92bc)

**Comment by ghost** [comment]
cc: @toniengelhardt tracking this here - i'm guessing this means we'll need to update all openai models to follow the max_input_tokens, max_output_tokens format

**Comment by toniengelhardt** [comment]
@krrishdholakia probably. I think PaLM 2 also makes a similar distinction. Would be great to have a consistent approach across different providers and comprehensive docs on how it works.

IMO, ideally we could set input limit and output limit separately, but in the past OpenAI only had a limit for both together.

**Comment by ghost** [comment]
agreed - i think a refactor might make most sense

**Comment by ghost** [comment]
tagging as a proxy request, as this impacts the `/model/info` issue too

**Comment by ghost** [comment]
Just pushed support for this - https://github.com/BerriAI/litellm/commit/2f377db604d57de814871658e1800eced5216194

cc: @toniengelhardt 

While we didn't remove the old 'max_tokens', i added a new 'max_output_tokens' key for the openai + azure models 

Over time, i think we'll migrate all models to follow a similar input/output structure

**Comment by ghost** [comment]
Also added max_input_tokens for the openai and azure models

**Comment by toniengelhardt** [comment]
@krrishdholakia could you clarify how the `max_tokens` and `max_input_tokens` apply to different models? Do they always only apply to the output?

I remember, originally the `input_tokens` parameter was the combined number of input and output tokens for OpenAI models. Did that change now?

I think it would be good to add this in detail to the docs.

**Comment by ghost** [comment]
> Did that change now?

No, that didn't change

I used max_input_tokens because it felt weird to not specify what the max input was, if we were doing the same for output.

What would you suggest?

**Comment by toniengelhardt** [comment]
Two settings makes a lot of sense, for max input and max output. On my end it would be good if it would be consistent across providers/models as far as possible and that the behavior is documented well.

Btw, the PR you mentioned added `max_input_tokens` only to the info json, not to the actual code and what's sent to the API right?
