### ISSUE TITLE
[Feature]: DynamoDB Backend

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#887]
### The Feature

Instead of PostgreSQL, it'd be nice to have support for DynamoDB. Should help with scaling.

### Motivation, pitch

Related to #881.

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by ghost** [comment]
doesn't seem like dynamodb would be supported by the prisma interface - https://github.com/prisma/prisma/issues/1676#issuecomment-1464117515

@Manouchehri is this still a valid feature request given the gcloud datastore issue + in-memory caching for key issue?

**Comment by Manouchehri** [comment]
Yeah, let's close this one off. =)
