### ISSUE TITLE
[Feature]: Google Cloud Datastore Backend

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#888]
### The Feature

Instead of PostgreSQL, it'd be nice to have support for Google Cloud Datastore. Should help with scaling on Google Cloud Run.

### Motivation, pitch

Related to #887.

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by Manouchehri** [comment]
Slightly on-topic: Google Cloud Run will likely scale better than AWS Lambdas, due to the fact that you can configure multiple requests to go to a single container with Cloud Run.

The main reason I'd go with Lambdas right now, is because it's likely a better option to stick with AWS if you're using Supabase for your PostgreSQL server.

(I also could be totally wrong, and Lambdas outperform Cloud Run in the end.)

**Comment by ghost** [comment]
we use prisma to manage the db interface - i believe they have support for google cloud datastore, will require investigation. - https://github.com/prisma/prisma1/issues/1708
