### ISSUE TITLE
[Feature]: track spend per key in proxy server

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#892]
### The Feature

add our budget manager for tracking spend per key in proxy server 

### Motivation, pitch

user request

**Comment by ghost** [comment]
do not block limits, just track how much the spend is

**Comment by ghost** [comment]
needs to support tracking spend for multiple azure regions


https://azure.microsoft.com/en-us/pricing/details/cognitive-services/openai-service/

**Comment by ghost** [comment]
I believe azure currently has a fixed cost per model independent of regions.

**Comment by ishaan-jaff** [comment]
Here's my checklist for this 

- [x] - add column to track spend
- [ ] - write to the column for spend
- [ ] - write spend for azure model
- [x] - add spend tracking for FT gpt-3.5

**Comment by ghost** [comment]
closing as this is now done.
