### ISSUE TITLE
[Bug]: OpenAPI Swagger has incorrect args

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#895]
### What happened?

Our swagger says to pass in requests as part of the request.args, this is wrong and leads to frustration for users using it to test queries. 

![image](https://github.com/BerriAI/litellm/assets/17561003/690a0b6f-6130-43fe-bb3f-2cf07817c465)
![image](https://github.com/BerriAI/litellm/assets/17561003/76b41df2-6d26-4307-9ae8-bf58efb8059d)

**Comment by ghost** [comment]
@ishaan-jaff can you look at this when you get the chance? i believe you worked on the initial swagger.

**Comment by Manouchehri** [comment]
This is because the request objects aren't defined properly with FastAPI.

This should get you started on the right path:

```python3
from fastapi import Body
from pydantic import BaseModel

# Define the request body model
class ChatCompletionRequest(BaseModel):
    messages: Optional[list] = None
    model: Optional[str] = None

@router.post("/v1/chat/completions", dependencies=[Depends(user_api_key_auth)])
@router.post("/chat/completions", dependencies=[Depends(user_api_key_auth)])
@router.post("/openai/deployments/{model:path}/chat/completions", dependencies=[Depends(user_api_key_auth)]) # azure compatible endpoint
async def chat_completion(request: Request, model: Optional[str] = None, body: ChatCompletionRequest = Body(...)):
    # Use the `body` instance directly since it’s already defined and parsed by pydantic
    try: 
        print(f"receiving data: {body}")
        body.model = (
            general_settings.get("completion_model", None) # server default
            or user_model # model name passed via cli args
            or model # for azure deployments
            or body.model # default passed in http request
        )
        data = body.dict()
        data["call_type"] = "chat_completion"
        return litellm_completion(
            **data
        )
    except Exception as e: 
        print(f"\033[1;31mAn error occurred: {e}\n\n Debug this by setting `--debug`, e.g. `litellm --model gpt-3.5-turbo --debug`")
        error_traceback = traceback.format_exc()
        error_msg = f"{str(e)}\n\n{error_traceback}"
        try:
            status = e.status_code # type: ignore
        except:
            status = 500
        raise HTTPException(
            status_code=status,
            detail=error_msg
        )
```

**Comment by ishaan-jaff** [comment]
<img width="857" alt="Screenshot 2023-12-01 at 9 11 40 AM" src="https://github.com/BerriAI/litellm/assets/29436595/a9174c6e-12ab-435c-b37f-c027f1b197fd">

discord user ran into an issue with this too

**Comment by ishaan-jaff** [comment]
they thought proxy was not working for them

**Comment by ishaan-jaff** [comment]
now u can see the expected output schema 
<img width="1020" alt="Screenshot 2023-12-01 at 9 25 31 AM" src="https://github.com/BerriAI/litellm/assets/29436595/8e0ada62-236e-4e78-8862-228e02dc89d8">

**Comment by ishaan-jaff** [comment]
<img width="1104" alt="Screenshot 2023-12-01 at 1 54 58 PM" src="https://github.com/BerriAI/litellm/assets/29436595/31321ba8-5909-446c-ba24-bcd882cc488f">


done

**Comment by ishaan-jaff** [comment]
https://github.com/BerriAI/litellm/commit/e8ae347681e5f7973fd96824df115801f719a6f4
