### ISSUE TITLE
[Bug]: OpenAPI spec is missing key/auth info

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#896]
### What happened?

e.g. endpoints that require a key, like https://api.litellm.ai/#/default/generate_key_fn_key_generate_post, should look like:

![image](https://github.com/BerriAI/litellm/assets/7232674/dc773616-f7d1-467f-83cf-ca32af137178)

Source: https://itsjoshcampos.codes/fast-api-api-key-authorization

**Comment by ishaan-jaff** [comment]
currently fast api is auto generating the OpenAPI spec

**Comment by Manouchehri** [comment]
It's doable. Working on it now.

![image](https://github.com/BerriAI/litellm/assets/7232674/3d255a87-3438-4f3d-b962-36f96b15ca97)
