### ISSUE TITLE
[Feature]: expose sync logging

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#897]
### The Feature

Currently we run logging in a separate thread. This makes sense when i'm trying to use logging tools but not when i'm trying to use the fact that a call failed or succeeded to execute logic in my app (e.g. cooldown server). 

Expose a way for me to plug into this information in a sync way. 

### Motivation, pitch

improving router cooldown logic.

**Comment by Manouchehri** [comment]
Could we also redact sensitive API keys from the logging? :)

**Comment by ghost** [comment]
closing as this was fixed by making failure calls sync (success callbacks are still async). 

@Manouchehri i'm creating a separate issue to track the logging issue.
