### ISSUE TITLE
[Feature]: `POST /key/delete` endpoint

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#899]
### The Feature

Similar to `POST /key/generate`, we should have an endpoint that allows deleting keys, like `POST /key/delete`.

The master key should be able to delete any key, including itself (this is in case the key is leaked). User keys should only be able to delete themselves. 

### Motivation, pitch

I think liteLLM should keep key management as simple as possible, and leave the specifics up to other developers who are building on top of it.

**Comment by ghost** [comment]
pushed - https://github.com/BerriAI/litellm/commit/9a444338448e79c134d69acef73c7bd324bd04bf

Test request: 
```bash
curl --location 'http://0.0.0.0:8000/key/delete' \
--header 'Authorization: Bearer sk-1234' \
--header 'Content-Type: application/json' \
--data '{
    "keys": ["sk-_4fTul60M74ARHjYts1--Q"]
}'
```

**Comment by ghost** [comment]
will have it in prod + in docs tomorrow (once it passes our ci/cd pipeline).

**Comment by ghost** [comment]
this is in prod - v`1.7.1`.
