### ISSUE TITLE
Add state handlers / observability

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#9]
When I call litellm there's always just 2 things I need to know - did the query succeed or fail? 

If it succeeds I'll log it to PostHog 

If it fails I'll log it to PostHog + Slack 

Wonder if litellm can help simplify this for me.

**Comment by ghost** [comment]
Analytics.js has callbacks -> maybe having them as `success_callback` and `failure_callback` 

<img width="742" alt="Screenshot 2023-07-28 at 9 34 21 AM" src="https://github.com/BerriAI/litellm/assets/17561003/fe527db6-9319-4716-81d9-654c4ff264c7">


Alt idea:

```
from litellm import completion_client
completion = completion_client(success_callback=["posthog"], failure_callback=["posthog","slack"]) 

response = completion(model="gpt-3.5-turbo", messages=messages)
```

**Comment by ghost** [comment]
Sketching this idea out a bit more - enabling custom functions as well

Use Case: I want to create a unified pricing dashboard on top of this. For that I need to know when it worked/didn't work - when it works -> i'm calculating the number of tokens used for input/output and then sending that data to my supabase table.

```
from litellm import completion_client
completion = completion_client(success_callback=["posthog"], failure_callback=["posthog","slack"]) 

def success_handler():
   print("it worked!")

def failure_handler():
   print("error occurred")

response = completion(model="gpt-3.5-turbo", messages=messages, success_callback_fn=success_handler, failure_callback_fn=failure_handler)
```

**Comment by ghost** [comment]
closing as this has been implemented. 

https://litellm.readthedocs.io/en/latest/advanced/
