### ISSUE TITLE
how do i do function calling with litellm?

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#90]
It's not clear to me how to do function calling with litellm - the docs don't give any examples.

**Comment by Blackkadder** [comment]
I'm interested in this as well

**Comment by ghost** [comment]
@Blackkadder we'll have a demo notebook out with this later today - happy to send it across 

P.S.: we do daily changelogs + resources on the Discord - would love to have you there https://discord.gg/wuPM9dRgDw

**Comment by ishaan-jaff** [comment]
@Blackkadder @krrishdholakia here's a notebook on the same: https://github.com/BerriAI/litellm/blob/main/cookbook/liteLLM_function_calling.ipynb
