### ISSUE TITLE
[Bug]: AttributeError: 'ModelResponse' object has no attribute 'response_ms'

### ISSUE THREAD

**Issue by saurabhk2** [BerriAI/litellm#901]
### What happened?

litellm-1.6.0 

```
from litellm import completion
import os
os.environ["OPENAI_API_KEY"] = "KEY"
messages=[{"role": "user", "content": "what is the color of the sky"}]
response = completion(model="gpt-3.5-turbo-1106", messages=messages)
print(response.response_ms) 
```

leads to error
> _File ~\anaconda3\envs\nlp\lib\site-packages\pydantic\main.py:718 in __getattr__
>     return pydantic_extra[item]
> 
> KeyError: 'response_ms'
> 
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
> 
>   Cell In[7], line 10
>     print(response.response_ms) # 616.25# 616.25
> 
>   File ~\anaconda3\envs\nlp\lib\site-packages\pydantic\main.py:720 in __getattr__
>     raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}') from exc
> 
> AttributeError: 'ModelResponse' object has no attribute 'response_ms'

seems the ModelResponse class does not have this variable any more.

is there any other way to get the response time now?

**Comment by ishaan-jaff** [comment]
I believe it's accessed like this

```
  print(response._response_ms)
```

**Comment by ishaan-jaff** [comment]
<img width="1280" alt="Screenshot 2023-11-24 at 5 23 10 AM" src="https://github.com/BerriAI/litellm/assets/29436595/3cf8587b-0e81-4e79-a3d4-b25457ff1fad">

works fine for me @saurabhk2

**Comment by ishaan-jaff** [comment]
can you try using `_response_ms` instead and see if it works for you @saurabhk2

**Comment by saurabhk2** [comment]
yes response._response_ms is working. seems this has changed in the updated code. earlier it used to work with response.response_ms.

Thanks for the prompt reply
