### ISSUE TITLE
[Feature]: Redact api keys from proxy loaded config file print statement 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#906]
### The Feature

don't send api keys to logging callbacks 

### Motivation, pitch

user request @Manouchehri

**Comment by ghost** [comment]
@Manouchehri can you add more details on this - how are you impacted by this today?

**Comment by Manouchehri** [comment]
![image](https://github.com/BerriAI/litellm/assets/7232674/5515766c-f8e6-4885-a73f-9cb34a178c9a)

Having keys show up in our plaintext logs breaks a lot of best practices for handling sensitive keys. 😅

**Comment by ghost** [comment]
this looks like the print statement on the proxy load

**Comment by ghost** [comment]
@Manouchehri pushed - https://github.com/BerriAI/litellm/commit/bb687cb96f72d19155c4ec175d474ccceb4abd78

**Comment by ghost** [comment]
let me know if this addresses your issue.

**Comment by Manouchehri** [comment]
Will test it out, thanks!

A good way of avoid regressions here, is to pipe all stdout/stderr to a file, and then grep for keys (as there should be 0 matches if redaction is working).

**Comment by Manouchehri** [comment]
We still have some leakage. 😄 

```
Enters prisma db call, token: REMOVED
```

https://github.com/BerriAI/litellm/blob/278ab7dcab523b1bc841e6590268d4a955068aa1/litellm/proxy/proxy_server.py#L411

**Comment by ghost** [comment]
@Manouchehri When I've tried to use the stdout/stderror method, I've often found it to work on local but fail on circle ci (not sure why). 

Open to suggestions on how we could test for this in a more stable way.

**Comment by Manouchehri** [comment]
What might be easier (and solve more problems in the future), is switching to the logging library completely and removing all usage of `print`.

https://docs.python.org/3/howto/logging.html

This way you can add an optional flag like `--logfile example.1.txt` to LiteLLM and not bother with stdout/stderr redirection.

**Comment by ishaan-jaff** [comment]
+1 on the idea of using logging for the proxy - another user had buffer issues and it would have fixed the problem if they could redirect to a file

**Comment by ishaan-jaff** [comment]
we only show the config yaml when `--debug` is passed
