### ISSUE TITLE
[Bug]: Perplexity model list doesn't match official docs

### ISSUE THREAD

**Issue by toniengelhardt** [BerriAI/litellm#908]
### What happened?

The Perplexity model list [here](https://docs.litellm.ai/docs/providers/perplexity) doesn't match the [official list](https://docs.perplexity.ai/docs/model-cards). Using e.g. `replit-code-v1.5-3b` results in 

```
Error code: 400 - {'error': {'message': "Invalid model 'replit-code-v1.5-3b'. Permitted models can be found in the documentation at https://docs.perplexity.ai/docs/model-cards.", 'type': 'invalid_model', 'code': 400}}
```

**Comment by ghost** [comment]
Thanks for the catch. I believe replit is only on the text completions endpoint. I'll push a fix.

**Comment by ghost** [comment]
fixed
