### ISSUE TITLE
[Feature]: complete list of requirements.txt

### ISSUE THREAD

**Issue by shuther** [BerriAI/litellm#911]
### The Feature

Is it possible to confirm which modules should be part of the requirements? I used 2 different tools (with of course 2 different outputs) so we can clean poetry?
`pigar -p ../dev-requirements.txt -i venv/ docs/`
and `pipreqs --print --ignore venv,docs`

### Motivation, pitch

the requirements.txt is incomplete, so building it with virtual environment is raising issues based on the feature we use.

**Comment by ghost** [comment]
@shuther what sort of issues are you seeing? We try to keep the requirements.txt in sync with the proxy requirements

**Comment by ghost** [comment]
@shuther bump?

**Comment by shuther** [comment]
it seems there are optional dependencies (try import within the code), do you consider they should be in the requirements.txt or under an extra section?

**Comment by shuther** [comment]
example just today, litellm returns the error:
`Import error - trying to use async for ollama. import async_generator failed. Try \'pip install async_generator\`

**Comment by ishaan-jaff** [comment]
@shuther requirements.txt is now up to date, it also includes async_generator https://github.com/BerriAI/litellm/commit/623716fa8951f6062caf2473f2fb776adf0412be 

feel free to re-open if this does not address your issue
