### ISSUE TITLE
[Feature]: load router fallback from completion call 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#914]
### The Feature

if a user passes in a fallback in router.completion() and it's available in the model_list, 

have that be used for fallbacks. 

### Motivation, pitch

(potential user) request

**Comment by ghost** [comment]
where we need to make the change: 
https://github.com/BerriAI/litellm/blob/7cf029d67740d16e0a9320cdcab69b9eb2345c3a/litellm/router.py#L135

**Comment by ghost** [comment]
pushed - https://github.com/BerriAI/litellm/commit/fa713abfc39cc62ec5e6ffe2713b705b87ad0133
