### ISSUE TITLE
[Bug]: ollama backend model list looks wrong to me

### ISSUE THREAD

**Issue by oderwat** [BerriAI/litellm#917]
### What happened?

I used the webinterface to query the models and got this result:

<img width="483" alt="image" src="https://github.com/BerriAI/litellm/assets/719156/95abb00a-557a-4bcb-a9d8-959067838d2d">

I wonder if that is what it is supposed to be.

I started litellm (pip installed) using:

`litellm --model "ollama/deepseek-coder:6.7b-instruct-q8_0" --api_base http://192.168.1.230:11434 --temperature 0.3 --max_tokens 2048`

**Comment by ishaan-jaff** [comment]
looks like a bug - it's not intended

**Comment by krrishdholakia** [comment]
@oderwat do you have steps for repro? i'm not seeing this when i run litellm (v`1.7.5`) locall
<img width="1518" alt="Screenshot 2023-11-27 at 7 58 33 AM" src="https://github.com/BerriAI/litellm/assets/17561003/afa21397-fde9-405e-979b-ee4782f03d90">

**Comment by oderwat** [comment]
@krrishdholakia I just `pip install litellm` it which installed 1.7.1 at that time.

**Comment by oderwat** [comment]
Error is there for me with 1.7.5 too.

**Comment by oderwat** [comment]
It seems like this is fixed with 1.7.7 now.
