### ISSUE TITLE
[Feature]: Expose a `/health` endpoint with simple test query for endpoint providers

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#919]
### The Feature

Expose a `/health` endpoint to send test queries to specified model deployments

### Motivation, pitch

user churned from us because we didn't have a good enough implementation of health checks, and ended up writing their own translation layer + proxy server with haproxy.

**Comment by ghost** [comment]
It's possible to spin up a haproxy load balancer in front of a vllm /openai compatible server endpoint. 

If we make our proxy look identical to that (i.e. implement a /health endpoint that makes a test call to the requested provider), you could then easily spin up a traditional load balancer in front of our proxy and have the best of both worlds.

**Comment by ghost** [comment]
done - https://github.com/BerriAI/litellm/commit/e4f302a8e29a5f3d23a56806e259cd2cfbc6af07

**Comment by Mikkolehtimaki** [comment]
I think this doesn't test embedding endpoints currently.

**Comment by speedyankur** [comment]
It also does not test the dalle3 or other image generation modes

**Comment by ghost** [comment]
@Mikkolehtimaki @speedyankur  embedding model and image gen are both supported

You need to add the mode to the model, so we know how to call it 

```python
model_list:
  - model_name: azure-embedding-model
    litellm_params:
      model: azure/azure-embedding-model
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
      api_version: "2023-07-01-preview"
    model_info:
      mode: embedding # 👈 ADD THIS
```

```python
model_list:
  - model_name: image-gen-model
    litellm_params:
      model: dall-e-3
    model_info:
      mode: image_generation # 👈 ADD THIS
```
Docs: https://docs.litellm.ai/docs/proxy/health#embedding-models
