### ISSUE TITLE
expose api testing for me

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#92]
I'm seeing inconsistent errors when trying to use the gorilla api. I'm unsure what is triggering this / why it's being triggered. If you could expose a simple set of tests (maybe even just 1 load test, that'd be awesome).

**Comment by ghost** [comment]
cc: @ishaan-jaff

**Comment by ishaan-jaff** [comment]
can you elaborate on what this means ?

**Comment by ishaan-jaff** [comment]
are you looking for a load_test_completion()
where you specify num runs = x and see how many failed ?

**Comment by ghost** [comment]
yep - even if it's preset that's fine 

```
litellm.test_model(model_name="...")
```

**Comment by ishaan-jaff** [comment]
marking this as done 😊
