### ISSUE TITLE
ollama problems

### ISSUE THREAD

**Issue by iplayfast** [BerriAI/litellm#921]
`
litellm --model ollama/alfred
`
Looks good.
says 
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 

in a new terminal
`
litellm --test
`
original terminal says
`INFO:     127.0.0.1:50152 - "POST /chat/completions HTTP/1.1" 200 OK
receiving data: {'messages': [{'role': 'user', 'content': 'this is a test request, write a short poem'}], 'model': 'gpt-3.5-turbo', 'stream': True}
An error occurred: Import error - trying to use async for ollama. import async_generator failed. Try 'pip install async_generator'

 Debug this by setting `--debug`, e.g. `litellm --model gpt-3.5-turbo --debug`
INFO:     127.0.0.1:50152 - "POST /chat/completions HTTP/1.1" 500 Internal Server Error
receiving data: {'messages': [{'role': 'user', 'content': 'this is a test request, write a short poem'}], 'model': 'gpt-3.5-turbo', 'stream': True}
An error occurred: Import error - trying to use async for ollama. import async_generator failed. Try 'pip install async_generator'

 Debug this by setting `--debug`, e.g. `litellm --model gpt-3.5-turbo --debug`
INFO:     127.0.0.1:50160 - "POST /chat/completions HTTP/1.1" 500 Internal Server Error
receiving data: {'messages': [{'role': 'user', 'content': 'this is a test request, write a short poem'}], 'model': 'gpt-3.5-turbo', 'stream': True}
An error occurred: Import error - trying to use async for ollama. import async_generator failed. Try 'pip install async_generator'

 Debug this by setting `--debug`, e.g. `litellm --model gpt-3.5-turbo --debug`
INFO:     127.0.0.1:50176 - "POST /chat/completions HTTP/1.1" 500 Internal Server Error

`

in test terminal 
`litellm --test

LiteLLM: Making a test ChatCompletions request to your proxy

LiteLLM: response from proxy ChatCompletion(id='chatcmpl-ef547205-420e-4fc3-82c9-8b51b119af94', choices=[Choice(finish_reason=None, index=0, message=ChatCompletionMessage(content='A rose is red and so is my face. This is an embarrassing moment for me to embrace', role='assistant', function_call=None, tool_calls=None))], created=1700988824, model='ollama/alfred', object='chat.completion', system_fingerprint=None, usage=CompletionUsage(completion_tokens=19, prompt_tokens=10, total_tokens=29))

 Making streaming request to proxy
Traceback (most recent call last):
  File "/home/chris/anaconda3/envs/autogen/bin/litellm", line 8, in <module>
    sys.exit(run_server())
             ^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/litellm/proxy/proxy_cli.py", line 202, in run_server
    response = client.chat.completions.create(model="gpt-3.5-turbo", messages = [
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/openai/_utils/_utils.py", line 299, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 598, in create
    return self._post(
           ^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/openai/_base_client.py", line 1063, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/openai/_base_client.py", line 842, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/openai/_base_client.py", line 873, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/openai/_base_client.py", line 933, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/openai/_base_client.py", line 873, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/openai/_base_client.py", line 933, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/openai/_base_client.py", line 885, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.InternalServerError: Error code: 500 - {'detail': 'Import error - trying to use async for ollama. import async_generator failed. Try \'pip install async_generator\'\n\nTraceback (most recent call last):\n  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/litellm/main.py", line 1239, in completion\n    async_generator = ollama.async_get_ollama_response_stream(api_base, model, prompt, optional_params, logging_obj=logging)\n                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: module \'litellm.llms.ollama\' has no attribute \'async_get_ollama_response_stream\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/litellm/main.py", line 187, in acompletion\n    response =  await loop.run_in_executor(None, func_with_context)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/concurrent/futures/thread.py", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/litellm/utils.py", line 1358, in wrapper\n    raise e\n  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/litellm/utils.py", line 1289, in wrapper\n    result = original_function(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/litellm/main.py", line 1392, in completion\n    raise exception_type(\n          ^^^^^^^^^^^^^^^\n  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/litellm/utils.py", line 4545, in exception_type\n    raise e\n  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/litellm/utils.py", line 4405, in exception_type\n    raise ImportError("Import error - trying to use async for ollama. import async_generator failed. Try \'pip install async_generator\'")\nImportError: Import error - trying to use async for ollama. import async_generator failed. Try \'pip install async_generator\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 730, in chat_completion\n    response = await litellm.acompletion(**data)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/litellm/utils.py", line 1454, in wrapper_async\n    raise e\n  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/litellm/utils.py", line 1400, in wrapper_async\n    result = await original_function(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/litellm/main.py", line 193, in acompletion\n    raise exception_type(\n          ^^^^^^^^^^^^^^^\n  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/litellm/utils.py", line 4545, in exception_type\n    raise e\n  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/litellm/utils.py", line 4522, in exception_type\n    raise APIConnectionError(\nlitellm.exceptions.APIConnectionError: Import error - trying to use async for ollama. import async_generator failed. Try \'pip install async_generator\'\n'}

`

**Comment by ghost** [comment]
Did you try pip install async generator? @iplayfast

**Comment by ishaan-jaff** [comment]
@iplayfast can you confirm this was fixed for you after running `pip install async generator`?

**Comment by chymian** [comment]
hi @ishaan-jaff ,
I can confirm.
`pip install async-generator`

fixes this problem with open-interpreter in:
```
pip list |grep -ie "open-in|litellm|openai"
litellm                   0.13.2
open-interpreter          0.1.16
openai                    0.28.1
```

```
pip list |grep -ie "open-in|litellm|openai"
litellm                   1.9.4
open-interpreter          0.1.16
openai                    1.3.6
```
