### ISSUE TITLE
[Feature]: support openai image creation API calls to support DALL-E

### ISSUE THREAD

**Issue by shuther** [BerriAI/litellm#929]
### The Feature

see [API](https://platform.openai.com/docs/api-reference/images/create)

### Motivation, pitch

some plugins (i.e. autogen) make use of DALL-E and the endpoints are different than for chat.

**Comment by ghost** [comment]
is there a reason you need litellm here vs. just openai.chat completions?

**Comment by geekyayush** [comment]
This would be an awesome feature.

**Comment by shuther** [comment]
because we can use Stable Diffusion self hosted ([github](https://github.com/AUTOMATIC1111/stable-diffusion-webui)) - [API Docs](https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/3734) or DALL-E or other third party, Like for text generation, we need image generation litellm router :)

**Comment by ghost** [comment]
This is now added - https://docs.litellm.ai/docs/image_generation

**Comment by geekyayush** [comment]
> This is now added - https://docs.litellm.ai/docs/image_generation

We love you man. Thanks <3
