### ISSUE TITLE
[Bug] Error when using Russian language! 

### ISSUE THREAD

**Issue by TasksAndreySorokin** [BerriAI/litellm#932]
Error when using Russian language! Works well with English and Chinese.

langchain>=0.0.306
openai>=0.27.8 
chromadb>=0.3.29
tiktoken>=0.4.0
pydantic>=1.10.7
litellm>=0.1.819
ipykernel>=6.25.2

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

langchain.llms.base 2023-11-27 22:08:54,139 - WARNING - Retrying langchain.chat_models.litellm.ChatLiteLLM.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIConnectionError: The read operation timed out.

**Comment by ishaan-jaff** [comment]
@TasksAndreySorokin can you give us the code to repro your error ?

**Comment by sorokin-as** [comment]
> @TasksAndreySorokin can you give us the code to repro your error ?

I'm using this project. https://github.com/filip-michalsky/SalesGPT
The code I use is here https://github.com/TasksAndreySorokin/salesgpt

Settings for Russian language here
examples/example_ru _agent_setup.json



Launch:
python run.py --verbose True --config examples/example_ru_agent_setup.json

**Comment by sorokin-as** [comment]
@ishaan-jaff 
This is very strange but the problem has disappeared. I cloned the project again and everything worked.

**Comment by ghost** [comment]
closing the issue for now @TasksAndreySorokin please re-open if it resurfaces
