### ISSUE TITLE
[Feature]: Provide more info about each model in /models

### ISSUE THREAD

**Issue by jeromeroussin** [BerriAI/litellm#933]
### The Feature

Users of the proxy need to know a few things about each model:
1. Is it a completion, chat or embedding model? Some models only reply to some specific calls and not others.
2. The context size
3. Throttling data (calls per minute, tokens per minute)
4. Other data pertinent to where the proxy runs

Rather than keeping track of all the models you support I suggest you let the proxy owner augment the data returned by /models with key/value pairs specified in config.yaml, in a "custom_params" section perhaps.

### Motivation, pitch

This would allow /models to become the basis for a model catalog frontend

**Comment by ghost** [comment]
Hey @jeromeroussin `/models` is an openai endpoint used by applications - https://platform.openai.com/docs/api-reference/models

If we make changes to the response object, it would break for applications that need it (e.g. aider). 

We could expose a `/model/info` endpoint, could you explain this a bit more: 
>  let the proxy owner augment the data returned by /models

**Comment by jeromeroussin** [comment]
Sure I'll explain a bit more.

The proxy is configured with specific models at specific locations. The list of models supported may grow or shrink over time based on business needs and available offerings. 

Users of the proxy need a way to discover what models are currently supported and how to interact with them. The /models route gets some of the way there but is missing critical information like context size, model type, function support, costs, throttling information, maybe even a description of what the models are good at. That information can be maintained outside the proxy I suppose, but I am suggesting it be exposed via a proxy route instead, using data provided via the config.yaml file. 

That route could then be used to dynamically generate a model catalog UI for the purpose of proxy documentation. (I am not suggesting you build a catalog UI in this RFE, only the data route)

**Comment by jeromeroussin** [comment]
Oh I forgot to mention the /models route used to return custom data from config.yaml but that stopped working in a recent version.

If using /models itself would break other stuff, I'd be fine with a different route.

**Comment by ghost** [comment]
that was a bug @jeromeroussin 😄 https://github.com/BerriAI/litellm/issues/865

so it sounds like you want an endpoint to return the proxy config - sounds good. Should it return the api key as well?

**Comment by jeromeroussin** [comment]
The api key and the api base should not be returned. Proxy users do not need to know where the models really are, they are supposed to talk to the proxy instead.

**Comment by ghost** [comment]
pushed beta endpoint - https://github.com/BerriAI/litellm/commit/7ee089b5ca1aa8d382cf74726395541ac972e1fd and https://github.com/BerriAI/litellm/commit/b4b7acdb72599accb7f4ba0fd25d433961737f6d (skips api base)

**Comment by ghost** [comment]
will update ticket once it's in prod.

**Comment by jeromeroussin** [comment]
Thanks. Do you think you could merge the data from model_prices_and_context_window_backup.json into the output of /model/info? I see it contains some of the stuff I was mentioning?

**Comment by jeromeroussin** [comment]
I see that /model/info returns extra fields from config.yaml, but the other routes don't like the new params. I added an "extra" field under "litellm_params" of each model and I am getting this error:

        AsyncCompletions.create() got an unexpected keyword argument \'extra\'

**Comment by ghost** [comment]
we use litellm params as params for litellm.completion() 

i believe extra params should work by putting them inside a metadata field 

```yaml
- model_name: gpt-3.5-turbo
    litellm_params:
      model: azure/gpt-turbo-small-eu
      api_base: https://my-endpoint-europe-berri-992.openai.azure.com/
      metadata: {... extra metadata}
```

**Comment by ghost** [comment]
open to feedback on what a better experience here might look like

**Comment by jeromeroussin** [comment]
Using metadata here does not seem right? Reading the code, metadata gets logged in a few places including langfuse.

I think my ask comes down to this:

1. Expose data litellm knows about each model, including what is in model_prices_and_context_window_backup.json. Merge that data at the model level with what is the config yaml. This will document context size, cost and mode for each model.

2. Allow proxy owners to inject more info in the config yaml (in a way that does not have side effects). I suggest an "extra_params" at the same level as "litellm_params".

**Comment by ghost** [comment]
acknowledging this feedback @jeromeroussin, will try and have an initial implementation of this out for feedback soon.

**Comment by ghost** [comment]
@jeromeroussin exposing support for a 'model_info' section to the model_list - https://github.com/BerriAI/litellm/commit/60af976aacebbbab4307cebf925441d340b85e68

was this what you were hoping for? 
<img width="656" alt="Screenshot 2023-12-01 at 8 55 41 PM" src="https://github.com/BerriAI/litellm/assets/17561003/f4d3645f-dee5-49c9-8d02-f31923851f43">

**Comment by jeromeroussin** [comment]
"model_info" is descriptive enough.

1. Can you populate that section with data from the model cost map? 
2. Can you make sure model_info is supported in /model/new (and any other location that makes sense)?

**Comment by ghost** [comment]
@jeromeroussin '/model/new' already supports model_info. 

Yes- will add support for the model cost + max tokens.

**Comment by jeromeroussin** [comment]
Hey, am I reading the code for /model/new wrong?

This is skipping model_info no?

        # Add the new model to the config
        config['model_list'].append({
            'model_name': model_params.model_name,
            'litellm_params': model_params.litellm_params
        })

**Comment by ghost** [comment]
@jeromeroussin  you're right. I just committed the fix and added it to our ci/cd to prevent future regressions - https://github.com/BerriAI/litellm/commit/5a4c054eef8beef468cf77481bc8f2deb32c653d.

**Comment by ghost** [comment]
@jeromeroussin is this issue resolved? 

if not what is remaining here?
