### ISSUE TITLE
[Feature]: Save call logs to user db (proxy) for debugging

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#934]
### The Feature

Save the call logs (including the error stack traces) to a db. Ideally this would also have a db viewer, but just having the stack trace saved somewhere would be great for now. 

### Motivation, pitch

I'm running 500 async calls on the proxy and 22 of them failed. But i have no idea what happened. It would be helpful to understand what went wrong and step through it.

**Comment by ghost** [comment]
Honestly any sort of debug tool here would work - e.g. sentry/etc. 

I just need a way to see what went wrong

**Comment by ishaan-jaff** [comment]
i used the litellm sentry callback here - it was way better than looking into a db row or log

**Comment by ghost** [comment]
Needs to see cost / user, prompt, responses

**Comment by ishaan-jaff** [comment]
we log this to dynamo db now
