### ISSUE TITLE
[Bug]: Tool_call is not in the first chunk for Azure streaming

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#936]
### What happened?

A bug happened!

**Comment by krrishdholakia** [comment]
fixed - https://github.com/BerriAI/litellm/commit/4cdd930fa216851a5440d3539570517558e1184e

**Comment by ghost** [comment]
fixed - https://github.com/BerriAI/litellm/commit/e8331a46478db19e8b0cf3ffa077b8d56ba50a29
