### ISSUE TITLE
support MPT + Falcon well

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#94]
These are HF models - i've seen them on a couple different repos  - e.g.
<img width="384" alt="Screenshot 2023-08-11 at 6 58 47 AM" src="https://github.com/BerriAI/litellm/assets/17561003/5a0a8edc-fbee-43b6-bf8b-776db3c25032">

We should test + make sure we support these well:
- includes consistent outputs 
- error mapping

**Comment by ghost** [comment]
this is now added via prompt templates
