### ISSUE TITLE
move model_cost_map to being a hosted file

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#95]
Move the model cost map to being a file that's hosted / downloaded at runtime (<- maybe have some cache/refresh logic here). 

Reason: 
- model prices get updated, but older versions of lite wouldn't have accurate costs then

<img width="808" alt="Screenshot 2023-08-11 at 7 01 59 AM" src="https://github.com/BerriAI/litellm/assets/17561003/2170ec81-c8c3-4d2e-b1ef-0d08ba3ddbc8">

**Comment by ishaan-jaff** [comment]
hmmmm makese sense ! I like this feature. 

it's a neat way for anyone to get cost per token

`litellm.get_cost_per_token(mode_name)`

litellm always has the latest pricing for models 
😊
This is super cool

**Comment by ishaan-jaff** [comment]
@krrishdholakia can you add the api endpoint in docs or here ?

**Comment by ishaan-jaff** [comment]
this is done
