### ISSUE TITLE
[Feature]: support multi-turn prompt templating for replicate

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#952]
### The Feature

litellm assumes that [replicate.com](http://replicate.com/) correctly applies a prompt-template. however [replicate.com](http://replicate.com/) only correctly applies it for single turn conversations. in order to support multiple turns correctly, the llama2 prompting template has to be applied.

### Motivation, pitch

user had to make a fix on their end because of this.

**Comment by wendlerc** [comment]
For the llama-2-chat series there are several issues in the current implementation.

The current implementation only correctly works when the user does not specify a system prompt and sends a single message.
In any other case, e.g., when specifying a system prompt or when sending multiple messages it just concatenates the message contents without applying any prompting template (not even if specified by the user via a config.yaml (see https://github.com/BerriAI/litellm/blob/main/litellm/llms/replicate.py#L218).

It would be nice to properly apply the template and expose all fields of the [replicate api](https://replicate.com/meta/llama-2-70b-chat/api?tab=nodejs)

According to this [guide](https://replicate.com/blog/how-to-prompt-llama) they expect multi-turn prompts to look like this 
```
output = replicate.run(
            "meta/llama-2-70b-chat:2c1608e18606fad2812020dc541930f2d0495ce32eee50074220b87300bc16e1",
            input={
                   "prompt": """
[INST] Hi! [/INST]
Hello! How are you?
[INST] I'm great, thanks for asking. Could you help me with a task? [/INST]
""",
                   "system_prompt": "You are a pirate"
                  }
         )
''.join(output)

```

and single turn prompts to look like this
```
output = replicate.run(
            "meta/llama-2-70b-chat:2c1608e18606fad2812020dc541930f2d0495ce32eee50074220b87300bc16e1",
            input={
                   "prompt": "Can you explain what a transformer is (in a machine learning context)?",
                   "system_prompt": "You are a pirate"
                  }
         )
''.join(output)
```

I just did a quick test and it seems that prompts structured in this way get processed correctly:

![image](https://github.com/BerriAI/litellm/assets/8095362/e1a6378f-8c72-474a-b1ef-d7a6834b5066)


Also would be nice to expose all the parameters to control the generation if this is not done already.

**Comment by ghost** [comment]
@wendlerc you can control provider specific params here - https://docs.litellm.ai/docs/completion/input#provider-specific-params

replicate is also inconsistent about params for each model

**Comment by ghost** [comment]
pushed a fix @wendlerc - https://github.com/BerriAI/litellm/commit/1f5a1122fcccd3fc7127861ee16d6cfafa114b3a

**Comment by ghost** [comment]
let me know if this resolves your issue.

**Comment by wendlerc** [comment]
The multiturn now works when no system message is provided by the user.

However, if the system message is provided, it gets passed into the prompt instead of the system_prompt field from replicate.
