### ISSUE TITLE
[Bug]: Cannot read properties of null (reading 'trim')' (librechat error) 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#953]
### What happened?

Im trying to set up a reverse proxy for libreChat using litellm.
but i'm stuck with this error: 'Cannot read properties of null (reading 'trim')'

The response is rendered on the frontend screen, but once it finishes, the message disappears and the 'trim' error shows up.

![image](https://github.com/BerriAI/litellm/assets/17561003/e8bd041c-d22e-4ada-85c6-d581a7cbf1e2)

### Relevant log output

```shell
I want the frontend query to pass through my python script before returning the rendered message to the user, and for that, I need the proxy.
I did a very basic test by running this:
litellm -m gpt-4

Then I went through the .env of librechat and edited:

Reverse proxy settings for OpenAI:
#https://github.com/waylaidwanderer/node-#chatgpt-api#using-a-reverse-proxy
#The URL must match the "url/v1," pattern, the #"openai" suffix is also allowed.
#Examples:
#- https://open.ai/v1
#https://open.ai/v1/ACCOUNT/GATEWAY/openai
#- https://open.ai/v1/hi/openai

OPENAI_REVERSE_PROXY=http://0.0.0.0:8000/
and then ...

"The response is rendered on the frontend screen, but once it finishes, the message disappears and the 'trim' error shows up."
```

**Comment by ghost** [comment]
closing as this works when setting the api to docker.internal instead of 0.0.0.0... 
<img width="1028" alt="Screenshot 2023-11-29 at 9 02 43 PM" src="https://github.com/BerriAI/litellm/assets/17561003/9359853c-9d79-434f-9ccb-5eeb342428cd">
