### ISSUE TITLE
[Bug]: fake streaming - ai21 bedrock 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#954]
### What happened?

bedrock ai21 doesn't support streaming - same as ai21 normal. fake the stream for this like we do for ai21, so user code still works.

**Comment by ghost** [comment]
fix pushed - https://github.com/BerriAI/litellm/commit/ab76daa90bc2b2ee1ef39f41df1e4d693cb0accd

**Comment by ghost** [comment]
in prod in v`1.7.19`.
