### ISSUE TITLE
[Feature]: add new bedrock pricing 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#955]
### The Feature

Bedrock introduced new pricing for different regions + models - 
https://aws.amazon.com/bedrock/pricing/

### Motivation, pitch

spend tracking

**Comment by ghost** [comment]
There's a lot of different pricing here. Tracking it here: 

## Anthropic 

Cost per call
- [x] us-east-1 
- [x] us-west-2 
- [x] ap-northeast-1 
- [x] eu-central-1 

Provisioned throughput (time-based pricing) 
- [x] us-east-1 (1mo., 6mo.)
- [x] us-west-2 (1mo., 6mo.)
- [x] ap-northeast-1 (1mo., 6mo.)
- [x] eu-central-1 (1mo., 6mo.)

## Cohere 
- [x] cost per call (fixed across regions) 
- [x] time-based pricing (fixed across regions) (1mo., 6mo.)

**Comment by ghost** [comment]
Anthropic pricing added - https://github.com/BerriAI/litellm/commit/d70645b5e7edbb1b943836fb4a5110249f21a288

**Comment by ghost** [comment]
Cohere pricing added - https://github.com/BerriAI/litellm/commit/f47bc7dfa04a704cacce181ff0ce89a672d59358
