### ISSUE TITLE
[Bug]: Ollama backend results in Pydantic error: Expected `Usage` but got `dict` - serialized value may not be as expected

### ISSUE THREAD

**Issue by ClaartjeBarkhofTNO** [BerriAI/litellm#959]
### What happened?

I am trying to run LiteLLM with Ollama models, but running it results in Pydantic errors:

The error
```
UserWarning: Pydantic serializer warnings:
  Expected `Usage` but got `dict` - serialized value may not be as expected
  return self.__pydantic_serializer__.to_python(
```

My code
```
from litellm import completion
response = completion(
    model="ollama/mistral:latest", 
    messages = [{ "content": "Hello, how are you?","role": "user"}], 
    api_base="http://localhost:13200"
)
```

Versions
```
litellm==1.7.21
pydantic==2.5.2
pydantic_core==2.14.5
```

### Relevant log output

```shell
UserWarning: Pydantic serializer warnings:
  Expected `Usage` but got `dict` - serialized value may not be as expected
  return self.__pydantic_serializer__.to_python(
```
```


### Twitter / LinkedIn details

_No response_

**Comment by r7l** [comment]
I can confirm this issue. Seeing the exact same error message.

**Comment by snoe925** [comment]
I also ran into this issue.  It appears the code may assume Ollama is streamed.
Using the streamed example runs with no errors.

https://github.com/BerriAI/litellm/blob/8c1439e910aa649598d8e2de78758fa0f0fa092c/docs/my-website/docs/providers/ollama.md?plain=1#L41

**Comment by ghost** [comment]
acknowledging this issue @snoe925 @r7l @ClaartjeBarkhofTNO, will aim to have a fix out by tomorrow.

**Comment by ghost** [comment]
is this causing calls to fail @snoe925 @r7l @ClaartjeBarkhofTNO

**Comment by ClaartjeBarkhofTNO** [comment]
@krrishdholakia I am not sure what you're asking. The issue persists in `litellm-1.10.2`. Thanks for having a look at it!

**Comment by estivate** [comment]
I also get the Pedantic serializer warnings, but for me the calls do NOT fail:

```
@:/app# python3 test-mistral.py 
I am Mistral, a language model trained by the Mistral AI team. How can I help you today?
/usr/local/lib/python3.11/site-packages/pydantic/main.py:308: UserWarning: Pydantic serializer warnings:
  Expected `Usage` but got `dict` - serialized value may not be as expected
  return self.__pydantic_serializer__.to_python(
@:/app# 
```

litellm==1.10.2
pydantic==2.5.2
pedantic_core==2.14.5

Code used to create the above output:
```
from litellm import completion

response = completion(
    model="ollama/mistral", 
    messages=[{ "content": "respond in 20 words. who are you?","role": "user"}], 
    api_base="http://ollama:11434"
)
print(response.choices[0].message.content)
```

When I run the same test but use `gpt-3.5-turbo` I do not get the Pydantic warnings

**Comment by ClaartjeBarkhofTNO** [comment]
You are right, it is not failing, just warning.

**Comment by ghost** [comment]
closing as this was fixed a while back. @ClaartjeBarkhofTNO let me know if the error resurfaces in v`1.12.1`
