### ISSUE TITLE
[Bug]: system fingerprint is none for azure/openai

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#962]
### What happened?

system fingerprint in response object is none for azure/openai calls. if it's passed in - set it

**Comment by ghost** [comment]
fix pushed - https://github.com/BerriAI/litellm/commit/01c7e18f317950885b7fb7034bc5509009c05b1c

**Comment by ghost** [comment]
reopening this issue as the problem still persists. 

if the streaming chunk has content, then the system fingerprint isn't always part of the first chunk?

**Comment by ghost** [comment]
able to repro this issue when sending a normal message to a tool call completion call.

**Comment by ghost** [comment]
fix pushed + testing added - https://github.com/BerriAI/litellm/commit/728b879c33f85a6844c4c07ed4d6ccea5b2bb2fc
