### ISSUE TITLE
Read Model, Temperature, Top_P, Stream params from config file

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#97]
See https://github.com/devchat-ai/devchat/pull/77#issuecomment-1668901516 

We should allow users to pass in params for completion() through a config file and use the configs 

cc @basicthinker

**Comment by ishaan-jaff** [comment]
Addressed in this commit: https://github.com/BerriAI/litellm/commit/27cc3760b738cade2cdb9ba083e276d7a45dcc01

**Comment by ghost** [comment]
@ishaan-jaff are you adding this to docs? if you can't do it now - just make an issue so we remember to do it

**Comment by ishaan-jaff** [comment]
re-opened, waiting to hear feedback on if this works in https://github.com/devchat-ai/devchat/pull/77#issuecomment-1668901516
