### ISSUE TITLE
[Feature]:  tag the version of the litellm docker image on github container registry

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#972]
### The Feature

"On more ask, could you tag the version of the image you publish on github container registry?

At the moment it's only tagged as latest which makes it difficult for us to know which users are on what version.

Again, many thanks."

### Motivation, pitch

user request

### Twitter / LinkedIn details

@ianpurton

**Comment by ishaan-jaff** [comment]
I've restarted the ghcr workflow for the proxy https://github.com/BerriAI/litellm/pkgs/container/litellm

**Comment by ishaan-jaff** [comment]
tags now include the version for the proxy too:
```
docker pull ghcr.io/berriai/litellm:main-v1.10.0
```

**Comment by ishaan-jaff** [comment]
https://github.com/berriai/litellm/pkgs/container/litellm

**Comment by ishaan-jaff** [comment]
done, docs https://docs.litellm.ai/docs/proxy/quick_start#quick-start-docker-image 

feel free to re-open this issue @ianpurton
