### ISSUE TITLE
[Bug]: From 1.9.5 onwards Pydantic dependency errors.

### ISSUE THREAD

**Issue by Luxadevi** [BerriAI/litellm#976]
### What happened?

From this 1.9.5 update onwards I get loads of errors when launching the pydantic protected namespaces.

```
/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_fields.py:149: UserWarning: Field "model_name" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
  
```

I am building a Gradio app as LLM companion and understandably there going to be conflict.

The idea of having dynamic config files is very good i already had that build in with my companion since it is so easy to query some endpoints. Alot of my variables are something named with model_ thats the nature of building for llms.

Would it be possiblle to have the querying and updating of the config file in its own enviroment this way it will never conflict with LLM inference libraries or applications like autogen or chatdev alot of apps use model_ as variable.

Summary op pip libraries.

```

- aiofiles                23.2.1
- aiohttp                 3.9.1
- aiosignal               1.3.1
- altair                  5.2.0
- annotated-types         0.6.0
- anyio                   3.7.1
- appdirs                 1.4.4
- APScheduler             3.10.4
- async-timeout           4.0.3
- asyncio                 3.4.3
- attrs                   21.2.0
- Automat                 20.2.0
- Babel                   2.8.0
- backoff                 2.2.1
- bcrypt                  3.2.0
- blinker                 1.7.0
- certifi                 2023.11.17
- chardet                 4.0.0
- charset-normalizer      3.3.2
- click                   8.1.7
- cloud-init              23.3.3
- colorama                0.4.4
- command-not-found       0.3
- configobj               5.0.6
- constantly              15.1.0
- contourpy               1.2.0
- cryptography            3.4.8
- cycler                  0.12.1
- dbus-python             1.2.18
- distro                  1.7.0
- distro-info             1.1+ubuntu0.1
- exceptiongroup          1.2.0
- fastapi                 0.104.1
- ffmpy                   0.3.1
- filelock                3.13.1
- Flask                   3.0.0
- flask-cloudflared       0.0.14
- fonttools               4.46.0
- frozenlist              1.4.0
- fsspec                  2023.10.0
- gradio                  4.7.1
- gradio_client           0.7.0
- h11                     0.14.0
- httpcore                1.0.2
- httplib2                0.20.2
- httpx                   0.25.2
- huggingface-hub         0.19.4
- hyperlink               21.0.0
- idna                    3.3
- importlib-metadata      6.9.0
- importlib-resources     6.1.1
- incremental             21.3.0
- itsdangerous            2.1.2
- jeepney                 0.7.1
- Jinja2                  3.1.2
- jsonpatch               1.32
- jsonpointer             2.0
- jsonschema              3.2.0
- keyring                 23.5.0
- kiwisolver              1.4.5
- launchpadlib            1.10.16
- lazr.restfulclient      0.14.4
- lazr.uri                1.0.6
- litellm                 1.9.4
- markdown-it-py          3.0.0
- MarkupSafe              2.1.3
- matplotlib              3.8.2
- mdurl                   0.1.2
- more-itertools          8.10.0
- multidict               6.0.4
- netifaces               0.11.0
- numpy                   1.26.2
- oauthlib                3.2.0
- openai                  1.3.7
- orjson                  3.9.10
- packaging               23.2
- pandas                  2.1.3
- pexpect                 4.8.0
- Pillow                  10.1.0
- pip                     22.0.2
- ptyprocess              0.7.0
- pyaml                   23.9.7
- pyasn1                  0.4.8
- pyasn1-modules          0.2.1
- pydantic                2.5.2
- pydantic_core           2.14.5
- pydub                   0.25.1
- Pygments                2.17.2
- PyGObject               3.42.1
- PyHamcrest              2.0.2
- PyJWT                   2.3.0
- pyOpenSSL               21.0.0
- pyparsing               2.4.7
- pyrsistent              0.18.1
- pyserial                3.5
- python-apt              2.4.0+ubuntu2
- python-dateutil         2.8.2
- python-debian           0.1.43+ubuntu1.1
- python-dotenv           1.0.0
- python-magic            0.4.24
- python-multipart        0.0.6
- pytz                    2022.1
- PyYAML                  6.0.1
- redis                   5.0.1
- regex                   2023.10.3
- requests                2.31.0
- rich                    13.7.0
- rq                      1.15.1
- screen-resolution-extra 0.0.0
- SecretStorage           3.3.1
- semantic-version        2.10.0
- service-identity        18.1.0
- setuptools              59.6.0
- shellingham             1.5.4
- six                     1.16.0
- sniffio                 1.3.0
- sos                     4.5.6
- ssh-import-id           5.11
- starlette               0.27.0
- systemd-python          234
- tiktoken                0.5.1
- tokenizers              0.15.0
- tomlkit                 0.12.0
- toolz                   0.12.0
- tqdm                    4.66.1
- Twisted                 22.1.0
- typer                   0.9.0
- typing_extensions       4.8.0
- tzdata                  2023.3
- tzlocal                 5.2
- ubuntu-advantage-tools  8001
- ufw                     0.36.1
- unattended-upgrades     0.1
- urllib3                 1.26.5
- uvicorn                 0.24.0.post1
- wadllib                 1.3.6
- websockets              11.0.3
- Werkzeug                3.0.1
- wheel                   0.37.1
- xkit                    0.0.0
- yarl                    1.9.3
- zipp                    1.0.0
- zope.interface          5.4.0

```

**Comment by ghost** [comment]
Hey @Luxadevi can you share any code for repro? 

and is this a warning (non-blocking) or an error (blocking) 

the message shared, looks like a warning

**Comment by ghost** [comment]
Re: " querying and updating of the config file in its own enviroment"

we just added that yesterday - v`1.10.0` 

New model management endpoints
<img width="1549" alt="Screenshot 2023-12-02 at 10 51 05 AM" src="https://github.com/BerriAI/litellm/assets/17561003/8185a762-1fde-4e4b-bfe1-f94195e0dddd">

**Comment by r7l** [comment]
I am having the same message. It's a non blocking warning. But there are multiple warnings and even a blocking error not related to pydantic. I'll open up another issue for those.

My config:

```
model_list:
  - model_name: ollama/mistral
    litellm_params:
      model: ollama/mistral
      api_base: "https://my-custom-domain.com"

litellm_settings:
  drop_params: True
  set_verbose: True
```

**Comment by ghost** [comment]
this is great. thanks @r7l

**Comment by Luxadevi** [comment]
This is my latest version i have running right now. As you can see since i work with LLMS that it would be pretty hard to work around the word model_

https://github.com/Luxadevi/Ollama-Companion/tree/dev

**Comment by Luxadevi** [comment]
> I am having the same message. It's a non blocking warning. But there are multiple warnings and even a blocking error not related to pydantic. I'll open up another issue for those.
> 
> My config:
> 
> ```
> model_list:
>   - model_name: ollama/mistral
>     litellm_params:
>       model: ollama/mistral
>       api_base: "https://my-custom-domain.com"
> 
> litellm_settings:
>   drop_params: True
>   set_verbose: True
> ```

Mine we're mostly about the protected namespaces. So i think would be best or to handle that in their own env, or just have it onder a whole different variable and use some logic to assemble the right words on the spot.
Really feel like blocking of words like model_ is less then ideal on a product for LLMS.

**Comment by ghost** [comment]
i don't believe we're doing the blocking here 😄 @Luxadevi

**Comment by Luxadevi** [comment]
> i don't believe we're doing the blocking here 😄 @Luxadevi

I think you do from this update https://github.com/BerriAI/litellm/commit/60af976aacebbbab4307cebf925441d340b85e68

**Comment by ishaan-jaff** [comment]
+1 I see this error now too

**Comment by ishaan-jaff** [comment]
User on discord complained about this too 

<img width="399" alt="Screenshot 2023-12-02 at 9 24 26 PM" src="https://github.com/BerriAI/litellm/assets/29436595/bdaee48d-f3ac-4f21-8458-135f4127e62d">

**Comment by ishaan-jaff** [comment]
okay I fixed this https://github.com/BerriAI/litellm/commit/ecddb852a256bef86dee7cb77511ad65587f833d

**Comment by ishaan-jaff** [comment]
## Before change 
<img width="1273" alt="Screenshot 2023-12-02 at 9 29 44 PM" src="https://github.com/BerriAI/litellm/assets/29436595/bf6be04d-fd87-47dc-bc40-677da65359d4">

## After Change 

<img width="1240" alt="Screenshot 2023-12-02 at 9 29 58 PM" src="https://github.com/BerriAI/litellm/assets/29436595/97c9e753-9d92-44a1-94b7-95686662cef7">

**Comment by ishaan-jaff** [comment]
@Luxadevi @r7l please let me know if this fixes it for you too

**Comment by Luxadevi** [comment]
> @Luxadevi @r7l please let me know if this fixes it for you too 

I'll let you know when I deploy a new cloud endpoint.

**Comment by ghost** [comment]
Closing for now @Luxadevi please re-open if the issue remains.
