### ISSUE TITLE
[Feature]: (Safely) Passing user IDs to OpenAI to identify abusive virtual keys users

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#978]
### The Feature

When using OpenAI/Azure, it's a best practice to pass a user ID. If OpenAI/Azure OpenAI finds some of your requests to violate their terms of service, this gives you an opportunity to identify (and remove) the user who is responsible (instead of having your entire account terminated by OpenAI).

```python
response = openai.Completion.create(engine = "davinci", prompt = "This is a test", max_tokens = 5, user = "1")
```

https://platform.openai.com/docs/guides/safety-best-practices/end-user-ids

https://help.openai.com/en/articles/5428082-how-to-incorporate-a-userid

I think this makes sense to add as a feature for identifying abusive requests by virtual keys users. https://docs.litellm.ai/docs/simple_proxy#managing-auth---virtual-keys

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by Manouchehri** [comment]
I think using a hash of the UUID (that was talked about on Discord) as the user ID for OpenAI calls makes sense. Though a lookup before each request would kinda suck for performance.. 

This should be a feature that's a toggleable config, as it does have privacy implications.

**Comment by Manouchehri** [comment]
This is a low-priority feature (for my team anyway), and isn't causing us issues yet (i.e. not a blocker). (We are currently only providing API access/services to other companies we personally trust.)

**Comment by ghost** [comment]
@Manouchehri can't you already do that client-side by passing in the user-id as part of the completion call 

https://platform.openai.com/docs/api-reference/chat/create#chat-create-user

**Comment by Manouchehri** [comment]
We'd want to override (or better, concat) what the end-user provided, otherwise if a virtual key user provided a completely random user ID in all their calls, we would have no clue who was responsible for getting our OpenAI account banned. =P

**Comment by ghost** [comment]
user id (either generated or passed in) is now stored in db - https://github.com/BerriAI/litellm/commit/6b1b1b82cfb0939faa819edd991f9bdc14e07ebe

**Comment by ghost** [comment]
sending user param to litellm.completion - https://github.com/BerriAI/litellm/commit/f0d8a87c4873784d7959f1a77328450d087a8b33

**Comment by ghost** [comment]
@Manouchehri did this resolve your issue?

**Comment by ishaan-jaff** [comment]
bump on this @Manouchehri

**Comment by Manouchehri** [comment]
Ah, I actually meant passing `user` on the upstream request as well (e.g. to Azure OpenAI, OpenAI, Anthropic, etc).

Assigning this ticket to myself. :) Low priority, but I'll probably do it eventually.

**Comment by Manouchehri** [comment]
I was wrong; I'm not sure I see where in the code LiteLLM is passing the user field to OpenAI, but it definitely is for OpenAI and Azure OpenAI.

My bad for reopening!
