### ISSUE TITLE
[Feature]: DOCS - add `/model/new` endpoint to docs

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#982]
### The Feature

Multiple users - @chanwit @Luxadevi @ ericblue have asked for this. 

### Motivation, pitch

We should have this on our docs - even if it's in beta - to collect feedback and improve it.

**Comment by ghost** [comment]
pushed - https://github.com/BerriAI/litellm/commit/31d9762b506ec5ce2783b38e02a9621846242ab2
