### ISSUE TITLE
[Feature]: Support for Perplexity's PPLX models: `pplx-7b-online` and `pplx-70b-online`

### ISSUE THREAD

**Issue by jamino30** [BerriAI/litellm#986]
### The Feature

Support for Perplexity's new [PPLX models](https://blog.perplexity.ai/blog/introducing-pplx-online-llms).

### Motivation, pitch

Boosting online LLM support, particularly for Perplexity-based models, would be highly impactful and useful.

### Twitter / LinkedIn details

https://www.linkedin.com/in/jaiamin30/

**Comment by ishaan-jaff** [comment]
@jamino30 we support this https://docs.litellm.ai/docs/providers/perplexity#supported-models

**Comment by ishaan-jaff** [comment]
did you run into issues using it ?

**Comment by jaiamin** [comment]
@ishaan-jaff Yes, for some reason I didn't not notice that. This issue can be ignored.
