### ISSUE TITLE
[Bug]: error in creating async loop - <asyncio.locks.Event object at 0x11f83ee10 [unset]> is bound to a different event loop

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#989]
### What happened?

Unable to make async db calls in sync custom logging function 

### Relevant log output

```shell
this is being triggered inside the cost update function: 
error in creating async loop - <asyncio.locks.Event object at 0x11f83ee10 [unset]> is bound to a different event loop
```

**Comment by ghost** [comment]
working on this today.

**Comment by ghost** [comment]
resolved with the introduction of async custom callbacks - https://github.com/BerriAI/litellm/commit/e0ccb281d8941ee0992bc26c4a5ad48616125eaf
