### ISSUE TITLE
[Bug]: GHCR container raises warning on MAC -  The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#990]
### What happened?

our proxy should work on mac but it raises this error

we need to make a fix here 
https://github.com/BerriAI/litellm/blob/main/.github/workflows/ghcr_deploy.yml 

### Relevant log output

```shell
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```
```


### Twitter / LinkedIn details

_No response_

**Comment by willgodfrey** [comment]
same issue here when trying to deploy to a mac via docker - same error

**Comment by ishaan-jaff** [comment]
I could use help with tackling this issue - contributions are welcome for this
