### ISSUE TITLE
[Feature]: Enable custom configuration on Redis cache

### ISSUE THREAD

**Issue by eliorc** [BerriAI/litellm#994]
### The Feature

Enable passing extra arguments to cache initialization to support real-world use-cases.

### Motivation, pitch

Currently, the `litellm.caching.RedisCache` is strictly using only `host`, `port` and `password` for the connection configuration.
The problem would be for example using a redis intance that is protected by SSL. This means that in order to interact with the redis instance you would have to pass `ssl=True` and maybe even path to the certificates to the `redis.Redis` client.
As it is now, since its not possible to pass extra arguments to the cache initialization, it is impossible to use an SSL enabled redis as a LiteLLM cache.

I believe this should be quite simple, by making `litellm.caching.Cache` constructor accept `**kwargs` which will be forwarded to the downstream cache used. I'll try to find the time to contribute this myself.

**Comment by shuther** [comment]
Maybe the cache configuration should be isolated in case we want to leverage a different approach (chromaDB, ...); and the format could be a json similar to what is used in other projects (see: [Djanjo-redis](https://docs.djangoproject.com/en/4.2/topics/cache/)) so we faciliate the integraton work. At the same time, we could make use of the KEY_PREFIX options.
More long tgerm, It is an opportunity to extend and support [ACL](https://redis.io/docs/management/security/acl/) with redis (requirepass is deprecated) so we could secure what we store based on the litellm key (maybe more long term). Better security is something to look at.

**Comment by ghost** [comment]
Acknowledging this issue. @eliorc i like your idea of allowing **kwargs to be passed in. 

Curious how're you using litellm today?

**Comment by ishaan-jaff** [comment]
added custom params https://github.com/BerriAI/litellm/commit/9ba17657ad664a21b5e91259a152db58540be024 for caching

**Comment by ishaan-jaff** [comment]
@eliorc is this what you were looking for ? feel free to re-open this issue

**Comment by ishaan-jaff** [comment]
@eliorc would love to set a support channel for you and ensure we solved this issue:
Please let me know what channel works best 

- Linkedin: https://www.linkedin.com/in/reffajnaahsi/ 
- Twitter: https://twitter.com/ishaan_jaff 
- Discord: https://discord.com/invite/wuPM9dRgDw

**Comment by eliorc** [comment]
@ishaan-jaff yep, exactly what I wanted. At the moment I have set up a monkey patch for the init to support the custom kwargs, I'll try this week to upgrade the library and see if this works for me

@krrishdholakia as a part of a larger project, we wanted to abstract the interface for interacting with LLMs. The project does not directly use `litellm` but rather a service built using `litellm`. This service implements functionality we need
Few examples of functionalities we developed in our service that `litellm` does not support (maybe you'd like to add it in the future)
1. When using multiple models in the backend, a routing strategy that accepts a list of models, ordered by relevancy and tries to invoke a completion call by order moving to the next one only if a model times out/out of capacity. Maybe litellm will support in teh future custom routing strategies for `Router`?
2. Context management for caching, so a user of the cache could do something like `with cache.disable_cache()...` or `with cache.cache_context(ttl=1000)` to change the behavior of the cache. 

These are just some examples, hope that answers your question

**Comment by ghost** [comment]
@eliorc Thanks for the response here + LinkedIn. I'll set up a support channel there with @ishaan-jaff. 

Had 2 questions here:

- is your service an API similar to the openai proxy server? 

- isn't #1.  Similar to how fallbacks work on the router? Curious what's missing there - https://docs.litellm.ai/docs/routing#fallbacks

**Comment by aseifert** [comment]
Thanks for adding the custom redis params, that's great! It would be really great if the Router supported these as well. Maybe we could pass a RedisCache object when initializing the router? Or a redis connection, which would allow using `redis.from_url` to parse a redis url, so I don't have to create so many ENV vars :-)

**Comment by ghost** [comment]
Hey @aseifert @eliorc @PSU3D0 

Made an initial commit - https://github.com/BerriAI/litellm/commit/88c95ca259f8677b1eb1e2a356e81bf50e87add1 based on some of the changes made in @PSU3D0's PR - https://github.com/BerriAI/litellm/pull/967

Will update this issue once it's in prod. Any feedback would be great.

**Comment by ghost** [comment]
this is live now in v`1.10.8`

**Comment by eliorc** [comment]
> @eliorc Thanks for the response here + LinkedIn. I'll set up a support channel there with @ishaan-jaff.
> 
> Had 2 questions here:
> 
> * is your service an API similar to the openai proxy server?
> * isn't [Give me consistent exceptions  #1](https://github.com/BerriAI/litellm/issues/1).  Similar to how fallbacks work on the router? Curious what's missing there - https://docs.litellm.ai/docs/routing#fallbacks

Yes, inside our project we implement something liek a proxy server which uses `litellm`

Regarding your question of what is missing there, in your example the routing is deterred from one model to another based on exceptions, we needed a more flexible strategy, I'll give an example.
Let's say you use function calling, but the response is not json serializable. Then there is no exception thrown here, that's the first difference. Secondly, in the "mitigation" part you just go to the next model, we wanted to have the ability to continue the chat if it failed like appending to the `messages` asking the model to fix this to be json serializable.

So in essence, this examples shows 2 differences (1) first one is that routing the call from one model or the other can be dependent on more than exceptions thrown by response, and second (2) is the ability to mitigate the error by doing something else than going to the next model in the list

**Comment by aseifert** [comment]
@krrishdholakia you guys are quick, thanks a lot! 🙏 will try this out today.

**Comment by ghost** [comment]
Hey @eliorc I want to make sure we capture your feedback. Created 2 issues to track this: 

- https://github.com/BerriAI/litellm/issues/1027
- https://github.com/BerriAI/litellm/issues/1028

Do you want to use the router with custom routing strategies? Can you share what that might look like in code?
