### ISSUE TITLE
[Bug]: Wrapping TGI

### ISSUE THREAD

**Issue by kulbinderdio** [BerriAI/litellm#998]
### What happened?

Hi, I've just upgraded both the litellm library and the docker container and get the following error when connecting to local instance of TGI. the library calls were working prior to update

I could be mistaken but this looks a bit like the issue we resolved together a week ago
call /models from web interface works fine

### Relevant log output

```shell
An error occurred: Expecting value: line 1 column 1 (char 0)

 Debug this by setting `--debug`, e.g. `litellm --model gpt-3.5-turbo --debug`
INFO:     127.0.0.1:59922 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
^N

Output from web interface when calling /completions
{
  "detail": "Expecting value: line 1 column 1 (char 0)\n\nTraceback (most recent call last):\n  File \"/home/dio/anaconda3/envs/litellm/lib/python3.11/site-packages/litellm/proxy/proxy_server.py\", line 836, in completion\n    data = json.loads(body_str)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/home/dio/anaconda3/envs/litellm/lib/python3.11/json/__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/dio/anaconda3/envs/litellm/lib/python3.11/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/dio/anaconda3/envs/litellm/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n"
}
```

**Comment by kulbinderdio** [comment]
I've just seen that the tagged container does a pip update, so if other libraries have changed the docker container will also change even though it's been tagged

**Comment by ghost** [comment]
hi @kulbinderdio - there's been no change to the fix implemented - https://github.com/BerriAI/litellm/blob/f2625bca243e1bff96cb8a613173010084ece914/litellm/llms/huggingface_restapi.py#L409

Your error message says this line is throwing an error: 
> data = json.loads(body_str)\n

this means the body sent in the POST request is not in the correct format. 

1. could you update your version (we added support for json bodies with single quotes `'`)
2. could you share the body being sent (testing the endpoint directly via postman would also work). 

Here's the testing we run as part of our ci/cd pipeline: 

https://github.com/BerriAI/litellm/blob/f2625bca243e1bff96cb8a613173010084ece914/litellm/tests/test_proxy_server.py#L25

I'm closing this issue for now, as it doesn't seem related to litellm or the tgi integration. Please feel free to re-open. 

Happy to set up a direct discord / linkedin support channel, based on preference. 

Discord: Krrish#8748
LinkedIn: https://www.linkedin.com/in/krish-d/
