### ISSUE TITLE
[Feature]: Support openai `/image/generations` endpoint 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#999]
### The Feature

https://platform.openai.com/docs/api-reference/images/create

### Motivation, pitch

user request

**Comment by ishaan-jaff** [comment]
it would be helpful to better understand why we should add support for this ? 

A lot of LiteLLM functionality assumes we are dealing with LLMs

**Comment by ghost** [comment]
cc: @geekyayush

**Comment by ghost** [comment]
this is now added - https://docs.litellm.ai/docs/image_generation
